### PR TITLE
luaengine: expose more methods + misc fixes 

### PR DESCRIPTION
**Pull request by lucab**
This is a cumulative PR to expose some more methods to LUA, and to fix some gotchas.

Fixes are in the first half: make better use of screen area infos, refactor some distate internals and later use them to rework state getter and setter. (After last review, I think I mostly grasp the pre_save/post_load needs and I think this may be enough for it, but I may still be off)

Last part is the new stuff: a memory writer (basically copied from the reader) and frame counter getter. @mmicko while at it, why is there a default 2sec autoboot_delay? I'm using 0sec for lua testing, and no quirks seen yet. Can I zero the default?

With these commits, TAS aficionados can re-use old hitboxes from mame-rr/fba-rr with minimal API compatibility changes:

mame-rr hitboxes for sf2

(not yet on-par with features, clearly)

### CODE REVIEW

**Comment by galibert** [comment]
Sorry, but "luaengine: rework state getter/setter for saves" is still
incorrect.  Not everything goes through interfaces, far from that.  The
rest is ok, we can merge it if you separate it.

  OG.

**Comment by lucab** [comment]
Oh, my bad, I was trying to avoid full machine updating on each state read/write (which seems a bit a performance hog).
Let me just factor out the presave/postload part of the save_manager and call that directly, then, as you originally proposed.

**Comment by galibert** [comment]
I understand, but no, it was not going to be reliable :-)  OTOH, you only
need to do it once as long as you don't restart the emulation.

  OG.

**Comment by lucab** [comment]
So maybe something along the line of this? https://gist.github.com/lucab/411b53c061935aaab29c

**Comment by galibert** [comment]
Yeah, that's pretty sure to work.

  OG.

**Comment by lucab** [comment]
Deal! Rebased and updated.

**Pull request merged**
