### PR TITLE
Emulation of HP85 tape drive

### PR DESCRIPTION
**Pull request by fulivi**
Hi,

this set of commits adds the emulation of HP85 tape drive.
This computer had a HP custom chip (whose part number was 1MA6-0001) as tape controller.
In order to add the 1MA6 emulation, I first separated the support for the HTI tape format into a proper module under "lib/formats".
Support for this format was previously embedded into TACO driver (tape controller of HP9845) and the related imgtool module.
It is now independent of any hw driver or support tool.

Thanks.
--F.Ulivi

### CODE REVIEW

**Comment by rb6502** [comment]
Nothing to do specifically with this commit, but where are you getting the HP custom chip documentation, and do you have any for later HP customs?  The 1A05 high-speed HPIB interface chip that's used instead of the TMS9914 for connecting disks and the 1RD2 HPIL chip are the major blockers for both the 9000/300 series workstations and the 16550 logic analyzer driver.

Thanks!

**Comment by kossow** [comment]
1TL1 (Medusa) ?
https://commons.wikimedia.org/wiki/File:HP_1TL1_die.jpg

http://www.hp9845.net/9845/tutorials/hpib/

**Comment by rb6502** [comment]
Nope, 1A05:
http://www.mirrorservice.org/sites/www.bitsavers.org/pdf/hp/9000_dio/photos/98625A_Disc_Intf/98625A_T.jpg

The '1' there is marginal in that photo, but AFAIK the 4-character HP chip names all started with a 1.

**Comment by fulivi** [comment]
Hi,

well, in this case I got plenty of "indirect" documentation on 1MA6 from commented sources of operating system & from the implementation of another HP85 emulator.
In general it seems that HP released very little documentation of its custom chips. For example, I developed the driver for the TACO chip entirely from reverse-engineering the system software.
Coming to the HPIB chip you mentioned, could it be that it's actually 1AD5 ? Because this chip is documented here:
12009A_HP-IBInterface_ReferenceManual_12009-90001_120pages_Sep82.pdf (available on bitsavers).
By the way this chip is very close to the PHI chip (I implemented a MAME driver for PHI here: src/devices/machine/phi.cpp).
For what concerns the HP-IL chip, I never heard of it.. sorry..
--F.Ulivi

**Comment by rb6502** [comment]
FreeBSD apparently supports the HP-IL chip, so I'll check there.  Thanks!

**Pull request merged**
