### PR TITLE
New WORKING clones 

### PR DESCRIPTION
**Pull request by clawgrip**
------------------------
Basket Ball (8-way Joystick bootleg of Arch Rivals) [jordigahan]

### CODE REVIEW

**Comment by rb6502** [comment]
This PR is changing every comment in the mcr68.cpp source file, which makes it very hard to review the actual changes.  Was that intentional?

**Comment by Osso13** [comment]
He's trying to follow the [MAME Coding Conventions](https://wiki.mamedev.org/index.php/MAME_Coding_Conventions) which state 
single-line comments should use // C++ line comment style

**Comment by rb6502** [comment]
I agree that the standard says you should do that for new code, but for existing files it should be part of a "cleanup" commit rather than mixed in with functional changes.  Mostly I'm curious if this was intentional or if they used an overly aggressive code editor.

**Comment by clawgrip** [comment]
Yes, it was intentional, it’s essier for me to read the sources that way, so I use to change them when I add some code, even if it is unrelated to code cleanup

**Pull request merged**
