### PR TITLE
Make Mega System 1 tilemaps into a device

### PR DESCRIPTION
**Pull request by ajrhacker**

### CODE REVIEW

**Comment by mamehaze** [comment]
this is an interesting one.

your submission seems to assume that the tilemaps are completely independent, however, I've wondered for a while now if maybe this isn't the case and if what you do with one potentially affects the others (if all tilemaps are handled by a single IC this could be the case, I didn't find good enough references to tell me)

the reason I say this is the soldam hack, needed for the high score table (and a few other elements IIRC) to render correctly.  I wonder if the way they set up the other tilemaps forces the tilemap we need a hack on into that mode even if that tilemap doesn't explicitly set it.

I never did any extensive research on the subject however.

something you might want to consider tho

**Comment by angelosa** [comment]
jalmah.cpp also uses the same chip apparently (one with scrolls and paging)
Maybe acommand.cpp/cischeat.cpp too?

**Comment by ajrhacker** [comment]
I know that some manufacturers used multi-tilemap chips in their later games, including Seibu Kaihatsu (the post-Raiden games with the "CRTC" control registers) and Dooyong (whose DY-PL-1 chip appears to provide exactly two ROM-based tilemaps; Vas Crabb's recent work doesn't account for this). However, NMK doesn't appear to have made this switch on their own games, and it doesn't appear to have happened with these tilemaps either.

When it comes to tilemap ASICs, it's very hard to tell which chips provide what functionality, in large part since official documentation is often totally nonexistent. In many cases (including this one) there's good evidence that each tilemap has its own ICs, but uses several different ones for each or several of the same kind (and might even be using some of them for sprites as well). I don't think it would make any practical sense to insist on mapping each of Seibu's earlier tilemap ICs onto a single MAME device.

Finding good references on the Internet for Jaleco PCBs of this era is almost impossible, since most of them are multiboard stacks. Stefan Lindberg's photo of Legend of Makai is by far the best, showing NEC-made "VCTR" and "SCTP" chips in proximity to each tilemap ROM. Peek-a-Boo, a late-generation single-board game, also has the 4 and 5 tilemap ROMs surrounded by multiple ICs (but not the same ones?). In conclusion, I really doubt that writes to one tilemap register are affecting other tilemaps here.

I've tried not to make gratuitous changes to the tilemap implementation (but oops, it seems that I may have messed up the scrolling somewhat). The soldam tweak is thus faithfully reproduced, though with a derived MCFG rather than with the evil use of strcmp on the machine name.

I do plan for this device to be hooked up in cischeat.cpp and jalmah.cpp, but disentangling the vregs   folderol in megasys1.cpp took so much effort that I decided to commit while I was still ahead.

**Comment by cuavas** [comment]
The Dooyong Z80 games use a sea of LSI logic (gates and counters) to implement the tilemaps.  I'd be very surprised if the DY-PL-1 isn't just an OTP CPLD programmed with similar logic.  It mimics the same control registers, ROM access pattern and 16-bit output each tile interval.  The outputs can still be routed completely arbitrarily, as shown by how "flexible" they are with which bits are tile index and which are CLUT index.

**Comment by cuavas** [comment]
Gah, SSI/MSI counters and gates, not LSI.

**Pull request merged**
