### PR TITLE
New working clones

### PR DESCRIPTION
**Pull request by clawgrip**
------------------
Prehistoric Isle in 1930 (World, set 2) [Victor Fernandez (City Game), ClawGrip]

### CODE REVIEW

**Comment by cuavas** [comment]
How much does this differ from the current sets?  Is it a code change?  Does it look like it lines up more closely with one of the current sets in particular?  It would be nice to know a bit about what’s different about it and how it fits into the picture.

**Comment by clawgrip** [comment]
The only different ROM is 9.bin, giving this romcmp output:

9.bin   pi8910.k14   [1/4]      80.154419%

All the other differences from the "prehisle" set is just using smaller EPROMs instead of larger mask ROMs.

The ROM 9.bin is for sprites, but I cannot spot anny difference. I've player the new set for some time and everything seems OK. We've verified the dump and it seems OK.

Thanks

**Comment by DavidHaywood** [comment]
hmm that's quite a big change to the first 1/4 of the sprite ROM.

that sprite ROM contains player ship and some enemies, not even copyright text.

(it's the 3rd gfx decode region in the viewer)

tiles 0x000 - 0x3ff are potentially different, and should be checked, maybe it's bad, or maybe an enemy was replaced for some reason?

**Comment by DavidHaywood** [comment]
maybe check the $ sign, sprite 0x139 and above? it's the only thing I can think that might have been changed for reasons of localization.  If you can't, send to me and I'll have a look?

**Comment by clawgrip** [comment]
> 
> 
> maybe check the $ sign, sprite 0x139 and above? it's the only thing I can think that might have been changed for reasons of localization. If you can't, send to me and I'll have a look?

Will send it to you, thanks a lot. We no longer have the PCB.

**Comment by DavidHaywood** [comment]
it simply appears to be a bad dump

there are some random pixel changes, then all the characters for that part of the ROM after 24e have been blanked out, this includes some enemy types, which if used are going to be invisible?

**Comment by DavidHaywood** [comment]
the random pixel changes cause corruption on some sprites http://mamedev.emulab.it/haze/pics2021/bitholes.png

so it seems to be a partially erased / partially programmed (last 1/4 blank) ROM with bad bytes?

**Comment by clawgrip** [comment]
Damn!

Thanks a lot. I'll close this PR. I've asked the new PCB owner to check for ingame gfx problems, to confirm if the EEPROM is bad or it's just a bad dump (I'd say it's a bad EEPROM, Victor verified the dump and he's a reliable dumper with good quality equipment).

Thanks again. Best regards: ClawGrip

**Pull request closed without merging**
