### PR TITLE
z180: added support for DREQ, TEND signals; fixed dma0 count, DREQ handling

### PR DESCRIPTION
**Pull request by BartmanAbyss**

### CODE REVIEW

**Comment by happppp** [comment]
For readability sake, please keep the coding style consistent with the rest of the file :)

**Comment by BartmanAbyss** [comment]
Sorry, what did I do?

**Comment by happppp** [comment]
Your curly braces style is K&R, the rest of the file is Allman style.

**Comment by rb6502** [comment]
MAME tends to use Allman-style bracing, ie

if (blah)
{
}
else 
{
}

You did the one block in GNU-style.

**Comment by BartmanAbyss** [comment]
Thanks for the info. Will try to be more careful next time...
Cheers

**Pull request merged**
