### PR TITLE
genpc.cpp: Load ROMs like in pc.cpp, allowing larger ROMs of late XTs to be added

### PR DESCRIPTION
**Pull request by rfka01**

### CODE REVIEW

**Comment by cuavas** [comment]
This changes behaviour - now for all the 8KiB BIOSes, rather than 0xf0000-0xfdfff being unmapped, it will return whatever the `bios` region gets initialised to in an area with nothing loaded into it.  I don't think there's really a clean way to support different size BIOSes in a single ROM set, just using the BIOS selection feature.

**Comment by rfka01** [comment]
The behaviour is now the same as it used to be in pc.cpp and ibmpc.cpp.
I could create two machines tailored to the different ROM lengths ... e.g. keep "pc" and introduce "pclrg" and sort the BIOS files to their appropriate sections. I'd have to do the same in pc.cpp, otherwise the change would be pointless.
How about ibmpc.cpp? ibm5150 has ROM starting from 0xf6000 ... should that be accounted for?

**Comment by cuavas** [comment]
I don't think it's hurting too much at the moment, I just commented that it caused a change.  Leave it as-is for now.

**Comment by cracyc** [comment]
There shouldn't be any effective difference as there are no adapter roms that cam be mapped there and upper memory blocks don't exist on the xt.  The only visible difference would be that reads there would return 0 instead of 0xff and I doubt that any software would care.

**Pull request merged**
