### PR TITLE
Nuon softlist

### PR DESCRIPTION
**Pull request by incog**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
orphaned softlists are bad.  if you're not going to make a sleketon driver with the softlist hooked up, don't make a softlist.

**Comment by incog** [comment]
We already have softlists exactly like this, why are they bad?

**Comment by Gurudumps** [comment]
FYI, I saw the PCB years ago. There's actually nothing on the Nuon PCB that is directly dumpable. Short of doing a full decap of every chip, this system will never be emulated. Meaning this pull can be deleted or closed or archived offline or whatever.

**Comment by DavidHaywood** [comment]
we've seen a picture of one that definitely had a fully dumpable BIOS mask / flash ROM of some kind... can't remember which model it was, but that statement definitely isn't true for all Nuon devices.

**Comment by Gurudumps** [comment]
The Nuon I saw only had a bunch of custom chips and no dumpable parts. But whatever.

**Comment by galibert** [comment]
The sdk was good enough to generate 3 different bioses, so yeah, we will
emulate it at some point.  There's an internal boot rom we don't have
access to, but I can guess (most of) what it does.

  OG.

**Comment by DavidHaywood** [comment]
This is what was posted by 'rosewood' back in the day on the bannister.org forum, although the ROM link is no longer valid.  There are other players that look similar in configuration to this tho.

The DVD-N505 has an OTP EPROM "AMIC A278308-90", I was able to dump it with the settings for "AMIC A27020". I don't know if the dump settings messed it up or if it is encrypted, please see for yourself: http://s000.tinyupload.com/?file_id=81603409329673969598

Sticker on the chip:
DVD-N505/XEG
VER EX2FEE1.2
TV.2001.12.07

Firmware info:
bios version information
bios version = 2.01
oem revision = 00
vml revision = 28
build date = nov 16 2001
info: bios rom version 2.1.28.0 for samsung. copyright c 1998-2001 vm labs, inc. all rights reserved.

cache configuration values
i-cache = 0x00000022
d-cache = 0x00000201

http://retrostuff.org/wp-content/uploads/2015/09/nuon_dvd-n505_01.jpg
http://retrostuff.org/wp-content/uploads/2015/09/nuon_dvd-n505_02.jpg

When you run the DVD-N501 firmware update disc it complains that this isn't a N501. As it is an OTP EPROM I don't see how it could update it anyways, maybe the N501 has a diffent firmware chip.

**Comment by DavidHaywood** [comment]
I'd guess the regular ROM is for the DVD part, and maybe the chip bottom left is some kind of FLASH rom for the Nuon? or the other way around..

**Comment by Gurudumps** [comment]
Someone should have the ROM from that link so the thread should be bumped and a request put there to get the file if anyone has it. Yeah the chip bottom left is a fairly common Atmel AT49BV1614 16Mbit TSOP48 flash ROM. This kind of thing is probably difficult to find out in the wild now, so some effort should be made to get one and dump the ROM while it is still possible. There are plenty of other things that are now impossible to find that could have been dumped if a little effort was put into it when the item was newer. The guy went to the trouble to make the softlist and it shouldn't be ignored for ~2 years (including many of the pulls here, some going back~ 4 years or more). That;s not good for public relations especially when mame is already on life support developer-wise. Within the next ~10 years there won't be anyone capable of emulating it even if the ROM was dumped.....

**Comment by DavidHaywood** [comment]
well incog is known anyway, he hasn't vanished.  as for the ROM dump, don't think anybody verified it as valid.  at the time I volunteered to make a skeleton driver for the player so that a list could be hooked up or whatever, but was told it was already being looked at.

not honestly sure there are any devs active now who could emulate it, apparently it requires all the cores to run in steplock with full pipelining etc. which is about the worst possible case for the MAME core.

**Comment by Gurudumps** [comment]
which brings us back full-circle... it's not going to be emulated ;-)

**Comment by MooglyGuy** [comment]
I like that you still contribute information to the handful of devs who remain willing to work with you, and you have retained your ability to drive away Japanese contributors through your mere presence as a contributor, yet your know-it-all attitude has not attenuated in the slightest.

In the future, I would advise sticking to what you're good at, which is reselling PCBs that were originally donated for the purposes of emulation, and releasing dumps of rare Japanese boards without the owner's consent.

**Comment by Gurudumps** [comment]
I'm going to ignore the first part. 
As the the 2nd part, if you are referring to dumps I put on my site, the same dumps were sent to me from 3 different people over a period of several months.... so they were already 'out there'. There's obviously a leak in Japan and that's not my problem. Anyway, this is not the place to discuss this. Move on dude and do what you are good at. Not sure anyone knows what that is, but anyway, move on.

**Comment by DopefishJustin** [comment]
I still have rosewood's dump from that thread and it's already in the usual place as "nuon-a278308.7z" along with several other dumps.

**Comment by arcadez2003** [comment]
> 
> 
>if you are referring to dumps I put on my site, the same dumps were sent to me from 3 different people over a period of several months.... so they were already 'out there'. There's obviously a leak in Japan and that's not my problem.

I have Sega Sonic Bros as im sure quite a few others do up and running in my own personal
MAME build, i would like to push a driver containing support for it to the git sometime but well 
that would only bring a large dose of drama trouble and strife with it :)

But anyway that is a debate for another time, i wanted to ask you is it possible to release a 
proper dump of Oo Parts.?? rather than the hacked version available on your site which 
piggybacks off Icident R.

Please note im only asking Mr Guru a direct question as i would like to support the rom properly
in my own personal not for public release segac2.cpp driver, i dont expect anyone else here to 
start finger wagging in my general direction.

**Comment by DavidHaywood** [comment]
The Sonic dump is hacked too.

You know this is taboo, so why are you asking here?

If this continues I'll be removing the C2 driver from official builds entirely, I've already had too many unwanted issues as a result of my name being in it and people adding these things, and this is NOT a private place to be asking things.

**Pull request merged**
