### PR TITLE
SCC improvements

### PR DESCRIPTION
**Pull request by JoakimLarsson**
- zbus interface functions zbus_r and zbus_w added supporting shift left/right modes
- improved variant handling including the incomplete read register maps for some
- external CTS and DCD interrupts added
- improved device reset values
- SWI acknowledge command added
- improved/fixed handling of wr9, rr2, rr3
- wr7prime register added

### CODE REVIEW

**Comment by cuavas** [comment]
How much testing have you done?  Have you checked that keyboard is still recognised across Sun 3/4 drivers after this?  They seemed to be pretty good at abusing the chip.

**Comment by JoakimLarsson** [comment]
I had to timekeeper image so I disabled that and compiled sun2, sun3 and sun4 drivers and tested it on several variants in these drivers without noticing any problem. However I have no access to a bootable disk. My feeling is that it may even work better though, I'll fix whatever problems arises, guess tafoid has set up the regression tests for these?! I could see some changes in the way the internal BRG was set up, it got baud rate values now in places that before was 0, can only interpret that as good...

**Comment by JoakimLarsson** [comment]
And of course the hk6810 and mvme147 boards were tested and still works

**Comment by cuavas** [comment]
You don't really need a bootable disk for the Suns to test SCC abuse.  They probe keyboard on startup, they'll either tell you the type of keyboard (working) or that no keyboard is present (not working).

**Comment by JoakimLarsson** [comment]
I checked again and sun2_120, sun3_30, sun3_80 and sun4_75 all can detect their keyboards

**Comment by JoakimLarsson** [comment]
I am more curious over extensive use of interrupts once the OS is up and running :)

**Comment by rb6502** [comment]
Those drivers can't boot an OS yet.  It's on my to-do list.

**Pull request merged**
