### PR TITLE
sinclair/sprinter.cpp: default layout with Turbo,NeoGS,FDD,HDD leds

### PR DESCRIPTION
**Pull request by holub**
Would such changes to atahle acceptable or can you suggest better place?

### CODE REVIEW

**Comment by cuavas** [comment]
The trouble with adding outputs in atahle is there can be more than one of them in a system, and they’ll stomp on each other’s outputs.  Eventually outputs will be per-device, but that requires `output_manager::set_value` to be phased out first, and no-one is actively working on removing uses of it.

**Comment by holub** [comment]
> The trouble with adding outputs in atahle is there can be more than one of them in a system, and they’ll stomp on each other’s outputs. Eventually outputs will be per-device, but that requires `output_manager::set_value` to be phased out first, and no-one is actively working on removing uses of it.

Yeah. That's my current trouble which I'm ignoring. It's fine to have one output for master+slave but second hdd will ruin everething.

Is it possible to have reference such as `ata0:ata_busy_led`?
What options do I have? Revert ATA part in the PR?

**Comment by holub** [comment]
By the way, here I exposed BUSY. I don't see a technical way to expose ACTIVE at the current state.

**Comment by cuavas** [comment]
I’d rather you remove the LED from the ATA HLE thing in MAME at this point.

As an aside, ATA activity LEDs in PCs were usually connected to the ATA interface card, or the motherboard if the ATA interface was integrated in the chipset (via a 2-pin 100 mil pitch header), not the drives themselves.  (SCSI activity LEDs were connected to the drives themselves via a 2-pin header with narrower pitch.)

**Comment by holub** [comment]
> I’d rather you remove the LED from the ATA HLE thing in MAME at this point.
> 
> As an aside, ATA activity LEDs in PCs were usually connected to the ATA interface card, or the motherboard if the ATA interface was integrated in the chipset (via a 2-pin 100 mil pitch header), not the drives themselves. (SCSI activity LEDs were connected to the drives themselves via a 2-pin header with narrower pitch.)

removed

**Pull request merged**
