### PR TITLE
Enhanced support for CMake.

### PR DESCRIPTION
**Pull request by dankan1890**
Added some entries to generated CMakeList files to allow compilation and build.

 **Note** 
There is no change at the operating level if CMake is not used.
Tested only on linux (Lubuntu 17.04 - 64bits), compiles and builds target MAME and TINY (both in Release and Debug).
For more support (other platforms, more flags to set), we need more radical changes to the MAME generation scripts files.

### CODE REVIEW

**Comment by cuavas** [comment]
Have you sent the changes upstream for GENie?

**Comment by dankan1890** [comment]
Is still too preliminary to be able to send it to the upstream.

**Comment by cuavas** [comment]
Well if it's too preliminary to send upstream, it's not really appropriate to go into GENie in mainline MAME.  There's too much risk of it getting out of sync, or coming to rely on something that never reaches a form suitable for inclusion in the upstream version.

**Comment by dankan1890** [comment]
In fact I have successfully tried to build the "bx" project from the official repository.
Of course, even there, there are changes to be made in the configuration file of the genie and toolchain, which should be easy for the owner.

**Comment by dankan1890** [comment]
Changes have been accepted and included in the upstream.

**Pull request closed without merging**
