### PR TITLE
Add udp multicast support

### PR DESCRIPTION
**Pull request by tedgreen99**
Example bitbanger usage: -bitb udp.234.99.99.99:15122

### CODE REVIEW

**Comment by Hydreigon223** [comment]
How would this do against #9101?

**Comment by tedgreen99** [comment]
udp multicast allows for many to many communication.  It would be similar to systems on an ethernet hub where everyone receives everything.

**Comment by cuavas** [comment]
God no!

**Comment by cuavas** [comment]
This is completely unsupportable.

Configuration is inadequate.  To configure UDP multicast reception, in addition to the group, you also need the local interface address (or IPv6 interface index) to bind to.  In practice, it often isn’t the interface that the routing table chooses.  It’s also useful to be able to specify a remote endpoint to connect the socket to in order to do kernel-side filtering on incoming packets if you’re only receiving from a single source.

To handle retransmission requests, etc. you need an additional socket, usually *without* the reuse address option, for handling one-to-one requests/responses.

You need to expose the datagram sources and boundaries to the client because UDP requires out-of-order reception and retransmissions to be handled at the presentation error (which is why we have things like [MoldUDP64](http://nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/moldudp64.pdf)).

Trying to force this into the stream-oriented `osd_file` and (poorly named) bitbanger device is a really bad idea and will just lead to things based on it working poorly.

**Pull request merged**
