### PR TITLE
c64_cass.xml: Correct some invalid software list filename entries

### PR DESCRIPTION
**Pull request by scoomby**
This pull request fixes some invalid software list filenames for some of the new clones added in my earlier c64_cass.xml pull requests.

### CODE REVIEW

**Comment by cuavas** [comment]
The name should match the actual label on the cassette where possible – there’s no requirement for names to be unique across different software list entries.  If the “(alt)” etc. aren’t actually on the tapes, they don’t belong there.

**Comment by scoomby** [comment]
These labels "(alt)", etc. were only added for clone set where the filenames matched the original set otherwise there would be an issue when using merged sets as previously advised

**Comment by cuavas** [comment]
That’s a “tail wags the dog” approach.  We don’t do that for system ROMs where clones have a ROM with the same label but different content, it shouldn’t be done for software list entries either.

**Comment by Tafoid** [comment]
I understand strict labeling rules when dealing with actual chips or other prefabricated storage devices, but in my opinion such a change is fine on lesser media such as floppies, cassettes, etc.  I don't see a problem with it.

**Comment by cuavas** [comment]
There’s no such thing as “lesser media”.  We’ve got a complete mess in the software lists now, and it needs to be cleaned up.

**Comment by scoomby** [comment]
It might be a “tail wags the dog” approach but it's an approach that seems to be used frequently for existing software list entries.  There are many other examples found in spectrum_cass.xml, c64_cass.xml, etc.  What is the alternative?

**Comment by cuavas** [comment]
The alternative is to start taking this seriously, and raise standards.  We’re trying to obtain best known dumps, and to replace poor-quality dumps, incomplete dumps, and dubious hacks/cracks.  The same standards for systems in MAME should be used for software lists.  Where possible, base the label on the actual label on the media.

**Comment by scoomby** [comment]
For this pull request, can we just merge this as it is just a fix.  Ideas/discussions for cleaning up the software lists can discussed going forward.  Thanks

**Comment by scoomby** [comment]
> The alternative is to start taking this seriously, and raise standards. We’re trying to obtain best known dumps, and to replace poor-quality dumps, incomplete dumps, and dubious hacks/cracks. The same standards for systems in MAME should be used for software lists. Where possible, base the label on the actual label on the media.

That is understood.  For all of my software list submissions, I have been keeping to the same filenames used on the C64 Ultimate Tape Archive V2 set.  But I do admit, the filenames used within the C64 Ultimate Tape Archive V2 do not have a consistent approach.

**Comment by Tafoid** [comment]
These changes seem perfectly valid to me.  @scoomby is simply retaining the extension which was obscured at the time with the (alt) additions.  The keeping of extension is consistent to the rest of the softlist.

**Comment by cuavas** [comment]
Further to that, the naming schemes used by a bunch of other software collections force far too much into the filenames, because that’s all they have.  For example, the ironically named “good sets” force a pile of dump flags into the filenames, because they have no other place for metadata.  As another example, some of the optical media collections require the filename of the cuesheet to be unique because that’s the primary key for identifying an entry.

MAME’s software lists don’t work like this.  We have a dedicated primary key (tuple consisting of short names of the list and item), and we have a uniqueness constraint on the description.  We have free-form metadata fields like the `alt_title`, dump flags, and so on, where various metadata can be preserved.  There’s no uniqueness constraint on labels for files that use the “ROM” loader between sets.

Forcing constraints from other collections onto MAME’s software lists is detrimental.

**Comment by cuavas** [comment]
>These changes seem perfectly valid to me. @scoomby is simply retaining the extension which was obscured at the time with the (alt) additions. The keeping of extension is consistent to the rest of the softlist.

The “(alt)” etc. are not actually part of the media labels at all.  If anything, “fixing” the software list would involve removing anything that isn’t part of the label on the original media.

**Comment by scoomby** [comment]
I am working on a separate pull request to add more C64 tapes to the c64_cass.xml software list.  It will be a small sample just to get some feedback on the way forward with the intent to raise standards.  The only thing that I am not clear on is the best way to manage clones for software lists where we have the same game label occurring twice (e.g. Arkanoid) but released from different publishers/distributors (e.g. Erbe & Imagine).  Any suggestions on how to manage this going forward will be very much appreciated.  Once a clear way forward for the software lists is identified, I can start tidying up all existing entries within the c64_cass.xml software list.

However, with the imminent release of MAME 0.234, I would still like to get this fix merged to correct the typos in my earlier pull requests.

**Comment by Robbbert** [comment]
This merge is purely on the understanding that the filenames are greatly improved as discussed.

**Pull request merged**
