### PR TITLE
Improve Patinho Feio driver & Generic Teleprinter

### PR DESCRIPTION
**Pull request by felipesanches**
This is a set of improvements to the emulation of the Patinho Feio driver.
It also includes improved rendering of the generic teleprinter featuring blotchy glyphs printed on paper and soudn samples for character printing, carriage-return moviment and linefeed.

The visual and audible aspects of it can be seen in the emscripten build of it at: http://felipesanches.github.io/emuladores/patinho.html

### CODE REVIEW

**Comment by cuavas** [comment]
Please separate the teleprinter changes from the Patinho Feio changed.  I take issue with a number of things in the teleprinter changes.

Anything relating to the Model 33 ASR belongs in a Model 33 ASR device, not in the generic teletype,  This includes its font, its speed characteristics, its sounds, etc.

Putting that aside, there are issues with the approach to simulating a Model 33 ASR:
* The Model 33 didn't produce "blotchy" glyphs, it use a typewheel mechanism and was capable of decent (although not spectacular) output quality.  The poor-quality teletype output seen these days comes from old machines where the platen has hardened, the print head has become misaligned, and the ribbon is in less than ideal condition.
* The Model 33 had 69 different typewheels available.  Which one are you trying to represent here?  Ideally, the loaded typewheel should be a configuration option or a slot device.
* The implementation of glyph lookup with a linear search and compare is nothing like how a teleprinter actually worked.  The Model 33 typewheels logically had 42 positions and two shift states (physically there are four rows of 21 characters on the typewheel).  A mapping function was used to convert seven bits of the incoming code to a position and shift state.  Simulation should represent this properly.
* The Model 33 had automatic WRU response of up to 20 arbitrary 8-bit characters by means of a drum with breakable tabs.  This should be simulated as an image device.
* The Model 33 ASR has an automatic 8-bit paper tape punch/reader which should be simulated as an image device.  (As a shortcut you could simulate a Model 33 KSR, which lacks the paper tape.)
* Simulating timing on the Model 33 is quite complicated, it's not as simple as just using delays.  It had a number of continuously rotating components.  Things like sending a character had to wait for the component to come into position before they'd begin.  So you'd need to track the current position of all the components and synchronise it to get timing right.

Simulating a particular teleprinter properly is quite complicated, which is probably why no-one has attempted it.  Good luck if you want to do it, but please do it properly when you do, and keep it separate from unrelated changes.

**Comment by felipesanches** [comment]
I tend to agree with lots of what you said, but I don't feel like spending too much time on this right now. I'd rather focus on the Patinho Feio computer now. I may work more on this teleprinter stuff later though. Perhaps. Thanks for the insights.

**Comment by rb6502** [comment]
Vas, is this OK for you now?

**Comment by felipesanches** [comment]
I did not actually address the things that Vas pointed out. I'm still working on incremental improvements to the emulation of the CPU and of the machine itself because I think that's more useful work for me to be doing on my leisure time. (because that's where most of the historical preservation value of the Patinho Feio computer actually is and I'm the only Brazilian developer working on it, so I have a duty to get this done)

Also, I think that my implementation of a printed paper rendering for the generic teleprinter is actually much better than the current rendering in MAME master branch (which looks like a pixelated terminal screen while the purpose should be to emulate/render a paper printer).

I can understand how the suggestions that Vas presented could lead to a *much more* accurate implementation of teleprinter emulation and rendering than my current code, but that should not let one forget the fact that my work in this pull request is already better than the one at master branch (that misleadingly depicts paper as a pixelated video terminal), so I am not too worried about spending time on undoing the good stuff I've done up to now.

**Comment by cuavas** [comment]
No the code is not acceptable in this state.  The teleprinter changes need to be done properly or backed out.  The implementation is shoddy, The font is based on imagination, not a real Model 33 typewheel so calling it an ASR33 font is stupid (there is no Model 33 typewheel with that character set).  An idealised TTY shouldn't have sounds based on a particular mechanism.

Please use `git rebase -i` to select just the Patinho Feio changes.

**Comment by felipesanches** [comment]
...or, alternatively, name it "generic typewriter font" instead of "ASR33 font". Then you'll have an "arbitrary" font (just like we already do have now) but with ink on paper rendering style instead of pixel on screen.

**Comment by cuavas** [comment]
Seriously, you're not helping yourself here.  Separate out the Patinho Feio changes.  You should be able to do this with `git rebase -i`

**Comment by felipesanches** [comment]
Maybe later. Maybe.

I won't waste my time with such counter-productive finicky demands. If you really care so much about properly emulating/simulating the intricacies of a mechanical teletype, then perhaps you should be helping to do it, instead of simply blocking iterative small improvements.

**Comment by cuavas** [comment]
First of all, you've tied up two completely unrelated changes.  It isn't two unrelated bug fixes that happen to be convenient to do together, it's two unrelated sets of functional changes.  That's already bad form.  Secondly, the code is inconsistent quality.

I hadn't brought it up before, but your code is still making use of mixed spaces and tabs for indentation.  For example in  src/mame/includes/patinhofeio.h at lines 37 to 50 you have some lines indented with a single tab, and others with eight spaces.  This is sloppy, will not line up for anyone with different tab settings to you, and doesn't follow the MAME convention of using tabs for initial indents.

The code in `patinho_feio_state::update_panel` is ugly with the xor in every if statement.  It would be cleaner (and easier for the optimiser) to do each xor once into a local variable and just test it.

If you want to use a python script to generate a layout, then you need to make it part of the build process, not check in the script and the generated output.  That's just asking for them to get out of sync.

A C++ source file containing an XPM bitmap in a string is not an XPM file and shouldn't have an XPM extension.

The code you're using to map bytes to bitmap positions is unacceptably bad.

Your choice of sound effects for a generic TTY is questionable at best.  A carriage return sound isn't relevant to all TTYs, as high-speed teleprinters with chain mechanisms don't have a concept of a carriage as such.  On the other hand, most teleprinters actually do make some kind of sound on line feed.  But the most glaring omission is lack of bell sounds.  TTYs generally ring a bell on receiving the the BEL character, and at a configurable column position when echoing keyboard input.  Unlike the other sounds which are side-effects of the mechanism used, bell sounds are actually intentionally generated.  If you're going to add sounds for a generic TTY, the ones to add would be the bell sounds.

It's far from the "iterative small improvements" you claim.  If you could actually accept criticism rather than immediately going into defensive mode and assuming you know better than anyone else, you wouldn't waste as much of your own time or others'.

**Comment by felipesanches** [comment]
I'm aware of several of the things you pointed out. All will be improved at some point. There's no need to rush, I'm still focusing on more fundamental aspects of the CPU emulation.

Some other things you just mentioned are new insights I had not thought of yet and I would have been really glad if you had provided such feedback as someone who wants to help, instead of using them as some sort of rhetoric weapon that you keep to yourself until you can use it strategically.

Unfortunately, your recurring behaviour does not make me feel like talking to a friend or a collaborator in a shared-effort project. You sound like a boss. A really bad boss, because a good boss has got the skills to encourage people to engage in work instead of making people angry or sad.

**Comment by balr0g** [comment]
@felipesanches I highly recommend splitting this into two separate branches / pull requests. Personally I prefer keeping things atomic since that makes tracking down problems much easier.

**Comment by felipesanches** [comment]
@balr0g yes, I agree and I will do it at some point. Maybe a bit later this week.

**Comment by cuavas** [comment]
Try to see this from someone else's point of view for once:
* You don't seem to be able to learn from past experience.  Every one of your pull requests that I look at has issues with indentation, spacing and consistency.  I raise the same issues every time, yet you never seem to learn.
* You always present a smug attitude, as though you think you know better than everyone else, and will only communicate on your own terms.
* You take it personally if anyone suggests that your ideas or code is flawed.
* You seem completely unable to accept or act on any kind of criticism of your code.
* In this pull request, you seem to be trying to force a change you want to make to the generic TTY by tying it up with changes to the Patinho Feio.  I indicated to you on IRC that changes like this would be contentious before you started, yet you still went ahead.

Can you seriously not see how you're antagonising people and not doing anything to build trust?

**Comment by felipesanches** [comment]
I just noticed something that may be a misunderstanding causing trouble in here. I'm not actively asking for this to be merged immediately. Instead, I'm working on the code publicly (rather than in private), so, from that you can better understand why the code may be in rough-shape in some parts. It is mostly a work in progress, among several other non-coding tasks related to the historical preservation of the Patinho Feio computer, such as book scanning, punched-tape data dumping, phone calls and in-person meetings with the people that were behind the development of this computer back in 1975, etc...

Now I can see that I probably should have placed a big disclaimer in the description of this PR making it clear that it it not meant for immediate merge, but rather for collecting feedback so that I can improve it. It's only natural that you faced this as a request for merge, since, after all this thing here is called a "pull request"! My mistake here, sorry. I'll add the big warning next time I do it.

Now, you may ask why did I open a Pull Request if I did not want it necessarily merged immediately, right? That's because I want to let people know I'm working on it. I want to make my work visible so that friendly people can help.

**Comment by felipesanches** [comment]
I'll probably continue pushing commits to this branch and they'll probably show up here in this closed PR as a side effect. No rush to merge. You don't even have to worry about it. I may squash everything into a single commit later when it reaches a good state. And yes, I'll split out the controversial teleprinter code to its own independent PR when I feel like doing it later.

**Comment by cuavas** [comment]
OK, if you're not asking for it to be merged in its current state, that's fine.  But in that case, I'd recommend not opening a pull request against it.  A pull request implies you want us to merge in the immediate timeframe.  If you just want to develop on a public branch, that's fine.  We can leave it on a closed pull request and re-open it when it's time to sort out issues and merge.

**Comment by felipesanches** [comment]
That sounds good! Thanks.

**Pull request closed without merging**
