### PR TITLE
I'm starting to hate save states :D

### PR DESCRIPTION
**Pull request by darq-**

### CODE REVIEW

**Comment by cuavas** [comment]
Could you please rebase or reset onto mainline after pull requests are merged?  It makes the revision graphs easier to follow.

**Comment by darq-** [comment]
Hi,
I'm very beginner to git :)

Could you explain me the fastest way to do this (possibly without deleting my fork, and doing a "re-fork") ?
Thanks.

**Comment by darq-** [comment]
Ok, I think I did it.
After setting a 'remote', I used -> git merge upstream/master
Is that the correct way?

**Comment by cuavas** [comment]
No, that merges master into your branch which is what you're been doing so far.  What you want to do is "git rebase upstream/master" to replay any divergences on top of master, or "git reset upstream/master" to replace the current state of your fork with master, then "git push --force".

**Pull request merged**
