### PR TITLE
Added 8 new entries to psx softlist

### PR DESCRIPTION
**Pull request by RalfVB**
Fire Pro Wrestling G v1.1 [fireprog]
Gradius Gaiden v1.1 [gradiusg]
Gunner's Heaven [gunnersh]
Hokuto no Ken - Seikimatsu Kyuuseishu Densetsu [hokutosk]
Jikkyou Oshaberi Parodius - Forever with Me [jikkparo]
Macross Digital Mission VF-X [macrovfx]
Macross VF-X 2 [macrvfx2]
Zanac x Zanac [zanacx]

### CODE REVIEW

**Comment by cuavas** [comment]
You appear to have touched every line in the file.  Please re-do this so we can see what the actual differences are.

**Comment by RalfVB** [comment]
I copied the file locally, made edits there, then re-uploaded it to my branch, and PR'ed it.
Either doing that counts as replacing every single file, or maybe my text editor screws with the formatting, line endings possibly?

Here's a text file containing the new entries > http://www.mediafire.com/file/mdv9tgq2c871ing/psx_new.xml

**Comment by RalfVB** [comment]
You can download my additions here > https://www.mediafire.com/file/pbhdyaujg52c1ff/psx_new.xml

As for why this happened, it's probably my editor mangling the formatting. I'll look into that.

**Comment by RalfVB** [comment]
You can download the additions here > http://www.mediafire.com/file/pbhdyaujg52c1ff/psx_new.xml

As for what happened, I suspect it's my editor mangling the formatting. I'll look into that.

**Comment by RalfVB** [comment]
I'll re-do the PR properly.

**Pull request closed without merging**
