### PR TITLE
Cps1 new bootleg set, pal dumps, pal verification etc.

### PR DESCRIPTION
**Pull request by TwistedTom**
New bootleg set:  Jurassic99 (Cadillacs and Dinosaurs hack/bootleg)
Better dinopic sprite renderer (fixes missing tiles when character jumps/flips etc.)
Added various new pal dumps [Jammarcade: Bonky, Layer, Neocps1 ]
Verified various existing pal dumps
Created new mappers for various games that were still using hand-crafted mappers despite having pal dumps.
Various/misc pal related notes and corrections

### CODE REVIEW

**Comment by cuavas** [comment]
This needs proper credits for the PAL dumps as well.

**Comment by TwistedTom** [comment]
They are from Jammarcade wiki, permission to use kindly granted by Porchy.
WL22B -> Layer 
Q522B -> Neocps1 
KD29B -> Porchy 
KD22B -> Bonky

**Comment by cuavas** [comment]
There is no KD29B in this commit. 
What about KR22B?

**Comment by TwistedTom** [comment]
Sorry, my mistake, have corrected

**Pull request merged**
