### PR TITLE
Fix NuBus image compilation.

### PR DESCRIPTION
**Pull request by Mokona**
Compilation with `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` causes : 

```
Compiling src/devices/bus/nubus/nubus_image.cpp...
In file included from /usr/include/string.h:495,
                 from /usr/include/c++/9/cstring:42,
                 from ../../../../../src/emu/emucore.h:20,
                 from ../../../../../src/emu/emu.h:30:
In function ‘char* strcat(char*, const char*)’,
    inlined from ‘void nubus_image_device::file_cmd_w(uint32_t)’ at ../../../../../src/devices/bus/nubus/nubus_image.cpp:261:10:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:128:33: error: ‘char* __builtin___strcat_chk(char*, const char*, long unsigned int)’ accessing 129 or more bytes at offsets 988 and 860 may overlap 1 byte at offset 988 [-Werror=restrict]
  128 |   return __builtin___strcat_chk (__dest, __src, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is a tentative fix.

### CODE REVIEW

**Comment by cuavas** [comment]
I don't think this will actually work. The guest-side driver for the card expects a fixed-size memory area for the file name buffer that it can read and write.

**Comment by Mokona** [comment]
Thanks, I was wondering about this without having an evidence. I'll update the PR.

**Comment by rb6502** [comment]
Also, isn't this one of the errors from Ubuntu forcing FORTIFY_SOURCE?

**Comment by Mokona** [comment]
It's possible it's about FORTIFY_SOURCE.

Here's a new, much simpler take, that makes the compiler happy.

**Comment by cuavas** [comment]
It’s still not safe.  The handler for `kFileCmdGetDir` can potentially overwrite part of `curdir`.  I don’t think `curdir` is actually accessed by the guest system, so it isn’t required to be an array.  But I think at this point, it’s looking a lot like a “silence the warning, ignore the issues” PR that isn’t actually tested.  We recommend building with fortify source disabled: https://docs.mamedev.org/initialsetup/compilingmame.html#gnu-c-library-fortify-source-feature

**Comment by galibert** [comment]
Note that it can't be tested yet, since I've broken the mac.

  OG.

**Comment by Mokona** [comment]
Indeed, it was not possible to test it and was a temporary workaround to silence the warning. I missed the mentioned  FORTIFY_SOURCE recommendation and will go for that.

**Pull request closed without merging**
