### PR TITLE
New NOT_WORKING machine

### PR DESCRIPTION
**Pull request by clawgrip**
---------------------------
Super Road Champions (TTL) [f205v]

### CODE REVIEW

**Comment by cuavas** [comment]
Why is it in taitottl.cpp if it isn’t from Taito?  These files don’t really seem to organise things by hardware at all, they‘re just buckets for skeletons organised by manufacturer.  As far as I can tell, they often contain games running on unrelated hardware, where the manufacturer is the only thing they have in common.

**Comment by Osso13** [comment]
It's my fault: I suggested it would be an appropriate place to put it, since according to http://www.tilt.it/deb/modelracing-en.html#superroadchampions it's derived from Taito's Road Champions.

**Comment by clawgrip** [comment]
@cuavas So, knowing that is a derivative work from a Taito TTL game... Is OK to put it here or should I create a new driver for it?

Thanks

**Comment by cuavas** [comment]
Well, the question is whether it’s a derivative in the sense that they cloned the gameplay, or it’s a relatively simple modification to the circuitry.  Given how specific the circuitry on a lot of these games was, even relatively minor changes from a player’s point of view could mean very different circuitry.  Is there anything better to go on than one line on a web site?  (I’m pretty reluctant to trust stuff on the web given the inaccuracy of arcade-history, KLOV and friends, and the way Underground King managed to find its way onto Japanese lists of rare arcade games.)

**Comment by clawgrip** [comment]
There are info about Model Racing Super Road Champions here: http://www.citylan.it/wiki/index.php/Super_Road_Champions , but I cannot find anything about the original Taito Road Champion.

**Pull request merged**
