### PR TITLE
Revert "Sync with GENie upstream revision ce9f3c5"

### PR DESCRIPTION
**Pull request by Robbbert**
Reverts mamedev/mame#6262

Completely breaks windows build.

### CODE REVIEW

**Comment by sl1pkn07** [comment]
revert this fail build in linux

~~~
make[1]: Entering directory '/tmp/makepkg/sdlmame-wout-toolkits/src/mame-mame0218/build/projects/sdl/mame/gmake-linux'
make[1]: Leaving directory '/tmp/makepkg/sdlmame-wout-toolkits/src/mame-mame0218/build/projects/sdl/mame/gmake-linux'
make -R verbose=1 -C build/projects/sdl/mame/gmake-linux config=release64
make[1]: Entering directory '/tmp/makepkg/sdlmame-wout-toolkits/src/mame-mame0218/build/projects/sdl/mame/gmake-linux'
Archiving libformats.a...
rm -f "../../../../linux_gcc/bin/x64/Release/mame_mame/libformats.a"
ar: ../../../../linux_gcc/bin/x64/Release/mame_mame/libformats.a../../../../linux_gcc/obj/x64/Release/src/lib/formats/2d_dsk.o: No such file or directory
make[2]: *** [formats.make:1304: ../../../../linux_gcc/bin/x64/Release/mame_mame/libformats.a] Error 1
make[1]: *** [Makefile:31: formats] Error 2
make[1]: Leaving directory '/tmp/makepkg/sdlmame-wout-toolkits/src/mame-mame0218/build/projects/sdl/mame/gmake-linux'
make: *** [makefile:1345: linux_x64] Error 2
~~~

**Comment by sl1pkn07** [comment]
please, almost, backport this commit

https://github.com/bkaradzic/GENie/commit/910e4d757f4cd6643e2a04b834d933329e577350

greetings

**Comment by rb6502** [comment]
I can build fine with those changes on Fedora 31 and Mac OS X.  Do a make clean and build with REGENIE=1 if you have previous build droppings.

**Comment by sl1pkn07** [comment]
is builded clean chroot

patched bundled genie with that PR builds fine in my Archlinux

greetings

**Pull request merged**
