### PR TITLE
ctk551.cpp: New working machines

### PR DESCRIPTION
**Pull request by devinacker**
---------------------------------------
Casio Celviano AP-10 [Devin Acker]
Casio CTK-601 [Devin Acker, Gabriel Miceli]
Casio GZ-70SP [Devin Acker]

These are three more GT913-based MIDI devices. Aside from the ROM definitions etc., this PR also:
* gives the GT913 a more complete CPU implementation and improved sound emulation. This includes replacing the `required_memory_bank` with a new address space, not just because it needs to be able to contain read/write handlers, but also because the bank-switchable memory is accessible not just through the regular program space but also through a special mode of indirect addressing (see `gt913_device::read8ib`, `write8ib`, etc.)
* Fixes the H8/300 `subx.b` instruction with regard to how it affects the Z flag. This was verified against docs from Renesas and is necessary for both of these machines to run because of how they perform 16-bit comparisons.

### CODE REVIEW

**Comment by devinacker** [comment]
Audio recordings from MAME: https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=121007#Post121007

**Comment by galibert** [comment]
read8i and friends must *not* touch icount.  All icount changes must happen through generated code.

Eventually the generated code will be able to redo a read/write if it didn't complete for reasons like bus contention, returning from execute_run and redoing it afterwards.  It can't work if icount is changed in the access code.

**Comment by devinacker** [comment]
Done. Also renamed the indirect read/write methods to avoid confusion with `h8_device::read16i`.

**Comment by devinacker** [comment]
Taking this out of draft status since the CTK-601 artwork is now ready, and added a third new machine while I'm at it.

**Comment by cuavas** [comment]
@galibert can you please take a look at this?  I was really just doing a “checklist review”, and you know the H8 and synth stuff better than me.

**Comment by devinacker** [comment]
Pushed a couple of minor CPU and sound fixes following some additional testing. That's probably all for now, though.

**Comment by devinacker** [comment]
Any chance the H8 stuff could be looked at before the upcoming freeze? :)

(FWIW, almost all of it is specific to the custom variant used by this driver; the only thing that should affect the rest of the variants is the corrected `subx.b` behavior)

**Comment by devinacker** [comment]
@galibert Sorry to nag, but do you think you'll have time to look at this anytime soon?

**Comment by galibert** [comment]
Probably not, and I'm going afk on a bike for two weeks soon.  @rbelmont
maybe?  He's done almost as much h8 as I did.

**Comment by galibert** [comment]
A quick look tells me that the h8 non-ctk/gtk parts make sense (subx and
intc).

**Pull request merged**
