### PR TITLE
spectrum48 int fix

### PR DESCRIPTION
**Pull request by holub**
additions to #9449 (changes made on top of it)
Fixed "floating" int. Now border in demos stays steady and not shaking.

shock_after
ula48
tacts_after

### CODE REVIEW

**Comment by holub** [comment]
Only latest commit for review. Rest already merged.

**Comment by cuavas** [comment]
Sorry, this has conflicts with master, and it looks like your branch is a bit of a mess.  Can you please create a new branch off mainline, and play your changes on top of that, so it’s in a clean state?

**Comment by holub** [comment]
> Sorry, this has conflicts with master, and it looks like your branch is a bit of a mess.  Can you please create a new branch off mainline, and play your changes on top of that, so it’s in a clean state?

Sure. There ara some concerns regarding adding such counter to debugger window. We'll make decision and I provide proper update to this PR.

**Comment by holub** [comment]
There you go #9637

**Pull request closed without merging**
