### PR TITLE
Add a webserver interface & module

### PR DESCRIPTION
**Pull request by cbrunschen**
Add a webserver interface, and a module that can provide a suitable implementation through machine().osd().get_webserver() .

The interface allows clients to register HTTP handlers at specific paths, such as to serve HTML, Javascript, JSON or similar. The interface also allows registering Websocket connection handlers at specific paths, as well as websocket message handlers once a connection has been accepted.

Also import the websocketpp library from https://github.com/zaphoyd/websocketpp/ , then use that to provide an implementation of the just-added webserver interface availabel through the webserver_websocketpp module.

In the esqpanel_device class, start using the webserver implementation provided by the webserver module, registering handlers to accept websocket connections and a protocol to communicate with an external panel, such as might run on a tablet or other device that can be more easily co-located with a MIDI keyboard for playing

In the esqpanel_device class, also register HTTP handlers that can serve an HTML / SVG / Javascript-based external panel implementation that uses that same websocket protocol; thus allowing a modern browser to connect to the newly-provided web server, retrieve the external panel implementation in HTML & Javascript (using SVG for rendering), which then communicates
using a Websocket connection with the esqpanel_device class and allows controlling & interacting with the emulated keyboard.

### CODE REVIEW

**Comment by felipesanches** [comment]
Nice! So this assumes that the emulator will be running server-side while the UI can be implemented with webtechnologies, right? I like the idea of using SVG and I think this could be useful as well for 3D arcade cabinets such as Galaxy Force II and the other examples discussed at #388 

Any idea if this system could also work nicely with an emscripten build of MAME so that the emulator itself could also be running within the browser?

**Comment by felipesanches** [comment]
Maybe a facade implementation of this could have the client-server communication protocol input/output notifiers translated into corresponding javascript events for the emscripten build.

**Comment by mmicko** [comment]
Due to a compiler limitations (visual studio) and easier development I would suggest that file serving is done by file system access and not from embedded strings

**Comment by cbrunschen** [comment]
The web server can be used for a lot of things - it can serve arbitrary HTTP requests and handle arbitrary Websocket connections.

But my particular use case is specifically to allow a much richer UI than seems easily achievable using layouts, and that can also optionally run on a separate device from the one that runs the emulator, in part to allow things like multi-touch – in this case, being able to activate multiple buttons at the same time, which has a few important use cases on these keyboards. Using websockets means that things like browser-based UIs become possible and that in turn makes it easy to turn an arbitrary tablet into a touchable control device.

I'm fairly agnostic towards where the HTML & Javascript files or anything else etc are served from, but I do quite like the option of having them compiled in, so they don't have to be separately installed. 

I know ROMs etc already have to live elsewhere so there's precedent for it, but those are distributed separately, whereas the HTML & Javascript files here are included as part of the emulator in part because they need to agree on the protocol they speak, so it makes sense they're relatively tightly coupled.

Of course, the web server itself doesn't care: any client could register HTTP handlers that read from the filesystem, and it would be fairly straightforward to add something to the web server where it could directly resolve paths against a directory specified as a webserver_root option or similar. 

I noticed that I must have gotten something wrong about the module instantiation / selection process; if I specify "-webserver none" as an option, the webserver_none module is instantiated but the osd_common_t::m_webserver still ends up as null, which then is passed to the esqpanel_device which crashes trying to dereference it. I'm trying to track down my mistake, but any advice would of course be appreciated.

**Comment by cbrunschen** [comment]
Crash found & fixed: I had forgotten to mark the inheritance of webserver_none's webserver_module superclass as 'public'.

**Comment by mamehaze** [comment]
we're also going to have to run our own servers of various kinds for internal communications in order to keep some of the devices we emulate in the future happy (cases where the original servers are no longer online so we have to fake data to keep things happy; an example might be simulating the original xbox live servers so that those parts of the emulation can be used with a fake / replacement store for non-physical items)

**Comment by rb6502** [comment]
Haze has an excellent point.  We will definitely need the ability for drivers to instantiate their own servers (not necessarily HTTP) for things like that.

**Comment by cbrunschen** [comment]
I've moved the HTML and Javascript to be served from the filesystem rather than being compiled in. This includes minimalistic template evaluation so I can put the keyboard type and protocol version in the HTML being served.

Is this getting closer to being usable?

**Comment by felipesanches** [comment]
@cbrunschen In order to avoid the clutter seen above (loads of unrelated commits and a few developer comments about them) I'd suggest that you use the **git rebase** command on your development branch. It would work like this:

```
git fetch upstream
git rebase upstream/master
git push origin webserver --force
```

**NOTE:** The above assumes that you have a git remote named **upstream** pointing to https://github.com/mamedev/mame.git and that **origin** points to https://github.com/cbrunschen/mame.git

**Comment by cbrunschen** [comment]
I had been rebasing against upstream/master, but apparently not with the desired result. I created a patch of my latest changes against the latest master, deleted and recreated the branch, applied the patch, and force-pushed that here; there should now be just a single patch here.

**Comment by cbrunschen** [comment]
I've applied the patch at https://github.com/zaphoyd/websocketpp/pull/479 that makes everything appear to compile on mingw again. 

To run this and see & use it in action, I connect a USB MIDI keyboard (a Korg microKEY 37) and run:

`make -j6 SUBTARGET=mess SOURCES=src/mame/drivers/esq5505.cpp`
`./mess64 -w -rp ~/mame/roms sd132 -midiin "microKEY KEYBOARD"`

I also open a web browser (Chrome or Safari, on a computer or tablet) and point it at `http://_hostname_:55555/esqpanel/FrontPanel.html` 

The browser should be able to load the HTML and Javascript already at this point.

I then type 'OK' into the MAME window to confirm that I want to run the machine even though it's marked as "not working", and things start to work; the Javascript code should auto-connect to the esqpanel instance in the running keyboard and it should start show the same contents on its emulated display, as in the MAME window.

For the SD-1/32, initially the keyboard itself reports an "Error 137", but pushing a few buttons makes it reboot itself and then it works, for playing music - and with an emulated front panel that is quite close to the real one, including multi-touch for being able to press multiple buttons and move sliders, etc.

**Comment by cbrunschen** [comment]
Any thoughts?

**Comment by cbrunschen** [comment]
Anything, from anyone? Am I wasting everyone's time?

**Comment by felipesanches** [comment]
I truly appreciate the work you are doing and I am interested in re-using this new capability in a few of my own drivers.

**Comment by mmicko** [comment]
Hi Christian,

Sorry for not responding, but was spending more time on other tasks.
General idea is good. Thing is that there is basic code for http server now
inside our code base.
Would like to improve that to point that it can be used for REST protocols.

Web sockets are needed for push info back to application, but would like to
make it more general.
Implementation you are using seams mature enough to be used, and nice is
that it needs just asio.

Please do not mind we are not getting hurry with this, thing is we need
also to tryout how this work on
All potential platforms.

So please keep this code in your repo, so we can cherry pick things from
there.

Last time I created some architecture decisions wrong and based it on non
fully open source solution, also it was all more experiment, but get much
better image how it should work now.

Hope you understand.

Micko

**Comment by cbrunschen** [comment]
Hi and thank you for your replies!

I absolutely understand that this may not be what you want to get into MAME, and for good reasons. What worried me was just that suddenly, after I was trying to address comments, there were no further responses at all.

The HTTP server you refer to is the one in progress at https://github.com/mamedev/mame/tree/de7e80804e21ad675c9fe86db6ba9ac709aabc65/src/lib/http ? It makes sense in that case to base my external-panel work on that instead of on websocketpp – though of course that wasn't there yet when I started this, hence my duplication of the ongoing effort.

I do, as you note, need websocket support to be able to pass messages from server to client as necessary (display updates etc) and not have to rely on the client polling or similar. Fortunately, the websocket protocol is fairly straightforward 

If anything I wrote is at all useful, that's great :) And I'm looking forward to the proper MAME built-in webserver so that I can move the external esqpanel support on top of it.

I do hope that some of the things I put into place in my webserver interface can serve as inspiration. For example, some kind of simple templating system can be very useful, as can be seen in the example of the FrontPanel HTML into which the keyboard type is inserted at serving time. 

I'd also be happy to bring my external-panel patches across early as a test case for this kind of functionality, for example.

Thank you again!

// Christian

**Comment by mmicko** [comment]
No problem. Right that is http server implementation, thing is I had it in
my tree for some time. Asia was added into trunk for that reason.
But had some issues that were at the end typos in Asio library.
Anyway will see if Websocket part can operate together with our http
implementation.

Your code will be there, in som form for sure, but please excuse me doing
this slow.

Thanks,
Micko

**Comment by rb6502** [comment]
Hey, Micko, are you still looking into this?  Just want to make sure it doesn't get lost :)

**Comment by mmicko** [comment]
Still looking have independent solution for http and websockets, cleaning
it up and adding thing that we can need and looking for integration in core.

**Comment by rb6502** [comment]
@cbrunschen As of Git top-of-tree yesterday we now have a webserver and websockets solution.  Please look into them to see if they'll work for what you need here.

**Comment by cbrunschen** [comment]
Ohhh I shall do so! :) Thank you for the update!

// Christian

**Comment by mmicko** [comment]
Sorry I tough I would have more time to add few more things before bugging
you but it is Xmas here today/tomorrow so not much free time for coding :)

Anyway it is operational, but still need to add interface for devices for
easy web service extension. Idea is to try to make all in forward
declarations instead of including http server/asio includes due to
large number of symbols in them. Otherwise our compile time would double or
even worse.

Micko

**Comment by cbrunschen** [comment]
The main thing is that it's great to see this progress, thank you so much!

I'm happy to hold off on things and just study it for now until you have a
solution in place for how to access it!

Best wishes

// Christian

**Comment by cbrunschen** [comment]
Any progress on this? I'd be happy to be a guinea pig for APIs and functionality.

**Comment by NULUSIOS** [comment]
+1 - any news on this?

**Comment by cbrunschen** [comment]
Hi everyone, 

I've moved the changes on top of the HTTP and Websocket servers that are now in the MAME codebase.

There's a new pull request, https://github.com/mamedev/mame/pull/2443 .

Best wishes,

// Christian

**Pull request closed without merging**
