### PR TITLE
Added layout for Midway V-Unit games

### PR DESCRIPTION
**Pull request by Risugami**
Cruis'n USA, Cruis'n World, and Off Road Challenge

### CODE REVIEW

**Comment by MooglyGuy** [comment]
While it's great to have more lamps hooked up, the way it's done in this case seems like an ugly hack, just reading some arbitrary RAM location. I sincerely doubt the hardware actually worked that way.

The lamps were more likely driven off of some I/O port. If you can find how the lamps are actually hooked up on real hardware, that would be more likely to be included. As it's implemented, I'd be uncomfortable accepting this pull request.

**Comment by mamehaze** [comment]
yeah, seconded, this is a hack, hence needing the per-game ram addresses etc.

**Comment by Risugami** [comment]
I have found the I/O port and am quickly debugging it now. Will have update soon.

**Comment by Risugami** [comment]
Ok, had a strange commit, but it seems to actually be working better on the port.

**Comment by mamehaze** [comment]
the request still looks a bit messed up, I can see the new and correct logic in there, but your old changes also still seem to be present (the init functions with per game addresses etc.)

**Comment by mamehaze** [comment]
looks better now :-)

**Comment by Risugami** [comment]
This port also seems to control the motion outputs and volume for some reason. It also has a sort of error check write by wrapping every output with FFXX where XX is the second byte of the actual output between the two FF writes. Not sure if this needs to be emulated nor do I know the proper way to handle the errors so I'll leave it at that. the motion and volume controls don't share the same structure as the lamps and wheel, and are apparently a stream of single bytes with a header byte FD to say this. Again, not sure if this should be emulated. Watching for expected values seems to be working as intended, but might be worth checking in the future.

**Comment by balr0g** [comment]
@Risugami could you document this in code comments?

**Comment by Risugami** [comment]
I'm currently walking through the unknown stuff so another commit is likely coming soon. I'll add comments on what I find.

**Comment by rb6502** [comment]
Makes sense that all the cabinet control comes out of one port, actually.  On hardware it probably goes to a separate board with a microcontroller that actually manages the lights and force-feedback and stuff.

**Comment by mamehaze** [comment]
comments in the submission mention a 'large payload' with one of the commands, might be worth checking if it's the entire program for a known cpu..

**Comment by balr0g** [comment]
http://www.arcade-museum.com/manuals-videogames/C/Cruisn%20USA%20Single%20Sitdown.pdf seems to have a fairly detailed schematic of the hardware.

**Comment by Risugami** [comment]
here's the payload. doesn't seem that useful for emulation:
JG 90000,90000,90000;BG;TL 0.6,0.6,1.8
TL 0.55,0.55,1.7;WT 1000
TL 0.50,0.50,1.6;WT 1000
TL 0.45,0.45,1.5;WT 1000
TL 0.40,0.40,1.4;WT 1000
TL 0.35,0.35,1.3;WT 1000
TL 0.30,0.30,1.2;WT 1000
TL 0.25,0.25,1.1;WT 1000
TL 0.20,0.20,1.0;WT 1000
TL 0.15,0.15,0.9;WT 1000
TL 0.10,0.10,0.8;WT 1000
TL 0.05,0.05,0.7;WT 1000
ST XYZ;MO

Yes it's in ASCII and the newlines are the end of each sequence.

**Comment by ajrhacker** [comment]
Those are commands for Galil motion controllers. The schematics show a connection from a "GALIL" PAL on the wheel driver board to a "Galil Board."

**Comment by Risugami** [comment]
If you turn on the motion dipswitch after boot, bypassing the testing, you can get some more of the commands sent. Here's the one that is repeatedly sent while in game:
#IBO;IBO=_SCX|_SCY|_SCZ;MG "V" IBO {$2.0}
Looked up some of the sample code for Galil, and that is a definite match for it.

**Pull request merged**
