### PR TITLE
coco3: Fix shape of ￡and 𝑓 in the GIME video chip.

### PR DESCRIPTION
**Pull request by tlindner**
Screen_Shot_2021-08-31_at_9 07 41_AM

### CODE REVIEW

**Comment by DavidHaywood** [comment]
why is this data in the driver? it looks like it's from some kind of ROM?

**Comment by npwoods** [comment]
Not a ROM - it’s built onto the chip; might even be combinatorial logic

**Comment by DavidHaywood** [comment]
it's a font, if it's built into the chip then it should be a device ROM.

I've never heard of a bitmapped font generated in logic.

**Comment by happppp** [comment]
PR is fine by me, so I'll merge.

Yes, this kind of thing is definitely an embedded ROM array inside the chip.
You can do it with logic on simple things like a 7seg chip, but not this.

**Comment by rb6502** [comment]
Co-signed.  I'm fine with the PR, but the chip needs to be decapped sometime.

**Pull request merged**
