### PR TITLE
Add stride as sixth parameter to debug dump command

### PR DESCRIPTION
**Pull request by ajrhacker**

### CODE REVIEW

**Comment by cuavas** [comment]
It needs a better name than stride, but I like it in principle. Anyone got any ideas?

**Comment by rb6502** [comment]
Width or byte width?  I actually don't mind stride either, although it has more of a graphics connotation.

**Comment by ajrhacker** [comment]
Does "row size" sound better?

**Comment by cuavas** [comment]
Row length sounds fine to me.

**Comment by ajrhacker** [comment]
Rebased and amended.

**Pull request merged**
