### PR TITLE
misc/globalvr.cpp: Small note about a few games.

### PR DESCRIPTION
**Pull request by mikehyrus**
The Swarm is known to exist on Global VR's hardware.

### CODE REVIEW

**Comment by mikehyrus** [comment]
(Image from Global VR’s website)

**Comment by mikehyrus** [comment]
Video reference:
https://youtu.be/4xXnEHUFqXI

**Review by cuavas — COMMENTED** [review]
> The Swarm may be known to exist on Global VR's hardware.

What do you mean “may be known”?  Someone possibly knows?  Do you actually know it runs on that hardware?

**Comment by mikehyrus** [comment]
Sorry Vas, I meant is it known, it’s a good possibility it runs on that hardware with different graphics cards and it’s capable of running on 3D displays at the time.

**Comment by mikehyrus** [comment]
image
(Image from Global VR's website)

**Comment by mikehyrus** [comment]
@cuavas Turns out these two games run on the same PC motherboard as Aliens Extermination, Paradise Lost, and such.

**Comment by mikehyrus** [comment]
Closing to comply with recent changes.

**Pull request closed without merging**
