### PR TITLE
New working clone

### PR DESCRIPTION
**Pull request by algestam**
-----------------
Khokkey [algestam, Milan Galcik]

This PR adds Elektronika Khokkey (export version title: Ice Hockey).

Info on the export version found here: https://skopil.ru/information/raznovidnosti-mikroprotsessornykh-igr-elektronika/igra-elektronika-im-10-khokkej

The manufacture year (1988) was sourced here:  https://game-im02.ru/index/ehlektronika_im10_quot_khokkej_quot/0-31

### CODE REVIEW

**Comment by p1pkin** [comment]
are you sure it wouldn't be better to call it "Hockey" ?

**Comment by algestam** [comment]
The naming of Elektronika game drivers has recently been changed to prioritize the transliterated Soviet titles and therefore I think that khokkey is more suitable since that is the transliterated original title (Khokkey).

**Comment by p1pkin** [comment]
oh, OK, it just for me as for native Russian person was a bit hard to realize what "Khokkey" actually means "Hockey"...

**Comment by cuavas** [comment]
Given it's a loanword, we'd usually use the conventional English spelling, in the same way that we use "Mahjong" in Japanese titles rather than "Maajan" (it's a Chinese loanword).

**Comment by algestam** [comment]
Ok, I don't have a strong opinion going forward with either option. I assume that it is the game driver name `khokkey` we are discussing? The game title should still be "Khokkey" in my opinion since that is whats printed on the unit.

Let me know if you want me to change the driver name to `hockey` :)

**Comment by cuavas** [comment]
The issue is that “Хоккей” is not a Russian word – it’s an English loanword transliterated into Russian Cyrillic.  Transliterating it back to English Latin makes it look strange, and borderline incomprehensible, even to a fluent Russian speaker like @p1pkin.  In general, we don’t do back-transliteration like this when a title contains loanwords.  We use the conventional English spellings of the loanwords.  To be consistent with the general policy, the descriptions should use “Hockey” and “Autoslalom”.

There are numerous examples of this with Japanese game titles.  Here are three examples:
* まーじゃんエロティカゴルフ is called Mahjong Erotica Golf, rather than Maajan Erotika Gorufu (the entire title consists of Chinese and English loanwords)
* ぴょんぴょんジャンプ is called Pyon Pyon Jump, rather than Pyon Pyon Janpu (jump is an English loanword)
* 1943改ミドウェイ海戦 is called 1943 Kai: Midway Kaisen, rather than 1943 Kai: Midouei Kaisen (Midway is an English loanword)

**Comment by happppp** [comment]
Sure, I'll take care of it

**Comment by algestam** [comment]
That makes perfect sense, thanks for the explanation and examples. Thanks also @happppp for all your help! I'm learning a lot :)

**Pull request merged**
