### PR TITLE
Adding layouts to Maygay driver

### PR DESCRIPTION
**Pull request by johnparker007**
Adding some provisional layouts to the Maygay driver.  These are generated, and will be updated as I improve the MFME2MAME converter, transcribe reels etc.

m1albsqp (Albert_Square_(Maygay)_[C01_1024_6jp].gam)
m1apollo2 (Apollo_9_(Maygay)_[C02_1024_10jp].gam)
m1bargnc (Bar-Gain_(Maygay)_[C02_1024_4-80jp].gam)
m1bghou (Big_Ghoulies_(Gemini)_[C01_800_5jp].gam)
m1bigdel (Big_Deal_(Maygay)_[C01_1280_5jp].gam)
m1calypsa (Calypso_(Maygay)_[C01_1024_5jp].gam)
m1casclb (Casino_Club_(Maygay)_[C01_v1-0_1024_150jp]_[c].gam)
m1casroy1 (Casino_Royale_(Maygay)_[C02_v1-0_800_100jp]_[c].gam)
m1chain (Chain_Reaction_(Maygay)_[C01_1024_5jp].gam)
m1cik51o (Cash_Is_King_(Maygay)_[C02_1024_15jp].gam)
m1clbfvr (Club_Fever_(Maygay)_[C01_1024_200jp]_[c].gam)
m1cluecb1 (Cluedo_Club_(Maygay)_[C01_800_100-200jp]_[c].gam)
m1cluedo4 (Cluedo_(Maygay)_[C02_1024_6jp].gam)
m1cluessf (Cluedo_Super_Sleuth_(Maygay)_[C01_1024_10jp].gam)
m1coro21n (Coronation_Street_(Maygay)_[C03_1024_6jp].gam)
m1dkong91n (Donkey_Kong_(Maygay)_[C02_1024_15jp].gam)
m1dxmono51o (Deluxe_Monopoly_(Maygay)_[C03_1024_6jp].gam)
m1eastndl (Eastenders_(Maygay)_[C03_v1-2_1024_10jp].gam)
m1eastqv3 (Eastenders_-_Queen_Vic_(Maygay)_[C01_v1-01_1024_15jp].gam)
m1fantfbb (Fantasy_Football_(Maygay)_[C02_v1-1_1024_8jp].gam)
m1fightb (Fight_Night_(Maygay)_[C01_1024_10jp].gam)
m1frexplc (Fruit_Explosion_(Maygay)_[C01_v1-0_1024_15jp].gam)
m1gladg (Gladiators_(Maygay)_[C04_800_8jp].gam)
m1grescb (Great_Escape,_The_(Maygay)_[C04_800_5jp].gam)
m1hotpoth (Hot_Pots_(Maygay)_[C02_v1-0_1024_8jp].gam)
m1htclb (Hi_Tension_Club_(Maygay)_[C01_1024_150jp]_[c].gam)
m1imclb (Instant_Millionaire_(Maygay)_[C01_v1-1_1024_200jp]_[c].gam)
m1infern (Inferno_(Maygay)_[C03_v1-20_1024_6jp].gam)
m1inwinc (Instant_Win_(Maygay)_[C01_v1-4_1024_6jp].gam)
m1itjobc (Italian_Job_(Maygay)_[C02_800_10jp].gam)
m1itskob (It's_A_Knockout_(Maygay)_[C01_1024_8jp].gam)
m1jpmult (Jackpot_Multiplier_(Maygay)_[C01_1024_4-80jp].gam)
m1lucknon (Lucky_Numbers_(Maygay)_[C02_1024_10jp].gam)
m1luxorb (Luxor_Casino_(Maygay)_[C01_800_5jp].gam)
m1manhat (Manhattan_Skylines_(Maygay)_[C01_v2-1_800_4-80jp].gam)
m1monclb (Monopoly_Club_(Maygay)_[C01_v1-0_1024_250jp]_[c].gam)
m1mongam (Money_Game_(Maygay)_[C01_v1-0_1024_200jp]_[c].gam)
m1monmon (Money_Money_Money_(Maygay)_[C01_1024_15jp].gam)
m1monou (Monopoly_(Maygay)_[C01_1024_8jp].gam)
m1nhp (Noel's_House_Party_(Maygay)_[C02_1024_6jp].gam)
m1nudbnke (Nudge_Banker_(Maygay)_[C01_v1-0_1024_8jp].gam)
m1omega (Omega_(Maygay)_[C01_v1-0_800_4-80jp].gam)
m1onbusa (On_The_Buses_(Maygay)_[C01_v1-0_1024_10jp].gam)
m1przeeb (Prize_Eastenders_(Maygay)_[C01_1024_6jp].gam)
m1retpp (Return_Of_The_Pink_Panther_(Maygay)_[C02_v1-0_1024_6jp].gam)
m1search (Search_Light_(Maygay)_[C01_v1-01_800_6jp].gam)
m1sptlgtc (Spotlight_(Maygay)_[C03_1024_6jp].gam)
m1startr (Star_Trekking_(Mdm)_[C01_v2-10_1024_8jp].gam)
m1taknot (Take_Note_(Maygay)_[C01_800_4-80jp].gam)
m1thatlfc (That's_Life_(Maygay)_[C01_800_6jp].gam)
m1topstr (Top_Strike_(Maygay)_[C01_800_2-40jp].gam)
m1triviax (Trivial_Pursuit_(Maygay)_[C02_v1-52_1024_8jp].gam)
m1trtr (Trick_Or_Treat_(Global)_[C02_800_15jp].gam)
m1ttcash (Tick_Tock_Cash_(Empire)_[C01_800_5jp].gam)
m1wldzner (Wild_Zone_(Maygay)_[C01_v1-11_1024_6jp].gam)
m1wotwa (War_Of_The_Worlds_(Maygay)_[C01_1280_5jp].gam)

### CODE REVIEW

**Comment by mamehaze** [comment]
I would be inclined to shuffle the sets around so that the versions where there are layouts are the parent sets

**Comment by johnparker007** [comment]
Ok - I thought the parent sets were perhaps at some point chosen to be the 'main' set for some reason/criteria?

The converter reads whichever MFME ROM the MFME layout points at, then uses a modified MAME to identify that MFME ROM as part of a MAME set, then that's how the layout is named.

Or are you thinking that because someone has chosen that MFME ROM when they made the layout, that ROM is more likely to be representative of a 'good' example of the ROM revision, so a good candidate for the parent?

As an alternative, I could make these layouts have the name of the current parent set as they are allocated in the driver, so I'd change **m1albsqp.lay** to be **m1albsq.lay** etc., preserving the current allocation of parent/children in MAME.

Honestly, I got a big dump of MFME layouts, and a big dump of ROMs, and they sometimes don't match up, so I pick a ROM myself that is the correct filesize, that MAME recognises... so it just seems a bit bad for me to start rearranging the sets based on in some cases (5-10%) my whim! ;)

I could make it a feature of the Converter process to always derive the parent name for the layouts, even if it gets a child name from matching the MFME rom that is pointed at by the layout.

Alternatively I don't mind doing the parent/child shuffling, if you think it's a good course of action anyway, based on what the majority of the MFME layouts were pointing at when I matched them up.

Also, one other thing to consider is that some ROMs are hardcoded to £5 jackpot, 5p a go... or £15 jackpot, 20p a go etc...  So the cash values on the layout will match up to the identified ROM in ~90% of cases... but will be wrong on the others (in the much longer term, we could perhaps expand the layout format to support something dynamic for this, though it's very FME-specific)

All good with me either way, lemme know what you think's best, and I will get it sorted hopefully on Fri/Sat :)

**Comment by mamehaze** [comment]
for the M1A sets there really is no reasoning to the order AFAIK, most of them were batch added.

the reason I suggest layouts being paired with the parent sets is simply because the parent sets are the ones people are most likely to run, so having a layout associated with them means they're most likely to see the progress.

also yeah, since the existing emulators are using those sets, we at least know they're usable sets, with no major issues.

MAME is playing catch-up here, so even if in the end things get switched around again later, making the primary sets the ones which are most likely to end up working is going to help us in the short term.

I think in the end the fruit machines will need layouts where the graphics / text descriptions used depend on the set, as noted, often you get the same machines with different payouts etc.  For sets where you can select the payout (the 'Y' sets in MPU4 at least, where they depend on jackpot / stake keys) I guess the layouts will have to include all the variations, so that people can select the correct one for their configuration.

**Comment by johnparker007** [comment]
Currently in this commit, for the layouts I added, I added them to *all* sets for that game, so here for example:

GAMEL( 199?, m1calyps  ,0        ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Calypso (Maygay) (M1A/B) (set 1)",GAME_FLAGS, layout_m1calypsa)
GAMEL( 199?, m1calypsa ,m1calyps ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Calypso (Maygay) (M1A/B) (set 2)",GAME_FLAGS, layout_m1calypsa)
GAMEL( 199?, m1calypsb ,m1calyps ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Calypso (Maygay) (M1A/B) (set 3)",GAME_FLAGS, layout_m1calypsa)

...whichever set you run, you get the layout (even though the layout is for the ROM set 2).

I think that some of the games are generated, but some have been done by hand, as there are comments on the right, showing the ROM versions, and using the 'newest' as the parent set.  For example, I'd be changing the parent set here from 3.1 to 1.1 to match the layout:

ROM_START( m1cluecb )   ROM_REGION( 0x10000, "maincpu", ROMREGION_ERASE00  )    ROM_LOAD( "sc5-437", 0x0000, 0x010000, CRC(0282878c) SHA1(90624916699e5866678b02260e0b0502041f32bf) )   m1_cluecb_sound ROM_END_M1A_MCU //nhq 3.1
ROM_START( m1cluecbp )  ROM_REGION( 0x10000, "maincpu", ROMREGION_ERASE00  )    ROM_LOAD( "sc5-438", 0x0000, 0x010000, CRC(26f6d094) SHA1(31fa78db1a581c00b39d4f6f64d8f08786dec97a) )   m1_cluecb_sound     ROM_END_M1A_MCU //phq 3.1 (typo?)
ROM_START( m1cluecb2 )  ROM_REGION( 0x10000, "maincpu", ROMREGION_ERASE00  )    ROM_LOAD( "sc5-435", 0x0000, 0x010000, CRC(84095d36) SHA1(f86f7f25fa25eb2731d81a23aafaf5e4c8aa976b) )   m1_cluecb_sound ROM_END_M1A_MCU //nhq 2.1
ROM_START( m1cluecb2p ) ROM_REGION( 0x10000, "maincpu", ROMREGION_ERASE00  )    ROM_LOAD( "sc5-436", 0x0000, 0x010000, CRC(3b277a98) SHA1(cab3b277bec84056f6a97a87d97bbd86f80a1c8c) )   m1_cluecb_sound ROM_END_M1A_MCU //phq 2.1
ROM_START( m1cluecb1 )  ROM_REGION( 0x10000, "maincpu", ROMREGION_ERASE00  )    ROM_LOAD( "sc5-433", 0x0000, 0x010000, CRC(27254937) SHA1(b75f4a7e66f625c0db7d658f0427c8c1893a3d10) )   m1_cluecb_sound ROM_END_M1A_MCU //nhq 1.1
ROM_START( m1cluecb1p ) ROM_REGION( 0x10000, "maincpu", ROMREGION_ERASE00  )    ROM_LOAD( "sc5-434", 0x0000, 0x010000, CRC(6185ea69) SHA1(a20bccb86cfcd929908974500186e9ecf2cdc55b) )   m1_cluecb_sound ROM_END_M1A_MCU //phq 1.1

GAMEL( 1993, m1cluecb    ,0          ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v3.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
GAMEL( 1993, m1cluecbp   ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v3.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
GAMEL( 1993, m1cluecb2   ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v2.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
GAMEL( 1993, m1cluecb2p  ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v2.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
GAMEL( 1993, m1cluecb1   ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v1.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
GAMEL( 1993, m1cluecb1p  ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v1.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)

So - if I'm definitely reorganising the parent sets by layout, how does that work - as then everyone else's ROMs will be invalid (including mine, so I'd have to manually swap their contents around to match the CRCs)?  Or is there another tool over at MAME HQ that somehow recompiles the official ROM sets as zips, based on the definitions in here?  

Also the parent set usually contains sound ROMs and an MCU rom... can they happily live in a child set, or do they need to be transferred?

I have a strong feeling I'm completely misunderstanding the process by which I swap a child set and a parent set, and it's hopefully less involved lol - otherwise I'm going to have to write some kind of tool myself to deal with all this :)

I think perhaps at the weekend, I should try swapping a single set around (so a child becomes the parent), and commit for review.  Seems like I'd have to change the contents of the ROM zipfiles?  Or am I completely not getting it lol ;)

**Comment by johnparker007** [comment]
Oh god - ok I think I see haha - so do you mean I just change from this:

> GAMEL( 1993, m1cluecb    ,0          ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v3.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecbp   ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v3.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb2   ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v2.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb2p  ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v2.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb1   ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v1.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb1p  ,m1cluecb   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v1.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)

to this:

> GAMEL( 1993, m1cluecb    ,m1cluecb1   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v3.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecbp   ,m1cluecb1   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v3.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb2   ,m1cluecb1   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v2.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb2p  ,m1cluecb1   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v2.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb1   ,0			  ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v1.1 (M1A/B)",GAME_FLAGS,layout_m1cluecb1)
> GAMEL( 1993, m1cluecb1p  ,m1cluecb1   ,maygay_m1,maygay_m1, maygay1b_state,m1, ROT0, "Maygay", "Cluedo Club (Maygay) v1.1 (Protocol) (M1A/B)",GAME_FLAGS,layout_m1cluecb1)


... and that takes care of everything? :)

**Comment by mamehaze** [comment]
not exactly

if the layout is intended for 'm1cluecb1 ' then I would rename (both romset and GAME definition of 'm1cluecb1' to 'm1cluecb' and rename the existing 'm1cluecb' to something else.

either way, don't let it bother you, if I feel it needs taking care of I'll do it myself  :)

**Comment by johnparker007** [comment]
Ok, I'm cool with that, as I'm still a bit mystified how I don't end up breaking everyone else's ROM set, I'm guessing perhaps there's a server that rebuilds the named ROM sets from the driver definitions for each new MAME version or some kind of magic lol :)

Right I will keep focused now mainly on MAME Internal layouts... so do you want me to continue add them to drivers using the GAMEL macro and ensure all the alternative romsets per game also point at them too, like I've done in this Maygay one?

And one last thing, as I want to check I did all this ok - is this commit good to go, and the Travis builder itself has gone wrong, or is something amiss with my commit?

$ if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y; fi
before_install.2
0.00s$ if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:beineri/opt-qt551 -y; fi
before_install.3
0.00s$ if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get update -qq; fi
before_install.4
0.00s$ if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get install -y --force-yes libsdl2-dev libsdl2-ttf-dev libasound2-dev qt55base qt55quickcontrols qt55declarative qt55tools qt55svg; fi
before_install.5
0.00s$ if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then source /opt/qt55/bin/qt55-env.sh; fi
133.00s$ if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew update; fi
error: RPC failed; result=35, HTTP code = 0
fatal: The remote end hung up unexpectedly
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
The command "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew update; fi" failed and exited with 1 during .
Your build has been stopped.

**Comment by mamehaze** [comment]
yeah, there are various sites that offer complete MAME set torrents for every release, not run by us, obviously, but they exist, so even when we rearrange things people catch up rather quickly.

if you're not rearranging any sets you're not breaking anything tho ;-)

some of the 'handheld electronic game' emulation we do actually includes the 'deluxe' layouts in the romsets with SVG graphics (which can be generated in your favourite SVG editors) however that style of artwork really only supports simple 'on/off' graphics, not something like the fruit machine reels.

**Comment by mamehaze** [comment]
the travis failure looks unrelated to the changes, looks like it couldn't pull from Github rather than couldn't compile.

fatal: The remote end hung up unexpectedly
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

**Comment by johnparker007** [comment]
> some of the 'handheld electronic game' emulation we do actually includes the 'deluxe' layouts in the romsets with SVG graphics (which can be generated in your favourite SVG editors) however that style of artwork really only supports simple 'on/off' graphics, not something like the fruit machine reels.

Yeah, I was hoping long term if we can get tons of FME compatibillity in MAME, to add more to the converter process and the mame layout renderer, so it could 'illuminate' with a shader... so you just have a single main image that is a bright fruit machine as cleaned up and hig res that we have.  Then the shader darkens it all, but allows the light through where the bulbs are... would allow for a more compact lamping system, overlapping lamp effects, be a bit more 3d-friendly (no risk of z-fighting, better scaling up), user can tune bulb brightness, can add nice effects like true filament decay, flicker from the mains/matrix... Guitar has already achieved a lot of this in Amber2.  Perhaps then we'd be ok to have that one single large "on image", plus the unique reel symbols stored in the parent ROM set?  If MAME played the full "deluxe" layouts, straight out of the box, that'd be pretty cool  :)  

...but I totally understand all that is all scope creep, since a ROM isn't really a ROM once it's got a backglass image and some reel images and a layout XML in there too ;) 

I will keep focused on improving/adding Internal layouts, plus I have more to do for James with the MPU4 configs (and layouts).

**Comment by james-wallace-ghub** [comment]
Just a point RE: Layouts and parents, I've noticed that some of the things that were used to make layouts weren't the parents, just because the people designing them wouldn't care about the latest software. When I've been building the converted layouts into configurations, I've been applying the configurations to all sets rather than just the parent, but of course this is by ignoring the percentage keys and other inputs. It may be worth a discussion as to how we document this, as end users could easily get code running that doesn't match the layouts by using different settings etc so there may be a need to do something with views etc.

**Comment by mamehaze** [comment]
I think that might eventually happen (even if it seems weird storing non-rom data in the romsets, things like the laserdiscs are 'analog captures' anyway.  That's some time away tho.  In a more short-term view it might be possible to ship some 'generic' symbols with MAME, for the classic fruits etc. just nothing that is too specific to one game.

Either way, for now the layout system we have provides a way of at least making things functional, which is a lot better than 'unusable'

In the end it will come down to momentum, and establishing a foothold.  Right now MAME has little presence in terms of Fruit Machine emulation, but, if we get the majority of machines running (especially it some of those don't run elsewhere) and it becomes a viable choice, then there will be more demand / interest in improving it, the layouts that are being created now will be useful fallbacks at worst if a newer system for representing these in 3D is created for example.

**Comment by james-wallace-ghub** [comment]
My hope is that, with the config data, we can put the basic classics in MAME (albeit with some of them using the wrong stake and prize info), with the image containing files or SVGs (still don't grasp how those work) used to flesh them out.

**Comment by james-wallace-ghub** [comment]
If everyone's happy with this, I'll merge it in tonight, just want to check the ROM names are OK.
I did try to sort some of the M1 sets a while back using version IDs, but they don't necessarily coincide with age as different build paths have reset the version ID in some cases (so later titles in a series reuse the earlier numbers). With fewer titles though, should be easier to sort through.

**Comment by mamehaze** [comment]
btw there seems to be a problem with some (all?) of the layouts
they reference "lamp_134_1_border" which doesn't exist, so you get
Error in XML string: Unable to find layout element lamp_134_1_border

tested with m1bargn and m1cluedo at least

**Comment by mamehaze** [comment]
actually they reference quite a few elements that don't exist..
lamp_134_1
and
lamp_130_1_border
probably others...

if there are XML errors like this the layouts don't display

**Comment by mamehaze** [comment]
ok, not all, but a couple more than the ones i initially tested..

does look like our lamping isn't quite right based on the squares that light up in deluxe monopoly tho

**Comment by mamehaze** [comment]
well I've fixed the lamping code, I'll do a pull request for that shortly.

**Comment by mamehaze** [comment]
https://github.com/mamedev/mame/pull/1267
that should take care of the lamping for both ports, with cleaner code, at least m1dxmono51o looks better this way

**Comment by johnparker007** [comment]
> actually they reference quite a few elements that don't exist..
> lamp_134_1
> and
> lamp_130_1_border
> probably others...

I will check into this next chance I get, hopefully this weekend - good news on the lamps :)

**Comment by mamehaze** [comment]
while the game lamps look pretty good in general now, the reel lamps don't seem quite right for a number of the games, I suspect that's a mapping problem with the converter program.

m1coro21n throws a slightly different error, which I'm guessing is the converter too, or an error in the original layout?
Error in XML string: Illegal bounds value in XML: (577.000000-575.000000)-(142.000000-141.000000)

btw, in MAME layouts support multiple views, would it be possible for your converter to generate a 2nd view, closer to the 'grid' layout MAME has now, but colour-coded based on information from the layout.

what I mean is that if a lamp in the grid has been referenced bu the layout being converted it could have a dark green (off) / green (on) colour scheme, if it's been referenced and is being used for a reel it could have a dark blue / blue colour scheme, and if it hasn't been referenced at all it could have a dark grey / white colour scheme.

that way you could easily bring up the debug view to make sure no unreferenced lamps are being used.

**Comment by johnparker007** [comment]
> while the game lamps look pretty good in general now, the reel lamps don't seem quite right for a number of the games, I suspect that's a mapping problem with the converter program.

Yes it is very possible it's a mapping issue from my side, I am aware that some MPU4 reel lamps are mapped wrong, and I know how to fix those ones.  The M1A/B ones will require further investigation, to see if MFME has any code to move them (like it does with MPU4).

> m1coro21n throws a slightly different error, which I'm guessing is the converter too, or an error in the original layout?
> Error in XML string: Illegal bounds value in XML: (577.000000-575.000000)-(142.000000-141.000000)

I got some free time today, and have got James set up with more MPU4 stuff - so I'll look at these M1A/B bugs and this new lamp/switch Debug view next... I'll update the layouts on git once they're sorted with the new stuff :)

**Comment by johnparker007** [comment]
I have committed the layouts, I checked each one, all 56 initialise now :)

It was a very recent Converter bug (it honestly used to work pretty reliably!), as I'd added a special lamp support for someone who is currently making a DX Deal Or No Deal layout, and I forgot to update the related areas for the 'no graphics' mode which makes these Internal layouts.  The bug with m1coro21n was a new one I'd not seen before.

I will get the Debug view implemented as my next task.  I was thinking it'd be useful to also have a complete input matrix on the screen as well as this enhanced lamp matrix?  So you can click on a cell in the input matrix and it'll press that button... I could also do the colouring scheme, so the buttons that are used by the layout are a different colour to the unused buttons (though all 256 inputtag/inputmask combination would be functional).

**Comment by mamehaze** [comment]
yeah it would probably help to have a grid of buttons for the input matrix too in the debug layout

really anything like that you can think of that would be useful would be good to have if you can implement it :)

**Comment by johnparker007** [comment]
Well that took longer than I thought it would, probably due to a big hangover lol ;)  I'll not submit updated layouts yet, as I have more info to add to the reels, but it's already looking like it'll be quite handy :)

debugviewv1

On the left is the lamp matrix, the colours mean:
- Blue is a reel lamp referenced in the layout
- Red is a segment-driving lamp in the layout
- Green is a standard lamp in the layout
- White is a lamp not referenced in the layout

On the bottom-right is the input matrix, the colours mean:
- Yellow is an input referenced in the layout
- White is an input not referenced in the layout

The 'buttons' can be clicked, and will send the relevant inputtag/inputmask for that tech to MAME.

The area at the top-right is for the reels and can accommodate up to 10x reels for those crazy machines that have that lots.

There will be some tweaking required per tech, this is just developed for Maygay for the moment, but it's not much work for it to support the other techs and their unique elements (Dot Matrix Displays etc).

Will update the Maygay layout set when I've finished it, hopefully tomorrow :)

**Comment by johnparker007** [comment]
Ok have got the new Debug View in - it's very handy, glad you prompted me and suggested colour-coding etc, I'd been thinking of doing something very basic just so I could click buttons, but getting all the extra colour-coding stuff, and flashing links lamps on the input matrix makes it really useful :)

I've fixed the inputs, it was a bug, once I could see clearly in the debug view it was a straightforward fix :)

The layouts have been updated with the Debug View, they're here:
[https://github.com/mamedev/mame/pull/1286](url)

...and here's a screenshot of the Debug View as it stands:
https://dl.dropboxusercontent.com/u/15679918/converter/screenshots/maygay/HotPotsMameInternal-DebugViewV2.png

I'll get it into the new techs as I batch them up and commit them :)

**Pull request merged**
