### PR TITLE
softlists - Fix some validation issues

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by Tafoid** [comment]
Please note that 8 letter setname restrictions on parents is no longer a restriction and, given the situation, you can use more letters.  Also, mixed case is allowed for rom labels... making most of these changes unneeded.

**Comment by FakeShemp** [comment]
All right. Yeah, that would probably make all of them unnecessary. My build threw validation errors on these, only reason I fixed. Sorry if it is unneeded. I'll remember from now.

Is the >8-letter set name restriction a new thing? Can't remember that being the case before at all.

Is small case rom labels still recommended or are you moving toward always using mixed case?

**Comment by Tafoid** [comment]
Normal -validate for me on the current GIT copy of the HASH folder (with fresh binary) doesn't show any of these you've changed.  What are you using to validate your copies of softlists?

The 8 letter change is a pretty recent one https://github.com/mamedev/mame/commit/3291684c2baf8d43c7300e0a2f7fc42b6ee8bcff and while we are allowed to use up to 16 characters for parent names (like the clones have been for years), we only need to use it when the need arises and the extra characters will help avoid confusion with other similar setnames.

The lowercase filenames for rom labels was historically for consistency but we've recently been trying to better represent actual labels by allowing uppercase where they appear on PCBs, Rom Chips, etc.  In most instances, actually, the labels on the actual chips are uppercase.  The names of a CD or cartridge blob of data doesn't matter so much for case.

**Comment by FakeShemp** [comment]
I thought I was using latest git, but an old build was throwing me off. I'm sorry :bowing_woman: 

With _actual_ latest git, everything checks out fine as it should.

Thank you very much for the info. I'm sure to take it to heart.

**Comment by happppp** [comment]
Uppercase letters in rom/image swlist filenames is a validation error? We
should be more lenient, we already allow this on MAME's internal romdefs.

On Sun, Oct 23, 2016 at 2:18 PM, Rebecca Wallander <notifications@github.com

**Comment by FakeShemp** [comment]
Yeah, it is allowed now, but apparently wasn't before. I'm sorry for any confusion.

**Pull request closed without merging**
