### PR TITLE
frontend/mame/infoxml.cpp: output more info about input ports' fields

### PR DESCRIPTION
**Pull request by 6t8k**
Having this readily accessible can be useful e.g. when analyzing/converting INP files using an [external tool](https://github.com/6t8k/inp2json).

### CODE REVIEW

**Comment by cuavas** [comment]
I understand the motivation for this, but I’m still not convinced putting this in the `-listxml` output is a great idea at the moment.

* It would cause the already large size of the `-listxml` output to increase phenomenally, which is problematic if you want to do any kind of DOM manipulation.
* It would probably need better filtering to not show custom and special input fields.
* Exposing numeric field types is unhelpfully leaking an implementation detail.  They’d need to be converted to their token form.
* The player number isn’t relevant to all control types, and shouldn’t be included where it doesn’t make sense.
* The `specific_name` can be null – it’s only set when the system overrides the standard field name.  Presenting the proper display name for a field is more complicated than that.  This is further complicated by the fact that default field names are localisable (we wouldn’t want `-listxml` output to be locale-sensitive, but a hypothetical configuration file editor would likely want to be able to display localised names).
* The field metadata can’t be treated as static as long as people insist on doing things like [this](https://github.com/mamedev/mame/blob/c0055a0e19f548d21deae6dd6f489f8b7c2d893a/src/devices/bus/vcs_ctrl/paddles.cpp#L52).

If we *do* decide to move towards putting enough information in the `-listxml` output to support external configuration editors, it needs more thought put into the design than this.

**Comment by ajrhacker** [comment]
This also doesn't account for `PORT_CONDITION` at all, even though some games use that for non-DSW inputs (e.g. jchan).

**Comment by cuavas** [comment]
To get past your immediate issue of wanting to dump inputs to migrate input recordings, could you use a Lua script instead?  You could write a Lua autoboot script or plugin to list inputs in any format that suits your purposes.

**Comment by 6t8k** [comment]
Thanks for the feedback! Looks like it was a bit premature to propose this.

> - It would probably need better filtering to not show custom and special input fields.
> - Exposing numeric field types is unhelpfully leaking an implementation detail. They’d need to be converted to their token form.
> - The player number isn’t relevant to all control types, and shouldn’t be included where it doesn’t make sense.
> - The `specific_name` can be null [...]

Improved on these aspects for my own purposes. I initially tried accessing `ioport_field::name()`, but that currently requires the respective machine to be running (else it segfaults).

> This also doesn't account for `PORT_CONDITION` at all, even though some games use that for non-DSW inputs (e.g. jchan).

Evaluating the conditions currently requires the respective machine to be running, so I didn't follow through with this.

I think the best path forward from here is to close this PR, as I currently don't have the resources to devise a proper implementation, and you'll likely have a better idea on how to go about it, not least because some larger decisions seem to be required.

---

> To get past your immediate issue of wanting to dump inputs to migrate input recordings, could you use a Lua script instead? You could write a Lua autoboot script or plugin to list inputs in any format that suits your purposes.

It would be nice if I could use the Lua engine for this. I examined the [class reference](https://docs.mamedev.org/techspecs/luareference.html#luareference) and played around a bit, but it seems only the currently running machine is accessible, which makes this not really practical, unfortunately. :[ Perhaps the interface could be amended to allow access to at least part of what I'd need.

**Comment by ajrhacker** [comment]
> Evaluating the conditions currently requires the respective machine to be running, so I didn't follow through with this.

There's an existing `output_ioport_condition` function that prints XML representations of unevaluated conditions.

**Comment by 6t8k** [comment]
> There's an existing output_ioport_condition function that prints XML representations of unevaluated conditions.

Now I understand - looks like it wouldn't be much work to furnish the input fields with this in a future supplement of the XML output then. For `inp2json` it doesn't seem needed, since MAME takes the conditions into account when writing INP files.

**Pull request closed without merging**
