### PR TITLE
Spectrum betadisk stuff

### PR DESCRIPTION
**Pull request by DavidHaywood**
renamed the beta128 support from beta.cpp to beta128.cpp for now
added basic devices for the older beta models, which seem to fall into 3 basic groups
1. Handmade version using V2 ROM and FD1771 controller
2. Production version using V3 ROM and FD1793 controller
3. 'Plus' version with more refined features, Magic Button and V4 ROM (closest to the beta128)

there are a number of hardware clones of these for different systems, which are not compatible, and will eventually need adding as their own devices.

note, these new devices are NOT working, as the disable mechanism for the ROM is not clear to me, and the remaining mappings not confirmed.  It does not appear to rely on executing code from RAM to disable like the Beta128, despite some sites claiming so?

it might be possible, later, to reintegrate the beta128 as a further extension of the betaplus, but until the remaining details of these original devices is worked out it's cleaner to keep them apart.

also added some notes about suspicious behavior with even the beta128 hookup that points at something potentially being wrong (the emulation of the pentagon machines with integrated support don't suffer from the same issue)

### CODE REVIEW

**Comment by p1pkin** [comment]
based on older BDI scematics I have, it seems the logic is like:
- memory access 0x3CXX (any type of access: code or data, read or write) -> temporary enable BDI ROM (**NOT** permanent latch/switch like in beta128)
- memory access <0x4000 area and BDI ROM_latch==true -> enable BDI ROM
- IO write to port 0bxxxxxx00 -> D7 master_latch, 0=enable, 1=disable

while master_latch is enabled access no regular Spectrum IO is blocked (output /IORQ forced to 1) but enabled BDI ports:
- IO write to port 0b1xxxx111 -> D7 BDI ROM_latch (0=enable, 1=disble), D6 - FDC DDEN, D4 - SIDE, D3 - FDC HLT, D2 - FDC /MR (reset), D0-1 - floppy drive select.
- IO read port 0b1xxxx111 <- D7 - FDC INTRQ, D6 - FDC DRQ
- IO read/write ports 0b0YYxx111 - access FDC ports YY
it is same as beta128, except for new BDI ROM_latch bit

**Comment by DavidHaywood** [comment]
yeah, definitely more complex than the 128 then, no wonder I couldn't guess it.  I'll see if implementing it based on that information gives something functional.

I do wonder why some features of the 128 malfunction in MAME or work better with the clone interface too mind you.

**Comment by p1pkin** [comment]
not sure if it really complex, basically it is the same as beta128, except for:
- 3Cxx area (not 3Dxx) always read as BDI ROM.
- rest of ROM reads depends on BDI port 0xFF bit 7 (0-BDI ROM, 1-Spectrum ROM)
- there is additional port 0xFC, bit7 == 0 enable BDI ports access.

**Comment by DavidHaywood** [comment]
well complex in an implementation sense, I'll have to rework the expansion bus so there are callbacks for 'opcode fetch' and 'data fetch' as right now data fetches won't even hit the expansion bus (which is clearly incorrect, as all should hit them, with the expansion hardware deciding if to act based on the m1 line)

but yeah, I'll find a workable solution.

**Comment by p1pkin** [comment]
ah, ok, I see.
I suppose 0xFC port may be problematic as well, as it "broadcasts" to mobo's port 0xFE
tbh, I dont think Nigel's implementation of Beta128 was really working. at some point I've played with Spectrum128+beta128 and it hangs/reset if you do TR-DOS mode enter-exit-enter-exit, looks like there is some bugs in BDI enable/disable logic.

as of "why some features of the 128 malfunction in MAME or work better with the clone FD interface" - currently I'm tend to think the docs it lying and both FD1793 and KR1818VG93 uses same "forced interrupt" command logic
https://github.com/mamedev/mame/blob/e157856b783520fd51f4704f894c4244e5222375/src/devices/machine/wd_fdc.cpp#L953
e.g. nonsticky_immint=true code path (btw, all Spectrum+beta128 emulators uses this logic). at least, I was told "CAT then CAT again" works fine too on real ZX-Spectrum + beta128 PCBs with FD1793, however I'd like it to be verified by some trusteable persons.

technically, all the problems because of TR-DOS's bug, very bad bug, it send various crap to FDC command register, including format or data write commands, but luckily no further data supplied to FDC, so commands aborts due to timeout and doesn't destroy floppy disc contents (if use modern wd_fdc, but it was killing floppies when was used legacy wd_fdc).

**Pull request merged**
