### PR TITLE
Add source for the minified modernizr.min.js file.

### PR DESCRIPTION
**Pull request by jmallach**
The current MAME source includes a generated minified version of modernizr.js. It would be optimal and in line with the spirit of the GPL to provide its accompanying source at the very least for reference purposes.

### CODE REVIEW

**Comment by Lord-Nightmare** [comment]
I was under the impression that modernizr.js was under the MIT license, not GPL...
https://github.com/Modernizr/Modernizr

**Comment by jmallach** [comment]
@Lord-Nightmare, it is, it is. That's why I talk about the spirit and not enforcement or anything. It's just a trivial patch, and quite nice to have: the min.js versions are unusable to the naked eye, and having the source for reference and to know how/where it got generated from is good at essentially the cost of 50KB.

**Comment by mnaberez** [comment]
The [modernizer.min.js file](https://github.com/mamedev/mame/blob/d7a9eeb64ff8f2388acb975968b32e2c3735dde2/docs/themes/sphinx_rtd_theme/static/js/modernizr.min.js) discussed here is part of the package [`sphinx_rtd_theme`](https://github.com/snide/sphinx_rtd_theme).  As far as I know, we are including `sphinx_rtd_theme` without changes or additions.  In the past, we have generally avoided changing things in third party dependencies unless it is necessary for the build.  I suggest submitting this patch to `sphinx_rtd_theme` directly, and if they include it, we would pull it in.

**Comment by jmallach** [comment]
@mnaberez I will try to get that merged upstream first then. Thanks for the comment!

**Comment by jmallach** [comment]
For completeness, this pull request was also sent upstream: https://github.com/snide/sphinx_rtd_theme/pull/332

**Comment by rb6502** [comment]
@jmallach It looks like the upstream merge was waiting on you to answer some things, could you please address those so we can get this taken care of?

**Comment by rb6502** [comment]
The upstream PR was never applied, so closing this version too.

**Pull request closed without merging**
