### PR TITLE
Fixed GCC 12.2.0 32bit compile of astrcorp.cpp

### PR DESCRIPTION
**Pull request by MASHinfo**
"for (u32 i = 1; i < size; i += 2)"  <<< This never reaches size!

### CODE REVIEW

**Comment by happppp** [comment]
"This never reaches size!"
The comparison is <, not !=. Sounds like a compiler bug, there's nothing wrong with the code.

**Comment by MASHinfo** [comment]
i start with i=1 and if for example size = 100 and i =99, then is i += 2 = 101.

**Comment by MASHinfo** [comment]
You can also see it as a workaround!

**Comment by happppp** [comment]
Ah it's this one? https://github.com/mamedev/mame/issues/10399
So, compile with NOWERROR=1

**Comment by MASHinfo** [comment]
It's not a compiler bug. It shows that ' i ' will be bigger than 'size' and it
will have problems with the next line!

>>  tmp[i] = bitswap<8>(rom[i], 6, 7, 5, 0, 4, 1, 3, 2);

**Comment by happppp** [comment]
Ok, then let me remind you that the "<" means "smaller than", it's a generic maths symbol.

"i start with i=1 and if for example size = 100 and i =99, then is i += 2 = 101."
So, it reaches 101, checks if 101 < 100. No it's not, then exit the loop.

**Comment by MASHinfo** [comment]
Ok. I will compile a 64bit version and log the value ' i ' and show you that the 64bit
version also has an i-value over 'size'. Don't close this report. Please wait!

**Comment by MASHinfo** [comment]
I have log 'i' and 'i' and 'dest' for both MAME versions (32bit/64bit) with
if(i > size - 10) logerror("i = %d\n", i);
if(i > size - 10) logerror("j = %d and dest = %d\n", i, dest);

All values are correct. The compiler must have a bug...
Here is the result:

[:] i = 131063
[:] i = 131065
[:] i = 131067
[:] i = 131069
[:] i = 131071
[:] j = 131063 and dest = 131063
[:] j = 131064 and dest = 131064
[:] j = 131065 and dest = 131065
[:] j = 131066 and dest = 131066
[:] j = 131067 and dest = 131067
[:] j = 131068 and dest = 131068
[:] j = 131069 and dest = 131069
[:] j = 131070 and dest = 131070
[:] j = 131071 and dest = 131071
Soft reset
[:maincpu] ':maincpu' (0008C0): unmapped program memory read from A10000 & 00FF
[:maincpu] ':maincpu' (0008DA): unmapped program memory read from C00004 & 00FF
[:maincpu] ':maincpu' (0008E4): unmapped program memory write to C00004 = 8000 & FFFF
[:maincpu] ':maincpu' (0008EC): unmapped program memory write to C00004 = 8100 & FFFF
[:maincpu] ':maincpu' (002188): unmapped program memory write to A11200 = 0100 & FFFF
[:maincpu] ':maincpu' (002154): unmapped program memory write to A11100 = 0100 & FFFF
[:maincpu] ':maincpu' (00215C): unmapped program memory read from A11100 & FF00
[:maincpu] ':maincpu' (0021B4): unmapped program memory write to A0101A = 0101 & 00FF
[:maincpu] ':maincpu' (0021BC): unmapped program memory write to A11100 = 0000 & FFFF
[:maincpu] ':maincpu' (002168): unmapped program memory write to A11200 = 0000 & FFFF
[:maincpu] ':maincpu' (00217A): unmapped program memory write to A11200 = 0100 & FFFF
[:maincpu] ':maincpu' (002154): unmapped program memory write to A11100 = 0100 & FFFF
[:maincpu] ':maincpu' (00215C): unmapped program memory read from A11100 & FF00
[:maincpu] ':maincpu' (002276): unmapped program memory write to A0101C = 0000 & FF00
[:maincpu] ':maincpu' (00227C): unmapped program memory write to A01018 = 0000 & FF00
[:maincpu] ':maincpu' (002282): unmapped program memory write to A01018 = 0000 & 00FF
[:maincpu] ':maincpu' (002288): unmapped program memory write to A0101A = 0000 & FF00
[:maincpu] ':maincpu' (00228E): unmapped program memory write to A0101A = 0000 & 00FF
[:maincpu] ':maincpu' (002296): unmapped program memory write to A11100 = 0000 & FFFF
[:maincpu] ':maincpu' (002154): unmapped program memory write to A11100 = 0100 & FFFF
[:maincpu] ':maincpu' (00215C): unmapped program memory read from A11100 & FF00
[:maincpu] ':maincpu' (0022C2): unmapped program memory write to A11100 = 0000 & FFFF

-

**Comment by MASHinfo** [comment]
Another thing is that when I am place somewhere in the magibomb init function
a logerror for size (logerror("size = %d\n", size);), the compiler can
compile astrcorp.cpp!.cpp

**Comment by MASHinfo** [comment]
Another solution:
I looked at other drivers and all have mostly taken int for the rom size. If i replace u32 with int:
const u32 size = memregion("maincpu")->bytes();
to
const int size = memregion("maincpu")->bytes();

...the compile can compile astrcorp.cpp and magibomb works! So can this be used in MAME as a workaround.
Using NOWERROR=1 to compile MAME only for one file that the GCC 12.2.0 can't compile would not
be suitable for debugging MAME.

**Comment by cuavas** [comment]
You can never end up with a ROM size where the loop won’t work.  You can hand-simulate it up to the largest possible even and odd sizes (0xfffffffe and 0xffffffff) and the loop bounding condition will be correct in both cases.  Take up the issue with the GCC maintainers.  It isn’t the first time we’ve had spurious static bounds check bugs in GCC for 32-bit x86.

**Pull request closed without merging**
