### PR TITLE
Pick low-hanging fruit from Coverity Scan results, basket 2.

### PR DESCRIPTION
**Pull request by shattered**

### CODE REVIEW

**Comment by happppp** [comment]
The only fix is the one in nubus, right? The others look like (hacky)
workarounds to suppress coverity warnings, we really don't have to 'fix'
everything it suggests.

**Comment by shattered** [comment]
All of that code (except maybe apexc) deals with input from the user (floppy images) or 3rd party software -- makes sense to protect against garbage input, I think

**Comment by happppp** [comment]
Take raiden2 for example:

AM_RANGE(0x0020, 0x002b) AM_WRITE(layer_scroll_w)

offset/2 is 0,1,or 2.
If you want to guard against that, IMHO your fix is ugly. If this is
necessary, I'd put assert(offset <= 6); on top instead.
Or hey, if you want to go really overboard, put an assert(offset < limit)
on each and every addressmap read/write function that accesses an array...
:P

**Comment by shattered** [comment]
I see, this is Zen and art of of MAME maintenance.   Forgive me, O master, for I am not worthy.

**Comment by happppp** [comment]
Don't want to discuss further? Fine whatever :)
If you have more fixes like the one in basket 1, keep them coming.

**Comment by cuavas** [comment]
@happppp is right, a lot of these things are or should be impossible because out-of-range values will be caught before you get there.  Assertions are better than checks in these cases.

Also, the dynamic casts in the image device code shouldn't ignore an object that can't be cast to the desired class - it should blow up in your face because it means the developer screwed up.  Silently skipping over the code if the dynamic cast fails will mask worse issues.

**Comment by rb6502** [comment]
If I may beat the raiden2 horse again, it's possible to get a useful effect in a natural-looking way:
	switch(offset/2) {
	case 0: tm = background_layer; break;
	case 1: tm = midground_layer; break;
	case 2: tm = foreground_layer; break;
        default: assert(0);
	}

I don't consider the fact that something is currently being called from an AM_RANGE that precludes failure to be sufficient, because you never know when someone is going to revise the driver or try and copy/paste parts of it to try and make related hardware work.  Unlike the proposed change, the default with the assert incurs no run-time penalty in the non-failure case yet provides absolute protection.

**Comment by happppp** [comment]
It accesses scrollvals[6] before that, so the assert needs to be on the top.
But again, then you have to ask yourself, what's so special about raiden2?
And why don't we put asserts on each non-AM_SHARE array access?

**Comment by rb6502** [comment]
Ok, so move the switch before the first access to scrollvals.  Still no real damage to the code.

Nothing is special about raiden2, aside from a certain reputation for being crashy.  If we're serious about safe programming, we *are* going to add asserts

**Comment by happppp** [comment]
Sure :)
Not that it matters for optimization though: assert is only active in DEBUG
builds iirc?

**Pull request closed without merging**
