### PR TITLE
de_3.cpp: New clones marked as NOT_WORKING, added CPU and display version on games descriptions, and fixed some games metadata

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
You’re mixing “Spain” (region) with “Dutch” (language).  Does this inconsistency exist in the way they licensed/distributed the machines?  There was already some inconsistency with “France”, and “Canada” for some games, but “French” for WWF Royal Rumble.

**Comment by clawgrip** [comment]
Yes, thanks. I'm using the String from the program ROM, and there's little consistency on these strings, should I try to normalize it?
Also, on the Spanish versions there's no specific program ROM (so no String to copy), just a different display ROM marked either as "S" (Spanish) or "L" (for Latin American Spanish spoken players). How should I label them (currently, all of them are labeled as "Spain").

Thanks again!

**Comment by cuavas** [comment]
If the string comes from the ROM, don't change it. I'd just leave the display ROM string as-is with the letter and not add "Spain". Just use what's there when possible.

**Comment by clawgrip** [comment]
Mmmm... But all the Spanish ones are "USA" program ROM and "L" or "S" display ROM.
For instance:

lah_108s: USA CPU 1.08. DISPLAY VERSION L1.04. Currently labeled "Last Action Hero (1.08 Spain, display L1.04)"
rab_103s: USA CPU 1.03. DISPLAY VERSION S1.03. Currently labeled "Adventures of Rocky and Bullwinkle and Friends (1.03 Spain, display S1.03)"

What would be the right labels for these examples?

Thanks!

**Comment by cuavas** [comment]
Just use the program and display strings as-is. Right now it's implying there's a different program, which there isn't.

**Comment by clawgrip** [comment]
Changed, thanks a lot!
I've also added a loose display ROM for "Last Action Hero" I've been sent. I've requested a full dump, but I don't count with it.

**Pull request merged**
