### PR TITLE
Fix typos throughout the codebase

### PR DESCRIPTION
**Pull request by jmallach**
This is a collection of commits to fix random typos throughout MAME's codebase.

I've done a commit per typo to make it easier for MAME admins to reject any of these that they find questionable or problematic.

### CODE REVIEW

**Comment by cracyc** [comment]
Assistent is a proper transliteration of the cyrillic [http://www.leningrad.su/museum/show_calc.php?n=573](http://www.leningrad.su/museum/show_calc.php?n=573).

**Comment by jmallach** [comment]
I knew I was risking a bit too much with that one in particular. :) Can a pull request leave out a commit in particular, or do I need to do the reversion in my branch?

**Comment by cuavas** [comment]
It's good for the most part, but there are some problems.
* You've attempted to correct "assistent" in titles which is actually the feminine of "assistant" as well as a legitimate word in other Germanic languages. I don't think this change is correct.
* "Softwares" is used as shorthand for "software list entries" or similar in various places. Just changing it to "software" doesn't read correctly.
* "standart" is a legitimate word in a number of European languages. Are you sure it should be "corrected"?

**Comment by jmallach** [comment]
Hi @cuavas,

I humbly disagree wrt "standart" and "assistent".

http://www.oxforddictionaries.com/spellcheck/english/?q=assistent
http://www.oxforddictionaries.com/spellcheck/english/?q=standart

Both are common misspellings as far as I can tell, and as far as all online dictionaries I have just queried confirm. However, "Assistent" in MAME's occurrence is a product name and that one in particular will need to be reverted.

Regarding the "softwares" commit, and as the commit message says, "software" is not countable, but indeed there are places where it might look a bit awkward (a translatable string similar to "10/25 softwares". I suggest we change that to software packages or software items or whatever, if we want to avoid a spelling mistake. The rest of the occurrences read ok to me after changing them to just "software".

Thanks!

**Comment by jmallach** [comment]
I have force pushed the deletion of the "assistent" commit.

**Comment by cuavas** [comment]
Yes, "assistent" is archaic usage and not considered standard in modern English anywhere.  However that doesn't stop people potentially using it in software titles for "artistic" reasons.  "Assistent" is also a legitimate word in Dutch, Danish, French, and other languages, so "correcting" it in software titles is more likely to be the wrong decision than not.

The three remaining changes I take issue with are:
* src/emu/ui/datfile.cpp:139 could be addressed by changing to "software list entries", rather than "software"
* src/emu/ui/selsoft.cpp:681 reads incorrectly after change, and it affects translations 
* src/mame/drivers/primo.cpp:361 "Standart" could very well be the correct transliteration from Hungarian - can you show that it's really an English misspelling?

**Comment by ajrhacker** [comment]
"Standart" is not the common Hungarian spelling of "standard"; it's not even the less common spelling (which is "sztandard").

**Comment by cuavas** [comment]
Look, there are plenty of software titles with intentional misspellings.  Can you show a source giving an official name for this BIOS version, or contact the developer who added it?

**Comment by stilett0** [comment]
I never thought I'd see the day. Finally, someone willing to tackle typos and misspellings! My advice: start with targeting sourcecode comments first and foremost. Software lists and arcade game titles in the ROM definitions are far more frequently intentional.

**Comment by jmallach** [comment]
@cuavas, first of all, I',m a total newcomer and a newbie when it comes to MAME's codebase and internals. All the actual code changes that I've done have been as conservative as I've been able to judge, and it wasn't my intention to rename ROMs at all. If

    ROM_SYSTEM_BIOS(0, "standart", "Standart")

references some software/BIOS name, I'll get rid of that commit as well. Can someone clue me?

**Comment by jmallach** [comment]
From what I can see, this is just a version string for a BIOS, right? The same file has a "ver 1" additional section. I also see a few other occurrences:

    src/mame/drivers/h8.cpp:	ROM_SYSTEM_BIOS(0, "bios0", "Standard")
    src/mame/drivers/ksys573.cpp:	ROM_SYSTEM_BIOS( 0, "std",        "Standard" ) \
    src/mame/drivers/apf.cpp:	ROM_SYSTEM_BIOS( 0, "0", "Standard" )
    src/mame/drivers/sorcerer.cpp:	ROM_SYSTEM_BIOS(0, "standard", "Standard")

I know little about historic ROMS or so, but I'd say this is just a typo. I don't know if this will render the BIOS non-functional, I'd like someone to help me understand that. :)

**Comment by mamehaze** [comment]
bios names can be whatever a driver author decides, some will be taken from actual documentation, others based on chip labels, others based on maybe a version string in the roms, others based on the regions the bios is, others based on a revision, and some invented for lack of better information.

**Comment by jmallach** [comment]
Can I do anything to get this merged before it bit rots a bit? Is there any change desired before it can be merged?

**Pull request merged**
