### PR TITLE
Add FDC Write Protect Delay

### PR DESCRIPTION
**Pull request by tlindner**
Added 108 microsecond delay between an attempt to write to a write protected disk and the subsequent INTRQ.
Fixes: https://mametesters.org/view.php?id=8258.

### CODE REVIEW

**Comment by BruceWayen66** [comment]
I found 139 support for android, Does laster version (say 248/249) support android? 
Or Is a libmame.so of version (248/249) available??

**Comment by cuavas** [comment]
@BruceWayen66 this is not a discussion forum.

**Comment by BruceWayen66** [comment]
> @BruceWayen66 this is not a discussion forum.

I know, I just can it register on the forum, So I came here for help.

**Comment by BruceWayen66** [comment]
> @BruceWayen66 this is not a discussion forum.

I know, I just cannot register on the forum, so I came here for help.

**Pull request merged**
