### PR TITLE
luaengine: add description comments for emu.item()

### PR DESCRIPTION
**Pull request by vadosnaprimer**
While testing, found out that read_range ignores offset/index, and that it returns char data only. Is any of that a bug?

Don't see an option to request a review, but these questions are mostly directed to @cracyc.

### CODE REVIEW

**Comment by cracyc** [comment]
Yes, that's a mistake.  The only user of that was the cheat finder which doesn't use the offset (well, it does but it's 0 all the time).  Add a fix to this PR if you want otherwise I'll get to it when I can.

**Comment by vadosnaprimer** [comment]
So returning chars is normal?

**Comment by cracyc** [comment]
It returns a string.  I guess it could be an array but since the most likely usage is to get the ram device buffer it could be a very large (multi megabyte) array with one byte per index.  If you want to create another function which returns an array feel free but the string return function is necessary.

**Comment by vadosnaprimer** [comment]
Please check now.

**Comment by vadosnaprimer** [comment]
Sorry for being too late, another observation:
```
[MAME]> print(manager:machine():render().targets)
function: 00000000003a8050
[MAME]> print(manager:machine():render():targets())
table: 0000000010dd7c00
[MAME]> for k,v in pairs(manager:machine():render():targets()) do print(k) end
1
0
```
The comment saying `render.target[] - render_target table` seems to have a typo.

**Comment by cracyc** [comment]
fixed

**Comment by vadosnaprimer** [comment]
I mean the working syntax also seems to be `render:target()` to access the table, otherwise it returns a function pointer. What's the principle behind using `.` and `:`? Looks somewhat inconsistent in comparison. For some items table is behind `:foo()`, for others it's behind `.foo`.

**Comment by cracyc** [comment]
Yeah, that is a leftover from before the change to sol2.  I'm inclined to make it a property for consistency as although it's a breaking change I doubt there are any significant users of that api and if there are converting is trival.

**Comment by vadosnaprimer** [comment]
I doubt there are many users (if any), since it wasn't working the way it was documented, and quite a few variations resulted in a crash, yet no one reported problems. One has to know how to use it beforehand. Also if there are fixes to inconsistency, migrating to a saner approach is usually worth it for users.

**Pull request merged**
