### PR TITLE
PSX GPU: Fix the 24bit rendering of video sequences on games such as GranTurismo and Digimon World 3

### PR DESCRIPTION
**Pull request by felipesanches**

### CODE REVIEW

**Comment by Shideravan** [comment]
Digimon World 2 video now runs fine too.

Valeu, Juca!

**Comment by felipesanches** [comment]
Hahaha! Do we know each other in person? Do you also speak portuguese? I'm glad that such a simple fix apparently made someone very happy :-)

**Comment by kamilmaj94** [comment]
"PSX GPU: Fix the 24bit rendering of video sequences on games such as GranTurismo and Digimon World 3" when had mame started to run games from PS1? ROMs based on ps1 hardware such as namcos12/11/22 etc but Gran Turismo? what?

**Comment by felipesanches** [comment]
MAME and MESS were merged into a single thing simply called MAME from now on (where 'now' means some months ago...).

**Comment by Shideravan** [comment]
Não o conheço pessoalmente, mas um dia ainda quero ter o prazer de conhecer o Garoa Hacker Clube aí em São Paulo, hahaha

And I have to say, I tested some other games which used to have graphical problems and the fix even made Heart of Darkness finally playable ;)
Other fixes include Final Fantasy 8 and 9, Gex videos, Iron Man - X-O Manowar in Heavy Metal, MK Trilogy intro, etc :)

**Comment by felipesanches** [comment]
Shideravan, please contact-me at juca@members.fsf.org
I'd like to chat. I still wonder whether you're a brazilian or maybe you're from Portugal? Anyway, it is nice to see other portuguese speaking people contributing to MAME. If you are from Brazil, I will be glad to meet in person to talk about emulation. If you're in Europe, than IRC chatting and/or e-mails are good as well :-)

Happy Hacking,
Felipe "Juca" Sanches

**Pull request merged**
