### PR TITLE
bus/nes_ctrl: Added emulation for IGS Tap-tap Mat controller.

### PR DESCRIPTION
**Pull request by 0kmg**
Software list items promoted to working (nes.xml)
---------------------------------------
Super Mogura Tataki!! Pokkun Moguraa (Japan)

### CODE REVIEW

**Comment by 0kmg** [comment]
Here's a picture of the mat: https://i.ebayimg.com/images/g/KRQAAOSw~Wpd-w0c/s-l1600.jpg.

The only technical description I could find is that it behaves like the Family Trainer Mat side B, but with columns reversed. I borrowed (shamelessly stole) that code as a starting point. Basically this is the Family Trainer Mat minus the flippable two sides, plus new pad labels, plus bug fixes for the Family Trainer's incorrect read function.

**Review by cuavas — COMMENTED** [review]
Is this a better case for buttons or keypad inputs?

**Comment by 0kmg** [comment]
Is this a question of the ioport_type? IPT_BUTTON#? You'll have to tell me what's appropriate as I don't understand the semantic difference in MAME. I only used IPT_KEYPAD since that's how it was done for Family Trainer. Was that choice largely just due to the fact that that one looks like a number pad?

**Comment by DavidHaywood** [comment]
there are 4 buttons in a row, it doesn't really work with the IPT_KEYPAD setup

(actually a lot of things don't really work well with IPT_KEYPAD because the PC keypad has the top and bottom rows swapped compared to the majority, but at least most of those are 3x3 grids)

**Comment by happppp** [comment]
IPT_KEYPAD or BUTTON or OTHER is meaningless if you override it with PORT_NAME and PORT_CODE such as done here.
So IMO: don't really care, I'd probably use BUTTON.

Haze FYI IPT_KEYPAD applies to the emulated input device, doesn't mean that it should use the PC numpad.

**Comment by cuavas** [comment]
`IPT_KEYPAD` has nothing to do with the numeric keypad on a PC keyboard.  It’s for data entry keypads, calculator keypads, etc. that aren’t full-size keyboards.  It works like `IPT_KEYBOARD` but doesn’t cause MAME to disable UI controls by default.

There *are* significant differences between `BUTTON`, `KEYPAD` and `OTHER` even if you override the names and default assignments:
* `BUTTON` inputs have distinct types, and are assigned logical player numbers.  There’s a limit of 16 distinct button input types per logical player.  They’re also handled specially by some things (e.g. the Autofire plugin only allows autofire for button inputs).
* `KEYPAD` interacts with the natural keyboard manager (e.g. you can make it react to UI paste), and keypad inputs can be enabled or disabled per device in the keyboard mode menu.  Internally, keypad inputs all have the same type are not assigned player numbers, which makes a big difference for plugins, etc.
* `OTHER` gets no special handling at all.

I think in this case, `BUTTON` is most appropriate.  Choose a logical ordering pattern (and maybe update the family mat while your at it).

Also, if this is as similar to the family mat as you’re suggesting, could you make them share a base class but use distinct port definitions or something?

**Comment by 0kmg** [comment]
Argh, still no response from GitHub about unflagging Actions on my account, so still no CI.

@cuavas Yes, I can and have merged ftrainer and the proposed taptapmat. Now in fcmat.cpp. I probably would have done this initially, but ftrainer wasn't working at the beginning and I implemented the fix in the easy-to-test whack-a-mole first.

I looked at PORT_INCLUDE/MODIFY but didn't see an obvious way of simplifying this further. BUTTON numbers were picked to match the Family Trainer B side numbered buttons (i.e. for either mat—either side in the case of the Family Trainer—the same BUTTON numbers eventually end up as the same bits given certain read/writes). Otherwise port stuff (and the rest) is all just copied over with minor alterations.

Will test more of the annoying Family Trainer games later, but I did a more thorough test of a couple here.

**Pull request merged**
