### PR TITLE
bandai/sv8000.cpp: Halved CPU clock. Fixes games running too fast.

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by 0kmg** [comment]
Here's hardware footage of two games: https://www.youtube.com/watch?v=QCo24GLyff4
This may be hardware footage of all seven (are there other emulators for this system?): https://www.youtube.com/watch?v=HgPUzoIc8gc

I couldn't find any additional info on the hardware, but halving the previously guessed clock gets MAME to run these about the speed of the above footage. Games are really unplayable in many cases as currently overclocked.

**Comment by FoxhackDN** [comment]
> This may be hardware footage of all seven (are there other emulators for this system?):

The uploader said in a comment that he used an emulator, but he doesn't say what it was.

**Comment by 0kmg** [comment]
Thanks. Yeah, I referenced that other video you linked too. Well, that's 3 of 7 that seem to about in line with hardware footage at least. Anyway, the clock rates are all guesses. Is the XTAL here also a guess? The only PCB image I could find was the tiny one on this page: http://www.ne.jp/asahi/cvs/odyssey/videogames/sv8000/system/

**Comment by cuavas** [comment]
I dunno about this I know there’s already guess-work involved, but my gut feel is that a divide-by-six on a ≈11 MHz clock for a Z80 doesn’t seem right.  Can we try to dig a bit more?

**Comment by 0kmg** [comment]
It's a rare system, so I can't turn up anything else. I've looked at what's available through the web and video. If anybody else has info or access to a machine that would be great. The game speed is obviously way too fast in MAME.

The 3.58 MHz seemed implausible on a cheap '79 console as well. Is the chip in it really a D780C or is it a D780C-1? The former maxed out at 2.5 Mhz.

**Comment by cuavas** [comment]
Is the CRTC generating the right screen parameters with its current clock?  How do the games generate timings?  Are they really just running flat-out, or are we missing some status bit or something?

I’m not questioning whether the games are running too fast.

**Comment by DavidHaywood** [comment]
The 4Mhz Z80A had been around since 1977 at least, but yeah, seems very unlikely they'd be using that in a cheap home system.  I looked at this a couple of years back, and couldn't see any other way to limit the speed.

It could be 2.5Mhz with waitstates I guess, but as kmg has found, there's basically no information on this thing out there now, so unless one falls into friendly hands I doubt we're going to see any kind of measurements; all we can do is replace one educated guess with another.

**Comment by 0kmg** [comment]
FWIW, squinting at the near useless PCB photos (how'd they manage to take that many blurry pics?) in Vas' link you can tell that it's a D780C. Anyway, if we don't want to change the made up XTAL/divider for another made up one, this driver should at the very least be marked as MNW.

**Comment by happppp** [comment]
Appears to be correct to me.
The game tempo is the same as in the console videos. The AY is also 10.73/6 and pitch matches with the videos. (not talking about the emulator videos here, but the low quality console ones)

**Pull request merged**
