### PR TITLE
New Champion Base Ball clone

### PR DESCRIPTION
**Pull request by MASHinfo**
New Clone Added
-----------------------------------------------------
Champion Base Ball (Japan set 3) [Siftware, MASH]

Rom: blue1.zip
Set is missing palette + look-up table proms, use the ones from (Japan set 1).

### CODE REVIEW

**Comment by happppp** [comment]
We may have simply overlooked some of Siftware's dumps in the past. In
other cases it could be deemed a bad dump of an existing set. Did you check
if this one is not the latter case?

**Comment by happppp** [comment]
Ok, rom seems good.

**Comment by happppp** [comment]
Please test your work when you make a PR :)
I fixed it for you this time.

C:\Dev\MAME\git_mame>m champbasjb
Driver champbasjb (file champbas.cpp): 2 errors, 0 warnings
Errors:
   HD44801 device 'alpha_8201:mcu': program space memory map entry 0-7FF
references non-existant region ':alpha_8201:mcu'
   HD44801 device 'alpha_8201:mcu': program space memory map entry F40-FBF
references non-existant region ':alpha_8201:mcu'

**Comment by MASHinfo** [comment]
Many thanks for the quick fix!

**Pull request merged**
