### PR TITLE
Update unzip.cpp to work with bigger files

### PR DESCRIPTION
**Pull request by LnmVolbo**
Re: issue https://github.com/mamedev/mame/issues/785
Enables the ui to be able to read 4GB+ zip files, in case the users choose to zip up entire folders for convenience.

**Updated summary of changes:**
Lines 82-91: added some defines
Lines 94-141 moved inline functions up so that modified archive_file::error initialize() routine would see them.
   Added new function read_qword()
Lines 208-254 modified archive_file::error initialize() to locate and use 8 byte offset to central directory.
Line 341 added extra_field definition to file header structure.
Line 357 added zip64 end of central directory locator definition (zip64_loc) to ecd structure.
Line 506 added extra_field field to central directory file entry structure. See line 341
Line 667 added zip64_loc to the ecd structure in order to make it easier to find the zip64 end of directory locator block later. See line 357
Lines 704-719 main code changes

### CODE REVIEW

**Comment by cuavas** [comment]
Please use the types from cstdint rather than the legacy all upercase types from MAME's OSD headers.
Please use C++ function-style casts or explicit static_cast/reinterpret_cast rather than C style casts.

The ZIP64 signature if present immediately precedes the ECD.  You should check for it after locating the ECD.  You definitely shouldn't be scanning for the ECD twice like this.  Copy/pasting clearly expensive code that does allocations and I/O should ring alarm bells in your head.

**Comment by LnmVolbo** [comment]
Thanks for the feedback, I will revise.

Yes I was alarmed, I thought the way read_ecd() did it was because of the necessity finding a signature at the head of a variable sized block, so I duplicated the functionality to find the "PK67" block.  Since you indicate it is unnecessary to scan for that, I will eliminate the 2nd scan.

My understanding of your directive to use C++ function style casts is this:
replace C-style casts, such as: (UINT64)var_name;
with C++-style cast, such as: static_cast<std::uint64_t>(var_name);

**Comment by cuavas** [comment]
No, that's an explicit static_cast which you generally don't need unless you're messing with references/pointers to polymorphic classes.  You can use a function-style cast most of the time.  Also, you don't need to explicitly cast when assigning an unsigned integer to a variable of a larger unsigned integer type.  C has automatic promotion.

**Comment by LnmVolbo** [comment]
Thanks for the tips, updated code ready for review.

**Comment by cuavas** [comment]
I see no changes.

**Comment by LnmVolbo** [comment]
I must be doing it wrong.  When I saw this link:

https://github.com/mamedev/mame/pull/790/commits/09282f196a26de70056336857299d7a13ac96582

I thought the changes were in place.  Sorry to be a pain, do I have to close this and make a new pull request to register the changes properly?

**Comment by cuavas** [comment]
OK: let me be more explicit: I still see a big copy/pasted loop in initialize() that clearly doesn't belong there.  The ZIP64 signature immediately precedes the ECD if present.  You shouldn't be searching for it separately.  And it definitely doesn't belong in that method.  Also you're looking for ZIP64 extra field whether you found ZIP64 signature or not.

**Comment by LnmVolbo** [comment]
I removed the loop.  Not sure what you are looking at.  Can you post the link to the code that you are using?

**Comment by cuavas** [comment]
This:
https://github.com/mamedev/mame/pull/790/files#diff-d83bc6ac7e3a959fd07120cb0bdef0f7R208

OK, not a loop, but still a big piece of copy/pasted code that's convoluted, unnecessarily complex and in the wrong place.  Why are you dynamically allocating a small fixed-size buffer?  Why are you doing this in what's supposed to be a small inline method?  Why are you later looking for ZIP64 extra fields whether or not you find the ZIP64 signature?

**Comment by cuavas** [comment]
Closing due to poor quality, incomplete implementation of ZIP64.

**Comment by LnmVolbo** [comment]
Thanks for the critique.

The complexity is inhibiting the looking for ZIP64 extra fields when the zip64 signature is not found.  I thought that was a requirement.

I am using a small buffer on the "locator" block because I want to check it's signature and then grab the pointer in it.  I use the pointer to load another small block that has the ultimate 8 byte pointer in it.  Again I load the whole block to verify the proper block header signature is present before continuing.

Another issue is the ECD structure has only a 4 byte offset.  It can't return an 8 byte value unless it is modified severely which could make it confusing or incompatible with the standard ECD structure.  The ECD structure does not return any info about the block immediately before it, or it's own location in the file.  Not clear to me how to get the block immediately previous to the ECD.  And that (locator) block does not have the required info.  All it has is a pointer to another block that has the needed info.

The initialize() routine has to be modified because the ECD only provides a 4 byte offset in it's structure.  I don't see any other way with out making severe changes to the ECD structure.  Is this what is desired?

I can understand if you are tired about corresponding about this.  I would appreciate it if you could provide more feedback about how to improve this pull request, or invite someone else to reply to my queries.

I would be interested in finding out how to make a more complete implementation of ZIP64.

**Comment by LnmVolbo** [comment]
Just pondering here, about changes which would make this a better submission.

Instead of using a buffer to read parts of the file, (as the read_ecd() routine does), I should just read dwords and qwords at specific points of the file to make sanity checks and follow the chain of indirection.

I had added a 4 byte field to the ECD structure to pass back the location of the "locator" block.  I then processed the "locator" block info in the initialize() routine to "correct" the bad 4 byte offset into the valid 8 byte offset.  This was only done when the 4 byte offset was determined to be overflowed.

I didn't want to replace the existing 4 byte offset field in the ECD with an 8 byte offset field because it would damage the monolithic structure that matches the zip specification.

It should be possible to tack on the 8 byte replacement offset value to the ECD structure.  But the initialize() function will have to be modified to choose either the 4 byte or 8 byte offset, depending on the value of the 4 byte offset.  The existing initialize() function is hard wired to only use the 4 byte offset.  As it is presently, it cannot use an 8 byte offset.  This is why it needs some kind of re-write.

**Pull request closed without merging**
