### PR TITLE
galaxian/galaxian.cpp: Dumped PROM for "catacomb" [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by Osso13** [comment]
Thanks, should the  MACHINE_WRONG_COLORS flag be removed or arte the colors still wrong?

**Comment by clawgrip** [comment]
Cannot tell, the PCB is broken... Maybe yes. Should I remove it?

**Comment by Osso13** [comment]
Maybe leave it and add a note about needing hw references to verify colors?

**Comment by clawgrip** [comment]
> Maybe leave it and add a note about needing hw references to verify colors?

Done, thanks!

**Pull request merged**
