### PR TITLE
jpmimpact.cpp: work on correctly mapping buttons for each machine [David Haywood]

### PR DESCRIPTION
**Pull request by DavidHaywood**
jpmimpact.cpp: work on correctly mapping buttons for each machine [David Haywood]
 - all sets with accessible button test modes now have buttons mapped, which should make correcting the layouts etc. much easier.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
Right.  I think this is a checkpoint.  I need to work out why some games aren't responding to the test mode key once the doors are open in order to work out the per-game button mappings for those.

**Comment by MooglyGuy** [comment]
Is it too much to ask to do a squash-merge with a reasonably-written commit message? Instead it seems like you'd rather just shit up whatsnew.txt and make Vas's life harder.

**Comment by DavidHaywood** [comment]
how do I do that in SourceTree?

**Comment by happppp** [comment]
Not you. It's to the person merging the PR to 'moderate' what goes in.

for example these commit messages, I'd delete those to prevent them from going in the whatsnew:

further per game inpiut work
further input work
further input fixes
attempting to locate a j6monmad input
further per-game inputs
additional per game inputs
remove a duplicate line
looked at a few more games
gave a few more inputs
cover more game inpus
more game inputs
additional per-game inputs
more per-game inputs
additional per game inputs

**Comment by MooglyGuy** [comment]
Yeah, my comment wasn't directed at you at all, @DavidHaywood. Sorry if I gave you that impression. My complaint was entirely that @Robbbert just blindly merged the pull request without even using the "Squash & Merge" button, let alone bothered writing a condensed commit message.

Merging pull requests comes with some responsibility, namely ensuring quality. That's not just the quality of the pull requests being approved, but the quality of the commit messages that go alongside them. If that's not a responsibility that is willing to be taken, then don't do it, leave it for someone else who is willing.

**Comment by Robbbert** [comment]
I did indeed use squash and merge, I can't help it if it didn't work. I also did consider the original message title and decided it was adequate as is. If there's a problem, then cuavas can tell me directly.

**Comment by happppp** [comment]
After you press "squash and merge", but before you press "confirm squash and merge", there's an editbox where you can modify the commit message that gets applied to master. There's more than just the title, see:

https://github.com/mamedev/mame/commit/c25ae86a7a4f8abfbb19e29b80f3418205584b57

**Comment by Robbbert** [comment]
The edit box only showed one line of text. There's no indication that an entire story was hiding there.

In future, please leave the childish name-calling out of the equation. I tried my best, but apparently it isn't good enough for some.

**Comment by cuavas** [comment]
@Robbbert I’ve been saying it for months now, there’s absolutely no excuse any more: if you’re going to merge a pull request, you’re responsible for making sure the commit message meets standards.  When you squash and merge a pull request, there are two edit text boxes – the first one is pre-populated with the title of the pull request, and the second one is pre-populated using the commit messages from the commits to be merged.  You need to check **both of them**.

If your not prepared to do this, please don’t merge pull requests.  Also, if you still want to play games with silly formats for added machines/software, please use pull requests so someone else can reformat them before they end up in the commit logs.

**Comment by Robbbert** [comment]
I'm not playing silly games, I'm trying my best to do it right. Please don't insult me by saying I'm lazy.

But I won't merge any more PRs or respond to issues until you feel I'm fit to.

**Pull request merged**
