### PR TITLE
Relieve UI menus and such from having to constantly fetch UI object f…

### PR DESCRIPTION
**Pull request by ajrhacker**
…rom global state (nw)

### CODE REVIEW

**Comment by mmicko** [comment]
Can you please rebase this? Thanks

**Comment by ajrhacker** [comment]
Sorry--I didn't quite get the warning that a large release "MAME 0.173" was approaching fast. Since rebasing a pull request is apparently considered harmful, I've done a merge for the sake of conflict resolution.

**Comment by galibert** [comment]
Huh?  No, rebasing a pull request is fine, and mainline merges in the
history are actually annoying.

  OG.

**Comment by stilett0** [comment]
@ajrhacker for future reference we're releasing on the last Wednesday of the month, with a feature-lock freeze for the preceding 48-72 hours

**Pull request merged**
