### PR TITLE
Added suspend and resume debugger commands

### PR DESCRIPTION
**Pull request by GavinAndrews**
Useful commands for investigations which require interfering devices to be suspended

### CODE REVIEW

**Comment by GavinAndrews** [comment]
Will sort out indents.  Please note that I am new to MAME this might not be the best approach.  Comments appreciated

**Comment by GavinAndrews** [comment]
fixed indents

**Comment by galibert** [comment]
The debugger is first and foremost a reverse-engineering tool.  So more
power is by definition good.  I'm not sure how useful it's going to be
though, since it's not going to stop irqs in general, so it's only a very
indirect way of reducing the amount of noise when trying to follow a
routine...

  OG.

**Comment by GavinAndrews** [comment]
My use case is investigating Juno First or specifically the 8039 SFX processor.  By suspending the :maincpu and the :audiocpu I am able to tickle the mcu by putting data into the latch at 5000 and then causing an interrupt by writing to 6000 (audiocpu memory space).

It's probably a bit niche. :)

**Pull request merged**
