### PR TITLE
sms/nes: Fix light gun regression and change the way its screen is configured

### PR DESCRIPTION
**Pull request by enikland2**
Avoid a possible but currently inexisting issue that @cuavas raised concern when he commented on pull request #4665.

### CODE REVIEW

**Comment by enikland2** [comment]
Could someone also review or commit the pull request #4871? I would like to see it included in the next stable version that is set to be released next Wednesday.

**Comment by cuavas** [comment]
Not acceptable.  Using an absolute tag lookup like this is still making an assumption about the host system.  The screen needs to be configured on the controller slot if controller devices are going to need it, so that it gets the right screen.  Devices must not make assumptions about the host system like this.

**Comment by enikland2** [comment]
New try submitted, it it better? For subdevices I had to set the screen in device_start(), else MAME would crash when run.

**Comment by enikland2** [comment]
Now I think the changes meet your criteria, @cuavas.

**Comment by Tafoid** [comment]
Ok, does this fix NES issues mentioned in MT report https://mametesters.org/view.php?id=7331  ?
If someone could test it..

**Comment by Osso13** [comment]
> 
> 
> Ok, does this fix NES issues mentioned in MT report https://mametesters.org/view.php?id=7331 ?
> If someone could test it..

I tried this patch with duckhunt, it doesn't fix the bug.

**Comment by enikland2** [comment]
The MT report https://mametesters.org/view.php?id=7331 shall be fixed by updating the screen before read the pixel color. I also added similar changes to the Sega Master System side.

**Comment by enikland2** [comment]
Note: the NES and derivative drivers required some additional changes when compared to SMS and derivative drivers because the code for the NES stuff wasn't prepared for more than one screen update per frame (only for full frame updates) and the line drawing routine for the NES PPU device is programmed to draw the last line that was surpassed by the beam, contrary to the routine of the SMS VDP (despite similar scheduling) that draws the next line that will be surpassed by the beam.

**Comment by enikland2** [comment]
I submitted pull request #5306 which contains only the necessary changes to fix the light gun regression first mentioned in MT report https://mametesters.org/view.php?id=7331

If there is interest about the additional changes proposed here to the setup of the screen used by light guns of NES, SMS and derivative drivers, those changes will need to be rebased after pull request #5306 is merged (that's why I tried to avoid doing separate submissions until now).

**Comment by enikland2** [comment]
The screen configuration changes were resubmitted as pull request #5324, that is already merged to the master tree.

**Pull request closed without merging**
