### PR TITLE
CoCo SAM:  Changed SAM clock speedup capability to (by a heuristic) identify all devices subject to clock scale changes

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by ajrhacker** [comment]
The "crude heuristic" here may be a convenient hack, but it does an unbelievably poor job of representing what a clock generator actually does. I think either a custom delegate or a list of device finders would be a much more coherent model for propagating runtime clock changes.

**Comment by npwoods** [comment]
Don't get me wrong - I hate this hack.

One idea that did occur to me was to add the ability to propagate clock changes through the CoCo slot infrastructure, but I felt reluctant to do so because I didn't want to build anything CoCo specific.

What I really want to do here is be able to "declare" a clock, and define the clock of various devices (which may be mounted in a device slot) in terms of that clock, and then to be able to control that clock directly with any changes to it propagating automatically.  I would love to find out that there is a convenient way to do so that I am overlooking.

**Comment by ajrhacker** [comment]
The implementation isn't even accurate for the CoCo. It seems that the SAM6883 has separate MPU (MC6809E) and VDG (MC6847) clock outputs, and only the former should be affected by writing to the control register.

**Comment by cuavas** [comment]
Just no. This is ridiculous. If the CoCo exposes multiple clocks on the slots, this should be exposed through the slots. Subscribing to global clock signals is a bad idea as well because it will fall over when we can run multiple drivers in a single MAME instance. Anything slot devices need to see about the machine needs to be exposed through the slot interface.

**Pull request closed without merging**
