### PR TITLE
dc.xml - Add all games up to N

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by p1pkin** [comment]
> Start replacing some dumps with Redump dumps.

why ?

**Comment by FakeShemp** [comment]
Two reasons.

To avoid the many duplicate dumps in tosec that result from discs with different write offsets.

And because Redream handles redump dumps correctly now so they can actually be tested.

**Comment by p1pkin** [comment]
sure, duplicate is not good, but why remove TOSEC and replace it with Redump ?

I've been told Redump images is different because theirs site database works only in this way. its not because more accurate dumping, and anything like that but, because site and database. is it sounds any sane ? I don't think so.
I see no good reason to replace good and verified dumps because of theirs database joke.

**Comment by FakeShemp** [comment]
@p1pkin Can you actually explain what is "wrong" with redump dumps and what is "right" with tosec's?

**Comment by p1pkin** [comment]
they are different, look there - https://assemblergames.com/threads/wrote-a-tool-for-gdemu-users-for-converting-redump-gdi-format-to-general-gdi-format.66263/#post-942906
and here
https://github.com/SONIC3D/gdi-utils
pictures in AG forum topic pretty much demonstrate differences - Dumpcast/TOSEC/Trurip/MAME dumps miss PREGAPs in some cases, and that's that GDI format is "by design".
while Redump dumps include gaps (except for LD area 1st track pregap, which is missing in Redump images too).

also, all "regular" GDI images have audio tracks with native Dreamcast offset (I've been told it is +684), it is same for all DC GD-ROM drives used for dumping and dumps itself in result, while Redump images have offsets corrected to some zero value.

so, in general, its mainly about consistency, we not interested to get in MAME romset of software lists mixture of 2 in fact different formats with the same name GDI.

**Comment by p1pkin** [comment]
on other note, iirc in previous PR there already was discussion about this, and you've been told by several MAME team members to use TOSEC/Dumpcast as primary source. why you not following this ?

**Comment by FakeShemp** [comment]
I've been told by many mamedev members to use *redump*. That's why I switched 😆

**Comment by p1pkin** [comment]
are you sure it was about Dreamcast ? Redump is great source, if not the best, but for everything except GD-ROMs (Dreamcast/Naomi/Triforce/Chihiro), because GDI support is implemented as a hack/quirk on top of Redump CUE-oriented database engine, and not match actual GDI format in result.

**Comment by FakeShemp** [comment]
Yes, I am. I think you have been the only one to directly tell me not to use redump. All other comments have been either to use redump or that either set is fine.

What does everyone else think? Personally, I don't care other than that several identical dumps with just different offsets are annoying to keep track of.

**Comment by p1pkin** [comment]
> the best, but for everything except GD-ROMs

self correction - Redump is not acceptable for discs where is important full subcode data or original disc TOC, or multisession discs, because of same reason.
did you ever asked question to yourself - why such 'dumping accuracy pedantic' community like Redump never(?) store subcode data in theirs dumps, but only have another hack/quirk 'SBI' files for LibCrypt-protected Playstation games ? -- that's another case of site/engine database limitation. people got all that data during dumping, but it goes to dev\null because Redump "core" engine can't store or document it.

**Comment by p1pkin** [comment]
>  I don't care other than that several identical dumps with just different offsets are annoying to keep track of.

did you read AssemblerGames topic and looked at pictures ? it is NOT about offsets, but PreGaps

**Comment by FakeShemp** [comment]
Having dumping CDs for 10+ years for various projects; yes, yes I have. 

Dumping subs accurately is pretty much impossible due to no error correction (except for CD+G data and similar). Redump's method is to only store the actually used sub sectors and dump those thousands of times to *probably* get them correct. And this isn't done just for playstation, Safedisc is the same.

**Comment by FakeShemp** [comment]
Okay, it's annoying to keep track of all versions with different pregaps 🙂

**Comment by p1pkin** [comment]
> Dumping subs accurately is pretty much impossible due to no error correction (except for CD+G data and similar). Redump's method is to only store the actually used sub sectors and dump those thousands of times to probably get them correct.

didn't Q channel subs have CRC ? and they are used, pretty many games use them, including Dreamcast ones, they read Q subs and to current audio play position. but yes, sure, its not any important preserve original disc data, if these data may be re-generated in software. heh, for some stange reason it is important to store empty PreGap sectors in GDI.
why its like that ? - because of CUE format limitations and database/engine crap.

**Comment by F1ReB4LL** [comment]
[quote]also, all "regular" GDI images have audio tracks with native Dreamcast offset (I've been told it is +684), it is same for all DC GD-ROM drives used for dumping and dumps itself in result, while Redump images have offsets corrected to some zero value.[/quote]
Redump images are dumped as scrambled, then unscrambled in software starting from the very first byte of the first track. As for the dumpcast's dumps, each dump has a different offset there, each disc has its own write offset value, that adds to the drive's reading offset, that sometimes results in quite huge values.

[quote]self correction - Redump is also not acceptable for discs where is important full subcode data or original disc TOC, or multisession discs, because of same reason.[/quote]
There's no problems with storing the full subcode data (and name any disc where that data is important, known sub-based protections only use the Q channel), multisessional TOCs aren't properly supported due to cue limitations, no problems with single-session TOCs.

[quote]did you ever asked question to yourself - why such 'dumping accuracy pedantic' community like Redump never(?) store subcode data in theirs dumps, but only have another hack/quirk 'SBI' files for LibCrypt-protected Playstation games ?[/quote]
Because only Q-channel is important for libcrypt (and securom) and SBI-files were used by the PSX emulators when the psxdb site was created.

[quote]didn't Q channel subs have CRC ? and they are used, pretty many games use them, including Dreamcast ones, they read Q subs to get current audio play position. but yes, sure, its not any important preserve original disc data, if these data may be re-generated in software.[/quote]
Q-CRC isn't enough, if we want to preserve the subs as is with all the mastering issues. But if we decide it's OK to fix all the 1-bit errors, subs checksums would be constant. So it's more of a lack of some 'political' decision there. Also, dumping the subchannels even from the unscratched disc may take a few hours, sadly, not many dumpers are ready to do this.

[quote]heh, but for some stange reason it is important to store empty PreGap sectors in GDI.[/quote]
Yes, because that's the "main" data that shouldn't be altered/cut just like MAME doesn't cut the ROMS that are mirrored or half-empty. There should be no 'double standards' for the dumps.

**Comment by F1ReB4LL** [comment]
> my memory may fool me, but I recall I've read in SDK docs Dreamcast disc authoring software may/will add random length small silence/pause before audio tracks, which you call "different offset".

No, offsets have nothing common with silences and pauses, it's a difference between the start of the scrambled data sector as read by the drive and the actual sector sync. Disc write offsets appear when the final CD-R/GD-R gets burned during the mastering stage (each burner has some write offset).

**Comment by p1pkin** [comment]
> No, offsets have nothing common with silences and pauses, it's a difference between the start of the scrambled data sector as read by the drive and the actual sector sync.

I hear you. but as was said, iirc mastering software may add random pause before audio. how do you know if its drive read offset or such software added silence ?

> Disc write offsets appear when the final CD-R/GD-R gets burned during the mastering stage (each burner has some write offset).

afaik Dreamcast titles was shipped to mass production in form of CDCraft produced disc images, except for early games.

**Comment by F1ReB4LL** [comment]
> I hear you. but as was said, iirc mastering software may add random pause before audio. how do you know if its drive read offset or such software added silence ?

Technically, there's no "offset fixing", we detect the first sector's sync position, we take the leadout value from TOC (which shows the length of the image) and read that amount of bytes starting at that position. The offset value itself is only needed for the documentation.

> 
afaik Dreamcast titles was shipped to mass production in form of CDCraft produced disc images, except for early games which was sent on GD-R-s.

Don't forget about the glass matrix burners.

> heh, but for some stange reason it is important to store empty PreGap sectors in GDI.

These can be cut, if MAME or any other emu needs them to be cut, the problem with the Dumpcast images is that some of their pregaps are not empty due to data shifted into the gaps by the offset and they cut the _non-empty_ pregaps, so it's impossible to reconstruct the initial image. In other cases the offset shifts the data into the lead-out area and they lose that data. Again, it's not "+684 samples" for all the images, each dump has its own combined offset.

**Comment by Tafoid** [comment]
Before any other decisions are made concerning final sourcing/dumping of the Dreamcast titles, we are going to accept this PR to clean the slate and not let all this work go to waste.  All entries have been scanned and confirmed valid and select tested titles do at least boot in current console emulation.

**Pull request merged**
