### PR TITLE
unzip: improve dos date / time decode performance

### PR DESCRIPTION
**Pull request by stuartcarnie**
When using the frontend, navigating ROMs is very slow when scanning
a large snap.zip file for screenshots. `mktime` is the culprit, so this
patch manually decodes the DOS date time.

### CODE REVIEW

**Comment by cuavas** [comment]
DOS timestamps are in local time - you have to consider the system timezone to decode them (yes, this means you get a different time if the archive comes from a machine with different timezone settings or the timezone definition changed since the archive was created).  The whole point of using `mktime` there is that it takes the timezone into consideration.  Trying to replace it would require a pile of platform-dependent code and a maintenance nightmare.

**Comment by cuavas** [comment]
Other approaches would be to only decode/cache the timestamp(s) on-demand, or to use an LRU cache for archive directory entries.  The code is fairly dumb at the moment, but `mktime` isn't the problem.

**Comment by stuartcarnie** [comment]
This code is inspired from logic used in the [Linux kernel][1] for parsing FAT date time stamps, which also does not insider the time zone. Other libraries use similar logic. Using the local time zone is potentially just as incorrect as ignoring it, even if it was created on the same machine, given a machine can change time zones. 

In my environment, `mktime` accounted for 100’s of milliseconds every time the snap.zip archive was scanned, making the UI extremely slow. 

[1]: https://github.com/torvalds/linux/blob/d719518d9ce9132bad8a06e8029aeead328f66a3/fs/fat/misc.c#L189

**Comment by cuavas** [comment]
I know that file formats containing local times potentially give different times.  However, if the machine changes timezone, the archive members should return the same local time in the new timezone.  Not considering the timezone takes it from potentially wrong to pretty much invariably wrong.  If a user creates a zip archive and immediately lists it on the same machine, the archived file's modification time should match.  The code does prefer an NTFS modification time (which is always UTC) from a type 0x000A extra header if present.

Please try 75fefade26471ed598bdaf0b87450811eb24b22c or later - this defers decoding DOS timestamps until actually necessary.

**Comment by stuartcarnie** [comment]
Sounds good - that  commit should  make a huge difference. Previously, scrolling through the ROM list was painfully slow.

**Pull request closed without merging**
