### PR TITLE
NAOMI new finding + plus few cosmetic updates

### PR DESCRIPTION
**Pull request by f205v**
added description for newly discovered game + a few cosmetic changes

### CODE REVIEW

**Comment by galibert** [comment]
You changed the X76F100 for Crazy Taxi from not present to present, why?

  OG.

**Comment by f205v** [comment]
Hi OG.
I changed it after checking pictures of the cart.
here is the picture:
http://www.citylan.it/wiki/images/2/26/848_PCB_component_side.jpg
and here is the reference page on my website:
http://www.citylan.it/wiki/index.php/Crazy_Taxi

As you can see the X76F100 at IC37 is present.

BTW I'm re-checking everything on NAOMI-CHIHIRO-TRIFORCE, and updating my table 
here:
http://www.citylan.it/wiki/index.php/Naomi_-_Chihiro_-_Triforce
That was the only difference I found up to now.

Ciao
Antonio (f205v)
www.citylan.it

**Comment by galibert** [comment]
Ah, so it was deliberate, cool.  Since it was in the commit message, I
wasn't sure.

  OG.

**Comment by p1pkin** [comment]
f205v, ughh, you must be did this changes in a big hurry -
- "new finding" game name is wrong, you probably copy/pasted my typo from DU mail subject, also I strongly thinking there not needed *any* unwanted attention to this game, until it will be preserved (or lost).
- Crazy Taxi PCB doesnt have X76F100 eeprom
- Alien Front not require Comm.Board (but supports it)
- you missed CR in GAME macro part.

sorry, but I reject this

**Comment by f205v** [comment]
On 01/06/2015 16:02, MetalliC wrote:
> f205v, ughh, you must be did this changes in a big hurry -
> - "new finding" game name is wrong, you probably copy/pasted my typo from DU mail subject, also I strongly thinking there not needed *any* unwanted attention to this game, until it will be preserved (or lost).
yes, I used your name as stated on the DU list, before we had the correct 
translation (Tokio Bus Guide) from Eric.
I do also fully understand your concern about publicity.

> - Crazy Taxi PCB doesnt have X76F100 eeprom
I have shown pics from ANY as a proof of the fact that X76F100 at IC37 is present.
What is the reason why you say it is NOT present?

> - Alien Front not require Comm.Board (but supports it)
Ok, thank you for this information

> - you missed CR in GAME macro part.
LOL

>
> sorry, but I reject this
Yes, agreed.
I will re-update it at a later stage, avoiding all the errors you mentioned.


Ciao
Antonio (f205v)
www.citylan.it

**Comment by p1pkin** [comment]
Re: [mame] NAOMI new finding + plus few cosmetic updates (#196)







> - Crazy Taxi PCB doesnt have X76F100 eeprom
I have shown pics from ANY as a proof of the fact that X76F100 at IC37 is present.
What is the reason why you say it is NOT present?





whats was my fault (as you can see original msg was edited), with not enough magnification IC37 looked like spare space.
btw you got this photo from me ;) found it somewhere on the net

-- 
with best regards
                     MetalliC        mailto:0vetal0@gmail.com

**Comment by f205v** [comment]
OK, great.
At least this point has been clarified.

**Pull request closed without merging**
