### PR TITLE
fix crash on pensebem / avr8 timer1

### PR DESCRIPTION
**Pull request by felipesanches**
(followup to commit c9d3d973dd955bc985346f3ef3cad77246ed753c)

### CODE REVIEW

**Comment by felipesanches** [comment]
I also substituted `reg == 0` by `reg == AVR8_REG_A` in the timer code

**Comment by cuavas** [comment]
Looks OK for me, but I’ll wait for @MooglyGuy to have a chance to eye it over.

**Comment by MooglyGuy** [comment]
Looks great, thanks for the fix!

**Comment by felipesanches** [comment]
you're welcome! Happy Hacking ;-)

**Pull request merged**
