### PR TITLE
asuka.cpp: Added new clone earthjkrb: "U.N. Defense Force: Earth Joker (US / Japan, set 3)"

### PR DESCRIPTION
**Pull request by sergiopolog**
Added new clone earthjkrb to asuka.cpp
Dump credits to: JammaFever, Nebula, Recreativos Piscis, Spain

* Found in Taito PCB: K1100726A / J1100169B
* It only differs from parent set in 2 program roms: `4.ic23` and `3.ic8`. They are very close to the earthjkra set ones and only differs in 42 bytes in each rom.
* Eprom labels are numbered in the same way as earthjkrp set, but 3 and 4 ones are swapped (Maybe a typo in earthjkrp ?)
* Same ROMSTAR license and no region disclaimer when dipswitch is changed, like earthjkr and earthjkra sets.
* It seems a newer version than earthjkra set, including additional changes to those added in earthjkra in comparison to earthjkr set, as earthjkra and earthjkrb share the same changes from earthjkr.
* Actual PCB picture: https://i.imgur.com/DYgniZc.jpg
* Comparison between earthjkrb and earthjkra:
  * `4.ic23` vs. `ejok_ic23`: https://i.imgur.com/NpBidEY.png
  * `3.ic8`  vs. `ejok_ic8`: https://i.imgur.com/rnenDhW.png
* Comparison between earthjkrb and earthjkr:
  * `4.ic23` vs. `ej_3b.ic23`: https://i.imgur.com/Co8hmCe.png
  * `3.ic8`  vs. `ej_3a.ic8`: https://i.imgur.com/EcnvW3Q.png

### CODE REVIEW

**Comment by sergiopolog** [comment]
Please, let me know where to send the dumped files

**Comment by sergiopolog** [comment]
@DavidHaywood I already sent the dump files to the proper email address. Is there any more actions needed for this one?

**Comment by DavidHaywood** [comment]
I think it's just a case of waiting for somebody to hit merge

**Comment by sergiopolog** [comment]
> I think it's just a case of waiting for somebody to hit merge

thanks! didn't sure about how exactly the contributing procedure is. Thanks for your quick response

**Pull request merged**
