### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
----------
Game & Watch: Pinball [algestam, Ryan Holtz]

### CODE REVIEW

**Comment by algestam** [comment]
I haven't been able to find any cheats for this game.

**Comment by happppp** [comment]
Then it probably doesn't have any, I can double check tomorrow.
As for the PR, looks good =)

**Comment by algestam** [comment]
Thanks! I'm guessing that there aren't any cheats but it would be great if you can take a second look at it :)

**Comment by happppp** [comment]
There was a cheat for infinite lives, only applies to the last life. And one to multiply scoring factor to get a high score faster.

**Comment by algestam** [comment]
Nice fix! I thought I had tested the B and BA ports but I must have missed something :)

**Pull request merged**
