### PR TITLE
use a handcrafted c-chip rom for Rainbow Islands Extra, pending a rea…

### PR DESCRIPTION
**Pull request by DavidHaywood**
…l dump, allows removal of simulation code and general cleanups.

also made rainbow islands extra a parent, since it has it's own game code, own c-chip and is generally considered a semi-sequel rather than a bugfix / revision of the original game.

(best I can tell behavior matches the differences between original and extra that were present in the simulation at least, but obviously the real chip could be hiding more secrets)

### CODE REVIEW

**Comment by ajrhacker** [comment]
Don't you know the rule about limiting parent set names to 8 characters dropped some time ago? I see no particularly good reason for renaming this set to an 8-letterism.

**Comment by DavidHaywood** [comment]
One of the other devs was pulled up on using more than 8 letters tho (Brian IIRC), so I'm just trying to conform with that.

**Comment by happppp** [comment]
I agree with AJR. A few letters overflow is fine now, that's why the restriction was removed. Just keep it short and simple(eg. rbislande is ok, rbislandextra is not)

**Comment by happppp** [comment]
You mean this one?
https://github.com/mamedev/mame/commit/25ca83503c76f3b7fb4ec095b373cb7ea749dbcb
Excluding Brian himself, 3 other developers on the mailinglist were against this commit, cuavas ignored the complaints.

**Comment by DavidHaywood** [comment]
well I've changed it back,, although I can't update mame.lst with the web interface, so either somebody else will have to take care of that bit, or it will need to wait until after the weekend

**Pull request merged**
