### PR TITLE
MEKD4 and D5: new machines

### PR DESCRIPTION
**Pull request by 68bit**
Motorola MC6809 evaluation board. This emulation implements the keypad and LED 7 segment display, and the RS-232 terminal interface, and the MEK68R2 MC6845 CRT and parallel keyboard interface. The RAM and ROM banking is not yet implemented but most of the D4BUG monitor commands are supported.

Some questions if anyone cares to help me get up to speed with MAME:

* If the machine emits sound for only a cassette interface then should it be flagged as `MACHINE_NO_SOUND`? Is that for a sound card rather than emulation of the machines noises?

* This board includes an address bus comparator which can trigger an interrupt. It is used for tracing and debugging. This has been implement by general address read and write functions and a bank device to add another address map. Is there a cleaner way to do this in MAME?

* The machine has multiple input devices, a keypad, a RS232 terminal, and a parallel keyboard which is part of a CRT interface. I could not see any way to change input focus in MAME, so this is managed by making the keypad clickable but with not keycodes, and separating the RS232 input and the CRT input via separate layout views and dropping the input if not in the appropriate view. Might there be a better way to do this in MAME?

* The board supports a range of ROMS. If these were supported in the emulator then would that be implemented via the 'cart' support?

### CODE REVIEW

**Comment by happppp** [comment]
1) I think MACHINE_NO_SOUND_HW is the right flag here, cassette noise doesn't count (unless it has a double function and the machine uses it for generic beeps as well?)

2) A memorymap trampoline, you did it the same way I would do it.

3) Are they pluggables? Then a bus device is the best way (a lot of work)

4) Different program revisions? Then use BIOS roms with ROM_LOAD. Otherwise yes, softwarelist 'cartridge' (even if they're loose pluggable romchips)

**Comment by happppp** [comment]
Some other tips:

- MAME has required_ioport and required_ioport_array. Not only is this faster than a string lookup, but it'd make you able to keypad_key_r much shorter, for example:
mux = m_digit >> 6 & 3;
data = (m_inputs[mux]->read() & m_digit) ? 0x80 : 0;
return data | m_segment;

- MAME has a PWM display device, it can do exactly what you're doing with the 7seg leds. It's in devices/video/pwm.*
Use it after writing to m_segment or m_digit like: m_display->matrix(m_digit, m_segment);

**Comment by 68bit** [comment]
Thank you for the feedback, and I'll looking into it. In case anyone were interested the ROMs for this one are at https://68bit.org/mekd4.zip

**Comment by 68bit** [comment]
Updated with the suggestions. So it now uses the pwm video device, removing the custom code, and uses the ioport suggestions. Thanks.

**Comment by happppp** [comment]
Looks good to me =)

**Comment by 68bit** [comment]
There are a few pending in this series. The patches will conflict if submitted separately, so shall bundle then in here while it is still pending review. If people have suggestions for one then it likely applies to others and code and style has been shared. The MEKD5 has been added to this PR, it was a cheap trainer, and the ROM is at  https://68bit.org/mekd5.zip

Motorola made a D1, D2, D3, D4, and D5 in this series, and I'd like to see these emulated for history. There is already a MAME D2 emulation but it has been re-written and a CRTBUG monitor has been recovered and CRT support has been added to the D2 emulation.

The D3 emulator is almost done too. One of the D3 ROM dumps needs a double check, it's embedded in a timer, but that should be ready soon too.

**Pull request merged**
