### PR TITLE
msx1_cart.xml: Add 4 not working items

### PR DESCRIPTION
**Pull request by wilbertpol**
New NOT_WORKING software list additions
------------------------------------------
DPQ-280 Quick Disk Drive [hans otten]
DPQ-280 Quick Disk Drive (alt) [hans otten]
QDM-01 Quick Disk Drive [hans otten]
VY-0002 Quick Disk Drive [hans otten]

### CODE REVIEW

**Comment by simzy39** [comment]
You put 'Sanyo' as the QDM-01 Quick Disk Drive publisher, but is this correct? 
I don't think Sanyo made a Quick Disk Drive interface: https://www.msx.org/wiki/Category:Quick_Disk_Drive_Interfaces

Maybe this is: AVT QDM-01, Logitec QDM-01, or Reis-Ware QDM-01

**Comment by wilbertpol** [comment]
> You put 'Sanyo' as the QDM-01 Quick Disk Drive publisher, but is this correct? I don't think Sanyo made a Quick Disk Drive interface: https://www.msx.org/wiki/Category:Quick_Disk_Drive_Interfaces
> 
> Maybe this is: AVT QDM-01, Logitec QDM-01, or Reis-Ware QDM-01

To be honest, I do not know if it is correct. I got the dumps from hans otten's site where it is listed as coming from a Sanyo device.

**Comment by simzy39** [comment]
How can I email you or message you schematics or docs?

**Comment by wilbertpol** [comment]
> How can I email you or message you schematics or docs?

Try 'judge' on the mame forum at bannister or the mame discord.

**Comment by ArcadeShadow** [comment]
Not directly related with this PR but could you fix the parent/cloneof relationship for those set:
sensha / sensha21
startrek / startreka
transbal / transbal132a

IMO, they should be parent/cloneof related.

**Comment by wilbertpol** [comment]
> Not directly related with this PR but could you fix the parent/cloneof relationship for those sets: sensha / sensha21 startrek / startreka transbal / transbal132a
> 
> IMO, they should be parent/cloneof related.

Yes, they should; I missed those when I added them. Thanks.

**Pull request merged**
