### PR TITLE
nichibutsu/cclimber.cpp: Improves Swimmer driver and adds a new game set

### PR DESCRIPTION
**Pull request by NeilBakersTech**
Hey folks. I was granted access to a private arcade collection to repair some game boards and an unusual one caught my eye.

The game board stack was a Tehkan Swimmer, the same as one in my own collection but with modifications to the CPU and Video layers.

Using a Willem programmer I was able to read the EPROM data as 2764 and 2764 types and a grep of MAME code returned no match on the checksums.

When trying to add it to MAME it did not work when renamed as Swimmer and creating replacement EPROMs for my Swimmer game board yielded no results either.

I spent some time making technical notes from my Swimmer game board to understand the working of the board and source of the problem. These notes did not allow the game to run either but led me to see some problems with MAME and the emulation of Swimmer.

Foremost there are numerous places on the game board where address lines are not fully decoded resulting in what MAME calls mirroring. It can be seen on the input section where MAME had separated ports. I have corrected these.

Specific to Swimmer and not Crazy Climber is the sound latch handling. The Swimmer board is a Tehkan game board and uses the same flp-flop configuration with LS273 as found on Bomb Jack for clearing sound latch on read.

After fixing these mistakes in MAME and performing a routine cleaning of the source files I began narrow down what was required to run this new ROM.

Without ongoing access to the modified game board I am unable to determine how the alterations work on hardware but they provide 2 new RAM areas over the standard Swimmer configuration. One of them bypasses the fixed color generation circuits of the original by providing dynamic colors with 3 bits per gun while the other acts as scratch RAM.

The ROM started up as a game I had not heard of before 'Au' with a copyright of 1983

I have begun understand the Dipswitch requirements but could not discover the meaning for a couple. Is there an AI game code analysis tool to help with them or is it a labor intensive process?

Please thank Neill Baker Tech if you decide to include my changes.

### CODE REVIEW

**Review by angelosa — CHANGES_REQUESTED** [review]
1. this _will_ fail CI because there's no reference between the added game for `mame.lst`
2. glueing together a PR with a cleanup AND a new romset should be already be a good reason to outright reject this. Choose one plan and stick with it to begin with.
3. OP message needs to be edited for a whatsnew friendly body.

**Comment by NeilBakersTech** [comment]
> 1. this _will_ fail CI because there's no reference between the added game for `mame.lst`
> 
>     2. glueing together a PR with a cleanup AND a new romset should be already be a good reason to outright reject this. Choose one plan and stick with it.

sod off and take your attitude elsewhere you odious little shit

**Comment by angelosa** [comment]
> > 1. this _will_ fail CI because there's no reference between the added game for `mame.lst`
> >    
> >    2. glueing together a PR with a cleanup AND a new romset should be already be a good reason to outright reject this. Choose one plan and stick with it.
> 
> sod off and take your attitude elsewhere you odious little shit



> > 1. this _will_ fail CI because there's no reference between the added game for `mame.lst`
> >    
> >    2. glueing together a PR with a cleanup AND a new romset should be already be a good reason to outright reject this. Choose one plan and stick with it.
> 
> sod off and take your attitude elsewhere you odious little shit

Well Mr. _random-first-time-github-contributor_ that happens to own an **incredibly rare pre-JAMMA romset**, **happened to do non-trivial C++ subclassing** and at the same time seemingly **didn't read the [contributing guidelines](https://wiki.mamedev.org/index.php?title=Submitting_Source_Code#Submitting_ROM_or_disk_dumps)**, your story doesn't hold together on its feet and I refuse to run the CI pipeline given I know it _will fail_. 

Are you gonna comply or you are pretending somebody else has to do the job for you?

**Comment by NeilBakersTech** [comment]
> > > 1. this _will_ fail CI because there's no reference between the added game for `mame.lst`
> > >    
> > >    2. glueing together a PR with a cleanup AND a new romset should be already be a good reason to outright reject this. Choose one plan and stick with it.
> > 
> > 
> > sod off and take your attitude elsewhere you odious little shit
> 
> Well Mr. _random-first-time-github-contributor_ that happens to own an **incredibly rare pre-JAMMA romset**, **happened to do non-trivial C++ subclassing** and at the same time seemingly **didn't read the [contributing guidelines](https://wiki.mamedev.org/index.php?title=Submitting_Source_Code#Submitting_ROM_or_disk_dumps)**, your story doesn't hold together on its feet and I refuse to run the CI pipeline given I know it _will fail_.
> 
> Are you gonna comply or you are pretending somebody else has to do the job for you?

Non-trivial subclassing? My CS degree and 37 years of EE and critical system maintenance experience say otherwise.

I had heard on the grapevine the community here were condescending and to be avoided but didn't expect to experience it with such a simple discovery.

Good luck in the future. You'll need it.

**Comment by rb6502** [comment]
I don't know what's going on here, but the changes actually look decent at a quick look.

And combining adding a new set with a cleanup pass is a perfectly normal thing to do, especially in a driver that's as much of a mess as Crazy Climber.  If it was a situation where those two operations spanned 17 commits in a single PR then I'd be peeved.  If the CI passes aside from the mame.lst problem I'll give it a closer look.

**Comment by angelosa** [comment]
> Non-trivial subclassing? My CS degree and 37 years of EE and critical system maintenance experience say otherwise.
> 
> I had heard on the grapevine the community here were condescending and to be avoided but didn't expect to experience it with such a simple discovery.
> 

Well, care to upload a PCB picture of this?

**Comment by wd40yasu** [comment]
uploaded video footage from Tecmo Arcade Game Chronicle
to ftp/videos/VTS_05_1(TEHKAN Au).VOB

**Comment by happppp** [comment]
I don't like angelosa's condescending feedback much either, but you'd be a champ if you had replied to it professionally. I don't care about the backstory. Next time you leak a hoarded ROM, please be more discreet.

The source code is fine. IMO it can be merged, we can adjust mame.lst ourselves if you don't want to.

**Comment by mamehaze** [comment]
> I don't like angelosa's condescending feedback much either, but you'd be a champ if you had replied to it professionally. I don't care about the backstory. Next time you leak a hoarded ROM, please be more discreet.
> 
> The source code is fine. IMO it can be merged, we can adjust mame.lst ourselves if you don't want to.

FWIW I don't think this is a 'leaked' ROM at all; if you take a look at https://www.tilt.it/deb/visti-it.html it indicates that the game was on location in a few places in Italy.  The most likely source is there IMHO, much as we've seen Alone Shettle Crew, Vampire and some others turn up in the last year; all games known to have been operated in Europe.

My betting here is that's been some warehouse raid or auctioning off of assets recently; Occam's razor and all that.  Would even make sense for somebody who has picked up some PCBs be looking to have them repaired if possible.

If something has been seen / played in Europe it's probably not as rare as some would have you believe, it's pretty evident at this point that Europe ended up being a dumping ground for PCBs / cabinets that weren't likely to do well in Japan (or otherwise a place where location tests got bootlegged)

**Review by rb6502 — APPROVED** [review]

**Comment by mamehaze** [comment]
I'd say bootleg (or Swimmer conversion) not hack, OP indicates it was a Swimmer PCB, most bootlegs are hacked.

**Comment by happppp** [comment]
IMO OP is not trustworthy =)

**Comment by mamehaze** [comment]
> IMO OP is not trustworthy =)

I don't really seem to see why not.  They demonstrated a good enough knowledge about the PCB in question, even if Kale seems to have driven them off with his initial hostile reply.  If they've said it's a Swimmer PCB I'd trust that, which almost certainly makes it a bootleg.

**Comment by happppp** [comment]
I have no way to prove it one way or another, but I'd say the chance is higher that this backstory is fabricated rather than genuine. I won't take Neill's word for it.

**Pull request merged**
