### PR TITLE
sms.xml: Added 2 working items

### PR DESCRIPTION
**Pull request by ArcadeShadow**
New working software list additions
--------------------------------------------
Gemitas [SMS Power!]
Sydney Hunter and the Sacred Tribe [No-Intro]

Renamed set [jewelstn] to [jeweljon] and renamed description to "Jewel Jones"

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
When adding items, please keep the sizes and offsets together – it makes it much easier to see how multiple ROMs are loaded.

Also, you only seem to have included the offset for one of these.  There are at least a few Master System games with multiple ROM chips, and at least the vast majority of items in the software list seem to include an offset even if there’s only one ROM.  Maybe include the offset for both for consistency?

**Comment by ArcadeShadow** [comment]
Added the offset in both set. I kept the `size` and `offset` together, but I think for consistency it should be done the same treatment for the existing sets.

**Comment by cuavas** [comment]
> Added the offset in both set. I kept the `size` and `offset` together, but I think for consistency it should be done the same treatment for the existing sets.

Yeah, but that would be a huge change, and there’s also the issue of mixing decimal sizes with hex offsets to think about.

**Review by cuavas — COMMENTED** [review]
Please use hex offsets – all the existing items in this software list that have non-zero offsets use hex offset, and it makes more sense in binary addressing schemes.

**Comment by ArcadeShadow** [comment]
done it.

**Pull request merged**
