### PR TITLE
nintendo/vsnes.cpp: More cleanups of INPUT_PORTS.

### PR DESCRIPTION
**Pull request by 0kmg**
- Used macros for the common repeated definitions of joystick, coins, etc.
- Player buttons are "B" and "A", like the real panels. Start buttons renamed to "Select 1 (Blue)", "Select 2 (Green)", etc.
- bnglngby, iceclimb, jajamaru, nvs_machridera, supxevs, tkoboxng: Removed as many modifications from the base VS. machine IO ports as possible.
- Adjusted coin PORT_IMPULSE closer to hardware. All games now work with this and use the generic inputs.

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
I’m not sure this is a beneficial change:
* Custom names for start buttons makes it less obvious what they do
* Custom names for player buttons break localisation
* Having stuff several macros deep makes it more confusing to read

**Comment by 0kmg** [comment]
Okie dokie. The macros were just to make it more concise and obvious what was the same and what was being "reversed". But if they're more confusing.

For the start buttons though, the problem is they aren't start buttons at all. They're context-sensitive select buttons "1", "2", "3", and "4". Sometimes games refer to them just with colored button images (VS.SMB), sometimes just by circled number (SkyKid), often as a colored button with the number on it. Yes, 1 and 2 most often have the obvious meaning, but MAME reports 3 as "3 Players Start" when it NEVER has that meaning—there are no 3 player games. In Vs. Tennis for instance 3 is a 2 player singles match.

**Comment by cuavas** [comment]
Oh interesting.  I guess they need special names then.

**Comment by 0kmg** [comment]
I was going to ask for feedback on the naming anyway. The Vs Tennis manual calls them "1", "2", "3", "4". Schematics call them Select 1, Select 2, etc. As mentioned the games have various ways of indicating their use. As another example, the Vs. Golf games that use 4 buttons show them all as colored numbered buttons, and they select: (1) 1PvsC stroke, (2) 2P stroke, (3) 1PvsC match, (4) 2P match.

**Comment by cuavas** [comment]
Maybe call them “Start 1 (Blue)”, etc. as they do seem to be used to start games?

**Comment by 0kmg** [comment]
Yeah, I think they were only ever used to choose a game type at start. Could have made a nice color puzzle game :)

**Comment by ICEknigh7** [comment]
> Schematics call them Select 1, Select 2, etc.

Maybe "Select 1 (Blue)", etc, since that seems to be the official naming.

**Comment by 0kmg** [comment]
I went with ICEknigh7's naming. There's the reason he cites. But also, the more subtle reason is that on a typical system the start buttons generally do start the game. In the DualSystem games though both sides must hit them. The second side is prompted to make a selection and opt in, even after the first side makes theirs. At least that's what I told myself to get over my indecisiveness :)

**Comment by 0kmg** [comment]
I think maybe I misunderstood bullet point 2. Is this referring to P1/P2 not being localized when using custom names for buttons A and B? Does "%p" work fine outside of slotted controllers?

**Comment by 0kmg** [comment]
I reinstituted macros, 1 level deep, and used "%p". Hopefully this is ok now?

Anyway, the main value of this PR is all the minor details trying to move the PORT defs away from bespoke stuff per game to something uniform that reflects the hardware—I've done quite a bit of investigating on that front.

**Pull request merged**
