### PR TITLE
Add clang/Windows CI build

### PR DESCRIPTION
**Pull request by invertego**
Same idea as the Linux CI build extended to Windows

### CODE REVIEW

**Comment by cuavas** [comment]
I'm not sure we want to do this at the moment, considering the resource usage of all the other CI builds. We've already had contributors banned from GitHub CI for excessive resource usage, and it can take quite a while for jobs to be allocated a virtual machine already at busy times.

**Comment by angelosa** [comment]
I believe compiling with Clang on Linux is enough too, this will add pointless extra job stress.

**Comment by invertego** [comment]
The win/clang build was recently broken, then fixed, then broken again by another change the very next day.  This wasn't caught by CI because the breaks were in Windows specific OSD code. Maybe that's not typical, but I wouldn't call this pointless. Maybe just too low value to justify the cost.

**Comment by galibert** [comment]
Could you change it into a tiny, or even single-driver build?  Testing compilation of the windows osd with clang makes sense.

**Comment by galibert** [comment]
Damn, it's still 64mn with the dummy target.  Vas, can we afford it or is it going to hit contributors?  Should the linux/clang build be dummy too since macos covers the drivers?  Or possibly the linux/gcc too, since windows/gcc covers them?

**Comment by cuavas** [comment]
> Damn, it's still 64mn with the dummy target. Vas, can we afford it or is it going to hit contributors?

Why not change the subtarget to `tiny` rather than `dummy`, or maybe even `virtual`?  That would reduce resource usage more, as `dummy` compiles all the devices.

But the thing is, an unstripped MAME build is always going to be pretty big, just from libemu.  My unstripped build with nintendo/gameboy.cpp, nintendo/snes.cpp and sony/psx.cpp is 100MB.  It’s possible to strip the binaries, but that would make them less useful when people download the artefacts.

> Should the linux/clang build be dummy too since macos covers the drivers? Or possibly the linux/gcc too, since windows/gcc covers them?

We need at least one of the Linux builds to include everything, as it’s used for the ORM check.  Maybe limiting the Linux clang build to a subtarget is a good idea?  I dunno.

**Comment by invertego** [comment]
Switching to the `tiny` subtarget reduced the build time to ~29 minutes. I'm looking for suggestions at this point.
1) Is this good enough, or should `virtual` be tried next? Based on local build times it seems unlikely to shave more than a few minutes off of `tiny` builds.
2) Should I go ahead and move one of the Linux CI builds to the `tiny` subtarget as part of this PR? Looking at historical data, the clang builds are faster more often than not, with the gcc builds sometimes running > 3 hours.

**Comment by firewave** [comment]
What about `ccache`?

Sorry for posting such a late reply.

**Comment by cuavas** [comment]
> What about `ccache`?

More trouble than it’s worth, and more stuff that can go wrong.

**Comment by firewave** [comment]
> More trouble than it’s worth, and more stuff that can go wrong.

That's what I thought as well. But it turned out if you are using GCC on non-EOL Linux with make it is no trouble at all - at least in terms of GitHub actions. See https://github.com/danmar/cppcheck/commit/070bae871a515b71df05bd4c7b2fb897aca0c591.

With a project of the size of MAME the GitHub cache might be an issue though.

But fair enough. Just thought it might be worth mentioning.

**Pull request merged**
