### PR TITLE
Adding support for stable controller id's

### PR DESCRIPTION
**Pull request by tverona1**
This change adds support for mapping device to controller id. This allows for stable controller ids even if USB devices are plugged / unplugged, system is rebooted, etc.

An example of defining a mapping is:
```xml
<mameconfig version="10">
    <system name="default">
        <input>
            <mapdevice device="VID_D209&amp;PID_1601" controller="GUNCODE_1" />
            <mapdevice device="VID_D209&amp;PID_1602" controller="GUNCODE_2" />
            <mapdevice device="XInput Player 1" controller="JOYCODE_1" />
            <mapdevice device="XInput Player 2" controller="JOYCODE_2" />
            ...
```
See documentation for additional details.

### CODE REVIEW

**Comment by cuavas** [comment]
Have you built with `OSD=sdl` and tested?  Does the configuration persist properly when MAME writes out the the cfg file?

**Comment by MooglyGuy** [comment]
A dev tried it on his arch linux system:

<dev> doesn't seem to work with sdl
<dev> Input: Adding Mouse #0: System mouse
<dev> Mouse: Registered System mouse
<dev> Mouse: End initialization
<dev> is all i get

**Comment by bradhugh** [comment]
The SDL OSD has its own name-based mapping for joysticks.  How is this different from that?  Ultimately, we need to decide if this needs to be handled at the OSD layer or core input system.

**Comment by tverona1** [comment]
Thanks for the feedback, guys! Let me address them one by one:
1. [@cuavas] Have you built with OSD=sdl and tested?
[tomer] Yes, it works as expected. I'm providing the output below, which demonstrates remapping controllers in sdl mode:
```
Keyboard: Start initialization
Input: Adding Kbd #0: System keyboard
Keyboard: Registered System keyboard
Keyboard: End initialization
Mouse: Start initialization
Input: Adding Mouse #0: System mouse
Mouse: Registered System mouse
Mouse: End initialization
Joystick: Start initialization
Input: Adding Joy #0: XInputController#1
Joystick: XInput Controller #1
Joystick:   ...  6 axes, 11 buttons 1 hats 0 balls
Joystick:   ...  Physical id 0 mapped to logical id 1
Input: Adding Joy #1: XInputController#2
Joystick: XInput Controller #2
Joystick:   ...  6 axes, 11 buttons 1 hats 0 balls
Joystick:   ...  Physical id 1 mapped to logical id 2
Input: Adding Joy #2: ATRAKDevice#2
Joystick: ATRAK Device #2
Joystick:   ...  2 axes, 8 buttons 0 hats 0 balls
Joystick:   ...  Physical id 2 mapped to logical id 3
Input: Adding Joy #3: ATRAKDevice#1
Joystick: ATRAK Device #1
Joystick:   ...  2 axes, 8 buttons 0 hats 0 balls
Joystick:   ...  Physical id 3 mapped to logical id 4
Joystick: End initialization
Region ':user1' created
Starting No Driver Loaded ':'
  (missing dependencies; rescheduling)
Starting Video Screen ':screen'
Optional device ':screen:finder_dummy_tag' not found
Starting No Driver Loaded ':'
Input: Remapped Joy #0: ATRAKDevice#1
Input: Remapped Joy #1: ATRAKDevice#2
Input: Remapped Joy #2: XInputController#1
Input: Remapped Joy #3: XInputController#2

```

2. [@cuavas]  Does the configuration persist properly when MAME writes out the the cfg file?
[tomer] Yes, I verified changing control mappings within MAME and that it is persisted properly.

3. [@MooglyGuy] A dev tried it on his arch linux system. doesn't seem to work with sdl
[tomer] I'm not sure what is the issue or if it related to my changes. I've verified on Windows - see the output above. My changes should agnostic of platform. Is that the entire output (it looks like it did not proceed far enough to hit the remapping code)? Does it work w/o the changes?

4. [@bradhugh] The SDL OSD has its own name-based mapping for joysticks. How is this different from that? Ultimately, we need to decide if this needs to be handled at the OSD layer or core input system.
[tomer] With SDL OSD, when name-based mapping is provided, I agree this is probably not required. This is more to support non-SDL, where MAME does its own enumeration of devices w/o the ability to specify named-based mappings. Even with SDL, this change allows you to remap when you do not explicitly specify named devices in command line (see output above to example of SDL mode). (As a side note, one option is to expose these mappings as command-line options [similar to what is possible in SDL mode] but it seems more consistent / easier to specify the mappings alongside control configs in the config file. Let me know your thoughts.)

Cheers!

**Comment by tverona1** [comment]
Hey guys, any other questions / feedback before we merge this in?

**Comment by rb6502** [comment]
This breaks Linux, it's going in over my dead body.

Also, we need Brad to decide what the proper way to do this is.

**Comment by tverona1** [comment]
No need for dead bodies chief, not my intention to break Linux. The change is very low risk and should not be platform specific, so I'd like to try to repro to understand what's breaking. Can you provide: distro you tried it on, verbose output, whether you specific devicemap settings?

**Comment by startaq** [comment]
I was looking for an additional identifier, like "HID-compliant mouse (\\?\HID#VID_045E&PID_0053#7&18297dcb&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd})" in the example. This didn't happen with SDL, so I assumed it doesn't work there. Other than that, it seems to work normally in Arch Linux. I don't have a joystick to test.

**Comment by tverona1** [comment]
Thanks @startaq for confirming that Linux works. I have now also verified on Ubuntu. SDL doesn't support raw input which is what my example had - to test it, you'd have to use whatever devices are recognized in SDL mode.

Note the change itself is super simple: It just allows the user to specify device index based on a device name to support consistent mapping. It doesn't change how or what devices are recognized. I've verified with Windows & Linux and with / without SDL. The inputs I verified include two lightguns, two xbox 360 gamepads and xarcade tank.

@bradhugh what's your take on whether this should be supported by core input system or at OSD layer? As the change is now (at core input system), it is agnostic to / works with any OSD implementation (both SDL & Windows native). I'm fine with either decision but it would be nice to address this issue which is painful & seems prevalent (at least on windows).

**Comment by rb6502** [comment]
@startaq Testing this patch without a joystick is roughly like testing an audio patch without a sound card.  Please do not assist Windows-supremists like the OP from trying to destroy my port.

**Comment by tverona1** [comment]
Hi @rb6502 thanks for the feedback. I've also verified on Linux (and Windows and with multiple input devices - see above). The change is working 100% on Linux.

@rb6205, did you actually try this change and run into any issues?

**Comment by bradhugh** [comment]
I will work on testing this today. Will let you know if I see any issues on Linux or OSX.

**Comment by bradhugh** [comment]
So I was trying to test this. It seems to work ok without any config.  I tried however to enter the mapping in the config file. Yes, I was kind of trying to break it, but it seems a reasonable scenario.  I tried plug in a single joystick and yet map it to JOYCODE_2 (Player 2).  In this scenario it crashes in m_device[newindex]->set_devindex(newindex);

Can you take a look?

**Comment by bradhugh** [comment]
Also, as @cuavas mentioned, if you go into the UI and choose "Save configuration" it overwrites any controller mappings which is not desired.  Please see if you can work that out as well.

**Comment by tverona1** [comment]
@bradhugh thank you very much for catching these issues! I've submitted the fix for both, please take a look.

Changes are:
1) I missed a null check when mapping to a null controller index.
2) I'm now restricting devicemap setting to controller config file (I missed this earlier because I was only verifying with controller config file). I experimented with allowing devicemap to be specified in default.cfg & game configs and with saving the configuration, but the behavior was not ideal (default.cfg would always get populated with devicemap settings upon exit). I then realized that it actually makes more sense to restrict this option to controller config file since these are a controller-specific settings and this now consistent with controller "remap" option which has the same restriction.

**Comment by bradhugh** [comment]
Ok, everything is working as I'd expect. I think this is fine for this layer and I think we may be able to do away with the SDL OSD mapping feature since this one could be universal.

One nagging issue I have is one that is causing some pain in other scenarios.  Right now, Mame Uniquely identifies controllers and input devices that aren't necessarily unique.  As you had to hack out the improve name functionality in rawinput, we may have to do something similar in other areas.  What I'd propose is that we add a new property on input_device called something like "unique_id()", "immutable_id()" or simply "id()" which would allow the osd layer when creating a device to pass a friendly display name along with a unique identifier.  You could then use this property for mapping devices instead of the display name.  I feel like "name" isn't descriptive enough to indicate that it needs to be unique.

I'm ok with taking this as is if you're ok with me changing it later to use some unique id for the mapping.

**Comment by cuavas** [comment]
I'm not OK with accepting it "on the condition that it's fixed later".  That never ends well.

**Comment by tverona1** [comment]
@bradhugh, that sounds fine to me and I agree that supporting unique controller identifiers is the right evolution. 

@cuavas, what Brad is suggesting is I think a bit more longer term and not something that is blocking current functionality. I think we would need to figure out how to generate unique controller IDs for each device type (for example I'm not sure how to come up with a unique ID for raw input other than (maybe some part of) the raw input name itself) - unless we just wanted to add a property and plumb through the current . It doesn't sound like

**Comment by tverona1** [comment]
Hey guys, I have a change that adds id() to input_device (and device_info) and plumbs it through OSD to input layer per Brad's feedback. For raw input, it is using raw input name as the id (and we are now preserving friendly name for device name as was done before). For all other devices, the device id is falling back to device name which we can evolve over time (note this change does not enforce uniqueness but for the non-raw-input devices I have tested the name does seem to be unique).

@bradhugh let me know if you'd like me to add this change to this pull request.

**Comment by bradhugh** [comment]
Yes, by all means - add it if you've already done the work :)

**Comment by tverona1** [comment]
@bradhugh cool, just pushed the change. Please take a look.

**Comment by bradhugh** [comment]
Looks good. I'll double-check on Linux and OSX which I expect to be fine - then merge.

**Comment by tverona1** [comment]
Awesome, thank you!

**Comment by Tafoid** [comment]
Quite possibly related errors in release 0.178 in Window (looks like Windows 10 since -verbose shows xaudio2 as default audio:   http://forum.mamedev.org/viewtopic.php?f=14&t=122&p=408#p407

**Comment by bradhugh** [comment]
Hmm.  I will take a look.

**Comment by bradhugh** [comment]
I think this is unrelated to this change.  The backtrace provided seems believable. It means that somewhere during windows_osd_interface::update we processed more random window messages (winwindow_process_events).  One of those window messages was destined for the output window (output_window_proc) and the message was om_mame_get_id_string.  We crash in output_win32::send_id_string but I'm unable to readily resolve the offset to see where we are dereferencing the value 00000030.

**Pull request merged**
