### PR TITLE
Throw a fatal error if combination of bgfx video and wayland videodriver has been detected

### PR DESCRIPTION
**Pull request by belegdol**
This should fix issue #9852, pending @substring's confirmation.

### CODE REVIEW

**Comment by rb6502** [comment]
In the interests of not introducing hidden magic behavior, I'd actually prefer it simply osd_fatalerror()s in the bgfx/wayland case.

**Comment by belegdol** [comment]
You mean something like this? This means that using `auto` for both `video` and `videodriver` is going to result in a fatalerror on Fedora, and possible more distros if wayland is made default by upstream SDL.

**Comment by substring** [comment]
Tested ok on KMS and X11

**Comment by substring** [comment]
So ? Are we stuck on this ?

**Comment by belegdol** [comment]
It is down to what is preferred:
- first commit if good experience out of the box on fedora is worth more than complexity introduced
- both commits if code simplicity is values higher than UX ootb on Fedora.

I am carrying the revert of the second commit as a downstream patch in Fedora as long as Fedora is the only distro defaulting to Wayland for SDL.

**Comment by cuavas** [comment]
I’m deferring to @rb6502 on this. IMO it’s a mess created by Fedora and want MAME to carry as little technical debt and/or issues pushed onto users of other distros as a result of working around it.

**Comment by belegdol** [comment]
I would suggest to merge this PR in its entirety then and I will revert the second coming downstream. If upstream SDL ever starts defaulting to Wayland, we can revisit this issue.

**Pull request merged**
