### PR TITLE
hooked up kicknrun MCU [dink]

### PR DESCRIPTION
**Pull request by DavidHaywood**
- hooked up kicknrun MCU [dink]
- split up kikikai class [David Haywood]

note, I haven't tested his 6801 changes with anything else, but they're said to be based on study of the manual.  changes originally posted at https://github.com/finalburnneo/FBNeo/commit/2b040632a758eecae5d4bf1f54cfcc6a8cd9caf2#commitcomment-38927617

### CODE REVIEW

**Comment by happppp** [comment]
6801 change looks like a revert of AJR's recent fix?
OCF2 is cleared on write.

**Comment by DavidHaywood** [comment]
the hookup is based on the bubble bobble one, which doesn't use them...  if drivers aren't even in sync with the core that's hardly our fault :/

**Comment by happppp** [comment]
Let me repeat: here's the same fix dink did, AJR applied it.
You reverted the part for timer compare reg 2.
https://github.com/mamedev/mame/commit/4ae11dd8608c48770c9daebde3817aa415401bf2

**Comment by DavidHaywood** [comment]
alright, well I've reverted this, but consider it abandoned, I was only trying to help, but it seems more is wanted than that.

**Comment by happppp** [comment]
What?

There must be a misunderstanding.
The 6801 fix that dink did is good. I notified AJR about dink's bug report and he applied it. Your PR is probably based on an older commit and therefore partially reverted this fix by mistake.

**Comment by DavidHaywood** [comment]
Well my point was more that I don't want to be updating it beyond this scope, if it needs further work on using callbacks etc. then I'd rather just leave it in the hands of somebody else.  (as Bubble Bobble will also need updating)  I was simply trying to help with this, not become actively involved beyond the basic cleanups.

**Comment by happppp** [comment]
I pressured you into correcting your 6801 change, OCF2 isn't even part of vanilla 6801(it's HD6301X & co). Yeah, that was a "core changes not wanted".

The unneeded ports reimplementation is not as big an issue, and indeed it was already there in the 1st place.

**Comment by DavidHaywood** [comment]
it really shouldn't need 2 video update functions either, because the games are a ROM swap (with one adding a sub-board for the extra z80) but that's also a bit outside the scope of what this PR is trying to achieve (I have a feeling the video can probably be shared with other things too, many even Bubble Bobble as several comments indicate it came from there in the first place)

**Comment by MooglyGuy** [comment]
Dave, nobody's saying that your changes are bad or that you're doing anything malicious. It's just that due to Git being a pain in the arse to deal with - something well outside of what could be characterized as your fault - your changes seem to have been based on an older revision of the relevant files.

That's literally all anyone is trying to point out here. Yeah, there are some technical aspects that can be done better, but nobody's flagging that as a reason to reject the PR. because there's plenty of tech debt in MAME already. It would just be preferable to not have recent changes inadvertently reverted out by applying the changes. Surely you can see the logic in that.

**Comment by DavidHaywood** [comment]
well yeah, Dink provided the files as a zip, rather than as a diff, so I guess they were out of sync somehow.

**Comment by MooglyGuy** [comment]
Alright, so let's talk to dink and figure out how we can improve the workflow. No sense in throwing the baby out with the bathwater.

**Comment by MooglyGuy** [comment]
And true, yeah, there were some comments made as to how the changes could be improved later, since it's a good way of documenting future plans. Nobody was saying the PR would be rejected except for the inadvertent reversion of other changes.

**Comment by dinkc64** [comment]
DavidHaywood, thanks for helping get this up and running :)
So all that basically needs to be done now is to remove the m6801 changes from this PR and all should be well, eh?

**Comment by happppp** [comment]
Hi dink, yes the 6801 changes were reluctantly taken out before haze
realized it was a misunderstanding, I think it's all good now. Another pair
of eyes can press the merge button.

**Comment by DavidHaywood** [comment]
the m6801 changes were removed already, it should be good to go.  other tweaks can be made later now that the need for them has been highlighted, but this part is good I think.

**Comment by dinkc64** [comment]
thanks guys :)

**Comment by Robbbert** [comment]
I'll be the bunny and commit this. I do not know if it will compile or run, but we can fix that later.

**Pull request merged**
