### PR TITLE
Add myself to the taito_f3_v.cpp header

### PR DESCRIPTION
**Pull request by DavidHaywood**
I've done some bits of work on this over the years, including, but not limited to, fixing up the billboards in the football games.

### CODE REVIEW

**Comment by happppp** [comment]
@DavidHaywood it's this commit, right?
https://github.com/mamedev/mame/commit/05bbe38c4bfa5264bf6454b8d2350a2e91d64a4f

In my neutral opinion, just looking at the amount of code relative to the whole file, that one is not sufficient for making yourself co-copyright holder of this file.
Show me more proof that you authored let's say at least 20% of this file.

In my not neutral opinion: This looks like a way to give yourself the legal right to go after license violations of this file. Why should we get involved in this drama when @galibert said this Elevator Action 2 hack was too insignificant to be called a violation.

**Comment by DavidHaywood** [comment]
I personally believe the effort put into researching this, and coming up with a solution to the problem counts.  This was a significant amount of research, and a solution which can be tied to my opinion on how things work.

It might be a rather small change, but it is not mechanical, it required me to figure out a solution which worked within the way in which the existing emulation worked, without breaking anything else.  For a piece of hardware as complex as this, even a relatively small change requires an extensive amount of work.

Without my work the football games in this driver would still be incorrectly stretching the pitch display where the crowd should be, and missing parts of the goals.

**Comment by DavidHaywood** [comment]
As for the other issue, the code in question certainly has it's own unique signature, it again is not mechanical, it is the result of a creative process, albeit one that has resorted to ugly hacks to not break the rest of the driver.

If I'm asked, on a professional level, to perform code analysis, to make sure code hasn't been stolen from somewhere else, this is the kind of highly questionable and unique signature I'll look for, as it's the kind of thing that survives mechanical obfuscation of code.  It's traceable, and identifiable, and therefore the original license under which is was distributed is known.  It should not be contaminating BSD licensed files.

**Comment by happppp** [comment]
research != amount of code.
Remember the Time Crisis invincible heli bug? I spent hours upon hours hunting that down, and finally found the cause and fixed it. A couple of lines in the m68k core. Do I have the guts to make copyright holders of that cpu core "Karl Stenerud, hap"? No way.

**Comment by DavidHaywood** [comment]
That's your own preference.  Had you been hired by a company to fix that bug, would you be expected to be paid and credited?  I'd hazard a guess your answer becomes 'yes' in that case.

**Comment by happppp** [comment]
Alright, I'll stop trying. I'm too biased anyway.
In the future regarding this license violators hunt, please don't say stuff like "MameDev had no problem accepting this missing accreditation", it's not unanimous.

**Comment by cuavas** [comment]
> That's your own preference. Had you been hired by a company specifically to fix that bug, would you be expected to be paid and credited? I'd hazard a guess your answer becomes 'yes' in that case because without your work, the product would not be able to ship.

That’s not how copyright works, though.  It’s about the amount of creative content in the work produced.

**Comment by DavidHaywood** [comment]
Indeed, which I do then later outline, as I didn't feel the example hap provided *was* creative.

These solutions were on the other hand, part of a creative process.  A different person would have, in both cases, likely concluded something different, and come up with different solutions.

Even at the time I had to make a creative decision over which one to use, I had a number of different approaches available each with pros and cons.

**Comment by DavidHaywood** [comment]
For the other hacks, I'd certainly call them creative, but I wouldn't be using that term in a positive sense.  Those are based around pure make-believe logic that exists only in the head of the person that authored them.

The changes might look small in context of the file, but in a smaller driver, say [misc\gumbo.cpp](https://github.com/mamedev/mame/blob/master/src/mame/misc/gumbo.cpp) they would stand out more.  I'd deem the changes made here (both mine, and the other hacks) to be a larger creative work than that *entire* driver.

**Pull request merged**
