### PR TITLE
Fix TKG-02 (Radarscope Conversion) palette.

### PR DESCRIPTION
**Pull request by trebor68**
Fix TKG-02 (Radarscope Conversion) palette.

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
Can you please provide a reference for this change?  Also, please make your pull request title descriptive.

**Comment by trebor68** [comment]
See MAME Testers ID 05052: https://mametesters.org/view.php?id=5052

**Comment by einstein95** [comment]
looks like `src/mame/atari/a7800.cpp` had line endings changed or something

**Comment by trebor68** [comment]
The original code has the PAL region palette as an approximation, via a reshuffle of the NTSC palette.

The update to a7800.cpp provides two separate palettes, one for NTSC and the other for PAL, interpreted and calibrated per the official 7800 CPS Diagnostic Test Cartridge.

**Comment by rb6502** [comment]
Is it verified on real hardware that the RadarScope conversion matches the dedicated hardware version?  And doesn't this change then re-break RadarScope?

**Comment by cuavas** [comment]
Besides whatever you did to make the whole a7800.cpp appear to be changed, unrelated changes should not be combined in this pull request.

That aside, [MT05052](https://mametesters.org/view.php?id=5052) doesn’t provide any evidence that the current behaviour is wrong.  It simply says that the fix for [MT05018](https://mametesters.org/view.php?id=5018) changed the colours.

Without any real supporting evidence, this pull request will be closed.

**Comment by trebor68** [comment]
Intention was not to combine request.  That inadvertently occurred with the outstanding pull request from April still opened.  No worries, closed request.

**Comment by trebor68** [comment]
Regarding the change to a7800.cpp, per the diff, see old Lines 460 though 596 compared to the submitted new Lines 460 through 692.  Unsure how that was interpreted as "had line endings changed or something".

**Comment by einstein95** [comment]
> Unsure how that was interpreted as "had line endings changed or something".
Because GitHub is reporting the entire file as changed

**Comment by Lord-Nightmare** [comment]
if you type `git config core.autocrlf true` while in the shell in the directory of your mame repository, it might fix it in the future

**Comment by trebor68** [comment]
How the red cabinet/TKG-02 Conversion should look - as it was under MAME 0.147: https://www.youtube.com/watch?v=C2oHHtRar_Q

**Pull request closed without merging**
