### PR TITLE
Show MAME's program name lowercase in help output.

### PR DESCRIPTION
**Pull request by jmallach**
As the name of the binary is normally installed lowercase, the help
output should also reflect this.

### CODE REVIEW

**Comment by jmallach** [comment]
There is a variable called exename, maybe it could be used instead. In fact, it is used in the output of mame -showusage. Please let me know your thoughts about this.

**Comment by mmicko** [comment]
better use exename in this case

**Comment by jmallach** [comment]
@mmicko the additional commit is compile tested, but it should be pretty straight forward.

**Comment by jmallach** [comment]
OK, not testing it was too lazy:

    jordi@penyagolosa:~/git/mame$ mametestname -h
    MAME v0.172
    Copyright Nicola Salmoria and the MAME team
    
    This software reproduces, more or less faithfully, the behaviour of a wide range
    of machines. But hardware is useless without software, so images of the ROMs and
    other media which run on that hardware are also required.
    
    Usage:  mametestname [machine] [media] [software] [options]
    
            mametestname -showusage    for a brief list of options
            mametestname -showconfig   for a list of configuration options
            mametestname -listmedia    for a full list of supported media
            mametestname -createconfig to create a mame.ini

**Pull request merged**
