### PR TITLE
New driver for the Force Computers ISCSI-1 VME board, skeleton missin…

### PR DESCRIPTION
**Pull request by JoakimLarsson**
…g driver for SCSI NCR5386s controller. It is also a part of the Besta computer and will inherently also need a VME bus driver

### CODE REVIEW

**Comment by rb6502** [comment]
FYI, the HD63450 that we do support is 100% compatible with the MC68450 (it's a licensed Hitachi clone of a Motorola part, something that those two companies did a lot).

**Comment by JoakimLarsson** [comment]
ahh, ok I'll map it in. I think the 5386 will be more of a headache since it is less automated than the 5390, the old ads talks about 4000 vs 2500 lines of code for a driver which is a funny comparison but make me thinks that the device is bit hairy

**Comment by rb6502** [comment]
Actually if the emulated code is doing more, that means the emulation code can do less, usually :)  For example, the original 5380 has very little intelligence and relatively little code.

**Comment by JoakimLarsson** [comment]
You are right I realized that after I wrote my comment, I'll take a look at some point, now I am first going to figure out how to hook in the DMA controller, looks a bit intriguing with all the clocks in burst and normal mode, I think after checking out the esq5505 driver, but certainly doable once I figure where to get those values.

**Comment by JoakimLarsson** [comment]
One step closer to becoming testable.

**Comment by JoakimLarsson** [comment]
I will not have time to write the SCSI controller device at the moment but the board should be complete as to interface through the floppy interface. I can provide ROM:s for anyone that have time to test it or I can remove the pull request, just let me know.

**Comment by rb6502** [comment]
That's fine.  Please send the ROMs to me at messdrivers at gmail dot com and I'll merge this as soon as I get them.

**Pull request merged**
