### PR TITLE
specpls3.cpp: mitigate regression in Spectrum +3

### PR DESCRIPTION
**Pull request by holub**
Mitigate regression in Spectrum+3 till final understanding of root cause (see comments in the sources)
reported: https://mametesters.org/view.php?id=8311

bonus: floppy sound enabled

### CODE REVIEW

**Comment by rb6502** [comment]
It would be preferable that you determine what's actually going wrong with the current code.  If there's some central issue with banking by bank number, that's potentially a lot of drivers broken.

**Comment by holub** [comment]
> It would be preferable that you determine what's actually going wrong with the current code. If there's some central issue with banking by bank number, that's potentially a lot of drivers broken.

I'm planing to investigate this. This one is just temporal solution in order not to leave driver in the known broken state.

**Comment by holub** [comment]
Still no luck :( But now I have a feeling something is off with ssdd in the driver, not really banks related.
If anybody interested to participate I have easy way to reproduce issue with "Rick Dangerous 2" in this PR.
```
void specpls3_state::machine_start()
{
	...
	m_bank_ram[3]->set_entry(1);
}
```
which in theory shouldn't brake anything because where is no place where bank entry is switched, any modifications of mem just update base of active entry. But it does break the game's loader.

**Comment by holub** [comment]
Or maybe not... We better merge this one and try to solve mystery without time pressure.

**Comment by smf-** [comment]
This seems to be fixed in master now.

**Pull request closed without merging**
