### PR TITLE
sq80: booting, frontpanel and digital audio fixes

### PR DESCRIPTION
**Pull request by jari100**
this PR fixes the following Ensoniq SQ80 related issues in *esq1.cpp* and *es5503.cpp*:

* sq80 banks SEQ/DOSRAM based on m_mapper_state. initializing it to 1 in machine_reset (instead of 0), and removing the inversion in mapper_w fixed the booting issue
* sq80 requires keyboard calibration ack (kpc_calibrated in key_stroke)
* sq80 frontpanel buttons are offset by -2 (in key_stroke)
* fixed waverom load addresses in ROM_REGION "es5503"
* sq80 adc routine cycles through six targets (m_adc_*). target selection shares the bank selection method (in duart_output and esq1_adc_read)
* es5503: address space increased to 18 bits. unsure if it is ok to just stab es5503 code like this, but could not find an efficient alternative. hope someone with a better insight will figure out a proper way.

couldn't have done these fixes without R.Buchty's insights on SQ80 internals, so for possible changelog attribution pls use (jariseon, r.buchty)

### CODE REVIEW

**Comment by rb6502** [comment]
Thanks!  Modifying the DOC is definitely not the way to go on the extra banking; the method shown in src/mame/drivers/mquake.cpp (an arcade board that's an Amiga 500 with a 5503 added) shows more of how that should work.  I can do that change myself no problem though :)

**Comment by jari100** [comment]
cool, thanks rb :) another thing which i could not figure out is how to reset the midi out interrupt line: it seems that after the first midi out message duart keeps interrupting the poor old cpu even if there's nothing more to send. this happens for both sq80 and esq1. any idea how to address that issue?

**Comment by rb6502** [comment]
Most Ensoniq gear runs on interrupts from the DUART's counter/timer; the "main line" is actually a "jump self" and everything runs on an interrupt.  Are you sure the interrupts you're seeing are due to the transmitter being empty?

**Comment by ajrhacker** [comment]
In the esq1's case, the DUART channel A transmitter apoears to be causing a continual stream of interrupts. The system never switches the transmitter off, which would disable that interrupt, but just keeps resending zero bytes.

**Comment by rb6502** [comment]
Interesting.  I'll check the DUART documentation and see if something's weird.

**Comment by rb6502** [comment]
Commit 3a0bde16d371b144ba3b8251e03a5c3769519eb2 should have all the functionality here without invading the DOC, so I'm closing this request.  Thanks @jari100 and if you get anything else working synth-wise let me know! :-)

**Pull request closed without merging**
