### PR TITLE
Changed the constructor of fs::dir_entry to take 'std::string &&name' instead of 'const std::string &name'

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by galibert** [comment]
While it's obviously correct and may have an impact on the rare times the string isn't SSO, do you really thing having to pepper std::move around is a good thing?

**Comment by npwoods** [comment]
> do you really thing having to pepper `std::move` around is a good thing?

My inclination is to say "as a veteran C++ programmer, well yes".  Furthermore, I've gotten used to `std::move` being a signal to the programmer that this method consumes the object rather than merely borrowing it.  That said, I completely defer to @cuavas when it comes to this stuff.

**Comment by cuavas** [comment]
Well, since we’re C++17 now, you shouldn’t be taking `const std::string &` arguments unless you have a good reason.  If you want a constant sequence of characters to do something with, you take `std::string_view`, and if you want a string to consume, you take `std::string &&`.  Most of the things with `const std::string &` arguments end up causing unnecessary temporary string construction.

**Comment by galibert** [comment]
Yeah, well, it's mostly subjective, but I see strings, especially with SSO, more like values than structs.

**Pull request merged**
