### PR TITLE
rf5c68.cpp - fix fmtmarty chasehq engine sound

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
the issue is if chan.step is greater than 1<11, it would skip 2 bytes in the read function, rather than just having a higher frequency.  this in turn meant it would not read the 'end of sample' 0xff markers, and continue to play the whole of sample RAM until it did...

maybe there are better ways to fix this, sound cores aren't my thing.  It hasn't been tested if this causes issues elsewhere.

**Comment by DavidHaywood** [comment]
this does seem to make the 'waahoo' sound when you insert a coin in mwalk sound worse however, so needs thought.

**Comment by Dunard** [comment]
> this does seem to make the 'waahoo' sound when you insert a coin in mwalk sound a little scratchier however, so needs thought.

Nice :)

**Comment by happppp** [comment]
Sounds like you're on the right track that it misses the end-of-sample marker for some reason. But your patch for it is impossible to work on a real chip. In other words: the cause of the bug must be somewhere else.

With this change, it's now browsing through RAM at variable frequency instead of from the channel address counters. If it was multiple games that were broken, I think a 'search for end of sample' workaround is fine, but it's only 1 game?

**Comment by DavidHaywood** [comment]
only one that I'm aware of, but I've not even tried a fraction of the library.  the nature of the engine sound does mean they're playing the same sample at a whole different set of rates.

OG put forward theories of interpolation (where it would actually effectively be clocked at double internally, so read twice as much data, and maybe not miss the marker that way?)  but honestly, I have no idea.  All I know is that if you miss the end of sample marker, you run off the end and play garbage.  Also, if you use anything except the first read each time, MoonWalker ends up sounding terrible instead.

My understanding of how these sound chips work internally isn't good enough to propose anything better.

**Comment by happppp** [comment]
Yeah it's possible that the internal clock is higher, it only has 8 channels (current 384 divider means 48 clocks per channel step). By comparison, rf5c400.cpp also implemented a divider of 384 but has 32 channels.

**Comment by happppp** [comment]
Is it possible that fmtowns.cpp rf5c68_mem_w/r have the byte order(endianness) wrong? Though then I'd expect to hear it in the sound output.

**Comment by mahlemiut** [comment]
I remember noticing that the PCM in the Might and Magic games was very scratchy, and wondered if it's really supposed to sound that bad.

**Comment by Rugaliz** [comment]
Dunno if it helps but recently I played a little of Angel Halo on the Marty and also though that the sound of characters talking was kinda scratchy or noisy. Now I know it only has 10 bit sample but comparing to other emulators on youtube, the sound is better on those (slightly less noise).

**Comment by cracyc** [comment]
It also works to reset to the loop addr instead of wrapping if it tries to play past the end of ram.  I don't have any reason to believe that is correct but I think there's a reason why they chose the highest 4K addresses for the engine sound.

**Comment by happppp** [comment]
Ok, then it's a case of a game relying on uninitialized ram being 0xff instead of MAME's default 0x00?
https://github.com/mamedev/mame/commit/07d0bf3763b7db4d8f93fbcd7a0be585ca47b10f

**Pull request closed without merging**
