### PR TITLE
snk/hng64.cpp: Add Koreanized Chinese title to sams64.

### PR DESCRIPTION
**Pull request by mikehyrus**
Chinese title exists under the Korean BIOS for some apparent reason.

### CODE REVIEW

**Comment by mikehyrus** [comment]
Meant C back to Z excuse my typing.

**Comment by DavidHaywood** [comment]
The 3rd title screen is used when you select the Korean BIOS.

**Comment by mikehyrus** [comment]
I’m aware of that Haze.

**Comment by DUSEO-1004** [comment]
Pronunciation of Chinese title in Korean is different from that in Mainland China.

**Comment by cuavas** [comment]
I wouldn’t use a Chinese reading for a title used in the Korean version of the game.

**Comment by DavidHaywood** [comment]
Right, the samsho4k set uses the Korean reading, as it was for Korea.  The same should be done here.

**Comment by mikehyrus** [comment]
I'll take care of that later tonight.

**Comment by DavidHaywood** [comment]
fwiw I'm fine with this, it doesn't conflict with my work

**Comment by mikehyrus** [comment]
I believe I’m alright with the changes I made here now.

**Pull request closed without merging**
