### PR TITLE
mc6845 - configuration; row update paths; partial cursors.

### PR DESCRIPTION
**Pull request by 68bit**
This patch proposes a change to the mc6845 driver. There are a range of issues in uses of this driver, it looks frustrating for machine coders, and it appears in need of such a cleanup, but it touches a lot of machines making it a difficult proposal. An attempt to test as many as possible has been made, but it is not possible to test all modes on all machines, so help testing this would be appreciated - that is if people think such a change is necessary. It is expected to improve many machines, with proper screen configuration and that should work with or without borders, it should avoid some artifacts in race conditions, and partial cursors should work for all the dependent machines now. A large block of machines that use the mc6845 driver but do not rely on it's configuration code or row update paths are not expected to be at risk of regression.

1. Clarify the border offsets and make uses of the mc6845 driver consistent.

The most consistent definition of the border placement appears to be that the
displayable characters are always offset for the border and that only the
screen visual clip area changes with or without a border. With this definition
only the screen visual area changes when the machine chooses to display the
border or not, and the machines do not need special cases in either case. The
configuration is refactored into the mc6845 driver in most cases.

The other possible definition would have been to offset the displayable
characters from the origin of the screen pixmap only when displaying the
border, and otherwise place it at the origin. This would appear to place a
greater burden on each machine.

This change requires updates to the majority of the uses of the mc6845 driver
configuration paths and in particular the driver row update paths.

There are a large block of machines that do not use these paths. These
machines do not associate a screen with the mc6845 driver and do not use the
driver row update code paths, rather these machines implement their own screen
update function. This includes a lot of games. These are expected to be low
risk for regressions and only a selection have been tested.

There are a lot of machines that do use the driver configuration and row
update code paths, so this change affects a lot of machines. Most have been
tested except a few for which roms or software was not available or that were
just skeletons. For system that would at least configure the mc6845 these were
tested by writing to the display memory area.

In many cases it was only necessary to include a horizontal border offset in
the row update function. These are low risk for regression or at a least a low
risk for machine specific regressions.

Some machine row update functions included a vertical offset which was not
appropriate and was removed. The 'y' value passed to the row update function
is now clearly defined as an offset in the target bitmap so already includes
an offset for the border.

Many machines attempted to show the border. It is expected that this was
largely because the configuration was not working properly and the driver
definitions were frustrating. These have been modified to not show the border
which seems an appropriate default for these machines, and in any case these
should also work with the border shown. Showing the border, or not, might be
considered for a configuration option now as it simply changes the screen
visual clip area.

Many machines manually defined the screen size and visarea. In some cases they
did not even associate a screen with the mc6845 driver to avoid the driver
mis-configuring the screen. This is no longer necessary to most of them and
these definitions have been removed. The mc6845 driver should now correctly
configure the screen, and even if the machine runs some non-standard code
defining a different screen size etc. Most of these were tested and configured
properly and clipped the border properly.

A few machines had complex code to work around the configuration problems and
these have been clean up and can now rely on the mc6845 driver.

There remain only a couple of machines for which the driver configuration does
not work, and these appear to be targeting LCD screens etc that might not
follow CRT timing. These need to avoid associating a screen with the driver
and define their own screen size and visual area. Perhaps these would have
been better off using their own screen update functions rather than the driver
row update code paths, but these have been tested and still appear to work.

2. The mc6845 driver and a few machines mixed driver state with the
screen update path state, and this has been separated.

The screen update paths run off their the screen timers, and might update as
little as part of a row. So it is not appropriate for the driver or machine
state to be updating the driver state on screen updates. When the screen was
updating only part of a line, and calls the driver multiple times per line,
the driver was advancing an address on each causing artifacts - it was not
workable.

If some synchronisation is required between the screen updates and the machine
state then some more thought will be need to get this driver working with that
properly.

The mc6845 driver was updating the current display address from the screen
update code paths which appeared to be visible to the machine. The screen
update no longer modifies that machine state, calculating the display address
from the requested row.

The CGA driver stood out in this issue and need some rewriting. This raises
questions about the coordination of the screen update paths with the driver
state, the drivers row and sync state etc. Some graphical CGA code was test and
it appear to still run ok, but perhaps there had been some attempt to make the
screen updates more responsive for this driver, but it seemed only for the CGA
driver?

3. Partial cursors have been implement.

The mc6845 driver now implements partial cursors. It appears the only one
machine, the kaypro, had implemented partial cursors and that machines code
has been cleaned up now that the driver supports this.

### CODE REVIEW

**Comment by Robbbert** [comment]
If this is to be accepted, please leave until next cycle - it's too close to the freeze cutoff now.

**Comment by ajrhacker** [comment]
I can't do a full review of this right now, but there are couple of concerning things I've noticed:

1. The removal of border areas seems to have been done a bit too sweepingly, since it was applied to some drivers that use the BEGIN_UPDATE callback to draw into non-"data enabled" parts of the screen (see e.g. applix).
2. Removing the screen size from the drivers may not be helpful, since MAME's internal configuration and external utilities depend on being able to access it from the configuration object or -listxml output. I've made it possible for CRTCs to define the default screen parameters in device_config_complete, but in this case each driver would have to provide a whole set of parameters since they aren't baked into the device as they are for, say, the V9938 or DP8350.

**Comment by cracyc** [comment]
8088mph shows how the 6845 with a fixed screen size can heavily abuse the controller to behave as if the frame ends anywhere.  It doesn't work correctly now but without the code at https://github.com/mamedev/mame/pull/5398/files#diff-49b689a3825b338417712ace1d495726R695 it fails spectacularly.

**Comment by 68bit** [comment]
A. Yes, if near a freeze cut off then please leave this one wait until the next cycle. It would be best to have some good testing.

B. The applix machine appears to be the only one with a non trivial BEGIN_UPDATE callback that is affected, and it also works with the border, will put that back. The other machines with non trivial BEGIN_UPDATE callbacks are merit, slotcarn, and tapatune and were not showing the border anyway and are not changed. There are a few machines that draw a trivial static background color into the border, some just black, and where these are basically terminals then it appeared appropriate to show them without the border. If some machines need the border to be 'authentic' then that should be noted but I did not get that impression for those modified. If a border is really wanted for some machines then it might be necessary to size that border too, and that size might not be the mc6845 computed border as that can also depend on the CRT not just the mc6845 timing. The adjustments still work and are applied and might address some machines. Making the border a configuration option might help keep everyone happy.

C. Screen sizes baked into configuration files will not work well with the mc6845 which is configured by software and resolution on PCs depends on the software they run. Are static screen sizes needed anywhere in the code? Could you direct me to some examples that are of concern so I can start to understand the challenge? One possibility would be to put back the defaults, and perhaps add some code to report if they vary from the dynamic configuration computed by the mc6845 driver to try to detect errors there, but if a screen is associated with the mc6845 then the driver will override them anyway so if some code depends on them then that seems brittle.

Feedback welcome, thanks. This is a big job due to the large number of machines using the mc6845. If people report issues then I'll try to address them.

**Comment by 68bit** [comment]
Great thanks for the pointer to 8088mph, and I'll take a look and try to understand the issue being addressed. The code disabled in the cga driver just seemed unnecessary, not a conflict, and if 8088mph works with only those pieces of code re-enabled then that is encouraging. Let me check that it seems consistent to have the machine calling back into the screen code, perhaps that's ok, perhaps that just triggers a quick screen update rather than waiting on the screen update timer. But if this was necessary for the cga driver then perhaps it is necessary for some drivers the rely on the mc6845 and perhaps that could be refactored into the mc6845 driver and made an option there.

**Comment by startaq** [comment]
The border on the `cgenie` driver was deliberately enabled to show CRT effects like used by the game `invasion`. Here's a short video demonstrating the effect: https://imgur.com/a/oQFfavq

**Comment by rb6502** [comment]
@cracyc , @ajrhacker : are we interested in doing this, or not?  Now would be the time.

**Comment by ajrhacker** [comment]
I'm not really happy with the screen configuration changes and would prefer for those to be left in, at least for now. I'm not even

**Comment by Pernod70** [comment]
I'm interested as it'll probably help with bbc, but agree with both @ajrhacker points. Anything that previously had a border should be re-instated, it was probably that way for a reason. And aren't screen sizes required for the initial info dialog before the machine starts. I wouldn't like to proceed with this until both points have been reverted.

**Comment by cracyc** [comment]
Testing 8088mph and making sure it works at least as well as before (improvement would be quite welcome) is all I'm looking for.

**Comment by 68bit** [comment]
Please don't merge this now. It needs more thought.

A. The configuration can not rely on the 6845 register state, as this PR currently does, because that state can change during a frame as shown in 8088mph. It appears practical to fix this. The scan lines can likely be counted, and the 'character' display and non display lines noted, and the vsync position noted, and this information could be used to configure the screen size. This needs to be tried and tested to determine if practical.

B. The code paths back to the screen update code need more study. The machine needs to drive the screen output, not the other way around, because the machine state can be transient. The screen code can clearly not asynchronously call back into the 6848 driver to update the screen, can not run off on it's own timer. There are some code paths by which the machines call the screen code to have the screen code call back and it might be possible to clarify these and make that work and this PR regresses some of these paths. If that is not practical, does not meet other design goals, then it might be necessary to double buffer the machine screen output. More work is needed here.

I'll split out the cursor shape improvements. You are welcome to close this PR but it has some interesting discussion and I am planning to keep working on this.

**Comment by cracyc** [comment]
> A. The configuration can not rely on the 6845 register state, as this PR currently does, because that state can change during a frame as shown in 8088mph. It appears practical to fix this. The scan lines can likely be counted, and the 'character' display and non display lines noted, and the vsync position noted, and this information could be used to configure the screen size. This needs to be tried and tested to determine if practical.

Cool, thanks for looking at it.

**Comment by rb6502** [comment]
Ok, thanks @68bit.  I'll close this one and look out for the cursor shape improvements.

**Pull request closed without merging**
