### PR TITLE
Maygay M1A/B partial fix for lamp mapping

### PR DESCRIPTION
**Pull request by johnparker007**
Fix the lamp mapping for the first half of the matrix
Fix typo and add comment to function that is intended to handle the second half of the matrix

### CODE REVIEW

**Comment by mamehaze** [comment]
looks like the MCU needs hooking up for the 2nd bank of lamps to work.  There is a dump of it, so full emulation is probably possible.

current driver attempts to hook it up as a 2nd 8279, when it is not.

**Comment by johnparker007** [comment]
Have just checked the MFME source (as that has fully working lamps on Maygay M1A/B) - MFME treats them as both 8279s... from `m1a.h`:

`I8279    io1;`
`I8279    io2;` 

Perhaps not correct but does seem to work as a stand-in :)

**Comment by mamehaze** [comment]
the difference is probably that MFME doesn't attempt to emulate the 8279 properly and we do, meaning the MFME implementation of it works for this case because it's less fussy?

M1A board pics are here FWIW
http://www.citylan.it/wiki/index.php/Gladiators_(Maygay)_(M1A/B)

**Comment by johnparker007** [comment]
Ah I see - good to know.  I don't want to get caught up in the low level
emulation work at this stage, as it's really not my forte :)

If it's still an issue in a year or so when I finally finished doing stuff
on the whole layout side of things, I'll come back to it and see if I can
write then new chip.

**Comment by mamehaze** [comment]
can this be merged? I'd like to take a look at the MCU.

**Comment by johnparker007** [comment]
Some Maygay M1A DX (A-H) MAME layouts in the Downloads section of the
MFME2MAME website (sorry you do have to register to get to see that
section), if you want to check lamps are mapped correctly - thanks for
taking a look, very much appreciated :)

http://mfme2mame.org/

**Comment by mamehaze** [comment]
ok, thanks, I'll take a look at them.

once some basic lamping works it will definitely help to get some of the more popular machines set up with internal layouts

**Pull request merged**
