### PR TITLE
mc6847: revise font

### PR DESCRIPTION
**Pull request by tlindner**
I recently did a detailed study of the font inside the various 6847s. http://tlindner.macmess.org/?p=913
And there is now a decode form the decap: https://exileinparadise.com/tandy_color_computer:vdg_rom_font
This PR fixes all the issues I've found.

### CODE REVIEW

**Review by npwoods — APPROVED** [review]

**Comment by rb6502** [comment]
We prefer now that stuff like this is loaded as a device ROM - makes the source more concise and the data's  in an easier form for external projects to use.  Looks good otherwise.

**Comment by npwoods** [comment]
I'd agree with putting this data in an external device ROM if we had any evidence of the actual structure of the ROM in the 6847 chip.  In its current form, the ordering in the various arrays (e.g - putting upper case before lower case `ntsc_square_fontdata8x12`) is an arbitrary decision that is not reflected of any known aspect of the chip.

**Comment by cuavas** [comment]
But we *do* have the ROM structure for the 6847, which @tlindner linked to: https://exileinparadise.com/tandy_color_computer:vdg_rom_font

Someone please turn this into a device ROM…

**Comment by npwoods** [comment]
Oh wow you're right

@tlindner Do we have an actual ROM dump or just those images of the circuit?  Also do we have something similar for the GIME?  I dislike the idea of creating a "fake" ROM in absence of authoritative information of what this data looked like in the GIME

**Comment by tlindner** [comment]
We just have the images of the die for the 6847. Nothing for the 6847 T1. We do have the GIME images both 86 and 87, but they are still trying to figure out the encoding.

I will look into finding a way to represent the 6847 die image that works for preservation and the emulation.

**Pull request merged**
