### PR TITLE
new NOT WORKING machines (Train)

### PR DESCRIPTION
**Pull request by mamehaze**
new NOT WORKING machines
----------------------------------------------
Boku wa Plarail Untenshi Shinkansen de Ikkou! Plus (Japan) [David Haywood, Team Europe]

### CODE REVIEW

**Comment by mamehaze** [comment]
need better title once more
vlcsnap-2024-07-30-19h03m22s600

**Comment by JWatersMeet** [comment]
This is 
ぼくはプラレール運転士 新幹線で行こう！プラス
Boku wa Plarail Untenshi (I am a Plarail driver)
Shinkansen de Ikkou! Plus (Let's go by Shinkansen! Plus)

Plarail is Tomy's rail toys.

See https://www.amazon.co.jp/dp/B015XA8JP4/ref=asc_df_B015XA8JP41722270600000?me=A3PBMZSH1XNKRD

**Comment by mamehaze** [comment]
thanks, now I have the proper name it looks like there's also a non-Plus version, so I've tried to buy that too

**Comment by mikehyrus** [comment]
Maybe the title could be Boku wa Plarail unten-shi - Shinkansen de Ikou! Plus

**Comment by DopefishJustin** [comment]
Ikou, not Ikkou

**Pull request merged**
