### PR TITLE
ins8250 support for BAUDOUT pin

### PR DESCRIPTION
**Pull request by JoakimLarsson**
Would such a crude solution be ok, I want to avoid rewriting the diserial hookup for ins8250, please review approach

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
Reason: Ericsson PC can select another ins8250 clock by raising the DTR pin of 8251...

**Comment by ajrhacker** [comment]
I don't really like this method, convenient as its implementation may be. It would be best if BAUDOUT and the RCLK input (which need to be tied together in a normal INS8250/NS16450/NS16550 configuration) were line writes, both functioning at 16x the baud rate.

**Comment by JoakimLarsson** [comment]
Nore do I, why I pushed a preliminary PR, I can rewrite it with line writes and then also replace the internal timer in diserial with a device timer and remove the set_rate calls which would fix the FIXME: too I presume. 

And yeah the BAUDOUT would always be assumed to be tied to RCLK unless the callback is defined. 

I'll take a stab at it and push it here and see what you think

**Comment by JoakimLarsson** [comment]
It doesn't seem to be possible to surgically implement BAUDOUT pin as write line without replacing all diserial logic in ins8250.cpp and I am not sure its worth the effort. Or any suggestions/pointers of approach here? [Schematics](https://imgur.com/eVwMQTu)

**Comment by rb6502** [comment]
diserial has at least partial support for an external clock; the clock_w, rx_clock_w, and tx_clock_w methods are all public.  I'm not sure how you stop the internal BRG in that case though; that may need to be added.

**Comment by JoakimLarsson** [comment]
Yes, the 8250 emulation stops the internal TxC (BAUDOUT) and RxC  (RCLK) when nothing is transmitted/received but the schematics just feed a raw 19200 baud clock signal into RCLK if selected. If not selected the BAUDOUT pin is fed back to RCLK as it normally would.

**Comment by JoakimLarsson** [comment]
Solution is to not use the diserial BRG timer at all of course and put a brg  timer in ins8250 instead, I'll try that

**Comment by JoakimLarsson** [comment]
I'm pretty happy with this, I removed the use of internal BRG of diserial and set up a local TIMER in the ins8250 device so I could feed it to the driver. The driver could return it using a new method rclk_w or ignore it and feed rclk_w from another timer in the driver, which I did. I tested it by attaching a terminal to COM1 and ran a simple gwbasic program on different baud rates and it worked as expected. GWBASIC even lost characters at higher speeds when echoed back from the terminal just like the manual said it would...

**Comment by JoakimLarsson** [comment]
And yes, if no callback is defined the behavior is as before, BAUDOUT pin connected to RCLK input pin so no need for other drivers to do anything

**Comment by JoakimLarsson** [comment]
Arghh, this was not as simple as I hoped for, replacing the built in BRG with a device local BRG without breaking a lot of drivers depending on ins8250 seems hard without also ripping out the shifters and refactor them specifically for the ins8250. The alternative is to refactor parts of diserial which could have epic effects on all serial devices using it. 

I will revert the BAUDOUT pin support for now as it is too much work for too little gain at the moment.

**Comment by smf-** [comment]
diserial was a bad mistake that has yet to be corrected.

The best option is to stop the 8250 using diserial completely.

**Comment by JoakimLarsson** [comment]
Yeah, I think most of the tasks it does could probably be done by some smart templates or something that could be tailored for each device instead of the current one size fits all approach. 

My naive attempt is now reverted anyway: 36753f6823312e928d035a6b0099729df381049a

**Comment by ajrhacker** [comment]
> diserial was a bad mistake that has yet to be corrected.

I see the existence of  `device_serial_interface` as being in line with the older philosophy that Aaron Giles brought to MAME of there being one generic core implementation to be used in as many emulated systems as it could conceivably apply to (even though he had nothing to do with this particular one). The problem with `device_serial_interface` is that not only does it fail to properly support many features of specific UARTs that go beyond the usual asynchronous modes (I was quite surprised when @Robbbert managed to get it to support synchronous communications on the 8251), its asynchronous support isn't very flexible or even well-implemented for what it does. Its persistent use in devices that aren't generic HLE can be partly explained by it at least being a technically superior solution to the fake PIO some of those previously used.

I do agree that MAME's INS8250 family emulation needs to be eventually reimplemented without  `device_serial_interface`, not only to properly support BAUDOUT and independent RCLKing but also for the sake of the enhanced modes added to the Intel 82510 and some chipsets.

**Comment by smf-** [comment]
On 19/11/2019 05:36, ajrhacker wrote:
>
> I see the existence of |device_serial_interface| as being in line with
> the older philosophy that Aaron Giles brought to MAME of there being
> one generic core implementation to be used in as many emulated systems
> as it could conceivably apply to
>
It's a case of premature abstraction.

I think there is a case for a stream interface, which could be hooked up
to write lines and be single stepped or hooked up to another stream
interface which allowed looser synchronisation. Potentially this could
be a base for synchronising sound and video as well.

If the clock is also made streamable then you could potentially reduce
the overhead of UARTS that use a 16x divider.

And ultra fast synchronous serial streams would not grind mame to a halt.

But what device_serial_interface currently does is just hiding some
simple code behind a much more complicated interface, which means it's
impossible to actually implement the actual UART behaviour.

**Pull request merged**
