### PR TITLE
Check that m_display is not null to prevent crash

### PR DESCRIPTION
**Pull request by GeorgeMcMullen**
https://mametesters.org/view.php?id=7372

### CODE REVIEW

**Comment by GeorgeMcMullen** [comment]
Hello,

Long time lurker, first time pull request. I appreciate your patience! MAME currently crashes on Raspberry Pi when built on RetroPie distributions. After tracing through the issue, I found that the LightGun routines were not checking to see if the display via X11 was available. So I added a couple of simple nullptr checks to the m_display variable in the LightGun routine.

**Comment by cuavas** [comment]
Is MAME being modified in any other way to run in this configuration?  What SDL video driver is being used in the absence of an X server?

**Comment by GeorgeMcMullen** [comment]
Thanks for the feedback. No other changes to the MAME source code or makefiles have been made. It's being compiled with the following parameters:

`NOWERROR=1 ARCHOPTS=-U_FORTIFY_SOURCE`

The video driver being called is set to RPI. Below is the output of `./mame -verbose` (with the changes I've made. You'll see below that it is being compiled with X11 enabled. This is because one may wish to run this on regular Raspbian with their default window manager.

I did a grep for RPI and found that most references are in the 3rdparty directory for bgfx, bx, and SDL2. But there is also a reference in [src/osd/modules/render/drawbgfx.cpp](https://github.com/mamedev/mame/blob/10f380468f8c9b8d44635dd52cc207c1a7dadce8/src/osd/modules/render/drawbgfx.cpp#L171) as follows:

```
#   if BX_PLATFORM_LINUX || BX_PLATFORM_BSD || BX_PLATFORM_RPI
        return (void*)wmi.info.x11.window;
```

This seems odd that it is returning an X11 window for RPI, even if another type of video driver is selected. But I may just be naive to the implementation and how its called.

I did notice that src/osd/modules/input/input_x11.cpp does not have an init() function in the x11_lightgun_module, where other input modules do. Do you think adding an init() method that checks viability (i.e. if m_display != nullptr) and returning -1 should suffice?

Thanks again!

```
$ ./mame -verbose
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Starting plugin data...
Starting plugin hiscore...
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Available videodrivers: x11 RPI dummy 
Current Videodriver: RPI
	Display #0
		Renderdrivers:
			 opengles2 (0x0)
			  opengles (0x0)
			  software (0x0)
Available audio drivers: 
	alsa                
	dsp                 
	disk                
	dummy               
Build version:      0.214 (mame0214-dirty)
Build architecure:  
Build defines 1:    SDLMAME_UNIX=1 SDLMAME_X11=1 SDLMAME_LINUX=1 
Build defines 1:    LSB_FIRST=1 MAME_NOASM=1 
SDL/OpenGL defines: SDL_COMPILEDVERSION=2008 USE_OPENGL=1 
Compiler defines A: __GNUC__=6 __GNUC_MINOR__=3 __GNUC_PATCHLEVEL__=0 __VERSION__="6.3.0 20170516" 
Compiler defines B: __unix__=1 
Compiler defines C: __USE_FORTIFY_LEVEL=0 
Enter init_monitors
Adding monitor screen0 (1680 x 1050)
Leave init_monitors
Enter sdlwindow_init
Using SDL multi-window soft driver (SDL 2.0+)

Hints:
	SDL_FRAMEBUFFER_ACCELERATION             (null)
	SDL_RENDER_DRIVER                        (null)
	SDL_RENDER_OPENGL_SHADERS                (null)
	SDL_RENDER_SCALE_QUALITY                 (null)
	SDL_RENDER_VSYNC                         (null)
	SDL_VIDEO_X11_XVIDMODE                   (null)
	SDL_VIDEO_X11_XINERAMA                   (null)
	SDL_VIDEO_X11_XRANDR                     (null)
	SDL_GRAB_KEYBOARD                        (null)
	SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS         (null)
	SDL_IOS_IDLE_TIMER_DISABLED              (null)
	SDL_IOS_ORIENTATIONS                     (null)
	SDL_XINPUT_ENABLED                       (null)
	SDL_GAMECONTROLLERCONFIG                 (null)
	SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS     (null)
	SDL_ALLOW_TOPMOST                        (null)
	SDL_TIMER_RESOLUTION                     (null)
	SDL_RENDER_DIRECT3D_THREADSAFE           (null)
	SDL_VIDEO_ALLOW_SCREENSAVER              (null)
	SDL_ACCELEROMETER_AS_JOYSTICK            (null)
	SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK   (null)
	SDL_VIDEO_WIN_D3DCOMPILER                (null)
	SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT      (null)
	SDL_VIDEO_MAC_FULLSCREEN_SPACES          (null)
	SDL_MOUSE_RELATIVE_MODE_WARP             (null)
	SDL_RENDER_DIRECT3D11_DEBUG              (null)
	SDL_VIDEO_HIGHDPI_DISABLED               (null)
	SDL_WINRT_PRIVACY_POLICY_URL             (null)
	SDL_WINRT_PRIVACY_POLICY_LABEL           (null)
	SDL_WINRT_HANDLE_BACK_BUTTON             (null)
Leave sdlwindow_init
Enter sdl_info::create
window: using renderer opengles2
renderer: flag SDL_RENDERER_ACCELERATED
Leave renderer_sdl2::create
Audio: Start initialization
Audio: Driver is alsa
Audio: frequency: 44100, channels: 2, samples: 512
sdl_create_buffers: creating stream buffer of 22528 bytes
Audio: End initialization
Keyboard: Start initialization
Input: Adding keyboard #0: System keyboard (device id: System keyboard)
Keyboard: Registered System keyboard
Keyboard: End initialization
Mouse: Start initialization
Input: Adding mouse #0: System mouse (device id: System mouse)
Mouse: Registered System mouse
Mouse: End initialization
Lightgun: Begin initialization
Unable to connect to X server
Unable to connect to X server
Joystick: Start initialization
Joystick: End initialization
Searching font Liberation Sans in -. path/s
font Liberation Sans|Regular is not TrueType or BDF, using MAME default
Region ':user1' created
Starting No Driver Loaded ':'
  (missing dependencies; rescheduling)
Starting Video Screen ':screen'
Starting No Driver Loaded ':'
Checking for icons in directory icons
No candidate icons found for machines
Attempting to parse: default.cfg
Attempting to parse: ___empty.cfg
Starting No Driver Loaded
hiscore: config found
sdl_kill: closing audio
Enter sdlwindow_exit
Leave sdlwindow_exit
```

**Comment by GeorgeMcMullen** [comment]
I did some additional logging and am finding that even with my changes, MAME is still trying to process events through the X11 lightgun provider. I'm looking for ways to detect that X11 is not in fact being used currently and to disable the lightgun routines.

I added an init() method into the input_x11.cpp file, with a check to see if an X11 display was being used, returning -1. But MAME is still trying to process lightgun events. Although I am not sure, it looks like the return value is not checked for validity. I found the m_lightgun_enabled variable, but declaring it false in the init() and input_init() methods does not seem to result in the desired effect.

I would appreciate any suggestions. Thanks!

**Comment by couriersud** [comment]
Quick solution: Just use "NO_USE_XINPUT=1" when compiling. That disables lightgun support.

Longer solution: In addition to init return -1 `should_poll_devices` should return false to avoid before_poll being called.

There is also a bug in code: input_x11.cpp, line 573ff currently is

```
			if (m_lightgun_map.initialized)
			{
				snprintf(tempname, ARRAY_LENGTH(tempname), "NC%d", index);
				devicelist()->create_device<x11_lightgun_device>(machine, tempname, tempname, *this);
			}

			return nullptr;
```
That should be 
```
			if (m_lightgun_map.initialized)
			{
				snprintf(tempname, ARRAY_LENGTH(tempname), "NC%d", index);
				return devicelist()->create_device<x11_lightgun_device>(machine, tempname, tempname, *this);
			} else
			    return nullptr;
```

**Comment by cuavas** [comment]
@couriersud compiling without Xi would make the resulting binary less flexible.  If they just want to work around the issue they can set the lightgun provider to `none` anyway.

@GeorgeMcMullen you're supposed to override `virtual bool probe()` to check whether an OSD module is viable, and return `fasle` if it isn't.  See src/osd/modules/netdev/pcap.cpp for an example.

**Comment by GeorgeMcMullen** [comment]
Thanks @cuavas and @couriersud !

I understand that compiling without Xinput and using the lightgunprovider none option solve the immediate need for me personally, but would not really be helpful for other folks who may stumble across the same issue. In fact, when I was first investigating the issue, I used both those options to help me pinpoint the issue.

I implemented an override for `virtual bool probe()` and it does in fact prevent the module from loading and no longer tries to process events. Looks like that is the best path! On the plus side, earlier I saw where probe() was getting called from, and now I know what it's for.

Looks like I don't need to bother with the `init()` method, `m_lightgun_enabled` variable, or the `should_poll_devices()` method. Luckily, I hadn't made any further commits, so I can easily get rid of all the other changes that I had made. Please correct me if I'm wrong anywhere.

Quick question on the `probe()` method. It doesn't output any messages even when using `osd_printf_verbose()`. Is it supposed to be that way?

I need to run some additional tests, using X11 on Raspbian, and then X11 on a PC. If all goes well, I'll commit the changes and update my pull request.

Thanks again!

**Comment by cuavas** [comment]
If you run MAME with the `-v` switch on the command line you should see the output from `osd_printf_verbose` on standard output, but it's suppressed by default.

**Comment by GeorgeMcMullen** [comment]
Yes, I'm running with -verbose and seeing all the other messages being printed except for the ones printed in the `probe()` method. Weird but true. I had to hard code return values to make sure it was actually being called.

**Comment by cuavas** [comment]
Ah, perhaps `probe` is being called before the command line options are parsed, because it needs to know the viable modules before it can parse the `*provider` options.  That's a problem.

**Comment by GeorgeMcMullen** [comment]
That makes sense. Might be a little outside the scope of this particular bug (and my current skill level with the code base) to fix right now though.

**Comment by cuavas** [comment]
Oh, I'm not expecting you to fix it, I just realised why that's happening.

**Comment by GeorgeMcMullen** [comment]
Ok, I've added probe() as suggested by @cuavas and fixed the create bug that returned nullptr as suggested by @couriersud . I did some tests on an RPi with RetroPie (display = RPI), RPi with Raspbian/X11 (display = X11), and a PC running Ubuntu (display = X11). All run, no crashes, and the probe prevents the X11 input module from loading when X11 is not being used.

Let me know if you have any other suggestions. Thanks again!

**Comment by cuavas** [comment]
Please remove the extra checks that `m_display` is not null while the module is running, or replace them with assertions. The module won't be used if probe returns `false` so the extra checks are not useful.

**Comment by GeorgeMcMullen** [comment]
You bring up an interesting question. How does MAME deal with hardware changes while running? In other areas of the code (e.g. https://github.com/mamedev/mame/blob/45f0307c251b912f1d3e44f903f5f09282b7b82e/src/osd/modules/input/input_sdlcommon.cpp#L80), I saw error checks with graceful fails in cases where a device may no longer be valid or a poll may fail. I used that as a model for my original fixes.

Of course, X11 is a different beast than a joystick or keyboard. If it has failed for one reason or another, then everything spawned within it will probably fail. But what about cases where a laptop user goes from single screen to multi-screen, or vice-versa? Or even screensavers / display sleep?

Thanks, I appreciate the input and feedback.

**Comment by cuavas** [comment]
MAME really doesn't deal with devices being hot-plugged very well at all.  It also doesn't deal well with certain configuration changes.  For example on a Windows tablet PC, if MAME is running in full-screen mode and you change the device orientation from portrait to landscape or vice versa, MAME will not handle the Diect3D context being torn down.  At any rate, gracefully dealing with an X server crashing is going to be a whole lot more complex than this.

**Comment by GeorgeMcMullen** [comment]
Good to know. In that case an assertion may actually be a better option, if dynamic hardware changes ever become part of the roadmap.

**Comment by GeorgeMcMullen** [comment]
Ok, I made the change to asserts, recompiled, and tested on RetroPie on RPi, Raspbian on RPi, and Intel with Ubuntu. Everything is operating under expected parameters. No crashes. X11 lightgun is initialized when using X11, ignored with X11 is not being used as the display driver.

**Comment by cuavas** [comment]
Thanks.

**Comment by GeorgeMcMullen** [comment]
Awesome. Thank you. I updated the MAMETesters tickets with the pull request link. I'm not familiar with the process on how tickets get closed, but I will monitor it as the next release occurs.

**Pull request merged**
