### PR TITLE
monon_color.cpp : rejig music CPU protection handling and update notes + new Monon Software List additions / c2color.cpp : dump C2 internal ROM + Software Lists

### PR DESCRIPTION
**Pull request by DavidHaywood**
monon_color.cpp : music MCU commands axxx really are reading a range from the internal ROM for a direct comparison, not sniffing the SPI bus.  Add some debugging code to run that if wanted for now, even if it's incomplete (defaults to suspending the CPU) [David Haywood]

c2color.cpp : added dumps of SPI ROMs from machine + notes [Peter Wilhelmsen]

new WORKING software list additions
-------------
monon_color.xml:
ielts: Yǎsī tǎ dà màoxiǎn / 雅思塔大冒险 / IELTS Adventure [Peter Wilhelmsen]
ultbrain: Nǎolì liánlián kàn / 脑力连连看 / Ultimate Brain Power [Peter Wilhelmsen]
labmath: Àoshù shíyàn shì / 奥数实验室 / Laboratory Mathematica Olympiad [Peter Wilhelmsen]

new NOT WORKING software list additions
-----------
c2color_cart.xml:
agree: Dì 1 dàn: Dài Lóngwáng Fēngyìn [Peter Wilhelmsen]
kingwing: Dì 2 dàn: Zhī Yìwáng De Shì Liàn [Peter Wilhelmsen]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
@happppp are you ok with this? would be nice to have the full set of Monon cart dumps in before the freeze at least

**Comment by happppp** [comment]
Code itself is fine, just some weird indentation at places (mix of Tab and Space?)
See the github diff viewer. For example the comment for game 207(hashfile). or the TODO comment in c2color.cpp

**Comment by DavidHaywood** [comment]
srccleaned it and synced it anyway, should be tidier now

**Comment by happppp** [comment]
Hi phone-hap, nevermind that email.

**Comment by happppp** [comment]
No internet on PC rn, someone else can merge

**Pull request merged**
