### PR TITLE
at.cpp: corrections, comments, motherboards, BIOS versions

### PR DESCRIPTION
**Pull request by rfka01**

### CODE REVIEW

**Comment by cuavas** [comment]
The Fun World Photo Play system should really be a fixed software machine with its hard disk dump attached, not a PC clone like this.

**Comment by rfka01** [comment]
I can try to make a skeleton driver, but I don't have the harddisk dump.

**Comment by rfka01** [comment]
I'll move the system over to photoply.cpp which has the 2000 and 2004 versions of the game.

**Comment by clawgrip** [comment]
I'd leave the PhotoPlay out of this commit... 
When we dumped this Award BIOS from a PhotoPlay PCB we did also the Multi-I/O board BIOS, the VGA BIOS (Cirrus Logic 1.31), the MicroTouch BIOS (v5.6), the Sound board BIOS (ESS) and two different versions of the parallel dongle SEEPROM (both for PhotoPlay Spanish 1999: Rev.1 and Rev.3).
Those dumps are not the included ones on the driver (different CRCs).
IMHO, it would be better to wait until he have proper devices (with their ROM loads) for the MicroTouch (currently HLEd), the Cirrus Logic (we already support an older model) and the other cards (sound, I/O) and then, start sorting out all the Photo Play dumps (CDs and HDDs) we have (dozens).

**Pull request merged**
