### PR TITLE
Add Bally squawk & talk boards

### PR DESCRIPTION
**Pull request by hackbar**
There is a change to the 6821 PIA code. It changes the output register reads to ignore the bus. This is a bit of a hack, but required for Bally games since they read from the output register during self test. Someone said this might break Kid Niki, but it seemed to work for me.

### CODE REVIEW

**Comment by Quench0** [comment]
Thanks for adding this and the recent other Bally sound boards.

Some notes:

 The S&T DAC volume is too high, it should be 25% of what it currently is to better balance it against the TMS5200 and AY8912.

 The S&T sound test switch needs to be changed from service switch 1 to service switch 3, because as it is it's conflicting with the game service switch. See the recent changes I made to your other sound boards.

In src/mame/layout/by35.lay
"Add sound LED to layouts"
 Please move the Sound LED to below the MPU LED in the layout file. The sound test switch will eventually be added where you currently put the Sound LED.

In /src/mame/layout/by35_playboy.lay
"Add sound LED to layouts"
 The AS2888 sound board doesn't have a LED so a Sound LED doesn't belong in the Playboy layout file - please revert this part.

In src/mame/audio/bally.h
When you recently moved the AS2888 code to this file you accidentally gave the AS2888 board a 3.579545MHz crystal at line 55. There's no such thing on that sound board so please change the clock to 0.

**Comment by hackbar** [comment]
Done. See how the volume on the DAC sounds.

**Comment by hackbar** [comment]
Let's put this on hold until I've tested the PIA change more.

**Comment by Tafoid** [comment]
Regressions/changes in behavior noted for the following due to 6821pia changes (previous test snap | current test snap | differences) in a 10 second emulated run.  If more is found, I will report.

dgnbeta - dgnbeta.cpp
dgnbeta-diff

dgnalpha - dragon.cpp
dgnalpha-diff

jpcoin, jpcoin2 - coinmstr.cpp
jpcoin-diff
jpcoin2-diff

Most mpu3.cpp machines - lost of segmented display (m3autort provided as sample)
m3autort-diff

Most mpu4.cpp machines - value changes (m4bjack provided as sample)
m4bjack-diff

mo5nr, mo6, pro128 - thomson.cpp
mo5nr-diff
mo6-diff
pro128-diff

**Comment by hackbar** [comment]
Yeah, this shouldn't have been merged. I'm working on improving the PIA fixes in another PR (not ready yet). 

Someone can either revert this, or we can wait until I've fixed the regression in another CL (later this week).

**Pull request merged**
