### PR TITLE
New NOT_WORKING software list additions

### PR DESCRIPTION
**Pull request by clawgrip**
-------------------------------
leapster.xml:
  2nd Grade - Musical Menace (USA), Bratz World - The Jet Set (USA), Crayola - Art Adventure (USA), Disney Fairies (USA), Disney Princess - Enchanted Learning (USA), Disney Princess - Worlds of Enchantment (USA, alt), Disney Tangled (USA), Disney·Pixar Finding Nemo (USA, alt), Kindergarten (USA, alt), Letter Factory (USA), Math Baseball (USA), Mr. Pencil's Learn to Draw & Write (USA, alt), nihao, kai-lan (USA), Nick Jr. Dora the Explorer - Animal Rescuer (USA), Nick Jr. Dora the Explorer - Wildlife Rescue (USA), Nick Jr. Dora the Explorer - Wildlife Rescue (USA, alt), Nick Jr. The Backyardigans (USA), Nickelodeon The Penguins of Madagascar - Race for the 1sr Place! (USA), Pet Pals (USA), Ratatouille (USA, alt), Scholastic - Animal Genius (USA), Scholastic - Math Missions (USA), School House Rock! - America Rock (USA), School House Rock! - Grammar Rock (USA), Spongebob Squarepants - Saves the Day (USA), The Batman - Multiply, Divide and Conquer (USA), The Incredibles (USA), The Princess and the Frog (USA), Top-Secret Personal Beeswax - Share a journal with Junie B. (USA), Word Chasers - Arcade-Style Learning! (USA), Word Chasers - Arcade-Style Learning! (USA, alt) [Skaman]

### CODE REVIEW

**Comment by Tafoid** [comment]
In checking this I see at least a couple entries with issues and they seem related.
- 1stgrade and 2ndgrade entries have swapped CRCs between each other although the rest of the metadata seems to match.  Copy/Paste mistake?

**Comment by clawgrip** [comment]
> 
> 
> In checking this I see at least a couple entries with issues and they seem related.
> 
>     * 1stgrade and 2ndgrade entries have swapped CRCs between each other although the rest of the metadata seems to match.  Copy/Paste mistake?

You're right. Fixed, thanks a lot!!

**Comment by cuavas** [comment]
Where did you get “Race for the 1sr place” from?  That doesn’t even read properly.  It’s “Race for 1st place” on every image I can find.  Can people besides me please check additions?

**Comment by cuavas** [comment]
Also, you’ve listed “Scholastic - Animal Genius (USA)” as an addition when it isn’t.

**Pull request merged**
