### PR TITLE
nesvt / snesb control improvements

### PR DESCRIPTION
**Pull request by ghost**
the Majesco DDR games have a dance mat, not joystick, so treat them as buttons as opposing directions are often needed (they are also single player only, so dummy out the 2nd control port)

the SNES based bootleg Venom / Spiderman Separation Anxiety appears to have had the code modified to only use 3 buttons, which makes sense as it's a JAMMA PCB that doesn't use SNES pads.  This maps things in a more appropriate way as a result.  I suspect several of the other games in the driver need the same treatment but I haven't tested, they were all JAMMA boards, with not even a kick harness afaik.

Also renamed the new sets to be closer to the SNES software list sets on which they're based.

### CODE REVIEW

**Comment by MooglyGuy** [comment]
This should be done by leaving it using IPT_JOYSTICK_* but adding PORT_16WAY to the four directional controls. Fix that and I'll be happy to merge it in. See how it's done for gnw_tfish in src/mame/drivers/hh_sm510.cpp

**Comment by DavidHaywood** [comment]
It isn't a PORT_16WAY joystick, it isn't a joystick at all.

Doing that would be adding technical debt, it's a hack.

It's a set of 4 buttons on the floor.

**Comment by MooglyGuy** [comment]
OK, someone else can merge the changelist then if they agree with you, because I won't.

**Comment by DavidHaywood** [comment]
actually fuck it, this can ship broken, I'm not dealing with the conflict it seems to be creating with people.

if anybody wants anything from this, take it yourself.

**Comment by MooglyGuy** [comment]
OK, I'll implement it and credit it to myself then, if that's what you want.

**Comment by DavidHaywood** [comment]
I don't mind who is credited, it was just a quality control PR for the release.  If things cause conflict and differing opinions my inclination is to simply close them and get on with something else, which I'm now doing.

**Comment by happppp** [comment]
This custom dance mat controller doesn't exist for the NES. IMO it shouldn't be added to the list of NES controllers. Instead, adding some kind of callback for exceptions like this. There's bound to be more custom controls for NES-derived hw, right? It's unfortunate the inputs can't be added to the driver with a simple PORT_MODIFY("ctrl1:joypad:JOYPAD").

**Comment by DavidHaywood** [comment]
it doesn't appear in the NES lists, there's a structure listing what's available for each system

**Pull request closed without merging**
