### PR TITLE
Out Run: simpler sprite logic 

### PR DESCRIPTION
**Pull request by jotego**
This simplifies the code to make it more readable
- There is no +1 or -1 in the data[7] assignment
- The flip/no flip cases are combined
- The meaning of "flip" is clearly stated
- The long line with multiple statements is broken into several lines
- It's shorter, even after expanding that long line
- Corrects the wrong "four pixels" comment (should be eight)

Tested with _Out Run_ and _After Burner_.

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
Please put what’s affected in the pull request title and description.  The title of this pull request doesn’t give enough context to know what it affects.

Please use consistent formatting, matching the style of the file.  sega/sega16sp.cpp seems to predominantly use Allman formatting.  Please don’t mix K&R formatting.

Please use consistent spacing for flow control statements and around parentheses.  The “English” convention is preferred in MAME (space between keyword and opening parenthesis of control expression, no space on inside of parentheses, spaces around binary operators).

The formatting should look like this:
```
    if (foo)
    {
        ...
    }
    else
    {
    }
```
etc.

**Comment by jotego** [comment]
I've added the core name to the title. I think the description is already good enough. Please ask me something more specific if you need an answer.
I've modified the formatting as you requested.
I hope this is enough.

**Comment by jotego** [comment]
I had missed your comment about the spaces. That's done now too.
Thank you for enforcing consistency in the code. The only thing worse than a bad convention is not having one. So I appreciate your efforts.

**Comment by galibert** [comment]
Can't we drop the pixels reorganization line and just use int pix = (pixels >> (28-4*k)) & 0xf; ?  And adjust the end-of-line test, of course.

**Comment by jotego** [comment]
I see your point, the code will be more succint. But I think the proposed code is more representative of how the real hardware works (a per-pixel shift register) and easier to understand.
It is also more efficient computationally to always shift by 4 and keep the result for the next iteration.

**Comment by galibert** [comment]
I suspect you are incorrect, efficiency-wise, for two reasons.  First the variable shift allows to drop the 8 fixed shifts of the inverter, which can be a lot.  Second, implementing it as a shift-register gets you a chain of dependencies between loop iterations (mask depends on all the previous shifts to have been done) which goes away when pixels is readonly, loop-wise (multiple shift/mask can be issues in parallel).  Given how far prediction goes in modern cpus that can make a difference.

If you really want to show it's a shift register, I'd do a fixed pix = (pixels >> 28) & 15 and shift left though, that inverter is too magic for a casual code reader.

**Comment by jotego** [comment]
Thank for your reviewing. I don't want to go deep in a technical or formatting discussion about this. The way I wrote it makes more sense to me from a hardware description point of view. I will not make further commits about this PR.

**Comment by galibert** [comment]
No problem, I'll do the final changes myself.  Thanks for the PR in any case :-)

**Comment by jotego** [comment]
Thank you for your understanding

**Comment by galibert** [comment]
Oh duh, I had missed it was in the flip case only.  Makes perfect sense then.

**Comment by jotego** [comment]
In the hardware, it shifts in the other direction and collects data from the other end when flip is set. But writting it that way in C may be slower and more confusing for the human reader. So I kept the same shifting in the loop for both cases and just re-arranged the data in the flip case.

**Pull request merged**
