### PR TITLE
Split Common Data East HuC6280 CPU based sound system to seperated device

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
Can you fix up some of the problems with some of your existing submissions before moving forward?

We're less than a week away from a release, which means we're half a week away from code lockdown.  Going into a new release with things like Boogie Wings and Night Slashers broken is bad form.

**Comment by bmcphail** [comment]
I'm not especially precious about it but why is Aaron a copyright holder on
a new file called deco6280 when he wasn't on any the files that it's
derived from?

I don't really feel it's my place to comment on Mame internals too much
these days, but is making a device like this the 'right' thing to do?  On a
real board the 6280, YM2151, YM2203, Okis, are discrete chips - they can be
mixed and matched (as can be seen some boards have 1 oki, some 2, later
ones don't have the YM2203).  So is bundling all those combinations into a
catch-all 'device' right?    Others can decide.

Hey, it wouldn't be Mame if all the files weren't constantly refactored
every year... :)

**Comment by ajrhacker** [comment]
I'm not so much in favor of this sort of subsystem wrapper device, mostly for the reasons @bmcphail mentioned. The idea might have merit if it would help fix MT #389 and related issues, but I don't see how that would follow from this.

**Comment by DavidHaywood** [comment]
Well the MAME concept of a device is a rather abstract thing, and often gets used to group common configurations and common design patterns found in the original hardware.  This in turn leads to less duplication in MAME, less to maintain, and less room for errors to creep in.

The PCBs were likely designed with these things as templates / building blocks anyway, which is why you see the reuse.

In that sense, I don't actually think this change is a bad thing at all, if anything I'd encourage it.

As for copyright owners, at this stage I really don't know.  I think once Aaron did do some work to improve the sounds in some of the Data East stuff..

**Comment by aaronsgiles** [comment]
LOL, no, I had nothing to do with Data East code pretty much ever, except touching files for cleanup. Please assign copyright to someone else.

Devices can be hierarchical, and this means that, say, entire common sound boards can be made into devices. In fact, the outputs of all the chips can be mixed at the device level and fed into the master output. See the atarijsa as the canonical example, though I remember doing it to a few other common situations as well. Maybe the exidy/berserk sound board? Or Sega USB? Memory is fuzzy....

**Comment by aaronsgiles** [comment]
Oh yeah, it was the Midway sound boards (Chip Squeak, etc.) that merited the device treatment as well. Doing so allowed for mixing and matching and in some cases combining multiple sound boards per-machine, as was done on the original hardware.

**Comment by cam900** [comment]
This commit is now outdated, Close this.

**Pull request closed without merging**
