### PR TITLE
ninjaw.cpp, warriorb.cpp : Accurate psg output position (subwoofer only)

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by cuavas** [comment]
The "subwoofer" position is going to be renamed, since "subwoofer" doesn't describe a location (it's a low-frequency effects channel).  Where is the subwoofer actually located on the cabinet?

**Comment by wd40yasu** [comment]
under the players' seat

**Comment by cuavas** [comment]
@wd40yasu thanks.  @cam900 please wait until I push an update with better pre-defined speaker locations.

**Comment by cuavas** [comment]
d672b349122f9b3a93d2bea377f3e87470bfae4e gives more speaker positions

**Pull request merged**
