### PR TITLE
bus/nes_ctrl: Updated mahjong controller based on hardware info.

### PR DESCRIPTION
**Pull request by 0kmg**
- Fixed reversed Start and Select buttons.
- Added more labels to the multi-use buttons.

### CODE REVIEW

**Comment by 0kmg** [comment]
This works...provided you remove one or both Famicom joypads. If not and the mahjong controller is in the expansion slot you get (i.e. the mahjong buttons that I didn't rename don't show up):
inputs

**Comment by 0kmg** [comment]
Oh, and [here's](https://i.ebayimg.com/images/g/DbwAAOSwaZFa-9xH/s-l1600.jpg) a picture of the sequel game's controller to illustrate the extra button function markings. Hardware-wise it behaves the same as the first controller. The extra labels are necessary to make sense (move around) in the sequel's RPG mode.

**Comment by 0kmg** [comment]
Thanks @cuavas, that fixed my issue. I added P4 because it sounded like you were thinking of doing so anyway. To be clear though, for this PR the Famicom only needed P3.

**Comment by cuavas** [comment]
Using N/M for yes/no is pretty normal for arcade mahjong and hanafuda games.

**Comment by 0kmg** [comment]
Good to know. I see there are some mahjong controllers like the ones by Pana that label N/M the other way no/yes. That's gotta be annoying if most of the arcade machines do it the other way around.

**Pull request merged**
