### PR TITLE
balsente: Improved the documentation about the Spanish Trivial sets and added a missing PAL for the Bally/Sente PCB [ClawGrip, Recreativas.org]

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
what's on the alt sound board? is it the same chips or was it reprogrammed to use something much cheaper like AY8910s ?

**Comment by Osso13** [comment]
as written in the driver: // sound PCB has: 2x Z80CTC, 2x AY8910A, 1x M5205, 1x 8MHz XTAL (divisor unknown for every device)

    Il giovedì 29 novembre 2018, 15:44:14 CET, David Haywood <notifications@github.com> ha scritto:  
 
 
what's on the alt sound board? is it the same chips or was it reprogrammed to use something much cheaper like AY8910s ?

**Comment by DavidHaywood** [comment]
ahh right, missed that note :)  guess I'll look into emulating it if nobody else does

**Comment by clawgrip** [comment]
Haze,
 Please, find here the PCB manual: 
http://media.recreativas.org/manuales/trivial-pursuit-maibesa-manual.pdf

It should be useful at least for the dipswitches.

Thanks. Regards.

**Pull request merged**
