### PR TITLE
WIP KRON-180 terminal controller

### PR DESCRIPTION
**Pull request by JoakimLarsson**
Sorry guys but I can't figure out why I can't get this to link with the full MAME, just as a single driver build. For the full build I get this error:

`GCC 6.2.0 detected
Building driver list...
33747 driver(s) found
Compiling generated/mame/mame/drivlist.cpp...
Compiling generated/version.cpp...
Emitting mamevers.rc...
Compiling resources scripts/resources/windows/mame/mame.rc...
Linking mame64.exe...
../../../../mingw-gcc/obj/x64/Release/generated/mame/mame/drivlist.o:drivlist.cpp:(.rdata+0x14cf0): undefined reference to `driver_kron180'
collect2.exe: error: ld returned 1 exit status
mame.make:240: recipe for target '../../../../../mame64.exe' failed
make[2]: *** [../../../../../mame64.exe] Error 1
makefile:952: recipe for target 'mame' failed
make[1]: *** [mame] Error 2
makefile:950: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2`

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
It passed, must be something wrong in my setup then. maybe the GCC 6.x linker...?

**Comment by happppp** [comment]
AFAIK the autochecker doesn't do a full compile.

**Comment by mmicko** [comment]
if you are doing small build locally, just add REGENIE=1 parameter in
command line  to force regeneration of project file

**Comment by JoakimLarsson** [comment]
I did the REGENIE=1 and it worked, but failed on ming32 in the full build. So maybe it does still fail if autochecker doesn't do a full build. I will try on my linux machine too.

**Comment by JoakimLarsson** [comment]
removing the build catalog completely solved it, so I am fine with it now :)

**Pull request merged**
