### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
----------
Game & Watch: Mickey Mouse (panorama screen) [algestam, Mr Jiggles the Christmas Man]

### CODE REVIEW

**Comment by happppp** [comment]
DC-95, right? not MC

**Comment by happppp** [comment]
And I'd keep "LCD is different" in the gamelist notes, so simply change the "?" to "," :D

**Comment by algestam** [comment]
Oh, I messed the naming. Thanks for finding it and I'll prepare a fix. Also, I'll change the wording regarding the LCD.

**Comment by happppp** [comment]
Thanks!

**Comment by john-iv** [comment]
Should Donkey Kong Circus be a clone of this?  Seems the first party IP would be the parent.

**Pull request merged**
