### PR TITLE
Additions and changes to Spectrum-related softlists

### PR DESCRIPTION
**Pull request by ICEknigh7**
**specpls3**
Spectrum disk version of Comando Tracer has been verified to be the standalone release, so its entry was changed.
Added list of known undumped games and other observations.

**spectrum_cass**
Added two demos and a good dump.
-Shock Megademo (Known dump on the internet was in TAP, so I created this TZX from the "SHOCKSAVER" program in the covertape for Sinclair User 85)
-The Lyra II (Full version, as opposed to the one split across several covertapes)
-Diseñador de Juegos (Microbyte): Replaced bad dump with verified one

**timex_cass**
Added a list of the known covertapes of "Byte Power, 1st Class Magazine" as well as the only known dump.
-Byte Power (February 1988)

**timex_cass and spectrum_cass**
Detected some games published by TMX Portugal but which were actually made for the Spectrum, so I moved them to the latter's softlist.
-Assalto A Embaixada (was already in both)
-Interface RS232 (now duplicated in both softlists, since the cover mentions both systems)
-Perigos Na Selva (replaces bad dump already in Spectrum softlist)
-Programa de Apresentação
-Space Raiders - Invasores Galácticos (replaces bad dump already in Spectrum softlist)

### CODE REVIEW

**Comment by cuavas** [comment]
Are there any objections to this from the resident ZX Spectrum experts?

**Comment by DavidHaywood** [comment]
ICEknigh7 can be trusted, and is obviously working with the people redumping the tapes etc. so yes, again as long as their PRs pass standards, they should be accepted.

**Comment by cuavas** [comment]
@ICEknigh7 please confirm the dump credit for the addition to timex_cass.xml (Byte Power (February 1988)).

**Comment by ICEknigh7** [comment]
Regarding credits for Spectrum additions in general, I feel it needs to be established that it's usually next to impossible to find dump credits for anything that's found in the big Spectrum dump resources such as World of Spectrum, Spectrum Computing, The TZX Archive, TOSEC, etc, since they don't actually credit whoever dumped them (and when they do give credit it's usually to whoever *submitted* it instead). For most of these entries, you could name either of them interchangeably and the dumping credit would be given equally (in)correctly, just like giving credit to a ROM site for any random dump that's been on the internet for decades.

*However*, in this case, I've been able to track down the original dump's source on this old archived site, which seemed to belong to @aralbrec: [https://web.archive.org/web/20090723102438/http://www.geocities.com/aralbrec/](url)

So the known credits for anything new here would be:

**timex_cass**
- Byte Power (February 1988) [aralbrec]

**spectrum_cass**
- Diseñador de Juegos (Microbyte) [Juan Pablo López, SPA2]
- Shock Megademo [ICEknigh7]

By the way, if anyone reading this has any materials related to this "Byte Power" magazine please get in touch with me. There seem to be a lot of Timex games yet to be preserved in those lost tapes (more info [here](http://www.retrolel.com/en/disenador-de-juegos-from-microbyte-spectrum/)).

**Comment by DavidHaywood** [comment]
Right, I still have stuff I was given rotting away on my HDD, unable to process it because there aren't proper credits / I can't 100% verify where it came from.

Sometimes stuff is just 'anonymous' for lack of better option.  Sometimes people even intentionally make sure there's no paper trail (especially if they're pushing out stuff that's been 'lost' for 40 odd years)

**Pull request merged**
