### PR TITLE
sun1: replace console hack with upd7201 device

### PR DESCRIPTION
**Pull request by shattered**

### CODE REVIEW

**Comment by rb6502** [comment]
This is not correct for Sun1 machines, which have an i8251 with the baud rate driven by an AMD programmable timer.

**Comment by ajrhacker** [comment]
We don't have an Am9513 device yet. Several other drivers also need one.

**Comment by rb6502** [comment]
Yeah, and the 9513's weirdo 8/16 bit interface is why I was hoping to trick someone else into doing it :)

**Comment by shattered** [comment]
Does a test suite exist for 9513?

**Comment by rb6502** [comment]
Not that I'm aware of.  I'll pass this for now because it *is* marginally better than the terminal hack, but we do want to see 9513 in the future (Sun2 and I think Sun3 also use it).

**Pull request merged**
