### PR TITLE
aica.cpp, aicadsp.cpp : Updates

### PR DESCRIPTION
**Pull request by cam900**
Add save states, device_memory_interface for PCM and DSP memory, Fix code styles, Fix some namings, Reduce unnecessary lines, Reduce unused values, Use shorter/correct type values, Simplify handlers

### CODE REVIEW

**Comment by DavidHaywood** [comment]
what is the performance impact of this?

**Comment by cam900** [comment]
It's slightly slowly but saveable some states.

**Comment by DavidHaywood** [comment]
you see that's the problem, if it's noticeable slower, even with the Naomi emulation then it's not a good solution.

I know it's a more modern way, but unless every system using a device is already running well within the region of comfortable framerates on modest hardware then it isn't really a good thing for the project; there are no benefits in the end result.

All we're seeing with this (and in other cases, like ST-V) is modernizations eating away at the rather minor performance increases we're seeing from Intel etc. and keeping 100% emulation speeds just out of reach at every step (which in turn leads to people choosing older versions of MAME, where other aspects of the emulation are worse)

There are still outstanding (significant) performance regressions in things like Seibu SPI (during the flashing sequence) due to similar changes.

Unless MAME performance when going through the memory handlers improves significantly this kind of modernization isn't always a positive.  It's great for widely used chips where performance isn't an issue (eg the OKI6295) but here I'm not convinced.

I don't get final call on this, and it's just my personal opinion, but we should be avoiding things that make already difficult emulation cases (in terms of performance) even more difficult.

**Comment by p1pkin** [comment]
My 5 cents - current SCSP and AICA in MAME is not really good and accurate by design. I see little to none sense improve current implementation (i.e. I think @cam900 is only wasting his and our time here).
In my opinion it will much better to replace current SCSP with really good one, for example from Mednafen.

**Pull request merged**
