### PR TITLE
new NOT WORKING --- TV games, help required to identify architecture of one of them

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING
---
Play TV Buckmasters Huntin' (NTSC) [Sean Riddle, Peter Wilhelmsen]
Track & Field Challenge [Sean Riddle, Clawgrip]

Huntin' needs the gun mapping, Track & Field however I can't identify the CPU architecture, so could really do with some help there.

### CODE REVIEW

**Comment by ajrhacker** [comment]
Track & Field Challenge appears to be g65816, m37710 or something similar.

**Comment by DavidHaywood** [comment]
where are the boot vectors?

**Comment by DavidHaywood** [comment]
also what are you seeing that looks like valid code for those types?

**Comment by happppp** [comment]
FWIW I'd go for "trackfldch", you're not limited to 8 characters.

**Comment by ajrhacker** [comment]
Here's one interrupt routine, which may be vectored to from 00000e:

> 0022ed: 78                 SEI
> 0022ee: c2 30              CLP #$30
> 0022f0: da                 PHX
> 0022f1: 48                 PHA
> 0022f2: 5a                 PHY
> 0022f3: 0b                 PHD
> 0022f4: 22 dd af 00        JSL $00afdd
> 0022f8: c2 30              CLP #$30
> 0022fa: 2b                 PLD
> 0022fb: 7a                 PLY
> 0022fc: 68                 PLA
> 0022fd: fa                 PLX
> 0022fe: 58                 CLI
> 0022ff: 40                 RTI

And here's a bit of some later code:

> 008029: a9 01 00           LDA #$0001
> 00802c: 8f 6e 11 00        STA $00116e
> 008030: 22 46 5e 01        JSL $015e46
> 008034: a9 00 00           LDA #$0000
> 008037: 8f 5c 00 00        STA $00005c
> 00803b: a9 00 00           LDA #$0000
> 00803e: e2 20              SEP #$20
> 008040: 8f 38 00 00        STA $000038
> 008044: c2 20              CLP #$20
> 008046: a9 00 00           LDA #$0000
> 008049: e2 20              SEP #$20
> 00804b: 8f 39 00 00        STA $000039

**Comment by DavidHaywood** [comment]
it's not a clone, therefore I prefer to stick within 8 characters

**Pull request merged**
