### PR TITLE
New software list additions [gbcolor.xml]

### PR DESCRIPTION
**Pull request by ICEknigh7**
Added some previously undumped games, clones and release candidates which arised recently. Also added the official ROM submission date to some of these entries, which gives an idea of when the game was ready versus when it was released (more useful in those cases where we don't even have a release date).

I've organized all the previously unknown dumps in this spreadsheet, for reference: https://docs.google.com/spreadsheets/d/1Ay20atcx39ytrM1YOhC0aST5t7M_JZegdOrbUyYc6_I/edit?usp=sharing

New games:
		Absolute X (Euro, Release Candidate 1)
		AMF Bowling (USA)
		Austin Powers - Yeah, Baby, Yeah! (Euro, Release Candidate 3)
		Austin Powers - Why Make Millions...? (Euro, Release Candidate 0)
		Billiard Club (Jpn, Release Candidate 0)
		Bounced (Euro, Release Candidate 0)
		Carmageddon TDR 2000 (Euro, Release Candidate 0)
		Carnivalé (USA, Release Candidate 1)
		Carrera (Euro, Release Candidate 0)
		Equestriad 2001 (Euro, Release Candidate 1)
		Ganso! Doubutsu Uranai + Ren'ai Puzzle (Jpn, Release Candidate 1)
		Gimmick Land (Jpn, Release Candidate 0)
		Grand Casino (Jpn, Release Candidate 0)
		Famicom Bunko - Hajimari no Mori (Jpn, Release Candidate 1)
		Jibaku-kun - Zero no Ki no Kajitsu (Jpn, Release Candidate 1)
		Kanji Shishuu (Jpn, Release Candidate 0)
		Kirby Family (Jpn, Release Candidate 0)
		Magi-Nation - Keeper's Quest (USA, Release Candidate 1)
		Max Steel - Covert Missions (USA, Release Candidate 1)
		Mission Bravo (USA, Release Candidate 0)
		Mission Impossible (Euro, Rev. A)
		Runelords (USA, Release Candidate 1)
		Sea-Doo Hydro Cross (USA, Release Candidate 2)
		Space-Net - Cosmo Neo (Jpn, Release Candidate 0)
		Towers II - Plight of the Stargazer (USA, Release Candidate 0)
		VR Sports Powerboat Racing (USA)

New clones:
		3D Pool Allstars (USA, Release Candidate 1)
		Blue's Clues - Blue's Alphabet Book (USA, Rev. A, Release Candidate 0)
		Bomberman Selection (Kor, discarded Release Candidate 0)
		Bomberman Selection (Kor, discarded Release Candidate 1)
		Cardcaptor Sakura - Tomoeda Shougakkou Daiundoukai (Jpn, Rev. A, Release Candidate 0)
		Carmageddon - Carpocalypse Now (USA, Release Candidate 3)
		Casper (USA, Rev. A, Release Candidate 1)
		Catwoman (Jpn, Release Candidate 0)
		Daikatana (USA, Release Candidate 0)
		David Beckham Soccer (USA, Release Candidate 0)
		Dejiko no Mahjong Party (Jpn, Rev. A, Release Candidate 0)
		Denki Blocks! (USA, Release Candidate 0)
		Donkey Kong Country (USA, Not for resale)
		E.T. The Extra Terrestrial - Digital Companion (Euro, Release Candidate 2)
		F-1 World Grand Prix (Jpn, Release Candidate 0)
		F-1 World Grand Prix (Jpn, Release Candidate 1)
		F-18 Thunder Strike (USA, Release Candidate 2)
		Primera División Stars 2001 (Spa, Release Candidate 3)
		F1 Racing Championship (USA, Release Candidate 0)
		Formula One 2000 (Euro, Release Candidate 8)
		Fushigi no Dungeon - Fuurai no Shiren GB2 - Sabaku no Majou (Jpn, Alt)
		Game Boy Wars: Pocket Tactics (Jpn, Release Candidate 2)
		Gift (Euro, Rev. A, Release Candidate 1)
		Gifty (Ger, Rev. A, Release Candidate 2)
		Heroes of Might and Magic (USA, Rev. A, Release Candidate 0)
		Jeremy McGrath Supercross 2000 (Jpn, Release Candidate 0)
		Jimmy White's Cueball (USA, Release Candidate 7)
		Jissen ni Yakudatsu Tsumego (Jpn)
		Kanji Boy 2 (Jpn, discarded Release Candidate 0)
		Laura (Euro, Rev. A, Release Candidate 0)
		Lemmings (Euro, Release Candidate 2)
		Little Mermaid II - Pinball (Jpn, Release Candidate 0)
		Monster Traveler (Jpn)
		Nakayoshi Cooking Series 5 - Cake o Tsukurou (Jpn, discarded Release Candidate 1)
		Nakayoshi Cooking Series 5 - Cake o Tsukurou (Jpn, discarded Release Candidate 2)
		NBA Show Time - NBA on NBC (USA, Rev. A, Release Candidate 0)
		The New Addams Family Series (Euro, Rev. A, Release Candidate 0)
		Pocket GT (USA, Release Candidate 1)
		Pocket Music (USA, Release Candidate 1)
		The Powerpuff Girls - Il Terribile Mojo Jojo (Ita, Release Candidate 4)
		The Powerpuff Girls - Bad Mojo Jojo (UK?, Release Candidate 0)
		The Powerpuff Girls - Paint the Townsville Green (UK?, Release Candidate 0)
		Qix Adventure (USA, Release Candidate 2)
		RPG Tsukuru GB (Jpn, Rev. A, Release Candidate 0)
		Shin Megami Tensei Devil Children - Shiro no Sho (Jpn, Rev. A, Release Candidate 1)
		Spy vs. Spy (Euro, Rev. A, Release Candidate 0)
		Spy vs. Spy (USA, Rev. A, Release Candidate 0)
		Street Fighter Alpha - Warriors' Dreams (Euro, Rev. A, Release Candidate 0)
		Suzuki Alstare Extreme Racing (USA, Release Candidate 0)
		Swing (Euro, Release Candidate 1)
		Sylvanian Families 2 - Irozuku Mori no Fantasy (Jpn, Rev. A, Release Candidate 1)
		Taxi 2 (Euro, Release Candidate 0)
		Tiny Toon Adventures - Dizzy's Candy Quest (USA, Release Candidate 2)
		Tonka Construction Zone (USA, discarded Release Candidate 0)
		Tony Hawk's Pro Skater (Jpn, Release Candidate 0)
		Top Gear Pocket 2 (Jpn, Rev. A, Release Candidate 0)
		Top Gear Pocket 2 (USA, Rev. A, Release Candidate 0)
		Vegas Games (USA, Rev. A, Release Candidate 0)
		Watashi no Restaurant (Jpn, discarded Release Candidate 0)
		Watashi no Restaurant (Jpn, discarded Release Candidate 1)
		Watashi no Restaurant (Jpn, discarded Release Candidate 2)
		Wendy - Der Traum von Arizona (Ger, discarded Release Candidate 0)
		Xtreme Wheels (Jpn, Release Candidate 0)
		Yu-Gi-Oh! - Dark Duel Stories (Euro, discarded Release Candidate 0)
		Yu-Gi-Oh! - Duel des Tenebres (Fra, discarded Release Candidate 0)

Corrected dumps from unknown sources with official dump (old entries now marked as "bad dump?"):
		Laura (Euro)
		Pro Pool (USA)
		Yakouchuu GB (Jpn)

### CODE REVIEW

**Comment by rb6502** [comment]
Several devs, myself included, have concerns about anything associated with the Nintendo "leaks" and would prefer nothing from them be included in MAME at this time.

**Comment by ICEknigh7** [comment]
What about just those found inside the numbered "presumed retail" folders? Would those be valid?

**Comment by DavidHaywood** [comment]
I'd argue this is all 'matter of fact' at this point, and that by NOT including the hashes, and instead giving them special treatment we open up MAME to potentially more issues.

There's no connection between Mamedev and the leak, and there are hundreds of other leaked things supported by MAME, so all MAME is doing is documenting facts.  A lot of prototypes already listed in reality came to be this way.

Only cases where things have been excluded before are where there have been direct connections back to Mamedev, or people trying to make them by claiming to be the source of dumps (even if in reality they were lying)

Mamedev is just a neutral body documenting what is known and now established as fact, we're not distributing the ROMs, there's no connection.

**Comment by ICEknigh7** [comment]
Let's try this again: https://github.com/mamedev/mame/pull/7257

**Pull request closed without merging**
