### PR TITLE
July 2022 update for Apple software lists.

### PR DESCRIPTION
**Pull request by Firehawke**
New working software list additions (apple2_flop_orig.xml)
----------------------------------------------------------

Lauren of the 25th Century [4am, Firehawke]

New working software list additions (apple2_flop_clcracked.xml)
---------------------------------------------------------------

Key Lingo (Revision 2) (cleanly cracked) [4am, Firehawke]
Number Explorer (cleanly cracked) [4am, Firehawke]
PFS File (Version B.01) (cleanly cracked) [4am, Firehawke]
PFS File (Version C.00) (cleanly cracked) [4am, Firehawke]
PFS Graph (Version 1983-01-12) (cleanly cracked) [4am, Firehawke]
PFS Graph (Version 1984-01-31) (cleanly cracked) [4am, Firehawke]
Spanish for Mastery (cleanly cracked) [4am, san inc, Firehawke]
The Chambers of Vocab (Revision 2) (cleanly cracked) [4am, Firehawke]
Take 1 (Version 06401) (cleanly cracked) [4am, Firehawke]
Sur les traces du Deirdron (cleanly cracked) [4am, Firehawke]
Pixit (Version 01331) (cleanly cracked) [4am, Firehawke]
Portrait Robot (cleanly cracked) [4am, Firehawke]
PFS Write (Version 1986-01-01) (cleanly cracked) [4am, Firehawke]
Blazing Paddles (Revision 0) (cleanly cracked) [4am, Firehawke]
PFS Graph (Version 1984-03-14) (cleanly cracked) [4am, Firehawke]
PFS Write (Version 1984-09-27) (cleanly cracked) [4am, Firehawke]
PFS Report (Version B:00 1981-01-03) (cleanly cracked) [4am, Firehawke]
Rainy Day Games (Version 13501) (cleanly cracked) [4am, Firehawke]
Ski Crazed (Version 28701) (cleanly cracked) [4am, Firehawke]
Video Vegas (Version 12511) (cleanly cracked) [4am, Firehawke]
Trickster Coyote (Version 1984) (cleanly cracked) [4am, Firehawke]
Blazing Paddles (Version 04421) (cleanly cracked) [4am, Firehawke]
PFS Report (Version 1982-01-14) (cleanly cracked) [4am, Firehawke]
Prince (Version 15531) (cleanly cracked) [4am, Firehawke]
PFS Write (Version 1984-11-01) (cleanly cracked) [4am, Firehawke]
German Vocabulary for Shopping Use (cleanly cracked) [4am, Firehawke]
Profession Détective: Qui a volé Lily (cleanly cracked) [4am, Firehawke]
The Factory (Version 1984) (cleanly cracked) [4am, Firehawke]
Prince (Version 15521) (cleanly cracked) [4am, Firehawke]
Fractions en Folie (cleanly cracked) [4am, Firehawke]
PFS Etat (Version 1984-11-26) (cleanly cracked) [4am, Firehawke]
Magicalc (Version 2.0-1984) (cleanly cracked) [4am, Firehawke]
Disk Optimizer II (Version 1.1) (cleanly cracked) [4am, Firehawke]
CHASM Checking Account Systems Manager (cleanly cracked) [4am, Firehawke]
Learning about Geography, Maps, and Globes (cleanly cracked) [4am, Firehawke]
Science Volume 1: The Environment (cleanly cracked) [4am, Firehawke]
Master Diagnostics II and II Plus (cleanly cracked) [4am, Firehawke]
PFS Fichier (Version 1984-11-26) (cleanly cracked) [4am, Firehawke]
PFS Report (Version 1985-09-10) (cleanly cracked) [4am, Firehawke]
Pacific 231 (cleanly cracked) [4am, Firehawke]
Sherwood Forest (cleanly cracked) [4am, Firehawke]
Mathematics Courseware Problem Solving Level 5 (cleanly cracked) [4am, Firehawke]
Star Warrior (Revision 2) (cleanly cracked) [4am, san inc, Firehawke]
Counting Parade (Revision 0) (cleanly cracked) [4am, Firehawke]
Living Chess Library: Paul Whitehead Teaches Chess (cleanly cracked) [4am, Firehawke]
Living Chess Library: King's Indian Defense (cleanly cracked) [4am, Firehawke]
Living Chess Library: 50 Classic Games (cleanly cracked) [4am, Firehawke]
Cotton's First Files (cleanly cracked) [4am, Firehawke]

New working software list additions (apple2gs_flop_orig.xml)
------------------------------------------------------------

Tomahawk [4am, Firehawke]

New working software list additions (apple2_flop_misc.xml)
----------------------------------------------------------

Lauren of the 25th Century [4am, Firehawke]

### CODE REVIEW

**Comment by ArcadeShadow** [comment]
What's the reason in adding in all the description's sets the "(cleanly cracked)" reference, if the Software List description already tell us that?

**Comment by Tafoid** [comment]
I

> What's the reason in adding in all the description's sets the "(cleanly cracked)" reference, if the Software List description already tell us that?

Not 100% sure, but given that multiple compatible lists share the same base game name description, the signification allows you to select it easier in menus.

**Comment by ArcadeShadow** [comment]
For this kind of reason (i.e. Crime Stopper)?
image

Well maybe it would be better to add a column with the Software List name, like MAMEUI
image

Just my opinion...

**Comment by Firehawke** [comment]
As noted by Tafoid, it makes it significantly easier to know what's an original disk as compared to a cleanly cracked disk. Compatibility may vary between the two, especially in the case of Apple II software where the protection frequently could break on newer model machines even where the actual software would run fine.

**Pull request merged**
