### PR TITLE
start improving mpu4vid set names, weeding out duplicates + correct utf8 use + some non-working Plug Play

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING machines
------
Lexibook Console Colour - Minnie Mouse [Team Europe]
Lexibook Console Colour - Disney's Planes [Team Europe]

- improved descriptions of several mpu4vid sets based on boot information [David Haywood]

### CODE REVIEW

**Comment by happppp** [comment]
Related:

Can we standardize UTF8 in strings?
- here it's \u00a3
- in lft_craft it's \xc3\xa3
- I saw cuavas suggesting the prefix u8, eg. u8"mystring"

And what about strings elsewhere, like PORT_NAME, I have some of them without any prefix or escapes and it works fine, example:
https://github.com/mamedev/mame/blob/master/src/mame/drivers/debut.cpp#L212

**Comment by DavidHaywood** [comment]
\xc3\xa3 didn't even want to compile for me when I tried it

**Comment by cuavas** [comment]
I’d rather we don’t have any completely unadorned ones like the one in debut.cpp – IIRC MSVC doesn’t like them, and really we should be setting the desired encoding of the string.  In that case, the `PORT_NAME` macros should use `u8"АН (Analysis)"`, `u8"ХОД (Force Move)"` and so on.

I’d also rather we get rid of the escaped UTF-8 codes, as they’re ugly and more annoying to look up.  They’re no longer necessary now that all the compilers support `u8` strings and `\u` escapes.  So no more `\xc3\xa3` please.

When you *are* using `\u` escapes, you still need the `u8` qualifier for the string to set the desired encoding, or MSVC will be upset.  For example see the names of the keys [here](https://github.com/mamedev/mame/blob/32e23a104ef216b23e49035892a1b98dd303afbe/src/devices/bus/mackbd/pluskbd.cpp#L381).

Characters with Unicode codepoints below the end of the Cyrillic supplement are allowed in strings by srcclean – you can use them in strings with the `u8` qualifier.  You just need to have your text editor set to the correct encoding.

**Comment by cuavas** [comment]
[Here](https://github.com/mamedev/mame/blob/32e23a104ef216b23e49035892a1b98dd303afbe/src/devices/bus/mackbd/pluskbd.cpp#L392) is a line that has a character outside ASCII (`¥`) and a Unicode escape (`\u30d8`) in a `u8` string as an example.

**Comment by happppp** [comment]
Alright, the pound symbol is below the end of the Cyrillic block so it should be fine (and more readable in source) to use u8"mystring £10" then

**Pull request closed without merging**
