### PR TITLE
Update hnayayoi.cpp to label 2 DIP switches

### PR DESCRIPTION
**Pull request by gingerbeardman**
Adds descriptions of 2 DIP switches for the game hnayayoi (Hana Yayoi):
- 1 coin = 2 credits
- 1 coin = 5 credits

### CODE REVIEW

**Comment by cuavas** [comment]
This is not the correct way to label coinage settings.

**Comment by gingerbeardman** [comment]
@cuavas thanks for your feedback. Rather than simply, closing this PR I think it would be better to encourage revision so that it is the correct way to label coinage settings. What do you think?

**Comment by angelosa** [comment]
The standard way to do [coinage](https://github.com/mamedev/mame/blob/c231ee373a461ee8555b2df25e68efea4506229d/src/mame/drivers/vsnes.cpp#L510)
Every setting interprets as `xC[oin]_yC[oinage]`, so a `1C_4C` means "for 1 coin grant 4 credits" while for a `5C_2C` it means `for 5 coins grant 2 credits`

**Comment by gingerbeardman** [comment]
Thanks, I just sae exactly that in another PR of mine and also in the edits made by @cuavas so I'll be sure to learn from those for future PRs. Cheers!

**Pull request closed without merging**
