### PR TITLE
Add SSE flag checking

### PR DESCRIPTION
**Pull request by MoochMcGee**

### CODE REVIEW

**Comment by yz70s** [comment]
This patch seems to make assumptions about the host processor running the emulator.
If some exception flags were previously set not beacuse of the current sse instruction, but because of something else inside the emulator, those flags will be set even in the emulated processor where they souldn't be.
Then there is the call to fesetround() that will effect all calculations, even those done outside the processor core. Consider also a system with two emulated processors with different rounding modes.

**Comment by Alegend45** [comment]
Oh, shit, whoops. But how else could we emulate the different rounding
modes?

**Comment by yz70s** [comment]
The easy way is to backup the current mode, set the new one, execute the instruction and restore the old mode.
The other way is to rewrite all the sse mathematical instructions to use the softfloat library.

**Comment by rb6502** [comment]
Yeah, this is pretty much exactly why the x87 and 680x0 FPUs are done in SoftFloat.  (Also MSVC doesn't support 80-bit extended floats).  Also keep in mind that we do support PowerPC and ARM targets to some extent (ARM support will be growing this year probably).

**Comment by firewave** [comment]
Err...what? GCC is way more stupid about floating-point than Visual 
Studio (as seen with the optimization issues with FLAC).

https://msdn.microsoft.com/en-us/library/e7s85ffb.aspx

**Comment by rb6502** [comment]
GCC on x86 and x64 always picks 32-bit registers for 'float', 64-bit for 'double', and 80-bit for 'long double'.  Those sizes are 100% guaranteed to be selected based on the variable type, which is ideal for emulation (and certain other use cases).  MSVC doesn't support 'long double' at all (it's either an error or it's silently treated as a plain 'double').  This is among VIsual C's most well-known incompatibilities with other compilers (it's why Bochs and Mini vMac use SoftFloat).

**Comment by firewave** [comment]
Ah...right..."long double"...

**Comment by yz70s** [comment]
I close this because is superseded by  #133

**Pull request closed without merging**
