### PR TITLE
stkbd: Add missing keycodes

### PR DESCRIPTION
**Pull request by ksherlock**
The st ikbd matrix was missing a number of characters.

### CODE REVIEW

**Comment by galibert** [comment]
There was a bunch of ST keyboard layouts.

https://tho-otto.de/keyboards/

They were never handled in mame.  I'm not sure, how should we do it?

**Comment by rb6502** [comment]
The official @cuavas method in https://github.com/mamedev/mame/blob/master/src/devices/bus/mackbd/keyboard.cpp is to just have different layouts as slot options, although that really only makes on a machine where the keyboard is actually physically separate.

Do different region STs have different ROMs?  If so, you can do the easy thing and make them different systems.  If not I don't know since the inputs are fixed per driver/device.

**Comment by ajrhacker** [comment]
The Mega ST and Mega STe had fully detached keyboards, though Atari didn't maintain a consistent connector pinout because incompatibility was the standard for keyboard engineering back then. There's also at least one (dumped) third-party ST keyboard.

**Comment by Luigi30** [comment]
> The official @cuavas method in https://github.com/mamedev/mame/blob/master/src/devices/bus/mackbd/keyboard.cpp is to just have different layouts as slot options, although that really only makes sense on a machine where the keyboard is actually physically separate.
> 
> Do different region STs have different ROMs? If so, you can do the easy thing and make them different systems. If not I don't know since the inputs are fixed per driver/device.

TOS ROMs came in different languages and the scancode -> key translation table is hardcoded according to the TOS language. The keyboard itself is internally the same in all regions other than the keycaps.

**Pull request merged**
