### PR TITLE
-debugcmd: Add the ability to save per-device regions. [Ryan Holtz]

### PR DESCRIPTION
**Pull request by MooglyGuy**

### CODE REVIEW

**Comment by cuavas** [comment]
I don’t think we need an extra command for this.  The `save`, `saved` and `savei` commands already allows a device to be specified as an optional fourth parameter.  It’s interpreted as a device tag first, and if that fails, as an index to a `device_execute_interface` enumerator.

At a quick glance, I didn’t see anything limiting the devices it works with:
* For tags, `validate_cpu_parameter` doesn’t check that the device implements any particular interface (i.e. it just checks for a device, it doesn’t have to be CPU-like).
* After that passes, `validate_cpu_space_parameter` just checks that the device implements `device_memory_interface` and has the specified space number populated.
* There are no artificial restrictions in `execute_save` either.

That should allow you save data from space 0, 1, or 2 of anything that implements `device_memory_interface` in the system.

If the issue is that you have a device using higher space numbers that you want to save data from (e.g. a 4040 CPU), the correct solution would be to extend the syntax for the fourth argument to `save` to allow including an arbitrary space number.  This is something we *do* need at some point, but we need to decide on an unambiguous syntax for it that doesn’t suck.  (See the debacle over attempting to extend `bpset`/`wpset` and accidentally preventing decimal addresses in breakpoints.)

What was the actual device the person wanted to save data for?

Also, the title of the PR is misleading – it’s not for saving arbitrary memory regions (the `saver` command already does that), it’s for saving data from device address spaces.  “Regions” has a meaning in MAME’s memory system.

**Comment by cuavas** [comment]
Assuming you’re talking about [this reddit post](https://www.reddit.com/r/MAME/comments/pw8285/is_it_possible_to_dump_vram/) I described one to do what the user wants.  There are multiple ways to do it via Lua as well.

Three things I noticed while writing that were that the description for those commands doesn’t explain the optional device parameter very well, you can’t get help for the alternate names of the command directly, and the Qt debugger copies whitespace at the end of blank lines.

**Comment by MooglyGuy** [comment]
I am referring to exactly that post. If this is the way it's supposed to be, then either the help text for the "save" command needs to be improved to not be CPU-specific and/or to have examples of named devices so that the impression isn't given that it only operates on CPU indices, or this PR should be applied on the contingency that help text be written specifically for it. It's just not a great experience for users otherwise.

**Comment by cuavas** [comment]
Too many issues:
* The actual use case that motivated this is already covered by existing commands.
* Discussion has already started about extending existing commands to support more cases – increasing proliferation of commands isn’t the desired approach.
* Adds debugger commands without updating the (already somewhat outdated) help.
* Introduces a pile of repetition in the code.

**Pull request closed without merging**
