### PR TITLE
apf: Split Imagination Machine carts into their own list, fixed tape mounting from list

### PR DESCRIPTION
**Pull request by rdroush**
not for whatsnew:
Sorted official APF carts by serial number
Shortened image_interface for carts
Removed unsupported status from all entries due to emulation improvements
Misc cleanups and formatting fixes

### CODE REVIEW

**Comment by etabeta78** [comment]
I don't see any reason to split the list in two, since the carts are cross
compatible.
This is not the direction to take about this, sorry.

**Comment by rb6502** [comment]
I'd say it's useful for classification/documentation purposes to split the lists, but if you're really against it I'll go along.

**Comment by etabeta78** [comment]
The easily acceptable part has been merged (which was the tape interface
fix)
In a couple of days I'll have enough spare time to go through the pull
request more in-depth and decide about the rest.
Thanks

**Comment by rb6502** [comment]
Eta, have you had time to check this out yet?  I'm trying to keep the pull requests folder as clean as possible, and to avoid undue delays for external contributors.

**Comment by etabeta78** [comment]
it's in my todo list. I'll need a couple of days more, then I'll either
merge the remaining part or reject them.

    f.

**Comment by etabeta78** [comment]
Even after going back re-reading most documents which are available online, I'm still convinced that a unique software list is better in this case, due to the almost complete compatibility between the two machines. The two (or three) games which don't work in the apf m-1000 can be marked with a compatibility <info> tag, but split them in a separate list seems not the best solution.

**Pull request closed without merging**
