### PR TITLE
hook up payout buttons and a hopper to Mahjong Senpu, promote to working

### PR DESCRIPTION
**Pull request by mamehaze**
there does seem to be another payout mode that isn't hooked up (selected by a dipswitch), and our current hopper is always a 'ticket dispenser' which might not be accurate, but you can press the payout button and it will count down the coins, so I think that's good enough for now.

the dipswitches still need translating properly.

### CODE REVIEW

**Comment by ajrhacker** [comment]
You should use IPT_GAMBLE_BOOK and IPT_MEMORY_RESET instead of renaming IPT_SERVICE1 and IPT_SERVICE2.

**Comment by mamehaze** [comment]
ahh, I looked in a few other drivers, and the ones I looked in weren't using GAMBLE_BOOK or MEMORY_RESET, I did search for BOOKKEEPING and it didn't throw up anything so thought there wasn't a specific input for it.

if you want to merge it and correct them, and do whatever you need to do to the ticket dispenser that might help.

hooking these things up properly in MAME is relatively recent, old policy was to basically ignore them, sfbonus.cpp could does with proper hookups for all the payout / ticket printer methods too.

**Comment by cuavas** [comment]
> if you want to merge it and correct them, and do whatever you need to do to the ticket dispenser that might help.

That's not how this works.  You can't keep acting like you don't have to do things properly.  You fix it, then we merge it.

**Comment by ajrhacker** [comment]
It's not so surprising that usage of IPT_MEMORY_RESET is still relatively low; I added it to MAME only fairly recently, and since then have been going through gambling drivers to increase its usage, hooking up dispensers to most of those as well. (The reason I didn't use IPT_MEMORY_RESET in mjsister was that it actually has two "M. Reset" inputs, and neither is actually functional.)

The ticket_dispenser_device issue obviously can only be fully resolved by a larger-scale cleanup which I intend to do when I find the time for it.

**Comment by mamehaze** [comment]
> That's not how this works. You can't keep acting like you don't have to do things properly. You fix it, then we merge it.

I don't see what's wrong with letting somebody take over it if they've expressed an interest, it's what I call teamwork.

**Comment by mamehaze** [comment]
> It's not so surprising that usage of IPT_MEMORY_RESET is still relatively low; I added it to MAME only fairly recently, and since then have been going through gambling drivers to increase its usage, hooking up dispensers to most of those as well. (The reason I didn't use IPT_MEMORY_RESET in mjsister was that it actually has two "M. Reset" inputs, and neither is actually functional.)

I do also wonder if 'Memory Reset' is the correct term here, it clears the stats if you're in the bookkeeping mode, but doesn't actually completely wipe memory.  Sometimes 'Memory Reset' means blank memory entirely, sometimes initialize memory, so I'm not 100% clear on if all use cases are covered by the same input (might explain why some games have 2) or if this is actually the correct one for this situation.

> The ticket_dispenser_device issue obviously can only be fully resolved by a larger-scale cleanup which I intend to do when I find the time for it.

Thank you, that is what I was hoping to hear before the needlessly aggressive comments from somebody else.

**Comment by cuavas** [comment]
You can use trampolines to improve the ticket dispenser hookup. It isn't an unassailable issue. And teamwork also involves taking on suggestions from others, not dumping stuff expecting others to clean it up.

**Comment by mamehaze** [comment]
the ticket dispenser hookup is taken straight from a driver that was only just modernized.

**Comment by cuavas** [comment]
@ajrhacker does #1489 necessitate changes to this, or is it safe to merge in its current state?

**Comment by ajrhacker** [comment]
Well, the new ticket_dispenser_device::motor_w method is meant to replace the old WRITE8 method in drivers, since of course that device doesn't need 8 lines of communication when it only reads one and writes one. I admit that motor_w's current implementation is a crudely hacked-in wrapper, and the device needs a more thorough rewrite in general.

**Pull request merged**
