### PR TITLE
brkthru.cpp: Marked brkthrut ROMs 6, 7 and 8 as BAD_DUMP (nw)

### PR DESCRIPTION
**Pull request by clawgrip**
The PCB owner redumped the ROMs, getting variable results on ROMs 6, 7 and 8, and constant reads on all other ROMs.
He also recorded a video of the game running: https://www.youtube.com/watch?v=eBbToDz0YQw

### CODE REVIEW

**Comment by DavidHaywood** [comment]
this shouldn't have happened in the first place

rule #1 of dumping is to do multiple reads.

**Comment by clawgrip** [comment]
I know, it was not my dump, I received it from someone I did not know before. Since he provided PCB pics and a video, we know for sure that he has the board and that it is really a Tecfri license (and that the PCB is on a working state), but it's hard from my side to check the ROMs, since I lack the required skills.

**Comment by DavidHaywood** [comment]
at this point are we even sure a proper dump wouldn't match the original set?  I don't have a MAME tree to check

**Comment by Tafoid** [comment]
Might as well update with what we have at the moment is it only adds bad dump warnings.  Good in case we cannot get the PCB again and another shows up in the future.

**Pull request merged**
