### PR TITLE
Creating an -attach_window command line parameter on Windows to attach to an existing window

### PR DESCRIPTION
**Pull request by npwoods**
This allows a front end (like BletchMAME) to provide the window and the MAME executable's job is to merely write over it.  This disabling functionality that is nonsensical on a window that you don't own (like the WNDPROC), and also some changes to how focus is identified and the DirectInput code works.

I would really welcome feedback from non-Win32 people here, because it isn't clear how this should work on other platforms.  I'm also not religious about how the precise command line argument works (perhaps it should have some sort of "scheme" qualifier, like '-attach_window hwnd:0x12345678)

When this change is merged, it will be possible (by virtue of the worker_ui LUA plugin) to use BletchMAME on an off the shelf version of MAME.

### CODE REVIEW

**Comment by npwoods** [comment]
It has occurred to me that the code for deciding when not to SendMessage(WM_USER_REDRAW) should in fact, check for non-multithread instead of an attached window.  When there is not an attached window and no multithreading, SendMessage(WM_USER_REDRAW) is just a fancy way to invoke the same redrawing code that is used in the attached window branch.

**Comment by AmatCoder** [comment]
> I would really welcome feedback from non-Win32 people here, because it isn't clear how this should work on other platforms [...]

On platforms that use X11 as windowing system (like Linux), Mame just needs to expose its XID (X window ID) to the frontend.

Then, frontend can use [XEmbed protocol](https://standards.freedesktop.org/xembed-spec/xembed-spec-latest.html) to embedding MAME window.

**Comment by npwoods** [comment]
Based on that, would it make sense to make the qualifier be "schemed"?  Hypothetically, SDLMAME running on Windows should be able to accept both '-attach_window hwnd:0x12345678' and '-attach_window xid:0x87654321'

**Comment by AmatCoder** [comment]
SDLMAME create native windows depending on the platform so on Windows only the window handle (HWND) can be used.

**Comment by rb6502** [comment]
@AmatCoder, any idea about Wayland?

**Comment by AmatCoder** [comment]
Wayland does not support XEmbed and most likely it never will. From FAQ:

> Wayland allows better isolation between processes: one window cannot access resources from, or inject keystrokes into, another window. 

The only possibility would be integrate frontend into Mame source (or vice versa).

( Other would be to expose the video drawing as library API (à la libretro)... )

**Comment by npwoods** [comment]
While I know little about X11 or Wayland, it seems unlikely to me that this sort of approach is not possible.

If for example, Google Chrome can delegate handling of one of its browser tabs to one of its sandbox worker processes, it seems like a front end (like BletchMAME) should be able to delegate handling to the MAME executable.

To me, it is just a question of "how", and whether a hypothetical "-attach_window" command line option makes sense for this and other scenarios.

**Comment by AmatCoder** [comment]
AFAIK Chrome has direct access to all components (windows, surfaces, events...) of its sandbox processes.

But frontend and Mame are separated processes. They can not share memory.
Example: this would be possible if frontend had access to _SDL_Texture*_ pointer from Mame.
But it is not possible.

**Comment by npwoods** [comment]
Then the question becomes, how would a front end launch MAME in a Wayland environment that would give it the same intimate access to the child process's (MAME's) internals that Chrome has?

**Comment by rb6502** [comment]
I don't know.  I believe it's similarly easy to Windows to do this on the Mac, though.

**Comment by AmatCoder** [comment]
QMC2 uses [QWindow::fromWinId()](https://doc.qt.io/qt-5/qwindow.html#fromWinId) method.

But that doesn't work with Wayland (on Linux it uses XEmbed under the hood so only works with X11...)

**Comment by npwoods** [comment]
A question from somebody who has only read the marketing literature:  XWayland is (to my understanding), an X server on top of Wayland.  How does it implement XEmbed on top of Wayland?

**Comment by AmatCoder** [comment]
AFAIK, with XWayland, embedding the window is done by the X server.

Then X server send individual top-level window as wayland surface to Wayland compositor that just handle the presentation of that top-level window.

**Comment by npwoods** [comment]
I just discovered a problem with this PR.  My changes to "unhack" how I was handling input focus broke my technique for providing a VICE-style "set input popup".  Specifically because I was more careful to only identify MAME as having focus when an emulation window was active, when a "set input popup" (saying "Press key for blah blah") was active, input would be ignored.

To get around this problem, I introduced a osd_set_aggressive_input_focus() function and exposed it to LUA.  I only implemented this on Windows, so this PR can't be merged as is right now.  It isn't clear to me if osd_set_aggressive_input_focus() is the "correct" hook so I would welcome feedback.

We're in the home stretch for making BletchMAME usable with off the shelf builds of MAME, so I would definitely welcome feedback!

**Comment by Tafoid** [comment]
Leaving this uncommitted for this long makes it difficult to make progress?  If there are no further objections nor any reported issues with the normal UI adding this, I don't see the problem in supporting development.

**Pull request merged**
