### PR TITLE
Plug and Play sync for TeamEurope (VT1682, nes_vt, iqunlim)

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING machines
----
InterAct Complete Video Game - 111 Games & 42 Songs (G5410) [TeamEurope]
Let's Play! Game Machine 240 in 1 [TeamEurope]

new WORKING machine
----
MiWi2 7-in-1 Sports [David Shah]

new NOT WORKING Software List
----
iqunlim_cart.xml: Englisch für Anfänger [TeamEurope]

note: the VT1682 based InterAct Complete Video Game is basically playable, apart from the 'Shooting games' because I haven't mapped the guns, and some issues with player 2 / alt control schemes in some titles.   want to address these (and maybe look for a better solution to some stability issues) before promoting it.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
also @daveshah1 
your VT1682 based "MiWi2 16-in-1 + Drum Master" dump was added in the previous release

the ROM was taken from your post at 
https://www.tapatalk.com/groups/pgc_forums/miwi2-vt168-dumping-attempt-t1768.html
you also post a link to the 7-in-1 sports there, but the link is invalid, it contains a duplicate of the 16-in-1 dump, just double-zipped, and as a result I was unable to add that dump.

do you have a correct link so the 7-in-1 can be added?  I tried mailing you but didn't get a reply.

**Comment by daveshah1** [comment]
Great work! I look forward to playing with it in the new year. This should be a working 7 in 1 dump: 
[MiWi 2 Sports 7 in 1 (VT168).zip](https://github.com/mamedev/mame/files/3998600/MiWi.2.Sports.7.in.1.VT168.zip)

**Comment by DavidHaywood** [comment]
Thanks, got it added, seems to work as expected

**Comment by DavidHaywood** [comment]
some interesting revision differences even between the same game on different systems btw
https://twitter.com/MameHaze/status/1209499454446936065

**Pull request merged**
