### PR TITLE
capcom/vulgus.cpp: Add a 1942 bootleg from Itisa (not working)

### PR DESCRIPTION
**Pull request by clawgrip**
New not working clone
----------------------------
1942 (Itisa bootleg) [Recreativas.org]

### CODE REVIEW

**Comment by cuavas** [comment]
I haven’t had a chance to look at this, but it would be good if someone could take a look and see if the issues are something relatively simple.

@clawgrip indicated that it runs with bad graphics/colours and doesn’t start at the first level.

**Comment by clawgrip** [comment]
> @clawgrip indicated that it runs with bad graphics/colours and doesn’t start at the first level.

After moving it from 1942.cpp to vulgus.cpp and some help from @Osso13 we have good colors and slightly better graphics, but still not good (and still the wrong start level).

**Comment by Osso13** [comment]
Wrong start level I'm not sure, it seems to me 1942 starts with the same level.

**Comment by FoxhackDN** [comment]
> Wrong start level I'm not sure, it seems to me 1942 starts with the same level.

Yep, the first stage says "Last 32 stage", then when you clear that, it says "Last 31 stage". The numbers should be correct.

**Comment by clawgrip** [comment]
Yes, you're both right! Saw too many planes on screen, but was just the corrupted graphics :D

**Pull request merged**
