### PR TITLE
Enable flexible structure saving

### PR DESCRIPTION
**Pull request by aaronsgiles**
This change introduces the ability to save arbitrary structures. To make a structure eligible for saving, it must implement a new method `register_save(save_registrar &)`. Structs can then save their members directly via the provided save_registrar. Nested structs and arrays of structs are supported in this manner.

Note that state registration is not done via a virtual method or mix-in interface because doing so would convert lightweight structures away from being POD, and lightweight structures are one of the most common situations where this system can be leveraged in MAME.

As a first example, the `attotime` struct has been changed to support this mechanism for saving, allowing us to remove the special cases for attotimes currently in save_manager. The voodoo code has also been ported to use this in place of a temporary mechanism that had similar behavior.

(It might be tempting to do the same for `bitmap_t`, but bitmaps are defined in lib/util and can't take a dependency on save.h so those special cases will remain.)

This is a prologue to full hierarchical save state support, which I am working on in another branch. The `save_registrar` class name and `reg()` signatures match current work on that branch, so any changes made to existing code to leverage struct saving in this way will port over cleanly.

### CODE REVIEW

**Comment by cuavas** [comment]
This creates one save item per array element for each structure member.  That caused the Windows debugger to become completely unusable for the SPARC MMU that had large arrays of structures.  Making people wade through huge numbers of save items in the debugger when there are structures in arrays is a big step backwards for usability.  I think this is the wrong direction to go in, given it was already causing problems when it was done in an ad-hoc way.

**Comment by aaronsgiles** [comment]
You're right, it currently does create one save item per element. This is because of limitations in the current save system.

Long-term, when I finish working on proper hierarchical support, it won't need to. However, that's a bigger effort (and still has some rough edges that need to be sorted). That said, I see some benefits to introducing this mechanism now for complex systems like voodoo, and also for some scheduler work. Using this ensures a smooth transition for new code that might find it a good match to what they need.

I'm not expecting a short-term bulk switchover to this new mechanism. Even so, for the vast majority of situations, using this now is probably fine even within today's limitations. For the edge cases, we can stick to using STRUCT_MEMBER to work around the current way of doing things.

The fact that today we dump all save items into the debugger memory view is gross (but admittedly useful). Part of the hierarchical work is the introduction of a new debugger view with a full tree-style view of all save data, which is designed to scale to large arrays or deep structures.

**Comment by cuavas** [comment]
It’s still gross having the sheer number of registrations this is going to create.  Each one of them needs a string for its name as well as the pointer/size information.  That’s a lot of overhead, and it all adds up.  It has an impact on the Lua stuff that walks the save state registrations as well.  I really don’t like gratuitously multiplying overhead like this.

**Comment by aaronsgiles** [comment]
This PR on its own creates no additional save state items, since attotime was already getting split into two, and the voodoo code already was creating its state in this manner.

Your nightmare scenario is a really just a theoretical short-term problem only if a large number of devs suddenly get it in their heads to switch to this. Whereas I only anticipate limited (but helpful at least to me, possibly to others) use in the near-term.

I believe the *model* of allowing saveable structs is the right way to go long-term, if we remove the overhead of shoehorning it into the current system. Do you disagree with that?

**Comment by cuavas** [comment]
The `attotime` was being split in two, but no matter how many `attotime` you have in an array, you only had two registrations total, not two per element in the array.  If I’m reading [this code](https://github.com/mamedev/mame/pull/8576/files#diff-b5ffe59ae2eebd4e60c0c24fc48ab26023dc02ae2238c962ce9b75b617ab97ccR218) right, you want to change it to two items for each element in the array.

Saving structures is a useful thing to be able to do, but this approach is intrusive (requires the structure itself to have a member function aware of the registrar type) and inefficient (requires a save item for every member of every instance of a structure in an array).

**Comment by aaronsgiles** [comment]
You are correct that for the small number of cases where attotime is used in an array, it does create additional items. It's mostly not that bad except for pwm.cpp, which I agree is a problem when the debugger is loaded. I could probably make the array form do the same thing attotime does now, i.e., the equivalent of `STRUCT_MEMBER` to resolve that.

As for saving structs in general, assuming the second problem gets solved, I don't see a way around your first problem (requiring knowledge of the registrar type). Registering save state requires interacting with the save manager in some way. Introducing a type with that explicit purpose seems the most logical approach. Do you have a way to avoid doing that?

**Comment by cuavas** [comment]
You specialise some template for the structures you want to be able to save, and use a concept for a visitor to register members. The whole approach in the PR is inside-out.

**Comment by aaronsgiles** [comment]
So you're suggesting that the right way is to rely on template specialization and a bleeding-edge C++20 feature to support saving of structs, rather than putting together something that the average programmer will understand?

**Comment by aaronsgiles** [comment]
From a consumer POV, saving should be simple: `save.reg(NAME(foo))` regardless of what type `foo` is. Today that largely works except for classes/structs and dynamically-allocated pointers.

If a consumer defines a class and wants to save items within the class, in my proposed model all they have to do is make a `register_save()` method and populate it with `save.reg(NAME(bar))` items.

I will admit I can't even imagine how your template/concept approach would work, but I'm definitely wary of making the consumer write template magic just to enable saving structs.

**Comment by rb6502** [comment]
> I will admit I can't even imagine how your template/concept approach would work, but I'm definitely wary of making the consumer write template magic just to enable saving structs.

Vas and OG (and sometimes AJR) have been very good about writing core template magic where those of us out in writing-devices-and-drivers land don't have to do anything complicated but still get awesome benefits, so we'll see.

**Comment by aaronsgiles** [comment]
I would hope that's the case. However, since I've been working on supporting hierarchical saving, it would be highly useful to see even a pseudo-code example of how this idea is supposed to work, because the description provided makes no sense to me.

This is the second time I've gotten a "your approach is completely wrong" response against a PR without a clear explanation for how it might be done "correctly". Kind of unsure how to proceed from here.

**Comment by cuavas** [comment]
To be blunt, your ideas about how to “design” things are the reason that we’ve got the current mess of spaghetti dependencies that are taking literally years to untangle.

Seriously, look at the “API” between the stuff in src/emu and src/osd.  All the OSD modules end up sucking in all the emu.h stuff because they need to get a platform window from the OSD window, and due to the lack of anything that could be described as an actual interface, that needs to suck in all the render target stuff from src/emu.

Or the input stuff, where the input types are descriptors for host input types which come from the OSD layer, but they’re in src/emu, and then the OSD modules also need to pull in the actual input manager and input device classes from src/emu because there’s no actual interface and they need the concrete classes.

Or what about the JPEG support in rendutil.cpp that would just plain abort on bad data?  Yeah, complete denial-of-service against MAME if you just gave something that isn’t a JPEG a name ending in .jpg and referred to it from a layout.  Or the PNG support that didn’t support something like 60% of a conformance suite and didn’t properly check anything.  (Yes, I fixed that stuff myself already.)

I could go on forever – so much of MAME is a fractal of bad design and/or shoddy implementation.  I’ve just lost another entire night just trying to make progress on cleaning up bad APIs that are entrenched in the project.

For years you’ve acted like you don’t want anything to do with the project.  You’ve left the rest of us to shoulder a mountain of technical debt, and now you come back hell-bent on making things worse.  You’re causing me an enormous amount of stress right now.  I’d like to be able to actually do some emulation work at some point, not just fight fires.

If “the description provided makes no sense” to you, please stay well away from this stuff.  It’s all I can say.

**Comment by aaronsgiles** [comment]
LOL, ok, thanks for finally stating something with clarity. It all makes sense now that I understand you hold me personally responsible for all the bad design decisions in MAME. I'm glad you finally got that off your chest.

I'll be the first to point out the many flaws in MAME's design. But MAME wasn't designed from whole cloth; it slowly evolved from the DOS-only C-based multipac to the cross-platform C++ monstrosity it is today, and a lot of that transition was under my watch. When I was running things, MESS still existed as a separate entity, and I was in favor of keeping it that way. A non-trivial amount of the grossness in MAME comes from retrofitting a design that was arcade-focused onto one that requires enormous flexibility.

You and OG and others have done a lot of work to try and improve things, which is great, but just as you disagree with some of my approaches, I disagree with some of yours. I'll be 100% honest that a lot of your design patterns are obtuse and confusing, and you lean too hard on leveraging complex and cutting-edge C++ features, which discourages developers who aren't language nerds. We'll never see eye-to-eye on design, but you're the boss, so it's really up to you no matter how I feel.

However, it's unfortunately become clear that you have a hate hard-on for me that causes you endless stress. It also causes me stress because I know you'll rage all over any non-trivial changes I make, or at the very least I'll have to endure your (not-so-passive-)aggressive feedback (or even rage at me over an innocuous question I ask, say, in the Shoutbox). There's honestly just a lot of anger in general coming from your direction.

And so it's probably for the best that I just step back and stop contributing altogether. It's just not worth it.

**Comment by ajrhacker** [comment]
I somewhat agree with @cuavas. Two issues stand out:

1. Saving each item individually does seem like a massive regression from what STRUCT_MEMBER provides. The stipulation that this approach could lead to massive efficiency loss "only if a large number of devs suddenly get it in their heads to switch" does not bode well for a supposedly forward-looking refactoring.
2. Most device emulations are tightly coupled to `device_t`, and so require no proxy class to save their members. The idea behind this pull request seems to be to facilitate saving for classes abstracted away from `device_t`. However, the new `save_registrar` proxy still depends on `device_t` (as well as `save_manager`), so this is just shifting the dependency to a lower level.

**Comment by simzy39** [comment]
Now that Mame has switched to C++20, will this be revisited?

**Pull request closed without merging**
