### PR TITLE
New WORKING clone

### PR DESCRIPTION
**Pull request by clawgrip**
-----------------------
Sea Wolf (Tecfri) [Lorenzo, Victor Fernandez (City Game)]

### CODE REVIEW

**Comment by clawgrip** [comment]
@cuavas I need help with this one. Some months ago Victor located a collector (Lorenzo) with a rare Sauro prototype called "Sea Wolf". He's been trying to  convince him to dump it for months, and finally he has send a dump.

He forgot to dump the mask ROMs (sound program and speech) and the PLDs, but the game power on ROM test is failing, and he won't redump the PCB.

I think that this set is rare enough to have it preserved and added to MAME, but I need help to determine which ROMs are bad and which ones are "probably good". By now, I've marked as BAD just the missing sound and speech ROMs.

Thanks!

**Comment by clawgrip** [comment]
Video of the real PCB: https://www.youtube.com/watch?v=ViXJWnhSqwQ

**Comment by clawgrip** [comment]
Ah! And the PCB is Tecfri original, Lorenzo sent us pics of the back side of the PCB some months ago, when we first knew about this set.

d9c88c30-5fd1-4665-9ce0-06b640106d94
faab8e78-4065-4ae7-a73a-d6ad9f4cb31a

**Comment by Osso13** [comment]
FWIW, 1.bin is the ROM failing the ROM test.

The obvious differences in the sprite ROMs are to change the title from Sauro to Sea Wolf, but there are various other bytes changed here and there that cause differences like the one below (Sauro on the left, Sea Wolf on the right). 

sauro-seawolft-str20

So the GFX ROMs are probably a mix of legit changes and bad bytes.

**Comment by clawgrip** [comment]
> FWIW, 1.bin is the ROM failing the ROM test (Adding 0x01 to a byte in the 1.bin program ROM makes the ROM test pass, so it's possible there aren't a lot of problems in there).
> 
> The obvious differences in the sprite ROMs are to change the title from Sauro to Sea Wolf, but there are various other bytes changed here and there that cause differences like the one below (Sauro on the left, Sea Wolf on the right).
> 
> So the GFX ROMs are probably a mix of legit changes and bad bytes.

Thanks a lot. I've marked every ROM as BAD_DUMP, as we cannot trust the dump.

**Comment by clawgrip** [comment]
> 2.bin passes the ROM test, I wouldn't mark it as bad.

Changed, thx!

**Comment by cuavas** [comment]
Look, I’m starting to think that we’ve been too lenient in accepting bad dumps from repeat offenders, and it’s encouraging bad behaviour.  This *isn’t* preservation.  We know that these alternate versions exist, but they’re as good as lost anyway.  If we don’t take a hard line on it, we’re just going to have more people submitting incomplete and/or bad dumps to get their names in whastnew.

I think this should be rejected.  At the very least:
* Everything from the well-known repeat offenders should be marked bad unless there’s a good reason to believe otherwise.  If we don’t do this, we could be unwittingly propagating bad dumps.
* Incomplete dumps shouldn’t be added.  It just encourages more people to partially dump games, and then flip the board off as a “super-rare undumped version” before submitting it.
* Systems with bad/suspect dumps shouldn’t be marked working unless it’s 100% certain that the dump errors don’t interfere with gameplay.

**Comment by clawgrip** [comment]
While I agree that we need to enforce good dumps somehow, this is the first (and probably last) dump from Lorenzo. Víctor didn't dump it, he only called the guy for weeks until he agreed to dump it by himself (I offered paying the shipping cost so I can dump it, but he refused). So it's not the case of a "well-known repeat offenders".
I'm currently holding back other dumps from Victor because I'm waiting for redumps or verification on the real PCB, but this isn's the case. It's a dump from Lorenzo.

> Systems with bad/suspect dumps shouldn’t be marked working unless it’s 100% certain that the dump errors don’t interfere with gameplay

That's true.

**Comment by clawgrip** [comment]
@cuavas , please, hold this PR just a little longer (I've marked it as a draft). Victor called the guy, and he (Lorenzo) has cleaned the pins and then double-dumped each ROM. He also has dumped the sound ROM (but not the speech one). Please, let me check this new dump.

This was unexpected, as he said he already had the PCB packed for selling it and had no intention to redump it (that's why I opened the PR without waiting for a redump).

Thanks.

**Comment by DavidHaywood** [comment]
The sp0256 ROM is an internal ROM to the speech IC anyway, if it's marked AL2 it will be the standard AL2 ROM.

While some of the sp0256 ROMs were single application, I do wonder if maybe we should be treating them as device ROMs based on the part number.

Otherwise what Vas said really, there's absolutely no excuse for the shocking quality of some of the dumps that been being submitted.  These are mistakes that would have been poor form at the end of the 90s, by 2021 decent tools are so readily available, and the process so well documented, it's inexcusable.

**Comment by clawgrip** [comment]
On this new dump, constant reads on first and second dump for each ROM, but only ROM 1.bin with different bits from the previous submission (now ROM test is OK), plus the sound ROM now dumped and matching the parent set.

He sends the dumps as Intel HEX, and this is good, as that way I know he's not simply using ROMs from other sets to force its inclusion. Also, the dates of each file enforces the idea that Lorenzo really redumped the board (forgot about the idea of him faking the dump with bin2hex and touch).

Sorry for all the unwanted noise (this redump was really unexpected, otherwise I'd had waited for it).

From now on, I'll tell untrusted sources to send the dumps to the public MAME emails. I'm really tired of all this.
I always triple-check my dumps, I always clean the pins, I even use different programmers for dumping the same ROM when I have doubts. 
I've submitted hundreds of dumps for more than ten years, and just two or three ended being bad.

Thanks again. Regards: ClawGrip

image

**Comment by Tafoid** [comment]
This looks good now and runs fine as far as I can tell using artifact build with newest dumps.  Dips and Inputs all react as expected in service mode and in game where tested.

**Pull request merged**
