### PR TITLE
Modernize x86log.h and x86log.cpp

### PR DESCRIPTION
**Pull request by SuperV1234**
* Use variadic template functions instead of `va_list`
    * In `x86log_mark_as_data` and `x86log_printf`
* Add `noexcept` where appropriate/safe
* Use `constexpr std::size_t` instead of macros for constants
* Nest `nullptr` check to prevent useless check, add assertion
    * In `x86log_printf`

*(Hope variadic templates are OK!)*

### CODE REVIEW

**Comment by mmicko** [comment]
ups, it does not compile

**Comment by SuperV1234** [comment]
Any compilation log? It compiles fine here.

**Comment by mmicko** [comment]
In file included from ../../../../../src/devices/cpu/drcbex86.h:18:0,
                 from ../../../../../src/devices/cpu/drcuml.cpp:40:
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_add_comment(x86log_context*, x86code*, const char*, Ts&& ...)':
../../../../../src/devices/cpu/x86log.h:60:20: error: invalid use of
incomplete type 'struct x86log_context'
  char *string = log->comment_pool_next;
                    ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
In file included from ../../../../../src/devices/cpu/x86log.cpp:13:0:
../../../../../src/devices/cpu/x86log.h:61:2: error: 'log_comment' was not
declared in this scope
  log_comment *comment;
  ^
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_add_comment(x86log_context*, x86code*, const char*, Ts&& ...)':
../../../../../src/devices/cpu/x86log.h:61:15: error: 'comment' was not
declared in this scope
../../../../../src/devices/cpu/x86log.h:60:20: error: invalid use of
incomplete type 'struct x86log_context'
  log_comment *comment;
               ^
  char *string = log->comment_pool_next;
                    ^
../../../../../src/devices/cpu/x86log.h:70:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_count >= MAX_COMMENTS)
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:70:28: error: 'MAX_COMMENTS' was
not declared in this scope
  if (log->comment_count >= MAX_COMMENTS)
                            ^
../../../../../src/devices/cpu/x86log.h:72:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:72:58: error: invalid use of
incomplete type 'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
 struct x86log_context;
                                                          ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
        ^
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:72:75: error: 'COMMENT_POOL_SIZE'
was not declared in this scope
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
                                                                           ^
../../../../../src/devices/cpu/x86log.h:76:5: error: invalid use of
incomplete type 'struct x86log_context'
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
     ^
../../../../../src/devices/cpu/x86log.h:61:2: error: 'log_comment' was not
declared in this scope
  log_comment *comment;
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:76:39: error: invalid use of
incomplete type 'struct x86log_context'
  ^
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
                                       ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:61:15: error: 'comment' was not
declared in this scope
../../../../../src/devices/cpu/x86log.h:79:16: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];
                ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
  log_comment *comment;
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:79:34: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];
                                  ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
               ^
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_printf(x86log_context*, const char*, Ts&& ...)':
../../../../../src/devices/cpu/x86log.h:94:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->file == nullptr)
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:96:6: error: invalid use of
incomplete type 'struct x86log_context'
   log->file = fopen(log->filename.c_str(), "w");
      ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:96:24: error: invalid use of
incomplete type 'struct x86log_context'
   log->file = fopen(log->filename.c_str(), "w");
                        ^
../../../../../src/devices/cpu/x86log.h:70:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_count >= MAX_COMMENTS)
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:98:10: error: invalid use of
incomplete type 'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
   if (log->file == nullptr)
 struct x86log_context;
          ^
        ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:70:28: error: 'MAX_COMMENTS' was
not declared in this scope
../../../../../src/devices/cpu/x86log.h:105:13: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_count >= MAX_COMMENTS)
  fprintf(log->file, format, std::forward<Ts>(xs)...);
             ^♪◙../../../../../src/devices/cpu/x86log.h:23:8: note: forward
declaration of 'struct x86log_context'
 struct x86log_context;
        ^
                            ^
../../../../../src/devices/cpu/x86log.h:108:12: error: invalid use of
incomplete type 'struct x86log_context'
  fflush(log->file);
            ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
../../../../../src/devices/cpu/x86log.h:72:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
        ^
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:72:58: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
                                                          ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:72:75: error: 'COMMENT_POOL_SIZE'
was not declared in this scope
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
                                                                           ^
../../../../../src/devices/cpu/x86log.h:76:5: error: invalid use of
incomplete type 'struct x86log_context'
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
     ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:76:39: error: invalid use of
incomplete type 'struct x86log_context'
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
                                       ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:79:16: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];
                ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:79:34: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];
                                  ^
In file included from ../../../../../src/devices/cpu/drcbex86.h:18:0,
                 from ../../../../../src/devices/cpu/drcbex86.cpp:89:
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_add_comment(x86log_context*, x86code*, const char*, Ts&& ...)':
 struct x86log_context;
../../../../../src/devices/cpu/x86log.h:60:20: error: invalid use of
incomplete type 'struct x86log_context'
        ^
  char *string = log->comment_pool_next;
                    ^
In file included from ../../../../../src/devices/cpu/drcbex64.h:18:0,
                 from ../../../../../src/devices/cpu/drcbex64.cpp:173:
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_add_comment(x86log_context*, x86code*, const char*, Ts&& ...)':
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_printf(x86log_context*, const char*, Ts&& ...)':
../../../../../src/devices/cpu/x86log.h:60:20: error: invalid use of
incomplete type 'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:94:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->file == nullptr)
 struct x86log_context;
  char *string = log->comment_pool_next;
         ^
        ^
                    ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:61:2: error: 'log_comment' was not
declared in this scope
 struct x86log_context;
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:61:2: error: 'log_comment' was not
declared in this scope
  log_comment *comment;
  ^
../../../../../src/devices/cpu/x86log.h:61:15: error: 'comment' was not
declared in this scope
  log_comment *comment;
        ^
  log_comment *comment;
               ^
../../../../../src/devices/cpu/x86log.h:70:9: error: invalid use of
incomplete type 'struct x86log_context'
  ^
  if (log->comment_count >= MAX_COMMENTS)
../../../../../src/devices/cpu/x86log.h:96:6: error: invalid use of
incomplete type 'struct x86log_context'
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:70:28: error: 'MAX_COMMENTS' was
not declared in this scope
  if (log->comment_count >= MAX_COMMENTS)
                            ^
../../../../../src/devices/cpu/x86log.h:61:15: error: 'comment' was not
declared in this scope
   log->file = fopen(log->filename.c_str(), "w");
../../../../../src/devices/cpu/x86log.h:72:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
         ^
      ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
  log_comment *comment;
 struct x86log_context;
               ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
        ^
../../../../../src/devices/cpu/x86log.h:72:58: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
                                                          ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:72:75: error: 'COMMENT_POOL_SIZE'
was not declared in this scope
../../../../../src/devices/cpu/x86log.h:70:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
                                                                           ^
../../../../../src/devices/cpu/x86log.h:76:5: error: invalid use of
incomplete type 'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:96:24: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->comment_count >= MAX_COMMENTS)
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
     ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
   log->file = fopen(log->filename.c_str(), "w");
         ^
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:76:39: error: invalid use of
incomplete type 'struct x86log_context'
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
                        ^
                                       ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
 struct x86log_context;
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
        ^
        ^
../../../../../src/devices/cpu/x86log.h:79:16: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];
                ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:79:34: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];

^♪◙../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration
of 'struct x86log_context'
 struct x86log_context;
        ^
 struct x86log_context;
../../../../../src/devices/cpu/x86log.h:70:28: error: 'MAX_COMMENTS' was
not declared in this scope
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_printf(x86log_context*, const char*, Ts&& ...)':
../../../../../src/devices/cpu/x86log.h:94:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->file == nullptr)
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:96:6: error: invalid use of
incomplete type 'struct x86log_context'
        ^
  if (log->comment_count >= MAX_COMMENTS)
   log->file = fopen(log->filename.c_str(), "w");
      ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
                            ^
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:96:24: error: invalid use of
incomplete type 'struct x86log_context'
   log->file = fopen(log->filename.c_str(), "w");
../../../../../src/devices/cpu/x86log.h:98:10: error: invalid use of
incomplete type 'struct x86log_context'
                        ^
   if (log->file == nullptr)♪◙../../../../../src/devices/cpu/x86log.h:72:9:
error: invalid use of incomplete type 'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
          ^
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
        ^
../../../../../src/devices/cpu/x86log.h:98:10: error: invalid use of
incomplete type 'struct x86log_context'
   if (log->file == nullptr)
          ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
         ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:105:13: error: invalid use of
incomplete type 'struct x86log_context'
 struct x86log_context;
  fprintf(log->file, format, std::forward<Ts>(xs)...);
             ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
 struct x86log_context;
../../../../../src/devices/cpu/x86log.h:108:12: error: invalid use of
incomplete type 'struct x86log_context'
        ^
        ^
  fflush(log->file);
            ^
../../../../../src/devices/cpu/x86log.h:105:13: error: invalid use of
incomplete type 'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:72:58: error: invalid use of
incomplete type 'struct x86log_context'
  fprintf(log->file, format, std::forward<Ts>(xs)...);
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
             ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
                                                          ^
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
        ^
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:108:12: error: invalid use of
incomplete type 'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:72:75: error: 'COMMENT_POOL_SIZE'
was not declared in this scope
  fflush(log->file);
  if (log->comment_pool_next + strlen(format) + 256 >= log->comment_pool +
COMMENT_POOL_SIZE)
            ^
                                                                           ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
../../../../../src/devices/cpu/x86log.h:76:5: error: invalid use of
incomplete type 'struct x86log_context'
 struct x86log_context;
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
        ^
     ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:76:39: error: invalid use of
incomplete type 'struct x86log_context'
  log->comment_pool_next += sprintf(log->comment_pool_next, format,
std::forward<Ts>(xs)...) + 1;
                                       ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
optional.make:4611: recipe for target
'../../../../mingw-gcc/obj/x64/Release/src/devices/cpu/drcuml.o' failed
 struct x86log_context;
        ^
make[2]: ***
[../../../../mingw-gcc/obj/x64/Release/src/devices/cpu/drcuml.o] Error 1
../../../../../src/devices/cpu/x86log.h:79:16: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];
                ^
make[2]: *** Waiting for unfinished jobs....
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:79:34: error: invalid use of
incomplete type 'struct x86log_context'
  comment = &log->comment_list[log->comment_count++];
                                  ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
optional.make:4623: recipe for target
'../../../../mingw-gcc/obj/x64/Release/src/devices/cpu/x86log.o' failed
../../../../../src/devices/cpu/x86log.h: In function 'void
x86log_printf(x86log_context*, const char*, Ts&& ...)':
../../../../../src/devices/cpu/x86log.h:94:9: error: invalid use of
incomplete type 'struct x86log_context'
  if (log->file == nullptr)
make[2]: ***
[../../../../mingw-gcc/obj/x64/Release/src/devices/cpu/x86log.o] Error 1♪◙
        ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:96:6: error: invalid use of
incomplete type 'struct x86log_context'
   log->file = fopen(log->filename.c_str(), "w");
      ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:96:24: error: invalid use of
incomplete type 'struct x86log_context'
   log->file = fopen(log->filename.c_str(), "w");
                        ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:98:10: error: invalid use of
incomplete type 'struct x86log_context'
   if (log->file == nullptr)
          ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:105:13: error: invalid use of
incomplete type 'struct x86log_context'
  fprintf(log->file, format, std::forward<Ts>(xs)...);
             ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^
../../../../../src/devices/cpu/x86log.h:108:12: error: invalid use of
incomplete type 'struct x86log_context'
  fflush(log->file);
            ^
../../../../../src/devices/cpu/x86log.h:23:8: note: forward declaration of
'struct x86log_context'
 struct x86log_context;
        ^



After I placed x86log_context from cpp to h I get :

Compiling src/devices/cpu/drcbex86.cpp...
In file included from ../../../../../src/devices/cpu/drcbex64.h:18:0,
                 from ../../../../../src/devices/cpu/drcbex64.cpp:173:
../../../../../src/devices/cpu/x86log.h: In instantiation of 'void
x86log_printf(x86log_context*, const char*, Ts&& ...) [with Ts = {}]':
../../../../../src/devices/cpu/drcbex64.cpp:683:71:   required from here
../../../../../src/devices/cpu/x86log.h:144:9: error: format not a string
literal and no format arguments [-Werror=format-security]
  fprintf(log->file, format, std::forward<Ts>(xs)...);
         ^
In file included from ../../../../../src/devices/cpu/drcbex86.h:18:0,
                 from ../../../../../src/devices/cpu/drcbex86.cpp:89:
../../../../../src/devices/cpu/x86log.h: In instantiation of 'void
x86log_printf(x86log_context*, const char*, Ts&& ...) [with Ts = {}]':
../../../../../src/devices/cpu/drcbex86.cpp:597:71:   required from here
../../../../../src/devices/cpu/x86log.h:144:9: error: format not a string
literal and no format arguments [-Werror=format-security]
  fprintf(log->file, format, std::forward<Ts>(xs)...);
         ^
cc1plus.exe: all warnings being treated as errors

This is all on Mingw GCC 5.2

**Comment by SuperV1234** [comment]
I see. Would it be acceptable to move the `struct` definitions of `log_comment`, `data_range_t`, `x86log_context` to the `x86_log.h` header file from the `x86_log.cpp` source file?

**Comment by mmicko** [comment]
yes I did that (complete const and types section) but then got that other
error

Compiling src/devices/cpu/drcbex86.cpp...
In file included from ../../../../../src/devices/cpu/drcbex64.h:18:0,
                 from ../../../../../src/devices/cpu/drcbex64.cpp:173:
../../../../../src/devices/cpu/x86log.h: In instantiation of 'void
x86log_printf(x86log_context*, const char*, Ts&& ...) [with Ts = {}]':
../../../../../src/devices/cpu/drcbex64.cpp:683:71:   required from here
../../../../../src/devices/cpu/x86log.h:144:9: error: format not a string
literal and no format arguments [-Werror=format-security]
  fprintf(log->file, format, std::forward<Ts>(xs)...);
         ^
In file included from ../../../../../src/devices/cpu/drcbex86.h:18:0,
                 from ../../../../../src/devices/cpu/drcbex86.cpp:89:
../../../../../src/devices/cpu/x86log.h: In instantiation of 'void
x86log_printf(x86log_context*, const char*, Ts&& ...) [with Ts = {}]':
../../../../../src/devices/cpu/drcbex86.cpp:597:71:   required from here
../../../../../src/devices/cpu/x86log.h:144:9: error: format not a string
literal and no format arguments [-Werror=format-security]
  fprintf(log->file, format, std::forward<Ts>(xs)...);
         ^
cc1plus.exe: all warnings being treated as errors

**Comment by mmicko** [comment]
please note we try to be compatible with clang 3.4 and up, gcc 4.9 and up,
and vs2013 and up

**Comment by SuperV1234** [comment]
You're right - I was compiling with `SUBTARGET=tiny`. [This commit](https://github.com/SuperV1234/mame/commit/ed48c2cabbe1cbc12a8c3c57c77a75f33d499633) fixes the compilation errors on my machine.

Also, continuous integration would greatly help - is there any plan of using it?

**Comment by mmicko** [comment]
We used TravisCI but that one just can't cope with our code, it requires
too much time to compile on those VM's.

Please use SUBTARGET=dummy while testing , it will at least compile all
devices and that covers lot usage cases. But making full build is always
only way to know all compiles.

**Comment by mmicko** [comment]
If you could please rebase and create new pull request, I would do manual
merge from my side and check if all compiles.

Please note that I have revert original changes on main trunk.

**Pull request merged**
