### PR TITLE
nmk16.cpp : Fix tdragon2 bankswitching

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by cuavas** [comment]
How can the problem be reproduced to show that the fix works?

**Comment by cam900** [comment]
Both tdragon2, macross2 has not used hi bits of scroll registers(these games are using pair of 8-bit wide registers)
ex:It's fixes stage 1 boss bg of tdragon2.

Before : When this scene, Highest nibble of scroll register is 0x1; it's wrong.

**Comment by DavidHaywood** [comment]
when was this problem introduced?

the nmk16 scrolling was very carefully checked before, the high bits are indeed a ram bank select, not scroll registers which had been carefully implemented against both thunder dragon 2 and rapid hero and verified against hardware.  this is why the driver was using 4 tilemaps, as marking entire tilemaps as dirty caused stuttering in performance so it was easier to track the ram banks as 4 tilemaps and enable the one for the current bank.

a lot of the recent changes are worrying me, things like this shouldn't be breaking in the first place.

**Comment by DavidHaywood** [comment]
furthermore the PCB videos on Youtube all show the blue background you claim is wrong
https://www.youtube.com/watch?v=hDCaeOP93WM

**Comment by cam900** [comment]
Blue one is correct; it just fixes old copy-n-paste error. (at tilemap_bank_select = (xscroll&0x3000)>>12;)

**Pull request merged**
