### PR TITLE
namco_c355spr.cpp : Fix drawing regression

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
what had regressed? does this need to go into the release?

**Comment by cam900** [comment]
> what had regressed? does this need to go into the release?

Color offset is different in namcos21_*.cpp drivers with c355 sprite.
ex:black sprites in solvalou

**Comment by cuavas** [comment]
Does this fix the regressions reported on #6392?  [This comment](https://github.com/mamedev/mame/pull/6392#issuecomment-595498564) specifically.

**Comment by Robbbert** [comment]
All looks good to me.

**Pull request merged**
