### PR TITLE
Add CEC-E CEC-G CEC-M CEC-2000

### PR DESCRIPTION
**Pull request by zzemu-cn**
CEC-E CEC-G CEC-M CEC-2000
qq 145409056

### CODE REVIEW

**Comment by rb6502** [comment]
Would it be possible to get the necessary ROMs to us?  The changes look good but I can't verify them.

**Comment by zzemu-cn** [comment]
Please sed me your email address.

url : https://pan.baidu.com/s/1ZojjEdAkI_WRIVU57LwT4w 
pasword：tlj0

**Comment by zzemu-cn** [comment]
I come from China.
These models are emerging in China in the 1980s.
This code has been tested for a while.
My email address is 535689143@qq.com

**Comment by zzemu-cn** [comment]
I can send the rom to you by email address.

**Pull request merged**
