### PR TITLE
Sega Pico PCM support, fix for FM-Towns clock, minor fixes

### PR DESCRIPTION
**Pull request by ValleyBell**
While working on my VGM logging mod for MAME, I did a few bug fixes.

* I added a FIFO to the uPD7759 in order to properly support Sega Pico PCM.
The additions shouldn't break anything. I tested them against only a few Sega System 16B games though.
* There is a small fix for the FM-Towns clock posted by the people on the vgmrips forum. (The original code used the Sega MegaCD clocks.)
* The interrupts for Xor World are pure guesswork, but it makes the game run at a playable speed (instead of insanely fast) and the music/sfx aren't way too slow anymore.
* I added a few checks to prevent MAME's main menu from overwriting wavelog + error.log.

### CODE REVIEW

**Comment by aaronsgiles** [comment]
Upd7759 doesn't have a fifo, so adding one is a hack that should be kept driver local. Ideally you should find a way to make it work workout a fifo.

Aaron

Sent from my Windows Phone
________________________________

**Comment by Lord-Nightmare** [comment]
You sure it doesn't have a fifo? The decap shows it has a lot of crap on die one of which could be a fifo of some sort...
http://siliconpr0n.org/map/nec/d7759c/mz_mit20x/
...although i was under the impression that the two dark areas were roms of some sort?

**Comment by aaronsgiles** [comment]
I studied this chip extensively when I rewrote it. It is explicitly documented that it has one byte input latch and you have to feed it carefully. Timing is everything and you have to get it just right.


I'm vague on the details (it's been a good 10 years, I'm guessing), but I will NAK any attempt to add FIFOs on top of it without demonstrable proof that the documentation was all wrong.


Aaron


________________________________

**Comment by balr0g** [comment]
@aaronsgiles: https://github.com/mamedev/mame/blob/master/src/emu/sound/upd7759.c#L103 -- are you sure? I'm not sure who wrote this because this is pre-SVN, but it seems to imply that slave mode involves FIFOs. If this is not correct, it should be removed from the source file, as it misleads contributors into doing things incorrectly.

**Comment by aaronsgiles** [comment]
Heh, I must have never removed those comments when I rewrote it. Much of that "information" is bogus and misleading.


Aaron

________________________________

**Comment by Cowering** [comment]
PCM sound in the PICO is 'custom'. Steve Snake told me so many years ago 
when he added PICO to Fusion.  IIRC from our talks, the PCM is tested 
best by playing title and startup music for the Mickey Mouse game. 
Mickey sound used to be horrid in MESS, but Steve finally got it right 
in Fusion. He would never tell me the 'fix'. I think he ended up selling 
Fusion core to someone else to be used in a commercial emulator and it 
went under NDA.

Cow

**Comment by rb6502** [comment]
Ok.  Given what Cowering said, then the PICO PCM should be a separate device type, possibly deriving from the 7759.  And then everyone's happy.

**Comment by ValleyBell** [comment]
My [current implementation] (http://vgm.mdscene.net/programs/creators/MAME0164_bin64_2015-08-14.7z) works pretty well with Mickey no Boku wa Meitantei and Sonic's Gameworld (J).

I can split the changes to the uPD7759 and put them into a separate device/file. Or I could integrate them into segapico.c, that's what I originally did. (before I read the comment about the FIFO in the 7759 driver)
You really should remove those misleading comments ASAP to avoid future confusion.

**Comment by Cowering** [comment]
On 8/21/2015 3:51 PM, ValleyBell wrote:
>
> My current implementation 
> <http://vgm.mdscene.net/programs/creators/MAME0164_bin64_2015-08-14.7z> works 
> pretty well with Mickey no Boku wa Meitantei and Sonic's Gameworld (J).
>
> I can split the changes to the uPD7759 and put them into a separate 
> device/file. Or I could integrate them into segapico.c, that's what I 
> originally did. (before I read the comment about the FIFO in the 7759 
> driver)
> You really should remove those misleading comments ASAP to avoid 
> future confusion.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mamedev/mame/pull/288#issuecomment-133560932>.
>

Why is it segapico.c and not just pico.c ?

I guess Mickey no... is same as Mickey's Blast Into the Past (U), as 
that is the one I was talking about.

Cow

**Comment by mamehaze** [comment]
is this going to be improved (new device or derived device for the Pico sound?)

should it be closed?

**Comment by mamehaze** [comment]
I've refactored your SegaPico changes here
https://github.com/mamedev/mame/commit/8abb4014f330944ef2d18f6eaba4b9ce677da75f

please create new pull requests for anything else you want including as there were multiple other changes included in this single request.

**Pull request closed without merging**
