### PR TITLE
Update Contributing.md

### PR DESCRIPTION
**Pull request by gbuntin**
This document is automatically linked to when creating a pull request (contributing guidelines and Contributing link under Helpful resources).  Since it is currently blank, lets link to the guidelines on Mamedev.org

### CODE REVIEW

**Comment by cuavas** [comment]
We have a minimal set of contribution guidelines in README.md which may overlap with the stuff that people would expect to find in this file.  @Firehawke as our docs guy, do you have any thoughts on this?

**Comment by Firehawke** [comment]
Sorry for delay in seeing this.

Let me see...
It probably wouldn't hurt to have all of it in one document and link it from all applicable locations. The question then becomes "Which document and where?"
My thought is it would have to be either the wiki or in the mainline docs itself. The wiki needs to be linked from the documentation where applicable as well, but I believe we'd established previously that the separation line was "usage of drivers from the user perspective" (e.g. how to install an OS, etc) VS the technical/user manual. With that split, I'd say we should put it into the docs itself and then link it from the **readme** (unless it's just easier on everyone to not have to click a link and just mirror that chunk in the **readme.md** file)  and from the **contributing.md** file too.

I need to see if there's a way to get the docs to generate that part of the *readme.md* file automagically as that would simplify things quite a bit.

Give me a day or two to look into things and I'll see what I can do. In the meantime, thanks for the report @gbuntin; we appreciate reports of areas where things are lacking.

**Comment by Firehawke** [comment]
Adding a quick note that I've been almost completely offline for over a week. It's over 100 degrees Fahrenheit at the moment and I've been dealing with a air conditioner failure at the same time as a busted water pipe, damaged floor (from the pipe), and something broken in the electrical system that I won't be able to get traced until Friday at the earliest.

It's been a horrible few days. Going to make a note to check back in on this when feasible.

Sincere apologies for not being able to stay on this.

**Comment by gbuntin** [comment]
It is OK!  Take care of YOU & YOURS first, that is what is truly important.  It isn't like this is a critical thing and the world will end if it doesn't get done.

**Comment by cuavas** [comment]
We’ve belatedly added the beginnings of a guide for contributors to our documentation: https://docs.mamedev.org/contributing/

The CONTRIBUTING.md file has been updated with a link.  Thanks for prompting the discussion, @gbuntin.

**Pull request closed without merging**
