### PR TITLE
[snes] Revert last changes (nw)

### PR DESCRIPTION
**Pull request by AmatCoder**
It has been reported that they caused breakage

### CODE REVIEW

**Comment by MooglyGuy** [comment]
A specific part of a specific change was reported to cause breakage. It is childish in the extreme to revert out far more than that specific part just because someone criticizes your code.

**Comment by AmatCoder** [comment]
I do not want to be insulted or ridiculed by mamedevs, now or in the future for contributing.
So I want to reverse my changes and not be associated with this project anymore.

I did it in good faith and now I appeal to your reciprocity for reconsideration on my request.

**Comment by happppp** [comment]
I get it, you were offended by moogly's insult on the bannister.org website. It's between you and him, not you and the MAME project as a whole. I'm sorry but we won't grant your request to do a full revert of all your (open-source licensed!) contributions to the MAME project. I hope you've calmed down by today and decide not to battle further.

I believe MooglyGuy is currently writing a fix for the SNES PPU crash (caused by mid-screen horizontal resolution changes).

**Comment by AmatCoder** [comment]
I'm sorry but I must insist on this.

I don't want to have any connection with projects that shelter people like moogly, even if he doesn't represent to the project as a whole (obviously it is not the case).

I just demand that _git blame_ does not point to me.

My contributions are and will always be open-source. Someone can to review and re-apply them (or modify them or just reject them) in such a way that he assumes responsibility for that code.

I believe that it would be just a sign of respect for contributors who no longer want to be associated with this project.

If this is not done, my only option would be to delete this account on GitHub and I don't want do that.

I hope that my request will be considered so that we can all follow our own path in the shortest possible time.

**Comment by cuavas** [comment]
Contributions to open source projects cannot be provided under a revocable license.  There would be chaos if developers could re-license or revoke the license under which their contributions were provided on a whim.  The contributions are understood to be provided under the license noted at the top of the source file.

@MooglyGuy has no authority to speak for the team as a whole.  Any positions he expresses are his own.  As for your comment about "sheltering" people like him, it's true that MAME does provide an environment where a broad range of people can contribute.  We aim to judge contributions on their own merit, not any personal issues we may have with the contributor.  @MooglyGuy has made a number of fairly significant contributions to the project over the years.

Your name will not be scrubbed from the repository.  Reverting the change won't remove your name from the revision history, and it will make your name appear on the reverted lines in `git blame` output.  It doesn't achieve anything.

**Pull request closed without merging**
