### PR TITLE
gp9001.cpp : Implement sprite limit per frame/sprite size, Add notes

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by happppp** [comment]
Sprite cycle timing taken out of a magician's hat or do you have a logical explanation?
Is the previous 256 sprite limit hack not sufficient?

**Comment by cam900** [comment]
Sprite RAM size is 2048 bytes (mirrored), and Each sprite uses 8 bytes. It's total sprite is 256.
Also, Sprites are limited related to both screen size and sprite size.

**Comment by happppp** [comment]
@rb6502 you're not merging this one? I still don't agree with this hacky implementation, but it is less bad than the similar https://github.com/mamedev/mame/pull/6341 which you merged rightaway.

**Comment by rb6502** [comment]
I generally don't merge stuff when there's an active discussion.  At the same time, I think both changes are reasonable at a high level aside from not knowing the actual cycle counts involved, because clearly these chips do have some sort of limit.

**Comment by happppp** [comment]
@cam900 it sounds like 8 cycles per byte blit is too much:
https://mametesters.org/view.php?id=7642

**Pull request merged**
