### PR TITLE
megadriv.xml: Added an unreleased prototype.

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions
-----------------------------------
Super Spin (prototype) [GamingLegend64, Forest of Illusion]

### CODE REVIEW

**Comment by ICEknigh7** [comment]
Should the .bin file be split since the board shows two EPROMS, or would that technically be considered a "bad dump"?
super-spin-preview-version-cart-front

**Comment by 0kmg** [comment]
The EPROMs on this board were dumped separately but were merged for public release. I'm not really sure how things should be split to undo this. Are Mega Drive ROMs always interleaved or is this board specific?

**Comment by ICEknigh7** [comment]
Most commercial Mega Drive games are contained within just one ROM, but some of the bigger ones are indeed interleaved across two.

**Comment by DavidHaywood** [comment]
yeah, it's definitely an interleave split based on that, although we don't know the endian, so you could get them the wrong way around anyway.  If the dumpers are still withholding the proper information in 2022 I'm not sure what can be done, it's kinda ridiculous.  Name them U1 and U2 and hope you get them the right way around.

**Comment by cuavas** [comment]
That’s an interleaved setup with the least significant bytes (odd addresses as it’s big-Endian) in U1 and the most significant bytes in U2.  No need to guess.

**Pull request merged**
