### PR TITLE
megaphx.cpp: Add PCBs ASCII layouts and corrected placeholders for PLDs on YoYo Spell

### PR DESCRIPTION
**Pull request by clawgrip**
Also added some notes

### CODE REVIEW

**Comment by happppp** [comment]
Can you doublecheck it has that 15MHz XTAL? Since the driver itself says 16MHz. Maybe for this game, the CPU is 7.5MHz then.

**Comment by clawgrip** [comment]
I won't have access to the PCB until next saturday, all I have now is this pic.

May be 16, can you read it well?

yoyo2 jpg

**Comment by cuavas** [comment]
> May be 16, can you read it well?

Comparing it to the 5 on the bottom line of text on the crystal can, it’s probably supposed to be a 6, and hence “16000KHZ” on the top line.

**Comment by clawgrip** [comment]
I’ll submit a new PR with the fix this Saturday, after checking it on the real PCB

Thanks a lot!!!!

**Pull request merged**
