### PR TITLE
Further improvements to the Patinho Feio driver & CPU

### PR DESCRIPTION
**Pull request by felipesanches**
I ha just addressed the issue pointed out at https://github.com/mamedev/mame/pull/893#issuecomment-221530130

### CODE REVIEW

**Comment by cuavas** [comment]
This pull request is still missing src/devices/cpu/patinhofeio/patinhofeio_cpu.h

**Comment by felipesanches** [comment]
I just added it and ammended the commit.

**Comment by cuavas** [comment]
OK I'll merge it now.

Note that you'll still have to replace UTF-8 with escapes at some point for the input names to survive the srcclean before the next release, e.g. "PREPARAÇÃO" -> "PREPARA\xc3\x87\xc3\x83O"

**Comment by felipesanches** [comment]
thanks! I'll do it.

Even though I think the srcclean approach is somewhat problematic, I'll do it as is the current way of doing it and then we can discuss better ways for the future releases (just like we've already talked about at https://github.com/mamedev/mame/issues/586).

**Pull request merged**
