### PR TITLE
Continuous integration improvements

### PR DESCRIPTION
**Pull request by belegdol**
As the only remaining build failures only affect debug build of tools, tweak the configuration so that the build can actually complete:
* disable tools build
* switch to release build while disabling optimization
* no longer allow msvc build to fail

### CODE REVIEW

**Comment by cuavas** [comment]
The trouble is it's a lot less useful if tools are disabled - for example the disassemblers won't all be built.

**Comment by belegdol** [comment]
I only disabled tools build because these are not enabled on travis (they never seem to have been) and on appveyor/MINGW (because build with tools enabled takes longer than 60 minutes).
In theory having a release build should be enough not to hit the ICEs, I will update the PR accordingly.
Would you say it makes sense to enable tools for travis builds as well?

**Comment by cuavas** [comment]
Well, a build build with tools enabled at least catches a number of common errors when refactoring CPU cores, while a tiny build without tools doesn't catch much at all for things affecting devices/drivers.

**Comment by belegdol** [comment]
Fair enough, I have now enabled tools for travis and appveyor MSVC. @startaq would need to request a build timeout extension with appveyor if we were to enable tools for MINGW too.

**Comment by belegdol** [comment]
oh, nltool failed to link on mac (travis). @couriersud, would you mind having a look?
In general, is it normal that we are using clang-3.6 on mac? It dates back to 2017.

**Comment by couriersud** [comment]
I am using 
`make SUBTARGET=nl -j 4 TOOLS=1 DEBUG=1`
and have no problem compiling. 
clang version is 10.0.1
3.6 seems to be pretty outdated.

**Comment by couriersud** [comment]
Non-debug build works as well with clang 10.0.1.

**Comment by belegdol** [comment]
@couriersud, thanks for the info. The mac build on travis is actually using Apple LLVM version 9.1.0 (clang-902.0.39.2), not 3.6, sorry for the confusion.
I managed to get ssh access to travis, this should hopefully result in a working tools build.

**Comment by cuavas** [comment]
Yeah, but Apple's numbering is completely whack - they change clang/llvm version numbers to vanity numbers that are much larger.  That's equivalent to clang 3.9 using standard numbering or something.  To be honest, I don't think it's worth supporting anything older than clang 5 (using standard numbering).  It's pretty easy to install with MacPorts even on ancient versions of macOS.

**Comment by belegdol** [comment]
I have now updated the travis CI config to use Xcode 11 as opposed to default 9.4.1. This was enough to complete the tools build successfully:
https://travis-ci.com/belegdol/mame/jobs/242174493

**Comment by belegdol** [comment]
The MSVC build hits C1060 errors randomly, but not all the time. In my appveyor instance I have numerous successful builds:
https://ci.appveyor.com/project/belegdol/mame/builds/27886055/job/vac159yu0a4p7x6u
https://ci.appveyor.com/project/belegdol/mame/builds/27861053/job/1mpjo1h98k3n6fx5
If anybody knows what else can be done in order to make the MSVC build succeed more reliably, feedback is welcome :)

**Comment by belegdol** [comment]
@peterferrie, I originally posted the comment in the wrong issue so I am replying here.
In theory the 64-bit compiler is enabled:
https://github.com/belegdol/mame/blob/8e75711438a7c0ec39efdede2149f83042780478/.appveyor.yml#L16

**Comment by belegdol** [comment]
remmina_appveyor_13 83 108 89:33847_2019108-17443,880583
Looks like 64-bit compiler is used. Would you consider letting the build fail again a viable workaround?
This would mean that the improvements in this PR would be:
- adding tools build to travis (linux/gcc and macos/clang) and to appveyor msvc
- building a release build with msvc
- moving travis macos to xcode 11

**Comment by belegdol** [comment]
It turns out that passing OPTIMIZE=0 to make has no effect on msbuild, Release builds are still compiled with /Ox. I am testing if explicitly passing /Od to msbuild helps resolving the memory problem.

**Comment by belegdol** [comment]
It turns out genie's logic will not allow building a release build with /Od. Not enabling optimization results in build being recongnized as debug and a ton of LNK2038 linking errors. This leaves us following options, all of them less than ideal:
- wait until MSVC 16.5 is released debug tools build can be done [1]
- disable tools build and keep building a debug build
- build tools as release build and allow failures due to the fact that such configuration will hit C1060 regularly (the builders have very little RAM [2])
- add logic to scripts/genie.lua mapping **some** of the OPTIMIZE=x values to MSVC's and hope that /O1 survives low memory more reliably, e.g.
  - OPTIMIZE=3 to /Ox
  - OPTIMIZE=2 to /O2
  - OPTIMIZE=1 and OPTIMIZE=s to /O1
  - OPTIMIZE=0 would need to be mapped to something unexpected by anybody using OPTIMIZE=0, as disabling optimization entirely breaks the build.

I am open to suggestions.

[1] https://developercommunity.visualstudio.com/content/problem/752372/vs2019-v1631-c-internal-compiler-error-when-zi-opt.html
[2] https://www.appveyor.com/docs/build-environment/#build-vm-configurations

**Comment by belegdol** [comment]
I have now synced the PR branch with master and simplified the changes considerably. The fix for imgtool and jedutil failing to build with /ZI is not to build imgtool and jedutil with ZI.
Let me know if this PR is acceptable now, or what should be fixed otherwise.

**Comment by belegdol** [comment]
I have just discovered that appveyor mingw builds appear to be way quicker with OPTIMIZE=1 [1] than with OPTIMIZE=0 (which necessitates mbig-obj) [2]. The difference is 73 vs 45 minutes. Does it make any sense?
If it does, would it be OK to switch appveyor to OPTIMIZE=1? If we are lucky we might win enough time to turn tools build on.
[1] https://ci.appveyor.com/project/belegdol/mame/builds/28130780/job/fwa7ke2igoixyuet
[2] https://ci.appveyor.com/project/belegdol/mame/builds/28129224/job/j686h2sftv0p0773

**Comment by belegdol** [comment]
Please don't merge this yet, I am still trying a few things out to get the gcc build to finish in time more regularly.

**Comment by cuavas** [comment]
If you don't enable function inlining, a ridiculous number of out-of-line functions need to be instantiated for all the little inline helpers in headers (e.g. all the little helpers for configuring devices).  This makes `OPTIMIZE=0` slower to build and run, and a lot bigger.

**Comment by belegdol** [comment]
Thanks for clarifying, this makes sense. It also means that it might make sense to switch Travis to OPTIMIZE=1 too. While the builds finish on time, having them finish quicker is even better.
VS is another story as we currently do not have a way of passing /O1 to the project files (see https://github.com/mamedev/mame/pull/5703#issuecomment-540134887).
Finally, it turns out that MINGW build completes almost twice as fast on VS 2017 image as on VS2019 one:
https://ci.appveyor.com/project/belegdol/mame/builds/28163993
I have reported this to appveyor support, but if they do not come up with a fix I will just adapt the config to use VS 2017 image for gcc and VS 2019 one for msvc.

**Comment by belegdol** [comment]
It appears optimization level has little to no effect on Travis:
https://travis-ci.com/belegdol/mame/builds/132276925
This means we need an answer from appveyor support and I should be able to finally complete this PR

**Comment by belegdol** [comment]
I switched MINGW build to VS 2017 so that we can actually have working CI, once appveyor sorts out VS 2019 slowness we can simplify the set-up.

**Pull request merged**
