### PR TITLE
eppc: Added ROM:s for NEW PC compatible, Ericsson Portable PC, needs …

### PR DESCRIPTION
**Pull request by JoakimLarsson**
…additional emulation to be complete, such as a RAM floppy disk, aka Ergo disk, proper emulation of the orange plasma screen in the peculiar mode 640x400 and not the least the built in thermal printer!

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
Contributor of the ROM is for this machine is Joel Tegnér

**Comment by JoakimLarsson** [comment]
Fake Shemp donated one piece of Ericsson Portable PC hardware for this project

**Comment by cuavas** [comment]
Make sure you correct the credits in whatsnew for this during freeze - neither the PR description or the commit message contain necessary information, and I'll likely forget about it between now and then.

**Comment by JoakimLarsson** [comment]
The format for credits is usually the names in brackets in PR or commit message right? However I'll make sure to add credits to whatsnew.txt for those submissions

**Pull request merged**
