### PR TITLE
via6522 shifter support for external clock

### PR DESCRIPTION
**Pull request by JoakimLarsson**
The regression of the Mac adb bus support caused me to refactor the shifter and I feel much better about this implementation as it got rid of ugly sub states and purely handles flanks now as opposed to a mix of flanks and cycles before. In my regression tests I noticed that some systems seems to work a bit better and of course both Mac adb bus and the Prodigy. Let me know any problems asap

### CODE REVIEW

**Comment by Tafoid** [comment]
raaspec and vectrex now show noticeably 'smeared' graphics, as illustrated in the 10 second regression snapshot, which appears to be triggered from this PR.
vectrex-diff

**Comment by JoakimLarsson** [comment]
Hmm, interesting, wonder how this happened, the idea was to get the shifter bahaving more correct. This can be a side effect of normal use of CB1/CB2, I'll check it out.

**Comment by rb6502** [comment]
Possibly related: I'm trying to re-fix the Mac non-6805 shifter code to work with the latest VIA updates, and I can't get the mac128 keyboard to work.  The code's supposed to detect the Mac pulling CB2 down as a signal to begin a shifter transaction, but that no longer happens.

mame macplus -ramsize 1M will show the problem nicely.

With a printf in the callback:
WRITE_LINE_MEMBER(mac128_state::mac_via_out_cb2)

I see CB2 raised at reset and then it never moves again.

**Comment by JoakimLarsson** [comment]
I found a bug that affects systems with internal O2 clocked CB2, like the Vectrex. When I switched to work with flanks I forgot to half the timer period so the data is shifted out at half the rate. Normally this doesn't matter as CB2 is used to clock in data on most systems but on the Vectrex and other timing optimized systems the data was chopped after half the period and a new value was placed in the shifter. I submit a patch for it later today. Could it be causing the problems you see RB? I'll check it out myself and let you know anyway.

**Comment by JoakimLarsson** [comment]
Ok, there is now a new pull request that reduces the smeariness of the graphics but I think it is not reverted completely to the previous state of the graphics. I am not sure this is a bug on the VIA side or if it is a timing dependent fix in the Vectrex driver to compensate for the previous faulty behavior of the VIA?

**Pull request merged**
