### PR TITLE
Consolidated logic for moving the current selection within a menu

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by cuavas** [comment]
As with the previous PR that was supposed to do this, it's useless if it can't make the selection member private and deal with what selgame/selsoft has to do.

**Comment by npwoods** [comment]
I've made an attempt to address the concerns that have been outlined.  To a certain extent, this is putting lipstick on a pig - selgame/selmenu really abuses the menu system.  But failing the adoption of a widgetting system this seems reasonable.

**Comment by rb6502** [comment]
@cuavas, do Nathan's changes address your concerns?

**Comment by cuavas** [comment]
Close for now, we can resurrect it later.  This is another can of worms thing.

**Comment by rb6502** [comment]
Fair enough.  Thanks!

**Pull request closed without merging**
