### PR TITLE
game name consinstency

### PR DESCRIPTION
**Pull request by f205v**
Changed a few games' names for consistency with similar situation,
where the Export version has the simplest name, and the Japan version
has a trailing j.

### CODE REVIEW

**Comment by f205v** [comment]
Thank you very much!
It was the first time I tried messing around with github.
Hope everything was OK.

Ciao
Antonio (f205v)
www.citylan.it

**Comment by rb6502** [comment]
Yeah, it was fine, sorry about the wait :)

**Comment by etabeta78** [comment]
In fact, you forgot to change names in mame.lst so that current tree does
not compile.
But I'm not on my working machine right now...

   f.

**Comment by f205v** [comment]
I'm sorry about this,  but I didn't change it because I thought that
mame.lst is now automatically generated and should not be touched by hand.
My fault.
Il 12/Apr/2016 15:35, "etabeta78" <notifications@github.com> ha scritto:

> In fact, you forgot to change names in mame.lst so that current tree does
> not compile.
> But I'm not on my working machine right now...
>
> f.
>

**Comment by etabeta78** [comment]
now that you mention it, you might be right :)
I haven't yet added any new set since the passage to GENiE build system...

   f.

**Comment by p1pkin** [comment]
@f205v at this moment mame.lst must be updated manually if set(s) was added or renamed.
however, this is not place for some documentation in comments anymore, because this comments can be wiped out during some auto-regeneration in future.

**Comment by f205v** [comment]
Ah! OK, thank you for explanation.

Ciao
Antonio (f205v)
www.citylan.it

**Pull request merged**
