### PR TITLE
Taito 68705 refactoring

### PR DESCRIPTION
**Pull request by mamehaze**
- renamed the rather misleading buggychl_mcu_device (machine/buggychl.cpp) to taito68705interface.cpp because a number of drivers were using it.

- refactored that device to use the new 68705 core with built in peripherals

- refactored some other drivers, including Tokio to use it (others will likely follow, as this is a standard way in which Taito hooked up 68705s to communicate with the main CPU)

### CODE REVIEW

**Comment by startaq** [comment]
I think this needs to be done in a cleaner way. First you create a common hookup (ok), but then you create invididual devices to handle the special cases anyway (`TAITO68705_MCU_TIGER` etc.). All this does is to obfuscate the actual MCU hookup. The common hookups need to be put into the drivers themselves.

**Comment by ajrhacker** [comment]
I agree with @startaq. The latches and bits aren't even part of the MCU package itself (they're a bunch of TTLs on actual HW). I think they would better be handled as a separate device or devices, to be hooked up to the 68705 ports using devcb. This could also be used to help handle cases where the MCU code is undumped and has to be simulated in the driver.

**Comment by mamehaze** [comment]
well the idea is to show where the hookups were different, and how, which can sometimes point at an MCU not really being an original taito one.

the device encapsulates common behavior, to avoid code duplication, it also forces the hookups to some kind of standard.  to me it makes it clear how they differ when at first some of them just look like the same code copy+pasted.  many of them were identical hookups.

actual CPU behavior goes in the CPU, this is just a common way Taito hooked things up.  The work has been discussed with @Lord-Nightmare who seemed to agree with this way of doing things, so I continued down this path.  It should make hooking up further MCU dumps for Taito games easier, and lets us know what kind of differences we can expect.

**Comment by mamehaze** [comment]
basically I see no way to do what is suggested without actually moving in the opposite direction, resulting in more copy+paste code that is liable to diverge in it's own way each time an individual driver is modified, the exact damage I'm trying to *undo* by encapsulating things like this.

if the hang-up is that this is TTL, then I'm not sure where that's coming from, we already have a number of devices that encapsulate common behavior, even if they just represent a common collection of circuits / way of doing things.  It's good OO programming.

if the hangup is that the organization, consider that it means all 68705 accesses using this have to go through a common interface, making the code easier to read / maintain as you know nothing else in the drivers is touching the 68705, this is where all the communication and talking to it lies, again, to me, that's good isolation of functionality, and good OO programming.

if the hangup is I've not moved the 68705 timers from the arkanoid driver into the 68705 core, it's simply because I've not got around to that yet, I haven't touched them at all.

otherwise, I'm a bit baffled, as it seems like I'm just being asked to go backwards and introduce more copy+pasted code using DevCB and individual devices, rather than sharing the common functionality to better highlight the differences.  Clearly having more duplicate code isn't a good way forward.

If this isn't wanted, so be it, but it would have turned adding the Tokio MCU from a job that took several hours to one that took 5 minutes at most had it been done before, and right now that is kinda important.

**Comment by ajrhacker** [comment]
The DEVCB approach I recommended may look like needless duplication of code, but ad-hoc subclassing suggests that the "common interface" isn't entirely common and greater flexibility is needed. DEVCB is very flexible now: it even incorporates optional bit-inverting functionality that on actual HW has to go through random TTL devices, and MCFG_DEVCB_CHAIN_INPUT, which I just recently implemented, can be used to combine a few line reads into a single byte without needing to write and declare a separate function to put them together.

I don't think it's wrong to use one device to represent a few TTL parts working in concert; after all, GENERIC_LATCH_8 is now basically something like a 74374 plus half of a 7474 flip-flop. However, I think it's wrong to aggregate too many complex parts together into a device when they don't form a separate board (airraid being my case in point).

**Comment by mamehaze** [comment]
I'm still looking at it from a maintenance point of view, and ease of understanding, plus the ability to easily compare and contrast the slightly different hookups to get an idea of what to expect for something new.

I think we're going to have to agree to disagree here, what that means for the submission I don't know, but from the point of view of me working on the code the solution I've come up with works best, as it does by the other criteria I've considered and feel to be important.  I feel the other suggestions made do not help in the same way and that I would be going backwards by implementing them.

re: Air Raid, for the dual board setup, the device does form a PCB, for the single board setup, it all happens to be integrated, it's no different really to where we have devices that represent both a load of TTL chips AND a custom chip on later boards when they got integrated into a single package (this happened a lot, sometimes with minor changes along the way)

**Comment by rb6502** [comment]
@ajrhacker and @startaq are you guys willing to redo this in the cleaner manner, and if yes would you prefer to work from current or current with Haze's changes here?  If no, I'm going to apply Haze's version and be done with it.

**Pull request merged**
