### PR TITLE
HP9845: TACO driver re-written

### PR DESCRIPTION
**Pull request by fulivi**
Hi,

this PR is for the complete re-write of HP TACO driver.
The re-write was prompted by the publication of a HP internal doc about TACO in late 2018.
The previous driver was written with just reverse-engineered info available.
I also re-factored the DC100 tape cartridge driver into a separated device so that all the tape motion and data R/W is handled there. I adapted the 1MA6 driver and the HP9825 tape sub-system to this new device.
I also had to change the HTI tape format (and hp9845_tape/hp85_tape modules in imgtool) because I found out that data words are actually 16-bit long in HP9845 and HP85 cases, whereas they are 17-bit long in HP9825. Previously, I was convinced that all systems stored 17-bit words on tape.
The new format keeps the "hti" file extension but the magic at the start of file has changed to "HTI0" (previous one was "TACO"). The old "TACO" format is still accepted and it's transparently converted to the new format when loaded.

In this PR I also fixed a small bug in HP Hybrid CPU emulation that caused hp9825t to hang when computing logarithms (for example).

Thanks,
--F.Ulivi

### CODE REVIEW

**Comment by happppp** [comment]
I understand that you had to have 2 "taco" devices while developing the new device. But after removing the old device, it's not needed anymore. Did you forget to remove "new" to the namings?(both for source filename and device name)

**Comment by fulivi** [comment]
Oops, you're right. That was something I was planning to do but got lost along the way...

**Comment by kossow** [comment]
"The re-write was prompted by the publication of a HP internal doc about TACO in late 2018."
where is this document located?

**Comment by fulivi** [comment]
Here: [TacoERS](https://groups.io/g/VintHPcom/files/HP%209825/9825%20Binary//TacoERS.pdf)

**Pull request merged**
