### PR TITLE
vsnes.cpp: Set raw screen parameters.

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by 0kmg** [comment]
Abbreviated details are here: https://wiki.nesdev.org/w/index.php?title=Cycle_reference_chart. This has the effect of pushing up the refresh rate slightly (60.098476 according to MAME, slightly lower than the rounded figure for RGB PPUs on the linked page). It improves but does not completely get rid of odd scrolling lines in Excite Bike: https://mametesters.org/view.php?id=6909. I played 15-20 or so sets and noticed no other positive or ill effects.

**Comment by Tafoid** [comment]
There are a number display changes (even noted at least one behavior change in 'wrecking') after this commit.
Perhaps you can verify such are acceptable?  Here is a link to the before/after/diff snaps from a 10 second run.

https://mameload.mameworld.info/vsnes_snapdiff.7z

**Comment by cuavas** [comment]
I doubt this will work properly – you’ve put the origin of the visible area at (1,0) but MAME really doesn’t like it if it isn’t at (0,0).  This is a limitation of MAME as it is today.

**Comment by 0kmg** [comment]
Thanks. Setting the origin at (0,0) fixes things being shifted right by one across the board. I'll submit a PR.

I can't say for sure how Wrecking Crew's attract mode is supposed to look. It looks like, based on visual inspection not disassembly, P1 is scripted and everything else is using the regular game AI. The timing is somehow affecting the PRNG. The only YT video (John's Arcade) I could find doesn't have enough footage to shed much light.

**Pull request merged**
