### PR TITLE
initial skeleton driver for Canon S-80 typowriter

### PR DESCRIPTION
**Pull request by felipesanches**

### CODE REVIEW

**Comment by happppp** [comment]
Please flesh it out a bit more before submitting this driver, this is too
bare-bones.

**Comment by felipesanches** [comment]
yeah, sure. Ramiro Polla is also involved in this one. He's the one who actually has access to the original device.

**Comment by mamehaze** [comment]
I didn't know there was such a thing as a 'too bare bones' skeletons.. that's the whole point in them...

**Comment by balr0g** [comment]
@mamehaze I agree; this one needs to be fixed up to work with the current MAME source though.

**Pull request merged**
