### PR TITLE
    Added driver for Heurikon HK68K/V10 VME board

### PR DESCRIPTION
**Pull request by JoakimLarsson**
This is my first stab at the Heurikon HK68K/V10 VME board. I just got the terminal working but the work involved  changes to the z80dart device driver which is used by many other board drivers:

altos5.c ampro.c apricot.c apricotf.c apricotp.c attache.c bigbord2.c czk80.c hk68v10.c isbc.c mtx.c mz2500.c nanos.c ngen.c onyx.c osbexec.c p8k.c pcm.c pulsar.c qx10.c rt1715.c sun1.c ts802.c univac.c

I have tried not to change any legacy functionality, just add Z80SCC support, essentially more registers and an alternative access interface. I have tested the sun1 and altos5 drivers with success. The 8530scc.c driver looked too incomplete and would have required much more work so I based the work on z80dart.c which already supported the Z80SIO which is the legacy base for the Z80SCC. Let me know what you think.

I will post layout and use info in the VME thread shortly

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
The upd7201 that is already somewhat supported in z80dart.c supports some of the synchronous features of SCC and is register compatible with SCC rather than the DART. I have two upd7201 on a Mizar VME board I am looking at right now and will add more missing features, this time for upd7102, to z80dart.c unless someone objects really soon. :)

Btw, should I do something about the failing AppVeyor? Where do I find info on the problem?

**Comment by rb6502** [comment]
Never mind the AppVeyor build, it's busted period unfortunately.

Regarding the Z8530, I think I'd prefer that a new device be made called "8530n" (N = new) or something and incorporates the useful pieces of the upd7201.  That would give us a cleaner basis for future expansion (e.g. supporting the weird encodings used for AppleTalk) than continuing to layer more stuff on top of z80dart.  We could later work on converting over the users of the existing 8530 skeleton.

**Comment by JoakimLarsson** [comment]
No problem, I'll split out the SCC and UPD7201 parts in a new driver. 

Btw the Mizar board doesn't seem to need new 7201 code, it just setup some synchrounous registers while at it which the current emulator code ignores and then open up a prompt asynchronously. So I can submit the Mizar board driver independently.

**Comment by JoakimLarsson** [comment]
I have looked around a bit for other devices supporting synchronous modes and I found 8530, 7201, 68561 and 6854. There are probably more. The mc6854.c seems to have an SDLC like implementation so maybe we can move that up to a generic place like diserial.c and derive it from there? I am not suggesting doing it right now but just outlining the code structure a bit of the new driver

**Comment by rb6502** [comment]
It may be worth splitting out SDLC later; the current prevailing theory (which I don't fully subscribe to) is that diserial was a mistake because of subtle differences in UARTs and thus a lot of recent UART emulations have copy/paste code to do the bitstream (de)serialization/parity/etc.  So for now I'd copy/paste as necessary.

**Comment by JoakimLarsson** [comment]
ok. I am working on the z80scc support right now as separate device driver. I am thinking of splittin out the z80sio aswell so both z80dart and z80scc can inherit it avoiding all that cut and pasting which is always a problem in the end. Should have something in a few days, unless distracted by realities

**Comment by JoakimLarsson** [comment]
Created tow new devices for z80sio and z80scc and used them instead of the z80dart. Also reverted the z80dart. Please review.

**Comment by rb6502** [comment]
Can you redo this request against latest top of tree?  Micko just moved all the devices around so it won't apply as-is.

**Comment by mmicko** [comment]
Sorry for this Joakim, files are just moved without any change in them so
it should be straight forward.

Micko

**Comment by JoakimLarsson** [comment]
No problem but it didn't build for me for some other reason I think so I hope I got it right. Got this message: <pre>  File "/home/joakim/work/mame/src/build/makedep.py", line 290
    sys.stdout.write('		MAME_DIR .. "src/devices",\n')
    ^
IndentationError: unexpected indent
  File "/home/joakim/work/mame/src/build/makedep.py", line 290
    sys.stdout.write('		MAME_DIR .. "src/devices",\n')
    ^
IndentationError: unexpected indent
/home/joakim/work/mame/scripts/genie.lua:1311: attempt to call a nil value
stack traceback:
	/home/joakim/work/mame/scripts/genie.lua:1311: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:74: in function 'dofile'
	[string "_WORKING_DIR        = os.getcwd()..."]:41: in function '_premake_main'

**Comment by mmicko** [comment]
please  pull latest, should be fine now. there was error in python script,
thanks for report.

Micko

**Comment by JoakimLarsson** [comment]
ok, I think I figured it out and moved the devices to the right place.

**Comment by JoakimLarsson** [comment]
Ahh, multiple definitions of SCC8530, I will fix this, just a moment

**Comment by JoakimLarsson** [comment]
Should be ok now

**Pull request merged**
