### PR TITLE
jpmimpct: add layout to Cluedo? Murder Mystery Quiz Game

### PR DESCRIPTION
**Pull request by as-tb-dev**
This adds the game board to Cluedo? Murder Mystery Quiz Game.

### CODE REVIEW

**Comment by cuavas** [comment]
This includes a layout that isn’t CC0-licensed.  If this can’t be addressed, I’m going to revert it.

**Comment by as-tb-dev** [comment]
> This includes a layout that isn’t CC0-licensed. If this can’t be addressed, I’m going to revert it.

Do I just need to change 'license: BSD-3-Clause' to 'license: CC0-1.0' in the layout file?  If so, then I can address it.

**Comment by cuavas** [comment]
> > This includes a layout that isn’t CC0-licensed. If this can’t be addressed, I’m going to revert it.
> 
> Do I just need to change 'license: BSD-3-Clause' to 'license: CC0-1.0' in the layout file? If so, then I can address it.

Yes, that's all that needs to be done. We like to keep the license for the layout files as permissive as possible to encourage people to expand on them and experiment with them.

**Comment by as-tb-dev** [comment]
> > > This includes a layout that isn’t CC0-licensed. If this can’t be addressed, I’m going to revert it.
> > 
> > 
> > Do I just need to change 'license: BSD-3-Clause' to 'license: CC0-1.0' in the layout file? If so, then I can address it.
> 
> Yes, that's all that needs to be done. We like to keep the license for the layout files as permissive as possible to encourage people to expand on them and experiment with them.

I corrected it in https://github.com/mamedev/mame/pull/12966.

**Pull request merged**
