### PR TITLE
fix screen_device::update_now() when drawing partial lines

### PR DESCRIPTION
**Pull request by enikland2**
This is necessary to fix the MT report https://mametesters.org/view.php?id=7331 along with a new commit I will add to pull request #4910.

### CODE REVIEW

**Comment by MooglyGuy** [comment]
This seems like black magic. We'd appreciate a verbal description of what the problem was, and how this fix addresses the problem.

From a quick look at the change, however, the use of `m_last_partial_scan++;` appears to be faulty, and based on an assumption that a screen will always do partial updates a scanline at a time. That is not safe to assume. Some systems do partial updates in blocks of scanlines, for example, or only when a given parameter is changed to require an update.

**Comment by enikland2** [comment]
m_last_partial_scan++; will be executed only if m_partial_scan_hpos > 0, what is being used to indicate if the last update was partial. When this "detection" was true, the old code wrongly first used update_partial() (that updates full lines of a partial frame) before first try to complete the partial line. What I did was invert the steps: first complete the partial line, then use update_partial() to update the frame until the previous line, then the rest of the code (unchanged) update the current line partially.

**Comment by enikland2** [comment]
I also had to change pixel() and pixels() to use the index of the current bitmap, but I left alone this line in screen.h because I don't know if there is some code that relies on the current situation:
   screen_bitmap &curbitmap() { return m_bitmap[m_curtexture]; }

**Comment by MooglyGuy** [comment]
Sounds reasonable enough.

How much testing has been done against the various systems that use partial updates, other than the affected system?

I'm thinking that since MAME is going into code freeze for the upcoming release in under 12 hours, and there's not enough time for a comprehensive regression test before Wednesday, it might be best to apply this PR after the code freeze so that we have the entire cycle leading up to 0.211 to catch any regressions, just in case.

Its ultimately up to the rest of the team, I just feel that it would be more responsible to hold off on a change like this until 0.211, given the last-minute nature of it.

**Comment by enikland2** [comment]
I didn't test systems other than NES/SMS, but the function as it was seems partially broken to me. Grep revels this list of additional files where it is being used (// lines omitted):

src/devices/video/tms9927.cpp
src/devices/bus/isa/cga.cpp
src/mame/drivers/apple2.cpp
src/mame/drivers/dotrikun.cpp
src/mame/drivers/superga2.cpp
src/mame/drivers/apple2e.cpp
src/mame/drivers/m79152pc.cpp
src/mame/drivers/tv990.cpp

**Comment by rb6502** [comment]
Enik's right, that functionality for partial-scanline updates has never worked right since I first attempted to add it, and I never got around to trying to fix it.  So I'm not sure his changes could make anything worse.

**Comment by MooglyGuy** [comment]
If its use is that limited, then yeah, let's give it a shot.

**Pull request merged**
