### PR TITLE
Fix build by removing unused placeholder definition (nw)

### PR DESCRIPTION
**Pull request by ajrhacker**

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
How was this detected? I did a full build with no problem on Win-7 and didn't see a build problem at the PR either

**Comment by ajrhacker** [comment]
Some compilers complain more about unused definitions than others. I'm using Apple LLVM version 7.0.2 (clang-700.1.81) and doing debug builds.

**Comment by cuavas** [comment]
If clang can see the bodies of all member functions and initialisers for all static data members of a class in a single translation unit, it will warn about unused private members, gcc doesn't do this check.  The CI builds don't build everything, just the core and a few drivers to check for major breakage.

**Comment by JoakimLarsson** [comment]
ok, I have to take a look at clang then

**Pull request merged**
