### PR TITLE
Fix mm1 video

### PR DESCRIPTION
**Pull request by kara1001000**
This branch should pretty much finalize MikroMikko 1 video, both text and graphics modes separately and together. Maybe some HLSL effects could be added for the afterglow effect of the slow phosphor display, but that's all I can think of now.

### CODE REVIEW

**Comment by cracyc** [comment]
There were too many issues with the 7220 changes so I did it differently.  Let me know if there are still problems with the mm1.

**Comment by kara1001000** [comment]
Well, that's a simpler solution, and it also works IF you take also away the lines
	if(y >= 25)
		y -= 25;
that you added in UPD7220_DISPLAY_PIXELS_MEMBER in mame/video/mikromik.c

However, if you leave out my changes in upd7220.c, visarea calculations there are wrong for MikroMikko 1. The reason for things working is that by leaving out my changes, also the call
		m_screen->configure(horiz_pix_total, vert_pix_total, visarea, refresh);
was moved back under "if (m_m)" condition branch in recompute_parameters().
The result is that m_screen->configure() is now never called for MikroMikko 1, as m_m is never != 0 as far as my testing so far has revealed.

I moved the m_screen->configure() -call under the else -branch during my testing at some point to see if things would still work if m_m  == 0, and forgot it there. So, now the hesitation remains that if m_m == 0 at some point, graphics will be offset and stretched in MM1 emulation.

Do you know what the m_m (VSYNC mode?) values can be, what they mean, and if it's assumable that the mode remains unchanged in all situations with a specific device such as MikroMikko 1? If there is any doubt that value of m_m can vary (depending on some draw mode or other dynamic configuration), I suggest taking in the MCFG_UPD7220_VISIBLE_AREA_OFFSET configuration macro implementation to enable calculating correct visarea values for any device and ensuring correct graphics positioning regardless of the value of m_m.

**Comment by kara1001000** [comment]
I think my testing last night revealed an issue with upd7220 emulation regarding read access of the display memory. When calling CDOT function for reading the color of a given pixel, MikroMikko 1 emulation freezes in all othe cases but the simplest one where we read the color of a pixel we just set (and do not change the coordinate meanwhile or do pretty much anything).

Who would understand the upd7220 enough to implement the FIFO timings and read-modify-write cycle properly? I think this issue may well have something to do with that, but the implementation part seems pretty tricky and I find it hard to understand.

**Comment by mr-t-guru** [comment]
probably the copyright holders listed at the top of src/devices/video/upd7220.c could know

**Comment by cracyc** [comment]
m_m is set for the master 7220 device which handles all the actual screen timing.  Out of all the dozen or so emulated machine that have 7220s only the mm1m6 and pc9801 have 7220s configured in slave mode.  Since it's the masters job to set up the screen the configure call should only be made if m_m is set so moving it broke quite a bit of things.  As far as the mm1m6 goes, the 8275 does the screen timing and having master mode set on the 7220 might really screw up the display output if you were to try it on a real machine. If it turns out that somehow configure is called from the 7220 we might have to put a guard around it so configure isn't called until the screen is actually enabled and m_m is set.   As for the CDOT, I looked into it and it's using 0xa0 (RDAT) opcode to read 2 bytes from the vram but it actually only reads one then is confused why the FIFO isn't empty.  The 7220 datasheet says that bytes are loaded from the FIFO to the data output register which might mean FIFO empty might be set when there is one more byte to read but I haven't gotten that to work yet.

**Comment by kara1001000** [comment]
Ok, thanks for clarifying that, M for master makes sense (as does your explanation). Sorry for breaking things, my bad for not remembering to return stuff to where I took it from after playing with it. :) 

Kudos for the research with CDOT, let's hope the root issue gets revealed and fixed!

**Comment by cracyc** [comment]
I committed something which appears to work.

**Comment by kara1001000** [comment]
Indeed it works. Well done!

**Pull request merged**
