### PR TITLE
Move disasm overrides into interface, reducing driver-debugger depend…

### PR DESCRIPTION
**Pull request by ajrhacker**
…encies (nw)

### CODE REVIEW

**Comment by cuavas** [comment]
Why aren't you using std::function?  A driver may want to have state available in its overriden disassembly function.

**Comment by ajrhacker** [comment]
Given that all the existing overrides depend only on lookup tables of system calls, even using device delegates (which other MAME interfaces use instead of std::function) seems superfluous now.

After all, most CPU disassembly methods, after passing through the interface wrapper, are non-member functions that can't consult the running state or even the configured state themselves because unidasm doesn't want to configure no stinking devices.

**Comment by cuavas** [comment]
They currently don't depend on state because it's difficult to. I'm working on making the SPARC disassembler integrate better with the running CPU core and driver already.

**Comment by rb6502** [comment]
AJR: until it was enabled recently nobody registered debugger commands that used class state either.  Because it was pretty much impossible.

**Pull request merged**
