### PR TITLE
megadriv: addition of L'Abbaye des Morts (2017)

### PR DESCRIPTION
**Pull request by arcadehistory**
Added the freeware ROM of the game, available here => https://playonretro.itch.io/labbaye-des-morts-megadrivegenesis-por-002

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
Please give your pull requests descriptive titles and use descriptive commit messages.  “Update megadriv.xml” does not tell anyone what the change is supposed to achieve.

**Comment by arcadehistory** [comment]
> Please give your pull requests descriptive titles and use descriptive commit messages. “Update megadriv.xml” does not tell anyone what the change is supposed to achieve.

**Comment by arcadehistory** [comment]
> Please give your pull requests descriptive titles and use descriptive commit messages. “Update megadriv.xml” does not tell anyone what the change is supposed to achieve.

Added the freeware ROM (published by the author) of this homebrew game, available here => https://playonretro.itch.io/labbaye-des-morts-megadrivegenesis-por-002.

It was also published as a physical cartridge in 2017. It works fine.

**Comment by cuavas** [comment]
We have a format we use for commit messages, including how lists of additions are formatted so they’re scraped properly.  Could you please look at how regular contributors do things?

**Comment by arcadehistory** [comment]
> We have a format we use for commit messages, including how lists of additions are formatted so they’re scraped properly. Could you please look at how regular contributors do things?

Hello, 

Since big files can't be opened and edited in the browser, I installed Git Desktop and I'm a total noob at using it.  Where I can find the "format" you are speaking about ?

**Comment by MooglyGuy** [comment]
I'm not sure how Git Desktop works, but presumably one of the things that it allows you to do is an action called a "Commit". This is where it should allow you to provide a description of your changes.

For changes to softlists, it's generally preferred that the commit messages contain the relevant info on what was added, as comments on pull requests are not scraped into the auto-generated list of changes each month.

For a good reference, consider looking at most of the recent softlist additions done by @ArcadeShadow.

**Comment by Robbbert** [comment]
Added L'Abbaye des Morts. Closing.

**Pull request closed without merging**
