### PR TITLE
pgmprot_igs027a_type1: simulated Photo Y2K2 sprite offset decode [iq_132]

### PR DESCRIPTION
**Pull request by Osso13**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
if you remove the 'NOT WORKING' flag it will appear in the promoted games list.

Given it still has the unemulated protection flag, which suggests there are still going to be protection issues, do you really want it to be promoted?

**Comment by iq132** [comment]
It would be great to have it marked as working (but with unemulated protection) and extensively play-tested before removing the flag.

**Comment by dinkc64** [comment]
I played 3 levels, no problem so far :)

**Comment by Osso13** [comment]
> 
> 
> if you remove the 'NOT WORKING' flag it will appear in the promoted games list.
> 
> Given it still has the unemulated protection flag, which suggests there are still going to be protection issues, do you really want it to be promoted?

I went that way because it seemed to me that's the way used in the driver for games where the simulation works well enough but haven't the internal ROM dumped (i.e. kov, kovplus). If you think it should stay as not working, I've got no issue with that.

**Comment by dinkc64** [comment]
unfortunately there is still something else needed - i found out the game crashes after level 11 or 12 :(

**Comment by dinkc64** [comment]
If possible, please hold off on merging this.  We have a solution to the game crashing at the end of level 12, from a savestate perspective.  Going to have to replay the entire game with the new code to see for sure :)

**Comment by dinkc64** [comment]
game now working!  I played to the end (after level 40 is ending) :D 
@Osso13, please add these code changes to this PR from:
https://github.com/finalburnneo/FBNeo/commit/33943eb272fb50c40294eec9fdd89d27e61428bd

best regards,
- dink

**Comment by Osso13** [comment]
Thanks for all the feedback! I'll close this for the time being and commit directly later.

**Comment by dinkc64** [comment]
Last night iq_132 figured out part of pgm3in1 crypt & prot table as well, though, there are 2 small issues to figure out regarding the sound playback and sprite priorities - will keep ya updated on that as well.  3in1: https://github.com/finalburnneo/FBNeo/commit/1e1cf03693b156864e17647b7a0e56344fb919ea

**Comment by dinkc64** [comment]
@Osso13, we just had a second person complete Photo Y2K 2, I'm confident that py2k2 is fully working now.

**Comment by Osso13** [comment]
@DavidHaywood should I remove the MNW flag, given what dinkc64 reports?

**Comment by DavidHaywood** [comment]
if there are no known protection issues then I guess both flags can be removed?

afaik we don't flag unemulated protection for simulations if they're accurate

**Pull request closed without merging**
