### PR TITLE
Removed unneeded strlen in info.c

### PR DESCRIPTION
**Pull request by MASHinfo**
If "device->shortname()!= nullptr" then strlen of device->shortname() can not be 0.
Increase listxml output ==> 18%

### CODE REVIEW

**Comment by cuavas** [comment]
I don't think you understand C strings.

**Comment by balr0g** [comment]
@MASHinfo's intent seems to be to speed things up, as strlen() is O(n) since it has to iterate over the string and find the null terminator. Unfortunately, the returned string could exist but be empty, in which case the code would print out tags like <device_ref name=""/> (with an empty name entry), which we don't want.

As an empty C string will have a null as its first character, it should be faster (but less obvious) to do "device->shortname()[0]=='\0', and just as safe as using strlen().

@MASHinfo, can you test that, and see if it also provides such a performance improvement?

**Comment by MASHinfo** [comment]
... with device->shortname()[0]!='\0' it is also ~18%.

**Comment by balr0g** [comment]
In that case, can you update this PR or open a new one?

**Comment by MASHinfo** [comment]
No! Vas has closed this report.

**Comment by mr-t-guru** [comment]
its open again. please go ahead and do the changes. thanks

**Comment by MASHinfo** [comment]
It's up. Thx!

**Comment by balr0g** [comment]
Rebased to remove the incorrect commit and merged in https://github.com/mamedev/mame/commit/e9648efd493069fd32a92febb3bc9a7d001ec0b9.

**Comment by galibert** [comment]
And we want to accept empty but not null shortnames?

  OG.

**Comment by etabeta78** [comment]
the code checks indeed for device->shortname()[0]!='\0' because we don't
want...  ;)

   f.

**Comment by galibert** [comment]
But then shouldn't the test be part of validate, not listxml?

  OG.

**Pull request closed without merging**
