### PR TITLE
psx.xml: Added European redump.org dumps (0-9)

### PR DESCRIPTION
**Pull request by aeternal606**

### CODE REVIEW

**Comment by aeternal606** [comment]
Oops, just noticed that I should have used short region names in the <description> tag ('Euro' instead of 'Europe', 'Ita' instead of 'Italy' and so on). Sorry, I'm going to fix that in the next commit!

**Comment by etabeta78** [comment]
Sorry but this is already in progress, together with Japan...
I  have #-S done, T-Z in progress

   f.

**Comment by aeternal606** [comment]
Oh, okay. Fortunately I only just started :D I'm glad to hear you've already gotten so far. Looking forward to your list!

**Comment by Shideravan** [comment]
I think that the best thing to do before work on a big change is to send just a small part of it, to see if it can be merged or have any problem with (or it will be reinventing the wheel for something yet to be merged by another dev)
You did the same as I used to do ;)

**Pull request closed without merging**
