### PR TITLE
electron.cpp: Use the BBC Micro cassette reading code to improve cass…

### PR DESCRIPTION
**Pull request by wilbertpol**
…ette reading.

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
Two things:
* Do the BBC Micro and Acorn Electron really use the same tape interface circuitry, or circuitry that behaves similarly?  Can you comment @Pernod70?
* If this actually is the same code as the BBC Micro tape code, it should be factored out so it can be reused.  We already have far too much tape code copy/pasted between drivers.  This is substantial enough that it‘s almost guaranteed to get out of sync when people forget there are two copies of it and only update one.

**Comment by Pernod70** [comment]
It is not the same circuitry as the BBC as the Electron is implemented in a single ULA (plus CPU, ROM, RAM), but is likely functionally very similar.
I've no objections to having this merged.

**Comment by cuavas** [comment]
I still don’t like the duplication, dual maintenance and potential for divergence if the intention is to make them behave identically.

**Comment by wilbertpol** [comment]
I moved the duplicated code into a device

**Comment by wilbertpol** [comment]
I am going to take a different approach with this

**Pull request closed without merging**
