### PR TITLE
New NOT_WORKING clone

### PR DESCRIPTION
**Pull request by clawgrip**
I'm adding this as NON WORKING just to save some time to whoever wants to work on it.

New NOT_WORKING clone
---------------------
Frogger (Video Dens, Spanish bootleg on Scramble hardware) [Tomas Garcia-Meras (ClawGrip), Roberto Fresca, Recreativas.org, The Dumping Union]

### CODE REVIEW

**Comment by ajrhacker** [comment]
I've managed to get this new set working. Unfortunately, two of the program ROMs appear to have some bitrot (`frogvd_r2-libro-s2.ae9` and `frogvd_r12-ot2.bd5`).

**Comment by clawgrip** [comment]
Thanks a Lot.

I’ll redump them on monday, although it’s probably, as you said, a bitrot. I allways redump every ROM until I get constant reads 🙁

Regards: Tomás

El 7 sept 2018, a las 21:06, ajrhacker <notifications@github.com<mailto:notifications@github.com>> escribió:


I've managed to get this new set working. Unfortunately, two of the program ROMs appear to have some bitrot (frogvd_r2-libro-s2.ae9 and frogvd_r12-ot2.bd5).

**Comment by clawgrip** [comment]
Can you please send me the two patched ROMs?

Thanks!!
________________________________
De: ajrhacker <notifications@github.com>
Enviado: viernes, 7 de septiembre de 2018 19:06
Para: mamedev/mame
Cc: ClawGrip; Author
Asunto: Re: [mamedev/mame] New NOT_WORKING clone (#3969)


I've managed to get this new set working. Unfortunately, two of the program ROMs appear to have some bitrot (frogvd_r2-libro-s2.ae9 and frogvd_r12-ot2.bd5).

**Comment by ajrhacker** [comment]
Here I will give the diffs between byte-sized hexdumps of the original and patched ROMs.

Changes to the second main program ROM (loaded at 0x800):
```
$ diff frogvd_r2-libro-s2.ae9-old.txt frogvd_r2-libro-s2.ae9.txt
17c17
< 010:  f6
---
> 010:  fe
97c97
< 060:  27
---
> 060:  2f
113c113
< 070:  32
---
> 070:  3a
129c129
< 080:  34
---
> 080:  3c
161c161
< 0a0:  76
---
> 0a0:  7e
193c193
< 0c0:  36
---
> 0c0:  3e
209c209
< 0d0:  42
---
> 0d0:  4a
225c225
< 0e0:  32
---
> 0e0:  3a
273c273
< 110:  02
---
> 110:  0a
289c289
< 120:  34
---
> 120:  3c
305c305
< 130:  f4
---
> 130:  fc
337c337
< 150:  32
---
> 150:  3a
369c369
< 170:  c7
---
> 170:  cf
401c401
< 190:  35
---
> 190:  3d
417c417
< 1a0:  c5
---
> 1a0:  cd
449c449
< 1c0:  24
---
> 1c0:  2c
465c465
< 1d0:  a2
---
> 1d0:  aa
529c529
< 210:  66
---
> 210:  6e
639c639
< 280:  11
---
> 280:  19
655c655
< 290:  35
---
> 290:  3d
671c671
< 2a0:  e3
---
> 2a0:  eb
687c687
< 2b0:  70
---
> 2b0:  78
719c719
< 2d0:  66
---
> 2d0:  6e

```

Changes to the second sound program ROM (loaded at 0x800):
```
$ diff frogvd_r12-ot2.bd5-old.txt frogvd_r12-ot2.bd5.txt
15c15
< 00e:  00
---
> 00e:  08
142c142
< 08e:  47
---
> 08e:  4f
190c190
< 0be:  00
---
> 0be:  08
206c206
< 0ce:  01
---
> 0ce:  09
334c334
< 14e:  24
---
> 14e:  2c
350c350
< 15e:  76
---
> 15e:  7e
382c382
< 17e:  81
---
> 17e:  89
398c398
< 18e:  76
---
> 18e:  7e
418c418
< 1ae:  02
---
> 1ae:  0a
434c434
< 1be:  04
---
> 1be:  0c

```

Note that the second sound ROM, as patched, is identical to `frogger.609` from the parent set (and the other Scramble hardware bootleg) and `epr-609.ic33` from the three Sega sets, though the main program ROM remains unique. Note also that the unreliable data bit (D3) was the same for both ROMs.

**Comment by cuavas** [comment]
Should the main program be marked as a bad dump given it's manually patched?

**Comment by ajrhacker** [comment]
I marked both hand-patched ROMs as BAD_DUMP in the same commit in which I added them (b7267796432cf31fdc0c83d234a269aa75d4655a). All other dumped ROMs were usable as-is, though having to put in a watchdog reset at 7800 as well as at 7000 still makes me feel slightly awkward.

**Pull request merged**
