### PR TITLE
New phosphor persistence shaders for HLSL

### PR DESCRIPTION
**Pull request by anikom15**
### Major Changes

- Two types of phosphor persistence models for raster and vector screens
- Separate persistence model for LCDs
- Update the presets to work with the new shaders.

### Explanation
There are two basic responses for phosphor persistence: exponential and inverse power. You can't combine the two; you have to commit to one. Exponential is simpler and is designed for displays that use short phosphors like black and white television. It uses one parameter, tau, which increases the persistence. Inverse power is for longer persistences, and can be made to have a long tail while keeping a fast initial decay. The two parameters are beta and gamma. Beta is the power, from 0.5 to 2. Lower beta means a slower decay and (much) longer persistence, with gamma 1, a power of 0.5 will persist for over 18 hr., while a power of 2 will persist for only 15 s. Gamma is a time constant. Higher gamma means a faster decay and shorter persistence. These constants can be set individually for red, green, and blue subpixels. The mode has a slider and the subpixels each have three sliders for the three constants.

LCD persistence uses the exponential model. This makes sense because the response is basically an asymmetric capacitor. LCDs don't have individual responses for their red, green, and blue subpixels, and so there is just one slider.

I will try to port this to BGFX although I am even more unfamiliar with that than I am with HLSL. Please let me know if you have any problems or ideas.

—W.

### CODE REVIEW

**Comment by ImJezze** [comment]
I haven't tested your changes yet, but I already have some thoughts.

I would not distinguish between raster and LCD screen for the Exponential mode. Let the people (preset) decide if tau should be applied for each color component or not. This would make the check for the screen type irrelevant and simplify the shader code.

In addition I mostly like normalized value ranges for parameters between 0 (no influence) and 1 (maximum influence) (higher to overdrive) and the shader decides how to transform these values.

I also thinks about a simplification of the beta, gamma and tau parameters. This is quite cryptic for the average user. How about only two parameters, one for the time constant and one for the additional inverse power. (I'm still not sure, just loudly thought)

Let me know what you think.

**Comment by anikom15** [comment]
I can scale tau by ten to normalize it, not an issue at all. I think a maximum of 0.1 is long enough.

Gamma needs to have a very large range in order to get full flexibility from the model. Gamma has a very wide range. Gamma is actually not the same as tau. Gamma is a frequency constant. Putting the inverse power into a single parameter is definitely possible, but it will only have a single characteristic curve. Only the length of the tail will be modified. If you just want to use it to simulate one phosphor used for color TVs and monitors that should be fine, but I don't think it would work right for green and amber monitors. Right now the two parameters allow you to adjust the length of the tail, the decay rate, and the settling point (not a true settling point, for t >> 1/gamma it will go to zero, but it is very slow). FYI impulse response is h(t) = (1+gamma*t)^-beta. I will do more tests and maybe some research to get a better grasp of gamma. At that point I will try to think of a good range and normalize it and possibly have the slider represent the reciprocal instead. Beta on the other hand I think should keep to 0.5 to 2. This is the theoretical range of beta anyway, and I don't think normalizing it will make it any more easier to understand.

LCDs actually have a more symmetric characteristic. If you look at the blinking cursor of a calculator you can see this. I was planning on implementing this (after I learn more about it), but I can take out the LCD until I do. The reason individual RGB does not make sense for LCDs is because color LCDs do not use separate materials for R, G, and B as is for phosphors. Color LCDs use the same liquid crystal for all subpixels, and the color is dervied simply from a filter placed over the liquid crystal, but if you want that flexibility to be there I will do that.

**Comment by ImJezze** [comment]
I finally could test your changes and I really like the new Inverse Power mode. Unfortunately the effect immediately burns-in. I used phosphor_beta at 1.80 and phosphor_gamma at 50; all other effects deactivated. The old phosphor effect also burned-in, but only for a very high phosphor_life (0.75+).

Here are some examples. At a gamma of 50 the burn-in leaves rgb(3,3,3) behind, at round 100 it's rgb(2,2,2) and at 200 it's rgb(1,1,1), which stays quite a while till a gamma of 700. (beta always at 1.80)

50 gamma and 1.80 beta is a nice looking setting and as I said I really like the new implementation, but maybe you can get rid off the burn-in effect.

**Comment by ImJezze** [comment]
This should prevent the burn-in effect.

```
// prevent burn-in
if (DeltaTime > 0.0f)
{
	float threshold = 0.5f / 255.0f; // half color increment
	r = max(0.0f, r - threshold);
	g = max(0.0f, g - threshold);
	b = max(0.0f, b - threshold);
}
```

Applied before Red/Green/BlueMax is calculated.

**Comment by anikom15** [comment]
Thanks for your feedback. I will fix the burn in and work on making the inverse power parameters easier to use.

**Comment by anikom15** [comment]
I've combined the time constants into one slider and normalized it. I also updated the presets appropriately. Feedback is welcome. I am going to be working on the LCD side of things now.

**Comment by anikom15** [comment]
With the LCD shader fully implemented, I consider this pull request to be complete. @ImJezze @MooglyGuy

**Comment by ImJezze** [comment]
Thanks for your effort and it looks really nice so far. But the burn-in effect is back again. ;) Unfortunately, currently I have no idea how to fix that. The workaround I suggested (which is only a small constant decay) cannot work for a very slow decay. The problem is we use floating points in the shaders, but in the end we will only have a texture with discrete RGB values with 8-bit (0 to 255) per channel.

e.g. A slow decay changes the previous value from 0.294 (~75/255) to 0.293 (x 255 = 74.715 ~ 75), but the texture's RGB value will be the same as before (75) and the next iteration will have the same outcome.

The only thing I can suggest by now is to increase the the threshold to 0.75 / 255.0 / 12.92. This will at least work for all gamma values with a beta value greater/equal to 0.85.

Another small thing I would like to be changed before merging is the default values of the new sliders and .ini settings. A clean mame.ini or a mame.ini with missing settings should show no effect. The current default settings for LCD for example show a heavy ghosting.

**Comment by anikom15** [comment]
I don't see the burn-in effect myself. What are the parameters you use where this occurs?

**Comment by ImJezze** [comment]
I used a clean mame.ini (created with mame.exe -cc) and changed the following settings. (all presets removed)

```
phosphor_mode             0
phosphor_time             0.050,0.018,0.018
phosphor_beta             1.0,0.7,0.7
```

Now start MAME with pacman, wait for the title screen and activate Inverse Power mode. You will get the following results. (the vertical bar)

pacman01

After a round of demo gameplay you get this. (the maze)

pacman02

If the phosphor effect is not deactivated on start, the whole screen will be burned-in by the noisy sprites when the game boots; therefore you wouldn't see the differences.

**Comment by anikom15** [comment]
If I understand how this works, we're limited to a finite persistence of 4.25 s at 60 Hz. This is inversely proportional to refresh rate (of the emulated system, not the monitor), and is due to the fact that in order to avoid burn-in we have to move at least 1 sRGB per frame.

The best way to fix this would be to preserve the floating point values. I don't know how to do this.

Otherwise the fix is simple, but my modification of your fix was naïve, as I assumed the issue only occurred at small intesities (less than 10 sRGB). Unfornately, a simple 2.2 gamma approximation to calculate the appropriate threshold is too inaccurate, so the fix involves a lot of math.

I have generated a 256-length lookup table for threshold, but I don't know how to implement it. Basically 'threshold' is dependent on the intensity of a subpixel. Getting threshold this way _should_ work, but I have no way of implementing it.

> const float THRESHOLD[] = {
>         0.000151763f, 0.000173726f, 0.000261157f, 0.00033135f,
>         0.000392263f, 0.000447087f, 0.000497502f, 0.000544522f,
>         0.000588818f, 0.000630863f, 0.000671004f, 0.000709506f,
>         0.000746576f, 0.000782381f, 0.000817057f, 0.000850716f,
>         0.000883453f, 0.00091535f, 0.000946474f, 0.000976886f,
>         0.00100664f, 0.00103578f, 0.00106435f, 0.00109238f,
>         0.00111991f, 0.00114696f, 0.00117357f, 0.00119976f,
>         0.00122554f, 0.00125095f, 0.00127599f, 0.00130069f,
>         0.00132506f, 0.00134911f, 0.00137286f, 0.00139632f,
>         0.00141951f, 0.00144243f, 0.00146509f, 0.0014875f,
>         0.00150968f, 0.00153163f, 0.00155335f, 0.00157486f,
>         0.00159617f, 0.00161727f, 0.00163818f, 0.0016589f,
>         0.00167944f, 0.0016998f, 0.00171998f, 0.00174f,
>         0.00175986f, 0.00177956f, 0.00179911f, 0.0018185f,
>         0.00183775f, 0.00185686f, 0.00187582f, 0.00189465f,
>         0.00191335f, 0.00193192f, 0.00195037f, 0.00196869f,
>         0.00198688f, 0.00200497f, 0.00202293f, 0.00204078f,
>         0.00205853f, 0.00207616f, 0.00209369f, 0.00211111f,
>         0.00212843f, 0.00214565f, 0.00216278f, 0.00217981f,
>         0.00219674f, 0.00221358f, 0.00223033f, 0.00224699f,
>         0.00226356f, 0.00228005f, 0.00229645f, 0.00231277f,
>         0.00232901f, 0.00234517f, 0.00236125f, 0.00237725f,
>         0.00239317f, 0.00240902f, 0.0024248f, 0.0024405f,
>         0.00245613f, 0.00247169f, 0.00248718f, 0.00250261f,
>         0.00251796f, 0.00253325f, 0.00254847f, 0.00256363f,
>         0.00257873f, 0.00259376f, 0.00260873f, 0.00262364f,
>         0.00263849f, 0.00265328f, 0.00266801f, 0.00268268f,
>         0.0026973f, 0.00271186f, 0.00272636f, 0.00274081f,
>         0.00275521f, 0.00276955f, 0.00278384f, 0.00279808f,
>         0.00281226f, 0.0028264f, 0.00284048f, 0.00285452f,
>         0.0028685f, 0.00288244f, 0.00289633f, 0.00291017f,
>         0.00292397f, 0.00293772f, 0.00295142f, 0.00296508f,
>         0.00297869f, 0.00299226f, 0.00300579f, 0.00301927f,
>         0.00303271f, 0.00304611f, 0.00305947f, 0.00307278f,
>         0.00308605f, 0.00309928f, 0.00311248f, 0.00312563f,
>         0.00313874f, 0.00315182f, 0.00316485f, 0.00317785f,
>         0.00319081f, 0.00320373f, 0.00321662f, 0.00322947f,
>         0.00324228f, 0.00325506f, 0.0032678f, 0.0032805f,
>         0.00329317f, 0.00330581f, 0.00331841f, 0.00333098f,
>         0.00334351f, 0.00335601f, 0.00336848f, 0.00338091f,
>         0.00339331f, 0.00340568f, 0.00341802f, 0.00343032f,
>         0.0034426f, 0.00345484f, 0.00346705f, 0.00347924f,
>         0.00349139f, 0.00350351f, 0.0035156f, 0.00352766f,
>         0.00353969f, 0.0035517f, 0.00356367f, 0.00357562f,
>         0.00358754f, 0.00359942f, 0.00361129f, 0.00362312f,
>         0.00363493f, 0.0036467f, 0.00365846f, 0.00367018f,
>         0.00368188f, 0.00369355f, 0.0037052f, 0.00371682f,
>         0.00372841f, 0.00373998f, 0.00375152f, 0.00376304f,
>         0.00377453f, 0.003786f, 0.00379744f, 0.00380886f,
>         0.00382025f, 0.00383162f, 0.00384297f, 0.00385429f,
>         0.00386559f, 0.00387686f, 0.00388811f, 0.00389934f,
>         0.00391055f, 0.00392173f, 0.00393289f, 0.00394402f,
>         0.00395514f, 0.00396623f, 0.0039773f, 0.00398835f,
>         0.00399938f, 0.00401038f, 0.00402136f, 0.00403233f,
>         0.00404327f, 0.00405419f, 0.00406509f, 0.00407596f,
>         0.00408682f, 0.00409766f, 0.00410847f, 0.00411927f,
>         0.00413005f, 0.0041408f, 0.00415154f, 0.00416225f,
>         0.00417295f, 0.00418363f, 0.00419429f, 0.00420492f,
>         0.00421554f, 0.00422614f, 0.00423672f, 0.00424729f,
>         0.00425783f, 0.00426836f, 0.00427886f, 0.00428935f,
>         0.00429982f, 0.00431027f, 0.00432071f, 0.00433112f,
>         0.00434152f, 0.0043519f, 0.00436226f, 0.00437261f,
>         0.00438294f, 0.00439325f, 0.00440354f, 0.00441382f,
>         0.00442407f, 0.00443432f, 0.00444454f, 0.00445475f
> };

**Comment by anikom15** [comment]
The slider and INI defaults have been fixed.

**Comment by anikom15** [comment]
What would be the implications for using 16-bit or 32-bit floats for textures? I have implemented it and it eliminates burn-in (as far as I can see), but I have not tested it thoroughly yet.

**Comment by ImJezze** [comment]
This also was my next thought, to use D3DFMT_A16B16G16R16 for the cache_texture.

**Comment by ImJezze** [comment]
This is patch for your pull request changes the texture format of the cached texture to D3DFMT_A16B16G16R16F while keeping D3DFMT_A8B8G8R8 for all other textures.

[pull-1843-cached-texture-to-16-bit-floating-point.zip](https://github.com/mamedev/mame/files/684673/pull-1843-cached-texture-to-16-bit-floating-point.zip)

**Comment by ImJezze** [comment]
Great I'll merge it. I still have one question and one favor to ask. 
1. Can you explain the constant tau factors of phosphor and ghosting? Does their detailed accuracy have a significant origin or do they just transform the relative input range [0, 1] to the previously absolute input range?
2. Could you update docs/source/advanced/hlsl.rst and add the new settings with a small description?

**Comment by Lord-Nightmare** [comment]
Is there any chance you could port these changes over to BGFX instead of just the windows-specific HLSL backend?

**Comment by rb6502** [comment]
Just to be clear: I am going to revert these changes.  We DO NOT accept HLSL or GLSL changes that don't have corresponding BGFX changes anymore as a matter of policy.

**Comment by u-man74** [comment]
this matter of policy is a ridiculous joke then.

**Comment by anikom15** [comment]
Yeah I'm going to port these changes to BGFX, but I need to learn more about it first, so it'll probably take a while.

**Comment by rb6502** [comment]
Thanks!  I've suggested @ImJezze set up a branch where this is applied and you guys can work on the port, hopefully he can get that going.  (Kale works that way all the time and it seems to go well for him).

**Comment by u-man74** [comment]
@rb6502 : I dont see, what the policy has to do with your last comment. It was told, that BGFX ports are easy and that the existing HLSL will be ported in no matter of time. it seems this is not the case.
Dont get me wrong, as i am not against BGFX or the future plans in general, but this policy sounds a little to harsh for me and i didnt saw it anywhere announced. Maybe you should rethink that or make a official announcement, before more people come up with HLSL improvements and then being forced to do their work twice.

**Pull request merged**
