### PR TITLE
First batch of input port name updates

### PR DESCRIPTION
**Pull request by RalfVB**

### CODE REVIEW

**Comment by cuavas** [comment]
I really think this is the wrong direction. It's messy, bad for code reuse when multiple games have the same ports, and hard to localise. If you really want to do this, look at a way to externalise the names.

**Comment by RalfVB** [comment]
Yes, I'm inclined to agree. Defining the port names in an external file would be the optimal solution.
If somebody more experienced with MAME's source is willing to provide some help in how to cleanly implement this, I'd be happy to build the construct the file the names are read from.

**Comment by ajrhacker** [comment]
I've had the idea of creating selectable XML "overlay" files for the purpose of renaming inputs, analogous to the plastic overlay cards that many console games were distributed with. It's a bit low on my list of personal coding priorities, though.

**Comment by rb6502** [comment]
Closing this since issue #1640 now tracks it.

**Pull request closed without merging**
