### PR TITLE
toaplan2.cpp: Fix bbakraid music timing, Add hardware notes

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by cuavas** [comment]
Where did you get the numbers from?  Are the dividers just a guess based on music tempo, or is there some evidence that it’s a divider of 1200?

**Comment by cam900** [comment]
bbakraid PCB has 32MHz XTAL, and this XTAL driven both CPUs, and also sound IRQ timer.
music tempo is controlled by timer, it's divided from sound CPU clock.

**Comment by cuavas** [comment]
Can you show some evidence for the divider of 1200?  Where is this actually implemented on the board?

**Comment by cam900** [comment]
sound CPU clock / 12000(375 * 32); Z80 IRQ pin is connected to nearest CPLD,(SUB-TECK on PCB marking) and timer logic is programmed in this CPLD.(or through R071? needs more verification.)

**Comment by happppp** [comment]
This is fine, I think Vas's concern is that the comment seems to imply that this divider is accurate instead of an assumption

**Pull request merged**
