### PR TITLE
lwriter.cpp: Add support for the original LaserWriter.

### PR DESCRIPTION
**Pull request by jrmuizel**

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
Does this really belong in the same driver file?  Wasn’t the LaserWriter IInt a completely different chipset?  I would’ve thought the proper thing to do would be to devicify the print engine and have different drivers for the different mainboard architectures.  Also, these enumerations for models are only one step up from using `strcmp` on the system shortname – that’s definitely *not* what we want going forward.

**Comment by jrmuizel** [comment]
@cuavas, it looks like "LaserWriter" and "LaserWriter II NT" are very similar. Even with the print engine moved out there would be quite a bit of duplicated code. Is there some halfway solution that would allow sharing more of the code?

**Comment by happppp** [comment]
The differences don't look that large to me either.
Anyway, you can remove m_model easily if you add extra functions for the VIA hookups.

Add via_pa_lw_w, from there, do: via_pa_w(data); and m_cbsy = bool(data & 1);
Add via_pb_lw2nt_r, and assuming the only difference is an inverted bit, do: return via_pb_r() ^ 0x04;

**Comment by happppp** [comment]
Another suggestion: Can you remove "Apple" from the title string? Or is it really part of the machine title? And if the machine is called LaserWriter (no space), remove the space too.

Also, IMO lwriter2nt instead of lwriteriint would be a better choice for the romset name. Consider having to type them in on the cmdline, you'd rather have the more intuitive one.

**Comment by jrmuizel** [comment]
I've updated the PR to match @happppp's suggestions

**Comment by rb6502** [comment]
To address one comment Vas had, the Canon print engine will need to be split out into a separate device, but the LW/LW Plus/LW II NT are all close enough hardware not to require it yet.

**Pull request merged**
