### PR TITLE
GNU/kFreeBSD support

### PR DESCRIPTION
**Pull request by stevenc99**
Hi!

This series of patches fixes the current issues building mame on Debian GNU/kFreeBSD.  There were some assumptions in code that glibc (its headers and functions) is not available when building on a BSD platform.

Thanks!

### CODE REVIEW

**Comment by balr0g** [comment]
@stevenc99, thanks! Could you PR the bx changes [upstream](https://github.com/bkaradzic/bx)?

**Comment by cuavas** [comment]
After the changes does it still build on stock FreeBSD without the GNU environment?  For example the change to src/osd/modules/file/posixptty.cpp - is that define present on stock FreeBSD?

**Comment by stevenc99** [comment]
Hi @cuavas: stock FreeBSD already defines __FreeBSD_kernel__, but I did not test building on a FreeBSD machine with these changes (I don't have any suitable build environment to do it myself).

**Comment by jmallach** [comment]
Hi @cuavas! Yes, __FreeBSD_kernel__ is available on regular FreeBSD:

https://svnweb.freebsd.org/base/head/sys/sys/param.h?view=markup#l64

**Comment by jmallach** [comment]
This, of course, would fix #1044.

**Comment by stevenc99** [comment]
Sent a pull request to bx upstream https://github.com/bkaradzic/bx/pull/119

**Comment by stevenc99** [comment]
@balr0g: the bx parts are merged upstream.  Commit https://github.com/mamedev/mame/pull/1093/commits/ef8816ae18f9d607e0542f3ebe9789ae57fa04a5 pulled the relevant parts (but not all upstream changes) into this merge request.  Thanks.

**Pull request merged**
