### PR TITLE
ax208 disassembly improvements (nw)

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by happppp** [comment]
Could you get rid of the empty commit "(nw)" habit and do a quick summary instead? eg. "update note", "clarification", "fix typo"

**Comment by DavidHaywood** [comment]
I've tried, but then end up simply not committing because I can't think of anything to write, which is even less productive.

**Comment by MooglyGuy** [comment]
Are you literally saying that it wouldn't have occurred to you to describe 233fc45 as "clarified comments", 7f27c99 as "documented additional game rev", and 0f78dbb as "updated comment"?

**Comment by DavidHaywood** [comment]
I'm saying it's completely irrelevant as it's not worth a mention anyway.

**Pull request merged**
