### PR TITLE
3rdparty/linenoise: Support keypad Enter on Windows

### PR DESCRIPTION
**Pull request by vadosnaprimer**
restores d73b585d65936a5b9736e23cf85e543ef5bd2779

### CODE REVIEW

**Comment by cuavas** [comment]
Please send this upstream, or it will just be lost on the next update.

**Comment by vadosnaprimer** [comment]
I absolutely did, unless it's the wrong one https://github.com/msteveb/linenoise/pull/33

**Comment by simzy39** [comment]
I think the original is here https://github.com/antirez/linenoise

**Comment by vadosnaprimer** [comment]
https://github.com/mamedev/mame/blob/5898fb935318ad0aa08338979784bcb32fbe7419/3rdparty/linenoise/README.markdown?plain=1#L25

**Pull request merged**
