### PR TITLE
Mark all "Unknown sources" in PS1 SW list with baddump flags.

### PR DESCRIPTION
**Pull request by angelosa**
* Added extensive compatibility lists.

TBD: there are new SW additions, needs to be tracked back in the history cfr. #5433  or marked as [unknown]

### CODE REVIEW

**Comment by angelosa** [comment]
@cuavas about filename validation, any real reason about `&amp;` being considered as valid?

**Comment by cuavas** [comment]
This contains a new entry `bblade2j` – please put the credit for this in the PR description so it’s easy to find.  Also, there’s mixed space/tab indent with the addition, so please srcclean it.

**Comment by cuavas** [comment]
`coolboa2j` is another addition, and also has mixed spaces/tabs.

**Comment by cuavas** [comment]
Also `dungcr`, `dekirugc`, `gaiamast`, `gal3`, `garouwa`, `suikodenj`, `suikodn2j`, `gunbull`, `gunbarl`, `gunbalin`, `gunnm`, `gunparad`, `gunpey`, `hardedge`, `iqubej`, `jetdego`, `jojobaj`, `maghopp`, `mslugj`, `mslugxj`, `mjkiwap2`, `mk2j`, `paqa`, `rtypedj`, `rtypesj`, `rageracej`, `rcdegoj`, `rebus`, `ridgeracj`, `rockman`, `simcit2kj`, `sfexpaj`, `smashcr2j`, `soukobns`, `souledge`, `strider2j`, `tobal2`, `vagstoryj`, and `wildarmsj`.

`ar2_223`, `apescapee`, `acrels96`, `bm`, `cte`, `crashbshe`, `demo1_1`, `demo1_2`, `demo1_4g`, `monstincsw`, `draculae`, `driver2e`, `edemo21`, `edemo22`, `edemo28`, `edemo58`, `edemo60`, `edemo62`, `edemo63`, `edemo64`, `edemo65`, `edemo66`, `edemo67`, `edemo68`, `edemo69`, `edemo70`, `edemo71`, `edemo72`, `edemo73`, `edemo74`, `evryglf2`, `f2cs2ke`, `ffant8e`, `frontms3e`, `ghlpanic`, `gt1e`, `gt2e`, `gta2e`, `lemans24`, `mhonrunde`, `mgse`, `mgssm`, `micromc3e`, `motorcre`, `motorcwte`, `music`, `nfs2e`, `nfs3e`, `nofeare`, `abeodysse`, `ptblanked`, `ptblanke`, `ptblank2e`, `porschece`, `powrsrc`, `ppinbrue`, `rshot`, `revile`, `revil3e`, `revilsrve`, `silenthe`, `sphere360`, `spidermne`, `spyroe`, `spyro3e`, `strkskat2`, `tenchude`, `td6e`, `themehose`, `themepw`, `tocawtc`, `traid4e`, `urbchaose`, `vanishpte`, `warpathe` and `wcmayhme` seem to be additions from redump.org.

A lot of additions say they have LibCrypt protection that isn’t in the CHD – shouldn’t these be marked as unsupported by default?

**Comment by cuavas** [comment]
What’s the plan for being able to get rid of the bad dump flags?  Can the sources be identified?  Is your intention to only accept things from redump.org?

What are we going to do about LibCrypt modified Q subchannel data?  I really don’t like redump.org’s approach of storing it out-of-band in SBI files.  Can we deal with raw sector data in CHD, including the subchannels?

**Comment by cuavas** [comment]
> @cuavas about filename validation, any real reason about `&amp;` being considered as valid?

It’s used for csh job control, it’s problematic for scripts and interactive command line.

**Comment by angelosa** [comment]
I mean I'm not a fan of `&` inside filenames, ofc because they needs to be converted to `&amp;` in the first place.

**Comment by angelosa** [comment]
> What’s the plan for being able to get rid of the bad dump flags? Can the sources be identified? Is your intention to only accept things from redump.org?

From my experience there's no way we can obtain where these were sourced. I honestly won't drop a tear for them being substituted by redump.org dumps, several clearly have misplaced audio gaps or even worse sports dreadful bootleg logos instead of the official PS ones (at worst be effectively hacked Japanese discs to work on US BIOSes)

> What are we going to do about LibCrypt modified Q subchannel data? I really don’t like redump.org’s approach of storing it out-of-band in SBI files. Can we deal with raw sector data in CHD, including the subchannels?

Those certainly needs to be marked as baddump/`supported=no`, passed under my radar being outside contribution.

**Comment by angelosa** [comment]
Was in a rush, really wanted to fix validation from CI then checked how vscode cleans it from command palette. 
Honestly surprised that whitespaces aren't trimmed by default in diffs, I guess one can `git diff -w`.

**Comment by cuavas** [comment]
We still don't want the code churn in the file by having every line show as changed twice.

**Comment by angelosa** [comment]
Sure, do I just need to srcclean on latest or I necessarily need to `git reset` on `98b3804` then fix the validation and run it?

**Comment by cuavas** [comment]
Just run srcclean on what you’ve got now and commit to your branch – squashing at the end will flatten the history.

**Comment by DavidHaywood** [comment]
> What are we going to do about LibCrypt modified Q subchannel data? I really don’t like redump.org’s approach of storing it out-of-band in SBI files. Can we deal with raw sector data in CHD, including the subchannels?

I think the SBI files should be put in a region for these, at least for now (as it's strangely only on the redump.org site at the moment, and there's a risk of that going down at any given moment given some of the infighting there)  

At some point CHDMAN could be updated to accept them and generate sub-channel data that incorporates that data, at which point those CHDs could be replaced with ones with the data incorporated.

It's not ideal, in fact, it's kind of awful, as is cue/bin in the first place, but it's what we've been left to deal with.

**Comment by cuavas** [comment]
The latest changes backed out too much stuff.  I srcclean'd 98b38047ae0e6cafd10bd13f0cc2847916ad6ef2, marked the LibCrypt discs as unsupported, and removed the items marked as unknown source.  Someone should test the redump Euro dumps at some point.

**Comment by cuavas** [comment]
This now has the unknown source additions.  @angelosa and/or @FakeShemp can we get credits for these so we can finally put this to bed?

**Comment by angelosa** [comment]
> coolboa2j is another addition, and also has mixed spaces/tabs.
> 
> Also `dungcr`, `dekirugc`, `gaiamast`, `gal3`, `garouwa`, `suikodenj`, `suikodn2j`, `gunbull`, `gunbarl`, `gunbalin`, `gunnm`, `gunparad`, `gunpey`, `hardedge`, `iqubej`, `jetdego`, `jojobaj`, `maghopp`, `mslugj`, `mslugxj`, `mjkiwap2`, `mk2j`, `paqa`, `rtypedj`, `rtypesj`, `rageracej`, `rcdegoj`, `rebus`, `ridgeracj`, `rockman`, `simcit2kj`, `sfexpaj`, `smashcr2j`, `soukobns`, `souledge`, `strider2j`, `tobal2`, `vagstoryj`, and `wildarmsj`.
> 

[anonymous]

> `ar2_223`, `apescapee`, `acrels96`, `bm`, `cte`, `crashbshe`, `demo1_1`, `demo1_2`, `demo1_4g`, `monstincsw`, `draculae`, `driver2e`, `edemo21`, `edemo22`, `edemo28`, `edemo58`, `edemo60`, `edemo62`, `edemo63`, `edemo64`, `edemo65`, `edemo66`, `edemo67`, `edemo68`, `edemo69`, `edemo70`, `edemo71`, `edemo72`, `edemo73`, `edemo74`, `evryglf2`, `f2cs2ke`, `ffant8e`, `frontms3e`, `ghlpanic`, `gt1e`, `gt2e`, `gta2e`, `lemans24`, `mhonrunde`, `mgse`, `mgssm`, `micromc3e`, `motorcre`, `motorcwte`, `music`, `nfs2e`, `nfs3e`, `nofeare`, `abeodysse`, `ptblanked`, `ptblanke`, `ptblank2e`, `porschece`, `powrsrc`, `ppinbrue`, `rshot`, `revile`, `revil3e`, `revilsrve`, `silenthe`, `sphere360`, `spidermne`, `spyroe`, `spyro3e`, `strkskat2`, `tenchude`, `td6e`, `themehose`, `themepw`, `tocawtc`, `traid4e`, `urbchaose`, `vanishpte`, `warpathe` and `wcmayhme` seem to be additions from redump.org.
> 
> A lot of additions say they have LibCrypt protection that isn’t in the CHD – shouldn’t these be marked as unsupported by default?

@FakeShemp

**Comment by cuavas** [comment]
Really someone who wants to remain anonymous?  Not just poor record keeping?

**Comment by FakeShemp** [comment]
Yeah, I dumped some of these, but they are identical to redump, so might as well credit them.

**Comment by cuavas** [comment]
> Yeah, I dumped some of these, but they are identical to redump, so might as well credit them.

The redump ones are already added and credited.  It’s the other ones that got added along the way that I want proper credits for so they can be added.

**Comment by FakeShemp** [comment]
Those Japanese ones I have no idea where they came from :(

**Comment by angelosa** [comment]
> Really someone who wants to remain anonymous? Not just poor record keeping?

They are old pre-redump.org dumps, found them useful for one reason or another to have them into mainline. 
I have no idea who the dumpers are and ofc needs redumping anyway.,

**Comment by angelosa** [comment]
Is this safe to be closed and deleted by now?

**Comment by cuavas** [comment]
Well, we need to either:
* credit the Japanese additions properly and merge it
* not bother to merge the Japanese additions since they're all marked bad dump by default anyway and just close it
* replace them with more trustworthy dumps of the same software from redump or somewhere

Which is the least unpalatable option?

**Comment by happppp** [comment]
not specifically related to PSX dumps, [unknown] should be fine if you don't know the origin.

**Comment by angelosa** [comment]
Can't be bothered to leave this open.

**Pull request closed without merging**
