### PR TITLE
by35.cpp: Mark one 'blbeauty' ROM as BAD_DUMP (it's empty)

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
empty should really just be NO_DUMP, nothing of worth was dumped.

**Comment by Quench0** [comment]
I suggest the U2 ROM is *not* a bad dump.
It maps to $5000-$57FF. This Black Beauty game code never references that address space other than Sterns standard ROM checksum routine on startup which they probably forgot to change.
The blank U2 ROM is there so the ROM zero checksum test passes and serves no other purpose.

What should be changed is the date of release. Stern went bust in 1984, it couldn't have been released in 1988??? KLOV lists it as released in 1984.

**Comment by clawgrip** [comment]
Ahhh... Makes sense.
I'll close this PR then. Another one will be needed for checking the years and maybe adding a comment about this empty ROM.

Thanks a lot!!

**Comment by DavidHaywood** [comment]
Yeah, sometimes you get empty ROMs on prototypes too (or just because of how the data arrangement ended up, even House of the Dead 2 has an 'empty' ROM that Sega assigned a number to, but then usually didn't populate)

**Comment by happppp** [comment]
Here you go: https://github.com/mamedev/mame/commit/49958221235d5e34d9f7eb078f7ffe1457c35f5f

**Pull request closed without merging**
