### PR TITLE
Promote clubpacm, clubpacma, and clubpacmb to working. [Melissa Goad]

### PR DESCRIPTION
**Pull request by MoochMcGee**
These games appear to have been marked MACHINE_NOT_WORKING,
due to a fundamental misunderstanding of what the Double Command mode
is. As far as I could gather with MAME's debugger and the various inputs
the game takes, there is no multiplexing of Player 1's inputs, and given
the fact that Player 2's inputs work in 2 player mode, but not Double
Command mode, and the fact that when one pacman dies, the other does
too... I suspect Double Command just means "You command two players
simultaneously". Why anybody would want to play Pac-Man like this is
beyond me.

### CODE REVIEW

**Comment by Tafoid** [comment]
The original commit https://github.com/mamedev/mame/commit/efe001bdf07f7cfd7d1ec471e8449fff9645ba7f plainly states what is vaguely commented in the driver regarding it.  There is still missing functionality and it was decided by the person adding who had knowledge of the dump/pcb that it deserved a NOT_WORKING flag because of it.

Did you test any of these games at all other than observing the parent romset?  Both clones do not even boot and are not in a position to be changed at all.

I humbly suggest these should stay flagged the way they have been.  Disproving by ignoring is not a valid means of reversing flags.

**Comment by MoochMcGee** [comment]
Ah, sorry, I didn't even think that the clones might have additional hardware functionality, sorry :P

**Comment by DavidHaywood** [comment]
Fwiw I could never find a multiplexer on the controls, so I'm inclined to agree it probably is just some gimmick mode where you control both Pacmen.  That said I remember it glitching out quite a lot too.

**Comment by cuavas** [comment]
Leave this for someone who knows the game better.

**Pull request closed without merging**
