### PR TITLE
ui.cpp cleanup (nw)

### PR DESCRIPTION
**Pull request by ajrhacker**
- Create class ui::machine_info for holding calculated machine info and generating descriptive strings for the UI. This absorbs a number of unimportant core functions that existed only for the UI's convenience.
- Move natural keyboard processing down into the core UI input module (which it depended on).

### CODE REVIEW

**Comment by cuavas** [comment]
A #define macro inside a class declaration? Seriously? Please either move it out of the class declaration (since it isn't scoped) or turn it into a constexpr.

**Comment by cuavas** [comment]
In menu_game_info::populate you should std::move the temporary string to avoid introducing an unnecessary copy.

**Comment by cuavas** [comment]
Also why move the natural keyboard down a level at all? It's a (rather poorly implemented) feature of the internal front end and not a core emulation feature. I'd argue it should be kept even further away from the core, not moved in deeper.

**Comment by ajrhacker** [comment]
The reason for taking natural keyboard handling out of ui.cpp is not because the core needs access to it (the core barely accesses ui_input at all now) but to have it be with related input routines, not buried in a master module that handles too many unrelated things. The UI input module deserves a wholesale reimplementation anyway, but I'd rather leave that to a developer who knows a more efficient way for the OSD layer to communicate with the frontend.

**Comment by cuavas** [comment]
I'm closing this on the grounds that moving natural keyboard around without even attempting to fix its fundamental issues (e.g. having no chance of working reliably with LLE keyboards) is pointless, and if anything it should be moved further away from the core, not closer to it.

**Comment by ajrhacker** [comment]
I have no idea as to what "LLE keyboards" are supposed to be in MAME. I guess I'll just have to forget about fixing issues like MT #6340 now and continue work on areas further removed from the so-called "future of MAME" PC and handheld emulation projects.

**Comment by galibert** [comment]
Hey hey hey :-)

First, machine_info is a good idea.  Could you separate it?  Could you, in
fact, in general, try to do one thing per pull request?  With git it's
usually not hard to split changes, git add -p in particular is very nice. I
know it's work, but it's really, really useful when we're talking about
internals.

As for natural keyboard, I'm not sure where it belongs.  What about we talk
about it on the list?  That's why it's there.

  OG.

**Pull request closed without merging**
