### PR TITLE
playmark.cpp: Use bin format instead of hex for PIC dumps

### PR DESCRIPTION
**Pull request by clawgrip**
Removed the in-driver functions for converting hex to bin.
Also converted the JEDECs to bin and move empty dumps from BAD_DUMP to NO_DUMP for 'hotmind'

### CODE REVIEW

**Comment by Quench0** [comment]
The HEX dumps of the PIC chips contains configuration info about how the PIC operates. Those configuration bits are lost in the binary version. I don't think it's a good idea throwing away that important info.

**Comment by cuavas** [comment]
The PIC device needs a better way to set the configuration word.  Currently it has to be set with `set_config`.  There should be a way for it to be loaded from the ROM data.  That said, we should move away from using Intel HEX as it’s a format where there are many representations for the same data.  Also, the HEX parser in this driver is pretty dreadful, making a lot of assumptions about how the input is formatted.

**Comment by Quench0** [comment]
> That said, we should move away from using Intel HEX as it’s a format where there are many representations for the same data.

The HEX parser in this file is specific to the HEX dumps it loads that have existed for about 20 years.
What file format are you proposing that's supported by all universal programmers that will maintain the configuration words? The Elnec universal programmers do not support PIC configuration words in binary files, the EE-Tools programmers don't even support binary files for PICs. These are not toy programmers bought off AliExpress. HEX format is the default in all the universal programmers I have supporting PICs.

**Comment by cuavas** [comment]
> What file format are you proposing that's supported by all universal programmers that will maintain the configuration words?

The “binary fusemap” format used for programmable logic chips in MAME isn’t supported by *any* programmers – it always needs to be transformed to JEDEC format before it can be written to a chip.  However we use it because the JEDEC format is too flexible so to speak, which means there are many possible representations of the same fusemap.

I’m not sure exactly what to do about it, but relying on driver init functions like this sure isn’t the “MAME way”, particularly relying on a parser as full of holes as this.

**Comment by cuavas** [comment]
It would be natural if the data EPROM content (if any) were in a separate region to the program.  Perhaps the PIC CPU should be able to load the config word from a separate ROM region?  It’s annoying when CPUs have a multitude of separate programmable areas.

**Comment by Quench0** [comment]
> The “binary fusemap” format used for programmable logic chips in MAME isn’t supported by _any_ programmers

That doesn't make it right. I've helped people in the past program PALs from MAMEs binary fusemaps that had no clue how to get them working with their programmers.

HEX format is standard for PICs. If/when later PIC cores get added for chips that have 10, 20, 50 config bits and HEX dumps come in, are these config words going to be stripped because they don't suit the 'MAME way' for the file format?

The User ID: "0794" in Caps0ff's dump very much looks like a date code considering the game was released in 1994. That info's now been stripped from the binary.

**Comment by smf-** [comment]
On 07/07/2022 18:07, Quench wrote:

> That doesn't make it right. I've helped people in the past program
> PALs from MAMEs binary fusemaps that had no clue how to get them
> working with their programmers.

Yes, we'd have been better off having a jed sanitiser than storing a
binary blob.

We presumably can cope with loading all the types of jed files, or
jedutil wouldn't work anyway.

My understanding is that it's more about being able to "dump from your
own chip and have it match MAME".

We should be able to improve the code situation, rather than go down
another preservation dead end.

**Comment by cuavas** [comment]
I’m not saying we shouldn’t preserve the configuration bits.  I’m saying we need a better way of supplying it than calling a function from a driver init function.

The point of the binary fusemap format is that it has a single representation for any given fusemap.  This isn’t true for the JEDEC format, which has a free-form comment area, the poorly-defined and deprecated D field, the optional Q fields, alternative hex and binary fuse list fields, the possibility of multiple fuse list which may be discontiguous if a default state field is present, and a bunch of other optional fields (e.g. the fields for test vectors).

Using a format that doesn’t have a single representation for given content breaks `-romident`.

I’m not sure trying to force particular formatting onto JEDEC files and treating that as canonical solves the problems without creating new ones:
* You’d still need to run the dumped JEDEC file through some kind of converter to produce the “canonicalised form”.
* It wouldn’t obvious when a file is in the “canonicalised form”.
* For systems that actually use the PLD contents for emulation, it could lead to confusion if a user attempts to replace the contents and isn’t aware they need to “canonicalise” it so the length matches.

But while we’re complaining about the binary fusemap format, I believe it has a serious omission in that it can’t represent security fuses (JEDEC G field), user data fuses (JEDEC U field), or feature fuses (JEDEC E field).

**Comment by cuavas** [comment]
Getting back to the topic of PIC microcontrollers specifically, for the deprotected PIC16C57 dumps, we have apparently good dumps of the programs and user IDs, but definitely bad dumps of the configuration words as they’re necessarily erased to deprotect the devices.  If they’re treated as separate “ROMs”, we can accurately represent that the dump of one of the three areas is bad.

**Comment by Quench0** [comment]
> Yes, we'd have been better off having a jed sanitiser than storing a binary blob.

You read my mind. My use of JEDUTIL has produced fine sanitised results.


> I’m not sure trying to force particular formatting onto JEDEC files and treating that as canonical solves the problems without creating new ones:

Respectfully, I'm sure you know the three points you mentioned are hardly worse than now.
But this ship has long sailed.

> Getting back to the topic of PIC microcontrollers specifically

Look up Microchips document "DS30190".
It confirms the locations in CapsOff's dump had the user IDs and configuration word at the correct address in the PIC16x57 memory map but note these locations are beyond the user memory space. The current driver HEX parser most certainly doesn't respect this since it wasn't known. I guess honoring it can eliminate "set_config" since the configuration word can be read on reset.

**Comment by smf-** [comment]
If we sanitise all jed files before being adding to mame, then -romident
can sanitise any jed files on the fly & then it would be able to
identify them.

We could also sanitise them while loading normally and report a warning
if they weren't sanitised, which would hopefully mean they were always
sanitised first.

**Comment by cuavas** [comment]
> Respectfully, I'm sure you know the three points you mentioned are hardly worse than now.

Right now you can at least easily tell when something is in binary fusemap format versus JEDEC format.  It would be far less obvious if something was in a MAME-defined canonical JEDEC form or not.

> It confirms the locations in CapsOff's dump had the user IDs and configuration word at the correct address in the PIC16x57 memory map but note these locations are beyond the user memory space. The current driver HEX parser most certainly doesn't respect this since it wasn't known. I guess honoring it can eliminate "set_config" since the configuration word can be read on reset.

Yeah, but the configuration word in the dumps is in its erased state – it’s useless.  Using a single file combining separate areas when we can have good dumps of some but not others means you can’t flag *which parts* are bad.

Maybe treating it as a single region and loading the different parts at the addresses that would be used in a HEX file is an OK solution (although the actual addresses vary by device family).  It’s going to get increasingly complicated for Flash-based devices, particularly the ones with program memory writeback (e.g. PIC16F877) – those ones need to treat the “ROM” like default NVRAM contents.

>If we sanitise all jed files before being adding to mame, then -romident can sanitise any jed files on the fly & then it would be able to identify them.
>
> We could also sanitise them while loading normally and report a warning if they weren't sanitised, which would hopefully mean they were always sanitised first.

That would require a disruptive change no matter how you try to do it.  Making ROM loading behaviour depend on file name extensions would be a big change since we’ve always used it for PCB location identifiers.  You’d need to ensure any extension doesn’t conflict with one that has special handling.  Adding more special load commands (like the one for CHD-like images) would complicate ROM loading and everything that depends on it.

**Pull request closed without merging**
