### PR TITLE
liberatr: fully disentangle from atarigen, fix typo

### PR DESCRIPTION
**Pull request by ajrhacker**

### CODE REVIEW

**Comment by happppp** [comment]
fine by me if the device is only like this in liberatr

**Comment by ajrhacker** [comment]
liberatr seems to use basically nothing from atarigen but the EAROM interface, and it's the only driver to use it now. (liberatr_state::update_interrupts is just a dummy callback for a feature it doesn't use at all.)

**Comment by Lord-Nightmare** [comment]
The liberatr earom interface is the 'new' one Aaron Giles wrote a while back. (src/devices/machine/er2055.cpp)
Recently (and not realizing Aaron had rewritten it) I rewrote the 'old' earom interface (src/mame/machine/atari_vg.cpp)

Both of these files effectively do the same thing, there are some advantages and disadvantages to each (atari_vg.cpp keeps track of the device bus state, while er2055.cpp uses separate input lines for the 5 control bits so it doesn't require a hack to make the two different wirings atari used work both at once)

Note: Neither of the ER2055 emulations above 'correctly' emulate the earom erased status. The real way the chip works is it stores two bits per bit of stored data, A and B; If A=0 and B=1, the bit reads as 0; if A=1 and B=0, the bit reads as 1. If A=B=0 or A=B=1 the bit reads randomly. Erasing a location sets both A and B bits to 0 (I think, I might have the polarity backwards). Programming a location sets one of the bits to 1, depending on the value programmed. Programming a location twice without erasing in between can set both A and B bits to 1.
Neither of the two emulation cores respect this, though it would be fairly easy to implement.

**Comment by rb6502** [comment]
LN: are you planning to sort out the ER2055 situation soon, or can we apply this?

**Comment by ajrhacker** [comment]
These two ER2055 implementations should ultimately be merged. But seeing as the merger would need extensive testing to safeguard against regressions, I think it would be better for now to keep them separate both from each other and from atarigen_state (which some other things, particularly the slapstic handling, really ought to be divorced from as well).

**Comment by rb6502** [comment]
AJR: since LN seems to have died, could you re-submit this against current?

**Comment by Lord-Nightmare** [comment]
LN isn't dead, he's working on other things, sorry.
We can merge this in and fix the duplicated er2055 stuff later. Both implementations happen to work fine.
If you'd like you can move the "atarigen" implementation to er2055alt.cpp in same directory as er2055.cpp or something and add a comment that it is a redundant implementation and needs to be merged with the other one.

**Pull request merged**
