### PR TITLE
wecleman.cpp Updates

### PR DESCRIPTION
**Pull request by cam900**
wecleman.cpp : Add notes, Minor cleanup, replace gfx* -> saner ROM areas
Add stereo output for both wecleman and hotchase Because real hardware has stereo sound output with seperated sound board
Add enum for m_gameid, m_sound_hw_type

### CODE REVIEW

**Comment by jsjyqz** [comment]
cam900,nice work,hope someday we can fully emulate the ES5510 cpu core and the taito_en sound device

**Comment by cuavas** [comment]
@jsjyqz your behaviour is starting to look like stalking.  If you don't stop harassing contributors to the MAME project, you will be banned from commenting here.

**Comment by jsjyqz** [comment]
@cuavas i'm sorry for my comments here，i'm keep silent here from now on😔

**Comment by rb6502** [comment]
Also, the ES5510 does work fine in 99% of cases.  I asked the original author to double-check cam900's changes and he said the sd132 (VF-X SD, 32 voice) driver still A/Bs favorably with real hardware.

**Pull request merged**
