### PR TITLE
Added "bad dump" status on cracked games

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Added "bad dump" status on cracked games:
aplepanc, bigtop, bublbobl, centipedc, decathln, digger, dkong, dunzhina, jbird, kingqst2, kult, marble, mpatrol, msadventcr, mspacmanc, mulecr, pinball, pirates, platoon, prehist, serptine

### CODE REVIEW

**Comment by DavidHaywood** [comment]
they're not bad dumps, they're cracked games...  cracked games are legitimate alternatives.

**Comment by rb6502** [comment]
Yeah, cracks are not bad dumps.

**Comment by ArcadeShadow** [comment]
I won't argue that.
Then I think it should be better, the creation of a System Software List for the ibm5150 cracked software. 
Like the "Apple II cleanly cracked 5.25" disks", for instance...
Just my opinion...

**Comment by rb6502** [comment]
If there's sufficient trusted-good originals to make that distinction then yes, a separate software list for cracks would be great.  The Apple II originally only had one list until the .WOZ flood of originals started.

**Pull request closed without merging**
