### PR TITLE
[spectrum_cass.xml] Added 56 type-in programs from MicroHobby

### PR DESCRIPTION
**Pull request by ICEknigh7**
- Balalín (type-in, MicroHobby issue 125) [Ignacio Prini]
- Magnus Zone (type-in, MicroHobby issue 126) [Ignacio Prini]
- Oráculo Egipcio (type-in, MicroHobby issue 127) [Ignacio Prini]
- Demolition (type-in, MicroHobby issue 128) [Ignacio Prini]
- Basket Trainer (type-in, MicroHobby issue 129) [Ignacio Prini]
- Galaxy Fun (type-in, MicroHobby issue 130) [Ignacio Prini]
- Micro Draw (type-in, MicroHobby issues 131, 132) [Ignacio Prini]
- El Alambrista (type-in, MicroHobby issue 133) [Ignacio Prini]
- Ranamirez (type-in, MicroHobby issue 134) [Ignacio Prini]
- Fórmula Suicida (type-in, MicroHobby issue 135) [Ignacio Prini]
- Phantasmas (type-in, MicroHobby issue 136) [Ignacio Prini]
- Dardos (type-in, MicroHobby issue 137) [Ignacio Prini]
- S.E.M.I.S.I.S. (type-in, MicroHobby issues 138, 139) [Ignacio Prini]
- Alley's Gun (type-in, MicroHobby issue 140) [Ignacio Prini]
- Kleingeld (type-in, MicroHobby issues 141, 142) [Ignacio Prini]
- Caribe’s Day (type-in, MicroHobby issue 143) [Ignacio Prini]
- Rally (type-in, MicroHobby issue 144) [Ignacio Prini]
- La Profecía (type-in, MicroHobby issue 145) [Ignacio Prini]
- Mine Alert (type-in, MicroHobby issues 146, 147) [Ignacio Prini]
- Freddy (type-in, MicroHobby issue 148) [Ignacio Prini]
- Russian's Attack (type-in, MicroHobby issues 149, 150) [Ignacio Prini]
- En Ruta (type-in, MicroHobby issue 151) [Ignacio Prini]
- Zinco (type-in, MicroHobby issue 152) [Ignacio Prini]
- Ruffo’s Dream (type-in, MicroHobby issue 153) [Ignacio Prini]
- Crozet (type-in, MicroHobby issue 154) [Ignacio Prini]
- Rock Animation (type-in, MicroHobby issue 155) [Ignacio Prini]
- Bunker (type-in, MicroHobby issue 156) [Ignacio Prini]
- Telepuzzle (type-in, MicroHobby issue 157) [Ignacio Prini]
- Golfo Pérsico (type-in, MicroHobby issue 158) [Ignacio Prini]
- Mad Drivers (type-in, MicroHobby issue 159) [Ignacio Prini]
- Bowling Star (type-in, MicroHobby issue 160) [Ignacio Prini]
- Gas-Car (type-in, MicroHobby issue 161) [Ignacio Prini]
- Ghost Like (type-in, MicroHobby issue 162) [Ignacio Prini]
- Sky Invaders (type-in, MicroHobby issue 163) [Ignacio Prini]
- Perico Jones (type-in, MicroHobby issue 164) [Ignacio Prini]
- Brad Zotes (type-in, MicroHobby issue 165) [Ignacio Prini]
- Striker (type-in, MicroHobby issue 166) [Ignacio Prini]
- Indy (type-in, MicroHobby issue 167) [Ignacio Prini]
- Topin (type-in, MicroHobby issue 168) [Ignacio Prini]
- Starlike (type-in, MicroHobby issue 169) [Ignacio Prini]
- Tres en Raya (type-in, MicroHobby issue 170) [Ignacio Prini]
- Goteras (type-in, MicroHobby issue 171) [Ignacio Prini]
- Parvision (type-in, MicroHobby issue 172) [Ignacio Prini]
- Furax (type-in, MicroHobby issue 173) [Ignacio Prini]
- Duck Shooting (type-in, MicroHobby issue 174) [Ignacio Prini]
- Nomen Rosae (type-in, MicroHobby issue 175) [Ignacio Prini]
- PunkyMan (type-in, MicroHobby issue 176) [Ignacio Prini]
- El Retorno del Yedi (type-in, MicroHobby issue 177) [Ignacio Prini]
- Sky Warrior (type-in, MicroHobby issue 178) [Ignacio Prini]
- Reptkon (type-in, MicroHobby issue 179) [Ignacio Prini]
- Intro (type-in, MicroHobby issue 180) [Ignacio Prini]
- Keops (type-in, MicroHobby issue 181) [Ignacio Prini]
- Sir Gawain (type-in, MicroHobby issue 182) [Ignacio Prini]
- Snake (type-in, MicroHobby issue 183) [Ignacio Prini]
- Microbowl (type-in, MicroHobby issue 184) [Ignacio Prini]
- God Save the Punk (type-in, MicroHobby issue 185) [Ignacio Prini]

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
You can use `author` info to provide the author in a way that the internal UI will display.

**Comment by ICEknigh7** [comment]
Added author tags here: https://github.com/mamedev/mame/pull/9934

Is there a place where all valid softlist tags can be consulted?

**Comment by cuavas** [comment]
Well, you can see the ones that the built-in UI specifically recognises and potentially displays localised labels for here: https://github.com/mamedev/mame/blob/mame0244/src/frontend/mame/ui/utils.cpp#L62

You can put other values as well if there’s a good reason to within the schema of your software list.

**Comment by ICEknigh7** [comment]
Also, what's the difference between the Publisher tag and the info tag "distributor"?

**Comment by cuavas** [comment]
Consider Cyberpunk 2077:
* The developer is the studio CD Projeckt Red (a subsidiary of CD Project S.A.)
* The publisher is the the company CD Project S.A.
* There are multiple distributors, for example:
  * Online distribution is handled by GOG.com (another subsidiary of CD Project S.A.)
  * The North American retail distributor is Warner Brothers Interactive Entertainment

Words have meanings, yo

**Comment by ICEknigh7** [comment]
> Words have meanings, yo

What the... I'm definitely taking a vacation from these.

**Pull request merged**
