### PR TITLE
Allow load/save state slots to be bound to joystick buttons

### PR DESCRIPTION
**Pull request by vasilvv**
Also fixes some bugs without which this feature ends up not very useful.

### CODE REVIEW

**Comment by happppp** [comment]
What are you trying to fix, can you be more verbose? The added code is
hacky IMO.

**Comment by vasilvv** [comment]
Bug 1 fixed in this PR, steps to reproduce:
1. Bind "save state" to Z
2. Press Z.
3. Now whenever you press Z, it will just save it to state Z instead of letting you pick one.  This is not triggered reliably, but it does occasionally happen.

Bug 2 fixed in this PR, steps to reproduce:
1. Bind "pause" to P.
2. Try saving a state to P.  It will save it to P, and subsequently pause the game.
That does not seem horrible, but if the key in question is, say, "throttle", the results are much worse.

The added code is somewhat hacky (despite my best effort to make it not so), but the situation here is complicated because there are two input mechanisms involved (UI input for remappable keys and raw input for save state name), and only one of them actually keeps track of whether the button press has been already handled.  I've thought for quite a while about how to solve that issue, and this is the best I could come up with.

**Comment by etabeta78** [comment]
On Tue, Feb 2, 2016 at 11:56 PM, Victor Vasiliev <notifications@github.com>
wrote:

> Bug 2 fixed in this PR, steps to reproduce:
>
> 1. Bind "pause" to P.
> 2. Try saving a state to P. It will save it to P, and subsequently pause
> the game.
> That does not seem horrible, but if the key in question is, say,
> "throttle", the results are much worse.
>
> I believe this is the intended behavior: you shall not bind Save State to
another UI key.
If you add a special case handling for save states one wonders why there
shouldn't be other special cases for all conflicts, etc.

  my 2c
    f.

**Comment by cuavas** [comment]
@etabeta78 I think you're missing the point. It's not about binding the Save State function to the same key as another UI function.  It's about using a key to select a save state slot that happens to be bound to another function.  For example you have Save State bound to some Fkey, but you try to use slot P which happens to be bound to pause or slot 5 that happens to be bound to coin 1.

Other functions don't have this issue because they don't accept a second keystroke for slot selection.  I'm not sure this code should be accepted as-is, but it's a real issue that is specific to save/load state.

**Comment by vasilvv** [comment]
>  I believe this is the intended behavior: you shall not bind Save State to
another UI key. If you add a special case handling for save states one wonders why there
shouldn't be other special cases for all conflicts, etc.

Other cases do not require special handling because they read all inputs they receive via `ui_input_manager`, and it handles those cases for them.  Save state UI has to read keyboard directly because it wants raw input (`ui_input_manager` only handles mapped keys as I understand it);  this naturally means that `ui_input_manager` does not know about save state UI already having handled the input.

**Comment by etabeta78** [comment]
yeah, I had missed that the problem was in the choice of the save slot and
not in the mapping of the save state function.
then it is definitely not the intended behavior.

thanks for clarifying that point.

    f.

**Comment by rb6502** [comment]
Agree that this is a real bug and should be fixed, and beyond Vas' uninitialized variable I don't see any real problems with the code.  Hap, could you clarify what you didn't like?

**Comment by happppp** [comment]
No, let's just accept the pull req. I can have a try at cleaning it up
later.

**Pull request merged**
