### PR TITLE
New working clones

### PR DESCRIPTION
**Pull request by clawgrip**
------------------
Karate Dou (Arfyc bootleg) [Retromaniacs, ArcadeHacker, Recreativas.org]

### CODE REVIEW

**Comment by happppp** [comment]
No need for that common mcfg.
In the bootleg mcfg, you can simply do something like:

kchamp(config);

m_maincpu->set_clock(x);
m_ay[0]->set_clock(x); 
m_ay[1]->set_clock(x);

**Comment by clawgrip** [comment]
Ahhh, good to know, thanks!!

Later tonight I'll close this one and open another one, much simpler as you're saying.

Best regards.

**Comment by happppp** [comment]
PR doesn't have to be closed. You can do new commits on top of PRs (look it up on google if you don't know how :) )

**Comment by clawgrip** [comment]
Yes, thanks! I like to close the PRs when I need to revert lot of changes, to make a cleaner one!

**Comment by happppp** [comment]
It's ok: even if you did 20 new commits to correct or add new things (see Haze for example), it's no problem. The commits are squashed and show up as a single commit on the master branch.

**Comment by clawgrip** [comment]
Thanks again! I'd say it's OK now

**Comment by happppp** [comment]
good!

**Pull request merged**
