### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
----------
Game & Watch: Spitball Sparky [algestam, Mr Jiggles the Christmas Man]

### CODE REVIEW

**Comment by happppp** [comment]
Can you make the height 1080? MAME doesn't anti-alias SVG screens when resizing them to fit the OSD window, LCD segment edges will look bad if they're resized too much.

**Comment by happppp** [comment]
Oh, and while you're editing this file, can you add hydef to the thanks-to list? =)

**Comment by algestam** [comment]
Definitely! I'll prepare an update :)

**Comment by happppp** [comment]
Ok great

**Pull request merged**
