### PR TITLE
pc_lpt: fix status ack

### PR DESCRIPTION
**Pull request by goldnchild**

### CODE REVIEW

**Comment by goldnchild** [comment]
sorry I don't know what I'm doing, any hints?

**Comment by cuavas** [comment]
I don’t see how this can possibly be right.  All the documentation for the IBM implementation of the Centronics printer interface says that only bit 7 of the status input port (BUSY) is inverted.  It can’t be that all the documentation is wrong.

(Three bits of the control output port are inverted, but that’s immaterial here.)

**Comment by goldnchild** [comment]
I was looking at this book
on page 1201 this says that printer ack is (ack if zero).

https://www.plantation-productions.com/Webster/www.artofasm.com/DOS/pdf/ch21.pdf

**Comment by rb6502** [comment]
Centronics ACK is actually /ACK (inverted logic).

**Comment by cuavas** [comment]
Yeah, MAME uses 0 for low voltage, 1 for high voltage on the Centronics lines (i.e. not 1 for logically asserted).

**Comment by goldnchild** [comment]
In looking at https://en.wikipedia.org/wiki/Parallel_port  I see that 
only the MSB is inverted...

Base+1 (Status port) | Pin: | ~11 | 10 | 12 | 13 | 15 |  

now I feel silly...

**Comment by goldnchild** [comment]
Maybe the problem lies in the ap2000's e05a30 device since it's treating ack as positive?

void e05a30_device::device_reset()
{
 ...

        m_write_centronics_ack   (!m_centronics_nack);
        m_write_centronics_busy  ( m_centronics_busy);
        m_write_centronics_perror(false);
        m_write_centronics_fault (true);
        m_write_centronics_select(true);

**Pull request closed without merging**
