### PR TITLE
gba.xml: Added 21 prototypes.

### PR DESCRIPTION
**Pull request by FoxhackDN**
New working software list items
-------------------------------
AGB Aging Cartridge (World, version 1.0) [SmellyGhost, Forest of Illusion]
AGB Aging Cartridge (World, version 9.0) [Suicune41, Forest of Illusion]
Aero the Acro-Bat - Rascal Rival Revenge (Europe, prototype earlier) [LongwoodGeek, Forest of Illusion]
Chokkan Hitofude Advance (Japan, prototype) [xprism, Forest of Illusion]
Commandos 2 (USA, prototype) [DillyDylan, Forest of Illusion]
Dark Eden (prototype) [Ian Dunlop, Forest of Illusion]
Demon's Crest (prototype) [Ian Dunlop, Forest of Illusion]
Manic Miner (Europe, 20030307) [March42, Forest of Illusion]
Mario Kart XXL (demo, 20040417) [Forest of Illusion]
R3D-Demo V1 (demo) [Forest of Illusion]
Racing Gears Advance (USA, prototype, 20030922) [XBrav, Forest of Illusion]
Sea Boy (prototype) [Ian Dunlop, Forest of Illusion]
Star Wars Trilogy - Apprentice of the Force (USA, prototype) [Rezrospect, Forest of Illusion]
The Holy Bible - World English Bible (USA, prototype) [Gonz, Forest of Illusion]
Ultimate Muscle - The Kinnikuman Legacy - The Path of the Superhero (USA, prototype, 20030429) [Zach Lambert, Forest of Illusion]
Uridium Advance (Europe, prototype, 20030307) [March42, Forest of Illusion]

New software list items marked not working
------------------------------------------
The King of Fighters EX2 - Howling Blood (USA, prototype, 20030403) [March42, Forest of Illusion]
Quake (demo) [Randy Linden, Forest of Illusion]
Paradroid (Europe, prototype, 20030320) [March42, Forest of Illusion]
Uridium Advance (Europe, prototype, 20020911) [March42, Forest of Illusion]
Uridium Advance and Paradroid 2 in 1 (Europe, prototype, 20030430) [March42, Forest of Illusion]

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
Please don’t add dumper names in the software lists like this.  It sets a bad precedent, and will lead to more attempts at grandstanding/self-promotion.

**Comment by FoxhackDN** [comment]
> Please don’t add dumper names in the software lists like this. It sets a bad precedent, and will lead to more attempts at grandstanding/self-promotion.

You mean the submission comments, or the actual xml? I was told to credit everyone involved in the dump, and I've seen people be credited in the list, so I added all of them.

**Comment by cuavas** [comment]
> > Please don’t add dumper names in the software lists like this. It sets a bad precedent, and will lead to more attempts at grandstanding/self-promotion.
> 
> You mean the submission comments, or the actual xml? I was told to credit everyone involved in the dump, and I've seen people be credited in the list, so I added all of them.

The commit message and/or PR description should credit dumpers, not in comments in the software list itself.  (The person merging the PR should ensure the credits are in the commit message for the squashed commit.)

**Comment by FoxhackDN** [comment]
> > > Please don’t add dumper names in the software lists like this. It sets a bad precedent, and will lead to more attempts at grandstanding/self-promotion.
> > 
> > 
> > You mean the submission comments, or the actual xml? I was told to credit everyone involved in the dump, and I've seen people be credited in the list, so I added all of them.
> 
> The commit message and/or PR description should credit dumpers, not in comments in the software list itself. (The person merging the PR should ensure the credits are in the commit message for the squashed commit.)

Allright, sorry for the confusion. I'll submit an update to correct this in a few hours.

**Comment by cuavas** [comment]
No problem.

**Comment by ICEknigh7** [comment]
Should the dump credits in other softlists be removed? Some like spectrum_cass feature many dump providers mentioned in the comments.

**Comment by cuavas** [comment]
> Should the dump credits in other softlists be removed? Some like `spectrum_cass` feature many dump providers mentioned in the comments.

Unless there’s a very good reason for noting the origin of a dump, it shouldn’t be listed.  They should be removed if there isn’t a good reason to keep them.  (Often converted dumps list the source files, e.g. the CD cuesheet and data files a CHD was generated from, in case it needs to be re-converted in the future.)

**Comment by ICEknigh7** [comment]
Ok, so perhaps it would be a good idea to define the line between "good enough reason" and "not good enough", cause there's a lot of names there.

**Comment by cuavas** [comment]
Rule of thumb: if it’s just a dump credit, there’s definitely no reason to keep it.

**Comment by FoxhackDN** [comment]
> No problem.

I made the changes you requested, but it looks like something on my end got screwed up when trying to amend this commit. So I'll be resubmitting this. Sorry.

**Pull request closed without merging**
