### PR TITLE
tilemap.cpp : Support drawing gfx with offsets in tilemap

### PR DESCRIPTION
**Pull request by cam900**
(ex: cps1 or similar hardwares, Left half and right half of 16x8 gfxs are can be drawn independently)

### CODE REVIEW

**Comment by galibert** [comment]
I want serious tests to be sure adding a method call and a modulo in the
middle of the tightest loop of tile_draw does not slow down things.
Tilemaps are critical.

  OG.

**Comment by cam900** [comment]
There's result : https://youtu.be/IKDYjEnN4Bs

**Comment by happppp** [comment]
Action Hollywood is a driver that tests your added tilemap core feature. What OG means is, are the other majority of games that use the tilemap system negatively affected? If so, then this implementation can remain driver-side as it is now.

**Comment by cam900** [comment]
I can't find any negatively affection in my test now, and video is results of speed differences when this PR is applied.

**Comment by qeeg** [comment]
You could probably just try pacman, play a few levels and report the average speed difference :/

**Comment by galibert** [comment]
Well, you didn't find slowdowns from the 16-bits indexes in tiles either,
yet neogeo took a 20% hit...

Tilemap-heavy drivers... could you try gokuparo, raiden2 and radiant
silvergun please?

  OG.

**Comment by cam900** [comment]
radiant silvergun driver (stv.cpp, saturn.cpp) currently doesn't use emu/tilemap.cpp for emulation, so performance issue hasn't found. (see src/devices/video/stvvdp2.cpp notes and includes/saturn.h)
Except that, I will update for remains later.

**Comment by galibert** [comment]
You're entirely correct, I was remembering an older implementation.

  OG.

**Comment by cuavas** [comment]
I’m not really sure this is a huge benefit even for CPS1.  Does it really simplify the code that much?  Does this make things possible that were impossible before?  It will increase the footprint and cache load of the tile info members though.

**Comment by cam900** [comment]
mame 0.219
rungun2 -bench 90
Average speed: 235.91% (89 seconds)
Average speed: 235.56% (89 seconds)
Average speed: 242.06% (89 seconds)

fantjour -bench 90
Average speed: 211.01% (89 seconds)
Average speed: 214.41% (89 seconds)
Average speed: 218.23% (89 seconds)

raiden2 -bench 90
Average speed: 552.32% (89 seconds).
Average speed: 553.42% (89 seconds)
Average speed: 565.02% (89 seconds)

tilemap_split with modulo
rungun2 -bench 90
Average speed: 218.27% (89 seconds)
Average speed: 213.45% (89 seconds)
Average speed: 209.75% (89 seconds)

fantjour -bench 90
Average speed: 197.68% (89 seconds)
Average speed: 218.27% (89 seconds)
Average speed: 219.52% (89 seconds)

raiden2 -bench 90
Average speed: 432.91% (89 seconds)
Average speed: 428.61% (89 seconds)
Average speed: 418.06% (89 seconds)

tilemap_split without modulo
rungun2 -bench 90
Average speed: 236.55% (89 seconds)
Average speed: 233.26% (89 seconds)
Average speed: 239.19% (89 seconds)

fantjour -bench 90
Average speed: 220.07% (89 seconds)
Average speed: 215.02% (89 seconds)
Average speed: 215.42% (89 seconds)

raiden2 -bench 90
Average speed: 553.90% (89 seconds)
Average speed: 552.60% (89 seconds)
Average speed: 544.04% (89 seconds)

**Comment by cam900** [comment]
In my opinion:
CPS1/2 (and clone/similar hardwares) 8x8 tilemap is actually using 16x8 tiles, and Split this per each column.
Every even columns use the right half of 16x8 tile, odd columns use left half.

**Comment by DavidHaywood** [comment]
I thought I already implemented that?  If you mix the Final Fight and Final Crash ROMS on a PCB you get a corrupt title screen where every other 8x8 column is from the other set of ROMs.

Not sure what that has to do with it being handled in the core or handled in the driver.

**Comment by cam900** [comment]
I close this PR now for later usages.

**Pull request closed without merging**
