### PR TITLE
docs: Added preliminary guide for would-be contributors

### PR DESCRIPTION
**Pull request by cuavas**
@MooglyGuy wrote the bulk of the C++ guidelines here.  Other parts of that page are taken from comments on various pull requests.

The software list contributors’ guide needs improvement/expansion, but it’s a start and mentions the most important metadata elements.

### CODE REVIEW

**Comment by cuavas** [comment]
I’m merging this, but this pull request can still be used for discussion.

**Comment by pmackinlay** [comment]
This is great stuff! Some suggestions for potential additions:
1. Avoid embedding links to potential IP-violating material, use "search friendly" descriptive text instead.
2. Maintain the same access specifiers as overridden virtual methods.
3. Group overridden functions by specialization and order to match the base declaration. 
4. Use the least public access specifier possible for class functions and variables.
5. Group configuration and live public functions in device header so they can be easily distinguished.
6. Prefer a single .cpp file including both class declaration and definition for new drivers (rather than .h/.cpp split).
7. Blank last line in file (should we suggest using srcclean before submission here?).

Hopefully others can word these in a more precise and readable way.

**Comment by pmackinlay** [comment]
Perhaps the license and copyright-holders comments for .h/.cpp files needs to be mentioned in here too?

**Comment by cuavas** [comment]
I’ve updated it with 8edb88dbaab9efbc0b1d843656fecc4b0f087df3:
* Added guidelines for class organisation to address points 2, 3, 4, and 5.
* Point 6 was already touched on.  I expanded it a bit.
* Added a section on file format to address point 7.
* Addressed your second comment in the section on organisation.

**Pull request merged**
