### PR TITLE
A few fixes and more documentation for Heathkit H19 and H89.

### PR DESCRIPTION
**Pull request by mgarlanger**

### CODE REVIEW

**Comment by startaq** [comment]
Give you give a bit more info what you changed? "A few fixes" can be anything.

**Comment by mgarlanger** [comment]
h19.cpp
----------
- Added comments about the memory and port layout from the manual.
- Fixed the frequency of the beep/keyclick: 2kHz -> 1 kHz
- Fixed the duration of the keyclick: 4 mSec -> 6 mSec
- Fixed the screen size: 200 pixels high -> 250 pixels high
--- The code appears to ignore it, and goes by what is programmed in the mc6845, which is wrong, 
    on a real H19, the screen size/character size does not change when the 25th line is 
    enabled/disabled. Only an extra line is shown on the screen 
- Separated the alternative ROMs into separate machines.

h89.cpp
-----------
- Fixed the memory map.
--- Added the disk controller RAM to the lower memory
--- Added comment about banked-switched ROM/RAM (Org-0).
- Fixed port addresses and added more comments to them.
--- Many are still commented out, but the addresses are all valid now.
- Added SW501 switch definitions for the early ROMs.
--- These are commented out, not show the right way to represent multiple definitions.

**Comment by ajrhacker** [comment]
Creating separate machines out of alternative ROMs seems to go against the standard of treating them as BIOSes set by drivers like spectrum.cpp.

**Comment by Lord-Nightmare** [comment]
There are a few exceptions where different sets with different roms is allowed, particularly where there are other hardware changes in addition to a rom swap. (pals, proms, wire mods, etc)

See prose2k.cpp for an example, due to the fact that the older set has a different prom for the rom mapping in addition to different roms, it has its own driver. It also has a different mcu, which isn't dumped yet.

However in this case with the h19, it probably isn't desired.

**Comment by mgarlanger** [comment]
I should have time tonight to see how spectrum handles it. My main goal, with that part of the change, is to not require users to have those other ROMs which are not required to get the H19 working. I saw something like this in one of the arcade games, I think Ms. PacMan, although it could have had other changes I didn't notice. 
I know some of the replacement ROMs for the H19 did require board changes. I'm not positive on which ones or the extent of the changes. There was also at least one other company which provided a replacement ROM. On the H89, there were even more ROMs available.

**Comment by mgarlanger** [comment]
In looking at spectrum.cpp, they have used both alternate ROMs under one machine and also defined several new machines for many of the ROMs.  Since the ROM on the H19, is an essential part of the terminal and many of the replacement ROMs also had replacement keyboard decoders and/or character bitmaps, it seems like separate machines is the best approach here.

**Pull request merged**
