### PR TITLE
video/vrender0.cpp: More accurate VRender0 pipeline inner workings

### PR DESCRIPTION
**Pull request by angelosa**
- Fixes donghaer split screen;

### CODE REVIEW

**Comment by angelosa** [comment]
Ported from https://github.com/mamedev/mame/tree/vrender0_3
Needs QA tests, donghaer looks unstable enough that I need to cross-check this out.

**Comment by angelosa** [comment]
donghaer random crashes are caused by https://github.com/mamedev/mame/pull/11054

**Comment by DavidHaywood** [comment]
I'm pretty sure the game has already gone wrong by the time it starts making unaligned accesses, and that preventing unaligned accesses just means there 1/4 the chance of a write from a bad pointer actually happening (and thus corrupting the game state) and is just masking the problem.

**Comment by angelosa** [comment]
Opening this for review, I'll wait for one release cycle before actually applying unless `donghaer` is fixed in the meantime.

**Comment by DavidHaywood** [comment]
I'm fine with it, donghaer has always been varying degrees of broken anyway, even prior to this if you played it for a while it would crash, or glitch.

There's likely an actual CPU core bug lurking.

**Pull request merged**
