### PR TITLE
prototypes from third session of Sonic Month 2019

### PR DESCRIPTION
**Pull request by kazblox**
segacd.xml related prototypes will come later, once I write an automation tool.

gamegear.xml:
WORKING:
Sonic the Hedgehog Chaos (Euro, Prototype 19930517) [Hidden Palace]

sms.xml:
NOT_WORKING:
Sonic the Hedgehog Chaos (Euro, "Ver 0.20", Prototype 19930630) [Hidden Palace]
WORKING:
Sonic the Hedgehog Chaos (Euro, Prototype 19930713) [Hidden Palace]

These prototypes are believed to have been solely burned for Sega Europe/UK, and thus are all labeled "Euro".

### CODE REVIEW

**Comment by kazblox** [comment]
Should have stated as a whatsnew? that I renamed sonicc in gamegear.xml from "Sonic Chaos" to "Sonic the Hedgehog Chaos" to maintain consistency (box art for Game Gear release packaging says "Sonic the Hedgehog Chaos" too) as well.

**Comment by Tafoid** [comment]
As with all added software to lists, we need a copy of everything for verification purposes.  Please use the information/email posted [HERE](https://wiki.mamedev.org/index.php/Submitting_Source_Code) to send in the images.

Thank you.

**Comment by Tafoid** [comment]
For the upcoming larger SegaCD images, if you have direct links or other ways to house them for sending, please send that information along in email as well.

**Comment by Tafoid** [comment]
Perhaps you can answer as to why these images are split up?
Was it located on 4 chips, each one being dumped separately?
Every other instance of addition of even protos to the list has been one single chip dump for Sega Master System and Game Gear.  I was able to obtain the added images from the source (which were all single chip dumps), but are you documenting it properly in the softlist XMLs ?

**Pull request merged**
