### PR TITLE
ms32.cpp, bnstars.cpp, tetrisp2.cpp : Device-fied sprite hardware (ms32_sprite.cpp), Fix zooming algorithm, Use shorter/correct type values, Verify clock related to XTAL

### PR DESCRIPTION
**Pull request by cam900**
ms32.cpp: Fix sprite delay

### CODE REVIEW

**Comment by Tafoid** [comment]
@cam900 
Noted Regressions
bnstars1 - bnstars1.cpp
Graphics missing
bnstars1-diff

More as they are found

**Comment by cuavas** [comment]
@Tafoid or @cam900, was the regression addressed?

**Comment by Tafoid** [comment]
@cuavas Still appears to be regressed

**Comment by Robbbert** [comment]
https://mametesters.org/view.php?id=7533

**Comment by rb6502** [comment]
@cam900 please fix this regression.  we will not accept anything more from you until this stuff is fixed.  And please test your changes.

**Pull request merged**
