### PR TITLE
HLE of HP9845 internal printer

### PR DESCRIPTION
**Pull request by fulivi**
Hi,

this PR adds the high-level emulation of hp9845-series internal printer.
It also fixes a couple of things broken by the recent emumem API change.
The printer emulation outputs the graphic image through ASCII lines, with '*' representing black pixels.
I'm attaching a simple python script to convert this output to a bitmapped image (a PNG file, for example).
I'm also sending the image of the character generator ROM to the "code" email address.
Thank you.
--F.Ulivi

```
#!/usr/bin/env python3

import sys
import re
import argparse
from PIL import Image

def ensure_space(img , min_lines):
    s_x , s_y = img.size
    if s_y < min_lines:
        new_img = Image.new("1" , (s_x , min_lines) , 1)
        new_img.paste(img , (0 , 0))
        img = new_img
    return img

def print_line(img , line , pixels):
    img = ensure_space(img , line + 24)
    for x , p in enumerate(pixels):
        if p == '*':
            img.putpixel((x * 2 , line) , 0)
            img.putpixel((x * 2 + 1 , line) , 0)
            img.putpixel((x * 2 , line + 1) , 0)
            img.putpixel((x * 2 + 1 , line + 1) , 0)
    return img

def fatal(msg):
    print("{}: Fatal error:{}".format(sys.argv[ 0 ] , msg) , file=sys.stderr)
    sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Convert HP9845 printer bitbanger to image")
    parser.add_argument('inp_file', help="Input bitb file")
    parser.add_argument('out_file', help="Output image file")
    args = parser.parse_args()

    try:
        inp = open(args.inp_file , "rt")
    except IOError:
        fatal("Can't open input file ({})".format(args.inp_file))

    mg = re.compile(r"(\d+):([ *]{560})")

    img = Image.new("1" , (1120 , 0) , 1)

    for line_no , l in enumerate(inp):
        mo = mg.match(l)
        if mo:
            img = print_line(img , int(mo.group(1)) , mo.group(2))
        else:
            print("Can't parse line {} in input file".format(line_no + 1))

    img.save(args.out_file)
    
if __name__ == '__main__':
    main()
```

### CODE REVIEW

**Comment by cuavas** [comment]
If this device is a one-off internal to this family of machines, it really belongs in `src/mame/machine` rather than `src/devices/machine`

**Comment by fulivi** [comment]
Ah, didn't know of this... I'll move the printer code over to `src/mame/machine`..

**Comment by cuavas** [comment]
See e.g. the [header](https://github.com/mamedev/mame/blob/master/src/mame/machine/imm6_76.h) and [source](https://github.com/mamedev/mame/blob/master/src/mame/machine/imm6_76.cpp) for the Intel imm6-76 EPROM programmer for a pre-existing example.  It gets linked into `libintel.a` - your printer would go into `libhp.a` when building.

**Comment by fulivi** [comment]
Here it is... hope I got it right

**Comment by cuavas** [comment]
Thanks

**Pull request merged**
