### PR TITLE
Apple updates for June 2021

### PR DESCRIPTION
**Pull request by Firehawke**
New working software list additions (apple2_flop_clcracked.xml)
---------------------------------------------------------------

Bumble Games (Version 1.3) (cleanly cracked) [4am, san, Firehawke]
Reader Rabbit (Version 1.0) (cleanly cracked) [4am, san, Firehawke]
Projectile and Circular Motion (cleanly cracked) [4am, Firehawke]
Bumble Plot (Version 1.1) (cleanly cracked) [4am, san, Firehawke]
Gertrude's Puzzles (1982 Version) (cleanly cracked) [4am, san, Firehawke]
Gertrude's Secrets 1982 (cleanly cracked) [4am, san, Firehawke]
Tales of Discovery (cleanly cracked) [4am, san, Firehawke]
Advanced Electricity (cleanly cracked) [4am, Firehawke]
Complex Circuits (cleanly cracked) [4am, Firehawke]
PAI Forth (Version 3.0, 12-21-1985) (cleanly cracked) [4am, Firehawke]
Rocky's Boots (Unknown 1982 version) (cleanly cracked) [4am, san, Firehawke]
The Prisoner (Version 1.10) (SoftSmith) (cleanly cracked) [4am, san, Firehawke]

New working software list additions (apple2gs_flop_orig.xml)
------------------------------------------------------------

Gin King / Cribbage King [4am, Firehawke]
Revolution '76 (Version June 27, 1989) [4am, Firehawke]
The Print Shop (Version 1.0) [4am, Firehawke]
The Print Shop Companion [4am, Firehawke]
Fantavision [4am, Firehawke]
Cartooners [4am, Firehawke]
Art and Film Director [4am, Firehawke]
Draw Plus (Version 1.1) [4am, Firehawke]
The Graphics Studio [4am, Firehawke]
The Immortal [4am, Firehawke]
TrianGo [4am, Firehawke]
816/Paint (Version 3.1) [4am, Firehawke]
BeagleDraw (Version 1.3) [4am, Firehawke]
DreamGrafix [4am, Firehawke]
Platinum Paint (Version 2.01) [4am, Firehawke]
Paintworks Plus (Version 1.2) [4am, Firehawke]
Paintworks Gold (Version 1.5) [4am, Firehawke]
ImageMaster: Basic Paint (Version 1.2) [4am, Firehawke]
Graphics Supermarket (Version 1.1) [4am, Firehawke]
GraphicWriter III (Version 1.0) [4am, Firehawke]
DeluxePaint II (Version 2.01) [4am, Firehawke]
Stars and Planets [4am, Firehawke]
Mavis Beacon Teaches Typing (Version 1.8) [4am, Firehawke]
Math and Me (Version 1.0 08/01/88) [4am, Firehawke]
SmoothTalker [4am, Firehawke]
Stickybear Shapes [4am, Firehawke]
Tarot [4am, Firehawke]
Full Metal Planete [4am, Firehawke]
Shanghai II: Dragon's Eye [4am, Firehawke]
Music Construction Set (Version 1.0) [4am, Firehawke]
Instant Synthesizer [4am, Firehawke]
Master Tracks Pro (Version 1.04) [4am, Firehawke]
The Music Studio (Version 2.0) [4am, Firehawke]
Jam Session (Version 1.0) [4am, Firehawke]
Pyware Music Writer (Version 2.03) [4am, Firehawke]
Master Tracks Jr. (Version 1.03) [4am, Firehawke]
Salvation Supreme (Version 2.0) [4am, Firehawke]
NoiseTracker (Version 1.0) [4am, Firehawke]
HyperStudio (Version 3.1c) [4am, Firehawke]
Writer's Choice Elite [4am, Firehawke]
WordPerfect (Version 2.1e) [4am, Firehawke]
The Wonders of the Animal Kingdom [4am, Firehawke]
The Word Master [4am, Firehawke]
Read and Rhyme [4am, Firehawke]
Aesop's Fables [4am, Firehawke]
Audubon Wildlife Adventures: Grizzly Bears [4am, Firehawke]
Audubon Wildlife Adventures: Whales [4am, Firehawke]

### CODE REVIEW

**Comment by Firehawke** [comment]
I'll leave this open for 24-48 hours before merging. If anyone has a complaint, I can get it worked out before merging.

**Comment by peterferrie** [comment]
Please change "san" to "san inc.", if they refer to me.

**Comment by Firehawke** [comment]
@peterferrie Just to be absolutely clear on this: so the given name should be "san inc.", and not inc as in incorporated?

**Comment by peterferrie** [comment]
> @peterferrie <https://github.com/peterferrie> Just to be absolutely clear
> on this: so the given name should be "san inc.", and not inc as in
> incorporated?
>

Yes, the given name is "san inc.".
Thank you.

>

**Comment by Firehawke** [comment]
The adjustment has been made, and merging now.

**Pull request merged**
