### PR TITLE
eispc.cpp: verified that BGFX related issue #5776 is gone and removed workaround

### PR DESCRIPTION
**Pull request by JoakimLarsson**

### CODE REVIEW

**Comment by cuavas** [comment]
Are you sure there isn't some other issue lurking?  Have you run it under a memory analyser?

**Comment by JoakimLarsson** [comment]
No, it was 100% repeatable before and now I can't reproduce it all, so I presume that some of the BGFX fixes applied fixed it. Naturally it can be something else as I was only observing a symptom.

**Comment by cuavas** [comment]
Yeah, but it could have just been some out-of-bounds access that happened to be exposed before and is hidden again.  Of course it could have been an out-of-bounds access in the bgfx code that has now been fixed.  I'd just rather have some assurance that it's not just working by chance.

**Comment by JoakimLarsson** [comment]
Ok i bisected it

Commit 06f99c21a08fe76ae833a5587d19c33ed0a035f1 bgfx: fix tgmj crash on resolution change (GitHub #5857) [Ryan Holtz] fixed it 
Commit 2012b38e1e7cb669ddecf684d0cbdb8c2d214292 just prior still has the problem

**Pull request merged**
