### PR TITLE
hyprduel : Cleanups, Add imagetek_i4220_device, Allocate sound output…

### PR DESCRIPTION
**Pull request by cam900**
… form real PCB(real PCB only has mono sound output)

imagetek_i4100.cpp : Boost tilemap drawing routines when VIDEO_UPDATE_SCANLINE case of screen video attributes, Add notes

### CODE REVIEW

**Comment by cam900** [comment]
I hasn't touch IRQ routines in hyprduel.cpp driver but magerror doesn't boot. it has imagetek_i4100 device timer issue?

**Comment by angelosa** [comment]
It's because you removed this line from magerror_map
 `AM_RANGE(0xc00000, 0xc1ffff) AM_RAM AM_SHARE("sharedram1") `

Which probably means it's not finding a necessary item for booting.

**Comment by angelosa** [comment]
Also VIDEO_UPDATE_SCANLINE is known to be really slow and requires cliprects to update properly.
Have you tested Hyper Duel stage 2? That's a common test case for rasters.

**Comment by cam900** [comment]
Rasters are working with 200% speed(at my computer with i3-4130 CPU) in hyprduel.
also, Thanks for information of my mistakes.

**Comment by Osso13** [comment]
This compiles cleanly on official tools as of right now.

**Pull request merged**
