### PR TITLE
Suggestion for very-low-latency mode on portaudio

### PR DESCRIPTION
**Pull request by ericvids**
- Needed to keep audio in sync when playing rhythm game machines such
as konami system 573. This is because the lowest audio_latency currently
supported (audio_latency 1) introduces at least 10 ms of variable latency.
I am unsure how to go about this without breaking backward compatibility
so I set it to work only when audio_latency is 0 (which was previously ignored
by mame itself and was treated equivalent to audio_latency 1). I am aware
that setting audio_latency to 0 is not supported by many mame frontends,
but this change seems natural. Otherwise, would it be better to add
a new mame.ini option, or to automatically enable this low-latency mode
when pa_latency is set lower than, say, 0.01 (10ms), which would
break people's configurations if they already rely on the old behavior?

### CODE REVIEW

**Comment by u-man74** [comment]
Not sure, how 10ms of less latency, would help that much. Portaudio has already so much less latency compared to WMA. 
With my onboard-sound i get usually around 20ms and for pushing this even lower, people would need external sound-cards of extra-ordinary quality.

**Comment by ericvids** [comment]
Music games are a whole different ball game. Drummania, for instance, has a Perfect timing window of +/-25 ms (and DDR is even stricter than that with Marvelous timing). A jitter of just 10 ms spells the difference between being able to unlock a Premium Encore stage or not.

My hardware reports just 3.63 ms of latency (also onboard sound), but because of the 10ms hard limit from before with audio_latency 1, it stops expert players from unlocking the hardest songs.

I anyway made the patch as backwards-compatible as possible, so hardware that can't support this wouldn't suddenly encounter problems. That said, I welcome any suggestion to make this solution more robust.

**Comment by u-man74** [comment]
Well, i do not know, how you achieved 3.63ms of latency with onboard-sound only and i am curious for your settings.

I also do not know how MAME is processing audio+video together (paralell or audio on top of video), but i would think that input-lag and calculating a videoframe-time have a much higher impact, then audio latency.

**Comment by MooglyGuy** [comment]
Don't worry about it, Eric. u-man is not a MAME developer and does not speak for the MAME team. I'm not quite sure why he is even commenting on pull requests.

**Comment by u-man74** [comment]
I am commenting, because it is a topic that interests me. I would like to understand, how much impact sound latency can have. Also 3.63ms latency is ridiculous low for a onboard sound and maybe i can achieve better results on my side, by knowing how ericvids did that.

**Comment by ericvids** [comment]
To elaborate, the latency I'm talking about is a variable latency (or jitter) that MAME allows the sound to run past on every audio callback.  (If MAME exceeds this value, sound samples are dropped adaptively.) This is different from the constant latency setting, which is controlled by pa_latency.  Setting pa_latency to 0.02 and audio_latency 1 will make it so that actual run-time latency would vary from 20 to 30 ms.  30 ms is already at the range where you will literally feel input that should have been Perfect on the dot will register as Great or Good instead -- not good (pardon the pun) if you're trying to get 98% Perfect on a song.

As for my constant latency of 3.63 ms, I have nothing to do with it -- it's just the default my hardware reports.  You'll be surprised how good built-in sound is these days.  :-)  I'm on an i7 7th gen laptop with a GeForce GTX 1050 Ti, default Realtek Hi Def Audio sound, and Windows 10 WASAPI exclusive mode. My external USB sound mixer actually has larger latency than this.

**Comment by Poliwrath** [comment]
> I'm not quite sure why he is even commenting on pull requests.

are people not allowed to give their own input on PRs?

**Pull request merged**
