### PR TITLE
Fixes for RM nimbus floppy image writing errors.

### PR DESCRIPTION
**Pull request by prime6809**

### CODE REVIEW

**Comment by prime6809** [comment]
Ok, I've removed the delays and modified the write sector code so that it correctly completes writing the sector before acting
on the forced interrupt. This seems to be what the real hardware does. This would be the logicl thing to do as the write multiple sector command can only be ended by a forced interrupt, or an error.

**Comment by prime6809** [comment]
K, will change static to const. 
What should I init as? when I used char * the compiler spat out something like "the c++ standard forbids casting char* to string"

**Comment by galibert** [comment]
static const char *const states[] = {...} should do.

  OG.

**Comment by prime6809** [comment]
Cheers, just pushed the change.

**Pull request merged**
