### PR TITLE
mega32x.cpp : Draw 32x layer only while resolution is same at megadrive vdp, Fix PWM masking

### PR DESCRIPTION
**Pull request by cam900**
reference : official document

### CODE REVIEW

**Comment by cuavas** [comment]
Are there any before/after comparisons you can show where software for the system is affected by suppressing the 32X layer when the resolution differs?

**Comment by cam900** [comment]
That is correction related to hardware behavior, and Minor performance optimization.

**Comment by cam900** [comment]
mortal kombat ii uses 256 horizontal resolution mode in sega logo, but 32x layer is unused at this scene.

**Comment by DavidHaywood** [comment]
would the layer actually be disabled, or would it 'stretch' to match.

32x is an analog overlay, you have to plug in the pass through connectors etc.

**Comment by DavidHaywood** [comment]
Also @cam900 please fix this bug you introduced
https://mametesters.org/view.php?id=7479
the CAVE games are considered important, people will refuse to update MAME with them broken.

**Comment by cam900** [comment]
> Also @cam900 please fix this bug you introduced
> https://mametesters.org/view.php?id=7479
> the CAVE games are considered important, people will refuse to update MAME with them broken.

Fixed in https://github.com/mamedev/mame/pull/5948.

**Comment by cuavas** [comment]
'would the layer actually be disabled, or would it 'stretch' to match.

Would it actually stretch?  VDP control signals are available on the cartridge connector - e.g. the 32X uses the /YS signal to detect when the VDP is drawing the background colour to support Mega Drive graphics over 32X graphics.  Does it derive the pixel clock from EDCLK or something?

At any rate, I think we need actual hardware tests.  The documentation could be advising against using the 32X layer when the VDP is running at a different horizontal resolution.

**Comment by cam900** [comment]
I close this PR now for later usages.

**Pull request closed without merging**
