### PR TITLE
Update bx, bimg and bgfx

### PR DESCRIPTION
**Pull request by mmicko**
Required by @MooglyGuy to continue his work, currently build shaders are still working fine with this build.

### CODE REVIEW

**Comment by mmicko** [comment]
Any objections merging this (mainly @cuavas ) ? 
Have let CI run again, but there was no errors compiling first time, just issues of GH itself (uploading artifacts, downloading tools and similar)

**Comment by Tafoid** [comment]
My opinion, if such a big update is done, as far as testing goes, it would be much better to do it as soon as possible.  We are about 11 days from freeze for 0.235.

**Comment by belegdol** [comment]
Did anybody check the vulkan backend? In my draft PR I had to rebuild the shaders, otherwise the output was flipped vertically.

**Comment by mmicko** [comment]
Right. MG is preparing PR with additional changes including shaders rebuild.

**Comment by algestam** [comment]
Just tried the changes locally and can confirm that recompiling the shaders resolves the flipped screen issue. Also, compiling (and running) with Emscripten works well.

**Pull request merged**
