### PR TITLE
megadriv.xml: Metadata cleaning

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Replaced countries' abbreviations by the full names

### CODE REVIEW

**Comment by cuavas** [comment]
For `bloodsht`, could you please change the description to “Bloodshot (Europe)” and put “Battle Frenzy” in an `alt_title`?  That’s the proper way to do multiple regional titles.

**Comment by cuavas** [comment]
`sonic3d` and `soniccmp` should also have the regional titles moved to `alt_title`.

**Comment by ArcadeShadow** [comment]
> For `bloodsht`, could you please change the description to “Bloodshot (Europe)” and put “Battle Frenzy” in an `alt_title`? That’s the proper way to do multiple regional titles.

Done it. There are like this (for instance, `fzone `or `mercs`). 
Do I keep it like it is or is it better to put the Japanese title on the `alt_title` ?

**Comment by cuavas** [comment]
> > For `bloodsht`, could you please change the description to “Bloodshot (Europe)” and put “Battle Frenzy” in an `alt_title`? That’s the proper way to do multiple regional titles.
> 
> Done it. There are like this (for instance, `fzone `or `mercs`). Do I keep it like it is or is it better to put the Japanese title on the `alt_title` ?

Leave the transliterations of Japanese titles as-is for now, I’ll think about what to do with them later.

**Pull request merged**
