### PR TITLE
Mame0252 bn

### PR DESCRIPTION
**Pull request by abcbarryn**
Allow floppy controller in any multi pak slot. Even though the manual states that floppy controller should be used in slot 4, they do in fact work in any slot on the real hardware, I know, I've done it more than once.

Add floppy controller with custom RGBDOS ROM, adds support for emulated HD in RSDOS.

### CODE REVIEW

**Comment by cuavas** [comment]
* Pull request title is non-descriptive.
* Commit messages and pull request description give no context.
* You’ve reformatted pretty much every line against our coding standard.

**Comment by npwoods** [comment]
@tlindner

**Comment by angelosa** [comment]
Title is `Mame0252 bn`. What even it means is anyone's guess ...

**Comment by Robbbert** [comment]
@abcbarryn I'll try to offer some insight as to what you need to do.

- Don't be aggressive. You'll never win.
- The title line is the introduction to your proposal, a one-line overview of what you hope to achieve. With the lazy title that you chose, it kills off any momentum right there. Have a look at some other pull requests.
- Very few people here know about the Color Computer. RGBDOS ROM or multi pak slot doesn't mean a lot to the average person. Given that there's no useful title, nobody will know what you're referring to.
- The formatting is actually the worst part. For some reason you've changed every line in every file, I can't see exactly how, but github has picked up a difference. Perhaps you changed tabs to spaces. It means nobody can see what your actual changes are, because every line is highlighted as changed. You need to change the formatting back to what it was before there's any hope of acceptance.
- The talk of ROMs might mean you added one or two. Where did they come from? This project requires that you indicate your source.
- Good luck!

**Comment by abcbarryn** [comment]
I don't care if I win. They can add the updates or not. I have my own fork, if they don't want to add them here I'll just update it there. I will try to reformat the code so the changes are apparent. RGB-DOS was sold by Burke and Burke of Washington. The main feature was adding hard drive support for RS-DOS. It did this by dividing a hard drive into 255 virtual floppy drives and adding commands to switch among these virutal floppies. I have permission from Chris Burke to distribute the ROM and I have the source code to a few different versions. The particular version was modified by Robert Gault with permission from Chris Burke. I have previously spoken with Robert Gault as well. Robert Gault 832 N.Renaud Grosse Pointe Woods, MI 48236. USA (313)-881-0335 e-mail: robert.gault@att.net

**Comment by abcbarryn** [comment]
I also have Robert Gault's phone number if you have additional questions I can call him and ask. I think the number is current however I have not spoken with him for quite sometime.

**Comment by angelosa** [comment]
I don't think Robert Gault will be happy to know that you posted his full address line and his e-mail on a public server. Think we've seen enough here.

**Pull request closed without merging**
