### PR TITLE
support rowscroll on the score layer of cps3, fixes jojoba combo meters

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by Xcl4m4t10n** [comment]
Thank you a lot for this one.

Sorry for this question but, will it be available at MAME regular tree? I am a little ignorant (well, not a little actually ...) of how MAME GitHub works, so I am curious to know if the next MAME version will have this fix.

BTW, could you please attach an image of 2P Combo Metter working please?

Thank you again!

**Comment by happppp** [comment]
Yes, it's in the master tree: https://github.com/mamedev/mame/commit/b8dd83fdcf519a3a465b539afe9558a7da37690d
If you want an executable to verify the fix, perhaps @DavidHaywood can provide you with one.

**Comment by Xcl4m4t10n** [comment]
Thank you @happppp for the clarification. And yes, it would be awesome if @DavidHaywood can provide a Windows executable (I have no Linux machine atm sorry), if I am not asking too much.

**Comment by DavidHaywood** [comment]
http://mamedev.emulab.it/haze/pics2018/cps3test.zip 
here is a 64-bit MAME binary, note, unzip it over a clean 0.202 tree as I haven't included support files (bad form, but I don't have time to do a complete package right now)  the binary only supports CPS3 titles.

http://mamedev.emulab.it/haze/pics2018/jojoban.png  screenshot if you're curious.

**Pull request merged**
