### PR TITLE
Autofire support (cheat)

### PR DESCRIPTION
**Pull request by motoschifo**
Added support for input buttons autofire.
This is a kind of cheat and I put it under the CHEAT menu, available using -cheat command line options only.
If that option is not specified, the autofire cheat can't be enabled by the shortcut key.

The menu settings (enable/disable, delay and on/off items for each button) is placed under the CHEAT menu.
The initial work has been made by Mamesick who sent me the source code.

### CODE REVIEW

**Comment by motoschifo** [comment]
Screenshots of the new menu.
autofire_disabled
autofire_enabled

**Comment by p1pkin** [comment]
is this code created by you from scratch or taken from some MAME fork ?

**Comment by motoschifo** [comment]
Mamesick has written initial code, then I changed a lot of things:
- added command line option checking
- moved submenu to cheat menu (it's a cheat...)
- redrawn the menu if options changed (for example with shortcut toggle)
- added gui toggle item
- added enabled/disabled layout with colored or grayed text, grouped players buttons
- optimize source code and variables
- changed a bit of existing cheat code (i.e. I used const instead of numbers 1 and 2)
- other minor changes

Before starting this work I asked permission to Mamesick to extend and change his code.
If this request will be accepted, his name should be present in credits.

**Comment by happppp** [comment]
The concept and feature of autofire is fine by me. I think an
implementation of it should be more generic though. The way you have it
there, it's only supported on 8 joystick buttons?

**Comment by mamesick** [comment]
The autofire code scans for all 16 buttons that are supported by MAME core: IPT_BUTTON1 <---> IPT_BUTTON16. Obviously if a game/machine has no buttons (e.g. a mahjong panel or a computer with keyboard) the menu is not populated and a message is displayed.

**Comment by cuavas** [comment]
So if you want to cheat to get the "punishment by repeated blows" in Taisen Hot Gimmick you're out of luck? Sounds less than ideal to me.

**Comment by mamesick** [comment]
Feel free to modify the code to also scan for IPT_MAHJONG keys/buttons. Sincerely I don't care too much about this. A friend asked me the source of my autofire feature to see if it was possible to implement in official MAME. That's all. I'm not asking anything here, nor to be credited neither to see it accepted. I simply posted a comment to better explain the behaviour. If you wish, you can scan for all IPT_XXXX entries of a game/machine so you will have autofire on IPT_COIN for example and you'll be able to insert hundreds of them. Have fun.

**Comment by galibert** [comment]
It's not ideal, but otoh it's not bad ui-wise right now.  Why not accept
it, that would show we're ok with that kind of feature, and someone
interested can enhance it.

  OG.

**Comment by mmicko** [comment]
Let's go that way

**Comment by motoschifo** [comment]
Thanks!

**Comment by Tafoid** [comment]
There is an issue with this that was discovered and being that we have only a few days before release we'd like to see it fixed.

You can activate a normal cheat, then goto autofire and activate a button for autofire, or even enable/disable it.  When you return to the cheats, they are all shut off.

Example:  defender
- Enter Cheat Menu and activate Invincibility "ON"
- Enter Autofire Settings and change any setting there (turn it on, or activate a specific button)
- When you leave the Autofire Settings menu and return to normal cheats, they are all set to "OFF"

In practice, going to another menu should not eliminate settings from another.  Could someone please look at correcting this?

**Comment by motoschifo** [comment]
I'm checking now...

**Comment by felixlang** [comment]
Can you add a setting that allows the autofire function to persist after powering off and back on? As it is now it looks like it needs to be re-enabled (and the delay reset) after each boot.

**Comment by motoschifo** [comment]
The autofire settings are not saved intentionally.
I don't know how to write these infos on cfg file, but I will create a pull request if I will do it.

**Comment by cuavas** [comment]
It likely wouldn't be accepted anyway. Autofire is like overclocking, something most games went built with in mind (with the notable exception of PC-Engine).

**Comment by Augusto7743** [comment]
Thanks for add autofire in MAME.
Please see the link below
http://forum.mamedev.org/viewtopic.php?f=14&t=107&p=365#p365
Overclocking and autofire not are the same feature. Overclocking is for devs.
Enabling autofire some games need two buttons for the same arcade button because of charge buttons. Shooters are one good example.
I all time need to enable autofire when starting. Is an few annoying.
Other emulators have the feature above.
MAME Plus 0.168 source code have details about saving autofire in cfg.
If add autofire for an separate button and saving in cfg much users will use just the official version having just one only current version of MAME.
Thanks for read my post and have a good night.

**Pull request merged**
