### PR TITLE
68230: Bitwise port update methods + new TTL device: 74164

### PR DESCRIPTION
**Pull request by JoakimLarsson**

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
ok, I'll close this and split it out then, guess the 68230 parts are ok.

I wasn't aware of the problem though, has there been a thread about it? I really need the functionality so I guess I just fake it in the driver for now then.

**Comment by JoakimLarsson** [comment]
Ahh got it, isn't checking my mails too often when I am coding... :)

**Comment by JoakimLarsson** [comment]
@cuavas: do we have a viable plan for these circuit clock domain issues yet? I refactored the 74164 as a netlist device and it became a lot more complex than a normal device driver, still doable though, and my circuit didn't have any clock domain issues to start with. So I am thinking, could we have dual implementations (device & netlist) of some and then use the appropriate one depending on the type of circuit or what is the recommendation here. I am about to implement a 74670 why I am asking in this context.

**Comment by happppp** [comment]
FWIW personally I'm against blocking emulation of new devices due to this MAME core problem. It is unrelated to specifically TTL devices, any chained devices sharing the same CLK are affected to this.

Any other people have opinions? Please share them.
The more we're leaning to a yes(or no), the better for a decision on this.

**Comment by MooglyGuy** [comment]
Document the fact that the chips exist on the board, then implement a high-level functional simulation if you're not willing to use the netlist system. It's perfectly possible to interoperate between a netlist and non-netlist hardware. I would know, I was working on exactly that this time last year. That's part of the point of the netlist system, to avoid these kinds of clock-sync issues.

I initially implemented a bunch of these TTL devices because I, too, thought that I would be able to make it work. In my case, with the Hazeltine 1500 video hardware. I wasn't, because it's not an easily-solved problem without resorting to a netlist. Anything else is basically just trying to kludge what the netlist system is already there for, and it shouldn't be encouraged.

What's bothersome to me on a personal level is that I thought that this conclusion was already done and dusted a year ago. But instead of taking my mistakes as a cautionary tale of what not to do, people seem to have seen it and gone, "Yeah, let's do more of that," which is exactly the opposite reaction that my tribulations with the Hazeltine 1500 video subsystem should have garnered.

**Comment by JoakimLarsson** [comment]
So there is a decission that all clocked ttl circuits should use netlist, even when there is no clock domain issue? No problem, I thought we still evaluated it, I just wanted to be sure before I made another clocked ttl device.

**Comment by ajrhacker** [comment]
Interoperability between netlists and normal MAME devices may be possible now, but I don't think it's generally advisable. The netlist system imposes significant performance burdens which don't seem to be worthwhile outside of the LLE video and discrete sound subsystems in which it has already proved itself.

As for 74164, I think that synchronizing the serial input on the active clock edge, similar to what `generic_latch_8_device` does, should be enough for most use cases.

**Pull request closed without merging**
