### PR TITLE
corrected connection between drivers and softwarelists for exl100 carts and spectrum floppies (nw)

### PR DESCRIPTION
**Pull request by sparrowred**

### CODE REVIEW

**Comment by mamehaze** [comment]
I don't understand this change, the spectrum plus 3 disks are
specpls3_flop.xml
so your change will cause them to not be seen?
as things stand they work.

some of the russian clones have their own TRDOS disks etc. which will need different lists.

**Comment by LnmVolbo** [comment]
Nearly all the software lists have the same "sofwarelist" name as software list .xml output file name.  If anyone is going to change the internal "softwarelist" name, please see that the .xml file name for that software list is the same.

For a long time the "specpls3_flop.xml" .xml output file has had the internal software list name of "spectrum_flop".  It would be better if either the .xml file name were to be "spectrum_flop.xml", or the internal software list name be "specpls3_flop".

With several hundred software lists now included, it's much easier to organize them if they all follow the same convention.  I'm not trying to say how any particular software list should be named, just that the names ought to be consistent between the internal name and the .xml file produced..

**Comment by mamehaze** [comment]
you'd be better off renaming the list in the xml then, disconnecting the list is not acceptable.

**Comment by LnmVolbo** [comment]
**@sparrowred,**

Of the 394 current software lists, only the **ZX Spectrum disk images** (spectrum_flop/specpls3_flop) list has the mismatch between the internal name and the .xml file name.

Your revisions to the *src/mame/drivers/specpls3.c* file may address that issue, but **Haze** knows better than I whether that will disconnect the list.

Your revisions to the *hash/exl100.xml* file look like they will create a new mismatch between the internal name and the .xml file name.  Is this intentional?

**Comment by sparrowred** [comment]
Sorry, this is a mistake from my side.
I tried to connect the softwarelist names from the drivers with the internal names of the xml file but of course instead the drivers softwarelist names represent the filename.

I promise to do better research next time before wasting your time again.

**Pull request closed without merging**
