### PR TITLE
Suggested changes to MacOS to build reqs

### PR DESCRIPTION
**Pull request by mac-a-r0ni**
Suggested changes to MacOS to build reqs, the old info is very out of date with the current requirements.

### CODE REVIEW

**Comment by rb6502** [comment]
A few additional things I'd like as long as we're updating this:

- Apple Silicon Macs need SDL 2.0.14 or later
- MacPorts now offers current MAME binaries for macOS all the way back to 10.6, so a note that users of pre-10.14 systems should go there (with a link) would be a good idea

Thanks in advance!

**Comment by mac-a-r0ni** [comment]
I'll revise the information with your suggested updates, RB. I am 
curious regarding macports offerings, as maybe this information should 
be noted here as well, but there should also be a more fleshed out bit 
in the wiki page here: 
https://wiki.mamedev.org/index.php/SDL_Supported_Platforms

thoughts?

On 2021-01-29 02:27 PM, R. Belmont wrote:

> A few additional things I'd like as long as we're updating this:
> 
> * Apple Silicon Macs need SDL 2.0.14 or later
> * MacPorts now offers current MAME binaries for macOS all the way back 
> to 10.6, so a note that users of pre-10.14 systems should go there 
> (with a link) would be a good idea
> 
> Thanks in advance!
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] https://github.com/mamedev/mame/pull/7715#issuecomment-770002549
[2]

**Comment by cuavas** [comment]
This page is for building MAME from official source yourself.  Telling people they can get binaries from MacPorts doesn’t belong on this page.

**Comment by mac-a-r0ni** [comment]
> This page is for building MAME from official source yourself. Telling people they can get binaries from MacPorts doesn’t belong on this page.

Yes, this is what I was suggesting that binaries like macports, and brew should be noted on the wiki instead.

**Comment by rb6502** [comment]
I disagree.  If someone on a pre-10.14 system comes to this page, it's important to make sure they understand that there are still options.

**Comment by cuavas** [comment]
> I disagree. If someone on a pre-10.14 system comes to this page, it's important to make sure they understand that there are still options.

If MacPorts can provide tools/libraries to build current MAME on pre-10.14 systems, then information on how to set that up belongs on this page.  However, right now all they’re doing is providing 0.226 binaries for pre-10.14 systems.

**Pull request merged**
