### PR TITLE
spdheat - timer setting dips were reversed, add actual timer values too (nw)

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by philipjbennett** [comment]
Oops yes, they are reversed but don't put the time values next to them; it varies per stage IIRC.

**Comment by DavidHaywood** [comment]
alright, moved the values to comments, as it does increase around the 4th race, but is still useful information for showing what the setting is based on

**Comment by DavidHaywood** [comment]
fwiw "Coin Display" seems to be inverted too, it shows the "Insert Coin(s) 1 Coin 3 Credits" string on one of the attract mode displays if it is 'Off' at present, but simply shows "Insert Coin(s)" if 'On'

**Comment by philipjbennett** [comment]
Change it if you please; I got that wrong too.

**Comment by DavidHaywood** [comment]
alright, I'll probably put it in with a future PR then if nobody beats me to it, it's rather minor compared to the inverted timer.

Still trying to work out what "Coin System" and "Functions of CPU-Controlled Cars" do in terms of gameplay in order to verify those.

**Comment by cuavas** [comment]
Doesn't "functions of CPU-controlled cars" allow/disallow the cars to "jump" when they're behind in the race?

**Comment by DavidHaywood** [comment]
could be, I'll need to test.
btw, Phil, sprites clip off early on the left edge of the leftmost screens, does this happen on hardware?
(drive towards the border)

**Comment by philipjbennett** [comment]
I don't have the PCB working so I can't tell you for sure but that doesn't
seem correct. If you're willing to fix it, go ahead; I'm a bit short on
time at the moment.

**Pull request merged**
