### PR TITLE
Made SPG2xx I/O IRQ checking a bit more lean; improved ADC behavior.

### PR DESCRIPTION
**Pull request by MooglyGuy**
-spg2xx_io: Cleaned up IRQ checking and improved ADC behavior. [Ryan Holtz]

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
Is it worth doing the check for null IRQ callbacks and logging them, or would it be sane to just use `resolve_safe` and black-hole them when nothing’s attached?

**Comment by MooglyGuy** [comment]
Good call. I'm not sure it's informative in any useful way to flag a lack of IRQ callback hookups. If anyone is writing an SPG derivative device, one of the more necessary and obvious things to do is to hook up the IRQ callbacks.

I've also done a cleanup pass on the timers in the device, favoring `TIMER_CALLBACK_MEMBER` instead of `device_timer` due to the sheer number of timers potentially introducing overhead through a switch/case in the device_timer callback.

**Comment by MooglyGuy** [comment]
Uh, I think I may have inadvertently clicked "Close & Comment" instead of just "Comment". Can someone reopen this, please?

**Comment by MooglyGuy** [comment]
Oh, I see it was merged while I was fixing it up and commenting.

**Pull request merged**
