### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Bad-A-Billy**
Added/changed some key & dip settings. 
Updated & added a couple of layouts.
Only did a couple before feedback, more that can be done though.

### CODE REVIEW

**Comment by Bad-A-Billy** [comment]
I've tried everything I can find to get rid of all the junk but nothing is getting rid of it. Any ideas would be appreciated. If nothing else I will close this out later today & submit a diff the old way.

**Comment by galibert** [comment]
Look at the commit list, cry a little, and try again.

**Comment by galibert** [comment]
Let's see if I can help you then...

  OG.

**Comment by Bad-A-Billy** [comment]
ok, thanks for the time OG.

**Comment by galibert** [comment]
As far as I can tell, there's nothing in that pull request.  As in, if you
git diff with 0e2299e424d7da177a57bb530ae740c79a3c92a0 (Ivan's commit), you
get nothing.  Dunno where your patch is, but it's not in there.

  OG.

**Comment by Bad-A-Billy** [comment]
Tried a few more things.

**Pull request closed without merging**
