### PR TITLE
Document that describes changes in core ini files.

### PR DESCRIPTION
**Pull request by NULUSIOS**
I believe this is a file that is missing from current distribution (and documentation) and is useful both for devs and end-users.
It currently goes up to 0.162 (first merged MAME + MESS release), but if there is interest I may go further back.

### CODE REVIEW

**Comment by u-man74** [comment]
yes, indeed it is a useful feature. maybe could be used even for "converting" older .ini files to newer .ini standards.

**Comment by Tafoid** [comment]
This file may be useful to an external tool, front-end or historical document (such as mameinfo.dat), but it doesn't belong in the current MAME distributions in my honest opinion.  With MAME we deal with the most current released binary and primarily care only to focus our energies on that release rather than listing commands or triggers that are no longer valid and are therefore unimportant.  MAME will warn you if there is a command in your .ini that is not recognize and a text list of such in a text file strikes me as needlessly redundant.

**Comment by NULUSIOS** [comment]
I understand what you say, but still think it's (plain and simply) useful.
In a few seconds someone can see why something that they think should work, doesn't (and even what replaced it -  if anything).
Docs are for users too, right? Not just devs.

Anyway, it is there, a tiny text file (and I could even maintain it) - if team says is not needed, so be it.

BTW I run mame64 (without parameters) both directly from desktop and from command line, with a fake entry in mame.ini and saw no warning whatsoever. (maybe a bad entry is a minor error that needs a higher debug level)

I guess we close this then?

**Comment by stilett0** [comment]
No one is saying you can't work on it, just that for now you can work on it and host it with someone like ProgettoSnaps.net :smiley:

**Comment by NULUSIOS** [comment]
Thanks.
It's just a text file though. Not sure how it would fit within Antonio's collection.
Anyway it is clear this will not go in the release.

**Pull request closed without merging**
