### PR TITLE
Moving single stepping logic from mame_ui_manager to video_manager

### PR DESCRIPTION
**Pull request by npwoods**
The logic to step single frames was essentially implemented in
mame_ui_manager, and having this logic here has a negative impact on the
ability to use it in worker_ui, which provides an alternative
implementation of ui_manager.

This change also has the effect of removing the single step property
from luaengine, which is positive because in practice it should have
been seen as an implenentation detail.

### CODE REVIEW

**Comment by cuavas** [comment]
The `video_manager` is already doing too much stuff that isn't actually related to video already.  Single stepping is a user interface function.  Pushing it into `video_manager` messes up the design even more.

**Comment by npwoods** [comment]
Perhaps there should be an intermediate abstraction that handles single stepping and frame skipping and similar activities that are not directly related to video emulation?

**Comment by npwoods** [comment]
To further clarify, while this might be a UI function, I am trying to figure out how to refactor things so that this is not tightly coupled to the MAME internal UI code, which queries for key assignments enumerated with IPT_* etc

**Comment by rb6502** [comment]
I'd suggest some kind of a frame_manager so that both OSD video and the video_manager can stop caring about frame timing and frame skipping and so on.

**Comment by u-man74** [comment]
... and if you really want to implement "interlace" output at some time, imho your option with a framemanager would be the best.

**Comment by npwoods** [comment]
I've just pushed an initial separation of the frameskipping and single stepping code from video_manager into a frame_manager class.

I'd like to hear comments, as the separation is not as clean as I would have hoped, as frame skipping, throttling and a few other things are pretty entangled.  I'm somewhat inclined to believe that the effective frameskip code should also move into frame.cpp, but throttling should not.

Thoughts?

**Comment by galibert** [comment]
interlace could be seen as the domain of the screen_device though.

  OG.

**Comment by galibert** [comment]
Eventually, throttling should exit the scheduler if we ever want to be nice
in a browser context.

  OG.

**Comment by cuavas** [comment]
Whatever the right thing to do it, this isn’t it. The video manager shouldn’t be doing user interface functions.

**Pull request closed without merging**
