### PR TITLE
lwriter.cpp: Implement switch setting.

### PR DESCRIPTION
**Pull request by jrmuizel**
Also change the mode to "Serial Batch Mode 9600 Baud"
from "AppleTalk".

The numbers correspond to documented values in
"Inside PostScript" (12-1)

### CODE REVIEW

**Comment by rb6502** [comment]
I appreciate that someone is looking at this driver!  Ideally this should be done as actual DIP switches.  You can add them to the currently empty "static INPUT_PORTS_START( lwriter )" block, and add a required_ioport object for the code to access them.  One relatively simple example would be the Apple II Super Serial Card emulation, in src/devices/bus/a2bus/a2ssc.cpp/a2ssc.h.

**Comment by jrmuizel** [comment]
I have it successfully booting to the postscript executive prompt with a collection of local patches. I'll look at hooking this up to the switch infrastructure.

**Comment by rb6502** [comment]
Thanks again!  This is almost perfect - just change the dip switch to actually set the 0x20/0x40 bits directly and then the code gets much simpler in the via_r() and we're good.

I'm also interested in whatever else you have that gets the PostScript executive prompt to come up, but let's clear this first.

**Comment by jrmuizel** [comment]
Done.

**Pull request merged**
