### PR TITLE
Fix for i8251 device driver

### PR DESCRIPTION
**Pull request by fulivi**
Hi,
I've just pushed a couple of changes to i8251 driver to improve handling of tx ready/empty flags.
Before these changes the HP64000 self-test on serial line failed.
Thanks.
--F.Ulivi

### CODE REVIEW

**Comment by Tafoid** [comment]
I noticed some regression which seem tied to the i8251 device changes.  It is important to at least give cursory checks to associated drivers which use a device you are working on for a current one.

In this case, these sets seem to have regressed and no longer show any text.  There may be more but this is based on screen comparisons of a 10 second test run for each.

sage2 - sage2.c
sdk80 - sdk80.c
softbox - softbox.c
xor100 - xor100.c

If you could please look at these, perhaps something driver level for each needs to be adjusted.
Thanks!
Tafoid

**Comment by fulivi** [comment]
Thanks for your mail.
I gave a quick look at the issue: it seems very simple to me. Before my
change to 8251 driver, the CTS signal was not being honored, whereas now it
is taken in account to see if the USART can transmit or not. Note that the
latter is a more accurate reproduction of the real device behaviour (see,
for example, the intel datasheet). So, by default the driver sets the CTS
signal to 1 (not active) at reset time. If no one is setting it to 0 the
transmission will never start (as it would have done in the real device).
What do you suggest to fix this regression, please?
- We set the CTS signal to 0 at reset (every driver that relied on
transmission to be enabled by default will see no change), or
- We change machine drivers to model the fact that in some hardware CTS was
permanently tied to 0.

Thanks.

-- F.Ulivi

**Comment by rb6502** [comment]
When smf made the 6551 respect CTS we had drivers where it's tied to 0 set it to 0 in the driver's reset function.  This makes the most sense in terms of moving hardware-specific things to the hardware without compromising the actual chip's accuracy.

**Comment by Tafoid** [comment]
Any movement on this before we go to release tomorrow?  We have about 12 hours to come up with a solution or it gets marked in an MT bug upon release..

**Comment by fulivi** [comment]
Sorry for late reply. If I understand the question correctly, the right
solution would be to add CTS=0 in the machine drivers needing it. This is
the reason I didn't do it myself, because I'm not an expert (nor have the
relevant documentation) of the affected machines.

**Comment by Robbbert** [comment]
This has now been fixed. Thanks Tafoid for finding it.
  -----Original Message-----

**Pull request merged**
