### PR TITLE
add apple2_cass tapes

### PR DESCRIPTION
**Pull request by Dagarman**
Additional apple 2 tapes.

Files are at https://www.sendspace.com/file/efmxcv

aligren and aligsam marked partial due to cassette sound not emulated
datamtel and aplstqrt marked partial/not supported due to modem not emulated
tapmatt marked not supported due to no tape measure prom

### CODE REVIEW

**Comment by rb6502** [comment]
What's a "tape measure prom"?

**Comment by Pernod70** [comment]
Why have you changed feature name="part_id" to feature name="label"?

The 'part_id' is recognised and shown in the UI, whereas 'label' is just a random tag.

**Comment by Dagarman** [comment]
I don't know what a tape measure prom is, but the label on the cassette tape states the requirement [http://www.brutaldeluxe.fr/projects/cassettes/apple/k7_apple_685000100_tapemeasure.jpeg](url)

**Comment by Dagarman** [comment]
I changed the feature name to be more descriptive as is the standard practice with many of the softlists. The driver doesn't use the feature, but I forgot that the UI displays the part_id. I'll fix the commit.

**Comment by Dagarman** [comment]
changed "feature name" data

**Comment by Dagarman** [comment]
I don't know what error message(s) mean where The Travis CI build failed. Appreciate any help in explaining this so I can fix it.

**Comment by Robbbert** [comment]
Next to the travis build is a "Details" button, click that and follow the errors, it's pretty obvious.

Anyway the error is:
**../../../../../src/frontend/mame/ui/selgame.cpp:961:15: error: operator '?:' has lower precedence than '<<'; '<<' will be evaluated first [-Werror,-Wparentheses]

        str << found ? _("Requires CHD\tYes\n") : _("Requires CHD\tNo\n");

        ~~~~~~~~~~~~ ^

../../../../../src/frontend/mame/ui/selgame.cpp:961:15: note: place parentheses around the '<<' expression to silence this warning

        str << found ? _("Requires CHD\tYes\n") : _("Requires CHD\tNo\n");

                     ^

        (           )

../../../../../src/frontend/mame/ui/selgame.cpp:961:15: note: place parentheses around the '?:' expression to evaluate it first

        str << found ? _("Requires CHD\tYes\n") : _("Requires CHD\tNo\n");**

**Comment by Dagarman** [comment]
Saw that and it doesn’t help because I wasn’t using any operators. I think the Travis build doesn’t parse the xml correctly so I will try changing the xml so it doesn’t think there is an operator

**Pull request closed without merging**
