### PR TITLE
tms9914: added SR & PP FSMs, typo fixed

### PR DESCRIPTION
**Pull request by fulivi**
Hi,

I've just added two missing FSMs in TMS9914 emulation (serial request & parallel poll). I've also fixed a typo reported by shattered (two bits swapped in a register).
Thanks.
--F.Ulivi

### CODE REVIEW

**Comment by usernameak** [comment]
Will try it out on my `gridcomp` branch.
I had a quick-and-dirty fix before, but your one is better

**Comment by usernameak** [comment]
Well, it works, but you still lack CIDS state implementation:

```cpp
			case FSM_C_CIDS:
				// sic | rqc -> CADS
				if (!controller_reset() && m_sic && m_c_state == FSM_C_CIDS) {
					m_c_state = FSM_C_CADS;
				}
				break;
```

**Comment by fulivi** [comment]
Leaving CIDS state is implemented but not in ``update_fsm`` function. It's part of SIC command handling (line 1447 in my latest version of tms9914.cpp). If there were no implementation of SIC the controller function of tms9914 would not work at all as it would stay in idle state forever.

**Comment by usernameak** [comment]
> Leaving CIDS state is implemented but not in `update_fsm` function. It's part of SIC command handling (line 1447 in my latest version of tms9914.cpp). If there were no implementation of SIC the controller function of tms9914 would not work at all as it would stay in idle state forever.

In fact, it *never* asserts ATN if I don't add that in update_fsm.

**Comment by fulivi** [comment]
Interesting, you might have found a bug! In HP Integral PC the controller function of 9914 works correctly, possibly because it uses the rqc aux command to start it instead of sic. Need more investigation.

**Pull request merged**
