### PR TITLE
atari/sprint8.cpp: Cleaned up input code.

### PR DESCRIPTION
**Pull request by 0kmg**
- Label gas and gear shift buttons. Set gear shift as PORT_TOGGLE as it is a high/low shifter. Starts in low gear now.
- Use finders for ioports, cut down on repeated code.

### CODE REVIEW

**Comment by 0kmg** [comment]
I think people must have thought the gear shift (button2) was a break pedal button. Holding it down put you into low gear before which kind of seemed like a break. Vice versa you were basically always in high gear before. Now with toggle and defaulting to low you can actually get off the starting line at the same pace as the other cars :)

BTW, it's hard to even find a decent pic of the machine much less any other info. There's this https://youtu.be/Zq2XmAaI028 video where if you pause at the right moment you can see a low/high shifter.

**Comment by cuavas** [comment]
Are you sure the shifter is actually a toggle?  Atari had a habit of using spring-returned two-speed shifters, and in that video, any time the guy uses low gear, he holds the shifter in position.  Starship 1 is another Atari game that you’d expect to have a toggle shifter where it’s actually sprint-returned.

**Comment by 0kmg** [comment]
I can't be 100% sure. There's this photo http://adb.arcadeitalia.net/media/mame.current/cpanels/sprint8.png?release=206 that shows at least one shifter in the up (low) position. I guess it's possible it could be that way due to the state of disrepair.

**Comment by cuavas** [comment]
I also don’t particularly like calling the accelerator “Gas” – it’s very US-specific, “gas” means “gas” in most of the English-speaking world.

**Comment by cuavas** [comment]
I’ll merge it for now, but I’d really like to see a service manual or something to find out whether the gear levers are supposed to be spring-returned.  Andy supposedly has a Sprint 8 manual.  I wasn’t able to find one with a quick web search.

**Comment by happppp** [comment]
1:13 in that video, yes it is a 'sticky' switch.

**Comment by 0kmg** [comment]
1:13, as in it looks like the guy's hand is hovering over the shifter and not really holding it up?

Anyway, are there any examples of non-toggling two gear shifters from Atari? It sounds like an incredibly bad design to have to hold a shifter in place. I looked at the Starship 1 example and it's not a shifter. It's spring-returned, but it's the throttle. It returns to the upward position, which is Slow, and one needs to pull and hold it down to go Fast.

My hunch with Sprint 8, given that there was no note in the driver, is that the author thought the gear shift was the brake pedal. One of the few common images out there for Sprint 8 is in the flyer, and it looks to be a mock-up or prototype model. It doesn't have a shifter at all and instead has two pedals.

**Comment by cuavas** [comment]
> 1:13, as in it looks like the guy's hand is hovering over the shifter and not really holding it up?

1:13 looks like he wasn’t holding it up, the movement of his hand makes it look like it’s a counter-weighted positive toggle shifter.  I’m satisfied it’s not spring-returned.  I just didn’t notice on the first play-though as it was so brief.

**Pull request merged**
