### PR TITLE
legionna.cpp, seibu_crtc.cpp, raiden2.cpp, r2dx_v33.cpp update

### PR DESCRIPTION
**Pull request by cam900**
legionna.cpp : Add notes, Fix oki clock, Fix denjinmk frame rate and year(title says 1994, and actually released at February 1994), Cleanup gfxdecode

raiden2.cpp : Cleanup gfxdecode, Fix configuration for xsedae, Fix oki clock for zeroteam, Add notes, Add object finders instead runtime tag lookups, Minor cleanups, Fix value names

r2dx_v33.cpp : Fix clock for nzeroteam/2000(PCB Hasn't 14.31818MHz XTAL), Add object finders instead runtime tag lookups, Minor cleanups, Fix value names

seibu_crtc.cpp : Add docs

### CODE REVIEW

**Comment by DavidHaywood** [comment]
you shouldn't be loading legionnire_back.u075 twice unless it was on the PCB twice, using ROM_COPY was correct

**Comment by cam900** [comment]
legionnire_back.u075 ROM has both Background("MBK") and Midground("LBK") area in Legionnaire, It seems like back-1.4y ROM on Seibu Cup Soccer.
I make it load only once and share gfx region between Background and Midground.

**Comment by angelosa** [comment]
> Demote Godzilla with MACHINE_IMPERFECT_SOUND, because oki bankswitching isn't verified/implemented

Demoting something out of a guess is a good way to not receive any MT report towards that. And considering Godzilla isn't exactly the most popular of the games that means it'll get in the backburner for many years at least.

**Comment by cam900** [comment]
This PR is outdated, close this

**Pull request closed without merging**
