### PR TITLE
Fix double key assignment acceleration and shifting in Four Trax

### PR DESCRIPTION
**Pull request by MASHinfo**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I thought we had a validity check that failed if there was a 'Button 3' defined without Buttons 1 and 2?

**Comment by happppp** [comment]
No there isn't one. pedal 1 and 2 default to the same inputs as button 1 and 2. This 'gear shift on button 3' workaround has been in a lot of drivers for ages.

**Comment by DavidHaywood** [comment]
Maybe there should be one?

**Comment by rb6502** [comment]
No, there shouldn't, for the reason hap stated.

**Comment by DavidHaywood** [comment]
That seems more like a failure of the code that creates the mappings?

**Pull request merged**
