### PR TITLE
Additions on the PSX softlist

### PR DESCRIPTION
**Pull request by arcadehistory**
[psx.zip](https://github.com/mamedev/mame/files/4353110/psx.zip)

I added three dumps (french releases) from **(admin EDIT: no poke URL -AS)** (account needed to download), then I converted the cue/bin to chd using chdman. I tested all and they work fine. If accepted, i'll add thousands of games in the futur, following this way.

PS: I don't know if it's the good way to submit an update for this big file but for some reason, I can't upload new hash files on the master branch...

### CODE REVIEW

**Comment by DavidHaywood** [comment]
why is this source not working with redump or similar in the first place? (and if they are, why single out this source?)

**Comment by arcadehistory** [comment]
Sorry, I didn't knew Redump has all french releases.

**Comment by DavidHaywood** [comment]
Well their 'missing PAL releases' list is rather short at this point in time...
http://wiki.redump.org/index.php?title=Sony_PlayStation_PAL_Missing_Games

**Comment by angelosa** [comment]
1. This PR is formally wrong, it just tries to merge psx_metafix into master with a diff attached to the message.
2. Rules for submitting rom dumps for inclusion are defined [here](https://wiki.mamedev.org/index.php?title=Submitting_Source_Code), I've edited the OP message to reflect this.
3. These dumps are already on redump.org and I'm not gonna bother to add these into the XML structure for the time being. It's not the purpose of the branch.

Obviously closing this off.

**Pull request closed without merging**
