### PR TITLE
cv1k.cpp: Add notes for pixel clock

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by p1pkin** [comment]
sorry, I'm not sure how your guess about possible pixel clock related to frame rate.
in this hardware 12.800 MHz XTAL clock goes to SH-3 CPU (and only to it), then internally multiplied by 4 and output as 51.2MHz to external devices, including FPGA which generates video, which might be internally divided in numerous ways.

anyway, if end goal was to determine actual/accurate frame rate - I've tweaked it to known measured values, see 95a91707d95d6dcd4931ab8e5ea425699d65a7df
is this PR may be closed now ?

**Comment by rb6502** [comment]
If you have known measured values, please set the full raw parameters.

**Comment by p1pkin** [comment]
I have only sampled CSYNC line data, where can be seen H rate, total lines count, Vsync duration and frame rate. we can not measure dot clock and total dots count, this hardware have no real video DAC IC, but simple resistors ladders.

**Comment by MooglyGuy** [comment]
What does the lack of a video DAC have to do with being "unable" to measure the dot clock or dot count?

**Comment by p1pkin** [comment]
because we have nothing to measure.
I'd imagine it will be possible to develop some homebrew, which will fill framebuffer with repeated black/white/black/white pattern, and then sample using logic analyzer one of color lines. but, such homebrew doesn't exists, and its also far not easy to run on real hardware, since all ROMs is soldered SMDs...

**Comment by p1pkin** [comment]
on other hand, special video DAC ICs often have some "CLK" line, and its trivial to measure

**Comment by cuavas** [comment]
This is just a guess, without either doing clock recovery on the video output or reverse-engineering the bitstream for the video chip, we can’t get a reliable figure.

**Pull request closed without merging**
