### PR TITLE
New features for the jedutil tool

### PR DESCRIPTION
**Pull request by keshbach**
- Added the ability to list all pal's that match a given jed file based on the total number of fuses
- Added a simple menu system that allows the user to choose the pal to use to generate the logic equations from a jed file based on the total number of fuses

### CODE REVIEW

**Comment by rb6502** [comment]
I like the functionality here, but why is it including ncurses?  That's not portable.

**Comment by keshbach** [comment]
I thought ncurses was portable.  What should I use instead?

**Comment by keshbach** [comment]
FYI I see the issue and I'm working on a fix.

**Comment by keshbach** [comment]
Portcurses was written by me from scratch to avoid any potential license issues with using a 3rd party Microsoft Visual Studio ncurses implementation.

I didn't use smart pointers because I felt it would be overkill for such a simple task.

Okay, I'll yank out the interactive feature.

**Comment by keshbach** [comment]
I'm going close this request and issue a new one where ncurses has been removed.

**Pull request closed without merging**
