### PR TITLE
Rewind feature and RAM savestates.

### PR DESCRIPTION
**Pull request by vadosnaprimer**
This starts the work requested in #2398. Rewind is also on @mmicko's [roadmap](https://github.com/mamedev/roadmap/blob/master/README.md#save-statesinp).

### How RAM states work.

Implemented using util::vectorstream. Instead of dumping m_save.m_entry_list to file, it writes them as binary to vectorstream. Compression is not used, as it would slow down the process. The header is written as usual, also in binary. When a state is loaded, the savestate data gets binary-read from vectorstream.

### How rewind works.

Rewind is optional, it can be turned off through MAME GUI while not running. Rewind capacity is available there too. Rewind step hotkey is available from the standard hotkey menu. In the debugger you have the "rewind" command ("rw" shortcut) that works the same as the hotkey.

Every time you advance a frame (pause step), rewinder captures a RAM savestate of the frame you were at. It does the same when you do step into/over/out in the debugger. Every time it captures a new state (and when you unpause), it marks as invalid all its states that go after the current machine time, because input might change, so they are not relevant anymore. It keeps their buffers allocated though, for future use. When rewinder runs out of allowed amount of savestates it can have, it invalidates the first state in the list and tosses its unique_ptr to the end of the list, then it uses its buffer to capture a new state. When you hit the rewind step key, or use "rewind" command in the debugger, it loads a state that is immediately before the current machine time. Invalid states between valid ones are not allowed to appear, as that breaks rewinder integrity and causes problems. Rewinder keeps its own set of ram states as a vector of unique_ptr's. All rewinder operations and errors get reported using machine().popmessage().

### icount

Since rewinder fully depends on accurate machine time, using it during debugging uncovered a bug in savestates that causes non-determinism. I fixed that with a one-liner, savestates created in the past are not going to work anymore.

### CODE REVIEW

**Comment by rb6502** [comment]
I love this and I'm going to merge it, but if you could add a "step backwards" command in the debugger it'd be even better :)

**Comment by vadosnaprimer** [comment]
You mean a GUI button? If some accelerator is attached to "rw", it'd work as well.

**Comment by mmicko** [comment]
this was totally unexpected :) thank you for this

**Comment by vadosnaprimer** [comment]
My plan is to wire up rewinder and ram states through lua as well. Saving/loading/flushing to usual save file.

**Comment by rb6502** [comment]
So the "rewind" command goes back one instruction?  That wasn't clear.

Wiring it up through lua should create a lot of interesting new use cases :)

**Comment by vadosnaprimer** [comment]
I feel like I need a new PR just to clarify that in debughlp.

**Pull request merged**
