### PR TITLE
Enc[r]apsulating nasty menu.cpp logic to move the selection

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by cuavas** [comment]
I'm working on encapsulating this stuff myself. It's not straightforward to make it wrap when it should, not wrap when it shouldn't, scroll as expected, etc. There's also code in derived classes that messes with the selection directly that needs to be considered. Could you hold off on this for a bit? I am looking into sorting it out, but it's intermixed with all the other stuff that's going on.

**Comment by npwoods** [comment]
My short term need was driven by the desire to have a selection_changed() protected virtual function, so my menu could know when the selection changed.  If you can eventually provide that hook, I can wait.

**Comment by cuavas** [comment]
Yeah I need a selection changed hook as well, but it requires that all derived classes are prevented from modifying the selection directly, too. As you know, the code is pretty nasty. I've been slowly untangling it. The drawing code for derived classes is actually split out now. The stuff for the multi-pane machine/software select menus have a common derived base that deals with a lot of their shared logic. It's just a lot to get through, and often not obvious where things are used or what logic is actually hit.

**Comment by npwoods** [comment]
Sounds good.  Closing out this pull request in light of your WIP.

**Pull request closed without merging**
