### PR TITLE
Converted Williams SC1/SC2 blitter to a device.

### PR DESCRIPTION
**Pull request by MooglyGuy**
First step towards breaking up the annoyingly spaghetti-y williams.cpp drivers.
Moving some of the control-bit checks outside of the inner blit loop seems to have given a slight improvement to performance, which is nice.

### CODE REVIEW

**Comment by ajrhacker** [comment]
The new source files need to be added to tiny.lua. The midway/wmg.cpp driver also needs to be updated.

**Comment by MooglyGuy** [comment]
Thanks for the heads-up. Addressing.

**Comment by MooglyGuy** [comment]
Fixed. I like the unnecessary function prefixes in wmg.cpp, very retro-MAME-standards.

**Comment by ajrhacker** [comment]
Not properly fixed with regard to tiny.lua.

**Comment by MooglyGuy** [comment]
Ugh, you're right. I found the first result for "williams" and wasn't paying attention. Having manufacturer-named files in shared is just awful.

**Comment by ajrhacker** [comment]
There's just an unused variable issue left. I'll take care of that.

**Pull request merged**
