### PR TITLE
Improved way to transform offsets for AM_DEVREAD/_DEVWRITE (nw)

### PR DESCRIPTION
**Pull request by ajrhacker**
In the past few hours AM_DEVREADWRITE_RSHIFT was created. This has made a lot of MAMEdevs (well, mostly R. Belmont) very angry and has widely been regarded as a bad move.

This patch replaces AM_DEVREADWRITE_RSHIFT with a similar but more functional-looking interface, which also now supports address line inversion as well as shifting.

### CODE REVIEW

**Comment by ajrhacker** [comment]
I would appreciate it if this weren't merged so quickly as #2586. The reason is while I like this quasi-functional approach, I have my doubts about the nomenclature. Some of these macros and inline functions probably deserve better names. (One of them was going to be called xor, but C++ now reserves that word.)

**Comment by rb6502** [comment]
I like this much, much better than _RSHIFT.  It doesn't sentence us to a new set of macros for each operation like that did, and the numbers are much less magical.  Thanks, good job!

**Comment by tedgreen99** [comment]
I'm not totally sold on using _OFFSET for the macro name.  I would much rather prefer something like _TRANS for translate/transform or maybe _MODIFY for the macro name.  To me _OFFSET immediately means add some value to the address which isn't necessarily the case.

**Comment by cuavas** [comment]
Yeah, `_TRANS`, `_XFORM`, `_MOD` or something as the suffix.  We've got very limited time until freeze, so can we get some more opinions on naming in ASAP?

**Comment by pmackinlay** [comment]
I like this. I like _TRANS or _XFORM as a suffix.

Is it too much to request an equivalent for AM_DEVICE? My system requires rshift<6> before the device map for an ncr53c94.

**Comment by ajrhacker** [comment]
@pmackinlay: Unfortunately AM_DEVICE works very differently from most address map macros; it has to dynamically import the handlers from the device's map and tweaks their offsets and masks. While its syntax may be designed to look like normal read and write mappings, it's less flexible in application than ordinary handlers (look at all the fatal error cases in address_map::uplift_submaps), which is why I've avoided it most of the time.

**Comment by rb6502** [comment]
I like _XFORM; it's less ambiguous than _TRANS without the extra typing of _TRANSFORM.  But since OG says the whole thing's probably going away for the new memory system I'm not too attached to any of those names.

**Comment by ajrhacker** [comment]
I decided to go with `_MOD` since it involves fewer keystrokes. I've also made `xor` usable with a little name munging.

**Comment by galibert** [comment]
To be precise, the *macros* are going to go away, to be replaced with
normal C++ methods.

  OG.

**Pull request merged**
