### PR TITLE
Implement 68k FPU FATAN instruction

### PR DESCRIPTION
**Pull request by NattyNarwhal**
Backports some Bochs SoftFPU code. That implements x87 FPATAN, but I believe that can do fractional atan, so one plus the single argument from FATAN should map the semantics. I'm not sure which argument order is correct though.

I wrote this because xeyes on Domain/OS needs it, but it seems like a lot of Mac media software wants it too.

Related to #8157

### CODE REVIEW

**Comment by rb6502** [comment]
As I said before this looks fine, but there's a Clang error that needs to be fixed before I can merge it:

../../../../../3rdparty/softfloat/fpatan.c:79:17: error: unused function 'propagateFloatx80NaNOneArg' [-Werror,-Wunused-function]

**Comment by DavidHaywood** [comment]
it's in 3rdparty, it needs submitting / fixing upstream, not here?

**Comment by DopefishJustin** [comment]
The makefiles should disable -Werror for 3rdparty/ IMO

**Comment by rb6502** [comment]
It's in 3rdparty/, but it's modified to get along with how MAME is set up.

**Comment by rb6502** [comment]
@NattyNarwhal Can you clean up the Clang error please?  I'd rather not apply it then fix the error and have the CI yell at my mailbox :)

**Comment by NattyNarwhal** [comment]
Sure, I was thinking of doing that today :)

**Pull request merged**
