### PR TITLE
aquarium.cpp : Updates

### PR DESCRIPTION
**Pull request by cam900**
Correct 5bpp gfx decode behavior into ROM data mixing, Fix naming, Simplify gfxdecodes, Reduce unnecessary lines

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I see you're doing the same thing here to expand the gfx as you did for Taito F3 etc.
@cuavas is this considered a 'good' way of doing it?
Essentially we now have a fake gfxdecode that makes it look like a 4bpp thing, then that gets modified in an init to put in the extra data.
The old approach was to use a correct gfxdecode, and copy the reformatted data into the region beforehand in the driver init.

Personally I liked the old approach better, but maybe this is considered more correct? Since cam now seems to be doing this to multiple drivers, it's probably best to check.

**Comment by cam900** [comment]
It's actually uses generic decoded data with extra data.

**Comment by DavidHaywood** [comment]
I find it very confusing tho, because now you have

static GFXDECODE_START( gfx_aquarium )
	GFXDECODE_ENTRY( "txt", 0, gfx_8x8x4_packed_msb,   0x200, 16 )
	GFXDECODE_ENTRY( "mid", 0, gfx_16x16x4_packed_msb, 0x400, 32 )
	GFXDECODE_ENTRY( "bak", 0, gfx_16x16x4_packed_msb, 0x400, 32 )
GFXDECODE_END

which at a glance makes it sound like pure 4bpp graphics, when it is really 5bpp graphics due to the expand function which is hidden away elsewhere that modifies the structures.

maybe it would be best to not have a GFXDECODE_START / GFXDECODE_END structure at all here and just do all the decoding in the expand function, it would be less misleading.

**Comment by DavidHaywood** [comment]
(I do prefer it with the current changes which show the 1bpp decode too at least tho, so yes that is also an option and less of a hybrid solution)

**Pull request merged**
