### PR TITLE
dpcplus - correct ARM speed, fix RAM, add ROM to map

### PR DESCRIPTION
**Pull request by kazblox**
most info taken from:
https://atariage.com/forums/uploads/monthly_03_2015/blogentry-3056-0-26480200-1425338924.png

### CODE REVIEW

**Comment by mamehaze** [comment]
pretty sure we can't just use 'AM_ROM' in this situation.

**Comment by kazblox** [comment]
right, since it's flash... commented that out

**Comment by mamehaze** [comment]
more that it's a CPU in a slot device, and I don't think it can automatically find the rom in this situation, I doubt being flash matters here because they're unlikely to be trying to check the flash ID or reprogram the chip ;-)

**Comment by rb6502** [comment]
CPUs in slot devices can absolutely find their ROMs automatically.

Check e.g. bus/a2bus/mouse.c - the 68705 finds its own ROM no trouble by standard means.

**Pull request merged**
