### PR TITLE
Revert "fixed some modernize-use-equals-default clang-tidy warnings (…

### PR DESCRIPTION
**Pull request by firewave**
…nw)"

This reverts commit 54486ab9

### CODE REVIEW

**Comment by firewave** [comment]
This completely reverts all the changes. I will clean up the auto stuff soon.

Sorry it took so long...

**Comment by Tafoid** [comment]
If I'm not mistaken, this is in release build for 0.219.   Should this be reverted there as well?

**Comment by firewave** [comment]
I think these changes were already in 0.218.

**Comment by firewave** [comment]
Thanks. Will take a look at the other "mess" I did soon.

**Pull request merged**
