### PR TITLE
Major D3D and BGFX code refactoring and bug fixes

### PR DESCRIPTION
**Pull request by MooglyGuy**
MAME Testers bugs fixed
-----------------------
- 08512: [Misc.] (osd/modules/render/bgfxutil.cpp) AddressSanitizer: heap-buffer-overflow with -video bgfx [Ryan Holtz]
- 08505: [Misc.] (osd/modules/render/bgfxutil.cpp) eggventr: Segfault on startup [Ryan Holtz]
- 07907: [Core] (drawbgfx): Prescale option doesn't work for bgfx video mode [Ryan Holtz]
- 07341: [Image Enhancement] HLSL & BGFX: HLSL Scanline_alpha zooms screen [Ryan Holtz]
- 07660: [Graphics] (osd/modules/render/bgfx/chainmanager.cpp) Toggle Full Screen bgfx screen chains reset to default [Ryan Holtz]
- 07586: [Graphics] (osd/modules/render/bgfx/chainentry.cpp) Artwork: screen combined with multiply-blend does not work on BGFX D3D9 [Ryan Holtz]
- 07587: [Graphics] (osd/modules/render/bgfx/chainentry.cpp) Artwork: multi-screen layer blending problem with BGFX [Ryan Holtz]
- 08084: [Misc.] New BGFX files interacting poorly with art/overlays in warpwarp.cpp games [Ryan Holtz]

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
This will be pretty good to get merged – it should improve behaviour in a log of corner cases.

It’s entirely possible I’m missing something obvious, so bear with me:
* In `renderer_bgfx::create`, it calculates `max_prescale_size` off the window size, and sets it on the chain manager when it constructs it at line 362.
* The chain manager then stores that in `m_max_prescale_size` and uses it to set maximum prescale factors, passing it to `chain_reader::read_from_value` and `update_target_sizes`.
* However I can't see where `m_max_prescale_size` can be updated if the window is resized.

My concern is that if someone starts `mame -video bgfx -window -nomax` or similar with prescaling enabled and then enlarges the window, `m_max_presale_size` in the chain manager will still be based on the small initial window size, so a smaller-than-expected prescale factor will be applied after the window is enlarged.

The code for saving/restoring slider state to XML config an probably be press-ganged into service for restoring state after toggling full-screen rather than the static array of chain numbers, but that can be done later and isn’t a blocker.

There’s some unnecessary copying of `std::string` in function arguments and calls to `.c_str()` in various places that are no longer necessary with improved logging functions, but none of that is new, and it’s all in startup code so not on the hot path.  All stuff that can be cleaned up another time.

**Comment by MooglyGuy** [comment]
I believe `target_manager::update_target_sizes` is the answer you're looking for. It could be that there's something I'm missing about the overall code structure, but `target_manager::update_target_sizes` should end up being called anytime there's a mismatch between the window height/width and the currently-stored height/width.

This means that anytime that window size changes, target_manager::update_target_sizes will be run, and if either dimension has changed, then `target_manager::rebuild_targets` will be run. This includes iterating over each guest-relative render target and using `bgfx_util::find_prescale_factor` to determine the actual prescale factor based on current data.

**Comment by firewave** [comment]
Awesome. I need a few days before I will be able to get a current build up and running to do tests.

**Comment by firewave** [comment]
The code for addressing the texture size looks straight forward and good. That should definitely resolve MT8512.

I am not too sure about MT8505 as that *might* have a different cause. But I didn't fully investigate that - yet.

**Comment by cuavas** [comment]
I’m going to go ahead and merge this.  Prescaling apparently works when expanding a small initial window, although it isn’t apparent why.  I’ll open an issue soon.

**Comment by cuavas** [comment]
First issue I’ve encountered is a crash-on-exit after toggling fullscreen:
* Run `mame -video bgfx -window -bgfx_screen_chains crt-geom -skip_gameinfo superx`
* Hit Alt+Enter to enter fullscreen
* Hit Alt+Enter to leave fullscreen
* Hit Escape to exit

It doesn’t seem to happen with the default screen chains, and it doesn’t seem to happen if you don’t toggle fullscreen.

```
#0  0x00007ff63b9b4356 in chain_manager::save_config(util::xml::data_node&) ()
#1  0x00007ff638490b58 in configuration_manager::save_xml(emu_file&, config_type) ()
#2  0x00007ff638492ac9 in configuration_manager::save_settings() ()
#3  0x00007ff6349c5cda in running_machine::run(bool) ()
#4  0x00007ff63845aa0b in mame_machine_manager::execute() ()
#5  0x00007ff63b0c6c19 in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#6  0x00007ff63b0c71cd in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#7  0x00007ff638455699 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#8  0x00007ff63c3af297 in main ()
```

**Comment by cuavas** [comment]
> First issue I’ve encountered is a crash-on-exit after toggling fullscreen:

Actually, it might not be a regression from this commit.  Saving BGFX slider configuration might need to be done a bit differently.

**Comment by cuavas** [comment]
Opened #10859 for tracking issues preventing bgfx from being enabled by default.

**Pull request merged**
