### PR TITLE
apple2_flop_orig, apple2_cass: Added latest dumps and improved metadata.

### PR DESCRIPTION
**Pull request by A-Noid33**
apple2_flop_orig: Added forty four working items and updated one item.
apple2_flop_orig: Redumped one item.
apple2_flop_orig: Improved metadata.
apple2_flop_clcracked: Redumped one item.
apple2_flop_clcracked: Removed two imperfect cracks.
apple2_flop_clcracked: Improved metadata.
apple2_cass: Added one not working item.

New working software list items (apple2_flop_orig.xml) 
-------------------------------
A Week That Changed The World [4am, yesterbits, A-Noid] 
Adventure in Time [4am, txgx42, A-Noid]
Animate [4am, A-Noid]
Bag of Tricks 2 (version 2.0) [4am, A-Noid]
David-DOS [4am, A-Noid]
Early Heroes of the Bible [4am, yesterbits, A-Noid] 
Federation [4am, A-Noid]
Israel's Golden Years [4am, yesterbits, A-Noid]
Measuring Economic Activity [4am, LoGo, A-Noid]
Moses Leads His People [4am, yesterbits, A-Noid]
Paul's Missionary Journeys [4am, yesterbits, A-Noid] 
Prince of Persia (interactive demo) [4am, A2_Canada, A-Noid] 
Science Toolkit [4am, A-Noid]
Searching for a King [4am, yesterbits, A-Noid]
The Bank Street Speller [4am, A-Noid]
The Bank Street Writer (version 1.3) [4am, A-Noid] 
The Bank Street Writer Tutorial (version 1.0) [4am, A-Noid] 
The Bank Street Writer Tutorial (version 1.1 1982-12-13) [4am, A-Noid] 
The Bank Street Writer Enhanced (version 2.6) [4am, A-Noid] 
The Bank Street Writer Enhanced Tutorial for ][+ [4am, A-Noid] 
The Bank Street Writer Enhanced Tutorial for IIe [4am, A-Noid] 
The Bank Street Writer Expanded (version 2.2) [4am, A-Noid] 
The Bank Street Writer Expanded Tutorial (version 2.2) [4am, A-Noid] 
The Bank Street Writer IIc (version 2.1 revision 1) [4am, A-Noid] 
The Bank Street Writer IIc (version 2.1 revision 2) [4am, A-Noid] 
The Bank Street Writer IIc (version 2.11) [4am, A-Noid] 
The Bank Street Writer IIc Tutorial (version 1984-06-27) [4am, A-Noid] 
The Bank Street Writer III (version 1.1) [4am, A-Noid] 
The Bank Street Writer III (version 1.4) [4am, A-Noid] 
The Bank Street Writer III Tutorial (version 1.1) [4am, A-Noid] 
The Bank Street Writer III Tutorial (version 1.4) [4am, A-Noid] 
The Bank Street Writer Plus (version 1.1) [4am, A-Noid] 
The Bank Street Writer Plus (version 1.4) [4am, A-Noid] 
The Bank Street Writer Plus Tutorial (version 1.1) [4am, A-Noid] 
The Bank Street Writer Plus Tutorial (version 1.4) [4am, A-Noid] 
The Boy Jesus [4am, yesterbits, A-Noid]
The Early Church [4am, yesterbits, A-Noid]
The Time Tunnel: Sports Edition [4am, A-Noid]
The Time Tunnel: The America Series: Early America [4am, A-Noid] 
The Time Tunnel: The America Series: The Presidents [4am, A-Noid] 
The U.S. Constitution: Nationalism and Federalism (version 1987) [4am, A-Noid] 
Trapshoot [4am, A2_Canada, A-Noid]
Wheeler Dealers (DOS 3.3 conversion) [4am, A2_Canada, A-Noid] 
Wizardry: Proving Grounds of the Mad Overload (version 2.0 01-JAN-82) [4am, A2_Canada, A-Noid]

Redumped software list items (apple2_flop_orig.xml) 
-------------------------------
Wizardry III: Legacy of Llylgamyn (version 4, 20-Aug-1983 update) [4am, A-Noid]

New not working software list items (apple2_cass.xml) 
-------------------------------
Wheeler Dealers [4am, A2_Canada, A-Noid]

Redumped software list items (apple2_flop_clcracked.xml) 
-------------------------------
Animate (4am crack) [4am, A-Noid]

Removed (apple2_flop_clcracked.xml)
-------------------------------
Animate (imperfect clean crack)
Bank Street Writer II (imperfect clean crack)

### CODE REVIEW

**Comment by cuavas** [comment]
Sorry, but the numbers don’t quite seem to add up.  I see 154 added `<software>` opening tags and 110 removed `<software>` opening tags, for a net change of 44.  But there are 43 working additions listed, one addition listed as not working, and two removals.  So shouldn’t there be a net change of 42 according to that?  Are there two additions not listed?  Or am I missing something?

**Comment by A-Noid33** [comment]
@cuavas One of the existing items was split.  I talked to 4am and he said that the Bank Rate Tutorials were separate products from the Bank Rate Software, so I split the tutorial and software for the Bank Street Write in apple2_flop_clcracked and properly renamed to "The Bank Street Writer Expanded (version 2.2).   4am confirmed that the crack exactly matched the newly dumped in apple2_flop_orig, besides the copy protection removal.  Also, there are 44 newly added in apple2_flop_orig.   So the numbers should match.

**Comment by cuavas** [comment]
Oh, the 43 is because of `wc` counting line endings, and Firefox not copying the ending of the final line in a triple-click-drag selection.  That makes sense.

**Comment by A-Noid33** [comment]
Here's the confirmation from 4AM:
[@a2_4am](https://mastodon.social/@a2_4am)
[@Anoid](https://mastodon.social/@Anoid) Disk 1 of that is "The Bank Street Writer Expanded v2.2" (all sectors match except protection artifacts) and disk 2 is "The Bank Street Writer Expanded v2.2 Tutorial" (all sectors match), and they should probably be renamed to match the woz.

**Pull request merged**
