### PR TITLE
found the rather obvious bug that was actually preventing the 2nd lot…

### PR DESCRIPTION
**Pull request by mamehaze**
… of lamps from working..

looked more at the MCU based on studying the (rather short) program, but the hookup so far doesn't work so continue to use the fake 2nd i8279..
it looks like the MCU really just implements a small set of the i8279 features?!

### CODE REVIEW

**Comment by mamehaze** [comment]
@johnparker007 you might want to check this, actual problem with 2nd lot of lamps was a bit dumb, the strobe wasn't hooked up at all, so the write handlers were being called, but doing nothing.

MCU needs a little more investigation so currently the handlers are nulled with a define, James might be right in that it was actually a limited replacement for a 2nd i8279 because they never needed the read features that the i8279 offered, although I find it bizarre that an MCU would be cheaper than an i8279

**Comment by james-wallace-ghub** [comment]
An element of the MCU use may be to just thwart bootlegging, like the CHR
chip in MPU4. With disreputable types apparently hacking the percentages
below legal minimum they had to be seen to act. Also, not surprised there's
stuff wrong with the lamping, I think I wrote bits of that based on Turbo
by Sega for the i8279 stuff.

**Comment by johnparker007** [comment]
This all sounds promising :)

I won't have a chance to properly look until tonight or potentially tomorrow night... bear with me :)

Actually I've still been getting side-tracked with this Maygay driver myself, trying to get the inputs matched up to the input map in the driver:

```
READ8_MEMBER( maygay1b_state::kbd_r )
{
	ioport_port * portnames[] = { m_sw1_port, m_s2_port, m_s3_port, m_s4_port, m_s5_port, m_s6_port, m_s7_port, m_sw2_port };

	UINT8 data = (portnames[(m_lamp_strobe + 2) & 0x07])->read();
	UINT8 swapped_data = BITSWAP8(data, 7, 1, 0, 6, 5, 4, 3, 2 );

	return swapped_data;
}
```

So with that code above, if you define input "59" as a key (from the MAME UI while game is running), that input puts in 8 test credits (have to reset machine each time you want to add another 8).  Then some of the main inputs are actually correct (Cancel, Hold 1, Hold 2, Hold 3, Hold 4 (probably), and Start).

So is that ok in terms of how this should be done in MAME?  As if so, I could perhaps figure out getting the rest of the inputs mapped at the weekend.

Also - I'll generate a bunch of internal layouts for Maygay, and see if I can figure out adding them in (GAMEL macro rather than GAME if memory serves correctly)...

**Comment by mamehaze** [comment]
are the lines swapped around on the PCB, or are the bits in the input ports just in the incorrect order? 

that really determines if it's the correct solution or not

**Comment by johnparker007** [comment]
I've no idea unfortunately, I could just see that the inputs are all there, just arranged differently to the input map (both in terms of the bits and the strobe channel).  The mapping is the same across all the working Maygay machines that I tried.

I have also twiddled the bits for remapping lamps on Maygay (fixes the lamp mapping, however - they may also be a case of me compensating for incorrect emulation at a lower level).

I can undo the committed lamp changes in the next couple of days, and just leave a comment instead explaining how they should be mapped?  It's a shame, but I understand it needs to be fundamentally correct to match the real hardware, rather than just working via what might be hacks :)

**Comment by james-wallace-ghub** [comment]
If the MCU/ 8279 works, that may be what's needed - the original version of this from my perspective was a bit hacky as I mainly set it up to check that the sampled sound emulation was sufficient.

**Comment by james-wallace-ghub** [comment]
Just a reminder that this stays open for comment if people want it to be, I remember driving myself slowly mad trying to work out why the inputs misbehaved, which it seems may have been fairly simple. As I recall we have an MCU dump somewhere which I presume we're using?

**Comment by mamehaze** [comment]
I guess the easiest way to tell with the bitswap might be (assuming it applies to them) how the dipswitches hook up, if we know which dip is which on the physical board, and they too need the lineswap to be in the right order, then the lineswap is almost certainly correct.  for lack of better knowledge it might just be best to go with 'whatever is compatible with existing layouts'

re: mcu, we load the mcu, and I now run it as a CPU, however I couldn't get it working properly, so currently we still use the extra i8279.  Looking at the MCU code it has nothing to do with inputs, it looks like it really was intended to act as a write-only i8279, it polls some lines in the main loop to make sure they're stable (probably the strobe) and in the interrupt(s) it reads in from another port, using the value on one read as an index, and the value on another as a value to store.

I'm a little surprised my hookup didn't work, but maybe i've misread / misunderstood something with the 8051 code, either way, since it exists only to implement a subset of the i8279, the 2nd i8279 works just fine.

our rom banking seems incorrect btw, at least if MFME is correct, in MFME 0x2800 - 0xd0ff (very weird range) is banked (either showing the upper or lower half of the rom) while 0xd100 - 0xffff always comes from the lower rom.  those ranges seem a bit arbitary to me (0x2800 makes sense, area below that is RAM, but 0xd100 as a banked ROM / fixed ROM split point is just plain weird, 0xd000 might make more sense, but I guess there must be a game that expects 0xd000 - 0xd0ff to bank or it wouldn't have been set up that way.

**Comment by johnparker007** [comment]
I can check more later, I'm sure it would be possible to reverse-engineer
the mapping to get them all working, as I was getting access to the various
(currently missing) inputs such as the coins etc when I was doing some very
quick experimenting this morning before work - I'd need to remap the
strobes as well as the bits though, the current order is wrong I think...

I will initially generate a selection of starter Maygay internal layouts
(of machines that are playable) and try get those into the driver with the
GAMEL macro... with a couple of adjustments to the converter it will then
be outputting clickable buttons/coinslots for the Maygay platform (provided
they're fixed MAME-side by the remapping approach, or some other way at a
lower level).

**Comment by johnparker007** [comment]
Incidentally a dadsfme member (wolf676) has been following these discussions on here, and helpfully posted these Maygay schematics for this hardware, if they are of any interest guys :)

https://dl.dropboxusercontent.com/u/15679918/converter/Maygay%20M1A%20Schematics.zip

**Comment by mamehaze** [comment]
schematics are always handy to have, not just for us, but especially owners of the hardware

**Comment by mamehaze** [comment]
btw the IC positions don't quite match up with the PCB pictures we've got, so I guess the schematics are for a different PCB revision (1B?) however, still handy to have :)

**Comment by johnparker007** [comment]
This was from the original thread from 2008:

http://www.fruitemu.co.uk/ib/index.php?/topic/3066-maygay-m1a-coincell-mod/


And what is perhaps a key comment:
"m1b has 2 8279 keyscan/matrix chips, m1a uses the 80c51 to replace one of
them."

... and also:
"check u35 on them, if it's an rtc (mc146818a) then it's m1b, if it's a
level shifter for the comport (mc1488p) then it's m1a."

**Comment by mamehaze** [comment]
yeah, u35 is a mc146818a on these, so they're the 1b schematics

also good to have it confirmed that 1b just uses 2x 8279 instead of the 80c51 in place of one of them.

probably still worth emulating the MCU for the sake of completeness and hooking that driver up to one of the earlier machines, but for simplicity most games can probably just run on the '1b' emulation with the 2x 8279 then.

**Comment by james-wallace-ghub** [comment]
If MFME has a different opinion on banking to our driver, go with MFME's. We can probably work out when M1A was used from dates, but the green board/red board stuff is beyond me.

**Comment by johnparker007** [comment]
Hey guys, I have just added 56 provisional layouts to the Maygay driver.  The reels are not yet transcribed, and there are some other issues, but I thought I'd get them in as a starting point.  It's easy for me to update them now they're in as I bugfix the converter, add reel symbol descriptions etc...

**Comment by james-wallace-ghub** [comment]
I'll take a look - I know that from the data you've supplied we're going to need more in terms of hopper emulation etc - but I'm not going to be able to catch that up for a while. Just wanted to let you know that there is something coming with that, as there's a lot of stubs in the MPU4 driver for it that need fleshing out.

**Pull request merged**
