### PR TITLE
devices/machine/jvsdev.cpp: Fix chaining resets

### PR DESCRIPTION
**Pull request by 987123879113**
Previously only the first device in the chain would receive the reset command, causing any slave devices to retain their assigned address after the reset. The desired behavior is for all slaves in the chain to reset.

### CODE REVIEW

**Comment by angelosa** [comment]
Does this finally fixes [bujutsu](https://github.com/mamedev/mame/blob/master/src/mame/konami/cobra.cpp) not registering credit inserted? 
If not do you have a possible culprit other than the misconfigured JVS in there?

**Review by angelosa — APPROVED** [review]

**Comment by 987123879113** [comment]
@angelosa I haven't tested bujutsu but I'll give it a go. 

For context of what I'm trying to fix: I'm working on emulating the Windy 2 JVS I/O device and tried chaining 2 boards together which is when I noticed the chain reset behavior was wrong. 

In my game in particular, the game would try to enumerate and set addresses to the attached JVS devices using the `f1` command while looking for a non-I/O debug-related JVS device. After that it would do a JVS reset and then round of another device enumeration + set addresses to look for proper Windy 2 I/O devices. The second time it would try to enumerate it would stop at the first device because the slave devices already had an address set which made the sense line trigger too early.

**Comment by 987123879113** [comment]
@angelosa No, it doesn't look like it fixed it. I have some ideas of what it might be, and it looks like these Cobra games have additional regional variants not currently playable in MAME that I could add, so I'll take a look at getting bujutsu's I/O while I'm messing with JVS things.

**Review by cuavas — CHANGES_REQUESTED** [review]
This isn’t the right way to do this stuff.  Calling `device_reset` from outside is pretty much always wrong, and it won’t properly reset anything using `device_interface` mixins.  It’s also going to do weird stuff with `device_reset` being called multiple times when the device tree is reset on start.

How does reset cascading actually work in real life?  It doesn’t actually have reset in/out as this kind of implies does it?  Isn’t JVS just multi-drop RS-485?  Shouldn’t all the devices on the bus respond to the reset command?

**Comment by 987123879113** [comment]
You're right, I thought about it again and this *should* be cascading down but it isn't (even with the current PR's code). 

I had a stare at the code again and I believe I found the actual reason it's not cascading down but it's going to take more time to rewrite. The code that would've cascaded wouldn't execute because it would always see at least 1 byte as "received" even if no messages actually returned data. 

ref requiring `recv_size` to be 0 here to cascade the message: https://github.com/mamedev/mame/blob/master/src/devices/machine/jvsdev.cpp#L79-L82

I threw in some debug prints to see the state when resetting and assigning addresses and the new code I just pushed looks right to me, while the other two don't.

Old:
```
Received reset on address 255
Received reset on address 255
Setting address to 1
Setting address to 2
Received reset on 2
Received reset on 2
Setting address to 1 (doesn't attempt to talk to device 2 after this)
```

Current PR's changes:
```
Received reset on address 255
Received reset on address 255
Setting address to 1
Setting address to 2
Received reset on 2
Received reset on 2
Setting address to 1
Setting address to 2
```

New changes:
```
Received reset on address 255
Received reset on address 255
Received reset on address 255
Received reset on address 255
Setting address to 1
Setting address to 2
Received reset on 2
Received reset on 1
Received reset on 2
Received reset on 1
Setting address to 1
Setting address to 2
```

The two resets weren't received by the slave in the current PR, whereas you can see it gets handled by both devices here.

**Comment by 987123879113** [comment]
@angelosa For a lack of a better way to contact you re: bujutsu

I've got coins working in my work branch now if you're interested in checking it out. I ripped out all of the old JVS code and replaced it with the JVS host I made for Hornet (https://github.com/mamedev/mame/pull/10559) and replaced the 3 generic JVS I/O devices with a single Windy 2 I/O device, fixed up the JVS sense detection, and then added a note about why the coins weren't working before (it was an undocumented interrupt bit that was stopping the function that updates coins from being called, bit checked in the func at 0x000018b0 on maincpu). I still have more work to do before I can upstream the required parts but this is a working example at least. https://github.com/987123879113/mame/commit/8a7875daa1a9ea64c0eb523b4d2276cb163f1567

**Pull request merged**
