### PR TITLE
xbox_nv2a.cpp: Get rid of game-specific hacks for literally every game in favor of a more accurate approach (nw)

### PR DESCRIPTION
**Pull request by MoochMcGee**

### CODE REVIEW

**Comment by MoochMcGee** [comment]
It works in outr2, so...

**Comment by yz70s** [comment]
Have you checked that it also works with the other games whose names are in the comments ?

**Comment by MoochMcGee** [comment]
No, but I did cross-reference with XQEMU, and this is how they do it.

**Comment by yz70s** [comment]
This patch does not work with crtaxihr (although with outr2 does)

**Comment by MoochMcGee** [comment]
well, it can't be an issue that has to do with the code modified here, because the xqemu approach works for every game it runs, which is TONS.

**Comment by yz70s** [comment]
Yes, but until that issue is found, this part should remain as it is now
Maybe xquemu has some way to reset the value of the DMA_GET register

**Comment by MoochMcGee** [comment]
@yz70s it does not. In fact, i checked all references to the dma get register, and there are no differences between this patch and xqemu. I guarantee more things will work with this patch than with your approach of game specific hacks for literally everything.

**Comment by MoochMcGee** [comment]
Also, game specific hacks go strictly against mame's philosophy, so if you're gonna tell me that my more accurate approaches aren't welcome, maybe you shouldn't have commit access.

**Comment by etabeta78** [comment]
it seems you're a bit shortsighted when it comes to MAME's philosophy. If a
game-specific hack allows to keep emulation development going on, then it's
definitely welcome, as long as it's not passed as a faithful implementation
of a real behavior.
when a better solution is available, *that does not stop progress on other
aspects of the emulation*, then the hacks shall go away.

maybe you shall study a bit more, before acting as a spokesperson about
MAME philosophy...

my 2c

**Comment by MooglyGuy** [comment]
+1 to what etabeta said. Please don't lecture a long-time MAME contributor on the core mailing list about the "MAME philosophy".

**Comment by PatrickvL** [comment]
It's unfortunate that an attempt to get closer to how real hardware works, and avoids game specific hacks, gets rejected. Why did this happen?

**Comment by anikom15** [comment]
I'm not sure, but I agree it's unfortunate.

**Comment by DopefishJustin** [comment]
It's unfortunate the submitter closed and deleted her own PR only 5 hours after submitting it and getting some negative feedback. That's not the same as a rejection.

A good start would be to do some debugging and find out why exactly crtaxihr breaks. The Chihiro support in MAME is still very work-in-progress and missing pieces so it's premature to insist on 100% no hacks at this stage even though that is of course the end goal.

**Comment by rb6502** [comment]
Yeah.  We like that it's closer to hardware and not keyed on each game's behavior, but at the same time it needs to be at least as functional as the code it's replacing.

If Mooch would like to debug the issue with Crazy Taxi HR (a good start would be finding out if XQEMU actually runs the Xbox version of Crazy Taxi High Roller in the first place) that would be win-win for everyone.

**Comment by stilett0** [comment]
@PatrickvL is the author of several cxbx rewrites and, IIRC, a contributor to XQEMU, so I think he'd know too?

**Comment by PatrickvL** [comment]
I only ever contributed to Dxbx and Cxbx-Reloaded. Not xqemu. So no, I wouldn't know.

**Pull request closed without merging**
