### PR TITLE
Arm64 travis fix

### PR DESCRIPTION
**Pull request by belegdol**
This PR fixes the arm64 build, but the CI needs to be moved from travis-ci.org to travis-ci.com. I am not sure who and how can do that.
s390x still fails due to insufficient memory and/or disk space. While having two working non-x86_64 arches would be better, having one is still better than not having any at all.

### CODE REVIEW

**Comment by belegdol** [comment]
travis-ci.org builds have ceased on 15th June. Are there plans for enabling travis-ci.com?

**Comment by cuavas** [comment]
The resource limits for the free tiers on Travis-CI just seem to be too low now.  I realise that running a business by giving stuff a way doesn’t work and they’re entitled to charge for their services, but I don’t think we can afford it.

**Comment by belegdol** [comment]
I thought travis-ci.com was meant to be free for open source projects as well but it appears that this has changed:
https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/4
Oh well, this is a shame. I hope we will not get too many alternative architectures breakage because of this.

**Comment by cuavas** [comment]
>I thought travis-ci.com was meant to be free for open source projects

It was while they were riding on VC funding.  Running at a loss initially to gain exposure is a pretty standard strategy for tech startups these days.  However, it’s not a valid long-term business model.  The investors do want to make their money back at some point.

**Pull request closed without merging**
