### PR TITLE
ZX Spectrum floating bus support

### PR DESCRIPTION
**Pull request by TwistedTom**
Added a floating bus behaviour, fixes a few games that rely on it.

### CODE REVIEW

**Comment by TwistedTom** [comment]
Doesn't break slot devices this time!

**Comment by cuavas** [comment]
@Pernod70 or @DavidHaywood can you test and/or comment on this?  You guys seem to know the Speccy better than most of us.

**Comment by DavidHaywood** [comment]
well it definitely needs to be emulated, although it should be specific to the models where it works if it isn't already.  I'm not too clued in on the exact details however.

**Comment by TwistedTom** [comment]
This change is just for the original 48k models. The 128k/+2 models have the floating bus which I was planning to add later (different driver). The later +2A/+3 etc. (Amstrad models) kind of do but it's quite different, I might add this if I can fiqure out the specifics. As for the many clones, I have no idea which do or don't have it, I will try to make it apply to the official machine only.

**Comment by p1pkin** [comment]
> As for the many clones, I have no idea which do or don't have it,

not sure about all clones, but very most of ex-USSR-made clones had no attributes read from port FF (but some of models had "floating" IM2 interrupt vector)

if I'm not mistaken, only clones which fully replicate original ULA logic and use 2x sets of DRAMs had this feature. but they was complicated, use more ICs, harder to debug, consume more power, not cost effective, etc etc. so, such clones was least popular from all.

**Comment by Pernod70** [comment]
I'm not able to test this right now, but if it doesn't break the slot devices then I have no objections. I really don't know enough about this behaviour to be able to comment on how correct this is.

**Comment by TwistedTom** [comment]
It's far from perfect but without any Spectrum memory/io contention support in mame it never will be. At least it allows those 6 games to run (5 of which haven't worked at all since slot device changes) and probably others I don't know about.

**Comment by TwistedTom** [comment]
I've changed it so only the official Sinclair model uses the floating bus, all clones are as they were, if anyone has knowledge of the clone machines they can just switch the machine spectrum_clone->spectrum.

**Comment by p1pkin** [comment]
@TwistedTom can you please recheck this implementation ?
it does break Beta-disk/TR-DOS floppy drive controllers, which use port FF for FDC status read, and do it as IN A,(FF), so upper address bits will be kind of random - previous register A value.

**Comment by TwistedTom** [comment]
The floating bus games and beta do clash on real h/w. The only thing I can think of is add a slot-device-type conditional check at the top ula_r, if the device is beta then pass the read on to the slot device. I think that would be correct as there's essentially no floating bus if beta is present as it overrides the port(s). Although I'm not sure offhand how best to check the slot device type, any suggestions?

**Comment by p1pkin** [comment]
> The floating bus games and beta do clash on real h/w.

afaik they don't, FDC IO ports normally disabled during game/basic/etc. except for special out port FCh, which bit 7 enable/disable all the other FDC IO ports. so in basic ROM or games port FFh will still return open bus.

**Comment by p1pkin** [comment]
I'd suggest change iorq_r() to return 2x 8bit values (or single 16bit) - actual data and "mask" which will indicate bits output by device.
also each device should combine own data/mask output (if any) and next expansion device output (if it exists). but I'm not sure which exact logic should be used.

another suggestion - forward iorq_w() through all the exp.devices chain, in a kinda broadcast way, like it is on real hardware (so several devices may handle same single port output).

**Comment by TwistedTom** [comment]
I agree with your suggestions, floating bus (what little support there was before this commit) and slot devices did coexist up until [https://github.com/mamedev/mame/commit/09f698ddc8f1e0ee0196f1069a3dc44a2e13b863](url). It's quite frustrating, I understand how that handful of games work but can't see a way to implement it without effecting slot devices. I'll see if there's anything I can do, if there's anything you can do, feel free, I wouldn't worry too much about breaking this commit, even though it was accepted I'm sure there's a better way of doing it.

**Pull request merged**
