### PR TITLE
Update dynax.cpp to label some unknown DIP switches for some Hanafuda games

### PR DESCRIPTION
**Pull request by gingerbeardman**
## `hanamai` (Hana no Mai)
Adds descriptions of 5 DIP switches:
- Start with 2 credits
- Start with 3 credits 
  (use both of these to Start with 5 credits)
  (use neither of these to Start with 1 credit)
- Censor genitalia (white circle appears on screen; there is still nudity & eroticism)
- Start each round with 960 points (enables you to buy any item every round)
- Reveal P2 cards (they're usually face down)

I have a feeling some DIPs that remain unknown control difficulty and some elements of the CPU play style. That's for another day.

## `hnoridur` (Hana Oriduru)
Adds descriptions of 3 DIP switches:
- Start rounds with 500 points
- Display debug number
- Moles on faces (nudity?)

## `hanayara` (Hana wo Yaraneba!)
- Moles on faces (nudity?)
- See all cheat cards

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Please leave this open until I figure out the following DIPS:
- Modest cutscenes
- CPU tends to call Koi-Koi (like they don't want to win)

**Comment by cuavas** [comment]
I checked these DIP switches myself and updated the ones where the function is clear.

**Comment by gingerbeardman** [comment]
@cuavas thanks for helping with these. Seeing as I'll be doing more of these I'll try my vest to learn from your edits here.

**Comment by cuavas** [comment]
Good luck with it, there are a lot of games, and the operator installation guides are hard to come by.  I do appreciate your effort probing what these do.

**Comment by gingerbeardman** [comment]
It's only Hanafuda games that I'm interested into doing this for, so it is a more manageable amount.

For years I've been playing every Hanafuda game I can find (total currently 256+) and just got round to Arcade games.

**Pull request closed without merging**
