### PR TITLE
Update freekick.cpp

### PR DESCRIPTION
**Pull request by gamez-fan**
Make Counter Run parent work

### CODE REVIEW

**Comment by ajrhacker** [comment]
Shouldn't this makeshift ROM be marked as BAD_DUMP?

**Comment by gamez-fan** [comment]
Yes it should definately be marked as a BAD_DUMP sorry i plain forgot to make it so

**Comment by mamehaze** [comment]
no, just no.

this is pointless, the bootleg rom (which is 100% of the CPU code and the only difference between a bootleg and original) is from a bootleg, adding it to the parent set achieves nothing.

the real rom still needs dumping, there's no point at all to doing this.

**Comment by gamez-fan** [comment]
Sure ok, i just thought it was better that the parent at least fuctions till such a time as the proper
and correct CPU for the parent is dumped i'll close down the request now.

**Comment by mamehaze** [comment]
it is not important that the parent set functions, it's important that the parent set fully documents that there's no dump of the CPU module from the original game, and therefore no code to run.

a dev is known to have one of these (although he's been saying that for several years now, heaven knows if it still works)  Ideally it would be sent to Charles who can do what he did for Free Kick.

**Pull request closed without merging**
