### PR TITLE
Add an external panel for the Ensoniq VFX family of keyboards

### PR DESCRIPTION
**Pull request by cbrunschen**
... with a websocket interface and an HTML/Javascript implementation that can be served over HTTP.

This was previously proposed with a different HTTP & Websocket server; in this pull request, the functionality has been ported un top of the web & websocket server that is exposed through the http_manager.

### CODE REVIEW

**Comment by cbrunschen** [comment]
I should mention how to use this:

I build & run using

> make -j6 SUBTARGET=mess SOURCES=src/mame/drivers/esq5505.cpp
> ./mess64 -w -rp ~/mame/roms sd132 -midiin 'IAC Driver Bus 1' -midiout 'IAC Driver Bus 2' -http

I connect to the front panel by visiting [http://localhost:8080/esqpanel/FrontPanel.html](http://localhost:8080/esqpanel/FrontPanel.html) in a suitable browser (I use Chrome), which loads the HTML and Javascript front panel code, and establishes the websocket connection.

**Comment by rb6502** [comment]
A few things having tried this:  first off, it looks and works great.

Secondly, MAME doesn't exit cleanly when running -http with one of the compatible Ensoniq drivers.  It does exit cleanly if I run some unrelated driver with -http.  (I'm testing on OS X Sierra 10.12.6 beta 5).

Here's the error and the backtrace:
mame64(6005,0x7fffbeaba3c0) malloc: *** error for object 0x7f9dad5af810: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

0   libsystem_kernel.dylib        	0x00007fffb5cd4d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffb5dc2457 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffb5c3a420 abort + 129
3   libsystem_malloc.dylib        	0x00007fffb5d29fe7 free + 530
4   libc++.1.dylib                	0x00007fffb4771dae std::__1::__shared_weak_count::__release_shared() + 44
5   mame64                        	0x000000010e16039a std::__1::__shared_ptr_emplace<websocket_endpoint_impl, std::__1::allocator<websocket_endpoint_impl> >::__on_zero_shared() + 26
6   libc++.1.dylib                	0x00007fffb4771dae std::__1::__shared_weak_count::__release_shared() + 44
7   mame64                        	0x000000010e150c65 webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint::~Endpoint() + 165
8   mame64                        	0x000000010e150b99 std::__1::__tree<std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint>, std::__1::__map_value_compare<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint>, std::__1::less<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable>, true>, std::__1::allocator<std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint> > >::destroy(std::__1::__tree_node<std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint>, void*>*) + 57
9   mame64                        	0x000000010e150b89 std::__1::__tree<std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint>, std::__1::__map_value_compare<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint>, std::__1::less<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable>, true>, std::__1::allocator<std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint> > >::destroy(std::__1::__tree_node<std::__1::__value_type<webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::regex_orderable, webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Endpoint>, void*>*) + 41
10  mame64                        	0x000000010e150de9 webpp::SocketServerBase<asio::basic_stream_socket<asio::ip::tcp> >::~SocketServerBase() + 265
11  mame64                        	0x000000010e15067e webpp::SocketServer<asio::basic_stream_socket<asio::ip::tcp> >::~SocketServer() + 14
12  mame64                        	0x000000010e142357 http_manager::~http_manager() + 455
13  mame64                        	0x000000010e14253e http_manager::~http_manager() + 14
14  mame64                        	0x000000010d81b18e mame_machine_manager::~mame_machine_manager() + 14
15  mame64                        	0x000000010d712853 cli_frontend::execute(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) + 99
16  mame64                        	0x000000010d81caf1 emulator_info::start_frontend(emu_options&, osd_interface&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) + 49
17  mame64                        	0x000000010d6fe789 main + 217
18  libdyld.dylib                 	0x00007fffb5ba6235 start + 1

**Comment by cbrunschen** [comment]
Hi,

I had just recently noticed the failure to exit cleanly and am going to
track it down and fix it. I shall do so in a new full request soon!

// Christian

**Comment by cuavas** [comment]
I think it's probably better to have this in at this point since work on the web server seems to have otherwise stalled.  @cbrunschen could you also address my comments on the commit in your next pull request?

**Comment by cuavas** [comment]
Also, you seem to have messed up a device class:
```
% ./mame64 -valid
3 errors, 0 warnings
Errors:
   Device esqpanel.cpp(esqpanel240) short name is a duplicate of esqpanel.cpp(esqpanel240)
   Device esqpanel.cpp(esqpanel240) name 'Ensoniq front panel with 2x40 VFD' is a duplicate of esqpanel.cpp(esqpanel240)
   Device esqpanel.cpp(esqpanel240) reports type '19esqpanel2x40_device' (created with '23esqpanel2x40_vfx_device')

Validity check failed (3 errors, 0 warnings in total)
```

**Comment by cbrunschen** [comment]
I will absolutely address all the comments!

Best wishes,

// Christian

**Pull request merged**
