### PR TITLE
Adding disasm code gun offset calc in comments

### PR DESCRIPTION
**Pull request by Pitou1**
I'm not sure if it's the right place, but I added the disasm code part into the comments - Pitou

### CODE REVIEW

**Comment by rb6502** [comment]
The comments in the disassembly seem to be made of descriptions of what each opcode does, rather than explaining how the algorithm works.  That's not very useful.

**Comment by Pitou1** [comment]
ok. I thought that would give a starting point to figure out how it's done. I do give some pointers in some places.

Again, the gun position itself is not modified in the game. It takes the coordinates and calculate a screen explosion position. I'm wondering how can we interact with the actual game code to inject calculated values (it also uses the values from the in-game calibration menu). From the driver, can we modify the screen position hit?

**Comment by holub** [comment]
Pretty old. Huh?

**Comment by angelosa** [comment]
Closing this off, outdated, review not addressed plus I'm against dumping multi-line comments on top of file head.

**Pull request closed without merging**
