### PR TITLE
attache: merged revisions and corrected name (nw)

### PR DESCRIPTION
**Pull request by Pernod70**

### CODE REVIEW

**Comment by mamehaze** [comment]
the name "Attaché" will probably end up being mangled by the cleanup script before a release.

**Comment by Pernod70** [comment]
any way around that? I did have to change the file encoding for the name to show correctly in MAME UI.

**Comment by mahlemiut** [comment]
You can use \xnn escape sequences.  Look at src/mess/machine/x68k_kbd.c for examples.

**Comment by Pernod70** [comment]
Thanks for the tip, will make the change and re-submit.

**Comment by Pernod70** [comment]
I changed the character to a literal a few days ago, any other reason it's not been merged yet?

**Pull request merged**
