### PR TITLE
Add support for dragging position-animated layout items.

### PR DESCRIPTION
**Pull request by aaronsgiles**
This is my attempt to enable dragging of position-animated layout items. The layout system has changed quite a bit since I first wrote it, so I'm not 100% sure this is the right approach, but it works. Please review and let me know of ways it could be improved.

### CODE REVIEW

**Comment by aaronsgiles** [comment]
(Test case for this is the sliders on the psr60 and psr70 layouts.)

**Comment by cuavas** [comment]
This isn’t the direction I’m going with this stuff.  It’s not a matter of improving the implementation, it’s diametrically opposed.

**Comment by aaronsgiles** [comment]
Can you elaborate?

**Comment by Gurudumps** [comment]
> This isn’t the direction I’m going with this stuff. It’s not a matter of improving the implementation, it’s diametrically opposed.

Eh? One of the most brilliant emulation programmers on this planet just did something really cool and you're trying to kill it off? It looks like you are completely opposed to the artwork system. You should be ashamed of yourself and quit now before you completely kill MAME and cause the remaining talented members to quit due to the apathy of the "leader" with his "diametrically opposed" ideas. Either that, or show us what you have that's better.....

**Comment by cuavas** [comment]
>It looks like you are completely opposed to the artwork system.

If anyone actually believes that, they clearly haven’t been paying attention.  I’ve put a huge amount of effort into improving the artwork system, and making it useful for things beyond the Space Invaders cabinet model.  Stuff I’ve added personally includes:
* Reusable groups, repeating loops, and sequence generator parameters
* Per-element blend modes rather than tying the blend mode to the layer
* Parameter animation (position and colour)
* Lua script bindings for state, position, and colour
* SVG assets, including inline SVG in layout files
* Per-view toggle controls
* Mathematically correct anti-aliased ellipse drawing
* Per-device internal layouts
* Screens referenced by tag

The history is public: https://github.com/mamedev/mame/commits/master?branch=mame0232&path[]=src&path[]=emu&path[]=rendlay.cpp

I’ve also actually documented it the layout format, and provided a layout scripting tutorial using worked examples:
* https://docs.mamedev.org/techspecs/layout_files.html
* https://docs.mamedev.org/techspecs/layout_script.html

>Can you elaborate?

This PR is at odds with what’s needed to deal with pen and touch input properly, further decouple aspects for flexibility, and improve scripting hooks.  Draggable elements will come, but this isn’t the way to do it.  I realise things are moving slowly, sorry about that.  Untangling the code enough for the stuff that’s already been added was a mammoth task, I have competing priorities, and I’m thin on the ground.

**Comment by Gurudumps** [comment]
If nothing gets broken and the changes only affect his driver, it wouldn't hurt to allow Aaron's changes now. Your vision of perfection might never eventuate and then all we're left with is a broken or unusable driver. At least with the changes it would be usable now, whereas your solution is vaporware. If by some pure miracle you do create perfection later you can always change what's there. MAME is full of things that are not 100% right. Are you now going to re-do the entire MAME tree so that it matches your perfect ideas? Or better in the real world, suggest something that Aaron can do so that his changes are accepted. We've already lost 90% of mamedevs, we don't want to lose more devs who move on because their code isn't your idea of perfection.  You seem to have forgotten who Aaron is and that much of what MAME is now was originally conceived by him (and others who are no longer on the team). You should make an exception for Aaron and allow him  to continue to do cool things which keeps him happy and we all win.

**Comment by cuavas** [comment]
>If nothing gets broken and the changes only affect his driver, it wouldn't hurt to allow Aaron's changes now.

It’s a core change, not a driver change.  It affects everything.  We’ll never get away from bad assumptions if we continue to add code that depends on them.

>Are you now going to re-do the entire MAME tree so that it matches your perfect ideas?

Well I already re-did the entire MAME tree for type-safe string formatting, machine configuration without macros, devcb3, and uniform device delegate configuration.

>We've already lost 90% of mamedevs, we don't want to lose more devs who move on because their code isn't your idea of perfection.

Former contributors have moved on, and new contributors have appeared over the history of the project.  One of the signs of a successful project is that it survives beyond the original authors’ involvement.  There’s more MAME development going on than ever.  We’re taking on more ambitious emulation targets, fixing stuff that may have been considered good enough in the past, and improving the framework.

**Pull request closed without merging**
