### PR TITLE
AtariGT: Add Primal Rage v2.3 Japanese

### PR DESCRIPTION
**Pull request by Lemon-King**
Made from a recent dump from my Primal Rage v2.3 Japanese board.

Service Menu Dates
OS: JAN 4 1995 18:25:45
MAIN: JAN 4 1995 18:28:24

### CODE REVIEW

**Comment by simzy39** [comment]
Great work! 

If it says '1995' on the menu, should the '1994' in the code be changed to 1995?

**Comment by Lemon-King** [comment]
I went with the date on the title screen which was 1994.

**Comment by FoxhackDN** [comment]
> I went with the date on the title screen which was 1994.

That's just the original copyright date. I would point out the build date somewhere, if possible (though that might mean doing the same with the other builds in MAME.)

**Comment by simzy39** [comment]
Do you if a 1.7 version exists? I am trying to confirm it.

**Comment by Lemon-King** [comment]
As far as I know a 1.7 and 1.9 exist. I've heard about a beta version but never seen it.

**Pull request merged**
