### PR TITLE
uzebox: adding sound emulation

### PR DESCRIPTION
**Pull request by felipesanches**
(It works but with terrible performance. Uzebox's DrMario song is recognizable even though the sound is choppy, full of noise).

### CODE REVIEW

**Comment by cuavas** [comment]
Once again, you're mixing spacing/indentation styles within your change.  Please clean this up.

**Comment by felipesanches** [comment]
I did notice it, sorry. And then I cleaned this up and amended the commit a few minutes after submitting this pull request. Please let me know if there's still any indentation mistakes to be fixed.

**Comment by felipesanches** [comment]
Oh! I see it now at src/mess/drivers/uzebox.c
I'll fix it now. Sorry.

**Comment by felipesanches** [comment]
Done. Please, let me know if that's good now.

**Comment by cuavas** [comment]
There's still a mess with positioning of braces and space between `if` and the opening parenthesis.  The rest of the file uses this style:

    if (foo)
    {
    }
    else
    {
    }

But there are places where you've used `if(foo)` (no space between `if` and the parenthesis) and placed braces on the same line as the `if` and `else`.  It's inconsistent with the rest of the function, and not even completely consistent within your change.

**Comment by felipesanches** [comment]
I've just updated the if/else code-style.

**Comment by Tafoid** [comment]
If you are adding sound unless you know it is 100% correct, please flag the
driver as GAME_IMPERFECT_SOUND.  Leaving this empty if the sound is not
100% correct encourages bug reports for things that are already known.

Also, regardless of how slow the emulation is.. using "-wavwrite xxxx.wav"
will record a wav file at the proper emulation speed letting you know if it
sounds correct even if performance suffers and causes stuttering/glitching
in real time.

**Comment by felipesanches** [comment]
Thanks for that tip, Tafoid! I have just updated the commit to include the GAME_IMPREFECT_SOUND flag.

Indeed, when listening to the recorded WAV file, the sound is much better, but not yet perfect. I hear a sort of high frequency noisy hiss in the recording. Maybe this is an artifact of the PWM used to generate the sound? I recall that the hardware design contains a filter in the sound output. Maybe it is meant to remove this high pitch noise ?

**Comment by felipesanches** [comment]
yeah, using the speaker_sound_device resulted in much better sound quality. Still bad in runtime. But much better when dumped to a wav file.

The resulting wav file still has some minor background noise, though... But definitely much better than with the DAC sound device!

**Comment by felipesanches** [comment]
I'm happy with this implementation. It is not great in terms of performance, but it is surely an improvement over the current master. I'll be glad to have it merged if you do not have any other pending issue regarding this implementation.

If I come up with a way to improve it's performance I can easily open a new pull request in the future.

**Pull request merged**
