### PR TITLE
Removal of macros that hide parameters and names

### PR DESCRIPTION
**Pull request by mmicko**
As agreed sending my pull request for first simple removing of macros that hid implementation calls.
MACHINE, SOUND, VIDEO START/RESET macro removal (nw)

### CODE REVIEW

**Comment by mmicko** [comment]
Just to add that there is no issues regarding conflicts and possible additional changes we need, I have created a tool to help me with this so it is much faster to change/update

**Comment by mamehaze** [comment]
I can understand why this is being done, but at the same time I do wonder if it's wise.

The macros do hide parameters, but they also enforce standards.  Without them it becomes easier to write code that doesn't pass all the parameters around which later on can cause problems if the code needs to be re-purposed to work with elsewhere else in MAME.

They things like the read/write handlers for bytes/lines also make it very clear from a documentation point of view if something was a line or something was a byte, they enforce a naming standard which makes the code easier to read.

The cleanups that were done in the past to use the macros wherever possible, and enforce some standards that way actually helped a lot, and while from a pure 'clean code' perspective this makes sense I do wonder if it isn't actually going backwards and undoing a lot of the hard work people did before while potentially making things more difficult to maintain going forward.

**Comment by cuavas** [comment]
If you don's provide all parameters, the memory system won't swallow it.  The signature has to match or it won't bind.  The read/write line members are obvious because they don't have the address space and offset, and they use unspecified size `int`.

**Comment by ajrhacker** [comment]
Vas, what you don't mention is that `int` is anything but an "obvious" representation of line state.

I do think that making the parameters to memory handlers explicit is a good idea (because it's easy to forget what the parameters are named when so many handlers don't use the mask or even the offset), but in some other cases I don't think the signatures have been so well thought out; for instance, modern C++ code shouldn't have to pass around random chunks of optional data as `void *` pointers.

**Comment by mamehaze** [comment]
Well I was more taking about cases where we have read/write handlers that aren't called directly by the memory system, but by other functions.

it was still nice form, and a decent tidy up to have them as read/write handlers because they serve the same purpose, ensuring everything got passed down, same parameter order, same names etc.  with a clear purpose.  It made reusing the code inside them easier if you ever did need them to be used as real memory handlers.  A lot of effort was put into cleaning things like that up in the past (not by me, but in general)

With that structure gone I can see things diverging more outside of the direct calls from the memory system, and I'm not entirely sure that's a good thing.

**Comment by mmicko** [comment]
well line state should be

enum line_state
{
CLEAR_LINE = 0,
ASSERT_LINE,
HOLD_LINE,
PULSE_LINE
};

or better use enum class. As I told it is not a problem to do all changes
again, this is just playground to see what would be best solution and how
will all look after changes.

**Comment by mmicko** [comment]
Moving all work to separate branch on main git repo, for better coordination with others

**Pull request closed without merging**
