### PR TITLE
MPU4 Video promotions after some testing / input fixups / set fixups

### PR DESCRIPTION
**Pull request by DavidHaywood**
machines promoted to WORKING
------

The Crystal Maze (v1.3) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The New Crystal Maze Featuring Ocean Zone (v2.2) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Crystal Maze Team Challenge (v0.9) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Mating Game (v0.4) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Adders and Ladders (v2.1) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Strike it Lucky (v0.5) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Barquest (v2.6) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Tetris Payout (BWB TET1 Version 2.2, set 1) (MPU4 Video)  [Ryan Holtz, James Wallace, David Haywood, Angelo Salese]
Blox (SJM BLOX, 50p/20p Play, Version 2.0) (MPU4 Video)  [Ryan Holtz, James Wallace, David Haywood, Angelo Salese]
Prize Tetris (BwB) (MPU4 Video)  [Ryan Holtz, James Wallace, David Haywood, Angelo Salese]
Vegas Poker (prototype, release 2) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood, Highwayman]

clones promoted to WORKING
-------
The Crystal Maze (v1.2) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Crystal Maze (v1.1) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Crystal Maze (v0.1, AMLD) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The New Crystal Maze Featuring Ocean Zone (v2.0) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The New Crystal Maze Featuring Ocean Zone (v0.1, AMLD) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Crystal Maze Team Challenge (v0.8) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Crystal Maze Team Challenge (v1.2, AMLD) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Adders and Ladders (v2.0) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Strike it Lucky (v0.53) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Prize Space Invaders (BWB INV1, 50p/30p Play, Version 1.2) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood, Angelo Salese]
Tetris Payout (BWB TET1 Version 2.2, set 2) (MPU4 Video)  [Ryan Holtz, James Wallace, David Haywood, Angelo Salese]
Prize Tetris (BwB) (Showcase) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood, Angelo Salese]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
btw can I not use £ in the set description? it seems to mess up the display, but at the same time isn't throwing a validation warning?

**Comment by angelosa** [comment]
What happens if you try with `\u00a3`?

**Comment by happppp** [comment]
You mean the game title string? It will look ok in the internal UI and on the (Windows) titlebar. But it will break when this string is output on the commandline for example with "mame.exe nearlygamename" and it will give a list of games, the ones with unicode in title or companyname will have garbled text.

**Comment by DavidHaywood** [comment]
well \u00a3 works better for the UI at least, and it seems we accept commandline breakage so I guess I should change it to that?

**Comment by ajrhacker** [comment]
I think it's acceptable. MAME already uses Unicode in some system names, and at least my OS X terminal window doesn't give garbled text in response to `./mame64d -ll pvmilfin`. Not using escape codes for non-ASCII characters in strings may still cause problems, especially if a source file is committed with an encoding other than UTF-8 (as happened recently in a20013147862dc9381860e97692546690db7e319).

**Comment by happppp** [comment]
British pound symbol in utf8 hex is: \xc2\xa3

**Comment by cuavas** [comment]
"Prize Tetris (BwB) (Showcase) (MPU4 Video)" is listed as promoted here, but the not working flag was not removed in the source.  Which is correct?

**Comment by DavidHaywood** [comment]
in the latest source it is set to working

GAME(  1994, v4pztet,    0,        bwbvid,     v4pztet,    mpu4vid_state, init_bwbhack,     ROT0, "BWB",           "Prize Tetris (BWB) (MPU4 Video)",GAME_FLAGS_OK )

**Comment by cuavas** [comment]
OK, but specifically, was it already working when this was committed, or did it only start to work at some point after this?  I’m trying to reconcile everything for 0.223 here.

**Comment by DavidHaywood** [comment]
It worked here, it even seems to be marked as working in this diff, just the setname was swapped later when the sets were fixed up.

from this diff
GAME(  1994, v4pztet,    0,        bwbvid,     v4pztet,    mpu4vid_state, init_bwbhack,     ROT0, "BwB",           "Prize Tetris (BwB) (MPU4 Video)",GAME_FLAGS_OK )
GAME(  1994, v4pzteta,   v4pztet,  bwbvid,     v4pztet,    mpu4vid_state, init_bwbhack,     ROT0, "BwB",           "Prize Tetris (BwB) (Showcase) (MPU4 Video)",GAME_FLAGS_OK ) // screen telling you to exchange tickets for prizes in the 'showcase' during attract

**Comment by cuavas** [comment]
I see, all the short names were rearranged out from under it.

**Comment by DavidHaywood** [comment]
yeah, setnames are in a state of flux as things are researched and corrected.

**Pull request merged**
