### PR TITLE
nes.xml: Added a couple large dumps.

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions
-----------------------------------
Super Games 143 in 1 (HKMK-143) [Consolethinks]

New NOT_WORKING software list additions
---------------------------------------
Game 500 in 1 (alt) [Consolethinks]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I imagine a lot of these larger ones / newer dumps were dumped by actually dumping a single Flash chip, so the 'baddump' flag really shouldn't apply.

(personally I think it should be removed from the dumps in here anyway, it was used because most were made by manually splitting .nes files into prg/chr ROMs, and the actual number of each was unknown, but it's sending out completely the wrong message)

**Comment by 0kmg** [comment]
@DavidHaywood I 100% agree. I don't know why only the NES list does this. There are lots of unverified dumps across the software lists but it seems only NES marks everything baddump as a rule. As a newb I never really felt I had the authority to change the policy as it's explicitly written in nes.xml. I suppose the best thing would be to change that comment. The half of the list above is supposedly verified carts in Bootgod's DB and everything below that could simply be considered unverified save for a few cases where dumps are genuinely thought to be bad.

**Comment by etabeta78** [comment]
On Sat, Mar 26, 2022 at 7:13 PM 0kmg ***@***.***> wrote:

> @DavidHaywood <https://github.com/DavidHaywood> I 100% agree. I don't
> know why only the NES list does this. There are lots of unverified dumps
> across the software lists but it seems only NES marks everything baddump as
> a rule. As a newb I never really felt I had the authority to change the
> policy as it's explicitly written in nes.xml. I suppose the best thing
> would be to change that comment. The half of the list above is supposedly
> verified carts in Bootgod's DB and everything below that could simply be
> considered unverified save for a few cases where dumps are genuinely
> thought to be bad.
>
> The original motivation was that the NES situation is way worse than the
one for other systems: most dumpers never cared for documenting the boards,
until Bootgod started doing properly. As such, I had left anything else
marked as bad dump.

Of course, things improved in the past 7 years, so that I think a lot of
stuff which has been finally documented (bootleg boards analyzed on nesdev,
dumps from trusted sources like TeamEurope, etc.) could definitely have the
flag removed. OTOH, dumps which got extracted from chinese forums and
possibly hacked, shall be left as potential bad dump.

my 2c

**Comment by 0kmg** [comment]
Thanks for the input @etabeta78. *sigh*, yeah, I suppose that's a big problem, since I don't necessarily know the origin of many dumps. I guess I'd have to work piecemeal. An easier first step would be removing bad dump status from official carts but otherwise leave them in the not fully documented section. There isn't PCB info on them, but now we know for certain reasons that the NoIntro DB they match is correct.

**Pull request merged**
