### PR TITLE
HLSL shader improvements

### PR DESCRIPTION
**Pull request by ImJezze**
I'm working on some improvements and additional features for the HLSL shader implementation. There are still unfinished tweaks on my list, but I'm quite happy with the results so far.

I would be pleased, if you merge the current changes into the official MAME/MESS codebase.

### CODE REVIEW

**Comment by rb6502** [comment]
Could you describe briefly what this fixes/improves please? :)

**Comment by cuavas** [comment]
He describes it in detail in the commit message for a70198a.  Expand it by clicking the "...: above.  I really don't see how you could make it brief given all the things he's done ;)

**Comment by ImJezze** [comment]
As Cuavas said. :)

But in addition and for documentation I could show you some before and after results of changes that are described too briefly.

**Comment by rb6502** [comment]
Ahh, my bad.  Thanks! :)  I'll apply this later today if nobody beats me to it.

**Comment by rb6502** [comment]
Jezze, could we get a preferred license for your changes?  Most of the project's going with either BSD-3-Clause or GPL, but pick whatever you like.  Thanks!

**Comment by ImJezze** [comment]
I'm not quite familiar with all the difference between those licenses, but I want that source changes will be reflected back to MAME. I think the GPL ensures that.

**Comment by Lord-Nightmare** [comment]
There's definitely still a few HLSL issues, even with this patch. For instance, adjusting the screen curvature causes the scanlines to diverge at the screen edges rather than converge, which looks very weird and unrealistic; the scanlines should follow the screen curvature and the input pixel lines exactly.
(I used the canon cat 'cat' MESS driver as an example, as that driver would benefit greatly from HLSL due to its prominent scanlines and extremely long phosphor persistence in real life)


Also (and this may be unrelated to this patch in particular), resizing the window in windowed mode seems to cause the hlsl slider settings as set in the tab menu to reset themselves to whatever was loaded from the .ini (or whatever was default); the changed slider settings don't seem save at all even within a single mame/mess session.

**Comment by u-man74** [comment]
off course there are still HLSL issues... but this patch correct and improve many things, that existed in prior versions and is an overall improvement and not the opposite. i got moire effects either with low prescale settings or extreme settings with HLSL, so my advice is to find good average settings.

you cant "save" slider settings, that feature was removed long time ago. the only way to keep your settings persistent, is to change them in your .ini settings. see the slider-function as a preview for changes that you do later in the .ini settings or a quick way to change HLSL for your current game that you play.

did the resizing error exist prior this patch?

**Comment by Lord-Nightmare** [comment]
Yes, the cause of the resize error existed prior to this; I edited my report above (you can see it on the github page); The cause of the "diverging" lines is not caused by your patch, it is a moire artifact caused by scanlines being so thin that whatever the next texture is which samples the scanline-applied texture in the hlsl 'stack' causes pseudo-scanlines to appear in a moire pattern. I'm not sure the best way to fix this.

**Comment by u-man74** [comment]
i just want to clarify... its not my patch... its Jezze´s one. He has done all the work and it is his effort. 
I am just a fanboy, nothing more ;) .

**Pull request merged**
