### PR TITLE
fix a Genesis VDP status bit which was breaking Mega Play 68k->Z80 comms

### PR DESCRIPTION
**Pull request by devinacker**
A bit of a strange one this time, hopefully I can explain it well enough...

This fixes the "odd interlace frame" bit in the VDP status register so that it is only set if interlace is actually enabled. Believe it or not, this was actually the cause of the 68k/Z80 communications issues in Mega Play games that were causing the two CPUs to get confused about the current game state.

This appears to fix all of the sets in megaplay.cpp, but I'll use some 68k code from Sonic 2 as an example.

Every frame, the game checks the "odd frame" bit here, and sets/clears a flag in RAM accordingly:

```
ROM:000003AE                 move.w  ($C00004).l,d0
ROM:000003B4                 btst    #4,d0
ROM:000003B8                 beq.s   loc_3D0
ROM:000003BA                 move.b  #$40,($FFFFAE).l ; interlace odd frame = set flag in RAM
ROM:000003C2                 move.b  #$40,($A10007).l
ROM:000003CA                 movem.w (sp)+,d0
ROM:000003CE                 bra.s   loc_3E2
ROM:000003D0 ; ---------------------------------------------------------------------------
ROM:000003D0
ROM:000003D0 loc_3D0:
ROM:000003D0                 clr.b   ($FFFFAE).l     ; otherwise clear it
ROM:000003D6                 move.b  #0,($A10007).l
```

Later on, when the 68k sends a message to the BIOS, this flag is (for whatever reason) repeatedly ORed with the data being shifted into the I/O port:

```
ROM:000012D0                 rol.w   #2,d0           ; write next two bits into the I/O port
ROM:000012D2                 or.b    ($FFFFAE).l,d0  ; bitwise-OR the odd frame flag into the remaining data, for some reason
ROM:000012D8                 move.b  d0,d6
ROM:000012DA                 andi.b  #$43,d6
ROM:000012DE                 move.w  d6,d4
ROM:000012E0                 ori.w   #4,d4
ROM:000012E4                 move.b  d4,($A10007).l
[...]
ROM:000012F8                 move.b  d6,($A10007).l
```

As a result, if that flag in RAM is set while this is happening, it causes the wrong data to get shifted out, which was resulting in the BIOS frequently missing messages from the 68k and leaving the game in a weird state as a result.

The VDP fix was checked against the VDP implementation in Blast'Em, and all Mega Play games appear to work fine as a result of the fix.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I would definitely have never suspected that!

**Comment by angelosa** [comment]
Weirdly enough the correlated ODD bit in Sega Saturn VDP2 is supposed to be always 1 when interlace is disabled, at least according to docs. May be the same as here tbh.

**Comment by DavidHaywood** [comment]
This doesn't seem entirely fixed btw, Shinobi III has a tendency to hang when you insert a coin.

(also Streets of Rage 2 intro is in Japanese, but that's probably a different issue)

**Comment by devinacker** [comment]
Hmm, that's weird. I didn't have any trouble adding credits in Shinobi when I was testing it but I think I only did it at the Mega Play screen, the actual title screen, and when continuing, which all seem to work okay. I'll check out the other things you mentioned though.

**Comment by DavidHaywood** [comment]
yeah, it works if you insert a coin straight away, but if you leave it to hit the intro scroller it fails every single time from what I can see

**Comment by devinacker** [comment]
It looks like the BIOS is resetting the 68k after coining up (like normal), then the BIOS sends a command to start running the game (`call $324A` with HL=FF02) but the game somehow misses it and just keeps waiting endlessly for it.

**Comment by DavidHaywood** [comment]
based on what you've said, if you reduce the menu CPU to about 73% of normal speed it doesn't send it before the 68k has a chance to see it.  73% is too significant for it to be a slight timing issue somewhere however, so I guess the menu CPU should be waiting on something that it isn't waiting on to know the 68k is ready again?

**Comment by DavidHaywood** [comment]
(either that or something is significantly slowing down the 68k that shouldn't be when it's reset, maybe excessive interrupts if they're meant to have been disabled but weren't?)

**Comment by devinacker** [comment]
Looking closer, it seems like the 68k is receiving and handling the commands from the BIOS just fine, but probably earlier than it's meant to...

Normally on boot, the game clears a "game ready" flag in RAM:

```
ROM:000004A6                 move.b  #0,($FF0026).l
```

During the vblank interrupt, when it gets the "start the game" command from the BIOS, the game sets the flag:

```
ROM:0003962C loc_3962C:                              ; CODE XREF: ROM:00039606j
ROM:0003962C                 move.b  #4,($FF0026).l
ROM:00039634                 rts
```

For whatever reason, when trying to coin up from the intro scroller, the flag gets cleared about 15-20 scanlines *after* the vblank interrupt sets it in response to the command from the BIOS. So I'm not sure if the vblank interrupt is just firing earlier than it's supposed to in this case or what.

**Comment by DavidHaywood** [comment]
I wonder if the corruption you get on Grand Slam when you insert a coin is related.  Something going out of sync?

**Comment by devinacker** [comment]
Possibly related to both, the debugger shows that the vblank interrupt is firing at y=186 rather than 224 or 240 like I'd expect it to.

**Comment by DavidHaywood** [comment]
yeah that definitely sounds like a problem.  I suspect some timers need resetting / stopping then?

**Comment by DavidHaywood** [comment]
it's been so long since I did anything with the code I honestly can't remember.

**Comment by DavidHaywood** [comment]
I do remember that at one time I started trying to rewrite the emulation to use the screen device for timings rather than its own timers, hence m_vdp->set_alt_timing(1); in segac2.cpp, although IIRC that requires some other plumbing to be changed, and caused issues with other things, so the effort kinda stalled.

maybe it would work better here, I don't know.

**Comment by devinacker** [comment]
Yeah, I noticed that setting in the VDP class and tried it since it seemed potentially helpful, but it didn't seem to play nice with the custom screen update stuff in the megaplay driver.

In any case it seems like the VDP constantly running ahead of the screen device seems to be the most likely cause of the Shinobi problem, but I don't really know enough about the internals of that stuff to have any good ideas right now.

**Comment by angelosa** [comment]
y=186 is also happening with vanilla megadrive as well. 
First suspect is [here](https://github.com/mamedev/mame/blob/331baa268a57628a02b5953c30966f058e192786/src/mame/machine/megadriv.cpp#L926), it's supposed to call `->set_raw` instead even if it's overridden later on.
Second suspect is [here](https://github.com/mamedev/mame/blob/331baa268a57628a02b5953c30966f058e192786/src/devices/video/315_5313.cpp#L2365), I don't see any real reason about why this doesn't call screen().vpos or even a configure_scanline fn.

**Comment by devinacker** [comment]
Should I open a new issue for this? It seems like it's probably unrelated to the original PR even though it affects some of the same games.

**Comment by DavidHaywood** [comment]
yeah, might be better for any discussion to be somewhere better than this PR.

at some point the entire Genesis emulation really needs replacing with something based on current knowledge; it was pretty good back in 2003, at which point it ran some things nothing else could run, but these days it's sorely lacking and showing its age in terms of how it implements things.

**Pull request merged**
