### PR TITLE
Fix comment

### PR DESCRIPTION
**Pull request by Dagarman**
This corrects an comment. There are two sections called TYPE DEFINTIONS. This first section contains #define directives and should be called MACROS as nearly all of the other header files do.

### CODE REVIEW

**Comment by galibert** [comment]
Your commit message is drunk, can you fix it?

  OG.

**Comment by Dagarman** [comment]
it is sober now

On Thu, Jun 16, 2016 at 10:33 AM, Olivier Galibert <notifications@github.com

**Comment by galibert** [comment]
Well, you edited the pull request (which was enough), it's the commit
message, "Add files via upload", which is what will stay in the tree
forever, which I have a problem with...

I'll do a new commit if you want, I don't know how intricate github is with
that stuff.

  OG.

**Comment by angelosa** [comment]
Dagarman: Do another commit in the pull request, it'll give a "stash" pull request option where the merger can edit the commit message itself.

**Comment by Dagarman** [comment]
I figured out how to change the message. Maybe this will do it??

**Comment by galibert** [comment]
Indeed it did :-)  Merged.

Thanks,

  OG.

**Pull request merged**
