### PR TITLE
Delete android-project directory

### PR DESCRIPTION
**Pull request by oil-bleach-re-el-idited**

### CODE REVIEW

**Comment by ajrhacker** [comment]
What's the rationale for killing this?

**Comment by Robbbert** [comment]
They just joined github especially for this. I suspect it's JJ.

**Comment by happppp** [comment]
@oil-bleach-re-el-idited this is upstream, you probably meant to do the work on https://github.com/oil-bleach-re-el-idited/mame ?

**Comment by oil-bleach-re-el-idited** [comment]
I suspect this is for nasa fix that happens to affect us all

**Comment by Robbbert** [comment]
Could be. It needs to be banned, and its various duplicate PRs to be closed.

**Pull request closed without merging**
