### PR TITLE
Add include path on linux when SDL_INSTALL_ROOT is used

### PR DESCRIPTION
**Pull request by couriersud**
Despite using SDL_INSTALL_ROOT the build system is using the SDL include files from /usr/include. This modification fixes this.

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
This doesn’t seem right – shouldn’t `sdlconfigcmd()` be giving the correct include path?  You can see that it’s adding the SDL install root path at line 137.  Was your SDL configured correctly for the installation location, or did you move it?

**Comment by couriersud** [comment]
I installed SDL 2.0.4 with the following
./configure --prefix=/opt/libs
./make
sudo ./make install

I added SDL_INSTALL_ROOT=/opt/libs to MAME make. This did not add the include path /opt/libs/include.
In the code sdl_config is only asked for "--libs". There is no code parsing "sdl_config --cflags".

**Comment by cuavas** [comment]
Well the proper solution would be to fix that.

**Comment by couriersud** [comment]
```
$ /opt/libs/bin/sdl2-config --libs
-L/opt/libs/lib -Wl,-rpath,/opt/libs/lib -Wl,--enable-new-dtags -lSDL2
```

**Comment by cuavas** [comment]
Yeah, but if it needs to pick up other flags from package config, it should be changed to do that.  Sidestepping the package config script is not the right solution.

**Comment by couriersud** [comment]
Ok agree. I will use sed to do. I have another commit on top to fix SUBTARGET=nl build. It would be great if you could accept this, so I can create a pull request. Afterwards I create the pull request for the proper fix to parse --cflags.

**Comment by cuavas** [comment]
You’re already out of sync with master.  It’s probably better to create a new branch for each independent set of changes.  You can play individual changes onto a branch easily.

**Comment by couriersud** [comment]
Ok will do. No contact with git for nearly two years. If you wonder, why I am using pull requests :-)

**Pull request closed without merging**
