### PR TITLE
Now setting m_filetype for images loaded from softlists

### PR DESCRIPTION
**Pull request by npwoods**
Tafoid reported that 'bbcb exile' failed in the tip, but succeeded in MAME 0.176.  I've identified the issue.

`
In MAME 0.176, cassette.cpp had the following code:

	const char *extension;

	...

	if (software_entry()==nullptr) {
		extension = filetype();
	} else {
		fname = m_mame_file->filename();
		int loc = fname.find_last_of('.');
		if (loc!=-1) {
			extension = fname.substr(loc + 1,fname.length()-loc).c_str();
		} else {
			extension = "";
		}
	}
`

The implication of this hack is that filetype() shouldn't be trusted for cassettes loaded by softlists.  The fact that this relied on the return value of c_str() invoked on an rvalue implies that this worked by accident, but that is a separate issue.

This hack was (IMHO correctly) completely unwound in my softlist changes.  The fix to make sure that filetype() works is in my opinion, the correct way to go.

It seems much safer to make it so that filetype() returns the right thing for items loaded from software lists.

### CODE REVIEW

**Comment by cuavas** [comment]
I don't think we really want to do this.  The information on the image format should be available through information in the softlist itself, not from the filename extension.  If the necessary information isn't present in the softlist, in needs to be added somehow.  Moving the hack into the softlist code is worse than leaving it where it is because it will allow other code to easily depend on it.

**Comment by etabeta78** [comment]
for tapes and disks, I think the file extension can be trusted for the file
format in softlists, at least as much as from fullpath (i.e. for disks
geometry has still to be calculated by other means).
OTOH, I can imagine that with carts and their .u1, .u2, .ic1 and .ic2
extensions, the format cannot be inferred by extensions, but the
device_load code already handles them properly.

   f.

**Comment by mamehaze** [comment]
hmm unless I'm misunderstanding this, there are times when we'll want to be able to derive the image format from the filename extension in the softlist.

for example with some tape / disk lists we have no choice but to go for 'best available' images, some of which are in better formats than others, using the file extension in those cases makes a lot more sense than adding addition metadata to every entry to specify it.

obviously it should be possible to override it / specify it manually, but by default, for such cases the filename extension is a very useful hint.

**Comment by npwoods** [comment]
Reopening pull request with alternate proposal.

**Comment by Pernod70** [comment]
I'm with haze and eta on this in that for floppies and cassettes in softlists the file extension should be trusted to determine format. The vast majority of legacy cassette formats have no checks in their identify, always returning cassette_legacy_identify with success. So for bbcb which has two legacy formats csw and uef the first checked format will succeed, then fail trying to load a uef as a csw.
For uef and csw I can add additional checks in their identify to fix cassette loading in bbcb, but overall I'd prefer if the extension was actually checked to be valid before proceeding to identify.
The bbc driver supports many floppy formats so when loading a ssd image why should it have to be checked against 6 other formats that don't have ssd in their extensions(). In acorn_dsk the identify for each format is quite complex simply due to not having access to the file extension. Why even define valid extensions if they are not used to check validity.

**Comment by cuavas** [comment]
But it's against the spirit of the softlist.  The softlist itself should contain all necessary metadata.  Relying on filename extension goes against that design.  I'm closing this.

**Comment by etabeta78** [comment]
How so? Look at the way floppy disks are handled: at loading time you
deduce the geometry from the file, but you rely on the extension for
guessing how to look for geometry (when for instance, the same disks appear
in multiple formats)...

    f.

**Comment by rb6502** [comment]
Yeah, Vas is being idealistic all the way into an unusable corner here.  It's nonsense on stilts for mass-storage media to have two completely separate code paths depending on if you open them through a softlist or the file picker.

**Comment by rb6502** [comment]
...and it's equally dumb to have a <file_ext=".2mg"/> tag or whatever for every softlist item that just duplicates data which already exists in the filename.

**Comment by cuavas** [comment]
Oh so what about `.dsk` for Mac disk images?  It's used for half a dozen disk image formats.  And what about all the DC42 and DART images that just plain have no filename extension?  The softlist should have the metadata somewhere, using the filename extension is a hack.

**Comment by Lord-Nightmare** [comment]
IIRC dc42 uses .image as its standard extension, but this could be erased by the user in the dialog box and stuff would still work, also if the user typed a name longer than 28 characters the end of .image would be chopped away, so <filename of 29 characters>.imag etc.
dc42 files have a 'strange' magic number which can be verified as the first part of an 'identify' function, though: bytes 0x52 and 0x53 are always 0x01 0x00
I suppose if those bytes match that, the second stage of verification is to make sure the file isn't corrupt, sanity check the data size field(0x40-0x43)+tag size field(0x44-0x47)+header size(0x54 bytes) vs the image file's size, then optionally check that the data and tag checksums are valid. I believe DART is similar.

**Comment by rb6502** [comment]
Mac disks pretty much universally can be IDed from their first two bytes and the image size, so that's a poor example.  What's life-or-death is knowing if an Apple II image is .DO or .PO - there's a (completely terrible) heuristic in MAME right now that tries to guess, but it gets things wrong on a fairly regular basis given the sheer variety of bootloaders you find on the machine.

**Comment by etabeta78** [comment]
Since for some Japanese systems we support non-raw dump formats, where
tracks are stored separately each with a different header, some disks would
need more than 30 metadata and it sounds really not worth the effort when
we still need the extension handling from fullpath...

    f.

**Comment by cuavas** [comment]
Well I guess it's getting merged, but I still dislike it in principle.

**Pull request merged**
