### PR TITLE
Update device names

### PR DESCRIPTION
**Pull request by MASHinfo**

### CODE REVIEW

**Comment by happppp** [comment]
I reject this.

MASH, a while ago you were told to stop the mass device renaming. That
doesn't mean you can retry it later.

On Mon, Dec 28, 2015 at 7:16 AM, Miodrag Milanović <notifications@github.com

**Comment by MASHinfo** [comment]
@hap
Nobody told me to stop device renaming.
Who said this? And why did you reverted it?

**Comment by happppp** [comment]
Ok, let's say it bluntly. The majority of the active MAME team does not
trust that you have the qualifications to be responsible for deciding names
of emulated devices.

**Comment by MASHinfo** [comment]
The new names are *good*. What are you doing there?

**Comment by happppp** [comment]
We prevented you from deciding emulated devices names.

**Comment by mamehaze** [comment]
the changes really aren't needed, there's nothing wrong with the old names, the entire set of changes is nothing but personal preference which isn't really objective.

**Comment by mr-t-guru** [comment]
I personally like them. most of the names and MANY of the game names have poorly chosen short [MAME] names. it wouldn't hurt to rename them by someone who is more subjective, rather than someone (i.e. a programmer) who believes everything they do is perfection.....

**Pull request merged**
