### PR TITLE
Implement custom software list loading

### PR DESCRIPTION
**Pull request by ajrhacker**
Software specified on the command line with an image format now looks for a file named 'software.xml' in the software's subdirectory or ZIP file if the driver-configured softlists have no info on it. This XML file should have the usual MAME software list format, and must contain an entry with the same name as the software; other entries are normally ignored.

Parsed software lists are now separate from devices, allowing them to exist independently from the configured state.

Tighten restrictions on "requirement" feature in software entries to simplify loading
- Required additional software must specify the software list it should	be loaded from unless it can be	found in the same list (which usually never happens, though it can happen with custom software lists). The validity checker now enforces this.
- Required additional software cannot be automatically loaded by any part other than the first.

### CODE REVIEW

**Comment by cuavas** [comment]
I don't like the direction of this.  It jams even more software list behaviour into diimage, where it really doesn't need to be.  Even if we don't move the software list structure out of emu, I still agree in principal with @npwoods that software lists and software loading shouldn't be tightly coupled with diimage.

**Comment by ajrhacker** [comment]
This admittedly does need substantial refactoring now to resolve conflicts on other changes @npwoods has been pushing. I think the criticisms against overloading diimage with software list stuff is justified, though only in part (since non-device software lists will have to be held by some device-related structure). I'll get around to this when I have time.

**Comment by npwoods** [comment]
#1137 also has conflicts with recent work.  What I'd like to do is get consensus on whether #1137 is the right way to go; if the biggest concern is the move to src/lib/util, I can address that

**Comment by ajrhacker** [comment]
My biggest problem with the mechanism implemented in e45d316bc9683d46c5a0414e57f9ec1b99d64d05 is that it tightly couples software loading to emu.h. I'm trying to mitigate this by removing the stealth include and moving software_list_loader, this time into romload.cpp/h (which already handles one of the two important cases).

**Comment by npwoods** [comment]
IIRC emu.h wasn't modified at all, but it did already include diimage.h.  Are you referring to how diimage.h then includes softlist.h?  If that is the biggest issue, I suppose that could be rectified with the right forward declarations.

**Comment by ajrhacker** [comment]
The software_list_loader situation can't be solved simply by forward declarations, as every definition of get_software_list_loader requires full access to one of its subclasses.

**Comment by npwoods** [comment]
I don't see why that should be a problem.  Forward declare software_list_loader in diimage.h and declare the implementations of those classes elsewhere.

**Comment by ajrhacker** [comment]
Yes, you can forward-declare software_list_loader in diimage.h (in fact, the rebased version I've pushed does precisely that), but that isn't enough to compile any _definition_ of get_software_list_loader, which would require either including a header file providing the superclass and subclass within each device header (or within diimage.h, which as I've said is bad form), or transferring the definition to a source file including the same. The latter would be more consistent with MAME's general coding style of not inlining definitions of common virtual functions, and is also what I've done with the default implementation of get_software_list_loader (whose source file also localizes false_software_list_loader, which, as a dummy class used only here, needs no further exposure).

**Comment by ajrhacker** [comment]
I'll close this for now; even if there is demand for this new feature, I see little point in this specific pull request remaining on the list indefinitely since my code will need a lot of refactoring to keep up with the current codebase.

**Comment by mizapf** [comment]
There is certainly demand for this feature (and if only to replace the current RPK handling). :) Please keep me informed as soon as your refactoring is ready.

**Pull request closed without merging**
