### PR TITLE
spectrum_cass: 27 new dumps, 10 replacements

### PR DESCRIPTION
**Pull request by ArcadeShadow**
### New working software list additions
Abu Simbel Profanation (small case, alt), Abu Simbel Profanation (small case), Cybernoid II - The Revenge (IBSA), Dan Dare II - SU Edition, Dan Dare III - The Escape (Dro Soft), Defender of the Crown, Defender of the Crown (alternative), Eddie Edwards' Super Ski (Erbe), Eddie Edwards' Super Ski (Players Premier), Eddie Edwards' Super Ski (Players Premier, alt), Firelord (Erbe), Green Beret (Erbe, medium case), Guerrilla War: Hail the Heroes (Erbe), Miami Vice (IBSA), Molar Maul (Microbyte), Pac-Mania (MCM), Pink Panther (Dro Soft, double case), Pink Panther (Dro Soft, small case), Quazatron (Erbe), Quest for the Holy Something (alt 2), Scuba Dive (GTS), Super Trolley (Dro Soft), SWIV (Dro Soft), Uchi-Mata (IBSA/Erbe, serie leyenda), Wizball (IBSA) [worldofspectrum.org]
Cárie, Terrormolinos! (Aackosoft) [Planeta Sinclair]

### Replaced software list items
Abu Simbel Profanation - Medium Case - 1st release, Abu Simbel Profanation (medium case), Choy-Lee-Fut Kung-Fu Warrior, Dan Dare, Dan Dare (Dro Soft), Soldier of Fortune (release 3), Stormlord II - Deliverance (Erbe), Super Trolley, Uchi-Mata (Erbe), Wizball (Erbe Software) [spectrumcomputing.co.uk]

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
Two things:
* Please format your commit message the way we format things in whatsenew, not in a similar way that’s still different enough that it’s going to trip up scripts.
* This has a huge amount of publisher churn again.  I’m getting really sick of this constant churn.  Please provide some evidence that the forms of names you’ve changed it to were actually used on these releases.

**Comment by ArcadeShadow** [comment]
1. I change the PR message, but I don't know how to change the commit message.
2. For the publisher, I've change 3 kind of things:
- Change the "unknown" publisher to the right publisher
- Remove the indication of "Ltd" and things like that, to keep the name the same that appear on the games (they told me to do this way)
- On games that have been re-release or release on other countries, I keep only the name of the last publisher (IMO is the most correct)
All the changes were made based on the info of the "worldofspectrum.org" and "spectrumcomputing.co.uk"

Please, let me know if it's the right or wrong way to do.

**Comment by Tafoid** [comment]
Just a note that all data has been accounted for, xmllint validates as well passing mame -validate.

**Comment by cuavas** [comment]
@Pernod70 are you familiar with the Spectrum software library?  Can you comment on the metadata changes?

**Comment by Pernod70** [comment]
I'm not overly familiar, but after a quick review I'd say the changes look good and should be merged.

**Comment by ArcadeShadow** [comment]
Thanks!
Just one question.
On MAME v0.212 somebody committed over 10.000 spectrum_cass sets, more than half were marked as "<unknown>" publisher and with 19?? on the year info. Beyond that, an enormous number of those sets have the "parent/cloneof" relationship completely incorrect.
Since MAME 0.231 I've been trying to correct that.
May I continue or is an useless effort?

**Comment by cuavas** [comment]
It’s worth trying to clean up the parent/clone relationships and metadata, but it might be better to do that in separate PRs to additions, so it can be reviewed independently.

**Comment by cuavas** [comment]
Where does this addition come from?  It isn’t credited.
```
  <software name="robocop2c" cloneof="robocop2">
       <description>Robocop 2 (Erbe, small case)</description>
       <year>1990</year>
       <publisher>Erbe Software</publisher>
       <part name="cass" interface="spectrum_cass">
           <dataarea name="cass" size="127215">
               <rom name="robocop 2 - small case (erbe).tzx" size="127215" crc="3a1e50c1" sha1="e0c4d4a8baf0c83a7e1020b0f5973fa2cc5aaf29"/>
           </dataarea>
       </part>
   </software>
```

**Comment by ArcadeShadow** [comment]
I forgot to add the source of this one, it came from spectrumcomputing.co.uk

**Pull request merged**
