### PR TITLE
Use correct Toshiba Pasopia7 font rom

### PR DESCRIPTION
**Pull request by palazzol**
Use this new dumped font rom, instead of a hack.  The size and content match the schematics. (4K 2732, not 2K)  For example, the second half of the image is the reverse-video of the first half, and the high address line is supposed to be for reverse video.  
Finally, it matches the videos of actual Pasopia7's online.

There is a BASIC test program for reverse video, which doesn't work, but I believe that's because the emulation is not hooked up right.  

All the drivers using the old rom work as well as they did before with this new one.

### CODE REVIEW

**Comment by angelosa** [comment]
Any easy way to test reverse video thru BASIC? `color N` I suppose?

**Comment by palazzol** [comment]
I just noticed...this page all the way at the bottom (2004) has a comment about the incorrect font rom being used in his emulation.  I believe this is the origin of the font file currently being used in MAME.
[http://takeda-toshiya.my.coocan.jp/pasopia7/index.html](http://takeda-toshiya.my.coocan.jp/pasopia7/index.html)
English Translation from google translate:
"Since the font ROM cannot be accessed from the CPU and cannot be sucked out, the free ROM for FM-7 is diverted."

**Comment by ajrhacker** [comment]
Updating the other drivers may not be the right idea here, even with BAD_DUMP flags. The schematics for the original Pasopia shows that it uses a 2716 CG PROM, not a 2732.

**Comment by palazzol** [comment]
Can you point me to the original Pasopia schematics?  Maybe I can do more digging.  I can leave the original Pasopia alone for now...it shouldn't be expanded to 4k if it's a 2716

**Comment by palazzol** [comment]
I restored pasopia to the original BAD_DUMP 2k image
I restored paso1600 to the original BAD_DUMP 2k image
I only updated pasopia7 and pasopia7lcd with the new 4K image
I think the pasopia7lcd is actually the proper dump, but I won't remove BAD_DUMP there until I'm sure

**Comment by Osso13** [comment]
Could you please update this to resolve the conflicts? Thanks!

**Comment by palazzol** [comment]
I have added the correct font roms for the pasopia and pasopia7 drivers.  These have been dumped from original hardware and verified correct.  The pasopia7lcd and paso1600 continue to use the possibly incorrect dumps, so I have left them marked as such.  This code has also been brought up to the latest MAME.  
Note - I have not updated the driver logic, and so the pasopia7 font rom is not currently used correctly.  It is now double the size, with the second half being reverse video characters, but these are not addressed by the driver.  I don't have time to update this any further at this time.

**Comment by angelosa** [comment]
> I have not updated the driver logic, and so the pasopia7 font rom is not currently used correctly. It is now double the size, with the second half being reverse video characters, but these are not addressed by the driver.

I'll take a look when this is in.

**Pull request merged**
