### PR TITLE
Support Colecovision Megacart.

### PR DESCRIPTION
**Pull request by ElectricMagic**
Assume that a rom file that is more than 32K in size is a megacart
and that it should be bankswitched using Megacart protocol.

### CODE REVIEW

**Comment by happppp** [comment]
Hi,
If it works, that's great. But you've edited the wrong file. ROMtype emulations are in separate files, for example std.* and xin1.*. Megacart implementation would be in megacart.h/cpp.

**Comment by ElectricMagic** [comment]
Any thoughts on how one would indicate to mame that a particular cartridge should be interpreted via megacart vs being treated as std? I'm not really au fait with mame techniques, so would it be a command line option, or perhaps some kind of config item attached to the cartridge via some xml file entry?
Could the particular device_colecovision_cartridge_interface be selected automatically by inspection of the rom data -- I mean, is there a sensible point in the code at which that would occur?
For that matter, the _8000, _a000, _c000, _e000 params are clearly part of some more sophisticated scheme, but there's nothing to indicate what they mean. xin1 uses one of the params, but only as a boolean. Do you have any pointers as where this was discussed -- google hasn't been terribly forthcoming.

**Comment by ElectricMagic** [comment]
OK, I see more what you're saying. I shoved the reinterpretation of the offset/data size into `colecovision_cartridge_slot_device`, which does work, but that entity is not really modeling the ROM. A slightly more correct gross hack would be to have modified `colecovision_standard_cartridge_device`.
Ideally though, there'd probably be a `colecovision_megacart_cartridge_device` in which the behavior would reside.
So what I need to figure out is how to cause the request that cartridge xxx be loaded will cause `colecovision_megacart_cartridge_device` to be instantiated rather than `colecovision_standard_cartridge_device`.

**Comment by happppp** [comment]
According to google, _8000, _a000, _c000, _e000 are chip select signals on the Coleco cartridge edge connector. But on MAME it looks unused.

Yup, you'd need a new file with colecovision_megacart_cartridge_device. Unfortunately there is no how-to or documentation about it(crudely put: the source code is the documentation).
How I would do it: simply copy-paste xin1.* and modify it so it becomes megacart. The megacart roms would be loaded through the softwarelist(hash folder). Simple autodetection may be doable in get_default_card_software.

**Comment by ElectricMagic** [comment]
OK, found it.
`std::string colecovision_cartridge_slot_device::get_default_card_software(get_default_card_software_hook &hook) const`
could be modified to look for oversized roms and do for megacart what it's already doing for xin1.

**Comment by happppp** [comment]
Great, I'll merge it and give it a try.

**Comment by ElectricMagic** [comment]
Brilliant! Thank you very much. That was a lot easier than I was expecting to be honest.

**Pull request merged**
