### PR TITLE
Cleanups and corrections for CoCo cartridge slot configuration

### PR DESCRIPTION
**Pull request by npwoods**
1. Consolidated CoCo cartridge slot device configuration, to remove duplicate code that was specific to slots on the Multi-Pak interface.
2. Marked "pak" and "banked_16k" as internal, as they are not standalone

### CODE REVIEW

**Comment by npwoods** [comment]
I call the attention of @tlindner because it is possible that more devices should be set up as "internal".  For example, I don't know what "Games Master" is.

**Comment by tlindner** [comment]
What does marking a cart internal mean?

The Games Master cart is a product John Linville sells to game developers. There are currently no released games using it, but there is a cassette game software using it as a sound cartridge.

**Comment by npwoods** [comment]
Making the option "internal" removes it as an independently selectable slot option, but keeps the ability for software list items to use it.  To me, it makes sense to mark "pak" and "banked_16k" this way because these are always used in conjunction with a cartridge image.

**Comment by tlindner** [comment]
Then I think the GMC should stay selectable. Since there is the possibility of using it for development.

**Review by cuavas — COMMENTED** [review]
This is one of those cases where Boolean parameters in a public function just serve to make things less clear.  I’d probably split it up as `coco_cart_add_basic_devices`, `coco_cart_add_multi_pak` and `coco_cart_add_fdcs`.

**Comment by npwoods** [comment]
Done!

**Pull request merged**
