### PR TITLE
new SOFTWARE LIST additions (ekara etc.) - mostly XaviX

### PR DESCRIPTION
**Pull request by mamehaze**
- consolidated ekara form-factor carts into a single list with compatibility filters [David Haywood]

new SOFTWARE LIST additions
--------
evio.xml:
Anime Mix 2 [David Haywood, TeamEurope]

ekara_cart.xml:

BH-01 Best Hit Collection (Japan)  [David Haywood, TeamEurope]
BH-04 Best Hit Collection (Japan)  [David Haywood, TeamEurope]
BH-07 Best Hit Collection (Japan)  [David Haywood, TeamEurope]
Kids' Song 20 (Japan) (KD-3)  [David Haywood, TeamEurope]
Artist Mini Volume 2 (PIKA☆NCHI, A・RA・SHI／他) (Japan) (MC0002-ATM)  [David Haywood, TeamEurope]
Kids Song Mini Volume 4 (Fantastic) (Japan) (MC0011-KSM)  [David Haywood, TeamEurope]
Saiten Cartridge Nesshō vol. 4 (Japan) (SC0013-SAI)  [David Haywood, TeamEurope]
Kids' Challenge Vol.2 (Japan) (SC0017-SAI)  [David Haywood, TeamEurope]
PR-01 Morning Musume - I'm Here! (Not for Sale, Japan)  [David Haywood, TeamEurope]
Natsukashi no Meikyoku-shū  [David Haywood, TeamEurope]
Dream Cartridge: TV Pop Junior Vol.8 (Japan) (DC0004-TPJ) [David Haywood, TeamEurope]
Dream Cartridge: TV Pop Junior Vol.10 (Japan) (DC0009-TPJ) [David Haywood, TeamEurope]

hikara_cart.xml:
Hi-kara 5-song capacity user cartridge (used, with 4 songs) (Japan) [David Haywood, TeamEurope]
Best Hit Collection Volume 3: J-Pop 3 (Japan) [David Haywood, TeamEurope]
Best Hit Collection Volume 5: Anime Song 2 [David Haywood, TeamEurope]
Best Hit Collection Volume 7 [David Haywood, TeamEurope]
Best Hit Collection Volume 8 [David Haywood, TeamEurope]
Ciao Special [David Haywood, TeamEurope]
Pocket Monsters Special [David Haywood, TeamEurope]

bkrankp_cart.xml:
J-Pop Blue [David Haywood, TeamEurope]
Aikatsu Ver. Best [David Haywood, TeamEurope]
J-Pop - Strawberry [David Haywood, TeamEurope]
J-Pop - Green [David Haywood, TeamEurope]
J-Pop - Pink [David Haywood, TeamEurope]
Kid's Pop - Lemon Yellow [David Haywood, TeamEurope]
Kid's Pop - Red [David Haywood, TeamEurope]
Kid's Pop - Apple Green [David Haywood, TeamEurope]
J-Pop - Grapefruit [David Haywood, TeamEurope]
Disney Dream Hit Song [David Haywood, TeamEurope]
J-Pop - Mint [David Haywood, TeamEurope]
Best Hit Song [David Haywood, TeamEurope]
 
new NOT WORKING machines
-----------
TV-PC Thomas & Friends (Japan) [TeamEurope]
TV-PC Doraemon (Japan) [TeamEurope]

### CODE REVIEW

**Comment by mamehaze** [comment]
Some of these need extra translation work (better title on GS-01, artist on MC0002)

Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB

**Comment by mamehaze** [comment]
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB

**Comment by ajrhacker** [comment]
As discussed a month ago, GS-1 is Natsukashi no Meikyoku-shū (懐かしの名曲集).

**Comment by mamehaze** [comment]
thanks, I'd saved a note, but on my other machine, which isn't where I am right now

**Comment by mamehaze** [comment]
there are a handful more e-kara carts, and some hi-kara carts to come, so leaving this as draft for now

**Comment by mamehaze** [comment]
Cart+PCB
Cart+PCB

**Comment by mamehaze** [comment]
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB
Cart+PCB

**Comment by mamehaze** [comment]
These are the 4 tracks present on the 5 song user cart for hi-kara

**Pull request merged**
