### PR TITLE
hook up victnine mcu, tested that it boots at least

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
@Osso13  do you want to check / merge this?  the vague comment about being hand verified made me not even really be sure I should go anywhere near this

**Comment by Osso13** [comment]
I tried to hook it up some days ago. It seemed to work fine, then I commented out the ROM definition and couldn't spot any problem even that way. So I don't know what the protection controls and thus where to look for possible malfunctions.

**Comment by DavidHaywood** [comment]
I think it's just used as a random number generator, strangely the game code doesn't wait on a boot status from it like you say

**Comment by Osso13** [comment]
Ah, that would explain it. Thanks! I played with it a bit when I tried my hook up and couldn't spot any random problems (balls and strikes were called ok, the CPU changed pitch type, batted balls landed in different places and with different traiectories, etc).
I'll play test it a bit more this evening or tomorrow, with the intention of merging this before freeze if I can't spot any regression.

**Comment by Osso13** [comment]
BTW, Guru confirms the dump works when burnt and used on an original PCB.

**Comment by DavidHaywood** [comment]
right, it only has a very simple function.  my concern with dumps being added like this that aren't trusted is exactly that tho, people are going to put them on PCBs and then when we buy a PCB to verify it, we'll just get the same code, and a false verification

**Comment by rb6502** [comment]
@Lord-Nightmare partially described how he verified it on the DU list, I don't believe he did any editing to make the checksum match but he can describe what he did.

**Comment by Lord-Nightmare** [comment]
What I did was first feed the 'raw dump' to the 68705_raw_decode program (whose source code I posted to the DU list about 2 years ago, there were no changes) and it spat out a large number of warnings and one file, which wasn't any good. (The raw file should contain roughly 225 copies of the rom image)
 I then observed from the warnings that the first few copies of the rom in the original raw file seemed more 'stable' than the later ones, so I chopped the first 0x8400 bytes (just 2.06 copies, though each 'copy' has the data for each byte 4 times) out of the raw file, and running that through the decoder produced a result that turned out later to be correct*.

*I'm still not 100% sure about this, and am hoping for a more stable redump of the mcu, or a significant rewrite of the decoder to handle streams with a lot of corruption.

Next, I manually did a 'better version' of what the decoder does by hand (since the 20170912 decoder is very primitive and cannot resynchronize mid-stream), and took the 'raw dump' file and deinterleaved it 3 times to produce 8 files, then hand-searched in a hex editor for the 68705p5 bootrom to figure out 'where I was' in the code (since it should repeat every 0x800 bytes), then searched the first 17 copies of the rom in the file and saved each to its own file. Unfortunately due to the dumper device sync issues, of those 17 copies, only 3 were exactly the right length (the rest all have extra/duplicated bytes throwing the sync off), but I worked around that in vbindiff, making a list of all the addresses that disagreed and 'voting' between each of them. I found a number of single byte errors in the various copies of the dump, but the final rom ended up matching the decoded dump supplied by the original dumper, barring two error areas:

1. In the original provided decoded dump, the area from 0x80-0xFB is incorrectly replaced with a copy of the code from 0x532-0x5ad, plus 4 bogus bytes at 0xFC-0xFF which don't appear elsewhere in the rom dump.
2. the data at 0x6AF and 0x6B0 was wrong. This falls within a 'boilerplate' function from 0x600-0x77f that was also used in A14_12 from sfposeid, and was the correct value in the handmade dump as well as the '0x8400' decoded dump.

So I'm reasonably sure the dump is correct, but not 100% sure, and probably won't be until we get a redump, or a much better automatic analyzer program written.

**Comment by ajrhacker** [comment]
> the first returned byte on these Taito games is a checksum that covers most of the custom part of the program

In most cases, yes. A few of the Taito 68705 MCUs just return a magic number instead of doing an actual checksum. This is the case with Nekketsu Kouha Kunio-kun, whose first MCU dump turned out to have a few bad bits.

**Comment by DavidHaywood** [comment]
chances are Nekketsu Kouha Kunio-kun was programmed by Technos tho, it doesn't follow the standard Taito structure used by the majority of the MCUs

**Comment by DavidHaywood** [comment]
anyway, I think this works, and there's a good chance the method used to make it has enough verification points to be confident based on what LN posted, so it should be good to go IMHO, another old simulation cleaned up

**Pull request merged**
