### PR TITLE
Change default XInput bindings for pedal inputs from -Z/+Z to Z/RZ

### PR DESCRIPTION
**Pull request by ajrhacker**
(nw) This does not remove the unwanted mid-pedal deadzone identified by hap, which is a core bug unrelated to the OSD layer. This fix is also untested, as my build machine does not run Windows.

### CODE REVIEW

**Comment by happppp** [comment]
Or maybe simulate them as half-axes? Right now the triggers range in MAME is -0x10000-0x10000, with a deadzone around 0. If we put the triggers on 0-0x10000 it will eliminate the deadzone. Original range is 0-255. So, something as simple as this in input_xinput.cpp:

gamepad.left_trigger = normalize_absolute_axis(xinput_state.xstate.Gamepad.bLeftTrigger, -255, 255);
gamepad.right_trigger = normalize_absolute_axis(xinput_state.xstate.Gamepad.bRightTrigger, -255, 255);

**Comment by rb6502** [comment]
I agree with hap, that should make it simpler to map the triggers in the tab menu as well.

**Comment by happppp** [comment]
In that case, MAME won't need to detect whether it's running on xinput or
dinput. Keep IPT_PEDAL as-is, and put IPT_PEDAL2 on ZRot. Since having both
pedals on the same axis isn't a good idea, right?

**Comment by ajrhacker** [comment]
> In that case, MAME won't need to detect whether it's running on xinput or
> dinput. Keep IPT_PEDAL as-is, and put IPT_PEDAL2 on ZRot. Since having both
> pedals on the same axis isn't a good idea, right?

I don't think I quite understand the change you're asking for here. Do you mean that DInput support should be changed so that the Z/RZ settings can be made default for it too? Keep in mind that I can't test any of this.

**Comment by happppp** [comment]
If you don't mind, here's a commit that applies it:
https://github.com/mamedev/mame/commit/f407c554596ebdba0bb7166d7d95936f2aa817c5

IPT_PEDAL and IPT_PEDAL2 are now defaulted on separate axes.
Xinput triggers are on Z- and RZ-.

**Comment by ajrhacker** [comment]
I suppose that will do for now.

**Pull request closed without merging**
