### PR TITLE
Redump a-19993 PAL (nw)

### PR DESCRIPTION
**Pull request by Hydreigon223**
Because someone managed to reproduce the link pal a-19993 and verified working, I may as well take the advantage to convert that jed file into a binary file and use that dump.

### CODE REVIEW

**Comment by Tafoid** [comment]
This newly converted/redumped PAL image has not been uploaded for examination.  Also, was this sourced from you, yourself, or elsewhere?  Please detail this information with the file (contained in a .zip please) and send to the email detailed here:
https://wiki.mamedev.org/index.php/Submitting_Source_Code

**Comment by Hydreigon223** [comment]
I sent the pal (obviously in binary format).

The PAL itself in jed format I got from this: http://www.jammarcade.net/files/pals/Cruisin%20USA%20linkup%20A-19993.jed

It was tested working on actual hardware.

**Comment by p1pkin** [comment]
description at https://www.jammarcade.net/wiki/index.php?title=Cruisin%27_USA says this jed was "recreated" by JROK, which probably means it is handmade.
so, it should be marked as BAD_DUMP in MAME

> It was tested working on actual hardware.

you tested it by yourself ?

**Comment by cuavas** [comment]
Still should be marked `BAD_DUMP` if it's a recreation, even if it works.  We do that with hand-made or hand-patched MCU programs even if they work on real hardware.

**Comment by Hydreigon223** [comment]
If that is the truth, then it shall be marked then. Didn't notice it was a recreation.

As of now, I'm concerned if pal dumps for all V-Unit games are even worth the time and resources as I had initial plans to buy one of those pcbs for the pals.

**Pull request merged**
