### PR TITLE
Another attempt at improving accuracy of sound emulation in inder.cpp…

### PR DESCRIPTION
**Pull request by ajrhacker**
… (nw)

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
Needs some Netlist implementation of the logic maybe? Seems to be similar problems that has been addressed by JD for the hazeltine driver

**Comment by ajrhacker** [comment]
There really isn't enough logic here to netlist. The 74157 isn't even a netlist device yet, nor are the ROMs its data comes from; it's been applied widely enough that netlist will probably need its own bit-level version of it sooner or later, though as the MAME device it lends itself to a more straightforward implementation than the overinvolved mess Aaron Giles made out of half a 7474. The MSM5205 obviously isn't fit for netlisting, though MAME's current emulation of that device is troublingly inaccurate.

**Comment by aaronsgiles** [comment]
“overinvolved mess Aaron Giles made out of half a 7474” LOL, I never wrote that code, nor have I ever been in favor of doing TTL emulation via devices.

Not sure why it was attributed to me except that I probably touched it numerous times during cleanup/devic-ification.

Aaron

**Comment by Osso13** [comment]
The 7474 was added in 0.37b15, The wn doesn't say who added it though.

**Pull request merged**
