### PR TITLE
Update freekick.cpp

### PR DESCRIPTION
**Pull request by gamez-fan**
Make The Counter Run Parent Work

### CODE REVIEW

**Comment by gamez-fan** [comment]
Not an ideal situation, but it makes sense to me at least to make the parent set of Counter Run work
by using the CPU from the bootleg until such a time as the proper CPU from this set is dumped. There are
instances where this has been done in other drivers.

**Comment by mamehaze** [comment]
why are you resubmitting this?

I already said it's a terrible idea.

There is no requirement for the parent to work, making the set 100% identical to the bootleg set serves no purpose and is completely misleading.

**Comment by mamehaze** [comment]
basically it needs doing properly, or not at all, because this has no purpose, if you want to run that bootleg, run that bootleg, using it as a fake rom in the parent just degrades the documentation.

**Comment by gamez-fan** [comment]
Haze You dont agree with this i fully understand, i come at it from a different perspective as i was brought up and taught sometimes your best to make the best of a bad situation. Your from the same country as me so im sure you'll get this Hula Hoops analogy...............

I love Hula Hoops but their £1 a bag and i only have 50p but there is something similar Potato Rings made by Tesco which are 50p a bag i then have two options i can simply do without or i can buy the
Potato Rings sure their not as good as Hula Hoops but they'll do in the meantime.

**Comment by happppp** [comment]
That's the situation as it is now. Your PR is opening the Potato Rings bag
and pouring the contents into an empty Hula Hoops bag. :P

**Comment by mamehaze** [comment]
your analogy makes no sense in this situation.

this is not a 'bad situation' this is accurate documentation.

if you want to run the bootleg you can run the bootleg.

misrepresenting the set is a 'bad situation'

**Comment by gamez-fan** [comment]
Yeah fair enough i'll stick wiht the Hula Hopps

**Comment by rb6502** [comment]
I don't actually think this is so terrible, since it's clearly marked BAD_DUMP.  We do equally awful things to make sets run as an interim solution all the time, and there are known users who only play parent sets.

**Comment by mamehaze** [comment]
it's pointless tho, it just makes the clone and parent 100% identical.

we have no way to know if the bootleg is actually the same code revision as the label we have for the CPU, so we either have a potentially wrong label or scrap it completely (which this patch does, throwing away documentation)

all for no benefit, because you can already run the bootleg and get exactly the same result.

**Comment by mamehaze** [comment]
furthermore, I've seen people say in the past that some of the powerup behaviors in the bootleg don't seem quite right (IIRC it was in a MARP replay, something with the 1-ups?) so it's possible the unprotected bootleg set is actually hacked from an MCU protected bootleg set with the protection removed again, or it's a glitch in the game that happens in certain situations.

we have no idea how close the bootleg roms are to what should be in the module so using it as a fake rom in the parent set isn't even necessarily going to give correct results, it's just left placed where it is now, in the bootleg set.

**Pull request closed without merging**
