### PR TITLE
sun4c, SPARC, and NCR53C90 bugfixes

### PR DESCRIPTION
**Pull request by MooglyGuy**
-ncr5390: Fixed 'Select w/ ATN and Stop' command in DMA mode. [Ryan Holtz]

-ncr5390: Renamed to ncr53c90 to avoid confusion about the actual NCR part name. [Ryan Holtz]

-sun4c_mmu: Fixed l2p debugger command by removing inadvertent narrowing conversion. [Ryan Holtz]

-sparc: Avoid using temporary C-strings as address space names. [Ryan Holtz]

-sun4: Switched to NCR 53C90 from 53C90A, and fixed DMA byte-address masking. Along with 53c90 fix above, allows Solaris 2.4 to boot. [Ryan Holtz]

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
The NCR53C90 changes look OK, although it might be a good idea to leave this open for a bit for SCSI experts to take a look.

I’m a bit concerned about putting the first-generation SPARC ASI names in the base SPARC CPU class as defaults.  The ASI definitions changed between generations, e.g. for [microSPARC](https://www.ece.lsu.edu/ee4720/microsparc-IIep.pdf) where they switched to the more conventional TLB style “SPARC reference MMU” and six bits are decoded, it’s:
* 00 reserved
* 03 Ref MMU Flush/Probe
* 04 MMU Registers
* 06 Ref MMU Diagnostics
* 08 User Instruction
* 09 Supervisor Instruction
* 0A User Data
* 0B Supervisor Data
* 0C Instruction Cache Tag
* 0D Instruction Cache Data
* 0E Data Cache Tag
* 0F Data Cache Data
* 10 Flush I&D Cache Line (page)
* 11 Flush I&D Cache Line (seg)
* 12 Flush I&D Cache Line (reg)
* 13 Flush I&D Cache Line (ctxt)
* 14 Flush I&D Cache Line (user)
* 15-1F Reserved
* 20 Ref MMU Bypass
* 21-3F Reserved

It changes again with UltraSPARC, where various ASIs are used for things like alternate Endian accesses and the block copy/fill accelerator.

It’s probably better to have the ASI names in the MB86930 device.

**Comment by MooglyGuy** [comment]
@cuavas I believe my changes may have been misread: the base SPARC device has no specific ASI names, they're named "asi0" through "asi15". Only `mb86930_device` provides specifically-named ASIs for the time being.

**Comment by cuavas** [comment]
Ah, I did misread it.  Sorry, multi-tasking two other code reviews.

**Comment by cuavas** [comment]
At this point the NCR53C90 change is minimal.

**Comment by MooglyGuy** [comment]
No worries. Regarding the NCR53C90 changes, there were three notable changes, although I've now verified that the third was unnecessary, and so I've backed it out:
- Only the "Select w/ ATN" case was being handled for lowering ATN, but "Select w/ ATN and Stop" has the same behaviour, per the datasheet.
- Setting the sequence step to 2 instead of 1 more accurately reflects the step tables in the NCR53C90 datasheet.
- Line 552 (denoted by `// if it's the last message byte, deassert ATN before sending`) was insufficient if an attached DMA-driving device sends bytes until DRQ is lowered, as `ncr53c90_device::step` will never be called. The transfer-count register will be 0 by the time it occurs, so ATN will never have the opportunity to be lowered. In my opinion, both `== 1` checks should be changed to `<= 1`, but Solaris 2.4 still boots without it, so I'm happy backing it out.

I discussed the first two changes extensively with @galibert, so I believe they can go in without additional feedback, but it's also fine if you'd prefer to wait.

**Comment by galibert** [comment]
WTF?  I told you select with atn and stop did *not* lower atn, that's the entire point of the command.  It's the point 3 that needs to be fixed, but correctly.

**Comment by galibert** [comment]
Gee, that's not discord, that's public.  I meant to say, "there's been a misunderstanding between us, this is currently incorrect, we should fix it together".

**Comment by galibert** [comment]
This is in practice incorrect.  Select with ATN and stop is designed to send multi-byte messages by sending the first byte of the message and leaving atn active so that a subsequent transfer data sends the remaining bytes and drops atn.  The issue is point 3, transfer data not doing that correctly in the presence of dma.

**Pull request merged**
