### PR TITLE
Add optional manufacturer field for devices

### PR DESCRIPTION
**Pull request by ajrhacker**
- Include device manufacturers in XML listing (nw)
- Update device types in intelfsh.cpp to use the new manufacturer field (nw)
- Remove device_t::source(), making the field accessible only through the device type (nw)

### CODE REVIEW

**Comment by cuavas** [comment]
At what point do we get to deprecate devices without manufacturers?

**Comment by ajrhacker** [comment]
Given that MAME currently defines well over three thousand device types, I'm not going to attempt assigning a manufacturer for every one of them in one go. There's also the point that some MAME devices (e.g. input_merger) really are just generic abstractions.

**Comment by cuavas** [comment]
Oh, BTW please use `MFG` rather than `MFT` as a three-letter abbreviation for "manufacturer".  It's at least [somewhat accepted](https://www.collinsdictionary.com/dictionary/english/mfg) in general English use.

**Comment by Pernod70** [comment]
Wouldn't this also be a good time to add a year field? This would be especially useful for peripheral devices.

**Comment by ajrhacker** [comment]
I see year fields as irrelevant trivia for most devices. Years of release usually go unmentioned in lists of parts and datasheets, and it's expected that older parts can be replaced with newer parts either during manufacturing or repairs. Perhaps it would be better to have year fields only for devices with their own ROM sets.

**Comment by Pernod70** [comment]
I agree that year is irrelevant for devices that represent individual IC's. It's the bus devices I'd like to specify a year for (and manufacturer) but not all bus devices will have a ROM set.
Maybe further discussion required for addition of year, and continue with manufacturer only for now.

**Comment by ajrhacker** [comment]
From the Shout Box at Bannister, regarding the recently-added inyourfa having an incorrect year in mame.lst:

> Stiletto: "Osso: For my defense, every now and then it's said that mame.lst will disappear in its current form so all that metadata will be useless"
> Stiletto: if that metadata *still* hasnt been copied into the individual driver files then we have a problem
> Osso: in this case it was just year and revision, which are in the driver. In other cases, there can be more, yes
> R. Belmont: that metadata should really be in arcade-history instead of MAME anyway
> R. Belmont: I'm completely serious that I think we should stop having the year in drivers.

**Comment by rb6502** [comment]
Is this something we're interested in pursuing?  I think a manufacturer field for devices is actually a "wait, we don't do that already?" thing.  For the reasons AJR mentioned I don't think a year field makes sense, but that wasn't part of this anyway.

**Pull request closed without merging**
