### PR TITLE
New working clone

### PR DESCRIPTION
**Pull request by algestam**
-----------------
Morskaja ataka [algestam, Milan Galcik]

This Elektronika G&W Mickey Mouse clone doesn't seem to have any confirmed export version name. The release year is marked as unknown since no reliable source has been found.

### CODE REVIEW

**Comment by happppp** [comment]
PR itself is good.

But I want to change my mind on giving the English export titles preference. Instead, go for the more common local Soviet/Russian version (transliteration) for all Elektronika G&W clones. For example, not "Merry Cook", but "Vesjolyj povar".
What do you think, does it make more sense?

It's not related to this PR, but I wanted to ask it publicly instead of email, so other people may see and give an opinion.

**Comment by algestam** [comment]
I agree that using the transliterated title for all Elektronika G&W clones make more sense and will be more consistent. A problem with the current approach (where the export title is preferred) is also that the game needs to be renamed if an export title is confirmed at a later time for games without an export title at the time the game is added.

**Comment by happppp** [comment]
The rename problem already exists if we change the existing export ones now ;p
Though it will be in 1 quick sweep

**Comment by stilett0** [comment]
For future reference (for anyone reading), we almost always prefer transliteration over translation.
https://docs.mamedev.org/techspecs/naming.html

**Comment by algestam** [comment]
I can rename the existing titles with English names to the transliterated original title. Will finish the last game in the current batch and proceed with the renaming after that.

**Comment by cuavas** [comment]
Please use the common English “phone book” transliterations for Russian titles (“ye”, “yo”, “yu”, “ya” for soft vowels, not “je”, “jo” etc.).

**Comment by stilett0** [comment]
Quasi-OT: I suspect this issue might also apply to anything we have ever added that ever was a Russian arcade game (15kop.ru stuff, if anything) - but that wouldn't be algestam's fault nor responsibility to fix. @cuavas , let's make a note to add Russian to https://docs.mamedev.org/techspecs/naming.html :)

**Pull request merged**
