### PR TITLE
bgfx crt-geom and crt-geom-deluxe improvements

### PR DESCRIPTION
**Pull request by cgwg**
In addition to some reduction of duplicate code, there are two improvements:
1. In crt-geom-deluxe, the Gaussian blur used for the halation uses more taps, allowing a wider blur.
2. The sRGB gamma ramp has been added as an option and made the default. This should reduce the long trails of phosphor persistence reported by some users.

As usual, I can't generate the full set of shader targets, so someone with Windows would have to do that.

### CODE REVIEW

**Comment by ICEknigh7** [comment]
While you're updating this, please have a look at this edit of `crt-geom-deluxe.json` that I've been preparing for the last few weeks: [https://pastebin.com/jyHRtmCD](https://pastebin.com/jyHRtmCD)

I've been tweaking the shader effects and comparing the results with a real CRT to make things look more like the real thing, with some of the effects now being much more subtle than the defaults.

In order for them to look realistic, I had to set a couple of values to even less than the possible minimum (0.0075 for "Phosphor amplitude", 0.005 for "Halation amplitude"), since anything else looked noticeably more "bloomy" than a CRT in direct comparison, so maybe those sliders could be tweaked with this information?

**Comment by ICEknigh7** [comment]
Also, please check out this related bug report: [https://mametesters.org/view.php?id=8089](https://mametesters.org/view.php?id=8089)

**Comment by cgwg** [comment]
@ICEknigh7 Unfortunately you will probably have to re-tweak your settings with these changes. The switch to the sRGB gamma ramp has a significant effect on very dark parts of the image, such as the outer edges of the halation and the long tail of the phosphor persistence. Another concern I have is that the quality of LCD displays can vary quite significantly, so settings that are good for you might not work well on others' displays.

Concerning your bug report: I don't understand it. The halation effect has always been modulated by the shadow mask, including in your screenshot.

**Comment by ICEknigh7** [comment]
> @ICEknigh7 Unfortunately you will probably have to re-tweak your settings with these changes.

I see, I'll just readjust things once the new version is out and then make an updated submission.
In any case, those two sliders I mentioned seem to be a bit "uncalibrated" with respect to the actual values which look more realistic (though maybe that's been changed already).


> Another concern I have is that the quality of LCD displays can vary quite significantly, so settings that are good for you might not work well on others' displays.

I think the aim here would be to make it look like a real CRT when using good quality LCDs, and then give people with bad ones the option for tweaking the sliders?
Adjusting it for bad displays and thus, giving people with good LCDs a less realistic result right off the bat would make less sense, in my opinion.


> Concerning your bug report: I don't understand it. The halation effect has always been modulated by the shadow mask, including in your screenshot.

Currently, a halation effect with a value higher than the minimum looks as if it was rendering its glow without the shadow mask fully covering it (something which can be actually observed on the real hardware screenshot, in the form of overlapping lines).
On the other hand, the shader doesn't seem to have this problem when rendering the phosphor persistence.

**Comment by cgwg** [comment]
@ICEknigh7 Sure, if you have a calibrated display then maybe your settings could be useful for others.

halation5x
Here's a crop and 5x zoom of your screenshot. Aside from some jpeg artifacts, the shadow mask effect is present everywhere.

Anyway, this is getting off-topic and is not related to the pull request. You could try opening a separate issue. (Or if it's not considered appropriate here, you could create an issue in my fork repository of MAME.)

**Comment by ICEknigh7** [comment]
Ok thanks, will wait for the next release or nightly after this PR is merged and keep doing tests from there.

**Comment by cuavas** [comment]
If I can’t rebuild the shaders locally, I’ll pick them up from the CI build.

**Pull request merged**
