### PR TITLE
namcos1.cpp: Fixed abbreviated title, and added allow continue DIPSW of Beraboh Man

### PR DESCRIPTION
**Pull request by sasuke-arcade**
- Added Beraboh Man allow continue setting (DIPSW4).
- Fixed unofficially abbreviated titles
  - Beraboh Man (ベラボーマン) -> Cho-Zetsurin-Jin Beraboh Man ([超絶倫人ベラボーマン](https://ja.wikipedia.org/wiki/%E8%B6%85%E7%B5%B6%E5%80%AB%E4%BA%BA%E3%83%99%E3%83%A9%E3%83%9C%E3%83%BC%E3%83%9E%E3%83%B3))
    - Cho (超) = Super
    - Zetsurin (絶倫) = Matchless
    - Jin (人) = Human
  - World Stadium (ワールドスタジアム) -> Pro Yakyuu World Stadium ([プロ野球 ワールドスタジアム](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E9%87%8E%E7%90%83%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%82%B9%E3%82%BF%E3%82%B8%E3%82%A2%E3%83%A0))
    - Yakyuu (野球) = Baseball
  - World Court (ワールドコート) -> Pro Tennis World Court ([プロテニス ワールドコート](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%83%86%E3%83%8B%E3%82%B9_%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%82%B3%E3%83%BC%E3%83%88))

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
Why the weird hyphenation?  Also, you’re including an additional “u” for sound extension in “Yakyuu”, so why not in “Chou” as well?

**Comment by sasuke-arcade** [comment]
> Why the weird hyphenation?

"超絶倫人" is a combination of three words, but is recognized as one word in Japanese.
MAME uses hyphens for such titles, so and used it here as well.
If no hyphens, the words will look separated and feel strange for Japanese language.
eg. 4ini-uch Mahjoung Jantotsu, Kyohkoh-Toppa, Dai-Dai-Kakumei, Dan-Ku-Ga, Makau-Mura etc.

> Also, you’re including an additional “u” for sound extension in “Yakyuu”, so why not in “Chou” as well?

I hadn't yet looked up "Cho" in other game titles from MAME.
I looked up a same pronunciation titles, and it was using "Chou", so I changed it.
eg. Quiz Nanairo Dreams: Nicjiirochou no Kiseki, Chouji Meikyuu Legion etc.

**Comment by cuavas** [comment]
We’re trying to move towards more standardised tranliterations.

**Comment by sasuke-arcade** [comment]
Writing Japanese in Romanization are several different notations, and none of them are wrong.
So in the current MAME, there seem to be some notations that are not unified.
(Makai-Mura and Daimakaimura etc.)
If a unified policy for MAME is decided upon, I can align with it.
Also, if the decision is difficult to make now, we can send this title change to Testers and close this PR, and separating only the DIPSW change to the new PR.

**Comment by cuavas** [comment]
Hyphenating “Makai-Mura” is silly, and I wouldn’t accept it now anyway.  If you were to try translating it, you’d end up with “Hellville” if you went for a compound word, or “Hell Village”, or even “Village From Hell”.  The English equivalent would never be hyphenated anyway.

I’m not sure we should be keeping the “Beraboh Man” title at all – the Japanese a slightly unconventional transliteration of “Bravoman”, and our policy is not to use back-transliterations of loanwords (e.g. “Mahjong Sisters”, not “Maajan Shisutaazu”).

**Comment by sasuke-arcade** [comment]
Understood, I will remove hyphens soon from "Chou-Zetsurin-Jin".

About "Beraboh Man":
Beraboh is derived from the Japanese word "beraboh" ([べらぼう](https://www.weblio.jp/content/%E3%81%B9%E3%82%89%E3%81%BC%E3%81%86)), which has nothing to do with bravo ([ブラボー](https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%A9%E3%83%9C%E3%83%BC)). In short, it is not back-transliterations.

"Bravoman" is the following titles:
- The overseas version for TG16
- The webcomic created in canada
- Smartphone game based on a webcomic. It localized from English to Japanese

These title was probably changed from "Beraboh" to "Bravo" in order to target the whole world, not just Japan.
"Bravoman" would change the meaning of the word, so I think "Beraboh Mah" may be the correct title for Japan version.

**Comment by sasuke-arcade** [comment]
image
I found "Berabow" that in the default ranking.

**Comment by cuavas** [comment]
OK, it looks like “Berabow” is the closest we have to an official Latin transliteration.  Would you be happy with “Chou Zetsurinjin Berabowman”?

**Comment by sasuke-arcade** [comment]
Yes, this is fine! I replaced to "Chou Zetsurinjin Berabowman".

**Pull request merged**
