### PR TITLE
First part of April's Apple II software list updates.

### PR DESCRIPTION
**Pull request by Firehawke**
Fixed dump of Choplifter, a large number of disk copiers.

### CODE REVIEW

**Comment by galibert** [comment]
Beware, CI failed on lsmith60A (the uppercase A I guess).

  OG.

**Comment by Firehawke** [comment]
> 

Thanks. Not sure how that happened, but I'll have that fixed shortly.

**Comment by Firehawke** [comment]
For anyone else looking at this: Feel free to comment if you see any issues, but I'll do the actual merge near the end of April so I can do a final clean-up during the merge.

**Comment by rb6502** [comment]
I'd like to request this be added before this goes in if possible (next month is OK too though): https://www.dropbox.com/sh/f1gwo507f0a8c7y/AABJ4W4QWAyEom9JCNAR_EAZa?dl=0

The story is amazing: https://www.dropbox.com/s/a63jbfppf6h7l8j/Preserving%20DRUGS-%20Their%20Effects%20On%20You%20by%20MarshWare.docx?dl=0

**Comment by Firehawke** [comment]
I'll try to get that in right now.

**Comment by Firehawke** [comment]
Well, Passport.py didn't get it-- could be for one of several reasons off the top of my head.

../passport.py/passport.py convert DRUGS-\ Their\ Effects\ On\ You\ -\ Disk\ 1,\ Side\ B.a2r
Traceback (most recent call last):
  File "/home/firehawke/projects/softlistworkspace/chopgen/../passport.py/passport.py", line 86, in <module>
    args.action(args)
  File "/home/firehawke/projects/softlistworkspace/chopgen/../passport.py/passport.py", line 44, in __call__
    self.processor(args.file, self.reader(f), self.logger)
  File "/home/firehawke/projects/softlistworkspace/passport.py/passport/a2rimage.py", line 11, in __init__
    self.a2r_image = a2rchery.A2RReader(stream=iostream)
  File "/home/firehawke/projects/softlistworkspace/passport.py/passport/a2rchery.py", line 152, in __init__
    self.__process_header(header_raw)
  File "/home/firehawke/projects/softlistworkspace/passport.py/passport/a2rchery.py", line 171, in __process_header
    raise_if(data[:4] != kA2R2, A2RHeaderError_NoA2R2, "Magic string 'A2R2' not present at offset 0")
  File "/home/firehawke/projects/softlistworkspace/passport.py/passport/a2rchery.py", line 77, in raise_if
    if cond: raise e(s)
passport.a2rchery.A2RHeaderError_NoA2R2: Magic string 'A2R2' not present at offset 0

Unfortunately, I won't have time to throw at this, if I'd caught this last night I probably could have gotten it but I have several major tasks I need to get done right this sec. I'll poke the Slack crowd late tonight and hope Vas will let me slip one last item into a new PR for the month if they get back to me fast enough. For now, let me get what I have in.

**Pull request merged**
