### PR TITLE
added Boku wa Plarail Untenshi Shinkansen de Ikou! (playable but SEEPROM still needs hooking up)

### PR DESCRIPTION
**Pull request by mamehaze**

### CODE REVIEW

**Comment by mamehaze** [comment]
it should be the prequel (non-plus version) of prailpls in generalplus_gpl16250_spi.cpp

**Comment by mamehaze** [comment]
this might be of interest to @sp1187 too as it has sound looping issues (as in the engine sounds don't loop properly at all, leaving a lot of the game in silence)

**Comment by mamehaze** [comment]
I'm not entirely sure where / how the SEEPROM hooks up, I *think* the writes are on port C, but the read pattern doesn't match what I'd expect to actually read from it.  Going to mark this as ready and just revisit later.

**Review by cuavas — COMMENTED** [review]
There are no comments or warning flags to indicate that the serial EEPROM isn’t hooked up.  It should at least be noted in the source.

**Comment by mamehaze** [comment]
added a note

**Comment by cuavas** [comment]
Also missing credits, but I assume it’s another TeamEurope dump.

**Comment by mamehaze** [comment]
yeah, sorry, this is another I picked up and TeamEurope dumped

**Pull request merged**
