### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
Game & Watch: Mario The Juggler [algestam, Mr. Do, Sean Riddle]

### CODE REVIEW

**Comment by happppp** [comment]
Ah, "MJ-108" in the gamelist isn't right (and neither is Wikipedia then, where I copied the model names from ;P)

**Comment by algestam** [comment]
Good catch, I'll submit a fix!

**Comment by algestam** [comment]
Fix committed here: https://github.com/mamedev/mame/pull/5855

**Comment by happppp** [comment]
Ok!

**Pull request merged**
