### PR TITLE
Add websocket-based external panels to the Ensoniq VFX & friends

### PR DESCRIPTION
**Pull request by cbrunschen**
Import the websocketpp library from https://github.com/zaphoyd/websocketpp into 3rdparty.

Using this, add websocket server for external panels to the esqpanel class for the Ensoniq VFX, VFX-SD, SD-1 and SD-1/32 keyboards. This is served as HTML and Javascript with keyboard type and protocol version information, which allows the client to reconnect automatiically and reload the page if it finds the wrong keyboard type or version.

The provided front panel includes the VFD as well as all of the buttons and sliders present on the Ensoniq VFX series. It does not currently handle the pitch and modulation wheels or the Patch Select buttons.

The main reason to use an external panel is that this allows the use of touch-screen devices such as tablets, which can also be kept close by the MIDI controller used for playing the keyboard. This combination gives an experience that is very close to that of using an actual Ensoniq keyboard, since all the buttons are pressed and sliders are moved in the expected way, including allowing multi-touch (such as the 'Preset + Compare' combination to show the analog tests, or pressing both increment and decrement buttons together to choose a default value). Because the server supports multiple external connections at the same time, you could even use multiple smaller tablets side-by-side, each showing a part of the original panel, to give a full-size experience.

### CODE REVIEW

**Comment by cuavas** [comment]
A single-driver hack isn't the direction we want for this. A possible implementation that would be considered would be extending the output module system to support controlling inputs as well, and providing a WebSockets-based module.

**Comment by mmicko** [comment]
@cbrunschen  can websocketpp be used to provide http server capabilities as well, or it is limited to web sockets only ? I have start some work on https://github.com/vinniefalco/beast to make it work without boost, but it will take some time

**Comment by cbrunschen** [comment]
websocketpp includes light-weight HTTP serving, and I'm using it to serve the HTTP & Javascript.

A more general-purpose solution would definitely be better in the long run, but right now this would make these particular keyboards a lot more useful and actually playable, which can make debugging the remaining issues with them a lot easier.

**Comment by mmicko** [comment]
Ok. I will take a look and do some more generic version. Will keep you in loop for this.

**Comment by cbrunschen** [comment]
Thank you!

Websocketpp already works nicely with standalone ASIO, which made it very easy to use.

For my use case I basically need a way for the panel to be able to register handlers to serve its HTML and Javascript, as well as accept incoming websocket connections and send & receive messages on them. Currently, this is all within the esqpanel_device class itself, but I can also take a stab at putting the websocket & HTTP server into a module instead, and have the panel use that.

**Comment by cbrunschen** [comment]
Websocketpp's HTTP handling is described a bit here: https://www.zaphoyd.com/websocketpp/manual/reference/handler-list/httphandler

**Comment by rb6502** [comment]
I'd like to see MAME's HTTP interface come back in general, and then add a mechanism by which drivers could add their own pages.  Good luck, Micko :)

**Comment by cbrunschen** [comment]
I've just sent https://github.com/mamedev/mame/pull/1625 that creates a separate webserver module, including both a no-op implementation and one based on websocketpp ; and with the external-panel support based on that. If nothing else, it can serve as a point for discussion around how this might be done better, giving a particular use case.

**Pull request closed without merging**
