### PR TITLE
Major overhaul of input type list construction

### PR DESCRIPTION
**Pull request by ajrhacker**
- Friendly default input names are assigned by the frontend, which makes them available for translation
- More strings in UI input menu available for translation
- Move default input sequences down into input classes (nw)
- Input tokens are generated at runtime, making the INPUT_PORT_XXX_TYPE macros obsolete (nw)
- Additional macros, predicates and helper functions provided for cleanliness (nw)

### CODE REVIEW

**Comment by mmicko** [comment]
This one is rather big, so would like to ask people to check if they have objection on this one

**Comment by ajrhacker** [comment]
Yes, it's big; the sheer size of this pull request is why it's been split into three commits. The first commit (separating the default sequences by input type) preceded the other two in my plans; I only realized the full potential of separating out the inpttype structure later. What inspired me to move the input names to where the frontend can translate them was disassembling German poker games that have multi-language support in their service modes.

I still have considerable doubts about the appropriateness of some of the standard input names; for instance, I'd prefer "Mahjong Take Score" to "Mahjong Score," and "Book-Keeping" could at least lose the unnecessary hyphenation. Also, changing the structure of the input type list itself to something like std::unordered_map would probably make some aspects of this cleaner.

Customizing the input names in mame_machine_manager::create_custom is admittedly more of an opportunistic implementation than an elegant one. However, the most obvious point of failure has been taken into account: if some future frontend neglects to name the inputs itself, MAME will use the configuration tokens as a fallback, which won't look so nice but at least make it possible to tell them apart.

Of course there's no way to localize driver-supplied PORT_NAMEs, which MAMEdevs have started to look upon as vaguely deprecated (#1513). My own plan for that is to introduce the concept of an "overlay" file, loosely analogous to the physical overlay cards supplied with many game cartridges, that when loaded will rename generic input fields to indicate their game-specific functions.

**Comment by rb6502** [comment]
@ajrhacker Is this still relevant and how you'd do this?  If so, I'm inclined to go ahead and apply it.

**Comment by ajrhacker** [comment]
Yes, there are a few worries I have about this:
* This will make it somewhat harder to add new input types. Though it's true that not many of those have been seen fit to add in the last few years, some others might be worth implementing, considering that MAME has been adding more and more types of machines.
* There's no translation support for DIP switch names and settings. MAME does have a library of standard labels for these, but they are often incredibly driver-specific, so I don't think they're really worth customizing anyway.
* mame.cpp is a bit of an ugly place for the frontend to customize the input names. A Lua script would be neater, but that would require a little more support from various APIs.
* The lack of msgctxt support is starting to really hurt.

I still think it's a good idea to have the input classes provide the standard input sequences. Not only does make the control schemes easier to understand, with some further architectural changes, the OSD layer will be able to subclass the input class types and handle its own customizations there.

**Pull request closed without merging**
