### PR TITLE
new working clone

### PR DESCRIPTION
**Pull request by clawgrip**
New Clone Added
---------------------------------------------
Pac-Man (Video Dens, Spanish bootleg on Galaxian hardware) [ClawGrip, Roberto Fresca, Recreativas.org, The Dumping Union]

### CODE REVIEW

**Comment by Osso13** [comment]
Unless I'm missing something, the set name you added to mame.lst doesn't match the one you added in the driver.

**Comment by clawgrip** [comment]
You're right. I'm right now using the web interface and I'm having problems with the lst. The new clone is pacmanbv ("v" after "Video Dens") Can you edit the PR or should I?

**Comment by clawgrip** [comment]
Nevermind, I'll close and reopen it. Sorry for the annoyance.

**Comment by stilett0** [comment]
For future reference @clawgrip: the mame.lst file is unable to be edited via the web interface due to its length and size. You'll have to use a Git client. If you don't want to use the command line/terminal... on Windows I've learned to use Github Desktop for Windows and a text editor of my choosing, it's not too hard to figure out.

**Comment by clawgrip** [comment]
Thanks!
Also, I'm finding that if I edit mame.lst with Windows standard notepad I get compile errors, while it compiles fine when I use vi, is there any problem with UNIX vs. DOS CR/LF on that particular file?
Anyway, it may take long until I set up a git client, so I'd be glad if anyone could add this clone. It's just a simple ROM swap.
Thanks again.

**Pull request closed without merging**
