### PR TITLE
ksys573.cpp - Let’s kick some typo.

### PR DESCRIPTION
**Pull request by mikehyrus**
Remove unneeded undumped asterisk for Kick & Kick.

### CODE REVIEW

**Comment by mikehyrus** [comment]
Doing this because Kick & Kick was recently dumped over a month ago.

**Comment by mikehyrus** [comment]
Chose to mention the evidence I found.

Korea

Asia

(Images by The Cutting Room Floor)

**Comment by mikehyrus** [comment]
Evidence I found so far.

Korea title



Asia



(Images by The Cutting Room Floor)

**Comment by mikehyrus** [comment]
Evidence I found.

https://tcrf.net/Mambo_a_Go_Go

**Comment by mikehyrus** [comment]
Evidence I found for Mambo A GoGo region names.

https://tcrf.net/Mambo_a_Go_Go

**Comment by 987123879113** [comment]
The other Mambo a Go Go regions aren't undumped, they were never released. That's why they're only accessible via patching the game data.

**Pull request merged**
