### PR TITLE
Separate Apple II video config from system config

### PR DESCRIPTION
**Pull request by benrg**
Add a `a2_video_config` port to contain the monitor type (with the idea of adding other settings later), and add some private accessors to avoid magic numbers. This incidentally fixes a bug in `apple2` and `apple2cp` which had another configuration field that overlapped with the monitor-type field. On the IIc+, setting 80-column mode would make the video system think a IIe RGB card was installed.

### CODE REVIEW

**Comment by benrg** [comment]
I'm not sure I did this correctly.

Is there any way to avoid the duplication in the definitions of `apple2_vidconfig` and `apple2_vidconfig_rgb`?

The monitor type switch appears below all other settings in the UI after this change, even though I kept the old order in the files. Can that be fixed? I don't mind it personally, but it's a visible change.

**Comment by rb6502** [comment]
Ideally the video config switches would just belong to the video device (e.g. mv_sonora.cpp for a shared Mac video device that does that), but that does mean you'd need to subclass the a2_video_device to have an a2_video_device_rgb that allows setting "RGB" as the monitor type for the IIe.  (Look at v8.cpp/.h to see what a device class with subclasses looks like).

**Comment by benrg** [comment]
apple2e.cpp defines many machines, some with RGB support and some not, that use the same `apple2e_state` class, which has a `required_device<a2_video_device>` member. How would I handle that? Subclass `apple2e_state`, have the `required_device` in the subclasses, and send all accesses through a virtual function? Or initialize `a2_video_device *m_video` from the actual device pointer? Would everything still work, binding to members, etc? I'd probably have to rename the base class, and all of the hundreds of `apple2e_state::`s in the file would become `apple2e_state_base::`... It seems like a lot of work and code clutter for one fairly obscure piece of hardware, when much bigger differences between machines are handled without subclassing.

**Comment by rb6502** [comment]
It's both legal and common to required_device<> a class's parent class type.  For instance, in apple2e.cpp m_maincpu references required_device<cpu_device> which all CPUs subclass rather than specifically m6502_device or m65c02_device.

**Comment by benrg** [comment]
It looks like the build breakage had nothing to do with me.

I had to remove `const` from the accessors because `read_safe` isn't `const`, though seemingly it should be.

**Comment by cracyc** [comment]
i8087.c built successfully here.  Your problem is different.
```

Run ./mame -validate
Driver mpf2 (file tk2000.cpp): 1 errors, 0 warnings
Errors:
   Required I/O port ':a2_config' not found

Driver tk2000 (file tk2000.cpp): 1 errors, 0 warnings
Errors:
   Required I/O port ':a2_config' not found

Validity check failed (2 errors, 0 warnings in total)
Error: Process completed with exit code 1.
```

**Comment by cracyc** [comment]
Okay, i looked at the wrong build.

**Pull request merged**
