### PR TITLE
Removed a hardcoded constant (nw)

### PR DESCRIPTION
**Pull request by npwoods**
Again, I'm not crazy about copying and pasting the expression '1 << (UCHAR_SHIFT_END - UCHAR_SHIFT_BEGIN + 1)' all over the place; if you have a better idea let me know

### CODE REVIEW

**Comment by cuavas** [comment]
Eugh, that isn't the only problem… You could make a constant for it in `ioport.h`, like a global `constexpr std::size_t IP_SHIFT_STATE_COUNT = …;` or something - that wouldn't increase coupling like using a member of the natural keyboard implementation does.

But did you notice that `UCHAR_MAMEKEY_BEGIN` is defined in terms of `UCHAR_PRIVATE` without any guard to ensure it doesn't accidentally overlap `UCHAR_SHIFT_*`?

Really, `UCHAR_SHIFT_*` and `UCHAR_MAMEKEY_*` should be noncharacters (as opposed to private use characters) since they're never supposed to be passed through an external system.  But there just aren't enough noncharacters for all the `ITEM_ID_*` to fit.  Perhaps `UCHAR_SHIFT_*` should be pushed down to the noncharacter block in the BMP at U+FDD0.

**Comment by npwoods** [comment]
Aren't there plenty of non-characters ripe for use if one starts way down at 0x110000?

**Comment by npwoods** [comment]
I've attempted to address your concerns by doing the following:
1. I've changed the various `UCHAR_` declarations to be an enum, to make it more difficult for `UCHAR_SHIFT_*` to bleed into the `UCHAR_MAMEKEY_BEGIN` range
2. Made `UCHAR_SHIFT_*` and `UCHAR_MAMEKEY_*` start at 0x110000, outside the range of valid unicode
3. Renated `UCHAR_PRIVATE` to be `UCHAR_NON_CHARACTER` to better reflect that these are not characters

I will note that some of the nomenclature (i.e. - use of the `UCHAR_` prefix) now falsely identifies these things as characters.  I realize that there is a strong possibility that this will elicit a strong objection from you, but it isn't clear to me what it should be called.  If you provide a better idea on how to name these, I will happily change things.

As always, please let me know how you want to proceed.

**Comment by cuavas** [comment]
Well, that comment isn't actually reflected in the code - there's still just one commit changing a number to an expression.  Also, I don't think you really understand this stuff.

Unicode noncharacters are part of the standard.  There are a block of them in the BMP starting at U+FDD0 (in the middle of an Arabic presentation forms group), and there are two of them at the end of each plane (U+xFFFE and U+xFFFF).  These assignments are subject to a stability guarantee.  The noncharacters can be safely encoded with all Unicode transforms (UTF-16, UTF-8, UTF-7, UTF-EBCDIC, etc.), and should be used when you need to embed something that isn't a character in a string or character value.  You aren't supposed to pass them through external systems, because they aren't characters.

Private use characters are a different concept, they're used for characters that aren't assigned a standard codepoint.  They can be passed through external systems, and parties can come to an agreement on how to use them.  One example of this is encoding characters from legacy encodings that have no Unicode equivalent, like the Apple logo character that appears in MacRoman.  MAME itself uses private use characters in the BMP for the symbols used when displaying command.dat and indicating selected filters in the UI.

There are a rather large number of private use characters on the top two Unicode planes (2^65-4 in total because of the four noncharacters).  MAME is using some of these for the `UCHAR_MAMEKEY` macro and to represent shift keys.  The thing is, these are not characters as such, which is why they'd be better suited to noncharacters than private use characters.  There's also a (somewhat remote) possibility that private use characters used this way could clash with the agreed private use characters actually used to represent characters a legacy system we emulate supports.

Values beyond the end of the second private use plane are not private use characters or noncharacters.  They're not valid codepoints at all.  They also can't be represented in UTF-16 for example.

**Comment by npwoods** [comment]
> Values beyond the end of the second private use plane are not private use characters or noncharacters. They're not valid codepoints at all. They also can't be represented in UTF-16 for example.

Ehhh?  That was precisely the point of pushing these values past the range of valid unicode characters.  The intention was that either these values are char32_t values that are either:
1. A Unicode code point
2. Something else that can map to a MAME ITEM_ID_* value

The intention with my change was that the burden is on the consumer of any of these char32_t values to handle either of these considerations; it would be illegal to pass one of these values to something that converted to UTF8/16 without ensuring that it is in the first category.  I articulated why the nomenclature (i.e. - the `UCHAR_` constants) was not ideal.

You articulated precisely why Unicode noncharacters could be used if it were not for the space considerations.  I suppose that `UCHAR_SHIFT_*` could be pushed down to the 0xFDD0 range, but what is the value of moving those two specific values down there while not moving the other `UCHAR_MAMEKEY` values?

As an aside, are we going to let issues like this block advancement in the Natural Keyboard?  My ultimate goal is to remove the limitations in the Natural Keyboard that prevent LEFT and BACKSPACE binding to the same character on the CoCo emulation.  In this case, this particular PR was to remove a hardcoded constant, something pretty much always considered bad in some form.  It is hard to make progress if even the most minuscule advancements get bogged down in issues like this.

**Comment by cuavas** [comment]
The constant in question is no longer present.

**Pull request closed without merging**
