### PR TITLE
Expansion systeme

### PR DESCRIPTION
**Pull request by hiroshica**
Sega's System-E board with extended FM sound source, Mark-III equivalent.
Reference Information
https://www.youtube.com/watch?v=7dLc9UZ81CI&list=FLKLfpOOH6SbAJzE3fl6lB1A&index=30

The following cheat codes will work.

<cheat desc="FantasyZone2 FM Patch">
    <script state="run">
    <action>maincpu.pb@DE00=01</action>
    </script>
</cheat>

The 0.245 repository is not buildable, so I created changes in the 0.244 repository.

### CODE REVIEW

**Comment by cuavas** [comment]
This has multiple issues:
* MAME 0.245 can definitely be built – it’s not like we fake continuous integration build results.
* The additional sound chip definitely shouldn’t be added to the base System E as it isn’t a standard part of the system.
* If this is a homebrew modifications it doesn’t belong in MAME itself.

**Comment by hiroshica** [comment]
What kind of fictitious System16C board would you add but not allow this kind of extension?
The laxity of the MAME DEV rules is irritating!

**Comment by hiroshica** [comment]
Please Close.

**Comment by einstein95** [comment]
> What kind of fictitious System16C board would you add but not allow this kind of extension?

If you had read `segas16b.cpp`, it says
> Sega operated this game on actual System 16 PCBs for various events

so no, it is not fictitious

**Comment by hiroshica** [comment]
ああ、そうですか。もういいです。これは閉じてください
改めて0.245のエラーを報告するべくビルドしているので.

**Comment by Robbbert** [comment]
Translates to:

Oh, I see. It's enough. Please close this
I'm building to report a 0.245 error again.

**Comment by DavidHaywood** [comment]
also the modified ROMs from that homebrew System E hack were never dumped.  We don't know what modifications were made to work with the sound board that was installed.  As observed, you have to at the very least hack the code to enable it as well as installing the extra chips.

**Pull request closed without merging**
