### PR TITLE
Added 4 controller support for N64/N64DD, as well as rough mouse support...

### PR DESCRIPTION
**Pull request by LuigiBlood**
.... You can select the device on each controller port.

### CODE REVIEW

**Comment by cuavas** [comment]
Is it really a good idea to do the mouse support this way?  I would've thought making it a slot device would be a better idea, making it easier to add other controller types (e.g. Densha De Go! controller) later.  Also, introducing global variables for the mouse is a red flag.  New code shouldn't be introducing things like that.

**Comment by etabeta78** [comment]
This approach is the "legacy way" to add input devices (still used e.g. by
megadrive), adopted when there were no slot devices available. I agree that
it would be better to use slot devices, of course, but maybe the patch can
be accepted and cleaned it up afterwards?

   f.

**Comment by cuavas** [comment]
Using globals for mouse input is still a bad sign - at the very least that should be cleaned up before accepting the patch.

**Comment by etabeta78** [comment]
oh yeah, those should just go inside the driver class, of course :)
I was referring only to the PORT_CONFIG stuff...

   f.

**Comment by LuigiBlood** [comment]
I didn't know about slot devices. And about the mouse input... it was a pain to do. I don't know how to do that without globals. I only looked at the Amiga files and Apple files.

**Comment by cuavas** [comment]
OK, good enough for me.  The globals have been eliminated, members are initialised on the right spot, multiple mouses should work.

**Pull request merged**
