### PR TITLE
atetris.cpp: Add remaining UM3482 ROM areas to 'atetb3482' [Sean Riddle]

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by ajrhacker** [comment]
I don't think formats that pack 7-bit or 9-bit words like this are going to be useful for emulation. It's more accepted practice to pad odd-width data out to the 8-bit, 16-bit, 32-bit and 64-bit formats modern compilers and the MAME core natively support.

**Comment by clawgrip** [comment]
You mean padding with one zero on 7-bits values and with seven zeroes on 9-bits values to make power of two words?

**Comment by ajrhacker** [comment]
Basically yes, much like is being done with 4-bit bipolar PROMs and 12-bit and 14-bit PICs.

**Comment by clawgrip** [comment]
Done, thx!

**Comment by happppp** [comment]
While an indexes rom is harmless compared to for example "Namco Pacman program rom, contents is 0x01 0x02 0x03 0x04...", I wouldn't put that info in MAME's source.

**Comment by clawgrip** [comment]
Done! Thanks!

**Comment by happppp** [comment]
All good then

**Pull request merged**
