### PR TITLE
MAME IBM and AT compatibles: Create seperate drivers for 286, 386sx, 386DX and 486 class machines

### PR DESCRIPTION
**Pull request by rfka01**
I've split the at.cpp driver like the title says, it was getting a bit unwieldy.
Please comment if that's not the preferred direction to go. No new drivers were added in this run.

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
I’m not sure this helps at all.  CPU isn’t really the main differentiating factor for these PCs.  This seems to replace one mess with another – for example you’ve got a copy/pasted driver state for the MegaPC Plus in amstr_megapc.cpp when it isn’t related to the other machine you moved to that source file anyway.

The file’s getting unwieldy, but this doesn’t get us any closer to grouping architecturally similar machines or moving towards better emulation of specific chipsets.  I’d much rather things get moved out when people actually start emulating specific PC models better, in the same way that various drivers have been moved out of mac.cpp as the emulation has been untangled.

**Comment by rfka01** [comment]
I've kept the MegaPCs together regardless of CPU as they need the Sega end bolted onto them anyway, as I understand them.

**Comment by angelosa** [comment]
Do we have some sort of family tree(s) documentation of any kind for these?

**Comment by rfka01** [comment]
As in how the chipsets evolved or what source file originated where?

**Comment by angelosa** [comment]
[IBM mainframes](https://www.ibm.com/ibm/history/exhibits/mainframe/mainframe_FT2.html)
PC98


Something like these but for XT, PCjr, AT and spin-offs.

**Comment by rfka01** [comment]
I think this would be nigh impossible from the point when the PC architecture sort of became an "industry standard" and IBM compatibility a must-have feature.

**Comment by davide125** [comment]
IMO the "broad strokes" evolutionary jumps for PCs are mostly marked the buses: 8 bit ISA (XT), 16 bit ISA (AT, 386, 486), EISA and MCA (386 and 486), VLB (486), PCI and AGP (late 486, 586, 686). For each of these, there were usually a set of well-known chipsets (e.g. [Intel](https://en.wikipedia.org/wiki/List_of_Intel_chipsets), [SiS](https://en.wikipedia.org/wiki/Silicon_Integrated_Systems), [VIA](https://en.wikipedia.org/wiki/List_of_VIA_chipsets)) that most systems would be built around. Bucketing by bus and then specializing by chipset could be a reasonable approach here.

**Comment by rfka01** [comment]
@davide125 If you will, that's the current state of at.cpp as even the 486 machines that are in there still need ISA, and the PCs and XTs are in their own driver files. They're sorted by chipset as best as I could find as well. 
ct486.cpp is an example of your proposed final stage, but unfortunately the chipset in there seems to have been used by just that one lone motherboard or even BIOS.

**Comment by cuavas** [comment]
The Amstrad MegaPC is really just a Mega Drive and PC in a single box.  They don’t interact in any way, and you can’t use both at the same time.  There’s a plastic slide thing on the front for choosing whether you want to use the Mega Drive or PC (it covers either the PC’s floppy drive or the Mega Drive’s cartridge slot and controller ports.  It’s not like a Teradrive.

**Pull request closed without merging**
