### PR TITLE
First version of HP9845B driver

### PR DESCRIPTION
**Pull request by fulivi**
Hi,

I've just pushed the first version of the hp9845b driver I'm working on. It's still WIP but it's usable.
Let me know where I should send the zip file with rom images, please.
Thanks.
-- F.Ulivi

### CODE REVIEW

**Comment by Pernod70** [comment]
Looking forward to trying this, I still used them at work in the 90's. Shame I didn't get to keep any software when the 8" drives eventually failed.

**Comment by Tafoid** [comment]
This looks to be the cause of compile issues - Windows - GCC 5.2.0
http://pastebin.com/q58y73Dy

**Comment by fulivi** [comment]
Hi, I've just pushed the missing overrides. Should I open a new pull
request for this? Branch is the same (hp9845_dev).
Thanks.
-- F.Ulivi

**Comment by mmicko** [comment]
yes, there is need for new pull

**Comment by Tafoid** [comment]
Regarding new roms for this submission, please send with info and as an
attachment to the submission email address located at:
http://wiki.mamedev.org/index.php/Submitting_Source_Code
Thank you.

**Pull request merged**
