### PR TITLE
Improvement GBA wavetable behavior, Adjust docs

### PR DESCRIPTION
**Pull request by cam900**
gb.cpp: Implement GBA specific bankswitched wavetable RAM/volume behavior
Add notes, Add imperfect_features due with incorrect sound pitch, Use lower case letter for hexadecimal values
gba.cpp: Fix XTAL docs(4.194304MHz clock input is internally multiplied by 4 for SoC), Add notes

### CODE REVIEW

**Comment by cuavas** [comment]
What’s a good example of software that uses this functionality for testing the change?

**Comment by cam900** [comment]
http://www.belogic.com/gba/channel3.shtml here is an homebrew demo for wave channel, supports wave bank size and bank swap.

**Comment by cuavas** [comment]
Can someone please test this?  The code looks OK, but I’d like someone to do at least a quick test of it before it’s merged.

**Comment by Tafoid** [comment]
@cuavas I can't even get the demo rom to load in current gameboy emulation as a -cart:
"Fatal error: Device Game Boy Cartridge Slot load failed: Invalid ROM file size"
It isn't a power of 2 expected size and outside of adjusting source I'm not sure how to go about forcing it to even test the before patch behaviour.

**Comment by cam900** [comment]
Both demo that linked in above and Wavetable bank function is for Game Boy Advance exclusive, Please try to load demo on GBA.

**Comment by rb6502** [comment]
Tested and manually merged in https://github.com/mamedev/mame/commit/39f54e4399d9196dcbc84410f60d4e981fbc7ef6

**Comment by ICEknigh7** [comment]
These changes seem to have almost fixed the music in `gwatch4` and other `gba` entries but for some reason broken one of the sound channels in `gbcolor`.

**Pull request closed without merging**
