### PR TITLE
vgmplay.cpp : Volume Modifier Support, Typo

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by Tafoid** [comment]
I've noticed many vgms/all tested in vgmplay now play at a greatly decreased volume - in some cases such a low volume that you need to adjust your system's master volume to 50% or more just to be able to hear anything. I do not understand what this commit does or how it improves things or find any new to adjust volume internal to the emulation on the fly which is what I assume this is supposed to do?

I'd suggest reverting as I see no real advantages to this commit unless it can be explained?

**Comment by MooglyGuy** [comment]
Your assumption is not correct. There is nothing about this change that would indicate that this has anything to do with allowing the user to adjust volume. Quite the opposite. The VGM spec allows a VGM file to specify a volume modifier. This change implements that. If the VGM volume now seems "too low", it is only because it was previously too high, and MAME is now complying with the actual values specified in the VGM files themselves.

**Comment by Tafoid** [comment]
I was under the assumption that behavior between actual emulation and vgmlog playable of the emulation should be the same?  Is it now that volumes were not logged properly in all cases?  Perhaps I'll need to test it because with the vgms currently made there is a huge difference in volume between that output and actual machine emulation in MAME.

**Comment by ValleyBell** [comment]
Handling of the VGM volume modifier (`volbyte` in the code) is correct.  
However, the calculation of the per-chip volume isn't. (And this is what causes the lower volume overall.) What VGMPlay does, it basically* this:
```
estimated_volume = 0.0;
for (chip : used_chips)
  estimated_volume += 1.0; // or 0.5 in dual-chip mode
final_volume = estimated_volume;
// multiply of divide all chip volume levels by 2 until final_volume is in the interval [1.0, 2.0]
```
When 2 instances of the same chip (e.g. 2x YM2612) are used, each instance gets its volume halved and thus only 0.5 is added to the "estimated_volume" value.

\* except that it's using tons of LUTs with per-chip volume levels for fine-tuning to get a sort of decent volume balance

I probably wouldn't try to recreate what VGMPlay does, but doubling the overall volume or at least not damping it unless >=3 chips are used might help.

**Comment by cuavas** [comment]
I can understand why he did that - it's supposed to prevent clipping when multiple chips are present.  But it obviously reduces volume in the presence of more chips.

**Pull request merged**
