### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Badabilly**
sigmab52.c updates

### CODE REVIEW

**Comment by Badabilly** [comment]
Sorry about the foul up. Please ignore the first 8.

**Comment by cuavas** [comment]
Sorry, but you've screwed up this pull request again.  Look at the preview under the "Files changed" tab on this page.  It has all the crud from a conflicted merge gone badly wrong in the HMCS40 CPU core.

**Comment by cuavas** [comment]
I think you've somehow got your branch into a state where you'd be better off forcibly overwriting it with mainline MAME and doing the change again.

**Comment by Badabilly** [comment]
Not sure why it won't let me close or remove those. I'll try that tomorrow. Sorry about the hassle.

**Pull request closed without merging**
