### PR TITLE
Created DYNAMIC_API macros for dynamic bind helper classes

### PR DESCRIPTION
**Pull request by bradhugh**
UWP needs a way to call the original (statically bound) functions while we want to dynamically bind them in Win32. Created macros that define helper classes and make them easy to call in a uniform way. UWP implementation just calls the original functions directly.

### CODE REVIEW

**Comment by cuavas** [comment]
Anything with function statics for singletons is unacceptable because of thread safety (or rather, complete lack thereof). You're going to need to find a better way than this.

**Comment by bradhugh** [comment]
I've addressed your comments but made a mess of my branch in the process.  Hold on merging this until I squash and rebase a bit.

**Comment by bradhugh** [comment]
Hm... having issues with this new approach (though it worked in MSVC). Are you sure the function local static would be a problem?  This seems to indicate they would be fine: http://en.cppreference.com/w/cpp/thread/call_once

"Initialization of function-local statics is guaranteed to occur only once even when called from multiple threads, and may be more efficient than the equivalent code using std::call_once. "

Am I missing something?

**Comment by cuavas** [comment]
There's a race condition with function statics because it effectively uses an unprotected Boolean to check whether it's been initialised.  It works as long as two threads don't call the function at the same time when it hasn't been called before, but it's a dangerous assumption to make.  Tracking down these issues is a nightmare.

**Comment by bradhugh** [comment]
Ok, sounds good. I think I fixed the new implementation with call_once which should be guaranteed. Please check if it looks ok.

**Comment by cuavas** [comment]
It's too much overhead to be checking a once flag on every invocation of a function, at the very least it causes an atomic fetch and write/read fence which are not cheap on modern memory architectures.  You're adding a lot of overhead to Windows for UWP support.  Also, a hack for UWP like this shouldn't be in a common header used on all platforms.  Is there really no way to just hack the `osd_dynamic_module` class on UWP to look up functions in application symbol space or something?

**Comment by bradhugh** [comment]
This isn't really just for UWP. Windows could also statically bind the functions and it would be altogether faster than the dynamic binding we're doing now.  This is actually just a choice between static and dynamic binding, not anything UWP specific.  Would a simple optimization be a != nullptr check and early return if the static member is already initialized?

**Comment by bradhugh** [comment]
I also could rethink these macros as a mix-in to define, call, and initialize the function pointers as members of whatever module class defines them.  That would avoid the singleton instances altogether and locking concerns.

**Comment by bradhugh** [comment]
This latest change takes my last described approach and is no more expensive than the original implementation.  It also makes defining and calling these functions uniform whether using dynamic binding or static binding.

**Comment by bradhugh** [comment]
@cuavas how are we looking here? Any objections to the revised implementation?

**Comment by cuavas** [comment]
Sorry for the delay.  It looks OK now.  Could you just change the names to be `OSD_DYNAMIC_xxx` rather than just `DYNAMIC_XXX_`?  I'm trying to think about the sociability of our libraries.

**Comment by bradhugh** [comment]
Sounds good - will update.

**Pull request merged**
