### PR TITLE
New WORKING clone

### PR DESCRIPTION
**Pull request by clawgrip**
--------------------------------
Cobra-Command (World/US, alt) [Victor Fernandez (City Game)]

### CODE REVIEW

**Comment by cuavas** [comment]
Does this only differ in graphics ROMs, or am I missing something?  (The program ROMs all seem to match the “b” suffix set.)  If that’s the case, which graphics have been changed, and how can we confirm that this is a good dump?

**Comment by Tafoid** [comment]
Did a file to file comparison to the **cobracomb** set added back in March 2020
https://github.com/mamedev/mame/commit/d56a93abdb7617fe3358abeb092241aa088787b5

-----

c:\mamegit\mame>romcmp -d C:\Users\THENGAMES\Desktop\cobracomb\cobracomb.zip C:\
Users\THENGAMES\Desktop\Games\cobracomc.zip
15 and 15 files
el14.14j                                                 x11xxxxxxxxxxxx = 0xFF
                        el-14.14j                        x11xxxxxxxxxxxx = 0xFF
el00.2a                 el-00.2a                IDENTICAL
el01.3a                 el-01.3a                IDENTICAL
el02.5a                 el-02.5a                IDENTICAL
el03.6a                 el-03.6a                IDENTICAL
el10.1f                 el-10.1f                IDENTICAL
el11.5j                 el-11.5j                IDENTICAL
el12.7j                 el-12.7j                IDENTICAL
el13.9j                 el-13.9j                IDENTICAL
el14.14j                el-14.14j               IDENTICAL
el05.15a     [1/2]      el-05.15a    [1/2]      IDENTICAL
el09.9d      [2/2]      el-09.9d     [2/2]      IDENTICAL
el04.13a     [3/4]      el-04.13a    [3/4]      IDENTICAL
el06.16a     [3/4]      el-06.16a    [3/4]      IDENTICAL
el07.18a     [3/4]      el-07.18a    [3/4]      IDENTICAL
el08.7d      [4/4]      el-08.7d     [4/4]      IDENTICAL
el09.9d      [1/2]      el-09.9d     [1/2]      99.996948%
el05.15a     [2/2]      el-05.15a    [2/2]      99.996948%
el06.16a     [1/4]      el-06.16a    [1/4]      99.993896%
el08.7d      [1/4]      el-08.7d     [1/4]      99.993896%
el06.16a     [2/4]      el-06.16a    [2/4]      99.993896%
el07.18a     [2/4]      el-07.18a    [2/4]      99.993896%
el08.7d      [2/4]      el-08.7d     [2/4]      99.993896%
el08.7d      [3/4]      el-08.7d     [3/4]      99.993896%
el06.16a     [4/4]      el-06.16a    [4/4]      99.993896%
el04.13a     [1/4]      el-04.13a    [1/4]      99.987793%
el07.18a     [1/4]      el-07.18a    [1/4]      99.987793%
el07.18a     [4/4]      el-07.18a    [4/4]      99.987793%
el04.13a     [2/4]      el-04.13a    [2/4]      99.981689%
el04.13a     [4/4]      el-04.13a    [4/4]      99.981689%

-----

FC (File Compare) output below:

Comparing files COBRACOMB\el00.2a and COBRACOMC\EL-00.2A
FC: no differences encountered

Comparing files COBRACOMB\el01.3a and COBRACOMC\EL-01.3A
FC: no differences encountered

Comparing files COBRACOMB\el02.5a and COBRACOMC\EL-02.5A
FC: no differences encountered

Comparing files COBRACOMB\el03.6a and COBRACOMC\EL-03.6A
FC: no differences encountered

Comparing files COBRACOMB\el04.13a and COBRACOMC\EL-04.13A
00001700: 00 FF
00002500: 00 FF
00004300: 00 04
00004F00: 00 FF
00007600: 00 02
0000D900: 00 07
0000F300: 00 FF
0000FD00: 00 06
Comparing files COBRACOMB\el05.15a and COBRACOMC\EL-05.15A
0000D900: 08 0C
Comparing files COBRACOMB\el06.16a and COBRACOMC\EL-06.16A
00001700: 00 04
00006700: 00 0C
0000D900: 00 04
Comparing files COBRACOMB\el07.18a and COBRACOMC\EL-07.18A
00001700: 00 EC
00002D00: 00 3F
00006500: 00 ED
0000DB00: 00 40
0000FB00: 00 02
Comparing files COBRACOMB\el08.7d and COBRACOMC\EL-08.7D
00002500: 00 B7
00007300: 00 CD
0000B700: 00 32
Comparing files COBRACOMB\el09.9d and COBRACOMC\EL-09.9D
00005B00: 00 04
Comparing files COBRACOMB\el10.1f and COBRACOMC\EL-10.1F
FC: no differences encountered

Comparing files COBRACOMB\el11.5j and COBRACOMC\EL-11.5J
FC: no differences encountered

Comparing files COBRACOMB\el12.7j and COBRACOMC\EL-12.7J
FC: no differences encountered

Comparing files COBRACOMB\el13.9j and COBRACOMC\EL-13.9J
FC: no differences encountered

Comparing files COBRACOMB\el14.14j and COBRACOMC\EL-14.14J
FC: no differences encountered

-----

Observations:
Almost all changes are 00 to another value.  The one that isn't from 00 is a single bit change.  (08 -> 0C)
All changes involve a very similar address:  xx00
All changes are in GFX3 and GFX4 rom areas.

Big question, which one is correct **cobracomb** or **cobracomc**?
Was **cobracomb** zeroed out in places on purpose?
Hopefully someone who can dig into things deeper can determine.

**Comment by Gurudumps** [comment]
This looks interesting since the changes are not just at random locations and several ROMs match, which means the dumping equipment is working correctly. Do the new (changed) ROMs have any visual differences when compared to the original dump? The visual png screenshot compare thing that Tafoid does on new releases would be interesting to see for this new set.

**Comment by Tafoid** [comment]
All I run are snapshots of the screen at the end of the timed run -STR or -BENCH.  If the image changes in any way from what shows at that time, I can detect the change.  There is no method of dumping anything from the F4 menu output (gfxdecode/tilemaps/etc) and would require some manual observation.  Perhaps some Devs have more direct methods.

**Comment by Gurudumps** [comment]
The changed ROMs are the tile ROMs so there should be visual changes as long as the tile gfx are on screen when the snap/compare is done. You could do several compares at different times and see if any changes show up in the pngs.

**Comment by Tafoid** [comment]
I did a test .. benches from 10 to 100 seconds (every 5 seconds) and saved/compared the snaps between **cobracomb** (on left) and **cobracomc** (middle) and the difference (on right) and was able to detect only one bit of graphics change between the two.

-bench 75
b_to_c_75secondsdiff

-bench 80
b_to_c_80secondsdiff

I was able to find the graphics in the F4 menu.
gfxdecode #2 of 3 - 2D8 13,0.  Part of a pillar which has an extra dot near the top.
My knowledge can't equate the data to a particular rom, but it should give a good hint to a Dev.

**Comment by Gurudumps** [comment]
Ok thanks. I doubt any arcade company would be that pedantic about a few dots on screen and issue a fix. Personally I would update the existing set cobracomb and add the changed ROM first then load over it with the original ROM, with a note next to it explaining why the ROM is loaded over. That way both ROMs are preserved and maybe later someone can figure out which one is correct, or if both are correct the the c set changed ROMs are maybe newer.  It doesn't make sense to make a whole new set cobracomc just for this very minor gfx ROM change, just add it to the existing set and load over it so both are kept. This also ensures that the crc32 is known for the changed ROMs in case this same set is found on a different PCB sometime in the future.

**Comment by happppp** [comment]
All different bytes are at $xx00 which is very suspicious.
When looking at them through a hex editor, the values in cobracomc don't fit the surrounding patterns. I say cobracomc is a bad dump.

**Comment by Gurudumps** [comment]
Yes I agree it's suspicious. The easiest solution is to ask the guy to redump those ROMs.

**Comment by clawgrip** [comment]
I've asked for a redump of ROMs 04, 05, 06, 07, 08 and 09

**Comment by Gurudumps** [comment]
Tell the guy to clean the legs on the ROMs with some fine sandpaper before reading. If the legs are bent straighten them with pliers. Then read the ROM 3 times, each time removing and replacing the ROM so the reads are totally separate. It's a common noob error to pull a 30 year old ROM and read it once then move to the next ROM. I've even seen people desolder ROMs and read them with all the old dirty solder and flux still on the legs and with the legs bent and beat up. That's obviously the kind of thing that will create bad reads. Clean, straighten and read 3X separately then compare the CRC given by the EPROM programmer is the correct way to read ROMs.

**Comment by cuavas** [comment]
We seem to get a lot of bad dumps from Victor Fernandez.  It’s often obvious when they’re close to an existing set and someone actually checks, but how many bad dumps are sneaking past?  Should we automatically consider anything he dumps suspect?

**Comment by Gurudumps** [comment]
Never say never. IMO new dumps should always be considered. But dumps where the program ROMs are identical and the gfx ROMs are 99.9% the same are clearly suspect and easy to spot.

**Comment by clawgrip** [comment]
Yes, it's a bad dump. Sorry.

I asked Victor to dump them several times and with different equipment, and he's now getting variable checksums.

Thanks a lot for checking this out.

**Pull request closed without merging**
