### PR TITLE
psx.xml: correct [lostvik2] set description

### PR DESCRIPTION
**Pull request by ArcadeShadow**
corrected [lostvik2] set description
_source: https://www.mobygames.com/game/playstation/norse-by-norse-west-the-return-of-the-lost-vikings__

### CODE REVIEW

**Comment by cuavas** [comment]
I’m not sure the cover art actually supports this change.  There’s a pronounced space between “Norse” and “by” but no space in “Norsewest”, and given the uneven letter height in the words (e.g. R and S are always substantially taller than O), I don’t think it even supports changing it to “NorseWest”.

On second thought, the title screen *does* appear to say “Norse West” (two words): https://www.mobygames.com/game/playstation/norse-by-norse-west-the-return-of-the-lost-vikings/screenshots/gameShotId,244148/

**Comment by ArcadeShadow** [comment]
I confess, I only saw the title screen... I didn't compare with the box cover.
This ain't the first time that a game has a title screen different than the cover.
IMO, the game title should be the main factor... but if you maintain the title as it is, I'll will accept the decision too.

**Comment by cuavas** [comment]
The title is a reference to the Hitchcock film “North by Northwest” where “Northwest” is written as one word, which would lean towards the spelling on the cover art.  The USPTO trademark filed for the game uses the spelling “Norsewest” which further suggests that’s the canonical spelling: https://tmsearch.uspto.gov/bin/showfield?f=doc&state=4801:jju07h.2.1

It’s definitely not the first or only case where a title screen doesn’t match other media.  This has come up in other software lists, e.g. the French version of a Lion King game for Game Boy where the title screen has a spelling error not present on the box, and the RX-78 game with “Mobil Suit” on the title screen.

I’ll leave this open a bit longer, but unless someone can come up with convincing evidence otherwise, I think the canonical title is “Norse by Norsewest”.  A comment or `alt_title` can be used to note that the title screen spells it differently.

**Comment by cuavas** [comment]
The cover art and trademark registration disagree with this, as well as the source of the pun.  If you’d like to note that the title screen spaces it like this, add an `alt_title` with a comment.

**Pull request closed without merging**
