### PR TITLE
Hardware ScrollUP FIX

### PR DESCRIPTION
**Pull request by zx70**
Otrona Attachè now scrolls the screen !

### CODE REVIEW

**Comment by zx70** [comment]
I have this already in the "RM480Z" proposal, sorry for the temporary duplicate  :S

**Comment by galibert** [comment]
Some stylistic remarks I'd like you to fix if you don't mind:
- keep addresses in the memory map in order.  the sio access is now
out-of-order
- in C++ and modern C, it's considered in good taste to declare variables
as late as possible.  In particular loop indexes (x, y) should be declared
in the for(), and variables local to a loop (like vy) should be declared
when initialized, not before
- personal quirk:  I find "128*vy + x" more readable than "(128*vy)+x"
- also, some space after the ';' in for() would be nice

  OG.

**Comment by zx70** [comment]
Your comments are much appreciated

I must apologize, I'm a total newbie with c++ and mess!

Hope the contribution is valid enough to be reformed and add to the matter repo,  though ?

________________________________

**Comment by happppp** [comment]
No style changes are necessary, it was kept in par with surrounding
sourcecode.

**Pull request closed without merging**
