### PR TITLE
zn.cpp: change Tetris: The Grand Master to 6 button inputs

### PR DESCRIPTION
**Pull request by devinacker**
Tetris: The Grand Master normally only uses 3 buttons per player, but I recently uncovered some [hidden features](https://tcrf.net/Tetris:_The_Grand_Master#Debug_Mode) that seem to be designed around the same 6-button kick harness setup as most other Capcom ZN-1/ZN-2 games. This patch changes TGM's input definitions to be based on the Capcom 6-button setup, in order to better match the behavior of these features and also remove other unused inputs for players 3 and 4.

### CODE REVIEW

**Comment by happppp** [comment]
TGM official cabinet only has 3 buttons, right? But what you can do here is add a fake config port "Enable Debug Inputs" (default off), and then put the extra buttons behind a PORT_CONDITION.

**Comment by devinacker** [comment]
That makes sense. How does this look?

```c
	/* Tetris: The Grand Master uses 6-button kick harness for debug inputs */
	PORT_START("DEBUG")
	PORT_CONFNAME( 0x01, 0x00, "Enable Debug Inputs" )
	PORT_CONFSETTING(    0x00, DEF_STR( Off ) )
	PORT_CONFSETTING(    0x01, DEF_STR( On ) )

	PORT_MODIFY("P3")
	PORT_BIT( 0x70, IP_ACTIVE_LOW, IPT_UNUSED ) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x00)
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_BUTTON4 ) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x01)
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_BUTTON5 ) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x01)
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_BUTTON6 ) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x01)

	PORT_MODIFY("P4")
	PORT_BIT( 0x70, IP_ACTIVE_LOW, IPT_UNUSED ) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x00)
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_BUTTON4 ) PORT_PLAYER(2) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x01)
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_BUTTON5 ) PORT_PLAYER(2) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x01)
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_BUTTON6 ) PORT_PLAYER(2) PORT_CONDITION("DEBUG", 0x01, EQUALS, 0x01)
```

**Comment by happppp** [comment]
Yeah that looks good

**Comment by happppp** [comment]
Could you rename zn4w to tgm? Also AFAIK we have def_str for Yes/No.

**Comment by devinacker** [comment]
Sure, I've done that now.

**Comment by happppp** [comment]
Ok thanks!

**Pull request merged**
