### PR TITLE
Make third party BIOS ROM's optional in Sorcerer2

### PR DESCRIPTION
**Pull request by exidyboy**
Absence of these obscure third-party Monitor ROM's should not prevent machine from booting.
Note there is no historical connection between the official 1.1 bugfix revision of the Exidy Standard monitor firmware and the Mark II Sorcerer hardware.

### CODE REVIEW

**Comment by cuavas** [comment]
Optional ROMs are frowned upon.  They were originally intended to be used for optional hardware like disk controller cards that could be enabled/disabled via machine configuration switches before the slot system was added.  Ultimately, the "optional" ROM flag will be removed.  If you start a system from the command line, it will not refuse to run when ROMs for BIOS sets other than the selected one are not present.

**Comment by exidyboy** [comment]
Correct but currently you can't launch a "Sorcerer2" via the GUI without having *all* those ROM's.

**Comment by cuavas** [comment]
I realise that - it's an inherent limitation of the internal UI because the quick ROM check is performed before displaying the BIOS selection menu.  The space consumed by the additional BIOS ROMs is minimal.

**Comment by exidyboy** [comment]
It's great they are in MAME, in fact I dumped ADSMON and will be dumping more.
Just politely querying whether it is correct that not having them should now break the Sorcerer2 in the GUI when it has been working for perhaps a decade or more?

**Pull request closed without merging**
