### PR TITLE
new NOT WORKING machines

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING machines
-------
DT7 (prototype) [Graham Noble]

as per @galibert  "Let's close it for now, we can revisit afterwards when things are clearer. Let's say next summer for instance?"

It is now officially summer, so I'll leave this clean PR here as the old PR no longer compiled, and the branch had already been deleted.

I won't be doing any further work on this.  Credit goes to the person who owned the PCB.

### CODE REVIEW

**Comment by happppp** [comment]
This driver is not worth the drama it will cause.
Maybe he meant the summer of 2033 ;p

**Comment by rb6502** [comment]
Is this in FBN yet?  If not, yeah, we don't wanna be the ones sticking our heads up.

**Comment by DavidHaywood** [comment]
it's in HBMAME/Arcade

**Comment by Robbbert** [comment]
The code is in HBMAME, but the game is not enabled. It isn't in ARCADE64 (if that's what you meant) at all.

**Comment by DavidHaywood** [comment]
Ok, it's the code is being distributed in HBMAME then, excuse me for not knowing what series of illogical decisions led to a non-homebrew game being in HBMAME rather than Arcade.  I tend to group them together.

**Comment by arcadez2003** [comment]
> Is this in FBN yet? If not, yeah, we don't wanna be the ones sticking our heads up.



> Is this in FBN yet? If not, yeah, we don't wanna be the ones sticking our heads up.

Someone i know was working on it a while back maybe it'll turn up soon in FBN maybe it wont, but at the end of the day 
it's not one of Toaplan's best efforts their earlier Rally bike title was a far better game.

**Comment by arcadez2003** [comment]
> This driver is not worth the drama it will cause. Maybe he meant the summer of 2033 ;p

If our forefathers had thought like that eg skip everything considered to be problematic that would have put a serious 
dent on our advancement as a species.

Then again we seem to be going back the way so much so i pine for the Scotland i was born into everything was simpler 
and IMO much better back then but hey ho i digress :)

**Pull request closed without merging**
