### PR TITLE
nes.xml: Added a Mega Man 2 re-release.

### PR DESCRIPTION
**Pull request by 0kmg**
New NOT_WORKING software list additions
---------------------------------------
Mega Man 2 - 30th Anniversary Classic Cartridge [kdawg]

### CODE REVIEW

**Comment by 0kmg** [comment]
These were a limited 8500 run re-release. PCB shots are a bit fuzzy. Front: https://datomatic.no-intro.org/sources%20media/Nintendo%20-%20Nintendo%20Entertainment%20System/20210626_061346_3162_pcb_front.JPG. Back: https://datomatic.no-intro.org/sources%20media/Nintendo%20-%20Nintendo%20Entertainment%20System/20210626_061346_3162_pcb_back.JPG.

On the surface this looks like it works other than vertical screen transitions. However, this soft reset mid-game on me, so I marked it as not supported. It's a variant mapper 30 board (partial support added in #8225) that uses cartridge RAM in place of some NES on-board RAM in unusual ways. I'm guessing that's why it soft reset, but I haven't actually looked into it. ROM only differs by 139 bytes from the original US release, so there's not too much to dig through here.

**Comment by ajrhacker** [comment]
I've done some digging into the differences here. It appears to still have MMC1-style CHR banking with one serial-input shift register at $5FFF, but PRG banking and mirroring configuration is accomplished with simple writes to $FFxx. It seems possible that the data written to $FFxx is irrelevant and only the offset is used.

**Comment by 0kmg** [comment]
If you'll humor some conjecture without having researched this for more than a few minutes, I'm guessing the writes to $5FFF are just a way of effectively NOPing the old CHR banking. Among the earlier ROM edits is this section:

$ unidasm -arch m6502 -skip 229416 -count 50 mega man 2 (iam8bit 30th anniversary).prg
0000: a9 8e     lda #$8e
0002: 85 29     sta $29
0004: 85 69     sta $69
0006: 20 5d c0  jsr $c05d
0009: a9 01     lda #$01
000b: 8d ff 5f  sta $5fff
000e: 4a        lsr a
000f: 8d ff 5f  sta $5fff
0012: 4a        lsr a
0013: 8d ff 5f  sta $5fff
0016: 4a        lsr a
0017: 8d ff 5f  sta $5fff
001a: a9 1f     lda #$1f
001c: 8d ff 5f  sta $5fff
001f: 4a        lsr a
0020: 8d ff 5f  sta $5fff
0023: 4a        lsr a
0024: 8d ff 5f  sta $5fff
0027: 4a        lsr a
0028: 8d ff 5f  sta $5fff
002b: 4a        lsr a
002c: 8d ff 5f  sta $5fff
002f: a9 03     lda #$03
0031: 85 a8     sta $a8

In particular note that in order to make room for the extra STAs before jumping to $c05d we've lost a write to $5fff. There are 4 writes replacing the MMC1 $bfff CHR reg, but 5 writes replacing $dfff? (Note that MMC1 shift register is 5-bit so there are 5 writes in both cases in the original code.)

Maybe I'll dig into this more, but my initial impression was that merely implementing this variant [memory layout](https://wiki.nesdev.org/w/index.php?title=INES_Mapper_030#InfiniteNESLives_4-screen_board) would fix things.

**Comment by 0kmg** [comment]
Further evidence the $5fff is just a dirty ROM hack NOP. Here's the routine at $c05d. In the original it just serially writes register A to the MMC1 control register (in the code using address $9fff). Note they left the last write in and again switched the 9 to a 5:

3c05d: 85 29     sta $29
3c05f: 85 69     sta $69
3c061: 8a        txa
3c062: 48        pha
3c063: a5 29     lda $29
3c065: aa        tax
3c066: 9d 50 ff  sta $ff50, x
3c069: 68        pla
3c06a: aa        tax
3c06b: a9 00     lda #$00
3c06d: 8d ff 5f  sta $5fff
3c070: 60        rts

**Comment by 0kmg** [comment]
Separately, for the $FFxx writes, we see 32 bytes that were a fill value of 0xff in the original ROM have been replaced with a sequence 0x70...0x8f at address $3FFC0. The STA $FF50, X writes line up with this range and those values which makes it a standard idiom for bus conflict avoidance. In other words it all seems to jibe with the UNROM512 description.

**Pull request merged**
