### PR TITLE
sms.xml: added recently published carts

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions
-----------------------------------
Bara Buru [Kagesan]
Bruce Lee [Kagesan]
Flight of Pigarus (v1.11) [Kagesan]
Flight of Pigarus (v1.10) [Kagesan]
Flight of Pigarus (v1.00) [Kagesan]
Heroes Against Demons [Ichigo]
Voyage - A Sorceress' Vacation [Snags]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
could you add the older releases eg https://www.smspower.org/Homebrew/FlightOfPigarus-SMS has 1.10 and 1.00

(otherwise I think this is good, this stuff isn't paywalled, or even 'freewalled' so is eligible for MAME)

**Comment by cuavas** [comment]
Do the SMS and related systems have compatibility filters that can be used rather than usage notes when software only works on some variants?

**Comment by 0kmg** [comment]
> Do the SMS and related systems have compatibility filters that can be used rather than usage notes when software only works on some variants?

I try to adhere to the style of the existing SL (i.e. I'm an inveterate copy-paster). There doesn't seem to be a move in that direction yet. I certainly don't like the vague "only works in some systems, here's one" type messages, but those are what are in sms.xml presently.

Further, the cribbed "others show SOFTWARE ERROR" message is due to systems that enforce checksum/region checks. Well all the Japanese and Korean machines (and I guess smssdisp) are exactly the machines that DON'T check. All others should fail in some way.

**Comment by DavidHaywood** [comment]
yeah, this is consistent with the existing list, reworking it is a bit outside the scope of this PR

**Comment by 0kmg** [comment]
I could do a follow-up PR to address SMS filtering, though I'm not super familiar with the code base. Seems like it's just a couple set_filter lines in the driver + sharedfeat name="compatibility" in the softlist? Unless I'm missing something :)

**Comment by DavidHaywood** [comment]
there's the further issue that different BIOS revisions have different compatibility, and there's no way to mark that.

(I'm actually thinking that for computers / consoles the 'BIOS' concept isn't the best anyway, maybe they should just be clones, it wasn't really a normal thing to be changing the BIOS in a machine, they were usually separate models)

**Comment by 0kmg** [comment]
Maybe a better arrangement is needed in the long run, but for the SMS family though the BIOS revisions do seem to easily clump mostly into Asia vs Export for compatibility. https://www.smspower.org/Development/BIOSes has a nice overview of them all and even a summary chart at the bottom. Other than the region/checksum checks I don't think BIOS differences cause other issues for SMS titles—the BIOS is too simple, it just checks the various slots, clears ram, sets the VDP to something sane.

Of course, this is probably overkill. No one has bothered with compatibility filters for the SMS games because there are so few exceptions, hence the usage fields. Anyway, I digress, and as you said, beyond the scope of this PR.

**Comment by Tafoid** [comment]
This passes mame's -validate, xmllint check and all additions are accounted for.

**Pull request merged**
