### PR TITLE
more mpu4 sorting

### PR DESCRIPTION
**Pull request by mamehaze**

### CODE REVIEW

**Comment by james-wallace-ghub** [comment]
Are you planning on doing anything with the configurations themselves, or is this all sorting/labelling? I have access to some of John's work with MFME configuration files, and plan to install the various setups as fragments as and when you're 'done' with a subdriver. Alternatively, I can pass the relevant bits on if that makes things easier, but I don't want to tread on what you're doing while adding stuff to make the games a bit more playable.

**Comment by mamehaze** [comment]
I'm just improving the organization for now, trying to make sure things are in the right places, and that the ones that are clear hacks are marked as such (plus in cases where the sets requiring datapaks are parents, making a regular set the parent as they're more likely to work / boot)

some thought definitely needs to go into how to handle the various machine configurations with appropriate callbacks on the ports etc.  (and likely promoting MPU4 itself to a device so that you can have a driver with multiple units - I suspect at least some of the games are going to require top and bottom units emulated)

even labelling all these the versioning and shortcodes used are highly illogical, although I guess that could again be multi-unit setups etc.

but no, basically this is just the grunt work, that has needed doing for a while to tidy things up, actual improvements are not stepping on toes :-)

**Comment by mamehaze** [comment]
I still think that the fruit machines are one of the great areas of potential for MAME too, especially with Android ports, touchscreen support etc.  A lot of the existing emulators are Windows only.

Not sure anybody reads the comments here, but any help in getting the other hardware up and running, or adding missing devices, improving the CPU cores to support all the SoC peripherals etc.  The Epoch stuff is still a nice big challenging H8 reverse engineering and simulating of devices case, The Scorpion 4 stuff really needs proper hoppers (and CPU peripherals so that the later games can boot with less ugly hacks) and the Scorpion 5 stuff could potentially do a lot too, but gets stuck on a hardware test at the moment.  Even the smaller systems with less games could do with work.

It's definitely an area people could contribute in if they wanted to make a real difference

**Comment by rb6502** [comment]
I will be working on the 68k-based SoCs this fall; I have specific Ensoniq use cases for them, but helping fruit machines is a bonus too since they annoy all the right people :)

**Comment by james-wallace-ghub** [comment]
Well, what I have planned is to do this the simple way for now, and think
about whether this can be made modular at some stage.

I've been toying with using lots of DRIVER_INIT_MEMBERS for the main
features (hoppers, reel setups, etc) - with the protection data being added
to the ROMsets as fake ROMs (.CHR files, like MFME). Ever since the
discussions regarding other elements, I've had a bit of a problem with
adding protection related data to the main source, but this is something
that would definitely wait until a cleanup run, as I would be fooling
around with the same code as you are.

CHR data aside, I probably have enough data to take us from A to S from
MFME2MAME in terms of the games that people have published layout code for
from other emulators, aside from some potential use of special 7 segment
display controllers. I'm certain I'll expose weaknesses in my core
emulation in the process, so hopefully everything can coexist without too
much breakage, and by the end of it all will work a bit better for the
corner cases.

**Comment by johnparker007** [comment]
Hey guys - only just seen these comments, thought I should chime in too, I'm the MFME2MAME guy (as Haze/agemame know)...

So, the Converter is already in a pretty good state, I can make Internal and External (the DX) layouts for all the techs.  I have a few techs batched up - the Internal ones do take me longer (I have to manually transcribe the reels to a text format).  But I really don't mind - so far I have focused on MPU4/Scorpion 1+2+4 as that hardware works pretty well.

At some point I can *maybe* write the Scorpion 4 hoppers, though the ccTalk stuff is beyond my knowledge at the moment (a guy has had a check, and it looked like the comms may be unencrypted).

I do think for now, my time is best spent generating layouts, and I am happy to automate/provide anything I can help with, in terms of config data, CHR data, DIP switch data etc... Even default keys could be a thing, I did experiment with it, but it only worked well on a couple of the hardware platforms.

We probably have like 500+ internal MAME layouts for machines spread across all the "techs" that MFME supports.  And more when you then include the external DX ones.  Also, I was toying with a way to generate Internal layouts from MFME DX layouts (will just require a little more manual transcribing than I do already), so that would take the number even higher (some machines went 'straight to DX', bypassing the Classic stage).

Anyway - whatever I can do to help, please let me know, and I will try my best to get it done! :)

**Comment by johnparker007** [comment]
Also, just want to add - the layout authors can use MFME to make MAME fruit machine layouts for any Fruit hardware platform (I've provided an early Alpha to a guy re-emulated, he's currently making a Scorpion 4 "Deal Or No Deal - Break The Bank", which has never been emulated before with a layout).

So if say Scorpion 5 were gotten working, the layouts would start to trickle through, certainly for the more popular machines on that platform :)

**Comment by mamehaze** [comment]
The protection stuff, yeah, might as well handle it with the existing chr files, even if ultimately they're pals and somebody should send one or more to Charles MacDonald to see if we can get the proper dumps and equations out of them rather than the fake files.

That said, not sure it matters if they are in the source, it's stuff that has been reverse engineered in order to make things work, like a lot of MAME, nowhere near the size of the Data East or NeoGeo encryption tables ;-)

The SC4 stuff needs proper peripherals on the CPU, for the CCTalk stuff I believe that means a proper MBUS / I2C hookup etc. (68307 peripherals)  RB said he was going to do some peripheral work later.  MPU5 is 68340 peripherals (as is the Adder 4 addon for SC4).  Scorpion 5 is Coldfire peripherals (there are other things that would surely benefit from improved Coldfire too eg. the Gaminator touchscreen gamblers, although I'm not sure they're all the same variation)

The stuff in 'pluto5.cpp' and 'astrofr.cpp' (which IMHO is the same platform) doesn't actually look too complex either, again needs peripherals.

jpmsys7.cpp (made up name) seems to be pluto 6 or 7, it's definitely Coldfire but seems a different one to SC5

Global 'stealth' hardware (M37702S based) is also an interesting target, but I think most games are missing sound roms.

The castle.cpp platform(s) which could be related to spACE stuff is also a viable target for somebody who likes the 8-bits CPUs. (HD6303Y) in that case...

I'm really surprised nobody has put in a bit more effort with these, I imagine progress with some of them would be trivial.

**Comment by johnparker007** [comment]
> The protection stuff, yeah, might as well handle it with the existing chr files, even if ultimately they're pals and somebody should send one or more to Charles MacDonald to see if we can get the proper dumps and equations out of them rather than the fake files.

I will look at adding automated saving of the .CHR files per machine/layout this weekend when I should have some dev time  :)

> I'm really surprised nobody has put in a bit more effort with these, I imagine progress with some of them would be trivial even if some might use MCUs for reel control etc. it can be simulated.

I will get back on this a bit, starting next week, on the evenings - as I'm sure it's slightly more tempting to work on this with the layouts too, so you end up with fully playable machines!

**Comment by johnparker007** [comment]
> The Epoch stuff is still a nice big challenging H8 reverse engineering and simulating of devices case...

In terms of Epoch, there's another FME coder called Guitar who has very recently released his Amber2 emulator.  It's a beta, but it emulates the Maygay Epoch platform very well... Hopefully he'd be up for sharing some of his emulation core code for someone who wanted to implement that hardware in MAME... save reverse-engineering the same thing twice... ;)

**Comment by mamehaze** [comment]
Ah yeah, I believe Guitar has been helpful in the past, it will be interesting to find out what he has uncovered about Epoch as it should really be possible to get MAME in the state that the likes of SC4 are in at the very least.  Our H8 core should be solid enough.

**Comment by mamehaze** [comment]
I'm pretty sure you could create a layout with proper labels for "Sphinx" or "Pennies From Heaven" in the current state btw, the reels might not spin properly, but the layout we have light up properly, and the entire layout of the machine(s) is basically a very neat square, so it should be easy enough to deduce things.

**Comment by james-wallace-ghub** [comment]
The biggest problem with this is, aside from me, there doesn't seem to be much traction with this sort of thing, because it's such an onerous looking thing. If we went down the external CHR route, it would save a lot of source related headaches (because this data is going to be huge with per game CHR files otherwise).
My problem is that I have ridiculously little time to work with things like this, so I can never actually sit down and debug something this size anymore. With a combination of your relabelling and the MFME2MAME data from John, it should be possible to actually get testable games going (and since we have generated layouts too, anything that we can configure we can at least have a playable element for), and perhaps once it looks like something is actually happening, it might open things up a bit more., rather than seeming quite so abstract.

**Comment by mamehaze** [comment]
yeah it can seems a bit opaque right now, there's so little info on most of the machines, some of them there seems to be literally nothing out there for.  I think once people see more usable examples it might gain a bit more momentum, our presentation layer is still rather limited tho.

it many cases, especially for the unemulated techs, it's not clear if dumps are complete either, there are so many things with missing sound roms it isn't funny, and some could be part of bigger systems with video boards too.

I notice for the Scorpion 6 stuff (which is brand new, encrypted and not really interesting to us yet) the dumps of the video ones are all just the files, rather than an image of whatever media they're on too, which is going to be messy later I'm sure.

**Comment by james-wallace-ghub** [comment]
This is usually the point where I bring up the 3D artwork idea that's in the issues tracker, or the perhaps slightly more insane idea of Amber as a Visual Pinball-esque presentation layer allied to the MAME output system. Of course, it's nothing without a working system side, and without something a bit more hotpluggable in terms of the various expansion boards, it's down to DRIVER_INITs at the source level rather than a pure softlist.

**Comment by johnparker007** [comment]
I think that yes, while the presentation layer is a tad limited, the "DX" versions look good enough for the moment, just to be working with:

https://dl.dropboxusercontent.com/u/15679918/converter/screenshots/DOND_BTB/ReelsBehindGlass.png

https://dl.dropboxusercontent.com/u/15679918/converter/screenshots/NewMPU4/FlashCash.png

...obviously the internal MAME ones (like the sample Frankie Dettori one I put in) look very basic, but with no bitmaps to make textures, I guess they'll always look pretty much like that.

If the emulation were more sorted across techs, it'd be worthwhile for me to 'derive' a 3d model per layout from these, so you'd have cylinders for the reels, couple of quads for the top/bottom glass with the 3d reels visible through the reel windows (alpha texture), generic fruit cabinet model scaled/wrapped around the top/side/back/base... plus the lighting could be reverse-engineered so you just have the large dark 'off-image' for the glass, then use a shader to apply the lights (like how Amber2 does it) to allow for glow/flicker effects etc, and I'd provide the shader coordinates/parameters per lamp via the Converter.  So I could see a route to generating many hundreds of 3D model fruit machines, automatically from these original MFME layouts.  But I wouldn't wanna get involved with that crazy level of new work unless the MAME emulation side was pretty solid across the techs.

I do have MFME in a ~4gb Virtual Machine image (for VirtualBox), so you can fire that up, run MFME from source in the IDE (it works straight out of the box, fully configured environment), then add breakpoints, step through the emulation cores while machines are running etc.  It runs a wide variety of "techs" pretty well, I guess that could be useful to help with debugging...?  It may be the closest thing to documentation for those old techs there is.  Though I'll warn you, be prepared for the joys of using Borland C Builder on Windows XP again!  :)   But it works fine for stepping thru code, hovering, breakpoints etc.

**Comment by johnparker007** [comment]
Yeah it would be cool if we could keep this thread going - still working on the expanded config generator at this end currently.  MPU4 seems to have by far the most options, though I think some of this may be of use on some of the other platforms too (DIPs/Hoppers/Stake/Percent/Jackpot/Reels)...

**Comment by kspencer72** [comment]
Hi all, as John mentioned ealier, I've been having a look at the ccTalk hopper comms on sc4dnd and the following commands are sent unencrypted immediately prior to when it stops with 'pay unit - error 17'.
F4 - Request Product code is sent with four retries, followed by F6 - Request Manufacturer ID then F1 - Request SW revision (breaks with wpset 80b4ba, 80b4a6 & 80b4a0).

I have no prior MAME dev experience and my attempts at trying to create a ccHopper serial device have so far come to nought. I've tried using _m_duart->rx_b_w(hopper_response);_ followed by _m_duart->read(space, 0x0b);_ to try and force the 68681 to read the rx register but run into problems with the data not going into the fifo buffer due to the rx clock not enabling due to the data not being framed correctly with start/stop bits.

Anyway, having all but given up with serial comms I've attached the debug output below for the ROM ccTalk transmission in the hope that this info may be of use to someone with the necessary dev skills. (I had to enable loopback with _m_duart->write(space,0x08,0x0080);_ to get the complete messages, otherwise it just repeatedly Txs 03).

[cc_comms.txt](https://github.com/mamedev/mame/files/415292/cc_comms.txt)

**Comment by johnparker007** [comment]
*crosses fingers* ... as there's plenty of documentation out there on ccTalk, in terms of how to construct messages and what response formats are expected - so as Keith said before (over on dadsfme), if someone were to commit a working skeleton device were constructed with one or two working commands (so perhaps correctly responding to the initial Request Product Code commands on sc4dnd) - it would be easier for someone to then flesh it out with all the other commands/responses (provided it doesn't encrypt comms later on).

**Comment by rb6502** [comment]
Look at something like the esqpanel device for an example of a MAME device
with 2-way HLE serial.

**Comment by Keith-S72** [comment]
Thanks RB for the esqpanel suggestion, I now have a working serial hopper communicating with the sc4. Just need to sort the protocol responses out now.

That's the great thing about MAME. Who'd have thought that a synthesizer display interface could be re-purposed as a fm hopper.

**Comment by rb6502** [comment]
Great!  I'm glad you got it figured out with that tip :)

**Comment by mamehaze** [comment]
yeah, MAME is good like that, it's one of the reasons we're more open about things these days, there are so many reusable bits of code it's wasted potential otherwise.

glad to hear you're making progress anyway

**Pull request merged**
