### PR TITLE
dvk_ksm: unbreak host comms, add PORT_CHARs to its keyboard

### PR DESCRIPTION
**Pull request by shattered**

### CODE REVIEW

**Comment by Tafoid** [comment]
This adds KEYCODE_F keys which are above the F15 which input.h can deal with.  Therefore, it doesn't compile unless you forgot to merge core input changes as well to take in account your driver additions?

**Comment by shattered** [comment]
Those changes are in https://github.com/mamedev/mame/pull/1159

**Comment by cuavas** [comment]
Yeah interdependent pull requests should be noted explicitly. And I'm not quite sure whether we want #1159. There are lots of common keys that we don't have macros for, e.g. the IME control keys on Japanese keyboards. Is adding macros for keys that are specific to DEC terminals and clones really something we want to do?

**Comment by shattered** [comment]
Lua emu.keypost() cannot post a F20 without a macro -- if I map it, say, to F12, that only works in interactive mode, Lua will send an actual F12 key, not the F20.

Actual use case is regression testing with Lua; on the dvk_ksm, F20 toggles online/local modes and I'm testing local loopback mode this way.

**Comment by rb6502** [comment]
It's not just DEC, Mac desktop keyboards go up to F19.

**Comment by cuavas** [comment]
Well there are two issues here:
* What keys do we want to add?  If we're adding them we may as well do a lot at once.
* How can we expose keys to Lua when they don't have macros?  We're never going to have a macro for every key on every exotic input device.

**Comment by etabeta78** [comment]
Aren't inputs without macro already being accessible by LUA via port bits?
or am I misunderstanding the problem?

It's not an universal solution, but for exotic input keys I think a
per-driver solution is acceptable...

   f.

**Comment by shattered** [comment]
sure, why not, but keypost() is more user-friendly (not by much -- I may be missing something, but can it accept a key name, and not just its Unicode codepoint in 0x100000 region?)

**Pull request merged**
