### PR TITLE
Enable an optional region filter for Megadrive/Genesis ROMS for softwarelists

### PR DESCRIPTION
**Pull request by csvowles**
Some Mega Drive/Genesis ROMs are region protected, when the game starts they either display a message (explaining the Cartridge is designed for a different region), or they hang (which is the case for some Konami games, which hang showing the KONAMI(R) white splash screen).

This enhancement allows the softwarelist to have an optional "compatibility" value set to prevent invalid combinations of Console region and ROM region. It is based on how the 32x Mega Drive based Mame machines achieve this.

The valid options are: 
- `NTSC-U` for North America/Brazil - `<sharedfeat name="compatibility" value="NTSC-U"/>`
- `NTSC-J` for Japan/S Korea/Asia - `<sharedfeat name="compatibility" value="NTSC-J"/>`
- `PAL` for Europe (including France SECAM variant, and Australia) - `<sharedfeat name="compatibility" value="PAL"/>`

ROMs can be valid in multiple regions, for example:

`<sharedfeat name="compatibility" value="NTSC-U,NTSC-J"/>`

or

`<sharedfeat name="compatibility" value="PAL,NTSC-U"/>`

Many ROMs work in all three regions, and if there is no `sharedfeat name="compatibility"` value set for that ROM in the softwarelist then it appears in the ROM list for all versions of the Mega Drive / Genesis console just as it did before this enhancement.

The `megadriv.xml` software list has now been updated #9688 to document the region locking of the various ROMs, and the code change in this PR would prevent listing a ROM which doesn't work on the regional variant of the Mega Drive / Genesis machine chosen.

The code has been compiled locally on Windows, and confirmed to exclude ROMs from those available based on any `compatibility` meta data now it has been added to the megadriv software list.

### CODE REVIEW

**Comment by Dunard** [comment]
I hope this get passed. I can't stand of loading the wrong ones.

**Review by cuavas — CHANGES_REQUESTED** [review]
This has numerous XML DTD validity errors.  Please check changes to software lists with `xmllint` or another DTD-aware XML validator.

**Comment by csvowles** [comment]
Thanks for the help, I have corrected the formatting of `megadriv.xml`, so `xmllint` reports no errors.  Also `mame -validate megadriv` reports no errors with the xml either. Compiled and tested that megadriv.xml works as expected, excluding roms from the list that are not valid for that region.

**Comment by cuavas** [comment]
You’re going to need to say when you’re actually done with this so someone can review the accuracy of the compatibility flags you’ve set.  You’re latest change doesn’t just add compatibility flags, it changes one.  You should really get to the point where the change is done and check your work yourself *before* opening the PR.

**Comment by csvowles** [comment]
I would say that 186 is more than enough ROMs to check for one PR.

There are around 2000 ROMs for the Mega Drive/Genesis; I am willing to assist in future PRs to update the software list further by adding additional region protection information, but this is a significant start to improving the software list meta data.

**Comment by csvowles** [comment]
I suspect that regarding the software list `megadriv.xml` the 241 additional entries are more than enough ROMs to review for one PR.
This would be a significant step to improving the software list meta data for Mega Drive concerning those region locked ROMs, and I estimate it covers approximately half of those which are region locked.
I am willing to assist in future PRs to update the software list again, adding further region protection information.

**Comment by csvowles** [comment]
> You’re going to need to say when you’re actually done with this so someone can review the accuracy of the compatibility flags you’ve set. You’re latest change doesn’t just add compatibility flags, it changes one. You should really get to the point where the change is done and check your work yourself _before_ opening the PR.

The `megadriv.xml` change, and the `.cpp/.h` code change are not dependent on each other; if only the code change were merged there would be no change in behaviour to Mame, and similarly if only the xml change were merged there would currently be no change in Mame behaviour (all ROMs would continue to appear in the list for all three variations of Genesis (NTSC-U), Mega Drive (PAL) and Mega Drive (NTSC-J)).

Given above, what can I do to assist further on this PR, I see the options as:

1) Call this done for now, and I will work on updating the region locked information for more ROMs in the XML for a future PR

2) Remove the xml changes completely from this PR leaving only the code changes, and raise a new PR with only the xml changes with no code changes

3) Modify the xml file to have fewer changes in, perhaps just have one example each of a Genesis (NTSC-U), Mega Drive (PAL) and Mega Drive (NTSC-J) ROM with region locked ROMs, and maybe one example of a ROM which works in only 2 of the 3 regions.

4) Any other suggestion?

**Comment by cuavas** [comment]
It needs to wait for someone with a decent knowledge of the system and its software library, and adequate time available, to check the changes to the software list for accuracy.  I’m not that person.

**Comment by ICEknigh7** [comment]
Would these changes take into account that you can use a region converter cartridge, Game Genie, etc, to successfully load region-locked games from other markets?

**Comment by csvowles** [comment]
> It needs to wait for someone with a decent knowledge of the system and its software library, and adequate time available, to check the changes to the software list for accuracy. I’m not that person.

Sounds like option 2 - just consider the code change for now, would be the best course for this PR then.

**Comment by csvowles** [comment]
> Would these changes take into account that you can use a region converter cartridge, Game Genie, etc, to successfully load region-locked games from other markets?

No, this change does not attempt to replicate any software region converter.

**Comment by csvowles** [comment]
> It needs to wait for someone with a decent knowledge of the system and its software library, and adequate time available, to check the changes to the software list for accuracy. I’m not that person.

If you would be kind enough to initiate the checks to run (code hasn't changed since it already passed the checks).

Software list removed, to be added to another PR.

**Comment by cuavas** [comment]
Do you have no patience at all?

**Comment by csvowles** [comment]
There is a suitably updated Megadriv software list to document the Roms with region lock issues in PR https://github.com/mamedev/mame/pull/9688

**Comment by angelosa** [comment]
At this point I believe this is fair to be merged.

**Comment by csvowles** [comment]
Failed to rebase this given the multiple directory renames and code moves since the PR was first raised, created new PR https://github.com/mamedev/mame/pull/10012

**Comment by angelosa** [comment]
Superseded by #10012 , guess it's fair to close this off.

**Pull request closed without merging**
