### PR TITLE
x1_012.cpp: restrict partial updates in the seta tilemap chip to caliber 50, it breaks too many other places due to unmasking some bad timing problems in the drivers.

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
@happppp even just limiting the scope to scrollx doesn't help, as Zombie Raid writes that in the middle of the screen too, so clearly some other timings are significantly wrong.

**Comment by DavidHaywood** [comment]
yes, it will still work that way.

this way however you at least get a log of when such things are happening, so get an indication of when the timings are wrong, even in drivers / games where updates aren't being allowed.

personally I think MAME should default to scanline update, but it would break so many cases / cause so many performance issues in drivers that aren't properly optimized it's probably not possible at this point.

**Comment by DavidHaywood** [comment]
forcing VIDEO_UPDATE_SCANLINE also causes a significant performance drop, at all times, as the sprite code is not well optimized for scanline drawing - it has no 'early get out' so calls the drawgfx function for every sprite, even fully clipped ones, on every scanline.

for now, I prefer this solution.

**Comment by happppp** [comment]
What about a trampoline in calibr50_map?
Maybe it's just me, I prefer workarounds like these at driver-side instead of the device.

**Comment by happppp** [comment]
The logmacro is obsolete now?
And the commented-out video attributes. Is that comment better placed at where the trampoline is? So just remove that line completely and explain the use for the trampoline inside vram_layer0_vctrl_raster_trampoline_w.

**Pull request merged**
