### PR TITLE
imagedev/floppy.cpp: Add hard-sector floppy support

### PR DESCRIPTION
**Pull request by ejona86**
* bus/s100/vectordualmode.cpp: Use IDX timings for hard-sector FDD
* formats/vgi_dsk.cpp: Load image with hard-sector index holes

@galibert

### CODE REVIEW

**Comment by galibert** [comment]
Something I don't manage to make my mind about: should the index hole list be a property of the image or of the drive?  I know that hard sectors were holes in the floppy, there's no doubt about that.  But having the information in the drive could make the image code simpler, and, more importantly, would give support for unformatted floppies.  Right now the "create" method is unreachable, it would have to go through fs_unformatted somehow.

Do we know of systems where the same drive supported hard-sectored floppies with different numbers of sectors?

**Comment by ejona86** [comment]
> Right now the "create" method is unreachable, it would have to go through fs_unformatted somehow.

It seems to work for me via the configuration menu. I go File Manager, create a new image, choose vgi as image format, and then I am able to format it using the Vector 4.

> Do we know of systems where the same drive supported hard-sectored floppies with different numbers of sectors?

The drive is a normal drive. There's nothing special about it for hard sectors. There are only two hard-sector index hole configurations: 10 sector and 16 sector. I've dug pretty deep and have been unable to find any other variations. I'm confident no _controller_ supported 10 _and_ 16 hard-sectors. I'm not aware of a controller that supported hard-sector and soft-sector, although I've not looked as deeply into it.

The other option I considered was to make it a flopimg variant, where we'd then probably make it a property of the drive to filter out incompatible image formats. I think on principal that feels like a fine idea, but I didn't want to make the enum cluttered and it was more invasive.

It would be very easy to have a "set the number of hard sectors" method on floppy_image_format_t, even just as a convenience. I didn't to reduce the image-specific knowledge in flopimg. It also side-stepped the discussion of where the "start" of the track was. But it would be easy and would simplify the image code for IMG-like formats like VGI.

Generic lower-level MFM and flux formats that can work with hard sectors encode the index explicitly in the format, and the index holes aren't guaranteed to be perfectly distributed. I don't know how much we might care about them.

The code changes here were pretty easy. I don't mind in the least swapping things to another approach. I expected debate when I started, although once I had these changes I felt it was a pretty natural approach.

**Comment by galibert** [comment]
My #1 problem is that if the user chooses mfi as the format, which is supposed to work with everything, the image will not be formattable.  That's why I'm saying it should come though fs_unformatted, it should be transverse.  And mfi should be extended for hard sectors, but that's an easy one.

**Comment by mgarlanger** [comment]
Any progress on supporting hard-sectored disks? I would like to add hard-sectored support for Heath H89/H8 and want to be consistent with what others are doing. Since the same drives can be used with either a hard-sectored or a soft-sectored controller, it doesn't seem like the drive should have any info about the type of sectoring, it should be in the disk image.

**Comment by galibert** [comment]
Ah sorry, too many things at the same time.  I thought about it, and I think, but I'd like your POV on that, that it should be part of variant.  We can have the floppy image device check it and act on it, we can declare drives compatible, and formats won't need to care as much (especially the generic mfi format).

**Comment by ejona86** [comment]
I think I do see now how fs_unformatted plays into things and agree it is probably more appropriate than a create() on the format. The issue is mostly plumbing to tell it what to do.

When opening an image, the format needs to be in charge of setting the index locations. So if these new variants are really only consequential when creating new images, that seems fine. But if the variant dictates the index positions even when opening a disk, then that seems strangely poor fidelity.

How should we assign IDs to the new variants, given the existing ones are four-letter ASCII? `SD16` for SSDD 16 hard sector?

I'll note that every image format I'm aware of that explicitly saves index information does not encode hard sectors per disk, and instead has index information per-track. I think that is because 1) it is generally easier to hack that way, since few care about hard sectors and it can be encoded as multiple rotations, and 2) it is more accurate, since the index is properly positioned with the data, dealing with variation in rotation speed. So if we were serious about fidelity we'd actually go a step further and store the information adjacent to the track splice or in the track data (similar to damaged).

**Comment by AlKossow** [comment]
you are going to quickly run out of mnemonic descriptions for hard-sectored formats in 4 characters
HS16 is meaningless if you don't know how the sectors are actually encoded

**Comment by ejona86** [comment]
@AlKossow, there's few organizations of hard sector index pulses. You have one index hole at the beginning of each sector (evenly spaced through track), with the last sector having an additional index in its middle. 5.25" floppies had 10 or 16 sectors, and 8" had 32. There may be some rare alternatives, but even if you found two exceptions the scale is low.

**Comment by galibert** [comment]
The format is the one setting the variant, so it is in control.  Going through the variant would allow to have a small, finite list of index positions in constant arrays which would be picked up automatically by the floppy_image_device (including a list with only one index pulse at position 0).

Something I wonder, I know the track index hole is sometimes slightly offset compared to the sector ones.  Do they end up as two separate signals in some drives?

**Comment by mgarlanger** [comment]
> 
> Something I wonder, I know the track index hole is sometimes slightly offset compared to the sector ones. Do they end up as two separate signals in some drives?

On 5.25" disks there is no offset, it will be the same signal. I'm not 100% sure on 8", but I believe they is no offset either. The offset that you may be thinking of is on 8" drives and where the hole in the housing is. There is a difference between DS and SS disks. This allows DS drives (with 2 sensors) to determine if a DS or SS disk is installed.   Here is a photo of an 8" hard-sectored disk, showing no offset - https://retrocmp.de/fdd/8inch/ss-ds-flippy.htm

**Comment by ejona86** [comment]
>> the format needs to be in charge of setting the index locations
>
> The format is the one setting the variant, so it is in control.

I was saying the precise locations, not a fixed menu of locations. Since the index locations are essential for timing, I'm wary of using only pre-defined positions. It would seem that'd be unable to use real recordings of media if the disk's holes weren't close enough to the assumed values. Although after investigation, I think custom index positions wouldn't even be enough. We'd have to have per-track index positions. So how badly do we want to support real disk images?

The Vector's sector preamble is 320 bitcells, with the first 256 bitcells warming a PLL. That means there's 64 bitcells of permitted tolerance, or 256 µs.

The tolerances don't work in our favor. Looking at 5 tracks on a recording of a single disk of mine, I see sector sizes over 100 µs away from ideal. (I poked at some other disks as well, but only their first tracks, and briefly. I don't expect the disk is a huge outlier.) That's partly due to rotational variance. Averaging over many rotations that comes down to 60 µs. But that error can accumulate across sectors, so the worst index location is 143 µs away from ideal. But depending on which hole I align the disk on, some index holes are 207 µs away from ideal. That means the disks themselves are probably not within tolerance for pre-defined index positions.

But even using average index positions, one track has a sector 376 µs away from ideal, but that sector is still 309 µs away from the average. That means the rotational variance on my floppy drive is too high for per-image index positions.

> I know the track index hole is sometimes slightly offset compared to the sector ones. Do they end up as two separate signals in some drives?

I'm not aware of any. The Helios II drive separated INDEX/SECTOR (and also CLOCK/DATA). But that was as convenience for the disk controller; all index/sector holes were at the same offset from the center.

> The offset that you may be thinking of is on 8" drives and where the hole in the housing is.

It was also used in the IBM Displaywriter on 5¼" disk for similar purpose. Electrically, it presented both holes together as a single index line, and only used the separate hole for a "diskette sense" line to tell the host the disk type.

**Comment by mgarlanger** [comment]
> The Vector's sector preamble is 320 bitcells, with the first 256 bitcells warming a PLL. That means there's 64 bitcells of permitted tolerance, or 256 µs.

Are you sure a real system is that time sensitive? On a real system there are going to a lot of variations, having such tight tolerances would seem to make the system unreliable. 
For the Heathkit hard-sector disks, timing is not critical. The format is FM encoding. After detecting the hole, the computer will but the USRT into syncing mode, and it just needs to find the Sync byte within a certain amount of time.

**Comment by ejona86** [comment]
>> The Vector's sector preamble is 320 bitcells, with the first 256 bitcells warming a PLL. That means there's 64 bitcells of permitted tolerance, or 256 µs.
>
> Are you sure a real system is that time sensitive?

Those were details from the hardware schematic. It uses MFM. After that period of 256 bitcells, it looks for the very first 1 data bit which becomes the start of the first byte. It uses data `00` in the preamble and `FF` for the sync, so the first 1 data bit is (hopefully) the sync. Those initial 256 bitcells _decrease_ time sensitivity in the real hardware, as it prevents detecting a write splice or unsynced clock as the (very weak) sync pattern in the first 1 ms of preamble.

The emulated sector timings here can cause the write splice to move _before_ the sector pulse. And that's where there is low tolerance, because real hardware only had to deal with the write splice moving _after_ the sector pulse due to software delays in the writer. There's essentially no delays by the reader, as the sector read is automatic reading to on-controller RAM. But other hardware used the same format and was more software-driven.

> For the Heathkit hard-sector disks, timing is not critical. The format is FM encoding.

Heathkit has 12 bytes of preamble so 768 µs of tolerance. Even losing 376 µs to bad sector alignment, the remaining 392 µs seems plenty to handle differences in software delays between the reader and writer.

**Comment by ejona86** [comment]
> That means the rotational variance on my floppy drive is too high for per-image index positions.

Hmm... That was assuming the index pulses in the image were discarded in favor of the idealized timings. But the flux timings are normally scaled to fit exactly 200 ms. Instead of scaling the track as a whole, we could scale _each sector_ separately. Then the index pulses would be perfectly aligned. Even if the disk had imprecise index holes, diffusing 300 µs of error through the sector is only 2.4% error which would be hardly noticed in the flux timings. The flux timings would change abruptly at each sector boundary, but nothing would care.

I'll change the code and create variants for the hard sectors.

**Comment by galibert** [comment]
200000000 is not a time, it's an angular position.  It matches time at 300rpm with an ideal perfectly stable drive because why not, but it's an angle.  And the index holes do not change angle from one rotation to the next.

**Comment by ejona86** [comment]
> 200000000 is not a time, it's an angular position. It matches time at 300rpm with an ideal perfectly stable drive because why not, but it's an angle. And the index holes do not change angle from one rotation to the next.

It sounds like you are arguing with me, but you only argued semantics and I see no impact to what I stated. I agree index holes don't change position between rotations, and I don't know why you've brought it up.

**Comment by ejona86** [comment]
@galibert, I just pushed an approach using the variant to include hard sector details. Pay special attention to the integer value I used to represent the variants.

**Comment by simzy39** [comment]
Is this ready to merge?

**Comment by galibert** [comment]
I'm ok with the values for variants.  I like the setup of the index positions on set_variant too.

I see two issues still.  First, the "main" index hole is supposed to be at position 0.  IOW the first element of index_array should be 0, and the others should follow, probably at (n+0.5)*sector angle positions I guess?  I suspect some of the floppy code to be a little fragile on the rotation transitions if there isn't a timer triggering at 0 in fact (a timer trigger having the nice side effect of synchronizing a lot of stuff).

The second is that fs_unformatted should be updated to behave correctly on those variants.

**Comment by ejona86** [comment]
I've updated fs_unformatted and tested that I can use mfi files. I created a bootable disk and was able to boot from it.

I've added back some documentation that describes `index_array`. I agree that index at 0 is really important, which is why it is implicit. The current hard sectoring has the sector 0 pulse as the start of the track, which is much easier to manage than considering the index hole in the last sector as the start of the track. The difference between the options is not observable to the floppy controller and it is easier this way for image formats.

**Comment by cuavas** [comment]
This has been reverted with 4d56a317550c0fd2771976fb58385e294aa22c79.  It caused regressions with numerous floppy formats, some of which were worked around with cf510adc9d34b4ad9a065f3d5bfbcf17115ea06f.  However, it seems to be fundamentally flawed.

**Comment by ejona86** [comment]
@cuavas, oh no. I'm sorry about that. Are any of the reports visible to me for me to investigate?

**Comment by cuavas** [comment]
If you check out the tagged mame0259 (before cf510adc9d34b4ad9a065f3d5bfbcf17115ea06f was committed), Apple II and Macintosh floppy formats don’t work at all.

If you check out tagged mame0260 (before 4d56a317550c0fd2771976fb58385e294aa22c79 was committed), attempting to load a .d64 disk image on an emulated Commodore 64 will cause the emulator to hang.

Those are pretty easy to reproduce.

**Comment by balr0g** [comment]
Also see:
https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=122852#Post122852

https://github.com/mamedev/mame/issues/11585

**Comment by ejona86** [comment]
cf510adc looks to workaround a difference-of-precision or rounding issue. `next_index/angular_speed` is a few (16 or 32) attoseconds different than rev_time for some rpms. Larger turns out fine, but when smaller it breaks. Replacing `next_index/angular_speed` with `next_index/2e8*60.0/rpm` produces the same result as rev_time and fixes the problem. That difference of precision was pre-existing, but only for the `new_idx == true` case.

The Commodore problem is similar. It is triggered simply by `60/rpm` becoming `60.0/rpm`, which changed from float to double precision. I haven't found a fix yet.

**Pull request merged**
