### PR TITLE
input_sdl.cpp: Fix compile with SDL < 2.0.6

### PR DESCRIPTION
**Pull request by couriersud**
sdl_input references functions which were added in SDL 2.0.6.

### CODE REVIEW

**Comment by cuavas** [comment]
SDL 2.0.6 is sufficiently old and widespread to require as a minimum version.  The documentation has been updated to reflect this.

**Comment by couriersud** [comment]
SDL in 3rdparty is 2.0.5. USE_BUNDLED_LIB_SDL2 will not compile as well.

**Comment by cuavas** [comment]
It needs to be updated to work on macOS anyway – 2.0.5 has been too old to work properly for a while now.  Someone needs to update it and test it.

**Comment by couriersud** [comment]
I can offer to do this. Can't do the macOS part, though. Is this a requirement for the update?

**Comment by cuavas** [comment]
If you update the included SDL to 2.0.14 and check that it works on at least some platforms, it should work on macOS as well (2.0.6 is minimum that works for macOS on x86-64, 2.0.14 is minimum that works on macOS for AArch64, so 2.0.5 is too old to work at all now).  If you don’t want to do it, I’m sure someone else will sort it out at some point.

**Comment by couriersud** [comment]
I can check on windows and linux. I might on macos - if the virtual machine still works.

**Pull request closed without merging**
