### PR TITLE
i8271: unload head after programmed revolutions

### PR DESCRIPTION
**Pull request by Pernod70**

### CODE REVIEW

**Comment by Tafoid** [comment]
I suspect a regression happened here causing exception/crash with the following sets:
torchh10, torchh21 - bbc.cpp
Exception at EIP=024D7934 (device_slot_interface::get_card_device()+0x0014): ACCESS VIOLATION

Please see what you can do.

**Comment by Pernod70** [comment]
Those two machines only have a single floppy drive but motor_w and side_w wrongly assume two drives are connected. I'll try to get a fix in later today. Thanks.

**Comment by Pernod70** [comment]
Looking at other drivers all similar head load callbacks always act on all possible drives, regardless of which the fdc currently has selected. In this case I can add a check to see if the drive is actually connected before changing its state in the callback, this fixes the issue. But wouldn't it make more sense to expose the SELECT0, SELECT1 lines of the 8271 so that the callback only takes action on the currently selected drive?

**Comment by Lord-Nightmare** [comment]
I think MAYBE (this is worth further research on bitsavers in the shugart/qume documentation) that at least 8" drives can be jumpered to use common head load (though the solenoid isn't supposed to fire unless a disk is inserted) or only load the drive which is currently selected. So whatever solution we come up with should be able to handle all of the different 'drive jumpering' cases.

**Pull request merged**
