### PR TITLE
bus/nes_ctrl: Added support for Doremikko piano keyboard.

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by 0kmg** [comment]
For reference [this](https://nintendosegajapan.com/2015/07/31/doremikko-famicom-disk-system/) has a picture of the unit and its box. The back side of the box (not shown) notes that the keyboard/FDS combination supports 4-voice polyphonic sound. With this implementation it is possible to get four voices but it is not easy or consistent. There may be other bugs as well, it's hard to tell. Unfortunately, I don't have much information on how this keyboard is supposed to work. In fact, though Nestopia's implementation might have some improvements (I haven't looked) I was mostly working from this 15 year old request ticket, errors and all: https://sourceforge.net/p/nestopia/feature-requests/51/

Oh, and I couldn't really figure out a great default button layout. In particular this overlaps with the default controller 2 buttons which have a few useful functions (octave select, sustain, vibrato, etc. For now, lacking any better ideas, I matched the keyboard layout in: https://github.com/mamedev/mame/blob/master/src/mame/drivers/spg2xx_ican.cpp.

**Comment by cuavas** [comment]
Would it be better to do this using `IPT_KEYPAD` and avoid the P key, so it doesn’t cause UI control to be disabled when it’s plugged in?

**Comment by 0kmg** [comment]
Yeah, I'll change it if you insist. I did try gapping over the P key (i.e highest pitch keys went: O, 0, [, =, ]) before settling back on this layout from the "I Can..." driver. However, in noodling around with it I found it pretty annoying with the gap. I also obviously found the overall experience pretty annoying without locking the UI then, due to P. That being said, I also find it annoying disabling the UI on a system like NES/Famicom when there's no actual computer keyboard, but ultimately went with this as it felt slightly better.

Anyway, this thing will really need an external piano keyboard input to be any fun. I'm not wed to the layout as is, so let me know if I should change it.

**Comment by cuavas** [comment]
This really falls into the “will need some manual configuration” category, but I think not disabling UI controls is probably the lesser evil for a console input device like this, particularly when you consider that people running NES software on MAME may be set up with game controllers without the “UI Toggle” input conveniently mapped.

**Comment by 0kmg** [comment]
Not annoying people doing console emulation who don't typically use UI Toggle is a good enough argument for me. I also switched the keys a bit to avoid P. Before I had everything identical with the "I Can..." driver. Since I'm breaking the possibility of a common layout anyway, I've shifted the bottom row of buttons. For some reason they put the lowest F way up there on the backslash key in that driver. I've moved it to the more sensible 'z' and shifted all the lower key assignments accordingly.

**Pull request merged**
