### PR TITLE
SEGA:System-E::fantzn2 extend YM2413.

### PR DESCRIPTION
**Pull request by hiroshica**
sound code == sega mark3.
extend emu. YM2413.

### CODE REVIEW

**Comment by galibert** [comment]
Hi,

Your code is a little strange, the write to de00 specifically.  Could you
explain it?

Best,

  OG.

**Comment by hiroshica** [comment]
Because that is adapted FM writing begins when the address value is entered
, it is rewritten by the value of dipSwitch.
I tried to appropriately translate translator . Will communicate meaning ?



2015-02-19 19:13 GMT+09:00 Olivier Galibert <notifications@github.com>:

> Hi,
>
> Your code is a little strange, the write to de00 specifically. Could you
> explain it?
>
> Best,
>
> OG.
>
>
> On Thu, Feb 19, 2015 at 8:55 AM, Hiromitsu Shioya <
> notifications@github.com>
> wrote:
>
> > sound code == sega mark3.
> > extend emu. YM2413.
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/mamedev/mame/pull/137
> > Commit Summary
> >
> > - SEGA:System-E::fantzn2 extend YM2413.
> >
> > File Changes
> >
> > - *M* src/mame/drivers/segae.c
> > <https://github.com/mamedev/mame/pull/137/files#diff-0> (34)
> >
> > Patch Links:
> >
> > - https://github.com/mamedev/mame/pull/137.patch
> > - https://github.com/mamedev/mame/pull/137.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mamedev/mame/pull/137>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mamedev/mame/pull/137#issuecomment-75027238>.
>



-- 
------------------------------------------------------------------------------
                       しおち:hiroshica
                                              hiroshica@gmail.com

**Comment by galibert** [comment]
Hi,

The translator is sufficient.

You say, if I understand correctly, that writing 1 to de00 makes the game
use the chip.  Does that mean it never uses it normally?

Best,

  OG.


On Thu, Feb 19, 2015 at 11:42 AM, Hiromitsu Shioya <notifications@github.com

**Comment by hiroshica** [comment]
Originally to mastersystem of Japan have been FM is equipped with
I tried to hack to hear the rich sound in the game because the sound code
has been directly applied to SystemE

2015-02-19 20:34 GMT+09:00 Olivier Galibert <notifications@github.com>:

> Hi,
>
> The translator is sufficient.
>
> You say, if I understand correctly, that writing 1 to de00 makes the game
> use the chip. Does that mean it never uses it normally?
>
> Best,
>
> OG.
>
>
> On Thu, Feb 19, 2015 at 11:42 AM, Hiromitsu Shioya <
> notifications@github.com
>
> > wrote:
>
> > Because that is adapted FM writing begins when the address value is
> entered
> > , it is rewritten by the value of dipSwitch.
> > I tried to appropriately translate translator . Will communicate meaning
> ?
> >
> >
> >
> > 2015-02-19 19:13 GMT+09:00 Olivier Galibert <notifications@github.com>:
> >
> > > Hi,
> > >
> > > Your code is a little strange, the write to de00 specifically. Could
> you
> > > explain it?
> > >
> > > Best,
> > >
> > > OG.
> > >
> > >
> > > On Thu, Feb 19, 2015 at 8:55 AM, Hiromitsu Shioya <
> > > notifications@github.com>
> > > wrote:
> > >
> > > > sound code == sega mark3.
> > > > extend emu. YM2413.
> > > > ------------------------------
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/mamedev/mame/pull/137
> > > > Commit Summary
> > > >
> > > > - SEGA:System-E::fantzn2 extend YM2413.
> > > >
> > > > File Changes
> > > >
> > > > - *M* src/mame/drivers/segae.c
> > > > <https://github.com/mamedev/mame/pull/137/files#diff-0> (34)
> > > >
> > > > Patch Links:
> > > >
> > > > - https://github.com/mamedev/mame/pull/137.patch
> > > > - https://github.com/mamedev/mame/pull/137.diff
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/mamedev/mame/pull/137>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/mamedev/mame/pull/137#issuecomment-75027238>.
> > >
> >
> >
> >
> > --
> >
> >
> ------------------------------------------------------------------------------
> > しおち:hiroshica
> > hiroshica@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mamedev/mame/pull/137#issuecomment-75031755>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mamedev/mame/pull/137#issuecomment-75037792>.
>



-- 
------------------------------------------------------------------------------
                       しおち:hiroshica
                                              hiroshica@gmail.com

**Comment by hiroshica** [comment]
gamecode of mastersystem is I've been notified that the FM-hard is
installed in de00 to but System-E is
Originally it will not be notified because nothing is resting FM-hard.

2015-02-19 20:34 GMT+09:00 Olivier Galibert <notifications@github.com>:

> Hi,
>
> The translator is sufficient.
>
> You say, if I understand correctly, that writing 1 to de00 makes the game
> use the chip. Does that mean it never uses it normally?
>
> Best,
>
> OG.
>
>
> On Thu, Feb 19, 2015 at 11:42 AM, Hiromitsu Shioya <
> notifications@github.com
>
> > wrote:
>
> > Because that is adapted FM writing begins when the address value is
> entered
> > , it is rewritten by the value of dipSwitch.
> > I tried to appropriately translate translator . Will communicate meaning
> ?
> >
> >
> >
> > 2015-02-19 19:13 GMT+09:00 Olivier Galibert <notifications@github.com>:
> >
> > > Hi,
> > >
> > > Your code is a little strange, the write to de00 specifically. Could
> you
> > > explain it?
> > >
> > > Best,
> > >
> > > OG.
> > >
> > >
> > > On Thu, Feb 19, 2015 at 8:55 AM, Hiromitsu Shioya <
> > > notifications@github.com>
> > > wrote:
> > >
> > > > sound code == sega mark3.
> > > > extend emu. YM2413.
> > > > ------------------------------
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/mamedev/mame/pull/137
> > > > Commit Summary
> > > >
> > > > - SEGA:System-E::fantzn2 extend YM2413.
> > > >
> > > > File Changes
> > > >
> > > > - *M* src/mame/drivers/segae.c
> > > > <https://github.com/mamedev/mame/pull/137/files#diff-0> (34)
> > > >
> > > > Patch Links:
> > > >
> > > > - https://github.com/mamedev/mame/pull/137.patch
> > > > - https://github.com/mamedev/mame/pull/137.diff
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/mamedev/mame/pull/137>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/mamedev/mame/pull/137#issuecomment-75027238>.
> > >
> >
> >
> >
> > --
> >
> >
> ------------------------------------------------------------------------------
> > しおち:hiroshica
> > hiroshica@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mamedev/mame/pull/137#issuecomment-75031755>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mamedev/mame/pull/137#issuecomment-75037792>.
>



-- 
------------------------------------------------------------------------------
                       しおち:hiroshica
                                              hiroshica@gmail.com

**Comment by mr-t-guru** [comment]
erm....
maybe Yasuhiro can contact the guy directly then give us an *English*
version of his explanation :-)


Guru

**Pull request merged**
