### PR TITLE
New WORKING clone

### PR DESCRIPTION
**Pull request by clawgrip**
-----------------------
Galaxy Gunners (1990 copyright) [David Torres, ClawGrip, Recreativas.org]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
given only the date differs, are we sure this isn't just a hack? Italy seemed to love date hacking things to appear more modern.

**Comment by clawgrip** [comment]
No, neither original silkscreen on the PCB nor original labels. 
Should I label it as "1990 year Hack?" or something like this? I also see strange to have just only one different byte between sets (and on one sprite) aside of the year change.
I think is good to have this set documented on the source, as, at least, we can tell the CPU type, the clock frecuency and the board's PLDs...

**Comment by DavidHaywood** [comment]
difficult to know, I'd probably label them as '1990 copyright' and '1989 copyright' instead of 'set 1' and 'set 2, older' since it's literally the same code.

one bit changed on a sprite is probably bitrot in one of the sets.

**Comment by clawgrip** [comment]
Sounds good, I've renamed the sets.

**Pull request merged**
