### PR TITLE
m10: Add support for missing greenber ROM gb7

### PR DESCRIPTION
**Pull request by palazzol**
Support new ROM dump.  Not yet playable, but attract mode runs and can be coined up

### CODE REVIEW

**Comment by happppp** [comment]
I played it for a bit after adding the missing up/down direction. I think it is working fine and can be marked working.

**Comment by MASHinfo** [comment]
@Frank
Is there a story about the Green Beret board that I can add to the MAMEinfo.dat, like
10th February 2020: Frank Palazzolo - Found a Green Beret board in Spain... ?
Many thanks :)

**Comment by happppp** [comment]
You can ping him with @palazzol 
That "frank" is someone else :D

**Comment by palazzol** [comment]
Well...I am going through bins of arcade pcbs that I've had since I was active with MAME from 97-03 or so.  Last night...when romident said it was Irem Green Beret...I saw it said gb7 was bad!  I dumped all the roms and gb8 was bad on mine.  Luckily a different one went bad on this board!
    I will eventually replace gb8 and try to record some samples...and also verify the color circuitry.

**Comment by palazzol** [comment]
FWIW I'm in Michigan USA..not Spain...and the pcb was in my basement in a box :)

**Comment by MASHinfo** [comment]
I think I can add that to the MAMEinfo. Thx!
https://www.deepl.com/translator helped me to translate it into German... :)

**Comment by DavidHaywood** [comment]
Ah, very lucky then.  These IREM PCBs are notorious for having bad ROMs, so getting a complete non-corrupt set is something of a miracle; your PCB having a different faulty ROM just adds more evidence for that.

Fingers crossed another IREM/IPS Anrdomeda shows up at some point too (again not the more common Galaxian bootlegs with that printed on the PCB or the GamePlan title)

**Pull request merged**
