### PR TITLE
Filesel cleanup

### PR DESCRIPTION
**Pull request by npwoods**
This fixes a bug in filesel.cpp that caused clicking on directories to omit the final path separator in the target directory, and does a bunch of changes related with replacing char buffers with std::string

### CODE REVIEW

**Comment by cuavas** [comment]
The new overload for ` utf8_from_unichar` is heavily dependent on small string optimisation for performance. It's going to perform pretty poorly with glibstdc++4.9 (glibstdc++5 and libc++ have SSO). Does MSVCPRT have SSO?

**Comment by npwoods** [comment]
According to http://info.prelert.com/blog/cpp-stdstring-implementations, MSVC used SSO since 2010.

Even if it didn't, is that really an issue?  SSO is clearly the future, and the file dialogs are not exactly performance sensitive.

**Comment by cuavas** [comment]
It's all very well to say that file dialogs are not performance-sensitive, but people will inevitably use it for something else.

**Comment by cuavas** [comment]
Also, have you checked for things using the result of the functions that you changed from `int` to `bool` return as an integer?  The behaviour of implicit `bool` to `int` cast shouldn't break anything, but it's still considered bad form to use `bool` in integer context.

**Comment by npwoods** [comment]
Arguably, the std::string overload of `utf8_from_uchar` should be made inline.  Presumably it would optimize into calling the other overload directly onto the buffer of the small string optimized instance of std::string

**Pull request merged**
