### PR TITLE
Tilemap operation and flip screen deglobalization (nw)

### PR DESCRIPTION
**Pull request by ajrhacker**
- Global tilemap flipping and dirty-marking operations are no longer global; they now apply only to tilemaps associated with a particular decoder.
- K053251 now uses a device callback to handle dirty-marking resulting from palette updates.
- Generic flip screen handling has been moved down from driver_device into gfxdecode_device. This entails the addition of required_device<gfxdecode_device> to many DECO drivers, and a boolean state variable to a few framebuffer/blitter-based drivers (epos.cpp, jangou.cpp, merit.cpp, n8080.cpp, nightgal.cpp).
- video/generic.* (which consisted only of generic GFX layouts) has been folded into digfx.*, along with gfxdecode_device.

### CODE REVIEW

**Comment by cuavas** [comment]
I'm sorry but this really doesn't make sense to me. How is making flip screen variable apply to a gfxdecode better than what we have? What's the use case where this is better than moving the flip screen attributes onto the tilemaps themselves?

The gfxdecode device isn't even a real "device" as such, it's a kind of HLE of the concept of mapping memory layout to bitmaps. It shouldn't be holding machine state.

I agree that the global flip screen state is a bit weird/confusing, not relevant for non-video machines, and often unhelpful for multiscreen machines, but this really doesn't seem like a sensible way to address it.

Also, looking to eliminate the dependency of tilemaps on the tilemap manager, and holding them with `unique_ptr` rather than naked pointers that magically get cleaned up when it feels like it could make sense.

**Comment by cuavas** [comment]
This is another good example of why it's worth discussing stuff with the team before embarking on a major change.

**Comment by ajrhacker** [comment]
> What's the use case where this is better than moving the flip screen attributes onto the tilemaps themselves?

Besides needing to be copied to the tilemaps, flip screen bits often need to be read by sprite drawing routines as well.

> The gfxdecode device isn't even a real "device" as such, it's a kind of HLE of the concept of mapping memory layout to bitmaps. It shouldn't be holding machine state.

Well, it's an unavoidable fact that many devices aren't "real devices" that you'd find on an actual PCB but abstractions created for the sake of emulation, and they're fully capable of holding HLE machine state if they need to. MAME's video device emulation has a particularly poor correspondence with actual ICs (though that can be a bit difficult to work out in the case of undocumented customs) and is generally a bunch of concepts (some very legacy-ish) thrown together in a way that sort of works. The screen_device still manages a whole bunch of somewhat to barely related things like a priority bitmap. device_video_interface ought to be the sort of structure to hold screen-flipping information, but device_video_interface as it exists is a conceptual abortion that provides nothing particularly useful, just the screen that also gets passed as a parameter in the update function. I see device_gfx_interface as better realized and think more devices should use it--but provide their own flipscreen functionality if they require it. (It's possible that many arcade boards that use custom graphics ICs have to write the flipscreen status to control registers on each graphics device; at least, this seems to be the case with later Seibu games.)

> Also, looking to eliminate the dependency of tilemaps on the tilemap manager, and holding them with unique_ptr rather than naked pointers that magically get cleaned up when it feels like it could make sense.

Eliminating the global tilemap manipulation functions and making tilemaps more dependent on device_gfx_interface is actually a step in the direction of having them owned by it. However, it would likely double the code churn here, and I still can't figure out how to replace tilemap_manager::create while keeping its syntax from becoming even uglier than it is.

> This is another good example of why it's worth discussing stuff with the team before embarking on a major change.

I'm willing to discuss things here or on the list, but so far the other participants in this thread have been you and yourself.

**Comment by cuavas** [comment]
I don't think machine state should be moved into gfxdecode, and machine state that has nothing to do with decoding graphics definitely shouldn't be moved into gfxdecode.  For example look at the dual-screen Psikyo 4 platform: two CRTs, independent flip screen bits, one gfx space for both.  There are also systems where some layers are magically flipped by setting a bit in a control register while other layers need the software to set the flip bits on the individual elements in the layer and adjust positions accordingly.  Global flip screen bits are really only good for games like Space Invaders and Laser Battle that have a single monitor and use relays to flip the polarity of the deflection coils.

**Comment by ajrhacker** [comment]
> machine state that has nothing to do with decoding graphics definitely shouldn't be moved into gfxdecode

Well, flipping tiles does qualify as decoding graphics in a way.

> There are also systems where some layers are magically flipped by setting a bit in a control register while other layers need the software to set the flip bits on the individual elements in the layer and adjust positions accordingly.

I don't know about those systems, but they should in no way be forced to use the generic flipscreen routines in gfxdecode_device.

> Global flip screen bits are really only good for games like Space Invaders and Laser Battle that have a single monitor and use relays to flip the polarity of the deflection coils.

Actually, it extends to hardware quite a bit later and more advanced. Take a look at the previous generation of Psikyo hardware (1993-1996), and you'll find a global flip bit hardwired to a DIP setting! (Space Invaders, being framebuffer-based, doesn't use or need the generic flipscreen routines.)

**Comment by ajrhacker** [comment]
The inclusion of flip screen latches in gfxdecode_device seems to be the main point of contention. Not long after I posted my last message, I came to the late-night conclusion that it would be better to eliminate them from generic devices and add them to specific drivers as needed, much as was done with such odds and ends as generic palette RAM. If there are no objections, I'll have that semi-major change included in this pull request.

**Comment by cuavas** [comment]
I don't have a problem with moving it out of the base machine state into drivers.

**Comment by rb6502** [comment]
@ajrhacker makes a lot of excellent points about the state of video, but yeah, I don't think the flip bit belongs in the graphics decode.

**Comment by ajrhacker** [comment]
Well, it turns out "semi-major" rather understates the code churn here.

I had a belated second thought that the generic flip screen latches could be separated as a device interface which drivers could use directly, thus making most of my laborious work here pointless. However, making them driver-specific, however monstrous the change may be, could make it easier to separate out graphics devices in the future. What do other devs have to say on this point?

**Comment by mamehaze** [comment]
Well I agree they need to be moved, it's completely illogical as a global global concept, I also agree they don't make sense in the GFX decode

in terms of keeping code churn to a minimum I'd personally I'd consider the screen device, but some others would disagree, and we'll probably end up with disagreement like there was over the screen orientation thing a while back (I still don't really feel that the orientation is a per-machine property either, it's a layout thing, it was moved to be part of the 'screen' device but it doesn't really belong there either so ended up being moved back)

in reality tho, it probably makes more sense to be done per-driver, like the sound latches.

things like random number generators should be the same, and also a device that gets added per driver if you want a PRNG (allowing for different algorithms and devices to have RNGs that don't affect each other etc.)

**Comment by ajrhacker** [comment]
machine().rand() seems to be used in drivers mainly as a crutch when some bit needs to vary in a way that the coder hasn't figured out. It's also used by the core's ROM loader to random-fill NO_DUMP regions in a way that doesn't break savestates.

**Comment by mamehaze** [comment]
some hardware does have genuine random number generators tho, system32 comes to mind plus simulation of some protection devices eg. the Kaneko ones.

I think having it as a device, which can be named (and if it is a fake one, given a name/tag to show such) could actually be useful.

**Comment by ajrhacker** [comment]
I just rebased this branch to resolve a few conflicts. I'd like to have some general feedback on this as it stands now; I'm inclined to withdraw this pull request unless there's a consensus that it really represents the right approach, not just an overambitious mass of code churn.

**Comment by ajrhacker** [comment]
I'd update this to resolve the conflict with my own changes if I was still confident in this approach. I now think this may not be quite the right approach, which perhaps could lie in improving device_video_interface to make it do something actually useful.

**Pull request closed without merging**
