### PR TITLE
Restore buttons 2-3 for Quarth / Block Hole

### PR DESCRIPTION
**Pull request by Mikejmoffitt**
The actual Quarth / Block Hole board allows the use of buttons 2 and 3 as well as 1 to fire blocks. Even though they all do the same thing, being able to hit multiple buttons in quick succession is critical for quick and accurate play.

I restored joystick down as well, as the game does scan for it and read it (even though it is only reflected in the test menu).

### CODE REVIEW

**Comment by p1pkin** [comment]
does control panel of original cabinet have these buttons ?

**Comment by DavidHaywood** [comment]
typically if things are tested in service mode we leave them in anyway...

**Comment by angelosa** [comment]
Chain shooting is when you have multiple buttons attached to the same action.
Another game that has this feature built in is Shmup Skill Test included in Shooting Love 2007

**Comment by vadosnaprimer** [comment]
Does it result in shooting _every_ frame, or it uses the same bit and can shoot at most _every other_ frame?

**Comment by Mikejmoffitt** [comment]
I'd have to check what happens if buttons 1, 2, and 3 are depressed across frames n, n+1, and n+2. I don't know if the max firing rate effectively becomes 60Hz with multiple buttons. Regardless, it is much easier to "piano" your fingers across multiple buttons in succession than it is to repeatedly hit the same button at the same rate. The Famicom and Game Boy versions of this game support the idea that multiple firing buttons are intended, as they map all face buttons to this action.

**Comment by vadosnaprimer** [comment]
You forgot the video link I suppose?

**Comment by Mikejmoffitt** [comment]
Yes, my mistake. Here it is: https://www.youtube.com/watch?v=i9SArNFYgS0

**Comment by Mikejmoffitt** [comment]
By frame-by-framing the video, I think I've also narrowed down how my PCB is crashing on occasion, and I think it's a legitimate bug in the game. When I return home I can work on a repro for it.

**Pull request merged**
