### PR TITLE
hh_sm510: Rename Elektronika drivers to use local Soviet names

### PR DESCRIPTION
**Pull request by algestam**
This PR renames the Elektronika drivers in `hh_sm510.cpp` to use local Soviet names instead of English export titles (see discussion in #8886).

Marking this PR as a draft until name changes has been agreed upon before renaming ROM files.

### CODE REVIEW

**Comment by happppp** [comment]
@p1pkin or @shattered can you have a quick look?

**Comment by shattered** [comment]
Looks good to me.  There are a billion of transliteration rules from Cyrillic to Latin, but I don't think it matters to MAME enough to enforce any of them :)

**Comment by happppp** [comment]
Thanks for having a look.
@algestam feel free to un-draft.

**Comment by algestam** [comment]
Thanks for looking into this and let me know if help is needed with updating the files.

**Pull request merged**
