### PR TITLE
sinclair/atm.cpp: ATM Turbo 2 - support ATA devices

### PR DESCRIPTION
**Pull request by holub**

### CODE REVIEW

**Comment by holub** [comment]
On hold: Looks like there ara some issues if driver stars without hdd image attached

**Comment by holub** [comment]
now ready

**Comment by cuavas** [comment]
Seems a bit hacky going peeking through the slot into the hard disk device.  It’s going to blow up if the slot is emptied or something else is connected.  Would it be better to default to not having a hard disk connected to the slot?  Is there a better way to achieve what it’s trying to do?

**Comment by holub** [comment]
I still think detect if image selected is better  than use extension option. The problem I tried to solve initially: in case image is not defined hdd status is IDE_STATUS_DRDY | IDE_STATUS_ERR, which is arguably correct.
+ @smf-

**Comment by holub** [comment]
Honestly I don't know how to fix this.
Having multiple machines with and without hdd doesn't look like a option. Forcing user to use hdd image if it's not required doesn't sound right either.

**Comment by holub** [comment]
I think I've got it now. Updated. Thanks!

**Comment by holub** [comment]
Doesn't worth to review. Bigger changeset is coming anyway.

**Pull request closed without merging**
