### PR TITLE
move 68705 timer logic out of arkanoid driver and into 68705 core

### PR DESCRIPTION
**Pull request by mamehaze**

### CODE REVIEW

**Comment by cuavas** [comment]
This is completely inadequate.  You're ignoring the fact that it can act as a counter, or a gated timer, and that the values of the timer control registers on reset are controlled in part by the mask option register in EPROM.  Please fix this - you could use a CPU core with a working timer/counter like MCS-48 as a reference.

**Comment by Lord-Nightmare** [comment]
That code in the commit belongs to me, not haze. Haze copied it from the machine/arkanoid.cpp specific implementation to the general implementation. I know it needs work, but it currently works for the limited subset of the 6805 timer which arkanoid.cpp needs, and arkanoid is so far the only mcu which actually uses the peripheral timer. So this is not a 'regression'; it isn't fully featured, but it works for the one use case we have so far.

**Comment by mamehaze** [comment]
exactly, this is correct for the scope of the work being done.  (ie the driver was the wrong place for it, the core is the correct place for it)

intention is to not break functionality, if we end up with things that make more use of the timer it can be improved and known use case (arkanoid) can be tested with new code.

it's progress however you look at it.  this way at least it does improve if something else needs it, as opposed to rotting away in a driver specific implementation (which is what has happened with a lot of peripheral code that has been placed in drivers over the years, rather than in the cores)

**Comment by cuavas** [comment]
The trouble is, when stubs like this are implemented in a driver it's acceptable for them to only satisfy the needs of that system.  However, when stuff is moved to a CPU core, it's expected that it should behave correctly for the general case.  The I/O ports and timer/counter are not behaving correctly for the general case, which means they have to be rewritten.  I hate the attitude that you take for granted that someone will do this rewriting for you.  It's not like the behaviour of the 68705 family is a big secret, it's a very well-understood and well-documented MCU family.

**Comment by Lord-Nightmare** [comment]
The code didn't exist at all in the 6805 cpu core before this addition happened. Moogly asked a while ago for it to be merged with the cpu core since the 68hc05 used on CD-I MCUs do use the timers and that later mcu works very similarly to these. This was supposed to be a step in that direction of getting it done fully in the cpu core and removing differing driver-specific implementations.
Implementing the MOR stuff shouldn't be hard at all, I was looking into that a few minutes ago. The more complicated DRIVER_LINE stuff for the /TIMER input though, I'm not sure if I understand enough of the _LINE system to implement that.

**Comment by rb6502** [comment]
For CPU cores, I've generally found it's much, much better to only implement things you have an available test case for.  Implementing everything and then going back later and trying to debug it is a complete nightmare.  I realize this goes against good software engineering, but it's proven to be savvy emulation programming.

That said, the code should fatalerror() loudly if anything tries to use any unimplemented modes, because silently failing in that case is the worst thing of all.

**Pull request merged**
