### PR TITLE
fmtowns_cd.xml: 12 new dumps, 9 replacements, 4 missing floppies added

### PR DESCRIPTION
**Pull request by rzero9**
- Added the missing floppy disks to pharmony and wyattd [tenyuhuang]
- Added the missing floppy disk to landlore [cyo.the.vile]
- Added the missing floppy disk to genchohi [Neo Kobe Collection]
- Normalized the titles of the New Horizon discs
- Moved gnutowns to the applications section, since it is a collection of GNU tools and not an OS
- Demoted asu120ex to not working (this doesn't seem to be a regression, it was just marked incorrectly)
- Promoted beast, beast2 and gunship from partial to fully working after the latest fixes to 15-bit sprite drawing [crazyc]

New working software list additions
-----------------------------------
Ehon Writer V1.1 L10 (FMB-3011) [redump.org]
CD Learning System II - New Horizon English Course 2 [redump.org]
FM Towns FlexData Collection Vol. 1 - E to Oto no 365-nichi [redump.org]
PersoCom de Tanoshimu - Yama to Chizu Vol. 1 [redump.org]
Shijou Saikyou no Video Bible - The Greatest Video Bible in the World [redump.org]
Shiki o Irodoru - Nihon no Shouka - Aki [redump.org]
Shiki o Irodoru - Nihon no Shouka - Fuyu [redump.org]
Shiki o Irodoru - Nihon no Shouka - Haru [redump.org]
Shiki o Irodoru - Nihon no Shouka - Natsu [redump.org]
Tamashii no Mon - Dante "Shinkyoku" yori [redump.org, Coolmod]
TenderLight V1.1 L10 [redump.org]
TownsPAINT V1.1 L22 [redump.org]
Welcome to FM Towns (1994-12-19) [redump.org]

Replaced software list items
----------------------------
Aoki Ookami to Shiroki Mejika - Genchou Hishi [redump.org]
Cal Gaiden - Tiny Steps Behind the Cal [redump.org]
Free Will - Knight of Argent [redump.org]
GNU for Towns Release 2 [redump.org]
Kikai Jikake no Marian [redump.org]
Lands of Lore - The Throne of Chaos [redump.org]
Planet's Edge [redump.org]
Taikenban CD [redump.org]
Welcome to FM Towns (1994-09-29) [redump.org]
Yamane no Sumu Mori [redump.org]

Software list items promoted to working
---------------------------------------
Planet Harmony [tenyuhuang]
The 4th Unit 7 - Wyatt (demo) [tenyuhuang]

### CODE REVIEW

**Comment by rzero9** [comment]
Actually, let me take back that Shadow of the Beast 2 promotion, I tested it a bit better and it turns out it's not playing music during gameplay (or more precisely, it plays for a fraction of a second and then stops), so it's back to partial.

**Comment by cracyc** [comment]
>Demoted asu120ex to not working (this doesn't seem to be a regression, it was just marked incorrectly)

This works if the second port is set to controller instead of mouse.

**Comment by rzero9** [comment]
That's... strange. I mean, in a way it makes sense because it's a fighting game and there's a 2-player mode, but it doesn't make sense that it would lock up like that even if you don't have anything plugged into port 2, and even in the single-player modes...

I'm changing this PR to a draft for a bit while I investigate how it's supposed to behave on real hardware.

**Comment by cracyc** [comment]
It's checking specific bits in the controller port io ports.  It's quite possible that we return the wrong values for mouse and nothing, they appear to 0 when not connected, maybe they should be 1.

>Actually, let me take back that Shadow of the Beast 2 promotion, I tested it a bit better and it turns out it's not playing music during gameplay (or more precisely, it plays for a fraction of a second and then stops), so it's back to partial.

We return 00,00,03,00 for cd status when starting but 07,00,00,00 after.  The causes it to continuously try to restart the music.  Seems likely that the later is supposed to indicate the music has finished.

**Comment by rzero9** [comment]
Okay, so I tested it with a real machine, and it's definitely a mix of a game bug and a MAME bug.

2 controllers = always works
controller on port 1 + mouse on port 2 = always freezes the game
controller on port 1 + nothing on port 2 = freezes the game in MAME but works on real hardware

**Comment by cracyc** [comment]
If you have a minute can you check in dos debug or something what the controller io ports return when nothing is connected?

**Comment by rzero9** [comment]
With everything disconnected I get 7F for all 4 I/O addresses (4d0 to 4d3).

This is probably unrelated to the Asuka issue, but when I was checking this I noticed that the odd addresses (4d1, 4d3) always return FF in MAME, while on real hardware they always mirror the previous address (4d0 = 4d1, 4d2 = 4d3).

**Comment by cracyc** [comment]
Thanks.  Committed the changes for the pad and cdda, it stops playing if you talk to an npc with cd voices enabled but since townsemu does the same it's probably right.  Don't promote sotb2 yet though because the dialogue boxes, https://youtu.be/SWTCA-Io1xk?t=74, don't display.

**Comment by rzero9** [comment]
It seems the pad fixes also help the early Alice Soft games that didn't respond to controller inputs before. I'll give those a re-test the next time I update the floppy lists.

**Comment by cracyc** [comment]
https://github.com/mamedev/mame/commit/617fe8553dfa9957a25f55625eb3e14989878c29 fixes the sotb2 text boxes the background layer offset which didn't match the text box background.  I did basic regression testing but wouldn't be too surprised to see breakage.

**Comment by rzero9** [comment]
I think pretty much everything that uses hardware sprites is broken now... I tested aburner, beast, beast2, gforce2, splatth, genocsq, raiden and a few others and they all hang soon after booting, usually when they are supposed to start drawing sprites.

This is basically the same thing that happened when I tried (and failed) to make Mad Stalker boot correctly without breaking anything else, so they are probably stuck waiting for the sprite drawing flag.

**Comment by cracyc** [comment]
Oops, I forgot to commit something.  I guess the sprites won't work if the timer doesn't run at all.

**Comment by rzero9** [comment]
I did a couple quick tests with that last commit. The good news is CRI games seem to run at the correct speed and Mad Stalker boots, but the bad news is games that are actually supposed to run at full 60 fps (like Splatterhouse or Raiden, for example) don't seem to be updating the sprites on every frame as they should.

With Splatterhouse in particular it's very easy to see. When you get hit, the sprite of the main character is supposed to blink while you are invulnerable, but now it either stays on screen all the time or disappears completely (depending on which frame you get hit, I guess).

**Comment by angelosa** [comment]
> Okay, so I tested it with a real machine, and it's definitely a mix of a game bug and a MAME bug.
> 
> 2 controllers = always works
> controller on port 1 + mouse on port 2 = always freezes the game
> controller on port 1 + nothing on port 2 = freezes the game in MAME but works on real hardware

Friendly reminder that this kind of note should be near the affected SW item.
Also last part makes me suppose that it should be `supported="partial"` anyway.

**Comment by cracyc** [comment]
Splatterhouse was rewriting the layer 1 display address forcing it to sprite page 0 even if page 1 was the current display buffer so it would draw the blinking sprite but not display it.  This solution (https://github.com/mamedev/mame/commit/ec687c94a03c80896e1553135f76ead5ebda312f) seems kind of wrong but the other things I tried had other side effects and the tech ref doesn't say anything specific about it.

**Comment by rzero9** [comment]
Thanks, I've done some more tests and seen no regressions so far, so I've updated the list with all the stuff that has been fixed. There are still some games that will require real hardware tests to really know if they are running as intended, but that will take time, so for now I think this PR could be merged.

It's interesting that quite a few games have the "no mouse connected to port 2" thing, though. I'm guessing it's actually a bug in a certain version of Fujitsu's TBIOS API and everything compiled with it is affected.

**Pull request merged**
