### PR TITLE
Correct Landing Gear control [sjy96525]

### PR DESCRIPTION
**Pull request by sjy96525**
Changed Landing Gear from Pedal to AD_STICK_Z.

### CODE REVIEW

**Comment by angelosa** [comment]
Pretty sure this actually requires AD_STICK_Y not Z (just like Top Landing)

**Comment by angelosa** [comment]
AD_STICK_Z with default 0x80 likely breaks validation.

Did you compiled & tested it first?

**Comment by sjy96525** [comment]
Yes you did, I Adjusted control, it's Working.

**Comment by happppp** [comment]
A typical airplane throttle control is not an autocenter stick(that is what
AD_STICK is to MAME). It is more like a slider. Maybe IPT_DIAL is better
here.

**Comment by happppp** [comment]
Scrap that, IPT_DIAL is relative.
I think this one can be solved if you add a centerdelta of 0, then this PR can be accepted.

So:
PORT_BIT( 0xff, 0x80, IPT_AD_STICK_Z ) PORT_MINMAX(0x00, 0xff) PORT_SENSITIVITY(35) PORT_KEYDELTA(5) PORT_CENTERDELTA(0) PORT_REVERSE

**Comment by cuavas** [comment]
`IPT_PADDLE` can be used for things like this.

**Comment by happppp** [comment]
Same thing underneath, isn't it? An autocenter +/- axis.
It would still need the centerdelta(0) workaround

**Comment by cuavas** [comment]
Paddle doesn't auto-centre - a real-life paddle control is typically a knob on a potentiometer, as used in paddle games like Pong (hence the name).

**Comment by happppp** [comment]
IPT_PADDLE autocenters by default in MAME. I just doublechecked to be sure.

**Comment by cuavas** [comment]
You're right, paddle games/consoles with `IPT_PADDLE` are explicitly setting `PORT_CENTERDELTA(0)`, so it's more like an auto-centring wheel than a paddle.

**Pull request merged**
