### PR TITLE
add support to extractcd for GDROM .cue/.bin 

### PR DESCRIPTION
**Pull request by nhand42**
This adds support to chdman extractcd for Redump GDROM .cue/.bin format. This complements an earlier patch adding Redump GDROM .cue/.bin support to createcd.  

This has been tested and works well for TYPE_I and TYPE_II discs. For those GDROM types the output from repeated createcd -> extractcd cycles is byte-identical. 

Type I disc.

```
74477ca268dcfec219463d921cbed89a  type_i_disc.cue
be87b59616171c57d9fd252acdda806b  type_i_disc (Track 1).bin
824ff123fbce45b5883962eb3fa43cab  type_i_disc (Track 2).bin
a127c8645b365990d8ec74a24dfc97c2  type_i_disc (Track 3).bin
be87b59616171c57d9fd252acdda806b  output01.bin
824ff123fbce45b5883962eb3fa43cab  output02.raw
a127c8645b365990d8ec74a24dfc97c2  output03.bin
064ae98cc6ba4431293eba78496b19af  output.cue
```

Type II disc.

```
1fb5fdaad0a7eb9ded22aef0994d9b12  type_ii_disc.cue
ba46bf7c1538394ce47e07c6f55054fb  type_ii_disc (Track 1).bin
4e8310bf18cae2749551c22a978f7ad7  type_ii_disc (Track 2).bin
9ef9194c451f3119c75050743967387e  type_ii_disc (Track 3).bin
997e6cf460f0a50e3c9c2e68c58c9a9d  type_ii_disc (Track 4).bin
c17bb9b873f34b01370f51688f7e25f5  type_ii_disc (Track 5).bin
ba46bf7c1538394ce47e07c6f55054fb  output01.bin
4e8310bf18cae2749551c22a978f7ad7  output02.raw
9ef9194c451f3119c75050743967387e  output03.bin
997e6cf460f0a50e3c9c2e68c58c9a9d  output04.raw
c17bb9b873f34b01370f51688f7e25f5  output05.raw
3d456f88c8ba986a7a29c7176b979945  output.cue
```

For TYPE_III some of the Redump data is thrown away by createcd. For example frames 75 - 224 in the final track. These are zero frames and can be recreated by populating the sync bytes, the MSF, the mode, then calculating the EDC/ECC. The EDC routines have been copied mostly verbatim from cdrtools (licensed LGPL). For the TYPE_III titles tested so far, the output from repeated createcd -> extractcd cycles is byte-identical.

Type III disc.

```
9c6830264544845880e14fe64eb94193  type_iii_disc (Track 1).bin
8973940cea2f0c670cb0084f12710a21  type_iii_disc (Track 2).bin
3753e9d495afabab3ef68228a4864b88  type_iii_disc (Track 3).bin
92f4b008fb82c9cd5c8b10b02a540b96  type_iii_disc (Track 4).bin
886ef9f9532ba942ebb369df3784090c  type_iii_disc (Track 5).bin
d243c502fa1654f21f09d38fcc2ea9f3  type_iii_disc (Track 6).bin
9c6830264544845880e14fe64eb94193  output01.bin
8973940cea2f0c670cb0084f12710a21  output02.raw
3753e9d495afabab3ef68228a4864b88  output03.bin
92f4b008fb82c9cd5c8b10b02a540b96  output04.raw
886ef9f9532ba942ebb369df3784090c  output05.raw
d243c502fa1654f21f09d38fcc2ea9f3  output06.bin
```

This code does assume the zero frames don’t contain any purposefully inaccurate EDC or ECC data as for copy-protection. This should be true for every legitimate Dreamcast GDROM but if there is an exception please let me know.

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
I don’t think the GD-ROM pattern stuff belongs in cdrom.cpp – it’s not really something inherent to the disc format, it’s essentially hack for the cue/bin format.  It’s the kind of thing they can only get away with because the format is essentially dead and no new discs are being pressed.

@p1pkin what are your thoughts on the feature?

**Comment by Anuskuss** [comment]
Hey @nhand42, I've been using the superior CUE+BINs Redump format for a while now and I got excited when I saw that someone finally added support for it in CHD - thanks! Has the Pattern III issue been figured out yet? Is the difference in the user or the auxiliary data? I don't know enough about the DC but I do know a thing or two about ECC/EDC, so I'd be interested to hear from you. People using Redump actually care about disc preservation (and not just what the DC can read like in the case of GDI) so getting your files back from chdman is crucial.

**Comment by nhand42** [comment]
In its current state it is not archival quality for specific Redump discs. There’s an unresolved issue caused by the difference between Redump and TOSEC dump methods. TOSEC dumps have gaps where the frames can’t be read by Dreamcast hardware. Redump uses an alternate dump method which reads the whole disc. There’s a spreadsheet by Sonic3D showing the differences between the two dump layouts.

GDROM CHDs from createcd always use TOSEC layout, no matter whether the source is TOSEC or Redump. This means when using a Redump source the unreadable frames are discarded. Most of the time the discarded frames are literal zeroes. They are easily recreated during extractcd with no data loss.  

The issue is with TYPE_III discs. With these discs the final track has data frames that are not in the TOSEC dumps but are in the Redump dumps. These frames are discarded when creating the CHD from a Redump source (compatibility with TOSEC). When converting back to Redump .cue/.bin the frames are already lost.

The discarded frames shouldn’t matter for emulation. The frames aren’t even in TOSEC dumps so they can’t be that important. But they are important for archival purposes. The discarded frames are again just zeroes but in this case they are data-zeroes, so 2048 bytes of 0s with MSF and ECC calculated. It should be possible to recreate them but I haven’t got that working yet.

**Comment by Anuskuss** [comment]
@nhand42 I'm already aware of those differences because I was following the relevant discussions, but thank you for pointing them out nevertheless. It's always a good idea to have that information readily available for interested users to find.
I was able to successfully reconstruct the two dropped seconds in INDEX0 in the last data track of Shenmue. I haven't really looked at your code because I'm not very good at C++ but I wrote my own 2048 to 2352 implementation in Python ages ago. I'm not even exactly sure how it all works anymore but after messing with my code I could reconstruct the data. Can you send my the first sector of you failed attempt (meaning 2352 -> 2048 -> 2352) for me to look at (it should be okay to upload here since it's all zero data anyway)? Also make sure it starts at the right block address (in the case of Shenmue it's 43 53 23) and set the mode to 0x01 (since it's data and not audio).

**Comment by nhand42** [comment]
Sure thing. I'd appreciate any help you can offer. This is my code as a diff against the current pull request. I'm setting the mode and MSF from the physical frame then calculating the ECC using existing libcdrom routines. I've linked the first 225 frames from the final track in the original Redump source and the corresponding 225 frames after createcd -> extractcd. All other bytes in the final track and all other tracks are identical.

[original-redump-frames](http://www.manu.com.au/files/redump.frames)
[output-extractcd-frames](http://www.manu.com.au/files/extractcd.frames)

```
diff --git a/src/tools/chdman.cpp b/src/tools/chdman.cpp
index e27e442f5fd..01381c28f60 100644
--- a/src/tools/chdman.cpp
+++ b/src/tools/chdman.cpp
@@ -2644,8 +2644,43 @@ static void do_extract_cd(parameters_map &params)
                        // GDROM .cue/.bin embeds pregap in output file
                        if (mode == MODE_GDROM_CUEBIN && (trackinfo.pregap > 0) && (trackinfo.pgdatasize > 0))
                        {
-                               outputoffs += trackinfo.pregap * trackinfo.pgdatasize;
-                               trackinfo.frames -= trackinfo.pregap;
+                               if ((tracknum == toc.numtrks-1) && (gdrom_identify_pattern(&toc) >= GDROM_TYPE_III))
+                               {
+                                       // special case, 75 frames actual-zeroes, 150 frames data-zeroes with PQ and sync
+                                       outputoffs += 75 * trackinfo.pgdatasize;
+                                       trackinfo.frames -= 225;
+                                       discoffs += 225;
+
+                                       uint8_t buffer[2352];
+                                       static const uint8_t syncbytes[12] = {0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00};
+                                       uint32_t physframeofs = trackinfo.physframeofs;
+
+                                       for (int frame=0; frame < 150; frame++)
+                                       {
+                                               uint32_t msf = lba_to_msf(physframeofs);
+                                               memcpy(&buffer[0], syncbytes, 12);
+                                               buffer[12] = msf>>16;
+                                               buffer[13] = msf>>8;
+                                               buffer[14] = msf&0xff;
+                                               buffer[15] = 1; // mode_1
+                                               memset(&buffer[16], 0, 2048);
+                                               ecc_generate(&buffer[0]);
+
+                                               output_bin_file->seek(outputoffs, SEEK_SET);
+                                               uint32_t byteswritten = output_bin_file->write(&buffer[0], 2352);
+                                               if (byteswritten != 2352)
+                                                       report_error(1, "Error writing pregap-frame %d to file (%s): %s\n", frame, output_file_str->second->c_str(), chd_file::error_string(CHDERR_WRITE_ERROR));
+
+                                               outputoffs += 2352;
+                                               physframeofs++;
+                                       }
+                               }
+                               else
+                               {
+                                       // normal case, pregap contains actual-zeroes
+                                       outputoffs += trackinfo.pregap * trackinfo.pgdatasize;
+                                       trackinfo.frames -= trackinfo.pregap;
+                               }
                        }

                        // now read and output the actual data
```

**Comment by Anuskuss** [comment]
Isn't [original-redump-frames](http://www.manu.com.au/files/redump.frames) supposed to be the original data? Because as I said earlier the two second block should start at 43:53:23, while yours starts at 22:57:37. I checked the data in TOSEC just to be sure and there the last track starts at 43:55:23, which when subtracting the missing data and weird layout, is identical to Redump. Are you sure you uploaded **Shenmue (Europe) (En,Fr,De,Es) (Disc 1) (Track 6).bin**?
Comparing original-redump and output-extractcd I can see that the EDC is missing (all null bytes) in the latter which is definitely strange.
Can you try to recreate "output-extractcd-frames" with the correct address (either by fixing your calculation or by hardcoding it) so I can take a look at it again? The ECC/EDC generator code should be the same (and has been working correctly according to your previous comments) so I'm still clueless as to why it's failing.

**Comment by nhand42** [comment]
I’m using a different title for my tests. The important thing is the difference, not a specific title. You can see the MSF in the original and the converted frames are the same.

I also spotted the absent EDC but don’t know whether this is a limitation in the libcdrom routines or something I’ve done incorrectly.

**Comment by Anuskuss** [comment]
Okay, I was just trying to make sure we are working on the same data. Good news is, I ran 2352->2048->2352 on your `original-redump` and could successfully regenerate the data. I also ran it with a zeroed out EDC, and got the same output as `output-extractcd` (meaning ECC generation is working fine). It's probably a small (copy-paste) mistake somewhere and probably easier to spot for you than it is for me (I'm no C++ dev) but if you can't figure it out, I'll take a look after work.

**Comment by nhand42** [comment]
I’m not doing anything special for EDC just relying on libcdrom. Link me the python code you’re using to generate the correct EDC. I’ll compare it with ecc_generate() and see what’s going on.

**Comment by Anuskuss** [comment]
I can't just "link the python code" because I wrote it myself and I'm not planning to publish it, but what I can tell you is that the EDC/ECC generator code is working as intended (and has been working correctly with your previous examples as well). It would be a different story if there was actual data in that two second block or if the metadata differed in any way, which is not the case here.
How can you successfully generate the auxiliary data of the first track of the high density area (3rd track overall) but fail to do so on the last track? That doesn't make any sense. Feel free to contact me on Discord though (Anuskuss#6340) so we can try to figure it out.

**Comment by nhand42** [comment]
You’re not being helpful. Stop commenting.

**Comment by nhand42** [comment]
Existing cdrom routines under lib/util/cdrom didn’t generate EDC checksum. The EDC is required when recreating the final track of TYPE_III GDROM in Redump .cue/.bin format. I’ve tested a half dozen TYPE_III discs and the output from extractcd is now byte identical to the Redump source. Assuming there are no other bugs this is now archival quality.

EDC tables and code have been taken from cdrtools which uses LGPL licensing.

**Comment by Anuskuss** [comment]
> You’re not being helpful. Stop commenting.

You could've just silently declined my offer to discuss on Discord (where I could've shared my code privately) without being a douchebag, but oh well.

> Existing cdrom routines under lib/util/cdrom didn’t generate EDC checksum.

Yeah. that was also what I was thinking because I didn't find any EDC references in the code. I still don't understand how it could've regenerated the data bit for bit on the other data tracks. I was actually trying to see for myself (it's still compiling), but I'm glad you figured it out. 

By the way, if you're interested in how the EDC LUT gets created, it looks something like this in Python:
```py
for i in range(256):
  edc = i
  for j in range(8): edc = edc >> 1 ^ (0xD8018001 if edc & 1 else 0)
  edc_lut[i] = edc
```

**Comment by nhand42** [comment]
User reported for abusive comments. Please delete your abuse and stop commenting.

**Comment by Anuskusss** [comment]
I didn't plan to comment here again because I didn't have anything useful to add (despite what nhand42 made it look like) but I had a realization today and tried to edit my last comment (to clarify what went wrong for future readers) but I'm being denied to edit my comment (and I already wrote this), so here we go:

> **Edit:** Okay, I see where the issue is now: I wrongfully assumed that chdman would strip (or zero out) the auxillary data (which is easily regeneratable as we've seen here), so obviously I was stuck thinking nhand42 made a copy-paste mistake because it was working with the previous data tracks. I suspected that they did something different with the two second data, by either having actual user data there (which would've required either some changes to the CHD format or a hacky workaround like appending it to the end of the track) or other changes that would result in the auxillary data not matching up. As this was not the case (since I did recreated the data myself), I didn't care to investigate further. Although nhand42 could've corrected me by saying that the previous data tracks did in fact not get regenerated but rather just uncompressed (I've mentioned that multiple times based on my wrong assumption), we got stuck in miscommunication. Fortunately, I did notice (and pointed out) straight away that the EDC block was missing, so in the end I think I did in fact help to figure this out.

**Comment by MooglyGuy** [comment]
Kids, the MAME project's Github is not a place to air petty grievances among parties unaffiliated with the project. If you want to throw barbs at each other, please do so on some unrelated Discord server or whatever the Zoomers are using these days. Not here.

**Pull request closed without merging**
