### PR TITLE
nintendo/n8080.cpp: Merged into single source file + minor cleanups.

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by cuavas** [comment]
Would it be better to keep the audio stuff in a separate file but devicify it?  These state classes and machine configurations are still a mess.

**Comment by 0kmg** [comment]
Dunno. Audio stuff did stick out as potentially revisable, but given my level of MAME experience and not knowing these machines I didn't consider restructuring anything and kept the changes trivial (getting rid of macros, making some system-dependent types fixed sized, etc).

**Comment by cuavas** [comment]
Probably better to leave the audio stuff in a separate file for now until it’s devicified.  It at least gives you and indication of which parts might work better in sound devices that way.

**Comment by cuavas** [comment]
This should be at least mostly covered by 04aac6dc77282224e5ee09d8a8248f33ef898e46.  There’s still some pretty sus code in there, but the sound boards are now clearly separated from the drivers and from each other.

**Pull request closed without merging**
