### PR TITLE
crt-geom-deluxe improvement

### PR DESCRIPTION
**Pull request by cgwg**
Modified crt-geom-deluxe to track the power-law fall-off for longer (up to 1024 frames). Ensured that the intensity falls to zero afterward.

Note that this is currently only compiled for GLSL. Someone with a Windows machine should generate the full set of shader targets before merging.

### CODE REVIEW

**Comment by cuavas** [comment]
Bumping this since it's been sitting open for ages, and we've had a bunch of bgfx updates lately.  Can someone set up to build all the shaders apply this?

**Comment by u-man74** [comment]
I really wanted to do this, but the problem was that nobody could remember well enough, how to compile bgfx shaders. I know, that noone gives a fuck what i say, but please, if somebody is doing this, make a small tutorial how to compile that stuff. It was not hard, as long as i remember. At least people (like me) could try to make conversions of existing shaders. I can only recommend to create a own topic for shaders on MW. From time to time, there are contributions, but they get lost in the forum.

**Comment by MooglyGuy** [comment]
`make shaders`

Alternatively, to compile a specific chain subdir:

`make shaders CHAIN=[dir]`

**Comment by u-man74** [comment]
Thanks Moogly. So easy, i cant believe that a few months ago, noone did remember this.

**Comment by MooglyGuy** [comment]
Yeah, I ended up having to go digging into the makefile. I could never remember whether it was `make SHADERS=1` or `make SHADERS` or `make shaders` or what.

**Comment by u-man74** [comment]
Somehow pity that this compiling step is needed, on the other side HLSL need that too. Maybe Firehawk could add this to the shader docs. I would like to compile this right away, but i will not be at home, for the next two weeks at least.

**Comment by rtissera** [comment]
This looks like an interesting improvement, what is missing to get it merged ?

**Comment by MooglyGuy** [comment]
Sorry, for some reason I completely forgot about this. please remind me on the 23rd of this month.

My working directory is not clean, so I cannot currently take point on this. However, once I reach a good stopping point on my HP Jornada 720 driver, I will be happy to actually deliver on this if someone reminds me.

**Comment by rtissera** [comment]
Kindly reminder to @MooglyGuy as per request !

**Comment by MooglyGuy** [comment]
Thanks! I'm nearing a good stopping point with my current changes, so I'll get to this sometime before the code freeze on Saturday.

**Comment by MooglyGuy** [comment]
The shader changes have been merged and committed, and the shaders have been recompiled and committed.

**Pull request closed without merging**
