### PR TITLE
Update sdk85.cpp

### PR DESCRIPTION
**Pull request by retrohun**
Add a15 option rom bank default mastermind image and bios empty rom image by NASZVADI Peter

### CODE REVIEW

**Comment by retrohun** [comment]
A small blogentry related to these changes:
https://github.com/retrohun/blog/tree/master/dt/intelmcs85tales
Any opinions, suggestions, participants are appreciated and kindly welcome!

**Comment by Tafoid** [comment]
Please make arrangements to submit missing image(s) needed to use this in MAME.  Use the email provided at this link to send for verification:  https://wiki.mamedev.org/index.php/Submitting_Source_Code

Thanks!

**Comment by Pernod70** [comment]
There are issues with this PR and don't believe it should've been merged in it's current form.
Problems:
- It adds a fake ROM containing all zeroes.
- Is this version of mastermind a worthy inclusion, and why ROM_LOAD_OPTIONAL?
The option ROM would probably be better supported as a GENERIC_SOCKET, then user can load any option ROM they like. If mastermind is worthwhile it could then be softlisted.

**Comment by retrohun** [comment]
> Please make arrangements to submit missing image(s) needed to use this in MAME. Use the email provided at this link to send for verification: https://wiki.mamedev.org/index.php/Submitting_Source_Code

Sure. Source and/or compiled form needed? Because I already pasted the mastermind.a15 in text-hexdump format in my so-called blog here:

https://github.com/retrohun/blog/tree/master/dt/intelmcs85tales

License: I do not care, BSD-ish, MIT, GPL, whatever you and the MAME developer community like if there is no default option. If there would be any questions, may I ask?

Thanks in advance!

**Comment by retrohun** [comment]
> Problems:
> 
>     * It adds a fake ROM containing all zeroes.

I haven't seen in any kind of WoW that states that use of constant valued flat rom images is an antipattern. Default empty ROM slot values usually initialized as 0xFF (RST 38H) statements AFAIK, which is unwanted in some certain situations.

> 
>     * Is this version of mastermind a worthy inclusion, and why ROM_LOAD_OPTIONAL?

Why not? Most end-users usually cannot obtain easily rom packs, and a missing mandatory image would be a showstopper. Getting some of the images seems to be chaotic in my "bubble".

> The option ROM would probably be better supported as a GENERIC_SOCKET, then user can load any option ROM they like. If mastermind is worthwhile it could then be softlisted.

Hmmm. I'd dug deep on rom/arch defining macros, and probably missed those generic socket solutions - sound useful. However, it would be better committed in an another PR. As owning 2 such evboards, it is risky to change roms regularly in main slot, especially the nowadays unobtainium 8355 ROM containing the original monitor.

Misc. remarks, elaborating my motivation:

Basically I altered and fixed the rom image developed by a MAME contributor who made an sdk85.cpp patch before. In a separate change, I think it would worth to patch the .a14 image to let it use default rAm bank only implying changes in the checksums - reasons: almost no one used the secondary 8155 slot (lack of spare parts). Mastermind.a15 already uses 0x2000..0x20FF RAM area only (see it in my blog, link in previous answer). The MCS-85 had been common an popular some decades ago in EMEA, among college/secondary school students. Even limited 4k BASIC ports existed allegedly using the serial interface as a terminal connection, which is also a missing feature for this emulated machine at the moment AFAIK. I also planning to port some limited games (chomp, nim, nibbles, donkey stick etc.) and making teensy demos in option rom slots and use it with my boards - MAME would be an excellent testing platform for it! :)

Thanks for the observations and remarks!

**Comment by cuavas** [comment]
We're trying to get to a point where `ROM_LOAD_OPTIONAL` is can be removed, and even without removing it, this isn't what it should be used for.  This is abusing the system ROM definition to load homebrew software.  If the system has a slot for an expansion ROM mapped at 0x800, use an image device for it.  If it's a more flexible I/O port, make a slot/card system for it.

I agree with the objections raised by @Pernod70 - this will be reverted.

**Comment by ajrhacker** [comment]
As of 4e0540d25b71f151616d5e0be2752269896080b4, `mastermind.a15` has been readded as a softlisted image.

**Comment by zx70** [comment]
I'm surprised you needed such workaround,  I didn't remember I sent a copy to Robbert, but it is nice to have it integrated.
Be aware if the fact tha Paolo Forlani wrote his game for his own computer board named PICO in 1976 (hobby stuff, just few articles on a magazine ..perhaps few kits?), as soon as the display+keyboard conntroller was available.  The SDK85 came an year later.
The PICO was close to SDK85 but the wiring of the keys and display were different.  mastermind.a15 is a conversion of my own, I still have the sources and we might either to fix them the way you prefer or to add the emulation of the pico in the 2 keyboard configurations which were available at the time (less keys for mastermind, few more for the monitor rom).

**Pull request merged**
