### PR TITLE
new NOT WORKING machines  (Plug and Play)

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING machines
-----
Mini Arcade Console (Arcade 10-in-1) [Team Europe]
Arcade Classics Mini Handheld Arcade (Supreme 150) [Team Europe]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
Note the is the ST2X hardware stuff.  As it seems we couldn't agree a good way to integrate changes into the core, I've just moved most of them to the driver for the time being, so that it's easier for me to maintain.  With things done this way the only change needed in the core is the DMA hookup.

`
void st2205u_base_device::dcnth_w(u8 data)
{
	m_dcnt[m_dctr >> 1] = (data & 0x7f) << 8 | (m_dcnt[m_dctr >> 1] & 0x00ff);

	// start DMA
	int source = m_dptr[0];
	int dest = m_dptr[1];
	int length = m_dcnt[0] << 1;

	address_space& mem = this->space(AS_PROGRAM);

	for (int i = 0; i < length; i++)
	{
		uint8_t byte = mem.read_byte(source);
		mem.write_byte(dest, byte);
		source++;
		dest++;
	}
}

`

which I'll move to a separate pull request.

**Comment by cuavas** [comment]
Could you ping @ajrhacker about it?  I really wanted his review on that stuff.

**Comment by DavidHaywood** [comment]
I've been getting no response, which is why I've moved everything out of the code he'd done and into my own code until something can be decided.

**Comment by DavidHaywood** [comment]
I'll try again anyway @ajrhacker can this go in? (and maybe even the small DMA part, as I really don't fancy moving that to the driver, too ugly)

Things can be moved around / shuffled around as needed at a later date. once we figure out where the pieces go  This is now minimal impact on your side of things but it's much easier for me to work with (and try to convince other people to send us other units) if this is in the source and can run in some form.

**Comment by DavidHaywood** [comment]
@cuavas  I've now created the separate PR with the DMA part required for this to function.  at this point I have no idea what else to do.

**Comment by DavidHaywood** [comment]
can these two be merged? @cuavas   I don't mind AJR taking his time to improve things beyond this in his own time, but the original PR is 2 months old at this point, but there's nothing more I can work on, and I've reworked this so that the changes are going to have 0 impact on anything outside of this driver (if anything relied on the DMA before it wasn't going to work anyway)

I've got people asking me every week when this is going to be merged, and I can't give them an answer.

**Comment by DavidHaywood** [comment]
Well somebody who was going to supply some other units has now decided otherwise....

**Comment by DavidHaywood** [comment]
OG indicated he was ok with these (including the DMA part) in the shoutbox.

**Comment by cuavas** [comment]
OK, this one is self-contained and should be relatively simple to improve upon.

**Pull request merged**
