### PR TITLE
This changes device_image_interface::filetype() to return 'const std::string &' instead of 'const char *'

### PR DESCRIPTION
**Pull request by npwoods**
In the interests of removing burdens from client code, I also changed the following:
- filetype() will always return the file extension in lower case
- device_image_interface::filetype() will return the correct extension for files loaded as a part of softlists
- The code for extracting a file extension is now encapsulated in core_filename_extract_extension()

Client code has been updated

### CODE REVIEW

**Comment by cuavas** [comment]
Sorry but converting to lowercase and then doing a literal compare is not safe when Unicode is involved. I realise core_stricmp is not Unicode-aware yet, but in principle, having a function that does a non-literal comparison is the right approach.

**Comment by npwoods** [comment]
While it may normally be incorrect to perform case insensitive string compares this way, this is fine for this application.

device_image_interface::filetype() is all about file extensions.  Every single scenario where this is used it is to compare against a specific file extension (e.g. - "dsk").  Arguably in the general case using anything other than 7-bit ASCII for file extensions is somewhat perverse as well.

While technically speaking the case sensitivity of file extensions is up to the platform (e.g. - *.c being a C file and *.C being a C++ file), this doesn't happen in practice in the world of emulation.

**Comment by cuavas** [comment]
It's the principle of the thing. I still don't believe in taking shortcuts that just happen to work at the moment for a given application.

**Comment by npwoods** [comment]
Do you have any specific recommendations?  The goal is to make it so that drivers only need to check against "dsk", and preempt the inevitable scenarios where drivers are inconsistent with how they check strings.

Arguably, if filetype() discovers a file extension that is not 7-bit ASCII, it should reject it and return an empty string.  Would that be sufficient?

**Comment by cuavas** [comment]
I disagree with anything that takes us further from treating any Unicode character as just another character.  The way forward is to do no more normalisation than potentially converting to NFC, and then having string comparison functions that accept nonliteral and case-insensitive flags.  Ultimately we need better Unicode support all through MAME, not hacks that take us further from that.

A very simple example of not wanting to drop non-ASCII characters in an extension is for error messages, e.g. ".über is not a recognised image file extension.  Recognised extensions are .foo and .bar."  Same goes for forcing lowercase, you should always preserve the original case so you can present it unadulterated in messages.  That's before you get into characters that have no uppercase form or no lowercase form (e.g. the eszett ß has no uppercase form so doing case conversion on it is lossy and not round-trip symmetrical).

**Pull request merged**
