### PR TITLE
Updated cdi.xml hashes for TOSEC disks

### PR DESCRIPTION
**Pull request by danifunker**
chdman changed since the chd hashes were taken. This is an update for about 200 disk hashes.

See issue #2517

### CODE REVIEW

**Comment by Robbbert** [comment]
@Tafoid are you happy with this?

**Comment by Tafoid** [comment]
I have no idea.  Have no been provided any images to check or compare for this commit.  It can sit until someone who has knowledge of the system can speak up to what is being done especially since it is a wholesale change of so much.

**Comment by danifunker** [comment]
I used the images referenced in the xml (verified all hashes) and regenerated the chds. The reason there are so many changes is because a lot were never changed since the initial merge between mess/mame- however the chd checksums are different as of ~2016 due to the new metadata bit introduced around 0.165

**Comment by danifunker** [comment]
Who can I talk with about getting this into an upcoming release? Thanks in advance,

**Comment by ajshell1** [comment]
I just discovered this same issue while  attempting to compress my newly-dumped CD-i images, and  I can verify that @danifunker has the correct checksums (at least, my limited subset of discs that I own match his).

Considering that MAME is arguably the best CD-i emulator (or at least the best open-source CD-i emulator), I think this should be given a higher priority.

**Comment by Tafoid** [comment]
With the help of a couple of very kind individuals, I was finally able to finally obtain updated CHD and confirm the hash changes posted to this PR.

**Pull request merged**
