### PR TITLE
powervr2.cpp: implement opaque polygons

### PR DESCRIPTION
**Pull request by snickerbockers**
PowerVR 2 treats opaque polygons as a separate class of polygon from transparent polygons.  Pixels rasterized from opaque polygons are always completely opaque regardless of what their alpha values are.

This PR resolves missing graphics in games which render opaque polygons with non-opaque alpha values.

There's also a third class of polygon called punch-through, which supports transparency but not blending (so every pixel is either entirely opaque or entirely transparent).  Those haven't been implemented, and are still being treated as if they were transparent polygons.

Before:

After:

Before:

After:

### CODE REVIEW

**Comment by MooglyGuy** [comment]
This is awesome! Thanks so much for looking into these PVR2 issues!

**Comment by Hydreigon223** [comment]
Any differences in performance/speed after these implementations for powervr2?

**Comment by happppp** [comment]
@Hydreigon223 could you please change your profile name "?" to something else? A nickname like "Hydreigon" is fine. It shows up as "?" in notifications now.

**Comment by snickerbockers** [comment]
@Hydreigon223 <https://github.com/Hydreigon223> It's possible that this may
make certain games faster because it doesn't have to blend every pixel
anymore, but on the games I tested there was no discernible change in
performance.

**Pull request merged**
