### PR TITLE
atari/a7800.cpp: Pass (phase 2) clock to cartridge slot. Fixes PAL add-on chip clock rates.

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by happppp** [comment]
You have a signed int for the xtal now, better use the XTAL object here: https://github.com/mamedev/mame/blob/master/src/emu/xtal.cpp (and h file)

The PAL one would need to be added to xtal.cpp then, it's an XTAL known to exist but not in the list yet:
14187580

**Comment by happppp** [comment]
And if m_xtal is only used in the machine config, you could pass it as a function parameter instead:
void a7800_state::a7800_common(machine_config &config, const XTAL clock)

**Comment by 0kmg** [comment]
Yeah, I didn't use XTAL because I wasn't sure if it was ok to add them to xtal.cpp.

**Comment by happppp** [comment]
@0kmg sorry, scrap the xtal.cpp change

**Comment by 0kmg** [comment]
People think the Y1 in the PAL schematic is an error. They say it's the same as the XTAL in the PAL XEs. There it listed as part C070034, 14.187576 MHz.

**Comment by 0kmg** [comment]
I scrapped the xtal.cpp, implemented the other advice, and went back to using Y1's of 14'318'180 and 14'187'576 for the time being.

**Comment by happppp** [comment]
I did more googling and yes, it's a 14.187576MHz xtal, so the one in schematics must be an error.

**Pull request merged**
