### PR TITLE
split some of the more enhanced vt chipset sets out of nes_vt.cpp so that the emulation can be developed from scratch [David Haywood]

### PR DESCRIPTION
**Pull request by DavidHaywood**
(the hope here is that this will make them easier to understand)

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
Please use a descriptive name.  “Newer” is unhelpful.  Newer than what?  What’s a defining feature for the ones that belong in the other source file?  What’s the baseline?

**Comment by DavidHaywood** [comment]
I don't know.  I used newer because they need additional research and are clearly newer.  Stop nitpicking.

**Comment by DavidHaywood** [comment]
closing due to nitpicking, work on these is abandoned.

**Comment by cuavas** [comment]
Look, to be blunt, you need to improve the quality of pull requests.  You’re slipping back into opening pull requests for changes that aren’t ready, adding stream-of-consciousness commits, and then saying “merge my pull request” elsewhere.  You should open a pull request when you have something ready, and you can describe what it affects, and what changes it makes.

But that aside, my issue with this PR is that it *doesn’t* make it clearer at all to split things into “NES VT” and “NES VT newer” without giving any defining characteristics for what defines a “newer” system.  It’s just two arbitrary buckets instead of one, and the next person to look at it is going to be at least as confused as they would be with them all in one file.

**Comment by DavidHaywood** [comment]
That is because I'm trying to research and work out what those defining characteristics are.  They access things not in the memory map for any VT system documentation we have, so seem to be using non-nes modes in addition to the NES ones (again, nothing documented can do this)

There's claims that some of these are VT268, but nothing they're doing aligns with 268, one of the PCBs says 368, but maybe that needs a further split later.

For now they're newer, that's all I know.  Anyway, as I said, I'm abandoning this, I've been putting off splitting them for months now because I know researching them fully is going to be a painful experience, and frankly if you're going to nitpick over me calling them newer then somebody else can take that pain, I'm happy to just forget these even exist.

**Comment by DavidHaywood** [comment]
Essentially I'm trying to research things here.  I'm not asking for special treatment, I'm saying this is the extent of my knowledge at the moment.

This is after months of poking around in the driver, observing little things like the way these turn off the IRQ, but still need it, register accesses that don't make sense in the context of a VT system, but still observing that you can extract and boot individual VT based NES hacks from many of these, meaning it must still have some kind of VT mode.

This is after noticing that even if I try and work blind the games often ending in jumping to nowhere, which makes me doubt the confirmed banking the VT uses, possibly changed, possibly scrambled, I don't know, but the current code is trusted and shouldn't be changed / hacked.

I can't name the file nes_vt_turns_off_nmi_strange_accesses_to_41xx_area.cpp

I can't research them in place easily without messing up existing code - I'm not going to add hacks to ignore the NMI disable so that I can research to see if the video makes sense, I'm not going to hack up / disable banking writes.

Essentially you're coming along, with no knowledge of the situation and basically telling me "you're researching this wrong" when in reality this is the only way I can research it.  This is why I'm cancelling research on these.  Somebody with research techniques that align more to your liking can start the entire process again (and likely conclude the same things I did)

Not everything is known in advance, a lot of MAME work is guesswork, doing one thing, realising it's wrong, doing another thing, realising that's wrong, learning from that experience, trying again.  In this case my current conclusion is that these need research outside of the established driver, maybe that's correct, maybe that isn't, maybe some of these are different again.  These are all facts that need to be established.

If developers can't research, then progress can't be made outside of things that are already fully documented, which outside of already well documented components is never the case.

I stand by calling this _newer, because actually naming a chip type, when none of the profile actually align, and even that is speculation, seems worse than just using a term that gives a rough idea of a relationship between these and the base.  I'm not going to argue the case for this any more however.  I accept that you're not happy with this, but it also leaves me in a position where I have no choice but to move on.

**Pull request closed without merging**
