### PR TITLE
sound/2612intf.cpp : Add YMF276 device, Clamp output related to internal 9-bit DAC, Add notes

### PR DESCRIPTION
**Pull request by cam900**
fmtowns.cpp : Add notes for sound chip

### CODE REVIEW

**Comment by Lord-Nightmare** [comment]
This patch isn't correct. The YM2612 and YM3438 do have a 9-bit DAC, but it is time-division-multiplexed to produce all 6 channels in sequence, with the blending between channels done either by external filtering and human perception.

The existing code in /src/devices/sound/fm2612.cpp lines 2277-2289 (inaccurately) mixes together the 6 channels into two samples (one for left and one for right outputs), while this patch just clamps the final output to 9 bits.
A more correct patch would clamp the channels to 9 bits in fm2612.cpp before they are mixed together.
An even more correct patch would clamp the channels to 9 bits in fm2612.cpp, and output the channels sequentially, instead of mixing them together at all.

Note that the behaviors of other OPN-series chips are different:
The YM2203/OPN mixes the channels internally (12-bit?) and uses an external serial DAC.
The YMF276/OPN2L presumably does the same as the YM2203, except it may use an external stereo DAC (?)
The YMF288 OPN3 and YMF297 OPN3L/OPL3L I'm not sure what their behavior is, they're used on some PC-9801 cards. These need testing or research.

**Comment by cam900** [comment]
Some Later FM Towns II models use YMF276; That is YM3438 compatible and low voltage variation but needs external DAC;

**Comment by Tafoid** [comment]
This update is causing severely distorted sound for at least the following drivers/machines:
megadriv.cpp
megadrive_abcl.cpp
segac2.cpp
segas32.cpp (arescue, radm)
segas18.cpp
segam1.cpp
puckpkmn.cpp
megatech.cpp
megaplay.cpp
segaufo.cpp

I'd suggest reverting until fixed.

**Comment by galibert** [comment]
Beware that the even more correct chip would require seriously upgrading
the downsampler we currently have...

  OG.

**Comment by rb6502** [comment]
@galibert Yes, actually emulating the time-division multiplexing would be catastrophic with our current downsampler.  Individually clamping the channels to 9 bits and then mixing as LN suggests would be a better compromise.

@cam900 please fix the distortion or this will be reverted.

**Pull request merged**
