### PR TITLE
New NOT_WORKING machines

### PR DESCRIPTION
**Pull request by clawgrip**
------------------------------------
Covidarts [Vicente y Sergio de electronicaVyS]
Minidart [jordigahan]

Also identified 'prospdp' as another set of 'Diana Bifuca'

### CODE REVIEW

**Comment by cuavas** [comment]
COVID darts?

**Comment by clawgrip** [comment]
> COVID darts?

Not the best name nowadays...

**Comment by clawgrip** [comment]
@ajrhacker I've added a newer set (Minidart) on a newer Microdar PCB revision, the V6.
This one replaces the Compumatic custom REF34VA by a regular Atmel MCS51 MCU. I've not added the ROM fills you did because I cannot tell if the internal ROM on this Atmel matches the one on the REF34VA.

**Comment by Tafoid** [comment]
The added machine 'minidart' is missing.  Unless I'm mistaken, this hasn't shown up yet.  Please send that data along.

>minidart: Unable to find matching ROM minidart_v0.00.ic3 (5ab9f755)

**Comment by clawgrip** [comment]
Sent to TDU!

**Pull request merged**
