### PR TITLE
Tweak NWK-TR's inputs

### PR DESCRIPTION
**Pull request by Hydreigon223**
"Clutch pedal" may as well be assigned to 'player 2' because wiring schematics from various manuals state that and it's an optional input specific to the DX version.

### CODE REVIEW

**Comment by angelosa** [comment]
It's not player 2 tho, and **hand** brake isn't a **foot** pedal.
I also don't see any option to disable clutch/select cabinet type in any game on this driver that allows to enter into test mode (i.e. doesn't throw a HW error). Is it a not hooked up bit?

Other input issues in this driver:
- `IPT_SERVICE `mapped as `KEYCODE_7 `is ugly, should really be `IPT_SERVICE1 `and without the `PORT_CODE` macro def.
- `Skip Post` is mispelled, should really be `POST `in all caps

**Comment by cuavas** [comment]
I don’t these changes in ranges without more supporting evidence.  It’s also not for a two-player cabinet, so the change doesn’t make sense.

**Comment by angelosa** [comment]
Think they are actually right, anything beyond 0x7ff goes out of max bound in test mode. Unless of course the factory default is somehow busted and needs a sensible inited NVRAM

**Comment by Hydreigon223** [comment]
> It's not player 2 tho, and **hand** brake isn't a **foot** pedal.
> I also don't see any option to disable clutch/select cabinet type in any game on this driver that allows to enter into test mode (i.e. doesn't throw a HW error). Is it a not hooked up bit?
> 
> Other minor issues in this driver:
> 
> * `IPT_SERVICE `mapped as `KEYCODE_7 `is ugly, should really be `IPT_SERVICE1 `and without the `PORT_CODE` macro def.
> * `Skip Post` is mispelled, should really be `POST `in all caps
> * `racingj2` & `racingj2j ` aren't clone of `racingj`, by definition.

The problem with a Hand Brake lever is the fact it functions more like a pedal as opposed to a stick hence why it's mapped as a pedal in gticlub.cpp. Why I had to map the clutch pedal as player 2 was because there is currently no implementation for any pedal value beyond 3 so implementing this as an "IPT_PEDAL4" won't work. All the other minor changes I will keep noted (because they were like that as far as I remember) if someone reopens the PR again. I think racingj2 was a clone of racingj initially because some roms are shared between racingj and racingj2.

Also, the cabinet type is determined by the timekeeper (sadly) meaning if one wants to change the cab type from Twin/SD to deluxe, they'll have to change the contents. The second byte in the timekeeper specifically determines the cab type: (GM676 = SD/Twin; GN676 = DX). All games use the same sixteen byte string from the original Racing Jam. This is because the later games were released as conversion kits for Racing Jam without having to replace the timekeeper. This explains why an X76F041 was added to the network board so it could be used to check the overall game and region ID. Sadly any Racing Jam Chapter 2 and Thrill Drive owners are stuck with whatever cab type and region is stored on the X76F041 while with Racing Jam, it's possible to change the region and cab type safely (given they adjust the 16-byte checksum at the end to match the current timekeeper's contents).

**Comment by Hydreigon223** [comment]
[racingj_timekeepers.zip](https://github.com/mamedev/mame/files/6681083/racingj_timekeepers.zip)

And here they are all tested in mame. There are eight timekeeper images total specifying the four regions (J, E, A and U) and the two cab types for each region (GM676 and GN676). Please go test them accordingly.

Thanks

**Comment by villedevs** [comment]
Might make sense to add IPT_LEVER or something (positive axis only, non-autocentering). There's a few other games that could also use it.

**Comment by cuavas** [comment]
Does a paddle with the default at one extremity not achieve that?

**Pull request closed without merging**
