### PR TITLE
Revert "AtariGT: Add Primal Rage v2.3 Japanese"

### PR DESCRIPTION
**Pull request by cuavas**
Reverts mamedev/mame#10301 - this is hoarded by a well-known hoarder.

### CODE REVIEW

**Comment by simzy39** [comment]
But Lemon-King dumped it from their own board.

**Comment by cuavas** [comment]
> But Lemon-King dumped it from their own board.

 The ROMs are hoarded. We have no way to even verify the digests.

**Comment by Lemon-King** [comment]
I replied to you and didn't hear anything back, as you were asking where to find them.

"These files are not available online. AFAIK, only Galloping Ghost Arcade and myself have the board. "

**Comment by Lemon-King** [comment]
I was hoping to hear back via email as to how I should proceed, as this was my second arcade board and first I've come across where MAME has not recognized it - and first submission.

**Comment by simzy39** [comment]
@Lemon-King 
This is the page on how to submit code or new data (roms, etc.) to Mame: 
https://wiki.mamedev.org/index.php?title=Submitting_Source_Code

Thank you for submitting it. I'd love if you can submit the other board of yours too.

**Comment by Lemon-King** [comment]
The other board is a very common Primal Rage v2.3.

I didn't know that subpage was working again, the last time I tried to access it I was receiving server errors.

**Comment by simzy39** [comment]
@Lemon-King How did you go with the submission?

**Comment by Lemon-King** [comment]
> @Lemon-King How did you go with the submission?

Never heard back.

**Comment by simzy39** [comment]
> > @Lemon-King How did you go with the submission?
> 
> Never heard back.

hap is saying your rom submission isn't relevant. When you check your roms, are they different than the ones in Mame?

**Comment by Osso13** [comment]
Hashes are the same.

**Comment by Lemon-King** [comment]
> > > @Lemon-King How did you go with the submission?
> > 
> > 
> > Never heard back.
> 
> hap is saying your rom submission isn't relevant. When you check your roms, are they different than the ones in Mame?

Using romident, it returned no match on the dumped roms.

**Comment by simzy39** [comment]
> Not relevant, because: [fdc062f#commitcomment-85605427](https://github.com/mamedev/mame/commit/fdc062f19860616d1a0518818bb8cdd781e5c998#commitcomment-85605427)

@happppp Are you sure they don't have another set? Their roms don't match what's in Mame

**Comment by happppp** [comment]
Compare the checksums of this one vs Guru's dump.
1 difference I'm not sure how much it matters: In Guru's dump, the 2 sound roms ("cage" region) are not the same. In Lemon-King's dump they are the same as the other 2.3 set (already in MAME).

**Pull request merged**
