### PR TITLE
cop01.cpp: unknown dip switches enable an undocumented invulnerability cheat (MT#8132)

### PR DESCRIPTION
**Pull request by scoomby**
Both DIP switches need to be set On to enable the undocumented invulnerability cheat.  Added a Fake dip switch so both DIP switches are set from a single input on the UI.  Both COP01 original and clone have been fully tested including loading and saving.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I think this is too convoluted of an approach, better just to mention in the switch description that both are needed if they're in different ports

**Comment by scoomby** [comment]
> I think this is too convoluted of an approach, better just to mention in the switch description that both are needed if they're in different ports.
> 
> That said, unless I'm missing something, in this case it's not even that complex, and you could just use both bits, with 3 states for 'off' and one for 'on'
> 
> Either that, or if there are other dips that change meaning when the debug one is one, use the conditional system to change their descriptions.

Thanks David.

The 2 off DIP switches are in different ports "DSW1" and "DSW2".  I went down the Fake port route so that it is easy for anyone to enable and disable the invulnerability with a single input on the UI.  I have seen the Fake port approach used similarly in other drivers (e.g. sag.cpp).

**Comment by scoomby** [comment]
Hi David.  I have removed the Fake DIP switch as advised.  I was definitely over thinking this one!!  Does the change look OK now?  Thanks in advance

**Review by cuavas — CHANGES_REQUESTED** [review]
Definitely not going to fly like this – it’s incompatible with adding DIP locations and making the DIP switch display clickable.

**Comment by scoomby** [comment]
> Definitely not going to fly like this – it’s incompatible with adding DIP locations and making the DIP switch display clickable.

No problem at all.  I was just trying to do something smart when I should have kept it simple!!

**Comment by happppp** [comment]
Simply do:
Invulnerability (Cheat, 1/2)
Invulnerability (Cheat, 2/2)

and a // comment saying you need to enable both to take effect

**Comment by scoomby** [comment]
> Simply do: Invulnerability (Cheat, 1/2) Invulnerability (Cheat, 2/2)
> 
> and a // comment saying you need to enable both to take effect

Thanks happppp.  I was going to do something like that

**Comment by happppp** [comment]
Ok

**Pull request merged**
