### PR TITLE
new MESS driver support for spc1500 from Samsung Electronics in 1987

### PR DESCRIPTION
**Pull request by meesokim**
Samsung SPC-1500 driver by Miso Kim

2015-12-16 preliminary driver initialized
2015-12-18 cassette tape supported
2015-12-26 80/40 column mode supported
2015-12-28 double access mode supported for I/O 
2016-01-02 Korean character input method and display enabled
	
TODO:
- Recover color palette after list and width command in basic mode
- Support user defined char setting
- Support floppy disk drive with SD-1500A controller card

### CODE REVIEW

**Comment by mamehaze** [comment]
please send things like roms / other binary files separately, not as part of the pull requests.

**Comment by mamehaze** [comment]
actually there are a lot of things in here that shouldn't really be in the pull request (subtargets, misc text files, python scripts in the rom folder etc.)

**Comment by meesokim** [comment]
Yes, I've made an issue with ROM binaries and the driver source code with some modified files.

**Comment by meesokim** [comment]
I will close this merge request.

**Pull request closed without merging**
