### PR TITLE
Fixed readonly cassette formats

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by etabeta78** [comment]
Was really necessary to lose the capability of creating a new .wav image by
just launching mame with the new filename? I think it was a great feature
that helped a lot testing from command line and I don't understand the
problem behind this chance.

 Fabio


On Sunday, August 21, 2016, Scott Stone <notifications@github.com> wrote:
> Merged #1278.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Y8wCK8NyE5o1nY8Zzl9GY4OCxSS2KMrlCl_J1Bb8gYYtCyCvh4__RgvUHkJ1kO0iP6Re2WKhAAd6MhI9i5MzE7pCKVFHu-ctLRQYldrOqYYDgRD3KuXKYWSCBiJ4YHwMkE0s_gw5E-0ZZgcwovjtqPUeYQnmGg=s0-d-e1-ft#https://github.com/notifications/beacon/AI0qvC5PuBboWV1yH_epUxmmfEYdNO0Lks5qiIk0gaJpZM4JpNg7.gif>

**Comment by etabeta78** [comment]
Chance --> change (stupid smartphone corrector).


On Monday, August 22, 2016, Fabio Priuli <doge.fabio@gmail.com> wrote:
> Was really necessary to lose the capability of creating a new .wav image
by just launching mame with the new filename? I think it was a great
feature that helped a lot testing from command line and I don't understand
the problem behind this chance.
>
>  Fabio
>
>
> On Sunday, August 21, 2016, Scott Stone <notifications@github.com> wrote:
>> Merged #1278.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Y8wCK8NyE5o1nY8Zzl9GY4OCxSS2KMrlCl_J1Bb8gYYtCyCvh4__RgvUHkJ1kO0iP6Re2WKhAAd6MhI9i5MzE7pCKVFHu-ctLRQYldrOqYYDgRD3KuXKYWSCBiJ4YHwMkE0s_gw5E-0ZZgcwovjtqPUeYQnmGg=s0-d-e1-ft#https://github.com/notifications/beacon/AI0qvC5PuBboWV1yH_epUxmmfEYdNO0Lks5qiIk0gaJpZM4JpNg7.gif>

**Comment by Tafoid** [comment]
Perhaps we should add a direct command line to allow for explicit image creation.  We can already create one using the internal UI.. perhaps something as simple as -createimage (filename) would be sufficient.

**Comment by etabeta78** [comment]
OTOH, I think the approach we supported since the dawn of MESS until past
release was quite solid and very intuitive: if you launched a driver with
-cass newfile.wav, a blank wav file was created and written to when the
emulated system wanted to save anything to tape, unless you launched from
softlist in which case a (ghastly) hack ensured that no blank images was
created
why do we need a new option, which would require more command line typing,
when the old approach just worked?
why was this feature drop necessary, without any discussion about its
desirability? which was the problem requiring the feature to be removed?
when we remove something that it is mentioned to be supported in the
documentation (for sure MESS user's manual explicitly suggested this
approach to create blank files, even if I'm not sure if this bit was picked
up by Firewave for MAME docs), there should be at least some clear
exposition of the problem which caused the removal, otherwise we just seem
to arbitrarily make users' life more complex...

   f.

**Comment by cuavas** [comment]
See this is why I didn't want to merge this PR.  Rather than simply fixing the regression, it carried a whole lot of other changes with it, and we don't know what other regressions it might have introduced, in addition to this change in behaviour.

**Comment by mamehaze** [comment]
I think the idea of automatically creating a wav file with "-cass newfile.wav" is flawed anyway tho

Tapes have sizes, fixed sizes, they're not (and should not be treated as) some kind of expanding entity or something like that.  You should have a fixed size tape, and be able to fast forward / rewind to any position it it, and start recording there.

I don't see how "-cass newfile.wav" in any way allows you to specify a size.

It  just feels a bit hacky.  In reality a cassette, a floppy, a hard drive, or a CD-RW aren't really too different and so should have a more standardized way of being created.

**Comment by galibert** [comment]
Right, so you're saying any tape file should be 450Megs.  Are you nuts?

  OG.

**Comment by mamehaze** [comment]
more along the lines that our native output format should probably be something like CHD, with the option to convert to wav if wanted.

tapes are of a fixed size, and you can ff / rewind to any position in them and play / record from there.

the way we do it is a poor representation of  a tape.

**Comment by npwoods** [comment]
Whether or not the old functionality for creating an image from the command line is desirable or not, the way that it was implemented was terrible.

Loading images at the command line is done through device_image_interface::load().  That method should only load images, not create them, and it just so happened that it supported creating images by accident for some device types.

**Comment by etabeta78** [comment]
Quite the opposite: I support the merging of the code to try and fix the
regression, my issue with this commit is that it is not explained in the
log why a feature was removed. Did it interact badly with some other code?
Did it only worked for tapes and not for disks? The commit does not tell
anything and thus other contributors are given no chance to know the
reasons behind it, and/or if a patch restoring (in a better way) the
support for it would be accepted.
I don't care if the whatsnew becomes two pages long, but I strongly believe
that explaining changes should always be preferable to not explaining
them... alienating possible external contributions with cryptic messages
that don't explain the reason behind such changes is not really a direction
I think MAME shall follow.


Back to this specific change, there might be the need for a per-format flag
that tells the emu whether a format supports creating a new image from
command line or not, or we might decide for some other workaround that
allows removing the old very bad check for softlist loading. In both cases,
a discussion on the behavior shall be done :)

   f.

**Comment by etabeta78** [comment]
Previous code was not creating by accident the images. By design, it was
checking if the format supported creation and if the loading was happening
from fullpath (as I had explained in a previous email): if both conditions
were met, then an empty file was created, ready to be filled with data by
the emulated system, with the appropriate number of data block required by
the system.
As such the problem was that load() had actually been implemented as
load_or_create(), but I don't think it is fine to just drop the latter part
to comply with the function name.

The real point anyway is that I think MAME shall create an empty file
whenever the image device support file creation: for tapes a .wav file
shall be created, for disks an empty .mfi flow would be desirable. I know
that currently disks don't work like that, but I still haven't become
familiar enough with the floppy code to add the few improvements I'd like
to make (after OG's review)...


     f.

**Comment by npwoods** [comment]
I feel that there are two distinct issues here:
1. Whether it is desirable to automatically create images from the command line when an image does not exist
2. Whether load() really was load_and_create()

I'm pretty much neutral on #1, but I have a very strong opinion on #2.  Whether or not it was called load() or load_and_create(), the behavior in practice was a pretty bad design pattern.  While the cassette behavior was "load and create", it was done extremely inconsistently across MAME.  It shouldn't be up to devices to do something extremely arbitrary like checking checking to see if a file is zero length.

What I'm trying to do is clean things up so that device code doesn't have to do sloppy things.  You can see this in pull request 1290; the cassette code did something very sloppy (and undefined according to the C++ standard) when softlists were involved.  Better to fix the problem in the core than leave it up to individual devices; I'm perfectly happy to clean up the fallout when the inevitable regressions happen.

Again while I'm neutral on #1, if we do want the ability to create images from the command line, it really needs to be done in a more consistent way.  It would be quite easy to do so in fact; just detect file not found in image.cpp and invoke create()

**Comment by andrew-gardner** [comment]
As far as #1 goes, I'm a proponent of creating as few surprises as possible
in a program's execution.  "Explicit rather than implicit."

A surprise in the case of #1 would be a person expecting a wav file to be
present, typing in a cassette name, misstyping it just a bit, and MAME
happily continuing to create its own wav file with that misstyped name
without mentioning it to the user.  It's possible the user would use the
machine for a long time before s/he realized their mistake.  This would be
a surprise, and potentially an unpleasant one.  If there were an explicit
flag that said something like -createtape, then there would be no surprises.

Apologies Fabio, but this is just something I've found over the years to be
a useful paradigm to follow.
/Andrew

**Pull request merged**
