### PR TITLE
Improve wofpic and other misc bootleg stuff

### PR DESCRIPTION
**Pull request by TwistedTom**
Improved new wofpic set, playable now, still some minor gfx issues (not using values from main ram this time!)
Redump bad wofpic,wofabl gfx rom
Load wofpic,wofabl gfx roms properly instead of rearranging in init
Make some of the bootlegs not use the brightness values as some don't have the h/w for it on the real pcbs (the 74ls07's and resistor arrays/dacs are unpopulated)

### CODE REVIEW

**Comment by Osso13** [comment]
So both dumps had the same ROM badly dumped in the same way?

**Comment by TwistedTom** [comment]
> So both dumps had the same ROM badly dumped in the same way?

I'm not sure if the gfx were re-dumped for the new set or copy/pasted from the older set? I assumed the latter but if we can confirm the bad rom from 2 different boards we should stick with that but hard to imagine they sold boards like that, even a bootleg!

**Comment by Hammy1986** [comment]
I dumped 2 of the mask roms and they matched (also mask rom marking match in the pictures) and copied the rest over to save 3 hours of time... The original dumped (nonPIC-based) is long gone sadly but can redump this no problem.

Tom, you are more than welcome to contact me on hammyxboxlive@gmail.com if you need any info / pics regarding any of my new dumps (i don't check the comments in here) we also need to get the SF2 PLD's sent over to you for analysis. -Carl

**Comment by TwistedTom** [comment]
I've [found a video](https://www.youtube.com/watch?v=RWKhBzwH0Gk), real pcb, but it's bad quality, but I can see the bright-green glitches on the trees on 1st level. I'm guessing by the sound that it's the older non-PIC version, so i'll switch it back to the original (bad) rom for that set. If Hammy would like to re-dump that one rom (gfx12.040) then that would confirm the PIC version.

**Comment by Hammy1986** [comment]
No problem i will dump it and get a video on friday.

The other bootleg was from a non working PCB non-pic version. <now scrapped>

**Comment by Hammy1986** [comment]
https://www.youtube.com/watch?v=Ozlb2gNRSfs&feature=youtu.be

**Comment by TwistedTom** [comment]
Can't see the glitches so looks like the PIC set has good rom 12.

**Comment by Hammy1986** [comment]
Cool, i will dump em' all tomorrow :)

**Pull request merged**
