### PR TITLE
sound/nes_apu.cpp: Can no longer read from anything but status register.

### PR DESCRIPTION
**Pull request by 0kmg**
nintendo/nes_vt*: Aligned PnP APU code with core changes.
nintendo/dkong.cpp: Fixed dkong3b crash regression.

### CODE REVIEW

**Comment by 0kmg** [comment]
@happppp Thanks for fixing the dkong3 sound regression. I was working on doing something very similar that included the changes here. Also note dkong3b uses dkongjr hardware, so it doesn't need the new dkong3 init function.

**Comment by happppp** [comment]
dkong3b: Ah I missed that.
Does anything need the apu_w trampoline from this and rp2a03? If not, that can be removed too, instead do a m_apu->write directly.

**Comment by 0kmg** [comment]
How do we get the proper 0x15/0x17 offsets to nesapu::write without the trampoline? That's the only reason I couldn't remove it I think.

**Comment by happppp** [comment]
m_apu->write(0x15, data); ?

**Comment by 0kmg** [comment]
I'll try to see what I can do. I guess I forgot these VT PnPs are using 6502s and so they don't have to deal with the internal 2A03 map issue.

**Comment by 0kmg** [comment]
Ok, that's better. Sorry, I still need hand holding for simple things sometimes :)

**Comment by happppp** [comment]
I was looking for github actions, but I don't see it on your PRs.

**Comment by 0kmg** [comment]
Yeah, sorry. GitHub hobbled my account, disabling actions, and then refused to tell me why despite repeated questions. This account has never done anything but MAME PRs, so go figure.

**Pull request merged**
