### PR TITLE
upd7220, qx10: Implement display zoom support

### PR DESCRIPTION
**Pull request by brijohn**
This adds zoom support for the QX10 system.  Zooming on the upd7220 works by having the gpu rpeat each scanline the number of times equal to the programmed zoom factor. This will zoom in the vertical direction, the horizontal diretion requires external hardware on the machine in question to slow the fresh rate down which will create streched pixels allowing for soomin in the horizontal direction. On the QX10 the zoom rate for this external circuitry is set via the io port 0x3a.

This patch modifies the upd7220 so that it will multiple each Y count by the zoom factor and then updates the QX10 code to correctly multiply the X direction based on the value sent to the 0x3a io port.

### CODE REVIEW

**Comment by angelosa** [comment]
Not convinced about this implementation:

1. according to the manual only bitmap mode is affected;
2. my interpretation of the documentation is that GDC can only magnify on X axis, Y magnification is host responsibility (and most likely not all implementations can handle it). It definitely mentions in multiple places that external circuitry is necessary.

**Comment by brijohn** [comment]
> Not convinced about this implementation:
> 
> 1. according to the manual only bitmap mode is affected;

So this is incorrect. I have to assume that comment is talking about the write zoom factor not the display zoom factor. The display zoom factor certainly will work for zooming text my real qx10 and diag disk confirm that quite clearly.  The write zoom factor would obviously only work for grahpics/bitmap display areas as it relies on the GDC multiplying pixels when it writes the pattern register to the video memory, however the displa zoom factor should work regardless.

> 2. my interpretation of the documentation is that GDC can only magnify on X axis, Y magnification is host responsibility (and most likely not all implementations can handle it). It definitely mentions in multiple places that external circuitry is necessary.

You have this backwards the documentation clearly says the following 
> The GDC automatically takes care of repeating the horizontal display lines to effect the vertical magnification.

So it is basically handling The Y zooming by repeated sending the same scan line multiple times. and yes external circuittry is needed for the X direction that is what on the QX10 you are doing when you by setting the zoom factor on IO port 0x3a you are telling the the external circuitry what display zoom factor the GDC is curently set to so it knows how much to slow the refresh rate to cause the correct pixels streching on the X direction.

If you where to set a display zoom factor on the gdc wihout the external circuitry you would see the display streched in the Y firection but not correctly in the X direction.

**Comment by cracyc** [comment]
The qx10 zoom is described in http://www.vintagecomputer.net/fjkraan/comp/qx10/doc/tm1_5.pdf on page 5-26 and it shows the horizontal zoom requires external circuitry so I think the patch is correct.

**Comment by angelosa** [comment]
To be more precise for 1, was referring to [page 2-9](http://www.bitsavers.org/components/nec/uPD7220-uPD7220A_User_Manual_Dec85.pdf), "the zoom option is available only in the bit mode graphic mode of operation" (sic). Wondering why this note then.

**Comment by brijohn** [comment]
> To be more precise for 1, was referring to [page 2-9](http://www.bitsavers.org/components/nec/uPD7220-uPD7220A_User_Manual_Dec85.pdf), "the zoom option is available only in the bit mode graphic mode of operation" (sic). Wondering why this note then.

Yes, i think that line is somewhat misleading, or just wrong.

Real qx10 hardware shows that display zooming does in fact work on a text display area. It could be referring to the fact that the write zoom factor only works on bitmaps since it relies on the the GCHRD command to multiply pixels when drawing the pattern stored in the PRAM to the video memory. However when the card is set to mixed mode and you apply a display zoom command it certainly does in fact take effect for text display areas.

**Comment by cuavas** [comment]
This PR adds a data member to the µPD7220 device without registering it for save states – that may break save state support for downstream users.  Have other PRs on this device been checked for save state support?

**Comment by brijohn** [comment]
> This PR adds a data member to the µPD7220 device without registering it for save states – that may break save state support for downstream users. Have other PRs on this device been checked for save state support?

The only data member I think I added in this PR was the m_zoom variable, but that is part of the QX10 machine not the upd7220 device.

**Comment by cuavas** [comment]
Oh sorry, I’m sleep-deprived again.

**Pull request merged**
