### PR TITLE
New Working Clones

### PR DESCRIPTION
**Pull request by UED-Wayder**
Warp 1 (Japan) [Team Japump!!!, Wayder]

--------

warp1
Japan, Sun Electronics Version (New Working)

warp1t
Taito license Version  (Supported Ver. 0.231)

ROM and source provided by Team Japump!!!, posted by Wayder on proxy.

### CODE REVIEW

**Comment by happppp** [comment]
"tvg_23t.6", "tvg_26t.9": there is no "t" on the rom chip labels of the Taito version. If this is due to a filename conflict for merged romsets, tools like clrmamepro can handle it fine.

**Comment by UED-Wayder** [comment]
Thank you for your trouble.
Does this mean that roms have no problem with the same file name?
It would be helpful if you could adjust the file name as well.

**Comment by happppp** [comment]
Yes, MAME will try to load by checksum if the one from the filename is a mismatch.

**Comment by UED-Wayder** [comment]
Thank you for fixing and marge it.

**Pull request merged**
