### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
Black Jack (Nintendo Game & Watch) [algestam]

### CODE REVIEW

**Comment by cuavas** [comment]
Once again, please copy the machine descriptions verbatim when making lists of new/promoted machines.  It makes it far easier to reconcile things.

**Comment by algestam** [comment]
@cuavas: Sorry, I must have misunderstood you earlier. I have changed the git branch names to match the game names (i.e. `gnw_bjack`) instead of using a different name as I did earlier (i.e. branch name `gnw-oil-panic` for `gnw_opanic`).

To get it right the next time I will use the full name for the game in the commit comment and PR description. For this PR the full name is `Game & Watch: Black Jack` and so the correct commit message would then be:

    New working machine added
    -----------
    Game & Watch: Black Jack [algestam]

Please let me know if this isn't right and sorry for the trouble this causes you.

Cheers,
Henrik

**Comment by happppp** [comment]
@rb6502 was a bit too fast with the merge :) 

I did a small update here: https://github.com/mamedev/mame/commit/854882c3bf9e55c2ba243d0266f3ede058611b5c
The buttons are not directional controls, so I changed them to simply button 1,2,3,4. Note that if you're going for 'joystick' controls and the physical buttons are separate, set the PORT_16WAY flag.
I also did a small update to the svg, the background alpha was 254 instead of 255. I'll email you the updated svg.

**Comment by algestam** [comment]
Thanks hap :) I weren't really sure on how to represent the controls and your fix is really good. Thanks also for noticing the alpha change (again!), I start to believe that the problem is within inkscape as well.

**Pull request merged**
