### PR TITLE
Z180_CPU: CSIO Flags  & FRC implementation

### PR DESCRIPTION
**Pull request by grullosgo**
CSIO Flags:
Suggest a different way to avoid setting up for TI & RI flags in CNTR, for a non working Sincronus Serial CSIO.

Programs that uses this flags for Tx and Rx control gets stuck waiting these flags cleared because it never happens due the lack of implementation of the transceiver routines in Z180 code.

FRC implementation:

FRC is the free running counter register. Suggest this implementation for a non implemented yet function.

### CODE REVIEW

**Comment by RobertoFresca** [comment]
This is absolutely necessary for Lucky Ball 96. If nobody objects this implementation, I will add it to the source.

**Comment by rb6502** [comment]
I have a concern about the removal of the line that apparently makes the Super Famicom Box work.  Is that done in a less hacky way elsewhere, or what?

**Comment by rb6502** [comment]
Thanks @grullosgo that sounds fine, I will apply! :)

**Comment by grullosgo** [comment]
Nice! Thanks for your support.  Robbie will be very happy getting "lucky ball" full working after this changes.

I'll keep in touch.

**Comment by RobertoFresca** [comment]
Sure!! :-)
Soon will commit an updated driver...

**Pull request merged**
