### PR TITLE
Changed notification callbacks to be std::function<void()> rather than our own delegates

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by cuavas** [comment]
`std::function` doesn't support late binding and is theoretically less efficient than our delegates.  What's the motivation for this?

**Comment by npwoods** [comment]
I wanted to replace the various lua_engine::on_*() functions with lambdas, which was not directly possible with the existing delegates.  I suppose that given the right template magic, our delegates could have been made to do this but that didn't seem appropriate.

Changing `m_notifier_list` from `std::list<std::unique_ptr<notifier_callback_item>>` to `std::list<std::function<void()>>` seemed like icing on the cake.

While you're right about `std::function<>` not having late binding, the features you describe are not used in practice by the notification delegates.  I wasn't proposing retiring all usage of our delegates, just this one.

**Comment by cuavas** [comment]
It's possible to use lambdas in delegates - it's done in various memory maps.  Look at a cam900 pull request and you'll likely see examples.

**Comment by npwoods** [comment]
I suppose at no point did I think it wasn't possible - but rather it wasn't as seamless as it is with `std::function<>`, hence the (perhaps poorly used) word "direct" in my other message.

All in all, this seemed like a good opportunistic cleanup, certainly better than my first idea of having something that wrapped an `std::function<>` up into a delegate.  If you disagree, I'd like to understand the official line about when it is appropriate to use our delegates versus `std::function<>`.

**Comment by rb6502** [comment]
The official coding standards, https://wiki.mamedev.org/index.php/MAME_Coding_Conventions , says "Use std::function for callbacks when performance isn't critical, and MAME delegates when it is".

I would consider NOTIFY_FRAME to be performance-critical since it happens every frame, and at that point you might as well use delegates for the rest to be consistent.

**Comment by vadosnaprimer** [comment]
I noticed that lua callbacks are now called twice in a row in the latest release. The reason seems to be `lua_engine::enumerate_functions()`.

Run this script:
```lua
local function getscreen()
    for k,v in pairs(manager:machine().screens) do return v end
end

local function frame()
	print("frame: " .. getscreen():frame_number())
end

emu.register_frame_done(frame)
```

Output:
```
[MAME]> frame: 0
frame: 0
frame: 1
frame: 1
frame: 2
frame: 2
frame: 3
frame: 3
frame: 4
```

@npwoods can you fix this while you're at it?

**Comment by Tafoid** [comment]
@vadosnaprimer 
I think this was fixed already based on an MT report, assume it is the same anyway as you are referring to:
https://mametesters.org/view.php?id=7408
https://github.com/mamedev/mame/commit/a17315b742dd3ae2f09d9078846272601139b8c1

**Comment by vadosnaprimer** [comment]
@Tafoid sorry I failed to find it and to test the latest build. Thanks.

**Pull request closed without merging**
