### PR TITLE
source org: Move drivers not marked as MACHINE_IS_SKELETON out of skeleton

### PR DESCRIPTION
**Pull request by einstein95**
All of these drivers have at least 1 COMP entry that doesn't have MACHINE_IS_SKELETON, so they shouldn't be in `skeleton`. I've tried to use folder names that aren't any longer than 15 characters.

### CODE REVIEW

**Comment by cuavas** [comment]
The last thing we need is a pile more libraries containing single drivers.  At this point, I’m almost regretting doing the source reorganisation with the number of chaotic moves that it’s triggered, with the same things being moved multiple times.

**Comment by happppp** [comment]
Right now, only a few problems remain:
- the skeleton folder (that's basically a "misc" folder imported from MESS)
- the large misc folder can be split up
- folders with only 1 driver in them

At the same time (said this on IRC). It is subjective. If we have 30 devs with 10 differing opinions on where to place files, it'll still be disorganized.

**Comment by DavidHaywood** [comment]
There are always going to be some subjective cases, due to hardware from one manufacturer being extensively used by another.  tnzs for example is 100% 'seta / allumer' chip setup, but on a Taito board, running only Taito games, likewise taito_x, except for the c-chip use on Superman.    One person might expect to find those drivers in the seta folder based on hardware similarity and chips used, others might expect to find them in the taito folder as they are technically Taito boards.

The old 'flat folder' hid those details, maybe in reality that was better, as you could for the most part just forget about them.

**Comment by felipesanches** [comment]
Group by manufacturers and you get industry standard overlaps. Group by industry standard, and you get a manufacturers overlap. This is a database. There's no query that gets you a perfectly uncontroversial ordering of things.

I feel that perhaps it could be better to group things by categories like 'home consoles', 'personal computers', 'servers', 'mainframes', 'arcade cabinets', 'coin pushers', 'pinball machines', 'VCR players', 'kitchen appliances', 'industrial machinery', 'LCD handhelds', etc

**Comment by DavidHaywood** [comment]
you can't group that way either, again there's overlap, and the categories you create are 100% subjective.

**Comment by DavidHaywood** [comment]
yeah it almost certainly needs moving out of the ngpc xml and turning into a machine then, although given the application it might even require an entirely different BIOS (as the NGPC bios requires initial setup)

**Pull request closed without merging**
