### PR TITLE
New NOT WORKING clone

### PR DESCRIPTION
**Pull request by clawgrip**
New clones marked as NOT_WORKING
------------------------------------------
Chouji Meikyuu Legion (Japan ver 1.05, bootleg set 2)
[Tomas Garcia-Meras (ClawGrip), Roberto Fresca, Recreativas.org, The Dumping Union]

### CODE REVIEW

**Comment by PeterBortas** [comment]
This looks white-space damaged. The entire file is replaced.

**Comment by clawgrip** [comment]
Corrected, thanks!

**Comment by PeterBortas** [comment]
I can confirm that the white-spaces look good now. :-)

**Comment by clawgrip** [comment]
Done!

**Pull request merged**
