### PR TITLE
minor galaxian driver note-related changes

### PR DESCRIPTION
**Pull request by kazblox**
-re-clarify everything about the meaning of galaxold.c, scramble.c, scobra.c and dambustr.c existing in the driver description.
-copy in mooncrst game notes from galaxold.c to galaxian.c

### CODE REVIEW

**Comment by kazblox** [comment]
Not sure if anyone agrees on the idea of my descriptions for the old drivers, but the exactly say the current meaning of them, sort of coming from the words of Haze...

**Comment by happppp** [comment]
Moving stephh's mooncrst notes to galaxian.c is good.
I wouldn't bother with documentation or improvements to deprecated galaxian
hw drivers. They're going to be relocated and any other work is a waste of
time IMO (...but yeah, it's taking much longer than anticipated)

**Comment by kazblox** [comment]
Maybe I'll try merging some galaxold games in at some point, but it'll take
some long time as Haze said, some of the galaxold/scramble/scobra games
were meant for wiremods and guessed prepherials. The galaxold driver is
tweaked to fit these wiremods and I can tell.

Once tried merging bagmanmc in and got completely wrong video positions at
the third point of the game and the game over screen, yet I checked and
everything is right.

**Comment by kazblox** [comment]
Should probably close this for a new pull request and some thinking time.

**Pull request closed without merging**
