### PR TITLE
pokey: performance optimization by not using modulus

### PR DESCRIPTION
**Pull request by schnitzeltony**
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by Lord-Nightmare** [comment]
The real way these counters work is they are probably LFSRs; I haven't had a chance to look at the POKEY die schematic to see if I can spot exactly where they are, though.

**Comment by cuavas** [comment]
Have you measured the performance difference with/without this change?  Most of the performance hit from the POKEY emulation is caused by the way it runs as a scheduled device like a CPU.

**Comment by schnitzeltony** [comment]
@Lord-Nightmare: The scope of this patch was not to change accuracy of emulation. It just should behave same but perform better.

@cuavas: My optimism sending out this patch was based upon some valgrind/calgrind profiling. Test case was 'starwars' because that has four pokeys. Wanted to generate mame builtin profiler (Shift+F11) numbers but currently there is:

* for the branch I put my patches on-top I get performance values for each pokey
* for master I get one value for all pokeys 

Was there some modification? Whatever - I am a bit confused currently and need some time to build versions which can be compared to each other...

**Comment by happppp** [comment]
I can confirm starwars is >5% faster

**Pull request merged**
