### PR TITLE
Fixed breakage from recent 6840PTM changes.

### PR DESCRIPTION
**Pull request by MooglyGuy**
-duet16: Added external PTM clock. [Ryan Holtz]

-6840ptm: Fixed one-shot behavior and timer enabling when switching to internal clock. [Ryan Holtz]

### CODE REVIEW

**Comment by Tafoid** [comment]
Appears to have fixed previous regression reported for duet16 and zwackery https://github.com/mamedev/mame/pull/10086#issuecomment-1186588902
However, cpu09 has continued to regress.
cpu09-diff

**Comment by MooglyGuy** [comment]
You're going to have to provide more information as to how you're running cpu09, then, because when I ran MAME with completely default settings, I didn't even get the screenshot that you provided in the last report about it, I just got a blinking cursor. And I certainly don't get the behavior that you're indicating now.

**Comment by Tafoid** [comment]
It is possible with the new development we have exposed or created uninit'd variables somewhere.  I'm using the straight MAMEDEV.org package on Windows (GCC 11.2.0) for 64-bit daily compiles.   Running with a simple **-bench 10** and comparing output from July 15 binary and July 19 binary shows what I posted above.   I also just tested the Windows Action binary - https://github.com/mamedev/mame/actions/runs/2694794606 made from your commit and the same thing happens for me as shown.

**Comment by MooglyGuy** [comment]
If you find any other breakage, please let me know, but I'm not going to go out of my way for a driver that's already marked MNW and doesn't exhibit this behavior on my machine.

**Comment by Tafoid** [comment]
ivg09, in same driver as cpu09,  This one only started regressing after this particular commit.

>  **mame ivg09 -norc -rompath d:\roms -str 10**

Of course, change -rompath to taste.  I chose to use -norc to disregard all configurations that might be interfering in any way.  Both daily build binary made for testing as well as the Action Binary linked above do the same for me.

ivg09-diff

**Pull request merged**
