### PR TITLE
merits.cpp: Correctly identified set as "Pub Time Darts II"

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by happppp** [comment]
OK, but don't right-align those 0s under PARENT at the game macros.

**Comment by happppp** [comment]
And is "Pub Time Darts II Plus 2 with Solo Challenger" the official title?
According to google, there's "Pub Time Darts", and "Pub Time(or Pubtime) II Plus 2"(no "Darts" in it) and the one with Solo Challenger

**Comment by clawgrip** [comment]
> 
> 
> And is "Pub Time Darts II Plus 2 with Solo Challenger" the official title?
> According to google, there's "Pub Time Darts", and "Pub Time(or Pubtime) II Plus 2"(no "Darts" in it) and the one with Solo Challenger
> 
> _edit_
> see https://www.ebay.com/itm/253477788615 2nd photo

PTD_Solo

Yes! See the manual...

**Comment by happppp** [comment]
Ok!

**Pull request merged**
