### PR TITLE
tms34020: Fix BLMOVE S=1, D=1 opcode handling

### PR DESCRIPTION
**Pull request by plaes**
Correctly handle S=1, D=1 case which allows any alignment of
source and destination. Fixes endless loop in atronic / atricmon.

### CODE REVIEW

**Comment by happppp** [comment]
Instead of those empty if statements, this is better?:

switch (op & 3)
case 3: implementation
default: logerror

**Comment by plaes** [comment]
> Instead of those empty if statements, this is better?:
> 
> switch (op & 3)
> case 3: implementation
> default: logerror

Yeah, makes sense. I'll force push the fix.

**Comment by happppp** [comment]
Also, please don't literally copy-paste from TI's manual, it's copyrighted. If something in the opcode handling needs explanation(like, the code itself isn't clear enough), you can briefly comment in your own words.

**Comment by happppp** [comment]
And if I'm seeing it correctly, this version will break if the BLMOVE is incomplete (eg. the current timeslice is too short and icount becomes 0).

**Comment by plaes** [comment]
> And if I'm seeing it correctly, this version will break if the BLMOVE is incomplete (eg. the current timeslice is too short and icount becomes 0).

Ugh, this is something I do not really know about :(

**Comment by happppp** [comment]
I suggest remove these lines (no need to update regs until the end):
BREG(2) += 0x10;
BREG(2) += bits;
BREG(0) += BREG(7);

change the commented out logerror to:
// logerror("020:BLMOVE: PC=%x: finished: B0=%x, B2=%x, B7=%d\n", m_pc, src, dst, bits);

and re-add the end part:
	/* update the final results */
	BREG(0) = src;
	BREG(2) = dst;
	BREG(7) = bits;

	/* if we're not done yet, back up the PC */
	if (bits != 0)
		m_pc -= 0x10;

The last line is for incomplete BLMOVE. And you didn't update BREG(7)

**Comment by plaes** [comment]
> I suggest remove these lines (no need to update regs until the end):
> BREG(2) += 0x10;
> BREG(2) += bits;
> BREG(0) += BREG(7);
> 
> change the commented out logerror to:
> // logerror("020:BLMOVE: PC=%x: finished: B0=%x, B2=%x, B7=%d\n", m_pc, src, dst, bits);
> 
> and re-add the end part:
> /* update the final results */
> BREG(0) = src;
> BREG(2) = dst;
> BREG(7) = bits;
> 
> ```
> /* if we're not done yet, back up the PC */
> if (bits != 0)
> 	m_pc -= 0x10;
> ```
> 
> The last line is for incomplete BLMOVE. And you didn't update BREG(7)

OK, thanks!

I redid the implementation a bit, although not really 100% what manual states and for this part I added TODO comment.

**Comment by happppp** [comment]
That's ok, as long as all emulated hardware using this CPU still works it's fine. The previous implementation was incomplete too.

**Pull request merged**
