### PR TITLE
Create GitHub Actions for CI

### PR DESCRIPTION
**Pull request by startaq**
This is intended as a replacement for AppVeyor and parts of TravisCI. It will create full builds of MAME (including tools) for the following platforms:

- Linux (GCC and Clang)
- macOS (Clang)
- Windows (GCC and MSVC 2019)

It will also upload the resulting executable as artifact so that it can be used for regression testing.

This commit also removes the unused TeaCI drone files.

### CODE REVIEW

**Comment by stilett0** [comment]
Don't forget the README.md badges when we pull the switch...

**Comment by belegdol** [comment]
Linux-gcc might need an update to run apt upgrade prior to building. As things stand now, it is built with gcc 7 whereas other builds are done using updated compilers.

**Comment by belegdol** [comment]
https://github.com/belegdol/mame/runs/937956007?check_suite_focus=true
apt upgrade already runs. ppa with the latest gcc needs to be added and OVERRIDE_GCC/CXX need to be invoked. In my fork the ppa is somehow added automatically, I am not sure which line exactly triggers it.

**Comment by belegdol** [comment]
Found it:
https://github.com/belegdol/mame/blob/github-actions-mametiny/.github/workflows/ci.yml#L14
Apologies for the noise, it's been a while since I touched this code.

**Comment by startaq** [comment]
> 
> 
> Linux-gcc might need an update to run apt upgrade prior to building. As things stand now, it is built with gcc 7 whereas other builds are done using updated compilers.

GCC 7 is still supported by MAME. It might even be considered an advantage that one build still uses it. If we drop support and GitHub hasn't switched over `ubuntu-latest` to 20.04 yet we can switch to `ubuntu-20.04` in the workflow that will use GCC 9.

**Comment by belegdol** [comment]
Fair enough, I just wanted to point this out so that it is a conscious decision to use the older compiler. Travis builds for Linux are supposed to stay and these use gcc-10 so we are covered on that front.

**Comment by cuavas** [comment]
Is there anything actually holding this up at this point?  Are you going to update README.md to show the correct badges?

**Comment by startaq** [comment]
I was going to adjust `README.md` in a followup commit, but sure, I can just attach the changes here.

**Comment by belegdol** [comment]
I just noticed that x64 Linux build was in fact dropped from Travis, meaning that Linux/x64 will only be tested on alternative architectures with gcc-10 and on x64 with gcc-7 only. Would it make sense to keep the x64 Travis build? This way if alternative arch breaks we will know if it is due to compiler or due to arch weirdness.

**Comment by startaq** [comment]
We don't need Travis for that. We can just add tests for GCC 10 to the GitHub workflow instead. I think this is something that can be tweaked at a later point if it is wanted.

**Comment by cuavas** [comment]
Let’s see what happens.

**Pull request merged**
