### PR TITLE
WIP rebase and completion of split out of epc driver and addition of graphics card

### PR DESCRIPTION
**Pull request by JoakimLarsson**
Rebase of old work and as it touches some files of common use I welcome comments of this draft PR as it also spans a period of substantial changes to the driver standards. I will add more code to this  and address any concerns over the next couple of weeks.

### CODE REVIEW

**Comment by ajrhacker** [comment]
It would be good to also move src/mame/drivers/e9161.cpp to the new subtarget.

**Comment by JoakimLarsson** [comment]
Datasaab is definitely on my list to research, I wonder if they don't deserve their own subtarget, I think I have access to some real systems too through some collectors I know. The PC era was more an Ericsson thing, we'll see, they aquired Datasaab at some point.

**Comment by ajrhacker** [comment]
Ericsson acquired Datasaab (including the Alfaskop line) in 1980.

**Comment by JoakimLarsson** [comment]
And Nokia and ICL aquired it later, inteteresting thread of ownership indeed

**Comment by rb6502** [comment]
I'm fine with this, although I think since the Ericsson MDA is basically completely unique code compared to the IBM MDA it really oughta be in its own file.

**Comment by JoakimLarsson** [comment]
> ...since the Ericsson MDA is basically completely unique code compared to the IBM MDA it really oughta be in its own file.

Ok, I look into it when I drill down in that part, there are some proprietary high resolution modes that needs to be supported aot. 

Right now I am awaiting the results of a dump attempt of the keyboard controller. I am working with Mattis Lind on a small project for this https://github.com/MattisLind/6801reader It is a serial keyboard so quite not PC compatible even though the serial controller data register is read at the same address as the PPI port A so it works in pc.cpp without emulating the serial keyboard! Despite not being bidirectional that is, why we make the effort.

**Comment by JoakimLarsson** [comment]
I will rebase and submit this once the serial keyboard works, stay tuned :)

**Comment by JoakimLarsson** [comment]
So now I need to clean it up, some minor fixes and rebase it to master head. I think I rather close this PR and cherry pick the changes to a new branch to get a little more control.

**Comment by JoakimLarsson** [comment]
This PR is replaced by #5686 as it was too far behind to easily rebase and merge here, for me at least.

**Pull request closed without merging**
