### PR TITLE
a7800.xml: Replaced Wasp! with a proper, working ROM (MT06949).

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
what's the older ROM? bad dump, or development revision that didn't work on hardware?

**Comment by Tafoid** [comment]
> what's the older ROM? bad dump, or development revision that didn't work on hardware?

There is always concern when homebrews are added that dumps that are not explicitly documented for version may be adjusted to work with emulator limitations, watermarked, or something else that adjusts the original data of the produced media.  Not saying this is the case here - just commenting on the situation as a whole.

**Comment by 0kmg** [comment]
> what's the older ROM? bad dump, or development revision that didn't work on hardware?

Yes, the development version we had had exactly the problem described in MT6949 on hardware. The author posted all the dev versions including final cartridge release swapped in here. None of the dev versions worked on hardware.

**Comment by rb6502** [comment]
I'd document the hashes for the development version but not actually include it.

Also it'd be worth fixing the driver so it gives the hardware behavior (doesn't even boot) rather than the current MAME behavior where it's glitchy, but that's a separate issue.

**Comment by 0kmg** [comment]
@rb6502 I've noted the hash of the removed version. To your other point, the thread on AtariAge indicates that that particular version had the same problem (invisible sprites) on hardware as it did in MAME, so this BTANB doesn't reveal any deficiencies with the a7800 driver AFAICT.

**Pull request merged**
