### PR TITLE
mpu4: Preliminary hopper hookups

### PR DESCRIPTION
**Pull request by james-wallace-ghub**

### CODE REVIEW

**Comment by james-wallace-ghub** [comment]
This needs someone with more 68681 nous than me to confirm this is OK. I'm currently using the hack read @DavidHaywood put in, instead of the input lines, as I can't find a way of interfacing into the relevant channels.

I need to be able to write from the PIA to DUART channel B, and set the IPX bits from an external handler.

**Comment by DavidHaywood** [comment]
I imagine ticket.cpp needs some kind of line callback adding on m_output changes at the moment it has an 'output finder' but not any kind of devcb_write_line

then in the driver you'd have that m_output change call ip0_w / ip1_w / ip2_w / ip3_w etc. on the duart depending on the bit?

of course then you'd remove the hack function that is mapped over the duart read.

I could however be entirely wrong, I'm not sure how these things hook up properly myself, but I'm 99% sure the ticket / hopper device needs a devcb_write_line on status changes at the very least.

**Comment by cuavas** [comment]
Well if they’re the same hoppers just hooked up differently, it should be possible to hook them up to devcbs using `.append(...).bit(...)` – read devcbs will or together the results from appended handlers.

**Comment by james-wallace-ghub** [comment]
Taking this into draft until I have the cleaner implementation ready.

I'll leave the branch available for those who want to look at it locally, but I agree this needs work before it goes mainline.

**Comment by cuavas** [comment]
> Taking this into draft until I have the cleaner implementation ready.

If you’ve got specific questions, give me a yell.  I’ll try to help out.  I believe @galibert is also taking a look at untangling some of the I/O code in the MPU4 drivers.

**Comment by james-wallace-ghub** [comment]
Cheers, much obliged - I'm on UK time (not far from David I think, so it might be ships passing in the night, but I'll get there).
This has been wrong for so long, I kind of feel motivated to go back and put it right, so to speak.

**Comment by Tafoid** [comment]
@james-wallace-ghub Got to testing this yesterday and a few machines were throwing an exception.  I've attached a list

[setstochecklater_barcrest.txt](https://github.com/mamedev/mame/files/9665120/setstochecklater_barcrest.txt)

**Comment by james-wallace-ghub** [comment]
> @james-wallace-ghub Got to testing this yesterday and a few machines were throwing an exception. I've attached a list
> 
> [setstochecklater_barcrest.txt](https://github.com/mamedev/mame/files/9665120/setstochecklater_barcrest.txt)

I've actually binned the branch because I saw similar issues, but I'll take this under advisement, it looks like the way I was doing this didn't work the way I intended.

**Pull request closed without merging**
