### PR TITLE
Work around what appears to be an MSVC bug by making two casts be explicit

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by npwoods** [comment]
Distilled test case

> 

	template<typename T>
	class foo
	{
	public:
		foo(T value)
			: m_value(value)
		{
		}

		constexpr operator T&()
		{
			return m_value;
		}

	private:
		T m_value;
	};

	enum class my_enum
	{
		alpha,
		bravo
	};

	void test()
	{
		foo<my_enum> my_foo(my_enum::alpha);
		bool value = my_foo == my_enum::alpha;
	}
`

**Comment by yz70s** [comment]
This bug is present in vs2017 and also in all versions of vs2019.
The bug report: https://developercommunity.visualstudio.com/content/problem/630838/vs2019-v1614-error-with-comparison-operator-in-c-c.html

**Comment by npwoods** [comment]
Are we sure that is the right way to go?  The resulting code is still legal C++, if just a bit luddite-ish.  If anything, #ifdef _MSC_VER paves the way for the logic to diverge.

That said, Vas seems to disagree with the idea of any concessions to MSVC bugs.

**Comment by peterferrie** [comment]
> Are we sure that is the right way to go?  The resulting code is still legal
> C++, if just a bit luddite-ish.  If anything, #ifdef _MSC_VER paves the way
> for the logic to diverge.
>
> That said, Vas seems to disagree with the idea of any concessions to MSVC
> bugs.

make vsllvm

Let's just abandon with MSVC and not #ifdef at all.

**Comment by pmackinlay** [comment]
This issue is claimed to be fixed in [Visual Studio 2019 16.3 Preview 2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.3.0-pre.2.0) released yesterday.  I haven't tested to confirm, however it's looking like 16.3 (probably MSVC 19.23) will resolve most/all of the known issues with building MAME, so we can finally upgrade from 15.7.6 to latest and MSVC can be considered to be a viable compiler again.

**Comment by yz70s** [comment]
It is not fixed.
However there are no internal error crashes and mame can be built with small modificatios to a few files.

**Comment by yz70s** [comment]
This bug is resolved in vs2019 16.3.0 preview 3.0

**Pull request closed without merging**
