### PR TITLE
Wat? Jungle Soft never had an apostrophe in its name, as its own title screen shows: http://supermulti.org/?post=4 (nw)

### PR DESCRIPTION
**Pull request by RebeccaRGB**

### CODE REVIEW

**Comment by MooglyGuy** [comment]
Now that I'm home from work, I had the chance to go through the various SPG-based sets supported by MAME. Not to put too fine a point on it, but if Jungle Soft "never had an apostrophe in its name", what's this then? A different company, also making SPG-based systems, that happens to be called Jungle's Soft?

**Comment by cuavas** [comment]
The company's official name is "丛林互动科技开发（福州）有限公司", which means "Jungle Interactive Technology Development (Fuzhou) Ltd" (see [here](https://www.liepin.com/company/gs637382/) for business registration details - mandarin pinyin is "Cónglín Hùdòng Kējì Kāifā (Fúzhōu) Yǒuxiàn Gōngsī").  They've used "JungleTac", "JungleSoft", "Jungle Soft", and "Jungle's Soft" branding.  Someone please revert this.

**Comment by MooglyGuy** [comment]
In any event, do you have access to a "12 in 1 Colour Games Console"? We could use a dump of it, and based on the fonts and time frame it's most likely also micron'SP-based. And I promise to refer to the creator as Jungle Soft if that's what it says on the title screen. :)

**Comment by MooglyGuy** [comment]
I'm not going to revert it, Vas. vii says "Jungle Soft" on the title screen, zone60 says "Jungle's Soft", and given that wirels60 was clearly made by the same company but lacks a proper company title anywhere in the game, the company name should most likely be listed as the more commonly anglicized name of "Jungle Soft", as BeckieRGB's commit indicates.

**Comment by MooglyGuy** [comment]
No need to apologize. As I said, given my history in the emulation scene I'm certainly throwing rocks from within a glass house on this one. :)

**Pull request merged**
