### PR TITLE
NTSC mode to set refresh rate to 59.82 for 240 and 59.94 for 480

### PR DESCRIPTION
**Pull request by hoholee12**
fixes sync issues regarding beatmania IIDX games

### CODE REVIEW

**Comment by hoholee12** [comment]
https://github.com/mamedev/mame/issues/4352

**Comment by angelosa** [comment]
This doesn’t really fix what it claims but rather kludges it. For whatever reason the core defines a h/vblank time of zero lines/pixels, how the HW actually defines that is a mystery to me (GPU command display start/stop?).

**Comment by hoholee12** [comment]
> This doesn’t really fix what it claims but rather kludges it. For whatever reason the core defines a h/vblank time of zero lines/pixels, how the HW actually defines that is a mystery to me (GPU command display start/stop?).
i do not know the specific details, but the actual refresh rate differs between 240 and 480 ntsc. i set them accordingly(480 is 59.94hz and 240 is 59.82... not the previous universal 60hz it was on)... and it fixes the timing. same thing happens on the other console port with pcsx2.
please elaborate on why you think this is just kludging...

**Comment by couriersud** [comment]
As a rule of thumb ... The visible scanline length in relation to the total scanline length on a lot of systems is usually 2/3. E.g. total scanline length 384, visible 256. Mame in a lot of places ignores this and uses 

total = visible, backporch=0, sync=0, frontporch=0.  

In older games (<1985?), using 

total = visible * 3 / 2, backporch =  total - visible - 80 , sync = 64, frontporch = 16

is a better approximation. IF NTSC is verified, total to visible is 858/720
```
ModeLine "720x480@30i" 13.5 720 736 799 858 480 486 492 525
```
However ... NTSC is interlaced. With 59.xx you are setting the field refresh frequency and interpreting the video as false-progressive.

And there may be some spurious accuracy involved here (59.82 vs 60). Most video hardware should easily cope with field refresh ratios between 58 and 62. It's hsync and vsync generated by the hardware which tells the monitor what to do. It's not that the monitor is imposing exactly 59.82.

**Comment by smf-** [comment]
On 03/02/2020 21:40, couriersud wrote:
> However ... NTSC is interlaced. With 59.xx you are setting the field
> refresh frequency and interpreting the video as false-progressive.

It would help if we supported interlaced.

**Pull request merged**
