### PR TITLE
nes: Replace VDP bitmap access with screen().pixel() for lightgun emulation

### PR DESCRIPTION
**Pull request by enikland2**

### CODE REVIEW

**Comment by cuavas** [comment]
I don't think this is a good approach.  Deriving from `device_video_interface` and not explicitly configuring a screen takes the first screen in a system implicitly, which may not be the desired screen.  Slot devices, etc. will interfere with this.  Making code rely on it isn't a great idea.  The zapper does actually rely on whether it's pointed at a bright pixel, but it should be supplied with the correct screen in some deterministic way.

**Comment by enikland2** [comment]
>  it should be supplied with the correct screen in some deterministic way.

I opened the pull request #4910 to address the issue.

**Comment by Tafoid** [comment]
This has basically killed usage of lightguns via mouse for at least NES related arcade titles as detailed in an MT report:  https://mametesters.org/view.php?id=7331

Can you work out a solution in the next week before release?  A revert of this might be warranted.

**Comment by enikland2** [comment]
Added a fix to the pull request #4910 but it also needs pull request #5109

**Pull request merged**
