### PR TITLE
qx10: Implement Sound/Speaker

### PR DESCRIPTION
**Pull request by brijohn**
This patch adds the currently missing sound support for QX10 systems.

### CODE REVIEW

**Comment by happppp** [comment]
Speaker output is determined by those 3? Then add an update_speaker() function, put your diagram and level_w in there. And call to it from qx10_18_w, speaker_freq(after m_spkr_freq = state;), speaker_duration.

**Comment by happppp** [comment]
Also, ! is boolean, & is binary. Best not mix them in algorithms. It's more like this I guess?
m_speaker->level_w(~(~(~m_spkr_enable & m_pit1_out0) & m_spkr_freq) & 1);

**Comment by brijohn** [comment]
> Also, ! is boolean, & is binary. Best not mix them in algorithms. It's more like this I guess?
> `m_speaker->level_w(~(~(~m_spkr_enable & m_pit1_out0) & m_spkr_freq) & 1);`
> or:
> `uint8_t level = !((!((!m_spkr_enable) && m_pit1_out0)) && m_spkr_freq) ? 1 : 0;`

Yes I meant to use binary ands here rather then bit ands. Of course testing showed it working due to the fact that all values here are ether 0 or 1. Should be fixed now.

**Comment by brijohn** [comment]
> Speaker output is determined by those 3? Then add an update_speaker() function, put your diagram and level_w in there. And call to it from qx10_18_w, speaker_freq(after m_spkr_freq = state;), speaker_duration.

That would not be correct the speaker output should only change on the edge transition of the frequency square wave. 

Basically there are two bits in the 8 bit flipflop at I/O adress 0x18 that control whether sound will be output or not. These are D0 and D2. D2 will turn on sound continuously until it is cleared, whereas D0 enables Gate 0 on the first PIT which will enable sound for whatever duration is programmed into counter 0. Either way though the output to the speaker should not change until an edge transition on the frequency timer. If sound is disabled the output will always be 1 otherwise it will follow whatever the current frequency transition is toggling between 0 and 1.

**Comment by happppp** [comment]
According to your diagram, if 'enable' or 'pit1_out0' toggles to turn off the sound, then speaker output will become 1 before the falling edge of freq, right?
So in theory, you could for example create a dual-pitch tone by toggling 'enable' at a faster rate than freq, which this implementation wouldn't allow.

**Comment by brijohn** [comment]
> According to your diagram, if 'enable' or 'pit1_out0' toggles to turn off the sound, then speaker output will become 1 before the falling edge of freq, right?
> So in theory, you could for example create a dual-pitch tone by toggling 'enable' at a faster rate than freq, which this implementation wouldn't allow.

Ah ok I se what you're saying now. Updated the code to reflect the updating the sound level when enable or Out 0 change as well.

**Pull request merged**
