### PR TITLE
Use C++17

### PR DESCRIPTION
**Pull request by vadosnaprimer**
This will allow to upgrade sol2 to version 3, which got lots of nice features since 3 years ago when mame incorporated it. And sol3 will allow to significantly reduce memory usage when compiling `luaengine.cpp`. Which, in turn, may unbreak 32bit build.

Not sure if `"-std=c++1y"`s were meant to stay. On Windows, I tried MSVC with pacman and GCC with arcade subtarget, both compile.

### CODE REVIEW

**Comment by cracyc** [comment]
I haven't looked at sol3.  How hard do you think the conversion is?

**Comment by vadosnaprimer** [comment]
I used sol's "single header" thing, and only had to remove https://github.com/mamedev/mame/blob/61b2a8afaf012e28ef14ad946ee0bb8319232aa6/src/frontend/mame/luaengine.cpp#L87

`sol.hpp` needs slight tweaks to work with gcc 9.2.0, but that part I can try resolving with upstream.

**Comment by cracyc** [comment]
Nice, thanks for working on this.

**Comment by cuavas** [comment]
Sorry, we can't switch to C++17 until we can drop support for GCC 7 and a number of older clang versions.

**Comment by vadosnaprimer** [comment]
@cuavas what is GCC 7 required for?

**Comment by cuavas** [comment]
We actually haven't dropped support for GCC 5.1 yet. But MSYS2 still provides GCC 7 for 32-bit targets, and GCC 8 only has preliminary C++17 support. After the trouble we had with the preliminary C++14 support in GCC 4.9, I'd be nervous about switching to C++17 until all supported compilers have mature C++17 support. It's hard to deal with "we use this C++ version, but avoid these features" because the preliminary support is not standards- compliant.

**Pull request closed without merging**
