### PR TITLE
Add Daioh loctest and remove hacked Daioh set.

### PR DESCRIPTION
**Pull request by trap15**
Add Daioh (location test version) [CoolMod, trap15]
Remove Daioh (set 1) and replace with Daioh (set 2).
Set 1 was a hack and probably should not have been accepted.

### CODE REVIEW

**Comment by mr-t-guru** [comment]
the original set 'daioh' with roms fg001001.u3 and fg001002.u4 was dumped at least 10-15 years ago (probably by Al Kossow judging by the PCB layout) and is definitely not a hack. the rom names match the PCB ascii layout in the src and also correspond with the standard way Seta ROMs were labelled at the factory.
it shoudn't be removed IMO.
why do you think it is a hack?

**Comment by trap15** [comment]
The set 1 at the time of this push request was not that one. Look at the combined program binaries. Here's a breakdown I did in IRC of the changes and why I think they're not official:
<trap15> the vector table has been changed to make bus error and address error go somewhere other than a hard lock
<trap15> the new destination is a newly inserted RTE that's located at the first NOP in the code
<trap15> that would've affected nothing
<trap15> there's a change in a jumptable at $23A28 that pushes the destination PC into the original function, but not into a different one
<trap15> which would make no sense from an official build
<trap15> and at $23DF2 a large chunk of code has been rewritten, with a bunch of NOPs added for padding
<trap15> I don't think these seem very likely to have been official modifications
<trap15> and there are various changes around that change things like "ADDI $20, D0" to "MOVE $7F, D0"

If I removed the wrong one, I'll revise my pull request, but I'm quite sure I got the right one. "set 1" was from a few years ago and was somehow promoted to "set 1" instead of the other set, despite it being pretty obviously hacked.

**Comment by mr-t-guru** [comment]
- ROM_LOAD16_BYTE( "fg001001.u3", 0x000000, 0x080000, CRC(e1ef3007) 
- ROM_LOAD16_BYTE( "fg001002.u4", 0x000001, 0x080000, CRC(5e3481f9) 
+ ROM_LOAD16_BYTE( "fg1-001.u3", 0x000000, 0x080000, CRC(104ae74a) 
+ ROM_LOAD16_BYTE( "fg1-002.u4", 0x000001, 0x080000, CRC(e39a4e67) 

looks to me like the original set with crc e1ef3007 and 5e3481f9 has been removed from the src and replaced with the daioha roms (u3/u4). surely not correct......

**Comment by trap15** [comment]
No, that's correct. "fg1-001.u3" matches the naming scheme of the other files in the set anyways. daioha was the old daioh, which got renamed to daioha when the current "set 1" was added and promoted to set 1. Check the second and 3rd 32bit value in the combined ROM, if they're $400 that's correct, if it's $A10 that's wrong. I'm pretty certain I deleted the one with $A10.

**Comment by mr-t-guru** [comment]
so you're saying at some point in the past the "hacked" set got promoted to the original parent set?

1. the hacked set shouldn't be totally removed regardless because of lack of proof. maybe it was converted at the factory to run on a different board that they had excess stock of.... we just don't know. leave it there and add any new sets with a different (clone) name.

2. the ascii layout clearly shows the rom names of the original set (dumped 10-15 years ago) are "FG-001-001" and "FG-001-002" etc and should not have been renamed, regardless! the original rom names as per the Daioh ascii PCB layout in the src should be kept.

**Comment by trap15** [comment]
Yeah, shortly after addition it was promoted to parent set. If you'd like to do a full ROM rename and keep the current "set 1" as "bootleg?" or "hack?" or just anything but the parent set, I'd be willing to compromise to that end.

**Comment by mr-t-guru** [comment]
I'm not going to do anything. you are messing with it, you can fix it or your merge will be nak'd ;-)
seriously though, don't mess with what is there already.

promote the original original Daioh set (with rom names that match the PCB layout in the src) to parent
move the 'hacked' set to set1 (without the hack text unless you have definitive proof as to why it was hacked and exactly which PCB it ran on, including a photo of the 'bootleg' PCB)
add your new 'location' set

**Comment by mr-t-guru** [comment]
p.s. if you want, also add the summary from your previous post with the code changes as a note above the daioha set when re-added showing what is changed and say it's possibly a hack/bootleg.

**Comment by trap15** [comment]
I've re-added the questionable set as 'daioh1' to try to help avoid confusing it with the 'daioha' set.

**Comment by mr-t-guru** [comment]
ok thats fine now. 
I see the location test PCB is using many EPROMs instead of the large capacity mask ROMs. Out of curiosity, have you got a pic (or link to pic) of the location test PCB?

**Comment by system11b** [comment]
I've sent them to TDU.

**Comment by trap15** [comment]
Here are pictures of the PCB courtesy of CoolMod. http://daifukkat.su/files/daiohloc_pics.7z
As you can see, the PCB does not work :) He removed the ROMs for dumping, but everything is indeed EPROMs.

**Comment by awjackson** [comment]
trap15, you yourself did a breakdown of the changes on a forum a couple of years ago. I guess you forgot:

http://shmups.system11.org/viewtopic.php?f=1&t=42415&p=822369

Summary: the changes consist of a fix for a crashing bug specific to the US 6-button mode, and some tweaks to make the game harder e.g. by spawning fewer 1up items.

None of the changes appear to be related to adapting the game to run on different hardware, so it's probably not a bootleg.

Luckily I have archives from the MAMEDev list going back to when the set was added. The ROMs were submitted in 2012 attached to the following email.

>Hi Micko,
>I tried doing the "freeze" bug on my Daioh board while playing, which I know happens in the version in MAME, and it didn't happen. I dumped my board, and all of the ROMs match except the program ones. I think it may be a newer version? I have attached a ZIP archive with the new ROMs."

In a followup email, the submitter provided this (unfortunately low resolution) photo of the PCB:

dsc00837

which Guru confirmed to be an original Seta board. Guru also commented that

>it's not uncommon for arcade companies to lose the source and have to fix it directly in existing binaries

The set was added as parent and the old set demoted to a clone specifically because of the crash fix.

**Comment by mamehaze** [comment]
btw, the prototype / location test version has some bad tiles on the background of the titlescreen, possibly due to it being a proto, but it would be good to know that the roms were read at least twice when it was dumped to rule out any potential dumping problem.

**Pull request merged**
