### PR TITLE
python script that generates the patinho feio layout file

### PR DESCRIPTION
**Pull request by felipesanches**
This PR removes the layout file and adds a python script that generates it. But this is not yet integrated into the build system. Can anyone here help me with that?

### CODE REVIEW

**Comment by happppp** [comment]
Let's not convolute it. I think it's simple enough to not need a custom
generator script. If the layout needs improvements, another contributor
will find it easier to edit the layout than your script. Especially if
they're not used to Python.

**Comment by felipesanches** [comment]
These are like 60 lamps with equal spacing. It is terrible to edit/tweak that directly in the layout file. That's why I added the scripting routines. To make my life easier. I'd bet other people would benefit from it as well.

**Comment by felipesanches** [comment]
Of course, an SVG layout system such as the one described at #386 would be much better than what we have nowadays... I actually have an SVG file for this computer panel layout, but converting that SVG into a MAME layout XML file is just too much work do be done manually.

**Comment by happppp** [comment]
Let me advice you on an efficient way to edit .lay: Make a copy of the
layout file, put it in mame exe folder/artwork/patinho/patinho.lay
Then open that file in an editor and start MAME running the patinho
machine. Every time you want to check your changes, save and simply press
Shift+F3 to refresh MAME.

With your script, every change needs a recompile.

**Comment by felipesanches** [comment]
hmmm... that's interesting! I think then I would adopt a mixed approach. Each change would require not a rebuild, but a re-run of my script + SHIFT-F3 (that way, I have a more semantic control of the placement of elements while benefiting from the real-time feedback)

**Comment by rb6502** [comment]
Don't the handheld games in fact use SVGs directly as layouts now?

**Comment by happppp** [comment]
Yup, it depends on the SVG*. Felipe could you show it?

*AFAIK embedded fonts and pictures are not possible yet, correct me if I'm
wrong. This means text labels will have to be made of bezier curves and
photo-realistic artwork isn't possible.

**Comment by galibert** [comment]
Pictures will happen eventually.  Fonts won't, but you can "convert to
path" in inkscape without loss or difficulty.  And that way the font is not
going to change from one system to another.

  OG.

**Comment by felipesanches** [comment]
https://github.com/felipesanches/PatinhoFeio/blob/master/SVG/Painel_Frontal_PatinhoFeio.svg

**Comment by happppp** [comment]
That looks great!
You'll need to substitute the embedded font though. I'd also cut out the
upper half, the button panel will show up very small on a widescreen
otherwise.

**Comment by felipesanches** [comment]
yeah... I've been thinking about that. Perhaps we should have a selection of views for a given machine so that the user could alternate between different areas of a panel like this. Also, how could I accomodate on screen both the computer front-panel rendering and the peripherals of the computer, such as the decwriter teletype ?

**Comment by happppp** [comment]
Peripherals with their own layout, attached to the 'parent' layout? It's a
good idea, but not possible with the current system.

**Comment by felipesanches** [comment]
Sooner or later I'll upload an SVG layout, so I'm giving up on adding the python script to the build system. Closing.

**Pull request closed without merging**
