### PR TITLE
Correct Daytona USA Year (Exclude Daytona USA Deluxe '93)

### PR DESCRIPTION
**Pull request by sjy96525**
Daytona USA titlescrreen says 1994 and released date is March 1994, Daytona USA Deluxe '93 titlescrreen says 1993.

### CODE REVIEW

**Comment by rb6502** [comment]
"Deluxe '93" is a third-party hack and so it cannot have come out before the main set.  Find out when it was actually released.

**Comment by happppp** [comment]
Daytona USA 1st release was Japan-only in 1993. Wide release was in 1994.

**Comment by rb6502** [comment]
So the parent "daytona" set should still be 1993 though, being Japan Rev A., right?

**Comment by happppp** [comment]
No, revision A is probably from 1994. I was digging through MAME history for proof that daytona93 is a 3rd party hack, but actually think it's likely that this is the 1st release. It should simply be named "Daytona USA (Japan)", it's misleading to name it "Daytona USA Deluxe '93" for being dumped from a deluxe cabinet 1993 version.

**Comment by rb6502** [comment]
Oh, good grief.  Yeah, in that case it should be renamed "Daytona USA (Japan, Deluxe Cabinet, Original)" and given the set name "daytonao" or something similar.

**Comment by DavidHaywood** [comment]
the To the MAXX sets and such should also be marked as hack tho, as they're Kyle Hodgetts things IIRC

**Comment by DavidHaywood** [comment]
based on the number of sets that are 'revision a' with no 'no revision' versions of the same roms we are missing an awful lot of sets tho.

**Pull request merged**
