### PR TITLE
c140.cpp: Update data bus behavior and support 12 bit PCM, Verified from assault(namcos2) schematics

### PR DESCRIPTION
**Pull request by cam900**
Add/Update notes, Use shorter/correct type values, Fix address/data bus bits, Modernize save states, Fix spacing, Reduce unnecessary lines, duplicates, Move little endian interface in c140.h, Move bankswitching and address/data decoding behavior in each drivers

namcos2.cpp, namcos21*.cpp: Fix c140 ROM loading, mirrored maps
namcos2.cpp: Implement c140 ROM address/data decoding logics

vgmplay.cpp: Fix C140 compatibility

### CODE REVIEW

**Comment by superctr** [comment]
Should the sample ROM data bus just be treated as 16-bit? Afaik (from Assualt schematics) the least significant 4 bits of each sample are stored interleaved in a "third" ROM bank with some decode logic sending the correct nibble to the chip. Since this rom have been unpopulated in every PCB I have seen, I'm not sure if it matters but it might be good to be correct from the beginning and emulate this decode logic.

**Comment by smf-** [comment]
The banking should be moved out of the sound chip. Any address bit
twiddling or nibble swapping should be done with an address map/rom load.

**Comment by cam900** [comment]
TODO: It has noisy sound after this PR, I will fix later and reopen the review for this PR.

**Comment by superctr** [comment]
I think in the long run C219 should be split from C140. Btw, the C219 uses the [same "mu-law" algorithm](https://github.com/mamedev/mame/blob/e64edf6c7127fb8291a157026f3ac72e38c78d80/src/devices/sound/c352.cpp#L367-L382) as the C352, it's extensively used by Knuckle Heads.

**Comment by p1pkin** [comment]
is there was made any attempts to test this PR / code at practice, or this was blind written ? I got a bunch of compiler errors

> Compiling src/mame/drivers/namcos21.cpp...
../../../../../src/mame/drivers/gal3.cpp: In member function 'void gal3_state::gal3(machine_config&)':
../../../../../src/mame/drivers/gal3.cpp:683:14: error: 'class c140_device' has no member named 'set_bank_type'
  683 |  m_c140_16g->set_bank_type(c140_device::C140_TYPE::SYSTEM21);    //to be verified
      |              ^~~~~~~~~~~~~
../../../../../src/mame/drivers/gal3.cpp:683:41: error: 'c140_device::C140_TYPE' has not been declared
  683 |  m_c140_16g->set_bank_type(c140_device::C140_TYPE::SYSTEM21);    //to be verified
      |                                         ^~~~~~~~~
../../../../../src/mame/drivers/gal3.cpp:688:14: error: 'class c140_device' has no member named 'set_bank_type'
  688 |  m_c140_16a->set_bank_type(c140_device::C140_TYPE::SYSTEM21);
      |              ^~~~~~~~~~~~~
../../../../../src/mame/drivers/gal3.cpp:688:41: error: 'c140_device::C140_TYPE' has not been declared
  688 |  m_c140_16a->set_bank_type(c140_device::C140_TYPE::SYSTEM21);

**Comment by rb6502** [comment]
The compile issues with this were blocking top of tree.  Please compile and run changes before submitting them.

**Comment by cam900** [comment]
Fixed in https://github.com/mamedev/mame/pull/6659.

**Pull request merged**
