### PR TITLE
Discrete fixes

### PR DESCRIPTION
**Pull request by DerrickRenaud**
Fixed DISC_555_TRIGGER_DISCHARGES_CAP option in DISCRETE_555_MSTABLE.  This fixes the sound in Amazing Maze (maze) so that it plays for more then 30s.

Fixed filenames in DISCRETE_CSVLOGx and DISCRETE_WAVLOGx making them function again.

### CODE REVIEW

**Comment by cuavas** [comment]
Why the change in filenames?  I would've thought having the tag would be useful, especially if a system instantiates multiple instances of the discrete sound device.  You can use `some_device.basetag()` to get just the last component of the tag if you're trying to avoid colons causing an issue on Windows.

**Comment by DerrickRenaud** [comment]
The tag is usually always called “discrete” so the filename would be “discrete_discrete_0.”  There is (probably) never going to be more then 1 discrete system, so there is no real need for the tag.  Also using the tag requires the driver to have used valid file characters, which I do not believe is checked.

**Comment by cuavas** [comment]
The characters in tags are restricted by validity checks.  Only lowercase English letters, decimal digits, `_`, `.` and `$` are permitted (`:` and `^` are used for root/separator and parent, respectively, so they won't appear in base tags).  Always using the tag `discrete` is a bit of a problem in and of itself - it's not very descriptive.

**Comment by DerrickRenaud** [comment]
Personally I feel this is way too much thought for something that is only used for a temporary debug log to observe individual nodes and would never be used in submitted code.  However MAMEDev wants to fix it is fine by me. 

FWIW, there are 5 other devices that can make wav logs and they all use fixed names.  Discrete just needs to add a number at the end for when multiple wav log nodes are used, which I did not even test to see if it still works.  Hmmm.

As far as all discrete devices being called "discrete," that does not bother me.  They are usually a discrete circuit on the game pcb.  Even if the circuit was on multiple boards, it would still be emulated by 1 discrete device.

I had no intention of opening up a can of worms and I do not plan to get back to full time MAME coding any time soon, so feel free to resolve these issues as the team sees fit.

Thank you

**Comment by cuavas** [comment]
Belatedly, it's never safe to assume there will only be one instance of a device.  Slots already wreak havoc with this assumption, where you can have things that look a lot like an entire system instantiated as a subdevice (e.g. PC compatibility cards for Amiga and Apple II, or the IE-15 terminal).  We're also slowly moving towards enabling a model where driver devices aren't root devices by necessity, so it will be possible to instantiate more than one in a single emulation instance.

**Pull request merged**
