### PR TITLE
Fixed palette in Battles (set 1)

### PR DESCRIPTION
**Pull request by MASHinfo**
Tafoid found the broken palette in Battles (set 1) , while i fixed the length of the proms.
This must correct this!

### CODE REVIEW

**Comment by happppp** [comment]
Could you please make your commit messages more meaningful?
Describe the changes instead of this:

   - Update galaga.cpp
   - Update xevious.cpp
   - Update xevious.h

**Comment by MASHinfo** [comment]
Ok. I will add some test mext time. But is there a way to merged all in one
for a 'Pull requests' viva WEB base edit?

**Comment by happppp** [comment]
Merge them in your git client before submitting the PR.

**Comment by stilett0** [comment]
@happppp as he said, he's using github.com, not a git client.

**Comment by cuavas** [comment]
It doesn't matter, we still need atomic updates with descriptive comments.  We can't accept more pull requests like this.

**Pull request merged**
