### PR TITLE
new sets from Sean Riddle, mostly NOT WORKING for now

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING
----
Gachinko Contest! Slot machine TV (Japan) [Sean Riddle, Peter Wilhemsen, ShouTime, David Haywood] (actually, no BIOS is dumped yet, but this means the carts don't have to be orphaned)
Shredmaster Jr (NTSC) [Sean Riddle, David Haywood]
Golden Tee Golf (JAKKS Pacific TV Game) [Sean Riddle, David Haywood]
Cars 2 (JAKKS Pacific TV Game) [Sean Riddle, David Haywood]
Toy Story Mania (JAKKS Pacific TV Game) [Sean Riddle, David Haywood]
V.Baby [Sean Riddle, Clawgrip]
Playskool Heroes Transformers Rescue Bots Beam Box (Spain) [Sean Riddle, Clawgrip]
Virtual Ping Pong (Conny / SDW Games) [Sean Riddle, David Haywood]
Konami Collector's Series Arcade Advanced [Sean Riddle, David Haywood]
Teenage Mutanat Ninja Turtles Hero Portal [Sean Riddle]
Star Wars Blaster Strike [Sean Riddle]
Handy Boy 11-in-1 (TV Play Power) [Sean Riddle, GameHistory.org]

new WORKING
----
InterAct Complete Video Game 89-in-1 [Sean Riddle, David Haywood]

new NOT WORKING Software List
----
gcslottv.xml:  Aladdin TV [Sean Riddle, Peter Wilhemsen, ShouTime, David Haywood] 
gcslottv.xml:  Ginginmaru TV [Sean Riddle, Peter Wilhemsen, ShouTime, David Haywood] 
gcslottv.xml:  Salaryman Kintaro [Sean Riddle, Peter Wilhemsen, ShouTime, David Haywood] 
gcslottv.xml:  Moju-o TV [Sean Riddle, Peter Wilhemsen, ShouTime, David Haywood]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
btw I could do with name translations on these
http://www.seanriddle.com/slotmachinecarts.JPG

they don't seem to follow the standard Takara cart numbering schemes (no proper ident code present anywhere on them, I guess because they're made by Sammy)

**Comment by cuavas** [comment]
* The first one is obviously Aladdin TV.
* The third one is サラリーマン金太郎/Salaryman Kintarō (presumably based on the manga).
* The fourth one is 猛獣王TV/Mōjū-ō TV.

**Comment by DavidHaywood** [comment]
Title screens if they help, although I guess they show the same. 
http://mamedev.emulab.it/haze/pics2019/c01black.png (Aladdin TV)
http://mamedev.emulab.it/haze/pics2019/c01orange.png (still unknown?)
http://mamedev.emulab.it/haze/pics2019/c05red.png (Salaryman Kintarō)
http://mamedev.emulab.it/haze/pics2019/c07yellow.png (Mōjū-ō TV.)

**Comment by cuavas** [comment]
Oh, that’s more legible – the other one is [ギンギン丸TV/Ginginmaru TV](http://www.marukin777.com/777town/ginginmaru.html).

**Comment by eanbowman** [comment]
@DavidHaywood I have a dump from a VT25xx Famiclone that I picked out of the trash. All custom made games on it. Very strange and I was wondering what the format is.

https://twitter.com/eanbowman/status/1203794876493651968?s=20

(See further down the thread for a Gdrive link)

**Comment by DavidHaywood** [comment]
@eanbowman Thanks
I'll add it as non-working,  Since it's an SPI rom I have a feeling it might boot from something else in the glob, but we'll see.

Also I can't find any gdrive link, the thread you link only has the one reply?  If you can point me in the right direction on Twitter that would be handy :-)

**Pull request merged**
