### PR TITLE
New working clones

### PR DESCRIPTION
**Pull request by clawgrip**
------------------
Sector Zone (set 2, encrypted, Tecfri hardware) [Juan Romero, ClawGrip, David Haywood, Recreativas.org]

### CODE REVIEW

**Comment by clawgrip** [comment]
This set uses an HD46802P instead of the NSC8105. It would be nice to declare the exact HD46802P for it, but it isn't supported by MAME as a 6802 variant, and I don't know what his specs are, so I'd appreciate if someone could do it.

Thanks!

**Comment by ajrhacker** [comment]
HD46802 is pretty much just a second source for MC6802. Most HD46xxx and HD68xx ICs, with the exception of a few HD6805 MCUs, have direct equivalents in the MC68xx line (though some were actually second-sourced by Motorola from Hitachi rather than vice versa). The HD63xx CPUs & MCUs, on the other hand, are all considerably enhanced CMOS versions.

**Comment by clawgrip** [comment]
Thanks!

But, for this specific set, if I move from:
	NSC8105(config, m_mcu, XTAL(18'432'000) / 6);
	m_mcu->set_addrmap(AS_PROGRAM, &seicross_state::mcu_no_nvram_map);
	m_mcu->set_addrmap(AS_OPCODES, &seicross_state::decrypted_opcodes_map);

To :
	M6802(config, m_mcu, XTAL(18'432'000) / 6);
	m_mcu->set_addrmap(AS_PROGRAM, &seicross_state::mcu_no_nvram_map);
	m_mcu->set_addrmap(AS_OPCODES, &seicross_state::decrypted_opcodes_map);

The game won't boot, and it seems it's because the encrypted opcodes... Why?

I'd apreciate a little help with this.

Thanks again!

**Comment by DavidHaywood** [comment]
I wouldn't worry too much about it for now, just leave a note.  These 3rd party manufactured boards often used equivalent parts, or regular marked versions of customs (the Tecfri Namco boards are similar)

I wonder if the 'encrypted' Frisky Tom was also a Tecfri board.

**Comment by Osso13** [comment]
I'll apply this directly. Apparently the 'decryption' used by the friskytb just bitswaps the opcodes to the expected encoding by the NSC8105 CPU. If you don't do this the opcodes match the M6802-expected opcodes encoding.

**Pull request closed without merging**
