### PR TITLE
ninjakd2.cpp: Replaced mnight with World version, Kawakus license now…

### PR DESCRIPTION
**Pull request by system11b**
… mnightj [frsj8112, system11]

nbmj8688.cpp: Corrected Second Love dips as per manual (minor corrections) [system11]

### CODE REVIEW

**Comment by cuavas** [comment]
Why the changes to the labels for mnightj? Do we have confirmation that the Japanese version has the same labels as the world version? In many cases they're actually different.

**Comment by system11b** [comment]
I believe the set in MAME came from a bootleg, they're actually clones aside from minor changes in the sound area, some start the numbering at 20, some are the same, some have no numbers etc.  
Here are some originals:

World:
http://v2.pxl.se/i/0sZ.jpg

Japan:
http://blog.system11.org/wp-content/uploads/2016/06/20160606_mutant_night.jpg

An example bootleg (this set matches Japan dump):
http://blog.system11.org/wp-content/uploads/2016/03/mutant_night_bl_fix1.jpg

There are at least 3 different bootleg types out there.

**Comment by cuavas** [comment]
So the japan set and bootleg have identical ROM contents?

**Comment by system11b** [comment]
That particular bootleg pictured did, I can't speak for the others.  In theory I should have added the Artic bootleg set as another driver entry, but it's not really of any value - same code, only difference would be removing one of the sound chips as that bootleg skipped one of them:
http://blog.system11.org/?p=1917

Owner of the world rev board dumped all the chips and only 13.b10 differed from the MAME set in terms of checksums.

**Pull request merged**
