### PR TITLE
Fix for Mametesters BugID #1455

### PR DESCRIPTION
**Pull request by Pitou1**
Patch that calculates offsets making the game playable.

### CODE REVIEW

**Comment by happppp** [comment]
That's a lot of extra code for correcting coords. Is this trial&error, or
did you study the 68k disasm and reverse the algorithm?

**Comment by Pitou1** [comment]
Hello,

I did not reverse the 68k code completely. It takes a value from 0 to 255 and calculate the hit/explosion directly on the screen graphic. I would have to access the machine's memory to get the calculated number and again I'm not sure it would have been precise.

What I did, is built a table of offsets by looking at the hits/explosions on every part of the screen compared to the crosshait position (0 - 255) and found out that it follows a linear function. The linear function differs depending of the screen region vs player number. That's the reason for the extra code.

Thank you.

Pitou!

**Comment by mamehaze** [comment]
the reason this happens is because the guns on the original (which are actually gun-shaped analog sticks) were not centered, rather one was to the left, the other center, the final one to the right.

the game software attempts to compensate for this positioning by moving the cursor more quickly on the opposite side of the screen to the gun.

the problem with fixing it the way it's been fixed here is if you attached guns in the original positions the cabinet had them then the alignment would be off, as you're changing the actual value returned to the emulated machine to match MAME's mapping.

it might actually make more sense to change the crosshair drawing function instead?

**Comment by Pitou1** [comment]
@mamehaze, right, that's what I also understand. The guns are placed at the edges for Player 1 and 3, Player 2 is centered and is fine.

I also thought of creating a 3D array offsets table for P1 and P3 and do something like this:

static const UINT8 offset_P1[] =
{
      { {x,y}, {x,y}..... },
      { {x,y}, {x,y}..... },
      ....
};

In the function:

pos_value_x = ioport("GUNX1")->read();
pos_value_y = 255 - ioport("GUNY1")->read();

// For X axis
m_lghost_value = pos_value_x + offset_P1[pos_value_x][pos_value_y][0];

// For Y axis
m_lghost_value = pos_value_x + offset_P1[pos_value_x][pos_value_y][1];

It's just that the table would be huge,

either (255x255x2) = 128k, probably the most accurate, but lots of repetitive datas and 128k of memory.

or if I just take regions, that would be about (51x51x2) = 5202. The screen is divided in 5x5 squares. Again the table would be very big in the c++ code.

Tell me what you think.

Thanks.

Pitou!

**Comment by mamehaze** [comment]
well what you actually want to do is find the 68k code that applies the offset correction and see what calculation it does, not build massive tables.

applying the offset in the crosshair drawing is definitely a more involved task, as that is handled at core level, so the actual crosshair functionality in MAME would need extending so that mappings that aren't 100% linear can be used, that is non-trivial.

The problem with changing the values that are returned on the ports, as I said, is that it will no longer work with guns hooked up in the original positions; the guns return a value of 0x00 - 0xff, that isn't scaled by the guns.  If you hooked up the original guns in their original positions and turned the crosshair off the shots would be in the correct place on the screen with the code we have now (the crosshair would not be, but as you'd be using the original guns you wouldn't need it)

I'll leave it up to other people to decide, but IMHO this fix is in the wrong place and the actual crosshair functionality of MAME needs improving to take into account possible non-linear scaling for guns that aren't centered on the original cabinets.

**Comment by mamehaze** [comment]
The problem gets more complicated however if you consider the user might want to use a regular gun, pointed straight at the screen for player 1, or turn off MAME's internal crosshair and use the OSD mouse pointer; in that case you would have to alter the return value the way you're doing now.

The cost of that is breaking support for the gun in the real position tho.. 

As you can see it's not really a 'simple' issue.

**Comment by Pitou1** [comment]
ok I understand what you mean now about the original guns hook in the original positions.

Thanks for the explanation.

I wasn't sure at first if that was the right way and that's why I asked on Mametesters if that would be acceptable and got somewhat a positive answer from a developer (Osso).

Is there another way? Can the cheat system be used? LUA plugin?

That way we keep everything original as expected,, but users could apply something temporary that make the game playable.

Pitou!

**Comment by mamehaze** [comment]
I'm not sure, it needs some thought for sure.

It might be that the devs are happy to accept this as a solution for 'most common use case' (ie somebody running the game on a PC)  however solutions that break trying to use the game with the original setups are generally frowned upon.

I guess a gun type input that can compensate either way (either in the cross hair drawing, or the input port reading depending on user preference) could be an option, but I'm in no way familiar enough with any of the code to give you guidance there.

would probably be a good idea if somebody else chipped in tho, don't want to lead you down the wrong path.

**Comment by mamehaze** [comment]
for this specific game it might actually be possible to get a better alignment by using the ingame calibration, but when asked to shoot the center, instead shoot somewhere about 60-70% along, because I assume the game uses those values in it's internal correction.

**Comment by Pitou1** [comment]
I tried that using the in-game calibration system, but could not get good results.
Actually, the game only asks for top-left and bottom-right corners.

**Comment by Pitou1** [comment]
> I guess a gun type input that can compensate either way (either in the cross hair drawing, or the input port reading depending on user preference) could be an option, but I'm in no way familiar enough with any of the code to give you guidance there.

That's a good idea. I'm ready and willing to help coding any solution that would do the job the right way.

Who's in charge of the input system these days?

Let's decide the proper way of doing it and let's code, if there is any interest! :)

Thank you.

Pitou!

**Comment by mamehaze** [comment]
Ah, that's a shame, most do have the 'center' input when calibrating, for reasons similar to this..

looks like this game really was designed around having the guns at those exact positions / angles from the screen.

which means there's no simple solution.. you either have it broken for PC users, or you have it broken for people who want to rebuild the original cabinet using MAME.  I suppose you could have a configuration switch to decide if the 'correction' is applied but it might still make more sense to try and do this as a core concept rather than per-driver kludgery..

**Comment by Pitou1** [comment]
I understand and agree with you mamehaze.

Again, thanks very much for the explanations and clarifications.

Although I've put a lot of work and many hours in this patch, let's reject this pull request and think of something else. :)

Pitou!

**Comment by mamehaze** [comment]
Well I don't think the whole thing has been a waste of time, it's been an interesting investigation into the problem at least, because on the surface it does seem like a simple and obvious fix until you consider why it acts as it does.

**Comment by Pitou1** [comment]
Right. I also learned a lot through the process.

**Comment by rb6502** [comment]
Is there some reason we couldn't just add a fake dip that allowed turning this correction off for the 1 person in all of history that's going to run MAME with the original h/w for this?  I mean, this seems like such an obvious win for 99.9% of MAME users that I can't believe we're going to discard it.

**Comment by happppp** [comment]
I'm ok with this PR actually

**Comment by happppp** [comment]
Anyway, let me take care of it. I will also add the option to disable it.

Within our aim for accurate emulation, there are limits to workarounds like
these. This one is fine I think, and looks like RB is ok with it too.

**Comment by Tafoid** [comment]
There is precedent for Configuration Options for games with 'real' controls and other options.  The example I'm thinking of is 720 (atarisy2.cpp).

**Comment by rb6502** [comment]
Yeah, and with MESS merged in we have access to the Machine Configuration to avoid polluting any real DIP switches the game might have.

**Comment by etabeta78** [comment]
FWIW, the confsetting macro were available in past MAME too, see e.g. the
Astro Blaster bg color implementation (based on some jumper wirings that
was inaccurate to implement as Dipswitch ;) )

    f.

**Comment by Pitou1** [comment]
I'm really happy this has been merged,

This encourages me a lot and my next step will be to fully reverse the m68k code.

Thank you very much everyone!

Pitou!

**Pull request merged**
