### PR TITLE
avoid "Redundant default attribute value assignment" in hash files (nw)

### PR DESCRIPTION
**Pull request by firewave**

### CODE REVIEW

**Comment by rb6502** [comment]
What is generating this error?  The documentation value isn't as good with fewer tags, IMO.

**Comment by firewave** [comment]
It was a CLion inspection.
The `supported="yes"` is obviously unnecessary, but I see value in the other things. But since it was just a few instances I thought it might make things more consistent across the board.

**Comment by angelosa** [comment]
Wow this slipped thru.
How @firewave is supposed to mark something as tested without `supported="yes"` then, I'm really curious to hear.

**Comment by cuavas** [comment]
Right now, the `supported` attribute has an implied value of `yes` in the DTD, so front-ends etc. must treat the `supported` attribute not being present the same way they treat `supported="yes"`.  In general though, I don’t favour blindly removing default attributes, as they often make things clearer.

**Comment by cuavas** [comment]
It may be worth considering whether we want to change the implied value for `supported` in the DTD to something meaning “untested but we’ll assume it works”, but that would be a serious change, with far-reaching effects on the whole ecosystem.

**Pull request merged**
