### PR TITLE
Fixed 280-ZZZAP graphics cut off

### PR DESCRIPTION
**Pull request by MASHinfo**
Fixed the graphics cut off of the Racing guy in 280-ZZZAP (MT #04716).
Incresed the horizontal resolution by adding 32 pixel to MW8080BW_HTOTAL.
All screen raw params are defined in src\mame\includes\mw8080bw.h

### CODE REVIEW

**Comment by happppp** [comment]
This is an inaccurate workaround. For a small bug like this? no thanks :)

**Comment by MASHinfo** [comment]
To my understanding, the SCREEN RAW PARAMETER are for the video device and can be
adjusted by potentiometers (slider or knob) individually by the manufacturer or a local technician.
So my fix is correct!

**Comment by cuavas** [comment]
No they aren't. Blanking signals are generated by logic on the game board and can't be changed without hardware and/or program modifications.

**Comment by happppp** [comment]
No, raw params are for the video signal generation on the game PCB.
You just changed the timing of the horizontal counter, this is not
something you can do on a tv/monitor.

**Pull request closed without merging**
