### PR TITLE
New NOT_WORKING software list additions

### PR DESCRIPTION
**Pull request by clawgrip**
---------------------------------------
tvgogo.xml:
  Basketball (EU) [TeamEurope, ClawGrip]

### CODE REVIEW

**Comment by cuavas** [comment]
Can you please mention the name of the affected software list in your commit messages as well as the titles of the additions?  It makes it easier to follow the commit log.

**Comment by clawgrip** [comment]
Done! (it's ok like that?)

**Comment by cuavas** [comment]
Well it’s in the pull request description for this one, but it would be nice to have it in the commit messages as well going forward.  Exact format doesn't matter too much – I’d be fine with any of these formats:

If all the additions are in one software list:
```
New NOT_WORKING software list additions (tvgogo.xml)
---------------------------------------
Some entries [Credit for These Entries]
Some other entries [Credit for These other Entries]
```

More general case that supports multiple affected software lists:
```
New NOT_WORKING software list additions
---------------------------------------
tvgogo.xml: Some entries [Credit for These Entries]
vsmile_cart.xml: Some other entries [Credit for These other Entries]
```

```
New NOT_WORKING software list additions
---------------------------------------
tvgogo.xml:
Some entries [Credit for These Entries]
Some other entries [Credit for These other Entries]
vsmile_cart.xml:
Even more entries [Credit for Extra Entries]
```

**Comment by clawgrip** [comment]
Haze already added this one!

**Pull request closed without merging**
