### PR TITLE
Apple II added 240 (238 working 2 not working), removed 10

### PR DESCRIPTION
**Pull request by A-Noid33**
Metadata cleanups and parent/clone relationships.  Renamed sets for consistency between software lists and other dumps.

New working software list items (apple2_flop_clcracked.xml) 
-------------------------------
A Christmas Adventure (version 2.0) (4am crack)
Ace Detective (revision 3) (4am crack)
ACT Preparation Series (version 1984) (4am crack)
Adventures in Problem Solving: A Trip to London (4am crack) 
Adventures in Problem Solving: Alice's Adventure in Numberland (4am crack)
Adventures in Problem Solving: Marathon (4am crack) 
Adventures in Problem Solving: The Treasure of Forest Isle (4am crack) 
Alfred's Music Achievement Series: Level I (4am crack) 
Algebra Volume 3 (revision 4, 1984) (Britannica) (4am crack) 
Aliencounter and Face Flash (revision 2) (4am crack) 
Alligator Mix (version 1985 revision 2) (4am crack) 
Alphabet Fun: Big and Little Letters (4am crack)
Alphabet Zoo (revision 2) (4am crack)
Alphabet Zoo (revision 3) (4am crack)
Animal Photo Fun (4am crack)
Animal Stories IV (4am crack)
Architectural Review &amp; Testmaker (version 2.0) (4am crack) 
Arizona Mix (A-335 version 1.0) (4am and san inc crack) 
Basic Number Facts: Practice (4am crack)
Battling Bugs and Concentraction (revision 2) (4am crack) 
Beyond Pinball (version 1.1) (4am crack)
Billboard (4am crack)
Black Belt (revision 2) (4am crack)
Broadsides (revision 1) (4am crack)
Broadsides (revision 2) (4am crack)
Broadsides (revision 3) (4am crack)
Broadsides (revision 4) (4am crack)
CAAT Skill Tester: Decimals (4am crack)
CAAT Skill Tester: Fractions: Addition and Subtraction (4am crack) 
CAAT Skill Tester: Fractions: Multiplication and Division (4am crack) 
CAAT Skill Tester: Whole Numbers (4am crack)
Car Builder (revision 4) (4am and san inc crack)
Career Scan IV (version 09.15.83N) (4am crack)
Cash Versus Credit Buying (4am crack)
Cause and Effect (version 02.15.85) (4am crack)
Change Maker (4am crack)
Child Development 2: Theories of Child Development (4am crack) 
Child Development 5: Infancy and Toddlerhood (4am crack) 
Classification of Objects (4am crack)
Classmate (version 2.0) (4am crack)
Clowning Around (revision 2) (4am crack)
Collamore Castle: Strategies for Problem Solving Level 1 (4am crack) 
Comparison Kitchen (4am crack)
Computer Biology Lab: Clam Dissection (4am crack)
Computer Biology Lab: Crayfish Dissection (4am crack) 
Computer Biology Lab: Earthworm Dissection (4am crack) 
Computer Biology Lab: Frog Dissection (4am crack)
Computer Biology Lab: Starfish Dissection (4am crack) 
Computers in Government (A-122 version 1.0) (4am crack) 
Continents and Countries (4am crack)
Copy II Plus (version 1.0) (4am crack)
Cotton Tales (version 1990) (4am crack)
Cribbage/Solitaire (4am crack)
Crosscountry Canada (revsion 1, 1986) (4am crack)
Crosscountry Canada (version 4.0) (4am crack)
Crosscountry USA (version 4.0) (4am crack)
Crosscountry USA (version 5.1) (4am crack)
Crystal Caverns (revision 0) (4am crack)
Cyborg (version 1) (4am crack)
Dancing Dinos (4am crack)
Dataquest: The Presidents (A-140 version 1.1) (4am crack) 
Dinosaur Dig (4am crack)
Dinosaurs (version 1.0) (4am crack)
Dog Sled Ambassadors (A-339 version 1.0) (4am and san inc crack) 
Dragon Mix (version 1985) (4am crack)
Early Discoveries: Size and Logic (version 07.31.85) (4am crack) 
Early Games: Matchmaker (revision 2) (4am crack)
Effective Study Skills (4am crack)
Electric Circuits (revision 1) (4am crack)
Electric Circuits (revision 2) (4am crack)
Excel-A-Read (4am crack)
E-Z Learner (4am crack)
Farmfiler (version 03.11.83) (4am crack)
Fish Scales (version 4.0) (4am crack)
Following Written Directions (4am crack)
Fortress (revision 2) (4am crack)
Fraction Fever (revision 1) (4am crack)
Fractions (version 3.0 04-10-82) (4am crack)
Fun with Directions (version 1984) (4am crack)
Genesis: The Adventure Game Creator (4am crack)
Genetic Engineering (4am crack)
German Vocabulary Builder (4am crack)
Glidepath (version 1.0) (4am crack)
Go to the Head of the Class (Media Materials release) (4am crack) 
Golf Classic and Compubar (4am crack)
Graphing (A-817 version 1.0) (4am crack)
Graphing Equations (version 1.3) (4am crack)
Guitar Wizard (version 11611) (4am crack)
Gulp and Arrow Graphics (4am crack)
Hard Hat Mack (4am and san inc crack)
Human Body Exploration (4am crack)
Improving Your Memory (4am crack)
Industrialism in America (4am crack)
Inferential Anne: Level II (4am crack)
J-Bird (4am crack)
Joe Theismann's Pro Football (4am crack)
Key Signatures (4am crack)
Keyboard Golf (4am and san inc crack)
Kids at Work (4am crack)
Kitchen Planner (4am crack)
Les Sports (4am crack)
Let's Explore Word Processing (Media Materials) (4am crack) 
Library Adventure: Blue Level (4am crack)
Library Magic (revision 0) (4am crack)
Magic Slate II: 20-Column Version (version 1.0) (4am crack) 
Magic Slate II: 40-Column Version (version 1.0) (4am crack) 
Magic Spells (version 1.1) (4am and san inc crack) 
Math Word Problems (4am and san inc crack)
Mathematics Action Games: Picture Parts: Basic Operations (4am crack) 
Mathematics Courseware Series: Adventures in Addition and Subtraction 3 (4am crack) 
Mathematics Courseware Series: Decimal Deli 2 (4am crack) 
Mathematics Courseware Series: Bicycling Through Decimals 3 (4am crack) 
Mathematics Courseware Series: Division 2 (4am crack) 
Mathematics Courseware Series: Division 3: The Prairie (4am crack) 
Mathematics Courseware Series: Fantastic Fractions 1 (4am crack) 
Mathematics Courseware Series: Electrifying Fractions 2 (4am crack) 
Mathematics Courseware Series: Fractions 3 (4am crack) 
Mathematics Courseware Series: Fractions 5: The River (4am crack) 
Mathematics Courseware Series: Mighty Multiplication 2 (4am crack) 
Mathematics Courseware Series: Percent 1: Get The Percent (4am crack) 
Mathematics Courseware Series: Percent 2 (4am crack) 
MasterType (version 1.7) (4am crack)
Medalist Series: Black Americans (version 04.13.84) (4am crack) 
Medalist Series: Presidents (version 11.23.84) (4am crack) 
Medalist Series: Women in History (version 11.21.83) (4am crack) 
Microtyping II (4am crack)
Mind Puzzles (H-102 version 1.0-1984.05.25) (4am crack) 
Miner 2049er (revision 1) (4am crack)
Modeling (A-823 version 1.0) (4am crack)
Money! Money! (version 02.05.87) (4am crack)
Monkey Business (revision 2) (4am crack)
Monsters and Make-Believe (version 1.1) (4am crack) 
Music Construction Set (revision 2) (4am and san inc crack) 
Music Tutor (Passport Designs) (4am crack)
Mystery Mazes Case 3: Castle Clues (4am crack)
Painter Power (4am crack)
People of the Old Testament (4am crack)
Perception (version 3.1) (4am crack)
Personality Profile 2 (4am crack)
Physical or Chemical (4am crack)
Picture Perfect (version 1987) (4am crack)
Place Value: Ones, Tens, and Hundreds (4am crack)
Plato's Cave (4am crack)
Please Help Me: Spelling (4am crack)
Polls and Politics (A-820 version 1.0) (4am crack) 
Prescriptive Math Drill (version 04.13.84) (4am crack) 
Primary Reading: Following Written Directions (4am crack) 
Primary WordMath (4am crack)
Prime Ducks (4am crack)
Pro Golf Challenge (4am crack)
Problem-Solving Strategies (H-103 version 1.0-1984.09.25) (4am crack) 
Quizagon (revision 0) (4am crack)
Rainbow Painter (4am crack)
Rascal Takes A Ride Home (4am crack)
Rascal Takes A Ride to School (4am crack)
Read & Rhyme (4am crack)
Reading for Understanding: Native Americans (4am crack) 
Reading Workshop: Grade 6 (Mindscape) (4am crack)
Return to Reading: The Black Stallion (4am crack)
Return to Reading: To Kill A Mockingbird (4am crack) 
Rhythm Write (4am crack)
Run Your Own Train (revision 2) (4am crack)
Scientific Simulations (version 1.0) (4am crack)
Sesame Street Crayon: Letters For You (version 1987-10-31) (4am crack) 
Shadow Hawk One (revision 1) (4am crack)
Shadow Hawk One (revision 2) (4am crack)
Shadows and Light (4am crack)
Shutterbug's Pictures (4am crack)
Sliding Block (revision 2) (Merit) (4am crack)
Social Studies: Africa (4am crack)
Sound and Vibrations (4am crack)
Space Journey: Planets and Stars (4am crack)
Spare Change (4am and san inc crack)
Spellakazam (revision 1) (4am crack)
Spelling Bee (version 1.1) (4am crack)
Spelling and Reading Primer (version 2.0.1) (4am crack) 
Square Pairs (version 1.0) (4am and san inc crack) 
Start Solving: Honeybear (4am crack)
Start Solving: Sam's Sticker Store (4am crack)
Start Solving: Tina's TV Show (4am crack)
Stickers (4am crack)
Stickybear Opposites (revision 2) (4am and san inc crack) 
Stickybear Opposites (800K 3.5") (4am crack)
Stickybear Printer (version 1) (4am and san inc crack) 
Stickybear Reading (revision 2) (4am and san inc crack) 
Stickybear Town Builder (revision 2) (4am and san inc crack) 
Stickybear Typing (revision 3) (4am and san inc crack) 
Stickybear Word Problems (revision 2) (4am and san inc crack) 
Story Maker (revision 2, 64K) (4am crack)
Strategies for Test Taking (4am crack)
Strategies in Problem Solving: Dinosaurs and Squids (4am crack) 
Strategies in Problem Solving: Spinners and Slugs (4am crack) 
Super-Text II Form Letter Module (version 1984) (4am crack) 
Tales From The Arabian Nights (4am crack)
Teddy Takes a Rain Walk (4am crack)
Test Construction and Review (4am crack)
The Art of Communication 2 (4am crack)
The Banking Simulation (4am crack)
The Banking Tutorial (version 5.2) (4am crack)
The Bare Facts on Composers Volume 2 (4am crack)
The Bare Facts on Composers Volume 3 (4am crack)
The Bare Facts on Intervals and Chords (4am crack) 
The Bare Facts on Music History (4am crack)
The Bare Facts on Notes, Rhythm, and Terms (4am crack) 
The Counting Bee (version 1.1, 26-FEB-82) (4am crack) 
The Cube (4am crack)
The Dream Machine (4am crack)
The Evelyn Wood Dynamic Reader (4am crack)
The Gem of Zephyrr (version 1.1.0) (4am crack)
The General Manager (version 2.0S) (4am and san inc crack) 
The General Manager (version 2.0Y) (4am and san inc crack) 
The Spy's Adventures in Europe (version 1986-09-30) (4am crack) 
The Story of Creation (4am crack)
The U.S. Constitution: Nationalism and Federalism (version 1984) (4am crack) 
Thinkers: Mathematics Unlimited Problem Solving (4am crack) 
Total Learning System (4am crack)
Troll Sports Math: Math Word Problems for Grades 4 to 6 (4am crack) 
Type Hype (revision 2) (4am crack)
Type Right on Your Apple IIe (4am crack)
Under Fire (4am crack)
U.S. Constitution Tutor (4am crack)
U.S. History: The Growth of a Nation (4am crack)
U.S. History: The Young Republic (4am crack)
Walt Disney Card &amp; Party Shop (4am crack)
Water Pollution (4am crack)
Werewolf!! (4am crack)
What's the Problem: Ace Reporter (4am crack)
What's the Problem: Chester and the Cheese (4am crack) 
What's the Problem: Where in the World? (4am crack) 
Wings Out of Shadow (4am crack)
Wizard of Words (version 1.0) (4am crack)
Word Scrambler and Spelling Tutor (4am crack)
Wordwise (4am crack)
WordWorx (4am crack)
Zenith (4am and san inc crack)
Zoo Master (revision 2) (4am crack)

New not working (apple2_flop_clcracked.xml)
-------------------------------
Mathematics Courseware Series: Addition and Subtraction 4: City Sights (4am crack) 
Mathematics Courseware Series: The Mysteries of Multiplication 3 (4am crack)

Removed (apple2_flop_clcracked.xml)
-------------------------------
Algebra Volume 3 (Revision 0) (imperfect clean crack) 
Algebra Volume 4 (version 1.1) (imperfect clean crack) 
Algebra Volume 6 (version 1.0) (imperfect clean crack) 
Dino Dig: Dictionary Skills (4am crack) (imperfect clean crack) 
In Search of the Most Amazing Thing (Revision 2) (imperfect clean crack) 
Pyramid Puzzler (imperfect clean crack)
Reading Workshop: Distant Views (imperfect clean crack) 
Reading Workshop: Running Free (imperfect clean crack) 
Space Journey (imperfect clean crack)
Story Maker (64K Version) (imperfect clean crack)

New working software list items (apple2_flop_orig.xml) 
-------------------------------
Copy II Plus (version 1.0)
Copy II Plus (version 2.2)
Galactic Gladiators

### CODE REVIEW

**Comment by A-Noid33** [comment]
@rb6502 I found 2 apple II disks from 4AM that cannot be read by any of the Apple II drivers in MAME.  I tried mounting the individual disks, too.  See Mathemathics Courseware Series in New not working above.  I rarely see loading errors, but I did notice that the file sizes were larger for these disks.

**Comment by cuavas** [comment]
Given there’s a lot of churn from stuff being moved around, I did a quick sanity check on the numbers from the diff.
```
$ egrep '^[+-]  +<software ' < /dev/clipboard | sort -k2 | egrep -c '^[-]'
849

$ egrep '^[+-]  +<software ' < /dev/clipboard | sort -k2 | egrep -c '^[+]'
1079
```

So there appears to be a net difference of 1079 - 849 = 230 net items added.  This doesn’t agree with the count in the PR title of 243 + 2 - 10 = 235.  There are also only 240 titles listed in the PR description.  Is this just a miscount in the title?

**Comment by cuavas** [comment]
There are a number of places you’ve put the title displayed on the title screen in a comment.  To make this available to the internal UI and to make it easier to search, it’s better to use `alt_title` info elements for this, e.g.
```xml
<info name="alt_title" value="Biology I Series: The Grasshopper" /> <!-- title screen -->
```

**Comment by rb6502** [comment]
In general, please try to do these in smaller batches, and separate cleanup churn commits from actually adding new stuff.  It's hard to sanity check stuff on this scale, especially a day or two before a freeze.

CC @galibert on the discs that don't work.

**Comment by cuavas** [comment]
Since it’s too big for GitHub to allow in-place comments:
* `apple2_flop_clcracked:sphtspell` has two parts with duplicate `part_id` of `Disk  Side ` – not filled in?
* `apple2_flop_clcracked:wizwords10` has a par with `part_id` of `Side - Royal registry of words` – is it missing the actual side?
* `apple2_flop_orig:wpappl20` has “Prodos” and “Dos 3.3” in `part_id` values – is this how it’s actually written on the labels, or is it incorrectly forcing title case for what should be “DOS 3.3” and “ProDOS”?

**Comment by A-Noid33** [comment]
@cuavas The count should be 240 added and 10 removed.  I did the title in a hurry yesterday, since I was very late for work.  I'll update the title.

**Comment by A-Noid33** [comment]
@cuavas I agree on the alt_title.  I started adding the alt_title to many entries, but I had already done the Biology I Series.   I'll update those entries.

**Comment by A-Noid33** [comment]
@rb6502 I was trying to get all the cracked Apple II lists up to date over the holidays.   They are caught up now, so no more big entries.   Going through all the consistency checks to try and get all the names consistent and parent / clone relationships took a huge amount of time.  When adding a new title, I also cleaned up all the meta data for other titles from that same publisher.  Will probably make MECC fully consistent next.

**Comment by A-Noid33** [comment]
@cuavas  Thanks for finding these.  I wrote a program to simplify creating softlist entries.  The "Disk Side" is a placeholder, and I must have missed updating them.  I probably need a better placeholder.

Agreed on the capitalization.  I had just capitalized the first letter.

I will fix the issues found below.  

> Since it’s too big for GitHub to allow in-place comments:
> 
> * `apple2_flop_clcracked:sphtspell` has two parts with duplicate `part_id` of `Disk  Side ` – not filled in?
> * `apple2_flop_clcracked:wizwords10` has a par with `part_id` of `Side - Royal registry of words` – is it missing the actual side?
> * `apple2_flop_orig:wpappl20` has “Prodos” and “Dos 3.3” in `part_id` values – is this how it’s actually written on the labels, or is it incorrectly forcing title case for what should be “DOS 3.3” and “ProDOS”?

**Comment by A-Noid33** [comment]
@cuavas @rb6502   Let me know if you find anything else.  Fixes pushed.

**Comment by cuavas** [comment]
@rb6502 this PR removed a number of older 4am cracks that were later found to be bad.  These are listed in the PR description.  I thought the previous thinking was that the hashes should be kept around somewhere so if they show up again in the future they could be identified easily.  Are you OK with them being removed from the cracked Apple II floppies list?

**Comment by cuavas** [comment]
Found another issues: “Keyboard Golf (4am and san inc crack)” is listed as an addition, but it isn’t – it was already in the software list and didn’t change.

**Comment by rb6502** [comment]
For non-software list ROMs, when we have a known bad dump of a ROM we just replace it.  I think modern bad cracks are conceptually similar enough to a dumper messing up that it works to handle them the same way (particularly since most 4am cracks are an automated process run against a new .WOZ dump).  Historical bad cracks do deserve inclusion, but we do want to make it clear if they're run that they're not going to be the best experience.

**Comment by cuavas** [comment]
> Found another issues: “Keyboard Golf (4am and san inc crack)” is listed as an addition, but it isn’t – it was already in the software list and didn’t change.

My bad, content of this one did change, I guess it’s another one where the previous crack turned out to be bad.

**Pull request merged**
