### PR TITLE
dragon: fix MT#7305

### PR DESCRIPTION
**Pull request by tlindner**
1. Add emulation of external pull up resistors on input pins.
2. Fix a save state for m_a_input_overrides_output_mask.

I'm not sure if this is the best way to accomplish this.

### CODE REVIEW

**Comment by ajrhacker** [comment]
This looks like the wrong idea for a fix. Why not change `coco_state::pia1_pa_r` instead?

**Comment by tlindner** [comment]
The internal PIA pull ups were not being applied for the code path of a valid ```m_in_a_handler()```.

If I switch to handle this in ```coco_state::pia1_pa_r()``` I would need to keep track of the DDR register in the coco driver. That seems like a separation violation.

**Comment by ajrhacker** [comment]
The handler may be "valid", but I don't think it's correctly implemented.

On a related note, please don't mark MT bugs as resolved based on unmerged commits.

**Comment by ajrhacker** [comment]
See 9c002bd2642a73e240d37f6c8528a22b880af590.

**Comment by smf-** [comment]
I don't think it's possible to correctly implement a handler with the
current code as the pia code expects you to return the value that should
be returned to the cpu.

However when you write, it takes input bits from the handler and merges
them in before calling the write handler

I think this is essentially wrong as if you set the ddr to output and
write a zero, then change the ddr to an input then the output should
change to a 1.

I know this is common on the c64 with disk turbo code that uses the cia
6526 ddr register to set the vic2 bank, to avoid and/or of the disk+vic2
bits before writing to the data register.

This particular case it seems to be used for changing the dac output
with the ddr register.

I know there are some issues with reading back the data register when
it's set to output and something is able to sink enough current that it
changes but IMO the way the code is written is a very 1997 view of
emulation.

**Pull request closed without merging**
