### PR TITLE
toaplan/twincobr.cpp: Dumped an added a newer ktiger set

### PR DESCRIPTION
**Pull request by clawgrip**
New WORKING clone
---------------------------------
Kyukyoku Tiger (Japan, set 1) [Mikado Game Center Europe, Victor Fernandez (City Game)]

### CODE REVIEW

**Comment by cuavas** [comment]
What’s the reasoning for making this the new parent?  Does it actually have revision A program ROM labels?  If so, why not actually include that in the description rather than just using arbitrary “set 1”/“set 2” numbering?

**Comment by clawgrip** [comment]
Same ROM labels as on the other set (also same Taito original PCB), but this one shows a 1989 copyright (instead of 1987), so it's newer.

index3

**Comment by cuavas** [comment]
* If the labels are the same, use the same labels in the source.  Don’t artificially change them to make them unique across parents and clones.
* Since they display different dates, you can use “Japan, newer” and “Japan, older” in descriptions.

**Comment by clawgrip** [comment]
> > * If the labels are the same, use the same labels in the source.  Don’t artificially change them to make them unique across parents and clones.
> 
> If this does happen, do try to make a comment at the end of the romload so people can quickly determine "Same Label Different Hash" denoting label exists elsewhere with differing data. This is used in many dozens of drivers in source as:
> 
> **// sldh**

Did not know that, thanks!!!!

**Pull request merged**
