### PR TITLE
PTY support for u*x OSes

### PR DESCRIPTION
**Pull request by fulivi**
Hi,

I've implemented a direct interface between emulated serial lines and pseudo terminals on u*x-like systems. I could only test it under Linux, but in principle it should compile & work correctly under *BSD and OS-X systems too.
Windows & OS/2 has no support for pseudo-terminals (as they are intended on unix-like systems): opening a pty there will always result in failure.
Thanks.

-- F.Ulivi

### CODE REVIEW

**Comment by mmicko** [comment]
Clang on OSX points to this error :

../../../../../src/osd/sdl/sdlptty_unix.c:121:13: error: use of undeclared
identifier 'ptsname_r'; did you mean 'ttyname_r'?
        if (ptsname_r(file->handle , name , name_len) < 0) {
            ^~~~~~~~~
            ttyname_r
/usr/include/unistd.h:483:6: note: 'ttyname_r' declared here
int      ttyname_r(int, char *, size_t) __DARWIN_ALIAS(ttyname_r);
         ^

you can check it in Travis log of this pull request

**Comment by mmicko** [comment]
For now you can add compile time check and disable this call for OSX.

**Comment by balr0g** [comment]
Any reason you must use the reentrant version of ptsname? OS X does have plain old non-reentrant ptsname.

**Comment by fulivi** [comment]
Ok, changed ptsname_r into ptsname. Could you check if it compiles on OSX now, please?
Thanks.
--F.Ulivi

**Comment by mmicko** [comment]
if you wait a bit you can see status of build at: https://travis-ci.org/mamedev/mame/builds/85922028

last two are those that should be of interest to you

**Comment by balr0g** [comment]
@fulivi: Grr... it looks like <stdlib.h> needs to be included on Mac OS X because that's where ptsname is defined (apparently that's where it's defined on Linux too, based on the man pages, so it probably would be a good idea to include <stdlib.h> for Linux as well).

**Comment by fulivi** [comment]
Ok, removed conditional inclusion of stdlib.h: it should be present on every u*x system now.

**Pull request merged**
