### PR TITLE
zr107, gticlub, nwk-tr, hornet: Greatly improve inputs (among other things)

### PR DESCRIPTION
**Pull request by Hydreigon223**
Changed and fixed a lot of (analog/dip) inputs to make them more responsive. Turns out Jet Wave previously had incorrect DIP settings that would disable the analog controls (MT7188).

### CODE REVIEW

**Comment by DavidHaywood** [comment]
Removing PORT_PLAYER(2) etc. will change the default mappings.

**Comment by Hydreigon223** [comment]
Restored. Didn't notice until now.

**Comment by Tafoid** [comment]
hangplt and hangpltu - gitclub.cpp
Neither machine boots or plays.  Progress stops at check devices/rom check screen with 19/21 roms showing errors.
hangplt

--

All machines in zr107.cpp
"flashing" black screen frame issue has gotten much worse, rather than once every 1.5 seconds or so, it is now easily 3 times a second: https://mametesters.org/view.php?id=5617
This exhibits a further regression.

**Comment by Hydreigon223** [comment]
In hangplt, you have DIP 1 set so the game doesn't skip post (set to off by default). I intended on having the game skip post but need to clean some cfgs from my end to see if hangplt defaults to skipping the post or not. Furthermore, 21U, 19U, 21R and 19R mark as bad because these roms are patched to bypass the step lock (which I would eventually like to implement). Even without the patches, the game will crash on the second CG board check (main reason why this game, all nwk-tr games, sscope and sscope2 has to skip post. I'm hoping to find that issue out).

The zr107 games display blanking out may either be a PPC or network function. I set the DIP back to 1 because it's factory setting always is set to 1 but can default it back to 4 in the meantime (ID4 blanks out a lot less). I also mention network function because in network test the "l" icon on the status column updates at the same speed as the display "blanking out". Setting the ID to "4" will update the "l" icon at a slower speed. This network behavior is also present in gticlub (but doesn't share the display blanking out issue).

**Pull request merged**
