### PR TITLE
sgi_mips.xml: Fix spacing (nw)

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by Tafoid** [comment]
I fixed a validation error right now https://github.com/mamedev/mame/commit/71dd03a7309fbddfad1ec3e11f0e7372f9654516 and didn't notice this.   you may need to re-base against current GIT

**Comment by clawgrip** [comment]
OK!

**Comment by Tafoid** [comment]
I didn't know you had to close the PR it to update the file.  Sorry about that.

**Comment by galibert** [comment]
You don't :-)

  OG.

**Comment by Tafoid** [comment]
Honestly, I would have done it myself and not even mentioned anything if I knew it was that complicated to top off his local copy to take in account any changes that may have come across.  That's all.

**Comment by clawgrip** [comment]
No, it's mainly my fault for previous the validation error... I'll open a new PR tonight to delete these spaces. Thanks!!

**Comment by galibert** [comment]
FYI, if you push -f to your PR branch, the PR updates.  No need to close
and recreate.

  OG.

**Pull request closed without merging**
