### PR TITLE
Five patches with code cleanups to the OSD layer

### PR DESCRIPTION
**Pull request by GiuseppeGorgoglione**
My previous request was failing the Travis check. This one should be ok.

### CODE REVIEW

**Comment by cuavas** [comment]
We have a significant number of users who require DirectInput 7 functionality for arcane controllers. Removing this is not acceptable. Brad already pointed this out on your previous pull request.

**Comment by GiuseppeGorgoglione** [comment]
That's fine. If you think there is any other patch of interest in my series, I can rework the pull request to include just that.

**Comment by cuavas** [comment]
Could you cherry-pick the following three commits into a pull request:
* Fix debugging code in font_dwrite.cpp
* Introduce osd_dynamic_bind
* Remove Direct3D abstraction layer

The font_dwrite changes should be a pretty clear improvement.  I believe removing the Direct3D abstraction layer should be fine as the D3D8 module is considered legacy support at this time and we're focusing on BGFX going forward.  The osd_dynamic_bind might need some adjustment, but it looks promising.

**Comment by GiuseppeGorgoglione** [comment]
Should i keep the patch "	Remove dynamic binding for standard Windows functions" as well? If not, I need to port those functions as well to osd_dynamic_bind.

**Comment by cuavas** [comment]
For now I'd rather you just port it to osd_dynamic_bind rather than removing the dynamic binding at this point.

**Pull request closed without merging**
