### PR TITLE
Changed the various usages of UI_*COLOR to be calls to src/frontend/mame/ui/moptions.h

### PR DESCRIPTION
**Pull request by npwoods**
The various UI_*COLOR macros were implemented as calls to
decode_ui_color, which cached the values for the various options in a
static array, which was obviously a gross hack.

This refactoring is strategic because I am trying to confine awareness
of mame_ui_manager to code in src/frontend/mame/ui, and the
implementation of decode_ui_color() relied on the ability to access
mame_ui_manager as a singleton from outside this code.

### CODE REVIEW

**Comment by cuavas** [comment]
Not caching the values means doing the string decode many times per frame.  This is a big hit to efficiency.

**Comment by npwoods** [comment]
Fair enough; I created a caching layer to minimize the amount of times these values need to be parsed

**Comment by npwoods** [comment]
Some crap workarounds for building under MSVC leaked into this PR.  Do not merge.

**Comment by rb6502** [comment]
Thanks Nathan.  Let us know when you have a mergeable version.

**Comment by npwoods** [comment]
Ok fixed the MSVC pollution and I hit a few more direct accesses to machine().options().xyz_color().  This should be ready for merging.

**Pull request merged**
