### PR TITLE
ay8910.cpp : Updates

### PR DESCRIPTION
**Pull request by cam900**
Implement ay8930 expanded mode, Add notes, Add feature value for chip specific features, Add runtime pin26 handler, Use struct for tone, envelope, Reduce defines, Fix spacings, Reduce unnecessary lines

### CODE REVIEW

**Comment by Tafoid** [comment]
This commit, by in large, completely KILLS ay8910 performance in all machines using ay8910, as well as ym2203 (ym2149).  Can this be done in an less performance impacting way?

Examples using YM2203:
c:\mamegit\mame>mame64_0909 1943 -bench 10
bme01.12d ROM NEEDS REDUMP
WARNING: the machine might not run correctly.
Average speed: 2128.20% (9 seconds)
c:\mamegit\mame>mame64_0910 1943 -bench 10
bme01.12d ROM NEEDS REDUMP
WARNING: the machine might not run correctly.
Average speed: 516.30% (9 seconds)
c:\mamegit\mame>mame64_0909 commando -bench 10
Average speed: 4139.79% (9 seconds)
c:\mamegit\mame>mame64_0910 commando -bench 10
Average speed: 598.43% (9 seconds)


Examples using AY8910:
c:\mamegit\mame>mame64_0909 gyruss -bench 10
Average speed: 1513.57% (9 seconds)
c:\mamegit\mame>mame64_0910 gyruss -bench 10
Average speed: 206.71% (9 seconds)
c:\mamegit\mame>mame64_0909 zzyzzyxx -bench 10
Average speed: 4276.49% (9 seconds)
c:\mamegit\mame>mame64_0910 zzyzzyxx -bench 10
Average speed: 1092.31% (9 seconds)

**Comment by happppp** [comment]
AY8930 needs to be a subclass, do the higher internal clockrate and all the 8930-specific functionality in there.

**Comment by rb6502** [comment]
Yes, please subclass the 8930 from the 8910 or this will be reverted.

**Comment by cam900** [comment]
Reduce performance issues in https://github.com/mamedev/mame/pull/5661.

**Comment by p1pkin** [comment]
it looks like this PR breaks noise generator edge case - period 0 and 1 should be the same for AY-3-891x, but it's not anymore, probably due to << 1 part here
`inline u8 noise_period() { return is_expnaded_mode() ? m_regs[AY_NOISEPER] & 0xff : (m_regs[AY_NOISEPER] & 0x1f) << 1; }`

@cam900 please fix this regression

**Comment by cam900** [comment]
> it looks like this PR breaks noise generator edge case - period 0 and 1 should be the same for AY-3-891x, but it's not anymore, probably due to << 1 part here
> `inline u8 noise_period() { return is_expnaded_mode() ? m_regs[AY_NOISEPER] & 0xff : (m_regs[AY_NOISEPER] & 0x1f) << 1; }`
> 
> @cam900 please fix this regression

Fixed in https://github.com/mamedev/mame/pull/7283.

**Pull request merged**
