### PR TITLE
nintendo/vsnes.cpp: Added missing DIP switch settings for vsmahjng.

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by 0kmg** [comment]
If anybody can help confirm these that would be nice. Based on how the DIP bits were split up and what I could glean from [this review](https://cooroot.hatenablog.jp/entry/2020/02/22/224334) of the digital re-release, I think this is probably pretty close to right. I know enough to win some mahjong hands but I can't tell things like the Rule and Mawashi differences really. And the Dora thing? A screenshot on the page shows one option as NEXT DORA. What's this? Normal rule where the next value above the dora yields the extra points? Dunno cus I dunno mahjong :)

**Comment by angelosa** [comment]
My only guess is that NEXT DORA -> URA DORA, the tile that lies below current dora indicator that may grant extra han if you agari with a riichi. It may be optional depending on whatever these 80s house rules are based on (almost every video jong I played has it).
Also interesting that Kansai is default, gonna guess because Nintendo -> Kyoto.

**Comment by 0kmg** [comment]
> Also interesting that Kansai is default, gonna guess because Nintendo -> Kyoto.

Well, I can't be sure which is which (is there an easy way to tell?). I assume Off is Kansai based on how the settings are laid out in that screenshot and how it lines up with the actual DIPs, plus Nintendo's VS games seem to follow the pattern of all off as the default setting.

**Comment by angelosa** [comment]
My alt guess about NEXT DORA is that the indicator either follows the normal convention or just tells the player the actual dora tile. Normally in mahjong the dora indicator is the "previous" tile in the sequence, so that a 2 pin dora indicator means that 3 pin is the actual dora worth han points.

**Comment by 0kmg** [comment]
Yeah, I think your alt guess is what I was trying to say my guess was.

**Comment by 0kmg** [comment]
I've verified the Mawashi DIP, well assuming 東南 and 東々 and actually read "tounan" and "tonton" in a mahjong context. If I understand what I've read the round order is 東１局, 東２局, 南１局, 南２局 for "tounan" and 東１局, 東２局, 東３局, 東４局 for "tonton". That's what the DIP seems to select.

**Comment by cuavas** [comment]
I think 東南 is read as "tonnan" in mahjong context, e.g. a four-round game of mahjong (starting with east, finishing with south) can be called 東南戦, read as "tonnansen".

**Comment by cuavas** [comment]
I looked this up just to make sure – 東々戦 is "tontonsen" and 東南戦 is "tonnansen".  東々戦 is played as an east round of eight hands.  東南戦, somewhat confusingly, seems to refer to both a Chinese style four-round game (east, north, west south), or a two-round game with an east round followed by a south round, the common factor being that both of them start with east and end with south.

**Comment by 0kmg** [comment]
Right, it looks like "ton" is always used in mahjong terms. I don't know why I would have supposed otherwise.

Luckily I did have the Famicom Mahjong manual at least, and it had a description of 東南回し round ordering.

**Pull request merged**
