### PR TITLE
chanbara.cpp - render low priority sprites

### PR DESCRIPTION
**Pull request by DavidHaywood**
https://mametesters.org/view.php?id=8024  confirms the sprite priority behaviour even if it looks ugly in places

I haven't fixed the sound tempo, it seems the only way you can do this is to adjust the YM clocks, but according to the driver notes the clocks are measured.  Could be another case like Street Fight, same chip, 2203.

### CODE REVIEW

**Comment by dinkc64** [comment]
Haze, this goes against something you taught me many many years ago when I came up with the Nostradamus end-boss fix: draw_sprites should never be called twice(or more), instead, a priority bitmap should be used.  (I don't remember your exact words, but it was something like this).  I'm curious why you went this way?

**Comment by cuavas** [comment]
I tend to agree with @dinkc64 here – true two-pass sprite rendering is rare, priority systems are far more common.

**Comment by DavidHaywood** [comment]
It probably should be done that way, although I wanted to minimize churn on the first pass.

**Comment by dinkc64** [comment]
Haze you're the best buddy, hang in there!

**Pull request merged**
