### PR TITLE
Update vsmilem_cart.xml

### PR DESCRIPTION
**Pull request by AlesanddroPB95**

### CODE REVIEW

**Comment by happppp** [comment]
@AlesanddroPB95 please confirm that you're reading our feedback. We can't work with you if you ignore it.

**Comment by cuavas** [comment]
@Tafoid that picture is a mobigo cartridge, this change affects the V.Smile Motion software list.  That said, the change is useless.

**Comment by cuavas** [comment]
@AlesanddroPB95 you’re clearly not responding to feedback.  I’m going to give you a 1-week ban to cool off.

**Comment by Tafoid** [comment]
> 
> 
> @Tafoid that picture is a mobigo cartridge, this change affects the V.Smile Motion software list. That said, the change is useless.

Yes.  My oversight.  I focused on mobigo since the crc32 hash had a hit on that entry in the softwarelist.  The point to make was it was an invalid change and despite the different format, the naming could likely be consistent between them vsmile or mobigo.

**Pull request closed without merging**
