### PR TITLE
Add all mm1 sounds

### PR DESCRIPTION
**Pull request by kara1001000**
This branch heavily modifies the floppy disk drive sound implementation. Now 3 sounds are required for the motor (spin up, loop, spin down), and 5 different sounds for the stepping to provide some variance. End results with good quality samples (smooth transitions from motor spin-up to loop to spin-down) are very impressive and significantly add realism (tested with MikroMikko 1).

There is also a minor fix for the MikroMikko 1 text rendering: first char of the 25th row is hidden only if it's using reverse video (tested with real HW).

### CODE REVIEW

**Comment by startaq** [comment]
Please separate the video related changes and put those into their own pull request.

**Comment by cracyc** [comment]
Setting the min_y of the viewport to m_vbp is required for pc9801 software which use the vbp to offset the slave 7220 start line from the master (such as Dragon Buster).  Can you fix it without that?

**Comment by cracyc** [comment]
Sorry, didn't mean to close it.

**Comment by kara1001000** [comment]
All right, I'll look into both of these suggestions.

**Comment by kara1001000** [comment]
startaq: video and audio changes are now separated, branches fix_mm1_video and add_mm1_sounds coming up as pull requests soon.

**Comment by kara1001000** [comment]
cracyc: Sorry for breaking pc9801 functionality, m_vbp is back there again. I was also a bit ashamed about the hard-coded magic numbers I added to visarea.max_y, but MikroMikko 1 needs that stuff. So, to serve both needs, I returned first the old implementation, and then added interface macro MCFG_UPD7220_VISIBLE_AREA_OFFSET to adjust those values as needed by various devices. Just pull my branches fix_mm1_video and add_mm1_sounds or wait until they are released.

**Pull request closed without merging**
