### PR TITLE
hooked igs_m027_023vid.cpp to PGM video system (made 023 video a device) - game runs attract demo

### PR DESCRIPTION
**Pull request by mamehaze**
- there are likely issues with the interrupt sources, causing palettes to not always transfer etc.  probably multiple sources with a source register somewhere.

### CODE REVIEW

**Comment by mamehaze** [comment]
this shows when it sometimes fails / misses a palette upload due to IRQ issues

**Comment by Tafoid** [comment]
@mamehaze
Issue(s) detected in current testing.  I'll add more if found:

happy6 - igs/pgm.cpp
Exception at EIP=00000001410f02e7 (pgm_arm_type3_state::init_happy6()+0x0047): ACCESS VIOLATION
happy6100cn - igs/pgm.cpp
Exception at EIP=00000001404d02e7 (pgm_arm_type3_state::init_happy6()+0x0047): ACCESS VIOLATION
happy6100hk - igs/pgm.cpp
Exception at EIP=0000000140d702e7 (pgm_arm_type3_state::init_happy6()+0x0047): ACCESS VIOLATION
happy6101 - igs/pgm.cpp
Exception at EIP=0000000140a102e7 (pgm_arm_type3_state::init_happy6()+0x0047): ACCESS VIOLATION

**Comment by Tafoid** [comment]
Additional Exceptions:

kovlsjb - igs/pgm.cpp
Exception at EIP=0000000140a30fba (pgm_arm_type1_state::pgm_decode_kovlsqh2_tiles()+0x002a): ACCESS VIOLATION
kovlsjba - igs/pgm.cpp
Exception at EIP=0000000140740fba (pgm_arm_type1_state::pgm_decode_kovlsqh2_tiles()+0x002a): ACCESS VIOLATION
kovlsqh - igs/pgm.cpp
Exception at EIP=0000000140f50fba (pgm_arm_type1_state::pgm_decode_kovlsqh2_tiles()+0x002a): ACCESS VIOLATION
kovlsqh2 - igs/pgm.cpp
Exception at EIP=0000000140c00fba (pgm_arm_type1_state::pgm_decode_kovlsqh2_tiles()+0x002a): ACCESS VIOLATION
kovqhsgs - igs/pgm.cpp
Exception at EIP=00000001403f0fba (pgm_arm_type1_state::pgm_decode_kovlsqh2_tiles()+0x002a): ACCESS VIOLATION

Hopefully easy fixes..

**Comment by Osso13** [comment]
Thanks for the reports, fixed in 914ac2a932ce21575e42b2e8bffa56925e3db546

**Pull request merged**
