### PR TITLE
split namco c169 roz chip, c123 tilemap chip and c355 sprite chip from namcos2 shared state by making them devices

### PR DESCRIPTION
**Pull request by DavidHaywood**
some reorganization still needed (eg move init stuff to config)

### CODE REVIEW

**Comment by DavidHaywood** [comment]
note, prior to device conversion MAME seemed to automatically know that .share("rozvideoram"); even on a 32-bit bus, was a 16-bit pointer, just like the (IMHO more difficult to read) way it automatically knows to use 16-bit handlers without them being explicitly specified.

once converted to a device, it was unable to make this connection and simply started giving me
Shared ptr 'rozvideoram' found but is width 32, not 16 as requested
Required shared pointer ':rozvideoram' not found

( you can see this if you apply http://mamedev.emulab.it/haze/misc/break_it_patch.zip over this )

so instead I'm having to pass a size and allocate the RAM in the device

**Comment by galibert** [comment]
No, it didn't.  It was working by pure luck on little-endian systems only.

  OG.

**Comment by galibert** [comment]
.umask32(0x0000ffff) does something different.  Without umask it's
equivalent to .umask32(0xffffffff).  And in such a case, it's 99% certain
the device uses dynamic bus sizing and the bus is technically 16 bits when
accessing it.

  OG.

**Comment by DavidHaywood** [comment]
ah, indeed, better fix my sizes then too :-)

**Comment by DavidHaywood** [comment]
ok, should be good for this part now

**Comment by ajrhacker** [comment]
When read/write handlers are being moved down into actual devices, I think preserving device name prefixes such as `c115_` and `c169_` is just a waste of space.

**Comment by DavidHaywood** [comment]
yes, that's part of the eventual cleanups

**Comment by DavidHaywood** [comment]
Right, I'll consider this to be a checkpoint.  Really needs merging before I resume.

**Pull request merged**
