### PR TITLE
Allow builing mame without OpenGL and X11

### PR DESCRIPTION
**Pull request by belegdol**
These changes should allow mame to build on minimal Linux installations used by SBCs like Odroid N2, having no OpenGL or X11. I have successfully built mame incorporating these changes on x86_64 Linux using
```
$ make NO_X11=1 NOWERROR=1 NO_USE_XINPUT=1 NO_OPENGL=1 NO_BGFX=1
```
The resulting binary seems to run without crashing.
Please refer to https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=116079 for the details.

### CODE REVIEW

**Comment by belegdol** [comment]
The MSVC build randomly fails with C1060 (compiler out of heap space). If anybody has suggestions how to deal with that, help is welcome.

**Comment by DavidHaywood** [comment]
The problem with BGFX is still the input latency is adds tho, this is widely reported.
Until that issue is gone, committing to it entirely seems like a bad idea.

**Comment by cuavas** [comment]
I'm not saying that we need to commit to it as the solution to all our problems going forward.  I'm saying that right now, it's the only thing we have that supports the following:
* Microsoft-supported accelerated drawing APIs on Windows 10 (DirectX 11/12)
* OpenGL ES
* A debugger when Win32, Cocoa and Qt are all unavailable, or no window manager is available

Until we have something else that covers those things, I don't think it's a good idea to make it too easy to build without bgfx.

**Comment by galibert** [comment]
Since you're going to need some kind of video output, and if you're not
accelerated the blit performance is going to be just uninteresting, could
you instead teach bgfx how to handle full-screen, X11-less opengl es, using
I guess drm and egl?  Since I guess that's what you're eventually going to
use.

  OG.

**Comment by belegdol** [comment]
I just pushed the other approach of getting the build to complete without X11. Let's wait for Steve's feedback as to whether it is actually useful.

**Comment by rb6502** [comment]
BGFX also has working support for Metal and Vulkan, which is also important.  I feel like finding out what the source of the alleged lag with it is would be the right way to go.

**Comment by belegdol** [comment]
https://github.com/mamedev/mame/blob/830cf62af66f4a1cac7df06404cbb153c2214e93/src/osd/modules/render/drawbgfx.cpp#L270-L296
Looking at the source code it seems like neither D3D12 nor Vulkan can be enabled via -bgfx_backend parameter. Is this intentional?

**Comment by cuavas** [comment]
The dx11 renderer is compatible with DirectX 12 (unlike MAME's Direct3D renderer which is completely incompatible with DirectX 11 or 12).

**Comment by belegdol** [comment]
I have now managed to build shaders under Windows, vulkan bgfx backend produces no output here either.

**Comment by rb6502** [comment]
Our copy of BGFX isn't the latest; we need to resync upstream in order to get Wayland support.  That may also fix the issues with D3D12 and Vulkan.

**Comment by peterferrie** [comment]
> The MSVC build randomly fails with C1060 (compiler out of heap space). If
> anybody has suggestions how to deal with that, help is welcome.

That happens with the 32-bit compiler, but it shouldn't happen with
the 64-bit compiler.
Are you definitely using the 64-bit compiler?
i.e. have you run the equivalent of "vcvarsall.bat amd64" or have your
environment including "PreferredToolArchitecture=x64" before starting
MSVC?

**Comment by belegdol** [comment]
Disabling bgfx is not endorsed and various other issues discussed here ended up in their own PRs. Closing.

**Pull request closed without merging**
