### PR TITLE
pgm2.cpp: Verified kof98umh refresh rate

### PR DESCRIPTION
**Pull request by cam900**
reference: https://www.youtube.com/watch?v=XOuJtOzx-Fw

### CODE REVIEW

**Comment by trap15** [comment]
I'm curious how a video verifies such a specific refresh rate?

**Comment by cam900** [comment]
> I'm curious how a video verifies such a specific refresh rate?

That video is recorded from real PGM2, and this PR matches a kof98umh title sequence to real hardware.
Possibly 15625hz for Hsync and 59.185...hz for Vsync, and it's seems like PGM1; needs to verification of refresh rate for 448x224 and 512x240 resolution mode.(Different pixel clock input?)

**Comment by p1pkin** [comment]
real hardwares usually limited by couple of things, like ARM CPU speed and memory access latency, blitter speed and probably others we aware of.
it is not right and hacky way to just tweak Vsync rate to make emulated gameplay speed match real hardware videos.
only H/V rate measurements using oscilloscope / logic analyzer might be considered as real reference or proof.

**Comment by happppp** [comment]
"Verified" means something else, either electronic measurement of h/v syncs or from detailed PCB photos or schematics. This one is a:
// guesswork, matches video recording

**Comment by DavidHaywood** [comment]
given these don't seem to push the CPU and probably aren't pushing anything else I don't think it's too inaccurate to measure this way in this case.  Due to the different screen resolution I expect the refresh to be different, so this is at least closer to correct than not using a different refresh at all for this vertical resolution.

**Comment by p1pkin** [comment]
well, we don't even know actual CPU clock, and its different in games, if I recall correctly KOF98 was the one which uses higher clock, and I'd guess there was a reason for this.

**Comment by angelosa** [comment]
Do we even know if it has a specific video/pixel clock? Doubt it uses _100 MHz_ for deriving three different (lowres) video modes ...

**Comment by DavidHaywood** [comment]
it has no clocks, everything is internally generated.

**Pull request merged**
