### PR TITLE
New core input type: "Memory Reset"

### PR DESCRIPTION
**Pull request by ajrhacker**
- In machines that store their settings and/or bookkeeping logs in some form of non-volatile memory, "Memory Reset" will reset them to some system-provided default.
- This replaces all existing inputs named "Memory Reset" and a few simply named "Reset" which are known to do this rather than reboot the system (a confusion to be avoided, though many systems will only acknowledge this input at boot time); others should be checked.
- The default key binding (F1) for this new input type is chosen partly to avoid conflicts with those used by gambling/mahjong games which are currently the only systems to use this, though broader use is envisioned.

### CODE REVIEW

**Comment by cuavas** [comment]
What about the Nichibustu mahjong games? Lots of games in nbmj8688 for example have a button for clearing persistent data. Also what semantics are you implying? Should this input type be used for things that just clear accumulated credits/bookkeeping, or only things that clear all persistent data including settings? There are a number of different reset behaviours depending on the game.

**Comment by cuavas** [comment]
Also do we want to think about a potential default mapping for this new input type?

**Comment by ajrhacker** [comment]
Yes, games may have different reset behaviors, and that's an unavoidable fact. I haven't closely studied the games that have "Credit Reset" or "Clear Credits" inputs, but they seem to represent a distinct input type with more specialized usage... at least in some cases; I think a few might be key-out switches that have been misidentified because the coin/ticket dispensers aren't emulated.

**Comment by ajrhacker** [comment]
A conflict has already arisen, and I have an explanation. It seems some gambling drivers are rebinding the IPT_SERVICE "Test" input to F1 so as not to conflict with the service mode DIP switch which is assigned the same binding by the PORT_SERVICE and PORT_SPECIAL_ONOFF macros. In such cases, I think a better workaround is to unbind the DIP switch, as it's likely to be redundant with the non-toggle input (totally so in the case of Fever Soccer) and still can be toggled itself through the UI's DIP settings menu.

**Pull request merged**
