### PR TITLE
New working clone

### PR DESCRIPTION
**Pull request by algestam**
-----------------
Monkey Goalkeeper [algestam, Milan Galcik]

### CODE REVIEW

**Comment by happppp** [comment]
Which one is it? (4th letter)
Веселые футболисты
Весёлые футболисты

And, is "Monkey Goalkeeper" the official title? I know some Elektronika games have official English titles, for example Fowling, Merry Cook.
Google translate says the transliteration is "Veselyye futbolisty", but I don't know if that's accurate.

**Comment by algestam** [comment]
I don't know Russian but according to [this wikipedia page](https://ru.wikipedia.org/wiki/%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%B8%D0%BA%D0%B0_(%D0%B8%D0%B3%D1%80%D1%8B)), it should be the second one. Also, from what I've found, "Monkey Goalkeeper" is the official export title. Please see this [image](https://game-im02.ru/_ph/7/629083839.jpg) where the export name is shown.

Also, did reorder the Elektronika clones so that they are ordered by ID number (port and ROM definitions). What's the MAME way of ordering the games in the state definition list?

**Comment by happppp** [comment]
Ok, Monkey Goalkeeper it is.
I'd use a shorter name, 8 letters instead of 11, like monkeygk.

Also, there's nooks and crannies in the SVG, it's something potrace does. I always do a cleanup round after auto tracing pictures into SVG.
monkey2
monkey1

**Comment by happppp** [comment]
I'd order the games by ID number. What is "state definition list"?
In mame.lst, it's alphabetical per driver file.

**Comment by algestam** [comment]
Thanks for the feedback! :)

Will rename the game and look into the SVG file.

This is the list I was referring to:

    public:
	gnw_mmouse_state(const machine_config &mconfig, device_type type, const char *tag) :
		hh_sm510_state(mconfig, type, tag)
	{ }

	void exospace(machine_config &config);
	void fowling(machine_config &config);
	void mnkgoalkeep(machine_config &config);
	void nupogodi(machine_config &config);
	void gnw_egg(machine_config &config);
	void gnw_mmouse(machine_config &config);
    };

Does it make sense to order the games by ID here as well? Should the clones be listed first (as they are now) or should the original game(s) be listed first?

**Comment by happppp** [comment]
Same order as the functions are in the body.
So, mmouse, egg, elektronika.

**Comment by algestam** [comment]
Thanks for the feedback :) The PR has been updated.

**Comment by happppp** [comment]
Thanks

**Pull request merged**
