### PR TITLE
#9048 Allow to setup custom offset decoder for gfx char

### PR DESCRIPTION
**Pull request by holub**
see #9048 for details

### CODE REVIEW

**Comment by holub** [comment]
@cuavas @DavidHaywood @galibert 
Can we please discuss this change? My flowing commit relies on this or whatever will be suggested.

**Comment by DavidHaywood** [comment]
I don't feel I have the authority here to make a call on this, it's not code I've ever touched, so it'll come down to what the others think.

**Comment by galibert** [comment]
How would one test if an alternative actually works?

  OG.

**Comment by holub** [comment]
> How would one test if an alternative actually works?
> 
> OG.

PR actually included reference implementation in TSConfig.
Before: we had to decode 8x8 tiles by line which visible in tile-viewer where we have *8 useless tiles decoded
After: PR tiles decoded exactly at their size and amount.

See my comments in PR which point to critical parts

**Comment by holub** [comment]
@rb6502 maybe you can make decision here?

**Comment by happppp** [comment]
If it really is not possible with MAME's generic gfxdecode, then instead of a single-use exception added to it, I'd do it the way you're doing it now (oversized vram viewer). Or, I'd go for drawing the pixels manually instead of using MAME tilemaps.

**Comment by holub** [comment]
> If it really is not possible with MAME's generic gfxdecode, then instead of a single-use exception added to it, I'd do it the way you're doing it now (oversized vram viewer). Or, I'd go for drawing the pixels manually instead of using MAME tilemaps.

I don't like the usage of oversized vram for certain reasons:
1. Memory consumed for this decoding is *8 more than required (in my case)
2. TileView UI is useless

"single-use" is also questionable because it's not rarely custom. Possibly just because other people use custom oversized regions in absence of common approach to the problem.

**Comment by holub** [comment]
I'm ok to stash these PR till more usecases were found in other drivers

**Comment by galibert** [comment]
I'm working on making it possible to do the decode at startup programmatically so that any custom setup can be handled without complexifying these already annoying structures.  Not working yet though.

**Comment by holub** [comment]
> I'm working on making it possible to do the decode at startup programmatically so that any custom setup can be handled without complexifying these already annoying structures.  Not working yet though.

Awesome. Would you please create empty branch attached to the issue in order to track the progress? I will change this PR then.

**Comment by holub** [comment]
Waiting for alternative solution

**Comment by smf-** [comment]
Would that work with a system that pulls graphics out of ram at run time?

**Comment by galibert** [comment]
We already have that.  I'm just trying to determine how it's handled after
a half-dozen code reorganizations :-)  But it's essentially the same thing.

  OG.

**Comment by holub** [comment]
substituted by #13145

**Pull request closed without merging**
