### PR TITLE
Polymorphize input_device and input_class; move to separate source fi…

### PR DESCRIPTION
**Pull request by ajrhacker**
…le (nw)

This isn't intended to be included in the 0.179 release, obviously.

### CODE REVIEW

**Comment by ajrhacker** [comment]
Now that 0.179 is out, I'm really hoping for at least some feedback here, preferably from devs concerned with the OSD layer.

**Comment by galibert** [comment]
Okay, if I read it right, you create objects for the different input
sources, then layer adapters on them to decide how they'll be used
(relative, absolute, etc).  The result looks rather clean.  I like it.

  OG.

**Comment by cuavas** [comment]
Yeah, if it's adapter pattern that sounds nice.  I just see a wall of diff, I'm not in a position to give a proper review.

**Comment by ajrhacker** [comment]
I worry somewhat that the new inheritance and construction schema here may not be exactly right; with some tweaking, I think it could reach a considerably higher potential. Making input_class polymorphic will increase modularity and prepare for a further overhaul of the input system that I have planned. Note that the polymorphic input_device_item adapters already existed.

Splitting input.cpp does inflict quite a bit of churn on the codebase; as usual, I did it to liberate a lesser piece of the core from emu.h dependency, and in this case it fortunately turns out that neither the UI nor any devices require access to core inputs on a deeper level than the standard input_seq codes and polling routines.

**Comment by galibert** [comment]
Well, we merge and we go from there?

  OG.

**Comment by ajrhacker** [comment]
> Well, we merge and we go from there?

At this stage, I don't see why not.

**Pull request merged**
