### PR TITLE
Make phosphor persistence independent of frame rate

### PR DESCRIPTION
**Pull request by anikom15**
Hello friends!

I am working on a better phosphor persistence shader right now, but I am still thinking about how flexible the model needs to be, and I also want to compare it with some real CRTs. In the mean time these changes I have done are a quick fix to an issue I discovered. You can see this effect by increasing frame skipping in MAME. If you increase frame skipping, and run a game like PONG which you can clearly see the effect of the persistence, you can see that the residual 'tails' from the persistence are longer with higher frame skips.

I've been writing a lot of notes about this phosphor stuff, so I wrote a brief summary on this effect from a signal processing perspective: [https://drive.google.com/open?id=0B4fRyCO0uHIrZmtvUi0wcXl0R0E](https://drive.google.com/open?id=0B4fRyCO0uHIrZmtvUi0wcXl0R0E)

Please feel free to offer any criticism.

—W.

### CODE REVIEW

**Comment by cuavas** [comment]
@ImJezze @MooglyGuy could you comment on this?  D3D and shaders are kinda your thing.

**Comment by ImJezze** [comment]
@anikom15 
You need to ensure your changes work for games with multiple screens like [darius] and multiple windows when [-numscreens] option is unequal 1; dt has to be calculated separately for each screen/window.

p.s. It would be nice to use written-out names for uniforms. I know dt is quite obvious, but I would prefer DeltaTime or something.

**Comment by anikom15** [comment]
Done. Note that the statics are gone :( in favor of a member function for dt. This will make it easier for other shaders to be time dependent however.

**Comment by ImJezze** [comment]
I'm not absolutely sure, but I think you could use shaders::begin_draw() to update delta_time and get rid of the additional update_t.

**Comment by anikom15** [comment]
Done. Also appears to give us a slight performance boost from my earlier version. Thanks @ImJezze .

**Pull request merged**
