### PR TITLE
toaplan2.cpp - Add subtitle to Japanese FixEight sets.

### PR DESCRIPTION
**Pull request by mikehyrus**

### CODE REVIEW

**Comment by mikehyrus** [comment]
image
(Image from The Arcade Flyer Archive)

**Comment by mikehyrus** [comment]
I may need to rebase this branch.

**Comment by FoxhackDN** [comment]
A small suggestion: log into the website, go to the source file you want to edit (toaplan2.cpp), hit the little pencil, and you'll create an all new fork in your profile with only that file. Then you can just paste the changes.

I just did that with a tiny, one byte change I submitted earlier today.

And yes, I hate git :)

**Comment by mikehyrus** [comment]
I was using Microsoft Studio BTW for most of the editing.

**Comment by 0kmg** [comment]
Git is okay. Occasionally I've hosed a branch real bad though (often from typos/wrong tab completions).  Sometimes it's so bad the only option left is to take off and nuke the entire branch from orbit—it's the only way to be sure.

**Comment by cuavas** [comment]
Please don’t recommend the GitHub web editor.  It encourages people to use useless commit messages, railroads you into editing a single file per commit so you can easily end up with intermediate broken commits.  Then you end up with a pile of useless Actions CI runs to cancel as well.

You can avoid all the issues here by just creating a new branch from upstream master for each logical set of changes.

**Comment by mikehyrus** [comment]
Made a new repository instead, sorry I wasn’t recommending the editor no.  But GitHub Desktop sure went wonky when I was editing the PR.

**Comment by FoxhackDN** [comment]
> Made a new repository instead, sorry I wasn’t recommending the editor no. But GitHub Desktop sure went wonky when I was editing the PR.

He was talking to me, don't worry. github desktop gives me a lot of hell too and sometimes it won't let me do anything until I nuke my local source repo, and this was the only way I found to get around that.

**Pull request closed without merging**
