### PR TITLE
correct typo in name of Mobile Suit Gundam romset

### PR DESCRIPTION
**Pull request by markwkidd**
`Mobil` should be `Mobile`

### CODE REVIEW

**Comment by DavidHaywood** [comment]
The title screen clearly shows 'Mobil' not 'Mobile'
http://mamedev.emulab.it/haze/pics2018/gdfs.png

**Comment by markwkidd** [comment]
I do see what you mean about the title screen, although the rest of the source comments refer to the correct anglicization of "Mobile". Here mobile is an english word originally that has been translated to Mo-bi-ru Japanese and back.

That said, maybe the text on the title screen should prevail. I'll leave this PR open for the moment but I'll understand if it is being declined.

**Comment by DavidHaywood** [comment]
I'd be inclined to standardize it (as is done with the manufacturer) with a comment mentioning how the title screen spells it, but not my call in the end.

**Comment by DavidHaywood** [comment]
I've incorporated this, with a note, into my other SSV pull request
https://github.com/mamedev/mame/pull/4341

**Comment by markwkidd** [comment]
Sounds good, thanks! I'll close this PR now.

**Pull request closed without merging**
