### PR TITLE
epos.cpp: swap ceiling/call elevator button assignments on beastf

### PR DESCRIPTION
**Pull request by scoomby**
Whilst looking at the game differences between Super Glob, The Glob and Beastie Feastie, I noticed that the ceiling (or energy) button / call elevator button assignments are swapped on Beastie Feastie when comparing with Super Glob and The Glob.  This small change swaps the button assignments to match Super Glob, The Glob and the Pac-Man conversion of Beastie Feastie (beastfp).  In addition, this change also matches the button arrangements shown on the control panel images that can be found online.

### CODE REVIEW

**Comment by cuavas** [comment]
What’s the pinout though?  Are these JAMMA-like?  If they are, the button assignments should match the pin names on the edge connector.

**Comment by ajrhacker** [comment]
There's an unofficial pinout here:

https://arcarc.xmission.com/archive/Tech/Pinouts%20(new%20Sep-21-2003)/The_Glob.txt

It doesn't seem to be JAMMA-compatible, which is unsurprising considering that the standard wasn't issued until 1986.

**Comment by scoomby** [comment]
Thanks for the quick responses.  I have noticed that the button assignments/arrangements in some drivers don't always follow the order of the pinouts.  Moon Patrol m52.cpp is a good example where button 2 is assigned in front of button 1.

**Comment by ajrhacker** [comment]
A more official pinout for Igmo is given in this manual:

https://www.gamesdatabase.org/Media/SYSTEM/Arcade//Manual/formated/IGMO_-_1984_-_Epos_Corporation.pdf

**Pull request merged**
