### PR TITLE
namcos22.cpp: improve handling of unused inputs for ridge racer standard cabinet

### PR DESCRIPTION
**Pull request by scoomby**

### CODE REVIEW

**Comment by happppp** [comment]
That won't work for ridgera2 or raveracw
conf mask, 6-speed yes/no:
0x0000: yes
0x0100: no
0x2000: no
0x2100: yes

**Comment by scoomby** [comment]
Thanks happppp.  I will tidy that up later

**Comment by happppp** [comment]
How about ridgeracf, will it add or remove buttons now if you press IPT_SERVICE2?
And after working around that one, you'd have to consider, is it really worth juggling all those PORT_CONDITIONs to hide 3 optional inputs?

**Comment by scoomby** [comment]
Thanks for the response.  The change didn't actually affect the buttons if IPT_SERVICE2.  However, I agree with your point that it isn't really worth juggling all of those PORT_CONDTIONs to hide these optional inputs.  Closing.

**Pull request closed without merging**
