### PR TITLE
gba.xml: Metadata cleaning

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Replaced the countries' abbreviation by the countries' full name.

### CODE REVIEW

**Comment by ArcadeShadow** [comment]
Two quick questions maybe you can advice me (@angelosa @cuavas)
First one, when a set has various alternative titles, like this one:
`<info name="alt_title" value="FIFA Soccer 2004 (USA Box), FIFA Football 2004 (Euro Box)" />`
All the alternative titles should be in 1 info tag (like the example above) or can be on various tags like:
`<info name="alt_title" value="FIFA Soccer 2004 (USA Box)" />`
`<info name="alt_title2" value="FIFA Football 2004 (Euro Box)" />`

Second doubt, on the language tag for now it must be the English name of the language:
`<info name="language" value="English,French,German,Italian,Dutch,Spanish" />`
or can be the standard language culture name:
`<info name="language" value="en-GB,fr-FR,de-DE,it-IT,nl-NL,es-ES" />`

**Comment by cuavas** [comment]
Multiple alternate titles should go in multiple `info` elements.  It makes searching and indexing work properly.

If you’re going to use abbreviations for languages, use [ISO 639](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).  It’s generally best to use a real standard.

If you look at [mac_hdflop.xml](https://github.com/mamedev/mame/blob/mame0248/hash/mac_hdflop.xml) for example, there are a bunch of items that need to have the language in the description because it’s the only part that differs between versions.  That software list seems to be using full names for languages.

**Comment by cuavas** [comment]
`bofa` has languages in the description while `bof` doesn’t – it’s not obvious how the languages differ.  Same for `brobeara` and `brobear`.

**Comment by cuavas** [comment]
`dogz`/`dogza`, `dogz2`/`dogz2a` and `fant4`/fant4a` are more pairs of “Europe” releases with languages in the description for one but not the other.

**Comment by ArcadeShadow** [comment]
> `dogz`/`dogza`, `dogz2`/`dogz2a` and `fant4`/fant4a` are more pairs of “Europe” releases with languages in the description for one but not the other.

I saw that too. I'll need to check the games to know what languages available are in (to complete the description).

Regarding ISO 639, it is not possible to differentiate between British English and US English (I think...).
On the [mac_hdflop.xml](https://github.com/mamedev/mame/blob/mame0248/hash/mac_hdflop.xml) software list, it exists both case, for this reason that I suggested using the language culture name (then you case use en-GB or en-US).
Is there any way to differentiate them using ISO 639?

**Comment by cuavas** [comment]
`hellokhp`/`hellokhpa` and `hotpot`/hotpota` are more pairs where the description for one lists languages and the other doesn’t.

`hpotphis` still has the US alternate title in the description.

It’s going to take me a while to read through this diff – it’s massive.

**Comment by ArcadeShadow** [comment]
> Multiple alternate titles should go in multiple `info` elements. It makes searching and indexing work properly.

So I can use the same tag name info for various alt_title, like this?
<info name="alt_title" value="FIFA Soccer 2004 (USA Box)" />
<info name="alt_title" value="FIFA Football 2004 (Euro Box)" />

**Comment by cuavas** [comment]
> Regarding ISO 639, it is not possible to differentiate between British English and US English (I think...).
> On the [mac_hdflop.xml](https://github.com/mamedev/mame/blob/mame0248/hash/mac_hdflop.xml) software list, it exists both case, for this reason that I suggested using the language culture name (then you case use en-GB or en-US).
> Is there any way to differentiate them using ISO 639?

You can use an ISO 639 language code with an [ISO 3166-1 Apha-1 code](https://en.wikipedia.org/wiki/ISO_3166-1) for a country.  But it’s probably going to fall over eventually when things don’t map directly onto it.  For example, how do you represent general Commonwealth English?  Making up codes will get us back to the old undesirable situation of using a non-standard abbreviation scheme.

**Comment by cuavas** [comment]
> > Multiple alternate titles should go in multiple `info` elements. It makes searching and indexing work properly.
> 
> So I can use the same tag name info for various alt_title, like this?
> `<info name="alt_title" value="FIFA Soccer 2004 (USA Box)" />`
> `<info name="alt_title" value="FIFA Football 2004 (Euro Box)" />`

Well, if you’re going to do put that extra information in the value, at least use `(USA, box)` and `(Europe, box)`.  I’m not sure it necessarily needs it to be in the value itself.  Some of the software lists have it in comments.  There’s also cases like Kouklotheatrika in the PlayStation software list where the Greek spelling and Japanese transliteration, which are logically separate alternate titles, are both on the box and disc.

**Comment by cuavas** [comment]
`madagscr`/`madagscra`, `mnsthous`/`mnsthousa`, `thawkask`/`thawkaska`, `ultspidm`/`ultspidma` and `2nemoinc`/`2nemoinca` are more of the pairs of European releases.  `madagopp`, `swmana` and `trollz` are “Europe” releases with no language listed, but with *two* Europe clones with languages listed each.

`legosocr` has alternate titles in the description.

I’d guess that the Europe releases with no languages listed might be English-only.

**Comment by ArcadeShadow** [comment]
> I’d guess that the Europe releases with no languages listed might be English-only.

I confirmed on each game, and those are English only.

**Comment by ArcadeShadow** [comment]
> You can use an ISO 639 language code with an [ISO 3166-1 Apha-1 code](https://en.wikipedia.org/wiki/ISO_3166-1) for a country. But it’s probably going to fall over eventually when things don’t map directly onto it. For example, how do you represent general Commonwealth English? Making up codes will get us back to the old undesirable situation of using a non-standard abbreviation scheme.

For now I added the English language name in the info tag
`<info name="language" value="English,French,German,Italian,Dutch,Spanish" />`
In the future I think it would be better to use a code (ISO or another standard)

**Comment by cuavas** [comment]
> In the future I think it would be better to use a code (ISO or another standard)
> The [IETF](https://en.wikipedia.org/wiki/IETF_language_tag) combines the 2 ISO's standard.
> The 639-1 (for the language) and the ISO 3166 (for the country code).
> As for the Commonwealth English, I think the en-GB should be the standard for this case.
> But it's just my opinion...

The trouble is, Commonwealth English is not the same as UK English which would be implied by “en-GB” – it has differences driven by Australian and Hong Kong usage among other things.  There’s also Apple’s weird “International English” that they had as a language option in the ’90s that won’t line up to a standard code, because as far as I can tell it isn’t actually something standardised.  Then you get into the mess of different variants of regional vernacular Chinese.  We’d be forced to come up with our own system of abbreviations, and that’s a pain to maintain.

**Pull request merged**
