### PR TITLE
Benesse work / new NOT WORKING Machine (Challenge Gear)

### PR DESCRIPTION
**Pull request by mamehaze**
New NOT WORKING Machine
----------
Challenge Gear [TeamEurope, SSJ, Youkal3]

New NOT WORKING Software List Entries
---------
challenge_gear_cart.xml:
Challenge 6 Years [TeamEurope, SSJ, Youkal3]

- moved pockchal.cpp and the new driver to a benesse folder, as benesse had many more products

- created a separate machine for the Pocket Challenge v2, the BIOS isn't dumped, but carts aren't physically compatible with a Wonderswan even if the software is.  Makes more sense to have a driver with the borrowed Wonderswan BIOS marked as BAD_DUMP than hiding everything behind the Wonderswan itself.

### CODE REVIEW

**Comment by mamehaze** [comment]
this ties to the work @ajrhacker is doing on the new CPU core.  As there's not even a stub of an execution core to hook it up to yet you can't do a -debug with the new driver and get the dasm at this point.

**Comment by mamehaze** [comment]
Console no.1

**Comment by mamehaze** [comment]
Console no.2

**Comment by mamehaze** [comment]
Cartridge

**Comment by asiekierka** [comment]
> created a separate machine for the Pocket Challenge v2, the BIOS isn't dumped, but carts aren't physically compatible with a Wonderswan even if the software is. 

That's not entirely accurate.

* The Pocket Challenge V2's BIOS is bit-identical to the mono WonderSwan BIOS, as both consoles use identical SoCs. See [this tweet from Adam Jaremko](https://x.com/adamjaremko/status/1163284248884891650) - the difference in behaviour is achieved by a difference in chip wiring, but not in chip firmware.
* While it is true that Pocket Challenge V2 cartridges are not physically compatible, this is merely due to a difference in shape; once disassembled, the PCBs themselves are electrically compatible with the WonderSwan, as evidenced by [being able to put a PCv2 cartridge in a WonderSwan](https://x.com/adamjaremko/status/1163485972631347200) and [vice versa](https://x.com/kyenprod/status/1532418259504472064).

**Comment by mamehaze** [comment]
well better to further the documentation then, and find what controls it skipping the logo so it can be implemented that way.

from the point of view of an end user they are incompatible systems though.

**Pull request merged**
