### PR TITLE
treat the bdm_dm01 as a 'screen' rather than 1000+ artwork elements to avoid 'death by string lookup'

### PR DESCRIPTION
**Pull request by mamehaze**
treat the bdm_dm01 as a 'screen' rather than 1000+ artwork elements to avoid 'death by string lookup'

other layouts will need updating too if this is the way forward.

we've still lost a HUGE amount of performance here at some point tho, it barely scrapes in at >100% on a 4ghz i7 even with this change (without it things were getitng down to 30%)  profiles points at it being a write handler, but I'm not sure which one yet, it's seems unrelated to the new layouts tho.

### CODE REVIEW

**Comment by Tafoid** [comment]
Haze,
If you can provide me an example or two of specific game/drivers that have regressed and I'll see what I can come up with.

**Comment by mamehaze** [comment]
sc2prem for example, but the reality is we shouldn't be doing so many string lookups, it needs a better solution.

we need some concept of a 'physical element' that drivers can interact directly with, that gets tied directly to artwork elements, so there is no string lookup every time.

**Comment by Tafoid** [comment]
I can confirm it.. and have a day of Dev performance tanked (January 10 of this year)
Without bisecting and testing, that's about all I can narrow it down to.

--

[MINGW64] c:\mamegit\mame>mame64_0110am -bench 10 sc2prem
ID String @ 0000ff00
PROJECT NUMBER PR6432  PREMIER CLUB MANAGER 25P !250  GAME No 95-750-848  THIS P
ROGRAM IS THE COPYRIGHT OF  BELL-FRUIT MANUFACTURING CO LTD  AND WILL BE STRICTL
Y ENFORCED  13-AUG-1996 14:05:05               1o    ?  N  ?}' N<   1  +  R&@RRS
2         W
Average speed: 1982.67% (9 seconds)

[MINGW64] c:\mamegit\mame>mame64_0110pm -bench 10 sc2prem
ID String @ 0000ff00
PROJECT NUMBER PR6432  PREMIER CLUB MANAGER 25P !250  GAME No 95-750-848  THIS P
ROGRAM IS THE COPYRIGHT OF  BELL-FRUIT MANUFACTURING CO LTD  AND WILL BE STRICTL
Y ENFORCED  13-AUG-1996 14:05:05               1o    ?  N  ?}' N<   1  +  R&@RRS
2         W
Average speed: 120.63% (9 seconds)

**Comment by mamehaze** [comment]
would love to have it narrowed down if possible, it's one hell of a performance drop

**Comment by Tafoid** [comment]
I'll attempt to do it sometime today or as soon as possible.  Just have a lot of testing on my plate at the moment and having to revert source tree to 8 months ago impedes that just a bit.

**Comment by ajrhacker** [comment]
@mmicko was doing a lot of crazy modernization that day, including converting the output module to C++. The new implementation of `output_manager::find_item` might be the cause of the inefficiency here, since it iterates over all the pairs instead of using `std::unordered_map::find`.

**Comment by Tafoid** [comment]
I did a bisect.. had to adjust the source for GCC 6.1 and add a flag or two to get everything to compile spending hours on it, but I got this:

git.exe bisect bad
f9f908d48bd3607f8ddf529eb6b83c2b4b0b9790 is the first bad commit
commit f9f908d48bd3607f8ddf529eb6b83c2b4b0b9790
Author: Miodrag Milanovic <mmicko@gmail.com>
Date:   Sun Jan 10 18:41:17 2016 +0100

modernize output_manager (nw)

:040000 040000 3f7f2bcaaf6db76ba890895bd6a5dc32669d47aa f5067a1226280b1ba0c35ec8e664ae679627e3f4 M	src

Success (343 ms @ 8/23/2016 8:14:55 PM)

--

Profiles were mentioned, this is my "TOP 5" output with -profile 5 for -str 10:
58.7% -  14701 : 000007FEFD9F5920 (strcmp)
                 000000000259CAF4 (output_manager::set_value(char const*, int)+0x0044)
                 000000000259CCE7 (output_manager::set_indexed_value(char const*, int, int)+0x0127)
                 000000000055DD19 (bfmdm01_device::mux_w(address_space&, unsigned int, unsigned char, unsigned char)+0x0169)
                 0000000003266E67 (address_space_specific<unsigned char, (endianness_t)1, false>::write_byte(unsigned int, unsigned char)+0x0067)

16.2% -   4060 : 000007FEFD9F5920 (strcmp)
                 000000000259CAF4 (output_manager::set_value(char const*, int)+0x0044)
                 000000000259CCE7 (output_manager::set_indexed_value(char const*, int, int)+0x0127)
                 0000000000549D9E (bfm_sc2_state::mux_output_w(address_space&, unsigned int, unsigned char, unsigned char)+0x004e)
                 0000000003266E67 (address_space_specific<unsigned char, (endianness_t)1, false>::write_byte(unsigned int, unsigned char)+0x0067)

13.2% -   3297 : 000000000259CAB0 (output_manager::set_value(char const*, int))
                 000000000259CCE7 (output_manager::set_indexed_value(char const*, int, int)+0x0127)
                 000000000055DD19 (bfmdm01_device::mux_w(address_space&, unsigned int, unsigned char, unsigned char)+0x0169)
                 0000000003266E67 (address_space_specific<unsigned char, (endianness_t)1, false>::write_byte(unsigned int, unsigned char)+0x0067)
                 00000000031CAC03 (m6809_base_device::execute_one()+0x23a3)

 2.1% -    534 : 00000000031C8860 (m6809_base_device::execute_one())
                 0000000001C2F169 (m6809_base_device::execute_run()+0x0019)
                 00000000025C405C (device_scheduler::timeslice()+0x053c)
                 0000000002584168 (running_machine::run(bool)+0x0148)
                 000000000257EBD6 (machine_manager::execute()+0x0216)

 2.1% -    518 : 000000000259CAB0 (output_manager::set_value(char const*, int))
                 000000000259CCE7 (output_manager::set_indexed_value(char const*, int, int)+0x0127)
                 0000000000549D9E (bfm_sc2_state::mux_output_w(address_space&, unsigned int, unsigned char, unsigned char)+0x004e)
                 0000000003266E67 (address_space_specific<unsigned char, (endianness_t)1, false>::write_byte(unsigned int, unsigned char)+0x0067)
                 0000000001C2E37C (m6809_base_device::mi_default::write(unsigned short, unsigned char)+0x001c)

**Comment by mamehaze** [comment]
yeah, looks like we have a winner then...
@mmicko what do you say? there's no way to win that performance back at a driver level and 2000% -> 120% is a significant loss.

**Comment by ajrhacker** [comment]
#1307 makes sc2prem run over sixteen times faster, which should be nearly as fast as it was before f9f908d48bd3607f8ddf529eb6b83c2b4b0b9790.

**Comment by mamehaze** [comment]
yeah, if that is accepted this one can be closed then (unless we WANT to treat DMDs as a type of screen? it would save an awful lot of lines in the artwork files)

**Comment by galibert** [comment]
I definitively handle the pinball dmds as screens, with pwm too.  What
these look like?

  OG.

**Comment by mamehaze** [comment]
https://youtu.be/LYyRQxqsop8?t=2m
near the bottom.

the 'problem' is they're driven more like lamps, the game code manually strobes each line and writes the data.. so the 'refresh rate' is entirely dependant on the game code, and how often it writes.  treating them as a screen doesn't feel quite right.

**Comment by galibert** [comment]
That's a characteristic of dmds, they're scanned.  They're no more, but no
less of a screen than svgs :-)

  OG.

**Comment by mamehaze** [comment]
well if we're ok with treating them as screens, then it's probably a lot tidier from a layout point of view, and for that reason I think I prefer it.

**Comment by galibert** [comment]
Have a look at attack from mars for instance is rendered, and check whether
it matches the kind of stuff the fruit machine hardware needs.

  OG.

**Comment by mamehaze** [comment]
yeah, I see, not too dissimilar, I think it makes sense to go ahead with this then.

**Comment by mamehaze** [comment]
ok, I've modified the other layouts by hand so that they have screens in them rather than 1000+ dot matrix entries

@johnparker007  if this gets pulled in you'll need to update your generation code :-)

**Comment by johnparker007** [comment]
Great stuff guys this all sounds good to me :)

I did hold off on putting a DMD on the new 'MFME2MAME Debug' View for precisely that reason (massive layout files), some of the XML layout files for DMD games would then have been over 20,000 lines, which did kinda seem like a lot ;) 

I should get some time on Fri/Sat, so I will update the Converter to generate these new DMDs from now on (and add the DMD to the new View).

**Pull request closed without merging**
