### PR TITLE
Updated brazilian portuguese translation

### PR DESCRIPTION
**Pull request by Felipefpl**
Here it is.

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
Unfortunately you seem to have been working against an older version of the source, and your changes won’t apply cleanly.  Please make a new branch in your fork starting with the current state of the master branch in the main MAME repository, and apply your changes to that.

**Comment by Felipefpl** [comment]
Done, is it working now?

**Comment by cuavas** [comment]
> Done, is it working now?

Sorry, for some reason this pull request is still showing the old state of your master branch before you recreated it.  Can you please open a new pull request?

**Comment by Felipefpl** [comment]
ok.

**Pull request closed without merging**
