### PR TITLE
Added 'Iron Blood' to ibm5170_cdrom

### PR DESCRIPTION
**Pull request by RalfVB**
Iron Blood is a decent Korean side scrolling mech action game, reminiscent of Assault Suits Valken on SFC.

Originally obtained from: https://archive.org/details/Iron_Blood_1996_Microforum

### CODE REVIEW

**Comment by RalfVB** [comment]
Using chdman info I get:
SHA1: 45f44fa1a8feb98daba2b7befb6a8360ad39b352
Data SHA1: 6e594464d7c6677134d325b9779f9df414fe5f51

Which one should I use?

**Comment by RalfVB** [comment]
I would like to resolve the merge error, but I'm not sure what to do?

**Comment by DopefishJustin** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-on-github/

**Comment by RalfVB** [comment]
I see now - the option to fix it is disabled for me >

`Tip: If the Resolve conflicts button is deactivated, your pull request's merge conflict is too complex to resolve on GitHub. You must resolve the merge conflict using another Git client like Atom's Git integration or the command line. For more information see "Resolving a merge conflict using the command line."`

Uh, I'd really rather not do that

**Pull request closed without merging**
