### PR TITLE
The start of a Dreamcast softlist

### PR DESCRIPTION
**Pull request by FakeShemp**
This was basically started as a documentation effort, so a lot of the games lack an actual dump and are simply there in the form of informational comments.

Currently only lists # through to A and their clones if any.

Not hooked up to the dc driver as I have no idea how. Will do so if I can get a pointer in the right direction.

### CODE REVIEW

**Comment by angelosa** [comment]
Please make US romsets parent instead of Euro. 
afaik DC Euro isn't even tested at all by anybody so far, and anyway it's an ugly convention that is also addressed by issue #1463

**Comment by Tafoid** [comment]
To OP, with all items added to MAME, we will need to verify/have access to all data committed to source.  In this case, it will be a large amount of data (CHDs) and may take while but this needs to be done.  Links to originally submitted data can be sent to the [Code Submission Email](http://wiki.mamedev.org/images/f/ff/Submit-email.png).  Thanks for your help and contribution.

**Comment by p1pkin** [comment]
@FakeShemp  it is good start, but I have to admit - converting Dreamcast homebrew/scene CDI or NRG to current CHD format produces pretty much "bad" and useless chunk of data. I see no reason add any of these into softlist.

@Tafoid let me know if there will problem with this, I have whole DC US set converted to CHD, and partially PAL and Japan sets.

**Comment by Tafoid** [comment]
@p1pkin MAME's only concern initially is that whatever hashes are provided in source, they can be produced/created from known and available sources of data and are verified to exist.  AFAIK, none of these have been verified the Development Team at this time.  This is why I requested original data from @FakeShemp

**Comment by p1pkin** [comment]
most if not all original data here - TOSEC Dreamcast sets

**Comment by FakeShemp** [comment]
@Tafoid I'm working on it. It'll just take a little time since the data set is quite large.

@p1pkin Yeah, the CDI/NRG dumps will result in bad dumps since data is lost from the original. But a bad dump is better than no dump, and they are clearly marked as bad dumps in the xml. Of course they should be replaced with proper dumps, but we have to work with what we have available until then.

**Comment by p1pkin** [comment]
@FakeShemp its not bad dumps, but current CHD format do not supports multi-session CDs, used in Dreamcast homebrew and pirated games. i.e. current CHD core is not designed to store such disk images. I see no reason trying to put them inthere, until will be added support of such CD disks into CHD core.
however it have sense to document known (original) dumps, in commented form, or with "no dump" disk entry.

**Comment by Tafoid** [comment]
I do tend to agree.  In the end, the driver is not mature enough to handle images even IF they were properly encased in a CHD.  Now, I'll yield to others' on if this should continue  with the bad dumps, or as @p1pkin suggested, showing no_dump instead and simply having the original contents (TOSEC) in a comment as a valid source.

**Comment by rb6502** [comment]
@Tafoid for commercial games, the driver is ready.  And having a ready supply of known-sourced-good images is required to make the driver better.  I can't work on the DRC because I have all of one DC image and it works with it already :)

We should absolutely add 100% of all .GDI sourced commercial games right now, to facilitate this.

Homebrew stuff in non-GDI format I would NO_DUMP.

**Comment by FakeShemp** [comment]
I can do that, no problem. My goal is to add all dreamcast games A-Z, so I'll fix that when I add more games.

Related to that, is the Redump dumps to prefer? I've done some research and the only problem people seem to have with them is that they do not work with current emulators correctly because the gdi format does not support the offset correction they have. Now, tosec dumps on the other hand are not offset corrected, resulting in several dumps having different hashes but containing the same data.

In my opinion, that Redump breaks the gdi format shouldn't matter for MAME, as there should be no reason to not use "better" dumps just for the sake of a specification, especially when everything is read from a CHD and the internal reader can be written to support those non-compliant gdi's. Basically, I think it's dumb to not support "proper" dumps because only the "bad" dumping method works with legacy software.

**Comment by Tafoid** [comment]
I concede to @rb6502 and @p1pkin as far as the future goes for the software list contents.  My sole concern, again, is that whatever group's dumps are chosen as a source are available and, through steps detailed, can be created 100% of the time with chosen source data.

**Comment by p1pkin** [comment]
I'd recommend stay away from Redump sets. because, errrm.. don't know how to say it polite, they are not really understand that they actually doing. in term of GD-ROM disc dumps Redump is not any "better dumps" IMO.
also I had negative experience from using theirs software (DIC), so please better stick to TOSEC, Dumpcast or Trurip dumps.

**Comment by rb6502** [comment]
TOSEC is fine if they're .GDIs.

**Comment by FakeShemp** [comment]
@p1pkin Care to elaborate on why they don't know what they're doing?

To elaborate, I don't consider them better per se, hence I don't mark TOSEC as bad dumps, it's just easier to compare dumps if they're offset corrected (when the discs have different write offsets) and we won't end up with a bunch of "Alts" which all contain the same data but offset.

@rb6502 Yeah, I consider them fine too, but we're in a position where where some games are dumped by both Redump and TOSEC. Which one is of preference?

**Comment by p1pkin** [comment]
> Care to elaborate on why they don't know what they're doing?
sure. for example Redump guys chosen GDI format to store theirs dumps, but only years later they really understood that GDI actually is. technically whole Redump Dreamcast set is bad dumps.

**Comment by FakeShemp** [comment]
As I said before, does it really matter that they came up with their own format and also called it GDI? 

I would personally say the dumps are only bad as in they're bad GDIs, as they don't follow the spec. But the data their method produce seem to be legit and reproducible.

If MAME team wrote a disc emulator that could read these malformed GDIs correctly, would they still be bad dumps?

Not trying to argue, just trying to understand why not to choose them :)

**Pull request merged**
