### PR TITLE
megadriv.xml: Added 104 working items + 4 NOT working

### PR DESCRIPTION
**Pull request by ArcadeShadow**
New working software list additions
--------------------------------------------
Affinity Sorrow (demo) [Second Dimension]
Alien Cat 2 [No-Intro]
Alien Cat 2 (demo) [No-Intro]
Alter Ego - Remastered [RetroSouls]
Arkagis Escape (rev. WX - trial version) [Sik]
Arkagis Escape (rev. ZZ - trial version) [Sik]
Arkagis Escape (rev. YW - trial version) [Sik]
Arkagis Revolution (rev. 01) [No-Intro]
Arkagis Revolution (rev. 00 - trial version) [No-Intro]
Arkagis Revolution (rev. WX - trial version) [No-Intro]
Arkagis Revolution (rev. XZ - trial version) [No-Intro]
Arkagis Revolution (rev. YX - trial version) [No-Intro]
Arkagis Revolution (rev. YZ - trial version) [No-Intro]
Arkagis Revolution (rev. ZW - trial version) [No-Intro]
Astebros (demo v1.1) [NeoFID Studios]
Astebros (demo v2.1, English) [NeoFID Studios]
Astebros (demo v2.1, French) [NeoFID Studios]
Attack of the Petscii Robots (shareware v1.0) [The 8-Bit Guy]
Attack of the Petscii Robots (shareware v1.2) [The 8-Bit Guy]
Beggar Prince (rev 1) (Europe, USA) [No-Intro]
Black Jewel Reborn (demo v0.2) [PSCD Games]
Bone Marrow (demo) [PSCD Games]
Bone Marrow Rebirth (demo) [PSCD Games]
Cave Story - Doukutsu Monogatari (v0.7.0, English) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.7.0, French) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.7.0, Italian) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.7.0, Portuguese) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, Chinese) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, English) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, French) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, German) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, Italian) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, Japanese) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, Korean) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, Portuguese) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, Portuguese-Brazil) [Andrew DeRosier]
Cave Story - Doukutsu Monogatari (v0.8.0, Spanish) [Andrew DeRosier]
Coffee Crisis [No-Intro]
Coffee Crisis (alt) [No-Intro]
Coffee Crisis (demo) [No-Intro]
Debtor [No-Intro]
Debtor (demo 4) [PSCD Games]
Demons of Asteborg (demo 0.1, English) [No-Intro]
Demons of Asteborg (demo 0.1, French) [No-Intro]
Demons of Asteborg (demo 20200721) [No-Intro]
Eyra - The Crow Maiden (demo) [Second Dimension]
FoxyLand [No-Intro]
FoxyLand (demo) [PSCD Games]
GLUF [RetroSouls]
Irena - Genesis Metal Fury (demo 20211209) [White Ninja Studio]
Irena - Genesis Metal Fury (demo 20210121) [White Ninja Studio]
Irena - Genesis Metal Fury (demo 20211002) [White Ninja Studio]
Jessie Jaeger in Cleopatra's Curse (demo) [Bold Game Studio]
Little Medusa [No-Intro]
Little Medusa (demo) [Mega Cat Studios]
Meka Grappler X [Sik]
Miniplanets (demo) [No-Intro]
Miniplanets Remix (rev 02) [Sik]
Miniplanets Remix (rev 03) [Sik]
Miniplanets Remix (rev 04) [Sik]
Misplaced (English) [RetroSouls]
Misplaced (Russian) [RetroSouls]
Old Towers (v1.1) [RetroSouls]
Old Towers (v1.2) [RetroSouls]
Phantom Gear (demo 0.2) [No-Intro]
Phantom Gear (demo 0.5) [No-Intro]
Phantom Gear (demo 0.6) [No-Intro]
Phantom Gear (demo 0.9) [No-Intro]
Phantom Gear (demo 0.17) (Bits Rule Games) [No-Intro]
Phantom Gear (demo 0.17) (Mega Cat Studios) [No-Intro]
Phantom Gear (demo 0.20) [No-Intro]
Phantom Gear (demo 0.21) [No-Intro]
Phantom Gear (demo 0.22) [No-Intro]
Phantom Gear (demo 0.25) [No-Intro]
Phantom Gear (demo 0.32) [No-Intro]
Puzzli [Portabledev]
Reknum - Fantasy of Dreams (demo) [PSCD Games]
Reknum - Fantasy of Dreams (demo 2) [PSCD Games]
Super Heavy Duty [No-Intro]
Super Heavy Duty (preview version) [Playnautic]
Tanglewood [No-Intro]
Tanglewood (GOG release) [No-Intro]
Tanglewood (tech demo build v0.0.11) [No-Intro]
Tanglewood (tech demo build v0.0.14) [No-Intro]
Tanglewood (tech demo build v0.0.15) [No-Intro]
Tanglewood (tech demo 0.1.04) [No-Intro]
Tanglewood (demo 0.8.01) [No-Intro]
Tanglewood (demo 0.9.37) [No-Intro]
The Curse of Illmoore Bay (demo 20191113) [Second Dimension]
The Curse of Illmoore Bay (demo 20190517) [Second Dimension]
The Curse of Illmoore Bay (demo 20190521) [Second Dimension]
The Curse of Illmoore Bay (demo 20190914) [Second Dimension]
The Curse of Illmoore Bay (Halloween official demo 20191028) [Second Dimension]
Thunder Paw (demo) [PSCD Games]
Thunder Paw (demo 2) [PSCD Games]
Tourmaline [RetroSouls]
Ultracore (Europe) [No-Intro]
Ultracore (Europe, USA) (Switch, PS Vita) [No-Intro]
Ultracore (Japan) [No-Intro]
Ultracore (USA) [No-Intro]
Uwol - Quest for Money (v1.0) [No-Intro]
Uwol - Quest for Money (v1.1) [No-Intro]
Uwol - Quest for Money (v1.2) [No-Intro]
Yazzie [RetroSouls]

New NOT working software list additions
--------------------------------------------
Demons of Asteborg (demo 20210827) [No-Intro]
Demons of Asteborg (demo 20210903) [No-Intro]
Demons of Asteborg (demo 20210913) [No-Intro]
Tanglewood (GOG / Windows release) [No-Intro]

### CODE REVIEW

**Comment by ajrhacker** [comment]
Shouldn't "kolobok" in the same list be marked as a hack of Uwol?

**Comment by ArcadeShadow** [comment]
> Shouldn't "kolobok" in the same list be marked as a hack of Uwol?

Fixed the parent/cloneof relationship.

**Comment by cuavas** [comment]
What’s the credit for “Cascade”?  It isn’t listed in the commit message or PR description.

**Comment by ArcadeShadow** [comment]
> What’s the credit for “Cascade”? It isn’t listed in the commit message or PR description.

done it. Sorry!

**Pull request merged**
