### PR TITLE
Revise comment

### PR DESCRIPTION
**Pull request by ZoeB**
Streets of Rage was previously listed at http://www.system16.com/hardware.php?id=707 but was removed between April 2016 and June 2017 judging by The Internet Archive's Wayback Machine:

https://web.archive.org/web/20160421233731/http://www.system16.com/hardware.php?id=707
https://web.archive.org/web/20170612023248/http://system16.com/hardware.php?id=707

The site now suggests, more sensibly, that the original Streets of Rage was only on the Mega-Tech system, not Megaplay.

### CODE REVIEW

**Comment by cuavas** [comment]
Is it worth keeping the comment at all?  A web site had an unsubstantiated claim and removed it.  We're no longer going to have people complaining that system16 says it exists but we don't have it.

**Comment by ZoeB** [comment]
Yeah, I'd certainly be happy to just delete the comment if no-one would object.

**Comment by DavidHaywood** [comment]
it can be deleted

**Comment by p1pkin** [comment]
@ZoeB please notice: system16 site is not ultimate truth, but collection from very various sources (including persons in this PR comments).
for sure it NOT worth to use older texts from system16, which high likely was indentified as wrong, and was removed or changed in current site version.

**Pull request merged**
