### PR TITLE
Update BGFX, BX and BIMG

### PR DESCRIPTION
**Pull request by mmicko**
Update libraries (as of 26th of December 2022):
- BGFX to https://github.com/bkaradzic/bgfx/commit/a93a714632b79b5ddbf5c86ac323fa9b76ed3433
- BX to https://github.com/bkaradzic/bx/commit/aed1086c48884b1b4f1c2f9af34c5198624263f6
- BIMG to https://github.com/bkaradzic/bimg/commit/1af90543ca262c1cfa10aa477aef9dc1b11419f4
- shaders updated (note dx9 and dx11 are not affected, have regenerated them on Windows machine)
- imgui is not using any more deprecated KeyIo functions

### CODE REVIEW

**Comment by rb6502** [comment]
I initially applied this, but it failed to link on my Mac (macOS 13.2) so it had to be reverted.  I would like to see the update since there's some weirdness with the Metal backend since the last time BGFX was updated, but we need to work out the linker issue first.

**Comment by mmicko** [comment]
@rb6502 Can you please try pulling update_bgfx branch at your machine ? I have upgraded my mini to 12.6 and got failed linking (now fixed), but can not upgrade further.

**Comment by rb6502** [comment]
The revised update_bgfx branch links and runs correctly on my Mac, thanks!  Go ahead and setup a new PR and I'll apply it.

**Comment by mmicko** [comment]
Thanks https://github.com/mamedev/mame/pull/10789 is made

**Pull request merged**
