### PR TITLE
JPM MPS: Added 89 Layouts

### PR DESCRIPTION
**Pull request by johnparker007**
Added layouts for these games:
j2adnote
j2always
j2bankch
j2bigbnk
j2bigbox
j2blustr
j2cashbn
j2cashrl
j2cashro
j2cashrv
j2cashtk
j2coinsh
j2coppot
j2cprndx
j2criscr
j2crown
j2cshalm
j2cshcrd
j2cshfil
j2cshnud
j2cshsmh
j2cvault
j2droplt
j2ewn
j2ews
j2exec
j2fasttk
j2fiveal
j2fiveln
j2fqueen
j2frucnx
j2fullhs
j2fws
j2ghostb
j2gldchy
j2goldbr
j2hilocl
j2hinote
j2hiroll
j2hitmon
j2hotpot
j2hotsht
j2hypnot
j2jackbr
j2kingcl
j2litean
j2litnot
j2lovshd
j2lovsht
j2luckar
j2lucky2
j2maxima
j2missis
j2monblt
j2mongam
j2montrp
j2nolimt
j2notesh
j2nudbnz
j2nudfev
j2nudmon
j2nudshf
j2paypkt
j2penny
j2plsmnd
j2plsnud
j2pndrsh
j2rdclb
j2reelbn
j2reelbo
j2reelcz
j2reelmc
j2reelmo
j2silvcl
j2silvsh
j2sldgld
j2slvrgh
j2spcrsv
j2sstrea
j2stahed
j2supfrc
j2suprsh
j2supsft
j2supstp
j2suptrk
j2swbank
j2take2
j2trail
j2tstplt

### CODE REVIEW

**Comment by cuavas** [comment]
Wow, this is probably the most 1337 patch MAME will ever receive!

**Comment by johnparker007** [comment]
Haha cheers! :)  

I'm trying to get as many fruit machine layouts into MAME as I can.  I've also fixed some simple emulation issues, but the low level stuff is waaay out of my abilities... so I'm hoping with these layouts I can lure some of the more knowledgeable emulation coders over to help fix up the fruit machines :)

**Comment by johnparker007** [comment]
haha I've only just spotted that this is in fact pull request #1337 - I thought I was getting kudos for committing over half a million lines of XML! :)

**Comment by cuavas** [comment]
Just one thing - can you make your converter put a newline at the end of the files?  That will reduce diff churn when we run our source cleaning tool on them.

**Comment by johnparker007** [comment]
I was just getting ready to commit another 21 layouts for a different hardware platform, I will update the converter and regenerate them, with a newline on the end.  

All these other layouts that I've already committed will be getting updated periodically, as I make improvements/bugfixes to the converter... so they'll all have newlines on the end in a month or two :)

**Comment by cuavas** [comment]
I'm merging this to get it in for the release as it's a low impact change to fruit machines, but we generally don't merge external stuff in the last few days before release.

**Pull request merged**
