### PR TITLE
work on rhhc152 / ragc153 / dphh8630 / dgun2953 (they run and are playable) [anonymous, David Haywood]

### PR DESCRIPTION
**Pull request by DavidHaywood**
This is an updated version of https://github.com/mamedev/mame/pull/7228 that has been re-synced to current code so that it compiles again.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I also did some further cleanups and added Save State support.

I've done some further research on this myself, and I'm not really sure what the barriers to merging are.  In terms of the changes to the STxxx core that I thought were hacks upon studying the code I was sent, I instead now think might be legitimate, the game code really does write the same value to the port in each case, and expects it to act as a 'reset' so I guess there's some kind of mechanism for knowing if values are written even if nothing has changed, and the core filters that out at the moment.  

The DMA code in the STxxx core is incomplete, but there are no other test cases, and we tend not to implement things that are untested (Kale has berated cam several times for doing that, closing / rejecting submission in the process) so implementing 'what is used' seems like the approach we're telling other people to use.

The SPI code in the driver, I'm not sure can be made into a clean device; these SoCs (at least the GeneralPlus ones) seem to blackbox the behavior a little as well as FIFOing it, so 'out of order' writes get rearranged to the correct order and such.  Effectively this means you're never dealing in raw SPI commands, but instead to the filtered spec of the SoC.  What's there works for the use cases we have.

I'd like to work on the menu protection device a little at some point, so it would helpful to have this merged so that it's there for when I need it; I haven't observed any breakage in the other systems using the SoC, so my feeling is that things can be improved in the tree, rather than this going out of sync again.

I've re-opened this as a draft pull request, as the one I closed to update was, but I think it's better than I thought it was upon first inspection (I was blinded more by just how bad the code I had to clean up was, judging it harshly, when in reality the functionality doesn't seem too bad)

**Comment by cuavas** [comment]
@ajrhacker this is more your area.  There’s a hard-coded `return 0xff` marked as a hack, and some other weird stuff.  What do you think of it overall?

**Comment by DavidHaywood** [comment]
yeah I was tempted to move that one to install in the driver-side to override the internal behaviour until it was better understood if possible, but I don't think we have anything depending on it returning anything else at the moment anyway.

**Comment by DavidHaywood** [comment]
I'm un-drafting this at this point, because I don't feel I can further improve it at present time, and think that in some form, maybe not far off this, it should be acceptable.

**Pull request closed without merging**
