### PR TITLE
more accurate colors for MikroMikko 1

### PR DESCRIPTION
**Pull request by kara1001000**
Colors are based on photos of MikroMikko 1 display on medium brightness.

### CODE REVIEW

**Comment by mmicko** [comment]
Based on images, not not measurements, therefore closed

**Comment by kara1001000** [comment]
Apart from the RGB values in the median-filtered "screenshots", the colors I defined are also based on one-to-one comparison with the screen of a working MikroMikko 1. I don't have calibrated color measurement device, but I do have good eye for color, and these values are very close to the shade of the phosphor that is used in the MM1 display. I'm looking forward to implement the (long) afterglow effect later on as well with hlsl.

Anyway, at least these colors are way better than the default MONOCHROME_GREEN_HIGHLIGHT palette (which has too little separation between light and dark shades of green), and the implementation also serves as placeholder for better values if someone ever does the measurements. So, I'm hoping you would reconsider merging this.

**Comment by rb6502** [comment]
Are there schematics for the system?  Those would allow determining the true RGB values.

**Comment by kara1001000** [comment]
I don't think I have such schemas at hand, and even if I did, those would not reveal any RGB values as we are talking about a monochrome CRT display with green phosphor as the origin of the color. I did some googling, and through
https://en.wikipedia.org/wiki/Monochrome_monitor
found a nice wiki about phosphors:
https://en.wikipedia.org/wiki/Phosphor#Standard_phosphor_types

There we have the wavelength for various green phosphors used in CRT's. Those can be used for heuristically estimating RGB values of the color. For example, from the table we can see that wavelength of P1 (commonly used in green CRTs) is 528 nm. However, we also see that the persistence of P1 is 1-100ms, which immediately excludes it from possibilities regarding MM1, as the phosphor in its display has very long persistence (around 2 seconds on medium brightness!). That fact would make P39 (Zn2SiO4:Mn,As) a good candidate with its 525 nm emission, as it's the only phosphor that is stated to have "long" persistence in the wiki, and also because the color is on the lower end of green wavelengths - also characteristic for MM1 display that could be described to have a very slightly blueish shade of green.

That said, we need to remember that also other matters come into play here, such as the properties of the glass of the display. However, most significant challenge is definitely the fact that there is no way to display a monochromatic light accurately on a modern RGB monitor (unless one of the RGB light sources happens to have exactly right wavelength). Green shades around 520 nm are especially problematic; have a look at the CIE 1931 chromaticity diagram:
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/CIE1931xy_gamut_comparison.svg/400px-CIE1931xy_gamut_comparison.svg.png

Thus, the bottom line is that exact modeling of what we see on those green monochrome screens is pretty much impossible with today's display technology, and trying to do so may even lead to inferior results regardless of good intentions. As much as I like the idea here that we're trying to emulate hardware (not simulate), sometimes it's better to draw the line and use, for example, recorded samples for sounds or best RGB estimates for colors. In fact, when it comes to monochrome displays, I think a photo of the monochrome screen with a good camera might be a very practical way to capture a good estimate for the color: the RGB sensor of the camera (plus camera's firmware) does the estimate for us in a way that's designed to produce as close-to-reality images on modern RGB computer screens of whatever it is that is photographed.

Sorry for the wall of text, this is a fascinating subject and I couldn't help myself. :)

**Comment by Lord-Nightmare** [comment]
So basically, it is a "1.5bpp" system (i.e. off, on, bright, per pixel, like the vt100), but uses a green phosphor crt, and our current green phosphor crt emulation colors are not extremely accurate (or are adjusted for the wrong gamma) ?

**Comment by kara1001000** [comment]
I don't have a reference to say anything about other systems that are using color definitions under MCFG_PALETTE_ADD_MONOCHROME_GREEN_HIGHLIGHT, but at least for MikroMikko 1 display they are wrong; not only the hues, but also the lightness difference between bright and dark green is too small. Both issues are fixed in this branch.

Note that a single definition for "green phosphor CRT" colors is not enough, there are more than one green phosphor types in use, and the brightness setting varies also. In MikroMikko 1, there is a knob in the display for adjusting the brightness, so that should also be somehow implemented in the emulation (together with heuristic rules for RGB mapping) if we want to do it as well as it can be done. Meanwhile, in this branch, colors approximate the middle brightness setting.

**Comment by rb6502** [comment]
I'm inclined to at least reopen this based on these side-by-side screens of a real Osborne-1 and MAME:
http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=102222#Post102222

ADD_MONOCHROME_GREEN_HIGHLIGHT is *way* too subtle with the highlights compared to hardware.

**Comment by kara1001000** [comment]
Rebased, please consider merging. Travis checks pass partially, failures are due to build timeouts.

**Pull request merged**
