### PR TITLE
WIP: miniFORCE 2P21 chassi - advice needed

### PR DESCRIPTION
**Pull request by JoakimLarsson**
This PR needs some thoughts and review I think. It is a 9 slot VME chassi and will emulate the miniFORCE 2P21 as documented on bitsavers. Right now it can load two slot devices in any of the 9 slots:

`mame miniforce -slot1 fcisio -slot2 fcisio etc...`

This works well for fcisio but the other slot device fcscsi triggers an assert in a device driver because there is no CPU in the chassi I assume:

`Fatal error: assert: ../../../../../src/devices/machine/hd63450.cpp:48: m_cpu != nullptr`

So please advice if I should fix the device(s) so they can be used in a system like this. I also need to make a fccpu20 board driver and a slot device. This seems not to be easy build wise so I am thinking of making two copies and maybe share some header file or similar. Thoughts?

### CODE REVIEW

**Comment by rb6502** [comment]
I'd say change the 63450 so it just does nothing if there's no CPU.  That way you can create a VME configuration that does nothing, just as it would IRL :)

**Comment by JoakimLarsson** [comment]
Ok, I have a look, there is a a CPU on the "owner" but not on machine root so it should be possible to change it is happy for whatever reason it needs the CPU.

What about the duplication of code in the case of being both a slot device and a board driver? 

Or is there a way to do both? We tried in mame/bus/vme recently as you know without luck

**Comment by rb6502** [comment]
The closest thing we have to that is the Roland MPU-401.  It's an intelligent MIDI interface consisting of a small metal box with a 6801 and all the I/O connectors, which attaches via DB-25 to cards for the Apple II, PC ISA, C64, and various other computers.  So the external box is a MAME device, and each computer's card is just the logic to interface it to that bus.

So for VME I'd have the card be an independent device someplace and then create host and guest adaptors that call into that device.

**Comment by JoakimLarsson** [comment]
I fixed it so fcscsi works now and regression tested it for esq5505 and x68k.  The fix left the old way of getting the CPU device too because I wasn't sure the subdevice thing would work in the general case. 

So for the independent device that had a host and guest adaptor I thought that was what we tried with the device in mame/machine, host in mame/drivers and guest in mame/bus/vme? C++ is still a bit gibberish for me and build systems in general is not something I fancy a lot, could you give me a bit more to go on, what I need to do?

Anyway, I think this PR can be merged now.

**Pull request merged**
