### PR TITLE
deco_mlc.cpp : Add video references

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by stilett0** [comment]
In general, we do try to keep URLs out of the sourcecode as they can break as things are rearranged and taken offline and become outdated.

Reference video is typically better off done as a informative MAMETesters.org issue.

**Comment by angelosa** [comment]
As Stiletto claimed, those need to go into MAMEtesters bug reports.
Closed.

**Comment by rb6502** [comment]
News to me, I add reference URLs and YouTube links to my drivers and devices a fair amount.  Worst case you can always Wayback Machine something.

**Comment by stilett0** [comment]
Wayback+YouTube isn't really a thing (yet?) so definitely don't count on that for YT.

IDK, I've been around to see links removed from source when they broke, as have you. Goal is that sourcecode provides everything we know, we should avoid linking elsewhere to documentation especially when we can. PDF links as a whole I haven't seen to be stable for much more than five years unless we're talking Bitsavers. It's an extra step of maintenance to run URLcheck or whatever against the source every so often. Driver authors definitely don't stay on top of it as a whole. URLs in source generally don't make me comfortable.

I think @Tafoid was maybe the last person ever to do a sweep and make sure that random URLs still worked whether he wrote the driver (well he has submitted skeletons) or no.

**Pull request closed without merging**
