### PR TITLE
cpu/z80/t6a84: Fix emscripten compile issue

### PR DESCRIPTION
**Pull request by algestam**
This PR changes fixes a emscripten compile issue described in #13041.

### CODE REVIEW

**Comment by cuavas** [comment]
Can you push back on Emscripten and tell them to:
* Stop polluting standard headers with architecture headers, and
* Use reserved names for their macros that start with either two underscores or an underscore followed by an uppercase letter?

If they used reserved names like they’re supposed to, we wouldn’t have to worry about this crap happening.

**Comment by algestam** [comment]
Agree that the macro should've had a better name in the first place. However, I'm not sure if Emscripten is to blame entirely here as they are bundling musl and have added an emscripten specific arch variant with it. All arch variants in musl seems to define `PAGESIZE` (changed from `PAGE_SIZE` in 2018: https://github.com/kraj/musl/commit/c9c2cd3e6955cb1d57b8be01d4b072bf44058762). The emscripten arch variant was most likely added before the name was changed.

We can of course ask Emscripten to change the variable name in the same manner as the upstream musl change but as MAME isn't building on the latest Emscripten builds that still won't resolve the issue with building MAME with emscripten.

**Comment by holub** [comment]
Cuavas' concern was not about who added this variable first.
Build environment shouldn't leak into client's environment. That can create all sort of dangerous results in unpredictable places.

I think we can merge the PR. I'll try to fined the way to deliver "the message" to Emscropten.community.

**Comment by happppp** [comment]
I agree the generic "PAGE_SIZE" shouldn't have been named that way.
But I think it was unneeded here, it's removed: https://github.com/mamedev/mame/commit/991bdf14be74ac69f9012534613433e317f95917

**Comment by holub** [comment]
> Can you push back on Emscripten and tell them to:
> 
>     * Stop polluting standard headers with architecture headers, and
> 
>     * Use reserved names for their macros that start with either two underscores or an underscore followed by an uppercase letter?
> 
> 
> If they used reserved names like they’re supposed to, we wouldn’t have to worry about this crap happening.

@cuavas can you give us a hand? https://github.com/emscripten-core/emscripten/issues/23082

**Comment by FlykeSpice** [comment]
This is the very same issue I came across when compiling mame to android. Android ndk leaks PAGE_SIZE into standard headers aswell: https://github.com/mamedev/mame/issues/12479

**Pull request closed without merging**
