### PR TITLE
fmtowns_flop.xml: split into three lists (original/cracked/misc), 7 new dumps, 1 replacement

### PR DESCRIPTION
**Pull request by rzero9**
Keeping track of what comes from original disks through XML comments was getting a bit unwieldy, and Vas suggested to split the list in the last PR, so now there are three: one for verified dumps from original disks, one for cracked versions and one for everything else. Some of the images in fmtowns_flop_misc likely match the originals, but it's probably better to keep them there until they can be verified.

Also added the latest dumps from the FM Towns preservation community:

New working software list additions (fmtowns_flop_orig.xml)
-----------------------------------------------------------
AIV - A Ressha de Ikou 4 - Map Construction + Power-Up Kit [wiggy2k]
CD+Graphics Player V1.1L10 [cyo.the.vile]
Legends of Valour - Gouyuu no Densetsu - Demonstration [wiggy2k]
Nihongo MS-DOS V6.2 L10 (Kihon Kinou) [cyo.the.vile]
Ponyon [cyo.the.vile]

New not working software list additions (fmtowns_flop_orig.xml)
---------------------------------------------------------------
Mah-Saiko-Jong [wiggy2k]
Nihongo MS-DOS V5.0 L10 (Kihon Kinou) [cyo.the.vile]

Replaced software list items (fmtowns_flop_orig.xml)
----------------------------------------------------
Brandish [cyo.the.vile]

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
The shortnames should match across lists, e.g. Cameltry should be `cameltry` in all lists, and the user selects the version they want by qualifying it as `fmtowns_flop_cracked:cameltry` or `fmtowns_flop_orig:cameltry` if they want to take the non-default one.

(IIRC there’s a bug in the internal UI when dealing with this.  I need someone to remind me exactly what it is so I can look into it.)

**Comment by rzero9** [comment]
Fixed. I'm assuming that, if no list is specified and the shortnames match, MAME will pick whatever list is defined first in the source.

**Comment by Tafoid** [comment]
This seems ok from my end (passes -validate and xmllint) and all items listed in the new split softlists appear to be available.

**Comment by cuavas** [comment]
It’s failing the ORM check though – at least two software lists have the name `fmtowns_flop` (check the opening tag of the root element) so software items can’t be uniquely identified.  That needs to be fixed.  As a courtesy, we usually make the software list name match the filename.

**Comment by rzero9** [comment]
Duplicate names should be fixed now.

**Comment by cuavas** [comment]
What happened to these two entries?  All other entries from the old list are accounted for, but these two were removed without explanation:
```

	<software name="tssl51">
		<description>Towns System Software v2.1 L51</description>
		<year>1995</year>
		<publisher>富士通 (Fujitsu)</publisher>
		<part name="flop1" interface="floppy_3_5">
			<dataarea name="flop" size="1261568">
				<rom name="[os] towns system software v2.1 l51.hdm" size="1261568" crc="0fc9176c" sha1="7d96f648912102b69e1a0329aeebf386a78ece75"/>
			</dataarea>
		</part>
	</software>

	<software name="tssl51a" cloneof="tssl51">
		<description>Towns System Software v2.1 L51 (Alt)</description>
		<year>1995</year>
		<publisher>富士通 (Fujitsu)</publisher>
		<part name="flop1" interface="floppy_3_5">
			<dataarea name="flop" size="1261568">
				<rom name="[os] towns system software v2.1 l51 [set 1].hdm" size="1261568" crc="a5bff98a" sha1="6c5d2cb94fd7d7bb31e6d55ee8700403569e5831"/>
			</dataarea>
		</part>
	</software>
```

**Comment by rzero9** [comment]
Those I wanted to remove, but I forgot to include it in the description, so I'll explain it here. 

Fujitsu only ever distributed the operating system on CD (with the only exception of the English version, which was a closed release for English-speaking developers), so these are simply boot disks created by running TownsOS from CD (or HDD) and formatting a blank disk with the option to copy the system files. They don't really represent any official release of the OS, and the same thing can be created by the user at any time.

**Pull request merged**
