### PR TITLE
msx1_cart.xml, msx1_cass.xml, msx1_flop.xml: Metadata cleanings

### PR DESCRIPTION
**Pull request by ArcadeShadow**
- Replaced countries' abbreviation by their full name
- Lowercase on descriptive words ("Alt", "Cracked", "Hacked", ... )

### CODE REVIEW

**Comment by wilbertpol** [comment]
I don't know what other people's views on this are, but shouldn't we also remove all those default offset="0" attributes?

**Comment by ArcadeShadow** [comment]
> I don't know what other people's views on this are, but shouldn't we also remove all those default offset="0" attributes?

I don't know if this attribute isn't used anymore. Someone can confirm?

**Comment by wilbertpol** [comment]
> > I don't know what other people's views on this are, but shouldn't we also remove all those default offset="0" attributes?
> 
> I don't know if this attribute isn't used anymore. Someone can confirm?

The attribute is still used but the default value is 0. It is used when loading a cartridge that has multiple roms for instance.

**Comment by cuavas** [comment]
Can you please resolve the conflicts on this, and then double-check the net changes?  I’d rather not review over eleven thousand changed lines when it could get screwed up by merging mainline.

**Comment by ArcadeShadow** [comment]
> Can you please resolve the conflicts on this, and then double-check the net changes? I’d rather not review over eleven thousand changed lines when it could get screwed up by merging mainline.

Done.

**Pull request merged**
