### PR TITLE
audio input support

### PR DESCRIPTION
**Pull request by jariseon**
seems to work fine in Mojave, tested using microphone and virtual audio cables.

this PR is probably not ready for prime time yet, but as suggested in the forums, i submitted it here for feedback. i can either hand it over to more experienced mame devs, or try to work it further given some suggestions on best practices.

current limitations:
- platform implementation is for coreaudio only
- binds to default audio input device
- dependency to a 3rd party ring buffer (TPCircularBuffer.c, good one though)

usage in a driver:
```
#include "emu.h"
#include "audioin.h"
#include "speaker.h"

class x_state : public driver_device
{
public:
  x_state (...) : driver_device(...), m_audioIn(*this, "audioin") {}
  void x (machine_config &config)
  {
    AUDIOIN(config, m_audioIn); // stereo
    SPEAKER(config, "lspeaker").front_left();
    SPEAKER(config, "rspeaker").front_right();

    // beware of feedback if routing mic to the speakers !!!
    m_audioIn->add_route(0, "lspeaker", 1.0);
    m_audioIn->add_route(1, "rspeaker", 1.0);    
  }
private:
  required_device<audioin_device> m_audioIn;
}
```

### CODE REVIEW

**Comment by darkstar** [comment]
The indenting seems totally off (tabs vs. spaces)

**Comment by rb6502** [comment]
@galibert can you take a look at this and see if it's what we'd want on the core side?

**Comment by cuavas** [comment]
The additions to the CoreAudio input module clash heavily with the rest of the file.  I don’t think the third-party circular buffer is a worthwhile addition, it’s not doing enough to be worth it.  Managing a single audio buffer is pretty straightforward.

**Comment by cuavas** [comment]
After some more thought, I don’t think this approach is really going to work well.  The OSD side of it needs to work more like the MIDI input, allowing sources to be enumerated and selected by name.  There are too many systems with multiple sound inputs that require more flexibility than the approach in this PR allows.

**Comment by cuavas** [comment]
This approach is not the direction we want to take.

**Pull request closed without merging**
