### PR TITLE
Fixing ROM names in the bootleg version of CAPCOM GunSmoke 1985 to re…

### PR DESCRIPTION
**Pull request by felipesanches**
…fer to the actual labels and PCB references used in this board.

### CODE REVIEW

**Comment by mr-t-guru** [comment]
bootlegs normally don't have constructive names on the labels, or even PCB locations. if yours does then fine but for shared ROMs (i.e. ROMs that have a matching CRC32 used on original PCBs) we leave the names as-is.
you can add a comment to each line on the bootleg to show the bootleg ROM names/locations if you want, but the ROMs used on the original should remain untouched. this ensures ROMs can be merged without overlapping.

**Comment by felipesanches** [comment]
The intent is to document the hardware. There are indeed stickers in the EPROMs of this bootleg pcb and the sticker for the EPROM at location referenced as IC25 in the silkscreen says "14" in its label. So the rom name reflects that by being called "14.ic25"

For me that's much more useful because it serves as technical documentation of the ROMset of this specific board. Not using the corrected name on purpose is simply losing information.

**Comment by mr-t-guru** [comment]
as I have said, any unique ROMs you can label any way you want.
if there are ROMs that also exist on the original such as is common with the gfx/sound etc, those names should be left as-is because those ROMs are from the parent.
and as I just said, if you want to add a comment on the end of each line stating where that ROM goes on the bootleg, go ahead.
there's no point having 2 roms with the same CRC32 and having different filenames.
you add a comment on the end of the line if the name/location is different on a bootleg.
there are hundreds of those comments in MAME src already. this is the procedure to follow.

**Comment by mamehaze** [comment]
we use the labels as per the PCB, often bootlegs have different ic locations too even if the content is the same, so using proper labels is important.  this submission is fine...

**Comment by mr-t-guru** [comment]
I'm fully aware bootleg PCBs have different locations.
in hundreds of other drivers there are bootlegs using the parent rom names with comments showing the bootleg name/location. should we fix all of those possibly 1000 items too?
what about rom merging? 2 roms with the same CRC32....

**Comment by felipesanches** [comment]
I already made clear my point.
And Haze presented support.
You did present your opposing points.

We need more voices in this debate.

**Comment by cuavas** [comment]
Yes, we should fix existing sets that don't use correct labels/locations for the boards they're supposed to document.
Two identical ROMs with different names aren't a problem in a merged set.  You only need one of them to be present in a zipped merged set and MAME will load it for either set as it scans checksums.
Bootlegs are no less deserving of proper documentation.

**Comment by mr-t-guru** [comment]
it's still a mess of contradictions in terms of consistency but fine then go ahead and commit it (I care less about this now than I did 12 hours ago ;-)

**Comment by Lord-Nightmare** [comment]
On 9/10/2015 10:41 PM, Guru wrote:
>
> I'm fully aware bootleg PCBs have different locations.
> in hundreds of other drivers there are bootlegs using the parent rom 
> names with comments showing the bootleg name/location. should we fix 
> all of those possibly 1000 items too?
> what about rom merging? 2 roms with the same CRC32....
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mamedev/mame/pull/317#issuecomment-139433363>.
>
In most drivers i've seen, the bootleg rom shows its own name and 
location and shows the parent rom name in the comments. I believe that 
should be the standard.

-- 
Jonathan Gevaryahu
jgevaryahu@gmail.com
jgevaryahu@hotmail.com

**Comment by etabeta78** [comment]
On Fri, Sep 11, 2015 at 6:32 AM, Jonathan Gevaryahu <
notifications@github.com> wrote:

> In most drivers i've seen, the bootleg rom shows its own name and
> location and shows the parent rom name in the comments. I believe that
> should be the standard.


IMHO, there is no need for the parent rom names in the comments either. the
CRC + SHA combo already documents what matches what in the parent.
bootleg markings and ICs should be used for the bootleg sets, period ;)


   f.

**Comment by Lord-Nightmare** [comment]
etabeta: That does make sense, except in the case where bootleg roms are made of one or more of the parent roms combined onto one chip or split to multiple chips. In those cases, I would definitely add comments explaining.

**Comment by mamehaze** [comment]
> should we fix all of those possibly 1000's of items too?

we go over things fixing them all the time, a lot of choices made in the past were made when we were all young(er) and a little naive.

yes, multiple bootlegs could exist with the things having different names, in those cases we can start to add comments about the other boards, and yes a comment stating where 2 roms in another set are joined / split to make the bootleg is handy too.

the key thing is providing a service to the people with the boards, and a mixed up mash up set of rom labels from original boards and a bootleg is far less useful than just using the bootleg labels.  I'm going to merge this.

**Comment by etabeta78** [comment]
On Fri, Sep 11, 2015 at 7:29 AM, Jonathan Gevaryahu <
notifications@github.com> wrote:

> etabeta: That does make sense, except in the case where bootleg roms are
> made of one or more of the parent roms combined onto one chip or split to
> multiple chips. In those cases, I would definitely add comments explaining.
>
of course, in such a case a comment is handy
but I was only referring to Guru's objections about same rom different name
;)

   f.

**Pull request merged**
