### PR TITLE
apple2gs_flop_clcracked.xml: added 6 dumps, used info tags for a lot of dumps [Brian Troha]

### PR DESCRIPTION
**Pull request by Osso13**
New working software list items
-------------------------------
GBA Championship Basketball: Two-on-Two (cleanly cracked) [Brian Troha]
Reader Rabbit (Version 2.0) (cleanly cracked) [Brian Troha]
ShowOff (Version 1.0) (cleanly cracked) [Brian Troha]
Sid Meier's Pirates! (cleanly cracked) [Brian Troha]
USA GeoGraph (Version 1.0) (cleanly cracked) [Brian Troha]
World GeoGraph (Version 1.3) (cleanly cracked) [Brian Troha]

### CODE REVIEW

**Comment by cuavas** [comment]
@A-Noid33 and/or @Firehawke can you have an initial look at this?

**Comment by A-Noid33** [comment]
> @A-Noid33 and/or @Firehawke can you have an initial look at this?

I'll have time to look at on Friday. 
A-Noid

**Comment by Firehawke** [comment]
I'll take a look tonight.

**Comment by Firehawke** [comment]
I didn't exactly go over it with a fine-toothed comb-- just a quick pass through a number of the entries in the diff viewer-- and it looks to be an improvement on what's in there right now.

**Comment by rb6502** [comment]
Agreed, I also took a look and it's definitely an improvement for anything that wants to parse the <info> tags.

**Comment by cuavas** [comment]
@A-Noid33 you’d been making the source of cracks clearer for the 8-bit Apple II floppy lists.  Are you going to be doing that for the IIgs list as well?

The only other thing I noticed was that separately sold course packs were added to `nicklaus`.  Generally we add these as separate software items with their own release information, etc.  If the add-ons aren’t also cracked, the crack can work with the add-ons from the software list for original dumps.

**Comment by A-Noid33** [comment]
Yes, I have been making updates to the IIGS lists.  I have an update that I
need to push with a bunch of changes for MECC titles.  I’ve been in crunch
mode for work, unfortunately.  I really want to test and push what I have
this weekend.

There are a few titles that have expansion/scenery/course disks added in
the 4am releases on Archive.  We can look into splitting those to separate
entries.

A-Noid

**Pull request merged**
