### PR TITLE
apple2gs_flop_orig.xml: Added 3 Games

### PR DESCRIPTION
**Pull request by A-Noid33**
* New working software list additions (apple2gs_flop_orig.xml)
--------------------------------------------------------------

Dragon's Lair [Antoine Vignau, A-Noid]
Dragon's Lair: Escape from Singe's Castle [Antoine Vignau, A-Noid]
Dragon's Lair II: Time Warp [Antoine Vignau, A-Noid]

### CODE REVIEW

**Comment by A-Noid33** [comment]
I've sent a shared link from google drive to code@mamedev.org.

**Comment by cuavas** [comment]
I’d have to confirm with @Firehawke and @rb6502, but I think we’re trying to stick with raw dumps in this software list rather than adding dumps in cooked formats like `.po`.

**Comment by rb6502** [comment]
These are brand new ports that were just released, so .po is fine.  There's no point in doing a .woz of something Antoine just made.

**Comment by A-Noid33** [comment]
Correct, I decided to use .po, since Antoine has released all his recent releases in .po.  Assuming that this pull is accepted, I would like to add all the games that he has posted.   I think it would be good to add hard drive images (*.chd) for DL, DLII, DL Singe's Castle since Antoine has also released a .po hard drive image with all 7-8 disks on a single hard drive.  This would make the games much more playable.

**Comment by rb6502** [comment]
I'm planning to make A2 and A2GS softlists for hard drive images sometime soon, those can be added then.

**Comment by A-Noid33** [comment]
Antoine added DLIII yesterday.  I will add this one this weekend.   Do I need to do anything else for this existing pull request?

**Pull request merged**
