### PR TITLE
bus/electron/plus1: Use BBC Micro-type slot for analogue joystick inputs

### PR DESCRIPTION
**Pull request by ajrhacker**

### CODE REVIEW

**Review by Pernod70 — COMMENTED** [review]
This makes sense, and not sure why I hadn't done it previously, maybe I added the plus1 device before I created the analogue slot.
My only comment is that I use PORT_REVERSE on the plus1 JOYx bits so could do with testing. I don't mind it being merged but will be at least a week before I can actually test it.

**Comment by cuavas** [comment]
Probably not such a great idea to merge right before release if it isn’t going to get proper testing for a while.

**Comment by ajrhacker** [comment]
One thing that may need adjusting for in the future is that the Plus 1 doesn't support LPSTB, but none of the MAME devices use that now.

**Comment by Pernod70** [comment]
I've compared schematics of the bbc and plus1 and the channel numbers appear to be the same for the uPD7002 and ADC0884, and no lines are inverted. So maybe one of the ADC devices needs some minor attention. I can test and investigate further when back from vacation.
The LPSTB is on my TODO list but very low priority as only demo programs that came with light pens made use of it.

**Comment by ajrhacker** [comment]
I see the following line in `src/mame/acorn/bbc_m.cpp`, copied and pasted into all other uses of the uPD7002 device:

> return ((0xff - m_analog->ch_r(channel_number)) << 8);

**Review by Pernod70 — APPROVED** [review]

**Comment by ajrhacker** [comment]
I've done some testing, and directional joystick inputs on both systems appear to be working with these changes.

**Pull request merged**
