### PR TITLE
added basic layout and frontpanel image

### PR DESCRIPTION
**Pull request by JoakimLarsson**
I don't know where to put the image, so I put into artwork and the layout file under src/mess/layout. How does the artwork distribution usually work? Anyone interested in this board would have their own custom ROM:s so it wouldn't make much sense to bundle them with the ROM:s.

### CODE REVIEW

**Comment by Robbbert** [comment]
After registering, go to the exact link Haze posted, and read carefully the text at the top of the screen. You have to follow the instructions exactly, to have any chance of getting approved.

**Comment by rb6502** [comment]
Yeah, look for where it says "Why has my account not been approved?" at the top of http://forums.bannister.org/ .  The same instructions appear during the registration process, but a significant number of people somehow manage to ignore them.

**Comment by JoakimLarsson** [comment]
Yeahh, I'll read it thoroughly at all times but the first, maybe I ended up on a blacklist with that user name Bouncer?! We'll see.

**Comment by JoakimLarsson** [comment]
I just include this in the main pull request for the driver. I haven't been approved at the forum yet to discuss the distribution of layout and the board in general but as soon as I can I open a thread there

**Pull request closed without merging**
