### PR TITLE
Use autofinder for Seibu sound ROM bank; fix airraid regression (nw)

### PR DESCRIPTION
**Pull request by ajrhacker**
Since this fixes a regression, this should be applied to the release branch as well.

### CODE REVIEW

**Comment by cuavas** [comment]
Cherry-picked onto release branch @Tafoid can we get a regression run?  Also try other things that use dirom (e.g. Toki and its bootlegs) since @ajrhacker changed how it works with the Seibu change.

**Comment by Tafoid** [comment]
@cuavas To me, it makes more sense to me to apply this to master first where it will be detected and tested daily.... and when it is has been tested, then you could apply those changes into the release branch.  This forces me to pull the release branch and make a new compile and run a test on that on top of my normal daily testing of master.  Sounds like a time waster to me since the release branch should be steady as I tested it when it was from master a couple days back and I shouldn't need to retest it.

Nevertheless, I'll do what I can to verify these changes are acceptable.  I just pray that future possible branch additions will be handled to master first, then release branch unless you'd want to volunteer yourself to test the affected drivers/devices/sets.

**Comment by cuavas** [comment]
But if you test master, you're testing whatever's there asking with changes scheduled for release, which is potentially the least stable point since it's the beginning of a cycle before any attempt at stabilisation. It would be better to just test the release branch during the freeze period and switch back to master after release.

**Comment by cuavas** [comment]
*along with

Anyway the point is master and release0180 have already diverged - merging this into master and testing that wouldn't help with confidence for the release because it would be combined with the other changes on master. We can live without tests of master for a few days.

**Comment by cuavas** [comment]
The commits are in master, but they don't appear as a merge because of the cherrypick process.

**Pull request closed without merging**
