### PR TITLE
new WORKING machines (Teléfono interactivo de TV)

### PR DESCRIPTION
**Pull request by DavidHaywood**
new WORKING machines
------
Teléfono interactivo de TV (Spain) [ClawGrip, Sean Riddle, David Haywood]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
this might actually work fine, as the mini games do seem playable, but I don't know what all the buttons are on the unit, so could do with a picture of the unit to verify them / how it should behave.

(also I'd like to investigate why I need a ROM patch to boot before promoting it)

**Comment by clawgrip** [comment]
> this might actually work fine, as the mini games do seem playable, but I don't know what all the buttons are on the unit, so could do with a picture of the unit to verify them / how it should behave.

[Interactive_TV_Phone_manual.pdf](https://github.com/mamedev/mame/files/6125179/Interactive_TV_Phone_manual.pdf)

Here's the manual (English / Spanish). Also, could you please add also ArcadeHacker to the credits?
The manual says that the game is from Taikee, but there's no Taikee logo on screen.

Thanks!!!

**Comment by DavidHaywood** [comment]
hmm I'm not sure what the 3 other buttons tested in test mode are then, maybe some sensor for the receiver?

**Comment by clawgrip** [comment]
> hmm I'm not sure what the 3 other buttons tested in test mode are then, maybe some sensor for the receiver?

No, there weren't sensors on the receiver... I did some pics of the actual phone, I'll post them tomorrow.

**Comment by stilett0** [comment]
> Here's the manual (English / Spanish).

I'd rather these sorts of things be sent in, in ways other than Github. Perhaps CODE@ ?

**Comment by DavidHaywood** [comment]
alright, the remaining 'buttons' are actually the slider switch for non-tv mode, and the 'bell' for non-tv mode.

that manual does list 'loudspeaker button' but there's no input associated with that, so maybe it's just a physical thing?

I've promoted it, the boot patch is probably some protection thing.

**Comment by DavidHaywood** [comment]
Also I've added Taikee.  I wonder if the Oregon Scientific logo replaces a Taikee logo, as it sounds like OS handled the Spanish localization?

That would likely mean there are other versions, but I've never seen these for sale.  You're having much more luck finding Spanish versions of some of these!

**Pull request merged**
