### PR TITLE
pacman.cpp: Use same company name for FAMARE S.A. on every game and driver (nw)

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by happppp** [comment]
"S.A." yes, but does FAMARE have to be allcaps? Is it an acronym?

**Comment by clawgrip** [comment]
Yes it is: Fabrica de Maquinas Recreativas S.A.

Anyway, almost every Spanish company name is, like CIRSA (Compañía Internacional de Recreativos S.A.), UNIDESA (Universal de Desarrollos Electrónicos S.A.), GAELCO (Gabinete Electrónico Consultivo), PETACO (Proyectos Electromecanicos de Tanteo y Color), INDER (Industria Electromecánica de Recreativos), etc.

So... Beter as Famare S.A.? Famaresa?

Thanks!!

**Comment by happppp** [comment]
What were they known as most commonly?
I find Famaresa here, written on the cab: https://www.youtube.com/watch?v=ceYpgdBH1AU

**Comment by clawgrip** [comment]
Famaresa then! I'll close this PR and will open another one tomorrow changing the pacman and williams drivers accordingly.

Thanks!

**Pull request closed without merging**
