### PR TITLE
seta, x1-010: Fix pitch in downtown

### PR DESCRIPTION
**Pull request by superctr**
Downtown has an issue in MAME where all the music and sound effects play at an octave higher than intended (compare [the PCB](https://www.youtube.com/watch?v=DBDnFbIDpA8) with [how it sounds like in MAME today](https://youtu.be/e6-Vqz_XJ6A?t=113)).

~~My solution is to add a frequency divider config in x1-010 which can be used by downtown (if needed, other sets with this problem, however I can't think of any right now).~~

~~The other solution would be to reduce the X1-010 clock, however this would affect the sample rate (which is already low enough in MAME) and waveform envelopes.~~

Discovered that bit 7 in the status register appears to divide the frequency. Implementing this fixes the pitch in downtown without affecting other games. (see bottom)

### CODE REVIEW

**Comment by happppp** [comment]
Sorry, it is very unlikely that the chip works this way.

**Comment by superctr** [comment]
You may be right. Upon investigating further, I found out that Downtown writes bit 7 to the channel status registers, which the other games do not seem to do. Going to do some more testing, and if it works, I will add the commits

**Comment by superctr** [comment]
After discovering bit 7 in the status register, I implemented it. This fixes the pitch in Downtown, and it did not seem to affect any other game I've tested so far.

**Comment by happppp** [comment]
ok from me

**Pull request merged**
