### PR TITLE
Fixed input in Space Lords and added PORT_NAMEs

### PR DESCRIPTION
**Pull request by MASHinfo**
I used the 'Service Mode' in Space Lords, the manual and a Flickr picture to fixed the controls
and added also PORT_NAMEs.
PORT_BIT( 0x00ff0000, IP_ACTIVE_LOW, IPT_UNUSED )  seems to be a debug freeze button.

Manual: www.gallopingghostarcade.com/qr/spacelords/manual.pdf
Controls: http://www.flickr.com/photos/10707024@N04/26548492116

### CODE REVIEW

**Comment by rb6502** [comment]
My understanding is that we are currently looking for someone to move PORT_NAMEs to an external data file and don't want to accept more of them in order to incentivize that happening.  If you can separate that part out of the patch the reset is probably OK.

**Comment by happppp** [comment]
I don't think it's a black & white issue. We probably shouldn't accept
super trivial ones, for example where button 1 is changed to "Jump" and
button 2 to "Punch". More complex control schemes like this one are better.

MASH can you clarify this? Are they buttons? Jamma pins? or what?
It makes me think of a cab link option. Don't implement them like this, but
as a read function.

+	PORT_BIT( 0x00001000, IP_ACTIVE_LOW, IPT_OTHER ) PORT_NAME("RIGHT of
DOUBLE") PORT_CODE(KEYCODE_C)     /* RIGHT of DOUBLE */
+	PORT_BIT( 0x00002000, IP_ACTIVE_LOW, IPT_OTHER ) PORT_NAME("DOUBLE
SYSTEM") PORT_CODE(KEYCODE_V)       /* DOUBLE SYSTEM */
+	PORT_BIT( 0x00004000, IP_ACTIVE_LOW, IPT_UNUSED )
+	PORT_BIT( 0x00008000, IP_ACTIVE_LOW, IPT_OTHER ) PORT_NAME("4 COIN
COUNTERS") PORT_CODE(KEYCODE_B)     /* 4 COIN COUNTERS */

**Comment by MASHinfo** [comment]
@hap
I didn't found any informations about the RIGHT of DOUBLE, DOUBLE SYSTEM and
4 COIN COUNTERS button. So i decided to add them as keys.

> Don't implement them like this, but as a read function.
Don't know how? Can you please do it!

**Comment by happppp** [comment]
Ok, then something like this instead:

+ PORT_BIT( 0x00001000, IP_ACTIVE_LOW, IPT_SPECIAL ) /* TODO: RIGHT of
DOUBLE */
+ PORT_BIT( 0x00002000, IP_ACTIVE_LOW, IPT_SPECIAL ) /* TODO: DOUBLE SYSTEM
*/
+ PORT_BIT( 0x00004000, IP_ACTIVE_LOW, IPT_UNUSED )
+ PORT_BIT( 0x00008000, IP_ACTIVE_LOW, IPT_SPECIAL ) /* TODO: 4 COIN
COUNTERS */

**Comment by happppp** [comment]
-> #1586

**Pull request closed without merging**
