### PR TITLE
start putting some 68705 functionality in the CPU core rather than copy+pasted in all the drivers.

### PR DESCRIPTION
**Pull request by mamehaze**
start putting some 68705 functionality in the CPU core rather than copy+pasted in all the drivers.

as this is a lengthy task I've created a derived CPU type with the new functionality to aid in the process without disrupting existing drivers that haven't yet been updated.

started with tiger heli / slap fight.

### CODE REVIEW

**Comment by mamehaze** [comment]
@Lord-Nightmare  you expressed an interest in this, some extra hands certainly would not go amiss.

**Comment by Tafoid** [comment]
Be careful how much we do here.. would hate regression we can't fix before release.

**Comment by mamehaze** [comment]
I was thinking this was probably past the release deadline anyway.  Either way, for the 2 games in the driver I've looked at I gave them a good run-out and found them to behave exactly as before.

**Comment by Tafoid** [comment]
If you aren't concerned about getting it into 0.181, we can wait until the tag is made in the next couple days.. no problems.

**Comment by mamehaze** [comment]
I'll let you decide, I'd consider this specific request low-risk tho, all reads/writes were monitored, results were identical to before the changes.

**Pull request merged**
