### PR TITLE
New working clones

### PR DESCRIPTION
**Pull request by clawgrip**
------------------
Beastorizer (USA, set 2) [jordigahan, ClawGrip]

### CODE REVIEW

**Comment by clawgrip** [comment]
I'd appreciate some help figuring out what the differences between this set and the existing one are (I see none), to name it accordingly.

**Comment by happppp** [comment]
USA set 1, USA set 2

**Comment by Osso13** [comment]
The set already in MAME has a Sep 22 1997 11:42:18 string at 4c9c, while this has a Jun 21 1997 14:09:23 string. So I suggest renaming the one already in MAME as newer and this one as older.

**Comment by cuavas** [comment]
How have you come to the conclusion that the ROMs not dumped for this set will match the parent?  I tend to prefer to be pessimistic and assume ROMs might not match.

**Comment by clawgrip** [comment]
It may take a while (if ever) to have this SMD ROMs dumped, so, in the meantime, I've marked them as BAD_DUMP.
Also renamed the sets as "older" and "newer", as suggested.

**Comment by DavidHaywood** [comment]
If the date strings are known I'd include them in the description rather than 'older' and 'newer'
That way, if somebody has a different board, it's easy to see without having to have the existing ROMs and loading them up.

**Comment by clawgrip** [comment]
Agree on adding the dates on the game descriptions...

**Comment by clawgrip** [comment]
I should be ready to merge now...

**Pull request merged**
