### PR TITLE
Change count_leading_zeros/ones to use __builtin_clz on gcc

### PR DESCRIPTION
**Pull request by aaronsgiles**
Currently these are implemented with inline assembly on each platform. Also add 64-bit variants.

### CODE REVIEW

**Comment by cuavas** [comment]
The trouble with this is you've now got the test for zero which incurs a data dependency at best (if it decides to use a conditional move) or a conditional branch at worst, even for targets that have an instruction for counting leading zeroes that *is* defined for zero. The x86 implementation we have currently at least guarantees that it can coalesce the test for zero and only cause a data dependency. When the whole point of the exercise is to provide an efficient primitive for an operation, this seems counter-productive.

**Comment by aaronsgiles** [comment]
True, but by using the builtin with surrounding code, the compiler can do work to pull the data dependency out away from the operation. So it's not guaranteed to be worse and in fact could be better on Intel since the compiler can't reorder/schedule the asm instructions. I didn't see any perf delta when switching.

Regardless, I need a 64-bit version. I'm happy to back off and restore the inline asm if you're still not convinced, but I won't be able to write the ARM/PPC-optimized versions of the new 64-bit ones. (I mean, I probably could if gcc didn't insist on the crappy AT&T syntax.)

**Comment by ajrhacker** [comment]
It might be worth keeping in mind for long-term strategy that equivalent functions are part of the standard library in C++20.

**Comment by cuavas** [comment]
I’m with @ajrhacker – when we eventually move to C++20, this will take care of itself.  In the mean time, I’ll worry about having half a dozen implementations.  Please continue discussion on #8178.

**Pull request closed without merging**
