### PR TITLE
Changed mame_ui_manager::draw_text_box() to scale text that cannot be fit on the screen

### PR DESCRIPTION
**Pull request by npwoods**
When the 'vgmplay' MAME driver was started up, the game info screen was too big.  This fixes that problem

### CODE REVIEW

**Comment by cuavas** [comment]
This is going to end up producing illegibly small text on low-resolution displays. Can you make it scrollable rather than just shrinking it when the length blows out?

**Comment by npwoods** [comment]
I agree that making this dialog scrollable is the ideal solution, but that is more of a drastic change.

Besides, the entire assumption around draw_text_box() is that it is a simple operation that doesn't require interaction.  I cannot think of any scenario where it would be better for draw_text_box() to push text off screen than it would be to shrink the text.

**Comment by Tafoid** [comment]
I wouldn't see the harm in this being a quick fix before release and working out the scrollable/pageable window in the next release.  vgmplay is likely the only machine in MAME that has so much hooked up that would require this 'shrinking' anyway - so effect should be minimal.

**Comment by cuavas** [comment]
>I cannot think of any scenario where it would be better for draw_text_box() to push text off screen than it would be to shrink the text.

If you're using a 15kHz monitor, or running a game at native resolution, or using a small window, or running embedded in a browser window,  the text will already be at the limit of legibility at its normal size. I mean that's why we supply uismall.bdf for these scenarios,  it pushes the limit down to a lower resolution using hand-drawn bitmaps. Cutting the text off still allows some of it to be read, while shrinking it makes all of it illegible. Incomplete legible text is better than completely illegible text.

**Comment by rb6502** [comment]
Closing for lack of consensus.

**Pull request closed without merging**
