### PR TITLE
Extend system library support (nw)

### PR DESCRIPTION
**Pull request by h0tw1r3**
Extend USE_SYSTEM_LIB_* to support providing the library name and include directory.
To link against system specific lib names and header path: (ref #711)

USE_SYSTEM_LIB_LUA=lua5.3:/usr/include/lua5.3

Should not change existing functionality.

### CODE REVIEW

**Comment by h0tw1r3** [comment]
request for comment, **not fully tested please do not merge**

**Comment by h0tw1r3** [comment]
Tested on debian and arch: gcc 5.3.1, clang 3.6, and mingw64 5.3.0 (mxe).

**Comment by h0tw1r3** [comment]
Tested on clean msys2 gcc 5.3.0 x86_64 (windows 10 ent).

**Comment by jmallach** [comment]
Thanks for writing this @h0tw1r3! While I was working on hacking the build system to make it do what I wanted (but actually missing some bits of how the build system is generated), I found my build also builds lzma from 3rdparty, but there seems to be no provision to use the system one.

As lzma is quite security-sensitive, it'd be great to include support for system lzma too.

Other 3rd party deps that could be interesting to allow as system lib is http-parser. I'm unsure of lua-zlib and lua-filesystem: they have Debian packages available but I'm unsure if these are taken into account when system Lua is in use.

**Pull request merged**
