### PR TITLE
added support for reading/writing hiscore files from cart images

### PR DESCRIPTION
**Pull request by eadmaster**
example hiscore.dat entry:
````
nes,smb:
Super Mario Bros. (World).nes:
Super Mario Bros. (W) [!].nes:
@:maincpu,program,7df,4,0,0,ff
````

### CODE REVIEW

**Comment by cracyc** [comment]
I don't think that this is something we want as part of the official distribution.  We try to encourage people to use softlist images.

**Comment by eadmaster** [comment]
As alternative i could use the cart CRC hash (from `manager:machine().images["cart"]:crc()`), but i think long filenames are less cryptic for the regular user.

Softlist images are good for developers who prefer shorter names to type in the terminal and source code, but for console rom dumps long filenames are more common.

Btw, if you prefer to reject this i will host it in a separate repository and rename the plugin as `console_hiscore` so it can be side-installed with the other shipped plugins without conflicts.

**Comment by DavidHaywood** [comment]
Softlist stuff isn't just about shortnames tho, it's the way MAME ties together ROMs and other cartridge components without having to fall back to detection hacks.  Nobody should be using loose ROMs for console stuff.

**Comment by rb6502** [comment]
Softlists are preferred because they're much easier for users, but we do and will continue to support loose dumps.

**Comment by eadmaster** [comment]
> If this patch works for both kinds of roms and passes coding standards I don't see a problem with it.

yes, softlists are still supported, in fact i've been using both while testing the plugin.
But if a loose dump is passed, then the generated hiscore file will get its name. e.g.: `mame nes -cart "Super Mario Bros. (W) [!].nes"`  will generate an hiscore file named `Super Mario Bros. (W) [!].nes.hi`.

The double extension is intentional to prevent name conflicts between roms with the same filename and different systems (e.g. "Tennis (USA).nes" and "Tennis (USA).sms").

I've verified this also works fine with compressed rom dumps, since mame returns this nice string as filename `"/home/andy/Documents/NEW/console_hiscore/Super Mario Bros. (W) [!].zip/Super Mario Bros. (W) [!].nes"`.

Another solution would be storing the hiscore file in a subfolder with the system name (e.g. `nes/Super Mario Bros. (W) [!].hi`), but i've ditched this atm.

Btw i have other enhancements in mind for the hiscore plugin, if this this pull gets accepted i will send another one soon...

**Comment by eadmaster** [comment]
I've updated the branch with my latest changes (now hiscores are stored in subdirs).

**Comment by cuavas** [comment]
This seems to break high scores for systems without cartridge slots.  It gives errors like:
```
[LUA ERROR] in execute_function: plugins/hiscore/init.lua:108: attempt to index a nil value (field 'cart')
```

It has been reverted in c39f46d6d259f686879d2afe226e7219d7266a39

**Pull request merged**
