### PR TITLE
Make wpdata and wpaddr debugger variables device-local, not global

### PR DESCRIPTION
**Pull request by ajrhacker**
(nw) Split debugger_cpu and device_debug into separate sources

### CODE REVIEW

**Comment by d235j** [comment]
diff that was requested to make the changes to debugcpu.cpp clearer: https://gist.github.com/balr0g/7c26b6dff49ff1261791a4b6cac87bf9

**Comment by balr0g** [comment]
diff that was requested to make the changes to debugcpu.cpp clearer: https://gist.github.com/balr0g/7c26b6dff49ff1261791a4b6cac87bf9

**Comment by ajrhacker** [comment]
Ah, but a single-file patch wouldn't quite compile on its own, for the subtle reason that debugger_cpu::m_debugger_access has no declared public accessor. The lack of a definition for debugger_cpu::watchpoint_check could also give rise to a linking error.

In any case, I think my commit message should make the secondary change clear enough.

**Comment by cuavas** [comment]
It's still easier to actually see what you changed in `device_debug` when it's split out like this.

**Comment by ajrhacker** [comment]
In case the devs have forgotten about this, I rebased this feature branch a few days ago to put the major change into a separate commit from the related minor change.

**Comment by ajrhacker** [comment]
Updated this to 0.176, whose last-minute automatic cleanups caused a conflict. I'd like at least a response if this still can't be accepted for some reason.

**Comment by cuavas** [comment]
There are now three unrelated changes in this pull request:
* moving device_debug to a separate file
* moving script processing from debug_cpu to debug_console
* moving some watchpoint stuff from debug_cpu to device_debug

The first two are pretty non-controversial and I'd probably merge them pretty quickly. The problem is that the third item is tied up in the same pull request. Given that watchpoints are tied to diexec, and the code after the change requires device_debug to do a whole lot of access to debug_cpu anyway when doing a watchpoint check,  I'm not convinced it's a good idea. You haven't given the motivation for it either.

In any case, it's better not to tie up unrelated changes in a single pull request.

**Comment by ajrhacker** [comment]
The thing about debugger_cpu is that it's a bit misnamed, since it's not a per-CPU structure at all. The vast majority of the interface between device_execute_interface and the debugger is handled by the device-owned device_debug class. The majority of debugger_cpu actually has to do with handling memory accesses for debugger expressions, though it also manages things like which CPU is currently executing.

**Pull request closed without merging**
