### PR TITLE
MajorHavoc fixes and new driver

### PR DESCRIPTION
**Pull request by jessaskey**
-Fixed issues in vector machine which did not allocate enough vector space to draw Major Havoc Space Maze levels
-Added new driver for upcoming release of Major Havoc - The Promised End (mhavocpe). Had to do some minor restructuring of the other mhavoc drivers to accommodate the increased ROM space of mhavocpe

### CODE REVIEW

**Comment by stilett0** [comment]
Wow, @jessaskey. Oldskool respekt. :)

This is too late to be absorbed into MAME 0.197, but we'll need the ROMs for testing anyhow, so expect to see this in MAME 0.198 :)

**Comment by jessaskey** [comment]
Okay, that is fine by me, thanks. I just wanted to get this checked in so the driver was in the full release sometime after CAX... the game won't be 'done' until later this fall so the ROM hashes will be variable for quite awhile. Once I get them solidified better, I will look into defining clones for my pre-releases and put in actual hash values. Im not a Git expert by any means, so can I just continue define my clones in my fork until you actually pull for 0.198?

**Comment by DavidHaywood** [comment]
if there are development builds of the game it would be interesting to document them too, so don't throw them away.  the development of recent software can be interesting.

**Comment by jessaskey** [comment]
Yeah, Im keeping all the various versions of the pre-release ROM's... I expect after release, there will still be bugfix and 'new' builds with some small feature enhancements too, so I will have plenty to choose from.

**Comment by cuavas** [comment]
Please fix your text editor so entire files don't show as changes.

**Comment by jessaskey** [comment]
Hey cuavas... Yes, I will address here this week and update my branch.

**Comment by jessaskey** [comment]
Hi Mame team.... I now have a working set of PRE-RELEASE ROM's that I made for CAX this past summer. It appears that the syntax has changed however on the the main MACRO's now.... could someone assist me in getting my mhavoc drivers checked into the main branch since Im not really a fluent MAME dev?

I am updating the CSUM's right now so that the CAX pre-release ROM's will run without loading warnings. However, 

Any suggestions on the best way to get this merged... should I just grab a current copy of the MAME trunk?

Sorry Me = MAME noob.

**Comment by rb6502** [comment]
Best course depends on if changes to the actual emulation are necessary.  If it's just a ROM swap, emailing the ROMs to "code at mamedev.org" is all you really need to do.  If it does require other changes, you'll want to pull latest MAME and rework the changes against it.

**Comment by cuavas** [comment]
I don't see how this qualifies for inclusion in MAME.  It's a personal hack/homebrew running on arcade hardware, and as a rule MAME does not include such ROM sets.  For an arcade set to be included in MAME, it generally has to be sold commercially and operated in public arcades, or be a common operator modification.  Isn't this something that's a better fit for HBMAME, which aims to document homebrew and hacks created for arcade systems?

**Comment by DavidHaywood** [comment]
I thought with the merge of MESS we were moving towards being more open about such things as long as they represent a substantial amount of effort and have actually been tested on PCBs / real hardware etc.

In this case it sounds like the project was developed using real hardware and exhibited at CAX, which to me passes the barrier.  It's only fair to recognize the active development scene for these, just as we should recognize it for some of home systems (where the software being developed today pushed the hardware much harder than anything developed at the time, and thus is highly beneficial to support)

**Comment by rb6502** [comment]
We'd accept this if it were on a computer or console, and supposedly we're all about anything with a CPU now.  I understand we don't want to just take every dumb graphics hack someone's made for an arcade cabinet, but this was playable in a cabinet at CAX which I think qualifies.

**Comment by cuavas** [comment]
I don't know about Craft, but Uzebox is well-documented with multiple examples existing.  More than one person has built one of them, and complete source code and CAD files are available.  It's probably a better example of that than SITCOM.

**Comment by cuavas** [comment]
Oh, and Uzebox is also available commercially in kit form: https://www.adafruit.com/product/1291
It's definitely not a one-off.

**Comment by jessaskey** [comment]
I can probably help define this project better for the MAME team if that helps. In general, this is a ROM patch (it has to be legally). My code is compiled and this release has a large set up of new features all built upon the premise that Atari made Owen release the game before it was done and henceforth, there is no homeworld at the end of the game. This version also brings into maze-play some enemies that were not in the original game but were located in the ROM's. In addition, it has speech and many other 'upgrades'. Owen has been working on this with me for over two years now so I can get this released and done at CAX this coming year. It is really a 'directors cut' of the game in my mind. Owen and myself presented the premise to the game and it was running on a single game at CAX in BETA form for folks to play. Next year, it will be complete at CAX. Im getting the driver running now because folks can play the CAX beta if they are owners of the game they have the rights to patch their ROM's.

I am working on rights to actually release this (no money being made however) with blessings from Atari but if that does not happen, it will simply remain a ROM patch that legal owners of games can use to burn on their game OR play on MAME.

If you all have any specific questions, let me know. 

Back to my original question as well, I finally got MAME to compile on my machine (not sure what the issue was) so I will work on getting my driver updated and clean.

Is there any documentation or a post (I didn't find any) on the SYNTAX changes...  an example is...

this -> AM_RANGE(0x0000, 0x07ff) AM_RAM AM_MIRROR(0x1800)
went to -> map(0x0000, 0x07ff).ram().mirror(0x1800);                 

I realize this is just the old macro seemingly being reverted back to the base call... but where can I find all the old MACRO defs now at this point... I will keep working on it, Im sure macro listing is quite large anyway.... since I couldn't compile, I was sorta stuck, but I go over that hurdle finally. 

thanks ya'll.

**Comment by jessaskey** [comment]
I'm working with one of the Repro marquee houses to create a Marquee for this game as well. So it will be badged and subtly 'packaged'.

**Comment by jessaskey** [comment]
And, to rb6502's comment... this software/ROMset won't run on the mhavoc driver or any of the existing drivers. The Paged ROM space has been expanded and it also uses the Speech driver which I included in the 'Return to Vaxx' driver years ago... the speech is supported on the Atari PCB if stuffed, and the Paged ROM expansion is supported via a PCB modification documented here...  https://github.com/jessaskey/mhavocpe (under the conversion folder). You may see that there is also a build of MAME64 sitting there that is a compiled version from around Mame 84 which has the mhavocpe driver included. I would like to get this into the main MAME release however.

**Comment by jessaskey** [comment]
Im going to close this PULL REQUEST because of the conflict of old files.

**Pull request closed without merging**
