### PR TITLE
new WORKING machines

### PR DESCRIPTION
**Pull request by DavidHaywood**
new WORKING machines
------------
Mahjong Block Jongbou 2 (Japan) [ShouTime]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
(afaik this should be sent to the DU, credits may need adjusting, so hold off merging just yet)

**Comment by dinkc64** [comment]
is this reparations from shou for taking the 2 cave games?

**Comment by iamthelaw2041** [comment]
Yeah I'd rather have the CAVE shooters back and they can keep this dogshit.

**Comment by DavidHaywood** [comment]
it's rarer, more valuable, and was considerably more work to add to the driver than said shooters (the graphic bank decoding took a a good 5-6 hours to figure out and implement in a neater and more correct way than it was implemented) but you do you.

**Review by cuavas — APPROVED** [review]

**Pull request merged**
