### PR TITLE
stvvdp1.cpp : Updates

### PR DESCRIPTION
**Pull request by cam900**
Fix transparency and endcode behavior, Fix gouraud shading behavior, Fix sprite count, Add note

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I notice you deleted various comments about specific games

// disable transmask since transparent pen is checked below (sasissu racing stage background clouds)
// Scud: the disposable assassin wants transparent pen on 0

were these games tested with the changes?

**Comment by DavidHaywood** [comment]
also it would still IMHO make more sense to simply port the VDP1/VDP2 from mednafen, as the MAME code is built on many bad designs that aren't going to be fixed by simple refactoring of the existing code.

**Comment by cam900** [comment]
Official vdp1 document says: sprite transpen is 0 at all case, endcode is 0xf(4bit), 0xff(6/7/8bit - actually 8 bit for each data), 0x7fff(15bit direct).
I correct this related to official documents, but other undocumented cases used just mimic old driver behavior.
sassisu is tested. and some sprite transparency issue are fixed(ex:bomb)

**Comment by cam900** [comment]
Before PR

0000_stvvdp1_trans
0001_stvvdp1_trans
After PR

**Comment by angelosa** [comment]
Haze is right on this: removing game comments from LEGACY code is beyond bad, and it’s even worse that this PASSED validation to deserve a merge.

In case you wonder: those comments are for future core rewrite, and undermining like this throws my willingness to do so out of the window.

A.

**Comment by rb6502** [comment]
If you need the comments, save a copy of 0.209 until your rewrite surfaces.

If you haven't started the rewrite yet, just port Mednafen's Saturn code.  Haze and I are in 100% agreement on that.

**Pull request merged**
