### PR TITLE
Preliminary software list for FM Towns CDs

### PR DESCRIPTION
**Pull request by rzero9**
Filled up to the letter A. More will come later.

### CODE REVIEW

**Comment by etabeta78** [comment]
would it be possible for you to submit (either via mamedev.org submission
or via PM at MESS forums) also a datfile with crc & sha1 of the original
bin+cue used to create CHDs?
this would help for re-creating the CHD for other users and to retrieve
original material if we need to recreate the files at a later stage.
once you have completed the list, I will integrate the info into the list
semi-automatically :)

other than that, the submission is very promising, so please keep up your
work! :)

    f.

**Comment by rzero9** [comment]
Your PM inbox seems to be full, so I've submitted it to the mamedev.org address. The DAT includes everything in the collection,not just CDs (floppies, BIOS files, etc.) but everything needed should be there.

**Comment by etabeta78** [comment]
Thanks a lot. I will take care (and free some PM space :) )

   f.

**Comment by Tafoid** [comment]
Someone assembling CHD's came across some issues (as reported by 'oddi' in IRC #mess-dev (freenode):

> looking at dat for fm towns just noticed that Alice no Yakata CD and Alice no Yakata III have the same sha1 so Alice no Yakata III is probally wrong and maybe 6 chds have bad sha1 , try few variants for convert from Neo Kobe Collection, but not luck

>38-man Kilo no Kokuu [folder: 38mank - size: 1mb]
missing set: 38-man Kilo no Kokuu
missing chd: 38-man Kilo no Kokuu.chd [chd-sha1: 8b3aed4b095183e3b9a0ee88e7dfd34d1c44e7d7]
3x3 Eyes: Sanjiyan Henjou [folder: 3x3eyes - size: 0]
missing set: 3x3 Eyes: Sanjiyan Henjou
missing chd: 3x3 Eyes - Sanjiyan Henjou.chd [chd-sha1: 243e61ee754eb6c7efc55a692cc89b0dd31d944c]
4D Driving [folder: 4ddriv - size: 0]
missing set: 4D Driving
missing chd: 4D Driving.chd [chd-sha1: b09e774be4ee926dc32efd2e3b28dd72bc223c76]
Amaranth III [folder: amarant3 - size: 0]
missing set: Amaranth III
missing chd: Amaranth 3.chd [chd-sha1: 9c83fcd4623dd62dcfc7c683c82836704f8665a7]
Angel [folder: angel - size: 0]
missing set: Angel
missing chd: Angel.chd [chd-sha1: e8da3eae3b949459751fd027579aee52b167dc2f]

**Comment by rzero9** [comment]
Hi,

Sadly I've found no easy way to convert CloneCD metadata to cuesheets while preserving track pregaps, so I had to use a bit of a convoluted method. I'll describe it so other people can replicate it:

- Mount the CCD image as a virtual drive (I used Daemon Tools since it preserves the track pregaps)
- With Exact Audio Copy: configure gap detection as "Method C / secure", and select "action / detect gaps".
- Select "Action / Append gaps to next track".
- Select "Action / Create CUE Sheet / Current Settings" and save the CUE file.
- Dump all audio tracks with EAC.
- With Isobuster, open the CCD file and extract the data track as raw data (2352 bytes/sector).
- With your favorite tool, remove as many sectors from the end of the data track as there are in the track 2 pregap (for example, 2 seconds pregap = 150 sectors = 3252800 bytes removed from the end of track 1).
- Edit the CUE with the track 1 file name and MODE1/2352.
- Feed the CUE file to CHDMAN.

If no one is able to do it, maybe I did something wrong. In that case we may have to remove those entries and try again later with a more straightforward method...

**Pull request merged**
