### PR TITLE
Further improvements to the Patinho Feio driver & CPU

### PR DESCRIPTION
**Pull request by felipesanches**
This pull request needs feedback & code review before getting merged into master.

This is a big set of improvements to the CPU emulation, with new instructions implemented, as well as to the driver of the Patinho Feio computer.

I tried to cleanup space-indentation, but there may be some still needing to be fixed, please let me know if that's the case. I also tried to address some issues pointed out by cuavas last week.

If the code looks good, then feel free to merge it. Otherwise, please let me know what still needs improvement.

### CODE REVIEW

**Comment by felipesanches** [comment]
I'm aware that there may be build issues with this changeset. I've been experimenting with emscripten builds as well as working with both full native build as well as native patial builds. Recently both native builds seem broken, but I still can get it to build with emmake. I'm not sure exactly what's wrong, but I'd appreciate feedback from whoever feels confortable with MAME's build rules.

**Comment by cuavas** [comment]
Looks good.  We're currently in feature freeze for release, but after the release this should be good to merge.

**Comment by cuavas** [comment]
the one issue I can see is that the UTF-8 in port names will have to be replaced with escapes to pass through the source cleaning tool.  For better or for worse, we still require our C++ source to be 7-bit ASCII.

**Comment by cuavas** [comment]
I'm merging this now, but some time before the 0.175 release, please open a pull request to replace UTF-8 in strings with escape sequences or it will be mangled by srcclean.

**Comment by cuavas** [comment]
This PR was missing the CPU header and hence was reverted.

**Pull request merged**
