### PR TITLE
Add improved qsound_hle core

### PR DESCRIPTION
**Pull request by Lord-Nightmare**
This adds the rewritten QSound HLE by ValleyBell and superctr with full spatialization, among other accuracy improvements.

### CODE REVIEW

**Comment by cuavas** [comment]
You knew what the response would be.

**Comment by MooglyGuy** [comment]
I will be applying this patch in approximately 6 hours unless actively barred from doing so, as I disagree in the strongest of terms with the decision to reject this patch, on the following grounds:

1. No valid reason was stated publicly. A snarky "you knew what the response would be" is not an acceptable rejection reason from the self-selected project leader.
2. It's obvious that the plan is to use the DSP16 DRC for the purposes of speed once it's ready, at which point LLE QSound will be made the default. This completely ignores e.g. JSMESS, and non-x86/x64 platforms, and is flatly unacceptable.

**Comment by cuavas** [comment]
Also, this code definitely shouldn't be merged until the obvious endianness issues are fixed.

**Comment by galibert** [comment]
FIxing the endianess issues means:
- make the rom region ROM_REGION16_LE
- then, only access the region through an aligned u16 pointer.  No u8, no
u32.
- also, use std::copy and std::fill, avoid memset/memcpy

Things should be better then.

  OG.

**Comment by cuavas** [comment]
You shouldn't even copy the tables.  The client program can supply word pointers into ROM space for tables it wants to use

**Comment by DavidHaywood** [comment]
I think this should be included, actually I think this is one of the most worthwhile and significant submissions we've had in probably a year.  It gives the benefits of the LLE without any of the bugs or drawbacks.

Qsound is used on a lot of performance sensitive systems, not just CPS2, but some of the ZN stuff that does require a half-decent machine already.  The weight of the LLE vs. the HLE is obscene in such cases.

We're also going to want to emulate the CPS2 SSF2 Tournament Battle at some point, which IIRC will mean running 8 linked machines, you absolutely don't want to be emulating a 50Mhz DSP there.

Even if we end up with a DSP16 recompiler there are environments that aren't friendly to generated code for security reasons or whatever else, and as you say the C backend for the recompiler is slower than the interpretors in every case I've seen.

The LLE should certainly be an option (and personally I'd like to see it as a switch, not a build-time thing) but this, using the ROM tables, but implemented natively is a massive improvement on the existing HLE, and is very likely the code most people are going to want to port if they bring MAME to a new platform (be it for commercial purposes, or just use on lower powered devices)

Either way, it's an improvement on what's already there, it's code people are more likely to want to take forward, it has no real cost, and unless you're ready to rip out the HLE and force everybody onto the LLE there's no logic to rejecting things that improve what we have.

**Comment by rb6502** [comment]
As far as I know, there is no precedent for pushing a better-wrong-way into MAME after the right way has been implemented.  Nobody rewrote the Taito C-chip in C++ after it was dumped, or the IGS ARM chip, or anything else.  This code is a great thing for FBA and other emulators that don't give a shit about the actual operation of hardware.  We do have higher standards here.

**Comment by DavidHaywood** [comment]
Sorry, but the LLE isn't live.

The HLE is.

However you look at it this is an improvement.

You're just being an arrogant ass about this.

**Comment by MooglyGuy** [comment]
If OG's proposed changes are implemented, there is no reason why the active HLE code cannot be improved based on knowledge gleaned from currently-disabled LLE code.

Furthermore, all of the comparisons that are being brought up are being made in bad faith. Proper emulation of the C-Chip didn't cripple performance for a simple 2D driver to the point of only running on high-end machines.

MAME already has a dwindling number of users, and decisions like these will simply accelerate that number even faster towards zero. Maybe once the DRC is implemented _and_the C backend has been fixed to not literally be slower than the interpreter so as to not shit all over non-x86/x64 platforms, we can talk about removing the HLE code. But given that it's currently the live device, improvements to it should and will be accepted.

**Comment by happppp** [comment]
github is not for drama, act civilized please :)
If you want to vent, there's the shoutbox on bannister.org.

**Comment by MooglyGuy** [comment]
Whatever. I'm apparently not allowed my opinion.

**Comment by MooglyGuy** [comment]
Sorry for the history spam. My deleted commented was to the effect of if OG's changes are addressed this should go in, as it is the live device. When the DSP is complete and the C backend is not actually slower than the interpreter, we can see about removing it, but improvements to the live advice should go in.

**Comment by rb6502** [comment]
Performance has never been a bar to implementing correct LLE emulation before.  The C-Chip is significantly slower than Mish's pile of reverse-engineered tables.  The IGS ARM is *much* slower than doing the equivalent functions in C.

**Comment by rb6502** [comment]
Also, why is this being submitted by LN?  superctr submits stuff all the time and it generally goes right in.

**Comment by superctr** [comment]
@rb6502 you got me there. This code was made for VGMPlay (the dedicated application). Since implementing a DSP16 emulator there would be too much effort and the performance would cause issues with things like seeking (especially backwards seeking, since we don't have savestates). And reverse engineering the DSP code is fun, we ended up discovering the ADPCM channels and exact details on the FIR filters and reverb effect.

I used MAME to develop and test the sound core, that's why I have a branch on my account.

Back in April I proposed replacing the current (old) HLE code with this so we could have accurate QSound emulation until the issues with with the LLE are fixed. Fixing the LLE seems like it would take a while, involving a new Z80 core, a DSP16 DRC, and making the audio stream more robust, so having an improved HLE would result in more accurate emulation in the meanwhile.

But based on the response I got in IRC, I decided not to send any PRs on this. Honestly, it was quite saddening hearing that my code was essentially worthless and being accused of having an agenda.

Yesterday LN approached me again about it, I told him it's fine if he sends a PR, but this time I really want to stay out of the MAME politics. I guess that was no use in the end.

I can fix the issues OG and Vas brought up regarding endianness and changing ROM copies to lookups, @Lord-Nightmare will just have to give me write access to the branch on his account or I'll open a new PR from my account.

**Comment by Lord-Nightmare** [comment]
@superctr I can close this PR and reopen #3819 which I had accidentally based directly on your repo instead of my fork of it, if that makes things easier for you.

**Comment by superctr** [comment]
That would be fine.

**Comment by rb6502** [comment]
@superctr: Just to clarify, nobody thinks your code has an agenda, that would be dumb.  We do believe LN's time would be better spent fixing speech chips than trying to push this :)

**Pull request closed without merging**
