### PR TITLE
ti85.cpp: New clones marked as NOT_WORKING

### PR DESCRIPTION
**Pull request by jlachniet**
TI-84 Plus Orion (Bootleg) [Julian Lachniet]
TI-84 Plus Orion (Boot Code 1.03) [Julian Lachniet]
TI-84 Plus Color Silver Edition (Boot Code 4.0) [Julian Lachniet]

### CODE REVIEW

**Comment by Tafoid** [comment]
As near as I can tell, these clones did not get sent as of yet.  Please send them to CODE email.

**Comment by Tafoid** [comment]
You have sent again your google drive link which points another submission, #3299.

This is what we need to support this pull request...
We have "v42.bin" which matches the posted hash CRC32/SHA1, but the size is misrepresented in source as 2MB (image shows 4MB in size).  Assuming "v42.bin" is correct and you've changed the source to match the size of file that was sent, we still are missing the two others you've added.  Please be sure that these match up and are the correct size.

TI-84 Plus Orion (bootleg) [folder: ti84pob - parent: ti84p - size: 1mb]
missing set: TI-84 Plus Orion (bootleg)
missing rom: ti84pobv255orn.bin [size: 1048576] [CRC32: b8992646] [SHA1: 643c2f03d0743ffe61d9ca5ed813bc748add7c44]

TI-84 Plus Orion (1.03) [folder: ti84pov3 - parent: ti84p - size: 1mb]
missing set: TI-84 Plus Orion (1.03)
missing rom: ti84pov3v255orn.bin [size: 1048576] [CRC32: 85e77211] [SHA1: 32e1962f33ec1c3b76921cda2a96e95fd0a6c805]

**Comment by jlachniet** [comment]
I will double check the sizes of both commits tomorrow

**Comment by jlachniet** [comment]
Is this fixed now?

**Pull request merged**
