### PR TITLE
Irem GA20: rewrite sound update

### PR DESCRIPTION
**Pull request by ValleyBell**
This pull request rewrites the sound update routine in order to
- clean up the code (for-loop instead of manually inlining update code for each channel)
- use value 0 as sample terminator, because that is apparently what was intended  
  The current code plays from (start) to (end - 0x20) and the magic 0x20 just makes no sense.
  I checked all currently supported GA20 sample ROMs to make sure that the change doesn't break anything.

### CODE REVIEW

**Comment by happppp** [comment]
This is mostly fine by me. I recommended @ValleyBell to make a PR when he mention this on the freenode chat. I think the end address safety check can be removed, we can assume that it's probably meant for sample looping. None of the games seem to use it, so they write the address past the end of sample marker.

**Comment by happppp** [comment]
I'll test it

**Comment by rb6502** [comment]
It's not unheard of for chips to stop at a zero sample *or* the length register, whichever comes first.  The ES5503 behaves that way, for instance.  This might be worth trying on hardware at some point.

**Comment by happppp** [comment]
I see the check triggering sometimes in gunforc2, when the game prepares the next sample while a sample is still playing and this next sample happens to be at a lower address than the current sample.

**Pull request merged**
