### PR TITLE
lwriter.cpp: Stub out a minimal print controller

### PR DESCRIPTION
**Pull request by jrmuizel**
This is enough to avoid the timeouts when initializing the print controller and
the ROM now crashes when trying to print the test page.

### CODE REVIEW

**Comment by jrmuizel** [comment]
@rb6502

**Comment by rb6502** [comment]
One question on this one - the DTR callback installation is commented out.  Is that intentional, given you also added a lot of code to that callback?

**Comment by jrmuizel** [comment]
It's the old callback installation that's commented out. I'll just remove it. I don't actually have the hardware for the board so it's not exactly clear what dtrb is actually connected to. It seems weird that it would be used for communicating with the print controller but that definitely seems to be what the ROM is doing.

**Comment by rb6502** [comment]
DCD was used on the early Macs as part of the mouse interface, so there's definitely precedent for Apple using some of the SCC handshake lines as GPIO.

**Comment by jrmuizel** [comment]
I've updated it to remove those commented out parts.

**Comment by Lord-Nightmare** [comment]
> 
> 
> It's the old callback installation that's commented out. I'll just remove it. I don't actually have the hardware for the board so it's not exactly clear what dtrb is actually connected to. It seems weird that it would be used for communicating with the print controller but that definitely seems to be what the ROM is doing.

I have a LaserWriter IINT board here which I can trace things on if needed, which SCC pin needs to be traced to where? I don't have the actual 'printer engine' part of the LaserWriter IINT, just the mainboard.

**Comment by jrmuizel** [comment]
@Lord-Nightmare, it should be the /DTR//REQB pin (which I believe is pin 24). I'd expect this pin to connect to one of the pins on the 'print engine' connector.

**Pull request merged**
