### PR TITLE
thoop crash research

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by dinkc64** [comment]
My good man - thank you for not giving up on this :)

**Comment by peterferrie** [comment]
Given the obfuscation of the target address, it looks like a
copy-protection check that's failing.  Then we have to wonder how many
others exist.

**Comment by peterferrie** [comment]
It's an emulation failure.  There's a timing loop at 0x49e-4ac.  It's
counting frames between interrupt-triggers.  0x49e writes the count to
0xffdb62.
While fighting the second-stage boss, when the pink things fly out,
0x8970 is called.  0x8988 fetches from 0xffdb62.  If the value is >
0xdd1 (via 0x898a) or < 0xdb1 (via 0x8992), then 0x89ac sets 0xffdc45
to 5.
The value is 0xd29 in our environment.  We're too slow, as far as the
game is concerned.

While fighting the third boss, 0xc2e8 is called.  After passing checks
to know exactly when to trigger (specifically, after the boss is
defeated and the power-up animation is finishes), 0xc350 checks if
0xffdc45 is 5.
If it is, then we reach 0xc368, which corrupts memory and crashes
during respawn.

**Comment by peterferrie** [comment]
I suspect that the safer change would be setting $ffdb62 to 0xdc0 or something when PC reaches 0x4ae.

**Comment by DavidHaywood** [comment]
Interesting, I suspect the frame rate shouldn't be exactly 60hz, what range
of values would pass that check?

**Comment by peterferrie** [comment]
> Interesting, I suspect the frame rate shouldn't be exactly 60hz, what
> range of values would pass that check?

A refresh rate of >=57.3, <=57.7 works.  There's room to add more
decimal places if you want a more precise range.
I didn't check if adjusting the vblank time had any effect.

**Comment by DavidHaywood** [comment]
Maybe a combination of that and waitstates, assuming CPU clock is good, not
sure how vbl
timing would affect it, but if it can that would be worth considering

**Comment by dinkc64** [comment]
confirmed works fine @ 57.5

**Comment by DavidHaywood** [comment]
That's a very unusual rate though, so I suspect there are other factors, as
a solution for now it is far less invasive however, so I'll probably change
it to that and add some notes so that the reasoning is clear for future
reference

**Comment by cuavas** [comment]
The trouble with that is it will throw off the timing of everything that the games base on the frame rate.  I know changing the frame rate is a simpler code change, but is it really “less invasive” when it will change so much behaviour?

**Comment by DavidHaywood** [comment]
Well it *could* be correct, some toaplans are 57, but other gaelcos have
been measured around 59. Existing is probably incorrect at least

**Comment by DavidHaywood** [comment]
Splash.cpp is set to 58, which is also close to 57.5, so it's not out of
the realm of possibility, also the person testing squash for me was having
unusual sync issues compared to many other pcbs

**Comment by rb6502** [comment]
~57 Hz isn't impossible given other games we've encountered with weird vsync rates (some Midway stuff runs at 53, IIRC).  It would be nice to get someone to measure an actual board, or at least to find a real hardware video and eyeball how fast things move compared to MAME though.

**Comment by DavidHaywood** [comment]
Yeah, trying to get a vid recorded, the one on yt claiming to be PCB is
clearly MAME (bad priorities and all)

**Comment by clawgrip** [comment]
> What can of video do you need? The attract mode for two or three minutes is enough?

**Comment by DavidHaywood** [comment]
Longer the better, sync over 10 minutes tells us more than over 2 or 3

**Comment by DavidHaywood** [comment]
https://www.youtube.com/watch?v=CZomQLZCAbI

57.42hz stays in good sync compared to real hardware footage, until the real hardware footage oddly dies a fraction earlier after about 10 minutes (which is quite strange in itself as this attract demo plays many times and doesn't usually die there)

it's definitely in the ballpark of what the code is checking for anyway, 60 is far too fast, 58 is too fast, 57 is too slow.

**Comment by DavidHaywood** [comment]
oh, and using this hz for squash, with the different CPU clock squash has (20/2, rather than 24/2 as found on thoop, despite being the same PCB) also fixes the 'bad sprites after continue' glitch in Squash, which is an even more bizarre thing to protect, but therey ou go...

**Pull request closed without merging**
