### PR TITLE
mame/drivers/plus4.cpp: fixed Coverity "Arguments in wrong order" war…

### PR DESCRIPTION
**Pull request by firewave**
…nings (nw)

### CODE REVIEW

**Comment by galibert** [comment]
Vu le prototype de plus4_cd_r/w, il serait bien meilleur de corriger le
prototype de plus4_expansion_slot_device::cd_r/w.

   OG.

**Comment by firewave** [comment]
It looks like calls in devices/bus/plus4/exp.cpp are also switched when calling the plus4_cd_r/w methods.

**Comment by galibert** [comment]
Damn, I answered in french?  I'm tired today :-)  I was saying, given the
plus4_cd_r/w prototype, it would be better to fix the
plus4_expansion_slot_device::cd_r/w prototype.

  OG.

**Comment by firewave** [comment]
I took another look and changing the prototypes would cause more intrusive changes than this since there's several plus4_cd_r/w methods.

**Pull request closed without merging**
