### PR TITLE
electron: correct beeper tone

### PR DESCRIPTION
**Pull request by kazblox**
NOTE: The comments below are obsolete, when we were trying to figure out the ULA clock. Please see the latest comment by me.

(also sneaking in some minor fixups in galaxold.c and galaxian.c)

### CODE REVIEW

**Comment by startaq** [comment]
It would be verified if you derived the frequency from the schematics, this is just another guess.

**Comment by kazblox** [comment]
>It would be verified if you derived the frequency from the schematics, this is just another guess.
Oh right, sorry.

**Comment by kazblox** [comment]
Just checked the schematics, sound is generated inside a chip, which means I cannot tell the exact frequency.

**Comment by galibert** [comment]
What frequency is going into the chip in the first place?

  OG.

**Comment by galibert** [comment]
Answering my own question, 16MHz.  So use XTAL_16Mhz / ( 512 * ( data + 1
)) and it will be a way better looking guess.

  OG.

**Comment by mr-t-guru** [comment]
the service manual says SOUND 0/P• Delivers a tone to the speaker from an internal oscillator.

key word is *internal*.
meaning a separate osc outputting something unknown and nothing to do with the external 16MHz input.
There goes your theory ;-)

**Comment by kazblox** [comment]
"So I suppose whatever the BBC has should be used as the frequency."

If you're talking about the frequency of bbcb's sn76489 and the electron beeper....
Thing is that the electron beeper operates in KHz while the SN76489 operates in MHz. both values are completely different.

**Comment by kazblox** [comment]
Thing is that, the Acorn Electron Advanced User's Manual says the generated sound algorithm is like this:
1 MHz / [16 * (S + 1)]
Which is the exact and WRONG algorithm Wilbert Pol used for the driver.

**Comment by kazblox** [comment]
>So I suppose whatever the BBC has should be used as the frequency.

Er... the SN76489 in the BBC is 4MHz, while the Acorn Electron beeper used in SN76489 translation operations is in KHz

**Comment by mr-t-guru** [comment]
show me on the schem where it says a SN76489 runs at 'x' speed....

**Comment by kazblox** [comment]
Guru: BBC Micro schematics don't mention anything about what the speed of the SN76489 is....

**Comment by kazblox** [comment]
4000000 or XTAL_4Mhz / ( 128 * ( data + 1 )) seems logical. Good enough?

**Comment by Pernod70** [comment]
In the BBC the 16 MHz clock line is supplied to the ULA via pin 8. The clock is divided via a chain of flip-flops into clocks of 8 MHz, 4 MHz, 2 MHz and 1 MHz, which are output on pins 7, 6, 5 and 4 respectively. The 4 MHz clock is used by the SN76489.

**Comment by kazblox** [comment]
Alright, did what Guru thought was best.

**Comment by mr-t-guru** [comment]
my point is there's no documentation or evidence to suggest what has been done is correct.
it's one big guess.
as per my statement above.....
the service manual says SOUND 0/P• Delivers a tone to the speaker from an internal oscillator.
key word is internal.
without docs on the ULA internal means anything.
so just do whatever is necessary to make it sound right and people will be happy.

**Comment by kazblox** [comment]
Guru: you know what, forget all of what I said above:
http://www.8bs.com/othrdnld/manuals/essentials/Eaug_pdf.zip

Apparently this is where Wilbert Pol got the algorithm from. It's exactly correct except the divider is off by 16.

False alarm people, nothing to see here, no code was harmed during the making of this pull!

**Comment by kazblox** [comment]
Let's just stick to the fixed up version of the manual's algorithm.

**Pull request closed without merging**
