### PR TITLE
SPG2XX - Make audio emulation a subdevice

### PR DESCRIPTION
**Pull request by DavidHaywood**
SPG2XX - Make audio emulation a subdevice (I need to reuse some of it for SPG110)

### CODE REVIEW

**Comment by MooglyGuy** [comment]
The change you refer to was intentional, I thought it might fix the too-slow timing. If it breaks things instead, feel free to undo it.

**Comment by DavidHaywood** [comment]
yeah, it causes the speech to cut off abruptly on the "icanpian jjs" title screen

**Comment by DavidHaywood** [comment]
should this be using channel_bit instead? the old code uses channel, but channel isn't really valid in this context

const uint16_t channel = (offset & 0x00f0) >> 4; // this can't be correct? bit 0x10 is part of register select?  (AUDIO_CHANNEL_ENABLE is 0x00 AUDIO_WAVE_IN_L is 0x10)

set_envelope_count(channel, get_envelope_load(channel));

**Comment by DavidHaywood** [comment]
based on the context of the surrounding code I'm guessing that is the case

**Comment by StinkerB06** [comment]
Is the audio emulation code allowed to go to https://github.com/mamedev/mame/tree/master/src/devices/sound ?

**Comment by angelosa** [comment]
If it's internal to the SoC (which I guess it is from a quick glance of the code) it's not a bad idea to have it in the same folder. 
Actually I'd rather move everything to a subfolder of machine itself, but I'm rather more concerned about doing drivers folder first due of the github 1000 files limit.

**Pull request merged**
