### PR TITLE
added crude lamp layout to "Video 21" so that it is actually worthy of the 'Working' tag

### PR DESCRIPTION
**Pull request by DavidHaywood**
(game doesn't let you know what to do onscreen, only with the lamps, it's still vague without a 'deal' lamp, but at least somewhat playable now and I suspect this is how the machine was)

### CODE REVIEW

**Comment by cuavas** [comment]
I know we lack proper lamp persistence models, but a timer running completely independently of the writes is a poor substitute.  See vgmplay for a better way of doing lamps that should go out if they're not repeatedly driven.

**Comment by happppp** [comment]
I don't think the lamps go off by themselves. For example if you hold the payout button, the start lamp is enabled, indicating you can press start while holding payout, to enter bookkeeping. The game design is a bit strange, I think it's meant for 2 persons, a dealer(operator) and player.

**Comment by happppp** [comment]
Another possibility is there is no deal button, but instead `PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_CUSTOM ) PORT_VBLANK("screen")`. Bit 6 of the same port seems to be hopper related.
Also, it looks like 44b5 is double or nothing, 44b6 is to take winnings.

**Comment by DavidHaywood** [comment]
right, there not being a 'deal' button is a distinct possibility given that there's no lamp associated with it, and pressing it is completely redundant.

in the end this simply failed my 'pre-release quality check' and I wanted to make sure we're not putting out what one user called "trickware" last time once again, by telling people things work when they don't.

there are already too many things that got promoted and advertised as working in recent releases when they don't work, eg. none of the beatmania II DX stuff is really working, it always desyncs, and gives random read errors.

it's all well and good maintaining 'code standards' but the actual functionality is what end users are going to look at and judge the project on, and things like marking games as working, when they blatantly don't work is not helping.

**Comment by galibert** [comment]
Do you realize you wrote that rant 2.5 hours after the game was downgraded to non-working in master and the release branch because, yeah, it's not working?

  OG.

**Comment by MooglyGuy** [comment]
Well thank god you spoke up then, I can't imagine what would have happened if it weren't for your brilliant insight and can-do attitude.

**Pull request merged**
