### PR TITLE
ddragon.c and ddragon3.c: Input ports named

### PR DESCRIPTION
**Pull request by RJRetro**
ddragon.c: inputs named in ddragon and ddragon2
ddragon3.c: inputs named in all supported games (Double Dragon 3, Combatribes, and WWF Wrestlefest)

Added for convenience for end users setting up inputs.

### CODE REVIEW

**Comment by RJRetro** [comment]
Both builds compiled on my end but ran into a time limit with Travis and AppVeyor.  What do I do from here?

**Comment by mamehaze** [comment]
we tend not to name 'obvious' buttons as it would just bloat the structures.

we should probably support a way of doing this with external files in all honesty.

**Comment by balr0g** [comment]
In addition we don't add copyright-holders tags for dipswitch or port name additions. You would still be credited in the whatsnew, though.

**Comment by p1pkin** [comment]
I guess add name to copyright-holders tag was the only goal of this "contribution" )

**Comment by RJRetro** [comment]
p1pkin, I find that insulting.  I simply saw every other person who'd added something to the code also add their name.  I only did what I thought was customary in that regard and meant no disrespect.

The goal of this contribution was convenience.  The layout of the buttons is not always so obvious and in some cases, even confusing.  Hope to see something implemented soon.  Love the xml idea.  For now, I'll consider maintaining my own branch.

**Comment by balr0g** [comment]
@RJRetro, I'm not sure why @p1pkin thought that was necessary. I was just trying to be informative regarding our practices, and hopefully I was clear.

Naming improvements are useful for documentation purposes. However, I'll let the others decide on this. @mamehaze may be on the right track, but I'm not sufficiently familiar with current practices in this particular situation to really say.

**Comment by RJRetro** [comment]
@balr0g I thank you for your information and am I happy to have had my submission even considered.  I like what @mamehaze proposed and in the future, would love to possibly help with the creation of some xml configs.

**Comment by mr-t-guru** [comment]
heh! I have influenced almost every driver in MAME in some way or other with either dumps or hardware info/readme's, running trojans to crack protection etc etc and almost none of them have my name in the copyright. you would need to do a lot more than change a few text button labels to have your name in lights ;-)
as far as button names, if you can show a control panel for the game that provides those button labels then I think the labels are warranted. otherwise if they are unlabelled on the real cab they will also be unlabelled on MAME.

**Comment by balr0g** [comment]
Well, I'm of the opinion that more information is better, but noting in every instance whether or not they are labeled in the cab would likely bloat the source code...

**Comment by RJRetro** [comment]
@mr-t-guru yeah, I feel a bit embarrassed about putting my name in now lol I apologize to all for my arrogant assumption.  A quick google search shows labeled buttons for Double Dragon 1 and 2.  Double Dragon 3 did as well, shown on the Bezel.  Combatribes, some did, some didn't.  Wrestlefest is the only exception it seems.  It had very detailed instructions that are not practical to include.  I haven't included the images since this has been closed.

@balr0g I wouldn't think a notation of whether or not they are labeled would be necessary.  Just have the labels if they exist and don't otherwise.

**Comment by balr0g** [comment]
@RJRetro, your mistake is understandable, as we don't list guidelines for this (yet).

**Comment by mr-t-guru** [comment]
I checked the labels in your pull request and I have to agree they are worthwhile and valid.
Perhaps even necessary because there are so many chop-sockey beat'em-ups with many buttons and it's not so clear which button does what initially. if there are labels on the control panel to inform the player we should also do the same in the source with matching button labels. saying that it bloats the source is a pretty lame excuse. its just a bit of text on the end of the port line. it doesn't even add any lines, it just extends the line a few extra characters. there are plenty of other things that bloat the source more than information about button labels. and as balr0g stated, more information is better.

**Comment by RJRetro** [comment]
@mr-t-guru nice compromise.  I wonder tho, would it work if the order of the buttons was different per-machine?

**Comment by mr-t-guru** [comment]
in the define the order doesn't matter. the define simply adds a custom button text.
in the source you put the defines wherever they need to go.

**Comment by RJRetro** [comment]
I see, that makes sense

**Pull request closed without merging**
