### PR TITLE
Add gcc-10 to Linux CI

### PR DESCRIPTION
**Pull request by belegdol**
This way support for both old and new compilers gets tested

### CODE REVIEW

**Comment by startaq** [comment]
Looks like GCC 10 is already installed by default. See platform specifications: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#language-and-runtime

I also would prefer `gcc10` instead of `gcc-10`. This way the uploaded artifacts are named more consistently.

**Comment by belegdol** [comment]
Hi, are the changes OK now?

**Comment by startaq** [comment]
The changes are fine, we just want to observe the current system a bit more before adding more features to it.

**Comment by belegdol** [comment]
Hi, how is it looking now? It appears that linux-clang was added recently. Thanks!

**Pull request closed without merging**
