### PR TITLE
Hp9845: added capabilty to load option ROMs

### PR DESCRIPTION
**Pull request by fulivi**
Hi,
I've just pushed a set of changes to hp9845b driver to implement loading of optional ROMs. I've partially updated the hash file: to be completed.
Thanks.
-- F.Ulivi

### CODE REVIEW

**Comment by etabeta78** [comment]
Could you please update the code to use the available get_feature function
to parse the "base" feature from softlist instead of the custom parsing you
use currently?
you shall not need any check about the presence of part_ptr either

thanks in advance

   f.

**Comment by fulivi** [comment]
Better like this? I hope I got your comment right.
By the way, is there a function somewhere in the code that parses (hexa)decimal integers from XML attributes? I couldn't find one, that's why I used sscanf.
Thanks.
-- F.Ulivi

**Comment by etabeta78** [comment]
Yeah, this kind of change is what I meant. Thanks a lot.

Concerning the question about integers from XML attributes, we currently
don't have one in the core. Typically features only have been used for
strings so far, thus I think the sscanf is fine.
In the 1 or 2 cases where I needed to pass an offset from the XML, I had
found more convenient to just cover the whole CPU space in the dataarea and
load the pieces with the appropriate offset. But I chose that solution
because most of the space was anyway covered with the loaded ROMs.
At first glance, in your case your solution seems more appropriate.

   f.

**Comment by fulivi** [comment]
Do you see other problems with my PR? Should I open a new PR to have
everything merged in? (This is one of my recurring doubts...)
Thanks.
-- F.Ulivi

**Comment by etabeta78** [comment]
Sorry, I forgot to push the "confirm the merge" button on github and the
push was not merged :blush:
It should be in, now, in time for 0.173 :-)

   f.

**Pull request merged**
