### PR TITLE
Adding visual and descriptive board layout for Versus City Billboard

### PR DESCRIPTION
**Pull request by cglmrfreeman**
Similar data is provided for other Sega boards. I tried to be as descriptive as I could. If more or less information is needed please advise.

### CODE REVIEW

**Comment by cuavas** [comment]
Pure facts aren't creative work and are not copyrightable.  You can't add your name to copyright holders on the file for a parts list.

**Comment by cglmrfreeman** [comment]
@cuavas Fair enough. Removed.

**Comment by rb6502** [comment]
Sega has copyright on the ROM so you don't want to claim it there, and the diagram/parts list are just facts as Vas said.   You get credit in the whatsnew, but not copyright for that.

**Comment by cglmrfreeman** [comment]
I guess that's acceptable. But consider this, if no one had the board, how could these facts ever be documented?

**Comment by happppp** [comment]
We have a "thanks-to" tag actually. I add people there considering how much they helped me(but haven't written any of the source code). It's a bit awkward to add yourself but feel free to do so, like this: https://github.com/mamedev/mame/blob/master/src/mame/drivers/saitek_mark5.cpp#L3

**Comment by cglmrfreeman** [comment]
At this point, I realize I am editing someone else's copyrighted work. And while making no meaningful contribution to the functionality of the code itself, I am wondering if a difference which makes no difference is no different and should be committed at all. I added myself to copyright mistakenly, I will admit that. If I can get a go-ahead from @startaq I will edit in the "thanks-to" tag.

**Comment by DavidHaywood** [comment]
you could argue copyright on the presentation of the facts however, the ASCII layout.

it's possible to identify who created the various different ASCII art elements found in the code, which IMHO does make them creative works to some degree, but that is an entire can or worms.

**Comment by startaq** [comment]
Feel free to add yourself to the `thanks-to` tag, then we can merge it. And thanks for the layout!

**Pull request merged**
