### PR TITLE
sknsspr.cpp : Correct algorithm for high precision shrink sprite, Use 10.6 fixed point for position values

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
does this improve / fix the zooming in jchan?

**Comment by cuavas** [comment]
@cam900 please address the outstanding breakage from your previously merged pull request #5978 before opening more pull requests.

Also, can you give a before/after comparison for something this corrects?

**Comment by DavidHaywood** [comment]
well to answer my own question, there are still gaps in the sprite scroll in the 'jchan2' intro, and there's still a 1 pixel gap in the lifebars in jchan, so I don't think the sprites are perfect with this patch (and thus I'm not sure what it improves, as I wasn't aware of any other major issues)

**Comment by cam900** [comment]
It's fixes 'high precision shrink' mode behavior (used in some suprnova.cpp games).

**Comment by cuavas** [comment]
>It's fixes 'high precision shrink' mode behavior (used in some suprnova.cpp games); but gaps in some zoomed sprites are still there.

Can you show a comparison with screenshots where this is actually an improvement?

**Comment by cam900** [comment]
MAME 0.216

**Comment by rb6502** [comment]
The shadows are better if you blow up the screenshots.  Do we have any objections to this now?

**Comment by DavidHaywood** [comment]
I have no objections now it's clear it's for a specific mode (that yeah, is only used by sengekis to my knowledge, because when I was first emulating it I thought there was a CPU bug until I realised they were using enabling alt shrink mode rather than zooming everything to super-size)

**Pull request merged**
