### PR TITLE
igs/goldstar.cpp: Dumped and added an "El Dorado" clone named "Suns Pecker"

### PR DESCRIPTION
**Pull request by clawgrip**
New NOT_WORKING clone
------------------------------
Suns Pecker (V1.0) [Taksangs]

### CODE REVIEW

**Comment by cuavas** [comment]
Can you change the short name to “sunspckr”?  It fits in eight characters and reads a bit better than “pecke”.

**Comment by mamehaze** [comment]
are the PROMs on these going to be dumped eventually?  It's starting to become concerning how many sets are being added without them IMHO.

**Comment by clawgrip** [comment]
> are the PROMs on these going to be dumped eventually? It's starting to become concerning how many sets are being added without them IMHO.

Taksangs is trying to rely on a repair shop to deal with them. We'll see the results this weekend.

**Comment by clawgrip** [comment]
> Can you change the short name to “sunspckr”? It fits in eight characters and reads a bit better than “pecke”.

Done, thanks!!

**Pull request merged**
