### PR TITLE
Direct3D HLSL: use aviwrite to record avi movies

### PR DESCRIPTION
**Pull request by GiuseppeGorgoglione**
Use common infrastructure in aviwrite.c instead of equivalent local code.

### CODE REVIEW

**Comment by cuavas** [comment]
Could you make it only allocate the AVI recorder if it's going to start recording?

**Comment by GiuseppeGorgoglione** [comment]
Yes, why not. I just copied the old behavior. Actually the change should also include avi_copy_texture/surface and avi_final_texture/surface which were/are allocated unconditionally.

**Comment by cuavas** [comment]
I'm merging this for now before it rots.  @GiuseppeGorgoglione can you please submit another PR to lazily create AVI writing components when you have time?

**Comment by GiuseppeGorgoglione** [comment]
I think I already implemented what you asked for, but forgot to send a
message announcing that, sorry.
Now in d3dhlsl.cpp there is a movie_recorder class which groups together
all the resources needed for AVI recording (avi_write and target textures).
One instance of this class is only allocated during AVI recording,
basically cutting 2/3 of video memory required by MAME during normal
operation.

**Comment by u-man74** [comment]
I tried this feature lately, but it didnt worked. I can record a AVI, but without HLSL effects :( . Maybe i am just to dumb :) .

**Comment by cuavas** [comment]
I tested it, and it seems to work properly for D3D with HLSL but it's regressed at some point with BGFX.  Oh well, another regression to chase...

**Pull request merged**
