### PR TITLE
Corrected Magic Card game names

### PR DESCRIPTION
**Pull request by Paul-Arnold**
TeamEurope pointed out that some of the Magic Card game names were incorrect, these have now been fixed.

Now the names are correct some of the romset names are obviously wrong.

Could someone give me guidance on what the romset names should be please as I'm really not sure.
For the Magic Card games there is the following (grouped together for easier reading)

magicard	"Magic Card (v2.01)"

magicarda	"Magic Card (v1.5 17.12.93, set 1)"
magicardb	"Magic Card (v1.5 17.12.93, set 2)"

magicarde	"Magic Card Export 94 (v2.11a, set 1)"
magicardea	"Magic Card Export 94 (v2.11a, set 2)"
magicardf	"Magic Card Export 94 (V2.11a, set 3)"

magicardeb	"Magic Card Export 94 (v2.09a)"

magicardec	"Magic Card III Jackpot (V4.01 6/98)"

magicardj	"Magic Card III Jackpot (V4.01 7/98)"

unkte06	"Magic Card (v1.10 14.09.94)"

magicardw	"Magic Card (v1.2 200/93, set 1)"
unkpkr_w	"Magic Card (v1.2 200/93, set 2)"

unkpkr_w and unkte06 are obviously wrong but what to name to ?
Should romsets such as magiarde/ea/f all be related now ? which possibly makes magicardec wrong ? Not sure about magicardeb either.
Possibly magicarda/b should be better related ?

Guidance very much needed on this please

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
Should the short names for `magicardw`, `unkte06` and `unkpkr_w` be changed as well?  Right now it’s fairly confusing because `magicardb`, `magicarde`, `magicardj` ad `magicardw` look like clone suffixes on `magicard`.

It might be better if the parents were renamed (assuming these names are available):
* `magicardb` -> `magicrd1` (since it’s the version 1 sets)
* `magicarde` -> `magicrde`
* `magicardj` -> `magicrdj`

Then make all the clones use the short name of the parent with a suffix appended.

**Comment by Paul-Arnold** [comment]
@cuavas That looks a good solution. So we end up with something like this ?

magicard		"Magic Card (v2.01)"

magicrd1		"Magic Card (v1.5 17.12.93, set 1)"
magicrd1a	"Magic Card (v1.5 17.12.93, set 2)"
magicrd1b	"Magic Card (v1.10 14.09.94)"
magicrd1c	"Magic Card (v1.2 200/93, set 1)"
magicrd1d	"Magic Card (v1.2 200/93, set 2)"

magicrde		"Magic Card Export 94 (v2.11a, set 1)"
magicrdea	"Magic Card Export 94 (v2.11a, set 2)"
magicrdeb	"Magic Card Export 94 (V2.11a, set 3)"
magicrdec	"Magic Card Export 94 (v2.09a)"

magicrdj		"Magic Card III Jackpot (V4.01 6/98)"
magicrdja	"Magic Card III Jackpot (V4.01 7/98)"

**Comment by cuavas** [comment]
Yes, that looks good to me.

**Comment by DavidHaywood** [comment]
based on the date strings
magicrd1b "Magic Card (v1.10 14.09.94)"
is newer than 
magicrd1 "Magic Card (v1.5 17.12.93, set 1)"
magicrd1a "Magic Card (v1.5 17.12.93, set 2)"
and
magicrd1c "Magic Card (v1.2 200/93, set 1)"
magicrd1d "Magic Card (v1.2 200/93, set 2)"

so it's a bit like the MAME numbering system, where 1.10 is higher than 1.5

with that in mind I'd go

magicrd1   "Magic Card (v1.10 14.09.94)"

magicrd1a "Magic Card (v1.5 17.12.93, set 1)"
magicrd1b "Magic Card (v1.5 17.12.93, set 2)"

magicrd1c "Magic Card (v1.2 200/93, set 1)"
magicrd1d "Magic Card (v1.2 200/93, set 2)"

**Comment by Paul-Arnold** [comment]
Just pushed the changes and only now noticed the comment by @DavidHaywood  :(

OK, will change.

**Comment by Paul-Arnold** [comment]
Changed the romset names to match Davids suggestion.

@Tafoid What files do you need from me for this PR ?
There are 11 new romset zips. Due to the name changes and parent/clone changes it's not just a case of renaming existing zips.

**Comment by Tafoid** [comment]
Anything NEW and not matching any hashes in MAME before your commit should be sent.  Label/setname/parent/clone changes are not needed.

**Pull request merged**
