### PR TITLE
Fixed Arcade build

### PR DESCRIPTION
**Pull request by MASHinfo**
Added missing krokha.cpp driver to Arcade build filter

### CODE REVIEW

**Comment by MASHinfo** [comment]
Are you sure that Krokha is not a arcade game. Only 200 of these were ever made and were given to the worker of the Technocommunications plant. That sounds not like a home video game console.
And thought you only moved the driver to the USSR Directory because it is Russian...

**Comment by happppp** [comment]
Ok here's a photo: https://raw.githubusercontent.com/alemorf/retro_computers/master/Kroha/photo/0.jpg

**Comment by MASHinfo** [comment]
Maybe shattered knows a better answer! He moves the driver to arcade:
https://github.com/mamedev/mame/commit/f6053b1e7d0b372ac24cfecdd07af4d973473ec4

**Comment by happppp** [comment]
Sure, I'm curious too why @shattered did that. When googling around, nothing says that it's an arcade game.
Maybe he thought non-cartridge tv games are "GAME", and therefore "arcade" target?

The only thing I guess someone could misinterpret is the clock display. In theory that could be a coin-operated timer like with Sega Mega-Tech. But here, I'm pretty sure it's just a clock.

**Comment by cuavas** [comment]
This thing wasn’t designed for public use as far as I can tell.  It’s just a TV game of sorts.

**Pull request closed without merging**
