### PR TITLE
snes.xml: Region and parent/clone updates

### PR DESCRIPTION
**Pull request by FoxhackDN**

### CODE REVIEW

**Comment by FoxhackDN** [comment]
Both Chavez games were promoted in the Mexican Club Nintendo magazine and articles confirmed that they were based on existing games (Riddick Bowe and Boxing Legends of the Ring.) The games were meant to be exclusive to Mexico, but copies were also sold in the US, so I left the country alone.

Super Copa is a strange case, the game was also released in Mexico and is considered one of the rarest games here. The verified No-Intro dump was made with a Mexican cart (serial SNS-75-USA), so I added Mexico as a country.

**Comment by cuavas** [comment]
> Both Chavez games were promoted in the Mexican Club Nintendo magazine and articles confirmed that they were based on existing games (Riddick Bowe and Boxing Legends of the Ring.)

Are they just based on the code, or are they effectively a version of the same game?  If they’re more like original games utilising misappropriated code, they shouldn’t be clones.  They should only be clones if they’re effectively new variants of the games they’re based on.

**Comment by FoxhackDN** [comment]
> Are they just based on the code, or are they effectively a version of the same game? If they’re more like original games utilising misappropriated code, they shouldn’t be clones. They should only be clones if they’re effectively new variants of the games they’re based on.

They're regional versions of the games by the same publisher and developers. Chavez has him instead of Riddick Bowe (there's leftover bio text from the original game), while Chavez II took out all the licensed boxers and replaced them with Chavez. The gameplay is mostly the same, the only differences are the player characters, language, sponsors, and sound clips (Spanish voice clips for the ref), plus special secret characters based on the people who helped localize the games.

**Comment by cuavas** [comment]
You’ve got multiple things mixed up in this PR now.  Please sort it out.

**Pull request closed without merging**
