### PR TITLE
new NOT WORKING Software List entries (CocoPad)

### PR DESCRIPTION
**Pull request by mamehaze**
new NOT WORKING Software List entries
--------------------------

leapfrog_leappad_cart.xml  [David Haywood, Team Europe]

ecchello1: ECC Junior no hajimete eikaiwa! 1 Eigo de tanoshiku Say Hello! (Japan)
funtogeth: Minna de tanoshiku! CoCoPad (Otameshi soft) (Japan)
bennyeng2: Benny and Friends English Book Vol. 2 -Majo to taiketsu! Daibouken- (Japan)
thomasj: Kikansha Thomas to nakamatachi - Kikansha Thomas Yakunitatsu kikansha (Japan)
multy2j: Shinkenzemi Challenge 2 nensei Korasho to issho ni kuku o oboeyou! (Japan)
anpapinj: Anpanman no CoCoPad de aiueo kyoushitsu Pinocchio (Japan)
idainaru: Idainaru Sakkyokukatachi (Japan)
anpanmnj: Yuuki Rinrin Anpunch! (Japan)
helkitj: Hello Kitty no gakkou no ichinichi (Japan)
disprinj: Disney Princess (Japan)
poohj: Kuma no Pooh-san Hachimitsu no tsubo ga ippai Pooh-san to kazu・katachi (Japan)
disbf1: Disney's World of English 1: Birthday Fun (Japan)
dispic2: Disney's World of English 2: The Picnic (Japan)
discirc3: Disney's World of English 3: The Circus (Japan)
diszoo4: Disney's World of English 4: The Zoo (Japan)
k3mar07: CoCoPad Rom Cassette Kono men o ue ni shiteirete ne! (3 March 2007 - 5 May 2007) (Japan)
k7jul07: CoCoPad Rom Cassette Kono men o ue ni shiteirete ne! (7 July 2007, 9 September 2007) (Japan)
k11nov07: CoCoPad Rom Cassette Kono men o ue ni shiteirete ne! (11 November 2007, 1 January 2008) (Japan)
abcj: Kodomo Challenge English CoCoPad Rom Cassette Kono men o ue ni shiteirete ne! (2008/3 March - Shimajirou to Libby no ABC Adventure, 2008/5 May - Shimajirou to Libby no Touch and step game de asobou) (Japan)
smartguid4 - FUN-damentals Series - Smart Guide to 4rd Grade (UK)
goochoco- Okaasan to Issho: Goo Choco Lantan: Spoo no Fushigi na Oto no Daibouken! (Japan)
poohhach- Kuma no Pooh-san: Pooh-san to Hachimitsu (Japan)

### CODE REVIEW

**Comment by mamehaze** [comment]
These all need better shortnames, descriptions, and alt titles at least (hence draft)

ecchello1 : ECC Junior Say Hello 1 (Japan)
Cart+PCB

funtoget : Have Fun Together (Japan)
Cart+PCB

bennyeng2 : Benny and Friends English Book Volume 2 (Japan)
Cart + PCB

thomasj : Thomas and Friends (Japan)
Cart + PCB

multy2j : Multiplication Year 2 (Japan)
Cart+PCB

anpapinj : Anpanman's Pinocchio (Japan)
Cart+PCB

mozartj : Mozart (Japan)
Cart+PCB

anpanmnj : Anpanman (Japan)
Cart+PCB

helkitj : Hello Kitty (Japan)
Cart+PCB

disprinj : Disney Princess (Japan)
Cart+PCB

poohj : Winnie the Pooh (Japan)
Cart + PCB

disbf1 : Disney's World of English - Birthday Fun 1 (Japan)
Cart + PCB

dispic2 : Disney's World of English - The Picnic 2 (Japan)
Cart + PCB

discirc3 : Disney's World of English - The Circus 3 (Japan)
Cart + PCB

diszoo4 : Disney's World of English - The Zoo 4 (Japan)
Cart + PCB

eatnoodj : Please Keep Eating the Noodles - 3 March 2007, 5 May 2007 (Japan)
Cart + PCB

noodtopj : Keep the Noodles on Top - 7 July 2007, 9 September 2007 (Japan)
Cart + PCB

eatnod2j : Please Keep Eating the Noodles - 11 November 2007, 1 January 2008 (Japan)
Cart + PCB

abcj : ABC - 3 March 2008, 5 May 2008 (Japan)
Cart + PCB

**Comment by modusc896d352** [comment]
i can make out basically more than half of what these carts are saying
but when i want to enlarge these images i get broken links instead

**Comment by ajrhacker** [comment]
Some transliterations:

9P4-0085A ECCジュニアのはじめて英会話! 英語でたのしく Say Hello!
ECC Junior no Hajimete Eikaiwa! Eigo de Tanoshiku Say Hello!

9P4-0092B みんなでたのしく!ココパッド
Minna de Tanoshiku! CocoPad

9P4-0122  Benny and Friends English Book Vol.2 -魔女と対決!大冒険-
Benny and Friends English Book Vol.2 - Majou to Taiketsu! Daibouken

9P4-0181  きかんしゃトーマスやくにたつきかんしゃ
Kikansha Thomas - Yakunitatsu Kikansha

9P4-0104A コラショといっしょに九九をおぼえよう!
Korasho to Issho ni Kuku o Oboeyou!

9P4-0105A アンパンマンのあいうえお教室
Anpanman no Aiueo Kyoushitsu

9P4-0088A 偉大なる作曲家たち
Idainaru Sakkyokukatachi

9P4-0114A ゆうきりんりんアンパンマン
Yuukirinrin Anpanman

9P0-0091A ハローキティのがっこういちにち
Hello Kitty no Gakkou Ichinichi

**Comment by modusc896d352** [comment]
pinging @DopefishJustin to give us accurate translations while acting like he's doing some fucking mic-drop

**Comment by 987123879113** [comment]
Here's what I got. Includes the ones not done in earlier comments + proper name for "anpanmnj".

ecchello1 - ECCジュニアのはじめて英会話！１　英語でたのしくSay Hello!
ECC Junior no hajimete eikaiwa! 1 Eigo de tanoshiku Say Hello!

funtoget - みんなでたのしく！ココパッド　おためしソフト
Minna de tanoshiku! CoCoPad (Otameshi soft)

bennyeng2 - Benny and Friends English Book Vol. 2 -魔女と対決！大冒険-
Benny and Friends English Book Vol. 2 -Majo to taiketsu! Daibouken-

thomasj - きかんしゃトーマスとなかまたち - きかんしゃトーマス　やくにたつきかんしゃ
Kikansha Thomas to nakamatachi - Kikansha Thomas Yakunitatsu kikansha

multy2j - 進研ゼミ・チャレンジ2年生 コラショといっしょに九九をおぼえよう！
Shinkenzemi Challenge 2 nensei Korasho to isshoni kuku o oboeyou!

anpapinj - アンパンマンのココパッドであいうえお教室 Pinocchio
Anpanman no CoCoPad de aiueo kyoushitsu Pinocchio

mozartj - 偉大なる作曲家たち
Idainaru sakkyokutachi

anpanmnj - ゆうきリンリンアンパンチ！
Yuuki Rinrin Anpunch!

helkitj - ハローキティのがっこうのいちにち
Hello Kitty no gakkou no ichinichi

poohj - くまのプーさん　はちみつのつぼがいっぱい　プーさんとかず・かたち
Kuma no Pooh-san  Hachimitsu no tsubo ga ippai  Pooh-san to kazu・katachi

eatnoodj, noodtopj, eatnod2j - ココパッドロムカッセット　このめんをうえにしていれてね！
CoCoPad Rom Cassette  Kono men o ue ni shiteirete ne!
(+ the respective year + months)

abcj - こどもちゃれんじ English ココパッドロムカッセット　このめんをうえにしていれてね！
2008/3 March - しまじろうとリビーのABCアドベンチャー
2008/5 May - しまじろうとリビーのタッチアンドステップゲームであそぼう

Kodomo Challenge English CoCoPad Rom Cassette  Kono men o ue ni shiteirete ne!
2008/3 March - Shimajirou to Libby no ABC Adventure
2008/5 May - Shimajirou to Libby no Touch and step game de asobou

**Comment by mamehaze** [comment]
TeamEurope dumped 2 more sets, so I'll need translations on these too
Cart+PCB
Cart+PCB

**Comment by DopefishJustin** [comment]
Kuma no Pooh-san: Pooh-san to Hachimitsu
Okaasan to Issho: Goo Choco Lantan: Spoo no Fushigi na Oto no Daibouken

re: the above names, 作曲家たち is Sakkyoku**ka**tachi, not Sakkyokutachi

**Comment by cuavas** [comment]
Is it supposed to be “FUN-damentals Series - Smart Guide to 3rd Grade (UK)” or “FUN-damentals Series - Smart Guide to 4th Grade (UK)”?  I don’t want to believe an educational cartridge has “4rd” on the label.

**Comment by mamehaze** [comment]
> Is it supposed to be “FUN-damentals Series - Smart Guide to 3rd Grade (UK)” or “FUN-damentals Series - Smart Guide to 4th Grade (UK)”? I don’t want to believe an educational cartridge has “4rd” on the label.

It's just a typo in this case, there's already a 3rd, so obviously 4th.

**Pull request merged**
