### PR TITLE
ews286: lower case rom names

### PR DESCRIPTION
**Pull request by JoakimLarsson**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
Do you have the pictures to show that this change is correct?

**Comment by JoakimLarsson** [comment]
How do you mean, pictures of the ROM lables? This is what I got from Mattis: https://drive.google.com/open?id=19KBbGBIJsW8fEF42rhEYFQssmTfbd2va

**Comment by etabeta78** [comment]
What really matters in rom labels is properly representing actual
characters present on chips/labels, not capitalization. Thus the change
is100% IMHO.
It's way more damaging the habit to replace blank space with _
(underscore)...

my 2c
     f.

**Comment by DavidHaywood** [comment]
well some PCB owners really dislike the labels being wrong in terms of capitalization which is why we've allowed it in plenty of drivers, because using the correct labels is important, we never know if a manufacturer used lower case and upper case letters to mean different things.  MAME preference is NEVER more important than the original material., 

If the labels on the roms are uppercase this is an invalid change

**Comment by etabeta78** [comment]
The idea of documenting label properly is to ensure that we don't miss
undumped PCBs due to incorrect labelling and that repairers don't use the
wrong ROMs to restore old boards... and I'm ready to be we will never see
mismatching labels where an uppercase letter has been changed to a
lowercase...
Cargo-cultist of capitalized labels should not forget about what is
valuable info and what is feticism... thus, I think this is an harmless
aesthetic change that does not devalue by any means the documentation
efforts of the driver (contrary to often happening replacement of blank
spaces with series of _ characters in arcade drivers).

but again these are just my 2c
    f.

**Comment by cuavas** [comment]
>well some PCB owners really dislike the labels being wrong in terms of capitalization which is why we've allowed it in plenty of drivers, because using the correct labels is important, we never know if a manufacturer used lower case and upper case letters to mean different things. MAME preference is NEVER more important than the original material.,

Oh not this crap again.  The ROM label string can't adequately represent the arrangement of the text on the ROM labels, label/text colours, and characters outside a restricted subset of printable ASCII.  There's no substitute for keeping photos of the labels.  If you think otherwise you're only fooling yourself.

As the ROM label strings are also used for for filenames when searching for ROMs, we need to make concessions for convenience.  When you may be using a case-sensitive filesystem, having to deal with potential mixed case is a pain.

**Pull request merged**
