### PR TITLE
Plug and Play additions (ekara + more)

### PR DESCRIPTION
**Pull request by mamehaze**
new NOT WORKING systems
------------
Teleshibai (Japan) [David Haywood, Team Europe]
Teleshibai - Purple Version (Japan) [David Haywood, Team Europe]
TV Mahjong Game (VTxx hardware) [David Haywood, Team Europe]

new software list entries
--------------
ekara_cart.xml:
Dream Cartridge: Kids' Song Volume 4 (Japan) (DC0007-KID)  [David Haywood, Team Europe]
Kids' Song Mini Volume 6 (Japan) (MC0017-KSM)  [David Haywood, Team Europe]
e-kara Web cartridge 8M (used, with 8 songs) (Japan)  [David Haywood, Team Europe]

### CODE REVIEW

**Comment by mamehaze** [comment]
IMG_20240828_120807941
What's the correct name for these Konami Storybook things (both Romanized and as Japanese, so that the latter can be added as a comment)

**Comment by einstein95** [comment]
> What's the correct name for these Konami Storybook things (both Romanized and as Japanese, so that the latter can be added as a comment)

テレしばい
Teleshibai

https://web.archive.org/web/20080913230842/http://www.konami.jp/tv-shibai/tereshibai/index.html

It's a play on television + kamishibai

**Comment by mamehaze** [comment]
Is there a better name for this TV Mahjong, it's VT (NES-type) hardware

**Comment by mamehaze** [comment]
these are the e-kara carts (don't have any boxes for them)
Cart+PCB
Cart+PCB
Cart+PCB

**Comment by mamehaze** [comment]
dc0007 when run with Popira (as the Popira units show a cart title)

**Comment by mamehaze** [comment]
The 8 songs on the e-kara user cart that will need adding to the comments

**Comment by ajrhacker** [comment]
"TV麻雀ゲーム" is literally TV Mahjong Game. It's really generic even in Japanese.

**Comment by einstein95** [comment]
> these are the e-kara carts (don't have any boxes for them)

キッズソング
Kids Songs

キッズソングミニ - mini vol.6
Kids Song Mini - mini vol.6


> dc0007 when run with Popira (as the Popira units show a cart title)

勇気りんりん - ドリーミング(それいけ!アンパンマン)
Yuuki Rinrin - Dreaming (Soreike! Anpanman)

おさかな天国 - 柴天裕美
Osakana Tengoku - Shibaya Hiromi



> The 8 songs on the e-kara user cart that will need adding to the comments

世界に一つだけの花 - SMAP
さくらんぼ - 大塚愛
あ~よかった - 花*花
ハッスル - かいけつゾロリ (山寺宏一)
アララの呪文 - ちびまる子ちゃん with 爆チュー問題
ミニハムずの愛の唄 - ミニハムず
ミニモニ。ジャンケンぴょん! - ミニモニ。
大きな古時計 - ? (hard to make out)

Sekai ni Hitotsu Dake no Hana - SMAP
Sakuranbo - Otsuka Ai
Ah Yokatta - Hana*Hana
Hustle - Kaiketsu Zorori (Yamadera Koichi)
Arara no Jumon - Chibi Maruko-chan with Bakuchu Monda
Minihams no Ai no Uta - Minihams
Mini-Moni. Jankenpyon! - Minimoni.
Ookina Furudokei - ?

**Comment by HappyASR** [comment]
> 大きな古時計 - ? (hard to make out)

童謠?

**Comment by mamehaze** [comment]
this is the final user cart song

also what's the middle option here? is this related to the download service? if you select it there's only one story (despite offering left/right options) and it's the same on both units.

**Comment by einstein95** [comment]
> > 大きな古時計 - ? (hard to make out)
> 
> 童謠?

Looks like it, so that makes it
大きな古時計 - 童謠
Ookina Furudokei - Douwa

> also what's the middle option here? is this related to the download service? if you select it there's only one story (despite offering left/right options) and it's the same on both units.

The archived website describes it as (via Google Translate):
> You can also have the story read aloud automatically. The story progresses with pre-recorded audio. (*Only applies to stories with audio included.)

The three options are basically
1. Read into the microphone (adding sound effects and voice changer) for a baby's entertainment
2. Have the device read to you
3. Play with the voice changer

**Comment by einstein95** [comment]
Additional info from https://web.archive.org/web/20150507065750/http://www.konami.jp/tv-shibai/plus/plus03.html:
Service ended July 31, 2010. After that, you could send it into Konami to get it rewritten, unsure when this ended.
Stories you could get:
* 世界のお話 (ナレーション入り) [Sekai no Ohanashi (Narration-iri)]
  * ブレーメンのおんがくたい (グリム童話)
    * Bremen no Ongakutai (Grimm douwa)
  * みにくいあひるのこ (アンデルセン)
    * Minikui Ahiru no Ko (Andersen)
  * てぶくろ (ウクライナ民話)
    * Tebukuro (Ukraine minwa)
  * はちかつぎひめ (日本昔話)
    * Hachi Katsugi-hime (Nippon mukashi banashi)
* 遊んで学ぼう・お歌で遊ぼう [Asonde Manabu - Outa de Asobou]
  * あそんでまなぼう (オリジナル)
    * Asonde Manabou (Original)
  * あそんでまなぼう2 (オリジナル)
    * Asonde Manabou 2 (Original)
    * (for some reason 2 is listed twice on the page)
  * おうたであそぼう3 (オリジナル)
    * Asonde Manabou 3 (Original)
  * おうたであそぼう4 (オリジナル)
    * Asonde Manabou 4 (Original)
* Included with Orange model (for customers with Purple model)
  * しあわせのおうじ (イギリス民話)
    * Shiawase no Ouji (English minwa)
  * ほしのぎんか (グリム童話)
    * Hoshi no Ginka (Grimm douwa)
  * おやゆびひめ (アンデルセン)
    * Oyayubi-hime (Anderson)
  * こびととくつや (グリム童話)
    * Kobi to Toku Tsuya (Grimm douwa)
  * みっつのねがい (日本昔話)
    * Mittsu no Negai (Nippon mukashi banashi)
  * うらしまたろう (日本昔話)
    * Urashima Tarou (Nippon mukashi banashi)
  * アフロンとがまじいの ちきゅうにやさしく (オリジナル)
    * Afuron to Gamajii no Chikyuu ni Yasashiku (Original)
  * かさこじぞう (日本昔話)
    * Kasakojizo (Nippon mukashi banashi)
  * きんのがちょう (グリム童話)
    * Kin no Gachou (Grimm douwa)
  * あそんでまなぼう (オリジナル)
    * Asonde Manabou (Original)
* Included with Purple model (for customers with Orange model)
  * ももたろう (日本昔話)
    * Momotarou (Nippon mukashi banashi)
  * あかずきん (グリム童話)
    * Aka Zukin (Grimm douwa)
  * きたかぜのくれたテーブルかけ (ノルウェー民話)
    * Kita Kaze no Kureta Table Kake (Norway minwa)
  * いっすんぼうし (日本昔話)
    * Issun-boushi (Nippon mukashi banashi)
  * おおきなかぶ (ロシア民話)
    * Oukina Kabu (Russia minwa)
  * ありときりぎりす (イソップ童話)
    * ari to kirigirisu (Aesop douwa)
  * マッチうりのしょうじょ (アンデルセン)
    * Match Uri no Shoujo (Anderson)
  * かさこじぞう (日本昔話)
    * Kasa Jizou (Nippon mukashi banashi)
  * きんのがちょう (グリム童話)
    * Kin no Gachou (Grimm douwa)
  * あそんでまなぼう2 (オリジナル)
    * Asonde Manabou 2 (Original)

**Comment by mamehaze** [comment]
Stories in teleshi set

**Comment by mamehaze** [comment]
Stories in teleship set

**Comment by mamehaze** [comment]
I thought when I tested these there were other things in the narration menu though, so I'm wondering if one of the other globs is additional flash storage.

**Comment by cuavas** [comment]
> > 大きな古時計 - ? (hard to make out)
> 
> 童謠?

No, 童謡

**Comment by einstein95** [comment]
> Stories in teleshi set

うらしまたろう
はちかつぎひめ
きんのがちょう
こびととくつや
ちきゅうにやさしく
しあわせのおうじ
あそんでまなぼう
かさこじぞう
きんのがちょう
みっつのねがい
かさこじぞう

> Stories in teleship set

ももたろう
あかずきん
きたかぜのくれたテーブルかけ
いっすんぼうし
おおきなかぶ
ありときりぎりす
マッチうりのしょうじょ
かさこじぞう
きんのがちょう
あそんでまなぼう2
かさこじぞう

Judging by the listings on that page, it looks like teleshi had some stories overwritten, while teleship is original (with かさこじぞう listed twice by accident?)

**Comment by mamehaze** [comment]
so the titles don't match up with the lists?
かさこじぞう is there twice because the 2nd time it's in the 'narrate' mode (it's the only song in the narrate mode, and the same on both)

I didn't think you *could* erase things already on them though? I thought it was a case of the downloads adding to them.

**Pull request merged**
