### PR TITLE
Spectrum list cleanup / reorgnaize [see previous credits]

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by ICEknigh7** [comment]
I've just uploaded here the cleaned up entries for all the MicroHobby covertapes: http://www.filedropper.com/microhobby

**Comment by DavidHaywood** [comment]
what does 'cleaned up' mean in this context?

one frustrating thing with a few of the magazine images is that they're stripped of non-spectrum stuff and therefore not proper representations of the tapes.  (I guess because TZX can't represent all the formats)

**Comment by ICEknigh7** [comment]
Cleaned up as in, ready to merge with all the correct titles, release date, publisher, etc. I didn't do it myself since this pull request is open (can't edit it) and I just don't want to mess things up.

**Comment by DavidHaywood** [comment]
Ok, in this case I'll paste those over the entries I have then as it's a simple block I can replace in the file, but in general I would recommend not doing too much until after I've done a few more passes.

I think I'll do a shortname / clone setup improvement pass, then maybe uncomment the commented out stuff (as the startup delay is annoying, even if it's clearly an xml parser bug / issue) at that point it'll be easier for you to make further changes IMHO.

**Comment by ICEknigh7** [comment]
"in general I would recommend not doing too much until after I've done a few more passes"
Sure, I just had a look at what you were doing and noticed that I could help with that very specific set of cassettes since I'm quite familiar with those.

**Comment by DavidHaywood** [comment]
@ICEknigh7 you changed the hashes on one of the microhobby files

microhobby issue 182 - tape 01 (side b) was changed from 
6f5f5eb4 to 5b1ab83c

I've restored it, as I don't have the dump you changed it to, and you claim to have not changed any of the hashes.

**Comment by ICEknigh7** [comment]
@DavidHaywood I've just sent the dump I have to the usual address.
I don't know what may be the origin of the file you had, as all the MicroHobby dumps I got came from the same place. Is the file date different to the dump of side A?

**Comment by ICEknigh7** [comment]
I've just found the tzx that's currently in the softlist and it seems to be an earlier version of the one I had added, lacking a "(game)" tag in the first text block.

**Pull request merged**
