### PR TITLE
ti85.cpp: fix typos in BIOS file names

### PR DESCRIPTION
**Pull request by jlachniet**

### CODE REVIEW

**Comment by Tafoid** [comment]
- ti84p, ti84pv3, ti84pseb, ti84psev3 are all not 100% matching hashes for data sent in/known.  These need updating to what is known for these machines.
- ti84pesb bios set also appears to be the wrong size (need to be 2048KB)

There may be more issues but I cannot tell at this time until those above are corrected.

**Comment by jlachniet** [comment]
Specifically which BIOS' appear to be missing? I can't find any errors in my hashes.

**Comment by Tafoid** [comment]
The biggest issue seems to be that you are using the same filenames for parent and clone (bootleg) bios sets.  In doing this you are basically telling MAME that if it cannot find the desired clone hash, it will use the parent's same named BIOS instead without complaint.  Based on what was sent for data/filenames to Dev concerning these added TI Calcs, this is a list of what is missing (lack of matching hashes).  Either the files sent are incorrect or your hashes in source are incorrect.

Example:   You have ti84p bios sets with the same filenames as ti84pb bios sets and even though the hashes are different and you have a ti84pb.zip in your roms folder, the -verifyroms command will not acknowledge that your roms are "bad" because of the parent - so the output will show:

**mame64 -verifyroms ti84pb
romset "ti84pb" not found!**

So, please take the time and verify the sets listed below that the size, hashes and filenames are unique to identify them as separate bios romsets.

Thank you.

-----

TI-84 Plus (Bootleg) [folder: ti84pb - parent: ti84p - size: 8mb]
missing set: TI-84 Plus (Bootleg)
missing rom: ti84pv221.bin [size: 1048576] [CRC32: b122f965] [SHA1: 8c81ea6046863a91ab50222f2dc4c4fa73b08e8f]
missing rom: ti84pv222.bin [size: 1048576] [CRC32: 7e58df26] [SHA1: 71a859ee1b8c23b8c09c718d1d96623e14a2728f]
missing rom: ti84pv230.bin [size: 1048576] [CRC32: 442230ce] [SHA1: d0a34121dcc437f2df60a646b879442800912fd9]
missing rom: ti84pv240.bin [size: 1048576] [CRC32: 066ec796] [SHA1: 37ffe852928124fab1bd61d66c44a4bb356b60d6]
missing rom: ti84pv241.bin [size: 1048576] [CRC32: 76c44541] [SHA1: 3be9456268b9c0b2e5cf3a65af2b148ef74ce89b]
missing rom: ti84pv243.bin [size: 1048576] [CRC32: de874b96] [SHA1: 2779db4987e22b3e3d946cecf5eb3942a0478eaa]
missing rom: ti84pv253mp.bin [size: 1048576] [CRC32: 53f1404a] [SHA1: 3535a0bcbed9d7949c2791695a26e4b2db1af8ba]
missing rom: ti84pv255mp.bin [size: 1048576] [CRC32: a5afffae] [SHA1: 5bf30a7ebbebfa90f221cdddc931ae0b96c419db]

TI-84 Plus (Boot Code 1.03) [folder: ti84pv3 - parent: ti84p - size: 1mb]
missing set: TI-84 Plus (Boot Code 1.03)
missing rom: ti84pv255mp.bin [size: 1048576] [CRC32: 086982c6] [SHA1: d500540feca974f6e8fa269981cfb25dc951c338]

TI-84 Plus Silver Edition (Bootleg) [folder: ti84pseb - parent: ti84pse - size: 16mb]
missing rom: ti84psev221.bin [size: 2097152] [CRC32: 1d448cac] [SHA1: 132ff36d4ebed04452fc0b54341b29db882d1292]
missing rom: ti84psev222.bin [size: 2097152] [CRC32: e1949af7] [SHA1: 167a8bc911fadd62e0b9eb2c4f3c96009795fb2f]
missing rom: ti84psev230.bin [size: 2097152] [CRC32: 275c42e0] [SHA1: 7d800eb350d6c7dd9fd6aaab44de6c2de70f6f49]
missing rom: ti84psev240.bin [size: 2097152] [CRC32: 4bcb29ca] [SHA1: 4cfcb232a310d42d252d5481ad4417ea1f55288e]
missing rom: ti84psev241.bin [size: 2097152] [CRC32: 290577b5] [SHA1: c70b5c58ba723e60787f8a5b0caef94ee9cec087]
missing rom: ti84psev243.bin [size: 2097152] [CRC32: 4e8ff7a5] [SHA1: a725f58532706deff2f60d700030da0e99a2c21d]

TI-84 Plus Silver Edition (Boot Code 1.03) [folder: ti84psev3 - parent: ti84pse - size: 2mb]
missing set: TI-84 Plus Silver Edition (Boot Code 1.03)
missing rom: ti84psev255mp.bin [size: 2097152] [CRC32: 0c6b9fb8] [SHA1: eabdc9b46a1cb7fef60b0fabf36ab7d484cdb3bf]

**Comment by jlachniet** [comment]
@Tafoid could you double check that https://github.com/mamedev/mame/pull/3285 fixes this?

**Comment by Tafoid** [comment]
The name conflicts seem to be gone, but the missing hashes issue remains.

**Comment by jlachniet** [comment]
I'll correct the issue later today.
  
  
  

  
  
  
  
  
>

**Comment by jlachniet** [comment]
Hopefully fixed by https://github.com/mamedev/mame/pull/3286

**Pull request merged**
