### PR TITLE
Fix M6502 reset procedure. Fixes MT6486 at the very least. [Melissa G…

### PR DESCRIPTION
**Pull request by MoochMcGee**
…oad]

### CODE REVIEW

**Comment by MoochMcGee** [comment]
MT5976 and MT6041 also seem to be fixed! lovely!

**Comment by happppp** [comment]
I think RESET doesn't directly set SP, it simply decrements it. Let's say for example in the middle of playing a game SP is 0x80 and you strobe the RESET pin, isn't SP 0x7d afterwards? In other words, use dec_SP 3 times. Might as well use read(SP) too, it's not an arg.

Does it work the same on 6502 derivatives? A lot of the om*.lst have their own reset handler. Also, there's a TODO note at the top of m6502.cpp you forgot to remove.

**Comment by MoochMcGee** [comment]
@happppp From the resources I've read, SP is initialized to 0 so :/
Also, I have no idea if it works the same on derivatives, I haven't really looked into that. But nonetheless, I'm gonna make a follow-up PR to fix the style issues you mentioned.

**Comment by MASHinfo** [comment]
I tested mame a2600 with dkongjr and the bug MT5976 is not fixed.
I saw no snap jaws in the 2nd level.
You can see these snap jaws in ths YouTube video https://youtu.be/osqj6tTniEI at 0.42.

**Comment by MoochMcGee** [comment]
I saw them.

**Comment by MASHinfo** [comment]
I test the emulator Stella and the snap jaws appear in the 2nd level. No snap jaws in MAME
with the newest style changes :(

**Comment by MoochMcGee** [comment]
Let me see if i can reproduce that issue on my end.

**Comment by happppp** [comment]
Maybe you tested the 1st level(snapjaws do appear), the bug is on the 2nd level.
a2600 dkongjr, one of the first things it does is set SP to $FF. Initial power-on/reset SP value does not affect dkongjr.

**Comment by MoochMcGee** [comment]
weird because i saw them on the 2nd level with the first version of my fix :/

**Comment by happppp** [comment]
No difference for me, either before this patch, or with both versions of it.

**Comment by MoochMcGee** [comment]
Strange, it works with the first version, but not with the second one for me o.o

**Pull request merged**
