### PR TITLE
gba_ereader.xml - update part 3

### PR DESCRIPTION
**Pull request by Shideravan**
Finally finishing Animal Crossing e-cards and also adding complete Domo-Kun Card-e collection

### CODE REVIEW

**Comment by oddi5593** [comment]
Hello, gba_ereader.xml - update part 3 it's not validated have few errors:
see next fragments : <software name="acr3b3s2"> line 1539
also missing "publisher"
---------------------------------
line 3300 , double ">>"
line 3369 - missing "name"

Good luck :)

**Comment by Shideravan** [comment]
Thanks Oddi, I fixed everything :)

**Comment by oddi5593** [comment]
Tnx, have new tiny bug : 2 sets with same name : 
line 3339 and 3369 : <software name="acr4tnk">
Tnx :)

**Comment by Shideravan** [comment]
Oops, fixed ;)

**Comment by oddi5593** [comment]
ok, now ready for merge :)

**Pull request merged**
