### PR TITLE
Improvements to hp64k driver

### PR DESCRIPTION
**Pull request by fulivi**
Hi,

I've committed some major changes to hp64k driver, the biggest one being the support for floppy drives. Now the driver boots the hp 64000 OS which seems to work correctly (you can edit, assemble, compile, etc.).

Thanks.
-- F.Ulivi

### CODE REVIEW

**Comment by rb6502** [comment]
Hi,

This patch is awesome, but it doesn't apply as-is to trunk.  Could you re-base it please?

Cheers,
-RB

**Comment by d235j** [comment]
Merged. This one was again due to srcclean changing whitespace.

**Comment by balr0g** [comment]
Merged. This one was again due to srcclean messing up whitespace.

**Comment by rb6502** [comment]
This was nothing to do with srcclean or whitespace: it misses OG's changes to how CPU cores work, and it appears to be using old floppy code rather than the modern system.

**Comment by rb6502** [comment]
I have, I think, resolved the issues.  Please check and make sure it's still working OK.

**Comment by fulivi** [comment]
Thanks to all of you. It seems to be ok now.

-- F.Ulivi

**Pull request merged**
