### PR TITLE
ibm5170.xml - New non-working software

### PR DESCRIPTION
**Pull request by FakeShemp**
Gilis presentask (Swe)

### CODE REVIEW

**Comment by DopefishJustin** [comment]
Is the disk copy-protected? If not, plain .img format would be preferred.

**Comment by DavidHaywood** [comment]
in the case of a damaged disk isn't there more chance of recovering data by analyzing a dump like this, than discarding it all and putting it in an img?

**Comment by FakeShemp** [comment]
Yeah, mfm sure handles the damaged disk better. The other ones have data in track 81, which I don't think IMG handles well either.

**Comment by DopefishJustin** [comment]
OK

**Pull request merged**
