### PR TITLE
Cartridge slot emulation added,Joystick inputs added.

### PR DESCRIPTION
**Pull request by jfdelnero**
Cartridge slot emulation added.
Joystick inputs added.

### CODE REVIEW

**Comment by mmicko** [comment]
Please rebase. Can not do auto merge

**Comment by jfdelnero** [comment]
What is the problem with auto merge ?

**Comment by mmicko** [comment]
I have done lot of changes on all files. So best just rebase on latest

**Comment by jfdelnero** [comment]
Rebase done.

**Pull request merged**
