### PR TITLE
gba: decouple video device from main machine state using callbacks

### PR DESCRIPTION
**Pull request by GiuseppeGorgoglione**
Thanks for your remark.   ;-)

### CODE REVIEW

**Comment by cuavas** [comment]
There are a lot of problems with the code as submitted:
* There should be no dependencies from src/devices on src/mame and this introduces another one
* The code plays fast and loose with integers, relying on undefined behaviour
* The code uses #define macros everywhere, even for simple constants where there's absolutely no excuse given that C++11 gives you a choice of enum, scoped enum and constexpr
* It puts all kinds of things in global scope that really shouldn't be

I'll merge this now, but can you at least try to clean up the sheer number of #define macros at some point?

**Comment by GiuseppeGorgoglione** [comment]
Absolutely, having a background as embedded system programmer, defines are a bad habit which is difficult to defeat but I'll try to. And after that I'll give it a run with ubsan just to be sure.

>There should be no dependencies from src/devices on src/mame and this introduces another one

Which one? With this last commit I removed the inclusion "includes/gba.h" from gba_lcd.cpp in favor of callbacks. Am I missing something?

Is there any specific driver / device I can take as a reference of proper and modern MAME code to steal ideas from?

**Comment by cuavas** [comment]
I was referring to previous PR adding the dependency.  This one fixed it.  As for good drivers...  I guess look at things that have been rewritten recently is the best generic advice.  Things get modernised slowly, and MAME still has a lot of cruft.

As an aside, I'm not really sure moving GBA LCD to src/devices is the right thing to do.  The intention is really to keep things that are common devices in src/devices, and things that are only used for a single system in src/mame.  I know this isn't always followed.

There's also some argument over what should be implemented as a device in MAME.  The general consensus is that devices should represent actual physical components or subsystems of a machine, like a sprite chip, a sound board, or a keyboard.  Some people strongly oppose separating different functions of a single SoC into different devices.

**Comment by galibert** [comment]
And some people, like me, strongly support separating them :-)  Some FM
chips are eventually going to be split among 4 or 5 devices.

  OG.

**Comment by rb6502** [comment]
I approve of this separation because it'll provide a useful basis for Nintendo DS, which contains basically 2 complete GBA video blocks.

**Comment by GiuseppeGorgoglione** [comment]
> Some people strongly oppose separating different functions of a single SoC into different devices.

Probably this does not yet apply to SoCs of systems emulated by MAME, but modern SoCs are made up mostly of standard components glued up together and reused many times across different products of different brands. The only things which change are the mapping of registers, interrupt channels, clocks and power lines. Without this kind of device modularity the Linux kernel would be many times bigger in terms of LoCs just because of the ARM SoCs alone.

> I approve of this separation because it'll provide a useful basis for Nintendo DS

This is indeed a good reason!  :-)

**Comment by mamehaze** [comment]
yeah, having individual parts as devices makes sense.

the cpu cores can pull together the various devices to form SoC implementations.

the various 68k variants often integrate standard Motorola peripherals (sometimes with a few limits, like only 1 DMA channel not 2) but making it so that the code can be reused, and implementing the variants in the chip implementations as derived dervices makes a lot more sense than duplicating all the code.

in the end the actual CPU core in a SoC is just another part it it, and we wouldn't dream of duplicating entire CPU cores.

**Pull request merged**
