### PR TITLE
fix mitchell.cpp nvram saving

### PR DESCRIPTION
**Pull request by DavidHaywood**
this must have been broken for a while, it was assuming that MAME used the CPU region as RAM for 8-bit CPUs and that hasn't been an valid for a long time. (15+ years?)  As a result data wasn't being saved / restored properly at all.

Corrado Tomaselli noticed this when playing with his Super Pang PCB, after replacing a hacked set with a proper original + Kabuki battery he noticed the game no longer showed '8Mhz Original Board' on bootup.  This is because the battery also backs up at least part of main RAM, and it only displays that string the first time it initializes main ram.

The previous MAME code only tried to save 0x80 bytes of the RAM, with a different location for some games.  I've left that behavior commented in case it turns out the original does only save that area, but it seems more likely it just backs up the whole of the RAM.

### CODE REVIEW

**Comment by galibert** [comment]
Please don't leave the commented lines.  If you (reasonably) think the
whole of the ram is saved (not sure how it could be different actually),
then don't leave the alternative version in.  That kind of crap stays
forever because nobody dares to remove it.

  OG.

**Comment by happppp** [comment]
It's likely that the pcb has more than 1 ram chip for main ram, and if so,
it's possible that only 1 ram chip is battery backed.

**Comment by galibert** [comment]
Not gonna end up at 0x80 though :-)

  OG.

**Comment by DavidHaywood** [comment]
I feel it's more likely the existing save was written based on the structures in RAM.  I guess if we're saving the whole thing without that option of going back it could just use the finder logic to get the region now too.

**Pull request merged**
