### PR TITLE
Introduce romtype.h analog to xtal.h to describe various (E)PROM types

### PR DESCRIPTION
**Pull request by startaq**
Doing this as a pull request to get some comments first.

One problem is that the ROM size in the `ROM_LOAD` macro gets a bit obfuscated. On the other hand, this already found some inconsistencies between driver readme and the actual ROM loading.

### CODE REVIEW

**Comment by mamehaze** [comment]
it needs doing at some point, as an additional verification step on the ROMs where a rom type is specified.

I'd also include the pinouts in each case, even with references around people often ask for pinouts, and mistakes are still made.

I'm not sure I'd replace the size the way you've done it, because as you say, some rom loading isn't 'plain' but as an additional parameter which acts as verification on the size it could work.

**Comment by happppp** [comment]
This won't work with ROM_CONTINUE

**Comment by startaq** [comment]
That's true, but `ROM_CONTINUE` is usually used to work around driver issues, or there are better modern methods to do what previously was only possible with `ROM_CONTINUE` it.

**Comment by ajrhacker** [comment]
It works with ROM_CONTINUE if the sizes can be divided. But why assume that most EPROM types are only available in CMOS?

**Comment by startaq** [comment]
I just added a few common ones, it's far from an exhaustive list (and `EPROM_2764`is NMOS).

**Comment by mamehaze** [comment]
also the only place ROM_CONTINUE is really being phased out is where it was used to workaround an old MAME limitation / optimization where CPUs with less than 16-bits of address space mapped RAM directly into the region.

there are many other places where ROM_CONTINUE is *incredibly* useful, especially loading graphic roms and getting the ordering right so that our gfxdecode functions can cleanly decode them without having to resort to ugly init functions swizzling the data around, it's much more readable and easy to understand where everything is going when it gets done in the ROM_LOAD structures.

**Comment by mamehaze** [comment]
possibly spltting the rom loading lines into 2 concepts; rom declaration and rom loading might actually help here..

so the existing macro would essentially become ROM_DECLARE_AND_LOAD

while for other cases you could declare the rom (label, position, type) using a ROM_DECLARE (which doesn't actually load anything)then specify the more complex loading routine on the next lines(s) (using ROM_LOAD, which doesn't directly declare anything and becomes more like ROM_CONTINUE anyway)

**Comment by startaq** [comment]
For graphics ROMs any swizzling needed should be done by the gfxdecode system, and not abuse the ROM loading for that.

I kinda like the idea with something like ROM_DECLARE though. So instead of a filename in the ROM_LOAD you specifiy a tag to the ROM you declared earlier. This seems very flexible, and you can cross reference ROMs into ROM_LOADs for clones etc.

**Comment by mamehaze** [comment]
I disagree, the gfxdecoding is complex enough, I get asked to do it so often for people because already people struggle to understand it, loading it with more functionality doesn't really make sense.

I don't consider ROM_CONTINUE to really be any more 'abuse' than say the odd/even/skip type things we have which also exist mainly to prepare data for easier use later.  It's a convenient feature.

**Comment by startaq** [comment]
The `ROM_SKIP` parameter has a clear equivalent in hardware that's very common: Attaching 8-bit ROMs to 16-bit systems or similar.

The gfxdecode things aren't getting easier just because you move the data swizzling to another place, in fact it would probably be easier if it would be all in in one place. But anyway, `ROM_CONTINUE` won't be removed in the near future, so we should limit the discussion to how to handle the ROM types.

**Comment by ajrhacker** [comment]
In principle, I agree with Haze that that using an additional declaration to specify ROM types would be a better way to recognize them. That way, they could be a separate data member and a list command could be used to display them.

**Comment by rb6502** [comment]
I like this in principle also, but I'm not thrilled about the proposed implementation.  This works for crystals because crystals have exactly 1 parameter of interest.  That is not true of ROMs.

**Comment by f205v** [comment]
If I may, from the point of view of documenting PCBs hardware, an additional declaration for ROMS types would be extremely useful. Also for people working with real PCBs trying to repair them. I found myself many time looking at MAME source, using an exadecimal calculator to convert ROMs size into decimal numbers and then from there trying to identify the EPROM type.
Retaining the EPROM type in the source has been asked even recently by other dumpers in the Dumping Union list.

**Comment by galibert** [comment]
Hard no from me.  First, I want to see the damn size in the loading information.  Second, I don't want yet another reason to have a emu.h recompile every five minutes like we had with xtal.h.  So, that implementation, not a chance.  The information may be useful, but you'll need to find another way.

**Pull request closed without merging**
