### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
-----------
Game & Watch: Zelda [algestam]

### CODE REVIEW

**Comment by happppp** [comment]
Exclamation mark! Thanks ;D

**Comment by algestam** [comment]
This game has been the most challenging one to dump yet due to the many segments and the way the game is played which makes it hard to get the game to lit up some of the segments. There are some segments on the LCD that I've ID:ed but haven't been able to verify when running the game in MAME (a sword on the bottom screen and the upper arm of the princess on the top screen).

The game lits up all segments if "Game", "Continue" or "Time" is held in when the game is started or reset.

**Comment by happppp** [comment]
They can also be verified by following the electronic traces you can see on the real lcd. Group them with IDs of known segments to get the x.y.z ID(for whichever of them is unsure).

**Comment by algestam** [comment]
Thanks :) Yes, that's what I've done but to make sure that everything works as it should I usually want to verify the segment ID:s by making sure that they are lit up correctly when running the game in MAME as well. It could be that these segments exists on the LCD but for some reason aren't used in the game, perhaps they couldn't fit some features in the ROM (or that I simply haven't found out how to activate these segments from the game yet).

**Pull request merged**
