### PR TITLE
New working clones 

### PR DESCRIPTION
**Pull request by clawgrip**
------------------
Kamikaze (Electrogame, Spanish bootleg of Galaxian) [Juan Romero, ClawGrip]

### CODE REVIEW

**Comment by clawgrip** [comment]
IMG_0209

Note that the game was on a genuine Midway PCB, and I was suggested that we should call it "hack" or "ROM kit" instead. Can anyone please confirm? @cuavas ?

**Comment by ajrhacker** [comment]
Isn't this hack similar to kamikazp, even though the one dumped graphics ROM is different?

**Comment by clawgrip** [comment]
> 
> 
> Isn't this hack similar to kamikazp, even though the one dumped graphics ROM is different?

No, it's a direct clone of Galaxian with some changed texts ("ptos" instead of "pts", "ELECTROGAME" on the title screen, etc.). It has some ROMs in common with "zerotime", "galaktron", "galaxrf", etc.

**Comment by cuavas** [comment]
It’s still a bootleg ROM swap.

**Comment by clawgrip** [comment]
> It’s still a bootleg ROM swap.

Then the game description is good as is, isn't it?

**Pull request merged**
