### PR TITLE
Fix asmjit compile error due to warning

### PR DESCRIPTION
**Pull request by couriersud**

### CODE REVIEW

**Comment by cuavas** [comment]
Which compiler does this happen with?  If it only happens with GCC7 I’d rather just recommend people still using it use `NOWERROR=1`.  It’s the oldest major version of GCC we still support, and it’s five years old this week, so it’s getting to the point where it can fall into “marginally supported” status.  I haven’t encountered this with GCC as far back as 8.3.1 and clang as far back as 6.0.1.

That aside, this wouldn’t be acceptable as-is because it doesn’t restrict the flag to configurations where it’s needed.

**Comment by couriersud** [comment]
Thanks the explanation. Yes, it is gcc-7. NOWERROR is not an option - I don't want to overlook warnings which can break the build. I'll try again later checking for gcc and version.

**Comment by cuavas** [comment]
> I'll try again later checking for gcc and version.

You can take a look at how zlib or 7z suppresses warnings for certain compiler versions in 3rdparty.lua.  You’ll probably need something like:

```
    configuration { "gmake or ninja" }
if (_OPTIONS["gcc"] ~= nil) and (not string.find(_OPTIONS["gcc"], "clang") and (str_to_version(_OPTIONS["gcc_version"]) < 80000) then
        buildoptions {
            "-Wno-maybe-uninitialized",
        }
end
```

I haven’t actually tested this.  Make sure the configuration filter is unset after doing it or the source files won’t be added for other configurations.

**Comment by couriersud** [comment]
Used your recommendations and updated PR.

**Pull request merged**
