### PR TITLE
vegas, midzeus and atalantis: updates (nw)

### PR DESCRIPTION
**Pull request by Hydreigon223**
vegas.cpp

-Major machine config cleanups based off of documentation. A Vegas 777 cpu board using a 250mhz cpu and/or 32mb ram doesn't exist as those changes applied to the Durango pcb. Gauntlet Dark Legacy, War: Final Assault and the NBA Showtime games can run on either a Vegas or Durango cpu board but came factory supplied with a Vegas cpu board. I tested both War: Final Assault and NBA Showtime with these changes and they ran the same with no ill effects.

-Updated game titles based off eeprom/guts/game code.

-New working game: NBA Showtime: NBA on NBC (ver 2.0).

midzeus and atlantis.cpp

-Documentation/info updates. It turns out all these games in mame run at incorrect speeds compared to actual pcb recordings.

### CODE REVIEW

**Comment by elhaya** [comment]
awesome!
nice to finally see some work being done on midzeus.
hopefully there's more to come :)

**Comment by MooglyGuy** [comment]
@elhaya Reading the diff, you will note that the change amounts to some updated comments and the addition of various machine flags to indicate imperfect timing and a lack of LAN emulation. I wouldn't hold my breath.

**Comment by elhaya** [comment]
> @elhaya Reading the diff, you will note that the change amounts to some updated comments and the addition of various machine flags to indicate imperfect timing and a lack of LAN emulation. Don't get too excited.

of course.
I'm hoping we'll so some serious progress from Phil Bennett anytime soon, however, every little change is welcome as it keeps the interest up and helps us achieve our final goal :)

**Comment by Hydreigon223** [comment]
> I'm hoping we'll so some serious progress from Phil Bennett anytime soon, however, every little change is welcome as it keeps the interest up and helps us achieve our final goal :)
Either Ted Green or Phil Bennett. I don't like the fact some drivers have outdated info. Kind of gives me an incentive to take a stab at those emulation problems.

One of my long term goals is to see link support on those Midway V Unit games. All I know is this hardware requires a good sync at the CPU level or they won't communicate. No form of shared ram is involved. @Risugami only had success in linking these games by underclocking the main cpu (most likely both instances running slow as a result). Ted Green mentioned Zeus 2 comms functioned similar to Midway V Unit comms.

**Comment by rb6502** [comment]
Aaron's info on the board configurations comes directly from the people who programmed the games, so I wouldn't be so fast to change it.

**Comment by Hydreigon223** [comment]
> Aaron's info on the board configurations comes directly from the people who programmed the games, so I wouldn't be so fast to change it.

That...I kind of find strange. What made me think a Vegas 777 board running at 250 MHz doesn't exist is because it's possible to use a Vegas 777 cpu board factory installed in a Gauntlet Legends to run War: Final Assault and NBA Showtime and both run no problems (at their factory setting of medium resolution).

Sorry for um...it's difficult to explain. Aaron is a good guy who got Mame very far in development but I wish he could keep his work consistent and updated. One trait I despise about him is straight up ignoring communication hardware for game linking.

**Comment by rb6502** [comment]
MAME's support for Ethernet, async bit-serial, and parallel all postdate Aaron's active work on the project.  Blaming him for not supporting comms is like blaming Nicola for not supporting D3D9.

**Comment by Hydreigon223** [comment]
> MAME's support for Ethernet, async bit-serial, and Centronics parallel all postdate Aaron's active work on the project. Blaming him for not supporting comms is like blaming Nicola for not supporting Windows 10.

If you think of it that way, you are correct. I wonder why Midway V Unit communications in Mame wasn't looked more into a few years ago? What sparked my interest was attempting to link two Cruis'n USA cabs with (specific) LCD monitors in them and they fail to communicate. Thinking about this issue drives me crazy and curious for multiple reasons.

**Comment by cuavas** [comment]
>One trait I despise about him is straight up ignoring communication hardware for game linking (unless that hardware is necessary to run the game otherwise it won't boot).

Watch yourself.

**Pull request closed without merging**
