### PR TITLE
202107 bgfx upstream sync (bgfx 13e6100, bx 51f25ba, bimg f5f27ec)

### PR DESCRIPTION
**Pull request by belegdol**
I have synced with upstream bgfx, bx and bimg in an attempt to fix https://gitlab.freedesktop.org/mesa/mesa/-/issues/4727 and https://github.com/mamedev/mame/issues/7820. Unfortunately, neither of the issues got better.

I am putting this out there in case someone finds this useful. There are two known issues:
1. ~~73641b4 needs to be fixed properly~~
2. ~~Under Linux when using vulkan bgfx backend, the output is flipped vertically.~~
3. Ikaruga crashes with dx9 and dx12 backends on Windows
4. Firefox crashes with dx9 backend on Windows

### CODE REVIEW

**Comment by algestam** [comment]
Nice work!

I've played around a bit and it seems like recompiling the shaders (`make shaders`) resolves the issue with semi-flipped video output with vulkan bgfx backend on linux.

When building an emscripten build, defining `BX_PLATFORM_STEAMLINK=0` was required to get the build to succeed.

**Comment by belegdol** [comment]
Indeed, sadly it does not help with either of the original issues I was trying to solve by syncing with upstream.

**Comment by belegdol** [comment]
I have now checked and the change in imgui debugger mount window is not too bad. The window is shorter but that's it. Before:
Zrzut ekranu z 2021-07-25 17-41-57
After:
Zrzut ekranu z 2021-07-25 17-46-38

As such, I have merged the build fix with others as it isn't a hack but a real fix.

**Comment by belegdol** [comment]
In case anybody wants to pick it up I have found the following issues:
- Ikaruga crashes with dx9 and dx12 backends on Windows
- Firefox crashes with dx9 backend on Windows

**Comment by cuavas** [comment]
See #8419

**Pull request closed without merging**
