### PR TITLE
Change the resolution to 512x384

### PR DESCRIPTION
**Pull request by launcherEXE**
The screen resolution for DJMain games for some reason was set to 488x384, but the resolution indeed was 512x384.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
seems likely, but based on what evidence?

**Comment by launcherEXE** [comment]
It was based on exploring tile and palette viewer (F4).

**Comment by cuavas** [comment]
That means nothing.  Many games have graphics larger than the display area.  You need to provide evidence that the hardware behaves this way.

**Comment by launcherEXE** [comment]
Maybe this video says something.
https://www.youtube.com/watch?v=n8b4bkRGv8A

**Comment by launcherEXE** [comment]
Also, system16 confirms that resolution (if you can name it trusted resource) .
http://www.system16.com/hardware.php?id=826

**Comment by MooglyGuy** [comment]
Based on the video, it looks like the tilemap should at least be extended on the right-hand side, and I'm willing to stake what little reputation I have on the left side simply being cut off due to monitor adjustments. This looks like a valid fix.

**Pull request closed without merging**
