### PR TITLE
toaplan1.cpp: Use pdrawgfx in draw single sprite

### PR DESCRIPTION
**Pull request by cam900**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
are there any differences between the custom implementation and pdrawgfx? usually custom implementations are used like this when pdrawgfx has been found to not  have the correct logic.

**Comment by cuavas** [comment]
Looking at the code for the custom draw function, it looks like it isn’t actually doing anything special for sprite/sprite priorities – it always flags sprite pixels as priority 0xff (i.e. sprite pixels always obscure other sprite pixels even if they aren’t drawn due to having lower priority than tilemap).  IIRC this is the default behaviour of `prio_transpen`.  Could someone confirm?

**Comment by angelosa** [comment]
As an aside: why `prio_transpen` is `u32`? 
To my knowledge each bit is supposed to be a layer where sprite should go above or below -> is there even any 2d-based system that requires 32 layers?

**Comment by cam900** [comment]
prio_* supports Actually 31 layer.
Topmost bit is always used for sprite order - latest sprite is drawn under the previous sprite.

**Comment by cuavas** [comment]
I think it’s a case of “15 might not be enough, but 31 is probably safe”.  See comments by @awjackson in drawgfx.h about the two schemes for priority drawing.

**Comment by cuavas** [comment]
Not directly related to this change, but this code is a bit sus:
```
u32 toaplan1_state::screen_update(screen_device &screen, bitmap_rgb32 &bitmap, const rectangle &cliprect)
{
    log_vram();

    screen.priority().fill(0, cliprect);

    // first draw everything, including "disabled" tiles and priority 0
    m_tilemap[0]->draw(screen, bitmap, cliprect, TILEMAP_DRAW_OPAQUE | TILEMAP_DRAW_ALL_CATEGORIES, 0);

    // then draw the higher priority layers in order
    for (int priority = 1; priority < 16; priority++)
    {
        m_tilemap[3]->draw(screen, bitmap, cliprect, priority, priority, 0);
        m_tilemap[2]->draw(screen, bitmap, cliprect, priority, priority, 0);
        m_tilemap[1]->draw(screen, bitmap, cliprect, priority, priority, 0);
        m_tilemap[0]->draw(screen, bitmap, cliprect, priority, priority, 0);
    }

    draw_sprites(screen, bitmap, cliprect);
    return 0;
}
```
It’s depending on the category to draw being in the low bits of the flags argument.  It should be using `TILEMAP_DRAW_CATEGORY` to make it clear what it’s trying to do.

**Comment by cuavas** [comment]
As far as I can tell, this is correct use of the second scheme described by @awjackson in the comments for drawgfx.h (the one with transitive priority, required when there are more than four layers).  If it causes issues, there’s a month to fix it.

**Pull request merged**
