### PR TITLE
force a partial update for seta x1_012 tilemaps whenever the scroll registers change - needed for a crude raster effect when entering underground areas on Caliber 50

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
https://www.youtube.com/watch?v=Q9lxLayq24A   shows the effect

**Comment by DavidHaywood** [comment]
I'm aware there are multiple approaches that could be used here.

Part of me considered avoiding adding the 'm_screen' member to the tilemap device, and instead trampoline it in the driver with a 'partial update' call before calling the device function.

Alternatively the flag to force scanline updates at all times could be set, although that seems overkill.

We need partial updates to happen, but if anybody has a preferred implementation over this one, feel free to close and do it another way.

**Comment by happppp** [comment]
If you go for this solution, could you use divideo? No need for all those set_screen then, unless there's a multi-screen game that uses this chip.
Also, if it's only for x-scroll, then add this?: if (offset == 0)

**Comment by DavidHaywood** [comment]
I'm honestly not sure what the best solution is, would divideo not be overkill?

I'd assume if the tilemap updates on xscroll, it would also read the other params per scanline, so I don't think limiting it to xscroll makes sense - there could be other yscroll effects we've never noticed.

**Comment by happppp** [comment]
Other than autodetection and some safety checks, divideo is the same thing you're doing here.

**Comment by ajrhacker** [comment]
At one point, I thought `device_video_interface` would be best reserved for CRTCs, and devices like X1-012 which merely rely on blanking/sync signals generated by other devices (X1-001 here) don't really deserve to use it. However, there are too many video devices which can technically be configured or strapped for either mode to make that a rule.

The automatic binding to the first screen may be more of a convenience than a good thing, since it frequently leads to configuration problems on emulated systems when they start acquiring slot options which can have their own screens.

**Comment by DavidHaywood** [comment]
I'm more inclined to think we should be moving away from trying to auto-bind / auto-detect screens

**Comment by cuavas** [comment]
> I'm more inclined to think we should be moving away from trying to auto-bind / auto-detect screens

I agree with this – in the long run, it’s more pain than it’s worth.

@ajrhacker can you please make a call on this?

**Comment by ajrhacker** [comment]
I have no strong preference for `device_video_interface` over the finder here, but the `set_screen` calls should probably stay.

**Pull request merged**
