### PR TITLE
New working clones

### PR DESCRIPTION
**Pull request by ajrhacker**
* Puck Man (Famaresa bootleg) [Marcos75]
* Pac-Man 4-in-1 (v3.3) [hack]

### CODE REVIEW

**Comment by Robbbert** [comment]
Are you sure about Pac-Man-4-in-1? It's just a homemade hack that's been in HBMAME for ages. The author's website: http://www.souzaonline.com/Games/Hacks/4in1hack.htm

**Comment by ajrhacker** [comment]
MAME has been more open to adding homebrew hacked versions in the last few
years, most of which don't involve hardware mods like this one does. I
haven't been looking at HBMAME, but I've seen at least one board converted
to this specific version auctioned on eBay.

AJR

**Comment by happppp** [comment]
Related to this, I think Multipac should be in MAME. It's not even a simple
(internet-only) romhack, it was sold as a kit.
manual with PCB info is on this page:
https://www.arcade-museum.com/game_detail.php?game_id=8789

It's one of my low-priority TODO :) but if someone else adds it, that would
be great too.

**Comment by stilett0** [comment]
I've no problem with either the Multipac suggestion (we used to not support any of Clay's kits which were currently being sold plus the typical couple year lead time as a courtesy to the scene, that time has now elapsed) or the Famaresa bootleg, but NAK from me re: the 4-in-1 hack (in case anyone cares what I think).

If we're gonna start supporting hacks that only very very infrequently were shoved onto a PCB, then we need to support all of HBMAME and put @Robbbert outta business. :(

**Comment by DavidHaywood** [comment]
there are probably a few thousand hacks in HBMAME that don't even work on PCBs ;-)

I've always tended to look at use cases with these things.  When people do start using them on PCBs because they offer something to the owners of the PCBs then it starts to make sense to document them in MAME, otherwise 20 years down the line PCBs are going to start showing up and it's not going to be clear what's running on them because we didn't do a good job of documenting it now.

I'd also say that hardware test software is worth documenting, even if it was developed by developers as it often provides a simple way to check for regressions.  For some drivers it might even be worth opening them up to some kind of software-list like approach if development on them becomes popular.

It's important MAME tracks what is going on, just as MAME evolves the culture surrounding what it documents has evolved too, things like the OutRun enhanced hack that we support exist because there was demand for it long after Sega stopped supporting the original game and as locations where arcades are placed started charging a single entry fee and expected the games set to freeplay to actually run proper attract modes for example.  I'd say some of these high score kits exist for similar reasons, or because now a lot of people are operating the board at home rather than them being turned on 24/7.

Outside of arcades you can see the very active development still going on around many of the classic home systems; new software, expansion boards etc. All very much as relevant as the original systems.

**Comment by rb6502** [comment]
This is fine, but it needs the conflicts resolved.

**Comment by ajrhacker** [comment]
The conflicts are easily resolved, but I'll return to this later.

**Pull request closed without merging**
