### PR TITLE
namco/namcos10: Add decrypter for Mr. Driller G [Samuel Neves, Peter Wilhelmsen]

### PR DESCRIPTION
**Pull request by 987123879113**
Hopefully this made it in before the freeze.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
ROM_LOAD( "0.8e", 0x0000000, 0x1080000, CRC(4b61ac62) SHA1(b91076ce3d99fbe1f9247c66a577af3c3d468b20) )
is the defaulted ROM, can you add it in?

**Comment by 987123879113** [comment]
Done.

**Comment by DavidHaywood** [comment]
I notice we're also a bit inconsistent on our use of the ull suffix on the 64-bit values in the keys, quite a few don't have them.

I don't know if this needs cleaning up for release, as I assume we have them in the first place because one of the compilers people expect to still work requires them?  Might be something for @cuavas to do a quick pass on after merging this in depending on what the preference is?

**Comment by 987123879113** [comment]
A consistency pass is quicker than waiting for a response so I went ahead and just did it. It kinda annoyed me at times too when I'd noticed the inconsistencies. They should all be consistent now I think.

**Comment by DavidHaywood** [comment]
I think Driller G can drop the NOT WORKING flag anyway, it seems to work fine.

panikuru too?  

these aren't timing sensitive like the music games

**Comment by 987123879113** [comment]
Oh right, I forgot to remove the set naming when I removed the other dump. Thanks. 

I guess those two games I wouldn't have an issue with promoting. There were some sound issues with panikuru similar to what I saw in knpuzzle but I was having fun playing it without any other noticeable issues for a while the other night. I'll leave the decision up to cuavas if he wants to include the last commit or not.

**Comment by 987123879113** [comment]
Ok, opened the PR again. I gave every game a quick boot one last time before release just to make sure nothing was obviously broken after the encryption key consistency pass.

**Comment by cuavas** [comment]
The `ull` suffixes are less important now than they used to be in older C++ standards as literal upgrade rules have been changed to be more intuitive.  They don’t really hurt though.

It’s too late for a ROM change, but I can get the decrypter in for the release.  Will it work with the existing ROM dump?

**Comment by DavidHaywood** [comment]
it will work with the existing ROM dump, the existing defaults aren't too bad with it, just has some high score data.

**Comment by cuavas** [comment]
Oh, and one other thing – uppercase integer literal suffixes are generally preferred, as you’re less likely to mistake “LL” for “11”.

**Comment by 987123879113** [comment]
As Haze said, existing ROM works fine. The initialized ROM just makes it use factory settings. It's no problem if the ROM change can't be included for this release. Sorry for the last minute change and thanks.

**Pull request merged**
