### PR TITLE
coco_cart.xml: flagged banked games as not supported, causing an alert

### PR DESCRIPTION
**Pull request by JoakimLarsson**
There are some code written to support banked games but there is no link to the softlist. I guess the interface="coco_cart" should be changed to interface="coco_banked_cart" and there is some code needed to make that connection. This assumes however that all banked games are using the same technique or we need to map carts to more unique drivers. Looks like @tlindner has started something here :)

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
Thx beta, I found the slot variants for ext now, I tried -ext banked_16 for predator and it still crashes, it is not obvious what slot extension I need here and maybe it is missing? I'll figure it out and add feature tags as needed if there is one available that works.

**Comment by cuavas** [comment]
Yeah, I'd rather let someone who knows how to work magic like that (e.g. @ajrhacker) address the issue.

**Comment by JoakimLarsson** [comment]
sure, I got a dialog with Nathan in the issue about it, I think there are several things that needs to be fixed. Right now it overflows the ROM memory_region area loading the rom.

**Comment by ajrhacker** [comment]
It turned out that the banked_16k interface type wasn't really set up to work with the CoCo 3's memory management, nor could it handle softlists. Anyway, the three banked games now load on coco3 as of 35526fa55615cdf8bcf453fa961b1e99c38d339c.

**Pull request closed without merging**
