### PR TITLE
new WORKING clones (YoYo Spell)

### PR DESCRIPTION
**Pull request by DavidHaywood**
new WORKING clones
------
YoYo Spell (prototype) [Opernet,  Recreativas.org, Museo del Recreativo]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I'd only *just* about consider this a clone, it's clearly what Little Robin evolved from, but at the same time it's almost an entirely different game, all the mechanics were reworked for the final game 2 years later on standalone hardware.

**Comment by happppp** [comment]
Was there a reason for the ".010" file extensions?

**Comment by DavidHaywood** [comment]
I'm not sure, you do see dumpers adding such extensions quite often though, so it probably has meaning to one of the tools or something.  @clawgrip  ?

**Comment by Osso13** [comment]
probably just the ROM type. 27010 is 0x20000.

**Pull request merged**
