### PR TITLE
Tidy up The Ultimate Tape Archive's dumps

### PR DESCRIPTION
**Pull request by ZoeB**
- Make both the software name and ROM names conform to lowercase 8.3 filename structure
- Give credit to who dumped each software title
- Optimise the image with tapclean, which changes the file's hashes (but not the payload's magic CRC32, as the target data itself is unaltered).  This makes the tape image fully pass inspection.

Many more to follow over the next few months, if this gets approved.

### CODE REVIEW

**Comment by etabeta78** [comment]
ROM names are not limited to 8.3... OTOH, we try to document in ROM names
labels or serials on original media.
Not sure what would be the best thing to place for these tapes, but it is
not necessary to cut those names at all...

**Comment by DavidHaywood** [comment]
for cassettes I try to leave the 'rom' names descriptive, so that if somebody unzips them (which a lot of people will do for non-MAME use) the content has meaningful names.

'8' letters is only a guide for the setnames too, just don't go crazy, they're meant to be easy to type / remember (and sometimes going over 8 does help with that, but if you get to about 20 you're doing something wrong)

**Comment by ZoeB** [comment]
OK, that's fine.  I'll stick to just adding new ones, then.  Thanks!

**Comment by ajrhacker** [comment]
I don't think the 8.3 filename change part was supposed to be merged.

**Pull request merged**
