### PR TITLE
Some WIP TBD

### PR DESCRIPTION
**Pull request by mikehyrus**

### CODE REVIEW

**Comment by happppp** [comment]
Some WIP TBD? It looks like you pressed the wrong button somewhere.
It's 30 unrelated commits containing https://github.com/mamedev/mame/pull/9804 plus https://github.com/mamedev/mame/pull/9184 plus a change to steppers.cpp

**Comment by mikehyrus** [comment]
Sorry, I'm having these cant automatically merge error how do I fix this.

**Comment by happppp** [comment]
Who knows.
If you want to try things out and learn more about pull requests, your own github page is a better place for trial&error testing.

**Comment by mikehyrus** [comment]
Well I can’t fetch the recent update on my repository side is there any help for that?

**Comment by happppp** [comment]
Make a new branch for each contribution you want to make?

**Comment by mikehyrus** [comment]
I don’t think that could link my future pull requests at this time.

**Comment by mikehyrus** [comment]
And I’m paranoid by the merge conflict I’m having on the master branch in my repository.

**Comment by ICEknigh7** [comment]
@mikehyrus:
- Save all your files with actual changes somewhere safe
- Delete your MAME fork
- Clone a new, up to date MAME fork
- Create a branch for your new changes
- Readd your changed files
- When you're finished, create a PR here
- Once it's merged, you can just delete the branch

**Comment by mikehyrus** [comment]
Does this mean I have to erase my repository or no?

**Comment by ICEknigh7** [comment]
Just do it and start from zero to make sure that everything is correct before you start making branches for each PR you want to make, it doesn't take so long.

**Comment by mikehyrus** [comment]
Copied my modified versions of dc_atomiswave.cpp and toaplan2.cpp as previous updated reference to a spare folder prior to the new pull request for those two.

**Comment by mikehyrus** [comment]
Maybe I'll go start on my Konami Viper PR 2.0 as well down the road since 1.0 closed due to the previous repository deletion.

**Pull request closed without merging**
