### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
----------
Game & Watch: Flagman [algestam, Mr. Do, Sean Riddle]

### CODE REVIEW

**Comment by happppp** [comment]
Probably better to use IPT_BUTTON1/2/3/4 for this one(no need for PORT_NAME then either). But if you want to use joystickleft/right, it will need PORT_16WAY.

PORT_BIT( 0x01, IP_ACTIVE_HIGH, IPT_JOYSTICKLEFT_UP ) PORT_CHANGED_CB(input_changed) PORT_16WAY PORT_NAME("1")

**Comment by algestam** [comment]
Thanks, I'll update the inupts to IPT_BUTTON1/2/3/4.

**Comment by algestam** [comment]
Also, I haven't found any cheats in this game. The only "hidden" functionality I've found is what seems to be a display test.

**Comment by happppp** [comment]
Ah, I see they're still 'directional' controls, maybe the fake joysticks is a better representation afterall?

**Comment by algestam** [comment]
Yes, the buttons are directional in the way that the are representing the legs and arms. I just commited a change to IPT_BUTTON* but perhaps it should be reverted?

**Comment by happppp** [comment]
A new update is fine, this PR will get squashed into 1 single commit before it's merged anyway.

**Comment by algestam** [comment]
Cool, I'll update now and add PORT_16WAY.

**Comment by happppp** [comment]
Thumbs up from me

**Pull request merged**
