### PR TITLE
gamegear, sg1000, sms software list additions

### PR DESCRIPTION
**Pull request by wilbertpol**
gamegear:
- Redumped Sports Illustrated Championship Football & Baseball (Euro, USA) [smspower]

New working software list additions
-----------------------------------
gamegear:
  Andre Agassi Tennis (prototype),
  Bubble Bobble (prototype),
  CJ Elephant Fugitive (prototype),
  Dinobasher Starring Bignose the Caveman (prototype),
  Dragon - The Bruce Lee Story (prototype),
  Empire Syndicate (Chicago Syndicate) (prototype, 19950320),
  Kawasaki Superbike Challenge (USA),
  Micro Machines (prototype)  [smspower]
sg1000:
  San-nin Mahjong (Jpn, alt)  [smspower]
sms:
  3D Gunner (prototype),
  Alex Kidd - High Tech World (prototype),
  Battle Wings (Bomber Raid, prototype),
  Cyborg Hunter (prototype),
  Game de Check! Koutsuu Anzen (Jpn, prototype)
  Hang-On (prototype),
  Missile Defense 3-D (prototype),
  Out Run 3-D (prototype),
  Solomon no Kagi - Oujo Rihita no Namida (prototype),
  Super Off Road (prototype)  [smspower]

New NOT_WORKING software list additions
---------------------------------------
gamegear:
  X-Terminator v2.1 for Game Gear (Euro, USA),
  X-Terminator v2.1J for Game Gear (Jpn)  [smspower]

### CODE REVIEW

**Comment by ajrhacker** [comment]
The redump of Sports Illustrated Championship Football & Baseball (GG) should also be mentioned in the commit, unless that change was a mistake.

**Comment by wilbertpol** [comment]
> The redump of Sports Illustrated Championship Football & Baseball (GG) should also be mentioned in the commit, unless that change was a mistake.

That change was intentional; I have updated the PR description.

**Comment by ajrhacker** [comment]
It should be noted in the commit message itself.

**Comment by wilbertpol** [comment]
Add a commit message for it

**Pull request merged**
