### PR TITLE
handheld/hh_sm510.cpp: Add Tiger Double Dragon II: The Revenge

### PR DESCRIPTION
**Pull request by algestam**
This PR adds Double Dragon II: The Revenge by Tiger. The MCU was dumped by Sean Riddle and I have digitized the display and prepared the MAME driver.

Marking this PR as a draft since the joystick left action doesn't seem to have any effect and I haven't figured out if the configuration is incorrect or if the left joystick simply doesn't have any effect in the game.

### CODE REVIEW

**Comment by FoxhackDN** [comment]
Someone is selling the manual on ebay, and zooming in on the poor photo they posted suggests backwards is only used in a specific mission. So it might not be broken.

**Comment by algestam** [comment]
Thanks @FoxhackDN, that sounds reasonable as I'm quite certain that the configuration is correct as per the PCB routing. Haven't played the game far enough to confirm this but will change the PR to be ready for review.

**Comment by FoxhackDN** [comment]
For future reference, he's a zoom in of that manual at 200%. It's blurry but you can kiiiiiiiinda see "Mission X only" there.
image

**Comment by happppp** [comment]
It's from 1990 (Tiger's copyright year is on the back of the packaging)
And yes, Batman is from 1989 even though it's a higher model number.

**Comment by algestam** [comment]
Thanks @happppp ! I'll update the year information 👍

**Pull request merged**
