### PR TITLE
Plug and Play additions

### PR DESCRIPTION
**Pull request by mamehaze**
(all [Team Europe, David Haywood])

New working clones
------------------
Mega Drive Play TV 1 (Japan)

New systems marked not working
------------------------------
Bakutou Sengen Daigunder DX (Japan)
Anpanman: Let's Go! Ikunou Drive (Japan)
Dragon Ball Z: Scouter Battle Taikan Kamehameha: Ora to Omee to Scouter (Japan)

New software list items marked not working
------------------------------------------
takara_daigander_dx_cart.xml:
R-01 ROM Robo Aoki Inazuma Bulion
R-02 ROM Robo Jurassic Soldier Bonerex

### CODE REVIEW

**Comment by mamehaze** [comment]
Maybe some of these could have better names
romr02
romr01

**Comment by einstein95** [comment]
> Maybe some of these could have better names

The names are... fun to romanise. The name is entirely subjective depending if you want to go with "what the creators meant" vs. "accurate to the Japanese"
R-01 ブライオン - bura + ion, lit. blue + lion so Bluion?
R-02 ボーンレックス - bōn + rekkusu, lit. bone + rex so Bonerex

**Comment by FoxhackDN** [comment]
> > Maybe some of these could have better names
> 
> The names are... fun to romanise. The name is entirely subjective depending if you want to go with "what the creators meant" vs. "accurate to the Japanese" R-01 ブライオン - bura + ion, lit. blue + lion so Bluion? R-02 ボーンレックス - bōn + rekkusu, lit. bone + rex so Bonerex

The full names are:
R-01 ROMロボ 蒼き稲妻 ブライオン = R-01 ROM Robo Aoki Inazuma Buraion (Official localized name appears to be "Blue Thrasher Bulion")
R-02 ROMロボ ジュラシックソルジャーボーンレックス = R-02 ROM Robo Jurassic Soldier Bonerex

**Comment by mamehaze** [comment]
I'm going to leave it to the team to decide on names, please change them to what you want them to be

**Pull request merged**
