### PR TITLE
Update the Sega CD software list.

### PR DESCRIPTION
**Pull request by FakeShemp**
This is pretty much a total rewrite of the Sega CD software list. I've tried to do as much research as I can on the subject and added a bunch of notes about the various discs in the list as well as what I could find out about missing software. 

Many software have been updated with "better" dumps (where "better" basically means "more well-documented"). There have also been a few new software dumps added which have popped up since the last time the list was updated.

### CODE REVIEW

**Comment by oddi5593** [comment]
not validation 
many errors

**Comment by FakeShemp** [comment]
That's what i get for forgetting to check the validation. Should be without syntax errors now hopefully.

**Comment by oddi5593** [comment]
why:
 double names 

    <software name="surgical">
		<description>Surgical Strike (Bra, 32X)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<info name="serial" value="157036"/>
		<info name="release" value="199601xx" />
		<part name="cdrom" interface="scd_cdrom">
			<diskarea name="cdrom">
				<disk name="surgical strike (bra, 32x)" status="nodump" />
			</diskarea>
		</part>
	</software>

this set have tag "nodump" , wh not have comment tag

**Comment by FakeShemp** [comment]
The duplicate name is a copy-paste error on my part. Will fix ASAP. 

Regarding nodump tag; why not? The nodump status indicates a dump is missing, which it is right. That's as far as my thought process went. If this is an incorrect usage, let me know please.

**Comment by Tafoid** [comment]
AFAIK, that is only acceptable to "nodump" a portion of a romset.  In the case of the entire set (or in this case, an entire disc image), it would be most acceptable to have the entry commented until it is found/dumped.  That means the six sets that come up in a **mame -validate** as having an incomplete disk definition will need to be commented.

colrmech
comptonsb
musijpbr
surgical (needs to be renamed as well)
smurfs
winxeye

**Comment by FakeShemp** [comment]
Seems I made a million mistakes eh? :)

I'll do a thorough look-through of all the set names when I'm in front of a larger screen tomorrow. Thank you all for your reports.

**Comment by oddi5593** [comment]
Explain how convert sets to chds. Me test few  sets from redump and trurip but sha1 it's different, try with chdman  and chdman x64 but not luck.
chdman createcd -i "blahblah.cue" -o "blahblah.chd"
where i mistake ?

**Comment by FakeShemp** [comment]
That's how I did it too. Not really sure what went wrong there, or if you or I are correct.

Could you post a sha1 hash for one of your converts?

**Comment by LnmVolbo** [comment]
@ FakeShemp, thanks for spending the time to overhaul this softlist.

Regarding the conversion issue, please consider indicating what version of CHDMAN.EXE you used for your conversions.  Older versions may not behave the same as the latest version.

**Comment by FakeShemp** [comment]
I know there are several versions that I used to convert. I'm on Linux mostly, so usually I'm always at the latest version thanks to apt. These are all at most made with a couple of months old binaries though.

All the TruRip dumps I believe I converted on Windows though, with the latest binaries from mame.net (0.178).

**Comment by LnmVolbo** [comment]
@ FakeShemp, thanks for responding.

Could any of the conversions have been performed with CHDMAN.EXE from MAME v0.174?

There have been reports of issues with that older version.

**Comment by FakeShemp** [comment]
They absolutely could have. I'll check it out.

**Comment by oddi5593** [comment]
Found where is problem with SHA1 , see first chd 

13:50:55.311: Info: stdout: Input file:   C:/1/3 Ninjas Kick Back (USA)/3 Ninjas Kick Back (USA).chd
13:50:55.312: Info: stdout: File Version: 5
13:50:55.312: Info: stdout: Logical size: 366,583,104 bytes
13:50:55.312: Info: stdout: Hunk Size:    19,584 bytes
13:50:55.312: Info: stdout: Total Hunks:  18,719
13:50:55.312: Info: stdout: Unit Size:    2,448 bytes
13:50:55.312: Info: stdout: Total Units:  149,748
13:50:55.313: Info: stdout: Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
13:50:55.313: Info: stdout: CHD size:     177,334,887 bytes
13:50:55.313: Info: stdout: Ratio:        48.4%
13:50:55.313: Info: stdout: SHA1:         7dfca4e3bfad7b8e6f98b24651970409fd0d7d6f
13:50:55.313: Info: stdout: Data SHA1:    6ebb602efa04127f905b39fafa6aa37ef69d1c7c

Need **SHA1** , this hashesh it's internal and correct , not **DATA SHA1**.
U must replace all hasesh with correct.

**Comment by FakeShemp** [comment]
Okay, I thought for sure it was the data sha1. Thanks for notifying me.

Well, that's an easy fix at least. Expect a new pull request soon.

**Comment by LnmVolbo** [comment]
@ **FakeShemp** and **oddi5593**, thanks for sorting this.

**Comment by FakeShemp** [comment]
Seems I've lost some files since I started this update. I don't have access to them any more unfortunately.

If anyone could help with the sha1 values for these redump.org dumps
- 3 Ninjas Kick Back (USA)
- Adventures of Willy Beamish, The (USA)
- Amazing Spider-Man vs. The Kingpin, The (USA)
- A-X-101 (USA) (RE)
- After Burner III (USA)
- Batman Returns (USA)
- Blackhole Assault (USA)
- Bouncers (USA)
- Bram Stoker's Dracula (USA) (Rev A)
- Chuck Rock (USA)
- Chuck Rock II - Son of Chuck (USA)
- Compton's Interactive Encyclopedia (USA) (2.01R)

that would help a lot.
Thanks!

**Comment by Flupper** [comment]
Input file:   adventures of willy beamish, the (usa).chd
File Version: 5
Logical size: 340,448,256 bytes
Hunk Size:    19,584 bytes
Total Hunks:  17,384
Unit Size:    2,448 bytes
Total Units:  139,072
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     120,893,683 bytes
Ratio:        35.5%
SHA1:         694476e5e82d7317ec6943d5d749764592045f37
Data SHA1:    c1516b30726c0335ca732e9595eba12b9dd62deb

Input file:   after burner iii (usa).chd
File Version: 5
Logical size: 336,374,784 bytes
Hunk Size:    19,584 bytes
Total Hunks:  17,176
Unit Size:    2,448 bytes
Total Units:  137,408
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     210,638,096 bytes
Ratio:        62.6%
SHA1:         5387cce37990836db962ce82ec217edbe2c1fd0d
Data SHA1:    95697301e1a81136a635f9dc93db9645cd31d3f8

Input file:   amazing spider-man vs. the kingpin, the (usa).chd
File Version: 5
Logical size: 578,922,624 bytes
Hunk Size:    19,584 bytes
Total Hunks:  29,561
Unit Size:    2,448 bytes
Total Units:  236,488
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     310,359,536 bytes
Ratio:        53.6%
SHA1:         4102f007184635832ca13ab770ccadcde32242da
Data SHA1:    f0b2ef9e37fb5f3f10129e438a1a98d7c36f10fd

Input file:   a-x-101 (usa) (re).chd
File Version: 5
Logical size: 656,534,016 bytes
Hunk Size:    19,584 bytes
Total Hunks:  33,524
Unit Size:    2,448 bytes
Total Units:  268,192
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     253,841,826 bytes
Ratio:        38.7%
SHA1:         4a0200c4b1d6b7f486d1946b6ce886d35872aae7
Data SHA1:    e0a323a38305dc8cbb4d9c778d8256dd0fcd4dc5

Input file:   batman returns (usa).chd
File Version: 5
Logical size: 548,733,888 bytes
Hunk Size:    19,584 bytes
Total Hunks:  28,020
Unit Size:    2,448 bytes
Total Units:  224,156
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     311,068,890 bytes
Ratio:        56.7%
SHA1:         fcef5b725f01b928a29a60a5e3d4c493908b209f
Data SHA1:    49dc8d5f2760123f8babc57837c3818b90c546c8

Input file:   blackhole assault (usa).chd
File Version: 5
Logical size: 555,970,176 bytes
Hunk Size:    19,584 bytes
Total Hunks:  28,389
Unit Size:    2,448 bytes
Total Units:  227,112
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     331,164,850 bytes
Ratio:        59.6%
SHA1:         e7533c9de5cea95b3d3ddbcc19d0002aa4fabb2b
Data SHA1:    028afbfd19ac39d3573725fb0caa5c05e3288fa5

Input file:   bouncers (usa).chd
File Version: 5
Logical size: 456,933,888 bytes
Hunk Size:    19,584 bytes
Total Hunks:  23,332
Unit Size:    2,448 bytes
Total Units:  186,656
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     164,592,845 bytes
Ratio:        36.0%
SHA1:         ec21e095b7670989495095f6a6cb9a94ba24a405
Data SHA1:    278c615b7d3411f7cc760e0147988c64b848cfdf

Input file:   bram stoker's dracula (usa) (rev a).chd
File Version: 5
Logical size: 465,619,392 bytes
Hunk Size:    19,584 bytes
Total Hunks:  23,776
Unit Size:    2,448 bytes
Total Units:  190,204
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     278,156,219 bytes
Ratio:        59.7%
SHA1:         ff8b30072085ed157c94859371e6a8f087ebd132
Data SHA1:    ae70b55e7e614b3cb98e03e207103fec0bc31873

Input file:   chuck rock (usa).chd
File Version: 5
Logical size: 339,508,224 bytes
Hunk Size:    19,584 bytes
Total Hunks:  17,336
Unit Size:    2,448 bytes
Total Units:  138,688
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     184,226,594 bytes
Ratio:        54.3%
SHA1:         2a0ca620f253992e92af5655c7ed4203a1537b0e
Data SHA1:    409746c3e505b9d5dade6cf4b5b01165930ade86

Input file:   chuck rock ii - son of chuck (usa).chd
File Version: 5
Logical size: 492,459,264 bytes
Hunk Size:    19,584 bytes
Total Hunks:  25,146
Unit Size:    2,448 bytes
Total Units:  201,168
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     241,242,457 bytes
Ratio:        49.0%
SHA1:         d47e53ee53653ee9b5623f276060e7a5f4f28c9e
Data SHA1:    b8445f6352fed1242b6dbf40807a0b1913a3cdad

Input file:   compton's interactive encyclopedia (usa) (2.01r).chd
File Version: 5
Logical size: 398,671,488 bytes
Hunk Size:    19,584 bytes
Total Hunks:  20,357
Unit Size:    2,448 bytes
Total Units:  162,856
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     183,460,550 bytes
Ratio:        46.0%
SHA1:         2df62d0e0a8f37e7b52c549ce7605d8c55fadf00
Data SHA1:    14ee396c5d4d02059527d9894fbf1d4ae17e2f0a

**Comment by FakeShemp** [comment]
@Flupper Thank you very much! I think all of the faulty hashes are fixed now :)

**Comment by Flupper** [comment]
You're welcome, glad to be of service. :)

**Comment by Flupper** [comment]
@FakeShemp Suppose you could share the fixed cuesheet for Road Rash (USA, Prototype, Beta 3 - 19950211) ?
The one at Hidden Palace is broken unfortunately.

**Comment by FakeShemp** [comment]
I can, but I'm away from my computer for about a week on business. Will do so when I can.

**Comment by Flupper** [comment]
No problem and thank you.

**Comment by LnmVolbo** [comment]
It appears that _Road Rash (USA, Prototype, Beta 3 - 19950211)_ was "fixed" by ignoring the track 02 information, because when that information is in the .cue file, chdman.exe fails to complete the conversion successfully.

I looked into that a little and found that the index 01 information for track 02 was too large.  If it is recuduced, chdman completes the conversion without errors.  The time (61:01:71) does not correspond to the file length of 625,857,792 bytes.

It is my understanding that if the existing track 02, index 01 line:

    INDEX 01 61:01:71

is reduced, a successful chdman conversion can be accomplished.

I have find that the largest value for index 01 that allows chdman to complete is:

    INDEX 01 59:05:73

And the corresponding sha-1 for that conversion is:

4213754f77d1b510c1259a54e4528499ef479421

Entire .cue file:

    FILE "Road Rash CD (Beta 3 - Feb 11, 1995) (hidden-palace.org).bin" BINARY
      TRACK 01 MODE1/2352
        INDEX 01 00:00:00
      TRACK 02 AUDIO
        PREGAP 00:02:00
        INDEX 01 59:05:73
    

Even with these changes, it is still likely to be considered a bad dump, unless someone has some better evidence that it is OK.

**Comment by FakeShemp** [comment]
Great research. Thank you.

I still don't have the cue I used here with me right now, but I'm fairly sure I didn't just cut the second track out. If I did, I did so by mistake.

**Comment by oddi5593** [comment]
@LnmVolbo  : I open bin with isobuster , this track 02 is missing , have only track 1 . If used isobuster for generate cue file, file it's same with Tafoid's cue.
Btw - isobuster generate 96% correct bin and 4 % bad sectors without track 02. 
If extract 96% correct sectors to new bin or iso , new SHA1 is very different.
My opinion  - this dump add with comments tag because we dont know which convert is right .
Now with my tests i have 4-5 different hashes !!!

**Comment by LnmVolbo** [comment]
@ FakeShemp, you're welcome.

Regarding cutting of second track.

In your absence, Tafoid cut it: https://github.com/mamedev/mame/commit/ff414f1a89327236d074187db6585a2820d4a5db

When you are able to locate your .cue file, chances are it won't match the new sha-1 from that commit.

**Comment by FakeShemp** [comment]
That works too. :)

**Comment by FakeShemp** [comment]
I'm back at my computer and checked the cue I used. It looked like this:

```
CATALOG 0000000000000
FILE "Road Rash CD (Beta 3 - Feb 11, 1995) (hidden-palace.org).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 12:01:71
```

I can't for the life of me remember where I got the 12:01:71 from. :confused:

**Pull request merged**
