### PR TITLE
some Namco posirq kludges [David Haywood] + Final Lap R sprite position fix [Ryan Holtz]

### PR DESCRIPTION
**Pull request by DavidHaywood**
- some Namco posirq kludges [David Haywood]

This fixes some graphics in Burning Force, Suzuka 8 Hours 2, and Nebulusray

In reality this probably needs correct emulation of when each layer latches values / renders scanlines (with some layers being linebuffered, and others not etc.) but I think identifying the problematic cases, and the fact that they are IRQ related helps for now, and Burning Force's regression keeps being reported.

- fix remaining finalapr sprite positions [Ryan Holtz]

This seems to cause a slight issue with Solvalou's top display, but Namco S21 positions are somewhat kludged anyway, and that's an unusual case with a mirror effect over the screen cropping off the top, so needs it's own research.

### CODE REVIEW

**Comment by happppp** [comment]
Is a 1-scanline gfx glitch worth this extra hack? IMO nope.

**Comment by DavidHaywood** [comment]
For burning force it's a big one we're losing out to 2003/Ra on, for nebray
its most of the stars, I'd say new behaviour was less the hack tbh, worth
it for quality of life/reputation

**Comment by cuavas** [comment]
So now we’ve got a game-specific hack papering over an issue.  Doesn’t that make people less likely to investigate it?  I don’t think, “But MAME2003+!” justifies this kind of thing.

**Comment by DavidHaywood** [comment]
Who is trying? I've spent 10 years looking for a cleaner noninvasive fix,
best I had was guessed timers and latches which was shot down on another
driver for lack of evidence, this is my compromise without going that route

**Comment by DavidHaywood** [comment]
The other thing with this, and maybe most important.

Both implementations are hacks.  To me, the -1 is more correct, as you update to the line before, which is more logical.

The only thing I've really done is, until there is a better solution, pick a better hack for the different cases.

I could add uglier guesswork, but we discussed before that doing that is worse than having a game specific hack, because it gives the illusion that we know more than we do.

Re: Mame2003, this game was played on a tournament recently.  People who were using newer MAME ditched it because they were told Mame2003 was better, because Mame2003 didn't have the glitch.  It's now cemented in their mind that MAME2003 is better.  I think offering a good experience, at least on par with older versions, is vital, otherwise we are going to bleed users, meaning this kind of gatekeeping will harm the project more than anything else.

My recent experience with investigating this Namco stuff, and the nature of some of the fixes really suggests nobody else is looking at it anyway, so this idea that it makes it less likely to be fixed doesn't hold water in this case.  It will probably be fixed when somebody does an FPGA implementation, as is often the case, because those are the only people doing the measurements  required.  What MAME does at this point will make no difference to that research, but shipping something worse than older versions does harm the project.

If this *really* isn't acceptable, I'd vote for just using the -1 version in both cases, the issues it causes are less significant than the current implementation.

**Comment by rb6502** [comment]
The major thing is that this has been broken for over a decade, so clearly nobody is looking into it.  MAME has a long history of doing things we know aren't hardware-correct to get correct audiovisual results, and we also have a long history of those things eventually being overtaken by hardware-correct implementations once we know what that is.  In this case, a fair number of games are affected and nobody has come up with a fix in the 10+ years this has been an issue, so I'm perfectly fine with this as the not-correct workaround.  It's marked with a TODO comment that it's not correct.

When someone hooks up a logic analyzer to one of the affected games' PCBs and figures out what's actually happening, it'll be great to get rid of this.  But until then, at least we're correctly representing what these games were intended to look like.  We've had a fair number of cases where official emulators/ports/remakes copy known-to-us MAME bugs, which to me is far more alarming than whatever 2003 is doing.

**Comment by philipjbennett** [comment]
If somebody is willing to write tests to run on actual hardware, I am
willing to get whatever measurements are needed.

Phil

**Comment by rb6502** [comment]
I'm not sure we even need a test program, as long as you have one of the 3 cited games (Nebulasray, Burning Force, or Suzuka 8 Hours 2).  @DavidHaywood can you tell us exactly what we're looking for?  POSIRQ time relative to the scanline counter, I guess?

**Comment by DavidHaywood** [comment]
far more than that.

I thought I already mentioned this, but the only way I got it running in all cases without kludges was by faking different timing for when each layer latches data, ensuring one layer type latches the line before, another doesn't latch (or reads the scroll data at the same time as every tile pull etc.)

plus yes, of course the exact time the posirq triggers, if it's relative to when the register is set, or relative to the start of a scanline.

practically everything regarding the timings in the driver is a complete guess.

'can reverse engineer from code behavior' will never tell you all those things.

it's also not something you can really sit and pass code to somebody else to test, makes more sense if you can sit there and study the results.

I feel Phil has more important things on his plate, we can offer a decent user experience in the meantime with a minimal impact change such as this.

**Comment by rb6502** [comment]
Phil is volunteering.  But if you think it's impossible for Phil to find the problem based on existing code and you aren't interested in writing a test program, then I'm going to revert the hack, because it's more important for the game to be obviously broken.

**Comment by DavidHaywood** [comment]
as I said, it's no more of a hack than what's already there, it's just a more suitable hack for those games (if anything the existing logic, without the -1, is more of a hack)

**Comment by aaronsgiles** [comment]
"because it's more important for the game to be obviously broken" -- for every time this approach works, it fails for dozens of other cases that have languished for years. I disagree that this is a winning attitude for development. Especially if high profile developers are going to yell at people on forums for using old versions appeared to work better to the end user.

**Comment by DavidHaywood** [comment]
For testing, and ease of support, it's important to try and keep people onboard with the latest versions.  If we do tell a user to upgrade (because for the most part the older versions were far worse, I'm quite embarrassed by a lot of the code I did back then) but one of their favourite games suddenly has issues that were not present before, it leaves a bad impression.

For cases like this, where it's low-impact to keep things looking correct, it gives people trying to claim "newer MAME is just slower, not more accurate" less ammo if we compromise a little on our end in cases like this.  The 'MAME 2003 was better' crowd is loud and dangerous, and giving them 'proof' when a game has an obvious glitch in new versions that wasn't there before doesn't help our cause.

I'm inclined to agree that this idea that leaving things obviously broken is magically going to result in somebody coming along to fix them properly does not work.  The 15+ years some of these bugs have languished, when we could have been giving users a better experience that whole time, does not suggest people are leaping forward to fix the issues even if we leave them broken.

The fix for flickering sprites in Suzuka 8 Hours 2 was 'add sprite buffer just like most of the other drivers using the chip' but in 20 years nobody else even did that.  Even the engine sound fix was low hanging fruit, basically a missing register readback.  Nobody came forward to fix it.

For cases like this, where proper timing will require extensive research, I don't think it's going to make much of a difference if there's a kludge in MAME or not.  Somebody wanting to do that research will do that research.  If they see there is a kludge in MAME, if anything, they'll know where they need to check more carefully.

More in-depth research on these things will happen when it happens.  That might be another 15 years from now.  Do we really want to intentionally ship something worse than we could be shipping for another 15 years?

The overall trend of the project has been removing hacks over time, it always feels much better doing that, but it's also important to realise that they did serve a purpose, bridged a gap.  A lot of the perceived accuracy in early versions of MAME was no such thing if we're honest, but hundreds of those drivers have been replaced with much better implementations, even with hacks that provided a better user experience.  I don't feel any of those prevented somebody with a desire to do further research from doing so.

**Comment by rb6502** [comment]
_practically everything regarding the timings in the driver is a complete guess._

If it's really that unknown, then we can at least start chipping away at it without any test code.  Someone just needs to point Phil at what to measure.  CPU clocks?  Vsync/Hsync?  Where in the frame IRQs happen?  I don't know what we're missing here, but it'd be great if people who do know could tell him.

**Comment by angelosa** [comment]
imho by quick look at the schematics available this driver already needs improvements in accuracy, and I honestly don’t mind if there’s a new hack since things are quite sloppy anyway.

**Comment by DavidHaywood** [comment]
As already mentioned.

All the basic screen timing events need confirming.

Even other event need confirming (eg. when MCU IRQs happen relative to other things - we have to do them before VBL as not to break Assault Plus)

For things like the POSIRQ we need to know exactly when it triggers.  Is it relative to when the write happens, or always in the same place.  I'd guess always the same place, based on some internal counters.  When do those internal counters expire? Is there a delay between writing it and it becoming active? can it trigger multiple times on the same line?

What delay is there between writing video registers and them having an effect.  Is the hardware latching scroll values, or even tile numbers in the hblank period of a previous scanline? the one before that? or is such data read in realtime, every 8/16/32 pixels of the display?  Is this the same for every layer? the Rotation Layers, the Road layers on some board types.  This kind of thing needs checking for every video register on every chip.

Likewise when are sprite attributes read, is they're rendered to a line buffer, when?  There are multiple sprite systems, so this needs checking on multiple board types.

Palette is the same, when can palette changes take place? can you do mid-scanline palette effects (ie are palette changes more immediate than tilemap / sprite attribute changes)

Are there waitstates? does the 2nd 68k bus steal?  Anything else that could impact timings beyond the video implementation itself

How does all of this relate to the later boards that are using similar setups with higher resolutions?

As I said, this is a huge amount of work, and something that a person with the board would need to construct a comprehensive test suite for, probably measuring a lot of these things with logic analyzers, knowing what they were looking for based on chip pinouts and such.

I know Phil offered, but if I look at the other things in Phil's pipeline I think it's more important those come through, cases where there is no emulation, or where it's solving problems that can't be papered over for the time being.  I do think at some point the FPGA scene will start cloning these Namco boards, and they do seem to have been forthcoming with information where it's needed, so it probably makes little sense for Phil to be doing it?

**Pull request merged**
