### PR TITLE
Implement new option to hold down inputs when machine boots

### PR DESCRIPTION
**Pull request by ajrhacker**
New -boot-pressed option allows a number of I/O fields to be specified on the command line. These buttons will be held down for some milliseconds (configurable, default to 750) after resetting the machine, after which the presses are permanently cleared.

Disallow ioport_field::name() from returning nullptr; there are too many places in the core that don't check for it and shouldn't have to. Use type_class instead to determine if a field is an anonymous internal input. (nw)

Move mouse hit targeting into uiinput.cpp, eliminating another dependency. (nw)

### CODE REVIEW

**Comment by p1pkin** [comment]
what the purpose of this ? I was thought such features  (i.e. input-macro type) supposed to be implemented as LUA plugins by nowadays design.

**Comment by ajrhacker** [comment]
The rationale is that some machines test certain inputs immediately after booting and jump into a service mode or something if those inputs are active. The problem is that they only give the user a very short time frame in which to enter these inputs, and the frontend interfaces and inevitable OS dependencies of MAME make that more of a challenge than it is on actual hardware.

There's also the pathological case of r2dx_v33, where inputting four joystick directions at once plus another button before the V33 gets too far is pretty much impossible to do (-joystick_contradictory is not enough for some keyboards) without -boot_pressed or modifying the driver. On actual hardware it probably involves temporarily uncoupling the joystick, but emulating precisely that in MAME would be even uglier. However, I see splitting that game into two sets and calling the feature an "undocumented secret" as a weak excuse to avoid making it user-accessible.

**Comment by mamehaze** [comment]
again, that's something lua should be able to take care of, without the need to add extra core options.

also for the Raiden 2 / Raiden DX 2-in-1 case they were sold as separate games (probably just both coded onto the board to reduce production costs) the way we handle it makes sense.

**Comment by ajrhacker** [comment]
In theory, yes, Lua could probably be used to implement features like this. However, the Lua engine doesn't grant access to the ioport structures on a level quite deep enough for the functionality of -boot_pressed, let alone the autofire cheat added a few months ago. Also, Lua scripts can't be configured through the command line except through autoboot commands, which as currently implemented wouldn't execute soon enough for this purpose.

**Comment by p1pkin** [comment]
can you cut this submission in two pull reqs please ? with separate fixes (which is pretty valid) and new core options (which is questionable)

**Comment by rb6502** [comment]
Agree with Haze and Metallic: if Lua doens't meet your needs, follow Carl's example and extend it so it does.  And remove that bit of this request; we'll certainly take the bugfix and the pointer cleanup.

**Comment by ajrhacker** [comment]
All right, I'll retreat, regroup and resubmit the fixes as a new request.

**Pull request closed without merging**
