### PR TITLE
ibm5150.xml: Software list additions

### PR DESCRIPTION
**Pull request by ArcadeShadow**
New working software list additions
--------------------------------------------
America's Cup Yacht Racing Simulator [Total DOS Collection]
Ballyhoo [Total DOS Collection]
Beyond Castle Wolfenstein (alt) [Total DOS Collection]
Bruce Lee [Total DOS Collection]
Championship Golf - The Great Courses of the World - Volume One: Pebble Beach [Total DOS Collection]
Commando [Total DOS Collection]
F-15 Strike Eagle (3.5", v402.01) [Total DOS Collection]
F-15 Strike Eagle (5.25") [Total DOS Collection]
Deadline (release 27) [Total DOS Collection]
Destroyer [Total DOS Collection]
Gettysburg: The Turning Point (v2.0) [Total DOS Collection]
Hacker II (alt) [Total DOS Collection]
Karateka (v1.0) [Total DOS Collection]
King's Quest (DOS release, v1.0U) [Total DOS Collection]
King's Quest III: To Heir Is Human (5.25", v1.01) [Total DOS Collection]
Leather Goddesses of Phobos (1986, release 59) [Total DOS Collection]
Math Rabbit [Total DOS Collection]
Maze Adventures [Total DOS Collection]
Mean 18 [Total DOS Collection]
Mickey's Space Adventure (3.5") [Total DOS Collection]
Mickey's Space Adventure (5.25") [Total DOS Collection]
Mind Boggle [Total DOS Collection]
Space Quest - The Sarien Encounter [Total DOS Collection]
Tag Team Wrestling [Total DOS Collection]
World Tour Golf [Total DOS Collection]

### CODE REVIEW

**Comment by Tafoid** [comment]
The SHA1 for America's Cup Yacht Racing Simulator (ameyacht) appears to be incorrect in the XML added while the SIZE and CRC32 appears to be the same.

In XML: f47d610d0c539f2e8d41ee9ea95f7246255e3f44
File: b6e38fa5f61173c40869c72f2abc4f05b1e4bfc6

Can someone verify this?

**Comment by ArcadeShadow** [comment]
> The SHA1 for America's Cup Yacht Racing Simulator (ameyacht) appears to be incorrect in the XML added while the SIZE and CRC32 appears to be the same.
> 
> In XML: f47d610d0c539f2e8d41ee9ea95f7246255e3f44 File: b6e38fa5f61173c40869c72f2abc4f05b1e4bfc6
> 
> Can someone verify this?

You are absolutely right. My mistake, an involuntary copy/paste.
On next PR I'll add it correctly

**Comment by cuavas** [comment]
This promotes “King's Quest (DOS release, v2.0F)” (kingqstd) to supported, adding a note about copy protection.  Was this intentional?  Does the game now work?

**Comment by ArcadeShadow** [comment]
> This promotes “King's Quest (DOS release, v2.0F)” (kingqstd) to supported, adding a note about copy protection. Was this intentional? Does the game now work?

Yes, it was. I try it and it worked, that's how I get the game version.

**Pull request merged**
