### PR TITLE
nes.xml: Added 4 ROMs Of Unusual Size.

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions
-----------------------------------
A Winner is You [anonymous]
Bully Boy 500 in 1 [anonymous]
Pocket Games 150 in 1 (Mario boot screen) [anonymous]

New NOT_WORKING software list additions
---------------------------------------
400 in 1 Real Game [taizou]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I wonder if mc_cb203 belongs in st2302u_bbl_spi.cpp

It doesn't boot (maybe needs a different BIOS?) but the E4 xor is familiar.

**Comment by DavidHaywood** [comment]
yeah, probably different internal BIOS on it

000676: a9 eb        lda #$eb
000678: 85 80        sta $80
00067a: a9 1d        lda #$1d
00067c: 85 81        sta $81
00067e: a9 00        lda #$00
000680: 85 82        sta $82
000682: a9 11        lda #$11
000684: 85 83        sta $83
000686: a9 00        lda #$00
000688: 85 84        sta $84
00068a: 20 ed 60     jsr $60ed
00068d: 78           sei

0009f: a9 c3        lda #$c3
000a1: 85 80        sta $80
000a3: a9 1a        lda #$1a
000a5: 85 81        sta $81
000a7: a9 00        lda #$00
000a9: 85 82        sta $82
000ab: a9 1d        lda #$1d
000ad: 85 83        sta $83
000af: a9 00        lda #$00
000b1: 85 84        sta $84
000b3: 20 e3 60     jsr $60e3
000b6: 78           sei

jumps to internal area are offset unfortunately.

**Comment by DavidHaywood** [comment]
000713: 20 00 60     jsr $6000
000716: 97 93        smb1 $93
000718: a9 0c        lda #$0c
00071a: 85 80        sta $80
00071c: a9 1e        lda #$1e
00071e: 85 81        sta $81
000720: a9 00        lda #$00
000722: 85 82        sta $82
000724: a9 0e        lda #$0e
000726: 85 83        sta $83
000728: a9 00        lda #$00
00072a: 85 84        sta $84
00072c: 4c 74 60     jmp $6074
00072f: a2 20        ldx #$20
000731: 80 e0        bra $0713

vs

0013f: 20 00 60     jsr $6000
00142: 97 93        smb1 $93
00144: a9 fc        lda #$fc
00146: 85 80        sta $80
00148: a9 1a        lda #$1a
0014a: 85 81        sta $81
0014c: a9 00        lda #$00
0014e: 85 82        sta $82
00150: a9 0e        lda #$0e
00152: 85 83        sta $83
00154: a9 00        lda #$00
00156: 85 84        sta $84
00158: 4c 62 60     jmp $6062
0015b: a2 20        ldx #$20
0015d: 80 e0        bra $013f

**Comment by DavidHaywood** [comment]
these addresses aren't the same as the undumped bbl380 internal BIOS (where even the external ROM is bad too) so there are at least 2 undumped BIOS revisions for that.

**Comment by 0kmg** [comment]
Thanks for investigating. It's hard to find info on Coolboy RS-17 and I probably wouldn't have figured any of that out. Heck, even for RS-18 in my last commit I only figured it out because searching the internet lead me immediately back to another MAME driver :smile:

**Comment by DavidHaywood** [comment]
feel free to move it btw, just mark the internal BIOS as NO DUMP

as the external ROM here is complete it might be able to hack the internal BIOS we have, making a guess at why the offsets are a bit different, but that's a task for another day.

ideally we'll need a working unit at some point.

**Comment by ajrhacker** [comment]
The 203-in-1 unit seems to have been produced in several different packages under multiple aliases, since the Coolbaby RS-12 looks identical to the few easily findable RS-17 screenshots:

https://www.youtube.com/watch?v=6Zl7-kq5XBM
https://www.youtube.com/watch?v=mJATXMbU2VM

And here's a short review of yet another version which might have also been sold as BL-606 but is here packaged as the "Digiking ZL-853":

http://notes.12bit.club/BL-606

**Comment by 0kmg** [comment]
@ajrhacker Point taken, but those videos are labeled RS-12 though. The RS-17 seems to have this oddball shape: https://www.aliexpress.com/item/32251205316.html

**Comment by 0kmg** [comment]
Ok, I took Haze's "feel free to move it" suggestion. Two issues: 1) Do I need to bother renaming the unknown/undumped BIOS that I copied from the bbl380 entry? 2) Should the main ROM be marked BAD_DUMP as I've got it? It wasn't marked as a bad dump in nes.xml, but again I'm not sure of its provenance beyond tracing it to 2015: https://github.com/mamedev/mame/commit/2f25479afdb2dfb2d89a10a80d492d6c231e7edb#diff-a7e9b60821c3ba130fddbab15bf9715d8c609853491d3fca500232918eddd3c0

**Comment by ajrhacker** [comment]
I don't think BAD_DUMP is warranted in this case; certainly it's not bad in the same way as bbl380 (which has numerous FF-erased sections that definitely included vital data).

**Pull request merged**
