### PR TITLE
Start work on C64 tapes

### PR DESCRIPTION
**Pull request by ZoeB**
This has two commits: one simply tidies up the name of Ocean's label The Hit Squad; the other one tentatively adds in some more tape dumps.

These dumps are [verified good](https://archive.org/download/c64tapes/the_list.htm) by the Tapclean software.  Where there are duplicates between The Ultimate Tape Archive and the C64 Tape Archive, the payload's "magic CRC32" matches, but the overall files' CRC32s and SHA1s don't, which I believe is to be expected, given the nature of the medium.  (At the end of the day, this isn't a 1:1 mapping of binary data like in a ROM chip; it's counting clock cycles between a pulse wave flipping on a Compact Cassette tape, stylised to compensate for wow and flutter, wrapped up in a custom format with its own headers.)  So I'm ignoring duplicates, even though the whole-file hashes don't match.

If this is all OK, I'll add more later.  There were some quite stellar games released on tape.

### CODE REVIEW

**Comment by Pernod70** [comment]
The intention was to update the C64 softlist with further releases from The Ultimate Tape Archive, which I was led to believe would be every few months. It's now been almost a year with no further updates so you are very welcome to add verified dumps from other sources.

**Comment by ZoeB** [comment]
OK, here's a few more for now...  Cheers!

**Comment by ZoeB** [comment]
Hmm, I'm not clear on why that last commit broke it..?

**Comment by ZoeB** [comment]
> Hmm, I'm not clear on why that last commit broke it..?

Nevermind, it seems like something's gotten dislodged in the pipes now.

**Pull request merged**
