### PR TITLE
vgmplay.xml: Software list rename

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Lowercase on descriptive support file

### CODE REVIEW

**Comment by cuavas** [comment]
Arguably the whole list title is descriptive text.  “Video game music” isn’t a proper noun.

**Comment by happppp** [comment]
Depends on how you interpret it. The file format is VGM, not Vgm.

**Comment by cuavas** [comment]
The name of the application that the format came from is “VGMPlay” though.  “VGMPlay” is a proper noun, but this list isn’t using that name, it’s just describing what the files are.

**Comment by happppp** [comment]
Then it should mention VGM instead?
otherwise it's similar to nes.xml being "Video game ROM images"

**Comment by cuavas** [comment]
Yeah, NES is a contraction of Nintendo Entertainment System which is what it was referred to officially, but is VGMPlay ever actually called “Video Game Music Play”?

Anyway, I wouldn’t object to changing the name to “VGM log files” or something.  The current name seems to be trying to avoid mentioning “VGM”/“VGMPlay” by name despite the driver’s short name being named after VGMPlay.

**Comment by ArcadeShadow** [comment]
OK. If there is no objection, I will rename it to "VGM sound logging files"

**Comment by happppp** [comment]
I'd go for simply "VGM files".
Similarly if we had an MP3 player, it would be "MP3 files", not "MP3 compressed audio files", IMO it's weird.

**Comment by cuavas** [comment]
But our cartridge lists, etc. are "Foo cartridges" or "Bar tapes", not "<Format> files. They describe the media represented, not the files themselves. "VGM logs"?

**Comment by ArcadeShadow** [comment]
For now, I changed to "VGM logs"

**Pull request merged**
