### PR TITLE
M1COMM update, S32COMM initial commit

### PR DESCRIPTION
**Pull request by SailorSat**
Updates to the MODEL1 COMM BOARD:
- general: don't build localhost/remotehost filenames multiple times.
- simulation: fixed "master bytes" - fixes missing "insert coin"/"press start" animation and "V.F."-flashing on virtua formula slaves.

Adds Sega SYSTEM 32 / MULTI32 COMM Board simulation:
- virtually the same as the MODEL1, but with half the shared memory.
- emulation: suffers the same problem as M1COMM - MB89374 not yet emulated.
- simulation: contains 3 known firmware revisions; rad rally, f1 super lap and outrunners/stadium cross
- simulation: rad rally and f1 super lap seem to work without problems.
- simulation: outrunners crashes when trying to coin up in a linked game.

f1lap_link_2p

orunners-link_4p

radr_link_2p

### CODE REVIEW

**Comment by SailorSat** [comment]
f1lap_link_4p

orunners-link_8p

radr_link_4p

**Comment by rb6502** [comment]
Looks great!  I'll apply this as soon as 0.163 is out.

**Comment by rb6502** [comment]
SailorSat, I'm showing conflicts against current.  Could you rebase the patch against latest please?

**Comment by SailorSat** [comment]
try again please.

**Pull request merged**
