### PR TITLE
bus/nes: Fixed Powerful 255 in 1 and added its parent.

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions (nes.xml)
-----------------------------------
Powerful 250 in 1 [NewRisingSun]

Software list items promoted to working (nes.xml)
---------------------------------------
Powerful 255 in 1

### CODE REVIEW

**Comment by 0kmg** [comment]
Note: this is a rewrite of the old version (that never showed more than a grey screen). I've added a base class for simple multicarts that have a write-protect feature of their CHR RAM. As far as I can tell only simple (i.e. nothing with a MMC3 clone or other ASIC) multicarts ever do this, so this seemed an appropriate place for the base class. There are at least a half dozen others that I plan to add, plus a couple of devices in multigame.cpp already that write-protect CHR RAM (same code with different identifier names of course!) that I'll look into switching over.

**Comment by Tafoid** [comment]
The mc_pw250 entry has the same rom label as the mc_pw255 entry (both show 255-in-1) and since one is denoted a clone of other, this gives us a same label different hash mismatch.  Could you take care of this in your next round of commits?

**Comment by cuavas** [comment]
@Tafoid please don’t try to enforce unique ROM labels across clones.  It’s unhelpful.  If the actual ROMs have the label/screen print in the cartridges, they should have the same label in the software list.

**Comment by Tafoid** [comment]
These are not rom labels in this case.  I suspect it is simply a copy and paste mistake.  I merely asked @0kmg to look at it.

**Comment by 0kmg** [comment]
It was a copy paste error, yes. I had intended the new made-up label to match the old made-up label :)
If only there were more PCB photos for bootleg cartridges...

**Comment by cuavas** [comment]
If you believe it’s a copy/paste error, then frame the question that way.  Your comment reads as though you’re trying to enforce unique labels across software list items.

**Comment by Tafoid** [comment]
@cuavas While you are welcome to read my comment any way you wish, of course.  I was merely stating the problem as I saw it.  One of the labels appeared to be wrong and because of the parent/clone relationship this was both noticed and can cause issues with people dealing with them.  Most of these consoles have manufactured names as it stands with no bearing on actual label/notes/model numbers and don't even reference any physical chip/board numbers inside them.  Many times they are a simple binary blob of data, sometimes even with manufactured headers from copiers or otherwise (INES mappers).  Many of these popular cartridge system will likely NEVER see proper internal labels like we've known for machines in MAME due to dumps coming from copiers and not requiring chip level dumping.  While there may be a time many of these consoles entries will be dumped at a game level (like bootgod did with documenting so many NES games years back), when/if these are corrected they might finally have 'proper' labels.  Everything right now, quite honestly, feels like a placeholder and a waste of time to argue about.

Anyway, I defend my comment and the reasoning behind posting it.

That all being said, I feel we are all going to start enforce strict softlist naming standards as strict we've seen in MAME historically, you'll find less and less people willing to take the time to even contribute softlist information because of the overall hassle of it all.  I'd rather have an entry in a softlist, in the end, regardless of label, even if we know the label isn't 100% correct to begin with.  Such information, should it become available, can easily be passed via update.  We are never going to get perfection on the first go.

**Comment by 0kmg** [comment]
For what it's worth label is changed in https://github.com/mamedev/mame/pull/8410.

**Pull request merged**
