### PR TITLE
Improvements to almost all games in skylncr.cpp

### PR DESCRIPTION
**Pull request by ajrhacker**
- Use standard input mappings in all games except Sonik Fighter
- Add working hopper outputs and payout buttons
- Promote mbutrfly to WORKING after solving the protection (the code wasn't encrypted) and add the button lamps internally associated with it
- Decrypt bdream97, which is almost working now with obvious graphical glitches and some apparent input problems

Slight error logging elaboration for illegal Z80 instructions (nw)

### CODE REVIEW

**Comment by cuavas** [comment]
So just to confirm, you're sure bdream97 expects to see encrypted data on normal load/store but gets decrypted data for M1 instruction fetches?

**Comment by ajrhacker** [comment]
Yes, only the opcodes in the program ROM (a lot of NOP fill included) have the D7 bit inverted. The non-opcode data isn't encrypted.

(bdream97 never attempts to write into the ROM, though the same couldn't be said of mbutrfly when it was still failing a protection check and putting the SP in the middle of ROM, which tended to run the Z80 off the rails in short time.)

**Comment by cuavas** [comment]
What if the CPU does an M1 fetch from RAM? Perhaps it would be better to use a single handler for the entire decrypted opcodes space that reads from the program space and does the necessary transform rather than a fake ROM region. That would better represent the hardware if it's doing something simple like XOR M1 with a data line.

**Comment by ajrhacker** [comment]
> What if the CPU does an M1 fetch from RAM?

That doesn't happen with most arcade games, and certainly not here.

> Perhaps it would be better to use a single handler for the entire decrypted opcodes space that reads from the program space and does the necessary transform rather than a fake ROM region.

All right, but there are dozens of existing drivers that use the "fake ROM region" method (or a memory share, which would get included in the savestate unnecessarily).

> That would better represent the hardware if it's doing something simple like XOR M1 with a data line.

I don't think you have any better idea than I do as to what the hardware actually does. Even the button lamps in mbutrfly are just an educated guess based on what causes those I/O lines to be set.

**Comment by cuavas** [comment]
From experience with these kinds of boards, the "encryption" schemes are usually the most trivial hack they can manage that will reduce the likelihood of unskilled bootleggers doing ROM swaps. XOR a data line with M1 fits pretty well with the kinds of things you'd likely find.

I know other drivers use fake ROM regions, but that doesn't make it right. Also, MAME hasn't supported separate address space for Z80 M1 access for very long, previously direct_update_handler hacks were necessary which pretty much required you to make a fake ROM region (MAME CPU cores couldn't fetch instructions from anything that wasn't plain memory so you couldn't decrypt on-the-fly even if you wanted to). The other drivers should really be updated where appropriate.

Button lamps are educated guesses in most gambler drivers. The longer you work with this kind of stuff, the better your guesses become. Such is the way when working without complete documentation.

**Comment by ajrhacker** [comment]
I thought I removed the "opcodes" region with my last rebase, but the dummy region was still in the ROM definition. Now it's gone for good.

**Comment by cuavas** [comment]
Can you please make it pass through the debugger access flag to the program space? See osborne1 or vixen for an example (it's needed to suppress read side effects when viewing memory in the debugger).

**Comment by ajrhacker** [comment]
The sort of code introduced in bb6369ab0d91a92f4942732f8155ac0e087b6d07 I see as too ugly to demand for widespread use. It's an overly complicated solution for a problem that seems of negligible importance when the target space has purely functional read handlers.

**Comment by cuavas** [comment]
Well we work with what we've got.  That's what you need to do when passing through accesses, if nothing else just because someone else might copy you in a case where it really does matter.

**Comment by ajrhacker** [comment]
I'd really like for this pull request to be accepted for 0.177. The solution to the debug access issue I implemented should be good enough for more general use, though I've refrained for the moment from applying it to fix what wasn't broken in other drivers. (It wasn't really broken here either, but...)

**Comment by cuavas** [comment]
Get rid of the default value for the debugger access constructor parameter and I'll merge it.

**Comment by ajrhacker** [comment]
That's fair enough. That value would only have to be always true in the debug memory access routines themselves.

**Pull request merged**
