### PR TITLE
Slot options list

### PR DESCRIPTION
**Pull request by goldnchild**
This is to add a function to luaengine that would return a string of the current slot options.

For example, you can ask for the list of options that are specified:

[MAME]> print(manager:machine():slot_options_list())
-sl1 parallel
-sl1:parallel:prn ap2000
-gameio joy

Or you can send it a TRUE value to get the full list of options:

[MAME]> print(manager:machine():slot_options_list(true))
-sl1 parallel
-sl1:parallel:prn ap2000
-sl2 ""
-sl3 ""
-sl4 mockingboard
-sl5 ""
-sl6 diskiing
-sl6:diskiing:0 525
-sl6:diskiing:1 525
-sl7 ""
-aux ext80
-gameio joy

You can also send a parameter that will be the delimiter between options like a space instead of the default, a "\n".

[MAME]> print(manager:machine():slot_options_list(true," "))
-sl1 parallel -sl1:parallel:prn ap2000 -sl2 "" -sl3 "" -sl4 mockingboard -sl5 "" -sl6 diskiing -sl6:diskiing:0 525 -sl6:diskiing:1 525 -sl7 "" -aux ext80 -gameio joy 

So if I use the UI to set the slot options, I can get the full list from the console and then use it to build a command line to invoke mame.

### CODE REVIEW

**Comment by cuavas** [comment]
To me, this seems like an awfully specific thing to be adding code for.  It sets off alarm bells to be adding code as specific as this in the Lua engine.

**Comment by rb6502** [comment]
I'd suggest having a machine():slots() exposure instead that returns a table of the available slot names (or nil if no slot devices are present), and a get_slot_option() exposure where you pass a slot name and it returns the current option.  That way you could also have set_slot_option() later on.

**Comment by goldnchild** [comment]
Thanks for your feedback, I added a slots function to manager:machine() so you can get a list of all the slots:

for i,j in pairs (manager:machine().slots) do print(i,j) end
sl6:diskiing:0	sol.device_slot_interface*: 0x55845f73a2e8
sl6:diskiing:1	sol.device_slot_interface*: 0x55845555eee8
sl6	sol.device_slot_interface*: 0x55845555fa88
sl2	sol.device_slot_interface*: 0x55845eae0158
sl4	sol.device_slot_interface*: 0x7fb1d4006898
gameio	sol.device_slot_interface*: 0x55845f73a238
aux	sol.device_slot_interface*: 0x55845f73a1f8
sl7	sol.device_slot_interface*: 0x55845555ef28
sl1	sol.device_slot_interface*: 0x55845d063008
sl3	sol.device_slot_interface*: 0x7fb1d4006918
sl1:parallel:prn	sol.device_slot_interface*: 0x55845eadede8
sl5	sol.device_slot_interface*: 0x55845d2694f8

I also added a device_slot_interface_type with a few of the members visible, such as:
has_selectable_options(), fixed(), slot_name()

[MAME]>  for i,j in pairs (manager:machine().slots) do print("-"..i.."  ",j:has_selectable_options()) end
-sl6:diskiing:0  	true
...

[MAME]> for i,j in pairs (manager:machine().slots) do print("-"..i.."  ",j:fixed()) end
-sl6:diskiing:0  	false
...

I added a function called get_current_option that is pretty much the same function as in slotopt.cpp:

[MAME]> for i,j in pairs (manager:machine().slots) do print("-"..i.."  ",j:get_current_option()) end
-sl6:diskiing:0  	525
-sl6:diskiing:1  	525
-sl6  	diskiing
-sl2  	
-sl4  	mockingboard
-gameio  	joy
-aux  	ext80
-sl7  	
-sl1  	parallel
-sl3  	
-sl1:parallel:prn  	ap2000
-sl5  	

and also default_option()

[MAME]> for i,j in pairs (manager:machine().slots) do print("-"..i.."  ",j:default_option()) end
-sl6:diskiing:0  	525
-sl6:diskiing:1  	525
-sl6  	diskiing
-sl2  	nil
-sl4  	mockingboard
-gameio  	nil
-aux  	ext80
-sl7  	nil
-sl1  	nil
-sl3  	nil
-sl1:parallel:prn  	printer
-sl5  	nil

I wonder if the same thing as get_current_option can be accomplished by using the name as a lookup into the manager:machine():options().entries table:

[MAME]> for i,j in pairs (manager:machine().slots) do print("-"..i.."  ",manager:machine():options().entries[i]:value()) end
-sl6:diskiing:0  	nil
-sl6:diskiing:1  	nil
-sl6  	nil
-sl2  	nil
-sl4  	nil
-gameio  	joy
-aux  	nil
-sl7  	nil
-sl1  	parallel
-sl3  	
-sl1:parallel:prn  	ap2000
-sl5  	nil

**Comment by rb6502** [comment]
Thank you!  That's much more of a classical Lua way to expose things, and it's far more flexible.  If @cuavas has no further objections I think this is mergeable.

**Comment by cracyc** [comment]
Agreed, this looks much better.

**Review by cuavas — CHANGES_REQUESTED** [review]
Please follow the same kind of spacing as the surrounding code, and update the API documentation comments, following the format @vadosnaprimer has used.

**Comment by goldnchild** [comment]
Thanks for the comments, I will make fix the spaces and put more comments in.

I've been adding more types which will allow me to reproduce the -listoptions with code that looks like this:

If we can get a list of the options:
	device_slot_interface_type.set("option_list", [this](device_slot_interface &slot) {
			sol::table option_table = sol().create_table();
			for (const auto & option : slot.option_list())
					option_table[option.first] = &*option.second;
			return  option_table;
		});

and then add a device_type_impl_base:

	auto device_type_impl_base_type = sol().registry().create_simple_usertype<emu::detail::device_type_impl_base>("new", sol::no_constructor);
	device_type_impl_base_type.set("shortname", &emu::detail::device_type_impl_base::shortname);
	device_type_impl_base_type.set("fullname", &emu::detail::device_type_impl_base::fullname);
	sol().registry().set_usertype("device_type_impl_base", device_type_impl_base_type);

then the lua code to give you the -listoptions is just:

for a,b in pairs(manager:machine().slots) do print("OPTION "..a) for c,d in pairs(b:option_list()) do print ("     "..c.."     "..d:devtype():fullname()) end end

OPTION sl6:diskiing:1
     525     5.25" single density floppy drive
OPTION sl6:diskiing:0
     525     5.25" single density floppy drive
OPTION sl5
     scsi     Apple II SCSI Card
     memexp     Apple II Memory Expansion Card
     softcard     Microsoft SoftCard
     twarp     Applied Engineering TransWarp
     ezcgi9958     E-Z Color Graphics Interface (TMS9958)
     sam     Don't Ask Software S.A.M.
     grapplerplus     Orange Micro Grappler+ Printer Interface
     sider1     First Class Peripherals Sider 1 SASI Card
     byte8251     BYTE Serial Interface (8251 based)
     applesurance     Applesurance Diagnostic Controller
     diskiiiwm     Apple Disk II IWM controller
etc..

It's not quite ready yet, I will continue to work on it.

**Comment by npwoods** [comment]
By a crazy coincidence, I developed and submitted a similar PR (#7458) without awareness of this PR.

**Comment by npwoods** [comment]
Any thoughts on #7436 vs #7458?

**Comment by npwoods** [comment]
...bueller???

**Comment by rb6502** [comment]
I don't have a preference one way or the other.  I imagine #7458 is more functional, so if it solves @goldnchild 's use case we might as well go with it.  @cuavas is of course the final arbiter though.

**Comment by cuavas** [comment]
@goldnchild can you please see if there’s anything you see as important functionality lacking in #7458?

**Comment by cuavas** [comment]
#7458 should allow this functionality to be implemented.  The Lua code in master has now diverged a long way from this.

**Pull request closed without merging**
