### PR TITLE
new NOT WORKING

### PR DESCRIPTION
**Pull request by DavidHaywood**
D-CAT16 (Mega Drive handheld) [Team Europe]

this was dumped ages ago, doesn't boot as-is, maybe custom enhanced hw like the NES clones, maybe just custom banking.

### CODE REVIEW

**Comment by felipesanches** [comment]
Hey!!!

I do have some MAME-based emulation code that implements some of the custom video hw in this handheld genesis variant!

Take a look at https://github.com/felipesanches/mame/commit/f269482f79a45bf9a9ad18de29052e9bcc43d07c

and also https://www.youtube.com/watch?v=snLWzKMR0Us

**Comment by felipesanches** [comment]
This also seems to be the same hardware, or similar hardware to what is being used in TecToy's newest Genesis console release this year.

**Comment by felipesanches** [comment]
https://web.archive.org/web/20170624192520/https://www.tectoy.com.br/pre-venda-mega-drive-edicao-limitada/p/995040461825

**Comment by DavidHaywood** [comment]
can you update your code to current and create a pull request for it?

**Comment by felipesanches** [comment]
yeah, sure

**Comment by felipesanches** [comment]
I'm not sure how fast I'll be, but I'll let you know once I have something good to merge. Thanks, Haze!

**Comment by felipesanches** [comment]
Also, the custom video hw details are not really completely figured out yet... so I do not have something ready for merge nowadays, even if I make it build agains latest master. That would require further investigation.

**Comment by felipesanches** [comment]
@DavidHaywood I would be grateful if you could extract the relevant stuff from my branch. I'm not able to do this quickly because I've been deeply focused on another emulation project for the last few weeks. I don't want to lose my focus at this moment. Please consider that branch as my current contribution to the  understanding of this custom video device.

**Comment by felipesanches** [comment]
I've also published a long thread with technical info about it here: https://forum.fiozera.com.br/t/engenharia-reversa-do-mega-drive-portatil-da-tectoy/38 (you'll probably want to use Google Translate for that one, though)

**Pull request merged**
