### PR TITLE
emumem: Remove endianness template parameter from handler_entry_read,…

### PR DESCRIPTION
**Pull request by ajrhacker**
… handler_entry_write and closely related classes. This appears to substantially reduce compilation time and binary size without too much impact on critical paths.

### CODE REVIEW

**Comment by cuavas** [comment]
So you say “without too much impact on critical paths” – which critical paths does it affect?  Handler installation?  Handler lookups?  Address space accesses?

**Comment by cuavas** [comment]
Also, there seem to be a lot of knock-on changes from the change to the template parameters.  Where should one look to see the actual meat of the change, so see how it works before and after?

**Comment by ajrhacker** [comment]
Actually the only critical-path parts really touched by this are probably `handler_entry_read_units<Width, AddrShift, Endian>::read` and `handler_entry_write_units<Width, AddrShift, Endian>::write`, which no longer need a branch on descriptor endianness for the downcast. (Using the member variable there in the first place instead of the template parameter, which would allow the branch to be optimized out, seemed a bit dumb.) The other instances of where the endianness now needs to be fetched from the address space are practically all in constructors, which probably don't get called too often except in drivers where the memory map is regularly rewritten (e.g. segas16b.cpp); even then the performance impact probably isn't huge.

A lot of the "knock-on" code churn is caused by simply combining explicit template specializations that had to be provided with ENDIANNESS_LITTLE and then again with ENDIANNESS_BIG for classes that didn't need to make much of a distinction between the two. This is a large part of the reduction in compiled file size.

**Comment by galibert** [comment]
I don't see any problems with that PR.  I wonder, should we add another layer to address_space_specific to have one Endian-less with the installer stuff, and one with Endian deriving from it with the endian-dependant memory accessors?  That could help compile time and binary size too.

**Pull request merged**
