### PR TITLE
Add new Brazilian CoCo clones (Prológica CP400 Color II and Codimex CD6809)

### PR DESCRIPTION
**Pull request by felipesanches**

### CODE REVIEW

**Comment by rb6502** [comment]
One question: are the cd6809_83 and _84 different hardware or just different ROMs?  If it's just ROMs, it should use the BIOS facility instead of having two separate drivers.

**Comment by felipesanches** [comment]
I don't know. I only had access to the ROMs, but not to the hardware. But I would assume that the only difference is in the ROMs.

I considered using the BIOS facility, but then I wondered what happens with the driver metadata. How does one convey the year of each ROM when the driver itself has a single year metadata ?

**Comment by felipesanches** [comment]
I've just fixed the recent code conflict and also addressed the issue pointed out by @rb6502 
(I've used the BIOS macros to declare multiple ROM-sets for the same PCB on the CD6809 driver).

I feel that this is probably good enough now to be merged.

cheers,
Felipe

**Comment by felipesanches** [comment]
thanks!

**Pull request merged**
