### PR TITLE
Minor changes to various drivers

### PR DESCRIPTION
**Pull request by shattered**

### CODE REVIEW

**Comment by angelosa** [comment]
If `superga2.cpp` is an Arcade game shouldn't it have the `GAME` macro in the metadata?

**Comment by cuavas** [comment]
Yeah, it probably should.  It’s dedicated game hardware.

**Comment by Tafoid** [comment]
Curious about ec1847 - it lost resolution (720x350 vs 640x200) and it's green tint.  I presume it is expected?

ec1847-diff

**Comment by shattered** [comment]
> If `superga2.cpp` `kuzmich` is an Arcade game shouldn't it have the `GAME` macro in the metadata?

Yeah, I'll change it in next PR.

> Curious about ec1847 - it lost resolution (720x350 vs 640x200) and its green tint. I presume it is expected?

Yes, this is expected - video adapter switched from MDA to CGA.

**Pull request merged**
