### PR TITLE
First pass at Apple IIgs software list overhaul

### PR DESCRIPTION
**Pull request by Firehawke**
New working software list additions (apple2gs_flop_orig.xml)
------------------------------------------------------------

Balance of Power: The 1990 Edition (IIgs) [4am, Firehawke]
Bridge 6.0 (Version 2.49B) (IIgs) [4am, Firehawke]
Questron II (Version 1.1) (IIgs) [4am, Firehawke]
Reach for the Stars (IIgs) [4am, Firehawke]
Roadwar 2000 (IIgs) [4am, Firehawke]
Superstar Ice Hockey (IIgs) [4am, Firehawke]
Life and Death (IIgs) [4am, Firehawke]
Tetris (IIgs) [4am, Firehawke]
LaserForce (IIgs) [4am, Firehawke]
Arkanoid II: Revenge of Doh (IIgs) [4am, Firehawke]
Bubble Ghost (IIgs) [4am, Firehawke]
Déjà Vu (IIgs) [4am, Firehawke]
Hacker II (IIgs) [4am, Firehawke]
Destroyer (IIgs) [4am, Firehawke]
GBA Championship Basketball (IIgs) [4am, Firehawke]
Jigsaw (IIgs) [4am, Firehawke]
Mini-Putt (IIgs) [4am, Firehawke]
Omega (IIgs) [4am, Firehawke]
Photonix (Version 1.46) (IIgs) [4am, Firehawke]
Silpheed (IIgs) [4am, Firehawke]
Space Quest (IIgs) [4am, Firehawke]
The Third Courier (IIgs) [4am, Firehawke]
War in Middle Earth (IIgs) [4am, Firehawke]
Where in the World is Carmen Sandiego? (IIgs) [4am, Firehawke]
Windwalker (IIgs) [4am, Firehawke]
Warlock (IIgs) [4am, Firehawke]
Winter Games (IIgs) [4am, Firehawke]
Shanghai (IIgs) [4am, Firehawke]
Police Quest (IIgs) [4am, Firehawke]
Dragon Wars (IIgs) [4am, Firehawke]
Monte Carlo (IIgs) [4am, Firehawke]
Sub Battle Simulator (IIgs) [4am, Firehawke]
John Elway's Quarterback (IIgs) [4am, Firehawke]
Space Quest II (IIgs) [4am, Firehawke]
King's Quest III (IIgs) [4am, Firehawke]
Great Western Shootout (IIgs) [4am, Firehawke]
Leisure Suit Larry in the Land of the Lounge Lizards (IIgs) [4am, Firehawke]
The Black Cauldron (IIgs) [4am, Firehawke]
The King of Chicago (IIgs) [4am, Firehawke]
King's Quest IV: The Perils of Rosella (IIgs) [4am, Firehawke]

### CODE REVIEW

**Comment by Firehawke** [comment]
This is the first shot at splitting out the IIgs software similarly to how the existing Apple software lists are.

I don't _anticipate_ any major issues, but that doesn't mean there aren't any. Let me know if anything needs adjusting. It passes -valid at least.

**Comment by rb6502** [comment]
I know Vas has opinions, but I strongly object to mixing in IIgs and 3.5" disks with 5.25".  That violates *all* of the rules of least surprise for Apple II users at once.

**Comment by cuavas** [comment]
Why does it violate the rule of least surprise?  We don’t separate 5.25" and 3.5" into separate lists for the PC software lists, and it doesn’t seen to cause a problem.  We have the interface thing on the software parts so the correct type of drive will be selected.  What purpose does separating them serve?

**Comment by cuavas** [comment]
And FWIW @rb6502 this change seems to get it closer to what you want anyway – this moves the 16-bit IIgs software out of the 8-bit Apple II software list into its own list.  That’s what I requested in the first place.

(Incidentally, all the 16-bit IIgs software we have so far is on 3.5" disks, so there are no 5.25" disks mixed into the IIgs list by this PR anyway.  Hypothetically speaking though, if/when 5.25" 16-bit IIgs or 3.5" IIc+ software shows up, I’d rather see it go in the same lists as the other software, not multiply the number of lists by media types.)

**Comment by ajrhacker** [comment]
> We don’t separate 5.25" and 3.5" into separate lists for the PC software lists, and it doesn’t seen to cause a problem.

There is still a problem in that a 3.5" drive configured by default cannot load 5.25" software items, and vice versa. Unfortunately, it's not one that can be solved just by separating software lists.

In principle, however, I don't see why the IIgs *shouldn't* have a separate set of software lists. With the separation, however, appending "(IIgs)" to the names of the items and "2gs" to their shortnames becomes less justifiable.

**Comment by Firehawke** [comment]
Well, once we actually have a consensus on how this stuff should be handled (same list or different list) I can adjust all the naming again. Right now I'm just in a holding pattern until then.

**Comment by Firehawke** [comment]
@rb6502 Per Vas's statement, the intention (has always been, in fact) is to split GS off to its own list in this. I'll also be removing the (IIgs) tags as part of the full process. Do you still have any complaints that I should address as part of this? If so, let me know and I'll be more than willing to take steps to address those concerns.

**Comment by cuavas** [comment]
Indentation is off BTW – the opening tags for the `software` elements are at the left margin, not aligned with the closing tags.

**Comment by rb6502** [comment]
Games that are arcade ports normally get the same short name as the arcade game.  For instance, the 8-bit Apple II version of Marble Madness is "marble" to match the System 1 arcade, so the IIgs version should also be "marble".  Arkanoid II should be "arknoid2" rather than "ark22gs", and so on.  (A case could be made for "arknoid2u" since it's based on the US version of Arkanoid II which has different levels, but I think that detail is unnecessary here since there's only one IIgs version).

Also, it's not necessary to append "gs" to the ends of the short names, and it messes up some opportunities to keep things 8.3 (I know that's not a requirement now, but where things can fit, it's still nice to do).

**Comment by Firehawke** [comment]
Not surprised at the indent issue, I have periodic problems with my editor deciding that the indent is completely wrong and I'm not sure what's triggering it. I'll re-indent it before my next set.

I'll also dig into renaming stuff appropriately. I'm going to assume that most arcade ports will be based on US/EU based on the port houses for GS/IBM/etc being mostly western. (e.g. NovaLogic and Taito)

I'll try to have something to show by the end of tonight, though there's no rush on Q&Aing.

**Comment by Firehawke** [comment]
Okay, this SHOULD have fixed the tabs as well. I've noticed a few preexisting (mostly *_misc) sets are showing with metadata with double spaces; "Super Puzzle", "B-1 Bomber", etc. I'll have to make a note to clean those up as well before doing the final push of this.

**Comment by rb6502** [comment]
Everything looks reasonable now except the two sets I specifically made examples of.  "marble" and "arknoid2", please.

Photonix and Photonix II each only had one release as far as I'm aware, so 1.46 can just be "photonix".

**Comment by cuavas** [comment]
>Photonix and Photonix II each only had one release as far as I'm aware, so 1.46 can just be "photonix".

Further to this, in general the latest version doesn’t need a version suffix in the shortname.

**Comment by Firehawke** [comment]
> Everything looks reasonable now except the two sets I specifically made examples of. "marble" and "arknoid2", please.

Sorry, typo on "marble" that I missed. Thanks for catching that.

> Arkanoid II should be "arknoid2" rather than "ark22gs", and so on. (A case could be made for "arknoid2u" since it's based on the US version of Arkanoid II which has different levels, but I think that detail is unnecessary here since there's only one IIgs version).

Changed it to straight "arknoid2"

> Photonix and Photonix II each only had one release as far as I'm aware, so 1.46 can just be "photonix".

Reasonable if the assumption is correct, and I have no reason to doubt that assumption, so adjusted.

**Pull request merged**
