### PR TITLE
Vme 2

### PR DESCRIPTION
**Pull request by JoakimLarsson**
One further step into VME land. I have some design issues around trampolines to iron out before taking the next step with the miniforce driver.

### CODE REVIEW

**Comment by JoakimLarsson** [comment]
An overview of the three different models to hook up a VME bus that I am working on
[VMEinMAME.pdf](https://github.com/mamedev/mame/files/811309/VMEinMAME.pdf)

**Comment by JoakimLarsson** [comment]
I got zero input on this so I remove the RP and get it working first, I just hate hearing afterwards that I have done something wrong and need to refactor it all for some reason but I guess I am close enough to be ignored for now. In fact I have some new ideas that I want to try too.

**Comment by galibert** [comment]
Any answer I have on "how it should be done" relies on nontrivial
infrastructure we currently do not have in Mame, and won't any time soon
afaict.  No way I'll tell someone to wait on something that may or may not
exist one day.  What you propose, which is in some aspects not far from
what I did for pci, looks sane given the codebase we currently have.  Go
for it.

  OG.

**Comment by JoakimLarsson** [comment]
Thanks, that's all I wanted hear, I will not/do not want to abuse the architecture so the code can't be migrated later on. Waiting for someone else to do the heavy lifting is never an option. :)

I am looking into a fourth model where a slave will be able to install handlers directly into the slot1 master, obviously also without an active bus emulation and intended to work better for high bus traffic apps. I am running out of time for the next release but will aim for one further down the road.

**Pull request closed without merging**
