### PR TITLE
Significant updates to the CD-i driver

### PR DESCRIPTION
**Pull request by MooglyGuy**
- Significantly cleaned up MCD212 code and brought it into modern standards.
- Fixed region handling and improved performance in the MCD212 video device.
- Added support for CDDA decoding and heuristics for handling CD-i Ready discs to the CDIC device.

### CODE REVIEW

**Comment by MooglyGuy** [comment]
The CI failure doesn't seem to be my fault:

```../../../../../src/osd/modules/debugger/win/consolewininfo.cpp: In member function 'virtual void consolewin_info::update_menu()':
../../../../../src/osd/modules/debugger/win/consolewininfo.cpp:227:49: error: invalid use of incomplete type 'const class software_part'
  227 |                                         if (!tmp->name().empty())
      |                                                 ^~
In file included from ../../../../../src/emu/emucore.h:44,
                 from ../../../../../src/emu/emu.h:30,
                 from ../../../../../src/osd/modules/debugger/win/consolewininfo.cpp:9:
../../../../../src/emu/emufwd.h:225:7: note: forward declaration of 'class software_part'
  225 | class software_part;
      |       ^~~~~~~~~~~~~
../../../../../src/osd/modules/debugger/win/consolewininfo.cpp:230:68: error: invalid use of incomplete type 'const class software_part'
  230 |                                                 filename.append(tmp->name());
      |                                                                    ^~
In file included from ../../../../../src/emu/emucore.h:44,
                 from ../../../../../src/emu/emu.h:30,
                 from ../../../../../src/osd/modules/debugger/win/consolewininfo.cpp:9:
../../../../../src/emu/emufwd.h:225:7: note: forward declaration of 'class software_part'
  225 | class software_part;
      |       ^~~~~~~~~~~~~
../../../../../src/osd/modules/debugger/win/consolewininfo.cpp: In member function 'bool consolewin_info::get_softlist_info(device_image_interface*)':
../../../../../src/osd/modules/debugger/win/consolewininfo.cpp:566:45: error: 'software_list_device_enumerator' was not declared in this scope; did you mean 'state_interface_enumerator'?```

**Comment by cuavas** [comment]
Yeah, that’s already fixed on master – don’t sweat it if only Windows is failing.

**Comment by DavidHaywood** [comment]
Alien Gate (Europe) from the current redump set is a regular non cdi-ready image, it has 3 tracks
Alien Gate (USA) and Alien Gate (USA) (Rev 1) from the same set are cdi-ready images, they have 2 tracks.

after this change the 3-track Europe version attempts to play the data track 1 as audio, it doesn't sound good.

**Comment by MooglyGuy** [comment]
@DavidHaywood Thanks for the report. Can I find the 3-track version at the expected IA location?

**Comment by DavidHaywood** [comment]
I believe so, at least that's where I found it following some hints that were left.

**Pull request merged**
