### PR TITLE
docs/source/initialsetup/compilingmame.rst: updated compilation packa…

### PR DESCRIPTION
**Pull request by goldnchild**
…ge information for missing qt5-default

The compiling instructions don't mention the missing qt5-default metapackage on more recent editions of debian/ubuntu.

This addition gives a workaround, basically installing the dependencies that were installed as part of the qt5-default metapackage:

https://packages.ubuntu.com/focal/qt5-default

### CODE REVIEW

**Comment by cuavas** [comment]
This just complicates it. If the individual packages are available on older distros, just expand it in the command.

**Comment by goldnchild** [comment]
Ok, added the expansion to the end of the command line.

**Comment by goldnchild** [comment]
Or do you think it makes sense to keep the "old" command line for older distros and have a newer command line for newer distros.

**Comment by cuavas** [comment]
Is Python 3 available by default anyway?  If it can be assumed to be installed by default, it can be omitted.

**Pull request merged**
