### PR TITLE
Final batch of Apple disks for July 2021

### PR DESCRIPTION
**Pull request by Firehawke**
New working software list additions (apple2_flop_orig.xml)
----------------------------------------------------------

Stickybear Math 2 (1988 Re-release) (800K 3.5") [4am, Firehawke]
Stickybear Opposites (1989 Re-release) (800K 3.5") [4am, Firehawke]
Stickybear Town Builder (1988 Re-release) (800K 3.5") [4am, Firehawke]
Stickybear Typing (1988 Re-release) (800K 3.5") [4am, Firehawke]
Spelling Rules (1989 Re-release) (800K 3.5") [4am, Firehawke]
Sentence Fun (1989 Re-release) (800K 3.5") [4am, Firehawke]
Alge-Blaster Plus! (Version 1.0) (800K 3.5") [4am, Firehawke]
Mickey's Crossword Puzzle Maker (800K 3.5") [4am, Firehawke]

### CODE REVIEW

**Comment by Firehawke** [comment]
Cancelled CI because there's no code changes and it's a waste of CI time.
Should have left the XML Validation/validate running, though. I'll make sure not to kill that one next time.

**Comment by cuavas** [comment]
Remember that the full build does additional validation checks for software lists that require MAME to be built.

**Comment by Firehawke** [comment]
Yeah, probably the same ones I'm doing locally (xmllint and -valid) before I commit, but I'll let the whole thing run in the future if that's what you want.

**Comment by cuavas** [comment]
The Linux workflow also uses minimaws to do an ORM check, which can catch additional errors with `info`, `feature`, etc.

**Pull request merged**
