### PR TITLE
Sound reference input

### PR DESCRIPTION
**Pull request by ajrhacker**
New way to provide DAC reference inputs (nw)
- Introduce MCFG_SOUND_REFERENCE_INPUT to provide fixed inputs through the resampler, eliminating the need for the "voltage regulator" device
- Replace memset use in sound.cpp with std::fill

This was my third implementation of this concept. The previous two involved attaching sound streams to the dummy device (which required giving it device_sound_interface and other modifications).

### CODE REVIEW

**Comment by happppp** [comment]
Good to get rid of the '5 volt for everyone' device.
Is the sound output volume identical to before?

**Comment by ajrhacker** [comment]
There seems to be no *meaningful* difference in sound output. I did a comparison on hiryuken (lasting into the first few seconds of the attract demo), and the only difference occurred early on when no actual sample was being played. (MAME doesn't have hardware-accurate emulation of the Hiryu no Ken DAC, but that's another matter entirely.)

**Comment by smf-** [comment]
I don't particularly like either implementation.

What I had in mind was to de-specialise sound streams, so they were used for all analogue handling. For example analogue controls would be pointed at an ADC. Then when we have sound inputs, we can use the same ADC for analogue controls and sound inputs.

I'd also like to improve our documentation of power and be able to emulate systems where parts can be powered down.

The conclusion I came to was that MCFG isn't really up to the task and we need something a bit more modern, maybe a bit like a netlist for endpoint hookups but done in code. Then use the same method for devcb, eventually allowing the concept of digital streams so that UARTS aren't forced to sync the entire emulation on every clock tick & only when a sync is actually required.

**Comment by ajrhacker** [comment]
> What I had in mind was to de-specialise sound streams, so they were used for all analogue handling. For example analogue controls would be pointed at an ADC. Then when we have sound inputs, we can use the same ADC for analogue controls and sound inputs.

Being able to process analog inputs and audio outputs would make it more convenient to implement the CD4051 analog multiplexer. Allowing sound streams as inputs would also help in emulating things such as audio digitizer boards. That's already quite a bit beyond the scope of this PR, though.

> I'd also like to improve our documentation of power and be able to emulate systems where parts can be powered down.

I don't think it would be particularly important to emulate system power as an analog input, though that clearly would need to be simulated in some cases. The more important concern is systems which need to receive a power failure interrupt in order to perform NVRAM housekeeping functions; I think this may include all of the Gaelco DS5002FPs as well as the Amusco poker games.

> The conclusion I came to was that MCFG isn't really up to the task and we need something a bit more modern, maybe a bit like a netlist for endpoint hookups but done in code. Then use the same method for devcb, eventually allowing the concept of digital streams so that UARTS aren't forced to sync the entire emulation on every clock tick & only when a sync is actually required.

I'd call that getting way ahead of yourself.

**Comment by ajrhacker** [comment]
Since there appear to be no serious objections, I'll launch this now rather than wait for another new driver that needs to be updated to work with it. The projected analog input stream emulation shouldn't need a dummy "voltage regulator" device either, anyway.

**Pull request merged**
