### PR TITLE
dumped megacd2 euro 2.11 bios

### PR DESCRIPTION
**Pull request by TwistedTom**
From late UK machine with the smaller Sony-made pcb.
Note, boot screen shows v2.00 (same as US v2.11 bios)

### CODE REVIEW

**Comment by Tafoid** [comment]
I know there is a comment for the machine bioses have a comment before the ROM_START:
`/* All confirmed good dump by ElBarto */`

I presume this one isn't?  Where was this sourced and is there a person to credit for it?

**Comment by TwistedTom** [comment]
Dumped it myself, i'll update the comments...

**Comment by cuavas** [comment]
Is the newer board logically identical to the older one?

**Comment by TwistedTom** [comment]
Can't say for sure, the Sony-made board is a lot different to look at, smaller, some components are moved to a sub board under the cd mech.  There's an old Sega document (service manual supplement) that says the Sony bios is backwards compatible with the old (Funai-made) board but not vice-versa. Can't confirm that as I don't have a Funai MCD2 to test this new bios on, perhaps someone else can try? (all recent flash carts, Everdrive etc. have ability to use different mcd biod)
The machine is model MK-4102**A**-50, they do seem a fair bit less common here in UK, can't speak for rest of Europe.

**Comment by 7ank0v1c** [comment]
Hey guys, I know I am picking this up quite some time after initial post, but I am wondering on the methods used to dump these bioses here?

**Comment by TwistedTom** [comment]
Best to remove the chip and read it with a device programmer, unfortunately that means unsoldering as they're not usually socketed. There are various methods to dump the rom in-system, but none give a good dump, can't remember exactly why, something to do with a register being mapped over a bios address (vector table?) meaning you get one bad byte from that instead of the bios (and therefore not 100% good dump).

**Comment by 7ank0v1c** [comment]
@TwistedTom Ah okay, thanks. I never did this before. Would something like this work? https://www.ebay.co.uk/itm/294425140647?mkcid=16&mkevt=1&mkrid=711-127632-2357-0&ssspo=t7VbWmHDTC2&sssrc=2349624&ssuid=R8M4fcyhR32&var=&widget_ver=artemis&media=COPY

And also is there any link that could help me with this process?

**Comment by TwistedTom** [comment]
Not sure what the device in that link supports, but Mega-CD bios is 40-pin 16-bit rom, the eprom equivalent is a 27c1024 so anything that does those will read it ok.

**Pull request merged**
