### PR TITLE
subsino/subsino.cpp: Partially dumped and added a new gambling game

### PR DESCRIPTION
**Pull request by clawgrip**
New NOT_WORKING machine
---------------------------------
Seven Land [Taksangs]

### CODE REVIEW

**Comment by ajrhacker** [comment]
A PCB photo I saved from an auction listing shows four more EPROMs (probably graphics-related) at U27-U30, plus a HMC HM86171-80 RAMDAC at U26.

**Comment by clawgrip** [comment]
> A PCB photo I saved from an auction listing shows four more EPROMs (probably graphics-related) at U27-U30, plus a HMC HM86171-80 RAMDAC at U26.

You're right!! Four A278308! I'll add placeholders, thanks!!!

**Comment by Osso13** [comment]
According to the person who added it to the Undumped Wiki, this is a Super Treasure Island bootleg.
Source: https://undumped.miraheze.org/wiki/Seven_Land_(no_copyright)

**Comment by clawgrip** [comment]
Thanks!! Marked as a clone of 'stbsub' by now.

**Comment by cuavas** [comment]
Sadly, this might be one of those things where the other ROMs never turn up.

**Pull request merged**
