### PR TITLE
Updated PT-BR Translation File.

### PR DESCRIPTION
**Pull request by Ashura-X**
[strings_PT-BR.zip](https://github.com/mamedev/mame/files/1183527/strings_PT-BR.zip)

### CODE REVIEW

**Comment by happppp** [comment]
There's nothing to merge. Is this your 1st time creating a pull request? Here's the github help page about them: https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by Ashura-X** [comment]
Just added only the file on a .zip

**Comment by happppp** [comment]
Right, you created an empty "Translation." file, and the real contents in a comment instead. It doesn't work like that. If you're new to github and pull requests, please do some reading on the topic and try again :)

**Comment by happppp** [comment]
Almost there. I believe the file in question is "/language/Portuguese_Brazil/strings.po".
Your PR at the moment is for "/Translation."

**Comment by Ashura-X** [comment]
Failed to atempt it.

**Pull request closed without merging**
