### PR TITLE
Fixed writes to decrypted opcode memory

### PR DESCRIPTION
**Pull request by PugsyMAME**
Fixes problem in the debugger and the cheat engine as currently the writes to opcode memory are not handled correctly, so separated EXPSPACE_RAMWRITE and EXPSPACE_OPCODE case statements to allow opcode writes to access the correct memory.

Example:
In flicky this will now disable cat collisions with the main sprite:
maincpu.ob@3ac6=c3

### CODE REVIEW

**Comment by galibert** [comment]
Reverted.  Pugsy, you broke all the side effect disable handling.  The
disable is active until the returned object is destroyed which, if you put
it alone in an if, is immediatly.  Things were written that way for a
reason.

  OG.

**Comment by PugsyMAME** [comment]
Sorry, didn't realise. I've redone the changes (new PR) and kept the side effect handling the same as it was originally I hope - annoyingly it's identical to the code I used in the first place but I thought by putting the side effect handling in it's own if statement I was helping clean up the code. Lesson learnt...hopefully.

**Comment by ajrhacker** [comment]
Sorry about merging this too quickly, OG. Clearly I should have thought
about this more, or at least have allowed time for you to take a look at it.

AJR

**Comment by galibert** [comment]
As long as it's caught before release, it's not a real problem.

  OG.

**Pull request merged**
