### PR TITLE
Lots of misc. softwarelist changes

### PR DESCRIPTION
**Pull request by einstein95**
Luckily not including the nes or snes_bspack ones...

### CODE REVIEW

**Comment by einstein95** [comment]
Oh damn it, forgot to validate.

**Comment by etabeta78** [comment]
First of all, thanks a lot for the contribution (and for the hard work that
has been done at your end to prepare such a massive submission!)

A few remarks however
I don't agree adding the Jpn flags to the games in nes_* sublists. Those
can be only used in connection with a Japanese game, so that the flag is
redundant (it's as if those were games for a Jpn-only computer)
I also object with removing blank lines in gba.xml between the <info> about
pcb locations and the ones necessary for emulation: it's easier to spot the
slot device used by the game if it is separated by an empty line

Concerning other changes:
- megadriv.xml: most changes are ok, but it is not the addition of "Sega
Channel" to Game no Kandume Otokuyou: that flag is for games which where
released through Sega Channel (despite the dumps probably coming from a
later compilation) while this one is a compilation of those games which
must have been released in other format (as you can read here
http://segaretro.org/Game_no_Kanzume_Otokuyou). when/if its source is
confirmed to be a DC disc, we will mark this as "ripped from Dreamcast" but
as things stand the "Sega Channel" flag is just wrong.
- pokemini.xml: I appreciate the addition of release dates, but country
flags should remain in alphabetical order (Aus,USA)

For the rest, the changes are ok and can be accepted

   f.

**Comment by einstein95** [comment]
I've edited the files as per your suggestions. As for the nes_* sublists, that's why I removed them (and are doing so for the snes_bspack list).

**Comment by einstein95** [comment]
Hasn't been merged and some software lists are no out of date

**Pull request closed without merging**
