### PR TITLE
Adding several official firmware image versions for the Makerbot Replicator 1 3d printer.

### PR DESCRIPTION
**Pull request by felipesanches**

### CODE REVIEW

**Comment by rb6502** [comment]
Please use the bios feature to make these all one driver.

**Comment by felipesanches** [comment]
I've updated the commit to use the bios feature you suggested. Please review and consider merging it.

**Comment by RobertoFresca** [comment]
Is not your first pull request... It's just a ROM LOAD. You should know that the offsets must be lower case to be consistent with the project...

**Comment by felipesanches** [comment]
Does it look good now?

**Comment by felipesanches** [comment]
thanks :-)

**Pull request merged**
