### PR TITLE
adding ROM dump of Commodore MPS-1000 dot matrix printer

### PR DESCRIPTION
**Pull request by felipesanches**

### CODE REVIEW

**Comment by mr-t-guru** [comment]
You probably made a type with the year. Regardless of day/month order, the year should be 1986?

**Comment by felipesanches** [comment]
I have 4 EPROMs, 3 of which say 1988 in the type-written label. Only one says 1986.  The one that says 1986 also says "original" in handwritting.

The contents of the ROM, in the few last bytes, say:
MPS1000 VERS 2.2 DATE 12/06/86 <C>HWH/BEH 85/86

So, yeah... 1986.

**Comment by felipesanches** [comment]
I just ammended and pushed --force'd the commit

**Comment by felipesanches** [comment]
thanks :-)

**Pull request merged**
