### PR TITLE
cps1bl_pic.cpp: Add PIC dump to 'dinopic', 'punipic' and clones [hammy]

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
have these been verified as good? all previous boards we've seen have had these protected, meaning you only get partial dumps

**Comment by clawgrip** [comment]
No, they're not verified, we'll need some help with that.

**Comment by DavidHaywood** [comment]
well you can always send the PIC dumps to me and I can tell you if they're valid or not, I'd be surprised if all these ones that were just added are, 9 times out of 10 these things are protected so you'll only get half the data for each byte.

**Comment by clawgrip** [comment]
I'll do! Thanks!!!

**Comment by Hammy1986** [comment]
Haze looking again my dumps look like columns of bits missing and clawgrip's barek2 looks good?
Will send them to caps0ff as planned, sorry for the time wasting but got excited when *some* data appeared normally it's FF's!
If you like i can send you a copy of my new dumps in future - you are missing out with most of them now you are not in the DU.

**Comment by DavidHaywood** [comment]
barek2 looks good, no data missing (12 bits populated each each 16-bit word these PICs use a 12 bit architecture) so data will look like "xx 0x xx 0x xx 0x xx 0x xx 0x" where x is a populated value

if you're only getting some of those bits populated eg "00 0x 00 0x 00 0x" and never seeing the other bits set, then it's protected.

**Comment by Hammy1986** [comment]
In this case, mine are bad. Sorry for the time wasting. they will be sent away (along with a lot of others) to be processed soon!

**Comment by clawgrip** [comment]
Thanks a lot!
So, I'll close this PR and modify the other one for the JAMMA MegaDrives to add only the barek2 one. Is that right?

**Comment by clawgrip** [comment]
Ok, I'm closing this PR. The only confirmed good dump is now added on PR #7378 
Thanks again to everyone.

**Pull request closed without merging**
