### PR TITLE
gamegear.xml: new software list additions + fix MT 7965

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions
-----------------------------------
Argos no Juujiken (Tw, SMS mode) [smspower]
Black Belt (Tw, SMS mode) [smspower]
The Cyber Shinobi (Tw, SMS mode) [smspower]
Doki Doki Penguin Land - Uchuu Daibouken (Tw, SMS mode) [smspower]
Double Dragon (Tw, SMS mode) [smspower]
Final Bubble Bobble (Tw, SMS mode) [smspower]
Forgotten Worlds (Tw, SMS mode) [smspower]
Great Basketball (Tw, SMS mode) [smspower]
Hokuto no Ken (Tw, SMS mode) [smspower]
Kung Fu Kid (Tw, SMS mode) [smspower]
Lord of Sword (Tw, SMS mode) [smspower]
Paperboy (Tw, SMS mode) [smspower]
Prince of Persia (Tw, SMS mode) [smspower]
Quartet (Tw, SMS mode) [smspower]
R-Type (Tw, SMS mode) [smspower]
Scramble Spirits (Tw, SMS mode) [smspower]
Secret Command (Tw, SMS mode) [smspower]
Seishun Scandal (Tw, SMS mode) [smspower]
Shadow Dancer (Tw, SMS mode) [smspower]
Shadow of the Beast (Tw, SMS mode) [smspower]
Strider (Tw, SMS mode) [smspower]
Submarine Attack (Tw, SMS mode) [smspower]
Thunder Blade (Tw, SMS mode) [smspower]

### CODE REVIEW

**Comment by ICEknigh7** [comment]
Shouldn't these be marked as bootlegs, or were they released with SEGA's permission?

**Comment by quasiscroto** [comment]
> Shouldn't these be marked as bootlegs, or were they released with SEGA's permission?

Unknown. Bock on SMS Power said, "As with Taiwanese Aaronix release, I'm not 100% ruling out the possibility that those games were actually legit licensed from Japan, but in tradition with Asian releases they sometimes use dubious naming and the name inside the program do not always match the one on the box."

**Review by cuavas — COMMENTED** [review]
Do these games actually have Japanese kana in Chinese titles?  That doesn’t make much sense.  Do they really use these English titles in the manuals or on-screen?  If not, please use Hanyu Pinyin transliteration of the Chinese titles.

**Comment by quasiscroto** [comment]
> Do these games actually have Japanese kana in Chinese titles? That doesn’t make much sense. Do they really use these English titles in the manuals or on-screen? If not, please use Hanyu Pinyin transliteration of the Chinese titles.

(TL;DR version: I'll add Pinyin to the alt_titles that are not straight-up Japanese.)

First and foremost, these dumps are all slight alterations of existing SMS dumps. On-screen titles are reflected in the description tags. The exceptions I believe are "kungfuk", which boots to the Japanese title (which I've included as alt_title as it's on the box, cart, and manual), and "secret", whose on-screen title is "Secret Commando" not "Secret Command". For descriptions I've simply followed the lead of smspower's file names. They've chosen Kung Fu Kid for the former because the dump is much closer to the SMS Kung Fu Kid dump than the Japanese Makai Retsuden dump. Secret Command appears to be named for the printed material and is likewise named so in our sms.xml (which I used for cross referencing set names and descriptions).

As for the alt_titles, they are exactly the weird mix of Japanese, English, and Chinese that appears on the printed game materials here: https://www.smspower.org/forums/18356-24TaiwaneseHungTaoHsinHTHReleases. I omitted redundant English if it was already in the main description (such as Quartet, The Cyber Shinobi, etc). Here's an allotment of boxes from the same post to give you an idea: https://www.smspower.org/forums/files/hth_releases_small_boxes_149.jpg. Note for instance the top left game. It boots to "青春スキャンダル", aka Seishun Scandal, but the box says "快打小子 Action Boy".

**Comment by Tafoid** [comment]
Going though this for addition and passes -validate/xmllint - all data appears accounted for.  Your new titles on initial commit only shows 23 titles and is missing Aerial Assault.  I can fix that when I commit but please verify that all titles you add are listed properly.

**Comment by 0kmg** [comment]
Thank you for adding Aerial Assault to the commit message. I'll redouble my effort to avoid oversights and mistakes in future PRs.

**Pull request merged**
