### PR TITLE
dectalk: fixed distortion in DTC07 DAC emulation

### PR DESCRIPTION
**Pull request by datajake1999**

### CODE REVIEW

**Comment by datajake1999** [comment]
I just implemented a hack to fix the broken DSP output.

**Comment by cracyc** [comment]
The only oscillator on the board is 20mhz.  I'm okay with a hack since there are already other in it but there should be a comment that it's wrong.

**Comment by datajake1999** [comment]
Done.

**Comment by cracyc** [comment]
The board dac is an ad7541 https://www.analog.com/media/en/technical-documentation/data-sheets/AD7541A.pdf .

**Comment by datajake1999** [comment]
I just reduced the DAC bit depth back down to 12, as it sounds more accurate when compared to actual hardware (most notably when the synth occasionally generates faint electronic beeps).

**Comment by datajake1999** [comment]
I just updated the comment that says which DAC the hardware uses, as it is now known.

**Comment by cuavas** [comment]
It’s definitely an unrealistic frequency – the TMS320C15 was rated for 25 MHz maximum.

**Pull request merged**
