### PR TITLE
Added interrupt support in DUSCC device, Force CPU30 board driver and…

### PR DESCRIPTION
**Pull request by JoakimLarsson**
… interrupt controller support in the FGA002 device. Improved LOG messages in the 68230 device

The fccpu30 is now able to boot VMEPROM with interrupt driven serial I/O.

### CODE REVIEW

**Comment by cuavas** [comment]
If you're messing with all the calls to `logerror` in a file, please remove the redundant tag from the formatting string, since `logerror` always prints device tag by itself.

**Comment by JoakimLarsson** [comment]
Intention is not to mess with logerror, is there a standard format? I redefine it as printf because there is more control in the console window than in the debugger log window, like using 'less' and do cut & paste

**Comment by galibert** [comment]
Tried -oslog?  Sends all logerror to stderr.

  OG.

**Comment by JoakimLarsson** [comment]
I'll try it OG and see if it is as useful, thx

**Pull request merged**
