### PR TITLE
samcoupe_flop.xml: Added 2 working items

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Rename "Sam Coupe" to "Sam Coupé"

New working software list additions
--------------------------------------------
Rick Dangerous [Spectrum Computing]
Street Fighter 1 [Spectrum Computing]

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
You need to explicitly qualify UTF-8 strings in C++ source code for portability.

**Comment by ArcadeShadow** [comment]
> You need to explicitly qualify UTF-8 strings in C++ source code for portability.

Please, check if the changes made are the way it must be.

**Review by ArcadeShadow — COMMENTED** [review]
Forced UTF8 encoding

**Review by cuavas — CHANGES_REQUESTED** [review]
Escaped encoded UTF-8 in strings is unreadable.  Why not qualify them as UTF-8 strings as I suggested?

**Comment by ArcadeShadow** [comment]
> Escaped encoded UTF-8 in strings is unreadable. Why not qualify them as UTF-8 strings as I suggested?

Now I think it's fixed like the way it should be.

**Pull request merged**
