### PR TITLE
Add preliminary hacky RIVA TNT support

### PR DESCRIPTION
**Pull request by MoochMcGee**
This is based off my implementation in PCem-mooch. 1280x1024x256 doesn't work there, but for some reason it works here.

What works:
Banked VESA modes up to 1280x1024x256

What doesn't work:
Linear VESA modes
Any kind of acceleration
Any kind of PCI or AGP stuff
1600x1200 (BIOS bug??? PCem shows this mode as 1856x1200)
Refresh rates (I know the fix for this, but it freezes MAME when I try it for some weird reason.)

### CODE REVIEW

**Comment by happppp** [comment]
Why did you make it a ISA device? PCI is supported by MAME core.

**Comment by cuavas** [comment]
Yeah, I'd question the value of implementing a hypothetical ISA card carrying a chip that IIRC was only sold on PCI and AGP card.

**Comment by MoochMcGee** [comment]
@happppp Well, the PC drivers don't support modernized PCI. If this were fixed, I'd be happy to port my code over. @cuavas The s3virge does the same thing. It was only ever sold as PCI, but yet it's implemented as an ISA card in MAME.

**Comment by MooglyGuy** [comment]
In that case, you should concentrate on modernizing the PC drivers first. Just because something was done wrong in MAME before doesn't mean that they should continue to be done wrong going forward.

Just to inform the rest of the developers, MoochMcGee is an alternate nickname for Alegend45.

**Comment by MoochMcGee** [comment]
You know I don't have the skills for that.

**Comment by rb6502** [comment]
We can revisit this when there are working PCI PCs in MAME.

**Pull request closed without merging**
