### PR TITLE
bus/nes: Added support for boards using the SMD133 ASIC.

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions (nes.xml)
-----------------------------------
Data East All-Star Collection [anonymous]
Mega Man 8 in 1 (PL-0006) [anonymous]
Super Games 143 in 1 (The Best Games of NES) [anonymous]

Software list items promoted to working (nes.xml)
---------------------------------------
CoolBoy 198 in 1
CoolBoy 400 in 1
CoolBoy 400 in 1 (alt, 403 games)
Game 450 in 1
Game 500 in 1
Pocket Games 150 in 1
Super Game 218 in 1 (JF2181)
Super Game 360 in 1
Super Game 402 in 1

### CODE REVIEW

**Comment by 0kmg** [comment]
A few tidbits. One, these are modern boards often with large capacities. I marked things as partially supported simply because it's infeasible for me to test hundreds of complex games per cart. Two, there are potentially another couple dozen Chinese games in the SL that use this clone chip that need reassigned to this cart type. I haven't looked into it. This is very much a WIP.

About the feature I added to the SL to support the SMD133: I chose the values "5K" and "6K" because boards that use this chip tend to have a solder pad with similar labeling. [Example PCB](https://cdn.discordapp.com/attachments/481262863114305537/665575344157360204/20200111_101709.jpg) from Metal Storm re-release.

**Comment by 0kmg** [comment]
I removed a couple things that seem to exist only as handhelds and are in another driver already. There's also mc_cb203 which seems to be another handheld. I'd remove this as well, but it doesn't look like it's preserved anywhere else yet. I've tried contacting @DavidHaywood about these and mc_pg150 here, which I believe is only a cartridge and belongs in nes.xml.

**Comment by DavidHaywood** [comment]
I haven't seen any notification elsewhere, but if there are any things you feel are in the wrong place, feel free to move them.  The NES stuff is one of those cases of "the more you think you know, the more you realise you've overlooked something" a never ending journey of discovery.

I have one or two handhelds / TV games here that are in nes.xml, where I plan on sending them to Sean to verify the dumps (make sure there are no encryptions that previous dumper stripped etc.)

Also some probably exist as both, a couple of tv units I've had featured internal cartridge slots, with a cartridge pcb glued in, but no external cart slot at all.

**Comment by DavidHaywood** [comment]
http://mamedev.emulab.it/haze/reference/rumblestation.jpg  there are dumps of this beauty for example, but I've not added them / moved them yet because I want to see if Sean can dump it (haven't opened it up yet to check the ROM type / glob type etc. though)

That one is funny because the battery compartment is glued shut with other components inside it (operates on mains only)  It's the same generic shell a number of Dreamgear and Senario units used.

**Comment by 0kmg** [comment]
Thanks. I sent you a PM on the Bannister forums, not knowing how best to contact you. No worries if you didn't see it.

Yes, the rumblestation is rumble15 in the NES softlist was my impression. I'm aware of it not belonging there, but I'm also pretty much totally unaware of what exists in MAME in the other nes vt drivers.

**Comment by DavidHaywood** [comment]
ah, haven't logged on today to check there, I'll probably end up seeing it later ;)

**Comment by 0kmg** [comment]
I suppose I could remove mc_pg150 from nes_vt369_vtunknown.cpp if you agree that it's not also somehow found in a handheld/PnP?

Otherwise, I was hoping you'd have more info than me on the provenance of some of this stuff, since I haven't been around very long. For instance, it looks like Tafoid added mc_cb203 (a Coolboy RS-17 handheld?) way back when from Team Europe. I tried looking at their blog, but it wasn't mentioned.

**Comment by DavidHaywood** [comment]
I have no solid info, there's a comment there expressing my own doubts over it being a cart or a plug and play, so if your research indicates more the former, I'm ok with it being moved.

**Comment by 0kmg** [comment]
To whomever reviews this, for reference, mc_pg150 is a cartridge according to: https://bootleggames.fandom.com/wiki/Pocket_Games_150-in-1, and so it remains in the NES softlist (and is now working).

**Pull request merged**
