### PR TITLE
handheld/hh_sm510.cpp: Add Tiger Pit-Fighter

### PR DESCRIPTION
**Pull request by algestam**
This PR adds Pit-Fighter by Tiger Electronics.

The MCU was decapped by Sean Riddle, hap has helped out with verifying the ROM and I've digitized the display and prepared the driver.

### CODE REVIEW

**Comment by happppp** [comment]
You forgot "licensed from" in the company string, but, no need, I think we should get rid of that altogether. It's weird to only add it for videogame franchises and not for movies or cartoons or comic books.

**Comment by algestam** [comment]
Thanks @hap, I'll add the license info. Getting rid of license info can be done later for all games.

**Comment by mamehaze** [comment]
I asked the same question elsewhere, but should these maybe all have "Electronic" before the name.  If you look at the units the word "Electronic" is in the top-left of almost all of them, suggesting that maybe the product is called "Electronic Pit-Fighter" (by Tiger Electronics)

**Comment by happppp** [comment]
It's ambiguous, I always thought it's for "Electronic LCD Video Game", as visible on the Tiger games box and manual.

https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2F9il9qjcy9ag51.jpg
https://static.wikia.nocookie.net/battletoads/images/6/6b/BattletoadsLCD.jpg

**Comment by happppp** [comment]
They placed the text differently on newer games.

Mortal Kombat says "Electronic LCD Video Game" on the box, and doesn't have "Electronic" on the handheld: https://retroravengames.com/products/tiger-electronics-mortal-kombat
The Shadow says "Electronic LCD Video Game" on the box, though it still has "Electronic" in the top left corner on the handheld. https://www.ebay.com/itm/203592461905
Golden Eye says "Electronic LCD Game" on the box, and has "Electronic" on the top right for some reason. https://jamesbond.fandom.com/wiki/GoldenEye_007_(handheld_LCD_game)

**Pull request merged**
