### PR TITLE
input_rawinput.cpp: Add win32 RawInput joystick provider

### PR DESCRIPTION
**Pull request by star69rem**
RawInput for joysticks supports more than four XInput gamepads, allows you to bind the Xbox Guide button to functions in MAME, and works with global inputs so that it's possible to control multiple linked devices on the same computer with gamepads regardless of window focus, eg. networked Virtua Racing setups are playable with analog controls. 

I also put in a workaround for PS4/PS5 triggers. In MAME's other joystick providers, the triggers aren't supported correctly and are treated as being in a constant state of activation. In the RawInput joystick provider, it's possible to bind MAME functions to the specific release of pressure on PS4/PS5 pad triggers.

Finally, I tried to use more Microsoft constants for usages/usage pages instead of magic numbers.

### CODE REVIEW

**Comment by star69rem** [comment]
https://i.kym-cdn.com/photos/images/facebook/000/643/028/442.jpg

**Comment by rb6502** [comment]
This is fine in general, but I don't think the Sony trigger workaround should be in the input provider.  @cuavas, any input (ha) on that?

**Comment by cuavas** [comment]
No, it isn’t fine:
* The code is borderline unreadable
* If we’re going to do HID report parsing, it needs to be done in a way that’s usable cross-platform for things other than joysticks – we’ll eventually want to be able to use HID on macOS to get around SDL limitations, and for keyboard/mouse on Windows to get around all the issues caused by RawInput emulating a PS/2 keyboard and mouse (limitation of five mouse buttons, no key-up events for various keys on Japanese keyboard, weird NumLock behaviour, etc.)
* There are better ways to get HID reports on Windows than using RawInput – RawInput is a dead end

**Comment by star69rem** [comment]
> No, it isn’t fine:
> 
>     * The code is borderline unreadable
> 
>     * If we’re going to do HID report parsing, it needs to be done in a way that’s usable cross-platform for things other than joysticks – we’ll eventually want to be able to use HID on macOS to get around SDL limitations, and for keyboard/mouse on Windows to get around all the issues caused by RawInput emulating a PS/2 keyboard and mouse (limitation of five mouse buttons, no key-up events for various keys on Japanese keyboard, weird NumLock behaviour, etc.)
> 
>     * There are better ways to get HID reports on Windows than using RawInput – RawInput is a dead end

XInput and DirectInput are literally wrappers around RawInput and they're in MAME, so I don't see how it's a "dead end." The only thing you get out of the former two is easier rumble support, but that doesn't seem to be on the table for MAME anyway, so it's a moot point, right? You're already stuck with RawInput for keyboard/mice/lightgun support anyway. We could straight up remove both XInput and DirectInput since they give you nothing RawInput doesn't do, eliminating hundreds of lines of OSD code.

I'll gladly rewrite the code to make it more readable unless you're just refusing to accept an objective improvement for users. Please let me know so we don't have to waste any more of each other's time. The bottom line is that you basically can't play linked Virtua Racing on a single machine today because of the input situation.

**Comment by star69rem** [comment]
> This is fine in general, but I don't think the Sony trigger workaround should be in the input provider. @cuavas, any input (ha) on that?

@rb6502 I don't know if I articulately it clearly, but as it stands today, using either DirectInput or XInput in MAME, you can't bind the PS4/5 triggers properly. I know it's a hacky workaround, but the current behavior today is basically crap.

**Comment by smf-** [comment]
I don't know if anyone has any ideas for how to do it, but I'd be
grateful if we did have it.

**Comment by star69rem** [comment]
@smf- @rb6502 @cuavas I cleaned it up a bit to get rid of the excessive nesting etc.

**Comment by star69rem** [comment]
https://i.kym-cdn.com/photos/images/facebook/000/643/028/442.jpg

**Comment by cuavas** [comment]
Given your history of insulting and harassing team members and other contributors, attempting to dox members of the emulation community, creating multiple accounts to evade bans, and general pattern of obnoxious behaviour and self-aggrandisement, I hope you understand why we don’t want to engage with you.

**Comment by star69rem** [comment]
> Given your history of insulting and harassing team members and other contributors, attempting to dox members of the emulation community, creating multiple accounts to evade bans, and general pattern of obnoxious behaviour and self-aggrandisement, I hope you understand why we don’t want to engage with you.

So I don't know what you're inhaling or injecting, but I've never harassed a team member, and I've never attempted to dox anyone in my life, so stop libeling me, you piece of trash. 

Regardless, thanks for finally having the courtesy to actually respond so I can completely write this off until someone without a unibrow takes over coordinating MAME.

**Comment by star69rem** [comment]
Oh and do me a favor and remove global inputs from MAME, too, because I added that, and you don't want to engage with me, you smarmy little cocksucker.

**Comment by happppp** [comment]
Personal insults removed, thread locked.

**Pull request closed without merging**
