### PR TITLE
Split src/emu/softlist.[cpp|h] into two modules...

### PR DESCRIPTION
**Pull request by npwoods**
- src/lib/util/softlist.[cpp|h], which just contains the softlist parsing and data structures
- src/emu/softlist_dev.[cpp|h], which contains the device and other runtime aspects

This was a very messy disentanglement, as the softlist data structures were pretty intertwined with the runtime.  I'm still not 100% satisfied with the interactions between diimage.cpp and softlist_dev.cpp; the hope is to push more of the runtime behaviors out of diimage.cpp and into softlist_dev.cpp.

### CODE REVIEW

**Comment by Robbbert** [comment]
Can this wait until after the release?

**Comment by cuavas** [comment]
At the very least, give me a chance to look this over before someone rush-merges it.

**Comment by cuavas** [comment]
The freeze is coming very soon.  This is a rather invasive, if mechanical, change.  Given the last significant change with the move to std::string in softlists actually did break things in significant ways, and the subsequent pull request changing the string utilities to use std::string has some careless breakage and oversights, I'm inclined to agree with @Robbbert and wait until after the release to merge this.

**Comment by ajrhacker** [comment]
I'm beginning to see more minuses than pluses. The structure of software lists, especially as parsed, depends heavily on core semantics and information models, and I think those dependencies could easily be increased in the future. And since XML isn't some arcane format devised for MAME, I don't think outside applications would really need access to MAME's own parsing methods.

**Comment by npwoods** [comment]
This isn't really for outside applications, as much as separating the softlist state from runtime objects like device_image_interface and software_list_device.  As it is even after this change I am still not satisfied with the interactions between softlist_dev.cpp and diimage.cpp; there is way too much softlist specific stuff in diimage.cpp and it is weird how calling device_image_interface::load() will check for a period, and if one is not present, try to reimagine a file path as a softlist.

As for dependencies on core semantics and information models, the only major dependency that exists is on the rom_entry stuff.  Arguably that is in need of cleanup as well - it is the way it is because roms have always been declared as a set of macros, and other macros were developed to walk the data structure.  The old softlist code goes through a painstaking effort to construct a data structure comparable to what is set up via those macros.  This wouldn't be necessary if the rom entry stuff was really C++-ified along the lines of input ports etc.

**Comment by ajrhacker** [comment]
You're right that rom_entry is the only explicit dependency of the existing parsed softlist format, and that it ought to be replaced some day by something that works better with C++ dynamic allocation and iteration. (I see util::software_rom_entry being a non-core class as a potential hindrance to that effort.) However, even though the tags are parsed as strings, their resolution depends heavily on the core structures of devices, image interfaces and memory regions, and one of my personal plans would involve entries referencing I/O port types, and that would really benefit from having access to enum ioport_type.

I do see some advantage in managing parsed software lists separately from devices configured for a particular machine. Maybe this patch is a step in the right general direction, but it doesn't really get there, and I don't think it's the best route to take. I think a better approach would begin with creating a device-independent class for parsed software lists, but keeping it within the core along with such machine-independent modules as drivenum.cpp and validity.cpp.

**Comment by npwoods** [comment]
I'll buy that - to me, the new location of softlist.cpp is probably the least interesting aspect of the changes I made (in fact, I asked on #mame-dev IRC where such code should go).  I agree that there is unlikely to be a need to use the softlist code in an external tool, unlike say the CHD code.

I wouldn't mind moving it back to src/emu if the separation was kept, though I would really want to penetrate further in my cleanups of diimage.cpp before doing so.  I do agree that the distinction between util::software_rom_entry and rom_entry is crappy though - with better refactoring of rom_entry the data structures could be reunified.

**Comment by etabeta78** [comment]
Unifying back rom_entry handling has been my dream for long time. Thanks
for working in this direction.

Ideally, what we would like to have added to softlist after the untangling
is the option to also pass an XML together with a software fullpath param
so to allow loading homebrew in drivers like NES or NeoGeo or C64 without
the need to manually add them to softlist (but it would also replace the
need for .RPK in TI-99 and it would probably allow for support of byuu's
MSU1 expansion for SNES).
My idea was to support something like

    "mame neogeo -cart C:\path\to\soft\mygame.zip -xml_lay custom.xml"

where custom.xml would be an xml with the exact same DTD structure as our
softlists which specifies where to load each piece inside the zip archive,
if it is a multifile archive, or where to split a .nes file into .prg &
.chr as the driver needs.
I had tried to add this to MESS in the past but I only managed to implement
(hackish-ly) the support for splitting a single file into multiple parts,
but I got stuck to handling multi-files due to the very complex archive
handling we had last yeat (and which Vas has wonderfully cleaned up
recently). RPK current support could be of help now that archive handling
is cleaner, since it supports multifiles, but I don't have much time until
September :(

    f.

**Comment by mizapf** [comment]
Totally agree with you, etabeta. I've already studied the softlist handling a bit to find out the most efficient way to replace RPK. My plan is indeed to get rid of the extra RPK and use the same functions as used in the softlist handling.

My idea, however, was to add the XML file into the cartridge ZIP. If you have two separate files (XML and ZIP) I'm afraid this makes things overly complicated. What if we have a software.xml inside the ZIP which is actually the same as e.g. the ti99_cart.xml, but with only one <software> entry that covers this cartridge? Also, one could consider a special syntax for selecting a <part> from this <software> entry.

The only issue is that the core would have to learn to load the softlist from the ZIP file.

**Comment by ajrhacker** [comment]
I actually now have a working implementation of custom softlists which can be placed inside ZIP archives, with parts selectable from the command line. (Loading softlists from ZIP files took no implementation effort at all, since emu_file handles that generically enough.) Of course it won't be in 0.176, but it goes to show that the software list device shouldn't take over software loading if the list may not even be attached to a device.

**Comment by mizapf** [comment]
@ajrhacker: That's great!
Another thing that we might consider are "instances" of cartridges. Some cartridges have NVRAM, and the NVRAM contents are saved by the name of the cartridge. It should be possible to select a particular instance with the associated NVRAM contents. 
With the ZIP file loading described here, one could probably use the ZIP file name for the NVRAM contents (so you can give different names for different instances), but for the softlist loading this should also be possible - something like "-cart minimem#1" or "-cart minimem#myprogs1".

**Comment by npwoods** [comment]
Sounds good!

Tactically, how do you want to proceed?  This pull request is ready to pulled, and separately I'm working on some changes that pull rom_entry out, eliminating the need for a dichotomy between rom_entry and software_rom_entry.

FWIW - It isn't so much that I believe that "the software list device should take over software loading", as much as the code should be a bit more cleanly factored than it is now, whatever that come to mean.

**Comment by npwoods** [comment]
A more specific example of what I'm trying to avoid:

If it were not for the check against osd_is_valid_filename_char(), I could go to the image creation window, create a new image with a softlist name (e.g. - apple2:flop1:agentusa), and instead of creating a disk image it would load the softlist.

In fact, I suspect that this is the case on Linux (I believe that osd_is_valid_filename_char(':') returns true on that platform)

**Comment by ajrhacker** [comment]
It goes without saying that #1151 is wholly incompatible with this, even though it also separates the parsing routines from the device structure. Besides introducing a new feature and keeping the parsing code within the core, it has the benefits of maintaining the parsed software list as a unique_ptr and removing the stealth include of softlist.h in emu.h that was introduced a few requests ago.

**Comment by npwoods** [comment]
I must admit that I don't care for this (as much as I like the capability itself); while the short term goal of #1137 was to separate out the softlist code from the device, my longer term intention was to disentagle softlists from the device_image_interface class in diimage.cpp.  From the perspective of minimizing the amount of softlist business logic in diimage.[cpp|h], #1151 is a step back.

device_image_interface is a base class intended to be a base class for devices like floppies, cassettes, cartridges and it should really be restricted to things common to those.  The softlist code in many ways a behavior that was grafted onto that base class.  At some level, this grafting is necessary because softlists are an opt in behavior on the part of devices (as well as owning the file handle), but my preference would be to keep that to a minimum.

I somewhat wish that the direction that we started with software_list_loader was taken further.  Get the bulk of softlist behaviors out of diimage.cpp and put them on something on software_list_loader, so that softlists get "plugged in"

**Comment by ajrhacker** [comment]
I don't think the software_list_loader class is quite the right solution for the conceptual problem. Even in its current stubby state, it and device_image_interface depend too much on each other.

**Comment by npwoods** [comment]
Can you be more specific?  While I agree that device_image_interface and software_list_loader are too coupled, some coupling is necessary only because devices declare their disposition to softlists, and I feel with more refactoring it can get better.

**Comment by mizapf** [comment]
@ajrhacker, @npwoods: Does the idea of cartridge instances make sense to you as I described above? Also, how is the file name for NVRAM determined? Within the softlist handling is the software name - in case of loading from homebrew ZIP it could be useful to take the file name instead.

**Comment by etabeta78** [comment]
Personally, I don't think it is really necessary to have variable
NVRAM/SRAM names. It is quite easy to manually duplicate the .nv file when
you need a new one, if the game does not already allow for multiple save
slot.
Notice also that save states can instead have their name configured with
the -statename option (which matches the -snapname option for snapshot
naming). The reason why the two are treated differently, in my eyes, has
always been that the NVRAM is "bundled" with the cart and thus
non-configurable; OTOH save states are something pertaining to emulation
and thus it makes sense to have it configurable.
In any case, if you add this option, you'd need to add it as well to arcade
cabinet NVRAMs, because if it fits well in one case, I don't see why it
should not in the other.

Concerning nvram names it already uses software name when loading from
fullpath (if you load C:\path\to\file\xxxx.zip, you get NVRAM either as
nvram\xxxx.nv or as nvram\xxxx\whatever_nvram_device_tag.nv ). This works
for SRAM as well (the RAM saved at machine_stop...)

my 2c
    f.

**Comment by mizapf** [comment]
@etabeta78, that is, if I had two instances of MiniMemory and store one copy as minimem1.zip and the other as minimem2.zip, could I select one specific instance as "-cart filepath/minimemN.zip" which automatically uses the minimemN.nv? This would be sufficient (although it means you cannot use the general softlist but have to use file zip loading).

**Pull request closed without merging**
