### PR TITLE
current mpu4 work + sorting (including progress to make m4andybt display correctly with existing layout)

### PR DESCRIPTION
**Pull request by DavidHaywood**
- fixes led extender strobes, allows output to be inverted

### CODE REVIEW

**Comment by DavidHaywood** [comment]
note, I've had to set
bool m_overcurrent_detect = false;

rather than true, as otherwise all origianl sets are broken, this is from the previous PR, it needs further investigation

**Comment by james-wallace-ghub** [comment]
I will recheck the overcurrent detect, it should be detecting and triggering by default, rather than not detecting, as this is Barcrest default behaviour.

If you're saying that it is not doing that, then I need to recheck matters.

**Review by cuavas — COMMENTED** [review]
Can you handle the active low LED outputs in the layouts rather than adding an extra state member for it?  I’d prefer having more of the presentation side done in the layouts if possible rather than special-casing more things in the already-convoluted driver code.

**Comment by DavidHaywood** [comment]
I don't know, the output is inverted compared to other games, but I don't know if that's because there's an inverter somewhere on certain boards, or if they've just used different 7-segment displays on some boards.

Can you invert 7-segment displays in the artwork?  I was trying to keep things compatible with the artwork we have as much as possible, unless the artwork has obvious errors, in which case I've fixed them.

**Comment by DavidHaywood** [comment]
ok, the layout now specifies if the 7seg is inverted.  I guess this makes sense, if they used different component types which inverted the signal or something.

kinda feels like we're missing a level of abstraction somewhere, but as it's mostly guesswork based on behavior, it should be ok for now.

**Comment by DavidHaywood** [comment]
@cuavas I'm done for now on this, @james-wallace-ghub  has some hopper hookup improvements to integrate once this is merged before I resume

**Pull request merged**
