### PR TITLE
marblmd2.cpp - removed /2 on clock, now runs 68k at 14Mhz like Batman + hook up EEPROM

### PR DESCRIPTION
**Pull request by DavidHaywood**
- remove divider on 68000 so that clock matches Batman
- hook up EEPROM

### CODE REVIEW

**Comment by angelosa** [comment]
fwiw coin chutes are reversed, cfr. sound test in service mode.
I think that is a common component with other Atari games?

**Comment by happppp** [comment]
Could you add a configuration param? set_inverted_coins(true/false)
Is it inverted or swapped? "inverted" makes me think ACTIVE_LOW.
For JSA III, I'd pick the most common configuration as default, not that many drivers would have to reconfigure it then.

**Comment by DavidHaywood** [comment]
That seems to be going a bit beyond what the scope of this PR was meant to be, but ok.

**Comment by Osso13** [comment]
If I understand properly what's being discussed, I added something similar here that maybe can be leveraged / improved: https://git.redump.net/mame/commit/?id=3583cce9af36c0739be83955a2456b17687c7fd5

**Comment by DavidHaywood** [comment]
yes, that is what was done

**Comment by ICEknigh7** [comment]
Somebody over at AtariAge is claiming that this board actually runs at 16Mhz, though I don't know if they're just assuming: https://atariage.com/forums/topic/246846-marble-madness-2-marble-man/page/18/?tab=comments#comment-5063417

**Pull request merged**
