### PR TITLE
Initial FAT file system support for Floptool

### PR DESCRIPTION
**Pull request by npwoods**
Current Limitations:
- Read only
- Only supports partitioned hard drives
	- Always accesses first supported partition
	- Floptool needs a way for partioning schemes to be indepenent of the file systems contained therein
- No FAT32 support
- No Long Filenames Support

### CODE REVIEW

**Comment by ajrhacker** [comment]
@galibert has suggested that this would be more useful if it included floppy disk support, since fs doesn't handle CHDs yet.

**Comment by cuavas** [comment]
Yeah, the blocker on this is that it’s doing its own CHD handling internally.  It needs to just work on top of the media abstraction that the filesystem library infrastructure provides.  Image formats and partition maps need to be handled in a different layer that isn’t done yet.

**Comment by npwoods** [comment]
I'm perfectly fine punting on things like CHD while the underlying support is not there yet (hopefully the partition code can be merged and left "dead" until the underlying support is there), but it isn't clear to me which specific floppy devices this should be hooked up to.  IRC time ;-)

**Comment by ajrhacker** [comment]
For ease of testing, you might want to also add `fs::PC_FAT` in `format_registration::add_pc_formats` in imagedev/floppy.cpp.

**Comment by npwoods** [comment]
Ok dumb question - what does that do, and what about that makes testing easier?

I've been limiting my work to floptool on the premise that core MAME doesn't integrate with the `fs` stuff yet.  I'm suspecting that premise is incorrect.

**Comment by ajrhacker** [comment]
I thought formatted image creation was already implemented in the UI. It's not quite there yet, though some hooks do exist.

**Comment by galibert** [comment]
> I thought formatted image creation was already implemented in the UI. It's not quite there yet, though some hooks do exist.

It is, but that fs is readonly and no formatting.

**Pull request merged**
