### PR TITLE
bbc: hd6845 fix, saa5050, softlists

### PR DESCRIPTION
**Pull request by Pernod70**
This also fixes the saa5050 issue with malzak, p2000t, etc.

### CODE REVIEW

**Comment by Pernod70** [comment]
Is there any way of identifying Travis issues before I push to my remote? Even though everything builds and runs fine it's a trial and error process of amending the pull request until it succeeds.

**Comment by startaq** [comment]
Well, for one you should split unrelated features into multiple pull requests. In this case, you should do one for the software list updates and floppy, and one for the mc6845 updates.

You then run "mame -validate" which will among other things point out issues with the software list xml files.

**Comment by Pernod70** [comment]
I wasn't aware of -validate, so that will definitely help. There'll be another commit in this pull to fix the softlists, so is it possible to rebase my commits even after I've pushed them to my remote?

**Comment by Tafoid** [comment]
Going though some things I noticed the softlist you added **bbc_68000_flop.xml** is attached to no driver or set.  We like to avoid adding more orphaned lists whenever possible.  Will an appropriate set be showing up to allow this image to be used or tested?

**Comment by Pernod70** [comment]
It's like the z80 and 32016 lists, they all require additional hardware emulating to test. The images are not that easy to find so wanted them included for my future emulation targets. I'll submit a pull that includes them in bbcb like the others.

**Pull request merged**
