### PR TITLE
Reworked split of Apple softlists + WOZ Feb 7 2019 (nw)

### PR DESCRIPTION
**Pull request by Firehawke**
Okay, let's try this again.

* Moved Impossible Mission to correct location in softlist
* Added 4AM original WOZ images up to Feb 7th, 2019
* Split apple2.xml into apple2_flop_clcracked.xml and apple2_flop_misc.xml
* Changes Apple 2 drivers to support the split softlists. Note there's no compatibility metadata for the older content, so we can't easily filter to the machine type there.

Remaining to be done:
* Sort the clean cracks list alphabetically
* Add 2000+ remaining 4AM clean cracks

I've gone over this PR about three times before commiting on my side just to make sure I didn't miss any major issues, including -valid checks.

### CODE REVIEW

**Comment by peterferrie** [comment]
When you get to them, Bad Dudes and Heavy Barrel are missing their
side B in his cracks, and aren't usable.

**Comment by peterferrie** [comment]
His Portal side 4 is also damaged.

**Comment by Firehawke** [comment]
> When you get to them, Bad Dudes and Heavy Barrel are missing their side B in his cracks, and aren't usable.

Yeah, that's in my notes along with Portal. The Portal I see in clcracked says "(trex crack)" so it's not his.

> Sorry, this is going to get nuked if you leave it like this. Use one tab per nesting level like the other software lists. You can adjust your editor to display this differently if you like (e.g. in vim you could use `set ts=2 sts=2 sw=2 noexpandtab` to get two spaces per indent/shift/tab and still use tabs). This is how you ended up with the 100% file conflict last time.

Okay, it SHOULD have been one tab per level. That's what I'm seeing on my side. I'm taking this to IRC.

**Comment by cuavas** [comment]
I played this on top of master and re-did the indentation, then squashed it: bba2609b7519a59552f63d3b3b6b200954025452

**Comment by cuavas** [comment]
The issue isn't that I can't re-indent the file myself, rather it's that if I do re-indent it, either immediately after applying the PR or when doing release preparations, it looks like a total file rewrite.  This messes up history and greatly increases the likelihood of conflicts if you've continued to work on the file, so I'd rather avoid having it happen.

**Pull request closed without merging**
