### PR TITLE
megadriv.xml: Minor cleanup of compatibility tags.

### PR DESCRIPTION
**Pull request by 0kmg**

### CODE REVIEW

**Comment by 0kmg** [comment]
These were spotted by very brief scripted testing of only items with compatibility tags. https://segaretro.org/Mega_Drive_region_coding looks like it is a good reference for possible further digging.

@angelosa I took the liberty of correcting booger's loading based on your earlier hint. Is collslam supposed to be supported="no"? I'll leave the EEPROM stuff to you.

**Comment by angelosa** [comment]
Please base the PR over megadrive_qa branch, not master. There’s some stuff duplicated which I’ve already sorted out (such as booger).

**Comment by 0kmg** [comment]
Hope this works? If not just take what you need. No need to credit me.

**Comment by angelosa** [comment]
Nope, you probably need to make a new PR, defining that you want to merge over my branch.

**Pull request closed without merging**
