### PR TITLE
fmtowns: adjust PCM volume

### PR DESCRIPTION
**Pull request by rzero9**
The volume of the PCM sound in the FM Towns driver has always been a bit too loud, but after the rewrite of the YM3438 core it has become even more evident, with the PCM sounds completely overpowering the FM instruments in music that uses both at the same time. The output of the RF5C68 was set to 3.00 gain, which is clearly too much, so this change sets it to 1.00, which sounds a lot closer to real hardware.

To demonstrate, here are recordings of the same track (from the game Deep) in:

- current MAME (after the FM rewrite): https://www.r-09.net/mame/deep_old.flac
- current MAME after this change: https://www.r-09.net/mame/deep_new.flac
- real hardware (original FM Towns Model 2): https://www.r-09.net/mame/deep_real.flac

The real thing seems to have some kind of lowpass filter that makes everything a lot "softer", but it should be enough to compare the volume levels.

### CODE REVIEW

**Comment by rzero9** [comment]
I just realized the CDDA sound also needs adjusting after this. I'm converting the PR to draft while I do some more testing.

**Comment by rzero9** [comment]
Done, bringing CDDA down to 0.30 keeps all three sound sources balanced reasonably close to real hardware.

**Comment by litaniast** [comment]
FM output volume is changed on latest git. Need to check with latest code

https://github.com/mamedev/mame/commit/0e0341b9b684623d49b879338e213a3c16ac3d02

**Comment by rzero9** [comment]
Any feedback about this? I've been testing all kinds of software with these changes enabled for a while, and I haven't found anything that sounds off.

**Comment by happppp** [comment]
You tested it well, so it's fine by me

**Pull request merged**
