### PR TITLE
new NOT WORKING machines (plug+play - JAKKS Pacific etc.) [Sean Riddle]

### PR DESCRIPTION
**Pull request by DavidHaywood**
new machines marked as NOT WORKING
------
Hannah Montana Pop Tour - Guitar Video Game (JAKKS Pacific TV Game) (May 16 2008) [Sean Riddle]
Robotech [Sean Riddle]
Rainbow Brite (mini-arcade) [Sean Riddle]

new NOT WORKING software list entries
------
karaokd_cart.xml: [Sean Riddle, ClawGrip]
karaokd1 - Karao Kids Songs 1 (Spain)
karaokd2 - Karao Kids Songs 2 (Spain)
origkara - Original Karaoke

- ROM was removed from karaokd2, set renamed karaokd, changed to use softlist.

### CODE REVIEW

**Comment by clawgrip** [comment]
Hi David,
 The Singing Star Karaoke manual has a Taikee logo on the footer (see pic).
I’d say all three carts are from Taikee, and Imaginarium (Spanish toy conpany) just did the regional adaptation for Spain and renamed it to Karaokids, adding also their splash screen.

9BE91535-D5D9-49A8-84C9-7C6CC765F099
A4311E5A-C8A4-4C6E-8B1C-901F0B758CB8
13271DC3-21A8-4731-8926-8D3D43296896
BC91EB26-4C1E-4CE2-9B38-887006FCBF30
EAFF7185-2056-41AC-B2D8-2FE6CACC40E8

**Comment by clawgrip** [comment]
Hi David,
The Singing Star Karaoke manual has a Taikee logo on the footer (see pic).
I’d say all three carts are from Taikee, and Imaginarium (Spanish toy conpany) just did the regional adaptation for Spain and renamed it to Karaokids, adding also their splash screen.
BFBDFFC3-8F0F-4C20-A11B-241C632C8EB9

**Comment by DavidHaywood** [comment]
alright, I've changed it to use Singing Star Karaoke as the primary name, it's a bit messy since it's a romless system, but that makes more sense.

**Comment by Tafoid** [comment]
sstarkar - spg110.cpp
Crash when launched without cart (via -str/-bench command-line)

Exception at EIP=0000000148c78410 (handler_entry_read_memory_bank<1, -1, (endianness_t)1>::read(unsigned int, unsigned short) const+0x0030): ACCESS VIOLATION

**Comment by DavidHaywood** [comment]
I've set 	m_cart->set_must_be_loaded(true);
it shouldn't be possible to run it without a cart?

**Comment by Tafoid** [comment]
This does not apply to any attempt which has -STR or -BENCH for obvious reasons.  Such delay would hang up any testing lists until some invisible interaction is done to attempt to select an image blindly.  I have since added a cart to load when the machine is queued for testing, but an empty cart slot shouldn't crash the emulator and at worse give you a black screen.

**Comment by DavidHaywood** [comment]
I'm not sure what the point of having a 'set_must_be_loaded' flag is then, if there are options that bypass it.

If you're benching something that requires a cartridge, without a cartridge inserted, at best you're going to be running code that doesn't exist anyway, which is an entirely meaningless benchmark.  Surely it should just exit and tell you that the system can't be benched without a cartridge present?

**Pull request merged**
