### PR TITLE
move sh2 / sh4 to a folder called superh

### PR DESCRIPTION
**Pull request by DavidHaywood**
the sh3 / sh4 core contains a lot of copy + pasted code from the sh2.

the family name is SuperH, so it seems more logical to place them in a folder with that name.

the basic execution engine could be shared, the diassembler could be shared (most of it is a straight copy+paste at the moment)

sh3/4 add things like fpu ops, mmu, 64-bit data bus but it should otherwise be possible to refactor and rebuild them around the existing sh2 core.

longer term this should allow leverage of the sh2 recompiler with some modifications (most of the new FPU ops in sh3/sh3 could be implemented with the UML cfunc callbacks like some of the existing SH2 maths ops still are, until somebody writes UML implementations of them)

anyway, this just gets things in place for further refactoring, no actual code changes in this commit.

### CODE REVIEW

**Comment by galibert** [comment]
RB once said sh1/2 and sh3/4 were different enough to make sharing the drc
not a good idea.  I'd like his go ahead on that patch before accepting it.

  OG.

**Comment by angelosa** [comment]
Several opcodes are identical through the cores, imho it makes sense to merge them all into some common structure.

Also don't forget that the devices used needs some merging with H8 too.

**Comment by rb6502** [comment]
It's intended as a political maneuver around my refusal to do more DRCs until he and Kale stop bullying me about the SH2 one.

**Comment by DavidHaywood** [comment]
I was talking to some of the other emu devs, and the general feeling was that they're close enough to merge and do proper c++ classes / inheritance / common execution engine etc.  I suspect they weren't done that way initially because MAME was less of a c++ project, so the copy+paste made more sense.

The SH3 is apparently closer to the SH2 than the SH4 in the first place too, they were surprised it had been built on the SH4 core.

**Comment by rb6502** [comment]
That said, I have issues with the patch itself too: "sh" should be the folder name, and it should be possible to build any combination of supported CPUs (SH1/2/3/4) just as it is with e.g. the MIPS III and other shared implementations.

**Comment by p1pkin** [comment]
@galibert sh3 is basically sh2 with MMU (not used by emulated in MAME games), and few more very minor CPU core changes.
tbh I was always wondering why sh3 was tied to SH4 core.

**Comment by DavidHaywood** [comment]
why sh, not superh?  I used superh because that seems to be the official family name

**Comment by rb6502** [comment]
SH3's peripherals and memory layout are closer to SH4 than SH2.

"sh" because it matches common usage, and we're not excessively strict on chip filenames.

**Comment by DavidHaywood** [comment]
The option to build individual SH1/SH2/SH3/SH4 will come as refactoring takes place anyway.  It's mostly ugly C macro stuff to separate the MIPS stuff anyway IIRC, which I'm not entirely convinced is ideal because files might not get recompiled when they need to be, but it's something I have in mind.

For the initial step I just wanted to do a clean move of the files.

**Comment by rb6502** [comment]
Thanks for the folder rename.  You will be graded later on building stuff individually :P

**Pull request merged**
