### PR TITLE
NE555 timing fixed, cleaner schematics found.

### PR DESCRIPTION
**Pull request by ensjo**
555 circuit

### CODE REVIEW

**Comment by mixxmaster** [comment]
clang build works, although GCC doesn't. not sure why...

**Comment by ensjo** [comment]
Hello, @mixxmaster, is there something I should do? Is the non compilation due to my code? I can't see anything wrong in it.

**Comment by Lord-Nightmare** [comment]
On 8/10/2015 8:56 PM, Emerson José Silveira da Costa wrote:
>
> Hello, @mixxmaster <https://github.com/mixxmaster>, is there something 
> I should do? Is the non compilation due to my code? I can't see 
> anything wrong in it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mamedev/mame/pull/262#issuecomment-129660435>.
>
The compile problem has nothing to do with your code.

-- 
Jonathan Gevaryahu
jgevaryahu@gmail.com
jgevaryahu@hotmail.com

**Comment by Lord-Nightmare** [comment]
The compile problem has nothing to do with your code.

**Comment by mixxmaster** [comment]
Yeah, most likely a AppVeyor/Travis VM running out of memory error due to large binary size.

**Pull request merged**
