### PR TITLE
add apple2_cass softlist

### PR DESCRIPTION
**Pull request by Dagarman**
This starts a cassette softlist for the apple2 series. Includes tapes with ml, integer basic, and applesoft basic.

https://www.sendspace.com/file/53yw41

### CODE REVIEW

**Comment by Pernod70** [comment]
In your double-sided entries you have info name="usage" twice at the same level. These are associated with the software and not each part, you cannot specify info for each part. 
Where you have multiple parts I recommend adding a part_id, inside the part before dataarea.

```
<software name="strtstw">
<description>Startrek / Starwars</description>
	<year>1978</year>
	<publisher>Apple Computer, Inc.</publisher>
	<info name="usage" value="16K >Load" />
	<part name="cass1" interface="apple2_cass">
		<feature name="part_id" value="Side A: Startrek"/>
		<dataarea name="cass" size="4134574">
			<rom name="startrek (1978)(apple computer).wav" size="4134574" crc="7112bff5" sha1="279545abc5bf9b57dc79e7ea322df59b733803b0" offset="0" />
		</dataarea>
	</part>
	<part name="cass2" interface="apple2_cass">
		<feature name="part_id" value="Side B: Starwars"/>
		<dataarea name="cass" size="2590032">
			<rom name="starwars (1978)(apple computer).wav" size="2590032" crc="d2ea22a1" sha1="823ac3669a4b98fb7ca41f90db0d562c624d4904" offset="0" />
		</dataarea>
	</part>
</software>
```

**Comment by Dagarman** [comment]
I don't understand this error. This is the first time I have tried to fix a submission so maybe I did it wrong. Should I just recommit the entire thing?

**Comment by Dagarman** [comment]
Hopefully no errors this time.

**Comment by Tafoid** [comment]
Any download for the remaining 2 titles added  (clrdlbo, karma)?  I've waited a couple days and nothing has surfaced.

**Comment by Dagarman** [comment]
Sorry about that:
https://www.sendspace.com/file/wwwwi8
https://www.sendspace.com/file/2etjdm

**Pull request merged**
