### PR TITLE
WIP: sync bgfx, bx and bimg with latest upstream

### PR DESCRIPTION
**Pull request by belegdol**
Once completed, this WIP will sync the bgfx, bx and bimg with latest upstream. The changes do not build yet but I am sharing what I have managed to get done so far.

### CODE REVIEW

**Comment by belegdol** [comment]
Milestone 1 reached: it builds.

**Comment by belegdol** [comment]
Milestone 2: compiles on mac too, mametiny64 -video bgfx wrally works as well.
I believe this is now ready for broader testing.

**Comment by belegdol** [comment]
@rb6502 : with these changes and additional updates (in my bgfx-enable-dx12-and-vulkan branch) dx12 renderer still crashes on exit, but vulkan renderer actually produces video output.
Strangely enough hlsl makes screen red with the rebuilt shaders as in the issue I reported a while back.
Should I push the dx12 and vulkan changes to this PR, or would you prefer a separate one? Thanks!

**Comment by rb6502** [comment]
@belegdol Include the Vulkan enable in this PR, we'll keep DX12 out until we can determine what the crash is from.

**Comment by belegdol** [comment]
I have now added the changes, please test. The dx12 renderer is there but commented out. Please note that you need to build the spir-v shaders yourself with make shaders, I would prefer not to push those until we fix issue #4396 being back. This likely needs input from someone being more familiar with shaders.
What I have been able to figure out so far: the in the original fix for the issue (commit a143090), only the glsl, elsl and metal shader binaries were pushed. dx9 and dx11 ones were not changed. Can it be that the XYZ_TO_sRGB matrix only needs to be transposed for opengl and some ifdefs are required? The situation at the moment supports this theory:
renderer | shaders not rebuilt | shaders rebuilt | shaders rebuilt, old fix reverted
------------ | ------------- | ------------- | -------------
opengl | OK | OK | red
dx9 | no video | no video | no video
dx11 | OK | red | OK
dx12 | OK | red | OK
vulkan | N/A | red | OK

**Comment by belegdol** [comment]
I have now added the logic to conditionally transpose the matrix depending on the backend. As the issue with red hlsl seems to only ever have been reported for glsl, I only enabled it there. This effectively reverts commit a143090 for all renderers except glsl.
We do know the matrix must be transposed for glsl, and must not be transposed for dx11 and spir-v.
Are you able to test elsl and/or metal?

**Comment by belegdol** [comment]
I managed to confirm that OpenGL ES needs transposed matrix to using mame hacked to use gles on Linux. So only metal remains to be confirmed.

**Comment by rb6502** [comment]
Metal colors are correct on current top-of-tree, whichever way that means.

**Comment by belegdol** [comment]
Did you rebuild the shaders? Or just use the ones from git?

**Comment by rb6502** [comment]
Just a git pull.  To clarify, that's current MAME master, without this CL.

**Comment by belegdol** [comment]
This means that metal needs to have the matrix transposed.
Just to be sure, can you rebuild the shaders on your end and retest?
```
make shaders CHAINS=hlsl
```
should do the trick. If you get weird yacc/bison/flex errors, run 3rdparty/bgfx/3rdparty/glsl-optimizer/generateParsers.sh

**Pull request merged**
