### PR TITLE
new WORKING machine (Gun Kids - Sammy Medal game)

### PR DESCRIPTION
**Pull request by mamehaze**
new WORKING machine
----
Gun Kids [Darksoft, TeamEurope]

### CODE REVIEW

**Comment by mamehaze** [comment]
this was sent to me as 'Gun Kids' but running google image translate on the title screen shows 'Gun Kiss' which seems more reasonable.

**Comment by Osso13** [comment]
https://www.youtube.com/watch?v=glOEdNib5Ng

FWIW this video's description has it as 早撃ちガンキッズ which according to Google Translate is 'Hayauchi gankizzu' -> 'Quick Draw Gun Kids'.

**Comment by mamehaze** [comment]
Well this is the title.  I'll leave it up to somebody who knows Japanese to decide what it should be, although I find it difficult to believe Sammy would be stupid enough to put out a game called Gun Kids, and Klaus was very unsure which was the correct title.

**Comment by mamehaze** [comment]
so the people you're shooting really are meant to be kids?

**Comment by happppp** [comment]
I don't know what the game is about, but when I see just the title, I'd think the "gun kids" are the playable chars.

**Comment by FoxhackDN** [comment]
キッズ = Kids
キス	 = Kiss

The little " on top of the last character changes how it's pronounced. +1 to "Kids". Also the video shows little tiny people being shot... https://www.youtube.com/watch?app=desktop&v=glOEdNib5Ng

**Comment by FoxhackDN** [comment]
... oh so apparently Sammy had a "Kids" series of Medal games. I'm finding several of them through Google.

https://www.sammy.co.jp/japanese/products/jurackeys/ (Jura Kids)
https://medalgm.com/kids-medal/hayauti-gankids (Blog post about Gun Kids)

So yeah, it's Kids.

**Comment by happppp** [comment]
See my message above, it's not "Quick Draw Gun Kids" (and not "Hayauchi Gankizzu"), it's "Hayauchi Gun Kids".
As you probably already know, MAME does not translate titles, except for obvious loanwords like Gun Kids in this case.

**Comment by cuavas** [comment]
> https://www.sammy.co.jp/japanese/products/jurackeys/ (Jura Kids)

No, that’s “Jurackeys” (ジュラッキーズ, “jurakkiizu” in romaji).  No “kids” in the title of that one.

**Pull request merged**
