### PR TITLE
Implement integer scaling in core renderer [Calamity]

### PR DESCRIPTION
**Pull request by antonioginer**
Implement integer scaling in core renderer.
- Move -keepaspect option to core
- Move -unevenstretch option to core (-nounevenstretch gives integer scaling)
- Add new -unevenstretchx option to core (fractional scaling on horizontal axis, integer scaling on vertical axis)
- Remove -hwstretch (Direct Draw)
- Fix pixel aspect management on video mode switching
- Small fixes on windows resizing

### CODE REVIEW

**Comment by ImJezze** [comment]
Were there any problems with your changes or why did you cancelled your pull request?

**Comment by antonioginer** [comment]
I'm just going to rework the idea, making it simpler.

**Comment by Tafoid** [comment]
Testing this morning based on this submit is showing all drivers/machines which have resolutions which are purposely larger for rendering (eg. sega system 1, galaxian, pce/tg16, snes, pc-based) are all showing aspect ratio cropped RAW snapshots surrounded by black screen when they should be showing snapshots entirely stretched out as rendered in the core.

Attached are some examples of these taken from my regression test this AM (-str 10) which automatically takes a "final.png" snapshots and was compared to the previously logged run.

crystalg-diff
su2000-diff
swat-diff
wboy-diff

**Comment by antonioginer** [comment]
This is fixed by https://github.com/mamedev/mame/pull/733

**Pull request merged**
