### PR TITLE
tv990: 'setup' key option

### PR DESCRIPTION
**Pull request by 68bit**
Translate the Ctrl-Alt-S key sequence to the 'setup' key code Ctrl-Alt-Esc, just so this can be used on a Linux desktop.

To use the terminal it needs access to the 'setup' key sequence Ctrl-Alt-Esc. However on Linux at least, the desktop intercepts this before it reaches MAME.

Would have preferred a firmware ROM patch, rather than an emulator hack, but looking at the firmware suggested no quick patch. There is a table but it appears generic and not specific to the ctrl-alt combination, and and while modifying this table can changes the setup key it also breaks other uses of the key.

This one might need some help, and not sure that adding a translation here is appropriate?

Might it be better to add an option in the KBDC8042 driver?

Am I just missing something?

### CODE REVIEW

**Comment by cuavas** [comment]
This really goes against the "MAME spirit".  It would be better if you used a lua script to check for a key combination and generate the Ctrl-Alt-Esc input that way.

**Comment by cracyc** [comment]
Or just remap esc in the input menu.

**Comment by ajrhacker** [comment]
In theory, MAME's "natural keyboard" input reprocessing layer should be able to rebind arbitrary key combinations like this. As it exists now, it's not quite versatile enough. Capturing Ctrl-Alt-S probably does lie within the capabilities of the new cheat system, though.

**Comment by 68bit** [comment]
Fwiw I'd also like a solution that can work when running MAME in a web browser. Let me explore some of these suggestions thanks. Even an pop up on screen keyboard would be adequate for a 'setup' button that is rarely used.

**Pull request closed without merging**
