### PR TITLE
OG broke the MSVC compile, now he must pay

### PR DESCRIPTION
**Pull request by kazblox**
Not sure if this is a proper fix, but there doesn't appear to be any side effects with anything that uses the fifo code.

### CODE REVIEW

**Comment by rb6502** [comment]
Does https://github.com/mamedev/mame/commit/f6ba62f3e9add815fa1c851ba2c79d732bc831d5 not fix it?

**Comment by kazblox** [comment]
Oh boy, I didn't notice that. Closing right away...

**Comment by cuavas** [comment]
This PR is very wrong as `std::move` leaves things in a state where the only valid operations are assignment and destruction, but I'm not sure f6ba62f3e9add815fa1c851ba2c79d732bc831d5 is necessarily right either - it guarantees an extra copy when the type may be non-trivial.

**Comment by galibert** [comment]
Yeah, that interface must be made better.  I went too C++y I guess, it's
probably sane to require copy-able objects for the fifos...

  OG.

**Pull request closed without merging**
