### PR TITLE
new NOT WORKING machines

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING machines
----
DT7 (prototype)

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I've had 4 people email me the ROMs to this asking if I can "Help with the emulation" including a some which are obviously watermarked, which suggests that the ROMs are out there.  However, the copy I was originally sent I agreed to not distribute, so I'm setting this as a draft PR.

If the ROMs show up, maybe I'll finish it off (the audio CPU needs properly decrypting)  If they don't, those wanting me to 'help' have this as a base.

**Comment by arcadez2003** [comment]
Once again there is this tipy tip toe around a certain someone "who as far as we knew had the only working copy of DT7"
attitude, i kinda know the hate which will come my way now as i've dared once again to suggest this situation eg a constant
attempt to keep someone sweet and supposidly onside can and never will benefit the overall aims of the MAME project.

Consider the following..........

DT7 until now has not been dumped and publically shared with the project from the source i clearly mentioned above
now that roms have been shared from multiple different sources this should be thought of surely as a good thing rather
than worrying it seems as always that a certain person might be all upset to see it :)

**Comment by smf-** [comment]
It benefits the people who get sent things privately though.

**Comment by simzy39** [comment]
@arcadez2003 That same person in the last few years released: SNK Mahjong Block Jongbou 2, Megumi Rescue, and Namennayo. Without them, these 3 games would probably never have been secured, especially Namennayo because it's worth over $10K, so stop going on a witch hunt. The person you're referring to has done, and does do, much good for the Mame community.

They themselves once wrote an explanation of why not everything is released by them, and it's quite a logically explanation. (They know of games we have never heard of, and they know who has them, and sometimes they have to make deals in order to make trades, and this sometimes involves their word that they won't release the data for x amount of years or so. They then trade their incredibly rare games to trade for other rare prototypes, trades that wouldn't happen if they'd released the data. But they do back everything up.)

**Comment by DavidHaywood** [comment]
My gut feeling here is that the other people contacting me might be doing so, without disclosing their reasons, because they've been tasked with giving the game a proper, official release, but actually don't have a clue how if MAME doesn't already support it (especially when it comes to things like the audiocpu decryption here, which is non-trivial to figure out - even what you see here was several months of work some years back)

This is the other reason I'm not forwarding anything I've been sent, and just waiting to see what happens.

**Comment by arcadez2003** [comment]
> @arcadez2003 That same person in the last few years released: SNK Mahjong Block Jongbou 2, Megumi Rescue, and Namennayo. Without them, these 3 games would probably never have been secured, especially Namennayo because it's worth over $10K, so stop going on a witch hunt. The person you're referring to has done, and does do, much good for the Mame community.
> 
> They themselves once wrote an explanation of why not everything is released by them, and it's quite a logically explanation. (They know of games we have never heard of, and they know who has them, and sometimes they have to make deals in order to make trades, and this sometimes involves their word that they won't release the data for x amount of years or so. They then trade their incredibly rare games to trade for other rare prototypes, trades that wouldn't happen if they'd released the data. But they do back everything up.)

There is no witch hunt here being a former member of the dumping union im familar with the man in question and his
many contributions to the preservation scene, my beef has never been with him per say but more a perceived bias IMO 
with regards to how MAME deal with unpreserved games a dump then becomes available for if said dump originates
from Japan.


Simply put IMO if there are no restrictions with regards to making the roms for DT7 publically available from those 
who shared them and there are no legality issues in doing then surely it should happen regardless of whether someone 
else connected to the preservation owns a pcb for that game or not as let's be honest here it has nothing to with them
either way.

**Comment by simzy39** [comment]
I wonder where the roms/copies are coming from though because there were only 3 of these prototype boards released, all in Japan. If the copies are watermarked, then maybe there was a hack or something.

**Comment by DavidHaywood** [comment]
As I said, I assume somebody wanting to do a modern release got hold of it, or it was dumped long before it even fell into hands of collectors.  I did point out to those forwarding me watermarked ROMs the differences between the known dumps and their watermarked ones, just so they were in the know that distributing them could end up being traced back to them, and was probably a bad idea.

**Comment by DavidHaywood** [comment]
ok, doesn't look like this is going to show up, I know those asking me to look at it have seen it, but sounds like they're not going to distribute anything.

**Comment by arcadez2003** [comment]
Well i can only speak for myself and certainly not having a dig at anyone here, but if it was me i'd take the viewpoint that
going forward i'd not help private individuals who happen to have undumped and or unpreserved game which they then
contact a member of the MAME project for help emulating without a cast iron guarantee beforehand that both the code 
and the romset for the game in question would be made public afterwards.

Two ole sayings spring to mind......

I'll scratch your back if you scratch mine!! and once bitten twice shy!!

**Comment by DavidHaywood** [comment]
In light of new information, I'll leave this open.

It isn't exactly clear what is going on, and as Exa is claiming ownership over this game / license, merging it could be a problem.

That said, the source of the ROMs that are going around seems to be entirely independent of Exa, the modern form of Toaplan (who I'm told don't have access to it) or any kind of license to a re-release the game, and is therefore probably a much older dump, possibly even something from when the game was originally being developed.

I don't really have much interest in the politics of this situation, but it seems similar to how Marble Madness II surfaced, although there was no threat of a C&D over that one.  Any policy call on this is 100% up to @cuavas

**Comment by arcadez2003** [comment]
Hmm an ole arcade prototype which never got a release back in the day of which 95% of the gaming community will never have heard of in the first place surfaces the IP of which just happens to be owned by EXA dont know about you but my
suspicion levels have just increased.

How do you make money from owning the IP to it.?? well it's by Toaplan who have a large fanbase myself included so that's an upside the next question is how to advertise and then distribute it to maximise the profit potential.??

A) clone it and release it as an pcb 

Well the above would have high costs and a very low userbase 

B) emulate the original hardware 

This seems the most likely solution low cost and a potentially high userbase

I suppose the problem with the last scenario is you require to have someone on your dev team with the skillset needed to
emulate said game in the first place otherwise you'd need to approach someone else in the hope they can help, you have
two ways of going about this be upfront with them at the start and ask properly or i suppose the other option is to go
about it in a more underhand way.

Im sure in the fullness of time the community will be privy to what method was used in this case.

Regards

**Comment by smf-** [comment]
Their business model is getting games ported to their own platform
https://exa.ac/product/exa-arcadia-hardware/ and the userbase is higher
than if everyone can play it for free.

You don't have to like it, but it's in nobodies interests to end up in
court.

**Comment by arcadez2003** [comment]
I dont like nor dislike really as this is not a game that i or many people for that matter have ever played but i agree it's 
better to not support DT7 officially than to end up in court for doing so.

Personally i think the business model for this company is not sound and not being alone in that viewpoint it might not 
be too long until the IP for this game and some others they hold along with EXA will go the way of the dodo.

**Comment by DavidHaywood** [comment]
As I said, vas's call at the end of the day.  Not including support for a 30 year old game probably sets a bad precedent, especially with this being independent of what's going on otherwise, but I can also understand the concern.

**Comment by simzy39** [comment]
@arcadez2003 

Why do you think the business model is unsound, and do you own a business? I'm curious, especially since you say you aren't alone in your viewpoint. 

From what I understand, the company is doing nothing illegal and are porting (producing a product) for people to consume. They legally have purchased the rights to the IP, which might have cost them a lot of money, so they obviously want to protect their IP, which is why they might ask Mame to not include certain things. This is how the modern world works.

Also, it is a great business model because they keep doing it, so obviously it makes them money. The owner also knows what games to do it with, since they know the market and know the consumer.

You should love the company because it makes the owner money, and then that owner buys rarer games, and eventually they end up in Mame. How do you think the owner was able to dump a $10 000 game (Namennayo)?

I actually think you need to delete your github account and stop bringing politics into a pull request, especially since you're contributing nothing but verbosity and manure. Also, I hope you enjoy having a mortgage.

**Comment by cuavas** [comment]
This is getting off-topic fast. Use a forum to discuss the relative merits of business models.

**Comment by rb6502** [comment]
@simzy39 It's widely accepted that exA has lost and continues to lose a lot of money and has no chance of ever breaking even, but of course we have no way of knowing the actual numbers.

**Comment by galibert** [comment]
I'd rather avoid more drama, honestly, we've had our fill for the year.  Let's close it for now, we can revisit afterwards when things are clearer.  Let's say next summer for instance?  Not as if many people are going to miss that game.

**Comment by arcadez2003** [comment]
> I'd rather avoid more drama, honestly, we've had our fill for the year. Let's close it for now, we can revisit afterwards when things are clearer. Let's say next summer for instance? Not as if many people are going to miss that game.

Yes it looks like a huge step down when compared with the earlier Rally Bike for example, but it seems certain people
are not missing this game a romset for which must be kicking around in certain circles and code has clearly been taken 
from this aborted pull req to emulate it as per this video....

https://www.youtube.com/watch?v=7Zo-wJjwuUw

Secret societies eh i hear to join the DT 7 club you have to find a member firstly shake their hand three times then jump 
up and down four times while waving a chequered flag it hasn't worked for me as yet but i'll keep on trying :)

**Comment by happppp** [comment]
Uhuh

**Pull request closed without merging**
