### PR TITLE
Changing START1 to START

### PR DESCRIPTION
**Pull request by Shideravan**
To match other consoles standarization for start button...

### CODE REVIEW

**Comment by rb6502** [comment]
I don't understand what this change is intended to accomplish.  START1 is 100% the correct thing to use for player 1 on a console driver.

**Comment by Shideravan** [comment]
Ok, but other systems, such Playstation, Genesis, Master System, Game Gear, Nintendo 64, Saturn, etc etc etc... all use START, not START1 (which is used normally for arcade machines as "enter new player button"). 
I think that a standardization is necessary so that the configuration is more intuitive for the user.

**Comment by Shideravan** [comment]
Also, I edited the title and the description of the pull request.
I didn't put much effort on what to write, then maybe the old description didn't fit very well for what this update is intended to do.

**Comment by cuavas** [comment]
The thing is, it isn't a player 1 start button on a console, it's a start button on a slot device that could be the start button for any player depending on where it's plugged in.  We're using START for this on all other console controllers that work as slot devices.

**Pull request merged**
