### PR TITLE
Fixed more Mahjong dips as per manuals - system11

### PR DESCRIPTION
**Pull request by system11b**

### CODE REVIEW

**Comment by cuavas** [comment]
The trouble with marking all these things as unused just because the manual says so is that the manual is misleading in at least some cases. The games actually read and use bits corresponding to switches that the manual says are unused. I'd be more comfortable leaving them as unknown rather than unused with a comment saying that the manual says the switch is unused until someone can verify from disassembly that the switch really has no effect. That's what we do with the gamblers.

**Comment by system11b** [comment]
That's why I didn't completely remove them.  Hardly anyone even cares about Mahjong games - I think it's misleading to see a whole bunch of 'unknown' leading people to believe there's probably functionality behind them when in fact in most cases there isn't.  Otona is an interesting example however where the manual says bank B isn't used, yet there's a test function on it.  Nobody with the PCB can access that though because the dip switch isn't actually fitted to the PCB - arguably that should be removed as it was provably never available to begin with in the product as sold to operators.

**Comment by cuavas** [comment]
Hardly anyone cares about gamblers either, but we still try to document them properly.  And the fact is, without disassembling/tracing the program, you don't know whether functionality is hidden behind these switches.  I've seen too many games that actually do use nominally "unused" switches to accept this without at least adding qualifying comments.

**Comment by mamehaze** [comment]
In this case it's less harmful than making them completely unavailable to the user, which was the old policy.

If the manual says they're unused, it's a fair base assumption (and in *most* cases, correct) if somebody proves that wrong they can be updated again.

**Pull request merged**
