### PR TITLE
added 4 XaviX based games, not working

### PR DESCRIPTION
**Pull request by mamehaze**
new NOT WORKING machines
--------------
Excite Ping Pong 2 (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]
Croket! Itada Kinka! Banker Battle!! (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]
Shooting King (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]
Gun Gun Revolution (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]

these all run, but lack inputs.  Excite Ping Pong 2 has some graphical corruption which looks like it might be bitrot, so is marked as bad (reads were consistent)

### CODE REVIEW

**Comment by mamehaze** [comment]
Boxart_Front
Console
PCB_Front

Boxart_Front
Console_Front
PCB_Front


Boxart_Front
Console
PCB_Top


Boxart_Front
Console
PCB_Front

**Comment by mamehaze** [comment]
I suspect the Croquet title is not accurate

**Comment by FoxhackDN** [comment]
> I suspect the Croquet title is not accurate

If you have the box, could you please paste the JAN from it so I can search for the game title? Nothing seems to be giving me any hits.

**Comment by FoxhackDN** [comment]
Actually... it seems the spelling they use is "Croket". It's seemingly based on a manga.

image

https://en.wikipedia.org/wiki/Croket!

**Comment by mamehaze** [comment]
Well I still really need a full title for this thing; Prohibited Goods is just a Google translation.

**Comment by mamehaze** [comment]
Boxart_Back
Boxart_Bottom
Boxart_Front
Boxart_Side1
Boxart_Side2
Boxart_Top

**Comment by FoxhackDN** [comment]
The transliterated title appears to be Croket! Itadakinga! Bunker Battle!!

バンカー means "Bunker"

**Comment by cuavas** [comment]
It’s “コロッケ! いただ禁貨! バンカーバトル!!”

“禁貨” should be read as “kinka” (not “kinga”) as confirmed by the furigana “きんか” above the kanji.

Full transliteration is “Croket! Itada Kinka! Bunker Battle!!”

**Comment by cuavas** [comment]
Scratch that, it’s Banker, not Bunker – “Croket! Itada Kinka! Banker Battle!!”

**Comment by FoxhackDN** [comment]
I hate this.

The most common romanization used in the GBA game seems to be "Bunker"... but the official one is "Banker", as seen here.

https://www.suruga-ya.com/en/product/148019844

So I don't like it, but it should be Banker. Bleh. Also sorry about the misspelling earlier.

**Comment by cuavas** [comment]
> So I don't like it, but it should be Banker. Bleh. Also sorry about the misspelling earlier.

I actually took a look at a couple of pages of the manga.  It’s about characters called “bankers” trying to collect “forbidden coins” (hence the catchphrase “いただ禁貨!” – “Take the forbidden coins!”).  It does not involve bunkers.  “Bunker” is definitely wrong whether you like it or not.

**Comment by FlykeSpice** [comment]
How would you represent input to these hand tracker machines in mame?

**Comment by mamehaze** [comment]
Knowing how to emulate the controls on some of these is not something I'm sure of myself.  The ones with cameras can detect not only where your hands are, but also the angle you're holding something at, which side of it is facing the camera (narrow side, wide side etc.)

They tend to work using 4 IR LEDS and a camera that picks up reflections off the silver surfaces.  The games, from what I can see detect that as a grid of intensity values.  

The ones added here aren't camera based ones though, they're just annoying to figure out for different reasons; even things like Ping Pong are reading much more data than the cheap knock-off consoles to pick up your movement.  The code is not exactly easy to follow either, which is why a lot of them still don't have hookups.  I think it's going to be one of those things where somebody who likes weird control schemes takes a look at getting the controls hooked up; my goal is to get them preserved in some form while they're still affordable / available so that they can be picked up at a later date.

**Pull request merged**
