### PR TITLE
Update BGFX, BX and BIMG

### PR DESCRIPTION
**Pull request by mmicko**
Update libraries (as of 26th of December 2022):
- BGFX to https://github.com/bkaradzic/bgfx/commit/a93a714632b79b5ddbf5c86ac323fa9b76ed3433
- BX to https://github.com/bkaradzic/bx/commit/aed1086c48884b1b4f1c2f9af34c5198624263f6
- BIMG to https://github.com/bkaradzic/bimg/commit/1af90543ca262c1cfa10aa477aef9dc1b11419f4
- shaders updated (note dx9 and dx11 are not affected, have regenerated them on Windows machine)
- imgui is not using any more deprecated KeyIo functions

### CODE REVIEW

**Comment by happppp** [comment]
Mingw64/GCC with latest updates from pacman fails:
`(...)
mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to 'always_inline' '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
  136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~
../../../../../3rdparty/bimg/3rdparty/astc-encoder/source/astcenc_vecmathlib_sse_4.h:1109:42: note: called from here
 1109 |         __m128i result = _mm_shuffle_epi8(t0.m, idxx);
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
`

**Comment by mmicko** [comment]
@happppp please try https://github.com/mamedev/mame/pull/10791 or just mingw_fix branch, to see if this is working on your setup. Fix landed 3 days ago there in repo for same reason.

**Comment by happppp** [comment]
It gives the same error.

**Comment by mmicko** [comment]
@happppp looks like msse4.2 is needed,  but need to upgrade my env in order to try

**Comment by happppp** [comment]
I cherry picked the change to 3rdparty.lua, that fixes the compile issue here.

**Comment by happppp** [comment]
I think you're right.
If you want, you could make a PR.

**Comment by smf-** [comment]
> I cherry picked the change to 3rdparty.lua, that fixes the compile issue here.

Weirdly it worked fine before you did that, now it's broken.

**Comment by happppp** [comment]
In my case it was probably the ASTCENC_AVX=0 that fixed the compile.

**Pull request merged**
