### PR TITLE
Work around for another MSVC bug involving a failure to recognize a constexpr

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by cuavas** [comment]
It's getting to the point where it's not worth working around MSVC any more.  Going forward, the recommended way to build and debug with Visual Studio is to use the clang/llvm plugin.  Does the error happen when you build with Visual Studio using the clang/llvm plugin?

**Comment by yz70s** [comment]
If someone can make a self-contained test case, i will report it as a bug to the visual studio community.

**Comment by npwoods** [comment]
Here you go; keep in mind we use an older MSVC and there is a good chance that this particular problem has been fixed.  I've created a test case for PR#5301 as well

> 
	template <typename FT, int SIZE>
	struct sizeabs
	{
		static constexpr std::size_t ABS() { return (SIZE < 0) ? static_cast<std::size_t>(0 - SIZE) : static_cast<std::size_t>(SIZE); }
		using container = typename std::array<FT, ABS()> ;
	};

**Comment by yz70s** [comment]
Thanks, i will test both with all the versions i have installed (the latest preview version too)

**Comment by yz70s** [comment]
From my tests this problem is present until the last version of vs2017, but it is not present in vs2019 v16.1.4 and preview 3 of 16.2
The community website has lots of errors with constexpr in vs2017, probably it was already reported.
But #5301 is still not fixed.

**Comment by pmackinlay** [comment]
@yz70s, for what it's worth, Compiler Explorer (https://godbolt.org/) provides a convenient way to interactively evaluate test cases such as this against many different compilers, including many versions of MSVC, without having to install them locally.

**Comment by vadosnaprimer** [comment]
vsllvm has the most important part of visual studio - compatible pdb that allows debugging in VS. The only inconvenience with it is not seeing which file it's currently compiling (maybe that has an easy fix).

**Pull request closed without merging**
