### PR TITLE
fm7_cass: New software list additions

### PR DESCRIPTION
**Pull request by TheMechasaur**
----------------------------------------------------------
New WORKING software list additions:
Biotek [Cytlan, Gaming Alexandria]
Elevator Game [Cytlan, Gaming Alexandria]
Hitsuji Yaai [Cytlan, Gaming Alexandria]
Killer Station [Cytlan, Gaming Alexandria]
Kinasai [Cytlan, Gaming Alexandria]
Oozumou [Cytlan, Gaming Alexandria]
Shinjuwan Kougeki [Cytlan, Gaming Alexandria]
Yume no Pro Yakyuu [Cytlan, Gaming Alexandria]

New NOT_WORKING software list additions:
Crash Ball [Cytlan, Gaming Alexandria]
FM Racer [Cytlan, Gaming Alexandria]

New WORKING software list clones:
I wa Sanjutsu Nari (alt) [Cytlan, Gaming Alexandria]
Sokoban (alt) [Cytlan, Gaming Alexandria]
Space Warp (alt) [Cytlan, Gaming Alexandria]

### CODE REVIEW

**Comment by TheMechasaur** [comment]
License: CC0 (to match what the file states in its header)

**Comment by TheMechasaur** [comment]
Is there a specific Romanization system used by MAME? The romanizations for several of the titles given by the source (Hitsuji Yaai, I wa Sanjutsu Nari) differ from romanizations used in this softlist and other softlists (Hitsuji-Ya, Iwasanjutsunari). For Yume no Pro Yakyuu, the game is listed as "Yume no Pro Yakyu" in x1_cass.xml, but the source lists it as "Yume no Puro Yakyuu." As "Puro" is an English loanword written as "プロ" in Katakana, I used the English word in the title of the game's softlist entry.

**Comment by DopefishJustin** [comment]
Generally the MAME standard is waapuro-style Hepburn, unless there is a different official romanization on the title screen or the like. Loanwords should be written as the English (or other foreign) word; spacing between words is somewhat arbitrary.

**Comment by cuavas** [comment]
Also see the guidelines for transliteration in MAME here: https://docs.mamedev.org/techspecs/naming.html#transliteration

**Pull request merged**
