### PR TITLE
Coco2drivewire

### PR DESCRIPTION
**Pull request by drencorxeen**
Added COCO2_HDB1 cart and ROM
Added Unofficial variants of CoCo2 and CoCo2B with the COCO2_HDB1 cart

The unofficial variants are called:  coco2dw1 and coco2bdw1

These systems are tested working.

### CODE REVIEW

**Comment by cuavas** [comment]
Are these actual modified machines, or is it a cartridge plugged in?  Are they real, or are they hypothetical configurations?

**Comment by drencorxeen** [comment]
The CoCo2_DW1 card is a hypothetical cart for giving the CoCo2 the same features as the CoCo3_DW1 cart gives the CoCo3 DriveWire features. This coco2_dw1 cart also includes the CoCo2 specific HDBDOS for Becker port ROM. 

The coco2dw1 and coco2bdw1 systems would be also hypothetical systems that of course would by default use that cart. 

These configurations gives a CoCo2 and CoCo2B style system like the coco3dw1 that is in the CoCo3.cpp file.

**Comment by cuavas** [comment]
I'm not particularly comfortable with this.  Would it be possible to implement it as a slot device that can be used with CoCo2/2B/3 and remove the coco3dw1 as well?

**Comment by drencorxeen** [comment]
Umm CoCo users have asked for ready to go systems which is why I made the coco2dw1 and coco2bdw1 systems as most people don’t like having to use the command line or have to keep changing the cart from the UI. 

People want MAME easier not more complex to use.

**Comment by drencorxeen** [comment]
As far as a cart yes that is part of this update was the COCO2_DW1 in the coco_fdc.cpp

**Comment by cuavas** [comment]
Well you can put your slot options in `ini/coco2.ini` or `ini/coco2b.ini` and they'll stick.  "People" don't want the system list polluted with hypothetical machines.

For the same reason we don't have different machines for the IBM 5150, Apple IIe and Intel INTELLEC 4/MOD40 with different card loadouts.  The default configuration provides a reasonable representative configuration.  For IBM 5150 there's a keyboard, CGA card, dual serial card, FDC card, and fixed disk controller card; for Apple IIe there's a Mockingboard card and a Disk II card; for INTELLEC 4/MOD40 there's a glass TTY, a high-speed paper tape reader and a PROM card.

These configurations are representative of a realistic setup for the machines, and they're enough to get started or experiment with the emulation.  Someone more experienced is probably going to want to change the defaults, and that's why we make it easy to configure this with INI files.  But we don't go creating separate hypothetical machines with additional built-in functionality, or special machines for different configurations like an Apple IIe with a mouse card, serial card and ImageWriter for running AppleWorks.

**Comment by drencorxeen** [comment]
@cuavas , as requested I removed the coco2dw1 and coco2bdw1.

The CART device is actually called COCO2_HDB1 and is working.

**Pull request merged**
