### PR TITLE
c64_cass.xml - updated year and publisher details

### PR DESCRIPTION
**Pull request by scoomby**
Reviewed c64_cass.xml and noticed a number of release years were inconsistent, missing or incorrect, and a few of the publisher details were also incorrect.

During the 80's and 90' there were a number of budget labels that had been created by some publishers to release games at a discounted price.  Sometimes these games were re-releases of games previously published by the same company at full price.

Notable budget labels are as follows:
Firebird Silver (Firebird) - A mix of original and re-releases.
Silverbird (previously Firebird Silver) - A mix of original releases and re-releases.
Ricochet (Mastertronic) - All re-releases.
The Hit Squad (Ocean & U.S. Gold) - All re-releases and compilations.
Encore (Elite Systems) - Mostly re-releases.
Kixx (U.S. Gold) - All re-releases.
Summit (Alternative Software) - A mix of original releases and re-releases.
GBH (Gremlin Graphics) - All re-releases.
Sparklers (Creative Sparks) - All re-releases.

In some cases, a re-release wasn't identical to the original release where tape loaders, loading screens, or title screens had been changed.  There also a couple of cases where the game has been modified in the re-release (e.g. Cauldron's difficulty level was lowered).

Presently, there are a lot of the C64 tape files are dumped from the budget label release.  To keep things consistent, the release year reflects the year of the original release or the year of the budget re-release as applicable.  Publisher details reflects the original release publisher, budget label or distributor as applicable.

Questions, suggestions and comments are very welcome.

### CODE REVIEW

**Comment by cuavas** [comment]
Firstly, I’m kind of nervous about these kinds of metadata changes because they tend to devolve into endless arguments.

Do we really want to be putting the original publisher in for re-releases?  If the re-release didn’t actually use the original publisher’s branding, does it go against the way we do this stuff?

If we do decide that the original label and re-release label should both be present, “re-release” should not be capitalised because it isn’t part of a name and isn’t a proper noun.

**Comment by cuavas** [comment]
What are you using as a reference for the years and publishers?

**Comment by cuavas** [comment]
Why did you add “(Compilation)” to a number of titles?  Is it actually part of the original titles?

**Comment by Pernod70** [comment]
I am against changing the publisher of budget re-releases to include the original publisher, there's no need for it, and also makes sorting by publisher in a front-end impossible. The only publisher change I agree with is 'Silver Range'->'Firebird Silver'.

The first year that I checked was your 'Ace 2088' change to 1991. I have a scan of the inlay which clearly says 1989 which also matches other references on the internet, though doesn't mean it's correct I'd like to see some evidence for the change.

The majority of c64_cass is based on the collection and metadata from the C64 Ultimate Tape Archive V1. This collection has since been updated to V2 and adds over 500 new titles, so c64_cass is due a major update to sync with this collection which will likely supersede any changes to metadata made now.

**Comment by scoomby** [comment]
Thanks for your comments. I completely understand your points and I wasn't intending to tread on anyone's toes if it appeared that way.  The release years were verified against my experience of owning a C64 and over 100 games on cassettes and disks, verifying against Lemon 64, Zzap 64 magazines, the cassette inlays, etc.  Happy to keep publisher the same to keep consistent approach as advised.  Might be worth looking at the V2 set as well. Will take a closer look at this tomorrow

**Comment by scoomby** [comment]
> I am against changing the publisher of budget re-releases to include the original publisher, there's no need for it, and also makes sorting by publisher in a front-end impossible. The only publisher change I agree with is 'Silver Range'->'Firebird Silver'.
> 
All noted and understandable.

> The first year that I checked was your 'Ace 2088' change to 1991. I have a scan of the inlay which clearly says 1989 which also matches other references on the internet, though doesn't mean it's correct I'd like to see some evidence for the change.
> 
No problem at all.  According to the xml entry for Ace 2088, it mentions Summit as the publisher which is indicates that this is a release the occurred after the original 1989 release by Cascade.
A link to Cascade 1989 release at full price can be found here:
[http://www.zzap64.co.uk/cgi-bin/displaypage.pl?issue=049&amp;page=027&amp;thumbstart=0&amp;magazine=zzap&amp;check=1](url)
Links confirming a Summit 1991 release can be found here:
[https://www.mobygames.com/game/c64/ace-2088/release-info](url)
[https://www.giantbomb.com/ace-2088/3030-48467/releases/](url)

> The majority of c64_cass is based on the collection and metadata from the C64 Ultimate Tape Archive V1. This collection has since been updated to V2 and adds over 500 new titles, so c64_cass is due a major update to sync with this collection which will likely supersede any changes to metadata made now.
Thanks for that clarification.  I actually have the V2 set and a sync to the latest set would be worthwhile.

**Comment by scoomby** [comment]
> Why did you add “(Compilation)” to a number of titles? Is it actually part of the original titles?
>
For clarity but clearly I have made a mistake here as this and the title needs to be left alone to be consistent with the C64 Ultimate Tape Archive set

**Comment by scoomby** [comment]
Reverted "compilation" title changes and the majority of the "publisher" changes.
Thanks again for the comments.

**Comment by Pernod70** [comment]
I'm still not convinced on the Ace 2088 year, the inlay clearly says Summit Software 1989. You need to consider that this is likely not a UK release, probably German. I believe Cascade only published in the UK.

The releases of Eagle Empire and Guardian are Dutch releases published by Central Software, we don't yet have the original UK Alligata releases.

Similarly, the Red Max release is Spanish from SERMA, in the V2 set there is an original Codemasters release to be added.

**Comment by scoomby** [comment]
> I'm still not convinced on the Ace 2088 year, the inlay clearly says Summit Software 1989. You need to consider that this is likely not a UK release, probably German. I believe Cascade only published in the UK.
> 
> The releases of Eagle Empire and Guardian are Dutch releases published by Central Software, we don't yet have the original UK Alligata releases.
> 
> Similarly, the Red Max release is Spanish from SERMA, in the V2 set there is an original Codemasters release to be added.

Thanks for your reply.  Considering that these releases occurred over 30 years ago, it is very difficult to provide full evidence for original publisher releases, re-releases and distribution.  I don't want to waste any more of your time on this but suggest that this change is scaled back to 'Silver Range'->'Firebird Silver' and then start updating this software list bring it in line with the V2 set.

**Comment by Pernod70** [comment]
I have no objection to any of the other year changes, especially those where it's obvious the current year refers to the original release rather than the budget re-release.

The task of syncing to the V2 set has been on my list of things to do for over 6 months now, so you're welcome to do this, as long as you use the metadata provided.

**Comment by scoomby** [comment]
Thanks.  I have scaled back the changes further as advised.  Whilst scanning through the last V2 set, I did spot another dump for "Beyond the Ice Palace" published by Elite Systems in 1988.  It appears the Encore budget re-release actually occurred a year later so made that small change to the release year from 1988 to 1989 to reflect.

With respect to synching to the V2 set, yes I plan to use the metadata provided.

**Review by Pernod70 — APPROVED** [review]

**Pull request merged**
