### PR TITLE
sgi_mips: Add new softlist entries from jrra.zone and archive.org

### PR DESCRIPTION
**Pull request by darkstar**
This is part 2 of the new softlist entries from jrra.zone and archive.org. The following was added:
- ImageVision Library 2.5
- Impressario Developer's Kit 1.1 and 1.2
- 3.10 Compiler Maintenance Update for IRIX 4.0.5
- MegaDev 3.0
- RapidApp 1.1
- SCSL Scientific Library Library 1.3
- WorkShop Pro MPF 2.5 w/ Ada Add-On
- MIPSPro 7.2.1 compiler Patches June 1998
- MIPSPro 7.3 and 7.4 Compiler Execution Environment
- ProDev WorkShop 2.5.1, 2.9.1 and 2.9.2

And from archive.org:
- Hot Mix 2 and Hot Mix 3
- IRIX 4.0.5f
- Trusted IRIX /B 4.0.4

The new CHD files are [here](https://s3.au.de:8082/md1-stuff/sgi_mips_part2.zip)

### CODE REVIEW

**Comment by darkstar** [comment]
More softlist entries from jrra.zone:
- Diagnostics 4.0.5J, 6.0 and 6.0.1
- Network File System 6.0
- Sirius Video 6.0
- Trusted IRIS Development Option 4.0.5epl
- IRIS Development Option 6.0
- IRIX 5.1.1.3 Patch
- IRIX 5.2.2 Patches # 2
- IRIX 5.3 Onyx RE/REII Patch
- IRIX 5.3 Patches for Indigo2 250MHz R4400 EX/XZ/XL
- IRIX 5.2, 5.3 and 5.3XFS IP19 Required Patches
- Trusted IRIX /B 4.0.5epl
- IRIX 5.3 with 175MHz and 2MB cache support
- IRIX 5.3 for Indigo2 Impact
- IRIX 6.0
- IRIX 6.5.16 Freeware CD 3 of 3 (CDs 1 and 2 are still missing)

CHD files available [here](https://s3.au.de:8082/md1-stuff/sgi_mips_part2.zip)

**Comment by Tafoid** [comment]
@darkstar In any future commits, can you send any data links to Submit-email instead of posting directly on Github?  We don't want our repository to be viewed as rom distribution hub which Github surely frowns upon.

Thank you!

**Comment by darkstar** [comment]
> @darkstar In any future commits, can you send any data links to Submit-email instead of posting directly on Github? We don't want our repository to be viewed as rom distribution hub which Github surely frowns upon.
> 
> Thank you!

Sure, no problem. Just to be clear, as soon as the PR is accepted I remove the files anyway so the time window is quite small anyway. I can also upload to some FTP or somewhere else, if that would be better

**Comment by darkstar** [comment]
The next batch of softlist entries:

- Digital Media 3.0
- IRIS Development Option 6.1
- NFS 6.1
- IRIX 6.2 Patchsets for IP19, IP21 and IP25
- IRIX 6.2 Fix on Fail patches
- IRIX 6.4 Applications
- IRIX 6.4 OCTANE I/O patches
- IRIX 6.4 Gigabit Ethernet patches
- IRIX 6.4 Recommended/Required patches 09/99

**Comment by darkstar** [comment]
- IRIX Development Foundation 1.2 for IRIX 6.5
- IRIX Development Foundation 1.3 for IRIX 6.5
- IRIX 6.5 Development Libraries
- IRIX 6.5 Beta Base Documentation
- IRIX 6.5.28 Base Documentation
- Varsity Update for IRIX 6.2, 6.3, 6.4 and 6.5 (August 1998)
- WorldView: Japanese for IRIX 6.5.4
- WorldView: Japanese for IRIX 6.5.8
- WorldView: Japanese for IRIX 6.5.10
- WorldView: Japanese for IRIX 6.5.12

**Pull request merged**
