### PR TITLE
Add more softlist documentation based off new dumps

### PR DESCRIPTION
**Pull request by FakeShemp**
Carts for a2600, megadriv, n64 and snes got redumped recently by TeamEurope. Add in newfound information from those dumps to the softlists.

Also remove syvalionp2 as it's simply a bad dump of syvalionp.

### CODE REVIEW

**Comment by etabeta78** [comment]
For the record, I personally disagree on using capitalized letters for chip
labels. I know we don't enforce anymore the check about small letters in
rom names, but I think small letters are more than enough: chip labels are
documented to help people to find easily whether they have an undumped
revision or not, or to fix their cart/pcb using the verified good dumps,
and nobody would think the version does not match only because of
capital/small letters.
As such, the lines where only capitalization is changed are not really
necessary, IMHO

    f.



On Fri, Nov 18, 2016 at 3:17 PM, Rebecca Wallander <notifications@github.com

**Comment by mamehaze** [comment]
and I still think it's just arrogance on the part of the team to consider 'lowercase only' a better / more important standard than 'as is printed on the chip'

I conceded that in cases where colours are used (red dot / blue dot) or graphics / non-romanized text it can be more difficult to represent the labels, but still, when things CAN be properly represented it seems silly not to properly represent them.

**Comment by etabeta78** [comment]
so why it is ok to keep removing blank spaces in the rom names to replace
them with undescores as it happens with arcade roms?
doesn't that represent a way worse lack of faithfulness? still that is *de
facto* our standard practice...

    f.

**Comment by mamehaze** [comment]
"so why it is ok to keep removing blank spaces in the rom names "

if you ask me, it isn't.  if some filesystems struggle with it then MAME could always automatically look for both, but with loading by CRC from containers it's rarely an issue anyway.

also I still think MAME should be storing 'label' and 'position' fields, and combining them to make 'filename' to encourage better documentation.

**Comment by happppp** [comment]
Please use more descriptive commit messages next time. These won't do:
- Formatting
- Oops
- Remember to save this time -_-
- Add note.

**Pull request merged**
