### PR TITLE
New WORKING clones

### PR DESCRIPTION
**Pull request by clawgrip**
-------------------------------------
MotoTour / Zippy Race (Assa version of Tecfri license) [Victor Fernandez (City Game), ClawGrip]

### CODE REVIEW

**Comment by Gurudumps** [comment]
PROMs don't need to be marked as bad_dumps. They are always common across different regions. There are some exceptions but they are rare and usually obvious issues can be seen on screen. If the game is working and looks ok there's no need to mark PROMs as bad, just copy them from the parent set. This has been done probably thousands of times already in MAME and is standard practice.

**Comment by clawgrip** [comment]
Since we found out that Tecfri's Break Thru had different PROMs than the other sets, I'm always afraid of not adding the BAD_DUMP mark, but if @cuavas or any other dev can double-confirm this policy, I'll remove the mark.

Thanks!

**Comment by Gurudumps** [comment]
Sure, but different PROMs would create obvious faults. As I said, if the game works perfect using the parent PROMs just use them. Or ask the guy to dump the PROMs. If he can't dump them because he's using a cheapo chinese eprom programmer, make a simple adapter and read them using an Arduino..... https://www.vintage-radio.net/forum/showthread.php?t=167042&page=3
This is not a one-off unique problem, google and you will find many solutions to read PROMs.

**Comment by cuavas** [comment]
It depends on the kind of PROMs.  Things like address decoding PROMs generally only change if the board uses different size ROMs/RAMs, a different address map, different ROM scrambling to protect against conversions, etc.  There’s some chance that colour PROMs like this could be different between sets, it’s happened before.  Given this is from Victor Fernandez, I’d be somewhat concerned about the quality of the program and graphics ROM dumps.  Does the game to a program ROM check?  Is there any way to verify the graphics ROMs?

**Comment by Gurudumps** [comment]
In this case they are color and lookup PROMs that generally don't change for a simple region change.
Most of the ROMs match other sets.
The ones to redump would be the ones that are different.....
a-00288_assa_m5_mp4.j3
snd.a1
a-00288_assa_m5_mf1.e3

clawgrip: Please ask the guy to redump these listed, and if he can, dump the PROMs (or use an adapter and an Arduino like I suggested above).

**Comment by clawgrip** [comment]
He no longer have the PCB, sorry

**Comment by Gurudumps** [comment]
ok. To answer the question about verifying ROMs, there's no way to verify if they are unique, but there are 2 ways to check them.
First way is do the Tafoid png compare thing. A few pixels difference means a bad dump.
Use ROMCMP to compare against the parent set. 
Zip all the ROMs and put them in a zip called x.zip. Put the parent rom set (rename y.zip) and ROMCMP.EXE into the same dir as the new dump.
Then run....
romcmp -d x.zip y.zip
The result will state if there are any issues.
Someone should run the 2 tests and report back here with the results.

**Comment by Osso13** [comment]
So, there are 3 unique ROMs in this set:
mt1-7.j3: the main program ROM which maps at 0x6000-0x7fff
snd.a1: the audio program ROM
mt1-1.e3: the GFX ROM that MAME loads at 0x000 in the "gfx1" region

mt1-7.j3 seems to be the only one where the differences may be legit. They are at 0x4a1-0x4af and then 0x4b1, 0x4b3, 0x4b5, 0x4b7, 0x4b9 and 0x4bb. This would need to be checked.

snd.a1 suffers from a very similar problem that was already noted in the cobracomc PR: the different bytes are all at X00 addresses (0x100, 0x200, 0x500, 0x700, 0x900, 0xb00, 0xd00, 0xe00). Moreover the error log shows MAME tripping a lot of illegal opcodes and the sound isn't working. I'd say the ROM is bad.

mt1-1.e3 has a single byte (or actually bit, since it's 0x5f instead of 0x7f at 0x158e). I'd consider it probable bitrot.

**Comment by cuavas** [comment]
@clawgrip you really need to have a serious word with Victor about the quality of dumps, and check that stuff is sane *before* opening pull requests.  At this point, it’s requiring a lot of effort to ensure we don’t just go propagating bad dumps.  Sadly, this set is as good as lost now.

**Comment by clawgrip** [comment]
> @clawgrip you really need to have a serious word with Victor about the quality of dumps, and check that stuff is sane _before_ opening pull requests. At this point, it’s requiring a lot of effort to ensure we don’t just go propagating bad dumps. Sadly, this set is as good as lost now.

Yes. It's not easy, believe me. With Víctor or Jordigahan, when I want to be 100% sure about a dump, I usually end up asking them to send the PCBs to be dumped by myself, but it's not always possible.

Jordi is improving his skills, as he's now at least dumping each ROM three times and marking them as bad when getting variable chacksums. I'm talking with Victor to do the same on the ROMs with no match on romident.

It's important to keep both contributing dumps, as they're getting lot of undumped sets, but I agree that we need good and verified dumps.

Thanks. Regards: ClawGrip

**Pull request closed without merging**
