### PR TITLE
Enable option to generate symbols in Release as well as Debug under V…

### PR DESCRIPTION
**Pull request by palazzol**
…isual Studio.  (This is important because debugging Debug builds is too slow)

### CODE REVIEW

**Comment by palazzol** [comment]
It's probably a good idea to add the same lines a little further down to the vsllvm builds, but I didn't do that because I'm not too familiar with that and can't test.

**Comment by cuavas** [comment]
Visual Studio already has problems doing a full debug build with symbols due to how big it gets.  I don’t want it to become impossible to do a full release build with the default project settings as well.  If you’re actually building with the IDE (as opposed to using msbuild) you can turn on symbols in the GUI after creating the projects.

**Comment by palazzol** [comment]
I don't want to affect the default build configuration.  I thought you could ask for extra symbols with 'make vs2019 SYMBOLS=1'.  As you said, you can do manually with the GUI but you need to do it with every project by hand, it's like ~10 things to click and change.  My use case is using vs2019 for development, building a SUBTARGET of fewer drivers, and wanting to do interactive debugging.  I'm not tied to using 'SYMBOLS' if there is a better option to hook up?

**Comment by smf-** [comment]
I think the vsllvm stuff is dead, at least modifying it didn't seem to
affect

make vs2019_clang

which is how I invoke clang builds.


As to how I got that to work, Visual Studio 2019 is supposed to support
clang out of the box (if you select it during installation). However I
never could manage to get it to work with the bundled version of clang,
instead I installed the x64 version from here.

https://releases.llvm.org/download.html#10.0.0
<https://releases.llvm.org/download.html#10.0.0>

I don't remember quite what else I did to make it work, but now if I
load up vs2019-clang\mame.sln and go to Project->Properties->VC++
Directories then the Executable Directories is

$(LLVMInstallDir)\bin;$(ExecutablePath)

and

If I go to Control Panel->System and Security->System->Advanced system
settings->Environment Variables

LLVMInstallDir

is set to

C:\Program Files\LLVM

**Comment by palazzol** [comment]
Just to be clear - with this commit, if SYMBOLS doesn't exist, you get Debug symbols but no Release symbols - this is the default behavior.  If SYMBOLS exists, you get symbols in both Debug and Release.  

To me, this matches the definition of SYMBOLS in the MAME compiling help, reproduced here:

**SYMBOLS
Set to 1 to include additional debugging symbols over the default for the target platform (many target platforms include function name symbols by default).**

If this is not satisfactory behavior - I could come up with a mapping using SYMLEVEL, but there are even more permutations of SYMBOLS and SYMLEVEL to deal with then.

**Pull request merged**
