### PR TITLE
dc.xml - Add games up to J

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
please take note of the comment on Mameworld
http://www.mameworld.info/ubbthreads/showthreaded.php?Cat=&Number=375221

**Comment by FakeShemp** [comment]
I have taken note of it and brought it up before like in https://github.com/mamedev/mame/pull/3137#comment-362750488 and later comments.

I'll continue to use the tosec dumps for now because redump seem to be rejiggering their database to not use GDIs anymore. When that is done it's going to be a good idea to switch over to redump for offset correction and more.

**Comment by rb6502** [comment]
Redump is switching everything to their own private version of clonecd, right?  If so, MAME will never be able to use it.

**Comment by FakeShemp** [comment]
Nope, cue-based like their other dumps apparently.

**Comment by p1pkin** [comment]
@rb6502 why? CloneCD is pretty well documented format, .CCD text file with TOC description + .BIN 2352 sector data + optional subcode .SUB file.
they use private dumping tool, but its source code circulating in closed circles ;)

**Comment by rb6502** [comment]
For "pretty well documented", trurip gets very quiet each time I ask for the documents.

**Comment by p1pkin** [comment]
what kind of documentation ? for CCD format ? I don't think they have any (private) docs about it.
as was said - CCD is well documented and its description can be googled like in minute, so its mainly matter of will. however I don't think there is much sense to add CCD support in MAME, until CHD will not really preserve TOC.

**Comment by DavidHaywood** [comment]
their actual demands were that we rip out CHD format for CDs and ONLY use the trurip CCDs

which misses the point that CHD is used because it's self-contained, single file with hashes etc. and the on-the-fly decompression also means there will be a failure if the data reads as corrupt rather than silently feeding the emulator bad data.

CHD does need improving to support more raw-like structures (including TOC handling) but yeah, the dumping group politics, especially from trurip, is why I think they're best avoided.

they threatened to make their own fork which only supported CCD, which of course they're welcome to do, but I don't think it will gain any ground at all.  If anything their attack on CHD comes at a time when it seems to be gaining more widespread use (although that in turn does mean it is important it is improved / scales to support all needed features)

It's quite a lot of years now since RB originally added CD support to CHD, so it is at least good that some places are starting to see the advantages it has :-)

**Comment by FakeShemp** [comment]
How difficult would it be to update the chd features for someone with no knowledge of mame internals and moderate programming abilities?

**Comment by p1pkin** [comment]
@FakeShemp with no knowledge of mame internals  ? nearly impossible.

**Pull request merged**
