### PR TITLE
twins.cpp: Demote 'twins' and 'twinsed2' to MNW because of MT #07516

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by Tafoid** [comment]
This was marked as fixed a couple years ago - has it re-regressed?
https://mametesters.org/view.php?id=7516

**Comment by clawgrip** [comment]
> This was marked as fixed a couple years ago - has it re-regressed? https://mametesters.org/view.php?id=7516

Let me test again. I'm not sure I used the latest version for testing it. I'll mark this PR as draft until confirmed.

**Comment by angelosa** [comment]
https://github.com/mamedev/mame/blob/13254830f47a13d6cf55ea6bcb8618d4d3aac520/src/mame/drivers/twins.cpp#L75

There's a driver_init kludge for both games. I doubt this has regressed?

**Comment by Tafoid** [comment]
Using current Git I was able to get to Stage 2 on both sets using a cheat.  I'll check 0.239.

**Comment by clawgrip** [comment]
> https://github.com/mamedev/mame/blob/13254830f47a13d6cf55ea6bcb8618d4d3aac520/src/mame/drivers/twins.cpp#L75
> 
> There's a driver_init kludge for both games. I doubt this has regressed?

My bad. I used an old binary by mistake for testing.

Sorry

**Pull request closed without merging**
