### PR TITLE
32x.xml : Lowercase on some description's words

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Lowercase on some description's words (like: Prototype, Set, ....)

### CODE REVIEW

**Comment by ArcadeShadow** [comment]
One doubt, the region name should stay abbreviated on some cases (like Jpn, Euro, ...) or should be change to the complete name (like Japan, Europe, ...)

**Comment by cuavas** [comment]
I’ll merge this for now.  I dislike non-standard abbreviations for countries and languages (ISO codes are the most widely recognised standardised abbreviations).  It’s better to use full names or standard abbreviations.

**Comment by ArcadeShadow** [comment]
OK. On the Next PR I'll change the countries' name to full name, this way it's understandable for everyone

**Comment by etabeta78** [comment]
The problem with full country names is that GBA has sometimes 5 or 6
nations, and it would make fullnames not so nice to read (before Vas
improvements to menus, it would have been not usable).
I'd go for some standard abbreviations (even if then either UK or Germany
will become a bit awkward).

my 2c

**Pull request merged**
