### PR TITLE
mac_hdflop.xml: second batch of additions, rename clarisw20sv

### PR DESCRIPTION
**Pull request by rzero9**
This is the second (and last, for now) batch of additions from WinWorld. There's probably a lot more out there, but that's going to take some time.

---

- Renamed "ClarisWorks 2.0 (Swedish)" to "ClarisWorks 3.0Sv1 (Swedish)", the version number was incorrect

New working software list additions
-----------------------------------
Apple Network Administration Toolkit 1.0 [WinWorld]
Apple Network Administration Toolkit 1.0 Updates [WinWorld]
Apple Network Administration Toolkit 2.0 Updates [WinWorld]
Claris Organizer 2.0v1 [WinWorld]
ClarisWorks 2.0CDv1 (UK English) [WinWorld]
ClarisWorks 3.0CDv1 (UK English) [WinWorld]
ClarisWorks 4.0v4 (US English) [WinWorld]
ClarisWorks 4.0Sv1 (Swedish) [WinWorld]
FoxBASE+/Mac 2.00 [WinWorld]
FrameMaker 4.0.2 [WinWorld]
FrameMaker 5.0 [WinWorld]
Microsoft Excel 5.0 (German) [WinWorld]
Microsoft Excel 5.0a (US English) [WinWorld]
Microsoft FoxPro 2.5c (French) [WinWorld]
Microsoft FoxPro 2.5c (German) [WinWorld]
Microsoft Office 4.2 (Australian English) [WinWorld]
Microsoft Office 4.2 (Danish) [WinWorld]
Microsoft Office 4.2 (Dutch) [WinWorld]
Microsoft Office 4.2 (French) [WinWorld]
Microsoft Office 4.2 (Italian) [WinWorld]
Microsoft Office 4.2 (Norwegian) [WinWorld]
Microsoft Office 4.2 (Swedish) [WinWorld]
Microsoft Office 4.2 (US English) [WinWorld]
Microsoft Office 4.2.1 (US English) [WinWorld]
Microsoft Office Manager 4.2 (German) [WinWorld]
Microsoft PowerPoint 3.0b [WinWorld]
Microsoft PowerPoint 4.0 (German) [WinWorld]
Microsoft PowerPoint 4.0 (Italian) [WinWorld]
Microsoft PowerPoint 4.0 (Swedish) [WinWorld]
Microsoft Word 6.0 (Canadian French) [WinWorld]
Microsoft Word 6.0 (Danish) [WinWorld]
Microsoft Word 6.0 (Dutch) [WinWorld]
Microsoft Word 6.0 (French) [WinWorld]
Microsoft Word 6.0 (German) [WinWorld]
Microsoft Word 6.0 (Italian) [WinWorld]
Microsoft Word 6.0 (International English) [WinWorld]
Microsoft Word 6.0 (Japanese) [WinWorld]
Microsoft Word 6.0 (Swedish) [WinWorld]
Microsoft Word 6.0a (Norwegian) [WinWorld]
Norton Utilities for Macintosh 3.1.3 [WinWorld]
Norton Utilities for Macintosh 3.2.1 [WinWorld]
Norton Utilities for Macintosh 3.5.3 [WinWorld]
PlainTalk 1.2.1 [WinWorld]
QuarkXPress 2.11 (French) [WinWorld]
QuarkXPress 3.3 (English) [WinWorld]
Ready, Set, Go! 4.5a [WinWorld]
Symantec C++ for Macintosh 7.0 [WinWorld]
WordPerfect 3.1 [WinWorld]
WordPerfect 3.5 [WinWorld]

New not working software list additions
---------------------------------------
Matlab 4.0 Student Edition [WinWorld]
Microsoft Works 4.0b (Australian English, Power Macintosh upgrade) [WinWorld]
Microsoft Works 4.0b (German, Power Macintosh upgrade) [WinWorld]
Microsoft Works 4.0b (International English, Power Macintosh upgrade) [WinWorld]
Microsoft Works 4.0b (US English, Power Macintosh upgrade) [WinWorld]
SoftWindows 3.0 [WinWorld]

### CODE REVIEW

**Comment by cuavas** [comment]
Why the non-standard “da” and “aus” suffixes for Denmark and Australia on the MS Office, MS Word and Pagemaker entries?  Did Microsoft and Aldus actually use these abbreviations?

**Comment by cuavas** [comment]
Do the variants tend to follow countries or languages more often?  If they tent to follow countries, ISO 3166-1 country codes would make more useful suffixes, but if they tend to follow languages, ISO 639-1 language codes would be more useful.  Multiple language variants for the same country complicate it further (e.g. Canadian English and French).

**Comment by rzero9** [comment]
In general, my perception is that they tend to follow languages more, at least with the software we have in the list right now. So far I have only found regional splits in English and French, and maybe we'll eventually find something in Spanish with different versions for Spain and Latin America (which, again, is not a specific country), but I don't expect too much else.

**Comment by cuavas** [comment]
>In general, my perception is that they tend to follow languages more, at least with the software we have in the list right now.

Except for English, where Apple had different combinations of US/UK/Australian/“international”/whatever English versions available for every piece of software.

**Pull request merged**
