### PR TITLE
Videosnaps patch (additional file to write: gamename.inp.timecode)

### PR DESCRIPTION
**Pull request by motoschifo**
This patch create a new file during recording inputs (inp.timecode extension) when the user presses the F12 key (take snapshot shortcut).
This file contains all information about the exact time when this action is taken (seconds, frames, elapsed, totals).
With these informations I can generate a video shortplay using automated scripts.

Mame exits when inp playback has finished.

We have done a lot of videos, see the project page on my web site:
http://adb.arcadeitalia.net/videosnaps.php?lang=en

### CODE REVIEW

**Comment by mahlemiut** [comment]
From a quick look through, I don't see much issue with this, it certainly doesn't appear to interfere with INP usage at all.
Couple suggestions I'd give though:
1) Would probably be more useful if it is enabled by an option (something like a -record_timecode/-norecord_timecode option).
2) Exiting after INP playback ends would be highly annoying if you're trying to check scores (which I do regularly).  Should also really be enabled by an option.
3) Any reason to use/switch to the attotime member variables instead of the member functions?

**Comment by motoschifo** [comment]
1) I ca use a command line option -record_timecode. Is it really necessary the -norecord_timecode option? Because with no additional params this file will never written on disk.

2) I can use the same option to exit playback or add another option -exit_after_playback/-noexit_after_playback (default).

3) No reason to use variables instead of functions, probably is an old code (I patched Mame since version 153 and I have changed code during this time). It's right to use use member functions.

I will make the changes, please tell me the name of these command lines options.

**Comment by mahlemiut** [comment]
1) I was thinking of a boolean-type option, so -record_timecode to enable, -norecord_timecode to disable.  (You'll just have to provide -record_timecode, -no is automatic with boolean options)

2) -(no)exit_after_playback is fine

**Comment by motoschifo** [comment]
I changed source code by adding the two options:
 -[no]exit_after_playback (default=no)
 -[no]record_input (default=no)
and added a new UI item to customize shortcut key (default is F12).
Translated also variable names and comments from italian english language.

Do I need to create a new request and close this one?

**Comment by mmicko** [comment]
No need, it is automatically added to new pull request

**Comment by motoschifo** [comment]
Thanks!

**Pull request merged**
