### PR TITLE
Correct Video Timings for Vigilante (M75-A-C)

### PR DESCRIPTION
**Pull request by atrac17**
Vigilante_Readings
Board Measurements

Vert
Vertical Refresh

Horz
Horizontal Refresh

[Vigilante_-_Synchronous.zip](https://github.com/mamedev/mame/files/8630763/Vigilante_-_Synchronous.zip)
sigrok vcd export file

```
// Measured on the original PCB by atrac17
// Pixel clock is 6.144MHz
// H: 256 active pixels, 128 blank pixels
// HSync lasts for 32 pixels, from pixel 40 to 72.
// V blank lasts for 28 lines
// V sync starts 8 lines after Vblank and lasts for 6 lines
// H freq 16.00 kHz
// V freq 56.34  Hz
```

The timing function on the .vcd file is corrupted due to an older version of sigrok.  Above you will find the correct pixel clock timings for the vigilant.cpp - I'm too lazy to update everything, take this information and use it if you'd like!

### CODE REVIEW

**Comment by jotego** [comment]
So it is 56.34 Hz, instead of the 55 Hz currently in the driver

https://github.com/mamedev/mame/blob/c253d43f333003f2a71ac1691616dd04b74038e3/src/mame/drivers/vigilant.cpp#L621

**Comment by atrac17** [comment]
Compiled with the changed info. Seems good to go.

**Comment by startaq** [comment]
You should use `set_raw()` to improve timings. The other methods are legacy.

**Comment by atrac17** [comment]
> You should use `set_raw()` to improve timings. The other methods are legacy.

I really don't mess with mame. I've provided proper information for the timings to be corrected. I guess take the information and do what you guy's want with it?

**Comment by ajrhacker** [comment]
One more note about `set_raw`: the fourth and seventh numbers are not the last displayed, as they are for `set_visible_area`, but the first ''not'' displayed, i.e. the start of the horizontal and vertical blanking areas.

**Review by cuavas — CHANGES_REQUESTED** [review]
This needs to use so-called “raw screen parameters” using `set_raw` rather than the rather kludgy legacy screen configuration method.

**Comment by atrac17** [comment]
Already stated I'm not interested in doing that work. I have my own projects and was passing on the proper information. Use it, don't use it.

**Comment by angelosa** [comment]
Why opening a PR in the first place then?

**Comment by atrac17** [comment]
> Why opening a PR in the first place then?

To be helpful, I didn't realize I'd have to do a different method. I haven't used mame in over 17 years...

**Comment by angelosa** [comment]
Again, you’re making this a lot harder than it really is. It’s just commenting out  `screen.set_refresh_hz(56.34);`, `screen.set_vblank_time(ATTOSECONDS_IN_USEC(1750))`;, `screen.set_size(64*8, 32*8);`, `screen.set_visarea((16*8)-1, (64-16)*8-4, 0*8, 32*8-1);`
Then add a `screen.set_raw(XTAL(6’144’000), 256+128, 16*8, (64-16)*8-4, 256+28, 0, 256);` if I’m getting the values right.

**Comment by jotego** [comment]
If I got it right from your remark, it should be:
```
  //screen.set_refresh_hz(55);
  //screen.set_vblank_time(ATTOSECONDS_IN_USEC(2500)); /* not accurate */
  //screen.set_size(64*8, 32*8);
  //screen.set_visarea((16*8)-1, (64-16)*8-4, 0*8, 32*8-1);
  screen.set_raw(XTAL(6’144’000), 256+128, 16*8, (64-16)*8-4, 256+28, 0, 256);
```

**Comment by jotego** [comment]
I made a separate PR with the changes

**Comment by atrac17** [comment]
> Again, you’re making this a lot harder than it really is. It’s just commenting out `screen.set_refresh_hz(56.34);`, `screen.set_vblank_time(ATTOSECONDS_IN_USEC(1750))`;, `screen.set_size(64*8, 32*8);`, `screen.set_visarea((16*8)-1, (64-16)*8-4, 0*8, 32*8-1);` Then add a `screen.set_raw(XTAL(6’144’000), 256+128, 16*8, (64-16)*8-4, 256+28, 0, 256);` if I’m getting the values right.

I don't write C++. I'll just make an issue for the other 65 games I've pulled correct timings for.

**Comment by jotego** [comment]
> I don't write C++. I'll just make an issue for the other 65 games I've pulled correct timings for.

Apparently it was a misunderstanding about the correct way of conveying the information. It should have been an issue instead of a PR. No big deal. The important thing is that we have made the driver a little bit better.

**Pull request closed without merging**
