### PR TITLE
Add Monkey King 3B SoC skeleton and RS-70 system

### PR DESCRIPTION
**Pull request by daveshah1**
The Monkey King 3B is an emulation-oriented ARM-based SoC by Digital Media Cartridge, a company closely associated with AtGames. The Monkey King family is a successor to their Titan ARM-based SoCs.

The RS-70 is one of the systems using it, with 648 NES and Genesis games on NOR flash in a PS1-esque casing and HDMI output.

This is just the beginnings of the core, all it does so far is print the following debug messages before hanging, but at least that means the memory mapping is vaguely right:

```
Modes:0x00000000
PUT: Setting joystick to mode 0x0, timer to 250us

******************************************************
 MK FIRMWARE INFORMATION
 Mode:       0xB4
 Build Time: May  8 2019 14:09:21
 CPU Clock:  240MHz
 TFS Start:  0x8070000
 Video Buf:  0x6000000
 Stack Top:  0x3001EE8
 IWRAM Size: 32kB
 EVRAM Size: 16384kB
 Heap Size:  6144kB at 0x18200000
 Video Mode: 0
 Video Size: 1280x720x16bpp
******************************************************
```

I can't guarantee that I will be able to finish this given the uncertainties involved, but hopefully this starting point is useful, and I would appreciate feedback on the code style.

### CODE REVIEW

**Comment by MooglyGuy** [comment]
For a skeleton driver, this looks perfectly alright to me.

**Comment by MooglyGuy** [comment]
Actually, there is one thing: I believe we prefer to try to keep parent ROM set names within 8 characters, still. Would you please rectify that? Something like rs70_748 would work fine.

**Comment by daveshah1** [comment]
Thanks, fixed. The 748 was a confusion on my part anyway, it should have been 648 in 1.

**Comment by MooglyGuy** [comment]
When I do a Squash-and-Merge, what name or nickname would you like to be credited under?

**Comment by daveshah1** [comment]
David Shah would be great

**Pull request merged**
