### PR TITLE
tilemap - fix calculation of visible area height and width.

### PR DESCRIPTION
**Pull request by 68bit**
There was no bug noticed there, but the calculation looks wrong, it looks like it intended to calculate the difference between the limits not to add them.

### CODE REVIEW

**Comment by DavidHaywood** [comment]
isn't this going to cause widespread changes in behavior?

**Comment by galibert** [comment]
That's going to change linescroll/rowscroll, and most often when flipped.
I'm curious to see what it's going to actually influence...

  OG.

**Comment by rb6502** [comment]
left+right and top+bottom are clearly not width and height.  So if the comments and variable names are correct, this is a valid fix.  I fully expect this is the sort of bug that was masking other bugs though, and if the carnage is too intense I'll revert it and add a comment that it needs to be re-addressed in the future.

**Comment by Tafoid** [comment]
Yeah, we can try again later.  I move for reverting.
I did quick sampling of some machines which have a flip screen switch with plans to actually check flipped screens and several upright screen are no longer showing correctly as detailed below.  This isn't a full list, just some examples with 10 second screenshots which show shifting or other issues:

avengers
avengers-diff

bking
bking-diff

darkadv
darkadv-diff

dondokod
dondokod-diff

hiticej
hiticej-diff

le2u
le2u-diff

liquidku
liquidku-diff

lwings
lwings-diff

rambo3
rambo3u-diff

skykiddx
skykiddx-diff

torus
torus-diff

viofight
viofight-diff

**Comment by ajrhacker** [comment]
I also think this ought to be reverted and revisited later. The old calculation may have been right, even though the variable names were misleading. It would be better not to merge this kind of apparently untested core change so shortly before the monthly release freeze.

**Comment by 68bit** [comment]
Yes, please revert this one, and thank you for the examples, I'll take a look at some of those when I get time.

**Comment by Robbbert** [comment]
Fixed by PR#5400.

**Pull request merged**
