### PR TITLE
mcs48: Convert ports to devcb (nw)

### PR DESCRIPTION
**Pull request by ajrhacker**
- T0, T1 and PROG handlers are now 1-bit rather than 8-bit
- Eliminate several T0/T1 handlers that DEVCB macros can take care of now
- T0 CLK output emulation (untested)

### CODE REVIEW

**Comment by ajrhacker** [comment]
Some help would be appreciated with sorting out good test cases from totally nonworking drivers and currently HLE'd keyboards. There's also the T0/T1 confusion in pc_kbd/pc83.cpp to check.

**Comment by cuavas** [comment]
This is supposed to correct the serial output so it can talk to serial chips properly, right?  If so, you should be able to remove the hack from `WRITE_LINE_MEMBER(im6402_device::write_rri)` (in src/devices/machine/im6402.cpp) and be able to get keyboard input working in `wangpc` afterwards.  Also, Microprose 3D hardware sound comms uses MCS-51 serial on one side and was broken because whatever's on the other side was converted to read-/write-line, so it should be possible to restore sound to the Microprose 3D games (B.O.T.S.S etc.).

**Comment by happppp** [comment]
MCS51 is a different cpu device

**Comment by cuavas** [comment]
Disregard that, I'm too sleep-deprived to be thinking about this.  MCS51 is a completely different beast.

Well, Gladiator and friends depend on the MCU comms working properly to coin up and read DIP switches, so that should be a half-decent test case for basic functionality.

Joshi Volleyball uses a pair of MCS-48 chips talking to each other for communication between CPUs.  If they lose sync, the game will display an error and lock up.

Not sure which keyboards should be working - I've mostly messed with the 8051-based keyboards.

**Comment by ajrhacker** [comment]
Iskra-1030 is one keyboard that definitely doesn't work with this. Of course, it also wasn't working before. The other MCS-48-based PC keyboards seem to work.

gladiatr seems to work about as well as before, at least once I deleted an old NVRAM that caused it to boot into service mode and count maniacally. (There is an older regression, between 0.181 and 0.182, that causes it to boot up with one credit inserted.) josvolly, though MACHINE_NOT_WORKING, also seems no worse than before.

**Comment by cuavas** [comment]
The one-credit-on-boot in Gladiator is [MT06475](http://mametesters.org/view.php?id=6475) - it's RAM initialisation, definitely not your fault.  The not working flag on josvolly is because we have no clue what the MCU clocks are, whether the two MCUs really run the same program (only dumped one, the other could be subtly different), or what the gate array does.

**Pull request merged**
