### PR TITLE
enable sub-second snapshot timers (nw)

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Comment by ajrhacker** [comment]
Wouldn't it be cleaner to replace `m_delay_seconds` with an attotime variable here?

**Comment by PeterBortas** [comment]
The buddha.cpp no-op changes seem pretty unrelated to the patch description

**Comment by peterferrie** [comment]
> Wouldn't it be cleaner to replace `m_delay_seconds` with an attotime
> variable here?

As I understood the original intention, m_delay_seconds is a whole
number, and m_delay_attoseconds is the fractional part, if any.
Until now, only a whole number was accepted.  I just enabled the
fractional part for the few that wanted it.
It seemed to be the least intrusive change, because the snapquik.cpp
calls a timer adjust() with both parameters.

**Comment by peterferrie** [comment]
> The buddha.cpp no-op changes seem pretty unrelated to the patch description

Yes, this inclusion was unintended as part of this PR, but part of the
wider goal of getting MSVC_LLVM to compile it (which is, incidently,
successful now.  My next step is getting the link to succeed).
I'll try to do better, but for now, it seems to be more disruptive to
back out the change just to separate them.  In the event that the rest
of the PR is not accepted then I will separate them before
resubmitting.

**Comment by peterferrie** [comment]
> cuavas requested changes on this pull request.
>
> It's unintuitive to force the caller to separate the whole and fractional
> parts.  Use an `attotime` so you can use `attotime::from_double(0.5)`,
> `attotime::from_msec(500)` or whatever.

Okay, that's what AJR said, too.  I've made that change.

**Comment by cuavas** [comment]
You still didn't make the requested change, no I have to go and change it myself.

**Pull request merged**
