### PR TITLE
Monon / AX208 - load internal AX208 ROM in device [Peter Wilhelmson, David Haywood]

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
this is the 'if I get hit by a bus' initial PR, I'll continue working on the system emulation.

**Comment by ajrhacker** [comment]
For AXC51-CORE, I think it's probably best to just emulate it from scratch. Too many features are dissimilar to 8051 or have drastic enhancements that would muddy the basic emulation (such as the automatic DPTR modifications). Even the basic on-chip ports and timers are very different.

**Comment by DavidHaywood** [comment]
you'd rather I duplicate an entire CPU core over a handful of changed behaviours such as register auto-inc and timers?

**Comment by galibert** [comment]
Yes.  The 8051 core is very much not generic at this point, that's annoying
for the MT1839 too.  We need some kind of core designed to cope with the
infinite amount of much faster, much customized derivatives.

  OG.

**Comment by DavidHaywood** [comment]
I *really* don't have time for that unless it becomes strictly neccessary.

The 8051 core is garbage, yes, but in all honesty I don't think the mods here are even as great as the DS5002 ones already there.

**Comment by ajrhacker** [comment]
There's also the matter of 1-cycle timings for most instructions, which is essentially incompatible with the goal of rewriting the 8051 for state-by-state accuracy. (Some conventional high-speed clones such as DS80C320 may fit into that model, but just barely.) Eventually 8051 and AXC51-CORE will have to be split.

**Comment by DavidHaywood** [comment]
at best I'll be able to copy+paste the existing core, and remove all the variants, and use that as a base, a complete core rewrite is rather out of the question, especially while we're in "discovery" stage.

**Comment by rb6502** [comment]
I agree AXS51 should be a separate core, but do we have to gate this particular PR on that?  I'd like to see the BIOS start getting mirrored given it was kind of a pain to get out of the thing.

**Comment by galibert** [comment]
No, we shouldn't gate the PR on that, but it's something we should keep in
mind.

  OG.

**Pull request merged**
