### PR TITLE
Midway V Unit linking stub

### PR DESCRIPTION
**Pull request by Risugami**
Linking is working over in https://github.com/Risugami/mame/tree/midvunit_link but the changes are far too destructive to be included in a release version.
This pull request contains the logic required to get it working should a well synchronized external connection be implemented.

### CODE REVIEW

**Comment by Hydreigon223** [comment]
I guess I will have to be the first comment for this -_-. Because I am a noob at coding, I'm trying to figure out how your link code works. I need to figure out hooking a port (split into two) to link Mame instances. This will really come into play when linking more than two Mame instances because any slave unit that isn't on a side sends data to the two corresponding machines at once due to the split port.

I personally think comparing this to real hardware is ideal but man do I rant a bit too much. I hope to eventually find four Cruis'n Worlds in a linked setup (with the same versions).

**Comment by Risugami** [comment]
I changed the majority of the code from being a machine to a modular device that could be loaded from any machine. The running machine now contained up to 4 of those devices. This actually turned out to be rather easy, except for the audio device which segfaults if there is more than one so the 4 devices had to share the same audio device. Next the CPU had to be, well, ruined. Only allowed it to execute one instruction at a time so all 4 devices could run an instruction one after the other. After doing all that the devices were synchronized and could effectively communicate over the linking bus.

**Comment by MooglyGuy** [comment]
> man do I rant a bit too much.

I just want to touch upon this: Yes, you do rant a bit too much. Far too much, in fact. You're consistently heavy on "info", and/or rants, but very light on actual worthwhile progress or real information.

@Risugami tried to allude to this in his comment on a previous PR, because he's polite, but I'm just going to come right out and say it: Just because you're enthusiastic about Midway games, and seeing them linked, doesn't mean that you're inherently qualified in any way to contribute toward that end goal. Full stop. Not everyone gets to be an astronaut. That's not a property of the MAME project, that's a property of life itself.

Your enthusiasm combined with your lack of actual practical results is actively putting off the people who genuinely have the ability to achieve what you're looking for, specifically because they don't want to reward your kind of behavior. No matter how helpful you *think* you're being, you aren't really.

I'm sure that your first reaction to this reply is going to be some self-pitying "woe is me" post, and/or some kind of condemnation against me for daring to criticize someone who wants to "contribute" - I've put that word in one set of quotes, because there aren't enough air-quotes in the world to characterize the sort of "contributions" you're making. So spare me and everyone else the effort of reading such a reply, and actually sit and think about how and why your behavior is being met with the reaction that it is. Perhaps in time, perhaps once you've actually learned to code and have the skills commensurate with your level of enthusiasm, you'll be able to contribute productively. But not now. Not with what you're putting forward.

**Comment by Hydreigon223** [comment]
It took me a while to reply (rather afraid of what Mog would say). Got no other choice but to lay low for a while (mainly due to current real life factors).

**Comment by Risugami** [comment]
From what I can infer, the original plans was for EXCOMINT to pass straight through U111 to COMINT to cause a hardware interrupt. I have a feeling this isn't true for the last version of Cruis'n USA and never for Cruis'n World, thanks to player 4 using that 75176B in the same way the other players are using the other 3. That means EXCOMINT is connected to BD27 and has output enabled by COMRD just like the others. Again, having a clean dump of A-19673 would remove all suspicion but it's clearly not required to get this working.

**Comment by Hydreigon223** [comment]
>primitive linking method
Buggy netcode to be exact (at least from what I been told). This method of linking drove me insane after failed attempts to link two Cruis'n USAs with Makivision LCDs and I'm sure figuring the link system out drove you insane too.

**Pull request merged**
