### PR TITLE
igs/igs009.cpp: Dumped and added a new Grand Prix '98 set 

### PR DESCRIPTION
**Pull request by clawgrip**
New WORKING clone
------------------------
Grand Prix '98 (V100K, set 2) [Taksangs, charlie]

### CODE REVIEW

**Comment by Osso13** [comment]
The program changes are legit, but the 2 u49 differ for only one byte (actually one bit). I believe the older dump is correct (on the right)
immagine

**Comment by clawgrip** [comment]
> The program changes are legit, but the 2 u49 differ for only one byte (actually one bit). I believe the older dump is correct (on the right)

Yes, it's clearly a bad byte... We'll redump it. Thanks!!!!!

**Comment by clawgrip** [comment]
Ok, we've redumped it several times, after cleaning the pins, with two different programmers, and we got the same result (with the bad byte).

Frankly, I'd use the ROM from the other set without flagging it ad BAD_DUMP, but adding a comment on the code, just in case this image surfaces again.

What do you think?

Thanks!!!!!

**Comment by Osso13** [comment]
If it were up to me I wouldn't even add a comment. If romcmp says the ROMs match 99,9999% or similar, the changes should always be checked, because it's almost always just bitrot, especially in GFX ROM (in program ROMs sometimes it happens it's just a hacked copyright year / manufacturer)

**Comment by clawgrip** [comment]
Agree. I've fixed it to use the U49 ROM from the other set.

Thanks again.

**Pull request merged**
