### PR TITLE
New NOT_WORKING machines

### PR DESCRIPTION
**Pull request by clawgrip**
--------------------------
The Fast And The Furious (v3.06) [Victor Fernandez (City Game)]
Guitar Hero Arcade (v1.0.5) [Museo del Recreativo]

### CODE REVIEW

**Comment by Hydreigon223** [comment]
I do have a Target Terror I/O board using an ST7 based microcontroller (one on mine says ST72F63BK4M1). While the board itself is the same as Fast and Furious, the ST7 firmware, internal flash rom, not only differs per game but underwent additional revisions. Some known labels I seen from various different I/O boards (not to mention the large CPLD is adjusted to work with its firmware). The board communicates via usb:

- U6 Fast and Furious Release 3
- U6 Fast and Furious Release 4
- U6 TARGET TERROR Rev 1.01
- U6 TARGET TERROR Rev 1.02

Guitar Hero's I/O board (along with the PC Big Buck Hunter games) consist of only an FPGA configured by an XCF01S (unsurprisingly differs per game). This board communicates with the computer via RS232.

I have no clue if it's possible to dump the firmware from either of these as I'd like to send my Target Terror I/O board to someone who can dump the firmware (unless mine is bad).

**Comment by clawgrip** [comment]
> I have no clue if it's possible to dump the firmware from either of these as I'd like to send my Target Terror I/O board to someone who can dump the firmware (unless mine is bad).

@Hydreigon223 Send me a private message.

**Comment by spiderzsoft** [comment]
> I do have a Target Terror I/O board using an ST7 based microcontroller (one on mine says ST72F63BK4M1). While the board itself is the same as Fast and Furious, the ST7 firmware, internal flash rom, not only differs per game but underwent additional revisions. Some known labels I seen from various different I/O boards (not to mention the large CPLD is adjusted to work with its firmware). The board communicates via usb:
> 
>     * U6 Fast and Furious Release 3
> 
>     * U6 Fast and Furious Release 4
> 
>     * U6 TARGET TERROR Rev 1.01
> 
>     * U6 TARGET TERROR Rev 1.02
> 
> 
> Guitar Hero's I/O board (along with the PC Big Buck Hunter games) consist of only an FPGA configured by an XCF01S (unsurprisingly differs per game). This board communicates with the computer via RS232.
> 
> I have no clue if it's possible to dump the firmware from either of these as I'd like to send my Target Terror I/O board to someone who can dump the firmware (unless mine is bad).

contact me on discord
spiderzsoft#1666

**Comment by spiderzsoft** [comment]
> The Fast And The Furious (v3.06) [Victor Fernandez (City Game)] Guitar Hero Arcade (v1.0.5) [Museo del Recreativo]

contact me on discord
spiderzsoft#1666

**Comment by clawgrip** [comment]
You have incoming requests blocked, please ping me on Discord at ClawGrip#8187

**Pull request merged**
