### PR TITLE
Added Bally Frontier pinball switch names. Fixed incorrect DIP switch…

### PR DESCRIPTION
**Pull request by darren5**
… settings for Frontier and other by35 os40 machines.

### CODE REVIEW

**Comment by Tafoid** [comment]
This machine changed behavior.  It triggers in cycle a lot of inputs as well as displaying numbers in a sequence.  Unsure if it is a regression or not:

bbbowlin - by35.cpp
bbbowlin-diff

**Comment by Quench0** [comment]
@Tafoid, when all dipswitches are off, bbbowlin starts in factory burn in test mode (all lamps flash, displays count and solenoids activate one at a time) which I guess is what you're seeing. So I'd say the dip switch defaults have changed to all off.

I have some updates to this driver I did 2.5 years ago but never got around to submitting. It includes fixes and some more mockup playfields - sorry Darren5 I haven't done Frontier yet. Might be time I updated and submited it..

**Comment by darren5** [comment]
In hindsight I probably should have left all the dips for everything except frontier era (os40) alone.  I just knew they were wrong for later games (like Frontier) and wanted that to be corrected. Sorry about that. I will go back in the next few days and fill in the dips for other by35 versions.

**Comment by darren5** [comment]
@Tafoid I added a new pull request that fixes the default dip switches for bbbowlin and other Bally games that I didn't mean to modify. 

https://github.com/mamedev/mame/pull/5051

**Pull request merged**
