### PR TITLE
sms.cpp: Change NMI to be routed through VDP on SMS systems

### PR DESCRIPTION
**Pull request by enikland2**

### CODE REVIEW

**Comment by ajrhacker** [comment]
Shouldn't NMI IN be implemented here as a line write handler rather than as an input callback?

**Comment by enikland2** [comment]
According to Charles MacDonald's tests, regardless of when the pause button (connected to NMI-IN) is pressed or released in the frame, /NMI is asserted or released always at start of the last logical line (261 for NTSC):

http://www.smspower.org/forums/8161-SMSDisplayTiming#37143

To my understanding is more likely to be the VDP that reads the line state than the line state be written to the VDP.

**Comment by enikland2** [comment]
I implemented /NMI-IN as a line write handler as you asked, AJR.

**Comment by enikland2** [comment]
@ajrhacker or anyone else, is there any problem with the pull request that still remains?

**Pull request merged**
