### PR TITLE
XA work for fearless/superkds - adds sound, promotes to working

### PR DESCRIPTION
**Pull request by mamehaze**
this adds basic execution to XA core.  It emulates enough of the XA to give fearless and superkds working sound.

some considerations
- only the exact forms of the opcodes used so far have been implemented
- no optimizations have been done, use of const, inline use, templates etc. are planned for a future update; code is still primed for debugging and development
- overall structure, code style are not 100% final (see above) and will be adjusted as the CPU is better understood
- peripherals, interrupts etc. are not yet implemented, nor is anything outside of the page zero mode used here due to lack of test cases

Machines Promoted to WORKING
-----------------------------------
Super Kids (S019CN) [David Haywood, XingXing]
Fearless Pinocchio (V101US) [David Haywood, XingXing, Peter Wilhelmsen, rtw]

### CODE REVIEW

**Comment by mamehaze** [comment]
most of the XA ROM just seems to be boilerplate stuff anyway, probably the example code shipped with the device.

functionality is mostly in the External Interrupt 0 handler (vector at 0x80) which contains the command processing logic.

commands are sent from the ARM at via offset 0 of xa_w (I think this is a port, not a range in reality)
0000ccss

cc is the command number, ss is the size in bytes, starting from 1, including this one

it's pretty obvious each time something is written here an IRQ0 should occur on the XA so that it can process the command.

**Comment by mamehaze** [comment]
with the kludged in interrupts the XA will executed the IRQ routine, which reads the command sent by the ARM if I allow it
commands are read via 2 of the IO Ports.

It recognizes both the primary command, and the 'size' parameter.  If the size parameter is >1 the XA does indeed wait for the next command containing the parameter before executing the main command handler.  Unfortunately either due to the crude hookup, or an opcode bug it does currently stall when executing command (83-02) (command 83, with 1 additional parameter) after getting the 0000 parameter write, and entering the command handler for command 83.

Given the relative simplicity of the XA program, and lack of features used by the program this likely isn't very far away from meeting the needs of the games here, even if it will need fleshing out and emulating more accurately if other XA programs which make proper use of the features of the CPU come along.

**Comment by mamehaze** [comment]
I think all the comms are multiplexed on the XA ports btw

Ports 0/2 are the data ports, we've already established that, but they seem to be used to communicate with multiple devices, including the command latch, but also I think the ICS itself, and possibly other devices can be accessed through them.

Port 3 seems like it might be the device address

Port 1 could be used for latching the data, I think 0->1 or 1->0 transitions on each of the bits probably pulls the data in / out to be used by ports 0/2.  Not currently sure how it works.

**Comment by mamehaze** [comment]
yeah, the ICS writes are in here

// happy 6 startup  when initializing channel 000e

ICS2115: Unhandled memory write 4f to 1
ICS2115: Unhandled memory write 0e to 2
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 01 to 3
ICS2115: Unhandled memory write 07 to 1
ICS2115: Unhandled memory write 01 to 3
ICS2115: Unhandled memory write 08 to 1
ICS2115: Unhandled memory write 01 to 3
ICS2115: Unhandled memory write 10 to 1
ICS2115: Unhandled memory write 0f to 3
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 03 to 3
ICS2115: Unhandled memory write 00 to 1
ICS2115: Unhandled memory write 00 to 3
ICS2115: Unhandled memory write 4f to 1
ICS2115: Unhandled memory write 0f to 2
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 01 to 3
ICS2115: Unhandled memory write 07 to 1
ICS2115: Unhandled memory write 01 to 3
ICS2115: Unhandled memory write 08 to 1
ICS2115: Unhandled memory write 01 to 3
ICS2115: Unhandled memory write 10 to 1
ICS2115: Unhandled memory write 0f to 3
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 0d to 1
ICS2115: Unhandled memory write 03 to 3
ICS2115: Unhandled memory write 00 to 1
ICS2115: Unhandled memory write 00 to 3

// fearless startup (command 8302, param 000e)

':xa' (001F34): mcu_p1_w() 02
':xa' (0002D8): mcu_p3_w() d0
':xa' (0002F6): mcu_p1_w() 06
':xa' (0002F9): mcu_p3_w() 50
':xa' (000303): COMMAND READ mcu_p2_r() returning 00 with port3 as 50
':xa' (000314): COMMAND READ LOWER mcu_p2_r() returning 0e with port3 as 50
':xa' (000324): mcu_p3_w() d0
':xa' (000327): mcu_p3_w() f0
':xa' (00103F): mcu_p3_w() e0
':xa' (00104C): mcu_p0_w() 4f with port 3 as e0 and port 1 as 06   // could be case 0x4f: // Oscillator Address being Programmed  (so regselect write?)  (4f should go to port 1 of the ics?)
':xa' (001061): mcu_p1_w() 01
':xa' (001064): mcu_p3_w() a0
':xa' (00106E): mcu_p3_w() e0
':xa' (001071): mcu_p3_w() f0
':xa' (00103F): mcu_p3_w() e0
':xa' (00104C): mcu_p0_w() 0e with port 3 as e0 and port 1 as 01          /// from the param   write to m_osc_select   (which voice we're programming?)  (0e should go to port 2 of the ics?)
':xa' (001061): mcu_p1_w() 02
':xa' (001064): mcu_p3_w() a0
':xa' (00106E): mcu_p3_w() e0
':xa' (001071): mcu_p3_w() f0
':xa' (00103F): mcu_p3_w() e0
':xa' (00104C): mcu_p0_w() 0d with port 3 as e0 and port 1 as 02          (0d should go to port 1 of the ics?)
':xa' (001061): mcu_p1_w() 01
':xa' (001064): mcu_p3_w() a0
':xa' (00106E): mcu_p3_w() e0
':xa' (001071): mcu_p3_w() f0
':xa' (001082): mcu_p3_w() e0
':xa' (00109D): mcu_p1_w() 03
':xa' (0010A0): mcu_p3_w() 60
':xa' (0010AA): mcu_p0_r() returning 01 with port3 as 60
':xa' (0010B7): mcu_p3_w() e0
':xa' (0010BA): mcu_p3_w() f0
':xa' (00103F): mcu_p3_w() e0
':xa' (00104C): mcu_p0_w() 0d with port 3 as e0 and port 1 as 03           (0d should go to port 1 of the ics)
':xa' (001061): mcu_p1_w() 01
':xa' (001064): mcu_p3_w() a0
':xa' (00106E): mcu_p3_w() e0
':xa' (001071): mcu_p3_w() f0
':xa' (00103F): mcu_p3_w() e0
':xa' (00104C): mcu_p0_w() 01 with port 3 as e0 and port 1 as 01          (01 should go to port 3 of the ics)
':xa' (001061): mcu_p1_w() 03
':xa' (001064): mcu_p3_w() a0
':xa' (00106E): mcu_p3_w() e0
':xa' (001071): mcu_p3_w() f0
':xa' (00103F): mcu_p3_w() e0
':xa' (00104C): mcu_p0_w() 07 with port 3 as e0 and port 1 as 03         (07 should go to port 1 of the ics)
':xa' (001061): mcu_p1_w() 01
':xa' (001064): mcu_p3_w() a0
':xa' (00106E): mcu_p3_w() e0
':xa' (001071): mcu_p3_w() f0

**Comment by HappyASR** [comment]
it seems that XA uses gpio to implement host bus emulation mode:
XA_PORT | NAME
---------| ----
P2,P0 | DATA
P1.0/P1.1/P1.2 | ADDR[0]/[1]/[2]
P3.4 | nCS_ICS2115
P3.5 | nCS_CMD_PORT
P3.6 | nWRITE
P3.7 | nREAD

**Comment by mamehaze** [comment]
> it seems that XA uses gpio to implement host bus emulation mode:
> XA_PORT 	NAME
> P2,P0 	DATA
> P1.0/P1.1/P1.2 	ADDR[0]/[1]/[2]
> P3.4 	nCS_ICS2115
> P3.5 	nCS_CMD_PORT
> P3.6 	nWRITE
> P3.7 	nREAD

yeah, it's definitely something along these lines although some other bits in port 1 are used too (probably IRQ related)

**Comment by HappyASR** [comment]
According to the XA disassembly, EXT_IRQ1 might be connected to the ICS2115.

**Comment by mamehaze** [comment]
the annoying thing with the XA program is that it's a little fragile itself, for example if the latch behavior is wrong, and it reads a command with too many paramaters, it doesn't check it's sane, it just reads parameters until it smashes its own stack

**Comment by mamehaze** [comment]
@HappyASR do you fancy trying to debug this?  I don't think I'm going to have any time for the next couple of weeks.  I'm 99% sure we should be able to get something more out of this already, but there are likely some bugs lurking, or the hookup still isn't quite right.

**Comment by HappyASR** [comment]
@mamehaze Sure, I've created a PR in your branch. The fearless works well with sound, but the superkids hangs on the logo screen waiting for the voice playing status to go idle. Should the ICS2115 trigger an IRQ when finishing playing a voice?

**Comment by mamehaze** [comment]
@HappyASR I've merged your PR.  SuperKids does continue if you do something to make a sound (insert coin, press start etc.) but then the sound dies in the boss round anyway.

There is still the unused IRQ on the XA side (we trigger EXT0 for commands, and EXT2 for ICS callback) but EXT1 *is* populated albeit only with a tiny piece of code (no other XA interrupts have anything except boilerplate code, so EXT1 having code is definitely intentional)

**Comment by HappyASR** [comment]
according to MX10EXA's datasheet, there are only 2 EXT_IRQ for this chip
- External interrupt 0
- Timer 0 interrupt
- External interrupt 1
- Timer 1 interrupt
- Timer 2 interrupt
- Serial port 0 Rx
- Serial port 0 Tx
- Serial port 1 Rx
- Serial port 1 Tx

Vector 0x21 is Timer0. The function just decreases two down-counters, which are used in timeout detection in some cases.

Some ARM functions will get stuck checking the voice channel busy status, which should be cleared in EXT_IRQ1. This needs more investigation.

**Comment by mamehaze** [comment]
could it just be that the ARM misses an IRQ due to the brief 'pulse line' way it's hooked up on the ARM?  maybe interrupts should be held until taken?

**Comment by HappyASR** [comment]
> I've merged in your changes. I see you've changed the screen update to 30hz, is it using an interlace mode? or is this VGA output? might be that it should still be 60 but with an IRQ every other frame?

The output is VGA at 60Hz, but the FIQ should be at 30Hz. Please correct that code.
We can hear the sound at half its length if FIQ is triggered every frame

**Comment by mamehaze** [comment]
adjustments have been made.  I think the most important thing now is getting superkds to read the trackball through the XA so that the command processing code can be cleaned up, and the HLE-like part removed entirely.

**Comment by mamehaze** [comment]
https://www.youtube.com/watch?v=dN0V5gqoBlc is how these look at present

**Comment by mamehaze** [comment]
replaced with squashed version https://github.com/mamedev/mame/pull/12617

**Pull request closed without merging**
