### PR TITLE
Fix linking when using external libraries.

### PR DESCRIPTION
**Pull request by 0-wiz-0**
The makefile rules -- when BUILD_* is unset -- did not link the
executables against the external libraries they need.

Signed-off-by: Thomas Klausner <wiz@NetBSD.org>

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
One could make this more fine-grained and link the executables only against the respective libraries they need, but this would have been a much bigger change to the main makefile. Let me know if that would be preferred.

**Comment by firewave** [comment]
What error are you getting? The introduction of BASELIBS was not to use LIBS. Also there was a change earlier, that added some of the external libraries to BASELIBS.

**Comment by 0-wiz-0** [comment]
Really lots of missing symbols in the linking steps, e.g. for deflate, crc32, flac*, ...

**Comment by firewave** [comment]
What tools? Did you pull the latest git since the missing libz and libFLAC symbols have been fixed.

https://github.com/mamedev/mame/commit/b55b45a5a99b8bce694b7ed3cd2d4a00d790f6ae

**Comment by 0-wiz-0** [comment]
This was already fixed by the previous pull request 122.
Thanks for clearing this up.

**Pull request closed without merging**
