### PR TITLE
New Crush Roller clone

### PR DESCRIPTION
**Pull request by MASHinfo**
This Crush Roller set from Kural has no NOPs like MAME's Kural sets Crush Roller (set 3) or (set 4).
They look like bootlegs by comparing the DASMs.
I changed the name to Crush Roller (set 3) and the others to (set 4) and (set 5).

Romset: Crush.zip
1.6E         4096  2752  1998-03-11  15:22   50A1A776
2.6F         4096  2617  1998-03-11  15:22   5B03C1F8
3.6H         4096  2997  1998-03-11  15:22   AE5B39FB
4.6J         4096  2206  1998-03-11  15:23   DDF63743
5.5E         4096  1993  1998-03-11  15:23   B1C86CD7
6.5F         4096  1439  1998-03-11  15:23   B5C14376
6331.4A       256    81  1998-07-14  14:43   63EF3927
82S129.1M     256   139  1998-07-19  21:41   A9CC86BF
82S129.3M     256    24  1998-07-19  21:41   77245366
82S129.4A     256    81  1998-07-19  21:42   63EF3927
82S129.7F      32    32  1998-07-19  21:42   FF344446

### CODE REVIEW

**Comment by cuavas** [comment]
Please make a new branch for this, group interdependent changes in a single commit and use meaningful commit messages.

**Comment by MASHinfo** [comment]
Sorry with Github.com i cannot do this. I tried GIT under Linux Mint with

sudo apt-get install git
mkdir mame
cd mame
git init
git clone https://github.com/mamedev/mame.git
*** Edit files ***
git status
git add *edit files*
git commit -m "New Crush Roller clone"
git remote add origin https://github.com/mamedev/mame.git
git push -u origin master

But i get the 403 error. Please help with this!

**Comment by rootfather** [comment]
First, you have to fork the mame repository, commit your changes to your fork and then open a pull request to get the code from your fork merged to the upstream repository.

After forking (use the "Fork" button at the top of this page, you have to clone your own repository (and not the mamedev/mame.git one), edit, add and commit the files you want to. Then, you have to push the changes to your own repository and open a pull request.

You cannot push directly to the mamedev/mame repository, because you are not a member of the team and you don't have the appropriate rights.

**Comment by MASHinfo** [comment]
@rootfather 
I can't reproduced it. First i am at https://github.com/mamedev/mame
2. Press the "Fork" button at the top right
3. Edit the files in my repository.
4. Press "New pull request" button next "Branch: master"
5. ??? How to push the changes to your my repository and open a pull request.
Can you tell me which button i must press/select?

**Comment by rootfather** [comment]
You have to push the changes to your repository using a git client.

git clone https://github.com/MASHinfo/mame.git
edit the files you want to change in your working directory
git add _files_
git commit -m "Useful commit message"
git push

and then open the pull request to get the changes you did in your own branch merged into the upstream repository.

I highly recommend https://guides.github.com/.

**Comment by MASHinfo** [comment]
This works. Many thanks.

**Comment by rootfather** [comment]
Sounds great, and I see that your PR is already merged.

For the future, I recommend that you try to become familiar with the concepts git follows, e.g. branching, adding upstream repositories and such.

**Pull request closed without merging**
