### PR TITLE
multiple keyboard devices: use required_ioport_array (nw)

### PR DESCRIPTION
**Pull request by shattered**

### CODE REVIEW

**Comment by cuavas** [comment]
There is no need to rename the I/O ports. You can either use an actual array of `required_ioport` (see `device_matrix_keyboard_interface` for an example) which is the preferred way to do this, or you can pass an `initializer_list`of names to the`required_ioport_array` constructor. Please make the change without renaming all the ports.

**Comment by startaq** [comment]
So is the plan to deprecate `required_ioport_array` then?

**Comment by manwithcatears** [comment]
Ultimately I'd like to do that, as `required_ioport_array` is a messy two-deep structure that has to dynamically allocate each element.  The issue is at the moment we don't have a good way to deal with cases where very large numbers of `required_ioport` are required without listing all the names.  It may be possible to do with some kind of generator template, but we don't have one at the moment.

**Comment by rb6502** [comment]
Yeah, I'd like to hear what's correct this week for keyboards too.  I've been doing mine as oldschool as possible because the fashion keeps changing and I can't keep up.

**Comment by mamehaze** [comment]
the example given seems over complicated too, rather than a very simple device to copy.

I couldn't get the intilization working in a very simple case using an array of required_ioports and a list, was having none of it.

**Comment by shattered** [comment]
@startaq recommended to do it this way in https://github.com/mamedev/mame/pull/1117

I'll wait until dust settles before reworking this :)

**Comment by Pernod70** [comment]
I suspect the main issue here is that all ports that were named KBD#, TERM_LINE#, MD# have been renamed to KEY#.

**Comment by cuavas** [comment]
It's not hard to make an array of required_ioport.  You can do it like this:
```c++
class my_device : public device_t
{
public:
    my_device(...)
        : device_t(...)
        , m_ports{
                { *this, "names" },
                { *this, "of" },
                { *this, "ports" } }
    {
    }

private:
    required_ioport m_ports[3];
};
```

I believe AJR has also made it possible to do something like this:
```c++
class my_device : public device_t
{
public:
    my_device(...)
        : device_t(...)
        , m_ports(*this, { "names", "of", "ports" })
    {
    }

private:
    required_ioport_array<3> m_port;
};
```

Either way, there's no need to go renaming all the I/O ports.

The `required_ioport_array` is an ugly structure that actually keeps a collection of smart pointers to the `required_ioport` objects, which themselves contain pointers to the actual I/O port objects.  This means that it has poor locality, which screws up L2 cache usage.  An actual array of `required_ioport` keeps all the objects together in one place.

The reason for not removing `required_ioport_array` is for pathological cases where there are hundreds or even thousands of I/O ports.  Listing them out in an initialiser list quickly becomes unwieldy.  Ideally we could use some kind of generator template to allow this to be done with an array, or failing that, with `std::array`, but we don't have such a template yet.

**Comment by cuavas** [comment]
See dbc1e6cd0e5d2fb57a77404ffda1d8421f28d149 for an example of arrays of both `required_device` and required_ioport` working.

**Comment by mamehaze** [comment]
ok, yes, that is a clearer example.
I was trying to do what you show in the 2nd example

 m_ports(*this, { "names", "of", "ports" })" and the compiler was having none of it

your first example does indeed work tho.

**Comment by cuavas** [comment]
@mamehaze you misread the example - the second case uses `required_ioport_array<3>`

**Comment by mamehaze** [comment]
yeah, that is indeed the mistake I made at the time.

so which is preferable?

**Comment by cuavas** [comment]
Did you read anything at all?

>The `required_ioport_array` is an ugly structure that actually keeps a collection of smart pointers to the `required_ioport` objects, which themselves contain pointers to the actual I/O port objects. This means that it has poor locality, which screws up L2 cache usage. An actual array of `required_ioport` keeps all the objects together in one place.

But I have a plan to make the `required_ioport_array` work better, so eventually either will perform as well as each other.

**Comment by cuavas** [comment]
It is done: `required_ioport_array` and `optional_ioport_array` no longer add a layer of runtime indirection and only have a small additional memory footprint cost and cost to initialise strings over an actual array.  Several types of syntax are supported for initialisation:

    required_ioport_array<5> ports(*this, "port");

Expands to `"port.0"`, `"port.1"`, `"port.2"`, `"port.3"`, `"port.4"` (legacy behaviour).

    required_ioport_array<3> ports(*this, "input_%u", 1);

Expands to `"input_1"`, `"input_2"`, `"input_3"` (format and starting number).

    required_ioport_array<2> ports(*this, { "port", "names" });

Obvious example is obvious.

**Comment by mamehaze** [comment]
yes, I can read, but then you gave 2 examples with no weighting.

anyway, it sounds like it should be easier now, and I think little things like this would be worth documenting in a 'coding tips / recommendations' section somewhere, because it's definitely a case where the preferred use case right now is in the minority.

**Comment by cuavas** [comment]
OK, the legacy form has been removed.  Now there are only two constructors: the freeform one and the one that takes a format and starting number.

**Pull request closed without merging**
