### PR TITLE
Exposing cheat manager to LUA

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by cracyc** [comment]
If you use the lua cheat engine instead you can control it entirely programmatically including adding cheats at runtime.

**Comment by npwoods** [comment]
I actually didn't know there was a LUA cheat engine.  Is the old built-in one deprecated?

**Comment by rb6502** [comment]
Yes, the built-in one is deprecated.

**Comment by npwoods** [comment]
Interesting, I'll have to take a look.

Perhaps the correct strategy for BletchMAME is to try not to piggyback off an existing cheat engine, but to essentially reimplement it.  I already have to reimplement the UX, and something to "poke" the runtime may in fact be less intrusive than trying to harness an existing implementation.

**Comment by cracyc** [comment]
I'd like to see what additional functionality you'd need so users can control the cheats from your ui and the builtin ui.  The lua cheat engine can load existing debugger expression cheats and native lua cheats for lots of additional capability (see this super street fighter 2 hitbox viewer http://www.mamecheat.co.uk/forums/viewtopic.php?t=12412) and it supports hotkeys to enable/disable cheats.

**Comment by npwoods** [comment]
Here is what I have so far:

https://imgur.com/a/jfWDn50

I'm starting to think that the best approach (for BletchMAME) is essentially just to load the cheat files in BletchMAME, and simply create primitives to run debugger expressions on command or periodically.  The MAME cheat engine doesn't really do that much beyond loading and parsing the cheat XML; it just has some trivial logic regarding when to run which flavor of script.  I'm already doing much of the same work so that I can figure out whether to drop down a check box, a button, menu, etc.

**Comment by cracyc** [comment]
I'd note that the lua cheat does the xml and debugger expression parsing and the results are available in a global variable ce (https://github.com/mamedev/mame/blob/master/plugins/cheat/init.lua#L900) so you wouldn't need to do it yourself.  Also since the new style cheats aren't in xml and don't use debugger expressions, they wouldn't be usable like that.  Enabling and disabling from another script isn't trivial right now but would require little work to make it.

**Comment by npwoods** [comment]
Regarding "new style cheats not being in XML" and not using debugger expressions, can you elaborate on that?

I suppose my overall concern is that MAME LUA plugins are really designed to be discrete units, but not really libraries to support other plugins.  I would want the cheat logic, but not the UI.

**Comment by cracyc** [comment]
http://www.mamecheat.co.uk/forums/viewtopic.php?t=12412 is an example, sandboxed lua scripts in a json file.

> I suppose my overall concern is that MAME LUA plugins are really designed to be discrete units, but not really libraries to support other plugins. I would want the cheat logic, but not the UI.

I wanted it and the cheat finder to be both.  The only ui is menu, suppressing it would seem to me to be overkill, it's not intrusive and might be useful to some users of your front end but could be without to much trouble if really needed.

**Review by cuavas — CHANGES_REQUESTED** [review]
I agree with @cracyc – you should piggyback on the cheat plugin.  Detect if it’s loaded and then interact with it programmatically.  Please work with @cracyc to expose the necessary interfaces in the cheat plugin.

**Comment by npwoods** [comment]
Reading @cuavas' message, and the fact that the PR was changed to "changes requested" instead of closed outright, my interpretation is that you're sanctioning code in luaengine.cpp that is specifically aware of the cheat plugin and interfaces it.

This is almost certainly a misinterpretation.

**Comment by cuavas** [comment]
No, I don’t think luaengine.cpp needs to be aware of the cheat plugin specifically.  Either the cheat plugin needs to expose something in the global Lua environment (accessible from other Lua plugins) that allows other plugins to interact with it, or if it’s not safe for plugins to leak global state like this, luaengine.cpp needs to provide some way for plugins to find each other and expose things that .  There shouldn’t be code specific to the cheat plugin, it should be generic enough to allow any plugin to leverage functionality provided by another plugin.

**Comment by cracyc** [comment]
Right now the cheat plugin adds a variable to the global lua state for other scripts to interact with.  I don't think there's a better way to handle it since each plugin is very different in it's capability and many have no functionality that would make sense to expose.  The cheat finder plugin already uses the interface to add test cheats at run time.

**Comment by npwoods** [comment]
So I started poking at the cheat plugin in the LUA console, and I was able to access the list of cheats with `print(_G.ce:list())`.  But I need more control.

My extensions to the existing cheat engine worked by exposing the following:
1. Checking for the existence of on/off/run/change scripts associated with each cheat, as well as the parameter
2. Ability to change the parameter and change the state, which was really just a wrapper for triggering the scripts

At first glance this all seems to be determinable - invoking `_G.ce:get()` should allow me to access the cheat data structures but the jury is out until I actually do it.

**Comment by npwoods** [comment]
Hmmm oddly _G.ce seems to work from the MAME console, but not my plug-in.  Going to have to poke around here.

**Comment by npwoods** [comment]
False alarm - turns out "-plugin worker_ui -plugin cheat" doesn't work but "-plugin worker_ui,cheat" does

**Comment by cracyc** [comment]
This interface is going to need some rethought to accommodate your ideas so it would be helpful to know what you think you'll need to make it work.

**Comment by npwoods** [comment]
Status update:  I'm in the process of changing my LUA code (that previously expected the code in this PR) to run against the cheat plugin.  All and all I'm making good progress, nothing blocking... yet

**Comment by npwoods** [comment]
Status update: I've changed my LUA code to successfully query for all data about cheats (availability of scripts, description, comment etc) with the exception of "state".  Up until now, no changes were required.

Reviewing the code for the cheat plugin to best identify how an external plugin would [de]activate cheats.  Changes may be needed.

**Comment by npwoods** [comment]
Looking at the cheat plugin, I see a lot of code in `menu_callback` that looks like this:

````
		elseif event == "right" then
			if cheat.parameter then
				local param = cheat.parameter
				if param.index == 0 then
					cheat.enabled = true
					run_if(cheat, cheat.script.on)
				elseif param.index == param.last then
					return false
				end
				param.index = param.index + 1
				param_calc(param)
				cheat.cheat_env.param = param.value
				if not is_oneshot(cheat) then
					run_if(cheat, cheat.script.change)
				end
				return true
			else
				if not cheat.enabled and not is_oneshot(cheat) then
					cheat.enabled = true
					run_if(cheat, cheat.script.on)
					return true
				end
				return false
			end
````

While I have access to the `cheat` object.  I do not have access to methods like `run_if`

While I could easily expose these internal methods, the ideal solution from my perspective would be if this was more object oriented, and the `cheat` object had I could invoke methods like `cheat:setEnabled(true)` and `cheat.parameter:setValue(42)` and the logic for executing the scripts would happen for me.

Given hooks like these, I probably have everything I need (!!!)

**Comment by cracyc** [comment]
Yup, I'll work on that.

**Comment by npwoods** [comment]
Awesome, thanks!  I'm glad to see how little had to change to use the LUA cheat plugin!

**Comment by cracyc** [comment]
Okay, i added getters and setters for enable state and the param values.  I checked most of the functionality but it's possible I missed something.  The whole thing could probably stand for some more factoring out of various things that might be useful for scripts but for now if there's something else you need let me know.

**Comment by npwoods** [comment]
Thanks for the quick turnaround!

One concern that I have is that instead of an index and a `set_index` method on cheats, my ideal solution would be to be able to just set parameter values directly.  When a create say a slider in Qt, I can pass it minimum/maximum values and not have to worry about making things usable to someone using arrow keys.

I can get around this, but I'm probably going to be implementing the reverse of `param_calc` to take a parameter value, and figure out an index to pass to `set_index`

**Comment by cracyc** [comment]
set_value is in there, https://github.com/mamedev/mame/blob/master/plugins/cheat/init.lua#L571.

**Comment by npwoods** [comment]
Also, is `cheat:set_enabled(true)` the ideal way to trigger a one-shot cheat?

**Comment by cracyc** [comment]
It might not be ideal but I think that if you call enabled(true) on a one shot the logical result would be to run it.

**Comment by npwoods** [comment]
Ultimately its your call - it works and I'm fine with it, but if you want to change it its easy for me.

Good news - I was able to get BletchMAME to work with the LUA cheat manager, so I'm closing out this PR.

**Pull request closed without merging**
