### PR TITLE
bus/nes: Added support for two dipswitch-based multicarts.

### PR DESCRIPTION
**Pull request by 0kmg**
New working software list additions (nes.xml)
-----------------------------------
31 in 1 (Super Mary) [krzysiobal, NewRisingSun]

Software list items promoted to working (nes.xml)
---------------------------------------
4 in 1 (Mr. Mary 2)

### CODE REVIEW

**Comment by 0kmg** [comment]
I'm not sure about the behavior of the dip switches on these boards or what would be the norm for something like this in MAME. As written this code just checks the status of the dip switches after hard/soft reset. This behaves nicely from a software perspective as it gives clean transitions between games. In reality flipping a switch on the board while running maybe immediately switches banks? This would of course crash the current game until reset was pressed and the newly selected game started.

Here are some photos of the 5-switch cart and board: http://gxemu.blog67.fc2.com/blog-entry-238.html. It's the second cart in the blog (I couldn't find a dump of the 4-switch cart featured first). There should also be a photo for the 2-switch board somewhere on forums.nesdev.com but they've had technical difficulties recently...

**Comment by rb6502** [comment]
Looking at the PCB photos, I can't see any way the switches don't just immediately flip the bank and crash the game, so we'd want it to behave that way in MAME as well.  Use a PORT_CHANGED_MEMBER handler to get live change notifications.

**Comment by 0kmg** [comment]
Thank you, rb6502. Having a starting point for those scary macros helped immensely :) I think I figured it out on the simpler multicart. I'll draft this and come back when I'm satisfied with the revision.

**Comment by 0kmg** [comment]
I've restructured the previous attempt. The simpler 31-in-1 board I'm more confident about because as you can see in the PCB photo there's not much there other than the 5 switches and a few NAND gates.

For the 4-in-1 there has to be SOME logic involved on the board that selects which banks are swappable under which DIP settings—for instance SMB2 requires fixed banks at 0x8000 and 0xa000 set in a way that isn't possible with how the other three games bank at those addresses. I've made assumptions that minimize branching based on the DIP settings. Perhaps when the NesDev forums come back up with a PCB photo someone can make a better conjecture.

**Comment by cuavas** [comment]
These are not DIP switches – they are not in dual inline packages.  They’re PCB-mounted slide switches.  I really don’t like lying and calling things DIP switches when they aren’t.  Really, they should be `PORT_TOGGLE` inputs.  It’s a problem that we don’t have a way to show the state of toggle inputs besides using the artwork system.  We probably need another menu for toggle inputs, like we have one for analog controls.  It’s eventually going to get to the point where we need to put all the input menus behind another item in the top-level menu now that we’ve got so many of them.

**Comment by 0kmg** [comment]
Alright. I think I'll close this for now. I also managed to dig up an archive of the NesDev forum that had a more detailed description of the 4-in-1 based on hands-on analysis of the board, so there's more even work that needs done here.

**Pull request closed without merging**
