### PR TITLE
Regional game names fixes (Spanish special characters)

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by etabeta78** [comment]
I could be wrong, but from the top of my head I think the title screen does
not have these accents and we tried to match title screens (possibly adding
alternative spelling in the alt_title feature).
If the accents are on the game title screen instead, the fixes are 100% fine

   f.

**Comment by clawgrip** [comment]
For the Game Boy Color games I've checked the cart labels and game boxes images on Internet, and all of them shows the accents... I can't find captures of those specific games on Spanish, but the French version of 102 dalmatians uses accents... Why sould the Spanish version not?

I remember lot of games on Nintendo platforms with accents on Spanish, like the "Edición" (Edition) with accent on the Pokémon games.

For the V.Tech and Leap Frog games I've checked the images on internet and the game manuals (that includes game captures), and all of them shows also the accents (on these cases, being educational games I highly doubt they made orotographic errors...).

Thanks. Regards: Tomás
________________________________
De: etabeta78 <notifications@github.com>
Enviado: lunes, 19 de marzo de 2018 15:44
Para: mamedev/mame
Cc: ClawGrip; Author
Asunto: Re: [mamedev/mame] Regional game names fixes (Spanish special characters) (#3362)

I could be wrong, but from the top of my head I think the title screen does
not have these accents and we tried to match title screens (possibly adding
alternative spelling in the alt_title feature).
If the accents are on the game title screen instead, the fixes are 100% fine

f.

**Comment by clawgrip** [comment]
Anyway, I'll check them on an emu, just to be sure...

**Comment by clawgrip** [comment]
Confirmed with the ROMs on an emu,
 the "Super Nenas" game have the accent on title screen. The "102 Dálmatas" game shows the accent on the copyright screen, but not on the title screen because its all capital leters. 

There was an ortographic rule on Spanish (deprecated, no longer valid) that you can omit accents on capital letters (because on old mechanic typewriters they were hardly visible), and even now some people wrongly keep omiting them.

Anyway, being the accent on the copyright screen, the cart label and the game box, I'd say the correct name is with it (that also is the right way to write it).

Thanks. Regards: Tomás

**Comment by etabeta78** [comment]
As I said, if the accents are there on title screen, they shall be in the
softlists too.
I had checked many of the french / german / spanish titles when adding
them, but probably not all of them and therefore I'm very happy that you
fixed these :-)

   f.

**Pull request merged**
