### PR TITLE
qsound.cpp: add sample interpolation

### PR DESCRIPTION
**Pull request by superctr**
This should improve the current HLE sound emulation a bit until the DSP is finally hooked up... I'm still not that sure about the chip frequency (sample rate), it seems a little too low for a DSP but I won't touch that without more knowledge.

### CODE REVIEW

**Comment by happppp** [comment]
I think interpolation belongs in MAME's sound core. Sarayan(OG) has it on
his evergrowing TODO :)

**Comment by superctr** [comment]
The effects from this commit are separate from the effect of improving
the sound.cpp resampler. Both when together will have the best output.

**Comment by happppp** [comment]
A good resampler will interpolate the stream(waveform). If you think about
it, interpolating twice (before mixing channels and after) doesn't have a
difference in the end.

**Comment by superctr** [comment]
Well the interpolation is done to prevent aliasing by the resampling done
by the chip itself (like playing voices at different frequencies). If all
sound chips only played voices at a single frequency, this would be the
case.

**Comment by mamehaze** [comment]
is there evidence that the chip actually does it?

**Comment by superctr** [comment]
I did a small comparison using the Tetris The Grand Master soundtrack (only one I had at hand that sounds like it's taken straight from the PCB), and to be honest, the difference actually seems rather small between the OST, current MAME and my PR (that order in the recording below). The 'QSound' effect is rather noticable though.

https://dl.dropboxusercontent.com/u/25073603/tgm%20comparison.ogg

**Comment by rb6502** [comment]
I'd suggest it should be simple enough for someone to disassemble the DSP code and find out if it's doing interpolation.

**Comment by rb6502** [comment]
I'm going to go ahead and close this pending someone making a serious attempt to disassemble the DSP code and determine if hardware did interpolation or not.

**Comment by Lord-Nightmare** [comment]
superctr and I are working (on and off) on exactly that, actually. Closing is fine for now.

**Pull request closed without merging**
