### PR TITLE
hikara.xml : add 5 carts

### PR DESCRIPTION
**Pull request by mamehaze**
new software list entries
-------------------------
hikara.xml:

user5b : Hi-kara 5-song capacity user cartridge (used, with 4 songs, set 2) (Japan) [David Haywood, TeamEurope]
user5c: Hi-kara 5-song capacity user cartridge (used, with 2 songs) (Japan [David Haywood, TeamEurope]
user10a: Hi-kara 10-song capacity user cartridge (used, with 10 songs, set 2) (Japan) [David Haywood, TeamEurope]
user20a: Hi-kara 20-song capacity user cartridge (used, with 20 songs, set 2) (Japan) [David Haywood, TeamEurope]
bh6kids1: Best Hit Collection Volume 6: Kids' Song 1 [David Haywood, TeamEurope]

### CODE REVIEW

**Comment by mamehaze** [comment]
these will need tracklists
user5b


user5c

**Comment by mamehaze** [comment]
Vol 6 cart
Cart+PCB

**Comment by mamehaze** [comment]
(as far as I know this completes the numbered set for hi-kara too, there were only 8 numbered carts to my knowledge, although there might be some more 'special' release ones without numbers that are still undumped)

**Comment by mamehaze** [comment]
user20a

**Comment by cuavas** [comment]
Quite a few duplicate songs across the user cartridges now.  Looks like TV show theme songs were popular with this download service.  Maybe it was more popular with younger users than the e-kara.

**Pull request merged**
