### PR TITLE
Adding undumped games to the list, pyson > python

### PR DESCRIPTION
**Pull request by Onmp314**
Renamed to Konami Python, adding notes and adding reserves. If there are errors in the code, I am sorry.

P.S. I added a preliminary reserve for Python 2.

### CODE REVIEW

**Comment by happppp** [comment]
This won't compile. Other files to update:
- scripts/target/mame/arcade.lua
- src/mame/mame.lst
- src/mame/arcade.lua

Also, we don't write signatures for small notes, if someone wants to know who wrote what part of the notes, they can check git history.
And I'm a bit surprised why a skeleton driver with hardly any actual source code has 3 copyright holders.

**Comment by Tafoid** [comment]
I initially created the skeleton before we started putting copyright attribution in the drivers.  In 2015 when we started to add these names at the top Guru was added initially then I added myself due to the amount of time and research I did on the driver to get it as (at the time) documented as possible.

As soon as some meat gets on the figurative bones here, I'll happily drop my name from the list.  You could do it now and I wouldn't be bothered by it.

**Comment by Onmp314** [comment]
I cannot modify /src/mame/mame.lst

But next time (if possible) I will remember it.

**Comment by Onmp314** [comment]
Yet this:
https://github.com/Onmp314/mame/blob/patch-3/src/mame/mame.lst
https://github.com/Onmp314/mame/blob/patch-3/src/mame/arcade.flt
https://github.com/Onmp314/mame/blob/patch-2/scripts/target/mame/arcade.lua

**Comment by stilett0** [comment]
"You can't edit..." 

Hang on, are you doing your editing at Github.com?

mame.lst is too large to edit on Github.com.

To make changes to it, you need to learn how to use a git client to check out the code to your desktop/laptop and create a pull request.

On Windows, the official Github Desktop client works, though there are others.

**Comment by Onmp314** [comment]
Will you give me instructions on how to do this?

**Comment by Hydreigon223** [comment]
I'm thinking the pyson driver wasn't originally named python probably to prevent confusion with a programming language of the same name. I could be wrong on that too. If I am correct, maybe changing the driver name to "kpython" could work.

**Comment by MooglyGuy** [comment]
You're not correct.

**Comment by Tafoid** [comment]
Just to clarify..  I was one to add the skeleton driver over 8.5 years ago to MAME at the insistence of the person(s) who provided the initial dumps and using the information at the time that was provided and all research I could muster.  Of course, the proper name for the boardset is known and proven to be "Python" and much more information regarding that platform has made it to the internet and is publcally known,  The fact that Python is also a programming language had no bearing in the naming.

**Comment by Onmp314** [comment]
And that's the reason why I changed my name from Pyson to Python.

**Comment by MooglyGuy** [comment]
That's awesome. We'll be happy to merge the pull request as soon as it's in a state that wouldn't break the build if it were merged. Github has comprehensive documentation on how to use Git. It would be good to familiarize yourself with that workflow, as making blind changes through the Github website is untenable for working with the MAME codebase.

**Comment by Hydreigon223** [comment]
Here is also a detailed explanation on Python 2's startup process: https://gamerepair.info/hardware/4_python_2

Konami really did some evil design with this hardware. The hard drive itself uses some protection partition that also locks the drive itself to the PS2 itself based on the serial numbers of the PS2 unit and hard drive. They also used those OG Sony hard drives accessed from the console itself (unlike System 2X6 which uses more standard means to access its media and has literally no protection). Also, Python 2 hard drives seem to be more prone to failing than System 2X6 from what I noticed. Very rarely did any operator I know have to replace a hard drive for a Time Crisis 4.

The PS2's hardcore crypto abilities along with Konami abusing those abilities in nearly every way possible makes this hardware a pain for operators.

**Comment by MooglyGuy** [comment]
This thread is for providing feedback on the pull request. Neither of your comments are relevant to the discussion at hand, @Hydreigon223. Stop.

**Comment by Onmp314** [comment]
I'm closing because someone else made a proposal.

**Pull request closed without merging**
