### PR TITLE
Scorpion 2: added 12 internal layouts

### PR DESCRIPTION
**Pull request by johnparker007**
Added these layouts:
sc2ptytm1
sc2cpe
sc2casr2
sc2majes
sc2eggs1
sc2prom
sc2cpg
sc2copcl7
sc2town2
sc2suprz1
sc2heypr
sc2prem2

### CODE REVIEW

**Comment by mamehaze** [comment]
I think we might have to turn the DMD device into a small 'screen'

the tag lookups for every 'pixel' (which are handled as lamps) absolutely kill us, and the bigger the XML file is the slower the lookups are, so it makes everything else slow too.

**Comment by johnparker007** [comment]
Ah I did wonder why the emulation for these Scorpion 2 DMD games had slowed to a crawl ;)

Interestingly, when I started doing this, and was using and older version of MAME (from around July 2014 I think it was, I will test when I next get chance), the emulation was running at a perfect 100% on sc2 DMD games.  Then I updated to a recent version of MAME (from 2016), and all the sc2 DMD games ran like treacle!

So I guess it's possible to have them running much faster, and somethings changed in the renderer which makes things slower, so could potentially be fixed without having to write the new 'DMD screen' control... though I totally agree it does seem a little messy/inefficient having all those individual DMD dots declared in the XML file :)

**Comment by johnparker007** [comment]
I just did a quick check, on Mame 0.166, the game "sc2prem" runs at ~600% unthrottled at the Set Pot Values screen on the DMD.  On Mame 0.173, the same game runs at ~50% unthrottled at the same point.

So something between those two versions has changed, that affects the speed significantly, this test was done using the original MAME Internal layouts, none of my new ones involved.

**Comment by james-wallace-ghub** [comment]
It's the accuracy vs actuality argument, we used to have it as a screen
because there was no alternative. If someone was willing to hook it up in
rendlay it would be faster, but the caching of graphic states might be
equally bad.

On 23 Aug 2016 08:55, "John Parker" <notifications@github.com> wrote:

I just did a quick check, on Mame 0.166, the game "sc2prem" runs at ~600%
unthrottled at the Set Pot Values screen on the DMD. On Mame 0.173, the
same game runs at ~50% unthrottled at the same point.

So something between those two versions has changed, that affects the speed
significantly, this test was done using the original MAME Internal layouts,
none of my new ones involved.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/mamedev/mame/pull/1292#issuecomment-241655241>, or mute
the thread

**Comment by james-wallace-ghub** [comment]
I'd also say that if we ever do proper dot matrix alphas (something I've been toying with for ages for SC4), those would be equally bad. I wonder if the best compromise is to set up a full 'row' as a mini screen, so you're sending one 32-bit state as opposed to lots of 1-bit ones.

**Comment by johnparker007** [comment]
If this is just a performance concern, the dot matrix display sc2 games used to run 12x faster in MAME 0.166 compared to MAME 0.173.  The current slowdown is due to a change that has been introduced somewhere between those two versions, not to do with how the DMDs are set up.  

Not saying that it's not inefficient how it's currently done, just that using the current system can work (on my old rig Cor2Duo rig) at 6x the speed of the original, as shown by the 0.166 performance.

**Comment by mamehaze** [comment]
there are some inefficiencies I need to address (tag lookups in the driver) but I think the problem is our string lookups have got slower and slower as code has been modernized.

it's unfortunate, but I'll see what can be done.

**Pull request merged**
