### PR TITLE
Correct descriptions and years

### PR DESCRIPTION
**Pull request by sjy96525**

### CODE REVIEW

**Comment by stilett0** [comment]
Because of your past history of spamming our developers with requests without any end, please understand that your submissions will be under a tighter scrutiny if not rejected outright.

On this Pull Request, the release date changes are probably okay, one of us will need to double-check and confirm your sources.

"Adding Undumped sets" by making up GAME definition ROM set descriptions, even commented out, has a bad history with the project and tends to inspire further requests for ROMs from our end users. If you really feel the need to add this information, a list in the comments at the top of the source file may be better.

(I understand the precedent set by the discrete games like atarittl.cpp, but ROM requests from end users will typically be low for those in comparison to Namco System 23 games).

As for adding version numbers to descriptions, probably helpful but again, one of us will need to verify.

**Comment by sjy96525** [comment]
Alpine Racer (Japan), Dirt Dash (Japan), Time Crisis (Japan), Prop Cycles (Japan), Alpine Surfer (Japan), Ace Driver: Victory Lap (Rev. AD1, Japan), Tokyo Wars (Japan):
http://www.ebay.com/itm/282016498770?rmvSB=true

Ace Driver (Japan):
https://www.youtube.com/watch?v=AvwIssrba94

Alpine Surfer (Japan):
https://www.youtube.com/watch?v=s6Kn3vNmby0

Alpine Racer 2 (Japan):
http://www.ebay.com/itm/281696149616?rmvSB=true

Aqua Jet (Japan):
https://www.youtube.com/watch?v=EfNP9E7xXiQ

Dirt Dash (Japan):
https://www.youtube.com/watch?v=GfnN-PqBRN4

Time Crisis (Japan):
https://www.youtube.com/watch?v=6fsiw392UBo

Tokyo Wars (Japan):
https://www.youtube.com/watch?v=EiMinOZbnG4
http://blog-imgs-55.fc2.com/n/a/m/namconian/tokyo_wars_b.jpg

Cyber Cycles (Japan):
https://www.youtube.com/watch?v=NtZhBb375UE

Prop Cycles (Japan):
http://www5f.biglobe.ne.jp/~zekzek/sample_namco2/35_prop_prop1.jpg
http://retrogameen.up.n.seesaa.net/retrogameen/image/IMG_3151.jpg?d=a1

Final Furlong (Japan):
https://www.youtube.com/watch?v=yP47tQwZotI

Rapid River (Japan):
https://www.youtube.com/watch?v=rrR4tKQe95E

Downhill Bikers (Japan):
https://www.youtube.com/watch?v=w26kA5Esf-U

Race ON (Japan):
http://www.ebay.com/itm/1998-NAMCO-AM-CATALOGUE-VIDEO-FLYER/282016501709?_trksid=p2047675.c100623.m-1&_trkparms=aid%3D222007%26algo%3DSIC.MBE%26ao%3D2%26asc%3D40130%26meid%3D3ce080ab447c4acea363691b1c3d7f92%26pid%3D100623%26rk%3D2%26rkt%3D6%26sd%3D400580685861

500 GP (Japan):
http://www.ebay.com/itm/400580685861?rmvSB=true

Crisis Zone (Japan):
http://www.ebay.com/itm/400970130749?rmvSB=true

**Comment by Robbbert** [comment]
You need to remove reference to sets that are not currently in MAME, and also to remove your spam, or this will be closed.

**Comment by stilett0** [comment]
@sjy96525 , your "evidence that they exists" comes across heavily like "I'd like you guys to buy these for me and then emulate them." due to the number of eBay auction links. That is not going to happen.

Again, putting big long lists of undumped revisions into MAME source isn't terribly productive. Better to submit that information to the guys running Undumped Wiki and the Dumping Union, and even then - they don't accept long lists of requests.

There are rare times that I think you're well-meaning and trying to help, but there's a language barrier in the way (Korean? Japanese?) that causes misunderstanding.

On the other hand, the huge number of times you've emailed unsolicited long lists like this to developers, and hacked around the security at MAMEWorld, are indicative of being a troll and a spammer.

**Pull request closed without merging**
