### PR TITLE
pentagon.cpp: cleanup driver detection

### PR DESCRIPTION
**Pull request by holub**
per #10194 review

### CODE REVIEW

**Review by cuavas — COMMENTED** [review]
Couldn’t you avoid at last some of the flag checking by making the 1MB Pentagon use a derived state class, and then overriding the start and reset members?  Also, checking that `m_beta` is started in `machine_reset` doesn’t make sense – start phase always completes before the first reset phase starts.

**Comment by holub** [comment]
m_beta is not starting but switching to active on reset. active(beta)/inactive(basic48) selects in update_memory()

**Comment by holub** [comment]
Checking beta started is all other the place in spectrum clones. I suspect idea was to support configurations with optional beta. So if no beta started, we avoid it.

**Comment by cuavas** [comment]
> Checking beta started is all over the place in spectrum clones. I suspect idea was to support configurations with optional beta. So if no beta started, we avoid it.

But if there’s no beta, then the device finder will not have found it and dereferencing it to test whether it’s started should just crash with an invalid access.  It only makes sense to test whether it’s started during start phase when you’re not sure what order devices will be starting, or in code that can be called before or after start phase.

**Comment by holub** [comment]
> > Checking beta started is all over the place in spectrum clones. I suspect idea was to support configurations with optional beta. So if no beta started, we avoid it.
> 
> But if there’s no beta, then the device finder will not have found it and dereferencing it to test whether it’s started should just crash with an invalid access. It only makes sense to test whether it’s started during start phase when you’re not sure what order devices will be starting, or in code that can be called before or after start phase.

Here it's not an issue as beta required, just bad heritage. I'll pay attention to other occuraces.

**Pull request merged**
