### PR TITLE
Add vgmplay K054539 supports, add device_rom_interface to K054539

### PR DESCRIPTION
**Pull request by cam900**
vgmplay : Add K054539 Support
qdrmfgp, djmain, konamigq : Moved sample RAM to K054539 address map
plygonet : Add K054321

### CODE REVIEW

**Comment by ajrhacker** [comment]
For the future, it would be really helpful if you made sure your changes actually compiled before opening up a pull request. Most of your recent changes have produced at least one compilation error; I had to fix up the source in half a dozen places after merging this one.

**Comment by Tafoid** [comment]
mtlchamp and clones - mystwarr.cpp
Exception at startup for all sets:

-----------------------------------------------------
Exception at EIP=00000000030894e4 (k054539_device::init_flags(int)+0x0004): ACCESS VIOLATION
While attempting to write memory at 0000000000000d70
-----------------------------------------------------
Stack crawl:
  0000000000228340: 00000000030894e4 (k054539_device::init_flags(int)+0x0004)
  0000000000228390: 0000000000909367 (mystwarr_state::machine_reset_martchmp()+0x0027)
  00000000002283d0: 0000000003611021 (driver_device::device_reset_after_children()+0x0191)
  0000000000228460: 00000000035d0734 (device_t::reset()+0x0464)
  0000000000228490: 000000000366a405 (running_machine::reset_all_devices()+0x0015)
  0000000000228530: 000000000366eae7 (running_machine::soft_reset(void*, int)+0x0187)
  00000000002285d0: 0000000003672a2c (running_machine::run(bool)+0x00dc)
  000000000022f210: 0000000001f3923a (mame_machine_manager::execute()+0x020a)
  000000000022f4c0: 0000000001fa6fd4 (cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x03f4)
  000000000022f630: 0000000001fa7495 (cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x0045)
  000000000022f690: 0000000001f371ea (emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)+0x002a)
  000000000022fe50: 0000000006eed21d (main+0x016d)
  000000000022ff20: 00000000004013f7 (__tmainCRTStartup+0x0247)
  000000000022ff50: 000000000040152b (mainCRTStartup+0x001b)
  000000000022ff80: 00000000773859cd (BaseThreadInitThunk+0x000d)
  000000000022ffd0: 00000000774ba561 (RtlUserThreadStart+0x0021)

**Comment by Tafoid** [comment]
This is from binary made from the last master commit 93cc49dfb8fc5de52969280022c50e32c70b0258

**Comment by trap15** [comment]
I'm pretty sure this regresses djmain to a full-on crash, and this made it to 0.194. Was any testing of the affected games even done here?

**Comment by Tafoid** [comment]
Seems to crash in about 50 emulated seconds - well beyond the regression testing done daily of 10 seconds to check for abnormalities.  We'll need an MT for this one.

**Comment by trap15** [comment]
I more meant did the person that wrote this change test it. It's pretty shameful to submit code that is apparently not able to build _and_ causes the modified games to not even boot. I'll submit an MT.

**Pull request merged**
