### PR TITLE
New working machine added

### PR DESCRIPTION
**Pull request by algestam**
Game & Watch: Popeye (wide screen) [Henrik Algestam]

### CODE REVIEW

**Comment by happppp** [comment]
Just to be clear, you wish to be credited under your real name in the MAME 'whatsnew'?. You also might as well change the one in the copyright-holder list(top of file) =)

**Comment by algestam** [comment]
Thanks for the comment, I've updated the copyright-holder name :) Also updated the name to "Game & Watch: Popeye (wide screen)" to distinguish this version from the tabletop and panorama versions.

**Comment by happppp** [comment]
Ok!

**Comment by happppp** [comment]
It looks like @cuavas used "algestam" in the whatsnew anyway. IMO it should be up to you what (nick)name to be credited with, and only you.

**Comment by DavidHaywood** [comment]
Yeah, I think he needs to respect what is given with the commit, not change credits to 'standardize' things.  It seems to be overstepping the mark a little.

**Comment by algestam** [comment]
I haven't specifically asked @cuavas to change my handle so I can understand that it was kept as before. I'm happy with the updated name in the credits so "there's no cow on the ice" as we say in Sweden ;)

**Comment by andrew-gardner** [comment]
https://www.youtube.com/watch?v=zV_Pwjq7sPc&feature=youtu.be&t=34

**Comment by cuavas** [comment]
The trouble is, if people change names like clothes, it makes it harder to group up changes by contributor, it makes compiling lists of contributors more difficult, it's more work when tracking down copyright holders if (God forbid) we have to do another large-scale licensing effort, etc.

**Comment by happppp** [comment]
Yes it can be annoying if people change their (nick)name. But your reasoning against respecting it sounds about as hard as having to keep a namechange list(either a doc or in your head), for the sake of changing them back into the old ones (aka what you're doing now). TBH I don't think this issue is that important, especially now that Henrik doesn't care. But I'm not buying your reason at all :P 

Hey, let's give an extreme example: someone decides to change their gender and change their (nick)name along with it. Would you keep the old one?

**Pull request merged**
