### PR TITLE
Document parent/child for AntiM on Apple II

### PR DESCRIPTION
**Pull request by Firehawke**

### CODE REVIEW

**Comment by Firehawke** [comment]
This should be the correct form, right? Otherwise I'd be updating each set to point to the newest version every time there's an update.

**Comment by DavidHaywood** [comment]
traditionally the newest set is made the parent, as it's the one people are most likely to want to run.

**Comment by Firehawke** [comment]
The problem with that is that it's going to keep changing every few months-- this program isn't anywhere near as static as what we'd normally do this with.

**Comment by peterferrie** [comment]
We're slowing down on the updates now, though.
I have only one update pending.  Nothing left in the queue after that.

**Comment by rb6502** [comment]
Also, for Anti-M there's no real point to running the older versions, so it's OK if it gets re-parented as Peter updates it.

**Comment by Firehawke** [comment]
Okay, I'll get one more adjustment in within the next 24 hours to cover that.

**Comment by Firehawke** [comment]
Okay, that should be the last adjustment needed I think. @rb6502 -- if this meets your expectations, you can merge it in; I'll leave final call to you. If not, I'll make more edits as directed.

**Comment by rb6502** [comment]
Unfortunately, that doesn't quite cover my feedback.  By MAME convention, the parent set doesn't have version information in the set name.  The exception has been for operating systems: DOS 3.3 isn't the parent of DOS 3.2, for instance.  For Anti-M, I think that the latest version (1.8 now) should have the set name "antim".  If a 1.9 is released later on, then 1.8 would become "antim18" and 1.9 would then be "antim".  You don't have to re-adjust the parent names each time that way.

**Comment by Firehawke** [comment]
Right. I somehow missed that while doing it. Sorry. Easily fixed.

**Comment by rb6502** [comment]
Sorry, I feel like I'm the a**hole now, but the cloneof="antim18" all need to be changed too.  I promise it can be committed then though!

**Review by cuavas — CHANGES_REQUESTED** [review]
Now the older versions are clones of the non-existent `antim18`.  Shouldn’t this fail validation?

**Comment by Firehawke** [comment]
Okay, I need to start completely over and recheck ALL my work because I'm clearly missing the forest for the trees now which means that I've been focusing on the small things too much. I'll get back to you in ten minutes or less.

**Comment by Firehawke** [comment]
You're both correct, and I apologize. I should have validated before committing. That's entirely on me and my rush to get this done.

**Comment by Firehawke** [comment]
Hopefully that should cover it, but if not, as per usual I'll make any other changes needed. Don't feel bad about pointing things out. I don't want to make it sound like I'm using my condition like it's a crutch but it does affect my ability to see the fine details and I often do miss these things so the assistance is appreciated.

**Pull request merged**
