### PR TITLE
cowtipping.cpp: Add partial PIC dump (just the freely readable area) [Recreativas.org]

### PR DESCRIPTION
**Pull request by clawgrip**

### CODE REVIEW

**Comment by MooglyGuy** [comment]
Do we really want to do this? One of the most common criticisms of MAME is that its ROM sets change from version to version.

While we can't typically control that, we can in this case. If the "freely readable area" is not sufficient to actually boot and run the protection device, then there is no point in accepting this pull request. It will simply cause needless ROMset churn.

**Comment by clawgrip** [comment]
Maybe just a comment about the contents of the freely readable zone?

**Comment by DavidHaywood** [comment]
it's useful for verifying a full dump if one comes later, especially if chips end up losing their labels

**Comment by clawgrip** [comment]
I was thinking on avoiding bad dumps mistakenly taken as good ones (as it happened recently with some dumps)

**Pull request closed without merging**
