### PR TITLE
Added lcd-grid shader.

### PR DESCRIPTION
**Pull request by cgwg**
Note that this is currently only compiled for GLSL. Someone with a Windows machine should generate the full set of shader targets.

### CODE REVIEW

**Comment by MooglyGuy** [comment]
I'll take care of this immediately.

But in the future, @cgwg, please be aware that you've chosen the worst possible time to submit these changes. MAME goes into a repository freeze at the start of the last Saturday of every month, in preparation to release onto the last Wednesday of every month.

More than that, this weekend I'm currently preoccupied with working overtime for my paying day-job. I'm going to take an hour's break to ensure that this change gets in in time, but please don't do this to me in the future.

**Comment by DavidHaywood** [comment]
@MooglyGuy it's not a bug fix, so there's no time pressure, it can miss the next release and still be fine, I find your message a little discouraging, I'd prefer people make Pull Requests when they have something, even if it doesn't make the very next release.  Other people have schedules / real life to work around too, which might not agree with the MAME release pattern to which we're subscribed.

**Comment by MooglyGuy** [comment]
@DavidHaywood If it's discouraging that I'm being honest, that I'm incredibly busy tonight, then so be it.

Any other weekend, including a release weekend, I'd jump onto this like white on rice, but I'm dealing with several issues in parallel here. One is that MSYS2 is hot garbage and so I can't use git via its interface, because it presents me with some "unable to join lazy_dir_thread" that not even Google seems to have any results for. Second is that if I try to use git to apply the patch outside of the MSYS2 envrionment, I get an error when creating any previously-nonexistent files, because "/dev/null/" is not recognized due to the lack of an active MSYS2 environment. Third is that I'm actually supposed to be focusing on putting overtime in at my day job, not dealing with these kinds of teething issues. If it were a simple matter of just downloading a set of files and then invoking a shader recompile, I'd do that, but this seems to be the worst of both worlds.

All I'm asking for some accommodation in the future that today is literally the last day possible to get something in for a given release. If the expectation is that it can wait a month, then the submitter can say so. Otherwise, the implied assumption is that it should go in for this release, and so I felt that it should be clarified what the project schedule looks like.

If you'd like all potential contributors to labour in darkness and ignorance without knowing about the overall project release schedule, then that's your business, but me, I think it's better to inform people about when good times are to submit things, and when dicey times are to submit things.

**Comment by cuavas** [comment]
I’ll take a look, I think I have the prerequisites for recompiling shaders.

**Pull request merged**
