### PR TITLE
es5506.cpp: Add device_memory_interface for sample space

### PR DESCRIPTION
**Pull request by cam900**
Use callback for external bankswitching, Modernize save states, Reduce unnecessary functions
taito_en.cpp: Add device_mixer_interface for outputs
ssv.cpp: Use memory_bank for bankswitching ES5506 sample ROMs
macrossp.cpp: Reduce unnecessary memory regions, Fix sound with debugging

### CODE REVIEW

**Comment by rb6502** [comment]
I like this patch for correctness, but can we get performance before-and-after to make sure it's not a major issue?

**Comment by galibert** [comment]
Yeah, update_exbank looks expensive for something done one every sample
read...

  OG.

**Comment by rb6502** [comment]
Yeah.  update_exbank() should be done at most once at the start of generate_samples() for each voice, not once per sample.  It's not possible in MAME's architecture for the CPU to update the bank value during generate_samples().

**Comment by rb6502** [comment]
Thinking about this further, the es5506 shouldn't have a callback for banking at all, because that's not how the hardware works.  There should be 4 address spaces for each of the 4 banks and then the external driver can use bankdev or whatever to bankswitch them.

**Comment by rb6502** [comment]
This is improved performance-wise, but I'm still not happy about the es5506 knowing about external banking, because on real hardware it doesn't.

**Comment by cam900** [comment]
srmp7 bankswitching function is just overall ROM Bank swaps per chip, and it's can be used for other chips and memory_bank compatible.
vgmplay support of ES5505/6 is still unimplemented related to ES5505/6 ROM format.

**Comment by cuavas** [comment]
@rb6502 does commit 2f1c29be0896bf0d74006e165d605ba0c5c2f573 pushed to this after your most recent comment address the issues you had with how banking is handled after the change?

**Comment by rb6502** [comment]
It's much more lightweight than what was originally offered here, but it's still handling external banking inside the chip which is not how hardware works.

**Pull request merged**
