### PR TITLE
megadriv: Metadata update (year)

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Metadata update (year) based on segaretro.org site

### CODE REVIEW

**Comment by ArcadeShadow** [comment]
Two quick questions:

1. There's a lot of games with the word "Prototype" in the description. This should or not be written with a "p" and not "P" in capital?
2. Any reason that the "Marble Madness (Japan)" game isn't a cloneof "Marble Madness (Euro, USA)"?

**Comment by cuavas** [comment]
Disambiguation text should not be capitalised if it isn’t a proper noun or initialism.  Lowercase “p” for “prototype” when it’s there for disambiguation of versions.

I’m not familiar with Marble Madness.  Is the Japanese version just a regional variant of the same game, or is it a completely separate port of the same arcade game?

**Review by cuavas — COMMENTED** [review]
What’s the actual source for these changes to years?  I want to make sure this is actually improving things, and not just churn.

**Comment by ArcadeShadow** [comment]
the source for these changes to years are on the title screen (in some cases) then the confirmation on the segaretro.org or mobygames.com site.
For instance, the "Barkley Shut Up and Jam!" game is marked as the year of 1993 but:
**Title screen:**
image
**Mobygames.com**
image
**Segaretro.org:**
image

They all say 1994

**Comment by 0kmg** [comment]
>     2. Any reason that the "Marble Madness (Japan)" game isn't a cloneof "Marble Madness (Euro, USA)"?

They appear to be quite different. https://segaretro.org/Marble_Madness describes the unrelated separate development tracks.

**Comment by ArcadeShadow** [comment]
> They appear to be quite different. https://segaretro.org/Marble_Madness describes the unrelated separate development tracks.

Yeah, I agree!

**Comment by cuavas** [comment]
Bear with me and excuse my ignorance, but how rigorous are SegaRetro about sourcing stuff like that?  I understand MobyGames is community-driven, so it’s as good as the contributors.

**Pull request closed without merging**
