### PR TITLE
New drivers for Brother wordprocessors/typewriters AX-145, LW-30, LW-350, LW-450, LW-840ic

### PR DESCRIPTION
**Pull request by BartmanAbyss**
Here are drivers for
```
@source:brother_ax145.cpp
ax145		// Brother AX-145 (c) 198? Brother Industries, Ltd.

@source:brother_lw30.cpp
lw30		// Brother LW-30 (c) 1991 Brother Industries, Ltd.

@source:brother_lw350.cpp
lw350		// Brother LW-350 (c) 1995 Brother Industries, Ltd.
lw450		// Brother LW-450 (c) 1992 Brother Industries, Ltd.

@source:brother_lw840.cpp
lw840		// Brother LW-840ic (c) 1997 Brother Industries, Ltd. 
```

These are late '80s/'90s word processors/typewriters with dot matrix LCD displays (except LW-450 which needs an external MDA monitor) and 3.5" disk drives, based on a Hitachi HD64180 CPU (except LW-840ic, which is based on a custom Hitachi H8/3003 CPU). They have a wordprocessor app built in ROM, but can execute additional software from floppy disks.

Please refer to https://github.com/BartmanAbyss/brother-hardware for datasheets, photos, screenshots.
I have put ROM dumps and Floppy images in a private repository. Please post here and I will give you access.

The Brother LW-30 uses a proprietary 3.5" single-sided/double-density 240kb floppy drive.
Here is a tool to create images of those disks using [Kryoflux](https://www.kryoflux.com/?page=kf_features) dumps and much more: https://github.com/BartmanAbyss/brother-diskconv
All other models use standard PC 1.44MB 3.5" floppies

This is my first PR for new drivers, I hope it's up to standard ;)

Edit: Also, I'm not sure why github shows 293 commits?!

### CODE REVIEW

**Comment by cracyc** [comment]
I think you need to rebase this.

**Comment by DavidHaywood** [comment]
+#pragma region(LW-30 Font)
+// fonts ripped from LW-350 ROM
+static const uint8_t lw30_font_normal[]{

ROM data should go in ROM files, not in the source.

**Comment by BartmanAbyss** [comment]
> I think you need to rebase this.

I think I made it worse... I'm new to this git stuff... Any ideas?

**Comment by BartmanAbyss** [comment]
> +#pragma region(LW-30 Font)
> +// fonts ripped from LW-350 ROM
> +static const uint8_t lw30_font_normal[]{
> 
> ROM data should go in ROM files, not in the source.

done

**Comment by BartmanAbyss** [comment]
argh, closing this one and creating a new one!

**Pull request closed without merging**
