### PR TITLE
Adding the Interactive CD Sampler collection

### PR DESCRIPTION
**Pull request by Shideravan**
Contact me for the CHDs

### CODE REVIEW

**Comment by mamehaze** [comment]
what were these made with, nobody can reproduce them from the existing sources (redump.org etc.)

if they're self-dumped, to what standard?

**Comment by Pernod70** [comment]
What format are they in, non of the files have extensions.

**Comment by Shideravan** [comment]
@Pernod70 CHD of course.
In what other format would they be?

**Comment by Tafoid** [comment]
Shideravan,

I know you mentioned "Contact me for the CHDs", but this shouldn't need to be done by any Devs directly.  It is custom for those who add softlist entries or other games to the MAME source to be prepared to make them available for examination and verification and able to be obtained at the time of your submission.

Upload to a filesharing site (sendspace, mediafire, mega, etc) the file(s) in question and then share the link with any active developer privately or send such links to the submission email address: 
submit-email   FTP and other options are also available but you as requested.

As it stands, your psx list additions are in danger of being rejected/reverted due to inability to recreate your hashes with known sources.  Please contact someone regarding this also being able to detail how/what program or hardware was used to produce the dumps.

**Comment by Shideravan** [comment]
Hello, @Tafoid
Well, thanks for the explanation, I really didn't knew what I had to do to share these files.
I had some trouble to send these files to mediafire before (my internet upload bandwith is way to slow for send the files there). I'm trying now to send to a private ftp (thanks oddi).
Also, I'll send you a email with details about these files, just after I finish this (could you please send me an active email which you are using?).
But in general, they are know community dumps, converted using default qchdman options.

**Comment by mamehaze** [comment]
again, you're failing to state what dumps were converted.

are they redump, tosec, or other sources? why did you pick the ones you picked etc?

are you using a proper current commandline CHDMAN or an older version with potentially different output due to different bugs

NOBODY has been able to reproduce these from any 'known community dumps' and the change will shortly be reverted, as it seems they're not from known dumps, or you've done something wrong.

**Comment by Shideravan** [comment]
@Tafoid and @mamehaze 
I send you a PM in the emuversal boards, with all the details about these files and also a link for MEGA for you to download them. If there's any question, please ask me.
Best regards ;)

**Comment by mamehaze** [comment]
for public reading, it has been established that the CHDs were added incorrectly, the SHA1 of the CHD file was added to the list, rather than the internal SHA1 of the CHD content stored in the CHD header.

basically the equivalent of adding the SHA1 of a zip file rather than the SHA1 of the file it contains.  CHD is a container format just like ZIP etc. the SHA1 of the metadata+data contained within it is stored in the header, so that the whole file doesn't need to be loaded on startup to verify you're using the expected image.

**Comment by Shideravan** [comment]
I submitted a fix for the wrong checksums.
https://github.com/mamedev/mame/pull/471

**Pull request merged**
