### PR TITLE
spectrum: fix FE port init value

### PR DESCRIPTION
**Pull request by holub**
spectrum: fix FE port init value

### CODE REVIEW

**Comment by holub** [comment]
It seams to premature to set defaults this way as some quick testing of real 128/+2 actually produce random border color on startup.
Screenshot_20220506-040005_Gallery

**Comment by DavidHaywood** [comment]
real hardware can be 'random' but afaik MAME policy is that things need to be deterministic from a MAME code point of view, otherwise it makes regression testing impossible, and things like inp playback unreliable.

**Comment by DavidHaywood** [comment]
Personally I feel for some cases, like this, MAME needs a 'random seed' that can be specified on the commandline.  This might tie in to the existing rand() functionality in MAME, or something similar.

That way cases like this could be handled in a way that means MAME is always deterministic for any given 'seed' but also that seed can be changed, if you want potentially different random behavior.

**Comment by smf-** [comment]
What is that a screen shot of? The bitmap looks too random for dram power on

I'd expect something more like this.
https://www.youtube.com/watch?v=IocU4fEHAF4&t=1038s

While dram is kinda random on power up, it mostly follows a pretty
stable pattern of 1's & 0's. I believe this is because some bits in the
dram go through an extra inverter.

We probably should support a fixed start up pattern that is roughly what
you would get on a real machine, rather than actually generating random
numbers.

**Comment by ICEknigh7** [comment]
`What is that a screen shot of?`
That's a screenshot of yesterday's real hardware tests, which show different border colors on boot up for the 128K +2 model, as opposed to the 48K Plus' fixed white border:
https://youtube.com/playlist?list=PLyxpjFwna1l0WwUduh_hXrSbuhTcBhJ52

**Comment by holub** [comment]
I've restored this as part of #9711 in order to have any defaults. Let's see how can me make them more precise when desired confirmed.

**Comment by cuavas** [comment]
Relying on the contents of uninitialised memory in the emulator itself isn’t a good idea – it can lead to all kinds of difficult-to-diagnose bugs.

**Comment by ICEknigh7** [comment]
> You need to look at the behavior if left off for a long time.

The +2's behavior on cold boot (after some time has passed) always seems to show four big black-white-black-white columns (as seen in the first attempt [here](https://www.youtube.com/watch?v=Kay7DXmMOTI&list=PLyxpjFwna1l0WwUduh_hXrSbuhTcBhJ52&index=3)), though it still seems to randomly alternate between black and (more uncommon) magenta borders and shows a random number of garbage blocks scattered across the left column.

image


Today's initial border color tests with a Spectrum +2:
- Black
- Black
- Magenta
- Black
- Black
- Magenta
- Black
- Black
- Black
- Magenta
- Black
- Black
- Magenta
- Black

MAME currently always shows this instead:


On the other hand, the 48K seems to always show a white border and eight white-black-white-black-white-black-white-black columns, likely with random garbage blocks scattered across the screen as seen here:
image

MAME currently shows this:

**Pull request closed without merging**
