### PR TITLE
cdi.xml: Metadata cleaning

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Lower case on "Alt" and "Demo" words in the set description.
Replaced the countries' abbreviation by the full name

### CODE REVIEW

**Comment by ArcadeShadow** [comment]
IMO it would be better, instead of having the [DVC] indication on the description, add the tag:
_info name="usage" value="DVC required"_
what your opinion?

**Comment by 0kmg** [comment]
Every DVC game already has a DVC compatibility sharedfeat tag, so I don't think you'd need to add anything? It looks like the DVC is only required for a subset of games, not all games that use it.

Anyway, I also don't see why "[DVC]" needs to be in the descriptions since every one has the compat tag already. My two cents.

**Comment by ArcadeShadow** [comment]
> also don't see why "[DVC]" needs to be in the descriptions since every entry has the compat tag already.

I totally agree

**Review by cuavas — COMMENTED** [review]
While you’re doing this, you can remove the “[DVC]” from descriptions.

Also, what are the numbers like “[8110033V113 50404169 02]” that some TOSEC discs have in descriptions?  It’s not obvious from context.  Should these be in an `info` element to make it clearer what they are and not clutter the descriptions?

**Comment by ArcadeShadow** [comment]
> hat are the numbers like “[8110033V113 50404169 02]” that some TOSEC discs have in descriptions? It’s not obvious from context. Should these be in an `info` element to make it clearer what they are and not clutter the descriptions?

No idea what are those numbers. 
It looks like some kind of serial number of the disc... but not sure about it.
For example: Golden Oldies Jukebox (USA)[310690006-2 50240 109 01]
On the http://redump.org/disc/52710/ site part of this number is the serial.
I can add a `info` element for `serial_number` with that information and remove it from the description.
Do you agree?

**Comment by cuavas** [comment]
Oh, that’s called “CD matrix information”.  Put it in `matrix_info` or `cd_matrix` info elements.  Choose a name that would let someone infer that it’s the CD matrix information text.

**Comment by ArcadeShadow** [comment]
> Oh, that’s called “CD matrix information”. Put it in `matrix_info` or `cd_matrix` info elements or something. Choose a name that would let someone infer that it’s the CD matrix information text.

Done it.

**Pull request merged**
