### PR TITLE
hash/nes.xml: add three working NES homebrew games

### PR DESCRIPTION
**Pull request by chungy**
New working software list items (nes.xml)
-----------------------------------------
D-Pad Hero (version 1.0)
D-Pad Hero (version 1.1)
D-Pad Hero II

The latest version of the games are available at https://dpadhero.com/Download.html

D-Pad Hero 1 1.0 can be found on the wayback machine at https://web.archive.org/web/20100110052408/https://dpadhero.com/Download.html

### CODE REVIEW

**Comment by chungy** [comment]
The policy on homebrew isn't entirely clear, but since there seems to be a pattern of only archiving things produced as hardware (regardless of licensed status...), I'd note these games were available on cartridge at one point:

* https://web.archive.org/web/20130708003620/http://www.thenesdump.com/games/homebrew/dpad.htm
* https://web.archive.org/web/20130707235721/http://www.thenesdump.com/games/homebrew/dpad2.htm

It's unlikely D-Pad Hero 1.0 was on cartridge, but I still feel it's nice to keep it around.

**Comment by ICEknigh7** [comment]
Homebrew should be fine, as long as it's not just mods of existing games.

**Comment by chungy** [comment]
These are originals :)

**Comment by rb6502** [comment]
Console/computer homebrew is fine, it doesn't even have to have been on a cartridge.

**Pull request merged**
