### PR TITLE
upd765.cpp: Set 'No Data' flag when FDC cannot find sector

### PR DESCRIPTION
**Pull request by AmatCoder**
This fixes Amstrad CPC games with speedlock version D/2.1 protection

### CODE REVIEW

**Comment by AmatCoder** [comment]
Ping to @mizapf

**Comment by galibert** [comment]
That sets the ND flag each time the floppy sees a sector header that
happens not the be the one it searches from.  That does not make much
sense...

**Comment by AmatCoder** [comment]
Where can I set the flag?

Commit 54f91cc removes flag from SCAN_ID_FAILED substate because it apparently breaks HX5102 floppy functionality.

I do not see alternatives, I'm afraid.

**Comment by AmatCoder** [comment]
I rewrote the patch, maybe this is more acceptable...

**Comment by Lord-Nightmare** [comment]
The UPD765A/B datasheet doesn't flat out say how ND works, but based on its wording (and the description of MA on the intel 82072 and 82077 datasheets), I'm guessing it works like this:

If the UPD765 is issued a READ DATA, READ DELETED DATA or SCAN command, and within the next full disk rotation (i.e., encountering the disk index pulse twice) it does not see a [*1] mark corresponding to the cylinder/sector/head specified as parameters to the command, it will set this bit.
If the UPD765 is issued a READ ID command, and within the next full disk rotation (i.e., encountering the disk index pulse twice) it does not see ANY valid address marks on the current track, it will set this bit.
If the UPD765 is issued a READ TRACK command, and within the next full disk rotation (i.e., encountering the disk index pulse twice) it cannot find the [*1] mark of the first sector on the track, it will set this bit.

[*1] Whether this means address mark, data mark, or both is unclear. Its possible that ND is equivalent to the MA bit, but it concerns itself only with the IDAM (the header for the data mark corresponding to the prior address mark) rather than an address mark. Or, particularly for when Reading a specific sector, if a sector has an address mark but no data mark and the UPD765 encounters another address mark before it sees the IDAM of the data mark, it will set ND since the data mark wasn't found.

This would probably be best figured out with some hardware tests of some disks with deliberately corrupted or missing address and data marks on them, if anyone feels like doing that.

**Comment by AmatCoder** [comment]
According to this: http://cpctech.cpc-live.com/docs/upd765a/necfdc.htm

**Read data:**
> [...] If the FDC detects the Index Hole twice without finding the right sector, (indicated in "R"), then the FDC sets the ND (No Data) flag [...]

 R stands for the Sector Number which will be read (or written).

**Read ID:**
> [...] If no proper ID Address Mark is found on the diskette, before the index hole is encountered for the second time then the MA (Missing Address Mark) flag is set [...], and if no data is found then the ND (No Data) flag is set [...]

**Read Track:**

> [...] The FDC compares the ID information read from each sector with the value stored in the IDR, and sets the ND flag if there is no comparison. [...] If the FDC does not find an ID address mark on the diskette after it senses the index hole for the second time, then it sets the MA (missing address mark) flag [...]

But the point is that, right now, ND flag is never set...and this is a regression because flag was being setted with 0.198 and previous versions.

**Comment by DawnKlingerRoberts** [comment]
I agree

Zookeeper

**Comment by mizapf** [comment]
Sorry that I missed this discussion. Is there any solution yet? As I noted in upd765.cpp, setting the ND bit when there is no address mark will immediately break the HX5102 floppy drive.

**Comment by AmatCoder** [comment]
@mizapf 

With my patch, ND bit is set on SCAN_ID substate instead on SCAN_ID_FAILED substate.

This should work with the HX5102 floppy drive. In pseudocode:

```
start_scan()
{
  st1 = ST1_MA;  // address mark is set at start
  [...]
  case SCAN_ID:
       [...]
       st1 &= ~ST1_MA;  // address mark is unset
+++    st1 |= ST1_ND;  // NEW: ND bit is set

        if(!sector_matches())
        {
          [...]
          return;  // now ND bit is correct. Speedlock protection works.
        }

+++  st1 &= ~ST1_ND; //NEW: ND bit is unset
     [...]
     live_start(fi, SEARCH_ADDRESS_MARK_DATA); // this set address mark with HX5102 because 
                                              // FM/MFM mismatch. Now it works because ND 
                                              // is not set on SCAN_ID_FAILED substate.
     return;
}
```

**Comment by galibert** [comment]
I don't get it.  What does your change change?

SCAN_ID means "I've just finished reading an ID, let's check it".  Setting
ND unconditionally at that point makes no sense.

From what I understand, the HX wants, when nothing can be read, to have MA
set but not ND.  What does speedlock want exactly?

  OG.

**Comment by AmatCoder** [comment]
> SCAN_ID means "I've just finished reading an ID, let's check it". Setting ND unconditionally at that point makes no sense.

I've done pretty much the same as this (SCAN_ID substate on _read_track_continue_ function) : 
https://github.com/mamedev/mame/blob/69902ee2b311831f18ed0f838b8493a58cc8c66d/src/devices/machine/upd765.cpp#L2116-L2120

Is this acceptable here but not on _read_data_continue_ function?

> ...
> From what I understand, the HX wants, when nothing can be read, to have MA set but not ND. What does speedlock want exactly?

Speedlock wants the ND flag setted when sector is not found. As the specification says:

 _[...] If the FDC detects the Index Hole twice without finding the right sector, then the FDC sets the ND (No Data) flag [...]_

**Comment by mizapf** [comment]
The patch seems to work for the HX5102, as far as my tests showed. This is method "read_data_continue", right? (lines 1760 and 1772 after inserting)

**Comment by AmatCoder** [comment]
Yes, right.

Patch also includes ND flag setting on _"write_data_continue"_ for the sake of completeness, but it is not really necessary for speedlock protection.

**Comment by mizapf** [comment]
I'm not sure what effect a patch in write_data_continue might have. It is somewhat difficult to conceive a test that has no read operation before a write operation; maybe a direct sector write. Once the density has been determined, it is kept by a flag, until reading fails again, e.g. after swapping the disk.

**Comment by AmatCoder** [comment]
I'm just followed the specification:

> ND (No Data): During execution of Read Data, Read Deleted Data, Write Data, Write Deleted Data or Scan Command, if the FDC cannot find the Sector specified in the IDR(2) register, then this flag is set.

And flag was being setted on _"write_data_continue"_ before 54f91cc commit.
But feel free to skip that part of patch if you are unsure.

**Comment by mizapf** [comment]
I just had a closer look. Your patch obviously does not affect the HX5102 operation, as I saw: The location of st1 |= ST1_ND is after the CRC check, which is never reached when the density is wrong; accordingly, the ND flag will never be set when MA is set. Good for HX5102.

So does it work for you? - Supposed that there is at least one CRC check on that track that was positive, the ND flag is set and only reset when the matching sector shows up. If that is good for Speedlock, fine.

I guess that patch also makes sense in write_data_continue, when the tests for CRC and sector_matches are swapped.

As for read_track, there is no way for checking this with the HX5102; it never uses that command.

For read_id_continue, I'm not sure whether ND makes sense because there is no search for a desired sector.

**Comment by AmatCoder** [comment]
> So does it work for you? - Supposed that there is at least one CRC check on that track that was positive, the ND flag is set and only reset when the matching sector shows up. If that is good for Speedlock, fine.

Yes. Speedlock protection is based on one intentionally malformed sector that can not be copied.
CRC check is good but FDC can not find sector. Then the program checks specifically for ND bit and if it is not set then refuses to continue loading.

> As for read_track, there is no way for checking this with the HX5102; it never uses that command.

ND flag is never set with Read Track command (though it can set the MA flag)

> For read_id_continue, I'm not sure whether ND makes sense because there is no search for a desired sector.

ND is set if there is an error. Quote from specification:

_"During executing the READ ID Command, if the FDC cannot read the ID field without an error, then No Data flag is set."_

**Comment by mizapf** [comment]
I just tried with st1 |= ST1_ND|ST1_MA in read_id_continue/SCAN_ID_FAILED (the formerly commented version) and could not find any problem with the HX5102; it is still properly recognizing the density. (I tried loading/saving files and formatting the medium.)

**Comment by AmatCoder** [comment]
I'd like to get some update on this...Patch is finally rejected?

**Comment by mizapf** [comment]
No, the patch seems OK. As I said, I applied your patch, and the HX5102 keeps working. Shall I apply the patch, or do you want to merge your commit?

**Comment by AmatCoder** [comment]
I have not write access to repository, but you should be able to merge the commit. Thanks!

**Pull request closed without merging**
