### PR TITLE
Create GitHub Action to validate hash XML files

### PR DESCRIPTION
**Pull request by startaq**
This GitHub Action will run on any commit or pull request that changes a file in the "hash" directory. It will do a simple xmllint run for the HSI files and will check the softwarelist XML files against their DTD.

### CODE REVIEW

**Comment by cuavas** [comment]
This is going to fail on that completely empty C64 software list.  Do we want to update the DTD to allow empty software lists while we’re at it?

**Comment by startaq** [comment]
Does the empty softwarelist serve any special purpose? It can always be re-created if there is actual content.

**Comment by Tafoid** [comment]
I'd say drop it.  It has been in source for 10 months and no one has bothered to populate it with even one entry.

**Comment by angelosa** [comment]
I honestly don't understand what's "cleanly" for in "Commodore 64 cleanly cracked disks". 
That makes it eligible for nixing imho.

**Comment by cuavas** [comment]
Clean cracks really seem to be something associated with the Apple II scene and 4am in particular.  I’m starting to question whether there’s an equivalent for C64, too.

**Comment by rb6502** [comment]
Clean cracks definitely aren't an Apple II specific concept, I've heard of them being done on other machines.  The idea is that there's no defacement and no content removed or changed.  The resulting disk works exactly as the original did, it's just copyable.

**Comment by cuavas** [comment]
Will the C64 and C128 drivers fail validation because a referenced software list is missing, or does that not cause an error?

**Comment by Robbbert** [comment]
Should not cause an error; squale had a non-existing software list for years, until it was recently removed
https://git.redump.net/mame/commit/?id=cf08a0d606714904bba6c83d565b3d78d89d2f9a

**Comment by darkstar** [comment]
Because I forgot this in the past:
Could we also check the equivalent of `mame -validate` to make sure none of the identifiers are too long etc.?

I know that this would require a full MAME build, but maybe the logic behind it could be re-created in a few lines of xslt or python?

**Comment by cuavas** [comment]
> I know that this would require a full MAME build, but maybe the logic behind it could be re-created in a few lines of xslt or python?

The trouble with doing that is it needs to be kept in sync.  You can validate your software list changes without having to rebuild MAME – I really don’t understand how so many pure software list change pull requests get submitted that either have invalid XML or haven’t been validated.

**Comment by darkstar** [comment]
> > I know that this would require a full MAME build, but maybe the logic behind it could be re-created in a few lines of xslt or python?
> 
> The trouble with doing that is it needs to be kept in sync. You can validate your software list changes without having to rebuild MAME – I really don’t understand how so many pure software list change pull requests get submitted that either have invalid XML or haven’t been validated.

I understand the in-sync requirements, but how often do these rules actually change? The softlist code has not changed much in recent years.

And I didn't mean that validating softlists requires a full MAME rebuild, but doing so in the CI/CD pipeline requires the MAME executable, which has to be built first

**Pull request merged**
