### PR TITLE
Adding Unitron APII+ (Teclado Inteligente) as another brazilian apple 2 clone …

### PR DESCRIPTION
**Pull request by felipesanches**
… (this one has got a dedicated CPU for the "smart keyboard")

### CODE REVIEW

**Comment by rb6502** [comment]
Do you have any information about this "intelligent keyboard" - how it's hooked up, or what the CPU type is?

**Comment by felipesanches** [comment]
The CPU is labeled 8404 (presumably yymm timestamp) and SYE6507.

**Comment by felipesanches** [comment]
I don't see any XTAL. So it may be using the CLOCK signal from the main-board.

**Comment by felipesanches** [comment]
unitron_apii _ti_keyboard_pcb

**Comment by felipesanches** [comment]
unitron_apii _ti_keyboard_pcb_back

**Comment by balr0g** [comment]
Probably a second-sourced MOS 6507 (smaller-package version of the 6502 also used in the Atari 2600)?

**Comment by rb6502** [comment]
Yup, likely a Synertek second-sourced MOS 6507.  Thanks!

**Comment by ricardocontieri** [comment]
Hi there,

This board is closer to this Videx Keyboard enhancer:
http://apple2online.com/web_documents/videx_enhancer_ii_installation___operation_manual.pdf

Unitron changed the roms so that PT-BR characters  were made available.

On the Apple II "red book" the connector is reasonably documented.

And yes, it runs a 6507, close by to an Atari processor.

Let me know if I can help any further.

Thanks,

Ricardo

**Comment by rb6502** [comment]
Interesting!  Thanks for the detail.

**Comment by mnaberez** [comment]
> The CPU is labeled 8404 (presumably yymm timestamp) and SYE6507.

...

> Yup, likely a Synertek second-sourced MOS 6507.

On the [Synertek datasheets page](http://6502.org/documents/datasheets/synertek/), you can download the 1981-1982 Data Catalog.  The `SYE` family is covered on page 3-65 in the catalog.  The `E` means extended temperature range.  The specs otherwise look the same as the MOS 6507.

**Pull request merged**
