### PR TITLE
New working clone added

### PR DESCRIPTION
**Pull request by algestam**
New working clone added
----------
Merry Cook [algestam]

New machine marked as NOT_WORKING
----------------------------------
Game & Watch: Chef [algestam]

### CODE REVIEW

**Comment by happppp** [comment]
Hmm, fine by me. You could do what I did with mmouse and egg and add a bad quality SVG based on photos. But it's a waste of time since gnw_chef will hopefully be scanned soon.

**Comment by algestam** [comment]
Thanks! I'll check for decent photos and eventually create a lower quality SVG which can be used as a placeholder until we get a proper scan. Would though prefer to have the actual game so that the dump can be verified as well.

**Comment by happppp** [comment]
Nah seriously it's not necessary. We can wait for it, I'll send you an email.

**Comment by algestam** [comment]
Great, thanks!

**Pull request merged**
