### PR TITLE
namcos2_sprite.cpp - use extra bit on x coordinate, prevents large oversized bad sprites in finallap2/3 and suzuka 8 hours

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by DavidHaywood** [comment]
this doesn't improve suzuka 8 hours 2 as much, but I think that's a different problem, maybe timing related, as it seems to be drawing half complete lists at times.

for final lap 2/3 instead, the game doesn't remove sprites from the list until they're quite far behind the camera, and have a very large zoom factor, at this point they're also using an extra x-coordinate bit, which keeps them off the screen, otherwise they wrap back on and you get huge unwanted graphics after each large object you pass.

**Comment by angelosa** [comment]
fwiw Suzuka 8 Hours 2 posirq seems to happen too early, cfr. tunnels in Bayside track (which leaves noticeable gaps in the drawing).

**Comment by DavidHaywood** [comment]
yes, burning force is off by 1 too

problem is if you adjust that others end up off by 1

it might be a case of when the hardware latches certain values to draw each line rather than when the IRQ occurs.

**Comment by DavidHaywood** [comment]
btw, do the schematics show any kind of framebuffering for the sprites, or a ram buffer? it might be that you can't do POSIRQ on sprites, and the fact the game is using the POSIRQ is exactly what is causing partial lists to be drawn if they're not ready and should be drawing from a buffer or to a buffer.

**Comment by ajrhacker** [comment]
Most sprite hardware involves some sort of buffer RAM, though often it's just line buffering. Final Lap seems to use a dual line buffer for the sprites (see Atari Games SP-322, Sheet 23), and another one for the road layer (on Sheet 26).

**Comment by DavidHaywood** [comment]
yeah, I figured it would probably only be a line buffer for rendering, so unless there's a ram buffer for the list, it doesn't explain what seem to be the incomplete lists Suzuka 8 Hours 2 seems to attempt to render (unless they added something on that board, it is the more advanced one with Roz support IIRC, even if they didn't populate the Roz here)

**Pull request merged**
