### PR TITLE
fixed -aviwrite/-mngwrite crash with screenless systems [Oliver Stöne…

### PR DESCRIPTION
**Pull request by firewave**
…berg]

### CODE REVIEW

**Comment by happppp** [comment]
I would add an osd_printf_error and not return silently.

Also, looking at the code, I think it's simpler to support screenless video recordings. However, it will stupidly record them at the default ratio 4:3, same artifact as making screenshots with F12 (try with "ti30" for example)

**Comment by firewave** [comment]
> I would add an osd_printf_error and not return silently.

I was thinking about that as well.

> Also, looking at the code, I think it's simpler to support screenless video recordings. However, it will stupidly record them at the default ratio 4:3, same artifact as making screenshots with F12 (try with "ti30" for example)

Seems reasonable as snaps are indeed being produced. I will not be looking into that though.

**Comment by firewave** [comment]
Works now - needs another name now since it is no longer my change I guess.

**Comment by happppp** [comment]
Sure, I inserted myself into the brackets for whatsnew.

**Pull request merged**
