### PR TITLE
various small improvements, no breakthroughs

### PR DESCRIPTION
**Pull request by pmackinlay**
Please note fixes to ncr5390 and ncr539x logging

### CODE REVIEW

**Comment by rb6502** [comment]
I'm going to merge this, but let me inject a little guidance: 539x is on my todo list to go away.  If you can get a working 5394 subclassed from the 5390, I'll start replacing 539x users with that and get it some more testing :)

**Comment by pmackinlay** [comment]
Thanks for the feedback RB. I'm not locked into 539x in particular - right now I'm alternating between it and 5390 because I get slightly different symptoms and it's helping me figure things out. Your point is taken, and I will target 5390 going forward and drop 539x as soon as I get enough internal progress to allow it. For what it's worth, I am still not clear if my system expects a 53c90a or 53c94, but when I figure it out I'll subclass 5390 to suit.

**Comment by Robbbert** [comment]
Validation failure: ip2800

C4E/C4T cammu device 'mmu': space 1 configured as address space 0

**Comment by pmackinlay** [comment]
I'm not going to fix this - it doesn't stop anything working, and it seems it's only being flagged as an error due to the unnecessary need to pass the space in with the address map in the first place. The correct fix appears to be to remove the need to pass the space at all, and the corresponding sanity check (which is the only thing it's used for anyway).

**Comment by rb6502** [comment]
Yeah, @galibert fixed it by removing the sanity check.

**Pull request merged**
