### PR TITLE
new WORKING machines (I Can Play Piano)

### PR DESCRIPTION
**Pull request by DavidHaywood**
new WORKING machines
--
I Can Play Piano [Sean Riddle, David Haywood, external donators]

I'm happy enough with the emulation of this to promote it.  There is one button I haven't been able to map which is market 'metronome' and should produce an audible beat.

The overall input mapping is quite messy and could probably be tidied up, but I'm not sure there is a standard way to map something with so many inputs (it's just abusing multiple player inputs to get enough buttons) at least where everything is has been identified.

### CODE REVIEW

**Comment by happppp** [comment]
Why not IPT_KEYPAD? Then you can default it to something user friendly, like QWERTYU for CDEFGAB, number keys above for semitones, etc. Also, it's "octave", not "octatve"

**Comment by DavidHaywood** [comment]
Well that's why I was looking for some sort of feedback with it :-)

**Comment by DavidHaywood** [comment]
ok, that was a squeeze, but it's using IPT_KEYPAD and maps everything by default.  My gut feeling is if more of these things get emulated we'll need some more standardized way in the future tho, especially for keyboards with more keys than this, where they're simply not all going to map to anything sensible.

**Comment by happppp** [comment]
Oh, since you're mapping to keys that are reserved by MAME's UI, for example the "P" pause key, it's better to use IPT_KEYBOARD. Then MAME will turn the UI shortcuts off (switch back on with scroll lock iirc).

And in case you have eg. 200 keys where mapping them doesn't make much sense, you're not required to. See for example the sensory chess board games with 64 buttons. I put IPT_KEYPAD and a PORT_NAME, mapped to nothing by default. But the artwork file can still access them, and if the user has a chessboard controller for example, they can still remap the inputs.

**Pull request merged**
