### PR TITLE
bus/nes_ctrl: Added a SNES controller port adapter.

### PR DESCRIPTION
**Pull request by 0kmg**
A SNES joypad or mouse can now be connected via adapter to either NES controller port.

### CODE REVIEW

**Comment by cuavas** [comment]
Not related to this PR, but why the hell is the SNES mouse using absolute lightgun axis inputs?  It’s a relative device.  I can’t see how that could possibly be working properly at all.

**Comment by 0kmg** [comment]
@cuavas, there's a comment in the mouse source about the lightgun usage right above my edits. I could only take it at face value given my limited knowledge.

**Comment by cuavas** [comment]
That just means the person who wrote it doesn’t understand how to deal with mouse/trackball inputs.  If the host wants delta since last update, you don’t just return the value from the I/O port field, you need to manage it yourself.  All the serial PC and Sun mouse devices manage to do this properly.

**Comment by 0kmg** [comment]
I only glanced at snes_ctrl/mouse.cpp, but it seemed like they were doing the managing.

Anyway, useful pointers for me. I have a branch with a rudimentary Famicom Hori Track(ball) that I'd like to polish up at some point. The PC mouse you mention is the hlemouse in rs232?

**Comment by cuavas** [comment]
Yeah, that does the Microsoft and Mouse Systems protocols.  The Sun mouse is a bit simpler as it only does non-rotatable Mouse Systems protocol.

**Comment by 0kmg** [comment]
Are the 12-bit PORT_BIT axes that the rs232 mouse uses arbitrary, i.e. is the size just what works well? I see those are used to calculate 8-bit deltas. The Hori Track has very small signed 4-bit deltas FWIW, and I have no information on how the trackball hardware part actually works (and was similarly hle fudging).

**Comment by cuavas** [comment]
The way the Mouse Systems, Microsoft and Logitech devices work in real life is that they have an internal counter that’s larger than the number of axis bits in an update packet so they can deal with rapid movements better.  If you make a brief, rapid movement, it won’t saturate or wrap, but it will take a few packets to send the movement to the computer.  IIRC the original Mouse Systems optical mouse used 16-bit counters internally.

Assigning 12 bits in the `PORT_BIT` macros is somewhat arbitrary.  It’s chosen to be smaller than 16 bits but sufficiently large that a quick movement shouldn’t saturate it.  MAME only updates the I/O ports once every frame for the first emulated video screen, so keep that in mind.

Gaming trackballs are usually a lot less sensitive than desktop trackballs, so your use case may work better with fewer bits and lower gain.

**Comment by cuavas** [comment]
By gain, I mean the value in `PORT_SENSITIVITY`, obviously.

**Comment by 0kmg** [comment]
Thanks for the info! The bad news is there's only about 4 FC games that even support the Hori Track, 1 freezes in MAME, and I think they're all fairly poor test cases for the hardware anyway (best one is operation wolf because it has a pointer on screen, but the pointer moves by tiles!)

**Pull request merged**
