### PR TITLE
Some new entries for the IBM5170 softlist

### PR DESCRIPTION
**Pull request by darkstar**
I dumped a lot of floppies recently, and these are the first ones that I create a pull-request for

All floppies were dumped with a KryoFlux and converted to img.

The *.img files as well as the KryoFlux stream dumps, KF logs and scans of the media are available on my archive.org account (archive.org/details/@ dark-star)

If you prefer a different submission method for the *.img files let me know

### CODE REVIEW

**Comment by DopefishJustin** [comment]
Thanks for the contributions! For the sets which are alternate editions of software we already have, can you please define clone relationships in the XML? For example, ```<software name="wfw311g">``` ought to be ```<software name="wfw311g" cloneof="wfw311">``` - this makes it easier to browse the list of available software using the GUI.

Looks good otherwise!

**Comment by darkstar** [comment]
Will do, totally forgot about clones. Should I fix the existing "win31" clone relationships while I'm at it? i.e. make win31a and win31m a clone of win31 as well?

**Comment by DopefishJustin** [comment]
Yes please.

**Comment by darkstar** [comment]
Updated PR

**Comment by DopefishJustin** [comment]
Thanks.

I found most of the disks on archive.org but I don't see the files corresponding to the win31g set.

**Comment by oddi5593** [comment]
Kaspersky detect virus in Windows_3.1_German_Disk1.img 
Virus.Boot.Parity.b

**Comment by darkstar** [comment]
Indeed.

Which is funny as the disk in question definitely checks out as "unmodified" (i.e. it hasn't been written to after being mastered) and there is even the "TRACER" data track (track 81) still present in the raw Kryoflux dump.

This means it must have been infected at the factory already (or the master disk was infected).

I transplanted the boot sector of the second floppy onto the first, taking care not to ovberwrite the volume label or volume serial number. This means the disk is now clean, something which VirusTotal seems to [agree with](https://virustotal.com/en/file/9ef11668930746d216786e81a142a34177c807634d3e37e6c43b52bcf7025763/analysis/1489430364/)

I will upload the whole set to archive.org today and will send the updated link to DFJustin

**Pull request merged**
