### PR TITLE
New working clone

### PR DESCRIPTION
**Pull request by algestam**
-----------------
Tayny okeana [algestam, Milan Galcik]

The year of release has been set to 1988 as that year can be found in a game manual found here: https://skopil.ru/fajly/elektronika/rukovodstvo-po-ekspluatatsii-elektronika-im-03-tajny-okeana
image

### CODE REVIEW

**Comment by simzy39** [comment]
@happppp What about putting 'Elektronika' in its own colomn with a list of their games/bootless. Just add a comment to say what each one is a bootleg for. Right now, it's not straight forward finding what Elektronika games are supported in one easy list, and it is messing up the Game&Watch list, while putting autoslam by itself under misc with the number matching thing.

**Comment by happppp** [comment]
I don't really agree, since it's the norm to put clonesets under their parents, plus the driver implementation is grouped with the parent sets too. But fine let's do it, since yes it makes it difficult to parse the game list.

As for a comment to say what each a bootleg is for: nah, that info is in the parent(cloneof) column already.

**Comment by cuavas** [comment]
I disagree with changing the organisation of the driver. It makes it harder to work with the source for developers. Finding Elektronika games and other things like that are better suited to a database built from system metadata.

**Comment by happppp** [comment]
Doesn't make it harder for me(the main developer of this driver), @algestam what about you?

**Comment by algestam** [comment]
I don't see any problems with changing this, the fix done by @happppp won't make things harder :thumbsup:

**Pull request merged**
