### PR TITLE
dynax/dynax.cpp: fix tenkai and ougonhai dip switch

### PR DESCRIPTION
**Pull request by crashGG**
According to the documentation submitted [here](https://github.com/mamedev/mame/issues/12846) and [here](https://github.com/mamedev/mame/issues/12802), fix tenkai and ougonhai dip switch,
After testing, they work fine.

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
We always translate DIP switches to English and try to have some consistency across games even when manufacturers use inconsistent terminology (e.g. “最小押注” would be `"Minimum Bet"`, “画面反转” would be `DEF_STR(Flip_Screen)`, “语言” would be `DEF_STR(Language)`, etc.).

**Comment by cuavas** [comment]
See an example here: https://github.com/mamedev/mame/blob/mame0271/src/mame/igs/igs_m027.cpp#L933

Chinese text displayed in test mode is in comments as well as relevant notes.

**Comment by little0000bag** [comment]
Please use below code for these two games of English Dip Switch.

static INPUT_PORTS_START( tenkai )
	PORT_START("DSW0")
	PORT_DIPNAME( 0x0f, 0x07, "Pay Out Rate" )
	PORT_DIPSETTING(    0x00, "50" )
	PORT_DIPSETTING(    0x01, "53" )
	PORT_DIPSETTING(    0x02, "56" )
	PORT_DIPSETTING(    0x03, "59" )
	PORT_DIPSETTING(    0x04, "62" )
	PORT_DIPSETTING(    0x05, "65" )
	PORT_DIPSETTING(    0x06, "68" )
	PORT_DIPSETTING(    0x07, "71" )
	PORT_DIPSETTING(    0x08, "75" )
	PORT_DIPSETTING(    0x09, "78" )
	PORT_DIPSETTING(    0x0a, "81" )
	PORT_DIPSETTING(    0x0b, "84" )
	PORT_DIPSETTING(    0x0c, "87" )
	PORT_DIPSETTING(    0x0d, "90" )
	PORT_DIPSETTING(    0x0e, "93" )
	PORT_DIPSETTING(    0x0f, "96" )
	PORT_DIPNAME( 0x30, 0x10, "Odds Rate" )
	PORT_DIPSETTING(    0x30, "1 2 4 8 12 16 24 32" )
	PORT_DIPSETTING(    0x00, "1 2 3 5 8 15 30 50" )
	PORT_DIPSETTING(    0x10, "1 2 3 5 10 25 50 100" )
	PORT_DIPSETTING(    0x20, "1 2 3 5 10 50 100 200" )
	PORT_DIPNAME( 0xc0, 0x40, "Max Bet" )
	PORT_DIPSETTING(    0xc0, "1" )
	PORT_DIPSETTING(    0x80, "5" )
	PORT_DIPSETTING(    0x40, "10" )
	PORT_DIPSETTING(    0x00, "20" )

	PORT_START("DSW1")
	PORT_DIPNAME( 0x03, 0x03, "Coin Rate" )
	PORT_DIPSETTING(    0x03, "1:1" )
	PORT_DIPSETTING(    0x02, "1:2" )
	PORT_DIPSETTING(    0x01, "1:5" )
	PORT_DIPSETTING(    0x00, "1:10" )
	PORT_DIPNAME( 0x0c, 0x0c, "Min Bet" )
	PORT_DIPSETTING(    0x0c, "1" )
	PORT_DIPSETTING(    0x08, "2" )
	PORT_DIPSETTING(    0x04, "3" )
	PORT_DIPSETTING(    0x00, "5" )
	PORT_DIPNAME( 0x70, 0x70, "YAKUMAN Bonus" )
	PORT_DIPSETTING(    0x70, "Cut" )
	PORT_DIPSETTING(    0x60, "1 T" )
	PORT_DIPSETTING(    0x50, "300" )
	PORT_DIPSETTING(    0x40, "500" )
	PORT_DIPSETTING(    0x30, "700" )
	PORT_DIPSETTING(    0x20, "1000" )
//  PORT_DIPSETTING(    0x10, "1000" )
//  PORT_DIPSETTING(    0x00, "1000" )
	PORT_DIPNAME( 0x80, 0x80, "YAKU TIMES" )
	PORT_DIPSETTING(    0x00, "1" )
	PORT_DIPSETTING(    0x80, "2" )

	PORT_START("DSW2")
	PORT_DIPNAME( 0x01, 0x01, "Credit Mode" )
	PORT_DIPSETTING(    0x01, "Key-In" )
	PORT_DIPSETTING(    0x00, "Coin Acceptor" )
	PORT_DIPNAME( 0x02, 0x02, "Flip_Screen" )
	PORT_DIPSETTING(    0x02, "Normal" )
	PORT_DIPSETTING(    0x00, "Flip" )
	PORT_DIPNAME( 0x04, 0x04, "TENKAIGEN" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPSETTING(    0x04, "No" )
	PORT_DIPNAME( 0x08, 0x08, "In-Game Bet" )
	PORT_DIPSETTING(    0x08, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x10, 0x10, "Dealer Bonus" )
	PORT_DIPSETTING(    0x10, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x20, 0x20, "Auto Tsumo after Reach" )
	PORT_DIPSETTING(    0x20, "Off" )
	PORT_DIPSETTING(    0x00, "On" )
	PORT_DIPNAME( 0x40, 0x40, "Last Chance" )
	PORT_DIPSETTING(    0x40, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x80, 0x80, "DonDen Key" )
	PORT_DIPSETTING(    0x80, "Start" )
	PORT_DIPSETTING(    0x00, "Flip Flop" )

	PORT_START("DSW3")
	PORT_DIPNAME( 0x01, 0x00, "Demo_Sounds" )
	PORT_DIPSETTING(    0x01, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x02, 0x00, "In-Game Music" )
	PORT_DIPSETTING(    0x02, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x04, 0x04, "Select Girl" )
	PORT_DIPSETTING(    0x04, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x08, 0x00, "Moles On Gal's Face" )
	PORT_DIPSETTING(    0x00, "No" )
	PORT_DIPSETTING(    0x08, "Yes" )
	PORT_DIPNAME( 0x10, 0x10, "Language" )
	PORT_DIPSETTING(    0x10, "Japanese" )
	PORT_DIPSETTING(    0x00, "Chinese" )
	PORT_DIPNAME( 0x20, 0x20, "Three Times Chances Changing Tiles Rate" )
	PORT_DIPSETTING(    0x20, "Normal" )
	PORT_DIPSETTING(    0x00, "Few" )
	PORT_DIPNAME( 0x40, 0x40, "TENKAIGEN Rate" )
	PORT_DIPSETTING(    0x40, "Normal" )
	PORT_DIPSETTING(    0x00, "Few" )
	PORT_DIPNAME( 0x80, 0x80, "Set Date" )
	PORT_DIPSETTING(    0x80, "Off" )
	PORT_DIPSETTING(    0x00, "On" )

	PORT_START("DSW4")  /* (top) */
	PORT_DIPNAME( 0x01, 0x01, "Game Style" )
	PORT_DIPSETTING(    0x01, "New Moon Style" )
	PORT_DIPSETTING(    0x00, "Hopper Style" )
	PORT_DIPNAME( 0x02, 0x02, "Hopper Activity" )
	PORT_DIPSETTING(    0x02, "No" )
	PORT_DIPSETTING(    0x00, "Activity" )
	PORT_DIPNAME( 0x04, 0x04, "CPU Weak  Or Strong" )
	PORT_DIPSETTING(    0x04, "Normal" )
	PORT_DIPSETTING(    0x00, "Strong" )
	PORT_DIPNAME( 0x08, 0x08, "Service Count" )
	PORT_DIPSETTING(    0x08, "Off" )
	PORT_DIPSETTING(    0x00, "On" )
	PORT_DIPNAME( 0x10, 0x10, "DON DEN TIME" )
	PORT_DIPSETTING(    0x10, "8" )
	PORT_DIPSETTING(    0x00, "5" )
	PORT_DIPNAME( 0x20, 0x20, "Show Clock" )
	PORT_DIPSETTING(    0x20, "Off" )
	PORT_DIPSETTING(    0x00, "On" )
	PORT_DIPNAME( 0x40, 0x40, "Subtitle" )
	PORT_DIPSETTING(    0x40, "None" )
	PORT_DIPSETTING(    0x00, "Part 2" )
	PORT_DIPNAME( 0x80, 0x80, "YAKUMAN TABLE" )
	PORT_DIPSETTING(    0x80, "No" )
	PORT_DIPSETTING(    0x00, "Only Part 2 Yes" )

	PORT_START("COINS")
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_GAMBLE_PAYOUT ) PORT_CODE(KEYCODE_4) // Pay
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_UNKNOWN  )   // 18B
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_SERVICE  )   // Test
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_SERVICE2 )   // Analyzer
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_MEMORY_RESET ) // Memory Reset
	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_COIN2    )   // Note
	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_COIN1    )   // Coin
	PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_SERVICE1 )   // Service

	PORT_INCLUDE( MAHJONG_KEYS_BET )
INPUT_PORTS_END

static INPUT_PORTS_START( ougonhai )
	PORT_INCLUDE( tenkai )
	PORT_MODIFY("DSW2")
	PORT_DIPNAME( 0x01, 0x01, "Credit Mode" )
	PORT_DIPSETTING(    0x01, "Key-In"  )
	PORT_DIPSETTING(    0x00, "Coin Acceptor" )
	PORT_DIPNAME( 0x02, 0x02, "Flip_Screen" )
	PORT_DIPSETTING(    0x02, "Normal" )
	PORT_DIPSETTING(    0x00, "Flip" )
	PORT_DIPNAME( 0x04, 0x04, "DonDen Key" )
	PORT_DIPSETTING(    0x04, "Flip Flop" )
	PORT_DIPSETTING(    0x00, "Start" )
	PORT_DIPNAME( 0x08, 0x08, "In-Game Bet" )
	PORT_DIPSETTING(    0x08, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x10, 0x10, "Auto Tsumo after Reach" )
	PORT_DIPSETTING(    0x10,  "Off" )
	PORT_DIPSETTING(    0x00, "On" )
	PORT_DIPNAME( 0x20, 0x20, "Last Chance" )
	PORT_DIPSETTING(    0x20, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x40, 0x40, "YAKUMAN TABLE" )
	PORT_DIPSETTING(    0x40, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x80, 0x80, "Gold Rush Rate" )
	PORT_DIPSETTING(    0x80, "High" )
	PORT_DIPSETTING(    0x00, "Normal" )
	PORT_MODIFY("DSW3")
	PORT_DIPNAME( 0x01, 0x00, "Demo_Sounds" )
	PORT_DIPSETTING(    0x01, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x02, 0x00, "In-Game Music" )
	PORT_DIPSETTING(    0x02, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x04, 0x04, "Girl After Dealer" )
	PORT_DIPSETTING(    0x04, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x08, 0x00, "Unknown" )
	PORT_DIPSETTING(    0x00, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x08, DEF_STR( On ) )
	PORT_DIPNAME( 0x10, 0x10, "Language" )
	PORT_DIPSETTING(    0x10, "Japanese" )
	PORT_DIPSETTING(    0x00, "Chinese" )
	PORT_DIPNAME( 0x20, 0x20, "Computer Show Tiles" )
	PORT_DIPSETTING(    0x20, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x40, 0x40, "Service Mode" )
	PORT_DIPSETTING(    0x40, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x80, 0x80, "Show Inventory" )
	PORT_DIPSETTING(    0x80, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_MODIFY("DSW4")  /* (top) */
	PORT_DIPNAME( 0x01, 0x01, "Key-In Rate" )
	PORT_DIPSETTING(    0x01, "5" )
	PORT_DIPSETTING(    0x00, "10" )
	PORT_DIPNAME( 0x02, 0x02, "Flip_Screen" )
	PORT_DIPSETTING(    0x02, "Normal" )
	PORT_DIPSETTING(    0x00, "Flip" )
	PORT_DIPNAME( 0x04, 0x04, "Computer Weak  Or Strong" )
	PORT_DIPSETTING(    0x04, "Normal" )
	PORT_DIPSETTING(    0x00, "Strong" )
	PORT_DIPNAME( 0x08, 0x08, "Dealer Bonus" )
	PORT_DIPSETTING(    0x08, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x10, 0x10, "DON DEN TIME" )
	PORT_DIPSETTING(    0x10, "8" )
	PORT_DIPSETTING(    0x00, "5" )
	PORT_DIPNAME( 0x20, 0x20, "Unknown" )
	PORT_DIPSETTING(    0x20, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
	PORT_DIPNAME( 0x40, 0x40, "Test Mode" )
	PORT_DIPSETTING(    0x40, "No" )
	PORT_DIPSETTING(    0x00, "Yes" )
	PORT_DIPNAME( 0x80, 0x80, "Unknown" )
	PORT_DIPSETTING(    0x80, DEF_STR( Off ) )
	PORT_DIPSETTING(    0x00, DEF_STR( On ) )
INPUT_PORTS_END

**Comment by MooglyGuy** [comment]
@little0000bag, if you are going to advise people on what DIP switch settings to use, please familiarize yourself with which string definitions are available. Don't give bad advice to new contributors.

`"Flip_Screen"` should actually be `DEF_STR( Flip_Screen )`.
`"Demo_Sounds"` should actually be `DEF_STR( Demo_Sounds )`.
By convention, the settings for flip-screen should be `DEF_STR( On )` and `DEF_STR( Off )`, not `"Yes"` and `"No"`. The same goes for the settings for Test Mode and Service Mode.

You aren't even being consistent in your changes, you have the raw strings `"On"` and `"Off"` for the "Auto Tsumo after Reach" setting, instead of `DEF_STR( On )` and `DEF_STR( Off )`.

@crashGG I suggest doing a consistency pass across the changes, because the ones provided by this "little0000bag" person are not in great shape, and merging them in as-is will simply create more maintenance burden for other people.

**Comment by little0000bag** [comment]
You are correct, I am not a professional, nor am I a programmer, just a game enthusiast. I previously wanted to correct the actual DIP switches and the current MAME DIP switch differences and make suggestions for modifications. Since it has not been fixed for a long time, I learned and tried to modify some DIP switch names myself. Initially, I provided the names in Chinese, and then later changed them to English. 
      Please use the DIP settings I provided,  the code including the strings need corrected to use.
      Thank you for your correction. I will learn more. Thank you!

**Comment by cuavas** [comment]
I’ll look at this later.

**Comment by cuavas** [comment]
Ougon no Hai addressed by ecacee47330774c88394660948708387c1ece0de

**Pull request closed without merging**
