### PR TITLE
z80dma.cpp: burst mode and refactoring

### PR DESCRIPTION
**Pull request by holub**
~~Opening as a draft as requires following (volunteers are appreciated) to be completed...~~

* ~~validate existing drivers which uses it and wire **busack**~~
```
	m_maincpu->busack_cb().set(m_dma, FUNC(z80dma_device::bai_w));
	m_dma->out_busreq_callback().set_inputline(m_maincpu, Z80_INPUT_LINE_BUSRQ);
```
* ~~update drivers which use HALT for **busreq** and replace with pattern above~~

### CODE REVIEW

**Comment by holub** [comment]
I think it's ready now.
Just maybe let's postpone the merge till current version released.

**Comment by angelosa** [comment]
Self assigning for testing my turf here.

**Comment by holub** [comment]
I decided to do deeper refactoring. Let's hold on this one.

**Comment by holub** [comment]
zorba has been broken and I'm not really sure why

**Comment by holub** [comment]
> zorba has been broken and I'm not really sure why

zorba is back in the business

**Comment by holub** [comment]
Gentlemen?

**Review by angelosa — COMMENTED** [review]
I tested this a while back, it makes `x1turbo40 lastarmg` to fail eariler during intro, while `x1turbo40 suikoden` throws a floppy error during bootstrap, making it unbootable.

**Comment by holub** [comment]
> I tested this a while back, it makes `x1turbo40 lastarmg` to fail eariler during intro, while `x1turbo40 suikoden` throws a floppy error during bootstrap, making it unbootable.

I fixed these

**Review by angelosa — APPROVED** [review]
Do we want this on this release or the next?

**Comment by rb6502** [comment]
I'd say let's wait for the freeze and put this in the August release so there's plenty of time for testing.

**Comment by holub** [comment]
> I'd say let's wait for the freeze and put this in the August release so there's plenty of time for testing.

Sounds good for me

**Comment by holub** [comment]
@rb6502 ping

**Pull request merged**
