### PR TITLE
Fix ISA bus on i82371sb (nw)

### PR DESCRIPTION
**Pull request by MoochMcGee**

### CODE REVIEW

**Comment by cuavas** [comment]
The southbridge shouldn't have ISA slots, only fixed peripherals for things it implements internally.  It may expose an ISA bus that PCs based on it break out to slots, but it doesn't have ISA slots itself.  Also, I don't actually see fixes, just uncommenting stuff.  Presumably there's a reason this stuff was commented out,

**Comment by yz70s** [comment]
It seems that this is a duplicate of the stuff in the src/devices/bus/lpci/
and is meant to be used with the new pci system.

However is still incopmplete,


2017-12-05 2:20 GMT+01:00 Vas Crabb <notifications@github.com>:

**Comment by MoochMcGee** [comment]
@yz70s yeah, we knew that, thanks

**Comment by MoochMcGee** [comment]
@cuavas how's this?

**Comment by cuavas** [comment]
It's still got a hard-coded tag for the system CPU, which will cause problems, and I'm still leery of just uncommenting the stuff.  If it was commented out wholesale, it's probably known to be flawed in some way, and just there so it can be uncommented in local builds as a hack for getting past something.  I want to know what @galibert has to say since he wrote it in the first place.

**Comment by MoochMcGee** [comment]
@cuavas as far as i can tell, it was just commented out because it didn't compile.

**Pull request closed without merging**
