### PR TITLE
ncr5390 changes - for review only, don't commit

### PR DESCRIPTION
**Pull request by pmackinlay**
With some help from OG yesterday, I've made some important changes to the "transfer information" logic in ncr5390. In theory, this will help Sun4 (it should now handle all phases), hopefully won't break NeXT, and my emerging InterPro is happy with it now.

In more detail, the things I've modified are:
* split transfer count/counter (count is latched and used to reset the counter when DMA commands start, while the counter is read-only and tracks the actual transfers)
* added rudimentary 53c90a/53c94 support (although the extra registers are essentially ignored for now)
* reworked initiator transfer information state machine: should now support all SCSI phases
* improved handling of DMA/non-DMA commands
* added an undocumented hack to make InterPro work (i.e. setting the sequence to non-zero after a message accept)

This PR is a placeholder for smarter people to comment before I commit this; I don't have the inputs necessary to test NeXT/Sun4 and don't want to break them. Also, I'm tampering with a fairly complex bit of code and I'd prefer if at least Olivier takes a good look first.

### CODE REVIEW

**Comment by galibert** [comment]
It looks sane.  It would be nicer to AM_INHERIT_FROM(ncr5390_device::map)
in the other two devices though.  If you do that I'll pull and we'll test.
NeXT, if broken, can be fixed before the next release and the other two
don't work anyway.

I wonder about interaction between fifo contents/access and dma, but we
won't have the answer anyway, so we'll have to test how the emu behaves
with real oses.

  OG.


On Fri, Jun 30, 2017 at 8:59 AM, Patrick Mackinlay <notifications@github.com

**Comment by pmackinlay** [comment]
Done - somehow convinced myself AM_INHERIT_FROM wouldn't work, so thanks for that.

Regarding fifo/DMA, I used the "command completion" logic from the NCR 53c90a/b databook, which spells this out reasonably clearly (for DMA/non-DMA and various phases), at least as far as the "transfer information" command is concerned, so I'm pretty confident this matches the documentation at least. Regarding reality, I can only say it works with InterPro at this point, so hopefully it doesn't make anything worse for those other drivers.

**Comment by pmackinlay** [comment]
I forgot one other important change I made here:
* implemented interrupt status flag in status register for 53c90a, this is critical for InterPro

**Comment by rb6502** [comment]
Trying to boot nextst with my installed NeXTStep HDD .chd from a while back results in a panic a little bit after the initial Mach bootloader comes up.  I don't know for sure if this was the version that broke it though.

**Comment by rb6502** [comment]
Ok, 0.186 does the same thing.  I remember it was a bit sensitive to the parameters in the nvram, so I might be doing something wrong.

**Pull request merged**
