### PR TITLE
Update gameboy.xml

### PR DESCRIPTION
**Pull request by FakeShemp**
Large re-haul of the gameboy softlist. Lots of information about carts added.

Added compatibility field for GB, SGB and GBC. It technically doesn't do anything since all SGB games work on GB hardware and vice versa, but now the emulator can at least access the information and parse it however it wants instead of the info lingering in comments.

Added more PCB layouts, regions, serials. Some new dumps added and some old corrected with redumps.

### CODE REVIEW

**Comment by Tafoid** [comment]
Formatting:  There are a large number of lines which have unneeded spaces intermixed with TABs at the beginning of them.  My scan found 3 different types of formatting (detailed below with line number at the end and the string found) which should be nothing but TABs at the beginning.  Cleaning these examples up document wide should fix up formatting.

3 not 2 gameboy.xml 63
TAB-SPACE-TAB

4 not 3 gameboy.xml 1658
TAB-TAB-SPACE-SPACE

2 not 3 gameboy.xml 18044
TAB-TAB-SPACE

**Comment by FakeShemp** [comment]
Dammit, vs code :( I thought I made it take care of that. I will format it as soon as I can.

**Comment by FakeShemp** [comment]
But no, that just made it worse.

I'll revert and do fix when I have more time on my hands. 

Feel free to recommend a good xml formatter.

**Comment by cuavas** [comment]
I checked again, and there's still a lot of churn, e.g. here:
```
@@ -53,29 +53,27 @@
 <softwarelist name="gameboy" description="Nintendo Game Boy cartridges">

        <software name="tamafrnd">
-               <description>3 Choume no Tama - Tama and Friends - 3 Choume Obake Panic!! (Japan)</description>
+               <description>3 Choume no Tama - Tama and Friends - 3 Choume Obake Panic!! (Jpn)</description>
                <year>1994</year>
                <publisher>Varie</publisher>
-               <info name="serial" value="DMG-WQJ" />
-               <info name="release" value="19940805" />
-               <info name="alt_title" value="3丁目のタマ タマ&amp;フレンズ 3丁目お化けパニック!!" />
-               <sharedfeat name="compatibility" value="GB" />
+               <info name="serial" value="DMG-WQJ"/>
+               <info name="release" value="19940805"/>
+               <info name="alt_title" value="3丁目のタマ タマ&amp;フレンズ 3丁目お化けパニック!!"/>
                <part name="cart" interface="gameboy_cart">
                        <feature name="slot" value="rom_mbc1" />
                        <dataarea name="rom" size="131072">
-                               <rom name="3 choume no tama - tama and friends - 3 choume obake panic!! (japan).bin" size="131072" crc="b61cd120" sha1="0982
bcc82deb9c4db08e602a22a2bb4f31e7e6ae" />
+                               <rom name="3 choume no tama - tama and friends - 3 choume obake panic!! (japan).bin" size="131072" crc="b61cd120" sha1="0982
bcc82deb9c4db08e602a22a2bb4f31e7e6ae"/>
                        </dataarea>
                </part>
        </software>

        <software name="3punyoso">
-               <description>3-pun Yosou Umaban Club (Japan)</description>
+               <description>3-pun Yosou Umaban Club (Jpn)</description>
                <year>1992</year>
                <publisher>Hect</publisher>
-               <info name="serial" value="DMG-U4J" />
-               <info name="release" value="19921016" />
-               <info name="alt_title" value="3分予想 馬番倶楽部" />
-               <sharedfeat name="compatibility" value="GB" />
+               <info name="serial" value="DMG-U4J"/>
+               <info name="release" value="19921016"/>
+               <info name="alt_title" value="3分予想 馬番倶楽部"/>
                <part name="cart" interface="gameboy_cart">
                        <feature name="pcb" value="DMG-GDAN-03" />
                        <feature name="u1" value="U1 PRG" />
```
where the formatting change swamps the actual removal of the compatibility tag, and here:
```
@@ -84,7 +82,7 @@
                        <feature name="batt" value="Batt CR1616" />
                        <feature name="slot" value="rom_mbc2" />
                        <dataarea name="rom" size="65536">
-                               <rom name="dmg-u4j-0.u1" size="65536" crc="cafe0d2b" sha1="76643f3f3481f7e515a24482779870862dd8b373" />
+                               <rom name="dmg-u4j-0.u1" size="65536" crc="cafe0d2b" sha1="76643f3f3481f7e515a24482779870862dd8b373"/>
                        </dataarea>
                        <dataarea name="nvram" size="8192">
                        </dataarea>
```
where as far as I can tell it's just the style change on that line, making it inconsistent with the rest of the elements in the entry.

**Comment by FakeShemp** [comment]
I think that's the other way around. My changes should add the compability tag and add a space to all ` />` tags so they're all the same.

**Comment by cuavas** [comment]
Hang on, lemme check again.  It's a huge diff and GitHub won't display it.

**Comment by cuavas** [comment]
OK, now it makes more sense.  You seem to have used the `SGB` flag for things that have additional SGB functionality.  That's not how the compatibility flags work.  They're used for filtering, so if some system had a "SGB" compatibility filter, it would *only* display software items with the `SGB` flag on them.  In theory, a Super Game Boy is supposed to play all standard Game Boy games.  The only uses I can think of for compatibility flags in this software list would be to mark items that for some reason *don't* work on SGB, GBC or some other variant, and that would have to be done by adding a flag to all the ones that *do* work.

**Comment by FakeShemp** [comment]
Yes, that's exactly how I used it. Right now every cart has `GB` as compatibility, since they should all work on a regular GB. And `SGB` for those with extra Super Gameboy functionality.

But as you said, they should also all work on a Super Gameboy and Color. Some pirate games don't, but I'm not 100% sure which ones those are.

I can remove the compatibility flags of course. Just say the word.

**Comment by cuavas** [comment]
I think given the way the compatibility fulters work it's not the right way to do it. You'd be better off adding a feature element to flag SGB-aware games. That could still be parsed and potentially used by front-ends to find them.

**Comment by cuavas** [comment]
I'll rename the feature from "compatibility" to "enhancement".

**Comment by Tafoid** [comment]
@FakeShemp Please be sure to provide the 2 images which have changed with your update either by uploading or sending to our submission address.  The formatting was nearly complete and I fixed just one TAB issue - thanks for all your fine work!

**Pull request merged**
