### PR TITLE
spectrum_cass.xml: Massive update metadata (year and publisher)

### PR DESCRIPTION
**Pull request by ArcadeShadow**

### CODE REVIEW

**Comment by cuavas** [comment]
You seem to have messed up `dmousmw`:
```
@@ -58194,8 +58194,8 @@ license:CC0
 
 	<software name="dmousmw">
 		<description>Danger Mouse - In Making Whoopee</description>
-		<year>19??</year>
-		<publisher>&lt;unknown&gt;</publisher>
+		<year> siz</year>
+		<publisher>37057</publisher>
 		<part name="cass" interface="spectrum_cass">
 			<dataarea name="cass" size="37057">
 				<rom name="danger mouse - in making whoopee.tzx" size="37057" crc="41dfe910" sha1="3becbb91c0fae5654d6024cb9e0582c093f43a50"/>
```

**Comment by cuavas** [comment]
You can also see errors in the validation task:
```
Driver atm (file atm.cpp): 3 errors, 0 warnings
Errors:
   Software List device 'cass_list': spectrum_cass.xml: thebount_a has duplicate description 'The Bounty Hunter' (bntyhun)
   Software List device 'cass_list': spectrum_cass.xml: dmousmw has an invalid year ' siz'
   Software List device 'cass_list': spectrum_cass.xml: tuttospe has an invalid year '198x'

Validity check failed (3 errors, 0 warnings in total)
```

You should really be validating software list changes before submitting.  It doesn’t require you to recompile MAME.

**Comment by cuavas** [comment]
What criteria were you using to match against whatever your source for the updated years/publishers was?

**Comment by ArcadeShadow** [comment]
> 
> 
> What criteria were you using to match against whatever your source for the updated years/publishers was?

The criteria used was the matching CRC32 and SHA1

**Comment by ArcadeShadow** [comment]
> 
> 
> You can also see errors in the validation task:
> 
> ```
> Driver atm (file atm.cpp): 3 errors, 0 warnings
> Errors:
>    Software List device 'cass_list': spectrum_cass.xml: thebount_a has duplicate description 'The Bounty Hunter' (bntyhun)
>    Software List device 'cass_list': spectrum_cass.xml: dmousmw has an invalid year ' siz'
>    Software List device 'cass_list': spectrum_cass.xml: tuttospe has an invalid year '198x'
> 
> Validity check failed (3 errors, 0 warnings in total)
> ```
> 
> You should really be validating software list changes before submitting. It doesn’t require you to recompile MAME.

I think now the 3 errors are corrected.

**Comment by ICEknigh7** [comment]
It does validate properly now with "mame -validate spectrum", awesome work adding the missing info in those 5000 entries!

Did you find any TZXs in those XMLs which weren't in the current softlist? It would be useful to isolate those games, so that their blocks can be compared with the similar entries in the softlist and see if we're missing any versions of them (or some games entirely).

**Comment by ArcadeShadow** [comment]
There are some TZX that aren't in the softlist. I use the SHA1 and CRC32 to find the matching entries. 
But I think the next step should be the validation of the Parent/Clones, they're some parents entries that should be clones of others.

**Comment by ICEknigh7** [comment]
I've revised the softlist and noticed that some publisher names come in different styles. Please change the following to their "more complete" names when you can, to add more consistency:

8th Day -> 8th Day Software
A'n'F -> A'n'F Software
ACE -> ACE Software
AWA -> AWA Software
Addictive Games -> Addictive Games Ltd
Adventure Probe -> Adventure Probe Software
Alternative -> Alternative Software Ltd
Americana -> Americana Software Ltd
Anirog -> Anirog Software
Arcade -> Arcade Software
Argus Press -> Argus Press Software
Ariolasoft UK -> Ariolasoft UK Ltd
Arnold Wheaton -> Arnold Wheaton Software
Arctic Computing -> Arctic Computing Ltd
Astro -> Astro Software
Atlantis -> Atlantis Software
Audiogenic Software -> Audiogenic Software Ltd
Automata UK -> Automata UK Ltd
Beyond -> Beyond Software
Blue Ribbon -> Blue Ribbon Software
Buffer Micro -> Buffer Micro Ltd
Bug-Byte -> Bug-Byte Software Ltd
Bulldog -> Bulldog Software
Cascade Games -> Cascade Games Ltd
Century City -> Century City Software Ltd
Century Communications -> Century Communications Ltd
Chalksoft -> Chalksoft Ltd
Cheetahsoft -> Cheetahsoft Ltd
Compass -> Compass Software
Contrast Software ->  Software
Crash -> Crash Magazine
DK'Tronics -> DK'Tronics Ltd
Delbert the Hamster -> Delbert the Hamster Software
Dinamic -> Dinamic Software
Domark -> Domark Ltd
E&J -> E&J Software
Electric Dreams -> Electric Dreams Software
Elfin -> Elfin Software
Elite Systems -> Elite Systems Ltd
Empire -> Empire Software
Erbe -> Erbe Software
Firebird Software -> Firebird Software Ltc
GTI -> GTI Software
Gem -> Gem Software
Gilsoft -> Gilsoft International
Global -> Global Software
Go -> Go!
Gremlin Graphics Software -> Gremlin Graphics Software Ltd
Griffin -> Griffin Software
Hamster -> Hamster Software
Hansesoft -> Hansesoft GmbH
Hektic -> Hektic Software
Hewson -> Hewson Consultants Ltd
Hi-Tec -> Hi-Tec Software
Hit-Pak -> Hit-Pak (Elite)
Hornby -> Hornby Software
Imagine -> Imagine Software Ltd
Imperial -> Imperial Software
Incentive -> Incentive Software Ltd
Interceptor -> Interceptor Software
Investronica -> Investronica S.A.
K'Soft -> K'Soft Ltd
Kayde -> Kayde Software Ltd
Kemp -> Kemp Ltd
Kerian UK -> Kerian UK Ltd
Longman -> Longman Software
MC Lothlorien -> MC Lothlorien Ltd
MCN -> MCN Software
Macmillan -> Macmillan Software Ltd
Macsen -> Macsen Software
Mandarin -> Mandarin Software
Martech Games -> Martech Games Ltd
Mastertronic -> Mastertronic Ltd
Matand -> Matand Software
Mayday -> Mayday Software
Microprose -> Microprose Software Ltd
Mikro-Gen -> Mikro-Gen Ltd
Mikro-Gen; -> Mikro-Gen Ltd
Mirrorsoft -> Mirrorsoft Ltd
Mosaic Publishing -> Mosaic Publishing Ltd
Mr. Chip -> Mr. Chip Software
Mr. Micro -> Mr. Micro Ltd
New Generation -> New Generation Software
Nexus Productions -> Nexus Productions Ltd
Ocean -> Ocean Software Ltd
Opera Soft -> Opera Soft S.A.
Pelagon -> Pelagon Software
Pirate Software -> Pirate Software Ltd
Prism Leisure Corporation -> Prism Leisure Corporation PLC
Proxima -> Proxima Software
Quiksilva -> Quiksilva Ltd
R&R -> R&R Software
R.D. Foord -> R.D. Foord Software
Rabbit -> Rabbit Software Ltd
Rainbird -> Rainbird Software Ltd
Red Shift -> Red Shift Ltd
River -> River Software
Rose -> Rose Software
SciCAL -> SciCAL Software Ltd
Scorpio Gamesworld -> Scorpio Gamesworld Ltd
Selec -> Selec Software
Silverbird -> Silverbird Software Ltd
Silversoft -> Silversoft Ltd
Sinclair Research -> Sinclair Research Ltd
Soft Sell Computer -> Soft Sell Computer Software
Software Projects -> Software Projects Ltd
Software Supersavers -> Software Supersavers Ltd
Spectrum Games -> Spectrum Games Ltd
Starlight -> Starlight Software
Storm -> Storm Software
Sulis -> Sulis Software
System 3 Software -> System 3 Software Ltd
Tanglewood -> Tanglewood Software
Tartan -> Tartan Software
Thalamus -> Thalamus Ltd
Thorn EMI Video -> Thorn EMI Video Ltd
Top Ten -> Top Ten Software
U.S. Gold -> U.S. Gold Ltd
Virgin Games -> Virgin Games Ltd
Virgin Mastertronic -> Virgin Mastertronic Ltd
Visions Software Factory -> Visions Software Factory Ltd
Vortex -> Vortex Software
Weird Science -> Weird Science Software
Widgit -> Widgit Software Ltd
Winters -> Winters Ltd
World XXI Soft -> World XXI Soft Inc
Wrightchoice -> Wrightchoice Software
Zeppelin Games -> Zeppelin Games Ltd

**Comment by cuavas** [comment]
Please don’t change things arbitrarily for “consistency” – where possible, use the name used when the individual piece of software was published (e.g. from the title screen of packaging for that particular piece of software).  Many companies styled their names differently at different times.  We don’t arbitrarily change these for consistency in MAME.

**Comment by ICEknigh7** [comment]
> We don’t arbitrarily change these for consistency in MAME.
I was only echoing what people in charge of revising the softlists told me here just a couple of years ago:
> don't be afraid to expand publisher names, ie. CP -> CP Software, Ocean -> Ocean Software, Superior -> Superior Software. Be consistent, I see both Ocean and Ocean Software, Hewson and Hewson Consultants, Gremlin Graphics and Gremlin Graphics Software.

In any case, this is the one mistake I've noticed that should be changed:
Mikro-Gen; -> Mikro-Gen

**Comment by ArcadeShadow** [comment]
> In any case, this is the one mistake I've noticed that should be changed:
> Mikro-Gen; -> Mikro-Gen

Corrected this publisher name.

**Pull request merged**
