### PR TITLE
Validity checking for AM_MASK/AM_MIRROR/AM_SELECT, based on OG's rece…

### PR DESCRIPTION
**Pull request by ajrhacker**
…nt restrictions (nw)

- Update address maps so all drivers pass checks
- Comment out some irregularly-patterned mirrors on RAM areas (needs better solution)

### CODE REVIEW

**Comment by happppp** [comment]
- Comment out some irregularly-patterned mirrors on RAM areas (needs
   better solution)


Instead of doing a wrong fix and commenting things out, just leave them
as-is and make a list of remaining errors so other devs can address them. :)

**Comment by ajrhacker** [comment]
When the old way now gives out fatal errors, leaving that untouched seems like the greater of two evils. The only pathological cases are various areas of color RAM in 8080bw.cpp and unkhorse.cpp, where the specified address mirroring for shared memory consists of bits in the middle of the offset range.

**Comment by happppp** [comment]
Ok, it looks like you can use AM_MASK to resolve this issue. See latest git
unkhorse.cpp that I updated just now.

**Comment by ajrhacker** [comment]
That's exactly how I just fixed 8080bw.cpp. I also undid the unnecessary handler split in timeplt.cpp.

**Comment by happppp** [comment]
Thanks

**Comment by galibert** [comment]
You can't, AM_MASK is ignored on AM_RAM.  I'll tell the bureaucrat to bitch.

  OG.

**Pull request merged**
