### PR TITLE
luaengine: addr_space:read_range()

### PR DESCRIPTION
**Pull request by vadosnaprimer**
_Removed outdated description._

### CODE REVIEW

**Comment by ajrhacker** [comment]
I have my doubts about this. Personally I see `get_read_ptr` as a somewhat obsolescent feature, since it won't work with Flash ROMs or any kind of memory emulated as something other than core RAM. It has even been known to fail when watchpoints have been set on a block of RAM.

**Comment by vadosnaprimer** [comment]
From my tests, address shift is accounted for in `get_read_ptr()`, so addressing remains the same here as with the space itself. So yes, `addrmask` accounts for shift as well.

Would it be fine if rely on `data_width` and use `space:read_*()` of the corresponding size? That way `count` would mean the number of addresses to read rather than bytes. Since `addr_space` is really address based and not byte based (anymore), that approach seems to make sense.

Please point out style errors I made, I'm not sure which part is wrong.

**Comment by cracyc** [comment]
If the part of the ram region that get_read_ptr returns is closer to the end than the byte count you'll overrun the buffer.

**Comment by vadosnaprimer** [comment]
I mean it won't be the byte count, but the amount of consecutive addresses to read.

**Comment by vadosnaprimer** [comment]
A bit lengthy due to checks and the switch, but I don't think read type can be deduced from data width directly. Otherwise, it now allows to specify everything relevant.

Step goes through every available address, so if address resolution overcomes data width you're reading, step needs to be increased. Width is bitwise, as usual for spaces.

**Pull request merged**
