### PR TITLE
fix power switch, kb beep and fdd sounds

### PR DESCRIPTION
**Pull request by kara1001000**
Here are the sounds for MikroMikko 1 and 5.25" floppy disk drives. All samples are recorded and mastered by me from my (still functional) MikroMikko 1, and hereby provided to be freely used within MAME. Implementation is MikroMikko 1 specific for the power switch click and the keyboard beep, but FDD sound implementation has been refactored in src\devices\imagedev\floppy.c. Sound is now available for both 3.5" and 5.25" drives (currently recognized from device tag), and implementation supports separate spin-up and spin-down samples in addition to the looping "motor on" sound. Up to 5 seek-sound samples may be defined for added variation and immersion. :) So far only 5.25 drives use the full capability of the FDD sound implementation, but it's easy to add better sounds also for other drive types as far as samples are available.

### CODE REVIEW

**Comment by startaq** [comment]
What's the exact drive model you recorded the sounds from? Eventually we should assign the correct sounds to the drive models, since they all sound a bit different.

**Comment by kara1001000** [comment]
I agree, and I wouldn't mind having own sound set even for each emulated machine, as the chassis construction can affect the sound pretty much. MikroMikko 1 has two 5,25", 640 kt floppy drives (quad density), driven by the NEC uPD765 controller. That's all the info I have without doing some intrusive exploration inside the chassis. Well, I know also that they are black, with red lights indicating motor/step action. :) Take a look: http://koti.mbnet.fi/~oju/retro/MikkoSystemFront.jpg

**Comment by Lord-Nightmare** [comment]
Can you take a closer/higher resolution picture at the front of the two drives?
They look like TEAC FD55B drives with black bezels, but there are several similar-looking drives that existed as well. (Also, if they are TEAC FD55BV drives, they have a head load solenoid, which makes a 'clunk' sound when the head is loaded. Normal TEAC FD55B drives the heads are loaded via the lever on the front.) They do not look like Tandon or Y-E Data drives, which had the lever on the opposite side of the front of the drive, Nor do they match Epson drives. Not sure about other manufacturers (Panasonic, Canon, etc)

**Comment by mr-t-guru** [comment]
there were *a lot* of companies making drives back then.
it'd be a whole lot easier and more accurate to just lift the top off and look on the back of the drive for the make/model sticker instead of guessing what might be.

**Comment by kara1001000** [comment]
Lord-Nightmare sir, you seem to be quite an expert recognizing old hardware: those drives are indeed TEAC FD-55's (and they do have a head load solenoid). I browsed my archives and found the schematics that were used when building my machine.

Maybe we should have also the "disk insertion" sound implemented in MAME. :)
For your entertainment, here's one more pic where you can see inside the FDD: http://koti.mbnet.fi/~oju/retro/MikkoInside.jpg

**Comment by Lord-Nightmare** [comment]
Ok, the question left is what type of TEAC FD55 series drives are they?
TEAC made the FD55 with a black bezel for multiple drive types.
FD55A is Single Sided, Double Density, 48tpi (40 tracks/side) (180K/disk)
FD55B is Double Sided, Double Density, 48tpi (40 tracks/side) (360K/disk)
FD55E is Single Sided, Double Density(Quad Density?), 96tpi (80 tracks/side) (360K/disk)
FD55F is Double Sided, Double Density(Quad Density?), 96tpi (80 tracks/side) (720K/disk)
FD55G (aka FD55GFR) is Double Sided, High Density, 96tpi (80 tracks/side) (1.2MB/disk)

Do you know offhand which of these the drives are? (How much data is stored per disk?)

**Comment by kara1001000** [comment]
This stores 640 kb of data / disk, after system tracks there is 628kb free for max. 127 files on an empty disk. Disk definition for cpmtools looks like this:

diskdef mm1dsdd
  seclen 512
  tracks 160
  sectrk 8
  blocksize 2048
  maxdir 127
  skew 3
  boottrk 2
  os 2.2
end

**Comment by mr-t-guru** [comment]
based on those numbers....
tracks * sectors per track * heads * 512
80 * 8 * 2 * 512  = 655360 bytes

If you have any floppy disks they can be backed-up and imaged using a DOS program called ImageDisk
which is available here.....
http://www.classiccmp.org/dunfield/img/index.htm
To use it: 
On a PC with a 5 1/4" HD floppy drive, in the GUI in settings set the number of
cylinders to 80, translate speed 300 -> 250 (to read a DD disk on a HD drive).
On the main menu press R to Read, type a file-name and press enter, press enter
again to skip the comment. Press enter again and it will read the disk and save
it to the HDD.

**Comment by Lord-Nightmare** [comment]
The MikroMikko drives here would have to be TEAC FD55FV, since they don't do 1.2MB disks (or do they?), but they do DD, 80 tracks, 2 sided (160 tracks total), and have a head load solenoid (V suffix for TEAC model number).

The difference between TEAC FD55GFR and FD55G, by the way, is that the former does both DD and HD disks (720k and 1.2MB, and both 300rpm and 360rpm, selected by jumpers or one of the shugart pins, see http://maben.homeip.net/static/S100/teac/diskette/Teac%20FD-55GFR%201.2MB%20floppy.pdf ) while the latter does ONLY HD 1.2MB disks (360rpm only; it might be able to read 720k disks but not reliably write them?)
See http://maben.homeip.net/static/s100/teac/brochure/Teac%20FD55%20summary%20specs.jpg

**Comment by kara1001000** [comment]
Yes mr-t-guru, I've already imaged all my 24 MM1 floppies, including many games and graphics programs that I wrote back in the days. Mandelbrot fractals with 8085, anyone? :)
http://www.ferrit.fi/images/MikroMikko%201/fract1%20full.jpg
http://www.ferrit.fi/images/MikroMikko%201/fract2%20full.jpg
(these took I think a day or two to calculate, each)

It's so cool to see all that old SW running emulated. I first used ImageDisk .IMD format, but then made .MFI (MESS image format) replicas out of them with MAME's File Manager and now use .MFI images only because they are R/W instead of read-only .IMDs.

MikroMikko 1 emulation is now very close to complete. Only issue seems to be with upd7220, reading pixels from display memory (CDOT call) freezes the system (unless it's a pixel that was just written to and we're not trying to read pixels from other places, too). May have something to do with FIFO timings.

**Pull request merged**
