### PR TITLE
[psxcd] The firmware image ROM sizes were wrong. And I also took the …

### PR DESCRIPTION
**Pull request by felipesanches**
…opportunity to add notes about the boards from which these ROMs were dumped.

### CODE REVIEW

**Comment by mr-t-guru** [comment]
Assuming the MCU is a custom chip and protected, how were they dumped?
They would still be considered incomplete/bad dumps IMO because the size is not a regular ROM size like 1k/2k/4k/8k/16k etc. Even if all the available on-chip ROM is not used they are still padded with either 0xff or 0x00 to fill all of the ROM space. for example if you read a 64kb ROM that is only half used you still get an 8k dump and the unused space contains 0xff. 
if we know how much ROM the (custom) MCU has it should be padded to that amount so the ROM becomes a standard size as per the original chip and/or datasheet specs.

**Comment by felipesanches** [comment]
yeah... I think you're right. The dumps were not done by me. The procedures are described by nocash here: http://www.psxdev.net/forum/viewtopic.php?f=70&t=557

**Comment by rb6502** [comment]
MCUs are 6805s that were dumped via test mode.  The specific model is known and has a non-power-of-2 ROM size, same as the Egret/Cuda 6805s in the Macs.

**Comment by smf-** [comment]
I know this is an old thread, but I wasn't around at the time and just 
in case someone cares.....

The dumps you get from the internal test are hex dumps (srec? format or 
something) of the entire memory map including ram and the boot rom. The 
boot rom on eprom parts allows you to program and test it, on the mask 
rom parts (I think) it just allows you to test it.

So those should be separate and the ram shouldn't be included, which is 
how I started adding them. No idea why anyone would undo that, but cest 
la vie.

**Pull request merged**
