### PR TITLE
Nes SL name fixes

### PR DESCRIPTION
**Pull request by Wintermute0110**
Filenames ending in a dot and with plain extensions cause trouble in some OSes. I have fixes those filenames to valid ones.

### CODE REVIEW

**Comment by cuavas** [comment]
Sorry, it isn't our intention to pander to this. Windows handles trailing `.` fine anyway, it's just explorer that doesn't like creating these names.

**Comment by etabeta78** [comment]
If you check PCB pics those are exactly the markings on the chips. As such
current names are the right ones.
Patch rejected.

   f.

**Comment by Wintermute0110** [comment]
Thanks @etabeta78

**Comment by etabeta78** [comment]
Thanks for checking anyway.
Other problems like trailing spaces you removed previously were indeed
mistakes in the list generation and they were good caughts :-)

**Comment by DavidHaywood** [comment]
So because capital letters cause 'problems' on one OS the field gets declared 'Not a label, but a filename'
and when a trailing dot causes problems on another OS the field gets declared 'Not a filename, but a label'

this is why the subject ends up making people angry, entirely inconsistent approach.  still haven't managed to win somebody over regarding the Capital change which is likely going to cost at least a clone or two.

**Comment by cuavas** [comment]
Perhaps adding a rule to disallow leading trailing `.` and ` ` is worthwhile.  Leading `.` is hidden on POSIX-alike and Windows explorer doesn't like creating them.  Trailing `.` breaks OS/2 and also upsets Windows explorer, cmd and 7zip.  Leading/trailing space is annoying to deal with in XML/SGML elements because of ignorable whitespace rules (needs CDATA markup).

**Comment by happppp** [comment]
I've removed the trailing dots in https://github.com/mamedev/mame/commit/e5d0d8ec029d767726fa3fe687df6fa3df0aecfe
If you need testing material for a future validity test update, it's easy to temporary generate your own.

@etabeta78 Let me know if you disagree with this and prefer something else, such as "_", as long as it doesn't end on ".".

**Pull request closed without merging**
