### PR TITLE
pc9801.cpp: add pc9801vx set, need someone to write machine config

### PR DESCRIPTION
**Pull request by qazmko1029**
This is not just a PR but also a request. Recently someone bought an unbootable PC-9801VX, who dumped the 4 EPROMs BIOS first and got the boards inside pictured/scanned to me. I'm not familiar with MAME development, made this dump to boot normally but obviously not enough for proper emulation, so it's a request for someone more specialized to write machine config for this machine. The remaining ROM chips would be dumped later and I'll upload them once done. Feel free to ask for anything needed.
pics:
https://drive.google.com/drive/folders/1cPBH7T1JZbOEZZRrdAvtwyxq7EIS-Bbs
All info.txt were me writing when checking the pics, it may be wrong because I'm not familiar with PC98 too...

Thanks for help!

### CODE REVIEW

**Comment by angelosa** [comment]
1. I have upstream changes, cfr. [pc98_state](https://github.com/mamedev/mame/tree/pc98_state) branch. I've just lost momentum because FDC mapping in NEC is always a fun deal. 
2. I also eventually need to add a `pc9821nr` machine among other things.
3. Please no ROM links in public but follow this [guide](https://wiki.mamedev.org/index.php?title=Submitting_Source_Code) instead.

**Comment by qazmko1029** [comment]
Removed roms in the link, sorry didn't read the guideline.

**Comment by angelosa** [comment]
Again, can you please submit romset to the attached email visible from [Submitting Source Code](https://wiki.mamedev.org/index.php?title=Submitting_Source_Code)? I totally need to fix up some stuff in order to emulate this properly, therefore may as well do that in the [feature branch](https://github.com/mamedev/mame/tree/pc98_state)

**Comment by qazmko1029** [comment]
Romset has been sent via email, no difference with last upload. Please check.

**Comment by angelosa** [comment]
Addressed by https://github.com/mamedev/mame/commit/c6b9580ca76b2b68b8972b1a1d3bc4dd7d16d43d

fwiw V30/286 CPU switch is unimplemented, I have no idea yet how that works out in HW. For the time being 286 can run V30 compatible mode by just flipping a dip-switch hooked in configuration.

Dump is functional btw, can run Basic, MS-DOS etc. just fine.

This PR can be closed, thanks.

**Pull request closed without merging**
