### PR TITLE
Synced with GENie upstream revision e78d6c1

### PR DESCRIPTION
**Pull request by belegdol**
Please do not merge this yet, I still need to test the changes. Once merged this will resolve issue #5597.

### CODE REVIEW

**Comment by belegdol** [comment]
OK, I believe this should be now ready for wider testing. Both travis builds have succeded, and so did a local
```
make -j12 TOOLS=1 VERBOSE=1 PYTHON_EXECUTABLE=python3
```
The appveyor build has failed as expected, I believe this one will only start working once the image is updated for VS2019 16.3.
Please test vsllvm in particual, this is where I had to do most of the manual merges.

**Comment by vadosnaprimer** [comment]
Just a note that VS version we want is **[16.3.0 preview 3.0](https://developercommunity.visualstudio.com/comments/723675/view.html)**, and appveyor only has **[16.0.0 Preview 2.1](https://www.appveyor.com/docs/windows-images-software/#visual-studio-2019)** yet. Once appveyor adds this to its `Visual Studio 2019 Preview` image, CI should start working again.

Meanwhile I tested the full build locally and in fact, there are some minor bugs to be fixed, but that's for a separate PR anyway.

**Comment by belegdol** [comment]
The non-Preview image is as far as Visual Studio Community 2019 version 16.2.3 but that is still too old.

**Comment by belegdol** [comment]
Hmm, it looks like genie now hardcodes -m64 in the makefiles needed to build itself:
https://github.com/bkaradzic/GENie/issues/425
https://github.com/bkaradzic/GENie/issues/475
This means building on any architecture not supporting it (aarch64, armv7hl, i686) will fail. Sadly the issues were closed without code fixes.

**Comment by belegdol** [comment]
Please do not merge yet, I will try to fix the hardcoded -m64 over the next few days.

**Comment by belegdol** [comment]
This is as good as I can make this PR currently. Even with -j2 the appveyor gcc build runs out of time during linking sometimes and sometimes finishes on time. I am open for suggestions how to speed it up even further. I hope this is not a merge blocker.

**Comment by belegdol** [comment]
I have now tweak the appveyor config to give it the best chances of succeeding: changed the number of threads to 3 and enabled pacman cache.
If this is still not enough, appveyor support seem to be open to extending the timeout when asked.
Please let me know what you think about this PR, I am also happy to split the appveyor tweaks into another PR if this is preferred.

**Comment by rb6502** [comment]
I'm generally fine with this, but I'm going to hold it until after the release is branched because changing the build system the day before a release branch is probably a bad idea :)

**Comment by belegdol** [comment]
@pmackinlay, it appears like we should join forces. Your latest updates seem to have excluded GCC build entirely.
Should I rebase? Or create a separate PR to fix the GCC build first? Thanks for letting me know!

**Comment by pmackinlay** [comment]
@belegdol my apologies, I wasn't paying attention to your work here, and just tried tinkering with the appveyor.yml to see if the new vs2019 16.3 image would build. Please feel free to revert/overwrite the changes I made, because they were really only an experiment in any case. I support removing all MSVC configurations prior to 14.23 (VS 16.3); only 15.7.6 works, and there's no image for that on AppVeyor. The end result would be one gcc build and one msvc build.

Have you checked to see if it's possible to stop GENie from setting the msbuild tools and Windows SDK versions altogether, and instead relying on whatever's installed?

Regarding MSVC 14.23, I believe there are 4 outstanding problems:
* 3rdparty\bgfx\3rdparty\dear-imgui\widgets\dock.inl(748): warning C4701: potentially uninitialized local variable 'tab_base' used
* src\lib\netlist\plib\pstring.h(202,1): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>'
* src\tools\jedutil.cpp : fatal error C1001: An internal error has occurred in the compiler
* src\tools\imgtool\filtbas.cpp : fatal error C1001: An internal error has occurred in the compiler

Obviously the latter two only show up in TOOLS=1 builds, but clearly they're the more serious ones that may require test case analysis and submission to Microsoft.

I raised an issue with bgfx upstream to see if they'll consider initializing the tab_base (the warning is bogus, but it seems both clang and msvc produce it). Not sure if clang builds are suppressing this warning in the MAME build environment?

The netlist pstring one exceeds my C++foo, @couriersud, do you have any thoughts or time to investigate this one? I assume it's something related to wchar_t instead of char.

**Comment by belegdol** [comment]
@pmackinlay, no worries, it would be unrealistic to expect every dev to check every PR prior to submitting changes. I just wanted to make sure that we are both aware of each other's work.
I will aim to rebase by the end of the weekend.

Regarding the versioning of the platform toolset, I am not sure, but so far the evidence seems to indicate that the targeted version is determined at the time project files are created.

Regarding the two ICEs: @yz70s, is this something you might be able to help with?

**Comment by yz70s** [comment]
> Regarding the two ICEs: @yz70s, is this something you might be able to help with?

Yes i will check them this evening.

**Comment by yz70s** [comment]
I have done some tests, and in my computer the internal error happens only in debug builds, not release ones.

**Comment by yz70s** [comment]
The error report is here
https://developercommunity.visualstudio.com/content/problem/752372/vs2019-v1631-c-internal-compiler-error-when-zi-opt.html

**Comment by belegdol** [comment]
The PR is back in mergeable state now, please let me know if anything else should be adjusted.

**Comment by tcamargo** [comment]
Hi,
````
ifeq ($(ARCHITECTURE),_x86)
MPARAM := -m32
else
ifeq ($(ARCHITECTURE),_x64)
MPARAM := -m64
else
MPARAM :=
endif
endif
````
This change broke cross compilation to x86 from a x64 host. It is forcing -m32 when the correct is -m64 or null.

Build log: https://pastebin.com/HcqUXHLs

It happens because I can make with PTR64 to 0. Should we consider CROSS_BUILD for that check?

Thanks!

**Comment by belegdol** [comment]
IIRC prior to the change there was no -m32/-m64 passed to genie build at all. Upstream then forced -m64 across the board which this little logic is trying to address.
How is the target CPU arch defined during cross build? The best solution would be to use that.

**Comment by belegdol** [comment]
Can you try moving the MPARAM block further up in the makefile, after
```
endif # TARGET_OS
```
and see if it helps? Genie always needs to run on the host so target architecture and PTR64 is irrelevant here.

**Comment by tcamargo** [comment]
> Can you try moving the MPARAM block further up in the makefile, after
> 
> ```
> endif # TARGET_OS
> ```
> 
> and see if it helps? Genie always needs to run on the host so target architecture and PTR64 is irrelevant here.

It works. PTR logic does not apply and MPARAM is set to -m64.
it would be nice to differentiate TARGET_OS/CPU from HOST_OS/CPU. It is a bit mixed up IMO.

**Pull request merged**
