### PR TITLE
x68k: Added some clones to the software list

### PR DESCRIPTION
**Pull request by nekoziman**
- New software list additions
  aqualesd    Aquales (Demo)
  genocid2da  Genocide 2 (Demo, Alt)
  gradius2d   Gradius II - Gofer no Yabou (Demo)
  lagoond     Lagoon (Demo)
  lagoondo    Lagoon (Demo, Older)
  lemmingsd   Lemmings (Demo)
  phalanxd    Phalanx (Demo)
  starwarsd   Star Wars - Attack on the Death Star (Demo)

http://wayder.blog102.fc2.com/blog-entry-2985.html

### CODE REVIEW

**Comment by rb6502** [comment]
Could you please re-push with a slightly more descriptive name, like "x68k: Added some clones to the software list" or similar?  That makes it much less error-prone to assemble the readme for the next version.

**Comment by nekoziman** [comment]
I'm sorry to trouble you. label name is changed.(assigned just as it.) thank you.

**Comment by Tafoid** [comment]
This software is not, as far as I can tell, publicly available, so it cannot be tested.   Please contact someone on the Dev team directly to address this or use CODE at MAMEDEV.ORG contact email to provide a source for these added images.  If you are not able to produce the images before release next Wednesday (September 28), we will be forced to revert this addition.

**Comment by nekoziman** [comment]
sorry that response was late.
please e-mail to necoziman@gmail.com (or please use twitter https://twitter.com/nekoziman/)

**Pull request merged**
