### PR TITLE
nmk/nmk16.cpp: Added new Big Bang set

### PR DESCRIPTION
**Pull request by sergiopolog**
New WORKING clone
-------------------------------
Big Bang (9th Nov. 1993 set 2) [Sergio Galiano, Recreativos Piscis]

### CODE REVIEW

**Comment by sergiopolog** [comment]
Found in a factory converted Macross II pcb, such as many other (or all) Big Bang game pcbs out there.

Same date (9th Nov. 1993) present in the code and in test screen.

Sound cpu code and gfx and oki roms are the same as parent set, in the same way as current Big Bang set is.

I also renamed the current Big Bang set as: "Big Bang (9th Nov. 1993 set 1)" to differentiate them, as I didn't figure out if this is a newer or older revision of the code.

**Comment by DavidHaywood** [comment]
Yeah NMK didn't bother to update the dates on these when they updated the code, in some cases the date is even the same for different games.  Annoying, but we've seen it across many games.

**Comment by sergiopolog** [comment]
Yep, I see the same case for Saboten Bombers.

As some friend point me up, this is probably a newer version of the code, due to strings on the code are shifted some bytes forward in the rom, denoting that some code was introduced in between (probably some bugfixing or further checks).

In that case, should I re-order the sets in the code to make "parent" the newer?

In fact, here is a picture (the best I have now) of the PCB: https://i.imgur.com/U4IjxeI.jpg
Same as other Big Bang PCBs made over Macross II korean board

**Comment by DavidHaywood** [comment]
unless you study the code it's difficult to know, smaller code could be better optimized, rather than larger code having bugfixes.

**Pull request merged**
