### PR TITLE
Address map fixes (nw)

### PR DESCRIPTION
**Pull request by ajrhacker**
- tms32025: Correct space of internal data maps
- mc1000: Separate out opcodes map
- addrmap.cpp: Replace a few debug asserts with friendlier error messages (makes validation less dangerous in debug builds)

### CODE REVIEW

**Comment by cuavas** [comment]
It's desirable for things to blow up in debug builds if they're wrong.  That's the point of `DEBUG=1` - it enables assertions.

**Comment by galibert** [comment]
I indeed fucked up the ram at 2800, but what do you have against
AM_IMPORT_FROM?

  OG.

**Comment by ajrhacker** [comment]
@cuavas: In many cases, assertions that make things blow up are useful in debug builds. Here, however, the default assert message is particularly uninformative for a common copy/paste error that will be encountered by the validity checker and should be properly reported for its sake.

@galibert: The only thing I have against AM_IMPORT_FROM is that it fails the formerly asserted check when the address space numbers don't match.

**Comment by galibert** [comment]
Oh fuck, a side effect of configure.  The last one wins.  Damn.

Well, the address space number is going to go, I expect, so we'll revisit
that later :-)

  OG.

**Pull request merged**
