### PR TITLE
NetBSD fixes

### PR DESCRIPTION
**Pull request by 0-wiz-0**
The patches in this pull request are build fixes for NetBSD.
One of the is needed for new versions of fontconfig.
Please merge them.

### CODE REVIEW

**Comment by mmicko** [comment]
Sorry, all updates to 3rdparty have to go there, not over us.

Micko

**Comment by 0-wiz-0** [comment]
Hm, take one of the four then, please (scripts/src/ is your code, right?) and I'll try to feed back the others upstream.

**Comment by mmicko** [comment]
right will take that one.

Micko

**Comment by 0-wiz-0** [comment]
Ok, filed upstream pull requests for all of them, please apply when you can. Thanks.

**Comment by mmicko** [comment]
applied

**Pull request closed without merging**
