### PR TITLE
Creating a -plugin_optional command line parameter to request a plugin to be loaded, but not failing if unsuccessful

### PR DESCRIPTION
**Pull request by npwoods**

### CODE REVIEW

**Comment by happppp** [comment]
That doesn't sound very useful at all

**Comment by cuavas** [comment]
I agree with @happppp – this is likely to lead to more confusion than anything else.

**Comment by npwoods** [comment]
BletchMAME composes MAME command line parameters that are not necessarily exposed to the user when started up.  I want to use the cheat plugin if its there, but not to fail if it is not present.  How do I achieve this soft dependency?

**Comment by cuavas** [comment]
Well, the cheat plugin should always be there since it’s part of a standard distribution.  But the proper way to find available plugins would be to walk the configured plugin directories and discover them.

**Comment by cracyc** [comment]
The cheat plugin is just a lua script, you should be able to run it directly from your own initialization code like boot.lua does then you can handle any failures yourself.

**Comment by npwoods** [comment]
I suppose the real question is how are plugins supposed to activate each other in a "soft" fashion.  Scanning the directories or simply assuming that the cheat plugin is available just because it comes with MAME feels like a sloppy solution.

Boot.lua does the heavy lifting of identifying and loading the plugins that are identified by the MAME executable as "to be loaded".  Perhaps this manifest of plugins (and the ability to mark plugins as "to be loaded") needs to in turn be exposed in and of itself?

**Comment by cracyc** [comment]
>I suppose the real question is how are plugins supposed to activate each other in a "soft" fashion. Scanning the directories or simply assuming that the cheat plugin is available just because it comes with MAME feels like a sloppy solution.

Scanning the directories is what mame already does so it's not really more sloppy than what already happens.

>Boot.lua does the heavy lifting of identifying and loading the plugins that are identified by the MAME executable as "to be loaded". Perhaps this manifest of plugins (and the ability to mark plugins as "to be loaded") needs to in turn be exposed in and of itself?

Boot.lua doesn't do much after your changes from last year.  The manager:plugins() function returns a list of plugins and their paths so
```
local cheatentry = manager:plugins()["cheat"]
local cheatplugin
if cheatentry and not cheatentry.start then -- don't try to start it twice
	local stat, res = pcall(require, cheatentry.name)
	if stat then
		cheatplugin = res
		cheatplugin.startplugin()
		if cheatplugin.set_folder~=nil then cheatplugin.set_folder(cheatentry.directory) end
	else
		print("cheat plugin load error " .. res)
	end
end
```
ought to work.

**Comment by npwoods** [comment]
I was able to get this technique to work - closing out this issue

**Comment by npwoods** [comment]
I must admit that one concern I have about this approach is that I feel that I'm too exposed to how boot.ini works, but if crazyc endorses this approach I'll do it.

**Comment by cracyc** [comment]
I don't think it's that exposed to boot.lua since the script above doesn't depend on anything from boot.lua.  It's very dependent on pluginopts.cpp but your plugin_optional would too.  The biggest issue I see is people not upgrading their plugins with new versions of mame.

**Pull request closed without merging**
