### PR TITLE
getaway.cpp: various updates, promoted to working

### PR DESCRIPTION
**Pull request by angelosa**
new WORKING machine
------
Get A Way [hap, Angelo Salese]

### CODE REVIEW

**Comment by happppp** [comment]
The improvements are awesome =)
You wanted a review?

imperfect_graphics flag: the extra 24KB VRAM for the score panel is not right, resolution is not likely 256x256, and missing green grass at the edges.
imperfect_controls flag, for steering wheel failing, especially with xbox pad instead of keyboard

Or if I'm honest, the game is not ready to be marked working yet.

Another small thing, in screen_update the r,g,b variable names are incorrect now that the palette is BGR.
If it's BGR then it's r<<2 | g<<1 | b;

**Comment by angelosa** [comment]
> imperfect_controls flag, for steering wheel failing, especially with xbox pad instead of keyboard
> 

I dunno, it kinda works with digital input hooked to Dec/Inc (tested with keyboard and xbox one), I honestly don't know how to cope with this being a peculiar case (maybe it's an `IPT_POSITIONAL`?) :woman_shrugging: 
I also digress that's a pretty common experience with me wrt. xbox one pads, I rarely use raw analog setting cause MAME doesn't seem to cope well with our legacy system (cfr. stuff like _Buggy Challenge_ being a chore to play in MAME on it vs. Taito Legends 2 port).

> Or if I'm honest, the game is not ready to be marked working yet.
> 

imho other than the addressed issues I don't see anything worth to be marked as MNW, especially considering the limited exposure that TMS9900 core has so far.

**Comment by cuavas** [comment]
Is it actually possible to play a complete game properly?  If the controls are flaky I’d be inclined to keep the not working flag for this release until it’s improved.

**Comment by happppp** [comment]
digital controls: alright, with small issues sometimes
analog controls (eg. left stick on xbox pad): very hard

**Comment by cuavas** [comment]
I think marking this working is premature.

**Comment by happppp** [comment]
Yeah, but Kale thinks not and I think the decision is up to him since he did most of the driver work. I'm going to merge it.

**Comment by DavidHaywood** [comment]
I think working is a bit premature too.  As I've said before, I think we've reached the point where even completely missing sound is a serious issue, and we shouldn't be promoting until there's something, but that's just me.

If not, I guess Fantasy Story can be promoted too, although I really wanted to see the PICs decapped first and sound added.

**Comment by happppp** [comment]
This is outdated: the steering wheel control was fixed by cuavas.

**Comment by angelosa** [comment]
To my interpretation, "working" state is a matter of consuming the medium without any breaking issues. 
It is not for this specific game, where the sound department is just a collection of "samples" and an incrementing engine noise, nothing that can be considered an important sound cue to the player. That's what `MACHINE_NO_SOUND `covers already.

**Comment by MooglyGuy** [comment]
The question of whether it should be flagged MNW had nothing to do with sound and everything to do with whether it could be controlled in a reasonable manner. Until Vas's changes, it wasn't, and it made perfect sense to have it marked as not-working. After the fixes, it does seem to be working, albeit with some caveats, which are now marked as appropriate.

`MACHINE_IMPERFECT_CONTROLS` is something that is more applicable to consoles or computer systems than arcade machines. Something like an additional controller not being fully supported. In the few cases where it would be applicable to an arcade machine, it would only apply to cases where an arcade machine has a swappable control panel, where one works perfectly but the other might not necessarily be supported.

In the case of an arcade machine where none of the controls work quite right, then MACHINE_IMPERFECT_CONTROLS is imply a cheap dodge around the fact that the machine should otherwise be marked MACHINE_NOT_WORKING. For arcade machines, the controls are the primary mechanic by which people will interact with the machine, and if that isn't up to spec, then it doesn't matter how accurate any other aspect of the machine is, it's still not working by any reasonable definition.

Please try to look at it from the standpoint of our ostensibly stated goal, historical preservation: This is a game that few people knew even existed, it just kind of came out of nowhere, from a company that made subsequently fairly well-remembered games like Mr. Do.

MAME is promoted as being oriented around accuracy, and with that in mind, if people try to play the game and have a bad time due to the controls, it isn't going to reflect so much on MAME. It will instead reflect on the conclusions people come to about the game, that it had faulty controls, when it really is, or in this case was, an issue with MAME.

If this were any number of the other relatively obscure games that have previously been prematurely promoted to working by one of the parties involved, I would agree with perhaps promoting it and letting the cards fall where they may, but we're not talking about that here. We're talking about a very little-known game, from a manufacturer that went on to do fairly significant things. If anything, that should put the quality bar higher, not lower, for marking it as working.

**Comment by DavidHaywood** [comment]
I go with 'if you drop the not working flag, it must be something you'd consider shipping in a commercial product'

That is how people view MAME these days, if we say something works, they expect that quality.  Our own accomplishments have set that bar.

**Comment by happppp** [comment]
A commercial product... I'd spend a few hours making the graphics and colours look nice with a dozen hacks. Hacks that are unrealistic from a technical pov and would have no place in MAME.

I'd also try to acquire sound recordings and add samples, again with a couple of hacks. All to make it nicer for the end-user in an as quick as possible development time.

**Comment by MooglyGuy** [comment]
Yeah, great. You both can prevaricate all day long about what you would do if MAME were a commercial product. Have fun with that.

But fact that MAME isn't a commercial product doesn't absolve us of our stated goals. And providing an accurate portrayal of the code or hardware is what we're after. As such, `MACHINE_NOT_WORKING` should be used pretty freely unless the machine is actually playable from an end-user standpoint. Until Vas's control fixes, it wasn't.

You can laugh about it and pretend like this is some big joke, @happppp, but that just reflects on your own lack of real commitment to what MAME is about, and will be taken into account in the future.

**Comment by happppp** [comment]
My cynical remarks were to point out that comparing MAME's quality standards to a commercial product is a bad idea.

**Pull request merged**
