### PR TITLE
68k: support for external MMU bus error instruction restart

### PR DESCRIPTION
**Pull request by agentbooth**
For review -- this is a proposed fix to address #9170 - suggested for @rb6502 to review. Also of interest to @pmackinlay 

Intended use:
`m_maincpu->set_emmu_enable(1);` called from machine_reset()

When page fault occurs desiring instruction restart, call:
`m_maincpu->set_buserror_details(fault_addr, rw, m_maincpu->get_fc(), true);`

`m_mmu_tmp_buserror_occurred` is set and then detected in execute_run()

If non-instruction restart bus errors are needed, the existing method can be used:
```
m_maincpu->set_input_line(M68K_LINE_BUSERROR, ASSERT_LINE);
m_maincpu->set_input_line(M68K_LINE_BUSERROR, CLEAR_LINE);
```

I also added setting of fault address in the 68010 and 68070 stack frames as this was not supported, but is for some other stack frames. Likewise also added rw and fc setting in 68010 special status word.

### CODE REVIEW

**Comment by cuavas** [comment]
@galibert and @rb6502 can you both look at this?

**Comment by rb6502** [comment]
@cuavas This comes from an issue.  I provided guidance there and none of it was followed.  This is a hard reject.

**Comment by agentbooth** [comment]
@rb6502 I intended to follow your guidance but it sounds like this is not what you had in mind. I was unable to just set m_mmu_tmp_buserror_occurred in set_buserror_details() and then set the bus error line as I mentioned here:
https://github.com/mamedev/mame/issues/9170#issuecomment-1045461600

 Perhaps you, @pmackinlay or someone else can provide a more suitable solution that addresses #9170 in the future.

**Comment by rb6502** [comment]
This isn't quite as bad as I thought it was - it's very confusing to review PRs made of multiple interlocking commits.

I'd still like the ultimate mechanism to be pulling the bus error line though, because that's how hardware actually works.

**Comment by agentbooth** [comment]
I apologize for the mess of commits, the relevant one is solely: https://github.com/mamedev/mame/pull/9369/commits/9eb63247dd84673e71f458c30b0d374d814bef6d 

Definitely agree with the goal of triggering the bus error line, but we have stack frames then being set in two places (cause_bus_error and execute_run) so will have to look at another solution to prevent that from happening.

**Comment by rb6502** [comment]
I'm going to approve this for now since it enables obscure UNIX and I love obscure UNIX, but I'd still like to rework this when I'm in the proper headspace.

**Comment by agentbooth** [comment]
Thanks @rb6502 --- I agree this is solution is a bit cryptic - as we really should be setting the bus error line. But as things are currently handled with the instruction restart handling, this was the simplest I could come up with and was what @pmackinlay had done in his testing, which had been recommended for the near term solution. I'll try to get my AT&T UNIX PC driver cleaned up so others can review and potentially help out. I'm at a bit of a wall at this point, UNIX has trouble attempting to init.

**Pull request merged**
