### PR TITLE
ygv608: Namco Classic Collection vol.1 & 2 Graphics improvements

### PR DESCRIPTION
**Pull request by agiri-san**
This patch fixes rotzoom behavior used in Namco Classic Collection vol.1 & 2.
Verified against actual PCBs.

In NCV1 Xevious Arrangement, scrolling-by-row feature is used to draw and move UFOs in 'AREA 8'.
I think this is the only part where the feature is used (but I'm not sure whether the feature is used in other games on the boards).

### CODE REVIEW

**Comment by sjy96525** [comment]
I play the Namco Classic Collection 2 Dig Dug Arrangement has a Graphics Corruption After Stage 30.
https://imgur.com/kXSMb93.png

**Comment by agiri-san** [comment]
Thanks for your reviewing.
I'm going to play Dig Dug Arrange to reproduce this screen.

**Comment by agiri-san** [comment]
I was running some of recent versions.
This graphics corruption exists in mame0190 release ver, and in older versions (I tested mame0190 and mame0185).

**Comment by rb6502** [comment]
sjy96525 is a sort of a troll, they were trying to task you with more things to fix rather than reviewing your changes.

**Pull request merged**
