### PR TITLE
new driver: ZAP - Z80 Applications Processor (by Steve Ciarcia - 1981)

### PR DESCRIPTION
**Pull request by felipesanches**
based on the book "Build Your Own Z80 Microcomputer" published by BYTE / McGRAW-HILL

### CODE REVIEW

**Comment by LnmVolbo** [comment]
Once the ROM dump of "zap.rom" became available, I found that there seems to be two errors in the transcription from the source code listed in the published book referenced above.

The first one seems to be a typo caused by poorly placed speck on the photocopier on the character "C", making it appear to be a "G", which the transcriber must have thought was a "6", as the value in the ROM dump is 0x62.  This is at location 0x245.  If one looks a the assembly code for that line, it is "JP   NZ,WARM2".  Fortunately there is another assembly line with the same code ("JP   NZ,WARM2") at location 0x253.  The values for this line are 0xC2 0x89 0x00.  So the value for location 0x245 should be a 0xC2, not 0x62.

The second problem is at location 0x375.  The book indicates that the value should be 0xBF, while the ROM dump indicates that it is 0xFE.  The value of the next location in the ROM dump is 0x0D, which seems to be an accidentally inserted value.  The values indicated by the book from location 0x376 and forward match the ROM dump starting at location 0x377.

I am also wondering about the choice of 0x00 to fill the not-specified bytes in the DS statements and the ST statement at the end of the code of the assembly listing.  It is my understanding that unprogrammed areas of ROMs from this era were left at the default erased value of 0xFF.

Posting this info in case there was a transcription error.

Here is a link to what I consider to be a more accurate transcription of the source code from the book.  I have included both 0x00 fill and 0xff fill versions.

https://www.sendspace.com/file/yqoo6n

**Comment by felipesanches** [comment]
Hey, @LnmVolbo ! Thanks for catching these :-)

You are absolutely right about the first one. I'll fix it in the ROM and update the driver with the new checksum.

I am a bit unsure about the second issue, though. My book is the Brazilian Portuguese edition. In my book it is indeed written:

* 0375 FE 0D          CP A, 0DH
* 0376 CA 91 03      JP Z, TTYIN2       * Jump if carriage return
* and so on...

It is clearly an issue in the book as the memory address only increments while it should increase by 2.
I saw this when I was transcribing the ROM. But I thought it was just a typo in the address values.
I actually have written with pencil in my book a not aobut the whole address range starting at 0376 being offset by 1.

The weird thing is that FE 0D actually means CP A, 0DH and BF means CP A (compare A with itselt, meaning, check if it is zero or nonzero). And 0DH actually means "carriage return" in the ASCII table, so my version would make more sense. At the same time, the jump addresses that exist within the off-by-1 block are consistent with the wrong addresses displayed in my version of the book. So I am puzzled.

The patch in the brazilian book seems to be very intentional and not a typo. The off-by-1 in addresses may be just a mistake in calculating the address values while the change may be an intentional "improvement of some sort. Maybe an attempt to fix an actual bug of the original english version?
I think I need to study the whole source code and decide

**Comment by LnmVolbo** [comment]
Thank you for responding.  I did not realize your source was a different publication.  The publication I am referencing is here: https://www.modmypi.com/download/BuildYourOwnZ80.pdf

Here are the lines around 0x375 from this version of the book:

<CODE>0372 DB 02            5570         IN    UARTIO        @GET INPUT CHARACTER</CODE>
<CODE>0374 77               5580         LD    (HL),A        @SAFE CHARACTER IN USERS BUF</CODE>
<CODE>0375 BF               5590         CP    A,0DH</CODE>
<CODE>0376 CA 91 03         5600         JP    Z,TTYIN2      @JUMP IF CARRIAGE RETURN</CODE>
<CODE>0379 3E 01            5610         LD    A,ONE         @SET OUTPUT CHARACTER COUNT</CODE>
<CODE>037B 22 FB 07         5620  TTYIN3 LD    (TTYOBF),HL   @SET OUTPUT BUFFE ADDRESS</CODE>

(I had to place @ for the * in the comments, due to the automatic markdown here on GIT)

As you can see, assembly code and comments matches your version, and the value at the location 0x375 does not.

Now that I look closer, I agree with you on the second apparent error I mentioned in my first message.  It looks like the version you are working from has been corrected from the version I was looking at.  Your analysis of the "off by 1" block seem correct to me.

I would not be surprised at all if the first edition publication was incorrect.  Reading BYTE Magazine all those years ago, I found that it was not unusual that program listings were published in their preliminary state, rather than a final confirmed version.  And a future issue may print a correction.

**Comment by felipesanches** [comment]
so, yeah... I gotta load this into the emulator and check if the brazilian version actually is a valid fix.
It seems they got addressing wrong when attempting to fix that opcode error. Maybe both versions are broken. Then I think we'll have to fix it ourselves and leave a compilation of the relevant portion of these comments in the source code for the sake of historical record.

**Comment by felipesanches** [comment]
I'll try to do it tomorrow.

**Comment by Robbbert** [comment]
I tried examples given in the book, but bugs show up immediately, both with the new and old roms. For example, the edit memory function (Shift-1) hangs after the first digit is entered. Since this makes the computer useless, I'd suggest fixing this be made a priority.

**Comment by LnmVolbo** [comment]
I was able to follow the examples in the book using this image:

https://www.sendspace.com/file/bx2n8m

And this checksum info:

    <rom name="zap.rom" size="1024" crc="669b5f13" sha1="545184c720dceccbda4829bd1596262a277929e0"/>

It is the image with the first typo corrected, and the second typo left as-is with the extra 0x0D character inserted at 0x376. (and 0xFF filling the undesignated memory locations)

Not all the examples were verbatim, but nothing locked up. When storing data, it always read back properly on the read.  The things that weren't identical to the examples in the book were things like reading uninitialized memory locations.

It looks like shift-1 is only supposed to enter a single digit, then the "next" (right arrow) button is to be pushed a couple of times to see any changes on the display.

**Comment by Robbbert** [comment]
Sorry about the email earlier, I had made a mistake.

It sounds like this latest rom should be the one to use. BF is most certainly a mistake, FE 0D is what I would expect to see there.

**Comment by LnmVolbo** [comment]
**Robbbert**, I think what crossed you up was the first typo at 0x245.  That one looks like it could cause a hang because it would interfere with execution getting back to the top.  I don't think we are testing the  area of the 2nd typo because it is in the middle of the TTY routines, and not in the entry routines that are tested by the examples in the book.

Thank you for suggesting to test by the examples.  I was dimly aware they were there, but had pretty much forgotten about them.  I hadn't tested them myself until after you mentioned it.

**Comment by Cowering** [comment]
Steve is still around.  He recently bought the rights to Circuit Cellar 
back from some place in the Netherlands.  He seemed friendly enough when 
I chatted with him in the early 80s at some conventions.  He has made 
the book available at 
http://www.scribd.com/doc/13388965/Build-Your-Own-Z80-Computer and I'd 
bet he would gladly give up the original and/or updated ROM. Back in the 
early 90s, BYTE subscribers got an offer for a CD with the complete BYTE 
index up to that time (1992-3).  IIRC it had notes about the original 
article, and any 'important' followups such as a revised review of a 
product. I don't know if the index had updates to previous projects (or 
this separate book). I do know that Steve would do updates if you msged 
him on BIX with a bug.

Just my remembrances, hope it helps someone

Cow

**Comment by felipesanches** [comment]
Observing the PDF and comparing it to the brazilian edition I noticed a few interesting things.
Editing and typesetting of the book for translation into portuguese was done by cuting sheets of paper and photocopying the mosaic of "patches" instead of by re-typing the whole thing from scrach in a type-writer. That's why the dot of dirt on top of 0xC2 remains in the portuguese version.

Also, I can see in some regions the borders of the paper sheets that were use to substitute the english text comments by the equivalent comments in portuguese. In some places the paper even covers partially some of the '*' characters. :-P

So, it means that by (literaly) cutting and pasting they decided to fix a bug, but forgot to edit the values of the addresses. So that's the source for the "off-by-one" issue in addressing.

**Comment by LnmVolbo** [comment]
If anyone is curious how this issue was resolved, see this:

https://github.com/mamedev/mame/commit/e1cad4365afe0f75f50e0a53215af7805fa28f4f

**Pull request merged**
