### PR TITLE
z80: interruptible execution

### PR DESCRIPTION
**Pull request by holub**
Credits:
* undocumented flags - Manuel Sainz de Baranda y Goñi, Peter Helcmanovsky, Patrik Rak
* tables removal - smf, happppp, Lord Nightmare

z80 interruptible implementation is ready for review
Main execution don't overflow scheduler frame more than 3 icounts (atomic for IO read/write)
take_interrupt() hasn't been converted yet (possibly TODO)

Drivers which must be updated before all TIME_GUARD sections completle removed from the code:
* ~~Amstrad~~
* ~~MSX~~
* ~~System1~~

### CODE REVIEW

**Comment by holub** [comment]
More confident now... Let's try to make it happen!

**Comment by holub** [comment]
drives identified as broken with PR:
* sigmab98.cpp - all machines

**Comment by holub** [comment]
All not working drivers identified with testing fixed!

**Comment by simzy39** [comment]
Can you mark this as Ready for Review?

**Comment by holub** [comment]
> Can you mark this as Ready for Review?

I think it is. Yet actuated with current master.

**Comment by DavidHaywood** [comment]
There seem to be 2 lines of thought with this, yet surprisingly nobody leaving comments here.

The first is that the Z80 code is already ugly, relies too much on macros, and trying to fit these changes in a core never designed for it is a waste of time and we should just wait for a complete new core.

The other is that this is the best way to get these changes, as it built on top of a mostly trusted Z80 core, so if things break in the process it'll be easier to identify and fix, whereas a brand new core would almost certainly come with it's own set of problems at first that might make it difficult to identify the source of issues.

I'm in the latter camp, I think this is worth doing, but maybe the lack of other comments / movement suggests that is a minority opinion.

**Comment by holub** [comment]
I agree lack of comments on this PR is discouraging.
IMHO we can wait for new z80 core for another 15 years or take advantage from these changes immidiatly. It's already provides big step forward and I think using it I can reimplement Spectrum memory contention using WAIT state, without playing with icount.
Macroses are ugly but without them the changes look even worse with anonymous functions. And frankly a lot of original macroses removed here.

I open to any suggestions if anybody is  interested.

**Comment by smf-** [comment]
I don't know what the performance difference is, but I still think with
the macros that this will be easier to deal with than a python code
generator.

**Comment by holub** [comment]
We should expect performance drop because old code was highly optimized with inlining which is not possible in inerruptible version. Based on my naive "max frame skip" performance test, the drop is ~40% from original.
That is still acceptable for z80 as it's not expected to run with clock faster than 20MHz.

**Comment by DavidHaywood** [comment]
ultimately this is going to be the decision of @cuavas 

will you allow this route to be taken? aside from a performance decrease (which will happen if a new cycle-accurate core is written from scratch) this doesn't inherently seem worse than what we have on a technical level.

personally I'd like it if at the point we get python generated cores, that it be possible to generate 2 different cores, one 'performance' core, where we're confident that cycle accuracy never comes into play, and another where it does, in order to reduce any performance loss for the less demanding cases, but if such a core is written we can deal with it at the time.

as it stands there are a number of cases where improving the Z80 is going to be important and could lead to improvements in the emulation of other components.

**Comment by DavidHaywood** [comment]
@cuavas since no consensus can be reached on this, how about some kind of compromise, like including it as a secondary core, /z80_interruptible or similar?

that way, it can be used where there seem to be benefits, with no risk to anything else, and can prove its worth in those situations?

**Comment by rb6502** [comment]
I think it's fine to actually just be the Z80 core.  I'm not really concerned about perf on any Z80 drivers.  Would be nice to get a second opinion from @cuavas or @galibert first though.

**Comment by holub** [comment]
Thank you @DavidHaywood and @rb6502 for support. I also think we can try to find driver where this functionality is critical and try to check it.

**Comment by galibert** [comment]
I'm currently reimplementing the 68000 for. among other things, interruptibility.  Once it fully works I'm going to add all that's needed for wait states & friends (which shouldn't take that long) and test it throughly on the ST and the Lisa.  What about we wait on the z80 until then (eg ~ a month) to see how we can make it fit in what's needed for the wait states?

**Comment by rb6502** [comment]
Pinging @cuavus and @galibert - I think with new68k settling nicely we need to identify a path to getting this in.

**Comment by cuavas** [comment]
I still think the approach of building all the handlers out of capturing lambdas in `std::function`s is too heavy.  It means the whole thing ends up needing indirection through heap-allocated objects, and generates a very large number of vtables and typeinfo for all the `std::function` instantiations.  It’s better to byte the bullet and actually write a code generator if this is the alternative.

We also haven’t heard back from @wilbertpol on his efforts at finishing off his interruptible Z80.  How’s that coming along?

**Comment by wilbertpol** [comment]
My old attempt was roughly twice as slow as the old core; in my opinion it was still too slow and not that easy to read. The main idea was similar to this PR just implemented differently.

These are still all based on observations from running code on a z80. Writing a code generator based on the internal instruction logic would have my preference.

**Comment by DavidHaywood** [comment]
@cuavus and @galibert  can't this just go in as a 2nd core z80_interruptable or something?

I think it has value, and will potentially unblock other work, and in cases where something allows progress in other areas to be made it becomes important beyond the scope of the PR.

Obviously if the longer term goal is to write a Z80 core with a generator, that can happen too, and potentially replace both, but until then why not allow cases that benefit from / need this to have it?

**Comment by holub** [comment]
Wow. If I did everything right this time, it's actually faster 1600% vs 900% full throttle on my machine. I used to measure with DEBUG and SYMBOLS which seams to be not lambda-friendly.

**Comment by simzy39** [comment]
Just in case you need it, here is a great source of z80 technical documentation:
https://github.com/redcode/Z80/wiki/Technical-literature

And tests:
https://github.com/redcode/Z80/wiki/Tests

**Comment by holub** [comment]
> Just in case you need it, here is a great source of z80 technical documentation:
> https://github.com/redcode/Z80/wiki/Technical-literature
> 
> And tests:
> https://github.com/redcode/Z80/wiki/Tests

Thank you! I'm in touch with these folks ;)

**Comment by holub** [comment]
With _TIME_GUARD=0_ performance is close to existing implementation
```
» ./mame-master spectrum -bench 300
Average speed: 2417.58% (299 seconds)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
» ./mame spectrum -bench 300
Average speed: 2649.29% (299 seconds)
```

**Comment by holub** [comment]
Custom tables only left in the system1. Need inspiration or help...

**Comment by simzy39** [comment]
Are you a member of the forums? Can post threads there or chat in the chat box. https://forums.bannister.org/
Great work tho, hopefully @cuavas  can give feedback

**Comment by holub** [comment]
added as a comment - sharing for discussion here:
```
system1 hardware change clock for m1. There are two possibilities to get rid of custom tables here (suprloco requires the same).
1. Keep overclocked z80 and use multipliter + adjust icount respectively in m1 (opcode_read)
	pros: more precise timings
	cons: z80 requires extra multiplier state which no other drivers use
2. Use proper z80 clock and only adjust icount in certain m1 reads
	pros: z80 can drop multiplier support
	cons: for couple commands timings going to be behind actual
```

**Comment by holub** [comment]
I can declare a victory now!

**Comment by holub** [comment]
'Q flag' for ccf/scf fixed:
image

**Comment by holub** [comment]
If there are concerns regarding this PR and we still don't see it happen, I can move tables removal and flags update to master branch.

**Comment by holub** [comment]
all tests in Patrik Rak's (raxoft) z80test - passed 100%
\+ rest interrupted block instructions uncovered by them:
image

**Comment by holub** [comment]
> I'm currently reimplementing the 68000 for. among other things, interruptibility. Once it fully works I'm going to add all that's needed for wait states & friends (which shouldn't take that long) and test it throughly on the ST and the Lisa. What about we wait on the z80 until then (eg ~ a month) to see how we can make it fit in what's needed for the wait states?

@galibert your turn

**Comment by simzy39** [comment]
What`s the performance drop now?

**Comment by holub** [comment]
> What`s the performance drop now?

If I'm did everething right:
```
» ./mame-master spectrum -bench 300
Average speed: 2768.18% (299 seconds)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
» ./mame-int spectrum -bench 300
Average speed: 1878.82% (299 seconds)
```

**Comment by rb6502** [comment]
This cannot be compiled on a Mac with 16 GB of RAM and no other applications open.  That's a serious problem.

**Comment by rb6502** [comment]
John IV reports "pacman -bench 90 from 18110 to 5749".  That's 30% of the former speed, which is also a serious problem.

**Comment by john-iv** [comment]
Further:
Mag_xain 488 to 234, 52% hit
Tnk3 4056 to 1524, 62% hit

**Comment by holub** [comment]
Let's revert it then. I don't have enough technical knowledge to fix these performance issues quickly.

**Comment by holub** [comment]
@rb6502 @john-iv just to be clear... you were talking about compilation with DEBUG=0 ?

**Comment by john-iv** [comment]
Yep.
make -Werror REGENIE=1 -j21 STRIP_SYMBOLS=1 ARCHOPTS=-fuse-ld=lld

**Comment by holub** [comment]
@rb6502 @john-iv 
Could you please try this branch? https://github.com/holub/mame/tree/z80-gen
Mine shows as:
```
~/workspace/mame (z80-gen*) » ./mame-master pacman -bench 180
Average speed: 13531.83% (179 seconds)

~/workspace/mame (z80-gen*) » ./mame pacman -bench 180
Average speed: 10013.71% (179 seconds)
```

**Pull request merged**
