### PR TITLE
SCC iack and reset improvements

### PR DESCRIPTION
**Pull request by JoakimLarsson**
- Added iack by reading rr2
- z80daisy_iack now returns -1 when no vector found or disabled through the WR9 VIS
- Removed z80daisy_reti code to match SCC documentation
- Removed defacto reset values where possible and replaced them with documented SCC reset values

### CODE REVIEW

**Comment by galibert** [comment]
That scc implementation has an issue with the indy (ip225015 in
indy_indigo2.cpp).  Reproducer:
- start ip225015 with no special parameters, you get a black screen (the
eeprom gets initialized in fact)
- press F3, you see a boot screen
- wait for the system to bitch (or press return to abort the failing boot),
it asks you to press a key to continue
- you get a black screen

What happens is that the firmware:
1- initializes the channel A, activating TX
2- resets channel A, disabling TX
3- tries to write a console string to channel A by:
3a- write a byte to send
3b- wait until the TX fifo is empty

In the current code, if you write a byte to send with TX off, the fifo
empty flag is cleared and nothing else happens.  That's where the firmware
freezes.  Not sure what should happen, but the current behaviour is
suboptimal.  Dunno if the reset is actually correct, hard to say (channel B
is also reset all the time but is reprogrammed afterwards when needed...).

Note that the initial black screen on eeprom reset may be due to the exact
same thing.

  OG.

**Comment by JoakimLarsson** [comment]
Fifos are not fully studied and implemented yet, this will follow next. Is the Indy roms same as for Mame 149? Or I might not have it, but I'll do a write up on the fifo's anyway and will look at the Indy driver

**Comment by JoakimLarsson** [comment]
It may also be that FIFO interrupts are not there, I'll check later this week, travelling until friday atm

**Comment by JoakimLarsson** [comment]
I had a quick check and this is definitely something that the tx fifo will fix, I add it in same fashion as in the scnxx562.cpp. There is a dependency on the variant also, the NMOS, CMOS has only 1 Tx slot but the ESCC has 4 tx slots, it is not what is the bug but the tx fifo will fix it

**Pull request merged**
