### PR TITLE
gba.xml : add apotris

### PR DESCRIPTION
**Pull request by DavidHaywood**

### CODE REVIEW

**Comment by cuavas** [comment]
Where did this come from?  Who gets the dump credit?

**Comment by einstein95** [comment]
> Where did this come from? Who gets the dump credit?
ROM matches the file shared by the developer on https://akouzoukos.com/apotris, was available on itch.io until it got DMCA'd by The Tetris Company

**Comment by cuavas** [comment]
GitHub editor screwed me over, sorry.  I’ll apply this manually.

**Comment by cuavas** [comment]
See c63155b86cc31ef47b126b383797de5735f44fbc

**Pull request closed without merging**
