### PR TITLE
ibm5150.xml add loom versions and incorporate existing with parent-clone relationship

### PR DESCRIPTION
**Pull request by Dagarman**
Adds 3 1/2" and 5 1/4" versions, Loom Demo, Loom Upgrade, and Spanish-language version. Moves French- and German-language versions to clones.

[https://www.sendspace.com/file/hp1phi](url)

### CODE REVIEW

**Comment by DavidHaywood** [comment]
If they represent unique versions however it might be an idea to support them, but marked as BAD_DUMP acknowledging that they're not properly sourced.  Sometimes we just have to make do with what exists until something better comes along.

**Comment by DopefishJustin** [comment]
I think there's an argument to be made there in the case of rarities we'll never see again, but for a popular best-seller like Loom, loads of people still have the disks and circulating fake dumps just makes it less likely anyone will ever bother to dump them IMO.

In the case of the IBM PC there are already multiple 'abandonware' projects collecting loose files for DOS games so there is no real danger of the data itself going away, and there are already several thousand real disk images waiting to be added to the softlist which are a higher priority than creating placeholder dumps.

**Comment by DopefishJustin** [comment]
Please do resubmit this once you get your git branch sorted out, the rest of the dumps looked fine so I'd like to get those in at a minimum.

**Comment by Dagarman** [comment]
No thanks. I did it as an exercise to figure out which files belong on the disks and submitted it as the best known dump. But I'll keep away from the PC/AT/XT stuff. You can have them for comparison purposes.
[loom.zip](https://github.com/mamedev/mame/files/1523291/loom.zip)
[ibm5150xml.zip](https://github.com/mamedev/mame/files/1523293/ibm5150xml.zip)

**Pull request closed without merging**
