### PR TITLE
Keep in memory last filter used by the software list menu (latest only).

### PR DESCRIPTION
**Pull request by dankan1890**

### CODE REVIEW

**Comment by cuavas** [comment]
No, you can't add more static members to the UI menus.  I've gone to a lot of effort to remove static members as they take us further from multiple machine support.

**Comment by dankan1890** [comment]
I agree with you, but in what other way can you achieve this without using static members?

**Comment by galibert** [comment]
That's a very good question.  Do we have a "standard" way to store state
that should be preserved across sessions?

  OG.

**Comment by etabeta78** [comment]
.ini files? ;)

    f.

On Sat, Sep 17, 2016 at 11:20 AM, Olivier Galibert <notifications@github.com

**Comment by dankan1890** [comment]
Great tip, thanks ;)

**Comment by etabeta78** [comment]
actually .cfg files are more fitting, since we're not talking about a
command line option... I'm not fully in love with such solution, but I
can't think to any other way.

   f.

**Comment by cuavas** [comment]
If you really need per-session variables, you can use a trick like the base menu or menu_select_launch uses.  Look here: https://github.com/mamedev/mame/blob/master/src/frontend/mame/ui/selmenu.cpp#L167
It creates an instance of cache for the running machine instance and cleans it up on exit.  It still needs static members, but the member is a map protected by a mutex that stores the data per running_machine.

**Pull request closed without merging**
