### PR TITLE
Renamed various Apple Macintosh software lists' description

### PR DESCRIPTION
**Pull request by ArcadeShadow**
Added the manufacturer's name.
Lowercase on the storage medias' name.
Renamed "Mac" abbreviation to "Macintosh".

### CODE REVIEW

**Comment by rb6502** [comment]
You drove away Firehawke, and  now you've come for me.  I guess it's time to reconsider my continuing involvement with the MAME project again.

**Comment by happppp** [comment]
"You drove away Firehawke, and now you've come for me. I guess it's time to
reconsider my continuing involvement with the MAME project again."

...Triple dot, that's so stupid, I'm glad you removed it and I guess you
had a bad day or something.

Was it the "Apple" prefix you don't agree with? IMO the other consistency
change is fine.
Now there's mixed "Macintosh" and "Mac". Imagine half of the ZX Spectrum
swlists were "Speccy xxx", changing them to be consistent with eachother is
good.

The capitalization is a minor thing but I see an inconsistency there as
well. Looks like your preference is to have the 1st word capitalized?
Though there is "Macintosh 400K/800K cleanly cracked disks" instead
of "Macintosh 400K/800K Cleanly cracked disks"

**Comment by ArcadeShadow** [comment]
What was wrong with this commit?

**Comment by rb6502** [comment]
We're gonna be here all day if I start on that, so I'll just note that the revert wasn't actually merged and you can let it go.

**Comment by ArcadeShadow** [comment]
I was just asking... nothing more than that.
I'm just trying to help...

**Pull request merged**
