### PR TITLE
bus/coco: rearrange files into subdirectory

### PR DESCRIPTION
**Pull request by tlindner**
bus/coco: rename file to remove platform prefix. Move to coco or dragon subdirectory.

### CODE REVIEW

**Review by cuavas — CHANGES_REQUESTED** [review]
Don’t use parent directory references in `#include` paths, it only causes issues.  If you need to refer to stuff at a higher level in the directory tree, use a path relative to one of the include search paths (e.g. `#include "bus/coco/cococart.h"`).

Also, be careful with header names that shadow the names of header files elsewhere – it can cause issues trying to get the other header if you’re not careful.

@npwoods do you have an opinion on this in terms of how the source should be laid out>

**Comment by npwoods** [comment]
I'm sort of on the fence here.

CoCo and Dragon are two extremely similar systems and their expansion ports behave virtually identically.  And in fact it _might_ be possible to plug the same devices into both (I'm not 100% sure about this), even if they might not have been function.  That said, in practice you had CoCo cartridges and you have Dragon cartridges.

It isn't clear to me what the correct solution here is.  I like the idea of getting rid of the ugly prefixes and putting CoCo peripherals into one directory and Dragon peripherals into another, but at the same time I don't really like having a `coco/coco` directory (even if that is better than `coco_and_dragon/coco`

**Comment by tlindner** [comment]
Another option would be to lump all these files into an EXT directory. This would mimic the command line -ext option to enable these slot devices. @Pernod70 ask me to do this. I'm am going to be adding another coco slot device soon so it made sense to start with a cleanup.
The Disto cartridges had an addition Mini Expansion Bus that I am almost finished implementing. They would go into a MEB directory.

**Comment by Pernod70** [comment]
I did suggest this cleanup but I agree having a coco/coco is not nice. @npwoods would it be more agreeable to rename the folders to cococart/dragoncart? I'd like to keep the separation of which cartridges were developed specifically for each machine and this is much clearer than the previous prefixes.

**Comment by tlindner** [comment]
Cloud the best solution to be to keep the filename prefixes? It sure solves @cuavas 's warning about headers with same names.

**Pull request closed without merging**
