### PR TITLE
new NOT WORKING ---- Storio [Team Europe]

### PR DESCRIPTION
**Pull request by DavidHaywood**
new NOT WORKING
----
Storio [Team Europe]

created this so that Clawgrip can add to it

### CODE REVIEW

**Comment by DavidHaywood** [comment]
@clawgrip   once this is merged you should be able to add new things to the softlist, and any BIOS roms to the driver etc.  (+ populate it with any known information)

**Comment by Osso13** [comment]
you forgot to add the new driver to mess.flt

**Comment by DavidHaywood** [comment]
what even *is* mess.flt, and why does it exist?  I've never had any need for it

**Comment by Osso13** [comment]
If it were for me it would already have been killed with his companion arcade.lst or however is called, but until it exists it's IMHO rude to knowingly have someone else update it for you.

**Comment by clawgrip** [comment]
Thx!

The BIOS files I got came directly from VTech, so they're trimmed to their real size (without padding to the ROM size, which is 64Mbytes), should I mark them as BAD_DUMP? I don't think so, but I would like to have more opinions.

**Comment by DavidHaywood** [comment]
Nah, I wouldn't mark them as bad, just mention that they're official support files, and therefore not padded.

**Comment by DavidHaywood** [comment]
since that's an orphan softlist, with nothing referencing it, and therefore isn't being validated at all, I'd suggest just deleting it an moving the information if that's the case.

**Comment by clawgrip** [comment]
I'll do it once merged.

**Comment by DavidHaywood** [comment]
Is this actually a different system to the "Reader Laptop E (Germany)" in vtech_eu3a12.cpp for which we were unable to identify the CPU?  I'd assume so since the NAND dumps look quite different to that?

**Comment by clawgrip** [comment]
The Storio uses a "Nuvoton W55FA9363SDN", an ARM designed to accelerate Macromedia/Adobe Flash Lite programs, I'd say it's different from an "Elan EU3A12".
From the Nuvoton technical manual:
"The W55FA93 is built on the ARM926EJ-S CPU core and integrated with JPEG codec, CMOS sensor interface, 32-channel SPU (Sound Processing Unit), ADC, DAC, & TV encoder, for meeting various kinds of application needs while saving the BOM cost. The combination of ARM926 @ 240MHz, DDR, BitBLT accelerator, & USB2.0 HS Device makes the W55FA93 the best choice for FlashLite-based ELA devices."

**Comment by DavidHaywood** [comment]
would be good to know if the 'vreader' and 'storio' are compatible, and what the original vreader.xml was for (as it listed both names in the description)

if they're completely different, incompatible systems, then obviously this PR needs changing, if not, this PR should be mergeable.  If there's no solid info, I'm inclined to say merge it anyway.

**Pull request merged**
