### PR TITLE
 Correct device description

### PR DESCRIPTION
**Pull request by MASHinfo**
Changed Data East --> DECO like all other Data East devices in MAME:
DECO 104 Protection
DECO 146 Protection
DECO 52 Sprite
DECO 55 / 56 / 74 / 141 Tilemap Generator
DECO BAC06 Tilemap
DECO Cassette Tape
DECO Common Video Functions
DECO Karnov Sprites
DECO MXC06 Sprite
DECO RM-C3 PALETTE
DECO Zooming Sprites

### CODE REVIEW

**Comment by rb6502** [comment]
I'm not convinced "Data East" isn't the more correct name here.  We typically don't abbreviate company names.

**Comment by MASHinfo** [comment]
Correct! On all boards the chips are named "DATA EAST". I should do a new Pull-Request
and changed all devices from DECO to DATA EAST?

**Comment by ajrhacker** [comment]
It seems that Data East only started putting the full company name (and logo) on their ASICs around 1986, since many of their earlier ASICs indeed carry "DECO" labels. The ones MAME emulates as devices are mostly of the "Data East" kind, though.

**Comment by cuavas** [comment]
MAME policy is to follow branding used at the time, not force artificial consistency.  This is definitely wrong.

**Pull request closed without merging**
