### PR TITLE
New WORKING clone

### PR DESCRIPTION
**Pull request by clawgrip**
---------------------------
Kung-Fu Senjyo (bootleg, Spanish) [Asociación Retroclub]

Also reformatted single-line comments.

### CODE REVIEW

**Comment by cuavas** [comment]
What does the title screen of this game actually show?  “Senjyo” is not conventional Hepburn Romaji.

**Comment by cuavas** [comment]
Oh, it’s actually written in Latin script – that’s not a transliteration of a title written in Japanese.

**Comment by cuavas** [comment]
Also, that title screen is very linguistically confused, featuring transliterated Chinese, transliterated Japanese, and Spanish.

**Comment by clawgrip** [comment]
There was a Spanish arcade cabs manufacturer, Barni SA, that had a model called "Senjyo": https://www.recreativas.org/senjyo-254-barni-sa
Maybe Barni was the bootlegger and just reused this name...

**Comment by cuavas** [comment]
In this case they probably mean “戦場” – “battlefield”.  The Hepburn Romaji would be “Senjō”, or “Senjou” if you need to make oo/ou unambiguous.

The cabinet model could also be alluding to the same Japanese word, but it could equally well be 仙女 (elf), or something else.

**Comment by ajrhacker** [comment]
Blame Tehkan/Tecmo for romanizing it that way (senjyo).

**Pull request merged**
