### PR TITLE
Remove reference to incorrect Yamaha TX81Z ROM image

### PR DESCRIPTION
**Pull request by ajxs**
The Yamaha TX81Z driver references a `tx81z-last-revision.ic15` ROM binary. This is an error.
The TX81Z's most recent firmware version is v1.6 from 1989. The binaries for the various firmware ROMs can be obtained here: _\<link removed\>_, as well as Yamaha's official documentation of changes: https://mgregory22.me/tx81z/files/TX81Z_Service_News.pdf

A version of the erroneous `tx81z-last-revision.ic15` ROM file (with the correct hash) can be found here: _\<link removed\>_. Doing a diff between this file and the v1.6 ROM shows the only thing that has changed is the version string. There are no functional changes.
I'm not sure where this file came from. It's not an official ROM, and does not appear to be of any practical use. I've removed the reference from the driver file.

### CODE REVIEW

**Comment by galibert** [comment]
Shouldn't they be renumbered though?

  OG.

**Comment by ajxs** [comment]
> Shouldn't they be renumbered though?

In what way? The ROM filenames appear to be totally arbitrary, and correspond to the file names as found here: https://dbwbp.com/index.php/9-misc/37-synth-eprom-dumps

**Comment by happppp** [comment]
Please remove those links to copyrighted roms, either indirect ones as in your prev comment, or a direct link as in the 1st message.
About BIOS numbering: before, it was 0-7, now it's 1-7, they can be renumbered to 0-6.

**Comment by ajxs** [comment]
Ah, pardon me. This is my first contribution to the project. I didn't know the etiquette regarding ROM links.
I've fixed the numbering of the ROMs. Thank you for pointing that out!

**Comment by happppp** [comment]
The same numbering is with those ROM_BIOS(x)

**Comment by simzy39** [comment]
In case you don't know, you'll need to send any new data/roms to Mame: https://wiki.mamedev.org/index.php/Submitting_Source_Code

**Comment by ajxs** [comment]
> In case you don't know, you'll need to send any new data/roms to Mame: https://wiki.mamedev.org/index.php/Submitting_Source_Code

In this case, there aren't any new ROMs. This PR just removes an erroneous ROM from the driver.

> The same numbering is with those ROM_BIOS(x)
I've resolved this in the latest commit. My apologies for missing this!

**Pull request merged**
