### PR TITLE
pce_tourvision.xml: New NOT_WORKING software list additions

### PR DESCRIPTION
**Pull request by clawgrip**
----------------------------
Blodia (Tourvision PCE bootleg) [system11, Recreativas.org, ClawGrip]
Ganbare! Golf Boys (Tourvision PCE bootleg) [system11, Recreativas.org, ClawGrip]
Hanii on the Road (Tourvision PCE bootleg) [system11, Ricky2001, Recreativas.org, ClawGrip]
Time Cruise II (Tourvision PCE bootleg) [system11, Ricky2001, Recreativas.org, ClawGrip]

### CODE REVIEW

**Comment by clawgrip** [comment]
Sorry, it's NOT_WORKING software list additions (I cannot change the PR title)

**Comment by Osso13** [comment]
Thanks! I believe that usually the sets added to this software list are given the same romset name as the PCE counterpart, so I'd prefer if you did that. Don't know if other devs have different opinions, though.
i.e. there is timcrus2 in pce.xml and timecruise2 here.

**Comment by Tafoid** [comment]
New adds should also be checked against PCE.XML to see if the data portion of the 1MB dumps are the same as established romsets for the console.  Then, you can add a comment above the rom name, as in the example of Adventure Island:
"0x40000 matches PCE advislnd"

**Comment by DavidHaywood** [comment]
They should ideally be trimmed to the correct sizes too since there isn't physically 1MB of data in the carts.  That however caused too much controversy when I last mentioned it.

However, come the time I do actually work on Tourvision again I will probably be trimming them all to the proper sizes.

**Comment by Tafoid** [comment]
At least having it documented to when the time comes that trimming happens, it'll be easier with the research already done and noted.

**Comment by clawgrip** [comment]
So... should I split the dumps? I thought that on the TourVision the decission was to leave the 1MB dumpd (although most added games are trimmed).

As reference, Last time we discussed the TourVisión size issue, Charles MacDonald said:

“It's a documentation issue. The correct action would be to trim the
1MB dumps into their most likely constituent parts (which is an
educated guess until we disassemble or X-ray each cartridge to be
certain), and document the ROM layout in terms of mirrored areas and
unused areas for each cartridge in the source. Who will do that work?
It hasn't happened yet.

The point of the 1MB format was to allow such documentation work to
potentially happen in the future, and we still have that possibility
with the untrimmed dumps.

If we just trim them and document nothing, using only the raw ROM size
as hint as to their layout ("split" or not), then we are losing
information and we're back to where we were decades ago with
copier-generated PC-Engine dumps that could only infer exactly that
much information as well. I specifically made an effort to avoid that.

If you think the size of the dump is misleading, add a
comment in the driver explaining why they're like that. The dump size
is to retain information (which we can indicate in the source after
trimming), not to indicate capacity.

Regards,

Charles”

**Comment by DavidHaywood** [comment]
As I said it was too controversial, and is why I've abandoned the Tourvision driver myself.

The current situation is the *least* accurate solution, as it's data we know is overdumped, it's literally just 'copier data' with no attempt to do what is most likely in the carts.

**Comment by clawgrip** [comment]
I agree. Knowing that there's a PCE HuCard inside the expoxy block, there's no reason to think that having overdumped content is more accurate that having the exact HuCard size.
I'll try to review also all the other games (it may take time, I'm really overwhelmed with "real life").

**Comment by Osso13** [comment]
Speaking on inaccurate things in this software list, it contains one of my least favourite things in MAME: a completely made up 'dump' of Parasol Stars. It it were up to me, this should be removed.

**Comment by clawgrip** [comment]
Also, we have a few carts without ID.
IIRC, those were loaned by AUMAP, but when I dumped them I did not check the IDs because we did not know about this feature yet.
I’ll try to reach them, maybe they still have the carts.

**Comment by DavidHaywood** [comment]
and if I'm being nitpicky the cart IDs should be hexadecimal as they represent 8 lines and it's far easier to read them that way.

**Comment by clawgrip** [comment]
Agree... I’ll try to clean up the whole softlist.
I also agree that Parasol should be removed.

**Comment by DavidHaywood** [comment]
fwiw discussed via email how the '384kb' cases do usually match, because in those cases there are likely 2 ROMs in the carts, a 256kb and 128kb one, with a high rom mapping, so it's not just a case of splitting the file into even parts.

**Comment by clawgrip** [comment]
Yes, I'll fix those tomorrow!

**Comment by clawgrip** [comment]
IMHO, the PR is ready to be merged.

**Comment by DavidHaywood** [comment]
yes, I think this brings things to a better state

**Pull request merged**
