### PR TITLE
seta2.cpp: Fix clocks, Add notes

### PR DESCRIPTION
**Pull request by cam900**
Replace to HQ reference video

### CODE REVIEW

**Comment by DavidHaywood** [comment]
are you planning any further work on this?

I can step back from my own work on it if you want to do further tweaks / improvements.

**Comment by happppp** [comment]
@DavidHaywood if your zoom changes are still WIP, seta2 PRs can wait.

**Comment by DavidHaywood** [comment]
Well I don't mind handing it off, there are other things I can work on, that's why I'm asking.

**Comment by cam900** [comment]
This PR is just for fix single pixel issue in current zooming behavior, and hardware notes for gundamex and grdians.

**Comment by DavidHaywood** [comment]
I don't mind this being merged by the way, as long as it doesn't cause any other issues such as out of bounds accesses.

I was mainly asking if any other work was going to be done because if there is it will start to conflict (there's a fair chance this code will change entirely in the future)

I also don't mind if cam or somebody else wants to take this on and fix up the things that I didn't manage to cover so far (reverse zooming cases acting as flipscreen etc.) as I'm equally happy to have just got the ball rolling with this again, while acknowledging there are still flaws in the updated code.

**Comment by cam900** [comment]
I've reverted this rendering emulation change for other PRs and commits.
I will yield this part to others.

**Comment by happppp** [comment]
Haze was saying that change is OK, as long as it does not break anything.

**Comment by cam900** [comment]
I close this PR now and I will open separate docs and rendering change (when that hasn't any conflicts) PRs.

**Pull request closed without merging**
