### PR TITLE
dbox: improved address map, more bootroms and minimal support for AM29F800 flash 

### PR DESCRIPTION
**Pull request by JoakimLarsson**

### CODE REVIEW

**Comment by ajrhacker** [comment]
There's already an AM29F800T device in `machine/intelfsh.cpp`. Why don't you try adapting that?

**Comment by JoakimLarsson** [comment]
As far as I can see the intelfsh.cpp 29F800T is marked as a 8-bit device and the 29F800B I know is a 16 bit device. If I correct that what happens with all the old save files? I can of course just add the 29F800B as a 16 bit device and not touch the old one, it just itch a bit to leave it wrong.

**Comment by startaq** [comment]
The both support 8 and 16-bit mode. The difference between B and T is 
shown on page 3 here:

https://www.digchip.com/datasheets/download_datasheet.php?id=698460&part-number=MX29F800T%2FB

------ Original Message ------

**Comment by JoakimLarsson** [comment]
Absolutelly, what I is referring to is the setting of m_bits = 8; on line 201, but maybe that is possible to override. Mine is used in 16bit mode anyway.

**Comment by cuavas** [comment]
Right now, I think you have to make an additional device for 16-bit mode.  I don't think the code supports switching modes with one device.  See e.g. the Sharp LH28F016S:
```
DECLARE_DEVICE_TYPE(SHARP_LH28F016S,       sharp_lh28f016s_device)
DECLARE_DEVICE_TYPE(SHARP_LH28F016S_16BIT, sharp_lh28f016s_16bit_device)
```

It's pretty easy to add additional devices though, so it isn't a huge priority to change.

**Comment by JoakimLarsson** [comment]
ok good, no problem then, I'll just add the additional modes as required

**Comment by ajrhacker** [comment]
Having `m68340_serial` and `m68340_serial_device` as separate classes looks rather suspect to me. The former class's read and write handlers shadow the latter's custom handlers and call those of `mc68681_base_device` instead, which will likely cause incorrect behavior. Please consolidate the two classes.

**Comment by JoakimLarsson** [comment]
I have a few things more I want to add but I need to re base the whole thing to resolve the conflicts and come up with a new PR shortly, so closing this now

**Comment by JoakimLarsson** [comment]
@ajrhacker , I didn't intended to call the base class but the derived class I made for the 68340 sim module so it's a bug I will fix. The reason I have it like that is that there are a number of registers that are specific to the CPU32 module rather than the duart so I don't want to include them in the derived duart class. There is also a need to access the 68340 SIM module to know if I need to auto vector or not that would look silly from the duart class I think. Maybe the naming could be better but I think I have reasons to keep handling of the registers separate. I tried to use a reference first but that looked really wierd. There may be a better way of course, let me know

**Comment by cuavas** [comment]
Could you break out the addition of the Flash chip?  That could probably be done on its own without tying it up with the rest of the changes.

**Comment by JoakimLarsson** [comment]
ok, I will make that a separate PR, I have verified it works the same way as my local hack which I will keep disabled for debugging and later remove

**Pull request closed without merging**
