### PR TITLE
model2.cpp: Fix ROM locations for Dead or Alive on Model 2B [Tailsnic Retroworks]

### PR DESCRIPTION
**Pull request by clawgrip**
8c13f0b4-3f9f-4b75-ac67-051a3dc85bd5

Verified on real hardware, ROM locations are not the same for Dead or Alive on Model 2B and Model 2A

### CODE REVIEW

**Comment by cuavas** [comment]
Is “not the same for Dead or Alive on Model 2B and Model 2B” a mistake, or am I missing something?

**Comment by clawgrip** [comment]
Model 2B uses different sound ROMs sockets than Model 2A.

**Comment by cuavas** [comment]
> Model 2B uses different sound ROMs sockets than Model 2A.

Read what you wrote in the PR description, particularly the part I quoted, again.  As written, it doesn’t make sense.

**Comment by clawgrip** [comment]
Typo fixed

**Pull request merged**
