### PR TITLE
New working clones

### PR DESCRIPTION
**Pull request by sergiopolog**
------------------
Magical Cat Adventure (Recreativos Zara,S.L.) [Nebula, Recreativos Piscis]

Found it in an original Wintechno PCB with custom eprom labels. This is a picture of the actual pcb: https://twitter.com/Recre_Piscis/status/1434467129525510146
It is actually a hack made over "mcatadv" by a spanish local operator to put his name in attract mode and title screen (added notes for it in code inline-comments).
Only 68k program roms are altered a bit to make that.
No further changes in the gameplay.

### CODE REVIEW

**Comment by sergiopolog** [comment]
Please, let me know if the naming of the romset and game title are the proper ones

**Comment by DavidHaywood** [comment]
I'd change the manufacturer field to "hack (Recreativos Zara,S.L.)" instead of "Wintechno"

**Comment by sergiopolog** [comment]
> I'd change the manufacturer field to "hack (Recreativos Zara,S.L.)" instead of "Wintechno"

Ok, will change it.  What about game title? Should it be: "Magical Cat Adventure (Recreativos Zara,S.L.)" too?

**Comment by clawgrip** [comment]
I'd use "Recreativos Zara, S.L." with a space before the "S". I know that the space it's not present on the title, but it is on the real company name and it's easier to read like that. @cuavas What's your opinion?

**Comment by cuavas** [comment]
I’m not sure it belongs in MAME at all.  “Vanity hacks” by arcade operators to put their name on the screen were prolific in South America in particular (just ask @RobertoFresca about that).  If we start supporting them, we’ll have thousands to add.  If it’s just a vanity hack and not an bootleg production run, I wouldn’t add it at all.  It might be a better fit for HBMAME.

**Comment by RobertoFresca** [comment]
Well... I think that the text hacks should be analyzed per basis. In this case, the company is just a local arcade instead of a manufacturer.
So, I agree with @cuavas here. We can't support thousand of dirty sets where operators changed texts just for vanity or fun. It has no point at all.

I still recall one set where "Game Over" was replaced by "Chau Puta" (bye bitch).

**Comment by Robbbert** [comment]
This set has been added to HBMAME 0.236 as "mcatadvs01".

**Pull request closed without merging**
