### PR TITLE
news_r3k.cpp: Flag NWS-3410 graphics as unimplemented

### PR DESCRIPTION
**Pull request by briceonk**

### CODE REVIEW

**Comment by cuavas** [comment]
Since the frame buffer isn’t emulated at all, you should flag it as unemulated graphics.  You need to implement `static constexpr feature_type unemulated_features()` in the driver state class.

**Comment by briceonk** [comment]
> Since the frame buffer isn’t emulated at all, you should flag it as unemulated graphics. You need to implement `static constexpr feature_type unemulated_features()` in the driver state class.

Ah, OK, thanks. I didn't see a macro for it.

**Comment by cuavas** [comment]
> Ah, OK, thanks. I didn't see a macro for it.

Yeah, there isn’t a macro for it.  Not all imperfect/unemulated features can be declared in the system definition macro.

**Comment by briceonk** [comment]
> > Ah, OK, thanks. I didn't see a macro for it.
> 
> Yeah, there isn’t a macro for it. Not all imperfect/unemulated features can be declared in the system definition macro.

Fixed. Sorry for the extra delay!

**Pull request merged**
