### PR TITLE
karatour and karatourj

### PR DESCRIPTION
**Pull request by Dunard**
Broken graphics. Demote to MACHINE_IMPERFECT_GRAPHICS

### CODE REVIEW

**Comment by Dunard** [comment]
I don't know how to do this the right way. So I just upload the file with those changes.

**Comment by angelosa** [comment]
It's not, regressions doesn't qualify as being worth being demoted with machine flag.

**Comment by happppp** [comment]
Since it looks like @ajrhacker hasn't fixed his 10month old regression and noone else did, sure they do.
@Dunard something went horribly wrong and github thinks you changed the whole file.
"I don't know how to do this the right way" -> Best do some reading online on how to make a Pull Request.

**Comment by Dunard** [comment]
That ok. I'm not gonna worry about it then. I still mark it as imperfect in my notes because the graphics so screw up. lol

Pull have two ways. Upload and sent in the changes as coding. There is two options. The reason why I didn't try to do the coding way because I didn't want to screw up the source.

**Comment by DavidHaywood** [comment]
@ajrhacker any idea what happened here? this is one of those games that is surprisingly popular, and the breakage seems to be being reported a couple of times each month.

**Comment by angelosa** [comment]
It's the code at 0x2b2 (vblank subroutine):
```as
0002B2: 0279 0020 0087 88A2      andi.w  #$20, $8788a2.l      // is it also an irq cause 5?
0002BA: 6700 0046                beq     $302
0002BE: 33F9 00FF C042 0087 8872 move.w  $ffc042.l, $878872.l // update scroll values
0002C8: 33F9 00FF C046 0087 8876 move.w  $ffc046.l, $878876.l
0002D2: 33F9 00FF C04A 0087 887A move.w  $ffc04a.l, $87887a.l
0002DC: 33F9 00FF C040 0087 8870 move.w  $ffc040.l, $878870.l
0002E6: 33F9 00FF C044 0087 8874 move.w  $ffc044.l, $878874.l
0002F0: 33F9 00FF C048 0087 8878 move.w  $ffc048.l, $878878.l
0002FA: 33FC 0002 00FF C032      move.w  #$2, $ffc032.l
000302: 4E75                     rts
```
For some reason it expects bit 0 AND 5 enabled on vblank otherwise scrolling values never updates.

**Comment by ajrhacker** [comment]
The VDP clearly includes some sort of interrupt controller. Probably all the interrupt causes are internally programmed, but the emulation remains very confused as to what they should be and provides them on a per-game basis. @angelosa has suggested that one of these may be an "arbitrary one-shot timer," which seems fairly plausible to me.

More work is very much needed here; puzzlet is considerably more broken in MAME because one of the IRQs it wants is and has always been missing. The karatour regression is acknowledged, but the old emulation wasn't anywhere near accurate either.

**Pull request closed without merging**
