### PR TITLE
Namco C352 improvements

### PR DESCRIPTION
**Pull request by superctr**
- Replaced C352 core with new one used in [VGMPlay](https://github.com/vgmrips/vgmplay). This fixes noise generation (ie ncv1 Xevious explosion sounds) as well as sample interpolation.
- Change clock frequencies for sub CPU and sound chip for System 12/23 drivers. The new values are based on my research on the sound drivers, including a comparison between the ND-1 and System 12 sound drivers. This affects music timing as well as pitch.
- Removed rear channels for systems that lack a second Sanyo LC78815M stereo DAC.

### CODE REVIEW

**Comment by galibert** [comment]
Are you the copyright owner for the new core (aka did you write it)?

  OG.

**Comment by kazblox** [comment]
Superctr is the holder of the code, yes.

**Comment by Lord-Nightmare** [comment]
The clock speed changes, have these been verified with a frequency counter on the actual board? I'm guessing the original clock speed numbers in the driver were measurements from who knows how long ago, but I could be wrong...

**Comment by galibert** [comment]
They were calculated based on the standard 120Hz interrupt rate all namco
games use and computing the base frequency from the timer programming.  And
the change is within the precision range of the measurements.  So I think
they're good.

To do better, we'll have to find where the frequency generator (2061asc) is
programmed.

  OG.

**Pull request merged**
