### PR TITLE
fixing/improving metadata on CoCo FDCs: CP-450 and CD-6809

### PR DESCRIPTION
**Pull request by felipesanches**
Thanks to Daniel Campos & Datassette.org for the CP-450 disk rom. MAME was calling it CP400_FDC, but the correct name of the disk controller unit is "Prológica CP-450". The ROM was correct (verified checksum), but I renamed it to fix the previous naming mistake. Unfortunately this FDC unit is rare, so I still don't know whats the IC reference for the EPROM on the PCB.

There is a photo of the CP-450 disk controller unit at:
https://datassette.org/softwares/tandy-trs-color/cp-450-basic-disco-v-10
http://files.datassette.org/softwares/img/wp_20141212_22_08_26_pro.jpg

### CODE REVIEW

**Comment by felipesanches** [comment]
Also thanks to Luciano Scharf for pointing out to me that there was a ROM dump of the CP-450 available on Datassette.org :-D

**Comment by cuavas** [comment]
Is this a replacement ROM for another FDC?  If it is, it should use the BIOS feature.  MAME supports BIOS selection for slot devices from the command like with syntax like:
```
mame system -slot device,bios=version
```

**Comment by felipesanches** [comment]
THis is a ROM and device rename. There's  no FDC called CP400. CP400 is the name of the computer. The FDC correct name is CP450.

There's a single ROM available for it, so no need to use the BIOS macros.

**Comment by felipesanches** [comment]
And the ROM contents is the same that was already cataloged on MAME. Same checksum. This is just a device and ROM name fix.

**Pull request merged**
