### PR TITLE
[CoCo] Overhaul to the cartridge slot subsystem and Speech/Sound Cartridge support

### PR DESCRIPTION
**Pull request by npwoods**
This was a general cleanup to the CoCo cartridge slot infrastructure, and related devices.
- Changed read() and write() to scs_read() and scs_write() and restricted to $FF40-5F, to restrict those methods to usage pertaining to reads/writes when the SCS pin is active
  - Added a distinct ability to install read/write handlers in the CoCo address space
  - This should fix cartridges that do this (Multi-Pak interface, Orch-90, RS232) on non-CoCo 3 systems
- Refactored each of the CoCo cartridge devices to keep their device classes in anonymous namespaces in their source files, eliminating the need for several header files, and performed cleanups.
- Also, updated each to use device_add_mconfig() instead of device_mconfig_additions()
   
Separately, the following device specific changes were made (by me when not otherwise specified):
- Added the CoCo S/SC (Speech & Sound) cartridge [Tim Lindner]
- Added the ROM to the CoCo Orch-90 device
- Corrected the address space for the RS-232 pak (supposed to be $FF68-B, was $FF68-F)
- Fixed a motor issue on the CoCo FDC [Tim Lindner]

### CODE REVIEW

**Comment by tlindner** [comment]
I'm not 100% sure, but I think I hear the disk spinning sound non-stop with these changes.
DECB generally stopped the disk spinning by writing 0 to $FF40 after 2 second of inactivity.

(Color Computer Disk System Manual, p. 61)

**Comment by tlindner** [comment]
I couldn't figure out how to load the Orch90 ROM and have the Orch90 hardware enabled.

**Comment by Pernod70** [comment]
The softlist entry for orch90 should probably have `<feature name="slot" value="orch90" />` added.

**Comment by tlindner** [comment]
I found a little problem with the Sound Activity Circuit in the S/SC. Here is a patch.
[sac patch.txt](https://github.com/mamedev/mame/files/1016448/sac.patch.txt)

I had to increase the buffer depth. The real circuit isn't as touchy.

**Comment by tlindner** [comment]
Here is a small patch to fix the turning on and off the spinning floppy disk properly.
[floppy spin patch.txt](https://github.com/mamedev/mame/files/1016560/floppy.spin.patch.txt)

**Comment by npwoods** [comment]
Holding off on this for a bit...

**Comment by npwoods** [comment]
Reopening; a number of improvements were made and Tim straightened out the SSC support.  It would be great to see this merged at the beginning of the next dev cycle.

**Pull request merged**
